#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C  @   aw    a     S  s   s Cw S>        s          a    a           a Sw      s    S             S    C  s      a   as s s S CC   C w     w  w as  S     s  S s wsC Ss                 S            S             w    a       S  w    w   sS             a  s s        w w  s SC s     s     SS sC   s    S      w  s    a  w wS   s  a    Cw  s  s   s s     a          s                w S   s    SC    SC  aa   S  a     a            C     a      a     C S       CaSC s S     ss S      C  C      a    a s   aSa       s w  w      w  w        a   s       C w  w   Cs  Sw a  w S  sw   S   a   S    w  C s   a          Sa a       a  w a C   Cs  s   SC   a    C     S    s      S  a      aSsC  w      aC    s      Sw S Ss C   C a     a       C      w Ss       S       w SsSa  S      wSw     CC   w     w    aa       Cs  aC     S  a    a S       s        a s a    Sa     w s     SC  C      a aC S C       s      w   s     C      a    w      a  C   s  sC      C|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 950
ace_score 4750
size 950, 1
stairs 34, 0

warrior 5, 0, :east

unit :captive, 2, 0, :east
unit :archer, 9, 0, :west
unit :wizard, 10, 0, :west
unit :archer, 15, 0, :west
unit :thick_sludge, 21, 0, :west
unit :sludge, 24, 0, :west
unit :sludge, 28, 0, :west
unit :captive, 30, 0, :west
unit :wizard, 31, 0, :west
unit :thick_sludge, 33, 0, :west
unit :sludge, 43, 0, :west
unit :archer, 54, 0, :west
unit :archer, 59, 0, :west
unit :archer, 71, 0, :west
unit :thick_sludge, 73, 0, :west
unit :wizard, 74, 0, :west
unit :sludge, 81, 0, :west
unit :thick_sludge, 86, 0, :west
unit :thick_sludge, 100, 0, :west
unit :captive, 105, 0, :west
unit :sludge, 108, 0, :west
unit :archer, 115, 0, :west
unit :archer, 119, 0, :west
unit :sludge, 120, 0, :west
unit :sludge, 122, 0, :west
unit :sludge, 124, 0, :west
unit :thick_sludge, 126, 0, :west
unit :captive, 128, 0, :west
unit :captive, 129, 0, :west
unit :captive, 133, 0, :west
unit :wizard, 135, 0, :west
unit :wizard, 141, 0, :west
unit :wizard, 144, 0, :west
unit :archer, 146, 0, :west
unit :sludge, 147, 0, :west
unit :thick_sludge, 150, 0, :west
unit :sludge, 156, 0, :west
unit :thick_sludge, 159, 0, :west
unit :sludge, 161, 0, :west
unit :wizard, 163, 0, :west
unit :sludge, 164, 0, :west
unit :captive, 165, 0, :west
unit :thick_sludge, 167, 0, :west
unit :sludge, 168, 0, :west
unit :thick_sludge, 186, 0, :west
unit :thick_sludge, 199, 0, :west
unit :wizard, 213, 0, :west
unit :archer, 218, 0, :west
unit :thick_sludge, 226, 0, :west
unit :wizard, 229, 0, :west
unit :wizard, 234, 0, :west
unit :sludge, 238, 0, :west
unit :thick_sludge, 239, 0, :west
unit :archer, 253, 0, :west
unit :sludge, 256, 0, :west
unit :sludge, 258, 0, :west
unit :wizard, 267, 0, :west
unit :wizard, 269, 0, :west
unit :sludge, 272, 0, :west
unit :thick_sludge, 274, 0, :west
unit :captive, 275, 0, :west
unit :sludge, 277, 0, :west
unit :sludge, 283, 0, :west
unit :thick_sludge, 289, 0, :west
unit :thick_sludge, 290, 0, :west
unit :sludge, 292, 0, :west
unit :captive, 293, 0, :west
unit :sludge, 297, 0, :west
unit :thick_sludge, 302, 0, :west
unit :wizard, 309, 0, :west
unit :sludge, 312, 0, :west
unit :archer, 317, 0, :west
unit :wizard, 320, 0, :west
unit :wizard, 322, 0, :west
unit :thick_sludge, 323, 0, :west
unit :sludge, 327, 0, :west
unit :archer, 330, 0, :west
unit :captive, 335, 0, :west
unit :wizard, 336, 0, :west
unit :sludge, 339, 0, :west
unit :sludge, 342, 0, :west
unit :sludge, 346, 0, :west
unit :sludge, 348, 0, :west
unit :archer, 354, 0, :west
unit :sludge, 365, 0, :west
unit :wizard, 382, 0, :west
unit :thick_sludge, 384, 0, :west
unit :sludge, 388, 0, :west
unit :thick_sludge, 393, 0, :west
unit :captive, 394, 0, :west
unit :thick_sludge, 399, 0, :west
unit :captive, 400, 0, :west
unit :archer, 403, 0, :west
unit :archer, 404, 0, :west
unit :thick_sludge, 408, 0, :west
unit :archer, 411, 0, :west
unit :archer, 417, 0, :west
unit :captive, 430, 0, :west
unit :archer, 436, 0, :west
unit :archer, 443, 0, :west
unit :captive, 449, 0, :west
unit :thick_sludge, 451, 0, :west
unit :captive, 459, 0, :west
unit :archer, 460, 0, :west
unit :thick_sludge, 461, 0, :west
unit :captive, 462, 0, :west
unit :sludge, 464, 0, :west
unit :thick_sludge, 466, 0, :west
unit :sludge, 472, 0, :west
unit :sludge, 473, 0, :west
unit :thick_sludge, 475, 0, :west
unit :captive, 482, 0, :west
unit :captive, 485, 0, :west
unit :archer, 492, 0, :west
unit :archer, 497, 0, :west
unit :sludge, 499, 0, :west
unit :archer, 503, 0, :west
unit :thick_sludge, 504, 0, :west
unit :archer, 505, 0, :west
unit :sludge, 513, 0, :west
unit :wizard, 515, 0, :west
unit :wizard, 518, 0, :west
unit :wizard, 525, 0, :west
unit :wizard, 528, 0, :west
unit :archer, 537, 0, :west
unit :sludge, 541, 0, :west
unit :captive, 549, 0, :west
unit :wizard, 551, 0, :west
unit :wizard, 554, 0, :west
unit :captive, 558, 0, :west
unit :sludge, 559, 0, :west
unit :thick_sludge, 562, 0, :west
unit :wizard, 563, 0, :west
unit :archer, 565, 0, :west
unit :wizard, 568, 0, :west
unit :thick_sludge, 570, 0, :west
unit :sludge, 573, 0, :west
unit :wizard, 574, 0, :west
unit :thick_sludge, 578, 0, :west
unit :archer, 582, 0, :west
unit :thick_sludge, 586, 0, :west
unit :wizard, 591, 0, :west
unit :captive, 594, 0, :west
unit :sludge, 596, 0, :west
unit :archer, 600, 0, :west
unit :thick_sludge, 611, 0, :west
unit :archer, 612, 0, :west
unit :archer, 614, 0, :west
unit :archer, 622, 0, :west
unit :wizard, 625, 0, :west
unit :archer, 627, 0, :west
unit :captive, 629, 0, :west
unit :captive, 633, 0, :west
unit :sludge, 634, 0, :west
unit :sludge, 637, 0, :west
unit :thick_sludge, 641, 0, :west
unit :captive, 642, 0, :west
unit :archer, 646, 0, :west
unit :captive, 651, 0, :west
unit :thick_sludge, 657, 0, :west
unit :sludge, 662, 0, :west
unit :thick_sludge, 669, 0, :west
unit :archer, 672, 0, :west
unit :archer, 679, 0, :west
unit :thick_sludge, 680, 0, :west
unit :sludge, 681, 0, :west
unit :captive, 682, 0, :west
unit :wizard, 685, 0, :west
unit :archer, 692, 0, :west
unit :captive, 693, 0, :west
unit :sludge, 698, 0, :west
unit :thick_sludge, 705, 0, :west
unit :wizard, 706, 0, :west
unit :thick_sludge, 708, 0, :west
unit :thick_sludge, 710, 0, :west
unit :sludge, 711, 0, :west
unit :captive, 713, 0, :west
unit :captive, 717, 0, :west
unit :archer, 719, 0, :west
unit :archer, 725, 0, :west
unit :captive, 733, 0, :west
unit :wizard, 740, 0, :west
unit :thick_sludge, 742, 0, :west
unit :sludge, 743, 0, :west
unit :thick_sludge, 751, 0, :west
unit :wizard, 759, 0, :west
unit :thick_sludge, 761, 0, :west
unit :sludge, 762, 0, :west
unit :thick_sludge, 763, 0, :west
unit :archer, 764, 0, :west
unit :thick_sludge, 767, 0, :west
unit :wizard, 774, 0, :west
unit :thick_sludge, 775, 0, :west
unit :wizard, 776, 0, :west
unit :captive, 782, 0, :west
unit :captive, 783, 0, :west
unit :wizard, 787, 0, :west
unit :wizard, 793, 0, :west
unit :archer, 798, 0, :west
unit :archer, 799, 0, :west
unit :captive, 807, 0, :west
unit :sludge, 808, 0, :west
unit :archer, 811, 0, :west
unit :captive, 812, 0, :west
unit :thick_sludge, 818, 0, :west
unit :archer, 821, 0, :west
unit :archer, 826, 0, :west
unit :thick_sludge, 828, 0, :west
unit :sludge, 836, 0, :west
unit :archer, 845, 0, :west
unit :sludge, 847, 0, :west
unit :archer, 849, 0, :west
unit :thick_sludge, 854, 0, :west
unit :archer, 855, 0, :west
unit :wizard, 861, 0, :west
unit :sludge, 863, 0, :west
unit :thick_sludge, 869, 0, :west
unit :captive, 870, 0, :west
unit :captive, 873, 0, :west
unit :archer, 880, 0, :west
unit :archer, 882, 0, :west
unit :captive, 883, 0, :west
unit :thick_sludge, 885, 0, :west
unit :captive, 887, 0, :west
unit :sludge, 895, 0, :west
unit :wizard, 902, 0, :west
unit :sludge, 906, 0, :west
unit :captive, 912, 0, :west
unit :archer, 919, 0, :west
unit :wizard, 924, 0, :west
unit :archer, 931, 0, :west
unit :captive, 934, 0, :west
unit :sludge, 938, 0, :west
unit :sludge, 941, 0, :west
unit :captive, 942, 0, :west
unit :captive, 949, 0, :west
