#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |s C   S Css    C    w C   s C    C        S      S   S      s C       C            C  SS  Cw   C    w                 sSa a   wC  w    SS  a       w      CS      a s      C     S   w      s    C    w  w    as w  CC        s   w S S         S                C s  S      w   C   C as   wSss  C  s s C   w           S    w       aS                aa  CCSa    C   S  S           s   SSa S   w  w        C  C a   sSSw  SS C       S  a  s s C    s saa  w   aS        s  a      aS    ss   s  s  a    s    aC sw  C      S a  S   C sS    C  w             @  w S  s      w C     w    sw as   wC   w    S a> a a wa S     w                  C       S     Ca  a     s   C C s   a  sSC aw s    sw   C  s Ssa            a a   Cs           C      a    w C    a  a          s       s                        C      s  a         s   C      s  SSass        w  s        wC w  w CC   w C    C      C S  a aS   s  C w  S    C      s w          |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 921
ace_score 4605
size 921, 1
stairs 595, 0

warrior 546, 0, :east

unit :sludge, 0, 0, :east
unit :captive, 2, 0, :east
unit :thick_sludge, 6, 0, :east
unit :captive, 8, 0, :east
unit :sludge, 9, 0, :east
unit :sludge, 10, 0, :east
unit :captive, 15, 0, :east
unit :wizard, 20, 0, :east
unit :captive, 22, 0, :east
unit :sludge, 26, 0, :east
unit :captive, 28, 0, :east
unit :captive, 33, 0, :east
unit :thick_sludge, 42, 0, :east
unit :thick_sludge, 49, 0, :east
unit :thick_sludge, 53, 0, :east
unit :sludge, 60, 0, :east
unit :captive, 62, 0, :east
unit :captive, 70, 0, :east
unit :captive, 83, 0, :east
unit :thick_sludge, 86, 0, :east
unit :thick_sludge, 87, 0, :east
unit :captive, 90, 0, :east
unit :wizard, 91, 0, :east
unit :captive, 95, 0, :east
unit :wizard, 100, 0, :east
unit :sludge, 118, 0, :east
unit :thick_sludge, 119, 0, :east
unit :archer, 120, 0, :east
unit :archer, 122, 0, :east
unit :wizard, 126, 0, :east
unit :captive, 127, 0, :east
unit :wizard, 130, 0, :east
unit :thick_sludge, 135, 0, :east
unit :thick_sludge, 136, 0, :east
unit :archer, 139, 0, :east
unit :wizard, 147, 0, :east
unit :captive, 154, 0, :east
unit :thick_sludge, 155, 0, :east
unit :archer, 162, 0, :east
unit :sludge, 164, 0, :east
unit :captive, 171, 0, :east
unit :thick_sludge, 177, 0, :east
unit :wizard, 181, 0, :east
unit :sludge, 188, 0, :east
unit :captive, 193, 0, :east
unit :wizard, 198, 0, :east
unit :wizard, 201, 0, :east
unit :archer, 206, 0, :east
unit :sludge, 207, 0, :east
unit :wizard, 209, 0, :east
unit :captive, 212, 0, :east
unit :captive, 213, 0, :east
unit :sludge, 222, 0, :east
unit :wizard, 226, 0, :east
unit :thick_sludge, 228, 0, :east
unit :thick_sludge, 230, 0, :east
unit :thick_sludge, 240, 0, :east
unit :captive, 257, 0, :east
unit :sludge, 259, 0, :east
unit :thick_sludge, 262, 0, :east
unit :wizard, 269, 0, :east
unit :captive, 273, 0, :east
unit :captive, 277, 0, :east
unit :archer, 279, 0, :east
unit :sludge, 280, 0, :east
unit :wizard, 284, 0, :east
unit :thick_sludge, 285, 0, :east
unit :sludge, 286, 0, :east
unit :sludge, 287, 0, :east
unit :captive, 290, 0, :east
unit :sludge, 293, 0, :east
unit :sludge, 295, 0, :east
unit :captive, 297, 0, :east
unit :wizard, 301, 0, :east
unit :thick_sludge, 313, 0, :east
unit :wizard, 318, 0, :east
unit :archer, 326, 0, :east
unit :thick_sludge, 327, 0, :east
unit :archer, 344, 0, :east
unit :archer, 345, 0, :east
unit :captive, 348, 0, :east
unit :captive, 349, 0, :east
unit :thick_sludge, 350, 0, :east
unit :archer, 351, 0, :east
unit :captive, 356, 0, :east
unit :thick_sludge, 360, 0, :east
unit :thick_sludge, 363, 0, :east
unit :sludge, 375, 0, :east
unit :thick_sludge, 379, 0, :east
unit :thick_sludge, 380, 0, :east
unit :archer, 381, 0, :east
unit :thick_sludge, 383, 0, :east
unit :wizard, 387, 0, :east
unit :wizard, 390, 0, :east
unit :captive, 399, 0, :east
unit :captive, 402, 0, :east
unit :archer, 404, 0, :east
unit :sludge, 408, 0, :east
unit :thick_sludge, 409, 0, :east
unit :thick_sludge, 410, 0, :east
unit :wizard, 411, 0, :east
unit :thick_sludge, 414, 0, :east
unit :thick_sludge, 415, 0, :east
unit :captive, 417, 0, :east
unit :thick_sludge, 425, 0, :east
unit :archer, 428, 0, :east
unit :sludge, 431, 0, :east
unit :sludge, 433, 0, :east
unit :captive, 435, 0, :east
unit :sludge, 440, 0, :east
unit :sludge, 442, 0, :east
unit :archer, 443, 0, :east
unit :archer, 444, 0, :east
unit :wizard, 447, 0, :east
unit :archer, 451, 0, :east
unit :thick_sludge, 452, 0, :east
unit :sludge, 461, 0, :east
unit :archer, 464, 0, :east
unit :archer, 471, 0, :east
unit :thick_sludge, 472, 0, :east
unit :sludge, 477, 0, :east
unit :sludge, 478, 0, :east
unit :sludge, 482, 0, :east
unit :sludge, 485, 0, :east
unit :archer, 488, 0, :east
unit :sludge, 493, 0, :east
unit :archer, 498, 0, :east
unit :captive, 499, 0, :east
unit :sludge, 501, 0, :east
unit :wizard, 502, 0, :east
unit :captive, 505, 0, :east
unit :thick_sludge, 512, 0, :east
unit :archer, 514, 0, :east
unit :thick_sludge, 517, 0, :east
unit :captive, 521, 0, :east
unit :sludge, 523, 0, :east
unit :thick_sludge, 524, 0, :east
unit :captive, 529, 0, :east
unit :wizard, 532, 0, :east
unit :wizard, 549, 0, :west
unit :thick_sludge, 551, 0, :west
unit :sludge, 554, 0, :west
unit :wizard, 561, 0, :west
unit :captive, 563, 0, :west
unit :wizard, 569, 0, :west
unit :sludge, 574, 0, :west
unit :wizard, 575, 0, :west
unit :archer, 577, 0, :west
unit :sludge, 578, 0, :west
unit :wizard, 582, 0, :west
unit :captive, 583, 0, :west
unit :wizard, 587, 0, :west
unit :thick_sludge, 592, 0, :west
unit :archer, 594, 0, :west
unit :archer, 597, 0, :west
unit :archer, 599, 0, :west
unit :wizard, 601, 0, :west
unit :archer, 602, 0, :west
unit :thick_sludge, 604, 0, :west
unit :wizard, 610, 0, :west
unit :captive, 629, 0, :west
unit :thick_sludge, 637, 0, :west
unit :captive, 643, 0, :west
unit :archer, 644, 0, :west
unit :archer, 647, 0, :west
unit :sludge, 653, 0, :west
unit :captive, 657, 0, :west
unit :captive, 659, 0, :west
unit :sludge, 661, 0, :west
unit :archer, 665, 0, :west
unit :sludge, 668, 0, :west
unit :thick_sludge, 669, 0, :west
unit :captive, 670, 0, :west
unit :archer, 672, 0, :west
unit :wizard, 673, 0, :west
unit :sludge, 675, 0, :west
unit :sludge, 680, 0, :west
unit :wizard, 681, 0, :west
unit :captive, 685, 0, :west
unit :sludge, 688, 0, :west
unit :thick_sludge, 690, 0, :west
unit :sludge, 691, 0, :west
unit :archer, 692, 0, :west
unit :archer, 705, 0, :west
unit :archer, 707, 0, :west
unit :captive, 711, 0, :west
unit :sludge, 712, 0, :west
unit :captive, 724, 0, :west
unit :archer, 731, 0, :west
unit :wizard, 736, 0, :west
unit :captive, 738, 0, :west
unit :archer, 743, 0, :west
unit :archer, 746, 0, :west
unit :sludge, 757, 0, :west
unit :sludge, 765, 0, :west
unit :captive, 790, 0, :west
unit :sludge, 797, 0, :west
unit :archer, 800, 0, :west
unit :sludge, 810, 0, :west
unit :captive, 814, 0, :west
unit :sludge, 821, 0, :west
unit :thick_sludge, 824, 0, :west
unit :thick_sludge, 825, 0, :west
unit :archer, 826, 0, :west
unit :sludge, 827, 0, :west
unit :sludge, 828, 0, :west
unit :wizard, 837, 0, :west
unit :sludge, 840, 0, :west
unit :wizard, 849, 0, :west
unit :captive, 850, 0, :west
unit :wizard, 852, 0, :west
unit :wizard, 855, 0, :west
unit :captive, 857, 0, :west
unit :captive, 858, 0, :west
unit :wizard, 862, 0, :west
unit :captive, 864, 0, :west
unit :captive, 869, 0, :west
unit :captive, 876, 0, :west
unit :thick_sludge, 878, 0, :west
unit :archer, 881, 0, :west
unit :archer, 883, 0, :west
unit :thick_sludge, 884, 0, :west
unit :sludge, 888, 0, :west
unit :captive, 891, 0, :west
unit :wizard, 893, 0, :west
unit :thick_sludge, 896, 0, :west
unit :captive, 901, 0, :west
unit :sludge, 908, 0, :west
unit :wizard, 910, 0, :west
