#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w aa  swa    s         swS   Ss      S s a C w  s  S  w    C  w     aCS  w a   C S           w  aaw    S  C        a          Ca   w s  C    C  SS   C    a S  ss >   a       S SCw     sC   C      w        w  C           SSS            Cw     w        s w  Sa   s  sCS  S  wS      C w   a     ss   a  w w    w   a      a    C  s  a w w   aS   S w  wC   s     CC   ss  S      s  C s S                     aS C               aC                  s   S     sa       aw     s         a  a S    w   Ca   aw   a        a  S   S w  s    w   s    s      C  s   w S      CS   w   @     s a a w   S    S      w       w      w       |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 622
ace_score 3110
size 622, 1
stairs 164, 0

warrior 571, 0, :east

unit :wizard, 2, 0, :east
unit :archer, 4, 0, :east
unit :archer, 5, 0, :east
unit :sludge, 8, 0, :east
unit :wizard, 9, 0, :east
unit :archer, 10, 0, :east
unit :sludge, 15, 0, :east
unit :sludge, 25, 0, :east
unit :wizard, 26, 0, :east
unit :thick_sludge, 27, 0, :east
unit :thick_sludge, 31, 0, :east
unit :sludge, 32, 0, :east
unit :thick_sludge, 39, 0, :east
unit :sludge, 41, 0, :east
unit :archer, 43, 0, :east
unit :captive, 45, 0, :east
unit :wizard, 47, 0, :east
unit :sludge, 50, 0, :east
unit :thick_sludge, 53, 0, :east
unit :wizard, 56, 0, :east
unit :captive, 61, 0, :east
unit :wizard, 64, 0, :east
unit :archer, 70, 0, :east
unit :captive, 71, 0, :east
unit :thick_sludge, 72, 0, :east
unit :wizard, 75, 0, :east
unit :archer, 77, 0, :east
unit :captive, 81, 0, :east
unit :thick_sludge, 83, 0, :east
unit :wizard, 95, 0, :east
unit :archer, 98, 0, :east
unit :archer, 99, 0, :east
unit :wizard, 100, 0, :east
unit :thick_sludge, 105, 0, :east
unit :captive, 108, 0, :east
unit :archer, 117, 0, :east
unit :captive, 128, 0, :east
unit :archer, 129, 0, :east
unit :wizard, 133, 0, :east
unit :sludge, 135, 0, :east
unit :captive, 138, 0, :east
unit :captive, 143, 0, :east
unit :thick_sludge, 146, 0, :east
unit :thick_sludge, 147, 0, :east
unit :captive, 151, 0, :east
unit :archer, 156, 0, :east
unit :thick_sludge, 158, 0, :east
unit :sludge, 161, 0, :east
unit :sludge, 162, 0, :east
unit :archer, 168, 0, :east
unit :thick_sludge, 176, 0, :east
unit :thick_sludge, 178, 0, :east
unit :captive, 179, 0, :east
unit :wizard, 180, 0, :east
unit :sludge, 186, 0, :east
unit :captive, 187, 0, :east
unit :captive, 191, 0, :east
unit :wizard, 198, 0, :east
unit :wizard, 207, 0, :east
unit :captive, 210, 0, :east
unit :thick_sludge, 222, 0, :east
unit :thick_sludge, 223, 0, :east
unit :thick_sludge, 224, 0, :east
unit :captive, 237, 0, :east
unit :wizard, 238, 0, :east
unit :wizard, 244, 0, :east
unit :sludge, 253, 0, :east
unit :wizard, 255, 0, :east
unit :thick_sludge, 258, 0, :east
unit :archer, 259, 0, :east
unit :sludge, 263, 0, :east
unit :sludge, 266, 0, :east
unit :captive, 267, 0, :east
unit :thick_sludge, 268, 0, :east
unit :thick_sludge, 271, 0, :east
unit :wizard, 274, 0, :east
unit :thick_sludge, 275, 0, :east
unit :captive, 282, 0, :east
unit :wizard, 284, 0, :east
unit :archer, 288, 0, :east
unit :sludge, 294, 0, :east
unit :sludge, 295, 0, :east
unit :archer, 299, 0, :east
unit :wizard, 302, 0, :east
unit :wizard, 304, 0, :east
unit :wizard, 309, 0, :east
unit :archer, 313, 0, :east
unit :archer, 320, 0, :east
unit :captive, 325, 0, :east
unit :sludge, 328, 0, :east
unit :archer, 331, 0, :east
unit :wizard, 333, 0, :east
unit :wizard, 335, 0, :east
unit :archer, 339, 0, :east
unit :thick_sludge, 340, 0, :east
unit :thick_sludge, 344, 0, :east
unit :wizard, 346, 0, :east
unit :wizard, 349, 0, :east
unit :captive, 350, 0, :east
unit :sludge, 354, 0, :east
unit :captive, 360, 0, :east
unit :captive, 361, 0, :east
unit :sludge, 365, 0, :east
unit :sludge, 366, 0, :east
unit :thick_sludge, 369, 0, :east
unit :sludge, 376, 0, :east
unit :captive, 379, 0, :east
unit :sludge, 381, 0, :east
unit :thick_sludge, 383, 0, :east
unit :archer, 405, 0, :east
unit :thick_sludge, 406, 0, :east
unit :captive, 408, 0, :east
unit :archer, 424, 0, :east
unit :captive, 425, 0, :east
unit :sludge, 444, 0, :east
unit :thick_sludge, 448, 0, :east
unit :sludge, 454, 0, :east
unit :archer, 455, 0, :east
unit :archer, 463, 0, :east
unit :wizard, 464, 0, :east
unit :sludge, 470, 0, :east
unit :archer, 480, 0, :east
unit :archer, 483, 0, :east
unit :thick_sludge, 485, 0, :east
unit :wizard, 490, 0, :east
unit :captive, 494, 0, :east
unit :archer, 495, 0, :east
unit :archer, 499, 0, :east
unit :wizard, 500, 0, :east
unit :archer, 504, 0, :east
unit :archer, 513, 0, :east
unit :thick_sludge, 516, 0, :east
unit :thick_sludge, 520, 0, :east
unit :wizard, 522, 0, :east
unit :sludge, 525, 0, :east
unit :wizard, 530, 0, :east
unit :sludge, 534, 0, :east
unit :sludge, 539, 0, :east
unit :captive, 546, 0, :east
unit :sludge, 549, 0, :east
unit :wizard, 553, 0, :east
unit :thick_sludge, 555, 0, :east
unit :captive, 562, 0, :east
unit :thick_sludge, 563, 0, :east
unit :wizard, 567, 0, :east
unit :sludge, 577, 0, :west
unit :archer, 579, 0, :west
unit :archer, 581, 0, :west
unit :wizard, 583, 0, :west
unit :thick_sludge, 587, 0, :west
unit :thick_sludge, 592, 0, :west
unit :wizard, 599, 0, :west
unit :wizard, 607, 0, :west
unit :wizard, 614, 0, :west
