#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   CS  @  C  w C    w    w  S     a C   S    C      S          a           C   C         swS            s    C    SC   S    w C s  C S       as a    w w  w      s     a a         w s   Sw C aC  S  C   w     a       Ss SC               SS           a S      a s  s w   a    S s   s       S C w    a  a  C  S   C     s   s   S aa C       C S          S   s sa S               > w CS as    w         S       aa   C      w                               C   s      S s       S         S   S   saa C s     sa    s S   s S w         C    as    S  C  a   w  S s S SS   ws  S a        s s        S w   S      S C  a   s sa a s ss S  w SsC   w        aS        s   sSSaS ss SC wa  C        sa w       w   w  SC s   a       Ca    C  a a   S              S C   SC      a   S|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 762
ace_score 3810
size 762, 1
stairs 374, 0

warrior 7, 0, :east

unit :captive, 3, 0, :east
unit :thick_sludge, 4, 0, :east
unit :captive, 10, 0, :west
unit :wizard, 13, 0, :west
unit :captive, 15, 0, :west
unit :wizard, 20, 0, :west
unit :wizard, 25, 0, :west
unit :thick_sludge, 28, 0, :west
unit :archer, 34, 0, :west
unit :captive, 36, 0, :west
unit :thick_sludge, 40, 0, :west
unit :captive, 45, 0, :west
unit :thick_sludge, 52, 0, :west
unit :archer, 63, 0, :west
unit :captive, 75, 0, :west
unit :captive, 79, 0, :west
unit :sludge, 89, 0, :west
unit :wizard, 90, 0, :west
unit :thick_sludge, 91, 0, :west
unit :sludge, 104, 0, :west
unit :captive, 109, 0, :west
unit :thick_sludge, 114, 0, :west
unit :captive, 115, 0, :west
unit :thick_sludge, 119, 0, :west
unit :wizard, 124, 0, :west
unit :captive, 126, 0, :west
unit :sludge, 128, 0, :west
unit :captive, 131, 0, :west
unit :thick_sludge, 133, 0, :west
unit :archer, 141, 0, :west
unit :sludge, 142, 0, :west
unit :archer, 144, 0, :west
unit :wizard, 149, 0, :west
unit :wizard, 151, 0, :west
unit :wizard, 154, 0, :west
unit :sludge, 161, 0, :west
unit :archer, 167, 0, :west
unit :archer, 169, 0, :west
unit :wizard, 179, 0, :west
unit :sludge, 181, 0, :west
unit :thick_sludge, 185, 0, :west
unit :wizard, 186, 0, :west
unit :captive, 188, 0, :west
unit :archer, 190, 0, :west
unit :captive, 191, 0, :west
unit :thick_sludge, 194, 0, :west
unit :captive, 197, 0, :west
unit :wizard, 201, 0, :west
unit :archer, 207, 0, :west
unit :thick_sludge, 215, 0, :west
unit :sludge, 216, 0, :west
unit :thick_sludge, 218, 0, :west
unit :captive, 219, 0, :west
unit :thick_sludge, 235, 0, :west
unit :thick_sludge, 236, 0, :west
unit :archer, 248, 0, :west
unit :thick_sludge, 250, 0, :west
unit :archer, 257, 0, :west
unit :sludge, 259, 0, :west
unit :sludge, 262, 0, :west
unit :wizard, 264, 0, :west
unit :archer, 268, 0, :west
unit :thick_sludge, 273, 0, :west
unit :sludge, 275, 0, :west
unit :sludge, 279, 0, :west
unit :thick_sludge, 287, 0, :west
unit :captive, 289, 0, :west
unit :wizard, 291, 0, :west
unit :archer, 296, 0, :west
unit :archer, 299, 0, :west
unit :captive, 302, 0, :west
unit :thick_sludge, 305, 0, :west
unit :captive, 309, 0, :west
unit :sludge, 315, 0, :west
unit :sludge, 319, 0, :west
unit :thick_sludge, 323, 0, :west
unit :archer, 325, 0, :west
unit :archer, 326, 0, :west
unit :captive, 328, 0, :west
unit :captive, 336, 0, :west
unit :thick_sludge, 338, 0, :west
unit :thick_sludge, 349, 0, :west
unit :sludge, 353, 0, :west
unit :sludge, 355, 0, :west
unit :archer, 356, 0, :west
unit :thick_sludge, 358, 0, :west
unit :wizard, 376, 0, :west
unit :captive, 378, 0, :west
unit :thick_sludge, 379, 0, :west
unit :archer, 381, 0, :west
unit :sludge, 382, 0, :west
unit :wizard, 387, 0, :west
unit :thick_sludge, 397, 0, :west
unit :archer, 405, 0, :west
unit :archer, 406, 0, :west
unit :captive, 410, 0, :west
unit :wizard, 417, 0, :west
unit :captive, 449, 0, :west
unit :sludge, 453, 0, :west
unit :thick_sludge, 460, 0, :west
unit :sludge, 462, 0, :west
unit :thick_sludge, 470, 0, :west
unit :thick_sludge, 480, 0, :west
unit :thick_sludge, 484, 0, :west
unit :sludge, 488, 0, :west
unit :archer, 489, 0, :west
unit :archer, 490, 0, :west
unit :captive, 492, 0, :west
unit :sludge, 494, 0, :west
unit :sludge, 500, 0, :west
unit :archer, 501, 0, :west
unit :sludge, 506, 0, :west
unit :thick_sludge, 508, 0, :west
unit :sludge, 512, 0, :west
unit :thick_sludge, 514, 0, :west
unit :wizard, 516, 0, :west
unit :captive, 526, 0, :west
unit :archer, 531, 0, :west
unit :sludge, 532, 0, :west
unit :thick_sludge, 537, 0, :west
unit :captive, 540, 0, :west
unit :archer, 543, 0, :west
unit :wizard, 547, 0, :west
unit :thick_sludge, 550, 0, :west
unit :sludge, 552, 0, :west
unit :thick_sludge, 554, 0, :west
unit :thick_sludge, 556, 0, :west
unit :thick_sludge, 557, 0, :west
unit :wizard, 561, 0, :west
unit :sludge, 562, 0, :west
unit :thick_sludge, 565, 0, :west
unit :archer, 567, 0, :west
unit :sludge, 576, 0, :west
unit :sludge, 578, 0, :west
unit :thick_sludge, 587, 0, :west
unit :wizard, 589, 0, :west
unit :thick_sludge, 593, 0, :west
unit :thick_sludge, 600, 0, :west
unit :captive, 602, 0, :west
unit :archer, 605, 0, :west
unit :sludge, 609, 0, :west
unit :sludge, 611, 0, :west
unit :archer, 612, 0, :west
unit :archer, 614, 0, :west
unit :sludge, 616, 0, :west
unit :sludge, 618, 0, :west
unit :sludge, 619, 0, :west
unit :thick_sludge, 621, 0, :west
unit :wizard, 624, 0, :west
unit :thick_sludge, 626, 0, :west
unit :sludge, 627, 0, :west
unit :captive, 628, 0, :west
unit :wizard, 632, 0, :west
unit :archer, 641, 0, :west
unit :thick_sludge, 642, 0, :west
unit :sludge, 651, 0, :west
unit :sludge, 655, 0, :west
unit :thick_sludge, 656, 0, :west
unit :thick_sludge, 657, 0, :west
unit :archer, 658, 0, :west
unit :thick_sludge, 659, 0, :west
unit :sludge, 661, 0, :west
unit :sludge, 662, 0, :west
unit :thick_sludge, 664, 0, :west
unit :captive, 665, 0, :west
unit :wizard, 667, 0, :west
unit :archer, 668, 0, :west
unit :captive, 671, 0, :west
unit :sludge, 680, 0, :west
unit :archer, 681, 0, :west
unit :wizard, 683, 0, :west
unit :wizard, 691, 0, :west
unit :wizard, 695, 0, :west
unit :thick_sludge, 698, 0, :west
unit :captive, 699, 0, :west
unit :sludge, 701, 0, :west
unit :archer, 705, 0, :west
unit :captive, 713, 0, :west
unit :archer, 714, 0, :west
unit :captive, 719, 0, :west
unit :archer, 722, 0, :west
unit :archer, 724, 0, :west
unit :thick_sludge, 728, 0, :west
unit :thick_sludge, 743, 0, :west
unit :captive, 745, 0, :west
unit :thick_sludge, 749, 0, :west
unit :captive, 750, 0, :west
unit :archer, 757, 0, :west
unit :thick_sludge, 761, 0, :west
