#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S    S  aw           C             s s  SCs     s  aC   w    C   C   w  S   aa   w      w   S s s    S Swa  S SS      s      aaa w            S     @  a    s      CC       w  w s              S   C C    SC CC      w     CC   a S  w   S   C  S      >     w         a   a       a       C  S          a C    S  w  a s   CC ss  S   SS      a   Cs       ss        S    ws   a   SC  S aaC           w S      s  Cw       a     a    w    s  sC           w    w w     S s     CC   w      s wS    s a  a C a   S     w      C           CSs      a       s       C   S sCs         w  S   w         w              s  w C    S       C  s     s w   w Ss      s C       S a C      w   S     sw        w     C   aw C   S a  CC  s   s        w      a a  s     C      aSa   C a aa        a   Ss  w        wS   Cs   CS          a   S     S ss  a     sw        S a         s SS   sC   C s a  S     w S      wS a         aC     S   C S        Sa     w  CwSa         a as  s Sw    s  wS  S Ss  w  S      w   s a S     w     CS   s|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 1006
ace_score 5030
size 1006, 1
stairs 248, 0

warrior 148, 0, :east

unit :thick_sludge, 0, 0, :east
unit :thick_sludge, 5, 0, :east
unit :archer, 8, 0, :east
unit :wizard, 9, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 35, 0, :east
unit :sludge, 37, 0, :east
unit :thick_sludge, 40, 0, :east
unit :captive, 41, 0, :east
unit :sludge, 42, 0, :east
unit :sludge, 48, 0, :east
unit :archer, 51, 0, :east
unit :captive, 52, 0, :east
unit :wizard, 56, 0, :east
unit :captive, 61, 0, :east
unit :captive, 65, 0, :east
unit :wizard, 69, 0, :east
unit :thick_sludge, 72, 0, :east
unit :archer, 76, 0, :east
unit :archer, 77, 0, :east
unit :wizard, 81, 0, :east
unit :wizard, 88, 0, :east
unit :thick_sludge, 92, 0, :east
unit :sludge, 94, 0, :east
unit :sludge, 96, 0, :east
unit :thick_sludge, 101, 0, :east
unit :thick_sludge, 103, 0, :east
unit :wizard, 104, 0, :east
unit :archer, 105, 0, :east
unit :thick_sludge, 108, 0, :east
unit :thick_sludge, 110, 0, :east
unit :thick_sludge, 111, 0, :east
unit :sludge, 118, 0, :east
unit :archer, 125, 0, :east
unit :archer, 126, 0, :east
unit :archer, 127, 0, :east
unit :wizard, 129, 0, :east
unit :thick_sludge, 142, 0, :east
unit :archer, 151, 0, :west
unit :sludge, 156, 0, :west
unit :captive, 163, 0, :west
unit :captive, 164, 0, :west
unit :wizard, 172, 0, :west
unit :wizard, 175, 0, :west
unit :sludge, 177, 0, :west
unit :thick_sludge, 192, 0, :west
unit :captive, 196, 0, :west
unit :captive, 198, 0, :west
unit :thick_sludge, 203, 0, :west
unit :captive, 204, 0, :west
unit :captive, 206, 0, :west
unit :captive, 207, 0, :west
unit :wizard, 214, 0, :west
unit :captive, 220, 0, :west
unit :captive, 221, 0, :west
unit :archer, 225, 0, :west
unit :thick_sludge, 227, 0, :west
unit :wizard, 230, 0, :west
unit :thick_sludge, 234, 0, :west
unit :captive, 238, 0, :west
unit :thick_sludge, 241, 0, :west
unit :wizard, 254, 0, :west
unit :archer, 264, 0, :west
unit :archer, 268, 0, :west
unit :archer, 276, 0, :west
unit :captive, 284, 0, :west
unit :thick_sludge, 287, 0, :west
unit :archer, 298, 0, :west
unit :captive, 300, 0, :west
unit :thick_sludge, 305, 0, :west
unit :wizard, 308, 0, :west
unit :archer, 311, 0, :west
unit :sludge, 313, 0, :west
unit :captive, 317, 0, :west
unit :captive, 318, 0, :west
unit :sludge, 320, 0, :west
unit :sludge, 321, 0, :west
unit :thick_sludge, 324, 0, :west
unit :thick_sludge, 328, 0, :west
unit :thick_sludge, 329, 0, :west
unit :archer, 336, 0, :west
unit :captive, 340, 0, :west
unit :sludge, 341, 0, :west
unit :sludge, 349, 0, :west
unit :sludge, 350, 0, :west
unit :thick_sludge, 359, 0, :west
unit :wizard, 364, 0, :west
unit :sludge, 365, 0, :west
unit :archer, 369, 0, :west
unit :thick_sludge, 373, 0, :west
unit :captive, 374, 0, :west
unit :thick_sludge, 377, 0, :west
unit :archer, 379, 0, :west
unit :archer, 380, 0, :west
unit :captive, 381, 0, :west
unit :wizard, 393, 0, :west
unit :thick_sludge, 395, 0, :west
unit :sludge, 402, 0, :west
unit :captive, 405, 0, :west
unit :wizard, 406, 0, :west
unit :archer, 414, 0, :west
unit :archer, 420, 0, :west
unit :wizard, 425, 0, :west
unit :sludge, 430, 0, :west
unit :sludge, 433, 0, :west
unit :captive, 434, 0, :west
unit :wizard, 446, 0, :west
unit :wizard, 451, 0, :west
unit :wizard, 453, 0, :west
unit :thick_sludge, 459, 0, :west
unit :sludge, 461, 0, :west
unit :captive, 467, 0, :west
unit :captive, 468, 0, :west
unit :wizard, 472, 0, :west
unit :sludge, 479, 0, :west
unit :wizard, 481, 0, :west
unit :thick_sludge, 482, 0, :west
unit :sludge, 487, 0, :west
unit :archer, 489, 0, :west
unit :archer, 492, 0, :west
unit :captive, 494, 0, :west
unit :archer, 496, 0, :west
unit :thick_sludge, 500, 0, :west
unit :wizard, 506, 0, :west
unit :captive, 513, 0, :west
unit :captive, 525, 0, :west
unit :thick_sludge, 526, 0, :west
unit :sludge, 527, 0, :west
unit :archer, 534, 0, :west
unit :sludge, 542, 0, :west
unit :captive, 550, 0, :west
unit :thick_sludge, 554, 0, :west
unit :sludge, 556, 0, :west
unit :captive, 557, 0, :west
unit :sludge, 558, 0, :west
unit :wizard, 568, 0, :west
unit :thick_sludge, 571, 0, :west
unit :wizard, 575, 0, :west
unit :wizard, 585, 0, :west
unit :sludge, 600, 0, :west
unit :wizard, 603, 0, :west
unit :captive, 605, 0, :west
unit :thick_sludge, 610, 0, :west
unit :captive, 618, 0, :west
unit :sludge, 621, 0, :west
unit :sludge, 627, 0, :west
unit :wizard, 629, 0, :west
unit :wizard, 633, 0, :west
unit :thick_sludge, 635, 0, :west
unit :sludge, 636, 0, :west
unit :sludge, 643, 0, :west
unit :captive, 645, 0, :west
unit :thick_sludge, 653, 0, :west
unit :archer, 655, 0, :west
unit :captive, 657, 0, :west
unit :wizard, 664, 0, :west
unit :thick_sludge, 668, 0, :west
unit :sludge, 674, 0, :west
unit :wizard, 675, 0, :west
unit :wizard, 684, 0, :west
unit :captive, 690, 0, :west
unit :archer, 694, 0, :west
unit :wizard, 695, 0, :west
unit :captive, 697, 0, :west
unit :thick_sludge, 701, 0, :west
unit :archer, 703, 0, :west
unit :captive, 706, 0, :west
unit :captive, 707, 0, :west
unit :sludge, 710, 0, :west
unit :sludge, 714, 0, :west
unit :wizard, 723, 0, :west
unit :archer, 730, 0, :west
unit :archer, 732, 0, :west
unit :sludge, 735, 0, :west
unit :captive, 741, 0, :west
unit :archer, 748, 0, :west
unit :thick_sludge, 749, 0, :west
unit :archer, 750, 0, :west
unit :captive, 754, 0, :west
unit :archer, 756, 0, :west
unit :archer, 758, 0, :west
unit :archer, 759, 0, :west
unit :archer, 768, 0, :west
unit :thick_sludge, 772, 0, :west
unit :sludge, 773, 0, :west
unit :wizard, 776, 0, :west
unit :wizard, 785, 0, :west
unit :thick_sludge, 786, 0, :west
unit :captive, 790, 0, :west
unit :sludge, 791, 0, :west
unit :captive, 795, 0, :west
unit :thick_sludge, 796, 0, :west
unit :archer, 807, 0, :west
unit :thick_sludge, 811, 0, :west
unit :thick_sludge, 817, 0, :west
unit :sludge, 819, 0, :west
unit :sludge, 820, 0, :west
unit :archer, 823, 0, :west
unit :sludge, 829, 0, :west
unit :wizard, 830, 0, :west
unit :thick_sludge, 839, 0, :west
unit :archer, 841, 0, :west
unit :sludge, 851, 0, :west
unit :thick_sludge, 853, 0, :west
unit :thick_sludge, 854, 0, :west
unit :sludge, 858, 0, :west
unit :captive, 859, 0, :west
unit :captive, 863, 0, :west
unit :sludge, 865, 0, :west
unit :archer, 867, 0, :west
unit :thick_sludge, 870, 0, :west
unit :wizard, 876, 0, :west
unit :thick_sludge, 878, 0, :west
unit :wizard, 885, 0, :west
unit :thick_sludge, 886, 0, :west
unit :archer, 888, 0, :west
unit :archer, 898, 0, :west
unit :captive, 899, 0, :west
unit :thick_sludge, 905, 0, :west
unit :captive, 909, 0, :west
unit :thick_sludge, 911, 0, :west
unit :thick_sludge, 920, 0, :west
unit :archer, 921, 0, :west
unit :wizard, 927, 0, :west
unit :captive, 930, 0, :west
unit :wizard, 931, 0, :west
unit :thick_sludge, 932, 0, :west
unit :archer, 933, 0, :west
unit :archer, 943, 0, :west
unit :archer, 945, 0, :west
unit :sludge, 946, 0, :west
unit :sludge, 949, 0, :west
unit :thick_sludge, 951, 0, :west
unit :wizard, 952, 0, :west
unit :sludge, 957, 0, :west
unit :wizard, 960, 0, :west
unit :thick_sludge, 961, 0, :west
unit :thick_sludge, 964, 0, :west
unit :thick_sludge, 966, 0, :west
unit :sludge, 967, 0, :west
unit :wizard, 970, 0, :west
unit :thick_sludge, 973, 0, :west
unit :wizard, 980, 0, :west
unit :sludge, 984, 0, :west
unit :archer, 986, 0, :west
unit :thick_sludge, 988, 0, :west
unit :wizard, 994, 0, :west
unit :captive, 1000, 0, :west
unit :thick_sludge, 1001, 0, :west
unit :sludge, 1005, 0, :west
