#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |as  a w    s s   w    Cs w  a     C     Ca  SC   SS  Sw C    S        S   s       ws  w   s CC      a  Sa    w   Ss    C     C S    s      S C       ss a  s C  s     S           C  aS C      s     sS       a s w a         aC w     Cs  a    Ss  s         C      C   C S    Sw  S   S  s  S  a  w     Ca                  S  a              C           a C       w       s       S         s     >s s       asa          w s SS   a S S  S    w     S      as     a        wSS S   s            Sa  sSC  CC   @   C   S   CSa  s    C   s     SC       C           w   s wS   C s     C     S     w       S   a     C w   a   w  Ca s  ss a                sa s    a  C a   C  a        aaC   C      w C S   S       Cas    a     s    s    C          sC   S S   C  C  a  C  s    w           a   w  s     w S   S   SC w      w       wSs      a   S  S a s       a  CSs  Ss C    w     wa  a   s  s s    |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 881
ace_score 4405
size 881, 1
stairs 390, 0

warrior 499, 0, :east

unit :archer, 0, 0, :east
unit :sludge, 1, 0, :east
unit :archer, 4, 0, :east
unit :wizard, 6, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 13, 0, :east
unit :wizard, 17, 0, :east
unit :captive, 22, 0, :east
unit :sludge, 23, 0, :east
unit :wizard, 25, 0, :east
unit :archer, 28, 0, :east
unit :captive, 34, 0, :east
unit :captive, 40, 0, :east
unit :archer, 41, 0, :east
unit :thick_sludge, 44, 0, :east
unit :captive, 45, 0, :east
unit :thick_sludge, 49, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 53, 0, :east
unit :wizard, 54, 0, :east
unit :captive, 56, 0, :east
unit :thick_sludge, 61, 0, :east
unit :thick_sludge, 70, 0, :east
unit :sludge, 74, 0, :east
unit :wizard, 82, 0, :east
unit :sludge, 83, 0, :east
unit :wizard, 86, 0, :east
unit :sludge, 90, 0, :east
unit :captive, 92, 0, :east
unit :captive, 93, 0, :east
unit :archer, 100, 0, :east
unit :thick_sludge, 103, 0, :east
unit :archer, 104, 0, :east
unit :wizard, 109, 0, :east
unit :thick_sludge, 113, 0, :east
unit :sludge, 114, 0, :east
unit :captive, 119, 0, :east
unit :captive, 125, 0, :east
unit :thick_sludge, 127, 0, :east
unit :sludge, 132, 0, :east
unit :thick_sludge, 139, 0, :east
unit :captive, 141, 0, :east
unit :sludge, 149, 0, :east
unit :sludge, 150, 0, :east
unit :archer, 152, 0, :east
unit :sludge, 155, 0, :east
unit :captive, 157, 0, :east
unit :sludge, 160, 0, :east
unit :thick_sludge, 166, 0, :east
unit :captive, 178, 0, :east
unit :archer, 181, 0, :east
unit :thick_sludge, 182, 0, :east
unit :captive, 184, 0, :east
unit :sludge, 191, 0, :east
unit :sludge, 197, 0, :east
unit :thick_sludge, 198, 0, :east
unit :archer, 206, 0, :east
unit :sludge, 208, 0, :east
unit :wizard, 210, 0, :east
unit :archer, 212, 0, :east
unit :archer, 222, 0, :east
unit :captive, 223, 0, :east
unit :wizard, 225, 0, :east
unit :captive, 231, 0, :east
unit :sludge, 232, 0, :east
unit :archer, 235, 0, :east
unit :thick_sludge, 240, 0, :east
unit :sludge, 241, 0, :east
unit :sludge, 244, 0, :east
unit :captive, 254, 0, :east
unit :captive, 261, 0, :east
unit :captive, 265, 0, :east
unit :thick_sludge, 267, 0, :east
unit :thick_sludge, 272, 0, :east
unit :wizard, 273, 0, :east
unit :thick_sludge, 276, 0, :east
unit :thick_sludge, 280, 0, :east
unit :sludge, 283, 0, :east
unit :thick_sludge, 286, 0, :east
unit :archer, 289, 0, :east
unit :wizard, 292, 0, :east
unit :captive, 298, 0, :east
unit :archer, 299, 0, :east
unit :thick_sludge, 318, 0, :east
unit :archer, 321, 0, :east
unit :captive, 336, 0, :east
unit :archer, 348, 0, :east
unit :captive, 350, 0, :east
unit :wizard, 358, 0, :east
unit :sludge, 366, 0, :east
unit :thick_sludge, 374, 0, :east
unit :sludge, 384, 0, :east
unit :sludge, 391, 0, :east
unit :sludge, 393, 0, :east
unit :archer, 401, 0, :east
unit :sludge, 402, 0, :east
unit :archer, 403, 0, :east
unit :wizard, 414, 0, :east
unit :sludge, 416, 0, :east
unit :thick_sludge, 418, 0, :east
unit :thick_sludge, 419, 0, :east
unit :archer, 423, 0, :east
unit :thick_sludge, 425, 0, :east
unit :thick_sludge, 427, 0, :east
unit :thick_sludge, 430, 0, :east
unit :wizard, 435, 0, :east
unit :thick_sludge, 441, 0, :east
unit :archer, 448, 0, :east
unit :sludge, 449, 0, :east
unit :archer, 455, 0, :east
unit :wizard, 464, 0, :east
unit :thick_sludge, 465, 0, :east
unit :thick_sludge, 466, 0, :east
unit :thick_sludge, 468, 0, :east
unit :sludge, 472, 0, :east
unit :thick_sludge, 485, 0, :east
unit :archer, 486, 0, :east
unit :sludge, 489, 0, :east
unit :thick_sludge, 490, 0, :east
unit :captive, 491, 0, :east
unit :captive, 494, 0, :east
unit :captive, 495, 0, :east
unit :captive, 503, 0, :west
unit :thick_sludge, 507, 0, :west
unit :captive, 511, 0, :west
unit :thick_sludge, 512, 0, :west
unit :archer, 513, 0, :west
unit :sludge, 516, 0, :west
unit :captive, 521, 0, :west
unit :sludge, 525, 0, :west
unit :thick_sludge, 531, 0, :west
unit :captive, 532, 0, :west
unit :captive, 540, 0, :west
unit :wizard, 552, 0, :west
unit :sludge, 556, 0, :west
unit :wizard, 558, 0, :west
unit :thick_sludge, 559, 0, :west
unit :captive, 563, 0, :west
unit :sludge, 565, 0, :west
unit :captive, 571, 0, :west
unit :thick_sludge, 577, 0, :west
unit :wizard, 583, 0, :west
unit :thick_sludge, 591, 0, :west
unit :archer, 595, 0, :west
unit :captive, 601, 0, :west
unit :wizard, 603, 0, :west
unit :archer, 607, 0, :west
unit :wizard, 611, 0, :west
unit :captive, 614, 0, :west
unit :archer, 615, 0, :west
unit :sludge, 617, 0, :west
unit :sludge, 620, 0, :west
unit :sludge, 621, 0, :west
unit :archer, 623, 0, :west
unit :sludge, 640, 0, :west
unit :archer, 641, 0, :west
unit :sludge, 643, 0, :west
unit :archer, 648, 0, :west
unit :captive, 651, 0, :west
unit :archer, 653, 0, :west
unit :captive, 657, 0, :west
unit :archer, 660, 0, :west
unit :archer, 669, 0, :west
unit :archer, 670, 0, :west
unit :captive, 671, 0, :west
unit :captive, 675, 0, :west
unit :wizard, 682, 0, :west
unit :captive, 684, 0, :west
unit :thick_sludge, 686, 0, :west
unit :thick_sludge, 690, 0, :west
unit :captive, 698, 0, :west
unit :archer, 699, 0, :west
unit :sludge, 700, 0, :west
unit :archer, 705, 0, :west
unit :sludge, 711, 0, :west
unit :sludge, 716, 0, :west
unit :captive, 721, 0, :west
unit :sludge, 732, 0, :west
unit :captive, 733, 0, :west
unit :thick_sludge, 737, 0, :west
unit :thick_sludge, 739, 0, :west
unit :captive, 743, 0, :west
unit :captive, 746, 0, :west
unit :archer, 749, 0, :west
unit :captive, 752, 0, :west
unit :sludge, 755, 0, :west
unit :wizard, 760, 0, :west
unit :archer, 772, 0, :west
unit :wizard, 776, 0, :west
unit :sludge, 779, 0, :west
unit :wizard, 785, 0, :west
unit :thick_sludge, 787, 0, :west
unit :thick_sludge, 791, 0, :west
unit :thick_sludge, 795, 0, :west
unit :captive, 796, 0, :west
unit :wizard, 798, 0, :west
unit :wizard, 805, 0, :west
unit :wizard, 813, 0, :west
unit :thick_sludge, 814, 0, :west
unit :sludge, 815, 0, :west
unit :archer, 822, 0, :west
unit :thick_sludge, 826, 0, :west
unit :thick_sludge, 829, 0, :west
unit :archer, 831, 0, :west
unit :sludge, 833, 0, :west
unit :archer, 841, 0, :west
unit :captive, 844, 0, :west
unit :thick_sludge, 845, 0, :west
unit :sludge, 846, 0, :west
unit :thick_sludge, 849, 0, :west
unit :sludge, 850, 0, :west
unit :captive, 852, 0, :west
unit :wizard, 857, 0, :west
unit :wizard, 863, 0, :west
unit :archer, 864, 0, :west
unit :archer, 867, 0, :west
unit :sludge, 871, 0, :west
unit :sludge, 874, 0, :west
unit :sludge, 876, 0, :west
