#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w    w   a  C   ss         a  a    a wS  s   S     S   Sa C  C s      ss        s w       sSw  a      S    a           CSs    C   S       w w S    a s C       w  sC S w s    C  a  a  Cs        a       ssw   s  C aa  s  a  w       a   a   C a   s          w aaa      w s CC a         s   Cw s  s  s  C    w S  S    s  @  s S  C      a   C s a      s      S    a       a       a w w  Ca                          S      w   w   a   s  S C  C  S C    C   w SCSasaS    s       S             C                a  a a w            w    Cs         w     S   C      S     C  S s     a  C C w   S Ss     Sa  Sa sSa    a    S     wC   S> a           C     a   C a   S        w         w a   s   a   SC     Ssa  a           w  a   S   Sa sa    w     a a C a      C  a    s        S   S       C  C    Sa     w   C    a      CC   w       SC    a   s  w     S  SC  Ss    s      S s    w   a  s w  s  aS      s     a  a C   C   sa   aS  sS s       C   a  a    CS   S          C  w s  C            w   w        C|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 994
ace_score 4970
size 994, 1
stairs 624, 0

warrior 317, 0, :east

unit :wizard, 0, 0, :east
unit :wizard, 5, 0, :east
unit :archer, 9, 0, :east
unit :captive, 12, 0, :east
unit :sludge, 16, 0, :east
unit :sludge, 17, 0, :east
unit :archer, 27, 0, :east
unit :archer, 30, 0, :east
unit :archer, 35, 0, :east
unit :wizard, 37, 0, :east
unit :thick_sludge, 38, 0, :east
unit :sludge, 41, 0, :east
unit :thick_sludge, 45, 0, :east
unit :thick_sludge, 51, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 56, 0, :east
unit :captive, 58, 0, :east
unit :captive, 61, 0, :east
unit :sludge, 63, 0, :east
unit :sludge, 70, 0, :east
unit :sludge, 71, 0, :east
unit :sludge, 80, 0, :east
unit :wizard, 82, 0, :east
unit :sludge, 90, 0, :east
unit :thick_sludge, 91, 0, :east
unit :wizard, 92, 0, :east
unit :archer, 95, 0, :east
unit :thick_sludge, 102, 0, :east
unit :archer, 107, 0, :east
unit :captive, 119, 0, :east
unit :thick_sludge, 120, 0, :east
unit :sludge, 121, 0, :east
unit :captive, 126, 0, :east
unit :thick_sludge, 130, 0, :east
unit :wizard, 138, 0, :east
unit :wizard, 140, 0, :east
unit :thick_sludge, 142, 0, :east
unit :archer, 147, 0, :east
unit :sludge, 149, 0, :east
unit :captive, 151, 0, :east
unit :wizard, 159, 0, :east
unit :sludge, 162, 0, :east
unit :captive, 163, 0, :east
unit :thick_sludge, 165, 0, :east
unit :wizard, 167, 0, :east
unit :sludge, 169, 0, :east
unit :captive, 174, 0, :east
unit :archer, 177, 0, :east
unit :archer, 180, 0, :east
unit :captive, 183, 0, :east
unit :sludge, 184, 0, :east
unit :archer, 193, 0, :east
unit :sludge, 201, 0, :east
unit :sludge, 202, 0, :east
unit :wizard, 203, 0, :east
unit :sludge, 207, 0, :east
unit :captive, 210, 0, :east
unit :archer, 212, 0, :east
unit :archer, 213, 0, :east
unit :sludge, 216, 0, :east
unit :archer, 219, 0, :east
unit :wizard, 222, 0, :east
unit :archer, 230, 0, :east
unit :archer, 234, 0, :east
unit :captive, 238, 0, :east
unit :archer, 240, 0, :east
unit :sludge, 244, 0, :east
unit :wizard, 255, 0, :east
unit :archer, 257, 0, :east
unit :archer, 258, 0, :east
unit :archer, 259, 0, :east
unit :wizard, 266, 0, :east
unit :sludge, 268, 0, :east
unit :captive, 270, 0, :east
unit :captive, 271, 0, :east
unit :archer, 273, 0, :east
unit :sludge, 283, 0, :east
unit :captive, 287, 0, :east
unit :wizard, 288, 0, :east
unit :sludge, 290, 0, :east
unit :sludge, 293, 0, :east
unit :sludge, 296, 0, :east
unit :captive, 299, 0, :east
unit :wizard, 304, 0, :east
unit :thick_sludge, 306, 0, :east
unit :thick_sludge, 309, 0, :east
unit :sludge, 314, 0, :east
unit :sludge, 320, 0, :west
unit :thick_sludge, 322, 0, :west
unit :captive, 325, 0, :west
unit :archer, 332, 0, :west
unit :captive, 336, 0, :west
unit :sludge, 338, 0, :west
unit :archer, 340, 0, :west
unit :sludge, 347, 0, :west
unit :thick_sludge, 354, 0, :west
unit :archer, 359, 0, :west
unit :archer, 367, 0, :west
unit :archer, 375, 0, :west
unit :wizard, 377, 0, :west
unit :wizard, 379, 0, :west
unit :captive, 382, 0, :west
unit :archer, 383, 0, :west
unit :thick_sludge, 410, 0, :west
unit :wizard, 417, 0, :west
unit :wizard, 421, 0, :west
unit :archer, 425, 0, :west
unit :sludge, 429, 0, :west
unit :thick_sludge, 432, 0, :west
unit :captive, 434, 0, :west
unit :captive, 437, 0, :west
unit :thick_sludge, 440, 0, :west
unit :captive, 442, 0, :west
unit :captive, 447, 0, :west
unit :wizard, 451, 0, :west
unit :thick_sludge, 453, 0, :west
unit :captive, 454, 0, :west
unit :thick_sludge, 455, 0, :west
unit :archer, 456, 0, :west
unit :sludge, 457, 0, :west
unit :archer, 458, 0, :west
unit :thick_sludge, 459, 0, :west
unit :sludge, 464, 0, :west
unit :thick_sludge, 472, 0, :west
unit :captive, 486, 0, :west
unit :archer, 503, 0, :west
unit :archer, 506, 0, :west
unit :archer, 508, 0, :west
unit :wizard, 510, 0, :west
unit :wizard, 523, 0, :west
unit :captive, 528, 0, :west
unit :sludge, 529, 0, :west
unit :wizard, 539, 0, :west
unit :thick_sludge, 545, 0, :west
unit :captive, 549, 0, :west
unit :thick_sludge, 556, 0, :west
unit :captive, 562, 0, :west
unit :thick_sludge, 565, 0, :west
unit :sludge, 567, 0, :west
unit :archer, 573, 0, :west
unit :captive, 576, 0, :west
unit :captive, 578, 0, :west
unit :wizard, 580, 0, :west
unit :thick_sludge, 584, 0, :west
unit :thick_sludge, 586, 0, :west
unit :sludge, 587, 0, :west
unit :thick_sludge, 593, 0, :west
unit :archer, 594, 0, :west
unit :thick_sludge, 597, 0, :west
unit :archer, 598, 0, :west
unit :sludge, 600, 0, :west
unit :thick_sludge, 601, 0, :west
unit :archer, 602, 0, :west
unit :archer, 607, 0, :west
unit :thick_sludge, 612, 0, :west
unit :wizard, 618, 0, :west
unit :captive, 619, 0, :west
unit :thick_sludge, 623, 0, :west
unit :archer, 626, 0, :west
unit :captive, 638, 0, :west
unit :archer, 644, 0, :west
unit :captive, 648, 0, :west
unit :archer, 650, 0, :west
unit :thick_sludge, 654, 0, :west
unit :wizard, 663, 0, :west
unit :wizard, 673, 0, :west
unit :archer, 675, 0, :west
unit :sludge, 679, 0, :west
unit :archer, 683, 0, :west
unit :thick_sludge, 687, 0, :west
unit :captive, 688, 0, :west
unit :thick_sludge, 694, 0, :west
unit :sludge, 695, 0, :west
unit :archer, 696, 0, :west
unit :archer, 699, 0, :west
unit :wizard, 711, 0, :west
unit :archer, 714, 0, :west
unit :thick_sludge, 718, 0, :west
unit :thick_sludge, 722, 0, :west
unit :archer, 723, 0, :west
unit :sludge, 725, 0, :west
unit :archer, 726, 0, :west
unit :wizard, 731, 0, :west
unit :archer, 737, 0, :west
unit :archer, 739, 0, :west
unit :captive, 741, 0, :west
unit :archer, 743, 0, :west
unit :captive, 750, 0, :west
unit :archer, 753, 0, :west
unit :sludge, 758, 0, :west
unit :thick_sludge, 767, 0, :west
unit :thick_sludge, 771, 0, :west
unit :captive, 779, 0, :west
unit :captive, 782, 0, :west
unit :thick_sludge, 787, 0, :west
unit :archer, 788, 0, :west
unit :wizard, 794, 0, :west
unit :captive, 798, 0, :west
unit :archer, 803, 0, :west
unit :captive, 810, 0, :west
unit :captive, 811, 0, :west
unit :wizard, 815, 0, :west
unit :thick_sludge, 823, 0, :west
unit :captive, 824, 0, :west
unit :archer, 829, 0, :west
unit :sludge, 833, 0, :west
unit :wizard, 836, 0, :west
unit :thick_sludge, 842, 0, :west
unit :thick_sludge, 845, 0, :west
unit :captive, 846, 0, :west
unit :thick_sludge, 849, 0, :west
unit :sludge, 850, 0, :west
unit :sludge, 855, 0, :west
unit :thick_sludge, 862, 0, :west
unit :sludge, 864, 0, :west
unit :wizard, 869, 0, :west
unit :archer, 873, 0, :west
unit :sludge, 876, 0, :west
unit :wizard, 878, 0, :west
unit :sludge, 881, 0, :west
unit :archer, 884, 0, :west
unit :thick_sludge, 885, 0, :west
unit :sludge, 892, 0, :west
unit :archer, 898, 0, :west
unit :archer, 901, 0, :west
unit :captive, 903, 0, :west
unit :captive, 907, 0, :west
unit :sludge, 911, 0, :west
unit :archer, 912, 0, :west
unit :archer, 916, 0, :west
unit :thick_sludge, 917, 0, :west
unit :sludge, 920, 0, :west
unit :thick_sludge, 921, 0, :west
unit :sludge, 923, 0, :west
unit :captive, 931, 0, :west
unit :archer, 935, 0, :west
unit :archer, 938, 0, :west
unit :captive, 943, 0, :west
unit :thick_sludge, 944, 0, :west
unit :thick_sludge, 948, 0, :west
unit :captive, 959, 0, :west
unit :wizard, 962, 0, :west
unit :sludge, 964, 0, :west
unit :captive, 967, 0, :west
unit :wizard, 980, 0, :west
unit :wizard, 984, 0, :west
unit :captive, 993, 0, :west
