#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     as     a    > C  C s  C          C s        s aC sC    S      aC a  S                sC      w    S sC      S C     s      CCCC ss       Csa C  wC   s         S   C       S                wS w   C  Ca w   C SsSsss       s  s  s w   C S  s  C  aa s  C  aa  s   C        a  C  s C     s C  a s           a   w   C    a a      S         s     w  S SSCw        w      Cs C  S       w   wsS   w    s   aa a  SS         s   C  C   w                w  S   s   a   C            C SS a    C     sa             a  a   S   S  @  s      S   aS S S     s   a  w   C   C    C     C     S    s    S   S w          aa w   SS s S           C a  a    w  C        |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 650
ace_score 3250
size 650, 1
stairs 17, 0

warrior 520, 0, :east

unit :archer, 5, 0, :east
unit :sludge, 6, 0, :east
unit :archer, 12, 0, :east
unit :captive, 19, 0, :east
unit :captive, 22, 0, :east
unit :sludge, 24, 0, :east
unit :captive, 27, 0, :east
unit :captive, 38, 0, :east
unit :sludge, 40, 0, :east
unit :sludge, 49, 0, :east
unit :archer, 51, 0, :east
unit :captive, 52, 0, :east
unit :sludge, 54, 0, :east
unit :captive, 55, 0, :east
unit :thick_sludge, 60, 0, :east
unit :archer, 67, 0, :east
unit :captive, 68, 0, :east
unit :archer, 70, 0, :east
unit :thick_sludge, 73, 0, :east
unit :sludge, 90, 0, :east
unit :captive, 91, 0, :east
unit :wizard, 98, 0, :east
unit :thick_sludge, 103, 0, :east
unit :sludge, 105, 0, :east
unit :captive, 106, 0, :east
unit :thick_sludge, 113, 0, :east
unit :captive, 115, 0, :east
unit :sludge, 121, 0, :east
unit :captive, 128, 0, :east
unit :captive, 129, 0, :east
unit :captive, 130, 0, :east
unit :captive, 131, 0, :east
unit :sludge, 133, 0, :east
unit :sludge, 134, 0, :east
unit :captive, 142, 0, :east
unit :sludge, 143, 0, :east
unit :archer, 144, 0, :east
unit :captive, 146, 0, :east
unit :wizard, 149, 0, :east
unit :captive, 150, 0, :east
unit :sludge, 154, 0, :east
unit :thick_sludge, 164, 0, :east
unit :captive, 168, 0, :east
unit :thick_sludge, 176, 0, :east
unit :wizard, 193, 0, :east
unit :thick_sludge, 194, 0, :east
unit :wizard, 196, 0, :east
unit :captive, 200, 0, :east
unit :captive, 203, 0, :east
unit :archer, 204, 0, :east
unit :wizard, 206, 0, :east
unit :captive, 210, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 213, 0, :east
unit :thick_sludge, 214, 0, :east
unit :sludge, 215, 0, :east
unit :sludge, 216, 0, :east
unit :sludge, 217, 0, :east
unit :sludge, 225, 0, :east
unit :sludge, 228, 0, :east
unit :sludge, 231, 0, :east
unit :wizard, 233, 0, :east
unit :captive, 237, 0, :east
unit :thick_sludge, 239, 0, :east
unit :sludge, 242, 0, :east
unit :captive, 245, 0, :east
unit :archer, 248, 0, :east
unit :archer, 249, 0, :east
unit :sludge, 251, 0, :east
unit :captive, 254, 0, :east
unit :archer, 257, 0, :east
unit :archer, 258, 0, :east
unit :sludge, 261, 0, :east
unit :captive, 265, 0, :east
unit :archer, 274, 0, :east
unit :captive, 277, 0, :east
unit :sludge, 280, 0, :east
unit :captive, 282, 0, :east
unit :sludge, 288, 0, :east
unit :captive, 290, 0, :east
unit :archer, 293, 0, :east
unit :sludge, 295, 0, :east
unit :archer, 307, 0, :east
unit :wizard, 311, 0, :east
unit :captive, 315, 0, :east
unit :archer, 320, 0, :east
unit :archer, 322, 0, :east
unit :thick_sludge, 329, 0, :east
unit :sludge, 339, 0, :east
unit :wizard, 345, 0, :east
unit :thick_sludge, 348, 0, :east
unit :thick_sludge, 350, 0, :east
unit :thick_sludge, 351, 0, :east
unit :captive, 352, 0, :east
unit :wizard, 353, 0, :east
unit :wizard, 362, 0, :east
unit :captive, 369, 0, :east
unit :sludge, 370, 0, :east
unit :captive, 372, 0, :east
unit :thick_sludge, 375, 0, :east
unit :wizard, 383, 0, :east
unit :wizard, 387, 0, :east
unit :sludge, 388, 0, :east
unit :thick_sludge, 389, 0, :east
unit :wizard, 393, 0, :east
unit :sludge, 398, 0, :east
unit :archer, 402, 0, :east
unit :archer, 403, 0, :east
unit :archer, 405, 0, :east
unit :thick_sludge, 408, 0, :east
unit :thick_sludge, 409, 0, :east
unit :sludge, 419, 0, :east
unit :captive, 423, 0, :east
unit :captive, 426, 0, :east
unit :wizard, 430, 0, :east
unit :wizard, 447, 0, :east
unit :thick_sludge, 450, 0, :east
unit :sludge, 454, 0, :east
unit :archer, 458, 0, :east
unit :captive, 462, 0, :east
unit :captive, 475, 0, :east
unit :thick_sludge, 477, 0, :east
unit :thick_sludge, 478, 0, :east
unit :archer, 480, 0, :east
unit :captive, 485, 0, :east
unit :sludge, 491, 0, :east
unit :archer, 492, 0, :east
unit :archer, 506, 0, :east
unit :archer, 509, 0, :east
unit :thick_sludge, 513, 0, :east
unit :thick_sludge, 517, 0, :east
unit :sludge, 523, 0, :west
unit :thick_sludge, 530, 0, :west
unit :archer, 534, 0, :west
unit :thick_sludge, 535, 0, :west
unit :thick_sludge, 537, 0, :west
unit :thick_sludge, 539, 0, :west
unit :sludge, 545, 0, :west
unit :archer, 549, 0, :west
unit :wizard, 552, 0, :west
unit :captive, 556, 0, :west
unit :captive, 560, 0, :west
unit :captive, 565, 0, :west
unit :captive, 571, 0, :west
unit :thick_sludge, 577, 0, :west
unit :sludge, 582, 0, :west
unit :thick_sludge, 587, 0, :west
unit :thick_sludge, 591, 0, :west
unit :wizard, 593, 0, :west
unit :archer, 604, 0, :west
unit :archer, 605, 0, :west
unit :wizard, 607, 0, :west
unit :thick_sludge, 611, 0, :west
unit :thick_sludge, 612, 0, :west
unit :sludge, 614, 0, :west
unit :thick_sludge, 616, 0, :west
unit :captive, 628, 0, :west
unit :archer, 630, 0, :west
unit :archer, 633, 0, :west
unit :wizard, 638, 0, :west
unit :captive, 641, 0, :west
