#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s      a a  s       C    C   S                      S  as   a C  C          C    C S C   >s w  w    SC  C                s     w    aCS                 aC    S   Ss    s  C   w  S  SC    C s     S C w  a            C w       w    a           C    a w     sa   S   wa sS     sCS   Ss    s  a  CC  w  s  C  s  C  w C    aS w   wsw C  as           S   S     C      a s   @    w   w          S   w      w       a S        C     ssSsCs s w         sS    C            ss      C   C              s  w s  a  ws    aC a  a  aa a CCC   a  aw Ca  CS S        s   Cw      S        s    sS   a a          C  w sS|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 601
ace_score 3005
size 601, 1
stairs 91, 0

warrior 370, 0, :east

unit :sludge, 2, 0, :east
unit :archer, 9, 0, :east
unit :archer, 11, 0, :east
unit :sludge, 14, 0, :east
unit :captive, 22, 0, :east
unit :captive, 27, 0, :east
unit :thick_sludge, 31, 0, :east
unit :thick_sludge, 54, 0, :east
unit :archer, 57, 0, :east
unit :sludge, 58, 0, :east
unit :archer, 62, 0, :east
unit :captive, 64, 0, :east
unit :captive, 67, 0, :east
unit :captive, 78, 0, :east
unit :captive, 83, 0, :east
unit :thick_sludge, 85, 0, :east
unit :captive, 87, 0, :east
unit :sludge, 92, 0, :east
unit :wizard, 94, 0, :east
unit :wizard, 97, 0, :east
unit :thick_sludge, 102, 0, :east
unit :captive, 103, 0, :east
unit :captive, 106, 0, :east
unit :sludge, 123, 0, :east
unit :wizard, 129, 0, :east
unit :archer, 134, 0, :east
unit :captive, 135, 0, :east
unit :thick_sludge, 136, 0, :east
unit :archer, 154, 0, :east
unit :captive, 155, 0, :east
unit :thick_sludge, 160, 0, :east
unit :thick_sludge, 164, 0, :east
unit :sludge, 165, 0, :east
unit :sludge, 170, 0, :east
unit :captive, 173, 0, :east
unit :wizard, 177, 0, :east
unit :thick_sludge, 180, 0, :east
unit :thick_sludge, 183, 0, :east
unit :captive, 184, 0, :east
unit :captive, 189, 0, :east
unit :sludge, 191, 0, :east
unit :thick_sludge, 197, 0, :east
unit :captive, 199, 0, :east
unit :wizard, 201, 0, :east
unit :archer, 204, 0, :east
unit :captive, 217, 0, :east
unit :wizard, 219, 0, :east
unit :wizard, 227, 0, :east
unit :archer, 232, 0, :east
unit :captive, 244, 0, :east
unit :archer, 249, 0, :east
unit :wizard, 251, 0, :east
unit :sludge, 257, 0, :east
unit :archer, 258, 0, :east
unit :thick_sludge, 262, 0, :east
unit :wizard, 266, 0, :east
unit :archer, 267, 0, :east
unit :sludge, 269, 0, :east
unit :thick_sludge, 270, 0, :east
unit :sludge, 276, 0, :east
unit :captive, 277, 0, :east
unit :thick_sludge, 278, 0, :east
unit :thick_sludge, 282, 0, :east
unit :sludge, 283, 0, :east
unit :sludge, 288, 0, :east
unit :archer, 291, 0, :east
unit :captive, 294, 0, :east
unit :captive, 295, 0, :east
unit :wizard, 298, 0, :east
unit :sludge, 301, 0, :east
unit :captive, 304, 0, :east
unit :sludge, 307, 0, :east
unit :captive, 310, 0, :east
unit :wizard, 313, 0, :east
unit :captive, 315, 0, :east
unit :archer, 320, 0, :east
unit :thick_sludge, 321, 0, :east
unit :wizard, 323, 0, :east
unit :wizard, 327, 0, :east
unit :sludge, 328, 0, :east
unit :wizard, 329, 0, :east
unit :captive, 331, 0, :east
unit :archer, 334, 0, :east
unit :sludge, 335, 0, :east
unit :thick_sludge, 347, 0, :east
unit :thick_sludge, 351, 0, :east
unit :captive, 357, 0, :east
unit :archer, 364, 0, :east
unit :sludge, 366, 0, :east
unit :wizard, 375, 0, :west
unit :wizard, 379, 0, :west
unit :thick_sludge, 390, 0, :west
unit :wizard, 394, 0, :west
unit :wizard, 401, 0, :west
unit :archer, 409, 0, :west
unit :thick_sludge, 411, 0, :west
unit :captive, 420, 0, :west
unit :sludge, 426, 0, :west
unit :sludge, 427, 0, :west
unit :thick_sludge, 428, 0, :west
unit :sludge, 429, 0, :west
unit :captive, 430, 0, :west
unit :sludge, 431, 0, :west
unit :sludge, 433, 0, :west
unit :wizard, 435, 0, :west
unit :sludge, 445, 0, :west
unit :thick_sludge, 446, 0, :west
unit :captive, 451, 0, :west
unit :sludge, 464, 0, :west
unit :sludge, 465, 0, :west
unit :captive, 472, 0, :west
unit :captive, 476, 0, :west
unit :sludge, 491, 0, :west
unit :wizard, 494, 0, :west
unit :sludge, 496, 0, :west
unit :archer, 499, 0, :west
unit :wizard, 502, 0, :west
unit :sludge, 503, 0, :west
unit :archer, 508, 0, :west
unit :captive, 509, 0, :west
unit :archer, 511, 0, :west
unit :archer, 514, 0, :west
unit :archer, 517, 0, :west
unit :archer, 518, 0, :west
unit :archer, 520, 0, :west
unit :captive, 522, 0, :west
unit :captive, 523, 0, :west
unit :captive, 524, 0, :west
unit :archer, 528, 0, :west
unit :archer, 531, 0, :west
unit :wizard, 532, 0, :west
unit :captive, 534, 0, :west
unit :archer, 535, 0, :west
unit :captive, 538, 0, :west
unit :thick_sludge, 539, 0, :west
unit :thick_sludge, 541, 0, :west
unit :sludge, 550, 0, :west
unit :captive, 554, 0, :west
unit :wizard, 555, 0, :west
unit :thick_sludge, 562, 0, :west
unit :sludge, 571, 0, :west
unit :sludge, 576, 0, :west
unit :thick_sludge, 577, 0, :west
unit :archer, 581, 0, :west
unit :archer, 583, 0, :west
unit :captive, 594, 0, :west
unit :wizard, 597, 0, :west
unit :sludge, 599, 0, :west
unit :thick_sludge, 600, 0, :west
