#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | s   sC      w S  aw s          aa            S         s  C  w    s    a s  s   s          C           s     s             S     s  s C S  s  a                    S        C C    Cw sa  a      aS       w       S      C  S      @    w       saCC s   w    s  S        CS   aa w s s Cs          sa  sC as  S   S   C     S   SC  wa   S    w CS         a  a sC   w    w   wSS S a Cs  sC  wS  s  C   s   w  C   S   aaC         w     C       C C   a  C  w                  sC  s CS>C w            a      Ss   a w a           a w           a w a       C   sC     Cw  S                   w s     C   S  S     C   sw  C    ssS      aa    Ca ws w  s  Sa CC C       w    aS    aC C a  s w sw sS          s        w a             C       s w   S        a a C  C      w  sS      s    s   a              aC    C       S       a     w CS  w     ss       S a s CCs    C   S               S  s s    a   w s S SSC s     Ss    S wS  SC  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 918
ace_score 4590
size 918, 1
stairs 475, 0

warrior 228, 0, :east

unit :sludge, 1, 0, :east
unit :sludge, 5, 0, :east
unit :captive, 6, 0, :east
unit :wizard, 13, 0, :east
unit :thick_sludge, 15, 0, :east
unit :archer, 18, 0, :east
unit :wizard, 19, 0, :east
unit :sludge, 21, 0, :east
unit :archer, 32, 0, :east
unit :archer, 33, 0, :east
unit :thick_sludge, 46, 0, :east
unit :sludge, 56, 0, :east
unit :captive, 59, 0, :east
unit :wizard, 62, 0, :east
unit :sludge, 67, 0, :east
unit :archer, 72, 0, :east
unit :sludge, 74, 0, :east
unit :sludge, 77, 0, :east
unit :sludge, 81, 0, :east
unit :captive, 92, 0, :east
unit :sludge, 104, 0, :east
unit :sludge, 110, 0, :east
unit :thick_sludge, 124, 0, :east
unit :sludge, 130, 0, :east
unit :sludge, 133, 0, :east
unit :captive, 135, 0, :east
unit :thick_sludge, 137, 0, :east
unit :sludge, 140, 0, :east
unit :archer, 143, 0, :east
unit :thick_sludge, 164, 0, :east
unit :captive, 173, 0, :east
unit :captive, 175, 0, :east
unit :captive, 180, 0, :east
unit :wizard, 181, 0, :east
unit :sludge, 183, 0, :east
unit :archer, 184, 0, :east
unit :archer, 187, 0, :east
unit :archer, 194, 0, :east
unit :thick_sludge, 195, 0, :east
unit :wizard, 203, 0, :east
unit :thick_sludge, 211, 0, :east
unit :captive, 218, 0, :east
unit :thick_sludge, 221, 0, :east
unit :wizard, 233, 0, :west
unit :sludge, 241, 0, :west
unit :archer, 242, 0, :west
unit :captive, 243, 0, :west
unit :captive, 244, 0, :west
unit :sludge, 246, 0, :west
unit :wizard, 250, 0, :west
unit :sludge, 255, 0, :west
unit :thick_sludge, 258, 0, :west
unit :captive, 267, 0, :west
unit :thick_sludge, 268, 0, :west
unit :archer, 272, 0, :west
unit :archer, 273, 0, :west
unit :wizard, 275, 0, :west
unit :sludge, 277, 0, :west
unit :sludge, 279, 0, :west
unit :captive, 281, 0, :west
unit :sludge, 282, 0, :west
unit :sludge, 293, 0, :west
unit :archer, 294, 0, :west
unit :sludge, 297, 0, :west
unit :captive, 298, 0, :west
unit :archer, 300, 0, :west
unit :sludge, 301, 0, :west
unit :thick_sludge, 304, 0, :west
unit :thick_sludge, 308, 0, :west
unit :captive, 312, 0, :west
unit :thick_sludge, 318, 0, :west
unit :thick_sludge, 322, 0, :west
unit :captive, 323, 0, :west
unit :wizard, 326, 0, :west
unit :archer, 327, 0, :west
unit :thick_sludge, 331, 0, :west
unit :wizard, 336, 0, :west
unit :captive, 338, 0, :west
unit :thick_sludge, 339, 0, :west
unit :archer, 349, 0, :west
unit :archer, 352, 0, :west
unit :sludge, 354, 0, :west
unit :captive, 355, 0, :west
unit :wizard, 359, 0, :west
unit :wizard, 364, 0, :west
unit :wizard, 368, 0, :west
unit :thick_sludge, 369, 0, :west
unit :thick_sludge, 370, 0, :west
unit :thick_sludge, 372, 0, :west
unit :archer, 374, 0, :west
unit :captive, 376, 0, :west
unit :sludge, 377, 0, :west
unit :sludge, 380, 0, :west
unit :captive, 381, 0, :west
unit :wizard, 384, 0, :west
unit :thick_sludge, 385, 0, :west
unit :sludge, 388, 0, :west
unit :captive, 391, 0, :west
unit :sludge, 395, 0, :west
unit :wizard, 399, 0, :west
unit :captive, 402, 0, :west
unit :thick_sludge, 406, 0, :west
unit :archer, 410, 0, :west
unit :archer, 411, 0, :west
unit :captive, 412, 0, :west
unit :wizard, 422, 0, :west
unit :captive, 428, 0, :west
unit :captive, 436, 0, :west
unit :captive, 438, 0, :west
unit :archer, 442, 0, :west
unit :captive, 445, 0, :west
unit :wizard, 448, 0, :west
unit :sludge, 467, 0, :west
unit :captive, 468, 0, :west
unit :sludge, 471, 0, :west
unit :captive, 473, 0, :west
unit :thick_sludge, 474, 0, :west
unit :captive, 476, 0, :west
unit :wizard, 478, 0, :west
unit :archer, 491, 0, :west
unit :thick_sludge, 498, 0, :west
unit :sludge, 499, 0, :west
unit :archer, 503, 0, :west
unit :wizard, 505, 0, :west
unit :archer, 507, 0, :west
unit :archer, 519, 0, :west
unit :wizard, 521, 0, :west
unit :archer, 533, 0, :west
unit :wizard, 535, 0, :west
unit :archer, 537, 0, :west
unit :captive, 545, 0, :west
unit :sludge, 549, 0, :west
unit :captive, 550, 0, :west
unit :captive, 556, 0, :west
unit :wizard, 557, 0, :west
unit :thick_sludge, 560, 0, :west
unit :wizard, 580, 0, :west
unit :sludge, 582, 0, :west
unit :captive, 588, 0, :west
unit :thick_sludge, 592, 0, :west
unit :thick_sludge, 595, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 605, 0, :west
unit :wizard, 606, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 614, 0, :west
unit :sludge, 615, 0, :west
unit :thick_sludge, 616, 0, :west
unit :archer, 623, 0, :west
unit :archer, 624, 0, :west
unit :captive, 629, 0, :west
unit :archer, 630, 0, :west
unit :wizard, 632, 0, :west
unit :sludge, 633, 0, :west
unit :wizard, 635, 0, :west
unit :sludge, 638, 0, :west
unit :thick_sludge, 641, 0, :west
unit :archer, 642, 0, :west
unit :captive, 644, 0, :west
unit :captive, 645, 0, :west
unit :captive, 647, 0, :west
unit :wizard, 655, 0, :west
unit :archer, 660, 0, :west
unit :thick_sludge, 661, 0, :west
unit :archer, 666, 0, :west
unit :captive, 667, 0, :west
unit :captive, 669, 0, :west
unit :archer, 671, 0, :west
unit :sludge, 674, 0, :west
unit :wizard, 676, 0, :west
unit :sludge, 678, 0, :west
unit :wizard, 679, 0, :west
unit :sludge, 681, 0, :west
unit :thick_sludge, 682, 0, :west
unit :sludge, 693, 0, :west
unit :wizard, 702, 0, :west
unit :archer, 704, 0, :west
unit :captive, 718, 0, :west
unit :sludge, 726, 0, :west
unit :wizard, 728, 0, :west
unit :thick_sludge, 732, 0, :west
unit :archer, 741, 0, :west
unit :archer, 743, 0, :west
unit :captive, 745, 0, :west
unit :captive, 748, 0, :west
unit :wizard, 755, 0, :west
unit :sludge, 758, 0, :west
unit :thick_sludge, 759, 0, :west
unit :sludge, 766, 0, :west
unit :sludge, 771, 0, :west
unit :archer, 775, 0, :west
unit :archer, 790, 0, :west
unit :captive, 791, 0, :west
unit :captive, 796, 0, :west
unit :thick_sludge, 804, 0, :west
unit :archer, 812, 0, :west
unit :wizard, 818, 0, :west
unit :captive, 820, 0, :west
unit :thick_sludge, 821, 0, :west
unit :wizard, 824, 0, :west
unit :sludge, 830, 0, :west
unit :sludge, 831, 0, :west
unit :thick_sludge, 839, 0, :west
unit :archer, 841, 0, :west
unit :sludge, 843, 0, :west
unit :captive, 845, 0, :west
unit :captive, 846, 0, :west
unit :sludge, 847, 0, :west
unit :captive, 852, 0, :west
unit :thick_sludge, 856, 0, :west
unit :thick_sludge, 872, 0, :west
unit :sludge, 875, 0, :west
unit :sludge, 877, 0, :west
unit :archer, 882, 0, :west
unit :wizard, 886, 0, :west
unit :sludge, 888, 0, :west
unit :thick_sludge, 890, 0, :west
unit :thick_sludge, 892, 0, :west
unit :thick_sludge, 893, 0, :west
unit :captive, 894, 0, :west
unit :sludge, 896, 0, :west
unit :thick_sludge, 902, 0, :west
unit :sludge, 903, 0, :west
unit :thick_sludge, 908, 0, :west
unit :wizard, 910, 0, :west
unit :thick_sludge, 911, 0, :west
unit :thick_sludge, 914, 0, :west
unit :captive, 915, 0, :west
