#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  S   Cs    s a     s C    a  sS     aa   s      s  a            s  S      S                   C     wSaS     as   C    w   a     s CC S S     S  s C   w C  w  S     aa        a    a  S S    w        w C   S aC S     w    S   w   S aSC     C    w  aS  SCa a s      w   >a   S     C   s            C  Ss     w  w    a     S     a ss ss          s    Sa w            s s  a           s    aSS      C    s S  a   S  w      w     a       ws     s S     sC  w    S  C   C      C  C      w  S       S          aS C    a  w       S aC      C  w      w   w                S C    w  s     s   w   s               C C   s S        w      w  S        SSw    sCa         SCCs  C C     CSC      S   S S     C  a   C     S   S   w S   s      aS      C           s  CS s          sC   wS   aa   C SC as  SC C w   CC  a  s    a SS              SCSC  w         a  S  a w     s     w     C     S      asS a a s     SSS   a  C   C C  @  sS   wa           C       sa  a s a  S      a  s      S   S  w   S|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 984
ace_score 4920
size 984, 1
stairs 269, 0

warrior 915, 0, :east

unit :thick_sludge, 2, 0, :east
unit :captive, 6, 0, :east
unit :sludge, 7, 0, :east
unit :sludge, 12, 0, :east
unit :archer, 14, 0, :east
unit :sludge, 20, 0, :east
unit :captive, 22, 0, :east
unit :archer, 27, 0, :east
unit :sludge, 30, 0, :east
unit :thick_sludge, 31, 0, :east
unit :archer, 37, 0, :east
unit :archer, 38, 0, :east
unit :sludge, 42, 0, :east
unit :sludge, 49, 0, :east
unit :archer, 52, 0, :east
unit :sludge, 65, 0, :east
unit :thick_sludge, 68, 0, :east
unit :thick_sludge, 75, 0, :east
unit :captive, 95, 0, :east
unit :wizard, 101, 0, :east
unit :thick_sludge, 102, 0, :east
unit :archer, 103, 0, :east
unit :thick_sludge, 104, 0, :east
unit :archer, 110, 0, :east
unit :sludge, 111, 0, :east
unit :captive, 115, 0, :east
unit :wizard, 120, 0, :east
unit :archer, 124, 0, :east
unit :sludge, 130, 0, :east
unit :captive, 132, 0, :east
unit :captive, 133, 0, :east
unit :thick_sludge, 135, 0, :east
unit :thick_sludge, 137, 0, :east
unit :thick_sludge, 143, 0, :east
unit :sludge, 146, 0, :east
unit :captive, 148, 0, :east
unit :wizard, 152, 0, :east
unit :captive, 154, 0, :east
unit :wizard, 157, 0, :east
unit :thick_sludge, 160, 0, :east
unit :archer, 166, 0, :east
unit :archer, 167, 0, :east
unit :archer, 176, 0, :east
unit :archer, 181, 0, :east
unit :thick_sludge, 184, 0, :east
unit :thick_sludge, 186, 0, :east
unit :wizard, 191, 0, :east
unit :wizard, 200, 0, :east
unit :captive, 202, 0, :east
unit :thick_sludge, 206, 0, :east
unit :archer, 208, 0, :east
unit :captive, 209, 0, :east
unit :thick_sludge, 211, 0, :east
unit :wizard, 217, 0, :east
unit :thick_sludge, 222, 0, :east
unit :wizard, 226, 0, :east
unit :thick_sludge, 230, 0, :east
unit :archer, 232, 0, :east
unit :thick_sludge, 233, 0, :east
unit :captive, 234, 0, :east
unit :captive, 240, 0, :east
unit :wizard, 245, 0, :east
unit :archer, 248, 0, :east
unit :thick_sludge, 249, 0, :east
unit :thick_sludge, 252, 0, :east
unit :captive, 253, 0, :east
unit :archer, 254, 0, :east
unit :archer, 256, 0, :east
unit :sludge, 258, 0, :east
unit :wizard, 265, 0, :east
unit :archer, 270, 0, :east
unit :thick_sludge, 274, 0, :east
unit :captive, 280, 0, :east
unit :sludge, 284, 0, :east
unit :captive, 297, 0, :east
unit :thick_sludge, 300, 0, :east
unit :sludge, 301, 0, :east
unit :wizard, 307, 0, :east
unit :wizard, 310, 0, :east
unit :archer, 315, 0, :east
unit :thick_sludge, 321, 0, :east
unit :archer, 327, 0, :east
unit :sludge, 329, 0, :east
unit :sludge, 330, 0, :east
unit :sludge, 332, 0, :east
unit :sludge, 333, 0, :east
unit :sludge, 344, 0, :east
unit :thick_sludge, 349, 0, :east
unit :archer, 350, 0, :east
unit :wizard, 352, 0, :east
unit :sludge, 365, 0, :east
unit :sludge, 367, 0, :east
unit :archer, 370, 0, :east
unit :sludge, 382, 0, :east
unit :archer, 387, 0, :east
unit :thick_sludge, 388, 0, :east
unit :thick_sludge, 389, 0, :east
unit :captive, 396, 0, :east
unit :sludge, 401, 0, :east
unit :thick_sludge, 403, 0, :east
unit :archer, 406, 0, :east
unit :thick_sludge, 410, 0, :east
unit :wizard, 413, 0, :east
unit :wizard, 420, 0, :east
unit :archer, 426, 0, :east
unit :wizard, 434, 0, :east
unit :sludge, 435, 0, :east
unit :sludge, 441, 0, :east
unit :thick_sludge, 443, 0, :east
unit :sludge, 449, 0, :east
unit :captive, 450, 0, :east
unit :wizard, 453, 0, :east
unit :thick_sludge, 458, 0, :east
unit :captive, 461, 0, :east
unit :captive, 465, 0, :east
unit :captive, 472, 0, :east
unit :captive, 475, 0, :east
unit :wizard, 482, 0, :east
unit :thick_sludge, 485, 0, :east
unit :thick_sludge, 493, 0, :east
unit :archer, 504, 0, :east
unit :thick_sludge, 505, 0, :east
unit :captive, 507, 0, :east
unit :archer, 512, 0, :east
unit :wizard, 515, 0, :east
unit :thick_sludge, 523, 0, :east
unit :archer, 525, 0, :east
unit :captive, 526, 0, :east
unit :captive, 533, 0, :east
unit :wizard, 536, 0, :east
unit :wizard, 543, 0, :east
unit :wizard, 547, 0, :east
unit :thick_sludge, 564, 0, :east
unit :captive, 566, 0, :east
unit :wizard, 571, 0, :east
unit :sludge, 574, 0, :east
unit :sludge, 580, 0, :east
unit :wizard, 584, 0, :east
unit :sludge, 588, 0, :east
unit :captive, 604, 0, :east
unit :captive, 606, 0, :east
unit :sludge, 610, 0, :east
unit :thick_sludge, 612, 0, :east
unit :wizard, 621, 0, :east
unit :wizard, 628, 0, :east
unit :thick_sludge, 631, 0, :east
unit :thick_sludge, 640, 0, :east
unit :thick_sludge, 641, 0, :east
unit :wizard, 642, 0, :east
unit :sludge, 647, 0, :east
unit :captive, 648, 0, :east
unit :archer, 649, 0, :east
unit :thick_sludge, 659, 0, :east
unit :captive, 660, 0, :east
unit :captive, 661, 0, :east
unit :sludge, 662, 0, :east
unit :captive, 665, 0, :east
unit :captive, 667, 0, :east
unit :captive, 673, 0, :east
unit :thick_sludge, 674, 0, :east
unit :captive, 675, 0, :east
unit :thick_sludge, 682, 0, :east
unit :thick_sludge, 686, 0, :east
unit :thick_sludge, 688, 0, :east
unit :captive, 694, 0, :east
unit :archer, 697, 0, :east
unit :captive, 701, 0, :east
unit :thick_sludge, 707, 0, :east
unit :thick_sludge, 711, 0, :east
unit :wizard, 715, 0, :east
unit :thick_sludge, 717, 0, :east
unit :sludge, 721, 0, :east
unit :archer, 728, 0, :east
unit :thick_sludge, 729, 0, :east
unit :captive, 736, 0, :east
unit :sludge, 748, 0, :east
unit :captive, 751, 0, :east
unit :thick_sludge, 752, 0, :east
unit :sludge, 754, 0, :east
unit :sludge, 765, 0, :east
unit :captive, 766, 0, :east
unit :wizard, 770, 0, :east
unit :thick_sludge, 771, 0, :east
unit :archer, 775, 0, :east
unit :archer, 776, 0, :east
unit :captive, 780, 0, :east
unit :thick_sludge, 782, 0, :east
unit :captive, 783, 0, :east
unit :archer, 785, 0, :east
unit :sludge, 786, 0, :east
unit :thick_sludge, 789, 0, :east
unit :captive, 790, 0, :east
unit :captive, 792, 0, :east
unit :wizard, 794, 0, :east
unit :captive, 798, 0, :east
unit :captive, 799, 0, :east
unit :archer, 802, 0, :east
unit :sludge, 805, 0, :east
unit :archer, 810, 0, :east
unit :thick_sludge, 812, 0, :east
unit :thick_sludge, 813, 0, :east
unit :thick_sludge, 828, 0, :east
unit :captive, 829, 0, :east
unit :thick_sludge, 830, 0, :east
unit :captive, 831, 0, :east
unit :wizard, 834, 0, :east
unit :archer, 844, 0, :east
unit :thick_sludge, 847, 0, :east
unit :archer, 850, 0, :east
unit :wizard, 852, 0, :east
unit :sludge, 858, 0, :east
unit :wizard, 864, 0, :east
unit :captive, 870, 0, :east
unit :thick_sludge, 876, 0, :east
unit :archer, 883, 0, :east
unit :sludge, 884, 0, :east
unit :thick_sludge, 885, 0, :east
unit :archer, 887, 0, :east
unit :archer, 889, 0, :east
unit :sludge, 891, 0, :east
unit :thick_sludge, 897, 0, :east
unit :thick_sludge, 898, 0, :east
unit :thick_sludge, 899, 0, :east
unit :archer, 903, 0, :east
unit :captive, 906, 0, :east
unit :captive, 910, 0, :east
unit :captive, 912, 0, :east
unit :sludge, 918, 0, :west
unit :thick_sludge, 919, 0, :west
unit :wizard, 923, 0, :west
unit :archer, 924, 0, :west
unit :captive, 936, 0, :west
unit :sludge, 944, 0, :west
unit :archer, 945, 0, :west
unit :archer, 948, 0, :west
unit :sludge, 950, 0, :west
unit :archer, 952, 0, :west
unit :thick_sludge, 955, 0, :west
unit :archer, 962, 0, :west
unit :sludge, 965, 0, :west
unit :thick_sludge, 972, 0, :west
unit :thick_sludge, 976, 0, :west
unit :wizard, 979, 0, :west
unit :thick_sludge, 983, 0, :west
