#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  aC  s     C       aC Cw w   s  w s        s   s  Cw        a       ss           aS S           C S   S    C       S   S  a  w    w          aSsC      s                  C        C   C  aC     S C      S C CCC S      S    SCa w s     C  C      a    C w  w    saC     w  w  w   s     w  S  s w       S  >   s   a  a   C             @       a a         a    w    Cw s   S   w S      Cw  S     w        C w a   a S C   w  w w    swC swS  a  ss a  S a       w S S           C C aC s                        a C S  ssS   aa   C    C  a     a   s  s  C     wS w         Cs w s    a    a   s     s  w a Sa w C  s s      C         a    s   S        S  w    s    sa C a w  C   s    a     sCS       C       a   CS  sa S  s             a a       w |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 737
ace_score 3685
size 737, 1
stairs 303, 0

warrior 332, 0, :east

unit :archer, 2, 0, :east
unit :captive, 3, 0, :east
unit :sludge, 6, 0, :east
unit :captive, 12, 0, :east
unit :archer, 20, 0, :east
unit :captive, 21, 0, :east
unit :captive, 23, 0, :east
unit :wizard, 24, 0, :east
unit :wizard, 26, 0, :east
unit :sludge, 30, 0, :east
unit :wizard, 33, 0, :east
unit :sludge, 35, 0, :east
unit :sludge, 44, 0, :east
unit :sludge, 48, 0, :east
unit :captive, 51, 0, :east
unit :wizard, 52, 0, :east
unit :archer, 61, 0, :east
unit :sludge, 69, 0, :east
unit :sludge, 70, 0, :east
unit :archer, 82, 0, :east
unit :thick_sludge, 83, 0, :east
unit :thick_sludge, 85, 0, :east
unit :captive, 97, 0, :east
unit :thick_sludge, 99, 0, :east
unit :thick_sludge, 103, 0, :east
unit :captive, 108, 0, :east
unit :thick_sludge, 116, 0, :east
unit :thick_sludge, 120, 0, :east
unit :archer, 123, 0, :east
unit :wizard, 126, 0, :east
unit :wizard, 131, 0, :east
unit :archer, 142, 0, :east
unit :thick_sludge, 143, 0, :east
unit :sludge, 144, 0, :east
unit :captive, 145, 0, :east
unit :sludge, 152, 0, :east
unit :captive, 171, 0, :east
unit :captive, 180, 0, :east
unit :captive, 184, 0, :east
unit :archer, 187, 0, :east
unit :captive, 188, 0, :east
unit :thick_sludge, 194, 0, :east
unit :captive, 196, 0, :east
unit :thick_sludge, 203, 0, :east
unit :captive, 205, 0, :east
unit :captive, 207, 0, :east
unit :captive, 208, 0, :east
unit :captive, 209, 0, :east
unit :thick_sludge, 211, 0, :east
unit :thick_sludge, 218, 0, :east
unit :thick_sludge, 223, 0, :east
unit :captive, 224, 0, :east
unit :archer, 225, 0, :east
unit :wizard, 227, 0, :east
unit :sludge, 229, 0, :east
unit :captive, 235, 0, :east
unit :captive, 238, 0, :east
unit :archer, 245, 0, :east
unit :captive, 250, 0, :east
unit :wizard, 252, 0, :east
unit :wizard, 255, 0, :east
unit :sludge, 260, 0, :east
unit :archer, 261, 0, :east
unit :captive, 262, 0, :east
unit :wizard, 268, 0, :east
unit :wizard, 271, 0, :east
unit :wizard, 274, 0, :east
unit :sludge, 278, 0, :east
unit :wizard, 284, 0, :east
unit :thick_sludge, 287, 0, :east
unit :sludge, 290, 0, :east
unit :wizard, 292, 0, :east
unit :thick_sludge, 300, 0, :east
unit :sludge, 307, 0, :east
unit :archer, 311, 0, :east
unit :archer, 314, 0, :east
unit :captive, 318, 0, :east
unit :archer, 340, 0, :west
unit :archer, 342, 0, :west
unit :archer, 352, 0, :west
unit :wizard, 357, 0, :west
unit :captive, 362, 0, :west
unit :wizard, 363, 0, :west
unit :sludge, 365, 0, :west
unit :thick_sludge, 369, 0, :west
unit :wizard, 373, 0, :west
unit :thick_sludge, 375, 0, :west
unit :captive, 382, 0, :west
unit :wizard, 383, 0, :west
unit :thick_sludge, 386, 0, :west
unit :wizard, 392, 0, :west
unit :captive, 401, 0, :west
unit :wizard, 403, 0, :west
unit :archer, 405, 0, :west
unit :archer, 409, 0, :west
unit :thick_sludge, 411, 0, :west
unit :captive, 413, 0, :west
unit :wizard, 417, 0, :west
unit :wizard, 420, 0, :west
unit :wizard, 422, 0, :west
unit :sludge, 427, 0, :west
unit :wizard, 428, 0, :west
unit :captive, 429, 0, :west
unit :sludge, 431, 0, :west
unit :wizard, 432, 0, :west
unit :thick_sludge, 433, 0, :west
unit :archer, 436, 0, :west
unit :sludge, 439, 0, :west
unit :sludge, 440, 0, :west
unit :archer, 442, 0, :west
unit :thick_sludge, 445, 0, :west
unit :archer, 447, 0, :west
unit :wizard, 455, 0, :west
unit :thick_sludge, 457, 0, :west
unit :thick_sludge, 459, 0, :west
unit :captive, 471, 0, :west
unit :captive, 473, 0, :west
unit :archer, 475, 0, :west
unit :captive, 476, 0, :west
unit :sludge, 478, 0, :west
unit :archer, 503, 0, :west
unit :captive, 505, 0, :west
unit :thick_sludge, 507, 0, :west
unit :sludge, 510, 0, :west
unit :sludge, 511, 0, :west
unit :thick_sludge, 512, 0, :west
unit :archer, 516, 0, :west
unit :archer, 517, 0, :west
unit :captive, 521, 0, :west
unit :captive, 526, 0, :west
unit :archer, 529, 0, :west
unit :archer, 535, 0, :west
unit :sludge, 539, 0, :west
unit :sludge, 542, 0, :west
unit :captive, 545, 0, :west
unit :wizard, 551, 0, :west
unit :thick_sludge, 552, 0, :west
unit :wizard, 554, 0, :west
unit :captive, 564, 0, :west
unit :sludge, 565, 0, :west
unit :wizard, 567, 0, :west
unit :sludge, 569, 0, :west
unit :archer, 574, 0, :west
unit :archer, 579, 0, :west
unit :sludge, 583, 0, :west
unit :sludge, 589, 0, :west
unit :wizard, 592, 0, :west
unit :archer, 594, 0, :west
unit :thick_sludge, 596, 0, :west
unit :archer, 597, 0, :west
unit :wizard, 599, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 604, 0, :west
unit :sludge, 606, 0, :west
unit :captive, 613, 0, :west
unit :archer, 623, 0, :west
unit :sludge, 628, 0, :west
unit :thick_sludge, 632, 0, :west
unit :thick_sludge, 641, 0, :west
unit :wizard, 644, 0, :west
unit :sludge, 649, 0, :west
unit :sludge, 654, 0, :west
unit :archer, 655, 0, :west
unit :captive, 657, 0, :west
unit :archer, 659, 0, :west
unit :wizard, 661, 0, :west
unit :captive, 664, 0, :west
unit :sludge, 668, 0, :west
unit :archer, 673, 0, :west
unit :sludge, 679, 0, :west
unit :captive, 680, 0, :west
unit :thick_sludge, 681, 0, :west
unit :captive, 689, 0, :west
unit :archer, 697, 0, :west
unit :captive, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :sludge, 705, 0, :west
unit :archer, 706, 0, :west
unit :thick_sludge, 708, 0, :west
unit :sludge, 711, 0, :west
unit :archer, 725, 0, :west
unit :archer, 727, 0, :west
unit :wizard, 735, 0, :west
