#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |a     s S    S    C        C     wS           s  w sw  Sa     C             a  saa    wsa  w         w    C  s            s  @    sa             sw  s        S    C         C        s   a    C       a sSCC    w  CC   S aSC Cw      C C    wC C a    C        aC   s     s  s w a   a    Ss   s  Sa         C  w S          w         s>     s      C  S    a    SsC    S   aC     S  w         C C  S Sa  s   w           S                       wS       Sa         CC     a        SC   aC    aw     C  w S S  s   aS w   C   a  S  w       S wa  S   w    w     a                  aC         s      C    S    C ssa   w    Cs a S       a  Cs    w           sw     s aCC   sS   w           w    Ca   S   aC C S      C     w aC  Cs CS S a  C s C s  aSa  C   s a   sa      sa  C    a w    C     as  C  S  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 791
ace_score 3955
size 791, 1
stairs 330, 0

warrior 125, 0, :east

unit :archer, 0, 0, :east
unit :sludge, 6, 0, :east
unit :thick_sludge, 8, 0, :east
unit :thick_sludge, 13, 0, :east
unit :captive, 18, 0, :east
unit :captive, 27, 0, :east
unit :wizard, 33, 0, :east
unit :thick_sludge, 34, 0, :east
unit :sludge, 46, 0, :east
unit :wizard, 49, 0, :east
unit :sludge, 51, 0, :east
unit :wizard, 52, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 56, 0, :east
unit :captive, 62, 0, :east
unit :archer, 76, 0, :east
unit :sludge, 79, 0, :east
unit :archer, 80, 0, :east
unit :archer, 81, 0, :east
unit :wizard, 86, 0, :east
unit :sludge, 87, 0, :east
unit :archer, 88, 0, :east
unit :wizard, 91, 0, :east
unit :wizard, 101, 0, :east
unit :captive, 106, 0, :east
unit :sludge, 109, 0, :east
unit :sludge, 122, 0, :east
unit :sludge, 130, 0, :west
unit :archer, 131, 0, :west
unit :sludge, 145, 0, :west
unit :wizard, 146, 0, :west
unit :sludge, 149, 0, :west
unit :thick_sludge, 158, 0, :west
unit :captive, 163, 0, :west
unit :captive, 173, 0, :west
unit :sludge, 182, 0, :west
unit :archer, 186, 0, :west
unit :captive, 191, 0, :west
unit :archer, 199, 0, :west
unit :sludge, 201, 0, :west
unit :thick_sludge, 202, 0, :west
unit :captive, 203, 0, :west
unit :captive, 204, 0, :west
unit :wizard, 209, 0, :west
unit :captive, 212, 0, :west
unit :captive, 213, 0, :west
unit :thick_sludge, 217, 0, :west
unit :archer, 219, 0, :west
unit :thick_sludge, 220, 0, :west
unit :captive, 221, 0, :west
unit :captive, 223, 0, :west
unit :wizard, 224, 0, :west
unit :captive, 231, 0, :west
unit :captive, 233, 0, :west
unit :wizard, 238, 0, :west
unit :captive, 239, 0, :west
unit :captive, 241, 0, :west
unit :archer, 243, 0, :west
unit :captive, 248, 0, :west
unit :archer, 257, 0, :west
unit :captive, 258, 0, :west
unit :sludge, 262, 0, :west
unit :sludge, 268, 0, :west
unit :sludge, 271, 0, :west
unit :wizard, 273, 0, :west
unit :archer, 275, 0, :west
unit :archer, 279, 0, :west
unit :thick_sludge, 284, 0, :west
unit :sludge, 285, 0, :west
unit :sludge, 289, 0, :west
unit :thick_sludge, 292, 0, :west
unit :archer, 293, 0, :west
unit :captive, 303, 0, :west
unit :wizard, 306, 0, :west
unit :thick_sludge, 308, 0, :west
unit :wizard, 319, 0, :west
unit :sludge, 329, 0, :west
unit :sludge, 336, 0, :west
unit :captive, 343, 0, :west
unit :thick_sludge, 346, 0, :west
unit :archer, 351, 0, :west
unit :thick_sludge, 356, 0, :west
unit :sludge, 357, 0, :west
unit :captive, 358, 0, :west
unit :thick_sludge, 363, 0, :west
unit :archer, 367, 0, :west
unit :captive, 368, 0, :west
unit :thick_sludge, 374, 0, :west
unit :wizard, 377, 0, :west
unit :captive, 387, 0, :west
unit :captive, 389, 0, :west
unit :thick_sludge, 392, 0, :west
unit :thick_sludge, 394, 0, :west
unit :archer, 395, 0, :west
unit :sludge, 398, 0, :west
unit :wizard, 402, 0, :west
unit :thick_sludge, 414, 0, :west
unit :wizard, 438, 0, :west
unit :thick_sludge, 439, 0, :west
unit :thick_sludge, 447, 0, :west
unit :archer, 448, 0, :west
unit :captive, 458, 0, :west
unit :captive, 459, 0, :west
unit :archer, 465, 0, :west
unit :thick_sludge, 474, 0, :west
unit :captive, 475, 0, :west
unit :archer, 479, 0, :west
unit :captive, 480, 0, :west
unit :archer, 485, 0, :west
unit :wizard, 486, 0, :west
unit :captive, 492, 0, :west
unit :wizard, 495, 0, :west
unit :thick_sludge, 497, 0, :west
unit :thick_sludge, 499, 0, :west
unit :sludge, 502, 0, :west
unit :archer, 506, 0, :west
unit :thick_sludge, 507, 0, :west
unit :wizard, 509, 0, :west
unit :captive, 513, 0, :west
unit :archer, 517, 0, :west
unit :thick_sludge, 520, 0, :west
unit :wizard, 523, 0, :west
unit :thick_sludge, 531, 0, :west
unit :wizard, 533, 0, :west
unit :archer, 534, 0, :west
unit :thick_sludge, 537, 0, :west
unit :wizard, 541, 0, :west
unit :wizard, 546, 0, :west
unit :archer, 552, 0, :west
unit :archer, 571, 0, :west
unit :captive, 572, 0, :west
unit :sludge, 582, 0, :west
unit :captive, 589, 0, :west
unit :thick_sludge, 594, 0, :west
unit :captive, 599, 0, :west
unit :sludge, 601, 0, :west
unit :sludge, 602, 0, :west
unit :archer, 603, 0, :west
unit :wizard, 607, 0, :west
unit :captive, 612, 0, :west
unit :sludge, 613, 0, :west
unit :archer, 615, 0, :west
unit :thick_sludge, 617, 0, :west
unit :archer, 625, 0, :west
unit :captive, 628, 0, :west
unit :sludge, 629, 0, :west
unit :wizard, 634, 0, :west
unit :sludge, 646, 0, :west
unit :wizard, 647, 0, :west
unit :sludge, 653, 0, :west
unit :archer, 655, 0, :west
unit :captive, 656, 0, :west
unit :captive, 657, 0, :west
unit :sludge, 661, 0, :west
unit :thick_sludge, 662, 0, :west
unit :wizard, 666, 0, :west
unit :wizard, 678, 0, :west
unit :captive, 683, 0, :west
unit :archer, 684, 0, :west
unit :thick_sludge, 688, 0, :west
unit :archer, 692, 0, :west
unit :captive, 693, 0, :west
unit :captive, 695, 0, :west
unit :thick_sludge, 697, 0, :west
unit :captive, 704, 0, :west
unit :wizard, 710, 0, :west
unit :archer, 712, 0, :west
unit :captive, 713, 0, :west
unit :captive, 716, 0, :west
unit :sludge, 717, 0, :west
unit :captive, 719, 0, :west
unit :thick_sludge, 720, 0, :west
unit :thick_sludge, 722, 0, :west
unit :archer, 724, 0, :west
unit :captive, 727, 0, :west
unit :sludge, 729, 0, :west
unit :captive, 731, 0, :west
unit :sludge, 733, 0, :west
unit :archer, 736, 0, :west
unit :thick_sludge, 737, 0, :west
unit :archer, 738, 0, :west
unit :captive, 741, 0, :west
unit :sludge, 745, 0, :west
unit :archer, 747, 0, :west
unit :sludge, 751, 0, :west
unit :archer, 752, 0, :west
unit :sludge, 759, 0, :west
unit :archer, 760, 0, :west
unit :captive, 763, 0, :west
unit :archer, 768, 0, :west
unit :wizard, 770, 0, :west
unit :captive, 775, 0, :west
unit :archer, 781, 0, :west
unit :sludge, 782, 0, :west
unit :captive, 785, 0, :west
unit :thick_sludge, 788, 0, :west
