#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       w     w   s   s      S a a w     a  a >  aa    S S    s     w  C        w     S     C       w   aSCS   a SCa       a w  S a    a         Cs    s wa     w  Sa    SC C         w   C       w   w  w S w  w   s w   a    s            s C    C    Cs           S       S  C C     C a    w  swsw     s   CCCa s    S              a    S S  s S    S w       w  sC w a C     Ss   a      a         C       s      SsS S    a   C   C w  SS  C     C    s a                    sS C s  a S        sa     a  SC S   wS   S     C CS saS s s  w     w  @     sa                        Cw    Sa      S     w  |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 592
ace_score 2960
size 592, 1
stairs 45, 0

warrior 537, 0, :east

unit :wizard, 7, 0, :east
unit :wizard, 13, 0, :east
unit :sludge, 17, 0, :east
unit :sludge, 21, 0, :east
unit :thick_sludge, 28, 0, :east
unit :archer, 30, 0, :east
unit :archer, 32, 0, :east
unit :wizard, 34, 0, :east
unit :archer, 40, 0, :east
unit :archer, 43, 0, :east
unit :archer, 48, 0, :east
unit :archer, 49, 0, :east
unit :thick_sludge, 54, 0, :east
unit :thick_sludge, 56, 0, :east
unit :sludge, 61, 0, :east
unit :wizard, 67, 0, :east
unit :captive, 70, 0, :east
unit :wizard, 79, 0, :east
unit :thick_sludge, 85, 0, :east
unit :captive, 91, 0, :east
unit :wizard, 99, 0, :east
unit :archer, 103, 0, :east
unit :thick_sludge, 104, 0, :east
unit :captive, 105, 0, :east
unit :thick_sludge, 106, 0, :east
unit :archer, 110, 0, :east
unit :thick_sludge, 112, 0, :east
unit :captive, 113, 0, :east
unit :archer, 114, 0, :east
unit :archer, 122, 0, :east
unit :wizard, 124, 0, :east
unit :thick_sludge, 127, 0, :east
unit :archer, 129, 0, :east
unit :archer, 134, 0, :east
unit :captive, 144, 0, :east
unit :sludge, 145, 0, :east
unit :sludge, 150, 0, :east
unit :wizard, 152, 0, :east
unit :archer, 153, 0, :east
unit :wizard, 159, 0, :east
unit :thick_sludge, 162, 0, :east
unit :archer, 163, 0, :east
unit :thick_sludge, 168, 0, :east
unit :captive, 169, 0, :east
unit :captive, 171, 0, :east
unit :wizard, 181, 0, :east
unit :captive, 185, 0, :east
unit :wizard, 193, 0, :east
unit :wizard, 197, 0, :east
unit :wizard, 200, 0, :east
unit :thick_sludge, 202, 0, :east
unit :wizard, 204, 0, :east
unit :wizard, 207, 0, :east
unit :sludge, 211, 0, :east
unit :wizard, 213, 0, :east
unit :archer, 217, 0, :east
unit :sludge, 222, 0, :east
unit :sludge, 235, 0, :east
unit :captive, 237, 0, :east
unit :captive, 242, 0, :east
unit :captive, 247, 0, :east
unit :sludge, 248, 0, :east
unit :thick_sludge, 260, 0, :east
unit :thick_sludge, 268, 0, :east
unit :captive, 271, 0, :east
unit :captive, 273, 0, :east
unit :captive, 279, 0, :east
unit :archer, 281, 0, :east
unit :wizard, 286, 0, :east
unit :sludge, 289, 0, :east
unit :wizard, 290, 0, :east
unit :sludge, 291, 0, :east
unit :wizard, 292, 0, :east
unit :sludge, 298, 0, :east
unit :captive, 302, 0, :east
unit :captive, 303, 0, :east
unit :captive, 304, 0, :east
unit :archer, 305, 0, :east
unit :sludge, 307, 0, :east
unit :thick_sludge, 312, 0, :east
unit :archer, 327, 0, :east
unit :thick_sludge, 332, 0, :east
unit :thick_sludge, 334, 0, :east
unit :sludge, 337, 0, :east
unit :thick_sludge, 339, 0, :east
unit :thick_sludge, 344, 0, :east
unit :wizard, 346, 0, :east
unit :wizard, 354, 0, :east
unit :sludge, 357, 0, :east
unit :captive, 358, 0, :east
unit :wizard, 360, 0, :east
unit :archer, 362, 0, :east
unit :captive, 364, 0, :east
unit :thick_sludge, 370, 0, :east
unit :sludge, 371, 0, :east
unit :archer, 375, 0, :east
unit :archer, 382, 0, :east
unit :captive, 392, 0, :east
unit :sludge, 400, 0, :east
unit :thick_sludge, 407, 0, :east
unit :sludge, 408, 0, :east
unit :thick_sludge, 409, 0, :east
unit :thick_sludge, 411, 0, :east
unit :archer, 416, 0, :east
unit :captive, 420, 0, :east
unit :captive, 424, 0, :east
unit :wizard, 426, 0, :east
unit :thick_sludge, 429, 0, :east
unit :thick_sludge, 430, 0, :east
unit :captive, 433, 0, :east
unit :captive, 439, 0, :east
unit :sludge, 444, 0, :east
unit :archer, 446, 0, :east
unit :sludge, 467, 0, :east
unit :thick_sludge, 468, 0, :east
unit :captive, 470, 0, :east
unit :sludge, 472, 0, :east
unit :archer, 475, 0, :east
unit :thick_sludge, 477, 0, :east
unit :sludge, 486, 0, :east
unit :archer, 487, 0, :east
unit :archer, 493, 0, :east
unit :thick_sludge, 496, 0, :east
unit :captive, 497, 0, :east
unit :thick_sludge, 499, 0, :east
unit :wizard, 503, 0, :east
unit :thick_sludge, 504, 0, :east
unit :thick_sludge, 508, 0, :east
unit :captive, 514, 0, :east
unit :captive, 516, 0, :east
unit :thick_sludge, 517, 0, :east
unit :sludge, 519, 0, :east
unit :archer, 520, 0, :east
unit :thick_sludge, 521, 0, :east
unit :sludge, 523, 0, :east
unit :sludge, 525, 0, :east
unit :wizard, 528, 0, :east
unit :wizard, 534, 0, :east
unit :sludge, 543, 0, :west
unit :archer, 544, 0, :west
unit :captive, 569, 0, :west
unit :wizard, 570, 0, :west
unit :thick_sludge, 575, 0, :west
unit :archer, 576, 0, :west
unit :thick_sludge, 583, 0, :west
unit :wizard, 589, 0, :west
