#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  a      s      C C         S  C        C   S S   C s C C C  S S Sa    C  a  S    w s  a     s      s        CS    Ca                 w  C   C   w  w  S S a a       a Sw  saa  S  wa  a  C        C aS CS     a            asC a    @   a         a   C      a C         CsS   a C  s   C      C       s   w C SC       a  C  C    w C  w  a S  s     sS   aS  C w  w s   a          ssC     s    S    a     a      C    w         w       C   Cs   S      w   Ca C    SaS     w C    C s     a           ass     a   s     C     a    S w    S  >      w Cw    aS   a   s       s     S a   s S    s  s  CS    s       aC s      s      |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 618
ace_score 3090
size 618, 1
stairs 530, 0

warrior 229, 0, :east

unit :archer, 2, 0, :east
unit :sludge, 9, 0, :east
unit :captive, 16, 0, :east
unit :captive, 18, 0, :east
unit :thick_sludge, 28, 0, :east
unit :captive, 31, 0, :east
unit :captive, 40, 0, :east
unit :thick_sludge, 44, 0, :east
unit :thick_sludge, 46, 0, :east
unit :captive, 50, 0, :east
unit :sludge, 52, 0, :east
unit :captive, 54, 0, :east
unit :captive, 56, 0, :east
unit :captive, 58, 0, :east
unit :thick_sludge, 61, 0, :east
unit :thick_sludge, 63, 0, :east
unit :thick_sludge, 65, 0, :east
unit :archer, 66, 0, :east
unit :captive, 71, 0, :east
unit :archer, 74, 0, :east
unit :thick_sludge, 77, 0, :east
unit :wizard, 82, 0, :east
unit :sludge, 84, 0, :east
unit :archer, 87, 0, :east
unit :sludge, 93, 0, :east
unit :sludge, 100, 0, :east
unit :captive, 109, 0, :east
unit :thick_sludge, 110, 0, :east
unit :captive, 115, 0, :east
unit :archer, 116, 0, :east
unit :wizard, 134, 0, :east
unit :captive, 137, 0, :east
unit :captive, 141, 0, :east
unit :wizard, 145, 0, :east
unit :wizard, 148, 0, :east
unit :thick_sludge, 151, 0, :east
unit :thick_sludge, 153, 0, :east
unit :archer, 155, 0, :east
unit :archer, 157, 0, :east
unit :archer, 165, 0, :east
unit :thick_sludge, 167, 0, :east
unit :wizard, 168, 0, :east
unit :sludge, 171, 0, :east
unit :archer, 172, 0, :east
unit :archer, 173, 0, :east
unit :thick_sludge, 176, 0, :east
unit :wizard, 179, 0, :east
unit :archer, 180, 0, :east
unit :archer, 183, 0, :east
unit :captive, 186, 0, :east
unit :captive, 195, 0, :east
unit :archer, 197, 0, :east
unit :thick_sludge, 198, 0, :east
unit :captive, 200, 0, :east
unit :thick_sludge, 201, 0, :east
unit :archer, 207, 0, :east
unit :archer, 220, 0, :east
unit :sludge, 221, 0, :east
unit :captive, 222, 0, :east
unit :archer, 224, 0, :east
unit :archer, 233, 0, :west
unit :archer, 243, 0, :west
unit :captive, 247, 0, :west
unit :archer, 254, 0, :west
unit :captive, 256, 0, :west
unit :captive, 266, 0, :west
unit :sludge, 267, 0, :west
unit :thick_sludge, 268, 0, :west
unit :archer, 272, 0, :west
unit :captive, 274, 0, :west
unit :sludge, 277, 0, :west
unit :captive, 281, 0, :west
unit :captive, 288, 0, :west
unit :sludge, 296, 0, :west
unit :wizard, 300, 0, :west
unit :captive, 302, 0, :west
unit :thick_sludge, 304, 0, :west
unit :captive, 305, 0, :west
unit :archer, 313, 0, :west
unit :captive, 316, 0, :west
unit :captive, 319, 0, :west
unit :wizard, 324, 0, :west
unit :captive, 326, 0, :west
unit :wizard, 329, 0, :west
unit :archer, 332, 0, :west
unit :thick_sludge, 334, 0, :west
unit :sludge, 337, 0, :west
unit :sludge, 343, 0, :west
unit :thick_sludge, 344, 0, :west
unit :archer, 348, 0, :west
unit :thick_sludge, 349, 0, :west
unit :captive, 352, 0, :west
unit :wizard, 354, 0, :west
unit :wizard, 357, 0, :west
unit :sludge, 359, 0, :west
unit :archer, 363, 0, :west
unit :sludge, 374, 0, :west
unit :sludge, 375, 0, :west
unit :captive, 376, 0, :west
unit :sludge, 382, 0, :west
unit :thick_sludge, 387, 0, :west
unit :archer, 392, 0, :west
unit :archer, 398, 0, :west
unit :captive, 405, 0, :west
unit :wizard, 410, 0, :west
unit :wizard, 420, 0, :west
unit :captive, 428, 0, :west
unit :captive, 432, 0, :west
unit :sludge, 433, 0, :west
unit :thick_sludge, 437, 0, :west
unit :wizard, 444, 0, :west
unit :captive, 448, 0, :west
unit :archer, 449, 0, :west
unit :captive, 451, 0, :west
unit :thick_sludge, 456, 0, :west
unit :archer, 457, 0, :west
unit :thick_sludge, 458, 0, :west
unit :wizard, 464, 0, :west
unit :captive, 466, 0, :west
unit :captive, 471, 0, :west
unit :sludge, 473, 0, :west
unit :archer, 479, 0, :west
unit :archer, 491, 0, :west
unit :sludge, 492, 0, :west
unit :sludge, 493, 0, :west
unit :archer, 499, 0, :west
unit :sludge, 503, 0, :west
unit :captive, 509, 0, :west
unit :archer, 515, 0, :west
unit :thick_sludge, 520, 0, :west
unit :wizard, 522, 0, :west
unit :thick_sludge, 527, 0, :west
unit :wizard, 537, 0, :west
unit :captive, 539, 0, :west
unit :wizard, 540, 0, :west
unit :archer, 545, 0, :west
unit :thick_sludge, 546, 0, :west
unit :archer, 550, 0, :west
unit :sludge, 554, 0, :west
unit :sludge, 562, 0, :west
unit :thick_sludge, 568, 0, :west
unit :archer, 570, 0, :west
unit :sludge, 574, 0, :west
unit :thick_sludge, 576, 0, :west
unit :sludge, 581, 0, :west
unit :sludge, 584, 0, :west
unit :captive, 587, 0, :west
unit :thick_sludge, 588, 0, :west
unit :sludge, 593, 0, :west
unit :archer, 601, 0, :west
unit :captive, 602, 0, :west
unit :sludge, 604, 0, :west
unit :sludge, 611, 0, :west
