#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  a   s     aC              s                   a  a     S S C a   C s      a      S   Sw Sw s        Cw       w     SCa    s    C w a w       a             s  aS  w  aw S  s  s     aa a       C      w w  Cs        s    as  > s  s    a w C     a w    w s  a C         a    w SS S    wC w     C    s S    s    ws   S   s    a     @    s  CC   s S  C  s s    s    S a  w     w             w w      a wsw     w  a         s  aSC         S   wss SS  w C   a   Sw   CaS            sa a   s    a   a  S C             w S       sSs  ssS      ssC  S    Sa    C             C  Cs       w      C     w  w   S   C       S w w sC a S    ss   S    a a aC aS          w  C   s        S  S   a  sw S  Ss    C          C w        C  C  s          wa CC s   C  s            s       C   Swa    w              s     S       aa     S S      SwS  w a    CS         C  s      |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 854
ace_score 4270
size 854, 1
stairs 224, 0

warrior 329, 0, :east

unit :archer, 2, 0, :east
unit :sludge, 6, 0, :east
unit :archer, 12, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 28, 0, :east
unit :archer, 48, 0, :east
unit :archer, 51, 0, :east
unit :thick_sludge, 57, 0, :east
unit :thick_sludge, 59, 0, :east
unit :captive, 61, 0, :east
unit :archer, 63, 0, :east
unit :captive, 67, 0, :east
unit :sludge, 69, 0, :east
unit :archer, 76, 0, :east
unit :thick_sludge, 83, 0, :east
unit :thick_sludge, 87, 0, :east
unit :wizard, 88, 0, :east
unit :thick_sludge, 90, 0, :east
unit :wizard, 91, 0, :east
unit :sludge, 93, 0, :east
unit :captive, 102, 0, :east
unit :wizard, 103, 0, :east
unit :wizard, 111, 0, :east
unit :thick_sludge, 117, 0, :east
unit :captive, 118, 0, :east
unit :archer, 119, 0, :east
unit :sludge, 124, 0, :east
unit :captive, 129, 0, :east
unit :wizard, 131, 0, :east
unit :archer, 133, 0, :east
unit :wizard, 135, 0, :east
unit :archer, 143, 0, :east
unit :sludge, 157, 0, :east
unit :archer, 160, 0, :east
unit :thick_sludge, 161, 0, :east
unit :wizard, 164, 0, :east
unit :archer, 167, 0, :east
unit :wizard, 168, 0, :east
unit :thick_sludge, 170, 0, :east
unit :sludge, 173, 0, :east
unit :sludge, 176, 0, :east
unit :archer, 182, 0, :east
unit :archer, 183, 0, :east
unit :archer, 185, 0, :east
unit :captive, 193, 0, :east
unit :wizard, 200, 0, :east
unit :wizard, 202, 0, :east
unit :captive, 205, 0, :east
unit :sludge, 206, 0, :east
unit :sludge, 215, 0, :east
unit :archer, 220, 0, :east
unit :sludge, 221, 0, :east
unit :sludge, 226, 0, :east
unit :sludge, 229, 0, :east
unit :archer, 234, 0, :east
unit :wizard, 236, 0, :east
unit :captive, 238, 0, :east
unit :archer, 244, 0, :east
unit :wizard, 246, 0, :east
unit :wizard, 251, 0, :east
unit :sludge, 253, 0, :east
unit :archer, 256, 0, :east
unit :captive, 258, 0, :east
unit :archer, 268, 0, :east
unit :wizard, 273, 0, :east
unit :thick_sludge, 275, 0, :east
unit :thick_sludge, 276, 0, :east
unit :thick_sludge, 278, 0, :east
unit :wizard, 283, 0, :east
unit :captive, 284, 0, :east
unit :wizard, 286, 0, :east
unit :captive, 292, 0, :east
unit :sludge, 297, 0, :east
unit :thick_sludge, 299, 0, :east
unit :sludge, 304, 0, :east
unit :wizard, 309, 0, :east
unit :sludge, 310, 0, :east
unit :thick_sludge, 314, 0, :east
unit :sludge, 318, 0, :east
unit :archer, 323, 0, :east
unit :sludge, 334, 0, :west
unit :captive, 337, 0, :west
unit :captive, 338, 0, :west
unit :sludge, 342, 0, :west
unit :thick_sludge, 344, 0, :west
unit :captive, 347, 0, :west
unit :sludge, 350, 0, :west
unit :sludge, 352, 0, :west
unit :sludge, 357, 0, :west
unit :thick_sludge, 362, 0, :west
unit :archer, 364, 0, :west
unit :wizard, 367, 0, :west
unit :wizard, 373, 0, :west
unit :wizard, 387, 0, :west
unit :wizard, 389, 0, :west
unit :archer, 396, 0, :west
unit :wizard, 398, 0, :west
unit :sludge, 399, 0, :west
unit :wizard, 400, 0, :west
unit :wizard, 406, 0, :west
unit :archer, 409, 0, :west
unit :sludge, 419, 0, :west
unit :archer, 422, 0, :west
unit :thick_sludge, 423, 0, :west
unit :captive, 424, 0, :west
unit :thick_sludge, 434, 0, :west
unit :wizard, 438, 0, :west
unit :sludge, 439, 0, :west
unit :sludge, 440, 0, :west
unit :thick_sludge, 442, 0, :west
unit :thick_sludge, 443, 0, :west
unit :wizard, 446, 0, :west
unit :captive, 448, 0, :west
unit :archer, 452, 0, :west
unit :thick_sludge, 456, 0, :west
unit :wizard, 457, 0, :west
unit :captive, 461, 0, :west
unit :archer, 462, 0, :west
unit :thick_sludge, 463, 0, :west
unit :sludge, 476, 0, :west
unit :archer, 477, 0, :west
unit :archer, 479, 0, :west
unit :sludge, 483, 0, :west
unit :archer, 488, 0, :west
unit :archer, 492, 0, :west
unit :thick_sludge, 495, 0, :west
unit :captive, 497, 0, :west
unit :wizard, 511, 0, :west
unit :thick_sludge, 513, 0, :west
unit :sludge, 521, 0, :west
unit :thick_sludge, 522, 0, :west
unit :sludge, 523, 0, :west
unit :sludge, 526, 0, :west
unit :sludge, 527, 0, :west
unit :thick_sludge, 528, 0, :west
unit :sludge, 535, 0, :west
unit :sludge, 536, 0, :west
unit :captive, 537, 0, :west
unit :thick_sludge, 540, 0, :west
unit :thick_sludge, 545, 0, :west
unit :archer, 546, 0, :west
unit :captive, 551, 0, :west
unit :captive, 565, 0, :west
unit :captive, 568, 0, :west
unit :sludge, 569, 0, :west
unit :wizard, 577, 0, :west
unit :captive, 584, 0, :west
unit :wizard, 590, 0, :west
unit :wizard, 593, 0, :west
unit :thick_sludge, 597, 0, :west
unit :captive, 601, 0, :west
unit :thick_sludge, 609, 0, :west
unit :wizard, 611, 0, :west
unit :wizard, 613, 0, :west
unit :sludge, 615, 0, :west
unit :captive, 616, 0, :west
unit :archer, 618, 0, :west
unit :thick_sludge, 620, 0, :west
unit :sludge, 625, 0, :west
unit :sludge, 626, 0, :west
unit :thick_sludge, 630, 0, :west
unit :archer, 635, 0, :west
unit :archer, 637, 0, :west
unit :archer, 639, 0, :west
unit :captive, 640, 0, :west
unit :archer, 642, 0, :west
unit :thick_sludge, 643, 0, :west
unit :wizard, 654, 0, :west
unit :captive, 657, 0, :west
unit :sludge, 661, 0, :west
unit :thick_sludge, 670, 0, :west
unit :thick_sludge, 673, 0, :west
unit :archer, 677, 0, :west
unit :sludge, 680, 0, :west
unit :wizard, 681, 0, :west
unit :thick_sludge, 683, 0, :west
unit :thick_sludge, 686, 0, :west
unit :sludge, 687, 0, :west
unit :captive, 692, 0, :west
unit :captive, 703, 0, :west
unit :wizard, 705, 0, :west
unit :captive, 714, 0, :west
unit :captive, 717, 0, :west
unit :sludge, 720, 0, :west
unit :wizard, 731, 0, :west
unit :archer, 732, 0, :west
unit :captive, 734, 0, :west
unit :captive, 735, 0, :west
unit :sludge, 737, 0, :west
unit :captive, 741, 0, :west
unit :sludge, 744, 0, :west
unit :sludge, 757, 0, :west
unit :captive, 765, 0, :west
unit :thick_sludge, 769, 0, :west
unit :wizard, 770, 0, :west
unit :archer, 771, 0, :west
unit :wizard, 776, 0, :west
unit :sludge, 791, 0, :west
unit :thick_sludge, 797, 0, :west
unit :archer, 805, 0, :west
unit :archer, 806, 0, :west
unit :thick_sludge, 812, 0, :west
unit :thick_sludge, 814, 0, :west
unit :thick_sludge, 821, 0, :west
unit :wizard, 822, 0, :west
unit :thick_sludge, 823, 0, :west
unit :wizard, 826, 0, :west
unit :archer, 828, 0, :west
unit :captive, 833, 0, :west
unit :thick_sludge, 834, 0, :west
unit :captive, 844, 0, :west
unit :sludge, 847, 0, :west
