#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s         S C      w  S s         w       Cw       S  SS    C         w     wC a           as w S  s  s           C      a a Sw      w        C     Ss   S   a     a a     s       a   S  s  C      a  Sa a   C   S a SS  S S    s     C Cs      S    w       C   as   S  s sS S aCs    S    s                 w       C w w               aC  s  Ss S  aa  Ss  a  Sa sC   S     C   S            w a           s a   w  Cs  C       C  @    wC          a    C   aw   w   a a S    aa         S a     s      S aC   S     a a  aC  S    a   C    C s   w S  a   C    S  s SC    S     S a       s S a              a  w aSS C    aS    sC w  a          a s   w  w       S     a s  Sa    sCSw  S    w    s s  S            s   s s>     a a     w       w    a  s    s      C w as      ws      SS      S   w        w C   S  w  s  a C  S    C C   C|
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 825
ace_score 4125
size 825, 1
stairs 710, 0

warrior 426, 0, :east

unit :sludge, 2, 0, :east
unit :thick_sludge, 12, 0, :east
unit :captive, 14, 0, :east
unit :wizard, 21, 0, :east
unit :thick_sludge, 24, 0, :east
unit :sludge, 26, 0, :east
unit :wizard, 36, 0, :east
unit :captive, 44, 0, :east
unit :wizard, 45, 0, :east
unit :thick_sludge, 53, 0, :east
unit :thick_sludge, 56, 0, :east
unit :thick_sludge, 57, 0, :east
unit :captive, 62, 0, :east
unit :wizard, 72, 0, :east
unit :wizard, 78, 0, :east
unit :captive, 79, 0, :east
unit :archer, 81, 0, :east
unit :archer, 93, 0, :east
unit :sludge, 94, 0, :east
unit :wizard, 96, 0, :east
unit :thick_sludge, 98, 0, :east
unit :sludge, 101, 0, :east
unit :sludge, 104, 0, :east
unit :captive, 116, 0, :east
unit :archer, 123, 0, :east
unit :archer, 125, 0, :east
unit :thick_sludge, 127, 0, :east
unit :wizard, 128, 0, :east
unit :wizard, 135, 0, :east
unit :captive, 144, 0, :east
unit :thick_sludge, 150, 0, :east
unit :sludge, 151, 0, :east
unit :thick_sludge, 155, 0, :east
unit :archer, 159, 0, :east
unit :archer, 165, 0, :east
unit :archer, 167, 0, :east
unit :sludge, 173, 0, :east
unit :archer, 181, 0, :east
unit :thick_sludge, 185, 0, :east
unit :sludge, 188, 0, :east
unit :captive, 191, 0, :east
unit :archer, 198, 0, :east
unit :thick_sludge, 201, 0, :east
unit :archer, 202, 0, :east
unit :archer, 204, 0, :east
unit :captive, 208, 0, :east
unit :thick_sludge, 212, 0, :east
unit :archer, 214, 0, :east
unit :thick_sludge, 216, 0, :east
unit :thick_sludge, 217, 0, :east
unit :thick_sludge, 220, 0, :east
unit :thick_sludge, 222, 0, :east
unit :sludge, 227, 0, :east
unit :captive, 233, 0, :east
unit :captive, 235, 0, :east
unit :sludge, 236, 0, :east
unit :thick_sludge, 243, 0, :east
unit :wizard, 248, 0, :east
unit :captive, 256, 0, :east
unit :archer, 260, 0, :east
unit :sludge, 261, 0, :east
unit :thick_sludge, 265, 0, :east
unit :sludge, 268, 0, :east
unit :sludge, 270, 0, :east
unit :thick_sludge, 271, 0, :east
unit :thick_sludge, 273, 0, :east
unit :archer, 275, 0, :east
unit :captive, 276, 0, :east
unit :sludge, 277, 0, :east
unit :thick_sludge, 282, 0, :east
unit :sludge, 287, 0, :east
unit :wizard, 305, 0, :east
unit :captive, 313, 0, :east
unit :wizard, 315, 0, :east
unit :wizard, 317, 0, :east
unit :archer, 333, 0, :east
unit :captive, 334, 0, :east
unit :sludge, 337, 0, :east
unit :thick_sludge, 340, 0, :east
unit :sludge, 341, 0, :east
unit :thick_sludge, 343, 0, :east
unit :archer, 346, 0, :east
unit :archer, 347, 0, :east
unit :thick_sludge, 350, 0, :east
unit :sludge, 351, 0, :east
unit :archer, 354, 0, :east
unit :thick_sludge, 357, 0, :east
unit :archer, 358, 0, :east
unit :sludge, 360, 0, :east
unit :captive, 361, 0, :east
unit :thick_sludge, 365, 0, :east
unit :captive, 371, 0, :east
unit :thick_sludge, 375, 0, :east
unit :wizard, 388, 0, :east
unit :archer, 390, 0, :east
unit :sludge, 402, 0, :east
unit :archer, 404, 0, :east
unit :wizard, 408, 0, :east
unit :captive, 411, 0, :east
unit :sludge, 412, 0, :east
unit :captive, 415, 0, :east
unit :captive, 423, 0, :east
unit :wizard, 431, 0, :west
unit :captive, 432, 0, :west
unit :archer, 443, 0, :west
unit :captive, 448, 0, :west
unit :archer, 452, 0, :west
unit :wizard, 453, 0, :west
unit :wizard, 457, 0, :west
unit :archer, 461, 0, :west
unit :archer, 463, 0, :west
unit :thick_sludge, 465, 0, :west
unit :archer, 470, 0, :west
unit :archer, 471, 0, :west
unit :thick_sludge, 481, 0, :west
unit :archer, 483, 0, :west
unit :sludge, 489, 0, :west
unit :thick_sludge, 496, 0, :west
unit :archer, 498, 0, :west
unit :captive, 499, 0, :west
unit :thick_sludge, 503, 0, :west
unit :archer, 509, 0, :west
unit :archer, 511, 0, :west
unit :archer, 514, 0, :west
unit :captive, 515, 0, :west
unit :thick_sludge, 518, 0, :west
unit :archer, 523, 0, :west
unit :captive, 527, 0, :west
unit :captive, 532, 0, :west
unit :sludge, 534, 0, :west
unit :wizard, 538, 0, :west
unit :thick_sludge, 540, 0, :west
unit :archer, 543, 0, :west
unit :captive, 547, 0, :west
unit :thick_sludge, 552, 0, :west
unit :sludge, 555, 0, :west
unit :thick_sludge, 557, 0, :west
unit :captive, 558, 0, :west
unit :thick_sludge, 563, 0, :west
unit :thick_sludge, 569, 0, :west
unit :archer, 571, 0, :west
unit :sludge, 579, 0, :west
unit :thick_sludge, 581, 0, :west
unit :archer, 583, 0, :west
unit :archer, 598, 0, :west
unit :wizard, 601, 0, :west
unit :archer, 603, 0, :west
unit :thick_sludge, 604, 0, :west
unit :thick_sludge, 605, 0, :west
unit :captive, 607, 0, :west
unit :archer, 612, 0, :west
unit :thick_sludge, 613, 0, :west
unit :sludge, 618, 0, :west
unit :captive, 619, 0, :west
unit :wizard, 621, 0, :west
unit :archer, 624, 0, :west
unit :archer, 635, 0, :west
unit :sludge, 637, 0, :west
unit :wizard, 641, 0, :west
unit :wizard, 644, 0, :west
unit :thick_sludge, 652, 0, :west
unit :archer, 658, 0, :west
unit :sludge, 660, 0, :west
unit :thick_sludge, 663, 0, :west
unit :archer, 664, 0, :west
unit :sludge, 669, 0, :west
unit :captive, 670, 0, :west
unit :thick_sludge, 671, 0, :west
unit :wizard, 672, 0, :west
unit :thick_sludge, 675, 0, :west
unit :wizard, 680, 0, :west
unit :sludge, 685, 0, :west
unit :sludge, 687, 0, :west
unit :thick_sludge, 690, 0, :west
unit :sludge, 703, 0, :west
unit :sludge, 707, 0, :west
unit :sludge, 709, 0, :west
unit :archer, 716, 0, :west
unit :archer, 718, 0, :west
unit :wizard, 724, 0, :west
unit :wizard, 732, 0, :west
unit :archer, 737, 0, :west
unit :sludge, 740, 0, :west
unit :sludge, 745, 0, :west
unit :captive, 752, 0, :west
unit :wizard, 754, 0, :west
unit :archer, 756, 0, :west
unit :sludge, 757, 0, :west
unit :wizard, 764, 0, :west
unit :sludge, 765, 0, :west
unit :thick_sludge, 772, 0, :west
unit :thick_sludge, 773, 0, :west
unit :thick_sludge, 780, 0, :west
unit :wizard, 784, 0, :west
unit :wizard, 793, 0, :west
unit :captive, 795, 0, :west
unit :thick_sludge, 799, 0, :west
unit :wizard, 802, 0, :west
unit :sludge, 805, 0, :west
unit :archer, 808, 0, :west
unit :captive, 810, 0, :west
unit :thick_sludge, 813, 0, :west
unit :captive, 818, 0, :west
unit :captive, 820, 0, :west
unit :captive, 824, 0, :west
