#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a     Sa       s   a a   w           ss CaC w    a          Ss          w  C w   S C      a    w s S     w  w      a     s   a w C  C           a  C     aC  CSC     S w C    C   S      a C       SS    a a  s  C       a a          aC      s a S      s  C         as wS   s  SS  C CS     w                 aa  s      w   s   aSs   w  a C  a C  Sw   S        w w   s  a w      aa     S  CCs   a      Cs s      sS        as  a w        s   C   S  w               s       w   a s         s  S C   C    CC    SC  S    >  w      w sS   C w           CS   C  a  a   aC  w  C    Css     CaSwa  @        SS wS C   a            w           aS S         S sSs  S     aS          w     a   Cw S             s   w       S    s    s         S s C aS |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 736
ace_score 3680
size 736, 1
stairs 513, 0

warrior 586, 0, :east

unit :archer, 1, 0, :east
unit :thick_sludge, 7, 0, :east
unit :archer, 8, 0, :east
unit :sludge, 16, 0, :east
unit :archer, 20, 0, :east
unit :archer, 22, 0, :east
unit :wizard, 26, 0, :east
unit :sludge, 38, 0, :east
unit :sludge, 39, 0, :east
unit :captive, 41, 0, :east
unit :archer, 42, 0, :east
unit :captive, 43, 0, :east
unit :wizard, 45, 0, :east
unit :archer, 50, 0, :east
unit :thick_sludge, 61, 0, :east
unit :sludge, 62, 0, :east
unit :wizard, 73, 0, :east
unit :captive, 76, 0, :east
unit :wizard, 78, 0, :east
unit :thick_sludge, 82, 0, :east
unit :captive, 84, 0, :east
unit :archer, 91, 0, :east
unit :wizard, 96, 0, :east
unit :sludge, 98, 0, :east
unit :thick_sludge, 100, 0, :east
unit :wizard, 106, 0, :east
unit :wizard, 109, 0, :east
unit :archer, 116, 0, :east
unit :sludge, 122, 0, :east
unit :archer, 126, 0, :east
unit :wizard, 128, 0, :east
unit :captive, 130, 0, :east
unit :captive, 133, 0, :east
unit :archer, 145, 0, :east
unit :captive, 148, 0, :east
unit :archer, 154, 0, :east
unit :captive, 155, 0, :east
unit :captive, 158, 0, :east
unit :thick_sludge, 159, 0, :east
unit :captive, 160, 0, :east
unit :thick_sludge, 166, 0, :east
unit :wizard, 168, 0, :east
unit :captive, 170, 0, :east
unit :captive, 175, 0, :east
unit :thick_sludge, 179, 0, :east
unit :archer, 186, 0, :east
unit :captive, 188, 0, :east
unit :thick_sludge, 196, 0, :east
unit :thick_sludge, 197, 0, :east
unit :archer, 202, 0, :east
unit :archer, 204, 0, :east
unit :sludge, 207, 0, :east
unit :captive, 210, 0, :east
unit :archer, 218, 0, :east
unit :archer, 220, 0, :east
unit :archer, 231, 0, :east
unit :captive, 232, 0, :east
unit :sludge, 239, 0, :east
unit :archer, 241, 0, :east
unit :thick_sludge, 243, 0, :east
unit :sludge, 250, 0, :east
unit :captive, 253, 0, :east
unit :archer, 263, 0, :east
unit :sludge, 264, 0, :east
unit :wizard, 266, 0, :east
unit :thick_sludge, 267, 0, :east
unit :sludge, 271, 0, :east
unit :thick_sludge, 274, 0, :east
unit :thick_sludge, 275, 0, :east
unit :captive, 278, 0, :east
unit :captive, 280, 0, :east
unit :thick_sludge, 281, 0, :east
unit :wizard, 287, 0, :east
unit :archer, 305, 0, :east
unit :archer, 306, 0, :east
unit :sludge, 309, 0, :east
unit :wizard, 316, 0, :east
unit :sludge, 320, 0, :east
unit :archer, 324, 0, :east
unit :thick_sludge, 325, 0, :east
unit :sludge, 326, 0, :east
unit :wizard, 330, 0, :east
unit :archer, 333, 0, :east
unit :captive, 335, 0, :east
unit :archer, 338, 0, :east
unit :captive, 340, 0, :east
unit :thick_sludge, 343, 0, :east
unit :wizard, 344, 0, :east
unit :thick_sludge, 348, 0, :east
unit :wizard, 357, 0, :east
unit :wizard, 359, 0, :east
unit :sludge, 363, 0, :east
unit :archer, 366, 0, :east
unit :wizard, 368, 0, :east
unit :archer, 375, 0, :east
unit :archer, 376, 0, :east
unit :thick_sludge, 382, 0, :east
unit :captive, 385, 0, :east
unit :captive, 386, 0, :east
unit :sludge, 387, 0, :east
unit :archer, 391, 0, :east
unit :captive, 398, 0, :east
unit :sludge, 399, 0, :east
unit :sludge, 401, 0, :east
unit :sludge, 408, 0, :east
unit :thick_sludge, 409, 0, :east
unit :archer, 418, 0, :east
unit :sludge, 419, 0, :east
unit :archer, 422, 0, :east
unit :wizard, 424, 0, :east
unit :sludge, 433, 0, :east
unit :captive, 437, 0, :east
unit :thick_sludge, 441, 0, :east
unit :wizard, 444, 0, :east
unit :sludge, 460, 0, :east
unit :wizard, 468, 0, :east
unit :archer, 472, 0, :east
unit :sludge, 474, 0, :east
unit :sludge, 484, 0, :east
unit :thick_sludge, 487, 0, :east
unit :captive, 489, 0, :east
unit :captive, 493, 0, :east
unit :captive, 498, 0, :east
unit :captive, 499, 0, :east
unit :thick_sludge, 504, 0, :east
unit :captive, 505, 0, :east
unit :thick_sludge, 508, 0, :east
unit :wizard, 516, 0, :east
unit :wizard, 523, 0, :east
unit :sludge, 525, 0, :east
unit :thick_sludge, 526, 0, :east
unit :captive, 530, 0, :east
unit :wizard, 532, 0, :east
unit :captive, 544, 0, :east
unit :thick_sludge, 545, 0, :east
unit :captive, 549, 0, :east
unit :archer, 552, 0, :east
unit :archer, 555, 0, :east
unit :archer, 559, 0, :east
unit :captive, 560, 0, :east
unit :wizard, 563, 0, :east
unit :captive, 566, 0, :east
unit :captive, 571, 0, :east
unit :sludge, 572, 0, :east
unit :sludge, 573, 0, :east
unit :captive, 579, 0, :east
unit :archer, 580, 0, :east
unit :thick_sludge, 581, 0, :east
unit :wizard, 582, 0, :east
unit :archer, 583, 0, :east
unit :thick_sludge, 595, 0, :west
unit :thick_sludge, 596, 0, :west
unit :wizard, 598, 0, :west
unit :thick_sludge, 599, 0, :west
unit :captive, 601, 0, :west
unit :archer, 605, 0, :west
unit :wizard, 618, 0, :west
unit :archer, 630, 0, :west
unit :thick_sludge, 631, 0, :west
unit :thick_sludge, 633, 0, :west
unit :thick_sludge, 643, 0, :west
unit :sludge, 645, 0, :west
unit :thick_sludge, 646, 0, :west
unit :sludge, 647, 0, :west
unit :thick_sludge, 650, 0, :west
unit :archer, 656, 0, :west
unit :thick_sludge, 657, 0, :west
unit :wizard, 668, 0, :west
unit :archer, 674, 0, :west
unit :captive, 678, 0, :west
unit :wizard, 679, 0, :west
unit :thick_sludge, 681, 0, :west
unit :sludge, 695, 0, :west
unit :wizard, 699, 0, :west
unit :thick_sludge, 707, 0, :west
unit :sludge, 712, 0, :west
unit :sludge, 717, 0, :west
unit :thick_sludge, 727, 0, :west
unit :sludge, 729, 0, :west
unit :captive, 731, 0, :west
unit :archer, 733, 0, :west
unit :thick_sludge, 734, 0, :west
