#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w S     a     C   w  w        >    sa         aa         S    S    w S    C wS      C  w    w s    s          w asC S aS C   C   a C  w   C     @  s   wC C          CC   a  w      w      s      s s        S a    s s   C S  S  s             s S  S      w S  s   w a      s sS       w    a   w a        a  a   S              a s      w     Sw      as                aa wa             wSSSsC s   Sw  a C   C        S w    CC    S   awS  s w Caa      s         s    a   s  ws      CS         C w     S  sC  C   s    C s      C  s   s        s      a      Saa  a   C       w   Ss     s   a SCCS     S      a Ca               a awCC       w      C CSa a  CC  |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 655
ace_score 3275
size 655, 1
stairs 32, 0

warrior 146, 0, :east

unit :wizard, 2, 0, :east
unit :thick_sludge, 4, 0, :east
unit :archer, 10, 0, :east
unit :captive, 16, 0, :east
unit :wizard, 20, 0, :east
unit :wizard, 23, 0, :east
unit :sludge, 37, 0, :east
unit :archer, 38, 0, :east
unit :archer, 48, 0, :east
unit :archer, 49, 0, :east
unit :thick_sludge, 59, 0, :east
unit :thick_sludge, 64, 0, :east
unit :wizard, 69, 0, :east
unit :thick_sludge, 71, 0, :east
unit :captive, 76, 0, :east
unit :wizard, 78, 0, :east
unit :thick_sludge, 79, 0, :east
unit :captive, 86, 0, :east
unit :wizard, 89, 0, :east
unit :wizard, 94, 0, :east
unit :sludge, 96, 0, :east
unit :sludge, 101, 0, :east
unit :wizard, 112, 0, :east
unit :archer, 114, 0, :east
unit :sludge, 115, 0, :east
unit :captive, 116, 0, :east
unit :thick_sludge, 118, 0, :east
unit :archer, 120, 0, :east
unit :thick_sludge, 121, 0, :east
unit :captive, 123, 0, :east
unit :captive, 127, 0, :east
unit :archer, 131, 0, :east
unit :captive, 133, 0, :east
unit :wizard, 136, 0, :east
unit :captive, 140, 0, :east
unit :sludge, 149, 0, :west
unit :wizard, 153, 0, :west
unit :captive, 154, 0, :west
unit :captive, 156, 0, :west
unit :captive, 167, 0, :west
unit :captive, 168, 0, :west
unit :archer, 172, 0, :west
unit :wizard, 175, 0, :west
unit :wizard, 182, 0, :west
unit :sludge, 189, 0, :west
unit :sludge, 196, 0, :west
unit :sludge, 198, 0, :west
unit :thick_sludge, 207, 0, :west
unit :archer, 209, 0, :west
unit :sludge, 214, 0, :west
unit :sludge, 216, 0, :west
unit :captive, 220, 0, :west
unit :thick_sludge, 222, 0, :west
unit :thick_sludge, 225, 0, :west
unit :sludge, 228, 0, :west
unit :sludge, 242, 0, :west
unit :thick_sludge, 244, 0, :west
unit :thick_sludge, 247, 0, :west
unit :wizard, 254, 0, :west
unit :thick_sludge, 256, 0, :west
unit :sludge, 259, 0, :west
unit :wizard, 263, 0, :west
unit :archer, 265, 0, :west
unit :sludge, 272, 0, :west
unit :sludge, 274, 0, :west
unit :thick_sludge, 275, 0, :west
unit :wizard, 283, 0, :west
unit :archer, 288, 0, :west
unit :wizard, 292, 0, :west
unit :archer, 294, 0, :west
unit :archer, 303, 0, :west
unit :archer, 306, 0, :west
unit :thick_sludge, 310, 0, :west
unit :archer, 325, 0, :west
unit :sludge, 327, 0, :west
unit :wizard, 334, 0, :west
unit :thick_sludge, 340, 0, :west
unit :wizard, 341, 0, :west
unit :archer, 348, 0, :west
unit :sludge, 349, 0, :west
unit :archer, 366, 0, :west
unit :archer, 367, 0, :west
unit :wizard, 369, 0, :west
unit :archer, 370, 0, :west
unit :wizard, 384, 0, :west
unit :thick_sludge, 385, 0, :west
unit :thick_sludge, 386, 0, :west
unit :thick_sludge, 387, 0, :west
unit :sludge, 388, 0, :west
unit :captive, 389, 0, :west
unit :sludge, 391, 0, :west
unit :thick_sludge, 395, 0, :west
unit :wizard, 396, 0, :west
unit :archer, 399, 0, :west
unit :captive, 401, 0, :west
unit :captive, 405, 0, :west
unit :thick_sludge, 414, 0, :west
unit :wizard, 416, 0, :west
unit :captive, 421, 0, :west
unit :captive, 422, 0, :west
unit :thick_sludge, 427, 0, :west
unit :archer, 431, 0, :west
unit :wizard, 432, 0, :west
unit :thick_sludge, 433, 0, :west
unit :sludge, 436, 0, :west
unit :wizard, 438, 0, :west
unit :captive, 440, 0, :west
unit :archer, 441, 0, :west
unit :archer, 442, 0, :west
unit :sludge, 449, 0, :west
unit :sludge, 459, 0, :west
unit :archer, 464, 0, :west
unit :sludge, 468, 0, :west
unit :wizard, 471, 0, :west
unit :sludge, 472, 0, :west
unit :captive, 479, 0, :west
unit :thick_sludge, 480, 0, :west
unit :captive, 490, 0, :west
unit :wizard, 492, 0, :west
unit :thick_sludge, 498, 0, :west
unit :sludge, 501, 0, :west
unit :captive, 502, 0, :west
unit :captive, 505, 0, :west
unit :sludge, 509, 0, :west
unit :captive, 514, 0, :west
unit :sludge, 516, 0, :west
unit :captive, 523, 0, :west
unit :sludge, 526, 0, :west
unit :sludge, 530, 0, :west
unit :sludge, 539, 0, :west
unit :archer, 546, 0, :west
unit :thick_sludge, 553, 0, :west
unit :archer, 554, 0, :west
unit :archer, 555, 0, :west
unit :archer, 558, 0, :west
unit :captive, 562, 0, :west
unit :wizard, 570, 0, :west
unit :thick_sludge, 574, 0, :west
unit :sludge, 575, 0, :west
unit :sludge, 581, 0, :west
unit :archer, 585, 0, :west
unit :thick_sludge, 587, 0, :west
unit :captive, 588, 0, :west
unit :captive, 589, 0, :west
unit :thick_sludge, 590, 0, :west
unit :thick_sludge, 596, 0, :west
unit :archer, 603, 0, :west
unit :captive, 605, 0, :west
unit :archer, 606, 0, :west
unit :archer, 622, 0, :west
unit :archer, 624, 0, :west
unit :wizard, 625, 0, :west
unit :captive, 626, 0, :west
unit :captive, 627, 0, :west
unit :wizard, 635, 0, :west
unit :captive, 642, 0, :west
unit :captive, 644, 0, :west
unit :thick_sludge, 645, 0, :west
unit :archer, 646, 0, :west
unit :archer, 648, 0, :west
unit :captive, 651, 0, :west
unit :captive, 652, 0, :west
