#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S    s  C Sw                    Sa S        sC  S Caa      S   S w ss     aw  s          S     a a aw   s CS   a      w    CS C    w SC    sw s  aC   w      w a   s  s       w w            C  a    C   s    s   C  S     s Ss aC  a      s a    a S     @      C   C   aS C    S       C     C     C     as w  w   w  S      a                   s      a     S S       w   s sSS   C     s  s    s    a           a s w         C   w a   sC            S   s  w  C  w C      w           S S    S w        C   s    aCa   S asS      Cs         s s w   w w           sw a                s  w S       w w S  w    C   S C a  a        aa  Ca  ss   S       w   a            a    sCs SS       a       ss     Ca wa w  s     a  C   S  aC CS  C  S       a s C Ss   C      s w  a   s    >  S     C Sa     S   SC   w        w   a wC  w aw          w S      w   |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 838
ace_score 4190
size 838, 1
stairs 765, 0

warrior 250, 0, :east

unit :thick_sludge, 0, 0, :east
unit :sludge, 5, 0, :east
unit :captive, 8, 0, :east
unit :thick_sludge, 10, 0, :east
unit :wizard, 11, 0, :east
unit :thick_sludge, 32, 0, :east
unit :archer, 33, 0, :east
unit :thick_sludge, 35, 0, :east
unit :sludge, 44, 0, :east
unit :captive, 45, 0, :east
unit :thick_sludge, 48, 0, :east
unit :captive, 50, 0, :east
unit :archer, 51, 0, :east
unit :archer, 52, 0, :east
unit :thick_sludge, 59, 0, :east
unit :thick_sludge, 63, 0, :east
unit :wizard, 65, 0, :east
unit :sludge, 67, 0, :east
unit :sludge, 68, 0, :east
unit :archer, 74, 0, :east
unit :wizard, 75, 0, :east
unit :sludge, 78, 0, :east
unit :thick_sludge, 89, 0, :east
unit :archer, 95, 0, :east
unit :archer, 97, 0, :east
unit :archer, 99, 0, :east
unit :wizard, 100, 0, :east
unit :sludge, 104, 0, :east
unit :captive, 106, 0, :east
unit :thick_sludge, 107, 0, :east
unit :archer, 111, 0, :east
unit :wizard, 118, 0, :east
unit :captive, 123, 0, :east
unit :thick_sludge, 124, 0, :east
unit :captive, 126, 0, :east
unit :wizard, 131, 0, :east
unit :thick_sludge, 133, 0, :east
unit :captive, 134, 0, :east
unit :sludge, 139, 0, :east
unit :wizard, 140, 0, :east
unit :sludge, 142, 0, :east
unit :archer, 145, 0, :east
unit :captive, 146, 0, :east
unit :wizard, 150, 0, :east
unit :wizard, 157, 0, :east
unit :archer, 159, 0, :east
unit :sludge, 163, 0, :east
unit :sludge, 166, 0, :east
unit :wizard, 174, 0, :east
unit :wizard, 176, 0, :east
unit :captive, 189, 0, :east
unit :archer, 192, 0, :east
unit :captive, 197, 0, :east
unit :sludge, 201, 0, :east
unit :sludge, 206, 0, :east
unit :captive, 210, 0, :east
unit :thick_sludge, 213, 0, :east
unit :sludge, 219, 0, :east
unit :thick_sludge, 221, 0, :east
unit :sludge, 222, 0, :east
unit :archer, 224, 0, :east
unit :captive, 225, 0, :east
unit :archer, 228, 0, :east
unit :sludge, 235, 0, :east
unit :archer, 237, 0, :east
unit :archer, 242, 0, :east
unit :thick_sludge, 244, 0, :east
unit :captive, 257, 0, :west
unit :captive, 261, 0, :west
unit :archer, 265, 0, :west
unit :thick_sludge, 266, 0, :west
unit :captive, 268, 0, :west
unit :thick_sludge, 273, 0, :west
unit :captive, 281, 0, :west
unit :captive, 287, 0, :west
unit :captive, 293, 0, :west
unit :archer, 299, 0, :west
unit :sludge, 300, 0, :west
unit :wizard, 302, 0, :west
unit :wizard, 305, 0, :west
unit :wizard, 309, 0, :west
unit :thick_sludge, 312, 0, :west
unit :archer, 319, 0, :west
unit :sludge, 339, 0, :west
unit :archer, 346, 0, :west
unit :thick_sludge, 352, 0, :west
unit :thick_sludge, 354, 0, :west
unit :wizard, 362, 0, :west
unit :sludge, 366, 0, :west
unit :sludge, 368, 0, :west
unit :thick_sludge, 369, 0, :west
unit :thick_sludge, 370, 0, :west
unit :captive, 374, 0, :west
unit :sludge, 380, 0, :west
unit :sludge, 383, 0, :west
unit :sludge, 388, 0, :west
unit :archer, 393, 0, :west
unit :archer, 405, 0, :west
unit :sludge, 407, 0, :west
unit :wizard, 409, 0, :west
unit :captive, 419, 0, :west
unit :wizard, 423, 0, :west
unit :archer, 425, 0, :west
unit :sludge, 429, 0, :west
unit :captive, 430, 0, :west
unit :thick_sludge, 443, 0, :west
unit :sludge, 447, 0, :west
unit :wizard, 450, 0, :west
unit :captive, 453, 0, :west
unit :wizard, 456, 0, :west
unit :captive, 458, 0, :west
unit :wizard, 465, 0, :west
unit :thick_sludge, 477, 0, :west
unit :thick_sludge, 479, 0, :west
unit :thick_sludge, 484, 0, :west
unit :wizard, 486, 0, :west
unit :captive, 495, 0, :west
unit :sludge, 499, 0, :west
unit :archer, 504, 0, :west
unit :captive, 505, 0, :west
unit :archer, 506, 0, :west
unit :thick_sludge, 510, 0, :west
unit :archer, 512, 0, :west
unit :sludge, 513, 0, :west
unit :thick_sludge, 514, 0, :west
unit :captive, 521, 0, :west
unit :sludge, 522, 0, :west
unit :sludge, 532, 0, :west
unit :sludge, 534, 0, :west
unit :wizard, 536, 0, :west
unit :wizard, 540, 0, :west
unit :wizard, 542, 0, :west
unit :sludge, 554, 0, :west
unit :wizard, 555, 0, :west
unit :archer, 557, 0, :west
unit :sludge, 574, 0, :west
unit :wizard, 577, 0, :west
unit :thick_sludge, 579, 0, :west
unit :wizard, 587, 0, :west
unit :wizard, 589, 0, :west
unit :thick_sludge, 591, 0, :west
unit :wizard, 594, 0, :west
unit :captive, 599, 0, :west
unit :thick_sludge, 603, 0, :west
unit :captive, 605, 0, :west
unit :archer, 607, 0, :west
unit :archer, 610, 0, :west
unit :archer, 619, 0, :west
unit :archer, 620, 0, :west
unit :captive, 623, 0, :west
unit :archer, 624, 0, :west
unit :sludge, 627, 0, :west
unit :sludge, 628, 0, :west
unit :thick_sludge, 632, 0, :west
unit :wizard, 640, 0, :west
unit :archer, 644, 0, :west
unit :archer, 657, 0, :west
unit :sludge, 662, 0, :west
unit :captive, 663, 0, :west
unit :sludge, 664, 0, :west
unit :thick_sludge, 666, 0, :west
unit :thick_sludge, 667, 0, :west
unit :archer, 675, 0, :west
unit :sludge, 683, 0, :west
unit :sludge, 684, 0, :west
unit :captive, 690, 0, :west
unit :archer, 691, 0, :west
unit :wizard, 693, 0, :west
unit :archer, 694, 0, :west
unit :wizard, 696, 0, :west
unit :sludge, 699, 0, :west
unit :archer, 705, 0, :west
unit :captive, 708, 0, :west
unit :thick_sludge, 712, 0, :west
unit :archer, 715, 0, :west
unit :captive, 716, 0, :west
unit :captive, 718, 0, :west
unit :thick_sludge, 719, 0, :west
unit :captive, 722, 0, :west
unit :thick_sludge, 725, 0, :west
unit :archer, 733, 0, :west
unit :sludge, 735, 0, :west
unit :captive, 737, 0, :west
unit :thick_sludge, 739, 0, :west
unit :sludge, 740, 0, :west
unit :captive, 744, 0, :west
unit :sludge, 751, 0, :west
unit :wizard, 753, 0, :west
unit :archer, 756, 0, :west
unit :sludge, 760, 0, :west
unit :thick_sludge, 768, 0, :west
unit :captive, 774, 0, :west
unit :thick_sludge, 776, 0, :west
unit :archer, 777, 0, :west
unit :thick_sludge, 783, 0, :west
unit :thick_sludge, 787, 0, :west
unit :captive, 788, 0, :west
unit :wizard, 792, 0, :west
unit :wizard, 801, 0, :west
unit :archer, 805, 0, :west
unit :wizard, 807, 0, :west
unit :captive, 808, 0, :west
unit :wizard, 811, 0, :west
unit :archer, 813, 0, :west
unit :wizard, 814, 0, :west
unit :wizard, 825, 0, :west
unit :thick_sludge, 827, 0, :west
unit :wizard, 834, 0, :west
