#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | w   w   S  a      a   sSS       S  a  S     s     s   a     w w  a   Ss       C  a      a a  S   w SC       s S S     S  SSsaC             C  CC    C        S w w    a s   w  s   aS w   C  sSa    w sS  aw   s     a  s   aC   a as   Ca    w            w     s   w  sCa s    a   w   swa   C sa    sC         w     S                w    w    S  w  a C    >C a sa  a          ss    s aC   s   w w  w s    a       a S C C                Ca   C           a    Cw          a  C s   w CS     assS      s   C     C a    w   S  Sa     w  S       ws S       w C   C S    C    s S sa      C S   a w as CSS             s   a w w   C    S s S S C   C   S a       s aS  sa    C  s s               C s sS S  w    S      S   aC      SC         aS s   w       as  S    a                 S             Ca    S     w      CS C       s         @        s   S  aa S aw                 w  a   a  s     C w a w       aw ss s     w  S         C  w   C a     s       C w      a  C S        C      aa    w                   |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 998
ace_score 4990
size 998, 1
stairs 353, 0

warrior 824, 0, :east

unit :wizard, 1, 0, :east
unit :wizard, 5, 0, :east
unit :thick_sludge, 9, 0, :east
unit :archer, 12, 0, :east
unit :archer, 19, 0, :east
unit :sludge, 23, 0, :east
unit :thick_sludge, 24, 0, :east
unit :thick_sludge, 25, 0, :east
unit :thick_sludge, 33, 0, :east
unit :archer, 36, 0, :east
unit :thick_sludge, 39, 0, :east
unit :sludge, 45, 0, :east
unit :sludge, 51, 0, :east
unit :archer, 55, 0, :east
unit :wizard, 61, 0, :east
unit :wizard, 63, 0, :east
unit :archer, 66, 0, :east
unit :thick_sludge, 70, 0, :east
unit :sludge, 71, 0, :east
unit :captive, 79, 0, :east
unit :archer, 82, 0, :east
unit :archer, 89, 0, :east
unit :archer, 91, 0, :east
unit :thick_sludge, 94, 0, :east
unit :wizard, 98, 0, :east
unit :thick_sludge, 100, 0, :east
unit :captive, 101, 0, :east
unit :sludge, 109, 0, :east
unit :thick_sludge, 111, 0, :east
unit :thick_sludge, 113, 0, :east
unit :thick_sludge, 119, 0, :east
unit :thick_sludge, 122, 0, :east
unit :thick_sludge, 123, 0, :east
unit :sludge, 124, 0, :east
unit :archer, 125, 0, :east
unit :captive, 126, 0, :east
unit :captive, 140, 0, :east
unit :captive, 143, 0, :east
unit :captive, 144, 0, :east
unit :captive, 149, 0, :east
unit :thick_sludge, 158, 0, :east
unit :wizard, 160, 0, :east
unit :wizard, 162, 0, :east
unit :archer, 167, 0, :east
unit :sludge, 169, 0, :east
unit :wizard, 173, 0, :east
unit :sludge, 176, 0, :east
unit :archer, 180, 0, :east
unit :thick_sludge, 181, 0, :east
unit :wizard, 183, 0, :east
unit :captive, 187, 0, :east
unit :sludge, 190, 0, :east
unit :thick_sludge, 191, 0, :east
unit :archer, 192, 0, :east
unit :wizard, 197, 0, :east
unit :sludge, 199, 0, :east
unit :thick_sludge, 200, 0, :east
unit :archer, 203, 0, :east
unit :wizard, 204, 0, :east
unit :sludge, 208, 0, :east
unit :archer, 214, 0, :east
unit :sludge, 217, 0, :east
unit :archer, 221, 0, :east
unit :captive, 222, 0, :east
unit :archer, 226, 0, :east
unit :archer, 228, 0, :east
unit :sludge, 229, 0, :east
unit :captive, 233, 0, :east
unit :archer, 234, 0, :east
unit :wizard, 239, 0, :east
unit :wizard, 252, 0, :east
unit :sludge, 258, 0, :east
unit :wizard, 262, 0, :east
unit :sludge, 265, 0, :east
unit :captive, 266, 0, :east
unit :archer, 267, 0, :east
unit :sludge, 269, 0, :east
unit :archer, 274, 0, :east
unit :wizard, 278, 0, :east
unit :sludge, 282, 0, :east
unit :wizard, 283, 0, :east
unit :archer, 284, 0, :east
unit :captive, 288, 0, :east
unit :sludge, 290, 0, :east
unit :archer, 291, 0, :east
unit :sludge, 296, 0, :east
unit :captive, 297, 0, :east
unit :wizard, 307, 0, :east
unit :thick_sludge, 313, 0, :east
unit :wizard, 330, 0, :east
unit :wizard, 335, 0, :east
unit :thick_sludge, 340, 0, :east
unit :wizard, 343, 0, :east
unit :archer, 346, 0, :east
unit :captive, 348, 0, :east
unit :captive, 354, 0, :east
unit :archer, 356, 0, :east
unit :sludge, 358, 0, :east
unit :archer, 359, 0, :east
unit :archer, 362, 0, :east
unit :sludge, 373, 0, :east
unit :sludge, 374, 0, :east
unit :sludge, 379, 0, :east
unit :archer, 381, 0, :east
unit :captive, 382, 0, :east
unit :sludge, 386, 0, :east
unit :wizard, 390, 0, :east
unit :wizard, 392, 0, :east
unit :wizard, 395, 0, :east
unit :sludge, 397, 0, :east
unit :archer, 402, 0, :east
unit :archer, 410, 0, :east
unit :thick_sludge, 412, 0, :east
unit :captive, 414, 0, :east
unit :captive, 416, 0, :east
unit :captive, 433, 0, :east
unit :archer, 434, 0, :east
unit :captive, 438, 0, :east
unit :archer, 450, 0, :east
unit :captive, 455, 0, :east
unit :wizard, 456, 0, :east
unit :archer, 467, 0, :east
unit :captive, 470, 0, :east
unit :sludge, 472, 0, :east
unit :wizard, 476, 0, :east
unit :captive, 478, 0, :east
unit :thick_sludge, 479, 0, :east
unit :archer, 485, 0, :east
unit :sludge, 486, 0, :east
unit :sludge, 487, 0, :east
unit :thick_sludge, 488, 0, :east
unit :sludge, 495, 0, :east
unit :captive, 499, 0, :east
unit :captive, 505, 0, :east
unit :archer, 507, 0, :east
unit :wizard, 512, 0, :east
unit :thick_sludge, 516, 0, :east
unit :thick_sludge, 519, 0, :east
unit :archer, 520, 0, :east
unit :wizard, 526, 0, :east
unit :thick_sludge, 529, 0, :east
unit :wizard, 537, 0, :east
unit :sludge, 538, 0, :east
unit :thick_sludge, 540, 0, :east
unit :wizard, 548, 0, :east
unit :captive, 550, 0, :east
unit :captive, 554, 0, :east
unit :thick_sludge, 556, 0, :east
unit :captive, 561, 0, :east
unit :sludge, 566, 0, :east
unit :thick_sludge, 568, 0, :east
unit :sludge, 570, 0, :east
unit :archer, 571, 0, :east
unit :captive, 578, 0, :east
unit :thick_sludge, 580, 0, :east
unit :archer, 584, 0, :east
unit :wizard, 586, 0, :east
unit :archer, 588, 0, :east
unit :sludge, 589, 0, :east
unit :captive, 591, 0, :east
unit :thick_sludge, 592, 0, :east
unit :thick_sludge, 593, 0, :east
unit :sludge, 607, 0, :east
unit :archer, 611, 0, :east
unit :wizard, 613, 0, :east
unit :wizard, 615, 0, :east
unit :captive, 619, 0, :east
unit :thick_sludge, 624, 0, :east
unit :sludge, 626, 0, :east
unit :thick_sludge, 628, 0, :east
unit :thick_sludge, 630, 0, :east
unit :captive, 632, 0, :east
unit :captive, 636, 0, :east
unit :thick_sludge, 640, 0, :east
unit :archer, 642, 0, :east
unit :sludge, 650, 0, :east
unit :archer, 652, 0, :east
unit :thick_sludge, 653, 0, :east
unit :sludge, 656, 0, :east
unit :archer, 657, 0, :east
unit :captive, 662, 0, :east
unit :sludge, 665, 0, :east
unit :sludge, 667, 0, :east
unit :captive, 683, 0, :east
unit :sludge, 685, 0, :east
unit :sludge, 687, 0, :east
unit :thick_sludge, 688, 0, :east
unit :thick_sludge, 690, 0, :east
unit :wizard, 693, 0, :east
unit :thick_sludge, 698, 0, :east
unit :thick_sludge, 705, 0, :east
unit :archer, 709, 0, :east
unit :captive, 710, 0, :east
unit :thick_sludge, 717, 0, :east
unit :captive, 718, 0, :east
unit :archer, 728, 0, :east
unit :thick_sludge, 729, 0, :east
unit :sludge, 731, 0, :east
unit :wizard, 735, 0, :east
unit :archer, 743, 0, :east
unit :sludge, 744, 0, :east
unit :thick_sludge, 747, 0, :east
unit :archer, 752, 0, :east
unit :thick_sludge, 770, 0, :east
unit :captive, 784, 0, :east
unit :archer, 785, 0, :east
unit :thick_sludge, 790, 0, :east
unit :wizard, 796, 0, :east
unit :captive, 803, 0, :east
unit :thick_sludge, 804, 0, :east
unit :captive, 806, 0, :east
unit :sludge, 814, 0, :east
unit :sludge, 833, 0, :west
unit :thick_sludge, 837, 0, :west
unit :archer, 840, 0, :west
unit :archer, 841, 0, :west
unit :thick_sludge, 843, 0, :west
unit :archer, 845, 0, :west
unit :wizard, 846, 0, :west
unit :wizard, 864, 0, :west
unit :archer, 867, 0, :west
unit :archer, 871, 0, :west
unit :sludge, 874, 0, :west
unit :captive, 880, 0, :west
unit :wizard, 882, 0, :west
unit :archer, 884, 0, :west
unit :wizard, 886, 0, :west
unit :archer, 894, 0, :west
unit :wizard, 895, 0, :west
unit :sludge, 897, 0, :west
unit :sludge, 898, 0, :west
unit :sludge, 900, 0, :west
unit :wizard, 906, 0, :west
unit :thick_sludge, 909, 0, :west
unit :captive, 919, 0, :west
unit :wizard, 922, 0, :west
unit :captive, 926, 0, :west
unit :archer, 928, 0, :west
unit :sludge, 934, 0, :west
unit :captive, 942, 0, :west
unit :wizard, 944, 0, :west
unit :archer, 951, 0, :west
unit :captive, 954, 0, :west
unit :thick_sludge, 956, 0, :west
unit :captive, 965, 0, :west
unit :archer, 972, 0, :west
unit :archer, 973, 0, :west
unit :wizard, 978, 0, :west
