#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   w  s    sSS  C  w      w   aa   aS    w S            a   C  >  a   C   s  a S         a  w a C  s  S   a    a w s w sC C SC   sS Ssa w  aS    w   a  w  C           C   @       S     s          S SS        C C              s w s C  s   Cw wC   CS s w  s  C        w  aSS      w   S  aC S   s  a     aC      S C    C sS    w      a      as   s   s      w   a          S  ss  a  sws    Cw         s         s       C       s       a               a     s      w s   sC  s  C      a      a  S    aC          S  w  SC  w   w                       s    ws  S s s       S           S s   a  S    s s   w  SC s    wCsss    w Sa          C  w                 sa w SS    SCa       a   a            Saa   S   a   s  Cs |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 711
ace_score 3555
size 711, 1
stairs 63, 0

warrior 171, 0, :east

unit :wizard, 3, 0, :east
unit :sludge, 6, 0, :east
unit :sludge, 11, 0, :east
unit :thick_sludge, 12, 0, :east
unit :thick_sludge, 13, 0, :east
unit :captive, 16, 0, :east
unit :wizard, 19, 0, :east
unit :wizard, 26, 0, :east
unit :archer, 30, 0, :east
unit :archer, 31, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 36, 0, :east
unit :wizard, 41, 0, :east
unit :thick_sludge, 43, 0, :east
unit :archer, 56, 0, :east
unit :captive, 60, 0, :east
unit :archer, 66, 0, :east
unit :captive, 70, 0, :east
unit :sludge, 74, 0, :east
unit :archer, 77, 0, :east
unit :thick_sludge, 79, 0, :east
unit :archer, 89, 0, :east
unit :wizard, 92, 0, :east
unit :archer, 94, 0, :east
unit :captive, 96, 0, :east
unit :sludge, 99, 0, :east
unit :thick_sludge, 102, 0, :east
unit :archer, 106, 0, :east
unit :archer, 111, 0, :east
unit :wizard, 113, 0, :east
unit :sludge, 115, 0, :east
unit :wizard, 117, 0, :east
unit :sludge, 119, 0, :east
unit :captive, 120, 0, :east
unit :captive, 122, 0, :east
unit :thick_sludge, 124, 0, :east
unit :captive, 125, 0, :east
unit :sludge, 129, 0, :east
unit :thick_sludge, 130, 0, :east
unit :thick_sludge, 132, 0, :east
unit :sludge, 133, 0, :east
unit :archer, 134, 0, :east
unit :wizard, 136, 0, :east
unit :archer, 139, 0, :east
unit :thick_sludge, 140, 0, :east
unit :wizard, 145, 0, :east
unit :archer, 149, 0, :east
unit :wizard, 152, 0, :east
unit :captive, 155, 0, :east
unit :captive, 167, 0, :east
unit :thick_sludge, 179, 0, :west
unit :sludge, 185, 0, :west
unit :thick_sludge, 196, 0, :west
unit :thick_sludge, 198, 0, :west
unit :thick_sludge, 199, 0, :west
unit :captive, 208, 0, :west
unit :captive, 210, 0, :west
unit :sludge, 225, 0, :west
unit :wizard, 227, 0, :west
unit :sludge, 229, 0, :west
unit :captive, 231, 0, :west
unit :sludge, 234, 0, :west
unit :captive, 238, 0, :west
unit :wizard, 239, 0, :west
unit :wizard, 241, 0, :west
unit :captive, 242, 0, :west
unit :captive, 246, 0, :west
unit :thick_sludge, 247, 0, :west
unit :sludge, 249, 0, :west
unit :wizard, 251, 0, :west
unit :sludge, 254, 0, :west
unit :captive, 257, 0, :west
unit :wizard, 266, 0, :west
unit :archer, 269, 0, :west
unit :thick_sludge, 270, 0, :west
unit :thick_sludge, 271, 0, :west
unit :wizard, 278, 0, :west
unit :thick_sludge, 282, 0, :west
unit :archer, 285, 0, :west
unit :captive, 286, 0, :west
unit :thick_sludge, 288, 0, :west
unit :sludge, 292, 0, :west
unit :archer, 295, 0, :west
unit :archer, 301, 0, :west
unit :captive, 302, 0, :west
unit :thick_sludge, 309, 0, :west
unit :captive, 311, 0, :west
unit :captive, 316, 0, :west
unit :sludge, 318, 0, :west
unit :thick_sludge, 319, 0, :west
unit :wizard, 324, 0, :west
unit :archer, 331, 0, :west
unit :archer, 338, 0, :west
unit :sludge, 339, 0, :west
unit :sludge, 343, 0, :west
unit :sludge, 347, 0, :west
unit :wizard, 354, 0, :west
unit :archer, 358, 0, :west
unit :thick_sludge, 369, 0, :west
unit :sludge, 372, 0, :west
unit :sludge, 373, 0, :west
unit :archer, 376, 0, :west
unit :sludge, 379, 0, :west
unit :wizard, 380, 0, :west
unit :sludge, 381, 0, :west
unit :captive, 386, 0, :west
unit :wizard, 387, 0, :west
unit :sludge, 397, 0, :west
unit :sludge, 407, 0, :west
unit :captive, 415, 0, :west
unit :sludge, 423, 0, :west
unit :archer, 431, 0, :west
unit :archer, 447, 0, :west
unit :sludge, 453, 0, :west
unit :wizard, 460, 0, :west
unit :sludge, 462, 0, :west
unit :sludge, 466, 0, :west
unit :captive, 467, 0, :west
unit :sludge, 470, 0, :west
unit :captive, 473, 0, :west
unit :archer, 480, 0, :west
unit :archer, 487, 0, :west
unit :thick_sludge, 490, 0, :west
unit :archer, 495, 0, :west
unit :captive, 496, 0, :west
unit :thick_sludge, 507, 0, :west
unit :wizard, 510, 0, :west
unit :thick_sludge, 513, 0, :west
unit :captive, 514, 0, :west
unit :wizard, 517, 0, :west
unit :wizard, 521, 0, :west
unit :sludge, 545, 0, :west
unit :wizard, 550, 0, :west
unit :sludge, 551, 0, :west
unit :thick_sludge, 554, 0, :west
unit :sludge, 556, 0, :west
unit :sludge, 558, 0, :west
unit :thick_sludge, 566, 0, :west
unit :thick_sludge, 578, 0, :west
unit :sludge, 580, 0, :west
unit :archer, 584, 0, :west
unit :thick_sludge, 587, 0, :west
unit :sludge, 592, 0, :west
unit :sludge, 594, 0, :west
unit :wizard, 598, 0, :west
unit :thick_sludge, 601, 0, :west
unit :captive, 602, 0, :west
unit :sludge, 604, 0, :west
unit :wizard, 609, 0, :west
unit :captive, 610, 0, :west
unit :sludge, 611, 0, :west
unit :sludge, 612, 0, :west
unit :sludge, 613, 0, :west
unit :wizard, 618, 0, :west
unit :thick_sludge, 620, 0, :west
unit :archer, 621, 0, :west
unit :captive, 632, 0, :west
unit :wizard, 635, 0, :west
unit :sludge, 653, 0, :west
unit :archer, 654, 0, :west
unit :wizard, 656, 0, :west
unit :thick_sludge, 658, 0, :west
unit :thick_sludge, 659, 0, :west
unit :thick_sludge, 664, 0, :west
unit :captive, 665, 0, :west
unit :archer, 666, 0, :west
unit :archer, 674, 0, :west
unit :archer, 678, 0, :west
unit :thick_sludge, 691, 0, :west
unit :archer, 692, 0, :west
unit :archer, 693, 0, :west
unit :thick_sludge, 697, 0, :west
unit :archer, 701, 0, :west
unit :sludge, 705, 0, :west
unit :captive, 708, 0, :west
unit :sludge, 709, 0, :west
