#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a  w     a    C         a  Sw a w    S C               sC a w   a   C    sC  a    Ssss  S  w s  s     s   a S     w  ss sas a  asa s   w      w   w w S  S   S  as S a  S S  Cw     s      aS     s C        sS s     s      a C       a     Ss  C   a          C  S a     S     s s     a   CS w    S     a      as  a     aw Cw a   C     a  aa   C       w aC   S  S      s         C   S   w Cw   w  sa >  s SS wa S  Ss S  a       C S  a  S    sS SC     sCs      C         as   C     a  a    w  a s    w  sS           w        S   S a   sS C               w    a w S    s    a C w    S   a C       SC  sa        S        S          w    w  w wCs        S       SS   a  Sas  a    C C         C  S   s      a a        w  w       s    aa   as  s  a         C  wa     w         C  w     @   w      C  S      Ca S        sS  a  ss  S  C      C    w w            S   S  w      a   S      CS        S          a a           S     s        a  s   w    s S  S      S       S          |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 969
ace_score 4845
size 969, 1
stairs 397, 0

warrior 777, 0, :east

unit :archer, 1, 0, :east
unit :wizard, 4, 0, :east
unit :archer, 10, 0, :east
unit :captive, 15, 0, :east
unit :archer, 25, 0, :east
unit :thick_sludge, 28, 0, :east
unit :wizard, 29, 0, :east
unit :archer, 31, 0, :east
unit :wizard, 33, 0, :east
unit :thick_sludge, 38, 0, :east
unit :captive, 40, 0, :east
unit :sludge, 56, 0, :east
unit :captive, 57, 0, :east
unit :archer, 59, 0, :east
unit :wizard, 61, 0, :east
unit :archer, 65, 0, :east
unit :captive, 69, 0, :east
unit :sludge, 74, 0, :east
unit :captive, 75, 0, :east
unit :archer, 78, 0, :east
unit :thick_sludge, 83, 0, :east
unit :sludge, 84, 0, :east
unit :sludge, 85, 0, :east
unit :sludge, 86, 0, :east
unit :thick_sludge, 89, 0, :east
unit :wizard, 92, 0, :east
unit :sludge, 94, 0, :east
unit :sludge, 97, 0, :east
unit :sludge, 103, 0, :east
unit :archer, 107, 0, :east
unit :thick_sludge, 109, 0, :east
unit :wizard, 115, 0, :east
unit :sludge, 118, 0, :east
unit :sludge, 119, 0, :east
unit :sludge, 121, 0, :east
unit :archer, 122, 0, :east
unit :sludge, 123, 0, :east
unit :archer, 125, 0, :east
unit :archer, 128, 0, :east
unit :sludge, 129, 0, :east
unit :archer, 130, 0, :east
unit :sludge, 132, 0, :east
unit :wizard, 136, 0, :east
unit :wizard, 143, 0, :east
unit :wizard, 147, 0, :east
unit :wizard, 149, 0, :east
unit :thick_sludge, 151, 0, :east
unit :thick_sludge, 154, 0, :east
unit :thick_sludge, 158, 0, :east
unit :archer, 161, 0, :east
unit :sludge, 162, 0, :east
unit :thick_sludge, 164, 0, :east
unit :archer, 166, 0, :east
unit :thick_sludge, 169, 0, :east
unit :thick_sludge, 171, 0, :east
unit :captive, 174, 0, :east
unit :wizard, 175, 0, :east
unit :sludge, 181, 0, :east
unit :archer, 188, 0, :east
unit :thick_sludge, 189, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 197, 0, :east
unit :sludge, 206, 0, :east
unit :thick_sludge, 207, 0, :east
unit :sludge, 209, 0, :east
unit :sludge, 215, 0, :east
unit :archer, 222, 0, :east
unit :captive, 224, 0, :east
unit :archer, 232, 0, :east
unit :thick_sludge, 238, 0, :east
unit :sludge, 239, 0, :east
unit :captive, 242, 0, :east
unit :archer, 246, 0, :east
unit :captive, 257, 0, :east
unit :thick_sludge, 260, 0, :east
unit :archer, 262, 0, :east
unit :thick_sludge, 268, 0, :east
unit :sludge, 274, 0, :east
unit :sludge, 276, 0, :east
unit :archer, 282, 0, :east
unit :captive, 286, 0, :east
unit :thick_sludge, 287, 0, :east
unit :wizard, 289, 0, :east
unit :thick_sludge, 294, 0, :east
unit :archer, 300, 0, :east
unit :archer, 307, 0, :east
unit :sludge, 308, 0, :east
unit :archer, 311, 0, :east
unit :archer, 317, 0, :east
unit :wizard, 318, 0, :east
unit :captive, 320, 0, :east
unit :wizard, 321, 0, :east
unit :archer, 323, 0, :east
unit :captive, 327, 0, :east
unit :archer, 333, 0, :east
unit :archer, 336, 0, :east
unit :archer, 337, 0, :east
unit :captive, 341, 0, :east
unit :wizard, 349, 0, :east
unit :archer, 351, 0, :east
unit :captive, 352, 0, :east
unit :thick_sludge, 356, 0, :east
unit :thick_sludge, 359, 0, :east
unit :sludge, 366, 0, :east
unit :captive, 376, 0, :east
unit :thick_sludge, 380, 0, :east
unit :wizard, 384, 0, :east
unit :captive, 386, 0, :east
unit :wizard, 387, 0, :east
unit :wizard, 391, 0, :east
unit :sludge, 394, 0, :east
unit :archer, 395, 0, :east
unit :sludge, 400, 0, :east
unit :thick_sludge, 402, 0, :east
unit :thick_sludge, 403, 0, :east
unit :wizard, 405, 0, :east
unit :archer, 406, 0, :east
unit :thick_sludge, 408, 0, :east
unit :thick_sludge, 411, 0, :east
unit :sludge, 412, 0, :east
unit :thick_sludge, 414, 0, :east
unit :archer, 417, 0, :east
unit :captive, 425, 0, :east
unit :thick_sludge, 427, 0, :east
unit :archer, 430, 0, :east
unit :thick_sludge, 433, 0, :east
unit :sludge, 438, 0, :east
unit :thick_sludge, 439, 0, :east
unit :thick_sludge, 441, 0, :east
unit :captive, 442, 0, :east
unit :sludge, 448, 0, :east
unit :captive, 449, 0, :east
unit :sludge, 450, 0, :east
unit :captive, 457, 0, :east
unit :archer, 467, 0, :east
unit :sludge, 468, 0, :east
unit :captive, 472, 0, :east
unit :archer, 478, 0, :east
unit :archer, 481, 0, :east
unit :wizard, 486, 0, :east
unit :archer, 489, 0, :east
unit :sludge, 491, 0, :east
unit :wizard, 496, 0, :east
unit :sludge, 499, 0, :east
unit :thick_sludge, 500, 0, :east
unit :wizard, 512, 0, :east
unit :thick_sludge, 521, 0, :east
unit :thick_sludge, 525, 0, :east
unit :archer, 527, 0, :east
unit :sludge, 531, 0, :east
unit :thick_sludge, 532, 0, :east
unit :captive, 534, 0, :east
unit :wizard, 550, 0, :east
unit :archer, 555, 0, :east
unit :wizard, 557, 0, :east
unit :thick_sludge, 559, 0, :east
unit :sludge, 564, 0, :east
unit :archer, 569, 0, :east
unit :captive, 571, 0, :east
unit :wizard, 573, 0, :east
unit :thick_sludge, 578, 0, :east
unit :archer, 582, 0, :east
unit :captive, 584, 0, :east
unit :thick_sludge, 592, 0, :east
unit :captive, 593, 0, :east
unit :sludge, 596, 0, :east
unit :archer, 597, 0, :east
unit :thick_sludge, 606, 0, :east
unit :thick_sludge, 615, 0, :east
unit :wizard, 626, 0, :east
unit :wizard, 631, 0, :east
unit :wizard, 634, 0, :east
unit :wizard, 636, 0, :east
unit :captive, 637, 0, :east
unit :sludge, 638, 0, :east
unit :thick_sludge, 647, 0, :east
unit :thick_sludge, 655, 0, :east
unit :thick_sludge, 656, 0, :east
unit :archer, 660, 0, :east
unit :thick_sludge, 663, 0, :east
unit :archer, 664, 0, :east
unit :sludge, 665, 0, :east
unit :archer, 668, 0, :east
unit :captive, 673, 0, :east
unit :captive, 675, 0, :east
unit :captive, 685, 0, :east
unit :thick_sludge, 688, 0, :east
unit :sludge, 692, 0, :east
unit :archer, 699, 0, :east
unit :archer, 701, 0, :east
unit :wizard, 710, 0, :east
unit :wizard, 713, 0, :east
unit :sludge, 721, 0, :east
unit :archer, 726, 0, :east
unit :archer, 727, 0, :east
unit :archer, 731, 0, :east
unit :sludge, 732, 0, :east
unit :sludge, 735, 0, :east
unit :archer, 738, 0, :east
unit :captive, 748, 0, :east
unit :wizard, 751, 0, :east
unit :archer, 752, 0, :east
unit :wizard, 758, 0, :east
unit :captive, 768, 0, :east
unit :wizard, 771, 0, :east
unit :wizard, 781, 0, :west
unit :captive, 788, 0, :west
unit :thick_sludge, 791, 0, :west
unit :captive, 798, 0, :west
unit :archer, 799, 0, :west
unit :thick_sludge, 801, 0, :west
unit :sludge, 810, 0, :west
unit :thick_sludge, 811, 0, :west
unit :archer, 814, 0, :west
unit :sludge, 817, 0, :west
unit :sludge, 818, 0, :west
unit :thick_sludge, 821, 0, :west
unit :captive, 824, 0, :west
unit :captive, 831, 0, :west
unit :wizard, 836, 0, :west
unit :wizard, 838, 0, :west
unit :thick_sludge, 851, 0, :west
unit :thick_sludge, 855, 0, :west
unit :wizard, 858, 0, :west
unit :archer, 865, 0, :west
unit :thick_sludge, 869, 0, :west
unit :captive, 876, 0, :west
unit :thick_sludge, 877, 0, :west
unit :thick_sludge, 886, 0, :west
unit :archer, 897, 0, :west
unit :archer, 899, 0, :west
unit :thick_sludge, 911, 0, :west
unit :sludge, 917, 0, :west
unit :archer, 926, 0, :west
unit :sludge, 929, 0, :west
unit :wizard, 933, 0, :west
unit :sludge, 938, 0, :west
unit :thick_sludge, 940, 0, :west
unit :thick_sludge, 943, 0, :west
unit :thick_sludge, 950, 0, :west
unit :thick_sludge, 958, 0, :west
