#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C w       a   s    s  S    sw      s S w  s   C      a           a  aCs       s    CS       sC    a  s          C    w  s        w    sC C C C  C       a  CC  s     aa C          C    S  S      w a   w  a        Ca  SC  s   w   S w   a     S       ss S     C  SS  S  CCS  ss           CC  >Ca    S    sw   a    w  S             a                 S    C  Sw  a     S s  C                  a C s w C   saC Cs     a    sCs        s Cs S S    C       C Ca   sa         SC a   w         C   C C   a    SaC    a    SC    SaC    SS           Sss   Sa a          @  a s     w    sw  s             a   C   w       C s         CS C     S w   w       S S a as a       s ss S    s        C       S |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 688
ace_score 3440
size 688, 1
stairs 291, 0

warrior 557, 0, :east

unit :captive, 2, 0, :east
unit :wizard, 4, 0, :east
unit :archer, 12, 0, :east
unit :sludge, 16, 0, :east
unit :sludge, 21, 0, :east
unit :thick_sludge, 24, 0, :east
unit :sludge, 29, 0, :east
unit :wizard, 30, 0, :east
unit :sludge, 37, 0, :east
unit :thick_sludge, 39, 0, :east
unit :wizard, 41, 0, :east
unit :sludge, 44, 0, :east
unit :captive, 48, 0, :east
unit :archer, 55, 0, :east
unit :archer, 67, 0, :east
unit :archer, 70, 0, :east
unit :captive, 71, 0, :east
unit :sludge, 72, 0, :east
unit :sludge, 80, 0, :east
unit :captive, 85, 0, :east
unit :thick_sludge, 86, 0, :east
unit :sludge, 94, 0, :east
unit :captive, 95, 0, :east
unit :archer, 100, 0, :east
unit :sludge, 103, 0, :east
unit :captive, 114, 0, :east
unit :wizard, 119, 0, :east
unit :sludge, 122, 0, :east
unit :wizard, 131, 0, :east
unit :sludge, 136, 0, :east
unit :captive, 137, 0, :east
unit :captive, 139, 0, :east
unit :captive, 141, 0, :east
unit :captive, 143, 0, :east
unit :captive, 146, 0, :east
unit :archer, 154, 0, :east
unit :captive, 157, 0, :east
unit :captive, 158, 0, :east
unit :sludge, 161, 0, :east
unit :archer, 167, 0, :east
unit :archer, 168, 0, :east
unit :captive, 170, 0, :east
unit :captive, 181, 0, :east
unit :thick_sludge, 186, 0, :east
unit :thick_sludge, 189, 0, :east
unit :wizard, 196, 0, :east
unit :archer, 198, 0, :east
unit :wizard, 202, 0, :east
unit :archer, 205, 0, :east
unit :captive, 214, 0, :east
unit :archer, 215, 0, :east
unit :thick_sludge, 218, 0, :east
unit :captive, 219, 0, :east
unit :sludge, 222, 0, :east
unit :wizard, 226, 0, :east
unit :thick_sludge, 230, 0, :east
unit :wizard, 232, 0, :east
unit :archer, 236, 0, :east
unit :thick_sludge, 242, 0, :east
unit :sludge, 250, 0, :east
unit :sludge, 251, 0, :east
unit :thick_sludge, 253, 0, :east
unit :captive, 259, 0, :east
unit :thick_sludge, 262, 0, :east
unit :thick_sludge, 263, 0, :east
unit :thick_sludge, 266, 0, :east
unit :captive, 269, 0, :east
unit :captive, 270, 0, :east
unit :thick_sludge, 271, 0, :east
unit :sludge, 274, 0, :east
unit :sludge, 275, 0, :east
unit :captive, 287, 0, :east
unit :captive, 288, 0, :east
unit :captive, 292, 0, :east
unit :archer, 293, 0, :east
unit :thick_sludge, 298, 0, :east
unit :sludge, 303, 0, :east
unit :wizard, 304, 0, :east
unit :archer, 308, 0, :east
unit :wizard, 313, 0, :east
unit :thick_sludge, 316, 0, :east
unit :archer, 330, 0, :east
unit :thick_sludge, 348, 0, :east
unit :captive, 353, 0, :east
unit :thick_sludge, 356, 0, :east
unit :wizard, 357, 0, :east
unit :archer, 360, 0, :east
unit :thick_sludge, 366, 0, :east
unit :sludge, 368, 0, :east
unit :captive, 371, 0, :east
unit :archer, 390, 0, :east
unit :captive, 392, 0, :east
unit :sludge, 394, 0, :east
unit :wizard, 396, 0, :east
unit :captive, 398, 0, :east
unit :sludge, 402, 0, :east
unit :archer, 403, 0, :east
unit :captive, 404, 0, :east
unit :captive, 406, 0, :east
unit :sludge, 407, 0, :east
unit :archer, 413, 0, :east
unit :sludge, 418, 0, :east
unit :captive, 419, 0, :east
unit :sludge, 420, 0, :east
unit :sludge, 429, 0, :east
unit :captive, 431, 0, :east
unit :sludge, 432, 0, :east
unit :thick_sludge, 434, 0, :east
unit :thick_sludge, 436, 0, :east
unit :captive, 441, 0, :east
unit :captive, 449, 0, :east
unit :captive, 451, 0, :east
unit :archer, 452, 0, :east
unit :sludge, 456, 0, :east
unit :archer, 457, 0, :east
unit :thick_sludge, 467, 0, :east
unit :captive, 468, 0, :east
unit :archer, 470, 0, :east
unit :wizard, 474, 0, :east
unit :captive, 484, 0, :east
unit :captive, 488, 0, :east
unit :captive, 490, 0, :east
unit :archer, 494, 0, :east
unit :thick_sludge, 499, 0, :east
unit :archer, 500, 0, :east
unit :captive, 501, 0, :east
unit :archer, 506, 0, :east
unit :thick_sludge, 511, 0, :east
unit :captive, 512, 0, :east
unit :thick_sludge, 517, 0, :east
unit :archer, 518, 0, :east
unit :captive, 519, 0, :east
unit :thick_sludge, 524, 0, :east
unit :thick_sludge, 525, 0, :east
unit :thick_sludge, 537, 0, :east
unit :sludge, 538, 0, :east
unit :sludge, 539, 0, :east
unit :thick_sludge, 543, 0, :east
unit :archer, 544, 0, :east
unit :archer, 546, 0, :east
unit :archer, 560, 0, :west
unit :sludge, 562, 0, :west
unit :wizard, 568, 0, :west
unit :sludge, 573, 0, :west
unit :wizard, 574, 0, :west
unit :sludge, 577, 0, :west
unit :archer, 591, 0, :west
unit :captive, 595, 0, :west
unit :wizard, 599, 0, :west
unit :captive, 607, 0, :west
unit :sludge, 609, 0, :west
unit :captive, 619, 0, :west
unit :thick_sludge, 620, 0, :west
unit :captive, 622, 0, :west
unit :thick_sludge, 628, 0, :west
unit :wizard, 630, 0, :west
unit :wizard, 634, 0, :west
unit :thick_sludge, 642, 0, :west
unit :thick_sludge, 644, 0, :west
unit :archer, 646, 0, :west
unit :archer, 648, 0, :west
unit :sludge, 649, 0, :west
unit :archer, 651, 0, :west
unit :sludge, 659, 0, :west
unit :sludge, 661, 0, :west
unit :sludge, 662, 0, :west
unit :thick_sludge, 664, 0, :west
unit :sludge, 669, 0, :west
unit :captive, 678, 0, :west
unit :thick_sludge, 686, 0, :west
