#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a     S  S s  ss           Ca   a    a     ssC            SSa       S  a    as   aa S CC  S C      wC C  sa  S C C  s a aC           a  a       w  s s       Ca         S  C SS    w           a        s   s sw wSC               w    C   C   a     s      w        C aa a  S    a    saC  a w w     S  w      s s   SC    S  w w   w  S    s s   C s  C               Ss           a      a     s   S             aa wa    w      S         S  S a    S                w    a C    s s s            S  s  S      w   s C        s  S     C       w        a aC w w  s    w s       S            S   aS    S C  as  s   S   s      C                  w    C    @  C S    sa  a    s  a        a  S S S  C   C  s s       ss   sC s w   Sa  a    w     w   C  SS SS     w s       C S sw      C    S  s           s  w  a SC s        a S   > CSsSS a      w       C  C    w    s   ss        CC   a    C  C  C   aCS    SsS ss    C w   a w w   |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 916
ace_score 4580
size 916, 1
stairs 815, 0

warrior 643, 0, :east

unit :archer, 1, 0, :east
unit :thick_sludge, 7, 0, :east
unit :thick_sludge, 10, 0, :east
unit :sludge, 12, 0, :east
unit :sludge, 15, 0, :east
unit :sludge, 16, 0, :east
unit :captive, 28, 0, :east
unit :archer, 29, 0, :east
unit :archer, 33, 0, :east
unit :archer, 38, 0, :east
unit :sludge, 44, 0, :east
unit :sludge, 45, 0, :east
unit :captive, 46, 0, :east
unit :thick_sludge, 59, 0, :east
unit :thick_sludge, 60, 0, :east
unit :archer, 61, 0, :east
unit :thick_sludge, 69, 0, :east
unit :archer, 72, 0, :east
unit :archer, 77, 0, :east
unit :sludge, 78, 0, :east
unit :archer, 82, 0, :east
unit :archer, 83, 0, :east
unit :thick_sludge, 85, 0, :east
unit :captive, 87, 0, :east
unit :captive, 88, 0, :east
unit :thick_sludge, 91, 0, :east
unit :captive, 93, 0, :east
unit :wizard, 100, 0, :east
unit :captive, 101, 0, :east
unit :captive, 103, 0, :east
unit :sludge, 106, 0, :east
unit :archer, 107, 0, :east
unit :thick_sludge, 110, 0, :east
unit :captive, 112, 0, :east
unit :captive, 114, 0, :east
unit :sludge, 117, 0, :east
unit :archer, 119, 0, :east
unit :archer, 121, 0, :east
unit :captive, 122, 0, :east
unit :archer, 134, 0, :east
unit :archer, 137, 0, :east
unit :wizard, 145, 0, :east
unit :sludge, 148, 0, :east
unit :sludge, 150, 0, :east
unit :captive, 158, 0, :east
unit :archer, 159, 0, :east
unit :thick_sludge, 169, 0, :east
unit :captive, 172, 0, :east
unit :thick_sludge, 174, 0, :east
unit :thick_sludge, 175, 0, :east
unit :wizard, 180, 0, :east
unit :archer, 192, 0, :east
unit :sludge, 201, 0, :east
unit :sludge, 205, 0, :east
unit :sludge, 207, 0, :east
unit :wizard, 208, 0, :east
unit :wizard, 210, 0, :east
unit :thick_sludge, 211, 0, :east
unit :captive, 212, 0, :east
unit :wizard, 228, 0, :east
unit :captive, 233, 0, :east
unit :captive, 237, 0, :east
unit :archer, 241, 0, :east
unit :sludge, 247, 0, :east
unit :wizard, 254, 0, :east
unit :captive, 263, 0, :east
unit :archer, 265, 0, :east
unit :archer, 266, 0, :east
unit :archer, 268, 0, :east
unit :thick_sludge, 271, 0, :east
unit :archer, 276, 0, :east
unit :sludge, 281, 0, :east
unit :archer, 282, 0, :east
unit :captive, 283, 0, :east
unit :archer, 286, 0, :east
unit :wizard, 288, 0, :east
unit :wizard, 290, 0, :east
unit :thick_sludge, 296, 0, :east
unit :wizard, 299, 0, :east
unit :sludge, 306, 0, :east
unit :sludge, 308, 0, :east
unit :thick_sludge, 312, 0, :east
unit :captive, 313, 0, :east
unit :thick_sludge, 318, 0, :east
unit :wizard, 321, 0, :east
unit :wizard, 323, 0, :east
unit :wizard, 327, 0, :east
unit :thick_sludge, 330, 0, :east
unit :sludge, 335, 0, :east
unit :sludge, 337, 0, :east
unit :captive, 341, 0, :east
unit :sludge, 343, 0, :east
unit :captive, 346, 0, :east
unit :thick_sludge, 362, 0, :east
unit :sludge, 363, 0, :east
unit :archer, 375, 0, :east
unit :archer, 382, 0, :east
unit :sludge, 388, 0, :east
unit :thick_sludge, 392, 0, :east
unit :archer, 406, 0, :east
unit :archer, 407, 0, :east
unit :wizard, 409, 0, :east
unit :archer, 410, 0, :east
unit :wizard, 415, 0, :east
unit :thick_sludge, 422, 0, :east
unit :thick_sludge, 432, 0, :east
unit :thick_sludge, 435, 0, :east
unit :archer, 437, 0, :east
unit :thick_sludge, 442, 0, :east
unit :wizard, 459, 0, :east
unit :archer, 464, 0, :east
unit :captive, 466, 0, :east
unit :sludge, 471, 0, :east
unit :sludge, 473, 0, :east
unit :sludge, 475, 0, :east
unit :thick_sludge, 488, 0, :east
unit :sludge, 491, 0, :east
unit :thick_sludge, 494, 0, :east
unit :wizard, 501, 0, :east
unit :sludge, 505, 0, :east
unit :captive, 507, 0, :east
unit :sludge, 516, 0, :east
unit :thick_sludge, 519, 0, :east
unit :captive, 525, 0, :east
unit :wizard, 533, 0, :east
unit :archer, 542, 0, :east
unit :archer, 544, 0, :east
unit :captive, 545, 0, :east
unit :wizard, 547, 0, :east
unit :wizard, 549, 0, :east
unit :sludge, 552, 0, :east
unit :wizard, 557, 0, :east
unit :sludge, 559, 0, :east
unit :thick_sludge, 567, 0, :east
unit :thick_sludge, 580, 0, :east
unit :archer, 584, 0, :east
unit :thick_sludge, 585, 0, :east
unit :thick_sludge, 590, 0, :east
unit :captive, 592, 0, :east
unit :archer, 595, 0, :east
unit :sludge, 596, 0, :east
unit :sludge, 599, 0, :east
unit :thick_sludge, 603, 0, :east
unit :sludge, 607, 0, :east
unit :captive, 614, 0, :east
unit :wizard, 633, 0, :east
unit :captive, 638, 0, :east
unit :captive, 646, 0, :west
unit :thick_sludge, 648, 0, :west
unit :sludge, 653, 0, :west
unit :archer, 654, 0, :west
unit :archer, 657, 0, :west
unit :sludge, 662, 0, :west
unit :archer, 665, 0, :west
unit :archer, 674, 0, :west
unit :thick_sludge, 677, 0, :west
unit :thick_sludge, 679, 0, :west
unit :thick_sludge, 681, 0, :west
unit :captive, 684, 0, :west
unit :captive, 688, 0, :west
unit :sludge, 691, 0, :west
unit :sludge, 693, 0, :west
unit :sludge, 701, 0, :west
unit :sludge, 702, 0, :west
unit :sludge, 706, 0, :west
unit :captive, 707, 0, :west
unit :sludge, 709, 0, :west
unit :wizard, 711, 0, :west
unit :thick_sludge, 715, 0, :west
unit :archer, 716, 0, :west
unit :archer, 719, 0, :west
unit :wizard, 724, 0, :west
unit :wizard, 730, 0, :west
unit :captive, 734, 0, :west
unit :thick_sludge, 737, 0, :west
unit :thick_sludge, 738, 0, :west
unit :thick_sludge, 740, 0, :west
unit :thick_sludge, 741, 0, :west
unit :wizard, 747, 0, :west
unit :sludge, 749, 0, :west
unit :captive, 757, 0, :west
unit :thick_sludge, 759, 0, :west
unit :sludge, 761, 0, :west
unit :wizard, 762, 0, :west
unit :captive, 769, 0, :west
unit :thick_sludge, 774, 0, :west
unit :sludge, 777, 0, :west
unit :sludge, 789, 0, :west
unit :wizard, 792, 0, :west
unit :archer, 795, 0, :west
unit :thick_sludge, 797, 0, :west
unit :captive, 798, 0, :west
unit :sludge, 800, 0, :west
unit :archer, 809, 0, :west
unit :thick_sludge, 811, 0, :west
unit :captive, 817, 0, :west
unit :thick_sludge, 818, 0, :west
unit :sludge, 819, 0, :west
unit :thick_sludge, 820, 0, :west
unit :thick_sludge, 821, 0, :west
unit :archer, 823, 0, :west
unit :wizard, 830, 0, :west
unit :captive, 838, 0, :west
unit :captive, 841, 0, :west
unit :wizard, 846, 0, :west
unit :sludge, 851, 0, :west
unit :sludge, 855, 0, :west
unit :sludge, 856, 0, :west
unit :captive, 865, 0, :west
unit :captive, 866, 0, :west
unit :archer, 870, 0, :west
unit :captive, 875, 0, :west
unit :captive, 878, 0, :west
unit :captive, 881, 0, :west
unit :archer, 885, 0, :west
unit :captive, 886, 0, :west
unit :thick_sludge, 887, 0, :west
unit :thick_sludge, 892, 0, :west
unit :sludge, 893, 0, :west
unit :thick_sludge, 894, 0, :west
unit :sludge, 896, 0, :west
unit :sludge, 897, 0, :west
unit :captive, 902, 0, :west
unit :wizard, 904, 0, :west
unit :archer, 908, 0, :west
unit :wizard, 910, 0, :west
unit :wizard, 912, 0, :west
