#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | s  wC S   S                S sw s  C                S      s    a                  S       C Csa w       w  w  a w   SC  w s  S   C  w   s           C s   w       C    s    w   s   w aaC  @         w  S  ssC    w        aw  S S     w w       ws      S  C s         a sS a     w      C      a sS     w      C   S   S  w   ss   C  aSs    sC C  C  Ca         a C     aw   SC       s          C w   SS     w    CsS    s  sC  C     w w    aws  wC C    w    s                   Sa  Csa   S w C                    wC   S C   w       C CS         C      C     S   C S        w     >sC     C w              w        s   a S C  a   Ca    a             a CSsC       w  sC     Cs  sS   a          w S    a  a a sC   s a  a s s    a w C    aw a    s   w      S a       s   aa  as   s a C  S        a C     S  Sa    wS   S ws a  C  S  a     aS S             s         s     S  CS    a   w S |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 878
ace_score 4390
size 878, 1
stairs 574, 0

warrior 189, 0, :east

unit :sludge, 1, 0, :east
unit :wizard, 4, 0, :east
unit :captive, 5, 0, :east
unit :thick_sludge, 7, 0, :east
unit :thick_sludge, 11, 0, :east
unit :thick_sludge, 28, 0, :east
unit :sludge, 30, 0, :east
unit :wizard, 31, 0, :east
unit :sludge, 33, 0, :east
unit :captive, 36, 0, :east
unit :thick_sludge, 53, 0, :east
unit :sludge, 60, 0, :east
unit :archer, 65, 0, :east
unit :thick_sludge, 84, 0, :east
unit :captive, 92, 0, :east
unit :captive, 94, 0, :east
unit :sludge, 95, 0, :east
unit :archer, 96, 0, :east
unit :wizard, 98, 0, :east
unit :wizard, 106, 0, :east
unit :wizard, 109, 0, :east
unit :archer, 112, 0, :east
unit :wizard, 114, 0, :east
unit :thick_sludge, 118, 0, :east
unit :captive, 119, 0, :east
unit :wizard, 122, 0, :east
unit :sludge, 124, 0, :east
unit :thick_sludge, 127, 0, :east
unit :captive, 131, 0, :east
unit :wizard, 134, 0, :east
unit :sludge, 138, 0, :east
unit :captive, 150, 0, :east
unit :sludge, 152, 0, :east
unit :wizard, 156, 0, :east
unit :captive, 164, 0, :east
unit :sludge, 169, 0, :east
unit :wizard, 174, 0, :east
unit :sludge, 178, 0, :east
unit :wizard, 182, 0, :east
unit :archer, 184, 0, :east
unit :archer, 185, 0, :east
unit :captive, 186, 0, :east
unit :wizard, 199, 0, :west
unit :thick_sludge, 202, 0, :west
unit :sludge, 205, 0, :west
unit :sludge, 206, 0, :west
unit :captive, 207, 0, :west
unit :wizard, 212, 0, :west
unit :archer, 221, 0, :west
unit :wizard, 222, 0, :west
unit :thick_sludge, 225, 0, :west
unit :thick_sludge, 227, 0, :west
unit :wizard, 233, 0, :west
unit :wizard, 235, 0, :west
unit :wizard, 243, 0, :west
unit :sludge, 244, 0, :west
unit :thick_sludge, 251, 0, :west
unit :captive, 254, 0, :west
unit :sludge, 256, 0, :west
unit :archer, 266, 0, :west
unit :sludge, 268, 0, :west
unit :thick_sludge, 269, 0, :west
unit :archer, 271, 0, :west
unit :wizard, 277, 0, :west
unit :captive, 284, 0, :west
unit :archer, 291, 0, :west
unit :sludge, 293, 0, :west
unit :thick_sludge, 294, 0, :west
unit :wizard, 300, 0, :west
unit :captive, 307, 0, :west
unit :thick_sludge, 311, 0, :west
unit :thick_sludge, 315, 0, :west
unit :wizard, 318, 0, :west
unit :sludge, 322, 0, :west
unit :sludge, 323, 0, :west
unit :captive, 327, 0, :west
unit :archer, 330, 0, :west
unit :thick_sludge, 331, 0, :west
unit :sludge, 332, 0, :west
unit :sludge, 337, 0, :west
unit :captive, 338, 0, :west
unit :captive, 340, 0, :west
unit :captive, 343, 0, :west
unit :captive, 346, 0, :west
unit :archer, 347, 0, :west
unit :archer, 357, 0, :west
unit :captive, 359, 0, :west
unit :archer, 365, 0, :west
unit :wizard, 366, 0, :west
unit :thick_sludge, 370, 0, :west
unit :captive, 371, 0, :west
unit :sludge, 379, 0, :west
unit :captive, 390, 0, :west
unit :wizard, 392, 0, :west
unit :thick_sludge, 396, 0, :west
unit :thick_sludge, 397, 0, :west
unit :wizard, 403, 0, :west
unit :captive, 408, 0, :west
unit :sludge, 409, 0, :west
unit :thick_sludge, 410, 0, :west
unit :sludge, 415, 0, :west
unit :sludge, 418, 0, :west
unit :captive, 419, 0, :west
unit :captive, 422, 0, :west
unit :wizard, 428, 0, :west
unit :wizard, 430, 0, :west
unit :archer, 435, 0, :west
unit :wizard, 436, 0, :west
unit :sludge, 437, 0, :west
unit :wizard, 440, 0, :west
unit :captive, 441, 0, :west
unit :captive, 443, 0, :west
unit :wizard, 448, 0, :west
unit :sludge, 453, 0, :west
unit :thick_sludge, 473, 0, :west
unit :archer, 474, 0, :west
unit :captive, 477, 0, :west
unit :sludge, 478, 0, :west
unit :archer, 479, 0, :west
unit :thick_sludge, 483, 0, :west
unit :wizard, 485, 0, :west
unit :captive, 487, 0, :west
unit :wizard, 508, 0, :west
unit :captive, 509, 0, :west
unit :thick_sludge, 513, 0, :west
unit :captive, 515, 0, :west
unit :wizard, 519, 0, :west
unit :captive, 527, 0, :west
unit :captive, 529, 0, :west
unit :thick_sludge, 530, 0, :west
unit :captive, 540, 0, :west
unit :captive, 547, 0, :west
unit :thick_sludge, 553, 0, :west
unit :captive, 557, 0, :west
unit :thick_sludge, 559, 0, :west
unit :wizard, 568, 0, :west
unit :sludge, 575, 0, :west
unit :captive, 576, 0, :west
unit :captive, 582, 0, :west
unit :wizard, 584, 0, :west
unit :wizard, 599, 0, :west
unit :sludge, 608, 0, :west
unit :archer, 612, 0, :west
unit :thick_sludge, 614, 0, :west
unit :captive, 616, 0, :west
unit :archer, 619, 0, :west
unit :captive, 623, 0, :west
unit :archer, 624, 0, :west
unit :archer, 629, 0, :west
unit :archer, 643, 0, :west
unit :captive, 645, 0, :west
unit :thick_sludge, 646, 0, :west
unit :sludge, 647, 0, :west
unit :captive, 648, 0, :west
unit :wizard, 656, 0, :west
unit :sludge, 659, 0, :west
unit :captive, 660, 0, :west
unit :captive, 666, 0, :west
unit :sludge, 667, 0, :west
unit :sludge, 670, 0, :west
unit :thick_sludge, 671, 0, :west
unit :archer, 675, 0, :west
unit :wizard, 686, 0, :west
unit :thick_sludge, 688, 0, :west
unit :archer, 693, 0, :west
unit :archer, 696, 0, :west
unit :archer, 698, 0, :west
unit :sludge, 700, 0, :west
unit :captive, 701, 0, :west
unit :sludge, 705, 0, :west
unit :archer, 707, 0, :west
unit :archer, 710, 0, :west
unit :sludge, 712, 0, :west
unit :sludge, 714, 0, :west
unit :archer, 719, 0, :west
unit :wizard, 721, 0, :west
unit :captive, 723, 0, :west
unit :archer, 728, 0, :west
unit :wizard, 729, 0, :west
unit :archer, 731, 0, :west
unit :sludge, 736, 0, :west
unit :wizard, 740, 0, :west
unit :thick_sludge, 747, 0, :west
unit :archer, 749, 0, :west
unit :sludge, 757, 0, :west
unit :archer, 761, 0, :west
unit :archer, 762, 0, :west
unit :archer, 765, 0, :west
unit :sludge, 766, 0, :west
unit :sludge, 770, 0, :west
unit :archer, 772, 0, :west
unit :captive, 774, 0, :west
unit :thick_sludge, 777, 0, :west
unit :archer, 786, 0, :west
unit :captive, 788, 0, :west
unit :thick_sludge, 794, 0, :west
unit :thick_sludge, 797, 0, :west
unit :archer, 798, 0, :west
unit :wizard, 803, 0, :west
unit :thick_sludge, 804, 0, :west
unit :thick_sludge, 808, 0, :west
unit :wizard, 810, 0, :west
unit :sludge, 811, 0, :west
unit :archer, 813, 0, :west
unit :captive, 816, 0, :west
unit :thick_sludge, 819, 0, :west
unit :archer, 822, 0, :west
unit :archer, 828, 0, :west
unit :thick_sludge, 829, 0, :west
unit :thick_sludge, 831, 0, :west
unit :sludge, 845, 0, :west
unit :sludge, 855, 0, :west
unit :thick_sludge, 861, 0, :west
unit :captive, 864, 0, :west
unit :thick_sludge, 865, 0, :west
unit :archer, 870, 0, :west
unit :wizard, 874, 0, :west
unit :thick_sludge, 876, 0, :west
