#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      a         s  Sa> s  w     aS    w C  CS       w   s w  w  a  a  Cw           s  s  sC  s   C       w   w   C a  S       s    C w C      SSw       ssss sS S a  @    w      wC  C   C s a     S   w  s          a    sS  w w  CS      a s   w   C  s   C   C    s  w    s     S  S        s        S    s      Ss  C     C  s            C   C      w      S w   C sCa  Cs  S S       w s         S S     S    s  w  s   S   a       s  as   s C      SC    C           C C  C         C   w Sa w   a     C   a        SS C s       C   C C    aC   s s  s    Csa      w  s    C          aS   a   a      C  w     s  C w  s wC  w     s       C   w   C  C   wS   S    a          s          a     w s        a    a  a    w  Ssa      S         a      S s      s s    s  s   w    S Sw w     S   a  Ss          a  s  s         S       SwCas      C    S     CS      Ca  a a  S aS             s w  C  C w   s  C   Ss      S s  w|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 907
ace_score 4535
size 907, 1
stairs 21, 0

warrior 165, 0, :east

unit :archer, 6, 0, :east
unit :sludge, 16, 0, :east
unit :thick_sludge, 19, 0, :east
unit :archer, 20, 0, :east
unit :sludge, 23, 0, :east
unit :wizard, 26, 0, :east
unit :archer, 32, 0, :east
unit :thick_sludge, 33, 0, :east
unit :wizard, 38, 0, :east
unit :captive, 40, 0, :east
unit :captive, 43, 0, :east
unit :thick_sludge, 44, 0, :east
unit :wizard, 52, 0, :east
unit :sludge, 56, 0, :east
unit :wizard, 58, 0, :east
unit :wizard, 61, 0, :east
unit :archer, 64, 0, :east
unit :archer, 67, 0, :east
unit :captive, 70, 0, :east
unit :wizard, 71, 0, :east
unit :sludge, 83, 0, :east
unit :sludge, 86, 0, :east
unit :sludge, 89, 0, :east
unit :captive, 90, 0, :east
unit :sludge, 93, 0, :east
unit :captive, 97, 0, :east
unit :wizard, 105, 0, :east
unit :wizard, 109, 0, :east
unit :captive, 113, 0, :east
unit :archer, 115, 0, :east
unit :thick_sludge, 118, 0, :east
unit :sludge, 126, 0, :east
unit :captive, 131, 0, :east
unit :wizard, 133, 0, :east
unit :captive, 135, 0, :east
unit :thick_sludge, 142, 0, :east
unit :thick_sludge, 143, 0, :east
unit :wizard, 144, 0, :east
unit :sludge, 152, 0, :east
unit :sludge, 153, 0, :east
unit :sludge, 154, 0, :east
unit :sludge, 155, 0, :east
unit :sludge, 157, 0, :east
unit :thick_sludge, 158, 0, :east
unit :thick_sludge, 160, 0, :east
unit :archer, 162, 0, :east
unit :wizard, 170, 0, :west
unit :wizard, 177, 0, :west
unit :captive, 178, 0, :west
unit :captive, 181, 0, :west
unit :captive, 185, 0, :west
unit :sludge, 187, 0, :west
unit :archer, 189, 0, :west
unit :thick_sludge, 195, 0, :west
unit :wizard, 199, 0, :west
unit :sludge, 202, 0, :west
unit :archer, 213, 0, :west
unit :sludge, 218, 0, :west
unit :thick_sludge, 219, 0, :west
unit :wizard, 222, 0, :west
unit :wizard, 224, 0, :west
unit :captive, 227, 0, :west
unit :thick_sludge, 228, 0, :west
unit :archer, 235, 0, :west
unit :sludge, 237, 0, :west
unit :wizard, 241, 0, :west
unit :captive, 245, 0, :west
unit :sludge, 248, 0, :west
unit :captive, 252, 0, :west
unit :captive, 256, 0, :west
unit :sludge, 261, 0, :west
unit :wizard, 264, 0, :west
unit :sludge, 269, 0, :west
unit :thick_sludge, 275, 0, :west
unit :thick_sludge, 278, 0, :west
unit :sludge, 287, 0, :west
unit :thick_sludge, 296, 0, :west
unit :sludge, 301, 0, :west
unit :thick_sludge, 308, 0, :west
unit :sludge, 309, 0, :west
unit :captive, 312, 0, :west
unit :captive, 318, 0, :west
unit :sludge, 321, 0, :west
unit :captive, 334, 0, :west
unit :captive, 338, 0, :west
unit :wizard, 345, 0, :west
unit :thick_sludge, 352, 0, :west
unit :wizard, 354, 0, :west
unit :captive, 358, 0, :west
unit :sludge, 360, 0, :west
unit :captive, 361, 0, :west
unit :archer, 362, 0, :west
unit :captive, 365, 0, :west
unit :sludge, 366, 0, :west
unit :thick_sludge, 369, 0, :west
unit :thick_sludge, 371, 0, :west
unit :wizard, 379, 0, :west
unit :sludge, 381, 0, :west
unit :thick_sludge, 391, 0, :west
unit :thick_sludge, 393, 0, :west
unit :thick_sludge, 399, 0, :west
unit :sludge, 404, 0, :west
unit :wizard, 407, 0, :west
unit :sludge, 410, 0, :west
unit :thick_sludge, 414, 0, :west
unit :archer, 418, 0, :west
unit :sludge, 426, 0, :west
unit :archer, 429, 0, :west
unit :sludge, 430, 0, :west
unit :sludge, 434, 0, :west
unit :captive, 436, 0, :west
unit :thick_sludge, 443, 0, :west
unit :captive, 444, 0, :west
unit :captive, 449, 0, :west
unit :captive, 461, 0, :west
unit :captive, 463, 0, :west
unit :captive, 466, 0, :west
unit :captive, 476, 0, :west
unit :wizard, 480, 0, :west
unit :thick_sludge, 482, 0, :west
unit :archer, 483, 0, :west
unit :wizard, 485, 0, :west
unit :archer, 489, 0, :west
unit :captive, 495, 0, :west
unit :archer, 499, 0, :west
unit :thick_sludge, 508, 0, :west
unit :thick_sludge, 509, 0, :west
unit :captive, 511, 0, :west
unit :sludge, 513, 0, :west
unit :captive, 521, 0, :west
unit :captive, 525, 0, :west
unit :captive, 527, 0, :west
unit :archer, 532, 0, :west
unit :captive, 533, 0, :west
unit :sludge, 537, 0, :west
unit :sludge, 539, 0, :west
unit :sludge, 542, 0, :west
unit :captive, 547, 0, :west
unit :sludge, 548, 0, :west
unit :archer, 549, 0, :west
unit :wizard, 556, 0, :west
unit :sludge, 559, 0, :west
unit :captive, 564, 0, :west
unit :archer, 575, 0, :west
unit :thick_sludge, 576, 0, :west
unit :archer, 580, 0, :west
unit :archer, 584, 0, :west
unit :captive, 591, 0, :west
unit :wizard, 594, 0, :west
unit :sludge, 600, 0, :west
unit :captive, 603, 0, :west
unit :wizard, 605, 0, :west
unit :sludge, 608, 0, :west
unit :wizard, 610, 0, :west
unit :captive, 611, 0, :west
unit :wizard, 614, 0, :west
unit :sludge, 620, 0, :west
unit :captive, 628, 0, :west
unit :wizard, 632, 0, :west
unit :captive, 636, 0, :west
unit :captive, 639, 0, :west
unit :wizard, 643, 0, :west
unit :thick_sludge, 644, 0, :west
unit :thick_sludge, 648, 0, :west
unit :archer, 653, 0, :west
unit :sludge, 664, 0, :west
unit :archer, 675, 0, :west
unit :wizard, 681, 0, :west
unit :sludge, 683, 0, :west
unit :archer, 692, 0, :west
unit :archer, 697, 0, :west
unit :archer, 700, 0, :west
unit :wizard, 705, 0, :west
unit :thick_sludge, 708, 0, :west
unit :sludge, 709, 0, :west
unit :archer, 710, 0, :west
unit :thick_sludge, 717, 0, :west
unit :archer, 727, 0, :west
unit :thick_sludge, 734, 0, :west
unit :sludge, 736, 0, :west
unit :sludge, 743, 0, :west
unit :sludge, 745, 0, :west
unit :sludge, 750, 0, :west
unit :sludge, 753, 0, :west
unit :wizard, 757, 0, :west
unit :thick_sludge, 762, 0, :west
unit :thick_sludge, 764, 0, :west
unit :wizard, 765, 0, :west
unit :wizard, 767, 0, :west
unit :thick_sludge, 773, 0, :west
unit :archer, 777, 0, :west
unit :thick_sludge, 780, 0, :west
unit :sludge, 781, 0, :west
unit :archer, 792, 0, :west
unit :sludge, 795, 0, :west
unit :sludge, 798, 0, :west
unit :thick_sludge, 808, 0, :west
unit :thick_sludge, 816, 0, :west
unit :wizard, 817, 0, :west
unit :captive, 818, 0, :west
unit :archer, 819, 0, :west
unit :sludge, 820, 0, :west
unit :captive, 827, 0, :west
unit :thick_sludge, 832, 0, :west
unit :captive, 838, 0, :west
unit :thick_sludge, 839, 0, :west
unit :captive, 846, 0, :west
unit :archer, 847, 0, :west
unit :archer, 850, 0, :west
unit :archer, 852, 0, :west
unit :thick_sludge, 855, 0, :west
unit :archer, 857, 0, :west
unit :thick_sludge, 858, 0, :west
unit :sludge, 872, 0, :west
unit :wizard, 874, 0, :west
unit :captive, 877, 0, :west
unit :captive, 880, 0, :west
unit :wizard, 882, 0, :west
unit :sludge, 886, 0, :west
unit :captive, 889, 0, :west
unit :thick_sludge, 893, 0, :west
unit :sludge, 894, 0, :west
unit :thick_sludge, 901, 0, :west
unit :sludge, 903, 0, :west
unit :wizard, 906, 0, :west
