#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S w     Cs            w    s a C     s  s   wa         aC       w  w      sa       > a   w s   CS    C   @     a         s      S            w           saS       w      s           CSC       a  C Cs   s  s     s S    C     w s        aS   s  w     S   a  S  w Ss w       C  C    w   a  S  a      a           w           w     S   aw C Sa  s   a  s        CC w       w C  a  Sa S   a    aS aCC  a  ws C    SCa   s w                C w   S     sS     C     w CS C    S C       aC  s  S   s Ca   w  ws        s  S   w       SS w a        s   ass  s        S    w      a             w        C S    as      s  w    CC     s     w CS    SS    S    s Sa    s   S  a       C C  C    sC         s   w     s aa S     w a      S as   aS   ss  w CC s aw  a  C   s       C   s  sC w    s      s w S  w     SC   Ss S S    sC        C    w  C           |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 841
ace_score 4205
size 841, 1
stairs 84, 0

warrior 106, 0, :east

unit :thick_sludge, 1, 0, :east
unit :wizard, 3, 0, :east
unit :captive, 9, 0, :east
unit :sludge, 10, 0, :east
unit :wizard, 23, 0, :east
unit :sludge, 28, 0, :east
unit :archer, 30, 0, :east
unit :captive, 32, 0, :east
unit :sludge, 38, 0, :east
unit :sludge, 41, 0, :east
unit :wizard, 45, 0, :east
unit :archer, 46, 0, :east
unit :archer, 56, 0, :east
unit :captive, 57, 0, :east
unit :wizard, 65, 0, :east
unit :wizard, 68, 0, :east
unit :sludge, 75, 0, :east
unit :archer, 76, 0, :east
unit :archer, 86, 0, :east
unit :wizard, 90, 0, :east
unit :sludge, 92, 0, :east
unit :captive, 96, 0, :east
unit :thick_sludge, 97, 0, :east
unit :captive, 102, 0, :east
unit :archer, 112, 0, :west
unit :sludge, 122, 0, :west
unit :thick_sludge, 129, 0, :west
unit :wizard, 142, 0, :west
unit :sludge, 154, 0, :west
unit :archer, 155, 0, :west
unit :thick_sludge, 156, 0, :west
unit :wizard, 164, 0, :west
unit :sludge, 171, 0, :west
unit :captive, 183, 0, :west
unit :thick_sludge, 184, 0, :west
unit :captive, 185, 0, :west
unit :archer, 193, 0, :west
unit :captive, 196, 0, :west
unit :captive, 198, 0, :west
unit :sludge, 199, 0, :west
unit :sludge, 203, 0, :west
unit :sludge, 206, 0, :west
unit :sludge, 212, 0, :west
unit :thick_sludge, 214, 0, :west
unit :captive, 219, 0, :west
unit :wizard, 225, 0, :west
unit :sludge, 227, 0, :west
unit :archer, 236, 0, :west
unit :thick_sludge, 237, 0, :west
unit :sludge, 241, 0, :west
unit :wizard, 244, 0, :west
unit :thick_sludge, 250, 0, :west
unit :archer, 254, 0, :west
unit :thick_sludge, 257, 0, :west
unit :wizard, 260, 0, :west
unit :thick_sludge, 262, 0, :west
unit :sludge, 263, 0, :west
unit :wizard, 265, 0, :west
unit :captive, 273, 0, :west
unit :captive, 276, 0, :west
unit :wizard, 281, 0, :west
unit :archer, 285, 0, :west
unit :thick_sludge, 288, 0, :west
unit :archer, 291, 0, :west
unit :archer, 298, 0, :west
unit :wizard, 310, 0, :west
unit :wizard, 322, 0, :west
unit :thick_sludge, 328, 0, :west
unit :archer, 332, 0, :west
unit :wizard, 333, 0, :west
unit :captive, 335, 0, :west
unit :thick_sludge, 337, 0, :west
unit :archer, 338, 0, :west
unit :sludge, 341, 0, :west
unit :archer, 345, 0, :west
unit :sludge, 348, 0, :west
unit :captive, 357, 0, :west
unit :captive, 358, 0, :west
unit :wizard, 360, 0, :west
unit :wizard, 368, 0, :west
unit :captive, 370, 0, :west
unit :archer, 373, 0, :west
unit :thick_sludge, 376, 0, :west
unit :archer, 377, 0, :west
unit :thick_sludge, 379, 0, :west
unit :archer, 383, 0, :west
unit :archer, 388, 0, :west
unit :thick_sludge, 389, 0, :west
unit :archer, 391, 0, :west
unit :captive, 392, 0, :west
unit :captive, 393, 0, :west
unit :archer, 396, 0, :west
unit :wizard, 399, 0, :west
unit :sludge, 400, 0, :west
unit :captive, 402, 0, :west
unit :thick_sludge, 407, 0, :west
unit :captive, 408, 0, :west
unit :archer, 409, 0, :west
unit :sludge, 413, 0, :west
unit :wizard, 415, 0, :west
unit :captive, 432, 0, :west
unit :wizard, 434, 0, :west
unit :thick_sludge, 438, 0, :west
unit :sludge, 444, 0, :west
unit :thick_sludge, 445, 0, :west
unit :captive, 451, 0, :west
unit :wizard, 457, 0, :west
unit :captive, 459, 0, :west
unit :thick_sludge, 460, 0, :west
unit :captive, 462, 0, :west
unit :thick_sludge, 467, 0, :west
unit :captive, 469, 0, :west
unit :archer, 477, 0, :west
unit :captive, 478, 0, :west
unit :sludge, 481, 0, :west
unit :thick_sludge, 484, 0, :west
unit :sludge, 488, 0, :west
unit :captive, 490, 0, :west
unit :archer, 491, 0, :west
unit :wizard, 495, 0, :west
unit :wizard, 498, 0, :west
unit :sludge, 499, 0, :west
unit :sludge, 508, 0, :west
unit :thick_sludge, 511, 0, :west
unit :wizard, 515, 0, :west
unit :thick_sludge, 523, 0, :west
unit :thick_sludge, 524, 0, :west
unit :wizard, 526, 0, :west
unit :archer, 528, 0, :west
unit :sludge, 537, 0, :west
unit :archer, 541, 0, :west
unit :sludge, 542, 0, :west
unit :sludge, 543, 0, :west
unit :sludge, 546, 0, :west
unit :thick_sludge, 555, 0, :west
unit :wizard, 560, 0, :west
unit :archer, 567, 0, :west
unit :wizard, 581, 0, :west
unit :captive, 590, 0, :west
unit :thick_sludge, 592, 0, :west
unit :archer, 597, 0, :west
unit :sludge, 598, 0, :west
unit :sludge, 605, 0, :west
unit :wizard, 608, 0, :west
unit :captive, 613, 0, :west
unit :captive, 614, 0, :west
unit :sludge, 620, 0, :west
unit :wizard, 626, 0, :west
unit :captive, 628, 0, :west
unit :thick_sludge, 629, 0, :west
unit :thick_sludge, 634, 0, :west
unit :thick_sludge, 635, 0, :west
unit :thick_sludge, 640, 0, :west
unit :sludge, 645, 0, :west
unit :thick_sludge, 647, 0, :west
unit :archer, 648, 0, :west
unit :sludge, 653, 0, :west
unit :thick_sludge, 657, 0, :west
unit :archer, 660, 0, :west
unit :captive, 668, 0, :west
unit :captive, 670, 0, :west
unit :captive, 673, 0, :west
unit :sludge, 678, 0, :west
unit :captive, 679, 0, :west
unit :sludge, 689, 0, :west
unit :wizard, 693, 0, :west
unit :sludge, 699, 0, :west
unit :archer, 701, 0, :west
unit :archer, 702, 0, :west
unit :thick_sludge, 704, 0, :west
unit :wizard, 710, 0, :west
unit :archer, 712, 0, :west
unit :thick_sludge, 719, 0, :west
unit :archer, 721, 0, :west
unit :sludge, 722, 0, :west
unit :archer, 726, 0, :west
unit :thick_sludge, 727, 0, :west
unit :sludge, 731, 0, :west
unit :sludge, 732, 0, :west
unit :wizard, 735, 0, :west
unit :captive, 737, 0, :west
unit :captive, 738, 0, :west
unit :sludge, 740, 0, :west
unit :archer, 742, 0, :west
unit :wizard, 743, 0, :west
unit :archer, 746, 0, :west
unit :captive, 749, 0, :west
unit :sludge, 753, 0, :west
unit :captive, 761, 0, :west
unit :sludge, 765, 0, :west
unit :sludge, 768, 0, :west
unit :captive, 769, 0, :west
unit :wizard, 771, 0, :west
unit :sludge, 776, 0, :west
unit :sludge, 783, 0, :west
unit :wizard, 785, 0, :west
unit :thick_sludge, 787, 0, :west
unit :wizard, 790, 0, :west
unit :thick_sludge, 796, 0, :west
unit :captive, 797, 0, :west
unit :thick_sludge, 801, 0, :west
unit :sludge, 802, 0, :west
unit :thick_sludge, 804, 0, :west
unit :thick_sludge, 806, 0, :west
unit :sludge, 811, 0, :west
unit :captive, 812, 0, :west
unit :captive, 821, 0, :west
unit :wizard, 826, 0, :west
unit :captive, 829, 0, :west
