#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   CCS            w        w  C        a       a     >    C    w s  a       a        s sC     S    w         ss   Sa a   S              C  a         w   a       w s    s w  S s    aw   sC    Ss S   s  asC   aC S   S w   C   S  s ss      C    w  w  S s  s  C  S         sw        aCC  Ss                  S    Sa s   s       s  S a     @    s    S        a     CSC   a  a    C  S  sCa   Cw w C    sw     CCs   s Sa  S aS w       S   aS     S   C s     w    s            a  S w S w     s         a CaSs    CC          S     s w  s      C       a   s wa  w     s  ssS          C   sS sa   S w     s   a   w    s C  s    s  aa s w     C      Sa C C         w             a  sa      s      s Cs         s      S   ss  a  w      w    C S      C     aC C     s   wa     S        a   wC  C  a a  s  S     a  C        C  w a S       w  S S       a |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 839
ace_score 4195
size 839, 1
stairs 53, 0

warrior 335, 0, :east

unit :captive, 3, 0, :east
unit :captive, 4, 0, :east
unit :thick_sludge, 5, 0, :east
unit :wizard, 18, 0, :east
unit :wizard, 27, 0, :east
unit :captive, 30, 0, :east
unit :archer, 39, 0, :east
unit :archer, 47, 0, :east
unit :captive, 58, 0, :east
unit :wizard, 63, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 68, 0, :east
unit :archer, 76, 0, :east
unit :sludge, 85, 0, :east
unit :sludge, 87, 0, :east
unit :captive, 88, 0, :east
unit :thick_sludge, 94, 0, :east
unit :wizard, 99, 0, :east
unit :sludge, 109, 0, :east
unit :sludge, 110, 0, :east
unit :thick_sludge, 114, 0, :east
unit :archer, 115, 0, :east
unit :archer, 117, 0, :east
unit :thick_sludge, 121, 0, :east
unit :captive, 136, 0, :east
unit :archer, 139, 0, :east
unit :wizard, 149, 0, :east
unit :archer, 153, 0, :east
unit :wizard, 161, 0, :east
unit :sludge, 163, 0, :east
unit :sludge, 168, 0, :east
unit :wizard, 170, 0, :east
unit :thick_sludge, 173, 0, :east
unit :sludge, 175, 0, :east
unit :archer, 180, 0, :east
unit :wizard, 181, 0, :east
unit :sludge, 185, 0, :east
unit :captive, 186, 0, :east
unit :thick_sludge, 191, 0, :east
unit :sludge, 192, 0, :east
unit :thick_sludge, 194, 0, :east
unit :sludge, 198, 0, :east
unit :archer, 201, 0, :east
unit :sludge, 202, 0, :east
unit :captive, 203, 0, :east
unit :archer, 207, 0, :east
unit :captive, 208, 0, :east
unit :thick_sludge, 210, 0, :east
unit :thick_sludge, 214, 0, :east
unit :wizard, 216, 0, :east
unit :captive, 220, 0, :east
unit :thick_sludge, 224, 0, :east
unit :sludge, 227, 0, :east
unit :sludge, 229, 0, :east
unit :sludge, 230, 0, :east
unit :captive, 237, 0, :east
unit :wizard, 242, 0, :east
unit :wizard, 245, 0, :east
unit :thick_sludge, 248, 0, :east
unit :sludge, 250, 0, :east
unit :sludge, 253, 0, :east
unit :captive, 256, 0, :east
unit :thick_sludge, 259, 0, :east
unit :sludge, 269, 0, :east
unit :wizard, 270, 0, :east
unit :archer, 279, 0, :east
unit :captive, 280, 0, :east
unit :captive, 281, 0, :east
unit :thick_sludge, 284, 0, :east
unit :sludge, 285, 0, :east
unit :thick_sludge, 304, 0, :east
unit :thick_sludge, 309, 0, :east
unit :archer, 310, 0, :east
unit :sludge, 312, 0, :east
unit :sludge, 316, 0, :east
unit :sludge, 324, 0, :east
unit :thick_sludge, 327, 0, :east
unit :archer, 329, 0, :east
unit :sludge, 340, 0, :west
unit :thick_sludge, 345, 0, :west
unit :archer, 354, 0, :west
unit :captive, 360, 0, :west
unit :thick_sludge, 361, 0, :west
unit :captive, 362, 0, :west
unit :archer, 366, 0, :west
unit :archer, 369, 0, :west
unit :captive, 374, 0, :west
unit :thick_sludge, 377, 0, :west
unit :sludge, 380, 0, :west
unit :captive, 381, 0, :west
unit :archer, 382, 0, :west
unit :captive, 386, 0, :west
unit :wizard, 387, 0, :west
unit :wizard, 389, 0, :west
unit :captive, 391, 0, :west
unit :sludge, 396, 0, :west
unit :wizard, 397, 0, :west
unit :captive, 403, 0, :west
unit :captive, 404, 0, :west
unit :sludge, 405, 0, :west
unit :sludge, 409, 0, :west
unit :thick_sludge, 411, 0, :west
unit :archer, 412, 0, :west
unit :thick_sludge, 415, 0, :west
unit :archer, 417, 0, :west
unit :thick_sludge, 418, 0, :west
unit :wizard, 420, 0, :west
unit :thick_sludge, 428, 0, :west
unit :archer, 432, 0, :west
unit :thick_sludge, 433, 0, :west
unit :thick_sludge, 439, 0, :west
unit :captive, 443, 0, :west
unit :sludge, 445, 0, :west
unit :wizard, 451, 0, :west
unit :sludge, 456, 0, :west
unit :archer, 469, 0, :west
unit :thick_sludge, 472, 0, :west
unit :wizard, 474, 0, :west
unit :thick_sludge, 476, 0, :west
unit :wizard, 478, 0, :west
unit :sludge, 484, 0, :west
unit :archer, 494, 0, :west
unit :captive, 496, 0, :west
unit :archer, 497, 0, :west
unit :thick_sludge, 498, 0, :west
unit :sludge, 499, 0, :west
unit :captive, 504, 0, :west
unit :captive, 505, 0, :west
unit :thick_sludge, 516, 0, :west
unit :sludge, 522, 0, :west
unit :wizard, 524, 0, :west
unit :sludge, 527, 0, :west
unit :captive, 534, 0, :west
unit :archer, 542, 0, :west
unit :sludge, 546, 0, :west
unit :wizard, 548, 0, :west
unit :archer, 549, 0, :west
unit :wizard, 552, 0, :west
unit :sludge, 558, 0, :west
unit :sludge, 561, 0, :west
unit :sludge, 562, 0, :west
unit :thick_sludge, 563, 0, :west
unit :captive, 574, 0, :west
unit :sludge, 578, 0, :west
unit :thick_sludge, 579, 0, :west
unit :sludge, 581, 0, :west
unit :archer, 582, 0, :west
unit :thick_sludge, 586, 0, :west
unit :wizard, 588, 0, :west
unit :sludge, 594, 0, :west
unit :archer, 598, 0, :west
unit :wizard, 602, 0, :west
unit :sludge, 607, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 612, 0, :west
unit :sludge, 617, 0, :west
unit :archer, 620, 0, :west
unit :archer, 621, 0, :west
unit :sludge, 623, 0, :west
unit :wizard, 625, 0, :west
unit :captive, 631, 0, :west
unit :thick_sludge, 638, 0, :west
unit :archer, 639, 0, :west
unit :captive, 641, 0, :west
unit :captive, 643, 0, :west
unit :wizard, 653, 0, :west
unit :archer, 667, 0, :west
unit :sludge, 670, 0, :west
unit :archer, 671, 0, :west
unit :sludge, 678, 0, :west
unit :sludge, 685, 0, :west
unit :captive, 687, 0, :west
unit :sludge, 688, 0, :west
unit :sludge, 698, 0, :west
unit :thick_sludge, 705, 0, :west
unit :sludge, 709, 0, :west
unit :sludge, 710, 0, :west
unit :archer, 713, 0, :west
unit :wizard, 716, 0, :west
unit :wizard, 723, 0, :west
unit :captive, 728, 0, :west
unit :thick_sludge, 730, 0, :west
unit :captive, 737, 0, :west
unit :archer, 743, 0, :west
unit :captive, 744, 0, :west
unit :captive, 746, 0, :west
unit :sludge, 752, 0, :west
unit :wizard, 756, 0, :west
unit :archer, 757, 0, :west
unit :thick_sludge, 763, 0, :west
unit :archer, 772, 0, :west
unit :wizard, 776, 0, :west
unit :captive, 777, 0, :west
unit :captive, 780, 0, :west
unit :archer, 783, 0, :west
unit :archer, 785, 0, :west
unit :sludge, 788, 0, :west
unit :thick_sludge, 791, 0, :west
unit :archer, 797, 0, :west
unit :captive, 800, 0, :west
unit :captive, 809, 0, :west
unit :wizard, 812, 0, :west
unit :archer, 814, 0, :west
unit :thick_sludge, 816, 0, :west
unit :wizard, 824, 0, :west
unit :thick_sludge, 827, 0, :west
unit :thick_sludge, 829, 0, :west
unit :archer, 837, 0, :west
