#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     C   C  a  wasa        s          C  a  C      S   w            s   a a a S   a      S      C     s      C   C aa    a       s    C Ca               w     s  w     S C          Ssw        C  a    CC Ss        sa  S    as Cs   sSCw  s      a      @            C C  S  sS      s S   Sa sS  w  C       SS   s  asCw  S    a         C  CwS   s  C   S     s  aa C     aa   w ss  S   C        S  as             aS   sS    C  ws     a s    w      a s        sSa   C s     w                 s     a  sa            aSs   w S  s w    s         S   a S C   a   S a  C       C   s a S    C      w   s  s      CCC  w    s  w   w          w    C      w  a S     C    S w    SCs  a Cs    w      C    s   s      S  s    Ca s      s    S     a C  w    a s S w   >  S  s   aC     Cs s S    w   w  s             w  a     C   a   C |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 815
ace_score 4075
size 815, 1
stairs 748, 0

warrior 250, 0, :east

unit :captive, 5, 0, :east
unit :captive, 9, 0, :east
unit :archer, 12, 0, :east
unit :wizard, 15, 0, :east
unit :archer, 16, 0, :east
unit :sludge, 17, 0, :east
unit :archer, 18, 0, :east
unit :sludge, 27, 0, :east
unit :captive, 38, 0, :east
unit :archer, 41, 0, :east
unit :captive, 44, 0, :east
unit :thick_sludge, 51, 0, :east
unit :wizard, 55, 0, :east
unit :sludge, 68, 0, :east
unit :archer, 72, 0, :east
unit :archer, 74, 0, :east
unit :archer, 76, 0, :east
unit :thick_sludge, 78, 0, :east
unit :archer, 82, 0, :east
unit :thick_sludge, 89, 0, :east
unit :captive, 96, 0, :east
unit :sludge, 102, 0, :east
unit :captive, 109, 0, :east
unit :captive, 113, 0, :east
unit :archer, 115, 0, :east
unit :archer, 116, 0, :east
unit :archer, 121, 0, :east
unit :sludge, 129, 0, :east
unit :captive, 134, 0, :east
unit :captive, 136, 0, :east
unit :archer, 137, 0, :east
unit :wizard, 153, 0, :east
unit :sludge, 159, 0, :east
unit :wizard, 162, 0, :east
unit :thick_sludge, 168, 0, :east
unit :captive, 170, 0, :east
unit :thick_sludge, 181, 0, :east
unit :sludge, 182, 0, :east
unit :wizard, 183, 0, :east
unit :captive, 192, 0, :east
unit :archer, 195, 0, :east
unit :captive, 200, 0, :east
unit :captive, 201, 0, :east
unit :thick_sludge, 203, 0, :east
unit :sludge, 204, 0, :east
unit :sludge, 213, 0, :east
unit :archer, 214, 0, :east
unit :thick_sludge, 217, 0, :east
unit :archer, 222, 0, :east
unit :sludge, 223, 0, :east
unit :captive, 225, 0, :east
unit :sludge, 226, 0, :east
unit :sludge, 230, 0, :east
unit :thick_sludge, 231, 0, :east
unit :captive, 232, 0, :east
unit :wizard, 233, 0, :east
unit :sludge, 236, 0, :east
unit :archer, 243, 0, :east
unit :captive, 263, 0, :west
unit :captive, 265, 0, :west
unit :thick_sludge, 268, 0, :west
unit :sludge, 271, 0, :west
unit :thick_sludge, 272, 0, :west
unit :sludge, 279, 0, :west
unit :thick_sludge, 281, 0, :west
unit :thick_sludge, 285, 0, :west
unit :archer, 286, 0, :west
unit :sludge, 288, 0, :west
unit :thick_sludge, 289, 0, :west
unit :wizard, 292, 0, :west
unit :captive, 295, 0, :west
unit :thick_sludge, 303, 0, :west
unit :thick_sludge, 304, 0, :west
unit :sludge, 308, 0, :west
unit :archer, 311, 0, :west
unit :sludge, 312, 0, :west
unit :captive, 313, 0, :west
unit :wizard, 314, 0, :west
unit :thick_sludge, 317, 0, :west
unit :archer, 322, 0, :west
unit :captive, 332, 0, :west
unit :captive, 335, 0, :west
unit :wizard, 336, 0, :west
unit :thick_sludge, 337, 0, :west
unit :sludge, 341, 0, :west
unit :captive, 344, 0, :west
unit :thick_sludge, 348, 0, :west
unit :sludge, 354, 0, :west
unit :archer, 357, 0, :west
unit :archer, 358, 0, :west
unit :captive, 360, 0, :west
unit :archer, 366, 0, :west
unit :archer, 367, 0, :west
unit :wizard, 371, 0, :west
unit :sludge, 373, 0, :west
unit :sludge, 374, 0, :west
unit :thick_sludge, 377, 0, :west
unit :captive, 381, 0, :west
unit :thick_sludge, 390, 0, :west
unit :archer, 393, 0, :west
unit :sludge, 394, 0, :west
unit :archer, 408, 0, :west
unit :thick_sludge, 409, 0, :west
unit :sludge, 413, 0, :west
unit :thick_sludge, 414, 0, :west
unit :captive, 419, 0, :west
unit :wizard, 422, 0, :west
unit :sludge, 423, 0, :west
unit :archer, 429, 0, :west
unit :sludge, 431, 0, :west
unit :wizard, 436, 0, :west
unit :archer, 443, 0, :west
unit :sludge, 445, 0, :west
unit :sludge, 454, 0, :west
unit :thick_sludge, 455, 0, :west
unit :archer, 456, 0, :west
unit :captive, 460, 0, :west
unit :sludge, 462, 0, :west
unit :wizard, 468, 0, :west
unit :sludge, 486, 0, :west
unit :archer, 492, 0, :west
unit :sludge, 495, 0, :west
unit :archer, 496, 0, :west
unit :archer, 509, 0, :west
unit :thick_sludge, 510, 0, :west
unit :sludge, 511, 0, :west
unit :wizard, 515, 0, :west
unit :thick_sludge, 517, 0, :west
unit :sludge, 520, 0, :west
unit :wizard, 522, 0, :west
unit :sludge, 527, 0, :west
unit :thick_sludge, 537, 0, :west
unit :archer, 541, 0, :west
unit :thick_sludge, 543, 0, :west
unit :captive, 545, 0, :west
unit :archer, 549, 0, :west
unit :thick_sludge, 553, 0, :west
unit :archer, 555, 0, :west
unit :captive, 558, 0, :west
unit :captive, 566, 0, :west
unit :sludge, 570, 0, :west
unit :archer, 572, 0, :west
unit :thick_sludge, 574, 0, :west
unit :captive, 579, 0, :west
unit :wizard, 586, 0, :west
unit :sludge, 590, 0, :west
unit :sludge, 593, 0, :west
unit :captive, 600, 0, :west
unit :captive, 601, 0, :west
unit :captive, 602, 0, :west
unit :wizard, 605, 0, :west
unit :sludge, 610, 0, :west
unit :wizard, 613, 0, :west
unit :wizard, 617, 0, :west
unit :wizard, 628, 0, :west
unit :captive, 633, 0, :west
unit :wizard, 640, 0, :west
unit :archer, 643, 0, :west
unit :thick_sludge, 645, 0, :west
unit :captive, 651, 0, :west
unit :thick_sludge, 656, 0, :west
unit :wizard, 658, 0, :west
unit :thick_sludge, 663, 0, :west
unit :captive, 664, 0, :west
unit :sludge, 665, 0, :west
unit :archer, 668, 0, :west
unit :captive, 670, 0, :west
unit :sludge, 671, 0, :west
unit :wizard, 676, 0, :west
unit :captive, 683, 0, :west
unit :sludge, 688, 0, :west
unit :sludge, 692, 0, :west
unit :thick_sludge, 699, 0, :west
unit :sludge, 702, 0, :west
unit :captive, 707, 0, :west
unit :archer, 708, 0, :west
unit :sludge, 710, 0, :west
unit :sludge, 717, 0, :west
unit :thick_sludge, 722, 0, :west
unit :archer, 728, 0, :west
unit :captive, 730, 0, :west
unit :wizard, 733, 0, :west
unit :archer, 738, 0, :west
unit :sludge, 740, 0, :west
unit :thick_sludge, 742, 0, :west
unit :wizard, 744, 0, :west
unit :thick_sludge, 751, 0, :west
unit :sludge, 754, 0, :west
unit :archer, 758, 0, :west
unit :captive, 759, 0, :west
unit :captive, 765, 0, :west
unit :sludge, 766, 0, :west
unit :sludge, 768, 0, :west
unit :thick_sludge, 770, 0, :west
unit :wizard, 775, 0, :west
unit :wizard, 779, 0, :west
unit :sludge, 782, 0, :west
unit :wizard, 796, 0, :west
unit :archer, 799, 0, :west
unit :captive, 805, 0, :west
unit :archer, 809, 0, :west
unit :captive, 813, 0, :west
