#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C   CC   S   Csaa S           S>   C   C         S         S s S    S     w   SS    sw w     w  SSsa        C a   w    w   S  a            a  s s   C C       s       C      C a    w sS    s S        Ca      w        CSs   w  w   C  w a   a wCs       Cw    s S w  s S aS    sS     a  ss    w   ssS   s  sa    S  a S       S C       s s   a S                 C        sSa             s        aS          a w   Sa      a    C        as  CwC                  a    a C   w         C  s  a     S         C  w  C  sC S          a   w  s S    w  C w        Sa   s S    aa  C C   C     a  s       a     C   sS   s     C          C   S C    @       w  a      a   aC    C   aS   a  S     S     SC  Ss   sC        a                s   w     s   Sa  CS  s  s   ss          s     a     a s Ss C   aw  a  s    w    C  w    s  w s aC  a     Ssa  aa     a        S    C  S    C        C  S  sCa aCwS  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 885
ace_score 4425
size 885, 1
stairs 31, 0

warrior 632, 0, :east

unit :captive, 0, 0, :east
unit :captive, 4, 0, :east
unit :captive, 5, 0, :east
unit :thick_sludge, 9, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 14, 0, :east
unit :archer, 15, 0, :east
unit :archer, 16, 0, :east
unit :thick_sludge, 18, 0, :east
unit :thick_sludge, 30, 0, :east
unit :captive, 35, 0, :east
unit :captive, 39, 0, :east
unit :thick_sludge, 49, 0, :east
unit :thick_sludge, 59, 0, :east
unit :sludge, 61, 0, :east
unit :thick_sludge, 63, 0, :east
unit :thick_sludge, 68, 0, :east
unit :wizard, 74, 0, :east
unit :thick_sludge, 78, 0, :east
unit :thick_sludge, 79, 0, :east
unit :sludge, 84, 0, :east
unit :wizard, 85, 0, :east
unit :wizard, 87, 0, :east
unit :wizard, 93, 0, :east
unit :thick_sludge, 96, 0, :east
unit :thick_sludge, 97, 0, :east
unit :sludge, 98, 0, :east
unit :archer, 99, 0, :east
unit :captive, 108, 0, :east
unit :archer, 110, 0, :east
unit :wizard, 114, 0, :east
unit :wizard, 119, 0, :east
unit :thick_sludge, 123, 0, :east
unit :archer, 126, 0, :east
unit :archer, 139, 0, :east
unit :sludge, 142, 0, :east
unit :sludge, 144, 0, :east
unit :captive, 148, 0, :east
unit :captive, 150, 0, :east
unit :sludge, 158, 0, :east
unit :captive, 166, 0, :east
unit :captive, 173, 0, :east
unit :archer, 175, 0, :east
unit :wizard, 180, 0, :east
unit :sludge, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :sludge, 188, 0, :east
unit :thick_sludge, 190, 0, :east
unit :captive, 199, 0, :east
unit :archer, 200, 0, :east
unit :wizard, 207, 0, :east
unit :captive, 216, 0, :east
unit :thick_sludge, 217, 0, :east
unit :sludge, 218, 0, :east
unit :wizard, 222, 0, :east
unit :wizard, 225, 0, :east
unit :captive, 229, 0, :east
unit :wizard, 232, 0, :east
unit :archer, 234, 0, :east
unit :archer, 238, 0, :east
unit :wizard, 240, 0, :east
unit :captive, 241, 0, :east
unit :sludge, 242, 0, :east
unit :captive, 250, 0, :east
unit :wizard, 251, 0, :east
unit :sludge, 256, 0, :east
unit :thick_sludge, 258, 0, :east
unit :wizard, 260, 0, :east
unit :sludge, 263, 0, :east
unit :thick_sludge, 265, 0, :east
unit :archer, 267, 0, :east
unit :thick_sludge, 268, 0, :east
unit :sludge, 273, 0, :east
unit :thick_sludge, 274, 0, :east
unit :archer, 280, 0, :east
unit :sludge, 283, 0, :east
unit :sludge, 284, 0, :east
unit :wizard, 289, 0, :east
unit :sludge, 293, 0, :east
unit :sludge, 294, 0, :east
unit :thick_sludge, 295, 0, :east
unit :sludge, 299, 0, :east
unit :sludge, 302, 0, :east
unit :archer, 303, 0, :east
unit :thick_sludge, 308, 0, :east
unit :archer, 311, 0, :east
unit :thick_sludge, 313, 0, :east
unit :thick_sludge, 321, 0, :east
unit :captive, 323, 0, :east
unit :sludge, 331, 0, :east
unit :sludge, 333, 0, :east
unit :archer, 337, 0, :east
unit :thick_sludge, 339, 0, :east
unit :captive, 357, 0, :east
unit :sludge, 366, 0, :east
unit :thick_sludge, 367, 0, :east
unit :archer, 368, 0, :east
unit :sludge, 382, 0, :east
unit :archer, 391, 0, :east
unit :thick_sludge, 392, 0, :east
unit :archer, 403, 0, :east
unit :wizard, 405, 0, :east
unit :thick_sludge, 409, 0, :east
unit :archer, 410, 0, :east
unit :archer, 417, 0, :east
unit :captive, 422, 0, :east
unit :archer, 431, 0, :east
unit :sludge, 432, 0, :east
unit :captive, 435, 0, :east
unit :wizard, 436, 0, :east
unit :captive, 437, 0, :east
unit :archer, 456, 0, :east
unit :archer, 461, 0, :east
unit :captive, 463, 0, :east
unit :wizard, 467, 0, :east
unit :captive, 477, 0, :east
unit :sludge, 480, 0, :east
unit :archer, 483, 0, :east
unit :thick_sludge, 489, 0, :east
unit :captive, 499, 0, :east
unit :wizard, 502, 0, :east
unit :captive, 505, 0, :east
unit :sludge, 508, 0, :east
unit :captive, 509, 0, :east
unit :thick_sludge, 511, 0, :east
unit :archer, 522, 0, :east
unit :wizard, 526, 0, :east
unit :sludge, 529, 0, :east
unit :thick_sludge, 531, 0, :east
unit :wizard, 536, 0, :east
unit :captive, 539, 0, :east
unit :wizard, 541, 0, :east
unit :thick_sludge, 550, 0, :east
unit :archer, 551, 0, :east
unit :sludge, 555, 0, :east
unit :thick_sludge, 557, 0, :east
unit :archer, 562, 0, :east
unit :archer, 563, 0, :east
unit :captive, 566, 0, :east
unit :captive, 568, 0, :east
unit :captive, 572, 0, :east
unit :archer, 578, 0, :east
unit :sludge, 581, 0, :east
unit :archer, 589, 0, :east
unit :captive, 595, 0, :east
unit :sludge, 599, 0, :east
unit :thick_sludge, 600, 0, :east
unit :sludge, 604, 0, :east
unit :captive, 610, 0, :east
unit :captive, 621, 0, :east
unit :thick_sludge, 625, 0, :east
unit :captive, 627, 0, :east
unit :wizard, 640, 0, :west
unit :archer, 643, 0, :west
unit :archer, 650, 0, :west
unit :archer, 654, 0, :west
unit :captive, 655, 0, :west
unit :captive, 660, 0, :west
unit :archer, 664, 0, :west
unit :thick_sludge, 665, 0, :west
unit :archer, 669, 0, :west
unit :thick_sludge, 672, 0, :west
unit :thick_sludge, 678, 0, :west
unit :thick_sludge, 684, 0, :west
unit :captive, 685, 0, :west
unit :thick_sludge, 688, 0, :west
unit :sludge, 689, 0, :west
unit :sludge, 693, 0, :west
unit :captive, 694, 0, :west
unit :archer, 703, 0, :west
unit :sludge, 720, 0, :west
unit :wizard, 724, 0, :west
unit :sludge, 730, 0, :west
unit :thick_sludge, 734, 0, :west
unit :archer, 735, 0, :west
unit :captive, 738, 0, :west
unit :thick_sludge, 739, 0, :west
unit :sludge, 742, 0, :west
unit :sludge, 745, 0, :west
unit :sludge, 749, 0, :west
unit :sludge, 750, 0, :west
unit :sludge, 761, 0, :west
unit :archer, 767, 0, :west
unit :archer, 773, 0, :west
unit :sludge, 775, 0, :west
unit :thick_sludge, 777, 0, :west
unit :sludge, 778, 0, :west
unit :captive, 780, 0, :west
unit :archer, 784, 0, :west
unit :wizard, 785, 0, :west
unit :archer, 788, 0, :west
unit :sludge, 791, 0, :west
unit :wizard, 796, 0, :west
unit :captive, 801, 0, :west
unit :wizard, 804, 0, :west
unit :sludge, 809, 0, :west
unit :wizard, 812, 0, :west
unit :sludge, 814, 0, :west
unit :archer, 816, 0, :west
unit :captive, 817, 0, :west
unit :archer, 820, 0, :west
unit :thick_sludge, 826, 0, :west
unit :sludge, 827, 0, :west
unit :archer, 828, 0, :west
unit :archer, 831, 0, :west
unit :archer, 832, 0, :west
unit :archer, 838, 0, :west
unit :thick_sludge, 847, 0, :west
unit :captive, 852, 0, :west
unit :thick_sludge, 855, 0, :west
unit :captive, 860, 0, :west
unit :captive, 869, 0, :west
unit :thick_sludge, 872, 0, :west
unit :sludge, 875, 0, :west
unit :captive, 876, 0, :west
unit :archer, 877, 0, :west
unit :archer, 879, 0, :west
unit :captive, 880, 0, :west
unit :wizard, 881, 0, :west
unit :thick_sludge, 882, 0, :west
