#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a    a   s   w       s S      w         sSS      C  s          s ws  a    ss   Cw      @     C  w    ss       ass         s w  a s       CwS    S  Ca       S S ss  s    a         C      C          asS            w    C   S a            s a            wa    C      S s  Ca         s     w       S   a     C  C           C  w a Sa a         a   S  w  w w   S         w    s   S  a w         sC         w Ca w C w      w      a a C               S  sC  asC SsCS     S      Ca  Sa  w             C      a  C  sC        Cw         sC CS  C    C  s      w  a      a  C   aw   w  w  C  sC       C      S   w   sS     S  ss     Sss    w   a    S     w  >S  w C    sC    a w sasa sa w   a   sSw S        w     a    w sa    C  S   s  S CS  w              C S a      w s     wS   s               S      S  Ss  s w     S     C C a C  a CC   S S   |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 836
ace_score 4180
size 836, 1
stairs 646, 0

warrior 88, 0, :east

unit :archer, 1, 0, :east
unit :archer, 6, 0, :east
unit :sludge, 10, 0, :east
unit :wizard, 14, 0, :east
unit :sludge, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :wizard, 31, 0, :east
unit :sludge, 41, 0, :east
unit :thick_sludge, 42, 0, :east
unit :thick_sludge, 43, 0, :east
unit :captive, 50, 0, :east
unit :sludge, 53, 0, :east
unit :sludge, 64, 0, :east
unit :wizard, 66, 0, :east
unit :sludge, 67, 0, :east
unit :archer, 70, 0, :east
unit :sludge, 75, 0, :east
unit :sludge, 76, 0, :east
unit :captive, 80, 0, :east
unit :wizard, 81, 0, :east
unit :captive, 94, 0, :west
unit :wizard, 97, 0, :west
unit :sludge, 102, 0, :west
unit :sludge, 103, 0, :west
unit :archer, 111, 0, :west
unit :sludge, 112, 0, :west
unit :sludge, 113, 0, :west
unit :sludge, 123, 0, :west
unit :wizard, 125, 0, :west
unit :archer, 128, 0, :west
unit :sludge, 130, 0, :west
unit :captive, 138, 0, :west
unit :wizard, 139, 0, :west
unit :thick_sludge, 140, 0, :west
unit :thick_sludge, 145, 0, :west
unit :captive, 148, 0, :west
unit :archer, 149, 0, :west
unit :thick_sludge, 157, 0, :west
unit :thick_sludge, 159, 0, :west
unit :sludge, 161, 0, :west
unit :sludge, 162, 0, :west
unit :sludge, 165, 0, :west
unit :archer, 170, 0, :west
unit :captive, 180, 0, :west
unit :captive, 187, 0, :west
unit :archer, 198, 0, :west
unit :sludge, 199, 0, :west
unit :thick_sludge, 200, 0, :west
unit :wizard, 213, 0, :west
unit :captive, 218, 0, :west
unit :thick_sludge, 222, 0, :west
unit :archer, 224, 0, :west
unit :sludge, 237, 0, :west
unit :archer, 239, 0, :west
unit :wizard, 252, 0, :west
unit :archer, 253, 0, :west
unit :captive, 258, 0, :west
unit :thick_sludge, 265, 0, :west
unit :sludge, 267, 0, :west
unit :captive, 270, 0, :west
unit :archer, 271, 0, :west
unit :sludge, 281, 0, :west
unit :wizard, 287, 0, :west
unit :thick_sludge, 295, 0, :west
unit :archer, 299, 0, :west
unit :captive, 305, 0, :west
unit :captive, 308, 0, :west
unit :captive, 320, 0, :west
unit :wizard, 323, 0, :west
unit :archer, 325, 0, :west
unit :thick_sludge, 327, 0, :west
unit :archer, 328, 0, :west
unit :archer, 330, 0, :west
unit :archer, 340, 0, :west
unit :thick_sludge, 344, 0, :west
unit :wizard, 347, 0, :west
unit :wizard, 350, 0, :west
unit :wizard, 352, 0, :west
unit :thick_sludge, 356, 0, :west
unit :wizard, 366, 0, :west
unit :sludge, 371, 0, :west
unit :thick_sludge, 375, 0, :west
unit :archer, 378, 0, :west
unit :wizard, 380, 0, :west
unit :sludge, 390, 0, :west
unit :captive, 391, 0, :west
unit :wizard, 401, 0, :west
unit :captive, 403, 0, :west
unit :archer, 404, 0, :west
unit :wizard, 406, 0, :west
unit :captive, 408, 0, :west
unit :wizard, 410, 0, :west
unit :wizard, 417, 0, :west
unit :archer, 424, 0, :west
unit :archer, 426, 0, :west
unit :captive, 428, 0, :west
unit :thick_sludge, 444, 0, :west
unit :sludge, 447, 0, :west
unit :captive, 448, 0, :west
unit :archer, 451, 0, :west
unit :sludge, 452, 0, :west
unit :captive, 453, 0, :west
unit :thick_sludge, 455, 0, :west
unit :sludge, 456, 0, :west
unit :captive, 457, 0, :west
unit :thick_sludge, 458, 0, :west
unit :thick_sludge, 464, 0, :west
unit :captive, 471, 0, :west
unit :archer, 472, 0, :west
unit :thick_sludge, 475, 0, :west
unit :archer, 476, 0, :west
unit :wizard, 479, 0, :west
unit :captive, 493, 0, :west
unit :archer, 500, 0, :west
unit :captive, 503, 0, :west
unit :sludge, 506, 0, :west
unit :captive, 507, 0, :west
unit :captive, 516, 0, :west
unit :wizard, 517, 0, :west
unit :sludge, 527, 0, :west
unit :captive, 528, 0, :west
unit :captive, 530, 0, :west
unit :thick_sludge, 531, 0, :west
unit :captive, 534, 0, :west
unit :captive, 539, 0, :west
unit :sludge, 542, 0, :west
unit :wizard, 549, 0, :west
unit :archer, 552, 0, :west
unit :archer, 559, 0, :west
unit :captive, 562, 0, :west
unit :archer, 566, 0, :west
unit :wizard, 567, 0, :west
unit :wizard, 571, 0, :west
unit :wizard, 574, 0, :west
unit :captive, 577, 0, :west
unit :sludge, 580, 0, :west
unit :captive, 581, 0, :west
unit :captive, 589, 0, :west
unit :thick_sludge, 596, 0, :west
unit :wizard, 600, 0, :west
unit :sludge, 604, 0, :west
unit :thick_sludge, 605, 0, :west
unit :thick_sludge, 611, 0, :west
unit :sludge, 614, 0, :west
unit :sludge, 615, 0, :west
unit :thick_sludge, 621, 0, :west
unit :sludge, 622, 0, :west
unit :sludge, 623, 0, :west
unit :wizard, 628, 0, :west
unit :archer, 632, 0, :west
unit :thick_sludge, 637, 0, :west
unit :wizard, 643, 0, :west
unit :thick_sludge, 647, 0, :west
unit :wizard, 650, 0, :west
unit :captive, 652, 0, :west
unit :sludge, 657, 0, :west
unit :captive, 658, 0, :west
unit :archer, 663, 0, :west
unit :wizard, 665, 0, :west
unit :sludge, 667, 0, :west
unit :archer, 668, 0, :west
unit :sludge, 669, 0, :west
unit :archer, 670, 0, :west
unit :sludge, 672, 0, :west
unit :archer, 673, 0, :west
unit :wizard, 675, 0, :west
unit :archer, 679, 0, :west
unit :sludge, 683, 0, :west
unit :thick_sludge, 684, 0, :west
unit :wizard, 685, 0, :west
unit :thick_sludge, 687, 0, :west
unit :wizard, 696, 0, :west
unit :archer, 702, 0, :west
unit :wizard, 707, 0, :west
unit :sludge, 709, 0, :west
unit :archer, 710, 0, :west
unit :captive, 715, 0, :west
unit :thick_sludge, 718, 0, :west
unit :sludge, 722, 0, :west
unit :thick_sludge, 725, 0, :west
unit :captive, 727, 0, :west
unit :thick_sludge, 728, 0, :west
unit :wizard, 731, 0, :west
unit :captive, 746, 0, :west
unit :thick_sludge, 748, 0, :west
unit :archer, 750, 0, :west
unit :wizard, 757, 0, :west
unit :sludge, 759, 0, :west
unit :wizard, 765, 0, :west
unit :thick_sludge, 766, 0, :west
unit :sludge, 770, 0, :west
unit :thick_sludge, 786, 0, :west
unit :thick_sludge, 793, 0, :west
unit :thick_sludge, 796, 0, :west
unit :sludge, 797, 0, :west
unit :sludge, 800, 0, :west
unit :wizard, 802, 0, :west
unit :thick_sludge, 808, 0, :west
unit :captive, 814, 0, :west
unit :captive, 816, 0, :west
unit :archer, 818, 0, :west
unit :captive, 820, 0, :west
unit :archer, 823, 0, :west
unit :captive, 825, 0, :west
unit :captive, 826, 0, :west
unit :thick_sludge, 830, 0, :west
unit :thick_sludge, 832, 0, :west
