#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |ss w        a  w S  a   S   a a  a   w    >   SC s   s S     w C         S  CC       a       w     s  s  w  s          aS   S  w   a    a                   w   w      C  w w    Ss   CCs s     a  S S   S     s  sa C C  w  C  s a Cs C        s        a a     w   CS    w       S C   C  s w w CCS w  a     w      S C    Cs   a w  w  a       w  s      Sa  w       CC C              sa   s    s  S w        wSw   S   s    C     CS w  s       C  s CS  C w a Cs   s S      C     s    as  w a      S w     w S        S    a  S         C   as Ss          s       s         w C  C a       S    @   C  s w   a  a       Ca   S        a   w     S Casw  Cs          aSs  S          a        C sas   S    s w          S ws            w      s  wS  s   SC s S      C S         aC C Csw   s   s SS   C    C   C C   C          w wS  aC   w  S  w S   w    Ca  w   s    Ss   C  C            s      w Cs                Ca s   s              a   w      a C    S     S     C               S C C   a  S   sS         |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 992
ace_score 4960
size 992, 1
stairs 42, 0

warrior 584, 0, :east

unit :sludge, 0, 0, :east
unit :sludge, 1, 0, :east
unit :wizard, 3, 0, :east
unit :archer, 12, 0, :east
unit :wizard, 15, 0, :east
unit :thick_sludge, 17, 0, :east
unit :archer, 20, 0, :east
unit :thick_sludge, 24, 0, :east
unit :archer, 28, 0, :east
unit :archer, 30, 0, :east
unit :archer, 33, 0, :east
unit :wizard, 37, 0, :east
unit :thick_sludge, 46, 0, :east
unit :captive, 47, 0, :east
unit :sludge, 49, 0, :east
unit :sludge, 53, 0, :east
unit :thick_sludge, 55, 0, :east
unit :wizard, 61, 0, :east
unit :captive, 63, 0, :east
unit :thick_sludge, 73, 0, :east
unit :captive, 76, 0, :east
unit :captive, 77, 0, :east
unit :archer, 85, 0, :east
unit :wizard, 93, 0, :east
unit :sludge, 99, 0, :east
unit :sludge, 102, 0, :east
unit :wizard, 105, 0, :east
unit :sludge, 108, 0, :east
unit :archer, 119, 0, :east
unit :thick_sludge, 120, 0, :east
unit :thick_sludge, 124, 0, :east
unit :wizard, 127, 0, :east
unit :archer, 131, 0, :east
unit :archer, 136, 0, :east
unit :wizard, 156, 0, :east
unit :wizard, 160, 0, :east
unit :captive, 167, 0, :east
unit :wizard, 170, 0, :east
unit :wizard, 172, 0, :east
unit :thick_sludge, 177, 0, :east
unit :sludge, 178, 0, :east
unit :captive, 182, 0, :east
unit :captive, 183, 0, :east
unit :sludge, 184, 0, :east
unit :sludge, 186, 0, :east
unit :archer, 192, 0, :east
unit :thick_sludge, 195, 0, :east
unit :thick_sludge, 197, 0, :east
unit :thick_sludge, 201, 0, :east
unit :sludge, 207, 0, :east
unit :sludge, 210, 0, :east
unit :archer, 211, 0, :east
unit :captive, 213, 0, :east
unit :captive, 215, 0, :east
unit :wizard, 218, 0, :east
unit :captive, 221, 0, :east
unit :sludge, 224, 0, :east
unit :archer, 226, 0, :east
unit :captive, 228, 0, :east
unit :sludge, 229, 0, :east
unit :captive, 231, 0, :east
unit :sludge, 240, 0, :east
unit :archer, 249, 0, :east
unit :archer, 251, 0, :east
unit :wizard, 257, 0, :east
unit :captive, 261, 0, :east
unit :thick_sludge, 262, 0, :east
unit :wizard, 267, 0, :east
unit :thick_sludge, 275, 0, :east
unit :captive, 277, 0, :east
unit :captive, 281, 0, :east
unit :sludge, 284, 0, :east
unit :wizard, 286, 0, :east
unit :wizard, 288, 0, :east
unit :captive, 290, 0, :east
unit :captive, 291, 0, :east
unit :thick_sludge, 292, 0, :east
unit :wizard, 294, 0, :east
unit :archer, 297, 0, :east
unit :wizard, 303, 0, :east
unit :thick_sludge, 310, 0, :east
unit :captive, 312, 0, :east
unit :captive, 317, 0, :east
unit :sludge, 318, 0, :east
unit :archer, 322, 0, :east
unit :wizard, 324, 0, :east
unit :wizard, 327, 0, :east
unit :archer, 330, 0, :east
unit :wizard, 338, 0, :east
unit :sludge, 341, 0, :east
unit :thick_sludge, 348, 0, :east
unit :archer, 349, 0, :east
unit :wizard, 352, 0, :east
unit :captive, 360, 0, :east
unit :captive, 361, 0, :east
unit :captive, 363, 0, :east
unit :sludge, 378, 0, :east
unit :archer, 379, 0, :east
unit :sludge, 383, 0, :east
unit :sludge, 388, 0, :east
unit :thick_sludge, 391, 0, :east
unit :wizard, 393, 0, :east
unit :wizard, 402, 0, :east
unit :thick_sludge, 403, 0, :east
unit :wizard, 404, 0, :east
unit :thick_sludge, 408, 0, :east
unit :sludge, 412, 0, :east
unit :captive, 417, 0, :east
unit :captive, 423, 0, :east
unit :thick_sludge, 424, 0, :east
unit :wizard, 426, 0, :east
unit :sludge, 429, 0, :east
unit :captive, 437, 0, :east
unit :sludge, 440, 0, :east
unit :captive, 442, 0, :east
unit :thick_sludge, 443, 0, :east
unit :captive, 446, 0, :east
unit :wizard, 448, 0, :east
unit :archer, 450, 0, :east
unit :captive, 452, 0, :east
unit :sludge, 453, 0, :east
unit :sludge, 457, 0, :east
unit :thick_sludge, 459, 0, :east
unit :captive, 466, 0, :east
unit :sludge, 472, 0, :east
unit :archer, 477, 0, :east
unit :sludge, 478, 0, :east
unit :wizard, 481, 0, :east
unit :archer, 483, 0, :east
unit :thick_sludge, 490, 0, :east
unit :wizard, 492, 0, :east
unit :wizard, 498, 0, :east
unit :thick_sludge, 500, 0, :east
unit :thick_sludge, 509, 0, :east
unit :archer, 514, 0, :east
unit :thick_sludge, 517, 0, :east
unit :captive, 527, 0, :east
unit :archer, 531, 0, :east
unit :sludge, 532, 0, :east
unit :thick_sludge, 534, 0, :east
unit :sludge, 535, 0, :east
unit :sludge, 546, 0, :east
unit :sludge, 554, 0, :east
unit :wizard, 564, 0, :east
unit :captive, 566, 0, :east
unit :captive, 569, 0, :east
unit :archer, 571, 0, :east
unit :thick_sludge, 579, 0, :east
unit :captive, 588, 0, :west
unit :sludge, 591, 0, :west
unit :wizard, 593, 0, :west
unit :archer, 597, 0, :west
unit :archer, 600, 0, :west
unit :captive, 608, 0, :west
unit :archer, 609, 0, :west
unit :thick_sludge, 613, 0, :west
unit :archer, 622, 0, :west
unit :wizard, 626, 0, :west
unit :thick_sludge, 632, 0, :west
unit :captive, 634, 0, :west
unit :archer, 635, 0, :west
unit :sludge, 636, 0, :west
unit :wizard, 637, 0, :west
unit :captive, 640, 0, :west
unit :sludge, 641, 0, :west
unit :archer, 652, 0, :west
unit :thick_sludge, 653, 0, :west
unit :sludge, 654, 0, :west
unit :thick_sludge, 657, 0, :west
unit :archer, 668, 0, :west
unit :captive, 677, 0, :west
unit :sludge, 679, 0, :west
unit :archer, 680, 0, :west
unit :sludge, 681, 0, :west
unit :thick_sludge, 685, 0, :west
unit :sludge, 690, 0, :west
unit :wizard, 692, 0, :west
unit :thick_sludge, 703, 0, :west
unit :wizard, 705, 0, :west
unit :sludge, 706, 0, :west
unit :wizard, 719, 0, :west
unit :sludge, 726, 0, :west
unit :wizard, 729, 0, :west
unit :thick_sludge, 730, 0, :west
unit :sludge, 733, 0, :west
unit :thick_sludge, 737, 0, :west
unit :captive, 738, 0, :west
unit :sludge, 740, 0, :west
unit :thick_sludge, 742, 0, :west
unit :captive, 749, 0, :west
unit :thick_sludge, 751, 0, :west
unit :archer, 761, 0, :west
unit :captive, 762, 0, :west
unit :captive, 764, 0, :west
unit :captive, 766, 0, :west
unit :sludge, 767, 0, :west
unit :wizard, 768, 0, :west
unit :sludge, 772, 0, :west
unit :sludge, 776, 0, :west
unit :thick_sludge, 778, 0, :west
unit :thick_sludge, 779, 0, :west
unit :captive, 783, 0, :west
unit :captive, 788, 0, :west
unit :captive, 792, 0, :west
unit :captive, 794, 0, :west
unit :captive, 798, 0, :west
unit :wizard, 809, 0, :west
unit :wizard, 811, 0, :west
unit :thick_sludge, 812, 0, :west
unit :archer, 815, 0, :west
unit :captive, 816, 0, :west
unit :wizard, 820, 0, :west
unit :thick_sludge, 823, 0, :west
unit :wizard, 826, 0, :west
unit :thick_sludge, 828, 0, :west
unit :wizard, 832, 0, :west
unit :captive, 837, 0, :west
unit :archer, 838, 0, :west
unit :wizard, 841, 0, :west
unit :sludge, 845, 0, :west
unit :thick_sludge, 850, 0, :west
unit :sludge, 851, 0, :west
unit :captive, 855, 0, :west
unit :captive, 858, 0, :west
unit :sludge, 871, 0, :west
unit :wizard, 878, 0, :west
unit :captive, 880, 0, :west
unit :sludge, 881, 0, :west
unit :captive, 898, 0, :west
unit :archer, 899, 0, :west
unit :sludge, 901, 0, :west
unit :sludge, 905, 0, :west
unit :archer, 920, 0, :west
unit :wizard, 924, 0, :west
unit :archer, 931, 0, :west
unit :captive, 933, 0, :west
unit :thick_sludge, 938, 0, :west
unit :thick_sludge, 944, 0, :west
unit :captive, 950, 0, :west
unit :thick_sludge, 966, 0, :west
unit :captive, 968, 0, :west
unit :captive, 970, 0, :west
unit :archer, 974, 0, :west
unit :thick_sludge, 977, 0, :west
unit :sludge, 981, 0, :west
unit :thick_sludge, 982, 0, :west
