#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w  a w    s   a C w  aS   s a    a S          ss w      w   a     s          sa  S w  w S    aS           Cs ws S sa     S       SS              a    S  a sa      sC s    s     C      a  w aS  C        s s   S     C ws a  s SS    s w    w                aC  S   S wa C  s  S   S            w  s  a S C  C  S  w    CCw sSw S  S     C  s     ssa  s   S   w    S  C   w C   a   C     s     a  Ss  s    w  C s     C    SC     sC  a  C s     as  S      s SS   C  a     C >C w      S             a    aC   a     C   S    a   s       a S     w  w     w    a  CC              @   C                w  SC   C a  CC                   w  wC                |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 646
ace_score 3230
size 646, 1
stairs 468, 0

warrior 570, 0, :east

unit :wizard, 2, 0, :east
unit :archer, 5, 0, :east
unit :wizard, 7, 0, :east
unit :sludge, 12, 0, :east
unit :archer, 16, 0, :east
unit :captive, 18, 0, :east
unit :wizard, 20, 0, :east
unit :archer, 23, 0, :east
unit :thick_sludge, 24, 0, :east
unit :sludge, 28, 0, :east
unit :archer, 30, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 37, 0, :east
unit :sludge, 48, 0, :east
unit :sludge, 49, 0, :east
unit :wizard, 51, 0, :east
unit :wizard, 58, 0, :east
unit :archer, 62, 0, :east
unit :sludge, 68, 0, :east
unit :sludge, 79, 0, :east
unit :archer, 80, 0, :east
unit :thick_sludge, 83, 0, :east
unit :wizard, 85, 0, :east
unit :wizard, 88, 0, :east
unit :thick_sludge, 90, 0, :east
unit :archer, 95, 0, :east
unit :thick_sludge, 96, 0, :east
unit :captive, 108, 0, :east
unit :sludge, 109, 0, :east
unit :wizard, 111, 0, :east
unit :sludge, 112, 0, :east
unit :thick_sludge, 114, 0, :east
unit :sludge, 116, 0, :east
unit :archer, 117, 0, :east
unit :thick_sludge, 123, 0, :east
unit :thick_sludge, 131, 0, :east
unit :thick_sludge, 132, 0, :east
unit :archer, 147, 0, :east
unit :thick_sludge, 152, 0, :east
unit :archer, 155, 0, :east
unit :sludge, 157, 0, :east
unit :archer, 158, 0, :east
unit :sludge, 165, 0, :east
unit :captive, 166, 0, :east
unit :sludge, 168, 0, :east
unit :sludge, 173, 0, :east
unit :captive, 179, 0, :east
unit :archer, 186, 0, :east
unit :wizard, 189, 0, :east
unit :archer, 191, 0, :east
unit :thick_sludge, 192, 0, :east
unit :captive, 195, 0, :east
unit :sludge, 204, 0, :east
unit :sludge, 206, 0, :east
unit :thick_sludge, 210, 0, :east
unit :captive, 216, 0, :east
unit :wizard, 218, 0, :east
unit :sludge, 219, 0, :east
unit :archer, 221, 0, :east
unit :sludge, 224, 0, :east
unit :thick_sludge, 226, 0, :east
unit :thick_sludge, 227, 0, :east
unit :sludge, 232, 0, :east
unit :wizard, 234, 0, :east
unit :wizard, 239, 0, :east
unit :archer, 256, 0, :east
unit :captive, 257, 0, :east
unit :thick_sludge, 260, 0, :east
unit :thick_sludge, 264, 0, :east
unit :wizard, 266, 0, :east
unit :archer, 267, 0, :east
unit :captive, 269, 0, :east
unit :sludge, 272, 0, :east
unit :thick_sludge, 275, 0, :east
unit :thick_sludge, 279, 0, :east
unit :wizard, 292, 0, :east
unit :sludge, 295, 0, :east
unit :archer, 298, 0, :east
unit :thick_sludge, 300, 0, :east
unit :captive, 302, 0, :east
unit :captive, 305, 0, :east
unit :thick_sludge, 308, 0, :east
unit :wizard, 311, 0, :east
unit :captive, 316, 0, :east
unit :captive, 317, 0, :east
unit :wizard, 318, 0, :east
unit :sludge, 320, 0, :east
unit :thick_sludge, 321, 0, :east
unit :wizard, 322, 0, :east
unit :thick_sludge, 324, 0, :east
unit :thick_sludge, 327, 0, :east
unit :captive, 333, 0, :east
unit :sludge, 336, 0, :east
unit :sludge, 342, 0, :east
unit :sludge, 343, 0, :east
unit :archer, 344, 0, :east
unit :sludge, 347, 0, :east
unit :thick_sludge, 351, 0, :east
unit :wizard, 355, 0, :east
unit :thick_sludge, 360, 0, :east
unit :captive, 363, 0, :east
unit :wizard, 367, 0, :east
unit :captive, 369, 0, :east
unit :archer, 373, 0, :east
unit :captive, 377, 0, :east
unit :sludge, 383, 0, :east
unit :archer, 389, 0, :east
unit :thick_sludge, 392, 0, :east
unit :sludge, 393, 0, :east
unit :sludge, 396, 0, :east
unit :wizard, 401, 0, :east
unit :captive, 404, 0, :east
unit :sludge, 406, 0, :east
unit :captive, 412, 0, :east
unit :thick_sludge, 417, 0, :east
unit :captive, 418, 0, :east
unit :sludge, 424, 0, :east
unit :captive, 425, 0, :east
unit :archer, 428, 0, :east
unit :captive, 431, 0, :east
unit :sludge, 433, 0, :east
unit :archer, 439, 0, :east
unit :sludge, 440, 0, :east
unit :thick_sludge, 443, 0, :east
unit :sludge, 450, 0, :east
unit :thick_sludge, 452, 0, :east
unit :thick_sludge, 453, 0, :east
unit :captive, 457, 0, :east
unit :archer, 460, 0, :east
unit :captive, 466, 0, :east
unit :captive, 469, 0, :east
unit :wizard, 471, 0, :east
unit :thick_sludge, 478, 0, :east
unit :archer, 492, 0, :east
unit :archer, 497, 0, :east
unit :captive, 498, 0, :east
unit :archer, 502, 0, :east
unit :captive, 508, 0, :east
unit :thick_sludge, 512, 0, :east
unit :archer, 517, 0, :east
unit :sludge, 521, 0, :east
unit :archer, 529, 0, :east
unit :thick_sludge, 531, 0, :east
unit :wizard, 537, 0, :east
unit :wizard, 540, 0, :east
unit :wizard, 546, 0, :east
unit :archer, 551, 0, :east
unit :captive, 554, 0, :east
unit :captive, 555, 0, :east
unit :captive, 574, 0, :west
unit :wizard, 591, 0, :west
unit :thick_sludge, 594, 0, :west
unit :captive, 595, 0, :west
unit :captive, 599, 0, :west
unit :archer, 601, 0, :west
unit :captive, 604, 0, :west
unit :captive, 605, 0, :west
unit :wizard, 625, 0, :west
unit :wizard, 628, 0, :west
unit :captive, 629, 0, :west
