#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |        C  C   a S   aCs S   S  s      C>a C      S       sC    s    w   w   ss          w  S     S  s    a a S w     C S     Cw               C   s    a   C    w Cs        w     C w                  C       s  @        s   C  C   CsaSa       S s        a         S       w sS             sa               C            C  s   sw  C        C           S    S S  C    w    C s aS    C  sS      a w               sw  S    S   S  w  s w    s  w  S w   Cs S   w s   a s   S S     s C Ca S     w S  s  S     a      S  S C     w a                    C Sss     C  C C    s  S     SSa  sC sas    S Sw  a     w      a a s  a   C a  s  s s           a     ss w        w S   s w  a        C        wS    S  aSC  aa CC         s   s   C     a w w       SSa Csa CC    C   Sa S  C    Sa    wC S       wS         C   C        a Ss w     ss S S      w    aC  C          SsS   S    s C    a   SS      S  w  |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 889
ace_score 4445
size 889, 1
stairs 40, 0

warrior 211, 0, :east

unit :captive, 8, 0, :east
unit :captive, 11, 0, :east
unit :archer, 15, 0, :east
unit :thick_sludge, 17, 0, :east
unit :archer, 21, 0, :east
unit :captive, 22, 0, :east
unit :sludge, 23, 0, :east
unit :thick_sludge, 25, 0, :east
unit :thick_sludge, 29, 0, :east
unit :sludge, 32, 0, :east
unit :captive, 39, 0, :east
unit :archer, 41, 0, :east
unit :captive, 43, 0, :east
unit :thick_sludge, 50, 0, :east
unit :sludge, 58, 0, :east
unit :captive, 59, 0, :east
unit :sludge, 64, 0, :east
unit :wizard, 69, 0, :east
unit :wizard, 73, 0, :east
unit :sludge, 77, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 89, 0, :east
unit :thick_sludge, 92, 0, :east
unit :thick_sludge, 98, 0, :east
unit :sludge, 101, 0, :east
unit :archer, 106, 0, :east
unit :archer, 108, 0, :east
unit :thick_sludge, 110, 0, :east
unit :wizard, 112, 0, :east
unit :captive, 118, 0, :east
unit :thick_sludge, 120, 0, :east
unit :captive, 126, 0, :east
unit :wizard, 127, 0, :east
unit :captive, 143, 0, :east
unit :sludge, 147, 0, :east
unit :archer, 152, 0, :east
unit :captive, 156, 0, :east
unit :wizard, 161, 0, :east
unit :captive, 163, 0, :east
unit :sludge, 164, 0, :east
unit :wizard, 173, 0, :east
unit :captive, 179, 0, :east
unit :wizard, 181, 0, :east
unit :captive, 200, 0, :east
unit :sludge, 208, 0, :east
unit :sludge, 220, 0, :west
unit :captive, 224, 0, :west
unit :captive, 227, 0, :west
unit :captive, 231, 0, :west
unit :sludge, 232, 0, :west
unit :archer, 233, 0, :west
unit :thick_sludge, 234, 0, :west
unit :archer, 235, 0, :west
unit :thick_sludge, 243, 0, :west
unit :sludge, 245, 0, :west
unit :archer, 254, 0, :west
unit :thick_sludge, 264, 0, :west
unit :wizard, 272, 0, :west
unit :sludge, 274, 0, :west
unit :thick_sludge, 275, 0, :west
unit :sludge, 289, 0, :west
unit :archer, 290, 0, :west
unit :captive, 306, 0, :west
unit :captive, 319, 0, :west
unit :sludge, 322, 0, :west
unit :sludge, 326, 0, :west
unit :wizard, 327, 0, :west
unit :captive, 330, 0, :west
unit :captive, 339, 0, :west
unit :thick_sludge, 351, 0, :west
unit :thick_sludge, 356, 0, :west
unit :thick_sludge, 358, 0, :west
unit :captive, 361, 0, :west
unit :wizard, 366, 0, :west
unit :captive, 371, 0, :west
unit :sludge, 373, 0, :west
unit :archer, 375, 0, :west
unit :thick_sludge, 376, 0, :west
unit :captive, 381, 0, :west
unit :sludge, 384, 0, :west
unit :thick_sludge, 385, 0, :west
unit :archer, 392, 0, :west
unit :wizard, 394, 0, :west
unit :sludge, 410, 0, :west
unit :wizard, 411, 0, :west
unit :thick_sludge, 414, 0, :west
unit :thick_sludge, 419, 0, :west
unit :thick_sludge, 423, 0, :west
unit :wizard, 426, 0, :west
unit :sludge, 429, 0, :west
unit :wizard, 431, 0, :west
unit :sludge, 436, 0, :west
unit :wizard, 439, 0, :west
unit :thick_sludge, 442, 0, :west
unit :wizard, 444, 0, :west
unit :captive, 448, 0, :west
unit :sludge, 449, 0, :west
unit :thick_sludge, 451, 0, :west
unit :wizard, 455, 0, :west
unit :sludge, 457, 0, :west
unit :archer, 461, 0, :west
unit :sludge, 463, 0, :west
unit :thick_sludge, 467, 0, :west
unit :thick_sludge, 469, 0, :west
unit :sludge, 475, 0, :west
unit :captive, 477, 0, :west
unit :captive, 479, 0, :west
unit :archer, 480, 0, :west
unit :thick_sludge, 482, 0, :west
unit :wizard, 488, 0, :west
unit :thick_sludge, 490, 0, :west
unit :sludge, 493, 0, :west
unit :thick_sludge, 496, 0, :west
unit :archer, 502, 0, :west
unit :thick_sludge, 509, 0, :west
unit :thick_sludge, 512, 0, :west
unit :captive, 514, 0, :west
unit :wizard, 520, 0, :west
unit :archer, 522, 0, :west
unit :captive, 543, 0, :west
unit :thick_sludge, 545, 0, :west
unit :sludge, 546, 0, :west
unit :sludge, 547, 0, :west
unit :captive, 553, 0, :west
unit :captive, 556, 0, :west
unit :captive, 558, 0, :west
unit :sludge, 563, 0, :west
unit :thick_sludge, 566, 0, :west
unit :thick_sludge, 572, 0, :west
unit :thick_sludge, 573, 0, :west
unit :archer, 574, 0, :west
unit :sludge, 577, 0, :west
unit :captive, 578, 0, :west
unit :sludge, 580, 0, :west
unit :archer, 581, 0, :west
unit :sludge, 582, 0, :west
unit :thick_sludge, 587, 0, :west
unit :thick_sludge, 589, 0, :west
unit :wizard, 590, 0, :west
unit :archer, 593, 0, :west
unit :wizard, 599, 0, :west
unit :archer, 606, 0, :west
unit :archer, 608, 0, :west
unit :sludge, 610, 0, :west
unit :archer, 613, 0, :west
unit :captive, 617, 0, :west
unit :archer, 619, 0, :west
unit :sludge, 622, 0, :west
unit :sludge, 625, 0, :west
unit :sludge, 627, 0, :west
unit :archer, 639, 0, :west
unit :sludge, 645, 0, :west
unit :sludge, 646, 0, :west
unit :wizard, 648, 0, :west
unit :wizard, 657, 0, :west
unit :thick_sludge, 659, 0, :west
unit :sludge, 663, 0, :west
unit :wizard, 665, 0, :west
unit :archer, 668, 0, :west
unit :captive, 677, 0, :west
unit :wizard, 686, 0, :west
unit :thick_sludge, 687, 0, :west
unit :thick_sludge, 692, 0, :west
unit :archer, 695, 0, :west
unit :thick_sludge, 696, 0, :west
unit :captive, 697, 0, :west
unit :archer, 700, 0, :west
unit :archer, 701, 0, :west
unit :captive, 703, 0, :west
unit :captive, 704, 0, :west
unit :sludge, 714, 0, :west
unit :sludge, 718, 0, :west
unit :captive, 722, 0, :west
unit :archer, 728, 0, :west
unit :wizard, 730, 0, :west
unit :wizard, 732, 0, :west
unit :thick_sludge, 740, 0, :west
unit :thick_sludge, 741, 0, :west
unit :archer, 742, 0, :west
unit :captive, 744, 0, :west
unit :sludge, 745, 0, :west
unit :archer, 746, 0, :west
unit :captive, 748, 0, :west
unit :captive, 749, 0, :west
unit :captive, 754, 0, :west
unit :thick_sludge, 758, 0, :west
unit :archer, 759, 0, :west
unit :thick_sludge, 761, 0, :west
unit :captive, 764, 0, :west
unit :thick_sludge, 769, 0, :west
unit :archer, 770, 0, :west
unit :wizard, 775, 0, :west
unit :captive, 776, 0, :west
unit :thick_sludge, 778, 0, :west
unit :wizard, 786, 0, :west
unit :thick_sludge, 787, 0, :west
unit :captive, 797, 0, :west
unit :captive, 801, 0, :west
unit :archer, 810, 0, :west
unit :thick_sludge, 812, 0, :west
unit :sludge, 813, 0, :west
unit :wizard, 815, 0, :west
unit :sludge, 821, 0, :west
unit :sludge, 822, 0, :west
unit :thick_sludge, 824, 0, :west
unit :thick_sludge, 826, 0, :west
unit :wizard, 833, 0, :west
unit :archer, 838, 0, :west
unit :captive, 839, 0, :west
unit :captive, 842, 0, :west
unit :thick_sludge, 853, 0, :west
unit :sludge, 854, 0, :west
unit :thick_sludge, 855, 0, :west
unit :thick_sludge, 859, 0, :west
unit :sludge, 864, 0, :west
unit :captive, 866, 0, :west
unit :archer, 871, 0, :west
unit :thick_sludge, 875, 0, :west
unit :thick_sludge, 876, 0, :west
unit :thick_sludge, 883, 0, :west
unit :wizard, 886, 0, :west
