#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |         C  w Ca                w  s C    wC  s  s     S          a  Sw   sS   sC     a           aC    C      a       S CaS    S CS S   C         w    w    a        s  s     C  a    a      w    C  aS  w   C              w  SS a     S S S SS a  w          C w S    Sa    a S          w  C   Ss    aa S          Cs w      a      S  s> w a        SS         a  C C S  w     C C a  s     w        s  CC  w  Sw   S   aC   a      s    sSs    SS    w aS             aas  S s                 s w        SS   s w  a  s    a   aC Ss a     S      w  a  C   S   S    C    S   C C         s S    w S  @      C a  CC   S        Sa Cs a a     saS      S s      Cs S  w C       w C        s         w a         w   s w S   Ca w  CC      a  w w      S         a   w  a    w a S|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 761
ace_score 3805
size 761, 1
stairs 332, 0

warrior 589, 0, :east

unit :captive, 9, 0, :east
unit :wizard, 12, 0, :east
unit :captive, 14, 0, :east
unit :archer, 15, 0, :east
unit :wizard, 32, 0, :east
unit :sludge, 35, 0, :east
unit :captive, 37, 0, :east
unit :wizard, 42, 0, :east
unit :captive, 43, 0, :east
unit :sludge, 46, 0, :east
unit :sludge, 49, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 66, 0, :east
unit :thick_sludge, 69, 0, :east
unit :wizard, 70, 0, :east
unit :sludge, 74, 0, :east
unit :thick_sludge, 75, 0, :east
unit :sludge, 79, 0, :east
unit :captive, 80, 0, :east
unit :archer, 86, 0, :east
unit :archer, 98, 0, :east
unit :captive, 99, 0, :east
unit :captive, 104, 0, :east
unit :archer, 111, 0, :east
unit :thick_sludge, 119, 0, :east
unit :captive, 121, 0, :east
unit :archer, 122, 0, :east
unit :thick_sludge, 123, 0, :east
unit :thick_sludge, 128, 0, :east
unit :captive, 130, 0, :east
unit :thick_sludge, 131, 0, :east
unit :thick_sludge, 133, 0, :east
unit :captive, 137, 0, :east
unit :wizard, 147, 0, :east
unit :wizard, 152, 0, :east
unit :archer, 157, 0, :east
unit :sludge, 166, 0, :east
unit :sludge, 169, 0, :east
unit :captive, 175, 0, :east
unit :archer, 178, 0, :east
unit :archer, 183, 0, :east
unit :wizard, 190, 0, :east
unit :captive, 195, 0, :east
unit :archer, 198, 0, :east
unit :thick_sludge, 199, 0, :east
unit :wizard, 202, 0, :east
unit :captive, 206, 0, :east
unit :wizard, 221, 0, :east
unit :thick_sludge, 224, 0, :east
unit :thick_sludge, 225, 0, :east
unit :archer, 227, 0, :east
unit :thick_sludge, 233, 0, :east
unit :thick_sludge, 235, 0, :east
unit :thick_sludge, 237, 0, :east
unit :thick_sludge, 239, 0, :east
unit :thick_sludge, 240, 0, :east
unit :archer, 242, 0, :east
unit :wizard, 245, 0, :east
unit :captive, 256, 0, :east
unit :wizard, 258, 0, :east
unit :thick_sludge, 260, 0, :east
unit :thick_sludge, 265, 0, :east
unit :archer, 266, 0, :east
unit :archer, 271, 0, :east
unit :thick_sludge, 273, 0, :east
unit :wizard, 284, 0, :east
unit :captive, 287, 0, :east
unit :thick_sludge, 291, 0, :east
unit :sludge, 292, 0, :east
unit :archer, 297, 0, :east
unit :archer, 298, 0, :east
unit :thick_sludge, 300, 0, :east
unit :captive, 311, 0, :east
unit :sludge, 312, 0, :east
unit :wizard, 314, 0, :east
unit :archer, 321, 0, :east
unit :thick_sludge, 328, 0, :east
unit :sludge, 331, 0, :east
unit :wizard, 334, 0, :east
unit :archer, 336, 0, :east
unit :thick_sludge, 345, 0, :east
unit :thick_sludge, 346, 0, :east
unit :archer, 356, 0, :east
unit :captive, 359, 0, :east
unit :captive, 361, 0, :east
unit :thick_sludge, 363, 0, :east
unit :wizard, 366, 0, :east
unit :captive, 372, 0, :east
unit :captive, 374, 0, :east
unit :archer, 376, 0, :east
unit :sludge, 379, 0, :east
unit :wizard, 385, 0, :east
unit :sludge, 394, 0, :east
unit :captive, 397, 0, :east
unit :captive, 398, 0, :east
unit :wizard, 401, 0, :east
unit :thick_sludge, 404, 0, :east
unit :wizard, 405, 0, :east
unit :thick_sludge, 409, 0, :east
unit :archer, 413, 0, :east
unit :captive, 414, 0, :east
unit :archer, 418, 0, :east
unit :sludge, 425, 0, :east
unit :sludge, 430, 0, :east
unit :thick_sludge, 431, 0, :east
unit :sludge, 432, 0, :east
unit :thick_sludge, 437, 0, :east
unit :thick_sludge, 438, 0, :east
unit :wizard, 443, 0, :east
unit :archer, 445, 0, :east
unit :thick_sludge, 446, 0, :east
unit :archer, 460, 0, :east
unit :archer, 461, 0, :east
unit :sludge, 462, 0, :east
unit :thick_sludge, 465, 0, :east
unit :sludge, 467, 0, :east
unit :sludge, 485, 0, :east
unit :wizard, 487, 0, :east
unit :thick_sludge, 496, 0, :east
unit :thick_sludge, 497, 0, :east
unit :sludge, 501, 0, :east
unit :wizard, 503, 0, :east
unit :archer, 506, 0, :east
unit :sludge, 509, 0, :east
unit :archer, 514, 0, :east
unit :archer, 518, 0, :east
unit :captive, 519, 0, :east
unit :thick_sludge, 521, 0, :east
unit :sludge, 522, 0, :east
unit :archer, 524, 0, :east
unit :thick_sludge, 530, 0, :east
unit :wizard, 537, 0, :east
unit :archer, 540, 0, :east
unit :captive, 543, 0, :east
unit :thick_sludge, 547, 0, :east
unit :thick_sludge, 551, 0, :east
unit :captive, 556, 0, :east
unit :thick_sludge, 561, 0, :east
unit :captive, 565, 0, :east
unit :captive, 567, 0, :east
unit :sludge, 577, 0, :east
unit :thick_sludge, 579, 0, :east
unit :wizard, 584, 0, :east
unit :thick_sludge, 586, 0, :east
unit :captive, 596, 0, :west
unit :archer, 598, 0, :west
unit :captive, 601, 0, :west
unit :captive, 602, 0, :west
unit :thick_sludge, 606, 0, :west
unit :thick_sludge, 615, 0, :west
unit :archer, 616, 0, :west
unit :captive, 618, 0, :west
unit :sludge, 619, 0, :west
unit :archer, 621, 0, :west
unit :archer, 623, 0, :west
unit :sludge, 629, 0, :west
unit :archer, 630, 0, :west
unit :thick_sludge, 631, 0, :west
unit :thick_sludge, 638, 0, :west
unit :sludge, 640, 0, :west
unit :captive, 647, 0, :west
unit :sludge, 648, 0, :west
unit :thick_sludge, 650, 0, :west
unit :wizard, 653, 0, :west
unit :captive, 655, 0, :west
unit :wizard, 663, 0, :west
unit :captive, 665, 0, :west
unit :sludge, 674, 0, :west
unit :wizard, 684, 0, :west
unit :archer, 686, 0, :west
unit :wizard, 696, 0, :west
unit :sludge, 700, 0, :west
unit :wizard, 702, 0, :west
unit :thick_sludge, 704, 0, :west
unit :captive, 708, 0, :west
unit :archer, 709, 0, :west
unit :wizard, 711, 0, :west
unit :captive, 714, 0, :west
unit :captive, 715, 0, :west
unit :archer, 722, 0, :west
unit :wizard, 725, 0, :west
unit :wizard, 727, 0, :west
unit :thick_sludge, 734, 0, :west
unit :archer, 744, 0, :west
unit :wizard, 748, 0, :west
unit :archer, 751, 0, :west
unit :wizard, 756, 0, :west
unit :archer, 758, 0, :west
unit :thick_sludge, 760, 0, :west
