#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |SCas s        S   s   S S S a ss   a a  a     CS    aCC     wS   w w a w    s w a ss   s  S aS  w S    C      s         S       a  s  CS                a C    s a       w    s       ss a S CC    S     s       C       C    w  C         a S   C wC S             a    w  s   as           w      w    S a sS   C            w  CCs                 w sC    s C                  w  a  w CS     w     S  w            w S      S      aa       @   C   w    s a  S S  S     a C  sS         S    C            w    w w      >  S wsS   a  s  a       a   w  C s    SC w     SC   C    S S   CS     C    C       S       ss w  Sa               Cs aC            sw  aC aC  Ss        w  w  a                       w  C         w  S S   S    SS      a   S   w  C  a a   w  S       s    sa  s  w      s s     C    w  C   as w w  wa C       S S C S C   C    C w aC   CC  s a      w   s w      a SsS   ws       C S SC C              a   w        a Ca s S    aC       S s      sC  C s      S a w       C |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 978
ace_score 4890
size 978, 1
stairs 510, 0

warrior 433, 0, :east

unit :thick_sludge, 0, 0, :east
unit :captive, 1, 0, :east
unit :archer, 2, 0, :east
unit :sludge, 3, 0, :east
unit :sludge, 5, 0, :east
unit :thick_sludge, 14, 0, :east
unit :sludge, 18, 0, :east
unit :thick_sludge, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :thick_sludge, 26, 0, :east
unit :archer, 28, 0, :east
unit :sludge, 30, 0, :east
unit :sludge, 31, 0, :east
unit :archer, 35, 0, :east
unit :archer, 37, 0, :east
unit :archer, 40, 0, :east
unit :captive, 46, 0, :east
unit :thick_sludge, 47, 0, :east
unit :archer, 52, 0, :east
unit :captive, 53, 0, :east
unit :captive, 54, 0, :east
unit :wizard, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :wizard, 65, 0, :east
unit :wizard, 67, 0, :east
unit :archer, 69, 0, :east
unit :wizard, 71, 0, :east
unit :sludge, 76, 0, :east
unit :wizard, 78, 0, :east
unit :archer, 80, 0, :east
unit :sludge, 82, 0, :east
unit :sludge, 83, 0, :east
unit :sludge, 87, 0, :east
unit :thick_sludge, 90, 0, :east
unit :archer, 92, 0, :east
unit :thick_sludge, 93, 0, :east
unit :wizard, 96, 0, :east
unit :thick_sludge, 98, 0, :east
unit :captive, 103, 0, :east
unit :sludge, 110, 0, :east
unit :thick_sludge, 120, 0, :east
unit :archer, 128, 0, :east
unit :sludge, 131, 0, :east
unit :captive, 134, 0, :east
unit :thick_sludge, 135, 0, :east
unit :archer, 152, 0, :east
unit :captive, 154, 0, :east
unit :sludge, 159, 0, :east
unit :archer, 161, 0, :east
unit :wizard, 169, 0, :east
unit :sludge, 174, 0, :east
unit :sludge, 182, 0, :east
unit :sludge, 183, 0, :east
unit :archer, 185, 0, :east
unit :thick_sludge, 187, 0, :east
unit :captive, 189, 0, :east
unit :captive, 190, 0, :east
unit :thick_sludge, 195, 0, :east
unit :sludge, 201, 0, :east
unit :captive, 209, 0, :east
unit :captive, 217, 0, :east
unit :wizard, 222, 0, :east
unit :captive, 225, 0, :east
unit :archer, 235, 0, :east
unit :thick_sludge, 237, 0, :east
unit :captive, 241, 0, :east
unit :wizard, 243, 0, :east
unit :captive, 244, 0, :east
unit :thick_sludge, 246, 0, :east
unit :archer, 260, 0, :east
unit :wizard, 265, 0, :east
unit :sludge, 268, 0, :east
unit :archer, 272, 0, :east
unit :sludge, 273, 0, :east
unit :wizard, 285, 0, :east
unit :wizard, 292, 0, :east
unit :thick_sludge, 297, 0, :east
unit :archer, 299, 0, :east
unit :sludge, 301, 0, :east
unit :thick_sludge, 302, 0, :east
unit :captive, 306, 0, :east
unit :wizard, 319, 0, :east
unit :captive, 322, 0, :east
unit :captive, 323, 0, :east
unit :sludge, 324, 0, :east
unit :wizard, 342, 0, :east
unit :sludge, 344, 0, :east
unit :captive, 345, 0, :east
unit :sludge, 350, 0, :east
unit :captive, 352, 0, :east
unit :wizard, 371, 0, :east
unit :archer, 374, 0, :east
unit :wizard, 377, 0, :east
unit :captive, 379, 0, :east
unit :thick_sludge, 380, 0, :east
unit :wizard, 386, 0, :east
unit :thick_sludge, 392, 0, :east
unit :wizard, 395, 0, :east
unit :wizard, 408, 0, :east
unit :thick_sludge, 410, 0, :east
unit :thick_sludge, 417, 0, :east
unit :archer, 424, 0, :east
unit :archer, 425, 0, :east
unit :captive, 437, 0, :west
unit :wizard, 441, 0, :west
unit :sludge, 446, 0, :west
unit :archer, 448, 0, :west
unit :thick_sludge, 451, 0, :west
unit :thick_sludge, 453, 0, :west
unit :thick_sludge, 456, 0, :west
unit :archer, 462, 0, :west
unit :captive, 464, 0, :west
unit :sludge, 467, 0, :west
unit :thick_sludge, 468, 0, :west
unit :thick_sludge, 478, 0, :west
unit :captive, 483, 0, :west
unit :wizard, 496, 0, :west
unit :wizard, 501, 0, :west
unit :wizard, 503, 0, :west
unit :thick_sludge, 513, 0, :west
unit :wizard, 515, 0, :west
unit :sludge, 516, 0, :west
unit :thick_sludge, 517, 0, :west
unit :archer, 521, 0, :west
unit :sludge, 524, 0, :west
unit :archer, 527, 0, :west
unit :archer, 535, 0, :west
unit :wizard, 539, 0, :west
unit :captive, 542, 0, :west
unit :sludge, 544, 0, :west
unit :thick_sludge, 549, 0, :west
unit :captive, 550, 0, :west
unit :wizard, 552, 0, :west
unit :thick_sludge, 558, 0, :west
unit :captive, 559, 0, :west
unit :captive, 563, 0, :west
unit :thick_sludge, 568, 0, :west
unit :thick_sludge, 570, 0, :west
unit :captive, 574, 0, :west
unit :thick_sludge, 575, 0, :west
unit :captive, 581, 0, :west
unit :captive, 586, 0, :west
unit :thick_sludge, 594, 0, :west
unit :sludge, 602, 0, :west
unit :sludge, 603, 0, :west
unit :wizard, 605, 0, :west
unit :thick_sludge, 608, 0, :west
unit :archer, 609, 0, :west
unit :captive, 625, 0, :west
unit :sludge, 626, 0, :west
unit :archer, 628, 0, :west
unit :captive, 629, 0, :west
unit :sludge, 642, 0, :west
unit :wizard, 643, 0, :west
unit :archer, 646, 0, :west
unit :captive, 647, 0, :west
unit :archer, 649, 0, :west
unit :captive, 650, 0, :west
unit :thick_sludge, 653, 0, :west
unit :sludge, 654, 0, :west
unit :wizard, 663, 0, :west
unit :wizard, 666, 0, :west
unit :archer, 669, 0, :west
unit :wizard, 693, 0, :west
unit :captive, 696, 0, :west
unit :wizard, 706, 0, :west
unit :thick_sludge, 709, 0, :west
unit :thick_sludge, 711, 0, :west
unit :thick_sludge, 715, 0, :west
unit :thick_sludge, 720, 0, :west
unit :thick_sludge, 721, 0, :west
unit :archer, 728, 0, :west
unit :thick_sludge, 732, 0, :west
unit :wizard, 736, 0, :west
unit :captive, 739, 0, :west
unit :archer, 742, 0, :west
unit :archer, 744, 0, :west
unit :wizard, 748, 0, :west
unit :thick_sludge, 751, 0, :west
unit :sludge, 759, 0, :west
unit :sludge, 764, 0, :west
unit :archer, 765, 0, :west
unit :sludge, 768, 0, :west
unit :wizard, 771, 0, :west
unit :sludge, 778, 0, :west
unit :sludge, 780, 0, :west
unit :captive, 786, 0, :west
unit :wizard, 791, 0, :west
unit :captive, 794, 0, :west
unit :archer, 798, 0, :west
unit :sludge, 799, 0, :west
unit :wizard, 801, 0, :west
unit :wizard, 803, 0, :west
unit :wizard, 806, 0, :west
unit :archer, 807, 0, :west
unit :captive, 809, 0, :west
unit :thick_sludge, 817, 0, :west
unit :thick_sludge, 819, 0, :west
unit :captive, 821, 0, :west
unit :thick_sludge, 823, 0, :west
unit :captive, 825, 0, :west
unit :captive, 829, 0, :west
unit :captive, 834, 0, :west
unit :wizard, 836, 0, :west
unit :archer, 838, 0, :west
unit :captive, 839, 0, :west
unit :captive, 843, 0, :west
unit :captive, 844, 0, :west
unit :sludge, 847, 0, :west
unit :archer, 849, 0, :west
unit :wizard, 856, 0, :west
unit :sludge, 860, 0, :west
unit :wizard, 862, 0, :west
unit :archer, 869, 0, :west
unit :thick_sludge, 871, 0, :west
unit :sludge, 872, 0, :west
unit :thick_sludge, 873, 0, :west
unit :wizard, 877, 0, :west
unit :sludge, 878, 0, :west
unit :captive, 886, 0, :west
unit :thick_sludge, 888, 0, :west
unit :thick_sludge, 890, 0, :west
unit :captive, 891, 0, :west
unit :captive, 893, 0, :west
unit :archer, 908, 0, :west
unit :wizard, 912, 0, :west
unit :archer, 921, 0, :west
unit :captive, 923, 0, :west
unit :archer, 924, 0, :west
unit :sludge, 926, 0, :west
unit :thick_sludge, 928, 0, :west
unit :archer, 933, 0, :west
unit :captive, 934, 0, :west
unit :thick_sludge, 942, 0, :west
unit :sludge, 944, 0, :west
unit :sludge, 951, 0, :west
unit :captive, 952, 0, :west
unit :captive, 955, 0, :west
unit :sludge, 957, 0, :west
unit :thick_sludge, 964, 0, :west
unit :archer, 966, 0, :west
unit :wizard, 968, 0, :west
unit :captive, 976, 0, :west
