#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C        a a      s    CS  S w  S  w      s   s     C  a      a    sC       CC      s       C     a             S w    sa          wC S      C   w    s      S        aCS   S C    w CS       w a swS    a S sS sC  s   w          C Csa   Ss s w    C   w a       S  CS s   s s   w Sw                   S      a  C         s    C  S C   C   a             a    s  S S S  w        Ssa      s  C     wC   sCs      @    S   S   a    a   S  a    sC   a   C                  w        s   s    a a  s C  a  CS   Cs  C    w     a  C  C      w  S     Ss  S a  S  sS       s  w      C  sC  w  s swSCs      S      aS     C C aSC   C a  CS     w    s               a  as  a       >    C  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 672
ace_score 3360
size 672, 1
stairs 664, 0

warrior 407, 0, :east

unit :captive, 1, 0, :east
unit :archer, 10, 0, :east
unit :archer, 12, 0, :east
unit :sludge, 19, 0, :east
unit :captive, 24, 0, :east
unit :thick_sludge, 25, 0, :east
unit :thick_sludge, 28, 0, :east
unit :wizard, 30, 0, :east
unit :thick_sludge, 33, 0, :east
unit :wizard, 36, 0, :east
unit :sludge, 43, 0, :east
unit :sludge, 47, 0, :east
unit :captive, 53, 0, :east
unit :archer, 56, 0, :east
unit :archer, 63, 0, :east
unit :sludge, 68, 0, :east
unit :captive, 69, 0, :east
unit :captive, 77, 0, :east
unit :captive, 78, 0, :east
unit :sludge, 85, 0, :east
unit :captive, 93, 0, :east
unit :archer, 99, 0, :east
unit :thick_sludge, 113, 0, :east
unit :wizard, 115, 0, :east
unit :sludge, 120, 0, :east
unit :archer, 121, 0, :east
unit :wizard, 132, 0, :east
unit :captive, 133, 0, :east
unit :thick_sludge, 135, 0, :east
unit :captive, 142, 0, :east
unit :wizard, 146, 0, :east
unit :sludge, 151, 0, :east
unit :thick_sludge, 158, 0, :east
unit :archer, 167, 0, :east
unit :captive, 168, 0, :east
unit :thick_sludge, 169, 0, :east
unit :thick_sludge, 173, 0, :east
unit :captive, 175, 0, :east
unit :wizard, 180, 0, :east
unit :captive, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :wizard, 191, 0, :east
unit :archer, 193, 0, :east
unit :sludge, 195, 0, :east
unit :wizard, 196, 0, :east
unit :thick_sludge, 197, 0, :east
unit :archer, 202, 0, :east
unit :thick_sludge, 204, 0, :east
unit :sludge, 206, 0, :east
unit :thick_sludge, 207, 0, :east
unit :sludge, 209, 0, :east
unit :captive, 210, 0, :east
unit :sludge, 213, 0, :east
unit :wizard, 217, 0, :east
unit :captive, 228, 0, :east
unit :captive, 230, 0, :east
unit :sludge, 231, 0, :east
unit :archer, 232, 0, :east
unit :thick_sludge, 236, 0, :east
unit :sludge, 237, 0, :east
unit :sludge, 239, 0, :east
unit :wizard, 241, 0, :east
unit :captive, 246, 0, :east
unit :wizard, 250, 0, :east
unit :archer, 252, 0, :east
unit :thick_sludge, 260, 0, :east
unit :captive, 263, 0, :east
unit :thick_sludge, 264, 0, :east
unit :sludge, 266, 0, :east
unit :sludge, 270, 0, :east
unit :sludge, 272, 0, :east
unit :wizard, 276, 0, :east
unit :thick_sludge, 278, 0, :east
unit :wizard, 279, 0, :east
unit :thick_sludge, 299, 0, :east
unit :archer, 306, 0, :east
unit :captive, 309, 0, :east
unit :sludge, 319, 0, :east
unit :captive, 324, 0, :east
unit :thick_sludge, 327, 0, :east
unit :captive, 329, 0, :east
unit :captive, 333, 0, :east
unit :archer, 337, 0, :east
unit :archer, 351, 0, :east
unit :sludge, 356, 0, :east
unit :thick_sludge, 359, 0, :east
unit :thick_sludge, 361, 0, :east
unit :thick_sludge, 363, 0, :east
unit :wizard, 366, 0, :east
unit :thick_sludge, 375, 0, :east
unit :sludge, 376, 0, :east
unit :archer, 377, 0, :east
unit :sludge, 384, 0, :east
unit :captive, 387, 0, :east
unit :wizard, 393, 0, :east
unit :captive, 394, 0, :east
unit :sludge, 398, 0, :east
unit :captive, 399, 0, :east
unit :sludge, 400, 0, :east
unit :thick_sludge, 412, 0, :west
unit :thick_sludge, 416, 0, :west
unit :archer, 420, 0, :west
unit :archer, 425, 0, :west
unit :thick_sludge, 429, 0, :west
unit :archer, 432, 0, :west
unit :sludge, 437, 0, :west
unit :captive, 438, 0, :west
unit :archer, 442, 0, :west
unit :captive, 446, 0, :west
unit :wizard, 465, 0, :west
unit :sludge, 474, 0, :west
unit :sludge, 478, 0, :west
unit :archer, 483, 0, :west
unit :archer, 485, 0, :west
unit :sludge, 488, 0, :west
unit :captive, 490, 0, :west
unit :archer, 493, 0, :west
unit :captive, 496, 0, :west
unit :thick_sludge, 497, 0, :west
unit :captive, 501, 0, :west
unit :sludge, 502, 0, :west
unit :captive, 505, 0, :west
unit :wizard, 510, 0, :west
unit :archer, 516, 0, :west
unit :captive, 519, 0, :west
unit :captive, 522, 0, :west
unit :wizard, 529, 0, :west
unit :thick_sludge, 532, 0, :west
unit :thick_sludge, 538, 0, :west
unit :sludge, 539, 0, :west
unit :thick_sludge, 542, 0, :west
unit :archer, 544, 0, :west
unit :thick_sludge, 547, 0, :west
unit :sludge, 550, 0, :west
unit :thick_sludge, 551, 0, :west
unit :sludge, 559, 0, :west
unit :wizard, 562, 0, :west
unit :captive, 569, 0, :west
unit :sludge, 572, 0, :west
unit :captive, 573, 0, :west
unit :wizard, 576, 0, :west
unit :sludge, 579, 0, :west
unit :sludge, 581, 0, :west
unit :wizard, 582, 0, :west
unit :thick_sludge, 583, 0, :west
unit :captive, 584, 0, :west
unit :sludge, 585, 0, :west
unit :thick_sludge, 592, 0, :west
unit :archer, 599, 0, :west
unit :thick_sludge, 600, 0, :west
unit :captive, 606, 0, :west
unit :captive, 608, 0, :west
unit :archer, 610, 0, :west
unit :thick_sludge, 611, 0, :west
unit :captive, 612, 0, :west
unit :captive, 616, 0, :west
unit :archer, 618, 0, :west
unit :captive, 621, 0, :west
unit :thick_sludge, 622, 0, :west
unit :wizard, 628, 0, :west
unit :sludge, 633, 0, :west
unit :archer, 649, 0, :west
unit :archer, 652, 0, :west
unit :sludge, 653, 0, :west
unit :archer, 656, 0, :west
unit :captive, 669, 0, :west
