#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  a       s        C     S SC  S w       s w ss    s     S  w   > a            S        a    aa         a w     w w a  C CC         aSa   s     S  a  w  sw w  C      S     s C  w sa    S  @         sS    w     Cs      S  Sw  w   C C   S    ss Sw  s C            Ss   S  w    S    w   sw C  aS     a  C C     as   s  C   w  s     SS            s a w  S     s  s s  S S C sCs     C  C   s  a    S   s        s C    w C   assS             S w      C   w   s              aS S  w         wa    S C   Ca w    CaC w  a   a     S            a SCw   C     Ss  s  s               s    s     s      C  a     a    s   C         |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 617
ace_score 3085
size 617, 1
stairs 64, 0

warrior 188, 0, :east

unit :archer, 2, 0, :east
unit :sludge, 10, 0, :east
unit :captive, 19, 0, :east
unit :thick_sludge, 25, 0, :east
unit :thick_sludge, 27, 0, :east
unit :captive, 28, 0, :east
unit :thick_sludge, 31, 0, :east
unit :wizard, 33, 0, :east
unit :sludge, 41, 0, :east
unit :wizard, 43, 0, :east
unit :sludge, 45, 0, :east
unit :sludge, 46, 0, :east
unit :sludge, 51, 0, :east
unit :thick_sludge, 57, 0, :east
unit :wizard, 60, 0, :east
unit :archer, 66, 0, :east
unit :thick_sludge, 79, 0, :east
unit :archer, 88, 0, :east
unit :archer, 93, 0, :east
unit :archer, 94, 0, :east
unit :archer, 104, 0, :east
unit :wizard, 106, 0, :east
unit :wizard, 112, 0, :east
unit :wizard, 114, 0, :east
unit :archer, 116, 0, :east
unit :captive, 119, 0, :east
unit :captive, 121, 0, :east
unit :captive, 122, 0, :east
unit :archer, 132, 0, :east
unit :thick_sludge, 133, 0, :east
unit :archer, 134, 0, :east
unit :sludge, 138, 0, :east
unit :thick_sludge, 144, 0, :east
unit :archer, 147, 0, :east
unit :wizard, 150, 0, :east
unit :sludge, 153, 0, :east
unit :wizard, 154, 0, :east
unit :wizard, 156, 0, :east
unit :captive, 159, 0, :east
unit :thick_sludge, 166, 0, :east
unit :sludge, 172, 0, :east
unit :captive, 174, 0, :east
unit :wizard, 177, 0, :east
unit :sludge, 179, 0, :east
unit :archer, 180, 0, :east
unit :thick_sludge, 185, 0, :east
unit :sludge, 198, 0, :west
unit :thick_sludge, 199, 0, :west
unit :wizard, 204, 0, :west
unit :captive, 210, 0, :west
unit :sludge, 211, 0, :west
unit :thick_sludge, 218, 0, :west
unit :thick_sludge, 221, 0, :west
unit :wizard, 222, 0, :west
unit :wizard, 225, 0, :west
unit :captive, 229, 0, :west
unit :captive, 231, 0, :west
unit :thick_sludge, 235, 0, :west
unit :sludge, 240, 0, :west
unit :sludge, 241, 0, :west
unit :thick_sludge, 243, 0, :west
unit :wizard, 244, 0, :west
unit :sludge, 247, 0, :west
unit :captive, 249, 0, :west
unit :thick_sludge, 262, 0, :west
unit :sludge, 263, 0, :west
unit :thick_sludge, 267, 0, :west
unit :wizard, 270, 0, :west
unit :thick_sludge, 275, 0, :west
unit :wizard, 280, 0, :west
unit :sludge, 284, 0, :west
unit :wizard, 285, 0, :west
unit :captive, 287, 0, :west
unit :archer, 290, 0, :west
unit :thick_sludge, 291, 0, :west
unit :archer, 297, 0, :west
unit :captive, 300, 0, :west
unit :captive, 302, 0, :west
unit :archer, 308, 0, :west
unit :sludge, 309, 0, :west
unit :sludge, 313, 0, :west
unit :captive, 316, 0, :west
unit :wizard, 320, 0, :west
unit :sludge, 323, 0, :west
unit :thick_sludge, 329, 0, :west
unit :thick_sludge, 330, 0, :west
unit :sludge, 343, 0, :west
unit :archer, 345, 0, :west
unit :wizard, 347, 0, :west
unit :thick_sludge, 350, 0, :west
unit :sludge, 356, 0, :west
unit :sludge, 359, 0, :west
unit :sludge, 361, 0, :west
unit :thick_sludge, 364, 0, :west
unit :thick_sludge, 366, 0, :west
unit :captive, 368, 0, :west
unit :sludge, 370, 0, :west
unit :captive, 371, 0, :west
unit :sludge, 372, 0, :west
unit :captive, 378, 0, :west
unit :captive, 381, 0, :west
unit :sludge, 385, 0, :west
unit :archer, 388, 0, :west
unit :thick_sludge, 393, 0, :west
unit :sludge, 397, 0, :west
unit :sludge, 406, 0, :west
unit :captive, 408, 0, :west
unit :wizard, 413, 0, :west
unit :captive, 415, 0, :west
unit :archer, 419, 0, :west
unit :sludge, 420, 0, :west
unit :sludge, 421, 0, :west
unit :thick_sludge, 422, 0, :west
unit :thick_sludge, 436, 0, :west
unit :wizard, 438, 0, :west
unit :captive, 445, 0, :west
unit :wizard, 449, 0, :west
unit :sludge, 453, 0, :west
unit :archer, 468, 0, :west
unit :thick_sludge, 469, 0, :west
unit :thick_sludge, 471, 0, :west
unit :wizard, 474, 0, :west
unit :wizard, 484, 0, :west
unit :archer, 485, 0, :west
unit :thick_sludge, 490, 0, :west
unit :captive, 492, 0, :west
unit :captive, 496, 0, :west
unit :archer, 497, 0, :west
unit :wizard, 499, 0, :west
unit :captive, 504, 0, :west
unit :archer, 505, 0, :west
unit :captive, 506, 0, :west
unit :wizard, 508, 0, :west
unit :archer, 511, 0, :west
unit :archer, 515, 0, :west
unit :thick_sludge, 521, 0, :west
unit :archer, 534, 0, :west
unit :thick_sludge, 536, 0, :west
unit :captive, 537, 0, :west
unit :wizard, 538, 0, :west
unit :captive, 542, 0, :west
unit :thick_sludge, 548, 0, :west
unit :sludge, 549, 0, :west
unit :sludge, 552, 0, :west
unit :sludge, 555, 0, :west
unit :sludge, 571, 0, :west
unit :sludge, 576, 0, :west
unit :sludge, 582, 0, :west
unit :captive, 589, 0, :west
unit :archer, 592, 0, :west
unit :archer, 598, 0, :west
unit :sludge, 603, 0, :west
unit :captive, 607, 0, :west
