#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w s   S  s    C    C a    SC     w       S  a   sC w  S  sC      C   C   a s  S  C S          aCw     Sw s C  s   ss     w          s   s      a       as     w   w     s   aa C  s           S aS S S   a  w   CSS a Ca  a    @  C     w   w  a       a a   C    w   ssC     a             w Ca   w S  w  a   C ss                >      C  a       w  s C  w wC    w Ca    w a        S      sa                 C     s     w               C   s  s    S         C    s     Ca     S S  a   a a   S          w     C a C  SSS S   sss       sa      CC S         CC    SS         a Sss   Ca    a   S    C  Cs C          s    w w s    aa         ss      s     w   s    s  S  C     a s      sa    ss     S C|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 690
ace_score 3450
size 690, 1
stairs 323, 0

warrior 223, 0, :east

unit :wizard, 0, 0, :east
unit :sludge, 2, 0, :east
unit :thick_sludge, 6, 0, :east
unit :sludge, 9, 0, :east
unit :captive, 14, 0, :east
unit :captive, 19, 0, :east
unit :archer, 21, 0, :east
unit :thick_sludge, 26, 0, :east
unit :captive, 27, 0, :east
unit :wizard, 33, 0, :east
unit :thick_sludge, 41, 0, :east
unit :archer, 44, 0, :east
unit :sludge, 48, 0, :east
unit :captive, 49, 0, :east
unit :wizard, 51, 0, :east
unit :thick_sludge, 54, 0, :east
unit :sludge, 57, 0, :east
unit :captive, 58, 0, :east
unit :captive, 65, 0, :east
unit :captive, 69, 0, :east
unit :archer, 73, 0, :east
unit :sludge, 75, 0, :east
unit :thick_sludge, 78, 0, :east
unit :captive, 81, 0, :east
unit :thick_sludge, 83, 0, :east
unit :archer, 94, 0, :east
unit :captive, 95, 0, :east
unit :wizard, 96, 0, :east
unit :thick_sludge, 102, 0, :east
unit :wizard, 103, 0, :east
unit :sludge, 105, 0, :east
unit :captive, 107, 0, :east
unit :sludge, 110, 0, :east
unit :sludge, 114, 0, :east
unit :sludge, 115, 0, :east
unit :wizard, 121, 0, :east
unit :sludge, 132, 0, :east
unit :sludge, 136, 0, :east
unit :archer, 143, 0, :east
unit :archer, 151, 0, :east
unit :sludge, 152, 0, :east
unit :wizard, 158, 0, :east
unit :wizard, 162, 0, :east
unit :sludge, 168, 0, :east
unit :archer, 172, 0, :east
unit :archer, 173, 0, :east
unit :captive, 175, 0, :east
unit :sludge, 178, 0, :east
unit :thick_sludge, 190, 0, :east
unit :archer, 192, 0, :east
unit :thick_sludge, 193, 0, :east
unit :thick_sludge, 195, 0, :east
unit :thick_sludge, 197, 0, :east
unit :archer, 201, 0, :east
unit :wizard, 204, 0, :east
unit :captive, 208, 0, :east
unit :thick_sludge, 209, 0, :east
unit :thick_sludge, 210, 0, :east
unit :archer, 212, 0, :east
unit :captive, 214, 0, :east
unit :archer, 215, 0, :east
unit :archer, 218, 0, :east
unit :captive, 226, 0, :west
unit :wizard, 232, 0, :west
unit :wizard, 236, 0, :west
unit :archer, 239, 0, :west
unit :archer, 247, 0, :west
unit :archer, 249, 0, :west
unit :captive, 253, 0, :west
unit :wizard, 258, 0, :west
unit :sludge, 262, 0, :west
unit :sludge, 263, 0, :west
unit :captive, 264, 0, :west
unit :archer, 270, 0, :west
unit :wizard, 284, 0, :west
unit :captive, 286, 0, :west
unit :archer, 287, 0, :west
unit :wizard, 291, 0, :west
unit :thick_sludge, 293, 0, :west
unit :wizard, 296, 0, :west
unit :archer, 299, 0, :west
unit :captive, 303, 0, :west
unit :sludge, 305, 0, :west
unit :sludge, 306, 0, :west
unit :captive, 330, 0, :west
unit :archer, 333, 0, :west
unit :wizard, 341, 0, :west
unit :sludge, 344, 0, :west
unit :captive, 346, 0, :west
unit :wizard, 349, 0, :west
unit :wizard, 351, 0, :west
unit :captive, 352, 0, :west
unit :wizard, 357, 0, :west
unit :captive, 359, 0, :west
unit :archer, 360, 0, :west
unit :wizard, 365, 0, :west
unit :archer, 367, 0, :west
unit :thick_sludge, 376, 0, :west
unit :sludge, 383, 0, :west
unit :archer, 384, 0, :west
unit :captive, 402, 0, :west
unit :sludge, 408, 0, :west
unit :wizard, 414, 0, :west
unit :captive, 430, 0, :west
unit :sludge, 434, 0, :west
unit :sludge, 437, 0, :west
unit :thick_sludge, 442, 0, :west
unit :captive, 452, 0, :west
unit :sludge, 457, 0, :west
unit :captive, 463, 0, :west
unit :archer, 464, 0, :west
unit :thick_sludge, 470, 0, :west
unit :thick_sludge, 472, 0, :west
unit :archer, 475, 0, :west
unit :archer, 479, 0, :west
unit :archer, 481, 0, :west
unit :thick_sludge, 485, 0, :west
unit :wizard, 496, 0, :west
unit :captive, 502, 0, :west
unit :archer, 504, 0, :west
unit :captive, 506, 0, :west
unit :thick_sludge, 509, 0, :west
unit :thick_sludge, 510, 0, :west
unit :thick_sludge, 511, 0, :west
unit :thick_sludge, 513, 0, :west
unit :sludge, 517, 0, :west
unit :sludge, 518, 0, :west
unit :sludge, 519, 0, :west
unit :sludge, 527, 0, :west
unit :archer, 528, 0, :west
unit :captive, 535, 0, :west
unit :captive, 536, 0, :west
unit :thick_sludge, 538, 0, :west
unit :captive, 548, 0, :west
unit :captive, 549, 0, :west
unit :thick_sludge, 554, 0, :west
unit :thick_sludge, 555, 0, :west
unit :archer, 565, 0, :west
unit :thick_sludge, 567, 0, :west
unit :sludge, 568, 0, :west
unit :sludge, 569, 0, :west
unit :captive, 573, 0, :west
unit :archer, 574, 0, :west
unit :archer, 579, 0, :west
unit :thick_sludge, 583, 0, :west
unit :captive, 588, 0, :west
unit :captive, 591, 0, :west
unit :sludge, 592, 0, :west
unit :captive, 594, 0, :west
unit :sludge, 605, 0, :west
unit :wizard, 610, 0, :west
unit :wizard, 612, 0, :west
unit :sludge, 614, 0, :west
unit :archer, 619, 0, :west
unit :archer, 620, 0, :west
unit :sludge, 630, 0, :west
unit :sludge, 631, 0, :west
unit :sludge, 638, 0, :west
unit :wizard, 644, 0, :west
unit :sludge, 648, 0, :west
unit :sludge, 653, 0, :west
unit :thick_sludge, 656, 0, :west
unit :captive, 659, 0, :west
unit :archer, 665, 0, :west
unit :sludge, 667, 0, :west
unit :sludge, 674, 0, :west
unit :archer, 675, 0, :west
unit :sludge, 680, 0, :west
unit :sludge, 681, 0, :west
unit :thick_sludge, 687, 0, :west
unit :captive, 689, 0, :west
