#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S  s a C w  SaS    sS  as         s  SC a S   a   s a  w     ws   S               sS        C  Sw  w s     Cs   C S          a      w  w               s C                  S  a C   w   SC     sC     s    C s w   C       a    sS        w a   CC      a    aC   C   a asw a  w    w  a        a      a s   C>  wSS a w   w    Sa  CC          S a    C      aSS   w Sa      S   s   S     S    wC  C         s    s  S a        Cs s C    a w     Ca  CC    a   s  CC     CS  S CCa       ws  w       a            C    @     a              w   w  s sa a  S    s as  a      a  S  aSs        SC  w    sS s              ws w s a  w  w    s a  a          wC    w  w             a s              s   aSa  S  C       a   s     s   S   S C    a w          S             w|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 752
ace_score 3760
size 752, 1
stairs 303, 0

warrior 507, 0, :east

unit :thick_sludge, 0, 0, :east
unit :sludge, 3, 0, :east
unit :archer, 5, 0, :east
unit :captive, 7, 0, :east
unit :wizard, 9, 0, :east
unit :thick_sludge, 12, 0, :east
unit :archer, 13, 0, :east
unit :thick_sludge, 14, 0, :east
unit :sludge, 19, 0, :east
unit :thick_sludge, 20, 0, :east
unit :archer, 23, 0, :east
unit :sludge, 24, 0, :east
unit :sludge, 34, 0, :east
unit :thick_sludge, 37, 0, :east
unit :captive, 38, 0, :east
unit :archer, 40, 0, :east
unit :thick_sludge, 42, 0, :east
unit :archer, 46, 0, :east
unit :sludge, 50, 0, :east
unit :archer, 52, 0, :east
unit :wizard, 55, 0, :east
unit :wizard, 61, 0, :east
unit :sludge, 62, 0, :east
unit :thick_sludge, 66, 0, :east
unit :sludge, 82, 0, :east
unit :thick_sludge, 83, 0, :east
unit :captive, 92, 0, :east
unit :thick_sludge, 95, 0, :east
unit :wizard, 96, 0, :east
unit :wizard, 99, 0, :east
unit :sludge, 101, 0, :east
unit :captive, 107, 0, :east
unit :sludge, 108, 0, :east
unit :captive, 112, 0, :east
unit :thick_sludge, 114, 0, :east
unit :archer, 125, 0, :east
unit :wizard, 132, 0, :east
unit :wizard, 135, 0, :east
unit :sludge, 151, 0, :east
unit :captive, 153, 0, :east
unit :thick_sludge, 172, 0, :east
unit :archer, 175, 0, :east
unit :captive, 177, 0, :east
unit :wizard, 181, 0, :east
unit :thick_sludge, 185, 0, :east
unit :captive, 186, 0, :east
unit :sludge, 192, 0, :east
unit :captive, 193, 0, :east
unit :sludge, 199, 0, :east
unit :captive, 204, 0, :east
unit :sludge, 206, 0, :east
unit :wizard, 208, 0, :east
unit :captive, 212, 0, :east
unit :archer, 220, 0, :east
unit :sludge, 225, 0, :east
unit :thick_sludge, 226, 0, :east
unit :wizard, 235, 0, :east
unit :archer, 237, 0, :east
unit :captive, 241, 0, :east
unit :captive, 242, 0, :east
unit :archer, 249, 0, :east
unit :archer, 254, 0, :east
unit :captive, 255, 0, :east
unit :captive, 259, 0, :east
unit :archer, 263, 0, :east
unit :archer, 265, 0, :east
unit :sludge, 266, 0, :east
unit :wizard, 267, 0, :east
unit :archer, 269, 0, :east
unit :wizard, 272, 0, :east
unit :wizard, 277, 0, :east
unit :archer, 280, 0, :east
unit :archer, 289, 0, :east
unit :archer, 296, 0, :east
unit :sludge, 298, 0, :east
unit :captive, 302, 0, :east
unit :wizard, 306, 0, :east
unit :thick_sludge, 307, 0, :east
unit :thick_sludge, 308, 0, :east
unit :archer, 310, 0, :east
unit :wizard, 312, 0, :east
unit :wizard, 316, 0, :east
unit :thick_sludge, 321, 0, :east
unit :archer, 322, 0, :east
unit :captive, 325, 0, :east
unit :captive, 326, 0, :east
unit :thick_sludge, 337, 0, :east
unit :archer, 339, 0, :east
unit :captive, 344, 0, :east
unit :archer, 351, 0, :east
unit :thick_sludge, 352, 0, :east
unit :thick_sludge, 353, 0, :east
unit :wizard, 357, 0, :east
unit :thick_sludge, 359, 0, :east
unit :archer, 360, 0, :east
unit :thick_sludge, 367, 0, :east
unit :sludge, 371, 0, :east
unit :thick_sludge, 375, 0, :east
unit :thick_sludge, 381, 0, :east
unit :wizard, 386, 0, :east
unit :captive, 387, 0, :east
unit :captive, 390, 0, :east
unit :sludge, 400, 0, :east
unit :sludge, 405, 0, :east
unit :thick_sludge, 408, 0, :east
unit :archer, 410, 0, :east
unit :captive, 419, 0, :east
unit :sludge, 420, 0, :east
unit :sludge, 422, 0, :east
unit :captive, 424, 0, :east
unit :archer, 429, 0, :east
unit :wizard, 431, 0, :east
unit :captive, 437, 0, :east
unit :archer, 438, 0, :east
unit :captive, 441, 0, :east
unit :captive, 442, 0, :east
unit :archer, 447, 0, :east
unit :sludge, 451, 0, :east
unit :captive, 454, 0, :east
unit :captive, 455, 0, :east
unit :captive, 461, 0, :east
unit :thick_sludge, 462, 0, :east
unit :thick_sludge, 465, 0, :east
unit :captive, 467, 0, :east
unit :captive, 468, 0, :east
unit :archer, 469, 0, :east
unit :wizard, 477, 0, :east
unit :sludge, 478, 0, :east
unit :wizard, 481, 0, :east
unit :archer, 489, 0, :east
unit :captive, 502, 0, :east
unit :archer, 513, 0, :west
unit :wizard, 528, 0, :west
unit :wizard, 532, 0, :west
unit :sludge, 535, 0, :west
unit :sludge, 537, 0, :west
unit :archer, 538, 0, :west
unit :archer, 540, 0, :west
unit :thick_sludge, 543, 0, :west
unit :sludge, 548, 0, :west
unit :archer, 550, 0, :west
unit :sludge, 551, 0, :west
unit :archer, 554, 0, :west
unit :archer, 561, 0, :west
unit :thick_sludge, 564, 0, :west
unit :archer, 567, 0, :west
unit :thick_sludge, 568, 0, :west
unit :sludge, 569, 0, :west
unit :thick_sludge, 578, 0, :west
unit :captive, 579, 0, :west
unit :wizard, 582, 0, :west
unit :sludge, 587, 0, :west
unit :thick_sludge, 588, 0, :west
unit :sludge, 590, 0, :west
unit :wizard, 605, 0, :west
unit :sludge, 606, 0, :west
unit :wizard, 608, 0, :west
unit :sludge, 610, 0, :west
unit :archer, 612, 0, :west
unit :wizard, 615, 0, :west
unit :wizard, 618, 0, :west
unit :sludge, 623, 0, :west
unit :archer, 625, 0, :west
unit :archer, 628, 0, :west
unit :wizard, 639, 0, :west
unit :captive, 640, 0, :west
unit :wizard, 645, 0, :west
unit :wizard, 648, 0, :west
unit :archer, 662, 0, :west
unit :sludge, 664, 0, :west
unit :sludge, 679, 0, :west
unit :archer, 683, 0, :west
unit :thick_sludge, 684, 0, :west
unit :archer, 685, 0, :west
unit :thick_sludge, 688, 0, :west
unit :captive, 691, 0, :west
unit :archer, 699, 0, :west
unit :sludge, 703, 0, :west
unit :sludge, 709, 0, :west
unit :thick_sludge, 713, 0, :west
unit :thick_sludge, 717, 0, :west
unit :captive, 719, 0, :west
unit :archer, 724, 0, :west
unit :wizard, 726, 0, :west
unit :thick_sludge, 737, 0, :west
unit :wizard, 751, 0, :west
