#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     S       C   ws a  a   S      CsC  S  a S w    s   SSS ss   s     a   SS wC s  CCa sSSSw sS   S  a                  sC          S S  CaC   a          s   a  a C        ss   w   s          a  s         a     C      s        w  a   C        s               s w        S  C   s w s w    S w     a     s     C w  SS CSa  @   w  a S      a S        wC sCS  C     S  a  SS    w      C         C      S       C  a aC               w           w      ss  sa       SSs      sS   a     s ssw  a a w        s       aaa C> S              S  C   C  sw    S S   a   w        S   s   s   S        S|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 587
ace_score 2935
size 587, 1
stairs 513, 0

warrior 321, 0, :east

unit :thick_sludge, 5, 0, :east
unit :captive, 13, 0, :east
unit :wizard, 17, 0, :east
unit :sludge, 18, 0, :east
unit :archer, 20, 0, :east
unit :archer, 23, 0, :east
unit :thick_sludge, 27, 0, :east
unit :captive, 34, 0, :east
unit :sludge, 35, 0, :east
unit :captive, 36, 0, :east
unit :thick_sludge, 39, 0, :east
unit :archer, 42, 0, :east
unit :thick_sludge, 44, 0, :east
unit :wizard, 46, 0, :east
unit :sludge, 51, 0, :east
unit :thick_sludge, 55, 0, :east
unit :thick_sludge, 56, 0, :east
unit :thick_sludge, 57, 0, :east
unit :sludge, 59, 0, :east
unit :sludge, 60, 0, :east
unit :sludge, 64, 0, :east
unit :archer, 70, 0, :east
unit :thick_sludge, 74, 0, :east
unit :thick_sludge, 75, 0, :east
unit :wizard, 77, 0, :east
unit :captive, 78, 0, :east
unit :sludge, 80, 0, :east
unit :captive, 83, 0, :east
unit :captive, 84, 0, :east
unit :archer, 85, 0, :east
unit :sludge, 87, 0, :east
unit :thick_sludge, 88, 0, :east
unit :thick_sludge, 89, 0, :east
unit :thick_sludge, 90, 0, :east
unit :wizard, 91, 0, :east
unit :sludge, 93, 0, :east
unit :thick_sludge, 94, 0, :east
unit :thick_sludge, 98, 0, :east
unit :archer, 101, 0, :east
unit :sludge, 120, 0, :east
unit :captive, 121, 0, :east
unit :thick_sludge, 132, 0, :east
unit :thick_sludge, 134, 0, :east
unit :captive, 137, 0, :east
unit :archer, 138, 0, :east
unit :captive, 139, 0, :east
unit :archer, 143, 0, :east
unit :sludge, 154, 0, :east
unit :archer, 158, 0, :east
unit :archer, 161, 0, :east
unit :captive, 163, 0, :east
unit :sludge, 172, 0, :east
unit :sludge, 173, 0, :east
unit :wizard, 177, 0, :east
unit :sludge, 181, 0, :east
unit :archer, 192, 0, :east
unit :sludge, 195, 0, :east
unit :archer, 205, 0, :east
unit :captive, 211, 0, :east
unit :sludge, 218, 0, :east
unit :wizard, 227, 0, :east
unit :archer, 230, 0, :east
unit :captive, 234, 0, :east
unit :sludge, 243, 0, :east
unit :sludge, 259, 0, :east
unit :wizard, 261, 0, :east
unit :thick_sludge, 270, 0, :east
unit :captive, 273, 0, :east
unit :sludge, 277, 0, :east
unit :wizard, 279, 0, :east
unit :sludge, 281, 0, :east
unit :wizard, 283, 0, :east
unit :thick_sludge, 288, 0, :east
unit :wizard, 290, 0, :east
unit :archer, 296, 0, :east
unit :sludge, 302, 0, :east
unit :captive, 308, 0, :east
unit :wizard, 310, 0, :east
unit :thick_sludge, 313, 0, :east
unit :thick_sludge, 314, 0, :east
unit :captive, 316, 0, :east
unit :thick_sludge, 317, 0, :east
unit :archer, 318, 0, :east
unit :wizard, 325, 0, :west
unit :archer, 328, 0, :west
unit :thick_sludge, 330, 0, :west
unit :archer, 337, 0, :west
unit :thick_sludge, 339, 0, :west
unit :wizard, 348, 0, :west
unit :captive, 349, 0, :west
unit :sludge, 351, 0, :west
unit :captive, 352, 0, :west
unit :thick_sludge, 353, 0, :west
unit :captive, 356, 0, :west
unit :thick_sludge, 362, 0, :west
unit :archer, 365, 0, :west
unit :thick_sludge, 368, 0, :west
unit :thick_sludge, 369, 0, :west
unit :wizard, 374, 0, :west
unit :captive, 381, 0, :west
unit :captive, 391, 0, :west
unit :thick_sludge, 398, 0, :west
unit :captive, 406, 0, :west
unit :archer, 409, 0, :west
unit :archer, 411, 0, :west
unit :captive, 412, 0, :west
unit :wizard, 428, 0, :west
unit :wizard, 440, 0, :west
unit :sludge, 447, 0, :west
unit :sludge, 448, 0, :west
unit :sludge, 451, 0, :west
unit :archer, 452, 0, :west
unit :thick_sludge, 460, 0, :west
unit :thick_sludge, 461, 0, :west
unit :sludge, 462, 0, :west
unit :sludge, 469, 0, :west
unit :thick_sludge, 470, 0, :west
unit :archer, 474, 0, :west
unit :sludge, 480, 0, :west
unit :sludge, 482, 0, :west
unit :sludge, 483, 0, :west
unit :wizard, 484, 0, :west
unit :archer, 487, 0, :west
unit :archer, 489, 0, :west
unit :wizard, 491, 0, :west
unit :sludge, 500, 0, :west
unit :archer, 508, 0, :west
unit :archer, 509, 0, :west
unit :archer, 510, 0, :west
unit :captive, 512, 0, :west
unit :thick_sludge, 515, 0, :west
unit :thick_sludge, 530, 0, :west
unit :captive, 533, 0, :west
unit :captive, 537, 0, :west
unit :sludge, 540, 0, :west
unit :wizard, 541, 0, :west
unit :thick_sludge, 546, 0, :west
unit :thick_sludge, 548, 0, :west
unit :archer, 552, 0, :west
unit :wizard, 556, 0, :west
unit :thick_sludge, 565, 0, :west
unit :sludge, 569, 0, :west
unit :sludge, 573, 0, :west
unit :thick_sludge, 577, 0, :west
unit :thick_sludge, 586, 0, :west
