#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C         s    a   CSw        Ca      S    w   Ssa  a a       w w       S  w   awS a  aw   sS  S S           S   a   C   ws    s     C C   S   a   C   a   CC a    sC             a w    S s  S C    a  w  w w    C  s  C a   w S  C  s   w CS  w        a Cw           a C       s w  s  wa  a S a  s     sa a Sa  C s         w a      C    ss   S Cw               S   S a s   wS     a C  SS      aa      a w  s     S            S  s   S S     S    CC         C          sCC       C       C S SwS    Cs sw  C w  C C   C s      C  ws   S  aa S      S  a        a  s          w   a C          w       CS          s             a             S    w    w        C   sa   S     s   a   S a   S     Sa C   ss s     C      a    w   S as   s w  C    s    as        a     w      s   S  S  ws    s     C           S     a     sS        a   a    a     s  a    w  a sS w   w w    a   >w   w SCsa     @     aw C a   w         w    C  s   w          C   s C  |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 938
ace_score 4690
size 938, 1
stairs 865, 0

warrior 881, 0, :east

unit :captive, 0, 0, :east
unit :sludge, 10, 0, :east
unit :archer, 15, 0, :east
unit :captive, 19, 0, :east
unit :thick_sludge, 20, 0, :east
unit :wizard, 21, 0, :east
unit :captive, 30, 0, :east
unit :archer, 31, 0, :east
unit :thick_sludge, 38, 0, :east
unit :wizard, 43, 0, :east
unit :thick_sludge, 47, 0, :east
unit :sludge, 48, 0, :east
unit :archer, 49, 0, :east
unit :archer, 52, 0, :east
unit :archer, 54, 0, :east
unit :wizard, 62, 0, :east
unit :wizard, 64, 0, :east
unit :thick_sludge, 72, 0, :east
unit :wizard, 75, 0, :east
unit :archer, 79, 0, :east
unit :wizard, 80, 0, :east
unit :thick_sludge, 81, 0, :east
unit :archer, 83, 0, :east
unit :archer, 86, 0, :east
unit :wizard, 87, 0, :east
unit :sludge, 91, 0, :east
unit :thick_sludge, 92, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 97, 0, :east
unit :thick_sludge, 109, 0, :east
unit :archer, 113, 0, :east
unit :captive, 117, 0, :east
unit :wizard, 121, 0, :east
unit :sludge, 122, 0, :east
unit :sludge, 127, 0, :east
unit :captive, 133, 0, :east
unit :captive, 135, 0, :east
unit :thick_sludge, 139, 0, :east
unit :archer, 143, 0, :east
unit :captive, 147, 0, :east
unit :archer, 151, 0, :east
unit :captive, 155, 0, :east
unit :captive, 156, 0, :east
unit :archer, 158, 0, :east
unit :sludge, 163, 0, :east
unit :captive, 164, 0, :east
unit :archer, 178, 0, :east
unit :wizard, 180, 0, :east
unit :thick_sludge, 185, 0, :east
unit :sludge, 187, 0, :east
unit :thick_sludge, 190, 0, :east
unit :captive, 192, 0, :east
unit :archer, 197, 0, :east
unit :wizard, 200, 0, :east
unit :wizard, 203, 0, :east
unit :wizard, 205, 0, :east
unit :captive, 210, 0, :east
unit :sludge, 213, 0, :east
unit :captive, 216, 0, :east
unit :archer, 218, 0, :east
unit :wizard, 222, 0, :east
unit :thick_sludge, 224, 0, :east
unit :captive, 227, 0, :east
unit :sludge, 230, 0, :east
unit :wizard, 234, 0, :east
unit :captive, 236, 0, :east
unit :thick_sludge, 237, 0, :east
unit :wizard, 240, 0, :east
unit :archer, 249, 0, :east
unit :captive, 251, 0, :east
unit :wizard, 252, 0, :east
unit :archer, 264, 0, :east
unit :captive, 266, 0, :east
unit :sludge, 274, 0, :east
unit :wizard, 276, 0, :east
unit :sludge, 279, 0, :east
unit :wizard, 282, 0, :east
unit :archer, 283, 0, :east
unit :archer, 286, 0, :east
unit :thick_sludge, 288, 0, :east
unit :archer, 290, 0, :east
unit :sludge, 293, 0, :east
unit :sludge, 299, 0, :east
unit :archer, 300, 0, :east
unit :archer, 302, 0, :east
unit :thick_sludge, 304, 0, :east
unit :archer, 305, 0, :east
unit :captive, 308, 0, :east
unit :sludge, 310, 0, :east
unit :wizard, 320, 0, :east
unit :archer, 322, 0, :east
unit :captive, 329, 0, :east
unit :sludge, 334, 0, :east
unit :sludge, 335, 0, :east
unit :thick_sludge, 339, 0, :east
unit :captive, 341, 0, :east
unit :wizard, 342, 0, :east
unit :thick_sludge, 358, 0, :east
unit :thick_sludge, 362, 0, :east
unit :archer, 364, 0, :east
unit :sludge, 366, 0, :east
unit :wizard, 370, 0, :east
unit :thick_sludge, 371, 0, :east
unit :archer, 377, 0, :east
unit :captive, 379, 0, :east
unit :thick_sludge, 382, 0, :east
unit :thick_sludge, 383, 0, :east
unit :archer, 390, 0, :east
unit :archer, 391, 0, :east
unit :archer, 398, 0, :east
unit :wizard, 400, 0, :east
unit :sludge, 403, 0, :east
unit :thick_sludge, 409, 0, :east
unit :thick_sludge, 422, 0, :east
unit :sludge, 425, 0, :east
unit :thick_sludge, 429, 0, :east
unit :thick_sludge, 431, 0, :east
unit :thick_sludge, 437, 0, :east
unit :captive, 442, 0, :east
unit :captive, 443, 0, :east
unit :captive, 453, 0, :east
unit :sludge, 464, 0, :east
unit :captive, 465, 0, :east
unit :captive, 466, 0, :east
unit :captive, 474, 0, :east
unit :captive, 482, 0, :east
unit :thick_sludge, 484, 0, :east
unit :thick_sludge, 486, 0, :east
unit :wizard, 487, 0, :east
unit :thick_sludge, 488, 0, :east
unit :captive, 493, 0, :east
unit :sludge, 494, 0, :east
unit :sludge, 496, 0, :east
unit :wizard, 497, 0, :east
unit :captive, 500, 0, :east
unit :wizard, 502, 0, :east
unit :captive, 505, 0, :east
unit :captive, 507, 0, :east
unit :captive, 511, 0, :east
unit :sludge, 513, 0, :east
unit :captive, 520, 0, :east
unit :wizard, 523, 0, :east
unit :sludge, 524, 0, :east
unit :thick_sludge, 528, 0, :east
unit :archer, 531, 0, :east
unit :archer, 532, 0, :east
unit :thick_sludge, 534, 0, :east
unit :thick_sludge, 541, 0, :east
unit :archer, 544, 0, :east
unit :archer, 553, 0, :east
unit :sludge, 556, 0, :east
unit :wizard, 567, 0, :east
unit :archer, 571, 0, :east
unit :captive, 573, 0, :east
unit :wizard, 584, 0, :east
unit :captive, 592, 0, :east
unit :thick_sludge, 593, 0, :east
unit :sludge, 604, 0, :east
unit :archer, 618, 0, :east
unit :thick_sludge, 632, 0, :east
unit :wizard, 637, 0, :east
unit :wizard, 642, 0, :east
unit :captive, 651, 0, :east
unit :sludge, 655, 0, :east
unit :archer, 656, 0, :east
unit :thick_sludge, 660, 0, :east
unit :sludge, 666, 0, :east
unit :archer, 670, 0, :east
unit :thick_sludge, 674, 0, :east
unit :archer, 676, 0, :east
unit :thick_sludge, 680, 0, :east
unit :thick_sludge, 686, 0, :east
unit :archer, 687, 0, :east
unit :captive, 689, 0, :east
unit :sludge, 693, 0, :east
unit :sludge, 694, 0, :east
unit :sludge, 696, 0, :east
unit :captive, 702, 0, :east
unit :archer, 709, 0, :east
unit :wizard, 714, 0, :east
unit :thick_sludge, 718, 0, :east
unit :archer, 720, 0, :east
unit :sludge, 721, 0, :east
unit :sludge, 725, 0, :east
unit :wizard, 727, 0, :east
unit :captive, 730, 0, :east
unit :sludge, 735, 0, :east
unit :archer, 740, 0, :east
unit :sludge, 741, 0, :east
unit :archer, 750, 0, :east
unit :wizard, 756, 0, :east
unit :sludge, 763, 0, :east
unit :thick_sludge, 767, 0, :east
unit :thick_sludge, 770, 0, :east
unit :wizard, 773, 0, :east
unit :sludge, 774, 0, :east
unit :sludge, 779, 0, :east
unit :captive, 785, 0, :east
unit :thick_sludge, 797, 0, :east
unit :archer, 803, 0, :east
unit :sludge, 809, 0, :east
unit :thick_sludge, 810, 0, :east
unit :archer, 819, 0, :east
unit :archer, 823, 0, :east
unit :archer, 828, 0, :east
unit :sludge, 834, 0, :east
unit :archer, 837, 0, :east
unit :wizard, 842, 0, :east
unit :archer, 845, 0, :east
unit :sludge, 847, 0, :east
unit :thick_sludge, 848, 0, :east
unit :wizard, 850, 0, :east
unit :wizard, 854, 0, :east
unit :wizard, 856, 0, :east
unit :archer, 861, 0, :east
unit :wizard, 866, 0, :east
unit :wizard, 870, 0, :east
unit :thick_sludge, 872, 0, :east
unit :captive, 873, 0, :east
unit :sludge, 874, 0, :east
unit :archer, 875, 0, :east
unit :archer, 887, 0, :west
unit :wizard, 888, 0, :west
unit :captive, 890, 0, :west
unit :archer, 892, 0, :west
unit :wizard, 896, 0, :west
unit :wizard, 906, 0, :west
unit :captive, 911, 0, :west
unit :sludge, 914, 0, :west
unit :wizard, 918, 0, :west
unit :captive, 929, 0, :west
unit :sludge, 933, 0, :west
unit :captive, 935, 0, :west
