#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S a C    s  C s  w   wCa w   s      s C   w  a  sw      C  a  w     SSw   w w S    Cs  s     s      a       s    aa   sw      s    a s    S       w      S   SC   S Ss     w    aa    s  w   S CS  wa CC       S    Ss   a s  Sw CC    S    S   Csw   a             s S S    C w  w    >  S C                      C  S   a S  a  C  S C  Cs C      w    C        s      @     CC    s   s a w   a C       s      S           a    s      S          C  w S     a         a C  ss  s     w S   s        s sC Ss Ss  w          s   a s S    s      sC     C C      a s  w S  w w    ws      C  ss      C S      sS           w  w S  S  s   a  w  w    a  s    CS  a   C    aS Cw   SSs       a SS C S         w   S   CS   s S s s     a   w   s                s       C     S     s   S              w  aw      a w   aS      Cs             w    w           a     s  C   s C    S  C S         |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 868
ace_score 4340
size 868, 1
stairs 279, 0

warrior 361, 0, :east

unit :thick_sludge, 0, 0, :east
unit :archer, 2, 0, :east
unit :captive, 4, 0, :east
unit :sludge, 9, 0, :east
unit :captive, 12, 0, :east
unit :sludge, 14, 0, :east
unit :wizard, 17, 0, :east
unit :wizard, 21, 0, :east
unit :captive, 22, 0, :east
unit :archer, 23, 0, :east
unit :wizard, 25, 0, :east
unit :sludge, 29, 0, :east
unit :sludge, 36, 0, :east
unit :captive, 38, 0, :east
unit :wizard, 42, 0, :east
unit :archer, 45, 0, :east
unit :sludge, 48, 0, :east
unit :wizard, 49, 0, :east
unit :captive, 56, 0, :east
unit :archer, 59, 0, :east
unit :wizard, 62, 0, :east
unit :thick_sludge, 68, 0, :east
unit :thick_sludge, 69, 0, :east
unit :wizard, 70, 0, :east
unit :wizard, 74, 0, :east
unit :wizard, 76, 0, :east
unit :thick_sludge, 78, 0, :east
unit :captive, 83, 0, :east
unit :sludge, 84, 0, :east
unit :sludge, 87, 0, :east
unit :sludge, 93, 0, :east
unit :archer, 100, 0, :east
unit :sludge, 108, 0, :east
unit :archer, 113, 0, :east
unit :archer, 114, 0, :east
unit :sludge, 118, 0, :east
unit :wizard, 119, 0, :east
unit :sludge, 126, 0, :east
unit :archer, 131, 0, :east
unit :sludge, 133, 0, :east
unit :thick_sludge, 138, 0, :east
unit :wizard, 146, 0, :east
unit :thick_sludge, 153, 0, :east
unit :thick_sludge, 157, 0, :east
unit :captive, 158, 0, :east
unit :thick_sludge, 162, 0, :east
unit :thick_sludge, 164, 0, :east
unit :sludge, 165, 0, :east
unit :wizard, 171, 0, :east
unit :archer, 176, 0, :east
unit :archer, 177, 0, :east
unit :sludge, 182, 0, :east
unit :wizard, 185, 0, :east
unit :thick_sludge, 189, 0, :east
unit :captive, 191, 0, :east
unit :thick_sludge, 192, 0, :east
unit :wizard, 195, 0, :east
unit :archer, 196, 0, :east
unit :captive, 198, 0, :east
unit :captive, 199, 0, :east
unit :thick_sludge, 207, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 213, 0, :east
unit :archer, 217, 0, :east
unit :sludge, 219, 0, :east
unit :thick_sludge, 222, 0, :east
unit :wizard, 223, 0, :east
unit :captive, 225, 0, :east
unit :captive, 226, 0, :east
unit :thick_sludge, 231, 0, :east
unit :thick_sludge, 236, 0, :east
unit :captive, 240, 0, :east
unit :sludge, 241, 0, :east
unit :wizard, 242, 0, :east
unit :archer, 246, 0, :east
unit :sludge, 260, 0, :east
unit :thick_sludge, 262, 0, :east
unit :thick_sludge, 264, 0, :east
unit :captive, 269, 0, :east
unit :wizard, 271, 0, :east
unit :wizard, 274, 0, :east
unit :thick_sludge, 282, 0, :east
unit :captive, 284, 0, :east
unit :captive, 307, 0, :east
unit :thick_sludge, 310, 0, :east
unit :archer, 314, 0, :east
unit :thick_sludge, 316, 0, :east
unit :archer, 319, 0, :east
unit :captive, 322, 0, :east
unit :thick_sludge, 325, 0, :east
unit :captive, 327, 0, :east
unit :captive, 330, 0, :east
unit :sludge, 331, 0, :east
unit :captive, 333, 0, :east
unit :wizard, 340, 0, :east
unit :captive, 345, 0, :east
unit :sludge, 354, 0, :east
unit :captive, 367, 0, :west
unit :captive, 368, 0, :west
unit :sludge, 373, 0, :west
unit :sludge, 377, 0, :west
unit :archer, 379, 0, :west
unit :wizard, 381, 0, :west
unit :archer, 385, 0, :west
unit :captive, 387, 0, :west
unit :sludge, 395, 0, :west
unit :thick_sludge, 402, 0, :west
unit :archer, 414, 0, :west
unit :sludge, 419, 0, :west
unit :thick_sludge, 426, 0, :west
unit :captive, 437, 0, :west
unit :wizard, 440, 0, :west
unit :thick_sludge, 442, 0, :west
unit :archer, 448, 0, :west
unit :archer, 458, 0, :west
unit :captive, 460, 0, :west
unit :sludge, 463, 0, :west
unit :sludge, 464, 0, :west
unit :sludge, 467, 0, :west
unit :wizard, 473, 0, :west
unit :thick_sludge, 475, 0, :west
unit :sludge, 479, 0, :west
unit :sludge, 488, 0, :west
unit :sludge, 490, 0, :west
unit :captive, 491, 0, :west
unit :thick_sludge, 493, 0, :west
unit :sludge, 494, 0, :west
unit :thick_sludge, 496, 0, :west
unit :sludge, 497, 0, :west
unit :wizard, 500, 0, :west
unit :sludge, 511, 0, :west
unit :archer, 515, 0, :west
unit :sludge, 517, 0, :west
unit :thick_sludge, 519, 0, :west
unit :sludge, 524, 0, :west
unit :sludge, 531, 0, :west
unit :captive, 532, 0, :west
unit :captive, 538, 0, :west
unit :captive, 540, 0, :west
unit :archer, 547, 0, :west
unit :sludge, 549, 0, :west
unit :wizard, 552, 0, :west
unit :thick_sludge, 554, 0, :west
unit :wizard, 557, 0, :west
unit :wizard, 559, 0, :west
unit :wizard, 564, 0, :west
unit :sludge, 565, 0, :west
unit :captive, 572, 0, :west
unit :sludge, 575, 0, :west
unit :sludge, 576, 0, :west
unit :captive, 583, 0, :west
unit :thick_sludge, 585, 0, :west
unit :sludge, 592, 0, :west
unit :thick_sludge, 593, 0, :west
unit :wizard, 605, 0, :west
unit :wizard, 608, 0, :west
unit :thick_sludge, 610, 0, :west
unit :thick_sludge, 613, 0, :west
unit :sludge, 616, 0, :west
unit :archer, 620, 0, :west
unit :wizard, 623, 0, :west
unit :wizard, 626, 0, :west
unit :archer, 631, 0, :west
unit :sludge, 634, 0, :west
unit :captive, 639, 0, :west
unit :thick_sludge, 640, 0, :west
unit :archer, 643, 0, :west
unit :captive, 647, 0, :west
unit :archer, 652, 0, :west
unit :thick_sludge, 653, 0, :west
unit :captive, 655, 0, :west
unit :wizard, 656, 0, :west
unit :thick_sludge, 660, 0, :west
unit :thick_sludge, 661, 0, :west
unit :sludge, 662, 0, :west
unit :archer, 670, 0, :west
unit :thick_sludge, 672, 0, :west
unit :thick_sludge, 673, 0, :west
unit :captive, 675, 0, :west
unit :thick_sludge, 677, 0, :west
unit :wizard, 687, 0, :west
unit :thick_sludge, 691, 0, :west
unit :captive, 695, 0, :west
unit :thick_sludge, 696, 0, :west
unit :sludge, 700, 0, :west
unit :thick_sludge, 702, 0, :west
unit :sludge, 704, 0, :west
unit :sludge, 706, 0, :west
unit :archer, 712, 0, :west
unit :wizard, 716, 0, :west
unit :sludge, 720, 0, :west
unit :sludge, 737, 0, :west
unit :captive, 745, 0, :west
unit :thick_sludge, 751, 0, :west
unit :sludge, 757, 0, :west
unit :thick_sludge, 761, 0, :west
unit :wizard, 776, 0, :west
unit :archer, 779, 0, :west
unit :wizard, 780, 0, :west
unit :archer, 787, 0, :west
unit :wizard, 789, 0, :west
unit :archer, 793, 0, :west
unit :thick_sludge, 794, 0, :west
unit :captive, 801, 0, :west
unit :sludge, 802, 0, :west
unit :wizard, 816, 0, :west
unit :wizard, 821, 0, :west
unit :archer, 833, 0, :west
unit :sludge, 839, 0, :west
unit :captive, 842, 0, :west
unit :sludge, 846, 0, :west
unit :captive, 848, 0, :west
unit :thick_sludge, 853, 0, :west
unit :captive, 856, 0, :west
unit :thick_sludge, 858, 0, :west
