#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | w         S    s  w     S       wS   C a    C                 w  ss  w   Cs        C    w   S    w w  w C      Ca Ss     s       C  w        s    sa C S Ss   SC  @  s   a s  a  s  s  C      SC s        C  wS  w   aS        S                   S    s   s      a          s as a C      wa       SC SSS          s      S          C      s  C w        s   w       a         w   w a a s aC    s    SC      CC            ss   C    s   >      ss   aS        a s    sC    a      Ca s       a    s sS                   Ss s         S    S  sSS w  S  S a S sSS      a C S a C S  w sS       ss    S   s  aS   w  C w   wS  a      s               S S S a   aS C    aw  a w    sSa s Ca      C C  Ss           s S        C  CC   s      CaS  s Swa             w           S C  s  a sa     S    S Sa     w    |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 793
ace_score 3965
size 793, 1
stairs 430, 0

warrior 163, 0, :east

unit :wizard, 1, 0, :east
unit :thick_sludge, 11, 0, :east
unit :sludge, 16, 0, :east
unit :wizard, 19, 0, :east
unit :thick_sludge, 25, 0, :east
unit :wizard, 33, 0, :east
unit :thick_sludge, 34, 0, :east
unit :captive, 38, 0, :east
unit :archer, 40, 0, :east
unit :captive, 45, 0, :east
unit :wizard, 63, 0, :east
unit :sludge, 66, 0, :east
unit :sludge, 67, 0, :east
unit :wizard, 70, 0, :east
unit :captive, 74, 0, :east
unit :sludge, 75, 0, :east
unit :captive, 84, 0, :east
unit :wizard, 89, 0, :east
unit :thick_sludge, 93, 0, :east
unit :wizard, 98, 0, :east
unit :wizard, 100, 0, :east
unit :wizard, 103, 0, :east
unit :captive, 105, 0, :east
unit :captive, 112, 0, :east
unit :archer, 113, 0, :east
unit :thick_sludge, 115, 0, :east
unit :sludge, 116, 0, :east
unit :sludge, 122, 0, :east
unit :captive, 130, 0, :east
unit :wizard, 133, 0, :east
unit :sludge, 142, 0, :east
unit :sludge, 147, 0, :east
unit :archer, 148, 0, :east
unit :captive, 150, 0, :east
unit :thick_sludge, 152, 0, :east
unit :thick_sludge, 154, 0, :east
unit :sludge, 155, 0, :east
unit :thick_sludge, 159, 0, :east
unit :captive, 160, 0, :east
unit :sludge, 166, 0, :west
unit :archer, 170, 0, :west
unit :sludge, 172, 0, :west
unit :archer, 175, 0, :west
unit :sludge, 178, 0, :west
unit :sludge, 181, 0, :west
unit :captive, 184, 0, :west
unit :thick_sludge, 191, 0, :west
unit :captive, 192, 0, :west
unit :sludge, 194, 0, :west
unit :captive, 203, 0, :west
unit :wizard, 206, 0, :west
unit :thick_sludge, 207, 0, :west
unit :wizard, 210, 0, :west
unit :archer, 214, 0, :west
unit :thick_sludge, 215, 0, :west
unit :thick_sludge, 224, 0, :west
unit :thick_sludge, 244, 0, :west
unit :sludge, 249, 0, :west
unit :sludge, 253, 0, :west
unit :archer, 260, 0, :west
unit :sludge, 271, 0, :west
unit :archer, 273, 0, :west
unit :sludge, 274, 0, :west
unit :archer, 276, 0, :west
unit :captive, 278, 0, :west
unit :wizard, 285, 0, :west
unit :archer, 286, 0, :west
unit :thick_sludge, 294, 0, :west
unit :captive, 295, 0, :west
unit :thick_sludge, 297, 0, :west
unit :thick_sludge, 298, 0, :west
unit :thick_sludge, 299, 0, :west
unit :sludge, 310, 0, :west
unit :thick_sludge, 317, 0, :west
unit :captive, 328, 0, :west
unit :sludge, 335, 0, :west
unit :captive, 338, 0, :west
unit :wizard, 340, 0, :west
unit :sludge, 349, 0, :west
unit :wizard, 353, 0, :west
unit :archer, 361, 0, :west
unit :wizard, 371, 0, :west
unit :wizard, 375, 0, :west
unit :archer, 377, 0, :west
unit :archer, 379, 0, :west
unit :sludge, 381, 0, :west
unit :archer, 383, 0, :west
unit :captive, 384, 0, :west
unit :sludge, 389, 0, :west
unit :thick_sludge, 394, 0, :west
unit :captive, 395, 0, :west
unit :captive, 402, 0, :west
unit :captive, 403, 0, :west
unit :sludge, 416, 0, :west
unit :sludge, 417, 0, :west
unit :captive, 421, 0, :west
unit :sludge, 426, 0, :west
unit :sludge, 437, 0, :west
unit :sludge, 438, 0, :west
unit :archer, 442, 0, :west
unit :thick_sludge, 443, 0, :west
unit :archer, 452, 0, :west
unit :sludge, 454, 0, :west
unit :sludge, 459, 0, :west
unit :captive, 460, 0, :west
unit :archer, 465, 0, :west
unit :captive, 472, 0, :west
unit :archer, 473, 0, :west
unit :sludge, 475, 0, :west
unit :archer, 483, 0, :west
unit :sludge, 488, 0, :west
unit :sludge, 490, 0, :west
unit :thick_sludge, 491, 0, :west
unit :thick_sludge, 511, 0, :west
unit :sludge, 512, 0, :west
unit :sludge, 514, 0, :west
unit :thick_sludge, 524, 0, :west
unit :thick_sludge, 529, 0, :west
unit :sludge, 532, 0, :west
unit :thick_sludge, 533, 0, :west
unit :thick_sludge, 534, 0, :west
unit :wizard, 536, 0, :west
unit :thick_sludge, 539, 0, :west
unit :thick_sludge, 542, 0, :west
unit :archer, 544, 0, :west
unit :thick_sludge, 546, 0, :west
unit :sludge, 548, 0, :west
unit :thick_sludge, 549, 0, :west
unit :thick_sludge, 550, 0, :west
unit :archer, 557, 0, :west
unit :captive, 559, 0, :west
unit :thick_sludge, 561, 0, :west
unit :archer, 563, 0, :west
unit :captive, 565, 0, :west
unit :thick_sludge, 567, 0, :west
unit :wizard, 570, 0, :west
unit :sludge, 572, 0, :west
unit :thick_sludge, 573, 0, :west
unit :sludge, 581, 0, :west
unit :sludge, 582, 0, :west
unit :thick_sludge, 587, 0, :west
unit :sludge, 591, 0, :west
unit :archer, 594, 0, :west
unit :thick_sludge, 595, 0, :west
unit :wizard, 599, 0, :west
unit :captive, 602, 0, :west
unit :wizard, 604, 0, :west
unit :wizard, 608, 0, :west
unit :thick_sludge, 609, 0, :west
unit :archer, 612, 0, :west
unit :sludge, 619, 0, :west
unit :thick_sludge, 635, 0, :west
unit :thick_sludge, 637, 0, :west
unit :thick_sludge, 639, 0, :west
unit :archer, 641, 0, :west
unit :archer, 645, 0, :west
unit :thick_sludge, 646, 0, :west
unit :captive, 648, 0, :west
unit :archer, 653, 0, :west
unit :wizard, 654, 0, :west
unit :archer, 657, 0, :west
unit :wizard, 659, 0, :west
unit :sludge, 664, 0, :west
unit :thick_sludge, 665, 0, :west
unit :archer, 666, 0, :west
unit :sludge, 668, 0, :west
unit :captive, 670, 0, :west
unit :archer, 671, 0, :west
unit :captive, 678, 0, :west
unit :captive, 680, 0, :west
unit :thick_sludge, 683, 0, :west
unit :sludge, 684, 0, :west
unit :sludge, 696, 0, :west
unit :thick_sludge, 698, 0, :west
unit :captive, 707, 0, :west
unit :captive, 710, 0, :west
unit :captive, 711, 0, :west
unit :sludge, 715, 0, :west
unit :captive, 722, 0, :west
unit :archer, 723, 0, :west
unit :thick_sludge, 724, 0, :west
unit :sludge, 727, 0, :west
unit :thick_sludge, 729, 0, :west
unit :wizard, 730, 0, :west
unit :archer, 731, 0, :west
unit :wizard, 745, 0, :west
unit :thick_sludge, 757, 0, :west
unit :captive, 759, 0, :west
unit :sludge, 762, 0, :west
unit :archer, 765, 0, :west
unit :sludge, 767, 0, :west
unit :archer, 768, 0, :west
unit :thick_sludge, 774, 0, :west
unit :thick_sludge, 779, 0, :west
unit :thick_sludge, 781, 0, :west
unit :archer, 782, 0, :west
unit :wizard, 788, 0, :west
