#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | w    C  C  s   SS S C w   w  w a w         S s  aC       s   C   a  w C   a       C  w  C      w    Ca>      Ca  awS  s     s S  s                        s s  w sS      C         s     SS    s    S as s aC S sw  S         s   s w  a  sSa  wS    s   S  SC      w a w S          ws   w          S sa C  w      @         S    w       S     C C     a                   a   w             s  C  S    w s s    a w  as      Sa s     S    C      w  a a    s S s     CC  s   S C   wC    S      aC             w  a  a ws     w      C   C sS  C    a     a      w aC     s   w s  C  a   s       C         aC  C  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 600
ace_score 3000
size 600, 1
stairs 103, 0

warrior 309, 0, :east

unit :wizard, 1, 0, :east
unit :captive, 6, 0, :east
unit :captive, 9, 0, :east
unit :sludge, 12, 0, :east
unit :thick_sludge, 16, 0, :east
unit :thick_sludge, 17, 0, :east
unit :thick_sludge, 19, 0, :east
unit :captive, 21, 0, :east
unit :wizard, 23, 0, :east
unit :wizard, 27, 0, :east
unit :wizard, 30, 0, :east
unit :archer, 32, 0, :east
unit :wizard, 34, 0, :east
unit :thick_sludge, 44, 0, :east
unit :sludge, 46, 0, :east
unit :archer, 49, 0, :east
unit :captive, 50, 0, :east
unit :sludge, 58, 0, :east
unit :captive, 62, 0, :east
unit :archer, 66, 0, :east
unit :wizard, 69, 0, :east
unit :captive, 71, 0, :east
unit :archer, 75, 0, :east
unit :captive, 83, 0, :east
unit :wizard, 86, 0, :east
unit :captive, 89, 0, :east
unit :wizard, 96, 0, :east
unit :captive, 101, 0, :east
unit :archer, 102, 0, :east
unit :captive, 110, 0, :east
unit :archer, 111, 0, :east
unit :archer, 114, 0, :east
unit :wizard, 115, 0, :east
unit :thick_sludge, 116, 0, :east
unit :sludge, 119, 0, :east
unit :sludge, 125, 0, :east
unit :thick_sludge, 127, 0, :east
unit :sludge, 130, 0, :east
unit :sludge, 155, 0, :east
unit :sludge, 157, 0, :east
unit :wizard, 160, 0, :east
unit :sludge, 162, 0, :east
unit :thick_sludge, 163, 0, :east
unit :captive, 170, 0, :east
unit :sludge, 180, 0, :east
unit :thick_sludge, 186, 0, :east
unit :thick_sludge, 187, 0, :east
unit :sludge, 192, 0, :east
unit :thick_sludge, 197, 0, :east
unit :archer, 199, 0, :east
unit :sludge, 200, 0, :east
unit :sludge, 202, 0, :east
unit :archer, 204, 0, :east
unit :captive, 205, 0, :east
unit :thick_sludge, 207, 0, :east
unit :sludge, 209, 0, :east
unit :wizard, 210, 0, :east
unit :thick_sludge, 213, 0, :east
unit :sludge, 223, 0, :east
unit :sludge, 227, 0, :east
unit :wizard, 229, 0, :east
unit :archer, 232, 0, :east
unit :sludge, 235, 0, :east
unit :thick_sludge, 236, 0, :east
unit :archer, 237, 0, :east
unit :wizard, 240, 0, :east
unit :thick_sludge, 241, 0, :east
unit :sludge, 246, 0, :east
unit :thick_sludge, 250, 0, :east
unit :thick_sludge, 253, 0, :east
unit :captive, 254, 0, :east
unit :wizard, 261, 0, :east
unit :archer, 263, 0, :east
unit :wizard, 265, 0, :east
unit :thick_sludge, 267, 0, :east
unit :wizard, 278, 0, :east
unit :sludge, 279, 0, :east
unit :wizard, 283, 0, :east
unit :thick_sludge, 294, 0, :east
unit :sludge, 296, 0, :east
unit :archer, 297, 0, :east
unit :captive, 299, 0, :east
unit :wizard, 302, 0, :east
unit :thick_sludge, 319, 0, :west
unit :wizard, 324, 0, :west
unit :thick_sludge, 332, 0, :west
unit :captive, 338, 0, :west
unit :captive, 340, 0, :west
unit :archer, 346, 0, :west
unit :archer, 366, 0, :west
unit :wizard, 370, 0, :west
unit :sludge, 384, 0, :west
unit :captive, 387, 0, :west
unit :thick_sludge, 390, 0, :west
unit :wizard, 395, 0, :west
unit :sludge, 397, 0, :west
unit :sludge, 399, 0, :west
unit :archer, 404, 0, :west
unit :wizard, 406, 0, :west
unit :archer, 409, 0, :west
unit :sludge, 410, 0, :west
unit :thick_sludge, 417, 0, :west
unit :archer, 418, 0, :west
unit :sludge, 420, 0, :west
unit :thick_sludge, 426, 0, :west
unit :captive, 431, 0, :west
unit :wizard, 438, 0, :west
unit :archer, 441, 0, :west
unit :archer, 443, 0, :west
unit :sludge, 448, 0, :west
unit :thick_sludge, 450, 0, :west
unit :sludge, 452, 0, :west
unit :captive, 458, 0, :west
unit :captive, 459, 0, :west
unit :sludge, 462, 0, :west
unit :thick_sludge, 466, 0, :west
unit :captive, 468, 0, :west
unit :wizard, 472, 0, :west
unit :captive, 473, 0, :west
unit :thick_sludge, 478, 0, :west
unit :archer, 485, 0, :west
unit :captive, 486, 0, :west
unit :wizard, 500, 0, :west
unit :archer, 503, 0, :west
unit :archer, 506, 0, :west
unit :wizard, 508, 0, :west
unit :sludge, 509, 0, :west
unit :wizard, 515, 0, :west
unit :captive, 522, 0, :west
unit :captive, 526, 0, :west
unit :sludge, 528, 0, :west
unit :thick_sludge, 529, 0, :west
unit :captive, 532, 0, :west
unit :archer, 537, 0, :west
unit :archer, 543, 0, :west
unit :wizard, 550, 0, :west
unit :archer, 552, 0, :west
unit :captive, 553, 0, :west
unit :sludge, 559, 0, :west
unit :wizard, 563, 0, :west
unit :sludge, 565, 0, :west
unit :captive, 568, 0, :west
unit :archer, 571, 0, :west
unit :sludge, 575, 0, :west
unit :captive, 583, 0, :west
unit :archer, 593, 0, :west
unit :captive, 594, 0, :west
unit :captive, 597, 0, :west
