#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C    w  S w s             w C C s w w    S   w     s         wsS    Csa s         asa      a SS a   S         s sS C w s       Ss S S       a      s S S    S s             C   S    CC a  s C       w       aS  w  aa       a    s       wa a  s a   C    C       s  s C     S S S     s w      w a         S  S   a  s  S     Cs      s     a Sw   C        a   a      s s    ss     s C             S  s         s    S  a a  ss    w    w  w      C SC w   w   a C >s              w    sC  @    C Sw          aa        SS s   s  a s    a    w  S a   |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 542
ace_score 2710
size 542, 1
stairs 457, 0

warrior 482, 0, :east

unit :captive, 2, 0, :east
unit :wizard, 7, 0, :east
unit :thick_sludge, 10, 0, :east
unit :wizard, 12, 0, :east
unit :sludge, 14, 0, :east
unit :wizard, 28, 0, :east
unit :captive, 30, 0, :east
unit :captive, 32, 0, :east
unit :sludge, 34, 0, :east
unit :wizard, 36, 0, :east
unit :wizard, 38, 0, :east
unit :thick_sludge, 43, 0, :east
unit :wizard, 47, 0, :east
unit :sludge, 53, 0, :east
unit :wizard, 63, 0, :east
unit :sludge, 64, 0, :east
unit :thick_sludge, 65, 0, :east
unit :captive, 70, 0, :east
unit :sludge, 71, 0, :east
unit :archer, 72, 0, :east
unit :sludge, 74, 0, :east
unit :archer, 84, 0, :east
unit :sludge, 85, 0, :east
unit :archer, 86, 0, :east
unit :archer, 93, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 96, 0, :east
unit :archer, 98, 0, :east
unit :thick_sludge, 102, 0, :east
unit :sludge, 112, 0, :east
unit :sludge, 114, 0, :east
unit :thick_sludge, 115, 0, :east
unit :captive, 117, 0, :east
unit :wizard, 119, 0, :east
unit :sludge, 121, 0, :east
unit :thick_sludge, 129, 0, :east
unit :sludge, 130, 0, :east
unit :thick_sludge, 132, 0, :east
unit :thick_sludge, 134, 0, :east
unit :archer, 142, 0, :east
unit :sludge, 149, 0, :east
unit :thick_sludge, 151, 0, :east
unit :thick_sludge, 153, 0, :east
unit :thick_sludge, 158, 0, :east
unit :sludge, 160, 0, :east
unit :captive, 174, 0, :east
unit :thick_sludge, 178, 0, :east
unit :captive, 183, 0, :east
unit :captive, 184, 0, :east
unit :archer, 186, 0, :east
unit :sludge, 189, 0, :east
unit :captive, 191, 0, :east
unit :wizard, 199, 0, :east
unit :archer, 207, 0, :east
unit :thick_sludge, 208, 0, :east
unit :wizard, 211, 0, :east
unit :archer, 214, 0, :east
unit :archer, 215, 0, :east
unit :archer, 223, 0, :east
unit :sludge, 228, 0, :east
unit :wizard, 236, 0, :east
unit :archer, 237, 0, :east
unit :archer, 239, 0, :east
unit :sludge, 242, 0, :east
unit :archer, 244, 0, :east
unit :captive, 248, 0, :east
unit :captive, 253, 0, :east
unit :sludge, 261, 0, :east
unit :sludge, 264, 0, :east
unit :captive, 266, 0, :east
unit :thick_sludge, 272, 0, :east
unit :thick_sludge, 274, 0, :east
unit :thick_sludge, 276, 0, :east
unit :sludge, 282, 0, :east
unit :wizard, 284, 0, :east
unit :wizard, 291, 0, :east
unit :archer, 293, 0, :east
unit :thick_sludge, 303, 0, :east
unit :thick_sludge, 306, 0, :east
unit :archer, 310, 0, :east
unit :sludge, 313, 0, :east
unit :thick_sludge, 316, 0, :east
unit :captive, 322, 0, :east
unit :sludge, 323, 0, :east
unit :sludge, 330, 0, :east
unit :archer, 336, 0, :east
unit :thick_sludge, 338, 0, :east
unit :wizard, 339, 0, :east
unit :captive, 343, 0, :east
unit :archer, 352, 0, :east
unit :archer, 356, 0, :east
unit :sludge, 363, 0, :east
unit :sludge, 365, 0, :east
unit :sludge, 370, 0, :east
unit :sludge, 371, 0, :east
unit :sludge, 377, 0, :east
unit :captive, 379, 0, :east
unit :thick_sludge, 393, 0, :east
unit :sludge, 396, 0, :east
unit :sludge, 406, 0, :east
unit :thick_sludge, 411, 0, :east
unit :archer, 414, 0, :east
unit :archer, 416, 0, :east
unit :sludge, 419, 0, :east
unit :sludge, 420, 0, :east
unit :wizard, 425, 0, :east
unit :wizard, 430, 0, :east
unit :wizard, 433, 0, :east
unit :captive, 440, 0, :east
unit :thick_sludge, 442, 0, :east
unit :captive, 443, 0, :east
unit :wizard, 445, 0, :east
unit :wizard, 449, 0, :east
unit :archer, 453, 0, :east
unit :captive, 455, 0, :east
unit :sludge, 458, 0, :east
unit :wizard, 473, 0, :east
unit :sludge, 478, 0, :east
unit :captive, 479, 0, :east
unit :captive, 487, 0, :west
unit :thick_sludge, 489, 0, :west
unit :wizard, 490, 0, :west
unit :archer, 501, 0, :west
unit :archer, 502, 0, :west
unit :thick_sludge, 511, 0, :west
unit :thick_sludge, 512, 0, :west
unit :sludge, 514, 0, :west
unit :sludge, 518, 0, :west
unit :archer, 521, 0, :west
unit :sludge, 523, 0, :west
unit :archer, 528, 0, :west
unit :wizard, 533, 0, :west
unit :thick_sludge, 536, 0, :west
unit :archer, 538, 0, :west
