#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     CsSa        a   Cs  C    ssC            s     as      s   S  Ss  S s     ss C    aSs    s  a  @          sC S S C     SC  Sa   CC    C      S a      aS >      S  C C   C w   CS SaS  ss         s     s  Cs         a        s        S C     C  s  aS    C      S    C  s   S       s     S     C     sa    Ss S   aa       ss    a     w           ss Ca  s        S  w  C       s     C  w                        ss ws       s      S    w      s   sSaw    w wa a              a    C s     a        s S          s   w   C    S     a      C    w  SSSs    a  Cs w        swC       C    aaC      C     a a     s  C   w   s     S  s   S  S s w       S a    S    sC       sa      C    SS   CC   S  w         S w aS  w a  sass C     S w   w a    w s C a            s         sC Cs    S C  C      w   s     s  w      S Cs   s        SCs s    s  C         w          s  C w      C  C a S      s  s  S  Ss         sS   C C    a    w    |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 924
ace_score 4620
size 924, 1
stairs 157, 0

warrior 99, 0, :east

unit :captive, 5, 0, :east
unit :sludge, 6, 0, :east
unit :thick_sludge, 7, 0, :east
unit :archer, 8, 0, :east
unit :archer, 17, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 22, 0, :east
unit :captive, 25, 0, :east
unit :sludge, 30, 0, :east
unit :sludge, 31, 0, :east
unit :captive, 32, 0, :east
unit :sludge, 45, 0, :east
unit :archer, 51, 0, :east
unit :sludge, 52, 0, :east
unit :sludge, 59, 0, :east
unit :thick_sludge, 63, 0, :east
unit :thick_sludge, 66, 0, :east
unit :sludge, 67, 0, :east
unit :thick_sludge, 70, 0, :east
unit :sludge, 72, 0, :east
unit :sludge, 78, 0, :east
unit :sludge, 79, 0, :east
unit :captive, 81, 0, :east
unit :archer, 86, 0, :east
unit :thick_sludge, 87, 0, :east
unit :sludge, 88, 0, :east
unit :sludge, 93, 0, :east
unit :archer, 96, 0, :east
unit :sludge, 110, 0, :west
unit :captive, 111, 0, :west
unit :thick_sludge, 113, 0, :west
unit :thick_sludge, 115, 0, :west
unit :captive, 117, 0, :west
unit :thick_sludge, 123, 0, :west
unit :captive, 124, 0, :west
unit :thick_sludge, 127, 0, :west
unit :archer, 128, 0, :west
unit :captive, 132, 0, :west
unit :captive, 133, 0, :west
unit :captive, 138, 0, :west
unit :thick_sludge, 145, 0, :west
unit :archer, 147, 0, :west
unit :archer, 154, 0, :west
unit :thick_sludge, 155, 0, :west
unit :thick_sludge, 164, 0, :west
unit :captive, 167, 0, :west
unit :captive, 169, 0, :west
unit :captive, 173, 0, :west
unit :wizard, 175, 0, :west
unit :captive, 179, 0, :west
unit :thick_sludge, 180, 0, :west
unit :thick_sludge, 182, 0, :west
unit :archer, 183, 0, :west
unit :thick_sludge, 184, 0, :west
unit :sludge, 187, 0, :west
unit :sludge, 188, 0, :west
unit :sludge, 198, 0, :west
unit :sludge, 204, 0, :west
unit :captive, 207, 0, :west
unit :sludge, 208, 0, :west
unit :archer, 218, 0, :west
unit :sludge, 227, 0, :west
unit :thick_sludge, 236, 0, :west
unit :captive, 238, 0, :west
unit :captive, 244, 0, :west
unit :sludge, 247, 0, :west
unit :archer, 250, 0, :west
unit :thick_sludge, 251, 0, :west
unit :captive, 256, 0, :west
unit :thick_sludge, 263, 0, :west
unit :captive, 268, 0, :west
unit :sludge, 271, 0, :west
unit :thick_sludge, 275, 0, :west
unit :sludge, 283, 0, :west
unit :thick_sludge, 289, 0, :west
unit :captive, 295, 0, :west
unit :sludge, 301, 0, :west
unit :archer, 302, 0, :west
unit :thick_sludge, 307, 0, :west
unit :sludge, 308, 0, :west
unit :thick_sludge, 310, 0, :west
unit :archer, 314, 0, :west
unit :archer, 315, 0, :west
unit :sludge, 323, 0, :west
unit :sludge, 324, 0, :west
unit :archer, 329, 0, :west
unit :wizard, 335, 0, :west
unit :sludge, 347, 0, :west
unit :sludge, 348, 0, :west
unit :captive, 350, 0, :west
unit :archer, 351, 0, :west
unit :sludge, 354, 0, :west
unit :thick_sludge, 363, 0, :west
unit :wizard, 366, 0, :west
unit :captive, 369, 0, :west
unit :sludge, 377, 0, :west
unit :captive, 383, 0, :west
unit :wizard, 386, 0, :west
unit :sludge, 411, 0, :west
unit :sludge, 412, 0, :west
unit :wizard, 414, 0, :west
unit :sludge, 415, 0, :west
unit :sludge, 423, 0, :west
unit :thick_sludge, 430, 0, :west
unit :wizard, 435, 0, :west
unit :sludge, 442, 0, :west
unit :sludge, 446, 0, :west
unit :thick_sludge, 447, 0, :west
unit :archer, 448, 0, :west
unit :wizard, 449, 0, :west
unit :wizard, 454, 0, :west
unit :wizard, 456, 0, :west
unit :archer, 457, 0, :west
unit :archer, 459, 0, :west
unit :archer, 474, 0, :west
unit :captive, 479, 0, :west
unit :sludge, 481, 0, :west
unit :archer, 487, 0, :west
unit :sludge, 496, 0, :west
unit :thick_sludge, 498, 0, :west
unit :sludge, 509, 0, :west
unit :wizard, 513, 0, :west
unit :captive, 517, 0, :west
unit :thick_sludge, 522, 0, :west
unit :archer, 528, 0, :west
unit :captive, 535, 0, :west
unit :wizard, 540, 0, :west
unit :thick_sludge, 543, 0, :west
unit :thick_sludge, 544, 0, :west
unit :thick_sludge, 545, 0, :west
unit :sludge, 546, 0, :west
unit :archer, 551, 0, :west
unit :captive, 554, 0, :west
unit :sludge, 555, 0, :west
unit :wizard, 557, 0, :west
unit :sludge, 566, 0, :west
unit :wizard, 567, 0, :west
unit :captive, 568, 0, :west
unit :captive, 576, 0, :west
unit :archer, 581, 0, :west
unit :archer, 582, 0, :west
unit :captive, 583, 0, :west
unit :captive, 590, 0, :west
unit :archer, 596, 0, :west
unit :archer, 598, 0, :west
unit :sludge, 604, 0, :west
unit :captive, 607, 0, :west
unit :wizard, 611, 0, :west
unit :sludge, 615, 0, :west
unit :thick_sludge, 621, 0, :west
unit :sludge, 624, 0, :west
unit :thick_sludge, 628, 0, :west
unit :thick_sludge, 631, 0, :west
unit :sludge, 633, 0, :west
unit :wizard, 635, 0, :west
unit :thick_sludge, 643, 0, :west
unit :archer, 645, 0, :west
unit :thick_sludge, 650, 0, :west
unit :sludge, 655, 0, :west
unit :captive, 656, 0, :west
unit :sludge, 664, 0, :west
unit :archer, 665, 0, :west
unit :captive, 672, 0, :west
unit :thick_sludge, 677, 0, :west
unit :thick_sludge, 678, 0, :west
unit :captive, 682, 0, :west
unit :captive, 683, 0, :west
unit :thick_sludge, 687, 0, :west
unit :wizard, 690, 0, :west
unit :thick_sludge, 700, 0, :west
unit :wizard, 702, 0, :west
unit :archer, 704, 0, :west
unit :thick_sludge, 705, 0, :west
unit :wizard, 708, 0, :west
unit :archer, 710, 0, :west
unit :sludge, 713, 0, :west
unit :archer, 714, 0, :west
unit :sludge, 715, 0, :west
unit :sludge, 716, 0, :west
unit :captive, 718, 0, :west
unit :thick_sludge, 724, 0, :west
unit :wizard, 726, 0, :west
unit :wizard, 730, 0, :west
unit :archer, 732, 0, :west
unit :wizard, 737, 0, :west
unit :sludge, 739, 0, :west
unit :captive, 741, 0, :west
unit :archer, 743, 0, :west
unit :sludge, 756, 0, :west
unit :sludge, 766, 0, :west
unit :captive, 767, 0, :west
unit :captive, 769, 0, :west
unit :sludge, 770, 0, :west
unit :thick_sludge, 775, 0, :west
unit :captive, 777, 0, :west
unit :captive, 780, 0, :west
unit :wizard, 787, 0, :west
unit :sludge, 791, 0, :west
unit :sludge, 797, 0, :west
unit :wizard, 800, 0, :west
unit :thick_sludge, 807, 0, :west
unit :captive, 809, 0, :west
unit :sludge, 810, 0, :west
unit :sludge, 814, 0, :west
unit :thick_sludge, 823, 0, :west
unit :captive, 824, 0, :west
unit :sludge, 825, 0, :west
unit :sludge, 827, 0, :west
unit :sludge, 832, 0, :west
unit :captive, 835, 0, :west
unit :wizard, 845, 0, :west
unit :sludge, 856, 0, :west
unit :captive, 859, 0, :west
unit :wizard, 861, 0, :west
unit :captive, 868, 0, :west
unit :captive, 871, 0, :west
unit :archer, 873, 0, :west
unit :thick_sludge, 875, 0, :west
unit :sludge, 882, 0, :west
unit :sludge, 885, 0, :west
unit :thick_sludge, 888, 0, :west
unit :thick_sludge, 891, 0, :west
unit :sludge, 892, 0, :west
unit :sludge, 902, 0, :west
unit :thick_sludge, 903, 0, :west
unit :captive, 907, 0, :west
unit :captive, 909, 0, :west
unit :archer, 914, 0, :west
unit :wizard, 919, 0, :west
