#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |        C        s          aS    C a   C     S C  C   C w  s  C   w         a        w s                  w w        w       S     w      C Sa     C  a     a      s  w    w            S   C     >Cs S      S           s a     S    a S C     a  CS        s   a  S        w S  C   aC    @   a   a   sss a     a w S      C  w  C C asa    C  S C        S s  C        a    a s     w  C     s  C Sa     SC  w     s        w   w    SCC  sS       C   aSS s w   C      a S s aSsw   s      a       S        sS    S   aC    S      asS      a  w    CCC      ss w    SS C  SC    a        s         a s w  a   s   S S   Ss         a       C                 C  w   S   C  a s          S  s w  C  w   C w           a  sa     a s   C Sw C   s      s  sSa  a SCS       s s Sa    C s  S a   CCs a         a sS w       s a  SS S  S     S  S aa   S          C  w    S  |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 848
ace_score 4240
size 848, 1
stairs 195, 0

warrior 285, 0, :east

unit :captive, 8, 0, :east
unit :sludge, 17, 0, :east
unit :archer, 28, 0, :east
unit :thick_sludge, 29, 0, :east
unit :captive, 34, 0, :east
unit :archer, 36, 0, :east
unit :captive, 40, 0, :east
unit :thick_sludge, 46, 0, :east
unit :captive, 48, 0, :east
unit :captive, 51, 0, :east
unit :captive, 55, 0, :east
unit :wizard, 57, 0, :east
unit :sludge, 60, 0, :east
unit :captive, 63, 0, :east
unit :wizard, 67, 0, :east
unit :archer, 77, 0, :east
unit :wizard, 86, 0, :east
unit :sludge, 88, 0, :east
unit :wizard, 107, 0, :east
unit :wizard, 109, 0, :east
unit :wizard, 118, 0, :east
unit :thick_sludge, 126, 0, :east
unit :wizard, 132, 0, :east
unit :captive, 139, 0, :east
unit :thick_sludge, 141, 0, :east
unit :archer, 142, 0, :east
unit :captive, 148, 0, :east
unit :archer, 151, 0, :east
unit :archer, 157, 0, :east
unit :sludge, 164, 0, :east
unit :wizard, 167, 0, :east
unit :wizard, 172, 0, :east
unit :thick_sludge, 185, 0, :east
unit :captive, 189, 0, :east
unit :captive, 196, 0, :east
unit :sludge, 197, 0, :east
unit :thick_sludge, 199, 0, :east
unit :thick_sludge, 206, 0, :east
unit :sludge, 218, 0, :east
unit :archer, 220, 0, :east
unit :thick_sludge, 226, 0, :east
unit :archer, 231, 0, :east
unit :thick_sludge, 233, 0, :east
unit :captive, 235, 0, :east
unit :archer, 241, 0, :east
unit :captive, 244, 0, :east
unit :thick_sludge, 245, 0, :east
unit :sludge, 254, 0, :east
unit :archer, 258, 0, :east
unit :thick_sludge, 261, 0, :east
unit :wizard, 270, 0, :east
unit :thick_sludge, 272, 0, :east
unit :captive, 275, 0, :east
unit :archer, 279, 0, :east
unit :captive, 280, 0, :east
unit :archer, 289, 0, :west
unit :archer, 293, 0, :west
unit :sludge, 297, 0, :west
unit :sludge, 298, 0, :west
unit :sludge, 299, 0, :west
unit :archer, 301, 0, :west
unit :archer, 307, 0, :west
unit :wizard, 309, 0, :west
unit :thick_sludge, 311, 0, :west
unit :captive, 318, 0, :west
unit :wizard, 321, 0, :west
unit :captive, 324, 0, :west
unit :captive, 326, 0, :west
unit :archer, 328, 0, :west
unit :sludge, 329, 0, :west
unit :archer, 330, 0, :west
unit :captive, 335, 0, :west
unit :thick_sludge, 338, 0, :west
unit :captive, 340, 0, :west
unit :thick_sludge, 349, 0, :west
unit :sludge, 351, 0, :west
unit :captive, 354, 0, :west
unit :archer, 363, 0, :west
unit :archer, 368, 0, :west
unit :sludge, 370, 0, :west
unit :wizard, 376, 0, :west
unit :captive, 379, 0, :west
unit :sludge, 385, 0, :west
unit :captive, 388, 0, :west
unit :thick_sludge, 390, 0, :west
unit :archer, 391, 0, :west
unit :thick_sludge, 397, 0, :west
unit :captive, 398, 0, :west
unit :wizard, 401, 0, :west
unit :sludge, 407, 0, :west
unit :wizard, 416, 0, :west
unit :wizard, 420, 0, :west
unit :thick_sludge, 425, 0, :west
unit :captive, 426, 0, :west
unit :captive, 427, 0, :west
unit :sludge, 430, 0, :west
unit :thick_sludge, 431, 0, :west
unit :captive, 439, 0, :west
unit :archer, 443, 0, :west
unit :thick_sludge, 444, 0, :west
unit :thick_sludge, 445, 0, :west
unit :sludge, 447, 0, :west
unit :wizard, 449, 0, :west
unit :captive, 453, 0, :west
unit :archer, 460, 0, :west
unit :thick_sludge, 462, 0, :west
unit :sludge, 464, 0, :west
unit :archer, 466, 0, :west
unit :thick_sludge, 467, 0, :west
unit :sludge, 468, 0, :west
unit :wizard, 469, 0, :west
unit :sludge, 473, 0, :west
unit :archer, 480, 0, :west
unit :thick_sludge, 488, 0, :west
unit :sludge, 497, 0, :west
unit :thick_sludge, 498, 0, :west
unit :thick_sludge, 503, 0, :west
unit :archer, 507, 0, :west
unit :captive, 508, 0, :west
unit :thick_sludge, 513, 0, :west
unit :archer, 520, 0, :west
unit :sludge, 521, 0, :west
unit :thick_sludge, 522, 0, :west
unit :archer, 529, 0, :west
unit :wizard, 532, 0, :west
unit :captive, 537, 0, :west
unit :captive, 538, 0, :west
unit :captive, 539, 0, :west
unit :sludge, 546, 0, :west
unit :sludge, 547, 0, :west
unit :wizard, 549, 0, :west
unit :thick_sludge, 554, 0, :west
unit :thick_sludge, 555, 0, :west
unit :captive, 557, 0, :west
unit :thick_sludge, 560, 0, :west
unit :captive, 561, 0, :west
unit :archer, 566, 0, :west
unit :sludge, 575, 0, :west
unit :archer, 585, 0, :west
unit :sludge, 587, 0, :west
unit :wizard, 589, 0, :west
unit :archer, 592, 0, :west
unit :sludge, 596, 0, :west
unit :thick_sludge, 600, 0, :west
unit :thick_sludge, 602, 0, :west
unit :thick_sludge, 606, 0, :west
unit :sludge, 607, 0, :west
unit :archer, 617, 0, :west
unit :captive, 625, 0, :west
unit :captive, 643, 0, :west
unit :wizard, 646, 0, :west
unit :thick_sludge, 650, 0, :west
unit :captive, 654, 0, :west
unit :archer, 657, 0, :west
unit :sludge, 659, 0, :west
unit :thick_sludge, 670, 0, :west
unit :sludge, 673, 0, :west
unit :wizard, 675, 0, :west
unit :captive, 678, 0, :west
unit :wizard, 681, 0, :west
unit :captive, 685, 0, :west
unit :wizard, 687, 0, :west
unit :archer, 699, 0, :west
unit :sludge, 702, 0, :west
unit :archer, 703, 0, :west
unit :archer, 709, 0, :west
unit :sludge, 711, 0, :west
unit :captive, 715, 0, :west
unit :thick_sludge, 717, 0, :west
unit :wizard, 718, 0, :west
unit :captive, 720, 0, :west
unit :sludge, 724, 0, :west
unit :sludge, 731, 0, :west
unit :sludge, 734, 0, :west
unit :thick_sludge, 735, 0, :west
unit :archer, 736, 0, :west
unit :archer, 739, 0, :west
unit :thick_sludge, 741, 0, :west
unit :captive, 742, 0, :west
unit :thick_sludge, 743, 0, :west
unit :sludge, 751, 0, :west
unit :sludge, 753, 0, :west
unit :thick_sludge, 755, 0, :west
unit :archer, 756, 0, :west
unit :captive, 761, 0, :west
unit :sludge, 763, 0, :west
unit :thick_sludge, 766, 0, :west
unit :archer, 768, 0, :west
unit :captive, 772, 0, :west
unit :captive, 773, 0, :west
unit :sludge, 774, 0, :west
unit :archer, 776, 0, :west
unit :archer, 786, 0, :west
unit :sludge, 788, 0, :west
unit :thick_sludge, 789, 0, :west
unit :wizard, 791, 0, :west
unit :sludge, 799, 0, :west
unit :archer, 801, 0, :west
unit :thick_sludge, 804, 0, :west
unit :thick_sludge, 805, 0, :west
unit :thick_sludge, 807, 0, :west
unit :thick_sludge, 810, 0, :west
unit :thick_sludge, 816, 0, :west
unit :thick_sludge, 819, 0, :west
unit :archer, 821, 0, :west
unit :archer, 822, 0, :west
unit :thick_sludge, 826, 0, :west
unit :captive, 837, 0, :west
unit :wizard, 840, 0, :west
unit :thick_sludge, 845, 0, :west
