#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |s w       >SsS    s   S w  CaS      C s   sw  s      C SS      C     w   sa   s     w         S          s        CS    C    w    w wC s    w s  @      ws    w    w  sa  s        s  a S S    s sSa       C     s  C   a     a    a S        ws    a   w   w C          w      C   w         a       C a   w s              s    S   a  w   S Cs        a C  S s  a s            S    a     s       a S    a w        a     S   S w  sS    a  sC  C     a  CC        a S  s    a  s  S     sa   a   S C    S s            CSa            aS     S  S        C asC  C       w   w S S    w sS wCa        s  a    C     w     C    sw w   s   SaC  w   w    SC    C S w S     a|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 654
ace_score 3270
size 654, 1
stairs 10, 0

warrior 145, 0, :east

unit :sludge, 0, 0, :east
unit :wizard, 2, 0, :east
unit :thick_sludge, 11, 0, :east
unit :sludge, 12, 0, :east
unit :thick_sludge, 13, 0, :east
unit :sludge, 18, 0, :east
unit :thick_sludge, 22, 0, :east
unit :wizard, 24, 0, :east
unit :captive, 27, 0, :east
unit :archer, 28, 0, :east
unit :thick_sludge, 29, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 38, 0, :east
unit :sludge, 42, 0, :east
unit :wizard, 43, 0, :east
unit :sludge, 46, 0, :east
unit :captive, 53, 0, :east
unit :thick_sludge, 55, 0, :east
unit :thick_sludge, 56, 0, :east
unit :captive, 63, 0, :east
unit :wizard, 69, 0, :east
unit :sludge, 73, 0, :east
unit :archer, 74, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 84, 0, :east
unit :thick_sludge, 94, 0, :east
unit :sludge, 105, 0, :east
unit :captive, 114, 0, :east
unit :thick_sludge, 115, 0, :east
unit :captive, 120, 0, :east
unit :wizard, 125, 0, :east
unit :wizard, 130, 0, :east
unit :wizard, 132, 0, :east
unit :captive, 133, 0, :east
unit :sludge, 135, 0, :east
unit :wizard, 140, 0, :east
unit :sludge, 142, 0, :east
unit :wizard, 152, 0, :west
unit :sludge, 153, 0, :west
unit :wizard, 158, 0, :west
unit :wizard, 163, 0, :west
unit :sludge, 166, 0, :west
unit :archer, 167, 0, :west
unit :sludge, 170, 0, :west
unit :sludge, 179, 0, :west
unit :archer, 182, 0, :west
unit :thick_sludge, 184, 0, :west
unit :thick_sludge, 186, 0, :west
unit :sludge, 191, 0, :west
unit :sludge, 193, 0, :west
unit :thick_sludge, 194, 0, :west
unit :archer, 195, 0, :west
unit :captive, 203, 0, :west
unit :sludge, 209, 0, :west
unit :captive, 212, 0, :west
unit :archer, 216, 0, :west
unit :archer, 222, 0, :west
unit :archer, 227, 0, :west
unit :thick_sludge, 229, 0, :west
unit :wizard, 238, 0, :west
unit :sludge, 239, 0, :west
unit :archer, 244, 0, :west
unit :wizard, 248, 0, :west
unit :wizard, 252, 0, :west
unit :captive, 254, 0, :west
unit :wizard, 265, 0, :west
unit :captive, 272, 0, :west
unit :wizard, 276, 0, :west
unit :archer, 286, 0, :west
unit :captive, 294, 0, :west
unit :archer, 296, 0, :west
unit :wizard, 300, 0, :west
unit :sludge, 302, 0, :west
unit :sludge, 317, 0, :west
unit :thick_sludge, 322, 0, :west
unit :archer, 326, 0, :west
unit :wizard, 329, 0, :west
unit :thick_sludge, 333, 0, :west
unit :captive, 335, 0, :west
unit :sludge, 336, 0, :west
unit :archer, 345, 0, :west
unit :captive, 347, 0, :west
unit :thick_sludge, 350, 0, :west
unit :sludge, 352, 0, :west
unit :archer, 355, 0, :west
unit :sludge, 357, 0, :west
unit :thick_sludge, 370, 0, :west
unit :archer, 375, 0, :west
unit :sludge, 381, 0, :west
unit :archer, 389, 0, :west
unit :thick_sludge, 391, 0, :west
unit :archer, 396, 0, :west
unit :wizard, 398, 0, :west
unit :archer, 407, 0, :west
unit :thick_sludge, 413, 0, :west
unit :thick_sludge, 417, 0, :west
unit :wizard, 419, 0, :west
unit :sludge, 422, 0, :west
unit :thick_sludge, 423, 0, :west
unit :archer, 428, 0, :west
unit :sludge, 431, 0, :west
unit :captive, 432, 0, :west
unit :captive, 435, 0, :west
unit :archer, 441, 0, :west
unit :captive, 444, 0, :west
unit :captive, 445, 0, :west
unit :archer, 454, 0, :west
unit :thick_sludge, 456, 0, :west
unit :sludge, 459, 0, :west
unit :archer, 464, 0, :west
unit :sludge, 467, 0, :west
unit :thick_sludge, 470, 0, :west
unit :sludge, 476, 0, :west
unit :archer, 477, 0, :west
unit :archer, 481, 0, :west
unit :thick_sludge, 485, 0, :west
unit :captive, 487, 0, :west
unit :thick_sludge, 492, 0, :west
unit :sludge, 494, 0, :west
unit :captive, 507, 0, :west
unit :thick_sludge, 508, 0, :west
unit :archer, 509, 0, :west
unit :archer, 522, 0, :west
unit :thick_sludge, 523, 0, :west
unit :thick_sludge, 529, 0, :west
unit :thick_sludge, 532, 0, :west
unit :captive, 541, 0, :west
unit :archer, 543, 0, :west
unit :sludge, 544, 0, :west
unit :captive, 545, 0, :west
unit :captive, 548, 0, :west
unit :wizard, 556, 0, :west
unit :wizard, 560, 0, :west
unit :thick_sludge, 562, 0, :west
unit :thick_sludge, 564, 0, :west
unit :wizard, 569, 0, :west
unit :sludge, 571, 0, :west
unit :thick_sludge, 572, 0, :west
unit :wizard, 574, 0, :west
unit :captive, 575, 0, :west
unit :archer, 576, 0, :west
unit :sludge, 585, 0, :west
unit :archer, 588, 0, :west
unit :captive, 593, 0, :west
unit :wizard, 599, 0, :west
unit :captive, 605, 0, :west
unit :sludge, 610, 0, :west
unit :wizard, 611, 0, :west
unit :wizard, 613, 0, :west
unit :sludge, 617, 0, :west
unit :thick_sludge, 621, 0, :west
unit :archer, 622, 0, :west
unit :captive, 623, 0, :west
unit :wizard, 626, 0, :west
unit :wizard, 630, 0, :west
unit :thick_sludge, 635, 0, :west
unit :captive, 636, 0, :west
unit :captive, 641, 0, :west
unit :thick_sludge, 643, 0, :west
unit :wizard, 645, 0, :west
unit :thick_sludge, 647, 0, :west
unit :archer, 653, 0, :west
