#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a  CC       wCS w    s       s S  s    s C     Ss w   C    CS     S     S    s              w a s             s         >         s    a     C  a aC       ws     a   a  ss  sw   w    sa  C S C  @   s  aa a   w   sC         S     w  w        Ss SCC  S S     C   ws S    s s a sS  S  w Sw       S  S      s    C w   sSa     C  a  a   S    a          s   S  S   S   s a      w  s w  wC     C    C  sa S    S     S   a a             S          s         a     C      s  C             Ss  w s   C    Cws CS   s        C   Ca S    sw   s            sa  a        C SC C SS s   CS    w    s  sCs  s  a  S       C                 as      w   s w        w a    S  S  C  |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 661
ace_score 3305
size 661, 1
stairs 121, 0

warrior 195, 0, :east

unit :archer, 1, 0, :east
unit :captive, 4, 0, :east
unit :captive, 5, 0, :east
unit :wizard, 13, 0, :east
unit :captive, 14, 0, :east
unit :thick_sludge, 15, 0, :east
unit :wizard, 17, 0, :east
unit :sludge, 22, 0, :east
unit :sludge, 30, 0, :east
unit :thick_sludge, 32, 0, :east
unit :sludge, 35, 0, :east
unit :sludge, 40, 0, :east
unit :captive, 42, 0, :east
unit :thick_sludge, 48, 0, :east
unit :sludge, 49, 0, :east
unit :wizard, 51, 0, :east
unit :captive, 55, 0, :east
unit :captive, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :thick_sludge, 67, 0, :east
unit :thick_sludge, 73, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 93, 0, :east
unit :archer, 95, 0, :east
unit :sludge, 97, 0, :east
unit :sludge, 111, 0, :east
unit :sludge, 131, 0, :east
unit :archer, 136, 0, :east
unit :captive, 142, 0, :east
unit :archer, 145, 0, :east
unit :archer, 147, 0, :east
unit :captive, 148, 0, :east
unit :wizard, 156, 0, :east
unit :sludge, 157, 0, :east
unit :archer, 163, 0, :east
unit :archer, 167, 0, :east
unit :sludge, 170, 0, :east
unit :sludge, 171, 0, :east
unit :sludge, 174, 0, :east
unit :wizard, 175, 0, :east
unit :wizard, 179, 0, :east
unit :sludge, 184, 0, :east
unit :archer, 185, 0, :east
unit :captive, 188, 0, :east
unit :thick_sludge, 190, 0, :east
unit :captive, 192, 0, :east
unit :sludge, 199, 0, :west
unit :archer, 202, 0, :west
unit :archer, 203, 0, :west
unit :archer, 205, 0, :west
unit :wizard, 209, 0, :west
unit :sludge, 213, 0, :west
unit :captive, 214, 0, :west
unit :thick_sludge, 224, 0, :west
unit :wizard, 230, 0, :west
unit :wizard, 233, 0, :west
unit :thick_sludge, 242, 0, :west
unit :sludge, 243, 0, :west
unit :thick_sludge, 245, 0, :west
unit :captive, 246, 0, :west
unit :captive, 247, 0, :west
unit :thick_sludge, 250, 0, :west
unit :thick_sludge, 252, 0, :west
unit :captive, 258, 0, :west
unit :wizard, 262, 0, :west
unit :sludge, 263, 0, :west
unit :thick_sludge, 265, 0, :west
unit :sludge, 270, 0, :west
unit :sludge, 272, 0, :west
unit :archer, 274, 0, :west
unit :sludge, 276, 0, :west
unit :thick_sludge, 277, 0, :west
unit :thick_sludge, 280, 0, :west
unit :wizard, 283, 0, :west
unit :thick_sludge, 285, 0, :west
unit :wizard, 286, 0, :west
unit :thick_sludge, 294, 0, :west
unit :thick_sludge, 297, 0, :west
unit :sludge, 304, 0, :west
unit :captive, 309, 0, :west
unit :wizard, 311, 0, :west
unit :sludge, 315, 0, :west
unit :thick_sludge, 316, 0, :west
unit :archer, 317, 0, :west
unit :captive, 323, 0, :west
unit :archer, 326, 0, :west
unit :archer, 329, 0, :west
unit :thick_sludge, 333, 0, :west
unit :archer, 338, 0, :west
unit :sludge, 349, 0, :west
unit :thick_sludge, 353, 0, :west
unit :thick_sludge, 356, 0, :west
unit :thick_sludge, 360, 0, :west
unit :sludge, 364, 0, :west
unit :archer, 366, 0, :west
unit :wizard, 373, 0, :west
unit :sludge, 376, 0, :west
unit :wizard, 378, 0, :west
unit :wizard, 381, 0, :west
unit :captive, 382, 0, :west
unit :captive, 388, 0, :west
unit :captive, 393, 0, :west
unit :sludge, 396, 0, :west
unit :archer, 397, 0, :west
unit :thick_sludge, 399, 0, :west
unit :thick_sludge, 404, 0, :west
unit :thick_sludge, 410, 0, :west
unit :archer, 414, 0, :west
unit :archer, 416, 0, :west
unit :thick_sludge, 430, 0, :west
unit :sludge, 441, 0, :west
unit :archer, 451, 0, :west
unit :captive, 457, 0, :west
unit :sludge, 464, 0, :west
unit :captive, 467, 0, :west
unit :thick_sludge, 481, 0, :west
unit :sludge, 482, 0, :west
unit :wizard, 485, 0, :west
unit :sludge, 487, 0, :west
unit :captive, 491, 0, :west
unit :captive, 496, 0, :west
unit :wizard, 497, 0, :west
unit :sludge, 498, 0, :west
unit :captive, 500, 0, :west
unit :thick_sludge, 501, 0, :west
unit :sludge, 505, 0, :west
unit :captive, 514, 0, :west
unit :captive, 518, 0, :west
unit :archer, 519, 0, :west
unit :thick_sludge, 521, 0, :west
unit :sludge, 526, 0, :west
unit :wizard, 527, 0, :west
unit :sludge, 531, 0, :west
unit :sludge, 544, 0, :west
unit :archer, 545, 0, :west
unit :archer, 548, 0, :west
unit :captive, 557, 0, :west
unit :thick_sludge, 559, 0, :west
unit :captive, 560, 0, :west
unit :captive, 562, 0, :west
unit :thick_sludge, 564, 0, :west
unit :thick_sludge, 565, 0, :west
unit :sludge, 567, 0, :west
unit :captive, 571, 0, :west
unit :thick_sludge, 572, 0, :west
unit :wizard, 577, 0, :west
unit :sludge, 582, 0, :west
unit :sludge, 585, 0, :west
unit :captive, 586, 0, :west
unit :sludge, 587, 0, :west
unit :sludge, 590, 0, :west
unit :archer, 593, 0, :west
unit :thick_sludge, 596, 0, :west
unit :captive, 604, 0, :west
unit :archer, 622, 0, :west
unit :sludge, 623, 0, :west
unit :wizard, 630, 0, :west
unit :sludge, 634, 0, :west
unit :wizard, 636, 0, :west
unit :wizard, 645, 0, :west
unit :archer, 647, 0, :west
unit :thick_sludge, 652, 0, :west
unit :thick_sludge, 655, 0, :west
unit :captive, 658, 0, :west
