#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |         s   sC C       aS C           w  C   S     SS   SSa  S s wC            s      a      s   w       S  C       C  a  a      s  C      s   a   s      s              S  S w  w   S          w  S       C   S w   C C  s   C    S   s    asC C Cs         w      a   C   a S  S      C a     s  s        C    sa   CC    sS      ssS as      C Cs C                 sS a  sw  saa  Ss w   w      a    S     a S      w  S   S  a  S  s  SSs s s   @  a               S     sw    aa wS  s       s   w                  w         C  S  a  S Ss     a Cs   SaS  s   asw s     s  C S   w C   as  SSa     S    C   ss    C S S     wC C     S w           S   w  C C   C               w    C      w       a     S       C  >   aa ss   sa S s w     a |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 729
ace_score 3645
size 729, 1
stairs 702, 0

warrior 438, 0, :east

unit :sludge, 9, 0, :east
unit :sludge, 13, 0, :east
unit :captive, 14, 0, :east
unit :captive, 16, 0, :east
unit :archer, 24, 0, :east
unit :thick_sludge, 25, 0, :east
unit :captive, 27, 0, :east
unit :wizard, 39, 0, :east
unit :captive, 42, 0, :east
unit :thick_sludge, 46, 0, :east
unit :thick_sludge, 52, 0, :east
unit :thick_sludge, 53, 0, :east
unit :thick_sludge, 57, 0, :east
unit :thick_sludge, 58, 0, :east
unit :archer, 59, 0, :east
unit :thick_sludge, 62, 0, :east
unit :sludge, 64, 0, :east
unit :wizard, 66, 0, :east
unit :captive, 67, 0, :east
unit :sludge, 80, 0, :east
unit :archer, 87, 0, :east
unit :sludge, 94, 0, :east
unit :wizard, 98, 0, :east
unit :thick_sludge, 106, 0, :east
unit :captive, 109, 0, :east
unit :captive, 117, 0, :east
unit :archer, 120, 0, :east
unit :archer, 123, 0, :east
unit :sludge, 130, 0, :east
unit :captive, 133, 0, :east
unit :sludge, 140, 0, :east
unit :archer, 144, 0, :east
unit :sludge, 148, 0, :east
unit :sludge, 155, 0, :east
unit :thick_sludge, 170, 0, :east
unit :thick_sludge, 173, 0, :east
unit :wizard, 175, 0, :east
unit :wizard, 178, 0, :east
unit :thick_sludge, 182, 0, :east
unit :wizard, 193, 0, :east
unit :thick_sludge, 196, 0, :east
unit :captive, 204, 0, :east
unit :thick_sludge, 208, 0, :east
unit :wizard, 210, 0, :east
unit :captive, 214, 0, :east
unit :captive, 216, 0, :east
unit :sludge, 219, 0, :east
unit :captive, 223, 0, :east
unit :thick_sludge, 228, 0, :east
unit :sludge, 232, 0, :east
unit :archer, 237, 0, :east
unit :sludge, 238, 0, :east
unit :captive, 239, 0, :east
unit :captive, 241, 0, :east
unit :captive, 243, 0, :east
unit :sludge, 244, 0, :east
unit :wizard, 254, 0, :east
unit :archer, 261, 0, :east
unit :captive, 265, 0, :east
unit :archer, 269, 0, :east
unit :thick_sludge, 271, 0, :east
unit :thick_sludge, 274, 0, :east
unit :captive, 281, 0, :east
unit :archer, 283, 0, :east
unit :sludge, 289, 0, :east
unit :sludge, 292, 0, :east
unit :captive, 301, 0, :east
unit :sludge, 306, 0, :east
unit :archer, 307, 0, :east
unit :captive, 311, 0, :east
unit :captive, 312, 0, :east
unit :sludge, 317, 0, :east
unit :thick_sludge, 318, 0, :east
unit :sludge, 325, 0, :east
unit :sludge, 326, 0, :east
unit :thick_sludge, 327, 0, :east
unit :archer, 329, 0, :east
unit :sludge, 330, 0, :east
unit :captive, 337, 0, :east
unit :captive, 339, 0, :east
unit :sludge, 340, 0, :east
unit :captive, 342, 0, :east
unit :sludge, 360, 0, :east
unit :thick_sludge, 361, 0, :east
unit :archer, 363, 0, :east
unit :sludge, 366, 0, :east
unit :wizard, 367, 0, :east
unit :sludge, 370, 0, :east
unit :archer, 371, 0, :east
unit :archer, 372, 0, :east
unit :thick_sludge, 375, 0, :east
unit :sludge, 376, 0, :east
unit :wizard, 378, 0, :east
unit :wizard, 382, 0, :east
unit :archer, 389, 0, :east
unit :thick_sludge, 394, 0, :east
unit :archer, 400, 0, :east
unit :thick_sludge, 402, 0, :east
unit :wizard, 409, 0, :east
unit :thick_sludge, 412, 0, :east
unit :thick_sludge, 416, 0, :east
unit :archer, 419, 0, :east
unit :thick_sludge, 422, 0, :east
unit :sludge, 425, 0, :east
unit :thick_sludge, 428, 0, :east
unit :thick_sludge, 429, 0, :east
unit :sludge, 430, 0, :east
unit :sludge, 432, 0, :east
unit :sludge, 434, 0, :east
unit :archer, 441, 0, :west
unit :thick_sludge, 457, 0, :west
unit :sludge, 463, 0, :west
unit :wizard, 464, 0, :west
unit :archer, 469, 0, :west
unit :archer, 470, 0, :west
unit :wizard, 472, 0, :west
unit :thick_sludge, 473, 0, :west
unit :sludge, 476, 0, :west
unit :sludge, 484, 0, :west
unit :wizard, 488, 0, :west
unit :wizard, 507, 0, :west
unit :captive, 517, 0, :west
unit :thick_sludge, 520, 0, :west
unit :archer, 523, 0, :west
unit :thick_sludge, 526, 0, :west
unit :thick_sludge, 528, 0, :west
unit :sludge, 529, 0, :west
unit :archer, 535, 0, :west
unit :captive, 537, 0, :west
unit :sludge, 538, 0, :west
unit :thick_sludge, 542, 0, :west
unit :archer, 543, 0, :west
unit :thick_sludge, 544, 0, :west
unit :sludge, 547, 0, :west
unit :archer, 551, 0, :west
unit :sludge, 552, 0, :west
unit :wizard, 553, 0, :west
unit :sludge, 555, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 564, 0, :west
unit :thick_sludge, 566, 0, :west
unit :wizard, 570, 0, :west
unit :captive, 572, 0, :west
unit :archer, 576, 0, :west
unit :sludge, 577, 0, :west
unit :thick_sludge, 580, 0, :west
unit :thick_sludge, 581, 0, :west
unit :archer, 582, 0, :west
unit :thick_sludge, 588, 0, :west
unit :captive, 593, 0, :west
unit :sludge, 597, 0, :west
unit :sludge, 598, 0, :west
unit :captive, 603, 0, :west
unit :thick_sludge, 605, 0, :west
unit :thick_sludge, 607, 0, :west
unit :wizard, 613, 0, :west
unit :captive, 614, 0, :west
unit :captive, 616, 0, :west
unit :thick_sludge, 622, 0, :west
unit :wizard, 624, 0, :west
unit :thick_sludge, 636, 0, :west
unit :wizard, 640, 0, :west
unit :captive, 643, 0, :west
unit :captive, 645, 0, :west
unit :captive, 649, 0, :west
unit :wizard, 665, 0, :west
unit :captive, 670, 0, :west
unit :wizard, 677, 0, :west
unit :archer, 685, 0, :west
unit :thick_sludge, 691, 0, :west
unit :captive, 699, 0, :west
unit :archer, 706, 0, :west
unit :archer, 707, 0, :west
unit :sludge, 709, 0, :west
unit :sludge, 710, 0, :west
unit :sludge, 714, 0, :west
unit :archer, 715, 0, :west
unit :thick_sludge, 717, 0, :west
unit :sludge, 719, 0, :west
unit :wizard, 721, 0, :west
unit :archer, 727, 0, :west
