#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    s       Ca            C  s C s                 S                 sSS    w w  s   S   S w   a C     S    w s    a    S    w   sC    C  S     w       a    w a  S as s      aw    a   w  S w      aa a s wSS           s   a  s  C     s  w s   C            w Cs     Ca    C    S a SS        S S S >S  C  C          C Ss    C     s    s  Sa  s   s   C a  s C s  w s   w s              sSs       w       a  sa   w  s S  saC   w         C      Cs    S  s s      S        C a   S C   sa   SS      s   aS w   s  CS C   s    s         w   sw        @  aSS  a  S      S S s  C   S    C       s    a        S        w w    a ss   S      |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 627
ace_score 3135
size 627, 1
stairs 295, 0

warrior 541, 0, :east

unit :sludge, 4, 0, :east
unit :captive, 12, 0, :east
unit :archer, 13, 0, :east
unit :captive, 26, 0, :east
unit :sludge, 29, 0, :east
unit :captive, 31, 0, :east
unit :sludge, 33, 0, :east
unit :thick_sludge, 51, 0, :east
unit :sludge, 69, 0, :east
unit :thick_sludge, 70, 0, :east
unit :thick_sludge, 71, 0, :east
unit :wizard, 76, 0, :east
unit :wizard, 78, 0, :east
unit :sludge, 81, 0, :east
unit :thick_sludge, 85, 0, :east
unit :thick_sludge, 89, 0, :east
unit :wizard, 91, 0, :east
unit :archer, 95, 0, :east
unit :captive, 97, 0, :east
unit :thick_sludge, 103, 0, :east
unit :wizard, 108, 0, :east
unit :sludge, 110, 0, :east
unit :archer, 115, 0, :east
unit :thick_sludge, 120, 0, :east
unit :wizard, 125, 0, :east
unit :sludge, 129, 0, :east
unit :captive, 130, 0, :east
unit :captive, 135, 0, :east
unit :thick_sludge, 138, 0, :east
unit :wizard, 144, 0, :east
unit :archer, 152, 0, :east
unit :wizard, 157, 0, :east
unit :archer, 159, 0, :east
unit :thick_sludge, 162, 0, :east
unit :archer, 164, 0, :east
unit :sludge, 165, 0, :east
unit :sludge, 167, 0, :east
unit :archer, 174, 0, :east
unit :wizard, 175, 0, :east
unit :archer, 180, 0, :east
unit :wizard, 184, 0, :east
unit :thick_sludge, 187, 0, :east
unit :wizard, 189, 0, :east
unit :archer, 196, 0, :east
unit :archer, 197, 0, :east
unit :archer, 199, 0, :east
unit :sludge, 201, 0, :east
unit :wizard, 203, 0, :east
unit :thick_sludge, 204, 0, :east
unit :thick_sludge, 205, 0, :east
unit :sludge, 217, 0, :east
unit :archer, 221, 0, :east
unit :sludge, 224, 0, :east
unit :captive, 227, 0, :east
unit :sludge, 233, 0, :east
unit :wizard, 236, 0, :east
unit :sludge, 238, 0, :east
unit :captive, 242, 0, :east
unit :wizard, 255, 0, :east
unit :captive, 257, 0, :east
unit :sludge, 258, 0, :east
unit :captive, 264, 0, :east
unit :archer, 265, 0, :east
unit :captive, 270, 0, :east
unit :thick_sludge, 275, 0, :east
unit :archer, 277, 0, :east
unit :thick_sludge, 279, 0, :east
unit :thick_sludge, 280, 0, :east
unit :thick_sludge, 289, 0, :east
unit :thick_sludge, 291, 0, :east
unit :thick_sludge, 293, 0, :east
unit :thick_sludge, 296, 0, :east
unit :captive, 299, 0, :east
unit :captive, 302, 0, :east
unit :captive, 313, 0, :east
unit :thick_sludge, 315, 0, :east
unit :sludge, 316, 0, :east
unit :captive, 321, 0, :east
unit :sludge, 327, 0, :east
unit :sludge, 332, 0, :east
unit :thick_sludge, 335, 0, :east
unit :archer, 336, 0, :east
unit :sludge, 339, 0, :east
unit :sludge, 343, 0, :east
unit :captive, 347, 0, :east
unit :archer, 349, 0, :east
unit :sludge, 352, 0, :east
unit :captive, 354, 0, :east
unit :sludge, 356, 0, :east
unit :wizard, 359, 0, :east
unit :sludge, 361, 0, :east
unit :wizard, 365, 0, :east
unit :sludge, 367, 0, :east
unit :sludge, 382, 0, :east
unit :thick_sludge, 383, 0, :east
unit :sludge, 384, 0, :east
unit :wizard, 392, 0, :east
unit :archer, 400, 0, :east
unit :sludge, 403, 0, :east
unit :archer, 404, 0, :east
unit :wizard, 408, 0, :east
unit :sludge, 411, 0, :east
unit :thick_sludge, 413, 0, :east
unit :sludge, 416, 0, :east
unit :archer, 417, 0, :east
unit :captive, 418, 0, :east
unit :wizard, 422, 0, :east
unit :captive, 432, 0, :east
unit :captive, 439, 0, :east
unit :sludge, 440, 0, :east
unit :thick_sludge, 445, 0, :east
unit :sludge, 448, 0, :east
unit :sludge, 450, 0, :east
unit :thick_sludge, 457, 0, :east
unit :captive, 466, 0, :east
unit :archer, 468, 0, :east
unit :thick_sludge, 472, 0, :east
unit :captive, 474, 0, :east
unit :sludge, 478, 0, :east
unit :archer, 479, 0, :east
unit :thick_sludge, 483, 0, :east
unit :thick_sludge, 484, 0, :east
unit :sludge, 491, 0, :east
unit :archer, 495, 0, :east
unit :thick_sludge, 496, 0, :east
unit :wizard, 498, 0, :east
unit :sludge, 502, 0, :east
unit :captive, 505, 0, :east
unit :thick_sludge, 506, 0, :east
unit :captive, 508, 0, :east
unit :sludge, 512, 0, :east
unit :sludge, 517, 0, :east
unit :wizard, 527, 0, :east
unit :sludge, 531, 0, :east
unit :wizard, 532, 0, :east
unit :archer, 544, 0, :west
unit :thick_sludge, 545, 0, :west
unit :thick_sludge, 546, 0, :west
unit :archer, 549, 0, :west
unit :thick_sludge, 552, 0, :west
unit :thick_sludge, 559, 0, :west
unit :thick_sludge, 561, 0, :west
unit :sludge, 563, 0, :west
unit :captive, 566, 0, :west
unit :thick_sludge, 570, 0, :west
unit :captive, 575, 0, :west
unit :sludge, 583, 0, :west
unit :archer, 588, 0, :west
unit :thick_sludge, 597, 0, :west
unit :wizard, 606, 0, :west
unit :wizard, 608, 0, :west
unit :archer, 613, 0, :west
unit :sludge, 615, 0, :west
unit :sludge, 616, 0, :west
unit :thick_sludge, 620, 0, :west
