#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      w   w S      s       w  S      aC  S Css  C    swS  C    a     w sC       w wSa  w  a a    S     s             aC  S sss  a      S w            S       s   a              C ws      C a     C       S   SS      C      S   CS C    Cas   CSs CSS  C    asC     wSa    CS s a   w               S         C  a         S  s  C   S    C a as      sC   s   @      w       s  ws    S     Ss  C                 SsaCSSs  S      Sa C       C  a    w            ss  C     C  s s     C   a     a    w   C   S C C   a   C          Sa  a  S    a C   aa    w w> as a        s C    s    S s   w    s      w   a   a    w C       a     a SS   ss w w      a  s   C   w a a   C     a    w  C s               s       SC  a  C a  C           s        C w            S       s C S    S  w     a    a     s   w     S        S  w            CsCw C   w  a s   S       s  C  S   ss w  s  a sSa    s|
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 873
ace_score 4365
size 873, 1
stairs 547, 0

warrior 353, 0, :east

unit :wizard, 6, 0, :east
unit :wizard, 10, 0, :east
unit :thick_sludge, 12, 0, :east
unit :sludge, 19, 0, :east
unit :wizard, 27, 0, :east
unit :thick_sludge, 30, 0, :east
unit :archer, 37, 0, :east
unit :captive, 38, 0, :east
unit :thick_sludge, 41, 0, :east
unit :captive, 43, 0, :east
unit :sludge, 44, 0, :east
unit :sludge, 45, 0, :east
unit :captive, 48, 0, :east
unit :sludge, 53, 0, :east
unit :wizard, 54, 0, :east
unit :thick_sludge, 55, 0, :east
unit :captive, 58, 0, :east
unit :archer, 63, 0, :east
unit :wizard, 69, 0, :east
unit :sludge, 71, 0, :east
unit :captive, 72, 0, :east
unit :wizard, 80, 0, :east
unit :wizard, 82, 0, :east
unit :thick_sludge, 83, 0, :east
unit :archer, 84, 0, :east
unit :wizard, 87, 0, :east
unit :archer, 90, 0, :east
unit :archer, 92, 0, :east
unit :thick_sludge, 97, 0, :east
unit :sludge, 103, 0, :east
unit :archer, 117, 0, :east
unit :captive, 118, 0, :east
unit :thick_sludge, 121, 0, :east
unit :sludge, 123, 0, :east
unit :sludge, 124, 0, :east
unit :sludge, 125, 0, :east
unit :archer, 128, 0, :east
unit :thick_sludge, 135, 0, :east
unit :wizard, 137, 0, :east
unit :thick_sludge, 150, 0, :east
unit :sludge, 158, 0, :east
unit :archer, 162, 0, :east
unit :captive, 177, 0, :east
unit :wizard, 179, 0, :east
unit :sludge, 180, 0, :east
unit :captive, 187, 0, :east
unit :archer, 189, 0, :east
unit :captive, 195, 0, :east
unit :thick_sludge, 203, 0, :east
unit :thick_sludge, 207, 0, :east
unit :thick_sludge, 208, 0, :east
unit :captive, 215, 0, :east
unit :thick_sludge, 222, 0, :east
unit :captive, 226, 0, :east
unit :thick_sludge, 227, 0, :east
unit :captive, 229, 0, :east
unit :captive, 234, 0, :east
unit :archer, 235, 0, :east
unit :sludge, 236, 0, :east
unit :captive, 240, 0, :east
unit :thick_sludge, 241, 0, :east
unit :sludge, 242, 0, :east
unit :captive, 244, 0, :east
unit :thick_sludge, 245, 0, :east
unit :thick_sludge, 246, 0, :east
unit :captive, 249, 0, :east
unit :archer, 254, 0, :east
unit :sludge, 255, 0, :east
unit :captive, 256, 0, :east
unit :wizard, 262, 0, :east
unit :thick_sludge, 263, 0, :east
unit :archer, 264, 0, :east
unit :captive, 269, 0, :east
unit :thick_sludge, 270, 0, :east
unit :sludge, 272, 0, :east
unit :archer, 274, 0, :east
unit :wizard, 278, 0, :east
unit :thick_sludge, 294, 0, :east
unit :captive, 304, 0, :east
unit :archer, 307, 0, :east
unit :thick_sludge, 317, 0, :east
unit :sludge, 320, 0, :east
unit :captive, 323, 0, :east
unit :thick_sludge, 327, 0, :east
unit :captive, 332, 0, :east
unit :archer, 334, 0, :east
unit :archer, 336, 0, :east
unit :sludge, 337, 0, :east
unit :sludge, 344, 0, :east
unit :captive, 345, 0, :east
unit :sludge, 349, 0, :east
unit :wizard, 360, 0, :west
unit :sludge, 368, 0, :west
unit :wizard, 371, 0, :west
unit :sludge, 372, 0, :west
unit :thick_sludge, 377, 0, :west
unit :thick_sludge, 383, 0, :west
unit :sludge, 384, 0, :west
unit :captive, 387, 0, :west
unit :thick_sludge, 405, 0, :west
unit :sludge, 406, 0, :west
unit :archer, 407, 0, :west
unit :captive, 408, 0, :west
unit :thick_sludge, 409, 0, :west
unit :thick_sludge, 410, 0, :west
unit :sludge, 411, 0, :west
unit :thick_sludge, 414, 0, :west
unit :thick_sludge, 421, 0, :west
unit :archer, 422, 0, :west
unit :captive, 424, 0, :west
unit :captive, 432, 0, :west
unit :archer, 435, 0, :west
unit :wizard, 440, 0, :west
unit :sludge, 453, 0, :west
unit :sludge, 454, 0, :west
unit :captive, 457, 0, :west
unit :captive, 463, 0, :west
unit :sludge, 466, 0, :west
unit :sludge, 468, 0, :west
unit :captive, 474, 0, :west
unit :archer, 478, 0, :west
unit :archer, 484, 0, :west
unit :wizard, 489, 0, :west
unit :captive, 493, 0, :west
unit :thick_sludge, 497, 0, :west
unit :captive, 499, 0, :west
unit :captive, 501, 0, :west
unit :archer, 505, 0, :west
unit :captive, 509, 0, :west
unit :thick_sludge, 520, 0, :west
unit :archer, 521, 0, :west
unit :archer, 524, 0, :west
unit :thick_sludge, 527, 0, :west
unit :archer, 532, 0, :west
unit :captive, 534, 0, :west
unit :archer, 538, 0, :west
unit :archer, 539, 0, :west
unit :wizard, 544, 0, :west
unit :wizard, 546, 0, :west
unit :archer, 549, 0, :west
unit :sludge, 550, 0, :west
unit :archer, 552, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 563, 0, :west
unit :sludge, 568, 0, :west
unit :thick_sludge, 573, 0, :west
unit :sludge, 575, 0, :west
unit :wizard, 579, 0, :west
unit :sludge, 584, 0, :west
unit :wizard, 591, 0, :west
unit :archer, 595, 0, :west
unit :archer, 599, 0, :west
unit :wizard, 604, 0, :west
unit :captive, 606, 0, :west
unit :archer, 614, 0, :west
unit :archer, 620, 0, :west
unit :thick_sludge, 622, 0, :west
unit :thick_sludge, 623, 0, :west
unit :sludge, 627, 0, :west
unit :sludge, 628, 0, :west
unit :wizard, 630, 0, :west
unit :wizard, 632, 0, :west
unit :archer, 639, 0, :west
unit :sludge, 642, 0, :west
unit :captive, 646, 0, :west
unit :wizard, 650, 0, :west
unit :archer, 652, 0, :west
unit :archer, 654, 0, :west
unit :captive, 658, 0, :west
unit :archer, 664, 0, :west
unit :wizard, 669, 0, :west
unit :captive, 672, 0, :west
unit :sludge, 674, 0, :west
unit :sludge, 690, 0, :west
unit :thick_sludge, 698, 0, :west
unit :captive, 699, 0, :west
unit :archer, 702, 0, :west
unit :captive, 705, 0, :west
unit :archer, 707, 0, :west
unit :captive, 710, 0, :west
unit :sludge, 722, 0, :west
unit :captive, 731, 0, :west
unit :wizard, 733, 0, :west
unit :thick_sludge, 746, 0, :west
unit :sludge, 754, 0, :west
unit :captive, 756, 0, :west
unit :thick_sludge, 758, 0, :west
unit :thick_sludge, 763, 0, :west
unit :wizard, 766, 0, :west
unit :archer, 772, 0, :west
unit :archer, 777, 0, :west
unit :sludge, 783, 0, :west
unit :wizard, 787, 0, :west
unit :thick_sludge, 793, 0, :west
unit :thick_sludge, 802, 0, :west
unit :wizard, 805, 0, :west
unit :captive, 818, 0, :west
unit :sludge, 819, 0, :west
unit :captive, 820, 0, :west
unit :wizard, 821, 0, :west
unit :captive, 823, 0, :west
unit :wizard, 827, 0, :west
unit :archer, 830, 0, :west
unit :sludge, 832, 0, :west
unit :thick_sludge, 836, 0, :west
unit :sludge, 844, 0, :west
unit :captive, 847, 0, :west
unit :thick_sludge, 850, 0, :west
unit :sludge, 854, 0, :west
unit :sludge, 855, 0, :west
unit :wizard, 857, 0, :west
unit :sludge, 860, 0, :west
unit :archer, 863, 0, :west
unit :sludge, 865, 0, :west
unit :thick_sludge, 866, 0, :west
unit :archer, 867, 0, :west
unit :sludge, 872, 0, :west
