#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C  s        a    s S >         a S    S       @                S    S  ss       C a          aSs   C    w    s   S s      s    s   s  a  C    w         a s aC  a     aC       a           C      s C         sC s   s  w       s w  S      s Cs      C  w as     w  aS     a  ass   C        S     C        w       C  w    a      C w        S   Caa         s S    C         sa sSaS     S    w  s        C s   S     a  asaS   S  C   wCCaSs  s  sS     w          s           aw CC S C  aC   sa w   w   sS  C   asS  C  aC       aSS w S            a S  C    S         S           S  a S     C        w   s a s             C  C w  CS  sC a     s                s C aSw S    aS aC  s       a    C     s   a      aS  S      w       sS      C    w  S a   C   s      C   CsSw    CS  s a  sw  w       S |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 788
ace_score 3940
size 788, 1
stairs 22, 0

warrior 47, 0, :east

unit :captive, 1, 0, :east
unit :sludge, 4, 0, :east
unit :archer, 13, 0, :east
unit :sludge, 18, 0, :east
unit :thick_sludge, 20, 0, :east
unit :archer, 32, 0, :east
unit :thick_sludge, 34, 0, :east
unit :thick_sludge, 39, 0, :east
unit :thick_sludge, 64, 0, :west
unit :thick_sludge, 69, 0, :west
unit :sludge, 72, 0, :west
unit :sludge, 73, 0, :west
unit :captive, 81, 0, :west
unit :archer, 83, 0, :west
unit :archer, 94, 0, :west
unit :thick_sludge, 95, 0, :west
unit :sludge, 96, 0, :west
unit :captive, 100, 0, :west
unit :wizard, 105, 0, :west
unit :sludge, 110, 0, :west
unit :thick_sludge, 114, 0, :west
unit :sludge, 116, 0, :west
unit :sludge, 123, 0, :west
unit :sludge, 128, 0, :west
unit :sludge, 132, 0, :west
unit :archer, 135, 0, :west
unit :captive, 138, 0, :west
unit :wizard, 143, 0, :west
unit :archer, 153, 0, :west
unit :sludge, 155, 0, :west
unit :archer, 157, 0, :west
unit :captive, 158, 0, :west
unit :archer, 161, 0, :west
unit :archer, 167, 0, :west
unit :captive, 168, 0, :west
unit :archer, 176, 0, :west
unit :captive, 188, 0, :west
unit :sludge, 195, 0, :west
unit :captive, 197, 0, :west
unit :sludge, 207, 0, :west
unit :captive, 208, 0, :west
unit :sludge, 210, 0, :west
unit :sludge, 214, 0, :west
unit :wizard, 217, 0, :west
unit :sludge, 225, 0, :west
unit :wizard, 227, 0, :west
unit :thick_sludge, 230, 0, :west
unit :sludge, 237, 0, :west
unit :captive, 239, 0, :west
unit :sludge, 240, 0, :west
unit :captive, 247, 0, :west
unit :wizard, 250, 0, :west
unit :archer, 252, 0, :west
unit :sludge, 253, 0, :west
unit :wizard, 259, 0, :west
unit :archer, 262, 0, :west
unit :thick_sludge, 263, 0, :west
unit :archer, 269, 0, :west
unit :archer, 272, 0, :west
unit :sludge, 273, 0, :west
unit :sludge, 274, 0, :west
unit :captive, 278, 0, :west
unit :thick_sludge, 287, 0, :west
unit :captive, 293, 0, :west
unit :wizard, 302, 0, :west
unit :captive, 310, 0, :west
unit :wizard, 313, 0, :west
unit :archer, 318, 0, :west
unit :captive, 325, 0, :west
unit :wizard, 327, 0, :west
unit :thick_sludge, 336, 0, :west
unit :captive, 340, 0, :west
unit :archer, 341, 0, :west
unit :archer, 342, 0, :west
unit :sludge, 352, 0, :west
unit :thick_sludge, 354, 0, :west
unit :captive, 359, 0, :west
unit :sludge, 369, 0, :west
unit :archer, 370, 0, :west
unit :sludge, 372, 0, :west
unit :thick_sludge, 373, 0, :west
unit :archer, 374, 0, :west
unit :thick_sludge, 375, 0, :west
unit :thick_sludge, 381, 0, :west
unit :wizard, 386, 0, :west
unit :sludge, 389, 0, :west
unit :captive, 398, 0, :west
unit :sludge, 400, 0, :west
unit :thick_sludge, 404, 0, :west
unit :archer, 410, 0, :west
unit :archer, 413, 0, :west
unit :sludge, 414, 0, :west
unit :archer, 415, 0, :west
unit :thick_sludge, 416, 0, :west
unit :thick_sludge, 420, 0, :west
unit :captive, 423, 0, :west
unit :wizard, 427, 0, :west
unit :captive, 428, 0, :west
unit :captive, 429, 0, :west
unit :archer, 430, 0, :west
unit :thick_sludge, 431, 0, :west
unit :sludge, 432, 0, :west
unit :sludge, 435, 0, :west
unit :sludge, 438, 0, :west
unit :thick_sludge, 439, 0, :west
unit :wizard, 445, 0, :west
unit :sludge, 456, 0, :west
unit :archer, 468, 0, :west
unit :wizard, 469, 0, :west
unit :captive, 471, 0, :west
unit :captive, 472, 0, :west
unit :thick_sludge, 474, 0, :west
unit :captive, 476, 0, :west
unit :archer, 479, 0, :west
unit :captive, 480, 0, :west
unit :sludge, 484, 0, :west
unit :archer, 485, 0, :west
unit :wizard, 487, 0, :west
unit :wizard, 491, 0, :west
unit :sludge, 495, 0, :west
unit :thick_sludge, 496, 0, :west
unit :captive, 499, 0, :west
unit :archer, 503, 0, :west
unit :sludge, 504, 0, :west
unit :thick_sludge, 505, 0, :west
unit :captive, 508, 0, :west
unit :archer, 511, 0, :west
unit :captive, 512, 0, :west
unit :archer, 520, 0, :west
unit :thick_sludge, 521, 0, :west
unit :thick_sludge, 522, 0, :west
unit :wizard, 524, 0, :west
unit :thick_sludge, 526, 0, :west
unit :archer, 539, 0, :west
unit :thick_sludge, 541, 0, :west
unit :captive, 544, 0, :west
unit :thick_sludge, 549, 0, :west
unit :thick_sludge, 559, 0, :west
unit :thick_sludge, 571, 0, :west
unit :archer, 574, 0, :west
unit :thick_sludge, 576, 0, :west
unit :captive, 582, 0, :west
unit :wizard, 591, 0, :west
unit :sludge, 595, 0, :west
unit :archer, 597, 0, :west
unit :sludge, 599, 0, :west
unit :captive, 613, 0, :west
unit :captive, 616, 0, :west
unit :wizard, 618, 0, :west
unit :captive, 621, 0, :west
unit :thick_sludge, 622, 0, :west
unit :sludge, 625, 0, :west
unit :captive, 626, 0, :west
unit :archer, 628, 0, :west
unit :sludge, 634, 0, :west
unit :sludge, 651, 0, :west
unit :captive, 653, 0, :west
unit :archer, 655, 0, :west
unit :thick_sludge, 656, 0, :west
unit :wizard, 657, 0, :west
unit :thick_sludge, 659, 0, :west
unit :archer, 664, 0, :west
unit :thick_sludge, 665, 0, :west
unit :archer, 667, 0, :west
unit :captive, 668, 0, :west
unit :sludge, 671, 0, :west
unit :archer, 679, 0, :west
unit :captive, 684, 0, :west
unit :sludge, 690, 0, :west
unit :archer, 694, 0, :west
unit :archer, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :thick_sludge, 705, 0, :west
unit :wizard, 712, 0, :west
unit :sludge, 720, 0, :west
unit :thick_sludge, 721, 0, :west
unit :captive, 728, 0, :west
unit :wizard, 733, 0, :west
unit :thick_sludge, 736, 0, :west
unit :archer, 738, 0, :west
unit :captive, 742, 0, :west
unit :sludge, 746, 0, :west
unit :captive, 753, 0, :west
unit :captive, 757, 0, :west
unit :sludge, 758, 0, :west
unit :thick_sludge, 759, 0, :west
unit :wizard, 760, 0, :west
unit :captive, 765, 0, :west
unit :thick_sludge, 766, 0, :west
unit :sludge, 769, 0, :west
unit :archer, 771, 0, :west
unit :sludge, 774, 0, :west
unit :wizard, 775, 0, :west
unit :wizard, 778, 0, :west
unit :thick_sludge, 786, 0, :west
