#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w      C  s Sa     CCa C  a    C   w S       CC    a   w    Cs    S s              C    a   SCa        a   s     wCs  a   C     s    CS    a s             w  a       s     sS S  a      C         s  S  C      s      w  C        a a            wS  a      C Sa    S  C  a C      s s    w   S    C         S C aa     w  a        Sa     w  as   s        a    S w w     a  @     S   S a    S Sa     wCsCS    aa       w >C    s   s       C     w   a swS            s Sa s a         S sCw   C w      C      S     s    S C       S   S   w     wC s    a   a   w     w  C  Cw  a    a SC  S S          S a        C      s wa          s  w S    w  Cw    sC  SS        CSas S        Ss      S      C      Cs  w    a   Ss s S        s   s   a  Cw     w  s     a  a   S   a|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 757
ace_score 3785
size 757, 1
stairs 413, 0

warrior 367, 0, :east

unit :wizard, 0, 0, :east
unit :captive, 7, 0, :east
unit :sludge, 10, 0, :east
unit :thick_sludge, 12, 0, :east
unit :archer, 13, 0, :east
unit :captive, 19, 0, :east
unit :captive, 20, 0, :east
unit :archer, 21, 0, :east
unit :captive, 23, 0, :east
unit :archer, 26, 0, :east
unit :captive, 31, 0, :east
unit :wizard, 35, 0, :east
unit :thick_sludge, 37, 0, :east
unit :captive, 45, 0, :east
unit :captive, 46, 0, :east
unit :archer, 51, 0, :east
unit :wizard, 55, 0, :east
unit :captive, 60, 0, :east
unit :sludge, 61, 0, :east
unit :thick_sludge, 66, 0, :east
unit :sludge, 68, 0, :east
unit :captive, 83, 0, :east
unit :archer, 88, 0, :east
unit :thick_sludge, 92, 0, :east
unit :captive, 93, 0, :east
unit :archer, 94, 0, :east
unit :archer, 103, 0, :east
unit :sludge, 107, 0, :east
unit :wizard, 113, 0, :east
unit :captive, 114, 0, :east
unit :sludge, 115, 0, :east
unit :archer, 118, 0, :east
unit :captive, 122, 0, :east
unit :sludge, 128, 0, :east
unit :captive, 133, 0, :east
unit :thick_sludge, 134, 0, :east
unit :archer, 139, 0, :east
unit :sludge, 141, 0, :east
unit :wizard, 155, 0, :east
unit :archer, 158, 0, :east
unit :sludge, 166, 0, :east
unit :sludge, 172, 0, :east
unit :thick_sludge, 173, 0, :east
unit :thick_sludge, 175, 0, :east
unit :archer, 178, 0, :east
unit :captive, 185, 0, :east
unit :sludge, 195, 0, :east
unit :thick_sludge, 198, 0, :east
unit :captive, 201, 0, :east
unit :sludge, 208, 0, :east
unit :wizard, 215, 0, :east
unit :captive, 218, 0, :east
unit :archer, 227, 0, :east
unit :archer, 229, 0, :east
unit :wizard, 242, 0, :east
unit :thick_sludge, 243, 0, :east
unit :archer, 246, 0, :east
unit :captive, 253, 0, :east
unit :thick_sludge, 255, 0, :east
unit :archer, 256, 0, :east
unit :thick_sludge, 261, 0, :east
unit :captive, 264, 0, :east
unit :archer, 267, 0, :east
unit :captive, 269, 0, :east
unit :sludge, 276, 0, :east
unit :sludge, 278, 0, :east
unit :wizard, 283, 0, :east
unit :thick_sludge, 287, 0, :east
unit :captive, 292, 0, :east
unit :thick_sludge, 302, 0, :east
unit :captive, 304, 0, :east
unit :archer, 306, 0, :east
unit :archer, 307, 0, :east
unit :wizard, 313, 0, :east
unit :archer, 316, 0, :east
unit :thick_sludge, 325, 0, :east
unit :archer, 326, 0, :east
unit :wizard, 332, 0, :east
unit :archer, 335, 0, :east
unit :sludge, 336, 0, :east
unit :sludge, 340, 0, :east
unit :archer, 349, 0, :east
unit :thick_sludge, 354, 0, :east
unit :wizard, 356, 0, :east
unit :wizard, 358, 0, :east
unit :archer, 364, 0, :east
unit :thick_sludge, 373, 0, :west
unit :thick_sludge, 377, 0, :west
unit :archer, 379, 0, :west
unit :thick_sludge, 384, 0, :west
unit :thick_sludge, 386, 0, :west
unit :archer, 387, 0, :west
unit :wizard, 393, 0, :west
unit :captive, 394, 0, :west
unit :sludge, 395, 0, :west
unit :captive, 396, 0, :west
unit :thick_sludge, 397, 0, :west
unit :archer, 402, 0, :west
unit :archer, 403, 0, :west
unit :wizard, 411, 0, :west
unit :captive, 414, 0, :west
unit :sludge, 419, 0, :west
unit :sludge, 423, 0, :west
unit :captive, 431, 0, :west
unit :wizard, 437, 0, :west
unit :archer, 441, 0, :west
unit :sludge, 443, 0, :west
unit :wizard, 444, 0, :west
unit :thick_sludge, 445, 0, :west
unit :sludge, 458, 0, :west
unit :thick_sludge, 460, 0, :west
unit :archer, 461, 0, :west
unit :sludge, 463, 0, :west
unit :archer, 465, 0, :west
unit :thick_sludge, 475, 0, :west
unit :sludge, 477, 0, :west
unit :captive, 478, 0, :west
unit :wizard, 479, 0, :west
unit :captive, 483, 0, :west
unit :wizard, 485, 0, :west
unit :captive, 492, 0, :west
unit :thick_sludge, 499, 0, :west
unit :sludge, 505, 0, :west
unit :thick_sludge, 510, 0, :west
unit :captive, 512, 0, :west
unit :thick_sludge, 520, 0, :west
unit :thick_sludge, 524, 0, :west
unit :wizard, 528, 0, :west
unit :wizard, 534, 0, :west
unit :captive, 535, 0, :west
unit :sludge, 537, 0, :west
unit :archer, 542, 0, :west
unit :archer, 546, 0, :west
unit :wizard, 550, 0, :west
unit :wizard, 556, 0, :west
unit :captive, 559, 0, :west
unit :captive, 562, 0, :west
unit :wizard, 563, 0, :west
unit :archer, 566, 0, :west
unit :archer, 571, 0, :west
unit :thick_sludge, 573, 0, :west
unit :captive, 574, 0, :west
unit :thick_sludge, 577, 0, :west
unit :thick_sludge, 579, 0, :west
unit :thick_sludge, 590, 0, :west
unit :archer, 592, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 608, 0, :west
unit :wizard, 610, 0, :west
unit :archer, 611, 0, :west
unit :sludge, 622, 0, :west
unit :wizard, 625, 0, :west
unit :thick_sludge, 627, 0, :west
unit :wizard, 632, 0, :west
unit :captive, 635, 0, :west
unit :wizard, 636, 0, :west
unit :sludge, 641, 0, :west
unit :captive, 642, 0, :west
unit :thick_sludge, 645, 0, :west
unit :thick_sludge, 646, 0, :west
unit :captive, 655, 0, :west
unit :thick_sludge, 656, 0, :west
unit :archer, 657, 0, :west
unit :sludge, 658, 0, :west
unit :thick_sludge, 660, 0, :west
unit :thick_sludge, 669, 0, :west
unit :sludge, 670, 0, :west
unit :thick_sludge, 677, 0, :west
unit :captive, 684, 0, :west
unit :captive, 691, 0, :west
unit :sludge, 692, 0, :west
unit :wizard, 695, 0, :west
unit :archer, 700, 0, :west
unit :thick_sludge, 704, 0, :west
unit :sludge, 705, 0, :west
unit :sludge, 707, 0, :west
unit :thick_sludge, 709, 0, :west
unit :sludge, 718, 0, :west
unit :sludge, 722, 0, :west
unit :archer, 726, 0, :west
unit :captive, 729, 0, :west
unit :wizard, 730, 0, :west
unit :wizard, 736, 0, :west
unit :sludge, 739, 0, :west
unit :archer, 745, 0, :west
unit :archer, 748, 0, :west
unit :thick_sludge, 752, 0, :west
unit :archer, 756, 0, :west
