#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w   Cw sC   C w      C s  sS w            S    a   sa  SC wCSS  w  w w  S  s S        s                       s        C a     s a  a     wS  w    w    w     S     s   s   sa         s  s w S     ss w  s         s   ssS   aw   C              w       w                  @                  a   a              a S w Cs     sw       S w          C SC    w  a  w         a a S  a          C            s        S           a  S   a  C C      w s        CC        ws    w    SS   s      C  C C         C       C a             Cs      s   S  C     S  w  >C    ss     S  S  S  s  S              S  w       C a    S asw a   C s           s s    aCC Cw s  a        S  s w  a          a s Sa       S    sC    SS CSw    s  SCC   s   s        s      ss   a     S w SC      SC w    a a   sS swC  as a  SS SS C     aCC  C a  a  C    a aSa a S     as     sC        Ssa   s  w   s  a    S w         sS a   C Cs |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 894
ace_score 4470
size 894, 1
stairs 547, 0

warrior 269, 0, :east

unit :wizard, 0, 0, :east
unit :captive, 4, 0, :east
unit :wizard, 5, 0, :east
unit :sludge, 7, 0, :east
unit :captive, 8, 0, :east
unit :captive, 12, 0, :east
unit :wizard, 14, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 23, 0, :east
unit :sludge, 26, 0, :east
unit :thick_sludge, 27, 0, :east
unit :wizard, 29, 0, :east
unit :thick_sludge, 42, 0, :east
unit :archer, 47, 0, :east
unit :sludge, 51, 0, :east
unit :archer, 52, 0, :east
unit :thick_sludge, 55, 0, :east
unit :captive, 56, 0, :east
unit :wizard, 58, 0, :east
unit :captive, 59, 0, :east
unit :thick_sludge, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :wizard, 64, 0, :east
unit :wizard, 67, 0, :east
unit :wizard, 69, 0, :east
unit :thick_sludge, 72, 0, :east
unit :sludge, 75, 0, :east
unit :thick_sludge, 77, 0, :east
unit :sludge, 86, 0, :east
unit :sludge, 110, 0, :east
unit :captive, 119, 0, :east
unit :archer, 121, 0, :east
unit :sludge, 127, 0, :east
unit :archer, 129, 0, :east
unit :archer, 132, 0, :east
unit :wizard, 138, 0, :east
unit :thick_sludge, 139, 0, :east
unit :wizard, 142, 0, :east
unit :wizard, 147, 0, :east
unit :wizard, 152, 0, :east
unit :thick_sludge, 158, 0, :east
unit :sludge, 164, 0, :east
unit :sludge, 168, 0, :east
unit :sludge, 172, 0, :east
unit :archer, 173, 0, :east
unit :sludge, 183, 0, :east
unit :sludge, 186, 0, :east
unit :wizard, 188, 0, :east
unit :thick_sludge, 190, 0, :east
unit :sludge, 196, 0, :east
unit :sludge, 197, 0, :east
unit :wizard, 199, 0, :east
unit :sludge, 202, 0, :east
unit :sludge, 212, 0, :east
unit :sludge, 216, 0, :east
unit :sludge, 217, 0, :east
unit :thick_sludge, 218, 0, :east
unit :archer, 222, 0, :east
unit :wizard, 223, 0, :east
unit :captive, 227, 0, :east
unit :wizard, 242, 0, :east
unit :wizard, 250, 0, :east
unit :archer, 288, 0, :west
unit :archer, 292, 0, :west
unit :archer, 307, 0, :west
unit :thick_sludge, 309, 0, :west
unit :wizard, 311, 0, :west
unit :captive, 313, 0, :west
unit :sludge, 314, 0, :west
unit :sludge, 320, 0, :west
unit :wizard, 321, 0, :west
unit :thick_sludge, 329, 0, :west
unit :wizard, 331, 0, :west
unit :captive, 342, 0, :west
unit :thick_sludge, 344, 0, :west
unit :captive, 345, 0, :west
unit :wizard, 350, 0, :west
unit :archer, 353, 0, :west
unit :wizard, 356, 0, :west
unit :archer, 366, 0, :west
unit :archer, 368, 0, :west
unit :thick_sludge, 370, 0, :west
unit :archer, 373, 0, :west
unit :captive, 384, 0, :west
unit :sludge, 397, 0, :west
unit :thick_sludge, 406, 0, :west
unit :archer, 418, 0, :west
unit :thick_sludge, 421, 0, :west
unit :archer, 425, 0, :west
unit :captive, 428, 0, :west
unit :captive, 430, 0, :west
unit :wizard, 437, 0, :west
unit :sludge, 439, 0, :west
unit :captive, 448, 0, :west
unit :captive, 449, 0, :west
unit :wizard, 458, 0, :west
unit :sludge, 459, 0, :west
unit :wizard, 464, 0, :west
unit :thick_sludge, 469, 0, :west
unit :thick_sludge, 470, 0, :west
unit :sludge, 474, 0, :west
unit :captive, 481, 0, :west
unit :captive, 484, 0, :west
unit :captive, 486, 0, :west
unit :captive, 496, 0, :west
unit :captive, 504, 0, :west
unit :archer, 506, 0, :west
unit :captive, 520, 0, :west
unit :sludge, 521, 0, :west
unit :sludge, 528, 0, :west
unit :thick_sludge, 532, 0, :west
unit :captive, 535, 0, :west
unit :thick_sludge, 541, 0, :west
unit :wizard, 544, 0, :west
unit :captive, 548, 0, :west
unit :sludge, 553, 0, :west
unit :sludge, 554, 0, :west
unit :thick_sludge, 560, 0, :west
unit :thick_sludge, 563, 0, :west
unit :thick_sludge, 566, 0, :west
unit :sludge, 569, 0, :west
unit :thick_sludge, 572, 0, :west
unit :thick_sludge, 587, 0, :west
unit :wizard, 590, 0, :west
unit :captive, 598, 0, :west
unit :archer, 600, 0, :west
unit :thick_sludge, 605, 0, :west
unit :archer, 607, 0, :west
unit :sludge, 608, 0, :west
unit :wizard, 609, 0, :west
unit :archer, 611, 0, :west
unit :captive, 615, 0, :west
unit :sludge, 617, 0, :west
unit :sludge, 629, 0, :west
unit :sludge, 631, 0, :west
unit :archer, 636, 0, :west
unit :captive, 637, 0, :west
unit :captive, 638, 0, :west
unit :captive, 640, 0, :west
unit :wizard, 641, 0, :west
unit :sludge, 643, 0, :west
unit :archer, 646, 0, :west
unit :thick_sludge, 655, 0, :west
unit :sludge, 658, 0, :west
unit :wizard, 660, 0, :west
unit :archer, 663, 0, :west
unit :archer, 674, 0, :west
unit :sludge, 676, 0, :west
unit :thick_sludge, 678, 0, :west
unit :archer, 679, 0, :west
unit :thick_sludge, 687, 0, :west
unit :sludge, 692, 0, :west
unit :captive, 693, 0, :west
unit :thick_sludge, 698, 0, :west
unit :thick_sludge, 699, 0, :west
unit :captive, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :wizard, 703, 0, :west
unit :sludge, 708, 0, :west
unit :thick_sludge, 711, 0, :west
unit :captive, 712, 0, :west
unit :captive, 713, 0, :west
unit :sludge, 717, 0, :west
unit :sludge, 721, 0, :west
unit :sludge, 730, 0, :west
unit :sludge, 737, 0, :west
unit :sludge, 738, 0, :west
unit :archer, 742, 0, :west
unit :thick_sludge, 748, 0, :west
unit :wizard, 750, 0, :west
unit :thick_sludge, 752, 0, :west
unit :captive, 753, 0, :west
unit :thick_sludge, 760, 0, :west
unit :captive, 761, 0, :west
unit :wizard, 763, 0, :west
unit :archer, 768, 0, :west
unit :archer, 770, 0, :west
unit :sludge, 774, 0, :west
unit :thick_sludge, 775, 0, :west
unit :sludge, 777, 0, :west
unit :wizard, 778, 0, :west
unit :captive, 779, 0, :west
unit :archer, 782, 0, :west
unit :sludge, 783, 0, :west
unit :archer, 785, 0, :west
unit :thick_sludge, 788, 0, :west
unit :thick_sludge, 789, 0, :west
unit :thick_sludge, 791, 0, :west
unit :thick_sludge, 792, 0, :west
unit :captive, 794, 0, :west
unit :archer, 800, 0, :west
unit :captive, 801, 0, :west
unit :captive, 802, 0, :west
unit :captive, 805, 0, :west
unit :archer, 807, 0, :west
unit :archer, 810, 0, :west
unit :captive, 813, 0, :west
unit :archer, 818, 0, :west
unit :archer, 820, 0, :west
unit :thick_sludge, 821, 0, :west
unit :archer, 822, 0, :west
unit :archer, 824, 0, :west
unit :thick_sludge, 826, 0, :west
unit :archer, 832, 0, :west
unit :sludge, 833, 0, :west
unit :sludge, 839, 0, :west
unit :captive, 840, 0, :west
unit :thick_sludge, 849, 0, :west
unit :sludge, 850, 0, :west
unit :archer, 851, 0, :west
unit :sludge, 855, 0, :west
unit :wizard, 858, 0, :west
unit :sludge, 862, 0, :west
unit :archer, 865, 0, :west
unit :thick_sludge, 870, 0, :west
unit :wizard, 872, 0, :west
unit :sludge, 882, 0, :west
unit :thick_sludge, 883, 0, :west
unit :archer, 885, 0, :west
unit :captive, 889, 0, :west
unit :captive, 891, 0, :west
unit :sludge, 892, 0, :west
