#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w      s C sw      a          as  Ca     w C S     C     as  sCw      C a   S      S S   aa    w  a     Ca s   C     @  a    a          w   sa     s    a  S             C w a >s  a     Ca           S    Cs  sa    C C  C       a        a  C w   w  SSSa aS     S s          a   SS  S    S  C  saS  SwC w w C  S  a           a  a     as  Sw  s       C     s   w   s         Ss   w a   a  S     S      S     S  s       a   w Cw           C  C s   s  s  sC       sa  S             a       C  S SC S    S  aS Sa          s    C CS   C      SCa            a w            a      S       |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 579
ace_score 2895
size 579, 1
stairs 175, 0

warrior 117, 0, :east

unit :wizard, 0, 0, :east
unit :sludge, 7, 0, :east
unit :captive, 9, 0, :east
unit :sludge, 11, 0, :east
unit :wizard, 12, 0, :east
unit :archer, 19, 0, :east
unit :archer, 30, 0, :east
unit :sludge, 31, 0, :east
unit :captive, 34, 0, :east
unit :archer, 35, 0, :east
unit :wizard, 41, 0, :east
unit :captive, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :captive, 51, 0, :east
unit :archer, 57, 0, :east
unit :sludge, 58, 0, :east
unit :sludge, 61, 0, :east
unit :captive, 62, 0, :east
unit :wizard, 63, 0, :east
unit :captive, 70, 0, :east
unit :archer, 72, 0, :east
unit :thick_sludge, 76, 0, :east
unit :thick_sludge, 83, 0, :east
unit :thick_sludge, 85, 0, :east
unit :archer, 89, 0, :east
unit :archer, 90, 0, :east
unit :wizard, 95, 0, :east
unit :archer, 98, 0, :east
unit :captive, 104, 0, :east
unit :archer, 105, 0, :east
unit :sludge, 107, 0, :east
unit :captive, 111, 0, :east
unit :archer, 120, 0, :west
unit :archer, 125, 0, :west
unit :wizard, 136, 0, :west
unit :sludge, 140, 0, :west
unit :archer, 141, 0, :west
unit :sludge, 147, 0, :west
unit :archer, 152, 0, :west
unit :thick_sludge, 155, 0, :west
unit :captive, 169, 0, :west
unit :wizard, 171, 0, :west
unit :archer, 173, 0, :west
unit :sludge, 176, 0, :west
unit :archer, 179, 0, :west
unit :captive, 185, 0, :west
unit :archer, 186, 0, :west
unit :thick_sludge, 198, 0, :west
unit :captive, 203, 0, :west
unit :sludge, 204, 0, :west
unit :sludge, 207, 0, :west
unit :archer, 208, 0, :west
unit :captive, 213, 0, :west
unit :captive, 215, 0, :west
unit :captive, 218, 0, :west
unit :archer, 226, 0, :west
unit :archer, 235, 0, :west
unit :captive, 238, 0, :west
unit :wizard, 240, 0, :west
unit :wizard, 244, 0, :west
unit :thick_sludge, 247, 0, :west
unit :thick_sludge, 248, 0, :west
unit :thick_sludge, 249, 0, :west
unit :archer, 250, 0, :west
unit :archer, 252, 0, :west
unit :thick_sludge, 253, 0, :west
unit :thick_sludge, 259, 0, :west
unit :sludge, 261, 0, :west
unit :archer, 272, 0, :west
unit :thick_sludge, 276, 0, :west
unit :thick_sludge, 277, 0, :west
unit :thick_sludge, 280, 0, :west
unit :thick_sludge, 285, 0, :west
unit :captive, 288, 0, :west
unit :sludge, 291, 0, :west
unit :archer, 292, 0, :west
unit :thick_sludge, 293, 0, :west
unit :thick_sludge, 296, 0, :west
unit :wizard, 297, 0, :west
unit :captive, 298, 0, :west
unit :wizard, 300, 0, :west
unit :wizard, 302, 0, :west
unit :captive, 304, 0, :west
unit :thick_sludge, 307, 0, :west
unit :archer, 310, 0, :west
unit :archer, 322, 0, :west
unit :archer, 325, 0, :west
unit :archer, 331, 0, :west
unit :sludge, 332, 0, :west
unit :thick_sludge, 335, 0, :west
unit :wizard, 336, 0, :west
unit :sludge, 339, 0, :west
unit :captive, 347, 0, :west
unit :sludge, 353, 0, :west
unit :wizard, 357, 0, :west
unit :sludge, 361, 0, :west
unit :thick_sludge, 371, 0, :west
unit :sludge, 372, 0, :west
unit :wizard, 376, 0, :west
unit :archer, 378, 0, :west
unit :archer, 382, 0, :west
unit :thick_sludge, 385, 0, :west
unit :thick_sludge, 391, 0, :west
unit :thick_sludge, 398, 0, :west
unit :thick_sludge, 404, 0, :west
unit :sludge, 407, 0, :west
unit :archer, 415, 0, :west
unit :wizard, 419, 0, :west
unit :captive, 421, 0, :west
unit :wizard, 422, 0, :west
unit :captive, 434, 0, :west
unit :captive, 437, 0, :west
unit :sludge, 439, 0, :west
unit :sludge, 443, 0, :west
unit :sludge, 446, 0, :west
unit :sludge, 449, 0, :west
unit :captive, 450, 0, :west
unit :sludge, 458, 0, :west
unit :archer, 459, 0, :west
unit :thick_sludge, 462, 0, :west
unit :archer, 476, 0, :west
unit :captive, 484, 0, :west
unit :thick_sludge, 487, 0, :west
unit :thick_sludge, 489, 0, :west
unit :captive, 490, 0, :west
unit :thick_sludge, 492, 0, :west
unit :thick_sludge, 497, 0, :west
unit :archer, 500, 0, :west
unit :thick_sludge, 501, 0, :west
unit :thick_sludge, 503, 0, :west
unit :archer, 504, 0, :west
unit :sludge, 515, 0, :west
unit :captive, 520, 0, :west
unit :captive, 522, 0, :west
unit :thick_sludge, 523, 0, :west
unit :captive, 527, 0, :west
unit :thick_sludge, 534, 0, :west
unit :captive, 535, 0, :west
unit :archer, 536, 0, :west
unit :archer, 549, 0, :west
unit :wizard, 551, 0, :west
unit :archer, 564, 0, :west
unit :thick_sludge, 571, 0, :west
