#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w a     C   a      w     a CS a    s w      C w  a   ss    w  w       w w  a      S   w  w    s a       C S C a  C sS  a          s   w    ss        s sa  s   a       C    s C  C   s    Ca S               w   aw  w     s       s  w  w   C       @           aw C   s           C    ws     sw       Ca    s    a                C S      C          C s  a          w   a  s w     a a a ss CCC a C s  S    CC        was   S         C   C S           C       S  wC C  s   s  a w        s aa           Sws     S         wsw        a    w   a   a w  S   w   SCC S  a a C    s  C     as   C   S  s   S S        s S  a  w  a     w S  w                 s sS   S   C    a w w Sw   CC  S    ws          S   s   C    s  C     s aw            w C S      sa sS a       C ws C  > C         S s SsS        S    w       aC aSw     Ss ss s     w S                 w C w   w    S |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 861
ace_score 4305
size 861, 1
stairs 763, 0

warrior 247, 0, :east

unit :wizard, 2, 0, :east
unit :archer, 4, 0, :east
unit :captive, 10, 0, :east
unit :archer, 14, 0, :east
unit :wizard, 21, 0, :east
unit :archer, 27, 0, :east
unit :captive, 29, 0, :east
unit :thick_sludge, 30, 0, :east
unit :archer, 32, 0, :east
unit :sludge, 37, 0, :east
unit :wizard, 39, 0, :east
unit :captive, 46, 0, :east
unit :wizard, 48, 0, :east
unit :archer, 51, 0, :east
unit :sludge, 55, 0, :east
unit :sludge, 56, 0, :east
unit :wizard, 61, 0, :east
unit :wizard, 64, 0, :east
unit :wizard, 72, 0, :east
unit :wizard, 74, 0, :east
unit :archer, 77, 0, :east
unit :thick_sludge, 84, 0, :east
unit :wizard, 88, 0, :east
unit :wizard, 91, 0, :east
unit :sludge, 96, 0, :east
unit :archer, 98, 0, :east
unit :captive, 106, 0, :east
unit :thick_sludge, 108, 0, :east
unit :captive, 110, 0, :east
unit :archer, 112, 0, :east
unit :captive, 115, 0, :east
unit :sludge, 117, 0, :east
unit :thick_sludge, 118, 0, :east
unit :archer, 121, 0, :east
unit :sludge, 132, 0, :east
unit :wizard, 136, 0, :east
unit :sludge, 141, 0, :east
unit :sludge, 142, 0, :east
unit :sludge, 151, 0, :east
unit :sludge, 153, 0, :east
unit :archer, 154, 0, :east
unit :sludge, 157, 0, :east
unit :archer, 161, 0, :east
unit :captive, 169, 0, :east
unit :sludge, 174, 0, :east
unit :captive, 176, 0, :east
unit :captive, 179, 0, :east
unit :sludge, 183, 0, :east
unit :captive, 188, 0, :east
unit :archer, 189, 0, :east
unit :thick_sludge, 191, 0, :east
unit :wizard, 207, 0, :east
unit :archer, 211, 0, :east
unit :wizard, 212, 0, :east
unit :wizard, 215, 0, :east
unit :sludge, 221, 0, :east
unit :sludge, 229, 0, :east
unit :wizard, 232, 0, :east
unit :wizard, 235, 0, :east
unit :captive, 239, 0, :east
unit :archer, 259, 0, :west
unit :wizard, 260, 0, :west
unit :captive, 262, 0, :west
unit :sludge, 266, 0, :west
unit :captive, 278, 0, :west
unit :wizard, 283, 0, :west
unit :sludge, 284, 0, :west
unit :sludge, 290, 0, :west
unit :wizard, 291, 0, :west
unit :captive, 299, 0, :west
unit :archer, 300, 0, :west
unit :sludge, 305, 0, :west
unit :archer, 310, 0, :west
unit :captive, 327, 0, :west
unit :thick_sludge, 329, 0, :west
unit :captive, 336, 0, :west
unit :captive, 347, 0, :west
unit :sludge, 349, 0, :west
unit :archer, 352, 0, :west
unit :wizard, 363, 0, :west
unit :archer, 367, 0, :west
unit :sludge, 370, 0, :west
unit :wizard, 372, 0, :west
unit :archer, 378, 0, :west
unit :archer, 380, 0, :west
unit :archer, 382, 0, :west
unit :sludge, 384, 0, :west
unit :sludge, 385, 0, :west
unit :captive, 387, 0, :west
unit :captive, 388, 0, :west
unit :captive, 389, 0, :west
unit :archer, 391, 0, :west
unit :captive, 393, 0, :west
unit :sludge, 395, 0, :west
unit :thick_sludge, 398, 0, :west
unit :captive, 403, 0, :west
unit :captive, 404, 0, :west
unit :wizard, 413, 0, :west
unit :archer, 414, 0, :west
unit :sludge, 415, 0, :west
unit :thick_sludge, 419, 0, :west
unit :captive, 429, 0, :west
unit :captive, 433, 0, :west
unit :thick_sludge, 435, 0, :west
unit :captive, 447, 0, :west
unit :thick_sludge, 455, 0, :west
unit :wizard, 458, 0, :west
unit :captive, 459, 0, :west
unit :captive, 461, 0, :west
unit :sludge, 464, 0, :west
unit :sludge, 468, 0, :west
unit :archer, 471, 0, :west
unit :wizard, 473, 0, :west
unit :sludge, 482, 0, :west
unit :archer, 484, 0, :west
unit :archer, 485, 0, :west
unit :thick_sludge, 497, 0, :west
unit :wizard, 498, 0, :west
unit :sludge, 499, 0, :west
unit :thick_sludge, 505, 0, :west
unit :wizard, 515, 0, :west
unit :sludge, 516, 0, :west
unit :wizard, 517, 0, :west
unit :archer, 526, 0, :west
unit :wizard, 531, 0, :west
unit :archer, 535, 0, :west
unit :archer, 539, 0, :west
unit :wizard, 541, 0, :west
unit :thick_sludge, 544, 0, :west
unit :wizard, 548, 0, :west
unit :thick_sludge, 552, 0, :west
unit :captive, 553, 0, :west
unit :captive, 554, 0, :west
unit :thick_sludge, 556, 0, :west
unit :archer, 559, 0, :west
unit :archer, 561, 0, :west
unit :captive, 563, 0, :west
unit :sludge, 568, 0, :west
unit :captive, 571, 0, :west
unit :archer, 577, 0, :west
unit :sludge, 578, 0, :west
unit :captive, 582, 0, :west
unit :thick_sludge, 586, 0, :west
unit :sludge, 589, 0, :west
unit :thick_sludge, 593, 0, :west
unit :thick_sludge, 595, 0, :west
unit :sludge, 604, 0, :west
unit :thick_sludge, 606, 0, :west
unit :archer, 609, 0, :west
unit :wizard, 612, 0, :west
unit :archer, 615, 0, :west
unit :wizard, 621, 0, :west
unit :thick_sludge, 623, 0, :west
unit :wizard, 626, 0, :west
unit :sludge, 644, 0, :west
unit :sludge, 646, 0, :west
unit :thick_sludge, 647, 0, :west
unit :thick_sludge, 651, 0, :west
unit :captive, 655, 0, :west
unit :archer, 660, 0, :west
unit :wizard, 662, 0, :west
unit :wizard, 664, 0, :west
unit :thick_sludge, 666, 0, :west
unit :wizard, 667, 0, :west
unit :captive, 671, 0, :west
unit :captive, 672, 0, :west
unit :thick_sludge, 675, 0, :west
unit :wizard, 680, 0, :west
unit :sludge, 681, 0, :west
unit :thick_sludge, 692, 0, :west
unit :sludge, 696, 0, :west
unit :captive, 700, 0, :west
unit :sludge, 705, 0, :west
unit :captive, 708, 0, :west
unit :sludge, 714, 0, :west
unit :archer, 716, 0, :west
unit :wizard, 717, 0, :west
unit :wizard, 730, 0, :west
unit :captive, 732, 0, :west
unit :thick_sludge, 734, 0, :west
unit :sludge, 741, 0, :west
unit :archer, 742, 0, :west
unit :sludge, 744, 0, :west
unit :thick_sludge, 745, 0, :west
unit :archer, 747, 0, :west
unit :captive, 755, 0, :west
unit :wizard, 757, 0, :west
unit :sludge, 758, 0, :west
unit :captive, 760, 0, :west
unit :captive, 765, 0, :west
unit :thick_sludge, 775, 0, :west
unit :sludge, 777, 0, :west
unit :thick_sludge, 779, 0, :west
unit :sludge, 780, 0, :west
unit :thick_sludge, 781, 0, :west
unit :thick_sludge, 790, 0, :west
unit :wizard, 795, 0, :west
unit :archer, 803, 0, :west
unit :captive, 804, 0, :west
unit :archer, 806, 0, :west
unit :thick_sludge, 807, 0, :west
unit :wizard, 808, 0, :west
unit :thick_sludge, 814, 0, :west
unit :sludge, 815, 0, :west
unit :sludge, 817, 0, :west
unit :sludge, 818, 0, :west
unit :sludge, 820, 0, :west
unit :wizard, 826, 0, :west
unit :thick_sludge, 828, 0, :west
unit :wizard, 846, 0, :west
unit :captive, 848, 0, :west
unit :wizard, 850, 0, :west
unit :wizard, 854, 0, :west
unit :thick_sludge, 859, 0, :west
