#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | aw  Sa     C S            a s C w   C ss        a a  C    C      S  @  a   C C  C       s     S C C   w               w     aCS    wa    sa  SS     aC  s       C S     S C   S    s s    SS  S       a s     S   aC  Ss a             w S  CS    a w  C      >sa a s     a   C s C  a  a  S  C w     w     S       S    S    w w wS   Ca     s         a         SC   a   Cs S    C   C    S     CSw a  C s    w     a   C CsS  s                 w    s wsS s       S a  C     s aSS        s   w    S   w            s      w           S    aas C S  CS s a  w s       a      S      w   C        w   S    s    ss  wS       s              C       C S   |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 639
ace_score 3195
size 639, 1
stairs 255, 0

warrior 69, 0, :east

unit :archer, 1, 0, :east
unit :wizard, 2, 0, :east
unit :thick_sludge, 5, 0, :east
unit :archer, 6, 0, :east
unit :captive, 12, 0, :east
unit :thick_sludge, 14, 0, :east
unit :archer, 27, 0, :east
unit :sludge, 29, 0, :east
unit :captive, 31, 0, :east
unit :wizard, 33, 0, :east
unit :captive, 37, 0, :east
unit :sludge, 39, 0, :east
unit :sludge, 40, 0, :east
unit :archer, 49, 0, :east
unit :archer, 51, 0, :east
unit :captive, 54, 0, :east
unit :captive, 59, 0, :east
unit :thick_sludge, 66, 0, :east
unit :archer, 72, 0, :west
unit :captive, 76, 0, :west
unit :captive, 78, 0, :west
unit :captive, 81, 0, :west
unit :sludge, 89, 0, :west
unit :thick_sludge, 95, 0, :west
unit :captive, 97, 0, :west
unit :captive, 99, 0, :west
unit :wizard, 103, 0, :west
unit :wizard, 119, 0, :west
unit :archer, 125, 0, :west
unit :captive, 126, 0, :west
unit :thick_sludge, 127, 0, :west
unit :wizard, 132, 0, :west
unit :archer, 133, 0, :west
unit :sludge, 138, 0, :west
unit :archer, 139, 0, :west
unit :thick_sludge, 142, 0, :west
unit :thick_sludge, 143, 0, :west
unit :archer, 149, 0, :west
unit :captive, 150, 0, :west
unit :sludge, 153, 0, :west
unit :captive, 161, 0, :west
unit :thick_sludge, 163, 0, :west
unit :thick_sludge, 169, 0, :west
unit :captive, 171, 0, :west
unit :thick_sludge, 175, 0, :west
unit :sludge, 180, 0, :west
unit :sludge, 182, 0, :west
unit :thick_sludge, 187, 0, :west
unit :thick_sludge, 188, 0, :west
unit :thick_sludge, 191, 0, :west
unit :archer, 199, 0, :west
unit :sludge, 201, 0, :west
unit :thick_sludge, 207, 0, :west
unit :archer, 211, 0, :west
unit :captive, 212, 0, :west
unit :thick_sludge, 215, 0, :west
unit :sludge, 216, 0, :west
unit :archer, 218, 0, :west
unit :wizard, 232, 0, :west
unit :thick_sludge, 234, 0, :west
unit :captive, 237, 0, :west
unit :thick_sludge, 238, 0, :west
unit :archer, 243, 0, :west
unit :wizard, 245, 0, :west
unit :captive, 248, 0, :west
unit :sludge, 256, 0, :west
unit :archer, 257, 0, :west
unit :archer, 259, 0, :west
unit :sludge, 261, 0, :west
unit :archer, 267, 0, :west
unit :captive, 271, 0, :west
unit :sludge, 273, 0, :west
unit :captive, 275, 0, :west
unit :archer, 278, 0, :west
unit :archer, 281, 0, :west
unit :thick_sludge, 284, 0, :west
unit :captive, 287, 0, :west
unit :wizard, 289, 0, :west
unit :wizard, 295, 0, :west
unit :thick_sludge, 301, 0, :west
unit :thick_sludge, 309, 0, :west
unit :thick_sludge, 314, 0, :west
unit :wizard, 319, 0, :west
unit :wizard, 321, 0, :west
unit :wizard, 323, 0, :west
unit :thick_sludge, 324, 0, :west
unit :captive, 328, 0, :west
unit :archer, 329, 0, :west
unit :sludge, 335, 0, :west
unit :archer, 345, 0, :west
unit :thick_sludge, 355, 0, :west
unit :captive, 356, 0, :west
unit :archer, 360, 0, :west
unit :captive, 364, 0, :west
unit :sludge, 365, 0, :west
unit :thick_sludge, 367, 0, :west
unit :captive, 372, 0, :west
unit :captive, 376, 0, :west
unit :thick_sludge, 381, 0, :west
unit :captive, 387, 0, :west
unit :thick_sludge, 388, 0, :west
unit :wizard, 389, 0, :west
unit :archer, 391, 0, :west
unit :captive, 394, 0, :west
unit :sludge, 396, 0, :west
unit :wizard, 401, 0, :west
unit :archer, 407, 0, :west
unit :captive, 411, 0, :west
unit :captive, 413, 0, :west
unit :sludge, 414, 0, :west
unit :thick_sludge, 415, 0, :west
unit :sludge, 418, 0, :west
unit :wizard, 436, 0, :west
unit :sludge, 441, 0, :west
unit :wizard, 443, 0, :west
unit :sludge, 444, 0, :west
unit :thick_sludge, 445, 0, :west
unit :sludge, 447, 0, :west
unit :thick_sludge, 455, 0, :west
unit :archer, 457, 0, :west
unit :captive, 460, 0, :west
unit :sludge, 466, 0, :west
unit :archer, 468, 0, :west
unit :thick_sludge, 469, 0, :west
unit :thick_sludge, 470, 0, :west
unit :sludge, 479, 0, :west
unit :wizard, 483, 0, :west
unit :thick_sludge, 488, 0, :west
unit :wizard, 492, 0, :west
unit :sludge, 505, 0, :west
unit :wizard, 512, 0, :west
unit :thick_sludge, 524, 0, :west
unit :archer, 529, 0, :west
unit :archer, 530, 0, :west
unit :sludge, 531, 0, :west
unit :captive, 533, 0, :west
unit :thick_sludge, 535, 0, :west
unit :captive, 538, 0, :west
unit :thick_sludge, 539, 0, :west
unit :sludge, 541, 0, :west
unit :archer, 543, 0, :west
unit :wizard, 546, 0, :west
unit :sludge, 548, 0, :west
unit :archer, 556, 0, :west
unit :thick_sludge, 563, 0, :west
unit :wizard, 570, 0, :west
unit :captive, 574, 0, :west
unit :wizard, 583, 0, :west
unit :thick_sludge, 587, 0, :west
unit :sludge, 592, 0, :west
unit :sludge, 597, 0, :west
unit :sludge, 598, 0, :west
unit :wizard, 601, 0, :west
unit :thick_sludge, 602, 0, :west
unit :sludge, 610, 0, :west
unit :captive, 625, 0, :west
unit :captive, 633, 0, :west
unit :thick_sludge, 635, 0, :west
