#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S w s  SCs  s a  asa   a asS awC s aa      s a  s  sw a    a     S  s                   s  w  as Cs w          C  C     w  s  w      Ss  w  S  C  ws  wC   w C       S      a         w         w    @     a w s S  S  a  s  C        C     C               s   a  w S   C C    w    w    w  SC      S s       C a  S    C   s       C  S  s            S    a  C   S   a  C  aa   S        C  C  S   s  S a   S        a s  w           s     S  w  w          s     S  w  ass     SC a       w  s w   a C CC           CC    aC  S         S     C  Sa s   s w        S w         C          sC C >s a          S w   w C C  s   Sw w a   w S a    C   s  C      S  s        w  Ss     a     s S            S  w         C    w      wC C  w  S        SS    C     w|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 743
ace_score 3715
size 743, 1
stairs 581, 0

warrior 198, 0, :east

unit :thick_sludge, 1, 0, :east
unit :wizard, 3, 0, :east
unit :sludge, 5, 0, :east
unit :thick_sludge, 8, 0, :east
unit :captive, 9, 0, :east
unit :sludge, 10, 0, :east
unit :sludge, 13, 0, :east
unit :archer, 15, 0, :east
unit :archer, 18, 0, :east
unit :sludge, 19, 0, :east
unit :archer, 20, 0, :east
unit :archer, 24, 0, :east
unit :archer, 26, 0, :east
unit :sludge, 27, 0, :east
unit :thick_sludge, 28, 0, :east
unit :archer, 30, 0, :east
unit :wizard, 31, 0, :east
unit :captive, 32, 0, :east
unit :sludge, 34, 0, :east
unit :archer, 36, 0, :east
unit :archer, 37, 0, :east
unit :sludge, 44, 0, :east
unit :archer, 46, 0, :east
unit :sludge, 49, 0, :east
unit :sludge, 52, 0, :east
unit :wizard, 53, 0, :east
unit :archer, 55, 0, :east
unit :archer, 60, 0, :east
unit :thick_sludge, 66, 0, :east
unit :sludge, 69, 0, :east
unit :sludge, 89, 0, :east
unit :wizard, 92, 0, :east
unit :archer, 95, 0, :east
unit :sludge, 96, 0, :east
unit :captive, 98, 0, :east
unit :sludge, 99, 0, :east
unit :wizard, 101, 0, :east
unit :captive, 112, 0, :east
unit :captive, 115, 0, :east
unit :wizard, 121, 0, :east
unit :sludge, 124, 0, :east
unit :wizard, 127, 0, :east
unit :thick_sludge, 134, 0, :east
unit :sludge, 135, 0, :east
unit :wizard, 138, 0, :east
unit :thick_sludge, 141, 0, :east
unit :captive, 144, 0, :east
unit :wizard, 147, 0, :east
unit :sludge, 148, 0, :east
unit :wizard, 151, 0, :east
unit :captive, 152, 0, :east
unit :wizard, 156, 0, :east
unit :captive, 158, 0, :east
unit :thick_sludge, 166, 0, :east
unit :archer, 173, 0, :east
unit :wizard, 183, 0, :east
unit :wizard, 193, 0, :east
unit :archer, 204, 0, :west
unit :wizard, 206, 0, :west
unit :sludge, 208, 0, :west
unit :thick_sludge, 210, 0, :west
unit :thick_sludge, 213, 0, :west
unit :archer, 216, 0, :west
unit :sludge, 219, 0, :west
unit :captive, 222, 0, :west
unit :captive, 231, 0, :west
unit :captive, 237, 0, :west
unit :sludge, 253, 0, :west
unit :archer, 257, 0, :west
unit :wizard, 260, 0, :west
unit :thick_sludge, 262, 0, :west
unit :captive, 266, 0, :west
unit :captive, 268, 0, :west
unit :wizard, 273, 0, :west
unit :wizard, 278, 0, :west
unit :wizard, 283, 0, :west
unit :thick_sludge, 286, 0, :west
unit :captive, 287, 0, :west
unit :thick_sludge, 294, 0, :west
unit :sludge, 296, 0, :west
unit :captive, 304, 0, :west
unit :archer, 306, 0, :west
unit :thick_sludge, 309, 0, :west
unit :captive, 314, 0, :west
unit :sludge, 318, 0, :west
unit :captive, 326, 0, :west
unit :thick_sludge, 329, 0, :west
unit :sludge, 332, 0, :west
unit :thick_sludge, 345, 0, :west
unit :archer, 350, 0, :west
unit :captive, 353, 0, :west
unit :thick_sludge, 357, 0, :west
unit :archer, 361, 0, :west
unit :captive, 364, 0, :west
unit :archer, 367, 0, :west
unit :archer, 368, 0, :west
unit :thick_sludge, 372, 0, :west
unit :captive, 381, 0, :west
unit :captive, 384, 0, :west
unit :thick_sludge, 387, 0, :west
unit :sludge, 391, 0, :west
unit :thick_sludge, 394, 0, :west
unit :archer, 396, 0, :west
unit :thick_sludge, 400, 0, :west
unit :archer, 409, 0, :west
unit :sludge, 411, 0, :west
unit :wizard, 414, 0, :west
unit :sludge, 426, 0, :west
unit :thick_sludge, 432, 0, :west
unit :wizard, 435, 0, :west
unit :wizard, 438, 0, :west
unit :sludge, 449, 0, :west
unit :thick_sludge, 455, 0, :west
unit :wizard, 458, 0, :west
unit :archer, 461, 0, :west
unit :sludge, 462, 0, :west
unit :sludge, 463, 0, :west
unit :thick_sludge, 469, 0, :west
unit :captive, 470, 0, :west
unit :archer, 472, 0, :west
unit :wizard, 480, 0, :west
unit :sludge, 483, 0, :west
unit :wizard, 485, 0, :west
unit :archer, 489, 0, :west
unit :captive, 491, 0, :west
unit :captive, 493, 0, :west
unit :captive, 494, 0, :west
unit :captive, 506, 0, :west
unit :captive, 507, 0, :west
unit :archer, 512, 0, :west
unit :captive, 513, 0, :west
unit :thick_sludge, 516, 0, :west
unit :thick_sludge, 526, 0, :west
unit :captive, 532, 0, :west
unit :thick_sludge, 535, 0, :west
unit :archer, 536, 0, :west
unit :sludge, 538, 0, :west
unit :sludge, 542, 0, :west
unit :wizard, 544, 0, :west
unit :thick_sludge, 553, 0, :west
unit :wizard, 555, 0, :west
unit :captive, 565, 0, :west
unit :sludge, 576, 0, :west
unit :captive, 577, 0, :west
unit :captive, 579, 0, :west
unit :sludge, 582, 0, :west
unit :archer, 584, 0, :west
unit :thick_sludge, 595, 0, :west
unit :wizard, 597, 0, :west
unit :wizard, 601, 0, :west
unit :captive, 603, 0, :west
unit :captive, 605, 0, :west
unit :sludge, 608, 0, :west
unit :thick_sludge, 612, 0, :west
unit :wizard, 613, 0, :west
unit :wizard, 615, 0, :west
unit :archer, 617, 0, :west
unit :wizard, 621, 0, :west
unit :thick_sludge, 623, 0, :west
unit :archer, 625, 0, :west
unit :captive, 630, 0, :west
unit :sludge, 634, 0, :west
unit :captive, 637, 0, :west
unit :thick_sludge, 644, 0, :west
unit :sludge, 647, 0, :west
unit :wizard, 656, 0, :west
unit :thick_sludge, 659, 0, :west
unit :sludge, 660, 0, :west
unit :archer, 666, 0, :west
unit :sludge, 672, 0, :west
unit :thick_sludge, 674, 0, :west
unit :thick_sludge, 687, 0, :west
unit :wizard, 690, 0, :west
unit :captive, 700, 0, :west
unit :wizard, 705, 0, :west
unit :wizard, 712, 0, :west
unit :captive, 713, 0, :west
unit :captive, 715, 0, :west
unit :wizard, 718, 0, :west
unit :thick_sludge, 721, 0, :west
unit :thick_sludge, 730, 0, :west
unit :thick_sludge, 731, 0, :west
unit :captive, 736, 0, :west
unit :wizard, 742, 0, :west
