#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     S   CS     S    aS  Ss          ss   a  w    C   s         w C   swS           a s ss        S  s  w    aa      sa     C        a   C  s  a S S    s           s aw C     aCa        s       s   S    a C    C   S >   S  S    @  ss       a w  sw  a    Cw w         S   w          Cs ss    S   sC       Ss      w   s S   S s  s   C    a  C        ws aC w C Ss     s    s      CCS     C                 aa       sC   S  S      s s  w       w     w  a  w           Ca    s a    sS       w s   w          a   CS   C         Ss aas  S      sC    S   a a   s C  ssSs  C         a    C        S  SCw   |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 597
ace_score 2985
size 597, 1
stairs 216, 0

warrior 228, 0, :east

unit :thick_sludge, 5, 0, :east
unit :captive, 9, 0, :east
unit :thick_sludge, 10, 0, :east
unit :thick_sludge, 16, 0, :east
unit :archer, 21, 0, :east
unit :thick_sludge, 22, 0, :east
unit :thick_sludge, 25, 0, :east
unit :sludge, 26, 0, :east
unit :sludge, 37, 0, :east
unit :sludge, 38, 0, :east
unit :archer, 42, 0, :east
unit :wizard, 45, 0, :east
unit :captive, 50, 0, :east
unit :sludge, 54, 0, :east
unit :wizard, 64, 0, :east
unit :captive, 66, 0, :east
unit :sludge, 70, 0, :east
unit :wizard, 71, 0, :east
unit :thick_sludge, 72, 0, :east
unit :archer, 84, 0, :east
unit :sludge, 86, 0, :east
unit :sludge, 88, 0, :east
unit :sludge, 89, 0, :east
unit :thick_sludge, 98, 0, :east
unit :sludge, 101, 0, :east
unit :wizard, 104, 0, :east
unit :archer, 109, 0, :east
unit :archer, 110, 0, :east
unit :sludge, 117, 0, :east
unit :archer, 118, 0, :east
unit :captive, 124, 0, :east
unit :archer, 133, 0, :east
unit :captive, 137, 0, :east
unit :sludge, 140, 0, :east
unit :archer, 143, 0, :east
unit :thick_sludge, 145, 0, :east
unit :thick_sludge, 147, 0, :east
unit :sludge, 152, 0, :east
unit :sludge, 164, 0, :east
unit :archer, 166, 0, :east
unit :wizard, 167, 0, :east
unit :captive, 169, 0, :east
unit :archer, 175, 0, :east
unit :captive, 176, 0, :east
unit :archer, 177, 0, :east
unit :sludge, 186, 0, :east
unit :sludge, 194, 0, :east
unit :thick_sludge, 198, 0, :east
unit :archer, 203, 0, :east
unit :captive, 205, 0, :east
unit :captive, 210, 0, :east
unit :thick_sludge, 214, 0, :east
unit :thick_sludge, 220, 0, :east
unit :thick_sludge, 223, 0, :east
unit :sludge, 231, 0, :west
unit :sludge, 232, 0, :west
unit :archer, 240, 0, :west
unit :wizard, 242, 0, :west
unit :sludge, 245, 0, :west
unit :wizard, 246, 0, :west
unit :archer, 249, 0, :west
unit :captive, 254, 0, :west
unit :wizard, 255, 0, :west
unit :wizard, 257, 0, :west
unit :thick_sludge, 267, 0, :west
unit :wizard, 271, 0, :west
unit :captive, 282, 0, :west
unit :sludge, 283, 0, :west
unit :sludge, 285, 0, :west
unit :sludge, 286, 0, :west
unit :thick_sludge, 291, 0, :west
unit :sludge, 295, 0, :west
unit :captive, 296, 0, :west
unit :thick_sludge, 304, 0, :west
unit :sludge, 305, 0, :west
unit :wizard, 312, 0, :west
unit :sludge, 316, 0, :west
unit :thick_sludge, 318, 0, :west
unit :thick_sludge, 322, 0, :west
unit :sludge, 324, 0, :west
unit :sludge, 327, 0, :west
unit :captive, 331, 0, :west
unit :archer, 336, 0, :west
unit :captive, 339, 0, :west
unit :wizard, 348, 0, :west
unit :sludge, 349, 0, :west
unit :archer, 351, 0, :west
unit :captive, 352, 0, :west
unit :wizard, 354, 0, :west
unit :captive, 356, 0, :west
unit :thick_sludge, 358, 0, :west
unit :sludge, 359, 0, :west
unit :sludge, 365, 0, :west
unit :sludge, 370, 0, :west
unit :captive, 377, 0, :west
unit :captive, 378, 0, :west
unit :thick_sludge, 379, 0, :west
unit :captive, 385, 0, :west
unit :archer, 403, 0, :west
unit :archer, 404, 0, :west
unit :sludge, 412, 0, :west
unit :captive, 413, 0, :west
unit :thick_sludge, 417, 0, :west
unit :thick_sludge, 420, 0, :west
unit :sludge, 427, 0, :west
unit :sludge, 429, 0, :west
unit :wizard, 432, 0, :west
unit :wizard, 440, 0, :west
unit :wizard, 446, 0, :west
unit :archer, 449, 0, :west
unit :wizard, 452, 0, :west
unit :captive, 464, 0, :west
unit :archer, 465, 0, :west
unit :sludge, 470, 0, :west
unit :archer, 472, 0, :west
unit :sludge, 477, 0, :west
unit :thick_sludge, 478, 0, :west
unit :wizard, 486, 0, :west
unit :sludge, 488, 0, :west
unit :wizard, 492, 0, :west
unit :archer, 503, 0, :west
unit :captive, 507, 0, :west
unit :thick_sludge, 508, 0, :west
unit :captive, 512, 0, :west
unit :thick_sludge, 522, 0, :west
unit :sludge, 523, 0, :west
unit :archer, 525, 0, :west
unit :archer, 526, 0, :west
unit :sludge, 527, 0, :west
unit :thick_sludge, 530, 0, :west
unit :sludge, 537, 0, :west
unit :captive, 538, 0, :west
unit :thick_sludge, 543, 0, :west
unit :archer, 547, 0, :west
unit :archer, 549, 0, :west
unit :sludge, 553, 0, :west
unit :captive, 555, 0, :west
unit :sludge, 558, 0, :west
unit :sludge, 559, 0, :west
unit :thick_sludge, 560, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 564, 0, :west
unit :archer, 574, 0, :west
unit :captive, 579, 0, :west
unit :thick_sludge, 588, 0, :west
unit :thick_sludge, 591, 0, :west
unit :captive, 592, 0, :west
unit :wizard, 593, 0, :west
