#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  CSaS   C S  a a      w       a  C    S    w s             w       a       w   S   S     wa              S  wS   @         aC    w     S           C w  C   w  C w  S     a Ss  a              s           S   w           w a   wCS a    S    a s   a   sS     >               w   s          wS       a     S S   Cs w  s    w ss  C a a w             a  C    SC   S  CC             S    s         s     S          a SC     sC Ca C     w  s S   sS     sS  aCw   S    Cs      s a   w  S      C          a  C w   S  C      C  ss   SS       S   C a  w C S w    Sa               a       SS w    w        C C w     wa  S   S w  w       a   a s  S     S w    s    s   w    aa        aw s             Ca sa       w  S s a  Csw    s    s as sC      w  s C       ss    wC  a a w    w CaC      Ca    as  C      a  C       s    S w      CwS              s aC  Ss     C  w      sw  C  s  aw     C w ss S  aaa S     a  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 900
ace_score 4500
size 900, 1
stairs 257, 0

warrior 114, 0, :east

unit :captive, 2, 0, :east
unit :thick_sludge, 3, 0, :east
unit :archer, 4, 0, :east
unit :thick_sludge, 5, 0, :east
unit :captive, 9, 0, :east
unit :thick_sludge, 11, 0, :east
unit :archer, 14, 0, :east
unit :archer, 16, 0, :east
unit :wizard, 23, 0, :east
unit :archer, 31, 0, :east
unit :captive, 34, 0, :east
unit :thick_sludge, 39, 0, :east
unit :wizard, 44, 0, :east
unit :sludge, 46, 0, :east
unit :wizard, 60, 0, :east
unit :archer, 68, 0, :east
unit :wizard, 76, 0, :east
unit :thick_sludge, 80, 0, :east
unit :thick_sludge, 84, 0, :east
unit :wizard, 90, 0, :east
unit :archer, 91, 0, :east
unit :thick_sludge, 106, 0, :east
unit :wizard, 109, 0, :east
unit :thick_sludge, 110, 0, :east
unit :archer, 124, 0, :west
unit :captive, 125, 0, :west
unit :wizard, 130, 0, :west
unit :thick_sludge, 136, 0, :west
unit :captive, 148, 0, :west
unit :wizard, 150, 0, :west
unit :captive, 153, 0, :west
unit :wizard, 157, 0, :west
unit :captive, 160, 0, :west
unit :wizard, 162, 0, :west
unit :thick_sludge, 165, 0, :west
unit :archer, 171, 0, :west
unit :thick_sludge, 173, 0, :west
unit :sludge, 174, 0, :west
unit :archer, 177, 0, :west
unit :sludge, 192, 0, :west
unit :thick_sludge, 204, 0, :west
unit :wizard, 208, 0, :west
unit :wizard, 220, 0, :west
unit :archer, 222, 0, :west
unit :wizard, 226, 0, :west
unit :captive, 227, 0, :west
unit :thick_sludge, 228, 0, :west
unit :archer, 230, 0, :west
unit :thick_sludge, 235, 0, :west
unit :archer, 240, 0, :west
unit :sludge, 242, 0, :west
unit :archer, 246, 0, :west
unit :sludge, 250, 0, :west
unit :thick_sludge, 251, 0, :west
unit :wizard, 273, 0, :west
unit :sludge, 277, 0, :west
unit :wizard, 288, 0, :west
unit :thick_sludge, 289, 0, :west
unit :archer, 297, 0, :west
unit :thick_sludge, 303, 0, :west
unit :thick_sludge, 305, 0, :west
unit :captive, 309, 0, :west
unit :sludge, 310, 0, :west
unit :wizard, 312, 0, :west
unit :sludge, 315, 0, :west
unit :wizard, 320, 0, :west
unit :sludge, 322, 0, :west
unit :sludge, 323, 0, :west
unit :captive, 326, 0, :west
unit :archer, 328, 0, :west
unit :archer, 330, 0, :west
unit :wizard, 332, 0, :west
unit :archer, 346, 0, :west
unit :captive, 349, 0, :west
unit :thick_sludge, 354, 0, :west
unit :captive, 355, 0, :west
unit :thick_sludge, 359, 0, :west
unit :captive, 362, 0, :west
unit :captive, 363, 0, :west
unit :thick_sludge, 377, 0, :west
unit :sludge, 382, 0, :west
unit :sludge, 392, 0, :west
unit :thick_sludge, 398, 0, :west
unit :archer, 409, 0, :west
unit :thick_sludge, 411, 0, :west
unit :captive, 412, 0, :west
unit :sludge, 418, 0, :west
unit :captive, 419, 0, :west
unit :captive, 421, 0, :west
unit :archer, 422, 0, :west
unit :captive, 424, 0, :west
unit :wizard, 430, 0, :west
unit :sludge, 433, 0, :west
unit :thick_sludge, 435, 0, :west
unit :sludge, 439, 0, :west
unit :thick_sludge, 440, 0, :west
unit :sludge, 446, 0, :west
unit :thick_sludge, 447, 0, :west
unit :archer, 450, 0, :west
unit :captive, 451, 0, :west
unit :wizard, 452, 0, :west
unit :thick_sludge, 456, 0, :west
unit :captive, 461, 0, :west
unit :sludge, 462, 0, :west
unit :sludge, 469, 0, :west
unit :archer, 471, 0, :west
unit :wizard, 475, 0, :west
unit :thick_sludge, 478, 0, :west
unit :captive, 485, 0, :west
unit :archer, 496, 0, :west
unit :captive, 499, 0, :west
unit :wizard, 501, 0, :west
unit :thick_sludge, 505, 0, :west
unit :captive, 508, 0, :west
unit :captive, 515, 0, :west
unit :sludge, 518, 0, :west
unit :sludge, 519, 0, :west
unit :thick_sludge, 523, 0, :west
unit :thick_sludge, 524, 0, :west
unit :thick_sludge, 532, 0, :west
unit :captive, 536, 0, :west
unit :archer, 538, 0, :west
unit :wizard, 541, 0, :west
unit :captive, 543, 0, :west
unit :thick_sludge, 545, 0, :west
unit :wizard, 547, 0, :west
unit :thick_sludge, 552, 0, :west
unit :archer, 553, 0, :west
unit :archer, 569, 0, :west
unit :thick_sludge, 577, 0, :west
unit :thick_sludge, 578, 0, :west
unit :wizard, 580, 0, :west
unit :wizard, 585, 0, :west
unit :captive, 594, 0, :west
unit :captive, 596, 0, :west
unit :wizard, 598, 0, :west
unit :wizard, 604, 0, :west
unit :archer, 605, 0, :west
unit :thick_sludge, 608, 0, :west
unit :thick_sludge, 612, 0, :west
unit :wizard, 614, 0, :west
unit :wizard, 617, 0, :west
unit :archer, 625, 0, :west
unit :archer, 629, 0, :west
unit :sludge, 631, 0, :west
unit :thick_sludge, 634, 0, :west
unit :thick_sludge, 640, 0, :west
unit :wizard, 642, 0, :west
unit :sludge, 647, 0, :west
unit :sludge, 652, 0, :west
unit :wizard, 656, 0, :west
unit :archer, 661, 0, :west
unit :archer, 662, 0, :west
unit :archer, 671, 0, :west
unit :wizard, 672, 0, :west
unit :sludge, 674, 0, :west
unit :captive, 688, 0, :west
unit :archer, 689, 0, :west
unit :sludge, 691, 0, :west
unit :archer, 692, 0, :west
unit :wizard, 700, 0, :west
unit :thick_sludge, 703, 0, :west
unit :sludge, 705, 0, :west
unit :archer, 707, 0, :west
unit :captive, 710, 0, :west
unit :sludge, 711, 0, :west
unit :wizard, 712, 0, :west
unit :sludge, 717, 0, :west
unit :sludge, 722, 0, :west
unit :archer, 724, 0, :west
unit :sludge, 725, 0, :west
unit :sludge, 727, 0, :west
unit :captive, 728, 0, :west
unit :wizard, 735, 0, :west
unit :sludge, 738, 0, :west
unit :captive, 740, 0, :west
unit :sludge, 748, 0, :west
unit :sludge, 749, 0, :west
unit :wizard, 754, 0, :west
unit :captive, 755, 0, :west
unit :archer, 758, 0, :west
unit :archer, 760, 0, :west
unit :wizard, 762, 0, :west
unit :wizard, 767, 0, :west
unit :captive, 769, 0, :west
unit :archer, 770, 0, :west
unit :captive, 771, 0, :west
unit :captive, 778, 0, :west
unit :archer, 779, 0, :west
unit :archer, 784, 0, :west
unit :sludge, 785, 0, :west
unit :captive, 788, 0, :west
unit :archer, 795, 0, :west
unit :captive, 798, 0, :west
unit :sludge, 806, 0, :west
unit :thick_sludge, 811, 0, :west
unit :wizard, 813, 0, :west
unit :captive, 820, 0, :west
unit :wizard, 821, 0, :west
unit :thick_sludge, 822, 0, :west
unit :sludge, 837, 0, :west
unit :archer, 839, 0, :west
unit :captive, 840, 0, :west
unit :thick_sludge, 843, 0, :west
unit :sludge, 844, 0, :west
unit :captive, 850, 0, :west
unit :wizard, 853, 0, :west
unit :sludge, 860, 0, :west
unit :wizard, 861, 0, :west
unit :captive, 864, 0, :west
unit :sludge, 867, 0, :west
unit :archer, 870, 0, :west
unit :wizard, 871, 0, :west
unit :captive, 877, 0, :west
unit :wizard, 879, 0, :west
unit :sludge, 881, 0, :west
unit :sludge, 882, 0, :west
unit :thick_sludge, 884, 0, :west
unit :archer, 887, 0, :west
unit :archer, 888, 0, :west
unit :archer, 889, 0, :west
unit :thick_sludge, 891, 0, :west
unit :archer, 897, 0, :west
