#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | aS  a Ss a   asS s       C   s aa   sS s S  w S    CSS   SC s   >wC      a    w         s    sa   S   s a     swS w    C     a   as   a   s     S                w   S       a     a w    w    a     C   C Ss   s w     S  aS      C w   a  CS   s   C w         a   S    s    s     a              w            S      S   S    S C S  S   ss w    s  @    a S w  s a    S CC        w      C                   s       Sw  s   C  aCSC s  S s sC        a       s  a a      w       a            sC   SC                            S w   Sa        w    C C   C    ass                as  s    a C  SS  C      aC SS   s    a w     S   a  a    S  w    w  s    w   S  C C w  w       a    sa  w s  s S     C         C    s  CS Cs C a  w      C  w  C  w aa  C    a   C     s  w     |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 763
ace_score 3815
size 763, 1
stairs 65, 0

warrior 344, 0, :east

unit :archer, 1, 0, :east
unit :thick_sludge, 2, 0, :east
unit :archer, 5, 0, :east
unit :thick_sludge, 7, 0, :east
unit :sludge, 8, 0, :east
unit :archer, 10, 0, :east
unit :archer, 14, 0, :east
unit :sludge, 15, 0, :east
unit :thick_sludge, 16, 0, :east
unit :sludge, 18, 0, :east
unit :captive, 26, 0, :east
unit :sludge, 30, 0, :east
unit :archer, 32, 0, :east
unit :archer, 33, 0, :east
unit :sludge, 37, 0, :east
unit :thick_sludge, 38, 0, :east
unit :sludge, 40, 0, :east
unit :thick_sludge, 42, 0, :east
unit :wizard, 45, 0, :east
unit :thick_sludge, 47, 0, :east
unit :captive, 52, 0, :east
unit :thick_sludge, 53, 0, :east
unit :thick_sludge, 54, 0, :east
unit :thick_sludge, 58, 0, :east
unit :captive, 59, 0, :east
unit :sludge, 61, 0, :east
unit :wizard, 66, 0, :east
unit :captive, 67, 0, :east
unit :archer, 74, 0, :east
unit :wizard, 79, 0, :east
unit :sludge, 89, 0, :east
unit :sludge, 94, 0, :east
unit :archer, 95, 0, :east
unit :thick_sludge, 99, 0, :east
unit :sludge, 103, 0, :east
unit :archer, 105, 0, :east
unit :sludge, 111, 0, :east
unit :wizard, 112, 0, :east
unit :thick_sludge, 113, 0, :east
unit :wizard, 115, 0, :east
unit :captive, 120, 0, :east
unit :archer, 126, 0, :east
unit :archer, 130, 0, :east
unit :sludge, 131, 0, :east
unit :archer, 135, 0, :east
unit :sludge, 139, 0, :east
unit :thick_sludge, 145, 0, :east
unit :wizard, 162, 0, :east
unit :thick_sludge, 166, 0, :east
unit :archer, 174, 0, :east
unit :archer, 180, 0, :east
unit :wizard, 182, 0, :east
unit :wizard, 187, 0, :east
unit :archer, 192, 0, :east
unit :captive, 198, 0, :east
unit :captive, 202, 0, :east
unit :thick_sludge, 204, 0, :east
unit :sludge, 205, 0, :east
unit :sludge, 209, 0, :east
unit :wizard, 211, 0, :east
unit :thick_sludge, 217, 0, :east
unit :archer, 220, 0, :east
unit :thick_sludge, 221, 0, :east
unit :captive, 228, 0, :east
unit :wizard, 230, 0, :east
unit :archer, 234, 0, :east
unit :captive, 237, 0, :east
unit :thick_sludge, 238, 0, :east
unit :sludge, 242, 0, :east
unit :captive, 246, 0, :east
unit :wizard, 248, 0, :east
unit :archer, 258, 0, :east
unit :thick_sludge, 262, 0, :east
unit :sludge, 267, 0, :east
unit :sludge, 272, 0, :east
unit :archer, 278, 0, :east
unit :wizard, 293, 0, :east
unit :thick_sludge, 306, 0, :east
unit :thick_sludge, 313, 0, :east
unit :thick_sludge, 317, 0, :east
unit :thick_sludge, 322, 0, :east
unit :captive, 324, 0, :east
unit :thick_sludge, 326, 0, :east
unit :thick_sludge, 329, 0, :east
unit :sludge, 333, 0, :east
unit :sludge, 334, 0, :east
unit :wizard, 336, 0, :east
unit :sludge, 341, 0, :east
unit :archer, 349, 0, :west
unit :thick_sludge, 351, 0, :west
unit :wizard, 353, 0, :west
unit :sludge, 356, 0, :west
unit :archer, 358, 0, :west
unit :thick_sludge, 363, 0, :west
unit :captive, 365, 0, :west
unit :captive, 366, 0, :west
unit :wizard, 375, 0, :west
unit :captive, 382, 0, :west
unit :sludge, 402, 0, :west
unit :thick_sludge, 410, 0, :west
unit :wizard, 411, 0, :west
unit :sludge, 414, 0, :west
unit :captive, 418, 0, :west
unit :archer, 421, 0, :west
unit :captive, 422, 0, :west
unit :thick_sludge, 423, 0, :west
unit :captive, 424, 0, :west
unit :sludge, 426, 0, :west
unit :thick_sludge, 429, 0, :west
unit :sludge, 431, 0, :west
unit :sludge, 433, 0, :west
unit :captive, 434, 0, :west
unit :archer, 443, 0, :west
unit :sludge, 451, 0, :west
unit :archer, 454, 0, :west
unit :archer, 456, 0, :west
unit :wizard, 463, 0, :west
unit :archer, 471, 0, :west
unit :sludge, 484, 0, :west
unit :captive, 485, 0, :west
unit :thick_sludge, 489, 0, :west
unit :captive, 490, 0, :west
unit :thick_sludge, 519, 0, :west
unit :wizard, 521, 0, :west
unit :thick_sludge, 525, 0, :west
unit :archer, 526, 0, :west
unit :wizard, 535, 0, :west
unit :captive, 540, 0, :west
unit :captive, 542, 0, :west
unit :captive, 546, 0, :west
unit :archer, 551, 0, :west
unit :sludge, 552, 0, :west
unit :sludge, 553, 0, :west
unit :archer, 570, 0, :west
unit :sludge, 571, 0, :west
unit :sludge, 574, 0, :west
unit :archer, 579, 0, :west
unit :captive, 581, 0, :west
unit :thick_sludge, 584, 0, :west
unit :thick_sludge, 585, 0, :west
unit :captive, 588, 0, :west
unit :archer, 595, 0, :west
unit :captive, 596, 0, :west
unit :thick_sludge, 598, 0, :west
unit :thick_sludge, 599, 0, :west
unit :sludge, 603, 0, :west
unit :archer, 608, 0, :west
unit :wizard, 610, 0, :west
unit :thick_sludge, 616, 0, :west
unit :archer, 620, 0, :west
unit :archer, 623, 0, :west
unit :thick_sludge, 628, 0, :west
unit :wizard, 631, 0, :west
unit :wizard, 636, 0, :west
unit :sludge, 639, 0, :west
unit :wizard, 644, 0, :west
unit :thick_sludge, 648, 0, :west
unit :captive, 651, 0, :west
unit :captive, 653, 0, :west
unit :wizard, 655, 0, :west
unit :wizard, 658, 0, :west
unit :archer, 666, 0, :west
unit :sludge, 671, 0, :west
unit :archer, 672, 0, :west
unit :wizard, 675, 0, :west
unit :sludge, 677, 0, :west
unit :sludge, 680, 0, :west
unit :thick_sludge, 682, 0, :west
unit :captive, 688, 0, :west
unit :captive, 698, 0, :west
unit :sludge, 703, 0, :west
unit :captive, 706, 0, :west
unit :thick_sludge, 707, 0, :west
unit :captive, 709, 0, :west
unit :sludge, 710, 0, :west
unit :captive, 712, 0, :west
unit :archer, 714, 0, :west
unit :wizard, 717, 0, :west
unit :captive, 724, 0, :west
unit :wizard, 727, 0, :west
unit :captive, 730, 0, :west
unit :wizard, 733, 0, :west
unit :archer, 735, 0, :west
unit :archer, 736, 0, :west
unit :captive, 739, 0, :west
unit :archer, 744, 0, :west
unit :captive, 748, 0, :west
unit :sludge, 754, 0, :west
unit :wizard, 757, 0, :west
