#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C C      S   S      S  w s a    CS            w   wC   C   SCa a    w   a s SC a  w  C    wa C   S C      C  s Cw w   w         s a       w                     S  a            C  ss   CS    C              a      w         C  C   C  SS   CC  s s   C       s Cw    sCa      C      S  a    a  s   S     w          w  wS    s  w     s   a   a      wa     w     S a  s  w      a  a  w     s    s  CS w s            a C    s  aCs  s       s  s      Sa s   C   s      wC    Cs    w  s    w            C        w a       CC  S    w  wC   w   sS   Ca  C  w>             w s C   w     w    S  w    SwSa sC   s       s  C       S    s a S   C  ws  a    a a          a      a   a w SC saC         Ca  a  S      SS C     s     s     a    w  w  CsS S  C  a a      @  C  a  w   w      a  a as aCw  C aS   a SC                    w       sC            |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 837
ace_score 4185
size 837, 1
stairs 548, 0

warrior 751, 0, :east

unit :captive, 1, 0, :east
unit :captive, 3, 0, :east
unit :thick_sludge, 10, 0, :east
unit :thick_sludge, 14, 0, :east
unit :thick_sludge, 21, 0, :east
unit :wizard, 24, 0, :east
unit :sludge, 26, 0, :east
unit :archer, 28, 0, :east
unit :captive, 33, 0, :east
unit :thick_sludge, 34, 0, :east
unit :wizard, 47, 0, :east
unit :wizard, 51, 0, :east
unit :captive, 52, 0, :east
unit :captive, 56, 0, :east
unit :thick_sludge, 60, 0, :east
unit :captive, 61, 0, :east
unit :archer, 62, 0, :east
unit :archer, 64, 0, :east
unit :wizard, 69, 0, :east
unit :archer, 73, 0, :east
unit :sludge, 75, 0, :east
unit :thick_sludge, 77, 0, :east
unit :captive, 78, 0, :east
unit :archer, 80, 0, :east
unit :wizard, 83, 0, :east
unit :captive, 86, 0, :east
unit :wizard, 91, 0, :east
unit :archer, 92, 0, :east
unit :captive, 94, 0, :east
unit :thick_sludge, 98, 0, :east
unit :captive, 100, 0, :east
unit :captive, 107, 0, :east
unit :sludge, 110, 0, :east
unit :captive, 112, 0, :east
unit :wizard, 113, 0, :east
unit :wizard, 115, 0, :east
unit :wizard, 119, 0, :east
unit :sludge, 129, 0, :east
unit :archer, 131, 0, :east
unit :wizard, 139, 0, :east
unit :thick_sludge, 161, 0, :east
unit :archer, 164, 0, :east
unit :captive, 177, 0, :east
unit :sludge, 180, 0, :east
unit :sludge, 181, 0, :east
unit :captive, 185, 0, :east
unit :thick_sludge, 186, 0, :east
unit :captive, 191, 0, :east
unit :archer, 206, 0, :east
unit :wizard, 213, 0, :east
unit :captive, 223, 0, :east
unit :captive, 226, 0, :east
unit :captive, 230, 0, :east
unit :thick_sludge, 233, 0, :east
unit :thick_sludge, 234, 0, :east
unit :captive, 238, 0, :east
unit :captive, 239, 0, :east
unit :sludge, 242, 0, :east
unit :sludge, 244, 0, :east
unit :captive, 248, 0, :east
unit :sludge, 256, 0, :east
unit :captive, 258, 0, :east
unit :wizard, 259, 0, :east
unit :sludge, 264, 0, :east
unit :captive, 265, 0, :east
unit :archer, 266, 0, :east
unit :captive, 273, 0, :east
unit :thick_sludge, 280, 0, :east
unit :archer, 283, 0, :east
unit :archer, 288, 0, :east
unit :sludge, 291, 0, :east
unit :thick_sludge, 295, 0, :east
unit :wizard, 301, 0, :east
unit :wizard, 312, 0, :east
unit :wizard, 315, 0, :east
unit :thick_sludge, 316, 0, :east
unit :sludge, 321, 0, :east
unit :wizard, 324, 0, :east
unit :sludge, 330, 0, :east
unit :archer, 334, 0, :east
unit :archer, 338, 0, :east
unit :wizard, 345, 0, :east
unit :archer, 346, 0, :east
unit :wizard, 352, 0, :east
unit :thick_sludge, 358, 0, :east
unit :archer, 360, 0, :east
unit :sludge, 363, 0, :east
unit :wizard, 366, 0, :east
unit :archer, 373, 0, :east
unit :archer, 376, 0, :east
unit :wizard, 379, 0, :east
unit :sludge, 385, 0, :east
unit :sludge, 390, 0, :east
unit :captive, 393, 0, :east
unit :thick_sludge, 394, 0, :east
unit :wizard, 396, 0, :east
unit :sludge, 398, 0, :east
unit :archer, 411, 0, :east
unit :captive, 413, 0, :east
unit :sludge, 418, 0, :east
unit :archer, 421, 0, :east
unit :captive, 422, 0, :east
unit :sludge, 423, 0, :east
unit :sludge, 426, 0, :east
unit :sludge, 434, 0, :east
unit :sludge, 437, 0, :east
unit :thick_sludge, 444, 0, :east
unit :archer, 445, 0, :east
unit :sludge, 447, 0, :east
unit :captive, 451, 0, :east
unit :sludge, 455, 0, :east
unit :wizard, 462, 0, :east
unit :captive, 463, 0, :east
unit :captive, 468, 0, :east
unit :sludge, 469, 0, :east
unit :wizard, 474, 0, :east
unit :sludge, 477, 0, :east
unit :wizard, 482, 0, :east
unit :captive, 495, 0, :east
unit :wizard, 504, 0, :east
unit :archer, 506, 0, :east
unit :captive, 514, 0, :east
unit :captive, 515, 0, :east
unit :thick_sludge, 518, 0, :east
unit :wizard, 523, 0, :east
unit :wizard, 526, 0, :east
unit :captive, 527, 0, :east
unit :wizard, 531, 0, :east
unit :sludge, 535, 0, :east
unit :thick_sludge, 536, 0, :east
unit :captive, 540, 0, :east
unit :archer, 541, 0, :east
unit :captive, 544, 0, :east
unit :wizard, 547, 0, :east
unit :wizard, 562, 0, :east
unit :sludge, 564, 0, :east
unit :captive, 566, 0, :east
unit :wizard, 570, 0, :east
unit :wizard, 576, 0, :east
unit :thick_sludge, 581, 0, :east
unit :wizard, 584, 0, :east
unit :thick_sludge, 589, 0, :east
unit :wizard, 590, 0, :east
unit :thick_sludge, 591, 0, :east
unit :archer, 592, 0, :east
unit :sludge, 594, 0, :east
unit :captive, 595, 0, :east
unit :sludge, 599, 0, :east
unit :sludge, 607, 0, :east
unit :captive, 610, 0, :east
unit :thick_sludge, 618, 0, :east
unit :sludge, 623, 0, :east
unit :archer, 625, 0, :east
unit :thick_sludge, 627, 0, :east
unit :captive, 631, 0, :east
unit :wizard, 634, 0, :east
unit :sludge, 635, 0, :east
unit :archer, 638, 0, :east
unit :archer, 643, 0, :east
unit :archer, 645, 0, :east
unit :archer, 656, 0, :east
unit :archer, 663, 0, :east
unit :archer, 667, 0, :east
unit :wizard, 669, 0, :east
unit :thick_sludge, 671, 0, :east
unit :captive, 672, 0, :east
unit :sludge, 674, 0, :east
unit :archer, 675, 0, :east
unit :captive, 676, 0, :east
unit :captive, 686, 0, :east
unit :archer, 687, 0, :east
unit :archer, 690, 0, :east
unit :thick_sludge, 693, 0, :east
unit :thick_sludge, 700, 0, :east
unit :thick_sludge, 701, 0, :east
unit :captive, 703, 0, :east
unit :sludge, 709, 0, :east
unit :sludge, 715, 0, :east
unit :archer, 721, 0, :east
unit :wizard, 726, 0, :east
unit :wizard, 729, 0, :east
unit :captive, 732, 0, :east
unit :sludge, 733, 0, :east
unit :thick_sludge, 734, 0, :east
unit :thick_sludge, 736, 0, :east
unit :captive, 739, 0, :east
unit :archer, 742, 0, :east
unit :archer, 744, 0, :east
unit :captive, 754, 0, :west
unit :archer, 757, 0, :west
unit :wizard, 760, 0, :west
unit :wizard, 764, 0, :west
unit :archer, 771, 0, :west
unit :archer, 774, 0, :west
unit :archer, 776, 0, :west
unit :sludge, 777, 0, :west
unit :archer, 779, 0, :west
unit :captive, 780, 0, :west
unit :wizard, 781, 0, :west
unit :captive, 784, 0, :west
unit :archer, 786, 0, :west
unit :thick_sludge, 787, 0, :west
unit :archer, 791, 0, :west
unit :thick_sludge, 793, 0, :west
unit :captive, 794, 0, :west
unit :wizard, 815, 0, :west
unit :sludge, 823, 0, :west
unit :captive, 824, 0, :west
