#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       ws      a    CS              w                s a     aSw  aCs           S  w Sw     a w          S  w   w     ws    S      a w   CS  C a      C         ss   >wCa s      C       a  w s Ca   aC     a  @    w w   S S           S   s    s as    a   Ca a  a s        C        a           s  s s wS C  SCa S        w  as     Ss s  a s  ss    s Cs w    S  s   w  wC a    Cw        a s              w  a     s  a a Csw       w C a C  a   a w        a aaw    C C wC  a       aS    sa   a       C       wa   S      s a             C         w           s S     S aCC      S   s    a        a   w  w   S       CS |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 610
ace_score 3050
size 610, 1
stairs 165, 0

warrior 207, 0, :east

unit :wizard, 7, 0, :east
unit :sludge, 8, 0, :east
unit :archer, 15, 0, :east
unit :captive, 20, 0, :east
unit :thick_sludge, 21, 0, :east
unit :wizard, 36, 0, :east
unit :sludge, 53, 0, :east
unit :archer, 55, 0, :east
unit :archer, 61, 0, :east
unit :thick_sludge, 62, 0, :east
unit :wizard, 63, 0, :east
unit :archer, 66, 0, :east
unit :captive, 67, 0, :east
unit :sludge, 68, 0, :east
unit :thick_sludge, 80, 0, :east
unit :wizard, 83, 0, :east
unit :thick_sludge, 85, 0, :east
unit :wizard, 86, 0, :east
unit :archer, 92, 0, :east
unit :wizard, 94, 0, :east
unit :thick_sludge, 105, 0, :east
unit :wizard, 108, 0, :east
unit :wizard, 112, 0, :east
unit :wizard, 118, 0, :east
unit :sludge, 119, 0, :east
unit :thick_sludge, 124, 0, :east
unit :archer, 131, 0, :east
unit :wizard, 133, 0, :east
unit :captive, 137, 0, :east
unit :thick_sludge, 138, 0, :east
unit :captive, 141, 0, :east
unit :archer, 143, 0, :east
unit :captive, 150, 0, :east
unit :sludge, 160, 0, :east
unit :sludge, 161, 0, :east
unit :wizard, 166, 0, :east
unit :captive, 167, 0, :east
unit :archer, 168, 0, :east
unit :sludge, 170, 0, :east
unit :captive, 177, 0, :east
unit :archer, 185, 0, :east
unit :wizard, 188, 0, :east
unit :sludge, 190, 0, :east
unit :captive, 192, 0, :east
unit :archer, 193, 0, :east
unit :archer, 197, 0, :east
unit :captive, 198, 0, :east
unit :archer, 204, 0, :east
unit :wizard, 212, 0, :west
unit :wizard, 214, 0, :west
unit :thick_sludge, 218, 0, :west
unit :thick_sludge, 220, 0, :west
unit :thick_sludge, 232, 0, :west
unit :sludge, 236, 0, :west
unit :sludge, 241, 0, :west
unit :archer, 243, 0, :west
unit :sludge, 244, 0, :west
unit :archer, 249, 0, :west
unit :captive, 253, 0, :west
unit :archer, 254, 0, :west
unit :archer, 256, 0, :west
unit :archer, 259, 0, :west
unit :sludge, 261, 0, :west
unit :captive, 270, 0, :west
unit :archer, 279, 0, :west
unit :sludge, 291, 0, :west
unit :sludge, 294, 0, :west
unit :sludge, 296, 0, :west
unit :wizard, 298, 0, :west
unit :thick_sludge, 299, 0, :west
unit :captive, 301, 0, :west
unit :thick_sludge, 304, 0, :west
unit :captive, 305, 0, :west
unit :archer, 306, 0, :west
unit :thick_sludge, 308, 0, :west
unit :wizard, 317, 0, :west
unit :archer, 320, 0, :west
unit :sludge, 321, 0, :west
unit :thick_sludge, 327, 0, :west
unit :sludge, 328, 0, :west
unit :sludge, 330, 0, :west
unit :archer, 333, 0, :west
unit :sludge, 335, 0, :west
unit :sludge, 338, 0, :west
unit :sludge, 339, 0, :west
unit :sludge, 344, 0, :west
unit :captive, 346, 0, :west
unit :sludge, 347, 0, :west
unit :wizard, 349, 0, :west
unit :thick_sludge, 354, 0, :west
unit :sludge, 357, 0, :west
unit :wizard, 361, 0, :west
unit :wizard, 364, 0, :west
unit :captive, 365, 0, :west
unit :archer, 367, 0, :west
unit :captive, 372, 0, :west
unit :wizard, 373, 0, :west
unit :archer, 382, 0, :west
unit :sludge, 384, 0, :west
unit :wizard, 399, 0, :west
unit :archer, 402, 0, :west
unit :sludge, 408, 0, :west
unit :archer, 411, 0, :west
unit :archer, 413, 0, :west
unit :captive, 415, 0, :west
unit :sludge, 416, 0, :west
unit :wizard, 417, 0, :west
unit :wizard, 425, 0, :west
unit :captive, 427, 0, :west
unit :archer, 429, 0, :west
unit :captive, 431, 0, :west
unit :archer, 434, 0, :west
unit :archer, 438, 0, :west
unit :wizard, 440, 0, :west
unit :archer, 449, 0, :west
unit :archer, 451, 0, :west
unit :archer, 452, 0, :west
unit :wizard, 453, 0, :west
unit :captive, 458, 0, :west
unit :captive, 460, 0, :west
unit :wizard, 462, 0, :west
unit :captive, 463, 0, :west
unit :archer, 466, 0, :west
unit :archer, 474, 0, :west
unit :thick_sludge, 475, 0, :west
unit :sludge, 480, 0, :west
unit :archer, 481, 0, :west
unit :archer, 485, 0, :west
unit :captive, 493, 0, :west
unit :wizard, 501, 0, :west
unit :archer, 502, 0, :west
unit :thick_sludge, 506, 0, :west
unit :sludge, 513, 0, :west
unit :archer, 515, 0, :west
unit :captive, 529, 0, :west
unit :wizard, 539, 0, :west
unit :sludge, 551, 0, :west
unit :thick_sludge, 553, 0, :west
unit :thick_sludge, 559, 0, :west
unit :archer, 561, 0, :west
unit :captive, 562, 0, :west
unit :captive, 563, 0, :west
unit :thick_sludge, 570, 0, :west
unit :sludge, 574, 0, :west
unit :archer, 579, 0, :west
unit :archer, 588, 0, :west
unit :wizard, 592, 0, :west
unit :wizard, 595, 0, :west
unit :thick_sludge, 599, 0, :west
unit :captive, 607, 0, :west
unit :thick_sludge, 608, 0, :west
