#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |sS as     a   sw     as a   s         SC               s  sw        C Ca           w    w   S       as      s   a  s sSw   sS  aa           ws    s  s SS w        C                  S      SSsC    s  C  S C           s   Cs   S      w   as a S      C      a    C aC w  sCCa       a   S  C       s a      S         s            aC w s        S      wa     C  sC     C as  C    S   s aC  a    a    s   C  aC s  S  C    C  C                         >   a            a a  wC w  C        Sw     aC S             s    S S a    CS a Ss     C Caa C     SC w  w          C    w w  a  a   s w          sSw s   a    aws s  w w    Ss   s   C    a aS                   C  S  w    C   w   s  S    @    w         S w C  C w   s  S ss    C     SwC  w    s       C   a    s     wSC  C  w  S     |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 778
ace_score 3890
size 778, 1
stairs 446, 0

warrior 683, 0, :east

unit :sludge, 0, 0, :east
unit :thick_sludge, 1, 0, :east
unit :archer, 3, 0, :east
unit :sludge, 4, 0, :east
unit :archer, 10, 0, :east
unit :sludge, 14, 0, :east
unit :wizard, 15, 0, :east
unit :archer, 21, 0, :east
unit :sludge, 22, 0, :east
unit :archer, 24, 0, :east
unit :sludge, 28, 0, :east
unit :thick_sludge, 38, 0, :east
unit :captive, 39, 0, :east
unit :sludge, 55, 0, :east
unit :sludge, 58, 0, :east
unit :wizard, 59, 0, :east
unit :captive, 68, 0, :east
unit :captive, 70, 0, :east
unit :archer, 71, 0, :east
unit :wizard, 83, 0, :east
unit :wizard, 88, 0, :east
unit :thick_sludge, 92, 0, :east
unit :archer, 100, 0, :east
unit :sludge, 101, 0, :east
unit :sludge, 108, 0, :east
unit :archer, 112, 0, :east
unit :sludge, 115, 0, :east
unit :sludge, 117, 0, :east
unit :thick_sludge, 118, 0, :east
unit :wizard, 119, 0, :east
unit :sludge, 123, 0, :east
unit :thick_sludge, 124, 0, :east
unit :archer, 127, 0, :east
unit :archer, 128, 0, :east
unit :wizard, 140, 0, :east
unit :sludge, 141, 0, :east
unit :sludge, 146, 0, :east
unit :sludge, 149, 0, :east
unit :thick_sludge, 151, 0, :east
unit :thick_sludge, 152, 0, :east
unit :wizard, 154, 0, :east
unit :captive, 163, 0, :east
unit :thick_sludge, 182, 0, :east
unit :thick_sludge, 189, 0, :east
unit :thick_sludge, 190, 0, :east
unit :sludge, 191, 0, :east
unit :captive, 192, 0, :east
unit :sludge, 197, 0, :east
unit :captive, 200, 0, :east
unit :thick_sludge, 203, 0, :east
unit :captive, 205, 0, :east
unit :sludge, 217, 0, :east
unit :captive, 221, 0, :east
unit :sludge, 222, 0, :east
unit :thick_sludge, 226, 0, :east
unit :wizard, 233, 0, :east
unit :archer, 237, 0, :east
unit :sludge, 238, 0, :east
unit :archer, 240, 0, :east
unit :thick_sludge, 242, 0, :east
unit :captive, 249, 0, :east
unit :archer, 256, 0, :east
unit :captive, 261, 0, :east
unit :archer, 263, 0, :east
unit :captive, 264, 0, :east
unit :wizard, 266, 0, :east
unit :sludge, 269, 0, :east
unit :captive, 270, 0, :east
unit :captive, 271, 0, :east
unit :archer, 272, 0, :east
unit :archer, 280, 0, :east
unit :thick_sludge, 284, 0, :east
unit :captive, 287, 0, :east
unit :sludge, 295, 0, :east
unit :archer, 297, 0, :east
unit :thick_sludge, 304, 0, :east
unit :sludge, 314, 0, :east
unit :archer, 327, 0, :east
unit :captive, 328, 0, :east
unit :wizard, 330, 0, :east
unit :sludge, 332, 0, :east
unit :thick_sludge, 341, 0, :east
unit :wizard, 348, 0, :east
unit :archer, 349, 0, :east
unit :captive, 355, 0, :east
unit :sludge, 358, 0, :east
unit :captive, 359, 0, :east
unit :captive, 365, 0, :east
unit :archer, 367, 0, :east
unit :sludge, 368, 0, :east
unit :captive, 371, 0, :east
unit :thick_sludge, 376, 0, :east
unit :sludge, 380, 0, :east
unit :archer, 382, 0, :east
unit :captive, 383, 0, :east
unit :archer, 386, 0, :east
unit :archer, 391, 0, :east
unit :sludge, 396, 0, :east
unit :captive, 400, 0, :east
unit :archer, 403, 0, :east
unit :captive, 404, 0, :east
unit :sludge, 406, 0, :east
unit :thick_sludge, 409, 0, :east
unit :captive, 412, 0, :east
unit :captive, 417, 0, :east
unit :captive, 420, 0, :east
unit :archer, 450, 0, :east
unit :archer, 463, 0, :east
unit :archer, 465, 0, :east
unit :wizard, 468, 0, :east
unit :captive, 469, 0, :east
unit :wizard, 471, 0, :east
unit :captive, 474, 0, :east
unit :thick_sludge, 483, 0, :east
unit :wizard, 484, 0, :east
unit :archer, 490, 0, :east
unit :captive, 491, 0, :east
unit :thick_sludge, 493, 0, :east
unit :sludge, 507, 0, :east
unit :thick_sludge, 512, 0, :east
unit :thick_sludge, 514, 0, :east
unit :archer, 516, 0, :east
unit :captive, 521, 0, :east
unit :thick_sludge, 522, 0, :east
unit :archer, 524, 0, :east
unit :thick_sludge, 526, 0, :east
unit :sludge, 527, 0, :east
unit :captive, 533, 0, :east
unit :captive, 535, 0, :east
unit :archer, 536, 0, :east
unit :archer, 537, 0, :east
unit :captive, 539, 0, :east
unit :thick_sludge, 545, 0, :east
unit :captive, 546, 0, :east
unit :wizard, 548, 0, :east
unit :wizard, 551, 0, :east
unit :captive, 562, 0, :east
unit :wizard, 567, 0, :east
unit :wizard, 569, 0, :east
unit :archer, 572, 0, :east
unit :archer, 575, 0, :east
unit :sludge, 579, 0, :east
unit :wizard, 581, 0, :east
unit :sludge, 592, 0, :east
unit :thick_sludge, 593, 0, :east
unit :wizard, 594, 0, :east
unit :sludge, 596, 0, :east
unit :archer, 600, 0, :east
unit :archer, 605, 0, :east
unit :wizard, 606, 0, :east
unit :sludge, 607, 0, :east
unit :sludge, 609, 0, :east
unit :wizard, 612, 0, :east
unit :wizard, 614, 0, :east
unit :thick_sludge, 619, 0, :east
unit :sludge, 620, 0, :east
unit :sludge, 624, 0, :east
unit :captive, 628, 0, :east
unit :archer, 633, 0, :east
unit :archer, 635, 0, :east
unit :thick_sludge, 636, 0, :east
unit :captive, 656, 0, :east
unit :thick_sludge, 659, 0, :east
unit :wizard, 662, 0, :east
unit :captive, 667, 0, :east
unit :wizard, 671, 0, :east
unit :sludge, 675, 0, :east
unit :thick_sludge, 678, 0, :east
unit :wizard, 688, 0, :west
unit :thick_sludge, 698, 0, :west
unit :wizard, 700, 0, :west
unit :captive, 702, 0, :west
unit :captive, 705, 0, :west
unit :wizard, 707, 0, :west
unit :sludge, 711, 0, :west
unit :thick_sludge, 714, 0, :west
unit :sludge, 716, 0, :west
unit :sludge, 717, 0, :west
unit :captive, 722, 0, :west
unit :thick_sludge, 728, 0, :west
unit :wizard, 729, 0, :west
unit :captive, 730, 0, :west
unit :wizard, 733, 0, :west
unit :sludge, 738, 0, :west
unit :captive, 746, 0, :west
unit :archer, 750, 0, :west
unit :sludge, 755, 0, :west
unit :wizard, 761, 0, :west
unit :thick_sludge, 762, 0, :west
unit :captive, 763, 0, :west
unit :captive, 766, 0, :west
unit :wizard, 769, 0, :west
unit :thick_sludge, 772, 0, :west
