#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |CSC      C S         s   S S         a  s        w  Sw     s        s s  w  S   a  w Cs             a  w   a    s S      aSC CCSS  s      C a    C w  CC sa  w  a  a   a S    s        w s        w C s C  aS a   C   S       s            a   w   Sw   a    @  S   aS C    Sa         C      S   S    w    w w      w C w C S            w           a               a   w S  C  s       a   S s       a       >  a    C S   C a aa SSwa     s      C SC a s   s       S  C            aw     C S S w        S  C   s      w     C wss     C        a     a  S C  SCs    wa    ss      a  S a     s   C  sC C    sS  a     CC   ssCs    S     S             s  a  S  C     Sa    s wa    C             C        s   s s |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 697
ace_score 3485
size 697, 1
stairs 400, 0

warrior 253, 0, :east

unit :captive, 0, 0, :east
unit :thick_sludge, 1, 0, :east
unit :captive, 2, 0, :east
unit :captive, 9, 0, :east
unit :thick_sludge, 11, 0, :east
unit :sludge, 21, 0, :east
unit :thick_sludge, 25, 0, :east
unit :thick_sludge, 27, 0, :east
unit :archer, 37, 0, :east
unit :sludge, 40, 0, :east
unit :wizard, 49, 0, :east
unit :thick_sludge, 52, 0, :east
unit :wizard, 53, 0, :east
unit :sludge, 59, 0, :east
unit :sludge, 68, 0, :east
unit :sludge, 70, 0, :east
unit :wizard, 73, 0, :east
unit :thick_sludge, 76, 0, :east
unit :archer, 80, 0, :east
unit :wizard, 83, 0, :east
unit :captive, 85, 0, :east
unit :sludge, 86, 0, :east
unit :archer, 100, 0, :east
unit :wizard, 103, 0, :east
unit :archer, 107, 0, :east
unit :sludge, 112, 0, :east
unit :thick_sludge, 114, 0, :east
unit :archer, 121, 0, :east
unit :thick_sludge, 122, 0, :east
unit :captive, 123, 0, :east
unit :captive, 125, 0, :east
unit :captive, 126, 0, :east
unit :thick_sludge, 127, 0, :east
unit :thick_sludge, 128, 0, :east
unit :sludge, 131, 0, :east
unit :captive, 138, 0, :east
unit :archer, 140, 0, :east
unit :captive, 145, 0, :east
unit :wizard, 147, 0, :east
unit :captive, 150, 0, :east
unit :captive, 151, 0, :east
unit :sludge, 153, 0, :east
unit :archer, 154, 0, :east
unit :wizard, 157, 0, :east
unit :archer, 160, 0, :east
unit :archer, 163, 0, :east
unit :archer, 167, 0, :east
unit :thick_sludge, 169, 0, :east
unit :sludge, 174, 0, :east
unit :wizard, 183, 0, :east
unit :sludge, 185, 0, :east
unit :wizard, 194, 0, :east
unit :captive, 196, 0, :east
unit :sludge, 198, 0, :east
unit :captive, 200, 0, :east
unit :archer, 203, 0, :east
unit :thick_sludge, 204, 0, :east
unit :archer, 206, 0, :east
unit :captive, 210, 0, :east
unit :thick_sludge, 214, 0, :east
unit :sludge, 222, 0, :east
unit :archer, 235, 0, :east
unit :wizard, 239, 0, :east
unit :thick_sludge, 243, 0, :east
unit :wizard, 244, 0, :east
unit :archer, 248, 0, :east
unit :thick_sludge, 256, 0, :west
unit :archer, 260, 0, :west
unit :thick_sludge, 261, 0, :west
unit :captive, 263, 0, :west
unit :thick_sludge, 268, 0, :west
unit :archer, 269, 0, :west
unit :captive, 279, 0, :west
unit :thick_sludge, 286, 0, :west
unit :thick_sludge, 290, 0, :west
unit :wizard, 295, 0, :west
unit :wizard, 300, 0, :west
unit :wizard, 302, 0, :west
unit :wizard, 309, 0, :west
unit :captive, 311, 0, :west
unit :wizard, 313, 0, :west
unit :captive, 315, 0, :west
unit :thick_sludge, 317, 0, :west
unit :wizard, 330, 0, :west
unit :archer, 342, 0, :west
unit :archer, 358, 0, :west
unit :wizard, 362, 0, :west
unit :thick_sludge, 364, 0, :west
unit :captive, 367, 0, :west
unit :sludge, 370, 0, :west
unit :archer, 378, 0, :west
unit :thick_sludge, 382, 0, :west
unit :sludge, 384, 0, :west
unit :archer, 392, 0, :west
unit :archer, 403, 0, :west
unit :captive, 408, 0, :west
unit :thick_sludge, 410, 0, :west
unit :captive, 414, 0, :west
unit :archer, 416, 0, :west
unit :archer, 418, 0, :west
unit :archer, 419, 0, :west
unit :thick_sludge, 421, 0, :west
unit :thick_sludge, 422, 0, :west
unit :wizard, 423, 0, :west
unit :archer, 424, 0, :west
unit :sludge, 430, 0, :west
unit :captive, 437, 0, :west
unit :thick_sludge, 439, 0, :west
unit :captive, 440, 0, :west
unit :archer, 442, 0, :west
unit :sludge, 444, 0, :west
unit :sludge, 448, 0, :west
unit :thick_sludge, 456, 0, :west
unit :captive, 459, 0, :west
unit :archer, 472, 0, :west
unit :wizard, 473, 0, :west
unit :captive, 479, 0, :west
unit :thick_sludge, 481, 0, :west
unit :thick_sludge, 483, 0, :west
unit :wizard, 485, 0, :west
unit :thick_sludge, 494, 0, :west
unit :captive, 497, 0, :west
unit :sludge, 501, 0, :west
unit :wizard, 508, 0, :west
unit :captive, 514, 0, :west
unit :wizard, 516, 0, :west
unit :sludge, 517, 0, :west
unit :sludge, 518, 0, :west
unit :captive, 524, 0, :west
unit :archer, 533, 0, :west
unit :archer, 539, 0, :west
unit :thick_sludge, 542, 0, :west
unit :captive, 544, 0, :west
unit :thick_sludge, 547, 0, :west
unit :captive, 548, 0, :west
unit :sludge, 549, 0, :west
unit :wizard, 554, 0, :west
unit :archer, 555, 0, :west
unit :sludge, 560, 0, :west
unit :sludge, 561, 0, :west
unit :archer, 568, 0, :west
unit :thick_sludge, 571, 0, :west
unit :archer, 573, 0, :west
unit :sludge, 579, 0, :west
unit :captive, 583, 0, :west
unit :sludge, 586, 0, :west
unit :captive, 587, 0, :west
unit :captive, 589, 0, :west
unit :sludge, 594, 0, :west
unit :thick_sludge, 595, 0, :west
unit :archer, 598, 0, :west
unit :captive, 604, 0, :west
unit :captive, 605, 0, :west
unit :sludge, 609, 0, :west
unit :sludge, 610, 0, :west
unit :captive, 611, 0, :west
unit :sludge, 612, 0, :west
unit :thick_sludge, 617, 0, :west
unit :thick_sludge, 623, 0, :west
unit :sludge, 637, 0, :west
unit :archer, 640, 0, :west
unit :thick_sludge, 643, 0, :west
unit :captive, 646, 0, :west
unit :thick_sludge, 652, 0, :west
unit :archer, 653, 0, :west
unit :sludge, 658, 0, :west
unit :wizard, 660, 0, :west
unit :archer, 661, 0, :west
unit :captive, 666, 0, :west
unit :captive, 680, 0, :west
unit :sludge, 689, 0, :west
unit :sludge, 693, 0, :west
unit :sludge, 695, 0, :west
