#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S      a        w            S s  s  S             sSs   S     w C  s  s w   w     s s         CSCa  Ss     s               w  C sa    S   a      aa          w  S    w  S      sw        s w C     S   a    a  sw  s         s    s           a   s    s  S w          a a   w     s a               S      @         a  s  S    w    S   sw     w> C   S S   Ss      aC             a a C   CS         S S SS a      as     s      S  S      a   a      sa      w     s  w         sS   s C Sa   s  S w  S   S     aa     C  w                C C  Cs wa Cs SC  w       waC       C        w   s     ws     w   a  w    s  s C Cwas   w    w s    C    a  w a s  a            w  Cw s s      S    s as        SS    s     a s     a sS asw  w  w w CC  CS  wS  a C a  a w   C a      |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 759
ace_score 3795
size 759, 1
stairs 339, 0

warrior 301, 0, :east

unit :thick_sludge, 0, 0, :east
unit :archer, 7, 0, :east
unit :wizard, 16, 0, :east
unit :thick_sludge, 29, 0, :east
unit :sludge, 31, 0, :east
unit :sludge, 34, 0, :east
unit :thick_sludge, 37, 0, :east
unit :sludge, 51, 0, :east
unit :thick_sludge, 52, 0, :east
unit :sludge, 53, 0, :east
unit :thick_sludge, 57, 0, :east
unit :wizard, 63, 0, :east
unit :captive, 65, 0, :east
unit :sludge, 68, 0, :east
unit :sludge, 71, 0, :east
unit :wizard, 73, 0, :east
unit :wizard, 77, 0, :east
unit :sludge, 83, 0, :east
unit :sludge, 85, 0, :east
unit :captive, 95, 0, :east
unit :thick_sludge, 96, 0, :east
unit :captive, 97, 0, :east
unit :archer, 98, 0, :east
unit :thick_sludge, 101, 0, :east
unit :sludge, 102, 0, :east
unit :sludge, 108, 0, :east
unit :wizard, 124, 0, :east
unit :captive, 127, 0, :east
unit :sludge, 129, 0, :east
unit :archer, 130, 0, :east
unit :thick_sludge, 135, 0, :east
unit :archer, 139, 0, :east
unit :archer, 146, 0, :east
unit :archer, 147, 0, :east
unit :wizard, 158, 0, :east
unit :thick_sludge, 161, 0, :east
unit :wizard, 166, 0, :east
unit :thick_sludge, 169, 0, :east
unit :sludge, 176, 0, :east
unit :wizard, 177, 0, :east
unit :sludge, 186, 0, :east
unit :wizard, 188, 0, :east
unit :captive, 190, 0, :east
unit :thick_sludge, 196, 0, :east
unit :archer, 200, 0, :east
unit :archer, 205, 0, :east
unit :sludge, 208, 0, :east
unit :wizard, 209, 0, :east
unit :sludge, 212, 0, :east
unit :sludge, 222, 0, :east
unit :sludge, 227, 0, :east
unit :archer, 239, 0, :east
unit :sludge, 243, 0, :east
unit :sludge, 248, 0, :east
unit :thick_sludge, 251, 0, :east
unit :wizard, 253, 0, :east
unit :archer, 264, 0, :east
unit :archer, 266, 0, :east
unit :wizard, 270, 0, :east
unit :sludge, 276, 0, :east
unit :archer, 278, 0, :east
unit :thick_sludge, 294, 0, :east
unit :archer, 311, 0, :west
unit :sludge, 314, 0, :west
unit :thick_sludge, 317, 0, :west
unit :wizard, 322, 0, :west
unit :thick_sludge, 327, 0, :west
unit :sludge, 331, 0, :west
unit :wizard, 332, 0, :west
unit :wizard, 338, 0, :west
unit :captive, 341, 0, :west
unit :thick_sludge, 345, 0, :west
unit :thick_sludge, 347, 0, :west
unit :thick_sludge, 351, 0, :west
unit :sludge, 352, 0, :west
unit :archer, 359, 0, :west
unit :captive, 360, 0, :west
unit :archer, 374, 0, :west
unit :archer, 376, 0, :west
unit :captive, 378, 0, :west
unit :captive, 382, 0, :west
unit :thick_sludge, 383, 0, :west
unit :thick_sludge, 393, 0, :west
unit :thick_sludge, 395, 0, :west
unit :thick_sludge, 397, 0, :west
unit :thick_sludge, 398, 0, :west
unit :archer, 400, 0, :west
unit :archer, 407, 0, :west
unit :sludge, 408, 0, :west
unit :sludge, 414, 0, :west
unit :thick_sludge, 421, 0, :west
unit :thick_sludge, 424, 0, :west
unit :archer, 431, 0, :west
unit :archer, 435, 0, :west
unit :sludge, 442, 0, :west
unit :archer, 443, 0, :west
unit :wizard, 450, 0, :west
unit :sludge, 456, 0, :west
unit :wizard, 459, 0, :west
unit :sludge, 469, 0, :west
unit :thick_sludge, 470, 0, :west
unit :sludge, 474, 0, :west
unit :captive, 476, 0, :west
unit :thick_sludge, 478, 0, :west
unit :archer, 479, 0, :west
unit :sludge, 483, 0, :west
unit :thick_sludge, 486, 0, :west
unit :wizard, 488, 0, :west
unit :thick_sludge, 491, 0, :west
unit :thick_sludge, 495, 0, :west
unit :archer, 501, 0, :west
unit :archer, 502, 0, :west
unit :captive, 508, 0, :west
unit :wizard, 511, 0, :west
unit :captive, 528, 0, :west
unit :captive, 530, 0, :west
unit :captive, 533, 0, :west
unit :sludge, 534, 0, :west
unit :wizard, 536, 0, :west
unit :archer, 537, 0, :west
unit :captive, 539, 0, :west
unit :sludge, 540, 0, :west
unit :thick_sludge, 542, 0, :west
unit :captive, 543, 0, :west
unit :wizard, 546, 0, :west
unit :wizard, 554, 0, :west
unit :archer, 555, 0, :west
unit :captive, 556, 0, :west
unit :captive, 564, 0, :west
unit :wizard, 573, 0, :west
unit :sludge, 577, 0, :west
unit :wizard, 583, 0, :west
unit :sludge, 584, 0, :west
unit :wizard, 590, 0, :west
unit :archer, 594, 0, :west
unit :wizard, 597, 0, :west
unit :sludge, 602, 0, :west
unit :sludge, 605, 0, :west
unit :captive, 607, 0, :west
unit :captive, 609, 0, :west
unit :wizard, 610, 0, :west
unit :archer, 611, 0, :west
unit :sludge, 612, 0, :west
unit :wizard, 616, 0, :west
unit :wizard, 621, 0, :west
unit :sludge, 623, 0, :west
unit :captive, 628, 0, :west
unit :archer, 633, 0, :west
unit :wizard, 636, 0, :west
unit :archer, 638, 0, :west
unit :sludge, 640, 0, :west
unit :archer, 643, 0, :west
unit :wizard, 656, 0, :west
unit :captive, 659, 0, :west
unit :wizard, 660, 0, :west
unit :sludge, 662, 0, :west
unit :sludge, 664, 0, :west
unit :thick_sludge, 671, 0, :west
unit :sludge, 676, 0, :west
unit :archer, 678, 0, :west
unit :sludge, 679, 0, :west
unit :thick_sludge, 688, 0, :west
unit :thick_sludge, 689, 0, :west
unit :sludge, 694, 0, :west
unit :archer, 700, 0, :west
unit :sludge, 702, 0, :west
unit :archer, 708, 0, :west
unit :sludge, 710, 0, :west
unit :thick_sludge, 711, 0, :west
unit :archer, 713, 0, :west
unit :sludge, 714, 0, :west
unit :wizard, 715, 0, :west
unit :wizard, 718, 0, :west
unit :wizard, 721, 0, :west
unit :wizard, 723, 0, :west
unit :captive, 725, 0, :west
unit :captive, 726, 0, :west
unit :captive, 729, 0, :west
unit :thick_sludge, 730, 0, :west
unit :wizard, 733, 0, :west
unit :thick_sludge, 734, 0, :west
unit :archer, 737, 0, :west
unit :captive, 739, 0, :west
unit :archer, 741, 0, :west
unit :archer, 744, 0, :west
unit :wizard, 746, 0, :west
unit :captive, 750, 0, :west
unit :archer, 752, 0, :west
