#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S a       a   C    w   sS   s S   a          ss  C  C       a w     a w    w  >           w          S C sS a a w         a   S  s      w   C      ws    a              Cs a      s ssS C          s    C  w      a     w  S   a w   a      a   s s  as          s       C S   S     C wSw       aC     a  a  C  S     w s    S    w      Cs    S s w   S    s s as         S    w  C  C         C     w   C a  S   aS         a    C   S     S a   w s w   w   SC s    s     S aS C  sC  C  s     S  s S aw                as   sa      s  @       Cw  s C      S     a sC  w Ca      Cw    S    C s      sC               s             sS a      w  aa aC C         w      a    a Cs    CaC   C   S  wS  S       s S    w SS    s    Cw      s     wS S       w  Sw    a SC             sa C      as     w     aC C   C aSs  s  s s                   w  S     saC  w    w C s  sS   S             S      w   sw w  S CC  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 893
ace_score 4465
size 893, 1
stairs 78, 0

warrior 524, 0, :east

unit :thick_sludge, 0, 0, :east
unit :archer, 2, 0, :east
unit :archer, 10, 0, :east
unit :captive, 14, 0, :east
unit :wizard, 19, 0, :east
unit :sludge, 23, 0, :east
unit :thick_sludge, 24, 0, :east
unit :sludge, 28, 0, :east
unit :thick_sludge, 30, 0, :east
unit :archer, 34, 0, :east
unit :sludge, 45, 0, :east
unit :sludge, 46, 0, :east
unit :captive, 49, 0, :east
unit :captive, 52, 0, :east
unit :archer, 60, 0, :east
unit :wizard, 62, 0, :east
unit :archer, 68, 0, :east
unit :wizard, 70, 0, :east
unit :wizard, 75, 0, :east
unit :wizard, 90, 0, :east
unit :thick_sludge, 101, 0, :east
unit :captive, 103, 0, :east
unit :sludge, 105, 0, :east
unit :thick_sludge, 106, 0, :east
unit :archer, 108, 0, :east
unit :archer, 110, 0, :east
unit :wizard, 112, 0, :east
unit :archer, 122, 0, :east
unit :thick_sludge, 126, 0, :east
unit :sludge, 129, 0, :east
unit :wizard, 136, 0, :east
unit :captive, 140, 0, :east
unit :wizard, 147, 0, :east
unit :sludge, 148, 0, :east
unit :archer, 153, 0, :east
unit :captive, 168, 0, :east
unit :sludge, 169, 0, :east
unit :archer, 171, 0, :east
unit :sludge, 178, 0, :east
unit :sludge, 180, 0, :east
unit :sludge, 181, 0, :east
unit :thick_sludge, 182, 0, :east
unit :captive, 184, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 200, 0, :east
unit :wizard, 203, 0, :east
unit :archer, 210, 0, :east
unit :wizard, 216, 0, :east
unit :thick_sludge, 219, 0, :east
unit :archer, 223, 0, :east
unit :wizard, 225, 0, :east
unit :archer, 229, 0, :east
unit :archer, 236, 0, :east
unit :sludge, 240, 0, :east
unit :sludge, 242, 0, :east
unit :archer, 245, 0, :east
unit :sludge, 246, 0, :east
unit :sludge, 257, 0, :east
unit :captive, 265, 0, :east
unit :thick_sludge, 267, 0, :east
unit :thick_sludge, 271, 0, :east
unit :captive, 277, 0, :east
unit :wizard, 279, 0, :east
unit :thick_sludge, 280, 0, :east
unit :wizard, 281, 0, :east
unit :archer, 289, 0, :east
unit :captive, 290, 0, :east
unit :archer, 296, 0, :east
unit :archer, 299, 0, :east
unit :captive, 302, 0, :east
unit :thick_sludge, 305, 0, :east
unit :wizard, 311, 0, :east
unit :sludge, 313, 0, :east
unit :thick_sludge, 318, 0, :east
unit :wizard, 323, 0, :east
unit :captive, 330, 0, :east
unit :sludge, 331, 0, :east
unit :thick_sludge, 336, 0, :east
unit :sludge, 338, 0, :east
unit :wizard, 340, 0, :east
unit :thick_sludge, 344, 0, :east
unit :sludge, 349, 0, :east
unit :sludge, 351, 0, :east
unit :archer, 353, 0, :east
unit :sludge, 354, 0, :east
unit :thick_sludge, 364, 0, :east
unit :wizard, 369, 0, :east
unit :captive, 372, 0, :east
unit :captive, 375, 0, :east
unit :captive, 385, 0, :east
unit :wizard, 391, 0, :east
unit :captive, 395, 0, :east
unit :archer, 397, 0, :east
unit :thick_sludge, 400, 0, :east
unit :archer, 404, 0, :east
unit :thick_sludge, 405, 0, :east
unit :archer, 415, 0, :east
unit :captive, 420, 0, :east
unit :thick_sludge, 424, 0, :east
unit :thick_sludge, 430, 0, :east
unit :archer, 432, 0, :east
unit :wizard, 436, 0, :east
unit :sludge, 438, 0, :east
unit :wizard, 440, 0, :east
unit :wizard, 444, 0, :east
unit :thick_sludge, 448, 0, :east
unit :captive, 449, 0, :east
unit :sludge, 451, 0, :east
unit :sludge, 456, 0, :east
unit :thick_sludge, 462, 0, :east
unit :archer, 464, 0, :east
unit :thick_sludge, 465, 0, :east
unit :captive, 467, 0, :east
unit :sludge, 470, 0, :east
unit :captive, 471, 0, :east
unit :captive, 474, 0, :east
unit :sludge, 477, 0, :east
unit :thick_sludge, 483, 0, :east
unit :sludge, 486, 0, :east
unit :thick_sludge, 488, 0, :east
unit :archer, 490, 0, :east
unit :wizard, 491, 0, :east
unit :archer, 508, 0, :east
unit :sludge, 509, 0, :east
unit :sludge, 513, 0, :east
unit :archer, 514, 0, :east
unit :sludge, 521, 0, :east
unit :captive, 532, 0, :west
unit :wizard, 533, 0, :west
unit :sludge, 536, 0, :west
unit :captive, 538, 0, :west
unit :thick_sludge, 545, 0, :west
unit :archer, 551, 0, :west
unit :sludge, 553, 0, :west
unit :captive, 554, 0, :west
unit :wizard, 557, 0, :west
unit :captive, 559, 0, :west
unit :archer, 560, 0, :west
unit :captive, 567, 0, :west
unit :wizard, 568, 0, :west
unit :thick_sludge, 573, 0, :west
unit :captive, 578, 0, :west
unit :sludge, 580, 0, :west
unit :sludge, 587, 0, :west
unit :captive, 588, 0, :west
unit :sludge, 604, 0, :west
unit :sludge, 618, 0, :west
unit :thick_sludge, 619, 0, :west
unit :archer, 621, 0, :west
unit :wizard, 628, 0, :west
unit :archer, 631, 0, :west
unit :archer, 632, 0, :west
unit :archer, 634, 0, :west
unit :captive, 635, 0, :west
unit :captive, 637, 0, :west
unit :wizard, 647, 0, :west
unit :archer, 654, 0, :west
unit :archer, 659, 0, :west
unit :captive, 661, 0, :west
unit :sludge, 662, 0, :west
unit :captive, 667, 0, :west
unit :archer, 668, 0, :west
unit :captive, 669, 0, :west
unit :captive, 673, 0, :west
unit :thick_sludge, 677, 0, :west
unit :wizard, 680, 0, :west
unit :thick_sludge, 681, 0, :west
unit :thick_sludge, 684, 0, :west
unit :sludge, 692, 0, :west
unit :thick_sludge, 694, 0, :west
unit :wizard, 699, 0, :west
unit :thick_sludge, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :sludge, 707, 0, :west
unit :captive, 712, 0, :west
unit :wizard, 713, 0, :west
unit :sludge, 720, 0, :west
unit :wizard, 726, 0, :west
unit :thick_sludge, 727, 0, :west
unit :thick_sludge, 729, 0, :west
unit :wizard, 737, 0, :west
unit :thick_sludge, 740, 0, :west
unit :wizard, 741, 0, :west
unit :archer, 746, 0, :west
unit :thick_sludge, 748, 0, :west
unit :captive, 749, 0, :west
unit :sludge, 763, 0, :west
unit :archer, 764, 0, :west
unit :captive, 766, 0, :west
unit :archer, 773, 0, :west
unit :sludge, 774, 0, :west
unit :wizard, 780, 0, :west
unit :archer, 786, 0, :west
unit :captive, 787, 0, :west
unit :captive, 789, 0, :west
unit :captive, 793, 0, :west
unit :archer, 795, 0, :west
unit :thick_sludge, 796, 0, :west
unit :sludge, 797, 0, :west
unit :sludge, 800, 0, :west
unit :sludge, 803, 0, :west
unit :sludge, 805, 0, :west
unit :wizard, 825, 0, :west
unit :thick_sludge, 828, 0, :west
unit :sludge, 834, 0, :west
unit :archer, 835, 0, :west
unit :captive, 836, 0, :west
unit :wizard, 839, 0, :west
unit :wizard, 844, 0, :west
unit :captive, 846, 0, :west
unit :sludge, 848, 0, :west
unit :sludge, 851, 0, :west
unit :thick_sludge, 852, 0, :west
unit :thick_sludge, 856, 0, :west
unit :thick_sludge, 870, 0, :west
unit :wizard, 877, 0, :west
unit :sludge, 881, 0, :west
unit :wizard, 882, 0, :west
unit :wizard, 884, 0, :west
unit :thick_sludge, 887, 0, :west
unit :captive, 889, 0, :west
unit :captive, 890, 0, :west
