#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S  w         w w   CC   w   SS        s s s      aS S  w        S w         C   w  s w  wS CS  s    S     w a        a  s      S s w   w  s  a     w     Sw     a w  C      a          w   S   @      w  S a     S    w S   w  w    C s        S    S     sCw  sa a        aC   aas  s S         C   a C        C      S  C  a    s      S w    S  C     s S   w    s     w S  s  w  Ca  S   aa  w          w   S   aa S   s         a     w  C               CS  C S      C C C sa s    S C      a     w  s    C        C               sCS  C    s  ass a S   S C Caa w  S Cw         C a   C    ss      aCS          S    w           a a               S s  S a S    S  s   w  C>  w       S C  |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 676
ace_score 3380
size 676, 1
stairs 660, 0

warrior 191, 0, :east

unit :thick_sludge, 0, 0, :east
unit :wizard, 3, 0, :east
unit :wizard, 13, 0, :east
unit :wizard, 15, 0, :east
unit :captive, 19, 0, :east
unit :captive, 20, 0, :east
unit :wizard, 24, 0, :east
unit :thick_sludge, 28, 0, :east
unit :thick_sludge, 29, 0, :east
unit :sludge, 38, 0, :east
unit :sludge, 40, 0, :east
unit :sludge, 42, 0, :east
unit :archer, 49, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 52, 0, :east
unit :wizard, 55, 0, :east
unit :thick_sludge, 64, 0, :east
unit :wizard, 66, 0, :east
unit :captive, 76, 0, :east
unit :wizard, 80, 0, :east
unit :sludge, 83, 0, :east
unit :wizard, 85, 0, :east
unit :wizard, 88, 0, :east
unit :thick_sludge, 89, 0, :east
unit :captive, 91, 0, :east
unit :thick_sludge, 92, 0, :east
unit :sludge, 95, 0, :east
unit :thick_sludge, 100, 0, :east
unit :wizard, 106, 0, :east
unit :archer, 108, 0, :east
unit :archer, 117, 0, :east
unit :sludge, 120, 0, :east
unit :thick_sludge, 127, 0, :east
unit :sludge, 129, 0, :east
unit :wizard, 131, 0, :east
unit :wizard, 135, 0, :east
unit :sludge, 138, 0, :east
unit :archer, 141, 0, :east
unit :wizard, 147, 0, :east
unit :thick_sludge, 153, 0, :east
unit :wizard, 154, 0, :east
unit :archer, 160, 0, :east
unit :wizard, 162, 0, :east
unit :captive, 165, 0, :east
unit :archer, 172, 0, :east
unit :wizard, 183, 0, :east
unit :thick_sludge, 187, 0, :east
unit :wizard, 198, 0, :west
unit :thick_sludge, 201, 0, :west
unit :archer, 203, 0, :west
unit :thick_sludge, 209, 0, :west
unit :wizard, 214, 0, :west
unit :thick_sludge, 216, 0, :west
unit :wizard, 220, 0, :west
unit :wizard, 223, 0, :west
unit :captive, 228, 0, :west
unit :sludge, 230, 0, :west
unit :thick_sludge, 239, 0, :west
unit :thick_sludge, 244, 0, :west
unit :sludge, 250, 0, :west
unit :captive, 251, 0, :west
unit :wizard, 252, 0, :west
unit :sludge, 255, 0, :west
unit :archer, 256, 0, :west
unit :archer, 258, 0, :west
unit :archer, 267, 0, :west
unit :captive, 268, 0, :west
unit :archer, 272, 0, :west
unit :archer, 273, 0, :west
unit :sludge, 274, 0, :west
unit :sludge, 277, 0, :west
unit :thick_sludge, 279, 0, :west
unit :captive, 289, 0, :west
unit :archer, 293, 0, :west
unit :captive, 295, 0, :west
unit :captive, 304, 0, :west
unit :thick_sludge, 311, 0, :west
unit :captive, 314, 0, :west
unit :archer, 317, 0, :west
unit :sludge, 322, 0, :west
unit :thick_sludge, 329, 0, :west
unit :wizard, 331, 0, :west
unit :thick_sludge, 336, 0, :west
unit :captive, 339, 0, :west
unit :sludge, 345, 0, :west
unit :thick_sludge, 347, 0, :west
unit :wizard, 351, 0, :west
unit :sludge, 356, 0, :west
unit :wizard, 362, 0, :west
unit :thick_sludge, 364, 0, :west
unit :sludge, 367, 0, :west
unit :wizard, 370, 0, :west
unit :captive, 373, 0, :west
unit :archer, 374, 0, :west
unit :thick_sludge, 377, 0, :west
unit :archer, 381, 0, :west
unit :archer, 382, 0, :west
unit :wizard, 385, 0, :west
unit :wizard, 396, 0, :west
unit :thick_sludge, 400, 0, :west
unit :archer, 404, 0, :west
unit :archer, 405, 0, :west
unit :thick_sludge, 407, 0, :west
unit :sludge, 411, 0, :west
unit :archer, 421, 0, :west
unit :wizard, 427, 0, :west
unit :captive, 430, 0, :west
unit :captive, 446, 0, :west
unit :thick_sludge, 447, 0, :west
unit :captive, 450, 0, :west
unit :thick_sludge, 452, 0, :west
unit :captive, 459, 0, :west
unit :captive, 461, 0, :west
unit :captive, 463, 0, :west
unit :sludge, 465, 0, :west
unit :archer, 466, 0, :west
unit :sludge, 468, 0, :west
unit :thick_sludge, 473, 0, :west
unit :captive, 475, 0, :west
unit :archer, 482, 0, :west
unit :wizard, 488, 0, :west
unit :sludge, 491, 0, :west
unit :captive, 496, 0, :west
unit :captive, 505, 0, :west
unit :sludge, 521, 0, :west
unit :captive, 522, 0, :west
unit :thick_sludge, 523, 0, :west
unit :captive, 526, 0, :west
unit :sludge, 531, 0, :west
unit :archer, 534, 0, :west
unit :sludge, 535, 0, :west
unit :sludge, 536, 0, :west
unit :archer, 538, 0, :west
unit :thick_sludge, 540, 0, :west
unit :thick_sludge, 544, 0, :west
unit :captive, 546, 0, :west
unit :captive, 548, 0, :west
unit :archer, 549, 0, :west
unit :archer, 550, 0, :west
unit :wizard, 552, 0, :west
unit :thick_sludge, 555, 0, :west
unit :captive, 557, 0, :west
unit :wizard, 558, 0, :west
unit :captive, 568, 0, :west
unit :archer, 570, 0, :west
unit :captive, 574, 0, :west
unit :sludge, 579, 0, :west
unit :sludge, 580, 0, :west
unit :archer, 587, 0, :west
unit :captive, 588, 0, :west
unit :thick_sludge, 589, 0, :west
unit :thick_sludge, 600, 0, :west
unit :wizard, 605, 0, :west
unit :archer, 617, 0, :west
unit :archer, 619, 0, :west
unit :thick_sludge, 635, 0, :west
unit :sludge, 637, 0, :west
unit :thick_sludge, 640, 0, :west
unit :archer, 642, 0, :west
unit :thick_sludge, 644, 0, :west
unit :thick_sludge, 649, 0, :west
unit :sludge, 652, 0, :west
unit :wizard, 656, 0, :west
unit :captive, 659, 0, :west
unit :wizard, 663, 0, :west
unit :thick_sludge, 671, 0, :west
unit :captive, 673, 0, :west
