#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     w CC  aa C    s  C   S     s         Cs  a aa   a          C C  Sw     Cs a    C     s s      w   s           ass  a        C  w      sS     w         s    w    CCC        a    C  s  w     C aa       S    a         w a         a w  SS  a        S    S   S    w      C     w   S Saa   s C    CS   s      Sa  > a S SwC S  S       S  C  w a s     w    S             w   a  aas   S  sCs    @   C   S    S        S  s   a      w  w          C  S   C    s      w w  S           ss                   S  C    S   a    a S  w  s    sS   C      w                  Cw  s S   C Ca a    w    s     wa aCC       s  s aSs     C          w    w        a      s     s      C  C sS  w  w w   w     s  aS     C C  ss   S  s   C       s      a aS        a   S CC          Sss S   SaS     Sa  w   ss      CaC SS s  s         w s    S Ca   CC   S S   |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 834
ace_score 4170
size 834, 1
stairs 312, 0

warrior 391, 0, :east

unit :wizard, 5, 0, :east
unit :captive, 7, 0, :east
unit :captive, 8, 0, :east
unit :archer, 11, 0, :east
unit :archer, 12, 0, :east
unit :captive, 14, 0, :east
unit :sludge, 19, 0, :east
unit :captive, 22, 0, :east
unit :thick_sludge, 26, 0, :east
unit :sludge, 32, 0, :east
unit :captive, 42, 0, :east
unit :sludge, 43, 0, :east
unit :archer, 46, 0, :east
unit :archer, 48, 0, :east
unit :archer, 49, 0, :east
unit :archer, 53, 0, :east
unit :captive, 64, 0, :east
unit :captive, 66, 0, :east
unit :thick_sludge, 69, 0, :east
unit :wizard, 70, 0, :east
unit :captive, 76, 0, :east
unit :sludge, 77, 0, :east
unit :archer, 79, 0, :east
unit :captive, 84, 0, :east
unit :sludge, 90, 0, :east
unit :sludge, 92, 0, :east
unit :wizard, 99, 0, :east
unit :sludge, 103, 0, :east
unit :archer, 115, 0, :east
unit :sludge, 116, 0, :east
unit :sludge, 117, 0, :east
unit :archer, 120, 0, :east
unit :captive, 129, 0, :east
unit :wizard, 132, 0, :east
unit :sludge, 139, 0, :east
unit :thick_sludge, 140, 0, :east
unit :wizard, 146, 0, :east
unit :sludge, 156, 0, :east
unit :wizard, 161, 0, :east
unit :captive, 166, 0, :east
unit :captive, 167, 0, :east
unit :captive, 168, 0, :east
unit :archer, 177, 0, :east
unit :captive, 182, 0, :east
unit :sludge, 185, 0, :east
unit :wizard, 188, 0, :east
unit :captive, 194, 0, :east
unit :archer, 196, 0, :east
unit :archer, 197, 0, :east
unit :thick_sludge, 205, 0, :east
unit :archer, 210, 0, :east
unit :wizard, 220, 0, :east
unit :archer, 222, 0, :east
unit :archer, 232, 0, :east
unit :wizard, 234, 0, :east
unit :thick_sludge, 237, 0, :east
unit :thick_sludge, 238, 0, :east
unit :archer, 241, 0, :east
unit :thick_sludge, 250, 0, :east
unit :thick_sludge, 255, 0, :east
unit :thick_sludge, 259, 0, :east
unit :wizard, 264, 0, :east
unit :captive, 271, 0, :east
unit :wizard, 277, 0, :east
unit :thick_sludge, 281, 0, :east
unit :thick_sludge, 283, 0, :east
unit :archer, 284, 0, :east
unit :archer, 285, 0, :east
unit :sludge, 289, 0, :east
unit :captive, 291, 0, :east
unit :captive, 296, 0, :east
unit :thick_sludge, 297, 0, :east
unit :sludge, 301, 0, :east
unit :thick_sludge, 308, 0, :east
unit :archer, 309, 0, :east
unit :archer, 314, 0, :east
unit :thick_sludge, 316, 0, :east
unit :thick_sludge, 318, 0, :east
unit :wizard, 319, 0, :east
unit :captive, 320, 0, :east
unit :thick_sludge, 322, 0, :east
unit :thick_sludge, 325, 0, :east
unit :thick_sludge, 333, 0, :east
unit :captive, 336, 0, :east
unit :wizard, 339, 0, :east
unit :archer, 341, 0, :east
unit :sludge, 343, 0, :east
unit :wizard, 349, 0, :east
unit :thick_sludge, 354, 0, :east
unit :wizard, 368, 0, :east
unit :archer, 372, 0, :east
unit :archer, 375, 0, :east
unit :archer, 376, 0, :east
unit :sludge, 377, 0, :east
unit :thick_sludge, 381, 0, :east
unit :sludge, 384, 0, :east
unit :captive, 385, 0, :east
unit :sludge, 386, 0, :east
unit :captive, 395, 0, :west
unit :thick_sludge, 399, 0, :west
unit :thick_sludge, 404, 0, :west
unit :thick_sludge, 413, 0, :west
unit :sludge, 416, 0, :west
unit :archer, 420, 0, :west
unit :wizard, 427, 0, :west
unit :wizard, 430, 0, :west
unit :captive, 441, 0, :west
unit :thick_sludge, 444, 0, :west
unit :captive, 448, 0, :west
unit :sludge, 453, 0, :west
unit :wizard, 460, 0, :west
unit :wizard, 462, 0, :west
unit :thick_sludge, 465, 0, :west
unit :sludge, 477, 0, :west
unit :sludge, 478, 0, :west
unit :thick_sludge, 498, 0, :west
unit :captive, 501, 0, :west
unit :thick_sludge, 506, 0, :west
unit :archer, 510, 0, :west
unit :archer, 515, 0, :west
unit :thick_sludge, 517, 0, :west
unit :wizard, 520, 0, :west
unit :sludge, 523, 0, :west
unit :sludge, 528, 0, :west
unit :thick_sludge, 529, 0, :west
unit :captive, 533, 0, :west
unit :wizard, 540, 0, :west
unit :captive, 559, 0, :west
unit :wizard, 560, 0, :west
unit :sludge, 563, 0, :west
unit :thick_sludge, 565, 0, :west
unit :captive, 569, 0, :west
unit :captive, 571, 0, :west
unit :archer, 572, 0, :west
unit :archer, 574, 0, :west
unit :wizard, 579, 0, :west
unit :sludge, 584, 0, :west
unit :wizard, 590, 0, :west
unit :archer, 591, 0, :west
unit :archer, 593, 0, :west
unit :captive, 594, 0, :west
unit :captive, 595, 0, :west
unit :sludge, 603, 0, :west
unit :sludge, 606, 0, :west
unit :archer, 608, 0, :west
unit :thick_sludge, 609, 0, :west
unit :sludge, 610, 0, :west
unit :captive, 616, 0, :west
unit :wizard, 627, 0, :west
unit :wizard, 632, 0, :west
unit :archer, 641, 0, :west
unit :sludge, 648, 0, :west
unit :sludge, 654, 0, :west
unit :captive, 661, 0, :west
unit :captive, 664, 0, :west
unit :sludge, 666, 0, :west
unit :thick_sludge, 667, 0, :west
unit :wizard, 670, 0, :west
unit :wizard, 673, 0, :west
unit :wizard, 675, 0, :west
unit :wizard, 679, 0, :west
unit :sludge, 685, 0, :west
unit :archer, 688, 0, :west
unit :thick_sludge, 689, 0, :west
unit :captive, 695, 0, :west
unit :captive, 697, 0, :west
unit :sludge, 700, 0, :west
unit :sludge, 701, 0, :west
unit :thick_sludge, 705, 0, :west
unit :sludge, 708, 0, :west
unit :captive, 712, 0, :west
unit :sludge, 720, 0, :west
unit :archer, 727, 0, :west
unit :archer, 729, 0, :west
unit :thick_sludge, 730, 0, :west
unit :archer, 739, 0, :west
unit :thick_sludge, 743, 0, :west
unit :captive, 745, 0, :west
unit :captive, 746, 0, :west
unit :thick_sludge, 757, 0, :west
unit :sludge, 758, 0, :west
unit :sludge, 759, 0, :west
unit :thick_sludge, 761, 0, :west
unit :thick_sludge, 765, 0, :west
unit :archer, 766, 0, :west
unit :thick_sludge, 767, 0, :west
unit :thick_sludge, 773, 0, :west
unit :archer, 774, 0, :west
unit :wizard, 777, 0, :west
unit :sludge, 781, 0, :west
unit :sludge, 782, 0, :west
unit :captive, 789, 0, :west
unit :archer, 790, 0, :west
unit :captive, 791, 0, :west
unit :thick_sludge, 793, 0, :west
unit :thick_sludge, 794, 0, :west
unit :sludge, 796, 0, :west
unit :sludge, 799, 0, :west
unit :wizard, 809, 0, :west
unit :sludge, 811, 0, :west
unit :thick_sludge, 816, 0, :west
unit :captive, 818, 0, :west
unit :archer, 819, 0, :west
unit :captive, 823, 0, :west
unit :captive, 824, 0, :west
unit :thick_sludge, 828, 0, :west
unit :thick_sludge, 830, 0, :west
