#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S          C  w  S        S  a  a a    S  Ss   w s            a a  C w         aS   w         S      C   w w s s     w    a       w  ss   s S aa          a       Ss  s  C    S as              s w  w w  a a    a  SS Ss    s a  C S    w w   CS  a        s      C s  sS C       w         C    aS  s  s C    w      S  w sC  C s  ss   CSa   C  s     w      s aa     C     S  a            S        S a w w    w    a    Sw   s  CsC       a C aa  sS s   S     C a   w  w  a   s    C     S S wS     a     s   w                   C  S  C  s a  >wa   a     w   aa   w    s S  aS    a Cas          C       a  S     s S            as   @     s w a    a        a s    S                a   a     C  s w  C  S S      a   a  w   S   |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 717
ace_score 3585
size 717, 1
stairs 535, 0

warrior 624, 0, :east

unit :thick_sludge, 1, 0, :east
unit :captive, 12, 0, :east
unit :wizard, 15, 0, :east
unit :thick_sludge, 18, 0, :east
unit :thick_sludge, 27, 0, :east
unit :archer, 30, 0, :east
unit :archer, 33, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 40, 0, :east
unit :thick_sludge, 43, 0, :east
unit :sludge, 44, 0, :east
unit :wizard, 48, 0, :east
unit :sludge, 50, 0, :east
unit :archer, 63, 0, :east
unit :archer, 65, 0, :east
unit :captive, 68, 0, :east
unit :wizard, 70, 0, :east
unit :archer, 80, 0, :east
unit :thick_sludge, 81, 0, :east
unit :wizard, 85, 0, :east
unit :thick_sludge, 95, 0, :east
unit :captive, 102, 0, :east
unit :wizard, 106, 0, :east
unit :wizard, 108, 0, :east
unit :sludge, 110, 0, :east
unit :sludge, 112, 0, :east
unit :wizard, 118, 0, :east
unit :archer, 123, 0, :east
unit :wizard, 131, 0, :east
unit :sludge, 134, 0, :east
unit :sludge, 135, 0, :east
unit :sludge, 139, 0, :east
unit :thick_sludge, 141, 0, :east
unit :archer, 143, 0, :east
unit :archer, 144, 0, :east
unit :archer, 155, 0, :east
unit :thick_sludge, 163, 0, :east
unit :sludge, 164, 0, :east
unit :sludge, 167, 0, :east
unit :captive, 170, 0, :east
unit :thick_sludge, 175, 0, :east
unit :archer, 177, 0, :east
unit :sludge, 178, 0, :east
unit :sludge, 193, 0, :east
unit :wizard, 195, 0, :east
unit :wizard, 198, 0, :east
unit :wizard, 200, 0, :east
unit :archer, 203, 0, :east
unit :archer, 205, 0, :east
unit :archer, 210, 0, :east
unit :thick_sludge, 213, 0, :east
unit :thick_sludge, 214, 0, :east
unit :thick_sludge, 216, 0, :east
unit :sludge, 217, 0, :east
unit :sludge, 222, 0, :east
unit :archer, 224, 0, :east
unit :captive, 227, 0, :east
unit :thick_sludge, 229, 0, :east
unit :wizard, 234, 0, :east
unit :wizard, 236, 0, :east
unit :captive, 240, 0, :east
unit :thick_sludge, 241, 0, :east
unit :archer, 244, 0, :east
unit :sludge, 253, 0, :east
unit :captive, 260, 0, :east
unit :sludge, 262, 0, :east
unit :sludge, 265, 0, :east
unit :thick_sludge, 266, 0, :east
unit :captive, 268, 0, :east
unit :wizard, 276, 0, :east
unit :captive, 286, 0, :east
unit :archer, 291, 0, :east
unit :thick_sludge, 292, 0, :east
unit :sludge, 295, 0, :east
unit :sludge, 298, 0, :east
unit :captive, 300, 0, :east
unit :wizard, 305, 0, :east
unit :thick_sludge, 312, 0, :east
unit :wizard, 315, 0, :east
unit :sludge, 317, 0, :east
unit :captive, 318, 0, :east
unit :captive, 321, 0, :east
unit :sludge, 323, 0, :east
unit :sludge, 326, 0, :east
unit :sludge, 327, 0, :east
unit :captive, 331, 0, :east
unit :thick_sludge, 332, 0, :east
unit :archer, 333, 0, :east
unit :captive, 337, 0, :east
unit :sludge, 340, 0, :east
unit :wizard, 346, 0, :east
unit :sludge, 353, 0, :east
unit :archer, 355, 0, :east
unit :archer, 356, 0, :east
unit :captive, 362, 0, :east
unit :thick_sludge, 368, 0, :east
unit :archer, 371, 0, :east
unit :thick_sludge, 384, 0, :east
unit :thick_sludge, 393, 0, :east
unit :archer, 395, 0, :east
unit :wizard, 397, 0, :east
unit :wizard, 399, 0, :east
unit :wizard, 404, 0, :east
unit :archer, 409, 0, :east
unit :thick_sludge, 414, 0, :east
unit :wizard, 415, 0, :east
unit :sludge, 419, 0, :east
unit :captive, 422, 0, :east
unit :sludge, 423, 0, :east
unit :captive, 424, 0, :east
unit :archer, 432, 0, :east
unit :captive, 434, 0, :east
unit :archer, 436, 0, :east
unit :archer, 437, 0, :east
unit :sludge, 440, 0, :east
unit :thick_sludge, 441, 0, :east
unit :sludge, 443, 0, :east
unit :thick_sludge, 447, 0, :east
unit :captive, 453, 0, :east
unit :archer, 455, 0, :east
unit :wizard, 459, 0, :east
unit :wizard, 462, 0, :east
unit :archer, 465, 0, :east
unit :sludge, 469, 0, :east
unit :captive, 474, 0, :east
unit :thick_sludge, 480, 0, :east
unit :thick_sludge, 482, 0, :east
unit :wizard, 484, 0, :east
unit :thick_sludge, 485, 0, :east
unit :archer, 491, 0, :east
unit :sludge, 497, 0, :east
unit :wizard, 501, 0, :east
unit :captive, 521, 0, :east
unit :thick_sludge, 524, 0, :east
unit :captive, 527, 0, :east
unit :sludge, 530, 0, :east
unit :archer, 532, 0, :east
unit :wizard, 536, 0, :east
unit :archer, 537, 0, :east
unit :archer, 541, 0, :east
unit :wizard, 547, 0, :east
unit :archer, 551, 0, :east
unit :archer, 552, 0, :east
unit :wizard, 556, 0, :east
unit :sludge, 561, 0, :east
unit :thick_sludge, 563, 0, :east
unit :archer, 566, 0, :east
unit :thick_sludge, 567, 0, :east
unit :archer, 572, 0, :east
unit :captive, 574, 0, :east
unit :archer, 575, 0, :east
unit :sludge, 576, 0, :east
unit :captive, 587, 0, :east
unit :archer, 595, 0, :east
unit :thick_sludge, 598, 0, :east
unit :sludge, 604, 0, :east
unit :thick_sludge, 606, 0, :east
unit :archer, 619, 0, :east
unit :sludge, 620, 0, :east
unit :sludge, 630, 0, :west
unit :wizard, 632, 0, :west
unit :archer, 634, 0, :west
unit :archer, 639, 0, :west
unit :archer, 648, 0, :west
unit :sludge, 650, 0, :west
unit :thick_sludge, 655, 0, :west
unit :archer, 672, 0, :west
unit :archer, 676, 0, :west
unit :captive, 682, 0, :west
unit :sludge, 685, 0, :west
unit :wizard, 687, 0, :west
unit :captive, 690, 0, :west
unit :thick_sludge, 693, 0, :west
unit :thick_sludge, 695, 0, :west
unit :archer, 702, 0, :west
unit :archer, 706, 0, :west
unit :wizard, 709, 0, :west
unit :thick_sludge, 713, 0, :west
