#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    s            a        a   ss  w a aa   a    s s   s a  S     s  a    s   s   S   Ca Sa  S s        C w         a  ws a           S  w S wCC C          S   s SS    aa aS          S               C      C a   w  Ca   s sa    aS  s  a aS a  CssS S     w     a  w  a S   s   C  w        S            aa   s            w         as    C S      s    w       S  s  s   @   S         s       C             a  C   w         C     S   C                 a                     w w S  s  a Cw CwSC        a a s  C s         s   aC C   a   w               a sa SS  C   a        ss Cs   s a  s CS   w C C      w a        CS         S  a                a        w   sw  asa           Cw   a C   C aC   ss      S  a  C   s  sC   a   C  C   C  w    ss     w sa C  S asa CS       aw     w   s  C       S  s      S  aS   a a a  Ss      a S  s w w s   s           s    a  a  S a    a      C C      C    aw>  S s     C    w  w SS sS s       w as     S               S     w s  s  w   S   C|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 971
ace_score 4855
size 971, 1
stairs 888, 0

warrior 366, 0, :east

unit :sludge, 4, 0, :east
unit :archer, 17, 0, :east
unit :archer, 26, 0, :east
unit :sludge, 30, 0, :east
unit :sludge, 31, 0, :east
unit :wizard, 34, 0, :east
unit :archer, 36, 0, :east
unit :archer, 38, 0, :east
unit :archer, 39, 0, :east
unit :archer, 43, 0, :east
unit :sludge, 48, 0, :east
unit :sludge, 50, 0, :east
unit :sludge, 54, 0, :east
unit :archer, 56, 0, :east
unit :thick_sludge, 59, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 68, 0, :east
unit :sludge, 73, 0, :east
unit :sludge, 77, 0, :east
unit :thick_sludge, 81, 0, :east
unit :captive, 85, 0, :east
unit :archer, 86, 0, :east
unit :thick_sludge, 88, 0, :east
unit :archer, 89, 0, :east
unit :thick_sludge, 92, 0, :east
unit :sludge, 94, 0, :east
unit :captive, 103, 0, :east
unit :wizard, 105, 0, :east
unit :archer, 115, 0, :east
unit :wizard, 118, 0, :east
unit :sludge, 119, 0, :east
unit :archer, 121, 0, :east
unit :thick_sludge, 133, 0, :east
unit :wizard, 136, 0, :east
unit :thick_sludge, 138, 0, :east
unit :wizard, 140, 0, :east
unit :captive, 141, 0, :east
unit :captive, 142, 0, :east
unit :captive, 144, 0, :east
unit :thick_sludge, 155, 0, :east
unit :sludge, 159, 0, :east
unit :thick_sludge, 161, 0, :east
unit :thick_sludge, 162, 0, :east
unit :archer, 167, 0, :east
unit :archer, 168, 0, :east
unit :archer, 170, 0, :east
unit :thick_sludge, 171, 0, :east
unit :thick_sludge, 182, 0, :east
unit :captive, 198, 0, :east
unit :captive, 205, 0, :east
unit :archer, 207, 0, :east
unit :wizard, 211, 0, :east
unit :captive, 214, 0, :east
unit :archer, 215, 0, :east
unit :sludge, 219, 0, :east
unit :sludge, 221, 0, :east
unit :archer, 222, 0, :east
unit :archer, 227, 0, :east
unit :thick_sludge, 228, 0, :east
unit :sludge, 231, 0, :east
unit :archer, 234, 0, :east
unit :archer, 236, 0, :east
unit :thick_sludge, 237, 0, :east
unit :archer, 239, 0, :east
unit :captive, 242, 0, :east
unit :sludge, 243, 0, :east
unit :sludge, 244, 0, :east
unit :thick_sludge, 245, 0, :east
unit :thick_sludge, 247, 0, :east
unit :wizard, 253, 0, :east
unit :archer, 259, 0, :east
unit :wizard, 262, 0, :east
unit :archer, 265, 0, :east
unit :thick_sludge, 267, 0, :east
unit :sludge, 271, 0, :east
unit :captive, 275, 0, :east
unit :wizard, 278, 0, :east
unit :thick_sludge, 287, 0, :east
unit :archer, 300, 0, :east
unit :archer, 301, 0, :east
unit :sludge, 305, 0, :east
unit :wizard, 318, 0, :east
unit :archer, 328, 0, :east
unit :sludge, 329, 0, :east
unit :captive, 334, 0, :east
unit :thick_sludge, 336, 0, :east
unit :sludge, 343, 0, :east
unit :wizard, 348, 0, :east
unit :thick_sludge, 356, 0, :east
unit :sludge, 359, 0, :east
unit :sludge, 362, 0, :east
unit :thick_sludge, 370, 0, :west
unit :sludge, 380, 0, :west
unit :captive, 388, 0, :west
unit :archer, 402, 0, :west
unit :captive, 405, 0, :west
unit :wizard, 409, 0, :west
unit :captive, 419, 0, :west
unit :thick_sludge, 425, 0, :west
unit :captive, 429, 0, :west
unit :archer, 447, 0, :west
unit :wizard, 469, 0, :west
unit :wizard, 471, 0, :west
unit :thick_sludge, 473, 0, :west
unit :sludge, 476, 0, :west
unit :archer, 479, 0, :west
unit :captive, 481, 0, :west
unit :wizard, 482, 0, :west
unit :captive, 484, 0, :west
unit :wizard, 485, 0, :west
unit :thick_sludge, 486, 0, :west
unit :captive, 487, 0, :west
unit :archer, 496, 0, :west
unit :archer, 498, 0, :west
unit :sludge, 500, 0, :west
unit :captive, 503, 0, :west
unit :sludge, 505, 0, :west
unit :sludge, 515, 0, :west
unit :archer, 519, 0, :west
unit :captive, 520, 0, :west
unit :captive, 522, 0, :west
unit :archer, 526, 0, :west
unit :wizard, 530, 0, :west
unit :archer, 546, 0, :west
unit :sludge, 548, 0, :west
unit :archer, 549, 0, :west
unit :thick_sludge, 551, 0, :west
unit :thick_sludge, 552, 0, :west
unit :captive, 555, 0, :west
unit :archer, 559, 0, :west
unit :sludge, 568, 0, :west
unit :sludge, 569, 0, :west
unit :captive, 571, 0, :west
unit :sludge, 572, 0, :west
unit :sludge, 576, 0, :west
unit :archer, 578, 0, :west
unit :sludge, 581, 0, :west
unit :captive, 583, 0, :west
unit :thick_sludge, 584, 0, :west
unit :wizard, 588, 0, :west
unit :captive, 590, 0, :west
unit :captive, 592, 0, :west
unit :wizard, 599, 0, :west
unit :archer, 601, 0, :west
unit :captive, 610, 0, :west
unit :thick_sludge, 611, 0, :west
unit :thick_sludge, 621, 0, :west
unit :archer, 624, 0, :west
unit :archer, 641, 0, :west
unit :wizard, 650, 0, :west
unit :sludge, 654, 0, :west
unit :wizard, 655, 0, :west
unit :archer, 658, 0, :west
unit :sludge, 659, 0, :west
unit :archer, 660, 0, :west
unit :captive, 672, 0, :west
unit :wizard, 673, 0, :west
unit :archer, 677, 0, :west
unit :captive, 679, 0, :west
unit :captive, 683, 0, :west
unit :archer, 685, 0, :west
unit :captive, 686, 0, :west
unit :sludge, 690, 0, :west
unit :sludge, 691, 0, :west
unit :thick_sludge, 698, 0, :west
unit :archer, 701, 0, :west
unit :captive, 704, 0, :west
unit :sludge, 708, 0, :west
unit :sludge, 711, 0, :west
unit :captive, 712, 0, :west
unit :archer, 716, 0, :west
unit :captive, 720, 0, :west
unit :captive, 723, 0, :west
unit :captive, 727, 0, :west
unit :wizard, 730, 0, :west
unit :sludge, 735, 0, :west
unit :sludge, 736, 0, :west
unit :wizard, 742, 0, :west
unit :sludge, 744, 0, :west
unit :archer, 745, 0, :west
unit :captive, 747, 0, :west
unit :thick_sludge, 750, 0, :west
unit :archer, 752, 0, :west
unit :sludge, 753, 0, :west
unit :archer, 754, 0, :west
unit :captive, 756, 0, :west
unit :thick_sludge, 757, 0, :west
unit :archer, 765, 0, :west
unit :wizard, 766, 0, :west
unit :wizard, 772, 0, :west
unit :sludge, 776, 0, :west
unit :captive, 779, 0, :west
unit :thick_sludge, 787, 0, :west
unit :sludge, 790, 0, :west
unit :thick_sludge, 797, 0, :west
unit :archer, 800, 0, :west
unit :thick_sludge, 801, 0, :west
unit :archer, 805, 0, :west
unit :archer, 807, 0, :west
unit :archer, 809, 0, :west
unit :thick_sludge, 812, 0, :west
unit :sludge, 813, 0, :west
unit :archer, 820, 0, :west
unit :thick_sludge, 822, 0, :west
unit :sludge, 825, 0, :west
unit :wizard, 827, 0, :west
unit :wizard, 829, 0, :west
unit :sludge, 831, 0, :west
unit :sludge, 835, 0, :west
unit :sludge, 847, 0, :west
unit :archer, 852, 0, :west
unit :archer, 855, 0, :west
unit :thick_sludge, 858, 0, :west
unit :archer, 860, 0, :west
unit :archer, 865, 0, :west
unit :captive, 872, 0, :west
unit :captive, 874, 0, :west
unit :captive, 881, 0, :west
unit :archer, 886, 0, :west
unit :wizard, 887, 0, :west
unit :thick_sludge, 891, 0, :west
unit :sludge, 893, 0, :west
unit :captive, 899, 0, :west
unit :wizard, 904, 0, :west
unit :wizard, 907, 0, :west
unit :thick_sludge, 909, 0, :west
unit :thick_sludge, 910, 0, :west
unit :sludge, 912, 0, :west
unit :thick_sludge, 913, 0, :west
unit :sludge, 915, 0, :west
unit :wizard, 923, 0, :west
unit :archer, 925, 0, :west
unit :sludge, 926, 0, :west
unit :thick_sludge, 932, 0, :west
unit :thick_sludge, 948, 0, :west
unit :wizard, 954, 0, :west
unit :sludge, 956, 0, :west
unit :sludge, 959, 0, :west
unit :wizard, 962, 0, :west
unit :thick_sludge, 966, 0, :west
unit :captive, 970, 0, :west
