#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  sS S  s  S        w s S a S   s    wS w C sS        CC          s  a     a   C C w    C   a   S     C     w                s  a           aaS C        aSS     Ss s     S      S S  w   s  s   C C Ss    aw     s            a  s         wCs  C    S    SS    C s  w a  S           S  S      s  SC ws   w          a    sC       S         w             @   a C aS  Sw     s    C        a   w  aa    C  w          S    sS   s   sCa sa  a s     C S   s  w a   s     >a S  SC              C C  w              S  s awC w a      C   a s   w        s C   s CC        a  S      s  w      w s    s        w s     a  a   CC      w   C Cw   a    S   C CSS C S             S     s  C w       S SaC w   SsC   s w          a  C   |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 713
ace_score 3565
size 713, 1
stairs 460, 0

warrior 349, 0, :east

unit :sludge, 2, 0, :east
unit :thick_sludge, 3, 0, :east
unit :thick_sludge, 5, 0, :east
unit :sludge, 8, 0, :east
unit :thick_sludge, 11, 0, :east
unit :wizard, 20, 0, :east
unit :sludge, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :archer, 26, 0, :east
unit :thick_sludge, 28, 0, :east
unit :sludge, 32, 0, :east
unit :wizard, 37, 0, :east
unit :thick_sludge, 38, 0, :east
unit :wizard, 40, 0, :east
unit :captive, 42, 0, :east
unit :sludge, 44, 0, :east
unit :thick_sludge, 45, 0, :east
unit :captive, 54, 0, :east
unit :captive, 55, 0, :east
unit :sludge, 66, 0, :east
unit :archer, 69, 0, :east
unit :archer, 75, 0, :east
unit :captive, 79, 0, :east
unit :captive, 81, 0, :east
unit :wizard, 83, 0, :east
unit :captive, 88, 0, :east
unit :archer, 92, 0, :east
unit :thick_sludge, 96, 0, :east
unit :captive, 102, 0, :east
unit :wizard, 108, 0, :east
unit :sludge, 125, 0, :east
unit :archer, 128, 0, :east
unit :archer, 140, 0, :east
unit :archer, 141, 0, :east
unit :thick_sludge, 142, 0, :east
unit :captive, 144, 0, :east
unit :archer, 153, 0, :east
unit :thick_sludge, 154, 0, :east
unit :thick_sludge, 155, 0, :east
unit :thick_sludge, 161, 0, :east
unit :sludge, 162, 0, :east
unit :sludge, 164, 0, :east
unit :thick_sludge, 170, 0, :east
unit :thick_sludge, 177, 0, :east
unit :thick_sludge, 179, 0, :east
unit :wizard, 182, 0, :east
unit :sludge, 186, 0, :east
unit :sludge, 189, 0, :east
unit :captive, 193, 0, :east
unit :captive, 195, 0, :east
unit :thick_sludge, 197, 0, :east
unit :sludge, 198, 0, :east
unit :archer, 203, 0, :east
unit :wizard, 204, 0, :east
unit :sludge, 210, 0, :east
unit :archer, 223, 0, :east
unit :sludge, 226, 0, :east
unit :wizard, 236, 0, :east
unit :captive, 237, 0, :east
unit :sludge, 238, 0, :east
unit :captive, 241, 0, :east
unit :thick_sludge, 246, 0, :east
unit :thick_sludge, 251, 0, :east
unit :thick_sludge, 252, 0, :east
unit :captive, 257, 0, :east
unit :sludge, 259, 0, :east
unit :wizard, 262, 0, :east
unit :archer, 264, 0, :east
unit :thick_sludge, 267, 0, :east
unit :thick_sludge, 279, 0, :east
unit :thick_sludge, 282, 0, :east
unit :sludge, 289, 0, :east
unit :thick_sludge, 292, 0, :east
unit :captive, 293, 0, :east
unit :wizard, 295, 0, :east
unit :sludge, 296, 0, :east
unit :wizard, 300, 0, :east
unit :archer, 311, 0, :east
unit :sludge, 316, 0, :east
unit :captive, 317, 0, :east
unit :thick_sludge, 325, 0, :east
unit :wizard, 335, 0, :east
unit :archer, 353, 0, :west
unit :captive, 355, 0, :west
unit :archer, 357, 0, :west
unit :thick_sludge, 358, 0, :west
unit :thick_sludge, 361, 0, :west
unit :wizard, 362, 0, :west
unit :sludge, 368, 0, :west
unit :captive, 373, 0, :west
unit :archer, 382, 0, :west
unit :wizard, 386, 0, :west
unit :archer, 389, 0, :west
unit :archer, 390, 0, :west
unit :captive, 395, 0, :west
unit :wizard, 398, 0, :west
unit :thick_sludge, 409, 0, :west
unit :sludge, 414, 0, :west
unit :thick_sludge, 415, 0, :west
unit :sludge, 419, 0, :west
unit :sludge, 423, 0, :west
unit :captive, 424, 0, :west
unit :archer, 425, 0, :west
unit :sludge, 427, 0, :west
unit :archer, 428, 0, :west
unit :archer, 431, 0, :west
unit :sludge, 433, 0, :west
unit :captive, 439, 0, :west
unit :thick_sludge, 441, 0, :west
unit :sludge, 445, 0, :west
unit :wizard, 448, 0, :west
unit :archer, 450, 0, :west
unit :sludge, 454, 0, :west
unit :archer, 461, 0, :west
unit :thick_sludge, 463, 0, :west
unit :thick_sludge, 466, 0, :west
unit :captive, 467, 0, :west
unit :captive, 482, 0, :west
unit :captive, 484, 0, :west
unit :wizard, 487, 0, :west
unit :thick_sludge, 502, 0, :west
unit :sludge, 505, 0, :west
unit :archer, 507, 0, :west
unit :wizard, 508, 0, :west
unit :captive, 509, 0, :west
unit :wizard, 511, 0, :west
unit :archer, 513, 0, :west
unit :captive, 520, 0, :west
unit :archer, 524, 0, :west
unit :sludge, 526, 0, :west
unit :wizard, 530, 0, :west
unit :sludge, 539, 0, :west
unit :captive, 541, 0, :west
unit :sludge, 545, 0, :west
unit :captive, 547, 0, :west
unit :captive, 548, 0, :west
unit :archer, 557, 0, :west
unit :thick_sludge, 560, 0, :west
unit :sludge, 567, 0, :west
unit :wizard, 570, 0, :west
unit :wizard, 577, 0, :west
unit :sludge, 579, 0, :west
unit :sludge, 584, 0, :west
unit :wizard, 593, 0, :west
unit :sludge, 595, 0, :west
unit :archer, 601, 0, :west
unit :archer, 604, 0, :west
unit :captive, 608, 0, :west
unit :captive, 609, 0, :west
unit :wizard, 616, 0, :west
unit :captive, 620, 0, :west
unit :captive, 622, 0, :west
unit :wizard, 623, 0, :west
unit :archer, 627, 0, :west
unit :thick_sludge, 632, 0, :west
unit :captive, 636, 0, :west
unit :captive, 638, 0, :west
unit :thick_sludge, 639, 0, :west
unit :thick_sludge, 640, 0, :west
unit :captive, 642, 0, :west
unit :thick_sludge, 644, 0, :west
unit :thick_sludge, 658, 0, :west
unit :sludge, 664, 0, :west
unit :captive, 667, 0, :west
unit :wizard, 669, 0, :west
unit :thick_sludge, 677, 0, :west
unit :thick_sludge, 679, 0, :west
unit :archer, 680, 0, :west
unit :captive, 681, 0, :west
unit :wizard, 683, 0, :west
unit :thick_sludge, 687, 0, :west
unit :sludge, 688, 0, :west
unit :captive, 689, 0, :west
unit :sludge, 693, 0, :west
unit :wizard, 695, 0, :west
unit :archer, 706, 0, :west
unit :captive, 709, 0, :west
