#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C as         w     a w       aC CCC    wS C S   s  C  S Sw  S  S S     s s  S   C         C a    s S  Sw     w  S   S      a    a aS    a  w C      wC       S    @  C   a C a      s s       s      a          w       a  a    w    C      C sSa    C  ss  S  CC   w          a CSw  S s C    a C   a   s C s    w S S  S           SC a         a     Ss        S  SS  C    a   s   a   C Ss   w      a  w  s   S        Cw             s  wa  a      C S w ss a S    w    SS w a           a         Sw       Ca                    S       C     s     s           aC   S S  C   C  C S     S   CC   wa       C   S      w      C w    C   S       C      C C s         S sa   s   CS   sC  C          aS  C     a w   s              a s w      s s a  S> s  S   a  CS   w    |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 755
ace_score 3775
size 755, 1
stairs 733, 0

warrior 162, 0, :east

unit :captive, 0, 0, :east
unit :archer, 2, 0, :east
unit :sludge, 3, 0, :east
unit :wizard, 13, 0, :east
unit :archer, 19, 0, :east
unit :wizard, 21, 0, :east
unit :archer, 29, 0, :east
unit :captive, 30, 0, :east
unit :captive, 32, 0, :east
unit :captive, 33, 0, :east
unit :captive, 34, 0, :east
unit :wizard, 39, 0, :east
unit :thick_sludge, 40, 0, :east
unit :captive, 42, 0, :east
unit :thick_sludge, 44, 0, :east
unit :sludge, 48, 0, :east
unit :captive, 51, 0, :east
unit :thick_sludge, 54, 0, :east
unit :thick_sludge, 56, 0, :east
unit :wizard, 57, 0, :east
unit :thick_sludge, 60, 0, :east
unit :thick_sludge, 63, 0, :east
unit :thick_sludge, 65, 0, :east
unit :sludge, 71, 0, :east
unit :sludge, 73, 0, :east
unit :thick_sludge, 76, 0, :east
unit :captive, 80, 0, :east
unit :captive, 90, 0, :east
unit :archer, 92, 0, :east
unit :sludge, 97, 0, :east
unit :thick_sludge, 99, 0, :east
unit :thick_sludge, 102, 0, :east
unit :wizard, 103, 0, :east
unit :wizard, 109, 0, :east
unit :thick_sludge, 112, 0, :east
unit :thick_sludge, 116, 0, :east
unit :archer, 123, 0, :east
unit :archer, 128, 0, :east
unit :archer, 130, 0, :east
unit :thick_sludge, 131, 0, :east
unit :archer, 136, 0, :east
unit :wizard, 139, 0, :east
unit :captive, 141, 0, :east
unit :wizard, 148, 0, :east
unit :captive, 149, 0, :east
unit :thick_sludge, 157, 0, :east
unit :captive, 165, 0, :west
unit :archer, 169, 0, :west
unit :captive, 171, 0, :west
unit :archer, 173, 0, :west
unit :sludge, 180, 0, :west
unit :sludge, 182, 0, :west
unit :sludge, 190, 0, :west
unit :archer, 197, 0, :west
unit :wizard, 208, 0, :west
unit :archer, 216, 0, :west
unit :archer, 219, 0, :west
unit :wizard, 224, 0, :west
unit :captive, 229, 0, :west
unit :captive, 236, 0, :west
unit :sludge, 238, 0, :west
unit :thick_sludge, 239, 0, :west
unit :archer, 240, 0, :west
unit :captive, 245, 0, :west
unit :sludge, 248, 0, :west
unit :sludge, 249, 0, :west
unit :thick_sludge, 252, 0, :west
unit :captive, 255, 0, :west
unit :captive, 256, 0, :west
unit :wizard, 260, 0, :west
unit :archer, 271, 0, :west
unit :captive, 273, 0, :west
unit :thick_sludge, 274, 0, :west
unit :wizard, 275, 0, :west
unit :thick_sludge, 278, 0, :west
unit :sludge, 280, 0, :west
unit :captive, 282, 0, :west
unit :archer, 287, 0, :west
unit :captive, 289, 0, :west
unit :archer, 293, 0, :west
unit :sludge, 297, 0, :west
unit :captive, 299, 0, :west
unit :sludge, 301, 0, :west
unit :wizard, 306, 0, :west
unit :thick_sludge, 308, 0, :west
unit :thick_sludge, 310, 0, :west
unit :thick_sludge, 313, 0, :west
unit :thick_sludge, 325, 0, :west
unit :captive, 326, 0, :west
unit :archer, 328, 0, :west
unit :archer, 338, 0, :west
unit :thick_sludge, 344, 0, :west
unit :sludge, 345, 0, :west
unit :thick_sludge, 354, 0, :west
unit :thick_sludge, 357, 0, :west
unit :thick_sludge, 358, 0, :west
unit :captive, 361, 0, :west
unit :archer, 366, 0, :west
unit :sludge, 370, 0, :west
unit :archer, 374, 0, :west
unit :captive, 378, 0, :west
unit :thick_sludge, 380, 0, :west
unit :sludge, 381, 0, :west
unit :wizard, 385, 0, :west
unit :archer, 392, 0, :west
unit :wizard, 395, 0, :west
unit :sludge, 398, 0, :west
unit :thick_sludge, 402, 0, :west
unit :captive, 411, 0, :west
unit :wizard, 412, 0, :west
unit :sludge, 426, 0, :west
unit :wizard, 429, 0, :west
unit :archer, 430, 0, :west
unit :archer, 433, 0, :west
unit :captive, 440, 0, :west
unit :thick_sludge, 442, 0, :west
unit :wizard, 444, 0, :west
unit :sludge, 446, 0, :west
unit :sludge, 447, 0, :west
unit :archer, 449, 0, :west
unit :thick_sludge, 451, 0, :west
unit :wizard, 456, 0, :west
unit :thick_sludge, 461, 0, :west
unit :thick_sludge, 462, 0, :west
unit :wizard, 464, 0, :west
unit :archer, 466, 0, :west
unit :archer, 478, 0, :west
unit :thick_sludge, 488, 0, :west
unit :wizard, 489, 0, :west
unit :captive, 497, 0, :west
unit :archer, 498, 0, :west
unit :thick_sludge, 519, 0, :west
unit :captive, 527, 0, :west
unit :sludge, 533, 0, :west
unit :sludge, 539, 0, :west
unit :archer, 551, 0, :west
unit :captive, 552, 0, :west
unit :thick_sludge, 556, 0, :west
unit :thick_sludge, 558, 0, :west
unit :captive, 561, 0, :west
unit :captive, 565, 0, :west
unit :captive, 568, 0, :west
unit :thick_sludge, 570, 0, :west
unit :thick_sludge, 576, 0, :west
unit :captive, 580, 0, :west
unit :captive, 581, 0, :west
unit :wizard, 585, 0, :west
unit :archer, 586, 0, :west
unit :captive, 594, 0, :west
unit :thick_sludge, 598, 0, :west
unit :wizard, 605, 0, :west
unit :captive, 612, 0, :west
unit :wizard, 614, 0, :west
unit :captive, 619, 0, :west
unit :thick_sludge, 623, 0, :west
unit :captive, 631, 0, :west
unit :captive, 638, 0, :west
unit :captive, 640, 0, :west
unit :sludge, 642, 0, :west
unit :thick_sludge, 652, 0, :west
unit :sludge, 654, 0, :west
unit :archer, 655, 0, :west
unit :sludge, 659, 0, :west
unit :captive, 663, 0, :west
unit :thick_sludge, 664, 0, :west
unit :sludge, 668, 0, :west
unit :captive, 669, 0, :west
unit :captive, 672, 0, :west
unit :archer, 683, 0, :west
unit :thick_sludge, 684, 0, :west
unit :captive, 687, 0, :west
unit :archer, 693, 0, :west
unit :wizard, 695, 0, :west
unit :sludge, 699, 0, :west
unit :archer, 714, 0, :west
unit :sludge, 716, 0, :west
unit :wizard, 718, 0, :west
unit :sludge, 725, 0, :west
unit :sludge, 727, 0, :west
unit :archer, 729, 0, :west
unit :thick_sludge, 732, 0, :west
unit :sludge, 735, 0, :west
unit :thick_sludge, 738, 0, :west
unit :archer, 742, 0, :west
unit :captive, 745, 0, :west
unit :thick_sludge, 746, 0, :west
unit :wizard, 750, 0, :west
