#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C   Cw    aw         C    a  w s C     w   C C        w S    w   S  as   SS>        CS  a   S   Sa   S  a s    CsCa   a     a   S      ss a               S aa    C CS    ss  C        S  S  a  s     asa   a a     sw  a    @  w   S S SS    Sa       C       S     SC  s         a s  S S      wC  S    s    a     ss  s          s C  C S     s w  SCC       w s       S     s   aC    sC   S       C             a           w      w   aw w     a    a     S      SS            S   S     s C a SC S   ws w C     SC    w     S C    w   w   w       CS     C S S S   C   S  CsaS  s   s   Ca a  s SC aC  C          s  Ss C     s w s a w sss aa  S as           a a as  S      a  s   w s C     w as  s                  s   C         S w    S       w w       C      sa     C S         a         w    a    C  SS  s S   s  S sa w w      s  C          S w       s   a   s  ws             S             w          w                    w   S            saS a    a    a       C sSw  s     |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 968
ace_score 4840
size 968, 1
stairs 76, 0

warrior 222, 0, :east

unit :captive, 1, 0, :east
unit :captive, 5, 0, :east
unit :wizard, 6, 0, :east
unit :archer, 11, 0, :east
unit :wizard, 12, 0, :east
unit :captive, 22, 0, :east
unit :archer, 27, 0, :east
unit :wizard, 30, 0, :east
unit :sludge, 32, 0, :east
unit :captive, 34, 0, :east
unit :wizard, 40, 0, :east
unit :captive, 44, 0, :east
unit :captive, 46, 0, :east
unit :wizard, 55, 0, :east
unit :thick_sludge, 57, 0, :east
unit :wizard, 62, 0, :east
unit :thick_sludge, 66, 0, :east
unit :archer, 69, 0, :east
unit :sludge, 70, 0, :east
unit :thick_sludge, 74, 0, :east
unit :thick_sludge, 75, 0, :east
unit :captive, 85, 0, :east
unit :thick_sludge, 86, 0, :east
unit :archer, 89, 0, :east
unit :thick_sludge, 93, 0, :east
unit :thick_sludge, 97, 0, :east
unit :archer, 98, 0, :east
unit :thick_sludge, 102, 0, :east
unit :archer, 105, 0, :east
unit :sludge, 107, 0, :east
unit :captive, 112, 0, :east
unit :sludge, 113, 0, :east
unit :captive, 114, 0, :east
unit :archer, 115, 0, :east
unit :archer, 119, 0, :east
unit :archer, 125, 0, :east
unit :thick_sludge, 129, 0, :east
unit :sludge, 136, 0, :east
unit :sludge, 137, 0, :east
unit :archer, 139, 0, :east
unit :thick_sludge, 155, 0, :east
unit :archer, 157, 0, :east
unit :archer, 158, 0, :east
unit :captive, 163, 0, :east
unit :captive, 165, 0, :east
unit :thick_sludge, 166, 0, :east
unit :sludge, 171, 0, :east
unit :sludge, 172, 0, :east
unit :captive, 175, 0, :east
unit :thick_sludge, 184, 0, :east
unit :thick_sludge, 187, 0, :east
unit :archer, 190, 0, :east
unit :sludge, 193, 0, :east
unit :archer, 199, 0, :east
unit :sludge, 200, 0, :east
unit :archer, 201, 0, :east
unit :archer, 205, 0, :east
unit :archer, 207, 0, :east
unit :sludge, 213, 0, :east
unit :wizard, 214, 0, :east
unit :archer, 217, 0, :east
unit :wizard, 225, 0, :west
unit :thick_sludge, 229, 0, :west
unit :thick_sludge, 231, 0, :west
unit :thick_sludge, 233, 0, :west
unit :thick_sludge, 234, 0, :west
unit :thick_sludge, 239, 0, :west
unit :archer, 240, 0, :west
unit :captive, 248, 0, :west
unit :thick_sludge, 256, 0, :west
unit :thick_sludge, 262, 0, :west
unit :captive, 263, 0, :west
unit :sludge, 266, 0, :west
unit :archer, 276, 0, :west
unit :sludge, 278, 0, :west
unit :thick_sludge, 281, 0, :west
unit :thick_sludge, 283, 0, :west
unit :wizard, 290, 0, :west
unit :captive, 291, 0, :west
unit :thick_sludge, 294, 0, :west
unit :sludge, 299, 0, :west
unit :archer, 304, 0, :west
unit :sludge, 310, 0, :west
unit :sludge, 311, 0, :west
unit :sludge, 314, 0, :west
unit :sludge, 325, 0, :west
unit :captive, 327, 0, :west
unit :captive, 330, 0, :west
unit :thick_sludge, 332, 0, :west
unit :sludge, 338, 0, :west
unit :wizard, 340, 0, :west
unit :thick_sludge, 343, 0, :west
unit :captive, 344, 0, :west
unit :captive, 345, 0, :west
unit :wizard, 353, 0, :west
unit :sludge, 355, 0, :west
unit :thick_sludge, 363, 0, :west
unit :sludge, 369, 0, :west
unit :archer, 373, 0, :west
unit :captive, 374, 0, :west
unit :sludge, 379, 0, :west
unit :captive, 380, 0, :west
unit :thick_sludge, 384, 0, :west
unit :captive, 392, 0, :west
unit :archer, 406, 0, :west
unit :wizard, 418, 0, :west
unit :wizard, 425, 0, :west
unit :archer, 429, 0, :west
unit :wizard, 430, 0, :west
unit :wizard, 432, 0, :west
unit :archer, 438, 0, :west
unit :archer, 443, 0, :west
unit :thick_sludge, 449, 0, :west
unit :thick_sludge, 456, 0, :west
unit :thick_sludge, 457, 0, :west
unit :thick_sludge, 470, 0, :west
unit :thick_sludge, 474, 0, :west
unit :sludge, 480, 0, :west
unit :captive, 482, 0, :west
unit :archer, 484, 0, :west
unit :thick_sludge, 486, 0, :west
unit :captive, 487, 0, :west
unit :thick_sludge, 489, 0, :west
unit :wizard, 493, 0, :west
unit :sludge, 494, 0, :west
unit :wizard, 496, 0, :west
unit :captive, 498, 0, :west
unit :thick_sludge, 504, 0, :west
unit :captive, 505, 0, :west
unit :wizard, 510, 0, :west
unit :thick_sludge, 516, 0, :west
unit :captive, 518, 0, :west
unit :wizard, 523, 0, :west
unit :wizard, 527, 0, :west
unit :wizard, 531, 0, :west
unit :captive, 539, 0, :west
unit :thick_sludge, 540, 0, :west
unit :captive, 546, 0, :west
unit :thick_sludge, 548, 0, :west
unit :thick_sludge, 550, 0, :west
unit :thick_sludge, 552, 0, :west
unit :captive, 556, 0, :west
unit :thick_sludge, 560, 0, :west
unit :captive, 563, 0, :west
unit :sludge, 564, 0, :west
unit :archer, 565, 0, :west
unit :thick_sludge, 566, 0, :west
unit :sludge, 569, 0, :west
unit :sludge, 573, 0, :west
unit :captive, 577, 0, :west
unit :archer, 578, 0, :west
unit :archer, 580, 0, :west
unit :sludge, 583, 0, :west
unit :thick_sludge, 585, 0, :west
unit :captive, 586, 0, :west
unit :archer, 588, 0, :west
unit :captive, 589, 0, :west
unit :captive, 592, 0, :west
unit :sludge, 603, 0, :west
unit :thick_sludge, 606, 0, :west
unit :sludge, 607, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 615, 0, :west
unit :wizard, 617, 0, :west
unit :sludge, 619, 0, :west
unit :archer, 621, 0, :west
unit :wizard, 623, 0, :west
unit :sludge, 625, 0, :west
unit :sludge, 626, 0, :west
unit :sludge, 627, 0, :west
unit :archer, 629, 0, :west
unit :archer, 630, 0, :west
unit :thick_sludge, 633, 0, :west
unit :archer, 635, 0, :west
unit :sludge, 636, 0, :west
unit :archer, 648, 0, :west
unit :archer, 650, 0, :west
unit :archer, 652, 0, :west
unit :sludge, 653, 0, :west
unit :thick_sludge, 656, 0, :west
unit :archer, 663, 0, :west
unit :sludge, 666, 0, :west
unit :wizard, 670, 0, :west
unit :sludge, 672, 0, :west
unit :captive, 674, 0, :west
unit :wizard, 680, 0, :west
unit :archer, 682, 0, :west
unit :sludge, 683, 0, :west
unit :sludge, 686, 0, :west
unit :sludge, 705, 0, :west
unit :captive, 709, 0, :west
unit :thick_sludge, 719, 0, :west
unit :wizard, 721, 0, :west
unit :thick_sludge, 726, 0, :west
unit :wizard, 734, 0, :west
unit :wizard, 736, 0, :west
unit :captive, 744, 0, :west
unit :sludge, 751, 0, :west
unit :archer, 752, 0, :west
unit :captive, 758, 0, :west
unit :thick_sludge, 760, 0, :west
unit :archer, 770, 0, :west
unit :wizard, 780, 0, :west
unit :archer, 785, 0, :west
unit :captive, 790, 0, :west
unit :thick_sludge, 793, 0, :west
unit :thick_sludge, 794, 0, :west
unit :sludge, 797, 0, :west
unit :thick_sludge, 799, 0, :west
unit :sludge, 803, 0, :west
unit :thick_sludge, 806, 0, :west
unit :sludge, 808, 0, :west
unit :archer, 809, 0, :west
unit :wizard, 811, 0, :west
unit :wizard, 813, 0, :west
unit :sludge, 820, 0, :west
unit :captive, 823, 0, :west
unit :thick_sludge, 834, 0, :west
unit :wizard, 836, 0, :west
unit :sludge, 844, 0, :west
unit :archer, 848, 0, :west
unit :sludge, 852, 0, :west
unit :wizard, 855, 0, :west
unit :sludge, 856, 0, :west
unit :thick_sludge, 870, 0, :west
unit :wizard, 884, 0, :west
unit :wizard, 895, 0, :west
unit :wizard, 916, 0, :west
unit :thick_sludge, 920, 0, :west
unit :sludge, 933, 0, :west
unit :archer, 934, 0, :west
unit :thick_sludge, 935, 0, :west
unit :archer, 937, 0, :west
unit :archer, 942, 0, :west
unit :archer, 947, 0, :west
unit :captive, 955, 0, :west
unit :sludge, 957, 0, :west
unit :thick_sludge, 958, 0, :west
unit :wizard, 959, 0, :west
unit :sludge, 962, 0, :west
