#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     s C Ca  S w  w s  SSs   s sa                    a C      >   w     a S    s a    a CSs  C     C s       a     a       a    w a     w  aC   Cw     w w  a  w              S    aaaSSs s s w      s  C    SC           s s   a  a       w    s    S    C     Sa w   C   a w w sa   a a S        w    aa   C      s S  S   w      a   w a   w  C     s   a   S  a    S  a   w              S  s       S  s s             s w  s   s  as   C   w  s   Cw  C        s  w      sa s      SwS  w  S   s a s  SC      w                    S      ss      ws C S   s        s a        C w S   s    a   sa   C   a   S  a Sa  C    a        s     C a  a  C Saa  C  s                C   C           C Ca      s   a w s    s   w a C  as  C s      ws  S                 S   aw       Ss  C    a S w  S   Ss  @   w      C  a      s  s  a w s      C       aC w a  SC a    C    a  w             s       a    a    w S   wC  a   a      s Ca        C |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 917
ace_score 4585
size 917, 1
stairs 62, 0

warrior 780, 0, :east

unit :sludge, 5, 0, :east
unit :captive, 7, 0, :east
unit :captive, 9, 0, :east
unit :archer, 10, 0, :east
unit :thick_sludge, 13, 0, :east
unit :wizard, 15, 0, :east
unit :wizard, 18, 0, :east
unit :sludge, 20, 0, :east
unit :thick_sludge, 23, 0, :east
unit :thick_sludge, 24, 0, :east
unit :sludge, 25, 0, :east
unit :sludge, 29, 0, :east
unit :sludge, 31, 0, :east
unit :archer, 32, 0, :east
unit :archer, 53, 0, :east
unit :captive, 55, 0, :east
unit :wizard, 66, 0, :east
unit :archer, 72, 0, :east
unit :thick_sludge, 74, 0, :east
unit :sludge, 79, 0, :east
unit :archer, 81, 0, :east
unit :archer, 86, 0, :east
unit :captive, 88, 0, :east
unit :thick_sludge, 89, 0, :east
unit :sludge, 90, 0, :east
unit :captive, 93, 0, :east
unit :captive, 99, 0, :east
unit :sludge, 101, 0, :east
unit :archer, 109, 0, :east
unit :archer, 115, 0, :east
unit :archer, 123, 0, :east
unit :wizard, 128, 0, :east
unit :archer, 130, 0, :east
unit :wizard, 136, 0, :east
unit :archer, 139, 0, :east
unit :captive, 140, 0, :east
unit :captive, 144, 0, :east
unit :wizard, 145, 0, :east
unit :wizard, 151, 0, :east
unit :wizard, 153, 0, :east
unit :archer, 156, 0, :east
unit :wizard, 159, 0, :east
unit :thick_sludge, 174, 0, :east
unit :archer, 179, 0, :east
unit :archer, 180, 0, :east
unit :archer, 181, 0, :east
unit :thick_sludge, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :sludge, 184, 0, :east
unit :sludge, 186, 0, :east
unit :sludge, 188, 0, :east
unit :wizard, 190, 0, :east
unit :sludge, 197, 0, :east
unit :captive, 200, 0, :east
unit :thick_sludge, 205, 0, :east
unit :captive, 206, 0, :east
unit :sludge, 218, 0, :east
unit :sludge, 220, 0, :east
unit :archer, 224, 0, :east
unit :archer, 227, 0, :east
unit :wizard, 235, 0, :east
unit :sludge, 240, 0, :east
unit :thick_sludge, 245, 0, :east
unit :captive, 250, 0, :east
unit :thick_sludge, 256, 0, :east
unit :archer, 257, 0, :east
unit :wizard, 259, 0, :east
unit :captive, 263, 0, :east
unit :archer, 267, 0, :east
unit :wizard, 269, 0, :east
unit :wizard, 271, 0, :east
unit :sludge, 273, 0, :east
unit :archer, 274, 0, :east
unit :archer, 278, 0, :east
unit :archer, 280, 0, :east
unit :thick_sludge, 282, 0, :east
unit :wizard, 291, 0, :east
unit :archer, 296, 0, :east
unit :archer, 297, 0, :east
unit :captive, 301, 0, :east
unit :sludge, 308, 0, :east
unit :thick_sludge, 310, 0, :east
unit :thick_sludge, 313, 0, :east
unit :wizard, 317, 0, :east
unit :archer, 324, 0, :east
unit :wizard, 328, 0, :east
unit :archer, 330, 0, :east
unit :wizard, 334, 0, :east
unit :captive, 337, 0, :east
unit :sludge, 343, 0, :east
unit :archer, 347, 0, :east
unit :thick_sludge, 351, 0, :east
unit :archer, 354, 0, :east
unit :thick_sludge, 359, 0, :east
unit :archer, 362, 0, :east
unit :wizard, 366, 0, :east
unit :thick_sludge, 381, 0, :east
unit :sludge, 384, 0, :east
unit :thick_sludge, 392, 0, :east
unit :sludge, 395, 0, :east
unit :sludge, 397, 0, :east
unit :sludge, 411, 0, :east
unit :wizard, 413, 0, :east
unit :sludge, 416, 0, :east
unit :sludge, 420, 0, :east
unit :archer, 423, 0, :east
unit :sludge, 424, 0, :east
unit :captive, 428, 0, :east
unit :wizard, 432, 0, :east
unit :sludge, 435, 0, :east
unit :captive, 439, 0, :east
unit :wizard, 440, 0, :east
unit :captive, 443, 0, :east
unit :sludge, 452, 0, :east
unit :wizard, 455, 0, :east
unit :sludge, 462, 0, :east
unit :archer, 463, 0, :east
unit :sludge, 465, 0, :east
unit :thick_sludge, 472, 0, :east
unit :wizard, 473, 0, :east
unit :thick_sludge, 474, 0, :east
unit :wizard, 477, 0, :east
unit :thick_sludge, 480, 0, :east
unit :sludge, 484, 0, :east
unit :archer, 486, 0, :east
unit :sludge, 488, 0, :east
unit :thick_sludge, 491, 0, :east
unit :captive, 492, 0, :east
unit :wizard, 499, 0, :east
unit :thick_sludge, 520, 0, :east
unit :sludge, 527, 0, :east
unit :sludge, 528, 0, :east
unit :wizard, 535, 0, :east
unit :sludge, 536, 0, :east
unit :captive, 538, 0, :east
unit :thick_sludge, 540, 0, :east
unit :sludge, 544, 0, :east
unit :sludge, 553, 0, :east
unit :archer, 555, 0, :east
unit :captive, 564, 0, :east
unit :wizard, 566, 0, :east
unit :thick_sludge, 568, 0, :east
unit :sludge, 572, 0, :east
unit :archer, 577, 0, :east
unit :sludge, 581, 0, :east
unit :archer, 582, 0, :east
unit :captive, 586, 0, :east
unit :archer, 590, 0, :east
unit :thick_sludge, 594, 0, :east
unit :archer, 597, 0, :east
unit :thick_sludge, 599, 0, :east
unit :archer, 600, 0, :east
unit :captive, 603, 0, :east
unit :archer, 608, 0, :east
unit :sludge, 617, 0, :east
unit :captive, 623, 0, :east
unit :archer, 625, 0, :east
unit :archer, 628, 0, :east
unit :captive, 631, 0, :east
unit :thick_sludge, 633, 0, :east
unit :archer, 634, 0, :east
unit :archer, 635, 0, :east
unit :captive, 638, 0, :east
unit :sludge, 641, 0, :east
unit :captive, 658, 0, :east
unit :captive, 662, 0, :east
unit :captive, 674, 0, :east
unit :captive, 676, 0, :east
unit :archer, 677, 0, :east
unit :sludge, 684, 0, :east
unit :archer, 688, 0, :east
unit :wizard, 690, 0, :east
unit :sludge, 692, 0, :east
unit :sludge, 697, 0, :east
unit :wizard, 701, 0, :east
unit :archer, 703, 0, :east
unit :captive, 705, 0, :east
unit :archer, 708, 0, :east
unit :sludge, 709, 0, :east
unit :captive, 712, 0, :east
unit :sludge, 714, 0, :east
unit :wizard, 721, 0, :east
unit :sludge, 722, 0, :east
unit :thick_sludge, 725, 0, :east
unit :thick_sludge, 743, 0, :east
unit :archer, 747, 0, :east
unit :wizard, 748, 0, :east
unit :thick_sludge, 756, 0, :east
unit :sludge, 757, 0, :east
unit :captive, 760, 0, :east
unit :archer, 765, 0, :east
unit :thick_sludge, 767, 0, :east
unit :wizard, 769, 0, :east
unit :thick_sludge, 772, 0, :east
unit :thick_sludge, 776, 0, :east
unit :sludge, 777, 0, :east
unit :wizard, 784, 0, :west
unit :captive, 791, 0, :west
unit :archer, 794, 0, :west
unit :sludge, 801, 0, :west
unit :sludge, 804, 0, :west
unit :archer, 807, 0, :west
unit :wizard, 809, 0, :west
unit :sludge, 811, 0, :west
unit :captive, 818, 0, :west
unit :archer, 826, 0, :west
unit :captive, 827, 0, :west
unit :wizard, 829, 0, :west
unit :archer, 831, 0, :west
unit :thick_sludge, 834, 0, :west
unit :captive, 835, 0, :west
unit :archer, 837, 0, :west
unit :captive, 842, 0, :west
unit :archer, 847, 0, :west
unit :wizard, 850, 0, :west
unit :sludge, 864, 0, :west
unit :archer, 872, 0, :west
unit :archer, 877, 0, :west
unit :wizard, 882, 0, :west
unit :thick_sludge, 884, 0, :west
unit :wizard, 888, 0, :west
unit :captive, 889, 0, :west
unit :archer, 892, 0, :west
unit :archer, 896, 0, :west
unit :sludge, 903, 0, :west
unit :captive, 905, 0, :west
unit :archer, 906, 0, :west
unit :captive, 915, 0, :west
