#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   a    w   S           a      aw   s  C  S    C  a  w w       S          s       S      s          S      C         Cw  sS     C    aS C  S  aa a          C  a S   SS s          C  s C w  aCS      CS  s  S w   w      s s         S   asaa w   sw           C SS      a    as       s S a  sa w  a C a a  CSs   @    w   S saC  S      as  C  w  Csa  C ws    sa  a a Cs     s wSS  s S    s S    s              S               w     w S        a C   S S  S       S        C    s SS w s             a a         S a a     saa C   s  a      C aC       C C s     sC         s        w      S a        a  S      w a        w   a      a         sw    >S    S  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 648
ace_score 3240
size 648, 1
stairs 639, 0

warrior 308, 0, :east

unit :archer, 3, 0, :east
unit :wizard, 8, 0, :east
unit :thick_sludge, 12, 0, :east
unit :archer, 24, 0, :east
unit :archer, 31, 0, :east
unit :wizard, 32, 0, :east
unit :sludge, 36, 0, :east
unit :captive, 39, 0, :east
unit :thick_sludge, 42, 0, :east
unit :captive, 47, 0, :east
unit :archer, 50, 0, :east
unit :wizard, 53, 0, :east
unit :wizard, 55, 0, :east
unit :thick_sludge, 63, 0, :east
unit :sludge, 74, 0, :east
unit :thick_sludge, 82, 0, :east
unit :sludge, 89, 0, :east
unit :thick_sludge, 100, 0, :east
unit :captive, 107, 0, :east
unit :captive, 117, 0, :east
unit :wizard, 118, 0, :east
unit :sludge, 121, 0, :east
unit :thick_sludge, 122, 0, :east
unit :captive, 128, 0, :east
unit :archer, 133, 0, :east
unit :thick_sludge, 134, 0, :east
unit :captive, 136, 0, :east
unit :thick_sludge, 139, 0, :east
unit :archer, 142, 0, :east
unit :archer, 143, 0, :east
unit :archer, 145, 0, :east
unit :captive, 156, 0, :east
unit :archer, 159, 0, :east
unit :thick_sludge, 161, 0, :east
unit :thick_sludge, 165, 0, :east
unit :thick_sludge, 166, 0, :east
unit :sludge, 168, 0, :east
unit :captive, 179, 0, :east
unit :sludge, 182, 0, :east
unit :captive, 184, 0, :east
unit :wizard, 186, 0, :east
unit :archer, 189, 0, :east
unit :captive, 190, 0, :east
unit :thick_sludge, 191, 0, :east
unit :captive, 198, 0, :east
unit :thick_sludge, 199, 0, :east
unit :sludge, 202, 0, :east
unit :thick_sludge, 205, 0, :east
unit :wizard, 207, 0, :east
unit :wizard, 211, 0, :east
unit :sludge, 218, 0, :east
unit :sludge, 220, 0, :east
unit :thick_sludge, 230, 0, :east
unit :archer, 234, 0, :east
unit :sludge, 235, 0, :east
unit :archer, 236, 0, :east
unit :archer, 237, 0, :east
unit :wizard, 239, 0, :east
unit :sludge, 243, 0, :east
unit :wizard, 244, 0, :east
unit :captive, 256, 0, :east
unit :thick_sludge, 258, 0, :east
unit :thick_sludge, 259, 0, :east
unit :archer, 266, 0, :east
unit :archer, 271, 0, :east
unit :sludge, 272, 0, :east
unit :sludge, 280, 0, :east
unit :thick_sludge, 282, 0, :east
unit :archer, 284, 0, :east
unit :sludge, 287, 0, :east
unit :archer, 288, 0, :east
unit :wizard, 290, 0, :east
unit :archer, 293, 0, :east
unit :captive, 295, 0, :east
unit :archer, 297, 0, :east
unit :archer, 299, 0, :east
unit :captive, 302, 0, :east
unit :thick_sludge, 303, 0, :east
unit :sludge, 304, 0, :east
unit :wizard, 313, 0, :west
unit :thick_sludge, 317, 0, :west
unit :sludge, 319, 0, :west
unit :archer, 320, 0, :west
unit :captive, 321, 0, :west
unit :thick_sludge, 324, 0, :west
unit :archer, 331, 0, :west
unit :sludge, 332, 0, :west
unit :captive, 335, 0, :west
unit :wizard, 338, 0, :west
unit :captive, 341, 0, :west
unit :sludge, 342, 0, :west
unit :archer, 343, 0, :west
unit :captive, 346, 0, :west
unit :wizard, 348, 0, :west
unit :sludge, 349, 0, :west
unit :sludge, 354, 0, :west
unit :archer, 355, 0, :west
unit :archer, 358, 0, :west
unit :archer, 360, 0, :west
unit :captive, 362, 0, :west
unit :sludge, 363, 0, :west
unit :sludge, 369, 0, :west
unit :wizard, 371, 0, :west
unit :thick_sludge, 372, 0, :west
unit :thick_sludge, 373, 0, :west
unit :sludge, 376, 0, :west
unit :thick_sludge, 378, 0, :west
unit :sludge, 383, 0, :west
unit :thick_sludge, 385, 0, :west
unit :sludge, 390, 0, :west
unit :thick_sludge, 405, 0, :west
unit :wizard, 421, 0, :west
unit :wizard, 427, 0, :west
unit :thick_sludge, 429, 0, :west
unit :archer, 438, 0, :west
unit :captive, 440, 0, :west
unit :thick_sludge, 444, 0, :west
unit :thick_sludge, 446, 0, :west
unit :thick_sludge, 449, 0, :west
unit :thick_sludge, 457, 0, :west
unit :captive, 466, 0, :west
unit :sludge, 471, 0, :west
unit :thick_sludge, 473, 0, :west
unit :thick_sludge, 474, 0, :west
unit :wizard, 476, 0, :west
unit :sludge, 478, 0, :west
unit :archer, 492, 0, :west
unit :archer, 494, 0, :west
unit :thick_sludge, 504, 0, :west
unit :archer, 506, 0, :west
unit :archer, 508, 0, :west
unit :sludge, 514, 0, :west
unit :archer, 515, 0, :west
unit :archer, 516, 0, :west
unit :captive, 518, 0, :west
unit :sludge, 522, 0, :west
unit :archer, 525, 0, :west
unit :captive, 532, 0, :west
unit :archer, 534, 0, :west
unit :captive, 535, 0, :west
unit :captive, 543, 0, :west
unit :captive, 545, 0, :west
unit :sludge, 547, 0, :west
unit :sludge, 553, 0, :west
unit :captive, 554, 0, :west
unit :sludge, 564, 0, :west
unit :wizard, 573, 0, :west
unit :thick_sludge, 580, 0, :west
unit :archer, 582, 0, :west
unit :archer, 591, 0, :west
unit :thick_sludge, 594, 0, :west
unit :wizard, 601, 0, :west
unit :archer, 603, 0, :west
unit :wizard, 612, 0, :west
unit :archer, 616, 0, :west
unit :archer, 623, 0, :west
unit :sludge, 633, 0, :west
unit :wizard, 634, 0, :west
unit :thick_sludge, 640, 0, :west
unit :thick_sludge, 645, 0, :west
