#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     wC s    S       s      a   S           S  s  a a       SC   C ss    S  S    C      a     S      CS     S  s S    a  S      a       Cw     sC    as     C    a   w  a   a        CS   w    s   w          a  Ca    Ca         C  a  @       sS   S C       C  sSC   w   s          a     Cw C S       sC a      Sw Cs   aS    S w  S  w  w s     a   s    a   SCC    a      C   C     ssCC   s  C s w  wa S     s    a  S CsCCs     aa   S      C Ca sa   C C        C     aS    a S   C       wSw   s  a                  >  S           S      a   C  w  s           C  S     C       C  a C  |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 580
ace_score 2900
size 580, 1
stairs 511, 0

warrior 232, 0, :east

unit :wizard, 5, 0, :east
unit :captive, 6, 0, :east
unit :sludge, 8, 0, :east
unit :thick_sludge, 13, 0, :east
unit :sludge, 21, 0, :east
unit :archer, 28, 0, :east
unit :thick_sludge, 32, 0, :east
unit :thick_sludge, 44, 0, :east
unit :sludge, 47, 0, :east
unit :archer, 50, 0, :east
unit :archer, 52, 0, :east
unit :thick_sludge, 60, 0, :east
unit :captive, 61, 0, :east
unit :captive, 65, 0, :east
unit :sludge, 67, 0, :east
unit :sludge, 68, 0, :east
unit :thick_sludge, 73, 0, :east
unit :thick_sludge, 76, 0, :east
unit :captive, 81, 0, :east
unit :archer, 88, 0, :east
unit :thick_sludge, 94, 0, :east
unit :captive, 101, 0, :east
unit :thick_sludge, 102, 0, :east
unit :thick_sludge, 108, 0, :east
unit :sludge, 111, 0, :east
unit :thick_sludge, 113, 0, :east
unit :archer, 118, 0, :east
unit :thick_sludge, 121, 0, :east
unit :archer, 128, 0, :east
unit :captive, 136, 0, :east
unit :wizard, 137, 0, :east
unit :sludge, 143, 0, :east
unit :captive, 144, 0, :east
unit :archer, 149, 0, :east
unit :sludge, 150, 0, :east
unit :captive, 156, 0, :east
unit :archer, 161, 0, :east
unit :wizard, 165, 0, :east
unit :archer, 168, 0, :east
unit :archer, 172, 0, :east
unit :captive, 181, 0, :east
unit :thick_sludge, 182, 0, :east
unit :wizard, 186, 0, :east
unit :sludge, 191, 0, :east
unit :wizard, 195, 0, :east
unit :archer, 206, 0, :east
unit :captive, 209, 0, :east
unit :archer, 210, 0, :east
unit :captive, 215, 0, :east
unit :archer, 216, 0, :east
unit :captive, 226, 0, :east
unit :archer, 229, 0, :east
unit :sludge, 240, 0, :west
unit :thick_sludge, 241, 0, :west
unit :thick_sludge, 245, 0, :west
unit :captive, 247, 0, :west
unit :captive, 255, 0, :west
unit :sludge, 258, 0, :west
unit :thick_sludge, 259, 0, :west
unit :captive, 260, 0, :west
unit :wizard, 264, 0, :west
unit :sludge, 268, 0, :west
unit :archer, 279, 0, :west
unit :captive, 285, 0, :west
unit :wizard, 286, 0, :west
unit :captive, 288, 0, :west
unit :thick_sludge, 290, 0, :west
unit :sludge, 298, 0, :west
unit :captive, 299, 0, :west
unit :archer, 301, 0, :west
unit :thick_sludge, 308, 0, :west
unit :wizard, 309, 0, :west
unit :captive, 311, 0, :west
unit :sludge, 312, 0, :west
unit :archer, 316, 0, :west
unit :thick_sludge, 317, 0, :west
unit :thick_sludge, 322, 0, :west
unit :wizard, 324, 0, :west
unit :thick_sludge, 327, 0, :west
unit :wizard, 330, 0, :west
unit :wizard, 333, 0, :west
unit :sludge, 335, 0, :west
unit :archer, 341, 0, :west
unit :sludge, 345, 0, :west
unit :archer, 350, 0, :west
unit :thick_sludge, 354, 0, :west
unit :captive, 355, 0, :west
unit :captive, 356, 0, :west
unit :archer, 361, 0, :west
unit :captive, 368, 0, :west
unit :captive, 372, 0, :west
unit :sludge, 378, 0, :west
unit :sludge, 379, 0, :west
unit :captive, 380, 0, :west
unit :captive, 381, 0, :west
unit :sludge, 385, 0, :west
unit :captive, 388, 0, :west
unit :sludge, 390, 0, :west
unit :wizard, 392, 0, :west
unit :wizard, 395, 0, :west
unit :archer, 396, 0, :west
unit :thick_sludge, 398, 0, :west
unit :sludge, 404, 0, :west
unit :archer, 409, 0, :west
unit :thick_sludge, 412, 0, :west
unit :captive, 414, 0, :west
unit :sludge, 415, 0, :west
unit :captive, 416, 0, :west
unit :captive, 417, 0, :west
unit :sludge, 418, 0, :west
unit :archer, 424, 0, :west
unit :archer, 425, 0, :west
unit :thick_sludge, 429, 0, :west
unit :captive, 436, 0, :west
unit :captive, 438, 0, :west
unit :archer, 439, 0, :west
unit :sludge, 441, 0, :west
unit :archer, 442, 0, :west
unit :captive, 446, 0, :west
unit :captive, 448, 0, :west
unit :captive, 457, 0, :west
unit :archer, 463, 0, :west
unit :thick_sludge, 464, 0, :west
unit :archer, 469, 0, :west
unit :thick_sludge, 471, 0, :west
unit :captive, 475, 0, :west
unit :wizard, 483, 0, :west
unit :thick_sludge, 484, 0, :west
unit :wizard, 485, 0, :west
unit :sludge, 489, 0, :west
unit :archer, 492, 0, :west
unit :thick_sludge, 514, 0, :west
unit :thick_sludge, 526, 0, :west
unit :archer, 533, 0, :west
unit :captive, 537, 0, :west
unit :wizard, 540, 0, :west
unit :sludge, 543, 0, :west
unit :captive, 555, 0, :west
unit :thick_sludge, 558, 0, :west
unit :captive, 564, 0, :west
unit :captive, 572, 0, :west
unit :archer, 575, 0, :west
unit :captive, 577, 0, :west
