#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C a s  s    s C        S   C        C s   S w  a      Ss              s     C      S S  a   aS       C S      C     aCw a  s s C  s Cs  C         a   w              s   w  C   S s                s aa   w        w SS      s aC                     w         C C w          C   w      a       Ss  a  w      Sa            S     s     S   w     Sa a s  a S s   w   sC  s w   C   a               C    SsC S  C      w       C  s   a   w   a   C  S   S   s a        C     w  s    aCsa  w  a   >         s  C    a   w   ssw  SCa        SS    aw w       C aa        Ca asCs C  s CS aSS w  C     a    S C w   a      a     C  C  S          CC S         w     C           S     a C    a  s  a  S         Ss     a   as    C S C    C sw           aS       w s w a  Sa  w    S  s  Cs wa     s       C  C   C    s    s  S aa   aa   aSC               s    @  s s     as     w  s w   SC  S    w  a    as SC   C   w   S   S     w|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 911
ace_score 4555
size 911, 1
stairs 487, 0

warrior 840, 0, :east

unit :captive, 2, 0, :east
unit :archer, 4, 0, :east
unit :sludge, 6, 0, :east
unit :sludge, 9, 0, :east
unit :sludge, 14, 0, :east
unit :captive, 16, 0, :east
unit :thick_sludge, 25, 0, :east
unit :captive, 29, 0, :east
unit :captive, 38, 0, :east
unit :sludge, 40, 0, :east
unit :thick_sludge, 44, 0, :east
unit :wizard, 46, 0, :east
unit :archer, 49, 0, :east
unit :thick_sludge, 56, 0, :east
unit :sludge, 57, 0, :east
unit :sludge, 72, 0, :east
unit :captive, 78, 0, :east
unit :thick_sludge, 85, 0, :east
unit :thick_sludge, 87, 0, :east
unit :archer, 90, 0, :east
unit :archer, 94, 0, :east
unit :thick_sludge, 95, 0, :east
unit :captive, 103, 0, :east
unit :thick_sludge, 105, 0, :east
unit :captive, 112, 0, :east
unit :archer, 118, 0, :east
unit :captive, 119, 0, :east
unit :wizard, 120, 0, :east
unit :archer, 122, 0, :east
unit :sludge, 125, 0, :east
unit :sludge, 127, 0, :east
unit :captive, 129, 0, :east
unit :sludge, 132, 0, :east
unit :captive, 134, 0, :east
unit :sludge, 135, 0, :east
unit :captive, 138, 0, :east
unit :archer, 148, 0, :east
unit :wizard, 152, 0, :east
unit :sludge, 167, 0, :east
unit :wizard, 171, 0, :east
unit :captive, 174, 0, :east
unit :thick_sludge, 178, 0, :east
unit :sludge, 180, 0, :east
unit :sludge, 197, 0, :east
unit :archer, 199, 0, :east
unit :archer, 200, 0, :east
unit :wizard, 204, 0, :east
unit :wizard, 213, 0, :east
unit :thick_sludge, 215, 0, :east
unit :thick_sludge, 216, 0, :east
unit :sludge, 223, 0, :east
unit :archer, 225, 0, :east
unit :captive, 226, 0, :east
unit :wizard, 248, 0, :east
unit :captive, 258, 0, :east
unit :captive, 260, 0, :east
unit :wizard, 262, 0, :east
unit :captive, 273, 0, :east
unit :wizard, 277, 0, :east
unit :archer, 284, 0, :east
unit :thick_sludge, 292, 0, :east
unit :sludge, 293, 0, :east
unit :archer, 296, 0, :east
unit :wizard, 299, 0, :east
unit :thick_sludge, 306, 0, :east
unit :archer, 307, 0, :east
unit :thick_sludge, 320, 0, :east
unit :sludge, 326, 0, :east
unit :thick_sludge, 332, 0, :east
unit :wizard, 336, 0, :east
unit :thick_sludge, 342, 0, :east
unit :archer, 343, 0, :east
unit :archer, 345, 0, :east
unit :sludge, 347, 0, :east
unit :archer, 350, 0, :east
unit :thick_sludge, 352, 0, :east
unit :sludge, 354, 0, :east
unit :wizard, 358, 0, :east
unit :sludge, 362, 0, :east
unit :captive, 363, 0, :east
unit :sludge, 366, 0, :east
unit :wizard, 368, 0, :east
unit :captive, 372, 0, :east
unit :archer, 376, 0, :east
unit :captive, 392, 0, :east
unit :thick_sludge, 397, 0, :east
unit :sludge, 398, 0, :east
unit :captive, 399, 0, :east
unit :thick_sludge, 401, 0, :east
unit :captive, 404, 0, :east
unit :wizard, 411, 0, :east
unit :captive, 419, 0, :east
unit :sludge, 422, 0, :east
unit :archer, 426, 0, :east
unit :wizard, 430, 0, :east
unit :archer, 434, 0, :east
unit :captive, 438, 0, :east
unit :thick_sludge, 441, 0, :east
unit :thick_sludge, 445, 0, :east
unit :sludge, 449, 0, :east
unit :archer, 451, 0, :east
unit :captive, 460, 0, :east
unit :wizard, 466, 0, :east
unit :sludge, 469, 0, :east
unit :archer, 474, 0, :east
unit :captive, 475, 0, :east
unit :sludge, 476, 0, :east
unit :archer, 477, 0, :east
unit :wizard, 480, 0, :east
unit :archer, 483, 0, :east
unit :sludge, 497, 0, :east
unit :captive, 500, 0, :east
unit :archer, 505, 0, :east
unit :wizard, 509, 0, :east
unit :sludge, 513, 0, :east
unit :sludge, 514, 0, :east
unit :wizard, 515, 0, :east
unit :thick_sludge, 518, 0, :east
unit :captive, 519, 0, :east
unit :archer, 520, 0, :east
unit :thick_sludge, 529, 0, :east
unit :thick_sludge, 530, 0, :east
unit :archer, 535, 0, :east
unit :wizard, 536, 0, :east
unit :wizard, 538, 0, :east
unit :captive, 546, 0, :east
unit :archer, 548, 0, :east
unit :archer, 549, 0, :east
unit :captive, 558, 0, :east
unit :archer, 559, 0, :east
unit :archer, 561, 0, :east
unit :sludge, 562, 0, :east
unit :captive, 563, 0, :east
unit :sludge, 564, 0, :east
unit :captive, 566, 0, :east
unit :sludge, 569, 0, :east
unit :captive, 571, 0, :east
unit :thick_sludge, 572, 0, :east
unit :archer, 574, 0, :east
unit :thick_sludge, 575, 0, :east
unit :thick_sludge, 576, 0, :east
unit :wizard, 578, 0, :east
unit :captive, 581, 0, :east
unit :archer, 587, 0, :east
unit :thick_sludge, 592, 0, :east
unit :captive, 594, 0, :east
unit :wizard, 596, 0, :east
unit :archer, 600, 0, :east
unit :archer, 607, 0, :east
unit :captive, 613, 0, :east
unit :captive, 616, 0, :east
unit :thick_sludge, 619, 0, :east
unit :captive, 630, 0, :east
unit :captive, 631, 0, :east
unit :thick_sludge, 633, 0, :east
unit :wizard, 643, 0, :east
unit :captive, 649, 0, :east
unit :thick_sludge, 661, 0, :east
unit :archer, 667, 0, :east
unit :captive, 669, 0, :east
unit :archer, 674, 0, :east
unit :sludge, 677, 0, :east
unit :archer, 680, 0, :east
unit :thick_sludge, 683, 0, :east
unit :thick_sludge, 693, 0, :east
unit :sludge, 694, 0, :east
unit :archer, 700, 0, :east
unit :archer, 704, 0, :east
unit :sludge, 705, 0, :east
unit :captive, 710, 0, :east
unit :thick_sludge, 712, 0, :east
unit :captive, 714, 0, :east
unit :captive, 719, 0, :east
unit :sludge, 721, 0, :east
unit :wizard, 722, 0, :east
unit :archer, 734, 0, :east
unit :thick_sludge, 735, 0, :east
unit :wizard, 743, 0, :east
unit :sludge, 745, 0, :east
unit :wizard, 747, 0, :east
unit :archer, 749, 0, :east
unit :thick_sludge, 752, 0, :east
unit :archer, 753, 0, :east
unit :wizard, 756, 0, :east
unit :thick_sludge, 761, 0, :east
unit :sludge, 764, 0, :east
unit :captive, 767, 0, :east
unit :sludge, 768, 0, :east
unit :wizard, 770, 0, :east
unit :archer, 771, 0, :east
unit :sludge, 777, 0, :east
unit :captive, 785, 0, :east
unit :captive, 788, 0, :east
unit :captive, 792, 0, :east
unit :sludge, 797, 0, :east
unit :sludge, 802, 0, :east
unit :thick_sludge, 805, 0, :east
unit :archer, 807, 0, :east
unit :archer, 808, 0, :east
unit :archer, 812, 0, :east
unit :archer, 813, 0, :east
unit :archer, 817, 0, :east
unit :thick_sludge, 818, 0, :east
unit :captive, 819, 0, :east
unit :sludge, 835, 0, :east
unit :sludge, 843, 0, :west
unit :sludge, 845, 0, :west
unit :archer, 851, 0, :west
unit :sludge, 852, 0, :west
unit :wizard, 858, 0, :west
unit :sludge, 861, 0, :west
unit :wizard, 863, 0, :west
unit :thick_sludge, 867, 0, :west
unit :captive, 868, 0, :west
unit :thick_sludge, 871, 0, :west
unit :wizard, 876, 0, :west
unit :archer, 879, 0, :west
unit :archer, 884, 0, :west
unit :sludge, 885, 0, :west
unit :thick_sludge, 887, 0, :west
unit :captive, 888, 0, :west
unit :captive, 892, 0, :west
unit :wizard, 896, 0, :west
unit :thick_sludge, 900, 0, :west
unit :thick_sludge, 904, 0, :west
unit :wizard, 910, 0, :west
