#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   a      a     w     a  s  C w    C wa    w   a  SC a C       s    C  s     a C  S  as      a S  Sa       s    w    a w Cs                  a       w a s    C  s w   > S C  C ss  Ss  w       a     s s a     S a   S  S              C     C     a   a s C           a        s    S    SC         a   aC   C   S    w   a            C    Sa     s   s C  w  a aS a Sa  wC   s C w      w  S          a            w    S   S w    s C  aa CC aa SS    s s  sa  SS           w  s                w   a wa s      w              S       C a    aw       S s a    C      s     S  a    a  aSC s         a  SSC S a     C   s S   S      s C C w     C     wa     S  s   CsC  S  w a   S      SC    wC a    aSC w  CS  a S  Sa    s  S  C            w   w       C S  aC      @  a      a            C        w     w    s   C    s       C  a C  s    asCS    |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 833
ace_score 4165
size 833, 1
stairs 167, 0

warrior 752, 0, :east

unit :archer, 3, 0, :east
unit :archer, 10, 0, :east
unit :wizard, 16, 0, :east
unit :archer, 22, 0, :east
unit :sludge, 25, 0, :east
unit :captive, 28, 0, :east
unit :wizard, 30, 0, :east
unit :captive, 35, 0, :east
unit :wizard, 37, 0, :east
unit :archer, 38, 0, :east
unit :wizard, 43, 0, :east
unit :archer, 47, 0, :east
unit :thick_sludge, 50, 0, :east
unit :captive, 51, 0, :east
unit :archer, 53, 0, :east
unit :captive, 55, 0, :east
unit :sludge, 63, 0, :east
unit :captive, 68, 0, :east
unit :sludge, 71, 0, :east
unit :archer, 77, 0, :east
unit :captive, 79, 0, :east
unit :thick_sludge, 82, 0, :east
unit :archer, 85, 0, :east
unit :sludge, 86, 0, :east
unit :archer, 93, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 98, 0, :east
unit :archer, 99, 0, :east
unit :sludge, 107, 0, :east
unit :wizard, 112, 0, :east
unit :archer, 117, 0, :east
unit :wizard, 119, 0, :east
unit :captive, 121, 0, :east
unit :sludge, 122, 0, :east
unit :archer, 141, 0, :east
unit :wizard, 149, 0, :east
unit :archer, 151, 0, :east
unit :sludge, 153, 0, :east
unit :captive, 158, 0, :east
unit :sludge, 161, 0, :east
unit :wizard, 163, 0, :east
unit :thick_sludge, 169, 0, :east
unit :captive, 171, 0, :east
unit :captive, 174, 0, :east
unit :sludge, 176, 0, :east
unit :sludge, 177, 0, :east
unit :thick_sludge, 180, 0, :east
unit :sludge, 181, 0, :east
unit :wizard, 184, 0, :east
unit :archer, 192, 0, :east
unit :sludge, 198, 0, :east
unit :sludge, 200, 0, :east
unit :archer, 202, 0, :east
unit :thick_sludge, 208, 0, :east
unit :archer, 210, 0, :east
unit :thick_sludge, 214, 0, :east
unit :thick_sludge, 217, 0, :east
unit :captive, 232, 0, :east
unit :captive, 238, 0, :east
unit :archer, 244, 0, :east
unit :archer, 248, 0, :east
unit :sludge, 250, 0, :east
unit :captive, 252, 0, :east
unit :archer, 264, 0, :east
unit :sludge, 273, 0, :east
unit :thick_sludge, 278, 0, :east
unit :thick_sludge, 283, 0, :east
unit :captive, 284, 0, :east
unit :archer, 294, 0, :east
unit :archer, 298, 0, :east
unit :captive, 299, 0, :east
unit :captive, 303, 0, :east
unit :thick_sludge, 307, 0, :east
unit :wizard, 312, 0, :east
unit :archer, 316, 0, :east
unit :captive, 329, 0, :east
unit :thick_sludge, 334, 0, :east
unit :archer, 335, 0, :east
unit :sludge, 341, 0, :east
unit :sludge, 345, 0, :east
unit :captive, 347, 0, :east
unit :wizard, 350, 0, :east
unit :archer, 353, 0, :east
unit :archer, 355, 0, :east
unit :thick_sludge, 356, 0, :east
unit :archer, 358, 0, :east
unit :thick_sludge, 360, 0, :east
unit :archer, 361, 0, :east
unit :wizard, 364, 0, :east
unit :captive, 365, 0, :east
unit :sludge, 369, 0, :east
unit :captive, 371, 0, :east
unit :wizard, 373, 0, :east
unit :wizard, 380, 0, :east
unit :thick_sludge, 383, 0, :east
unit :archer, 394, 0, :east
unit :wizard, 407, 0, :east
unit :thick_sludge, 412, 0, :east
unit :thick_sludge, 416, 0, :east
unit :wizard, 418, 0, :east
unit :sludge, 423, 0, :east
unit :captive, 425, 0, :east
unit :archer, 428, 0, :east
unit :archer, 429, 0, :east
unit :captive, 431, 0, :east
unit :captive, 432, 0, :east
unit :archer, 434, 0, :east
unit :archer, 435, 0, :east
unit :thick_sludge, 437, 0, :east
unit :thick_sludge, 438, 0, :east
unit :sludge, 443, 0, :east
unit :sludge, 445, 0, :east
unit :sludge, 448, 0, :east
unit :archer, 449, 0, :east
unit :thick_sludge, 452, 0, :east
unit :thick_sludge, 453, 0, :east
unit :wizard, 465, 0, :east
unit :sludge, 468, 0, :east
unit :wizard, 485, 0, :east
unit :archer, 489, 0, :east
unit :wizard, 491, 0, :east
unit :archer, 492, 0, :east
unit :sludge, 494, 0, :east
unit :wizard, 501, 0, :east
unit :thick_sludge, 516, 0, :east
unit :captive, 524, 0, :east
unit :archer, 526, 0, :east
unit :archer, 531, 0, :east
unit :wizard, 532, 0, :east
unit :thick_sludge, 540, 0, :east
unit :sludge, 542, 0, :east
unit :archer, 544, 0, :east
unit :captive, 549, 0, :east
unit :sludge, 556, 0, :east
unit :thick_sludge, 562, 0, :east
unit :archer, 565, 0, :east
unit :archer, 570, 0, :east
unit :archer, 573, 0, :east
unit :thick_sludge, 574, 0, :east
unit :captive, 575, 0, :east
unit :sludge, 577, 0, :east
unit :archer, 587, 0, :east
unit :thick_sludge, 590, 0, :east
unit :thick_sludge, 591, 0, :east
unit :captive, 592, 0, :east
unit :thick_sludge, 594, 0, :east
unit :archer, 596, 0, :east
unit :captive, 602, 0, :east
unit :sludge, 606, 0, :east
unit :thick_sludge, 608, 0, :east
unit :thick_sludge, 612, 0, :east
unit :sludge, 619, 0, :east
unit :captive, 621, 0, :east
unit :captive, 623, 0, :east
unit :wizard, 625, 0, :east
unit :captive, 631, 0, :east
unit :wizard, 637, 0, :east
unit :archer, 638, 0, :east
unit :thick_sludge, 644, 0, :east
unit :sludge, 647, 0, :east
unit :captive, 651, 0, :east
unit :sludge, 652, 0, :east
unit :captive, 653, 0, :east
unit :thick_sludge, 656, 0, :east
unit :wizard, 659, 0, :east
unit :archer, 661, 0, :east
unit :thick_sludge, 665, 0, :east
unit :thick_sludge, 672, 0, :east
unit :captive, 673, 0, :east
unit :wizard, 678, 0, :east
unit :captive, 679, 0, :east
unit :archer, 681, 0, :east
unit :archer, 686, 0, :east
unit :thick_sludge, 687, 0, :east
unit :captive, 688, 0, :east
unit :wizard, 690, 0, :east
unit :captive, 693, 0, :east
unit :thick_sludge, 694, 0, :east
unit :archer, 697, 0, :east
unit :thick_sludge, 699, 0, :east
unit :thick_sludge, 702, 0, :east
unit :archer, 703, 0, :east
unit :sludge, 708, 0, :east
unit :thick_sludge, 711, 0, :east
unit :captive, 714, 0, :east
unit :wizard, 727, 0, :east
unit :wizard, 731, 0, :east
unit :captive, 739, 0, :east
unit :thick_sludge, 741, 0, :east
unit :archer, 744, 0, :east
unit :captive, 745, 0, :east
unit :archer, 755, 0, :west
unit :archer, 762, 0, :west
unit :captive, 775, 0, :west
unit :wizard, 784, 0, :west
unit :wizard, 790, 0, :west
unit :sludge, 795, 0, :west
unit :captive, 799, 0, :west
unit :sludge, 804, 0, :west
unit :captive, 812, 0, :west
unit :archer, 815, 0, :west
unit :captive, 817, 0, :west
unit :sludge, 820, 0, :west
unit :archer, 825, 0, :west
unit :sludge, 826, 0, :west
unit :captive, 827, 0, :west
unit :thick_sludge, 828, 0, :west
