#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w C  a    a   SS    a     s  S s     s  a  a        S              aS   C          a     a w      S     S  C    S    a a  aw    C  S    S     Cs    CS w   sw  S         S   C            w  a S    a a a a       SS   a  @   s      s        w   C w a  Cs     w    C        s s                   SS  a   s   C      S     s a  S  a    C  w w     C      a   Caa wS     s   C  w  w             w  s      C w w   wa    CSw S     C       s w CC      wS S    C   aS  s s    s S  wa    a CSS S CS      s               s  C      CC   w   a  S  a wCa a  sa    C     S    s    >       S   ssSC    s    w S C        w w  sa       w  S      S   s    |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 634
ace_score 3170
size 634, 1
stairs 563, 0

warrior 218, 0, :east

unit :wizard, 0, 0, :east
unit :captive, 2, 0, :east
unit :archer, 5, 0, :east
unit :archer, 10, 0, :east
unit :thick_sludge, 14, 0, :east
unit :thick_sludge, 15, 0, :east
unit :archer, 20, 0, :east
unit :sludge, 26, 0, :east
unit :thick_sludge, 29, 0, :east
unit :sludge, 31, 0, :east
unit :sludge, 37, 0, :east
unit :archer, 40, 0, :east
unit :archer, 43, 0, :east
unit :thick_sludge, 52, 0, :east
unit :archer, 67, 0, :east
unit :thick_sludge, 68, 0, :east
unit :captive, 72, 0, :east
unit :archer, 83, 0, :east
unit :archer, 89, 0, :east
unit :wizard, 91, 0, :east
unit :thick_sludge, 98, 0, :east
unit :thick_sludge, 104, 0, :east
unit :captive, 107, 0, :east
unit :thick_sludge, 112, 0, :east
unit :archer, 117, 0, :east
unit :archer, 119, 0, :east
unit :archer, 122, 0, :east
unit :wizard, 123, 0, :east
unit :captive, 128, 0, :east
unit :thick_sludge, 131, 0, :east
unit :thick_sludge, 136, 0, :east
unit :captive, 142, 0, :east
unit :sludge, 143, 0, :east
unit :captive, 148, 0, :east
unit :thick_sludge, 149, 0, :east
unit :wizard, 151, 0, :east
unit :sludge, 155, 0, :east
unit :wizard, 156, 0, :east
unit :thick_sludge, 159, 0, :east
unit :thick_sludge, 169, 0, :east
unit :captive, 173, 0, :east
unit :wizard, 186, 0, :east
unit :archer, 189, 0, :east
unit :thick_sludge, 191, 0, :east
unit :archer, 196, 0, :east
unit :archer, 198, 0, :east
unit :archer, 200, 0, :east
unit :archer, 202, 0, :east
unit :thick_sludge, 210, 0, :east
unit :thick_sludge, 211, 0, :east
unit :archer, 215, 0, :east
unit :sludge, 222, 0, :west
unit :sludge, 229, 0, :west
unit :wizard, 238, 0, :west
unit :captive, 242, 0, :west
unit :wizard, 244, 0, :west
unit :archer, 246, 0, :west
unit :captive, 249, 0, :west
unit :sludge, 250, 0, :west
unit :wizard, 256, 0, :west
unit :captive, 261, 0, :west
unit :sludge, 270, 0, :west
unit :sludge, 272, 0, :west
unit :thick_sludge, 292, 0, :west
unit :thick_sludge, 293, 0, :west
unit :archer, 296, 0, :west
unit :sludge, 300, 0, :west
unit :captive, 304, 0, :west
unit :thick_sludge, 311, 0, :west
unit :sludge, 317, 0, :west
unit :archer, 319, 0, :west
unit :thick_sludge, 322, 0, :west
unit :archer, 325, 0, :west
unit :captive, 330, 0, :west
unit :wizard, 333, 0, :west
unit :wizard, 335, 0, :west
unit :captive, 341, 0, :west
unit :archer, 348, 0, :west
unit :captive, 352, 0, :west
unit :archer, 353, 0, :west
unit :archer, 354, 0, :west
unit :wizard, 356, 0, :west
unit :thick_sludge, 357, 0, :west
unit :sludge, 363, 0, :west
unit :captive, 367, 0, :west
unit :wizard, 370, 0, :west
unit :wizard, 373, 0, :west
unit :wizard, 387, 0, :west
unit :sludge, 390, 0, :west
unit :captive, 397, 0, :west
unit :wizard, 399, 0, :west
unit :wizard, 401, 0, :west
unit :wizard, 405, 0, :west
unit :archer, 406, 0, :west
unit :captive, 411, 0, :west
unit :thick_sludge, 412, 0, :west
unit :wizard, 413, 0, :west
unit :thick_sludge, 415, 0, :west
unit :captive, 421, 0, :west
unit :sludge, 429, 0, :west
unit :wizard, 431, 0, :west
unit :captive, 433, 0, :west
unit :captive, 434, 0, :west
unit :wizard, 441, 0, :west
unit :thick_sludge, 442, 0, :west
unit :thick_sludge, 444, 0, :west
unit :captive, 449, 0, :west
unit :archer, 453, 0, :west
unit :thick_sludge, 454, 0, :west
unit :sludge, 457, 0, :west
unit :sludge, 459, 0, :west
unit :sludge, 464, 0, :west
unit :thick_sludge, 466, 0, :west
unit :wizard, 469, 0, :west
unit :archer, 470, 0, :west
unit :archer, 475, 0, :west
unit :captive, 477, 0, :west
unit :thick_sludge, 478, 0, :west
unit :thick_sludge, 479, 0, :west
unit :thick_sludge, 481, 0, :west
unit :captive, 483, 0, :west
unit :thick_sludge, 484, 0, :west
unit :sludge, 491, 0, :west
unit :sludge, 507, 0, :west
unit :captive, 510, 0, :west
unit :captive, 517, 0, :west
unit :captive, 518, 0, :west
unit :wizard, 522, 0, :west
unit :archer, 526, 0, :west
unit :thick_sludge, 529, 0, :west
unit :archer, 532, 0, :west
unit :wizard, 534, 0, :west
unit :captive, 535, 0, :west
unit :archer, 536, 0, :west
unit :archer, 538, 0, :west
unit :sludge, 541, 0, :west
unit :archer, 542, 0, :west
unit :captive, 547, 0, :west
unit :thick_sludge, 553, 0, :west
unit :sludge, 558, 0, :west
unit :thick_sludge, 571, 0, :west
unit :sludge, 575, 0, :west
unit :sludge, 576, 0, :west
unit :thick_sludge, 577, 0, :west
unit :captive, 578, 0, :west
unit :sludge, 583, 0, :west
unit :wizard, 588, 0, :west
unit :thick_sludge, 590, 0, :west
unit :captive, 592, 0, :west
unit :wizard, 601, 0, :west
unit :wizard, 603, 0, :west
unit :sludge, 606, 0, :west
unit :archer, 607, 0, :west
unit :wizard, 615, 0, :west
unit :thick_sludge, 618, 0, :west
unit :thick_sludge, 625, 0, :west
unit :sludge, 629, 0, :west
