#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   w   a   s w     C  ssC       w     C  s SCa aC      w   Sw    s    a  C a   s w  C ss a      C w w s CC          S   s         C  S     w    a           @  aC    Sa a      a  C              ss  sS  w w w    s C  a    s     a   a w S a ws  w     S       a wCa      s  sCC   as w       w       s          C    CC w aC        C     C  C        Ca   C>      s wS     as   s     a w w   aa  Sa  Ss w s            a        w C SC   s        sCs   s  s   s      S        Sa    aw S        s   a  C       a w C    C     C        S a  SaS     S Sa  Sa  s  s      CS  S      w    a                          a       s             C        C   CS   S a            C   Cs   a |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 666
ace_score 3330
size 666, 1
stairs 350, 0

warrior 156, 0, :east

unit :wizard, 3, 0, :east
unit :archer, 7, 0, :east
unit :sludge, 11, 0, :east
unit :wizard, 13, 0, :east
unit :captive, 19, 0, :east
unit :sludge, 22, 0, :east
unit :sludge, 23, 0, :east
unit :captive, 24, 0, :east
unit :wizard, 32, 0, :east
unit :captive, 38, 0, :east
unit :sludge, 41, 0, :east
unit :thick_sludge, 43, 0, :east
unit :captive, 44, 0, :east
unit :archer, 45, 0, :east
unit :archer, 47, 0, :east
unit :captive, 48, 0, :east
unit :wizard, 55, 0, :east
unit :thick_sludge, 59, 0, :east
unit :wizard, 60, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 70, 0, :east
unit :captive, 73, 0, :east
unit :archer, 75, 0, :east
unit :sludge, 79, 0, :east
unit :wizard, 81, 0, :east
unit :captive, 84, 0, :east
unit :sludge, 86, 0, :east
unit :sludge, 87, 0, :east
unit :archer, 89, 0, :east
unit :captive, 96, 0, :east
unit :wizard, 98, 0, :east
unit :wizard, 100, 0, :east
unit :sludge, 102, 0, :east
unit :captive, 104, 0, :east
unit :captive, 105, 0, :east
unit :thick_sludge, 116, 0, :east
unit :sludge, 120, 0, :east
unit :captive, 130, 0, :east
unit :thick_sludge, 133, 0, :east
unit :wizard, 139, 0, :east
unit :archer, 144, 0, :east
unit :archer, 159, 0, :west
unit :captive, 160, 0, :west
unit :thick_sludge, 165, 0, :west
unit :archer, 166, 0, :west
unit :archer, 168, 0, :west
unit :archer, 175, 0, :west
unit :captive, 178, 0, :west
unit :sludge, 193, 0, :west
unit :sludge, 194, 0, :west
unit :sludge, 197, 0, :west
unit :thick_sludge, 198, 0, :west
unit :wizard, 201, 0, :west
unit :wizard, 203, 0, :west
unit :wizard, 205, 0, :west
unit :sludge, 210, 0, :west
unit :captive, 212, 0, :west
unit :archer, 215, 0, :west
unit :sludge, 220, 0, :west
unit :archer, 226, 0, :west
unit :archer, 230, 0, :west
unit :wizard, 232, 0, :west
unit :thick_sludge, 234, 0, :west
unit :archer, 236, 0, :west
unit :wizard, 238, 0, :west
unit :sludge, 239, 0, :west
unit :wizard, 242, 0, :west
unit :thick_sludge, 248, 0, :west
unit :archer, 256, 0, :west
unit :wizard, 258, 0, :west
unit :captive, 259, 0, :west
unit :archer, 260, 0, :west
unit :sludge, 267, 0, :west
unit :sludge, 270, 0, :west
unit :captive, 271, 0, :west
unit :captive, 272, 0, :west
unit :archer, 276, 0, :west
unit :sludge, 277, 0, :west
unit :wizard, 279, 0, :west
unit :wizard, 287, 0, :west
unit :sludge, 295, 0, :west
unit :captive, 306, 0, :west
unit :captive, 311, 0, :west
unit :captive, 312, 0, :west
unit :wizard, 314, 0, :west
unit :archer, 316, 0, :west
unit :captive, 317, 0, :west
unit :captive, 326, 0, :west
unit :captive, 332, 0, :west
unit :captive, 335, 0, :west
unit :captive, 344, 0, :west
unit :archer, 345, 0, :west
unit :captive, 349, 0, :west
unit :sludge, 357, 0, :west
unit :wizard, 359, 0, :west
unit :thick_sludge, 360, 0, :west
unit :archer, 366, 0, :west
unit :sludge, 367, 0, :west
unit :sludge, 371, 0, :west
unit :archer, 377, 0, :west
unit :wizard, 379, 0, :west
unit :wizard, 381, 0, :west
unit :archer, 385, 0, :west
unit :archer, 386, 0, :west
unit :thick_sludge, 389, 0, :west
unit :archer, 390, 0, :west
unit :thick_sludge, 393, 0, :west
unit :sludge, 394, 0, :west
unit :wizard, 396, 0, :west
unit :sludge, 398, 0, :west
unit :archer, 411, 0, :west
unit :wizard, 420, 0, :west
unit :captive, 422, 0, :west
unit :thick_sludge, 424, 0, :west
unit :captive, 425, 0, :west
unit :sludge, 429, 0, :west
unit :sludge, 438, 0, :west
unit :captive, 439, 0, :west
unit :sludge, 440, 0, :west
unit :sludge, 444, 0, :west
unit :sludge, 447, 0, :west
unit :sludge, 451, 0, :west
unit :thick_sludge, 458, 0, :west
unit :thick_sludge, 467, 0, :west
unit :archer, 468, 0, :west
unit :archer, 473, 0, :west
unit :wizard, 474, 0, :west
unit :thick_sludge, 476, 0, :west
unit :sludge, 485, 0, :west
unit :archer, 489, 0, :west
unit :captive, 492, 0, :west
unit :archer, 500, 0, :west
unit :wizard, 502, 0, :west
unit :captive, 504, 0, :west
unit :captive, 509, 0, :west
unit :captive, 515, 0, :west
unit :thick_sludge, 524, 0, :west
unit :archer, 526, 0, :west
unit :thick_sludge, 529, 0, :west
unit :archer, 530, 0, :west
unit :thick_sludge, 531, 0, :west
unit :thick_sludge, 537, 0, :west
unit :thick_sludge, 539, 0, :west
unit :archer, 540, 0, :west
unit :thick_sludge, 543, 0, :west
unit :archer, 544, 0, :west
unit :sludge, 547, 0, :west
unit :sludge, 550, 0, :west
unit :captive, 557, 0, :west
unit :thick_sludge, 558, 0, :west
unit :thick_sludge, 561, 0, :west
unit :wizard, 568, 0, :west
unit :archer, 573, 0, :west
unit :archer, 600, 0, :west
unit :sludge, 608, 0, :west
unit :captive, 622, 0, :west
unit :captive, 631, 0, :west
unit :captive, 635, 0, :west
unit :thick_sludge, 636, 0, :west
unit :thick_sludge, 640, 0, :west
unit :archer, 642, 0, :west
unit :captive, 655, 0, :west
unit :captive, 659, 0, :west
unit :sludge, 660, 0, :west
unit :archer, 664, 0, :west
