#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     Ss    S     sC sw Cs   s S                 C sCC           a     s  a     S     w    w       >   w a      s     @     a  S w S    C   SSs w a   a      w C         s    s  sa  w     s   S   Sa C w  S C     w w      s  sw      w SS  Ss     a s  s         S C    C    s  C      a S   w S Ca               w                 a  CS    C      w  sS   w       C a   SS     s C    sw    a  s w CSC C   C a   a     S       C a     S       Cw  Ss     S        s  s s         w   C       s   a      C   sS  w       w          a a   s   C   C     C            S  a     s a   C Ca s    aCaS    Ca w     a  a s   S  SS C w  s   C a  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 623
ace_score 3115
size 623, 1
stairs 98, 0

warrior 117, 0, :east

unit :thick_sludge, 5, 0, :east
unit :sludge, 6, 0, :east
unit :thick_sludge, 11, 0, :east
unit :sludge, 17, 0, :east
unit :captive, 18, 0, :east
unit :sludge, 20, 0, :east
unit :wizard, 21, 0, :east
unit :captive, 23, 0, :east
unit :sludge, 24, 0, :east
unit :sludge, 28, 0, :east
unit :thick_sludge, 30, 0, :east
unit :captive, 48, 0, :east
unit :sludge, 50, 0, :east
unit :captive, 51, 0, :east
unit :captive, 52, 0, :east
unit :archer, 64, 0, :east
unit :sludge, 70, 0, :east
unit :archer, 73, 0, :east
unit :thick_sludge, 79, 0, :east
unit :wizard, 85, 0, :east
unit :wizard, 90, 0, :east
unit :wizard, 102, 0, :east
unit :archer, 104, 0, :east
unit :sludge, 111, 0, :east
unit :archer, 123, 0, :west
unit :thick_sludge, 126, 0, :west
unit :wizard, 128, 0, :west
unit :thick_sludge, 130, 0, :west
unit :captive, 135, 0, :west
unit :thick_sludge, 139, 0, :west
unit :thick_sludge, 140, 0, :west
unit :sludge, 141, 0, :west
unit :wizard, 143, 0, :west
unit :archer, 145, 0, :west
unit :archer, 149, 0, :west
unit :wizard, 156, 0, :west
unit :captive, 158, 0, :west
unit :sludge, 168, 0, :west
unit :sludge, 173, 0, :west
unit :sludge, 176, 0, :west
unit :archer, 177, 0, :west
unit :wizard, 180, 0, :west
unit :sludge, 186, 0, :west
unit :thick_sludge, 190, 0, :west
unit :thick_sludge, 194, 0, :west
unit :archer, 195, 0, :west
unit :captive, 197, 0, :west
unit :wizard, 199, 0, :west
unit :thick_sludge, 202, 0, :west
unit :captive, 204, 0, :west
unit :wizard, 210, 0, :west
unit :wizard, 212, 0, :west
unit :sludge, 219, 0, :west
unit :sludge, 222, 0, :west
unit :wizard, 223, 0, :west
unit :wizard, 230, 0, :west
unit :thick_sludge, 232, 0, :west
unit :thick_sludge, 233, 0, :west
unit :thick_sludge, 236, 0, :west
unit :sludge, 237, 0, :west
unit :archer, 243, 0, :west
unit :sludge, 245, 0, :west
unit :sludge, 248, 0, :west
unit :thick_sludge, 258, 0, :west
unit :captive, 260, 0, :west
unit :captive, 265, 0, :west
unit :sludge, 270, 0, :west
unit :captive, 273, 0, :west
unit :archer, 280, 0, :west
unit :thick_sludge, 282, 0, :west
unit :wizard, 286, 0, :west
unit :thick_sludge, 288, 0, :west
unit :captive, 290, 0, :west
unit :archer, 291, 0, :west
unit :wizard, 307, 0, :west
unit :archer, 325, 0, :west
unit :captive, 328, 0, :west
unit :thick_sludge, 329, 0, :west
unit :captive, 334, 0, :west
unit :wizard, 341, 0, :west
unit :sludge, 344, 0, :west
unit :thick_sludge, 345, 0, :west
unit :wizard, 349, 0, :west
unit :captive, 357, 0, :west
unit :archer, 359, 0, :west
unit :thick_sludge, 363, 0, :west
unit :thick_sludge, 364, 0, :west
unit :sludge, 370, 0, :west
unit :captive, 372, 0, :west
unit :sludge, 377, 0, :west
unit :wizard, 378, 0, :west
unit :archer, 383, 0, :west
unit :sludge, 386, 0, :west
unit :wizard, 388, 0, :west
unit :captive, 390, 0, :west
unit :thick_sludge, 391, 0, :west
unit :captive, 392, 0, :west
unit :captive, 394, 0, :west
unit :captive, 398, 0, :west
unit :archer, 400, 0, :west
unit :archer, 404, 0, :west
unit :thick_sludge, 410, 0, :west
unit :captive, 418, 0, :west
unit :archer, 420, 0, :west
unit :thick_sludge, 426, 0, :west
unit :captive, 434, 0, :west
unit :wizard, 435, 0, :west
unit :thick_sludge, 438, 0, :west
unit :sludge, 439, 0, :west
unit :thick_sludge, 445, 0, :west
unit :sludge, 454, 0, :west
unit :sludge, 457, 0, :west
unit :sludge, 459, 0, :west
unit :wizard, 469, 0, :west
unit :captive, 473, 0, :west
unit :sludge, 481, 0, :west
unit :archer, 485, 0, :west
unit :captive, 492, 0, :west
unit :sludge, 496, 0, :west
unit :thick_sludge, 497, 0, :west
unit :wizard, 500, 0, :west
unit :wizard, 508, 0, :west
unit :archer, 519, 0, :west
unit :archer, 521, 0, :west
unit :sludge, 525, 0, :west
unit :captive, 529, 0, :west
unit :captive, 533, 0, :west
unit :captive, 539, 0, :west
unit :thick_sludge, 552, 0, :west
unit :archer, 555, 0, :west
unit :sludge, 561, 0, :west
unit :archer, 563, 0, :west
unit :captive, 567, 0, :west
unit :captive, 569, 0, :west
unit :archer, 570, 0, :west
unit :sludge, 572, 0, :west
unit :archer, 577, 0, :west
unit :captive, 578, 0, :west
unit :archer, 579, 0, :west
unit :thick_sludge, 580, 0, :west
unit :captive, 585, 0, :west
unit :archer, 586, 0, :west
unit :wizard, 588, 0, :west
unit :archer, 594, 0, :west
unit :archer, 597, 0, :west
unit :sludge, 599, 0, :west
unit :thick_sludge, 603, 0, :west
unit :thick_sludge, 606, 0, :west
unit :thick_sludge, 607, 0, :west
unit :captive, 609, 0, :west
unit :wizard, 611, 0, :west
unit :sludge, 614, 0, :west
unit :captive, 618, 0, :west
unit :archer, 620, 0, :west
