#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S w     a  a         C S   S           C       w s    wC  w w  s  SS a   sC       CS a        CC a  S  w S  w      sCs C           a    w      C          Sw s w  CCC       CC w  waC  C Sas wS   w            C    w   s     w      w  s   w    w  C   w   w       a a            w   C w s C  as   S    C        a a  s   C     CS  CsC       S  C  >w       s a a      Ca     SC  w  s   a     a  C w      S      w C  s   S          SC   w      asa w   C      a   a    s    a    s  w   w a     w              w  @   a w    S   a     a      S            a wS   s     a     s        s         a wCC C     S     ass       Ca   a  s          a        ss ssS    wa wC  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 657
ace_score 3285
size 657, 1
stairs 343, 0

warrior 505, 0, :east

unit :thick_sludge, 1, 0, :east
unit :wizard, 3, 0, :east
unit :archer, 9, 0, :east
unit :archer, 12, 0, :east
unit :captive, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :thick_sludge, 28, 0, :east
unit :captive, 40, 0, :east
unit :wizard, 48, 0, :east
unit :sludge, 50, 0, :east
unit :wizard, 55, 0, :east
unit :captive, 56, 0, :east
unit :wizard, 59, 0, :east
unit :wizard, 61, 0, :east
unit :sludge, 64, 0, :east
unit :thick_sludge, 67, 0, :east
unit :thick_sludge, 68, 0, :east
unit :archer, 70, 0, :east
unit :sludge, 74, 0, :east
unit :captive, 75, 0, :east
unit :captive, 83, 0, :east
unit :thick_sludge, 84, 0, :east
unit :archer, 86, 0, :east
unit :captive, 95, 0, :east
unit :captive, 96, 0, :east
unit :archer, 98, 0, :east
unit :thick_sludge, 101, 0, :east
unit :wizard, 104, 0, :east
unit :thick_sludge, 106, 0, :east
unit :wizard, 109, 0, :east
unit :sludge, 116, 0, :east
unit :captive, 117, 0, :east
unit :sludge, 118, 0, :east
unit :captive, 120, 0, :east
unit :archer, 132, 0, :east
unit :wizard, 137, 0, :east
unit :captive, 144, 0, :east
unit :thick_sludge, 155, 0, :east
unit :wizard, 156, 0, :east
unit :sludge, 158, 0, :east
unit :wizard, 160, 0, :east
unit :captive, 163, 0, :east
unit :captive, 164, 0, :east
unit :captive, 165, 0, :east
unit :captive, 173, 0, :east
unit :captive, 174, 0, :east
unit :wizard, 176, 0, :east
unit :wizard, 179, 0, :east
unit :archer, 180, 0, :east
unit :captive, 181, 0, :east
unit :captive, 184, 0, :east
unit :thick_sludge, 186, 0, :east
unit :archer, 187, 0, :east
unit :sludge, 188, 0, :east
unit :wizard, 190, 0, :east
unit :thick_sludge, 191, 0, :east
unit :wizard, 195, 0, :east
unit :captive, 208, 0, :east
unit :wizard, 213, 0, :east
unit :sludge, 217, 0, :east
unit :wizard, 223, 0, :east
unit :wizard, 230, 0, :east
unit :sludge, 233, 0, :east
unit :wizard, 237, 0, :east
unit :wizard, 242, 0, :east
unit :captive, 245, 0, :east
unit :wizard, 249, 0, :east
unit :wizard, 253, 0, :east
unit :archer, 261, 0, :east
unit :archer, 263, 0, :east
unit :wizard, 276, 0, :east
unit :captive, 280, 0, :east
unit :wizard, 282, 0, :east
unit :sludge, 284, 0, :east
unit :captive, 286, 0, :east
unit :archer, 289, 0, :east
unit :sludge, 290, 0, :east
unit :thick_sludge, 294, 0, :east
unit :captive, 299, 0, :east
unit :archer, 308, 0, :east
unit :archer, 310, 0, :east
unit :sludge, 313, 0, :east
unit :captive, 317, 0, :east
unit :captive, 323, 0, :east
unit :thick_sludge, 324, 0, :east
unit :captive, 327, 0, :east
unit :sludge, 328, 0, :east
unit :captive, 329, 0, :east
unit :thick_sludge, 337, 0, :east
unit :captive, 340, 0, :east
unit :wizard, 344, 0, :east
unit :sludge, 352, 0, :east
unit :archer, 354, 0, :east
unit :archer, 356, 0, :east
unit :captive, 363, 0, :east
unit :archer, 364, 0, :east
unit :thick_sludge, 370, 0, :east
unit :captive, 371, 0, :east
unit :wizard, 374, 0, :east
unit :sludge, 377, 0, :east
unit :archer, 381, 0, :east
unit :archer, 387, 0, :east
unit :captive, 390, 0, :east
unit :wizard, 392, 0, :east
unit :thick_sludge, 399, 0, :east
unit :wizard, 406, 0, :east
unit :captive, 408, 0, :east
unit :sludge, 411, 0, :east
unit :thick_sludge, 415, 0, :east
unit :thick_sludge, 426, 0, :east
unit :captive, 427, 0, :east
unit :wizard, 431, 0, :east
unit :archer, 438, 0, :east
unit :sludge, 439, 0, :east
unit :archer, 440, 0, :east
unit :wizard, 442, 0, :east
unit :captive, 446, 0, :east
unit :archer, 453, 0, :east
unit :archer, 457, 0, :east
unit :sludge, 462, 0, :east
unit :archer, 467, 0, :east
unit :sludge, 472, 0, :east
unit :wizard, 475, 0, :east
unit :wizard, 479, 0, :east
unit :archer, 481, 0, :east
unit :wizard, 487, 0, :east
unit :wizard, 502, 0, :east
unit :archer, 509, 0, :west
unit :wizard, 511, 0, :west
unit :thick_sludge, 516, 0, :west
unit :archer, 520, 0, :west
unit :archer, 526, 0, :west
unit :thick_sludge, 533, 0, :west
unit :archer, 546, 0, :west
unit :wizard, 548, 0, :west
unit :thick_sludge, 549, 0, :west
unit :sludge, 553, 0, :west
unit :archer, 559, 0, :west
unit :sludge, 565, 0, :west
unit :sludge, 574, 0, :west
unit :archer, 584, 0, :west
unit :wizard, 586, 0, :west
unit :captive, 587, 0, :west
unit :captive, 588, 0, :west
unit :captive, 590, 0, :west
unit :thick_sludge, 596, 0, :west
unit :archer, 602, 0, :west
unit :sludge, 603, 0, :west
unit :sludge, 604, 0, :west
unit :captive, 612, 0, :west
unit :archer, 613, 0, :west
unit :archer, 617, 0, :west
unit :sludge, 620, 0, :west
unit :archer, 631, 0, :west
unit :sludge, 640, 0, :west
unit :sludge, 641, 0, :west
unit :sludge, 643, 0, :west
unit :sludge, 644, 0, :west
unit :thick_sludge, 645, 0, :west
unit :wizard, 650, 0, :west
unit :archer, 651, 0, :west
unit :wizard, 653, 0, :west
unit :captive, 654, 0, :west
