#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |s w  s     w  a   C     s s     a    S   aa           Ca         sa           s a    aw  w  a w asSC     C   C sC     a           sC aSS    Sa  Ss        wa a C        sS       w    SS C  w C a     a  S            w   w w s             s           w                w    a  S    S  Sw  C      C        aS  C         w      saa w       a   a    a    @   a       w   a C  C aa         a  a        S C  s   S   aCS        w          S Ss a        a     S          aa       s   a      w          a  a        a  a s CSCC  s     C  a    S   w     a   a C s  w S S  a      s  s CC    S  a   S           w  s  S C  SC a   s     w aS  sC s      S w            s      C    s aS  w    w     w  S s S    C S  w aw C     C   sS  C         >  S  a  w a aa      a a    Ss        s s  SS  a Cs    aS|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 782
ace_score 3910
size 782, 1
stairs 725, 0

warrior 348, 0, :east

unit :sludge, 0, 0, :east
unit :wizard, 2, 0, :east
unit :sludge, 5, 0, :east
unit :wizard, 11, 0, :east
unit :archer, 14, 0, :east
unit :captive, 18, 0, :east
unit :sludge, 24, 0, :east
unit :sludge, 26, 0, :east
unit :archer, 32, 0, :east
unit :thick_sludge, 37, 0, :east
unit :archer, 41, 0, :east
unit :archer, 42, 0, :east
unit :captive, 54, 0, :east
unit :archer, 55, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 66, 0, :east
unit :sludge, 78, 0, :east
unit :archer, 80, 0, :east
unit :archer, 85, 0, :east
unit :wizard, 86, 0, :east
unit :wizard, 89, 0, :east
unit :archer, 92, 0, :east
unit :wizard, 94, 0, :east
unit :archer, 96, 0, :east
unit :sludge, 97, 0, :east
unit :thick_sludge, 98, 0, :east
unit :captive, 99, 0, :east
unit :captive, 105, 0, :east
unit :captive, 109, 0, :east
unit :sludge, 111, 0, :east
unit :captive, 112, 0, :east
unit :archer, 118, 0, :east
unit :sludge, 130, 0, :east
unit :captive, 131, 0, :east
unit :archer, 133, 0, :east
unit :thick_sludge, 134, 0, :east
unit :thick_sludge, 135, 0, :east
unit :thick_sludge, 140, 0, :east
unit :archer, 141, 0, :east
unit :thick_sludge, 144, 0, :east
unit :sludge, 145, 0, :east
unit :wizard, 154, 0, :east
unit :archer, 155, 0, :east
unit :archer, 157, 0, :east
unit :captive, 159, 0, :east
unit :sludge, 168, 0, :east
unit :thick_sludge, 169, 0, :east
unit :wizard, 177, 0, :east
unit :thick_sludge, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :captive, 185, 0, :east
unit :wizard, 188, 0, :east
unit :captive, 190, 0, :east
unit :archer, 192, 0, :east
unit :archer, 198, 0, :east
unit :thick_sludge, 201, 0, :east
unit :wizard, 214, 0, :east
unit :wizard, 218, 0, :east
unit :wizard, 220, 0, :east
unit :sludge, 222, 0, :east
unit :sludge, 236, 0, :east
unit :wizard, 248, 0, :east
unit :wizard, 265, 0, :east
unit :archer, 270, 0, :east
unit :thick_sludge, 273, 0, :east
unit :thick_sludge, 278, 0, :east
unit :thick_sludge, 281, 0, :east
unit :wizard, 282, 0, :east
unit :captive, 285, 0, :east
unit :captive, 292, 0, :east
unit :archer, 301, 0, :east
unit :thick_sludge, 302, 0, :east
unit :captive, 305, 0, :east
unit :wizard, 315, 0, :east
unit :sludge, 322, 0, :east
unit :archer, 323, 0, :east
unit :archer, 324, 0, :east
unit :wizard, 326, 0, :east
unit :archer, 334, 0, :east
unit :archer, 338, 0, :east
unit :archer, 343, 0, :east
unit :archer, 352, 0, :west
unit :wizard, 360, 0, :west
unit :archer, 364, 0, :west
unit :captive, 366, 0, :west
unit :captive, 369, 0, :west
unit :archer, 371, 0, :west
unit :archer, 372, 0, :west
unit :archer, 382, 0, :west
unit :archer, 385, 0, :west
unit :thick_sludge, 394, 0, :west
unit :captive, 396, 0, :west
unit :sludge, 399, 0, :west
unit :thick_sludge, 403, 0, :west
unit :archer, 407, 0, :west
unit :captive, 408, 0, :west
unit :thick_sludge, 409, 0, :west
unit :wizard, 418, 0, :west
unit :thick_sludge, 429, 0, :west
unit :thick_sludge, 431, 0, :west
unit :sludge, 432, 0, :west
unit :archer, 434, 0, :west
unit :archer, 443, 0, :west
unit :thick_sludge, 449, 0, :west
unit :archer, 460, 0, :west
unit :archer, 461, 0, :west
unit :sludge, 469, 0, :west
unit :archer, 473, 0, :west
unit :wizard, 480, 0, :west
unit :archer, 491, 0, :west
unit :archer, 494, 0, :west
unit :archer, 503, 0, :west
unit :archer, 506, 0, :west
unit :sludge, 508, 0, :west
unit :captive, 510, 0, :west
unit :thick_sludge, 511, 0, :west
unit :captive, 512, 0, :west
unit :captive, 513, 0, :west
unit :sludge, 516, 0, :west
unit :captive, 522, 0, :west
unit :archer, 525, 0, :west
unit :thick_sludge, 530, 0, :west
unit :wizard, 534, 0, :west
unit :archer, 540, 0, :west
unit :archer, 544, 0, :west
unit :captive, 546, 0, :west
unit :sludge, 548, 0, :west
unit :wizard, 551, 0, :west
unit :thick_sludge, 553, 0, :west
unit :thick_sludge, 555, 0, :west
unit :archer, 558, 0, :west
unit :sludge, 565, 0, :west
unit :sludge, 568, 0, :west
unit :captive, 570, 0, :west
unit :captive, 571, 0, :west
unit :thick_sludge, 576, 0, :west
unit :archer, 579, 0, :west
unit :thick_sludge, 583, 0, :west
unit :wizard, 595, 0, :west
unit :sludge, 598, 0, :west
unit :thick_sludge, 601, 0, :west
unit :captive, 603, 0, :west
unit :thick_sludge, 606, 0, :west
unit :captive, 607, 0, :west
unit :archer, 609, 0, :west
unit :sludge, 613, 0, :west
unit :wizard, 619, 0, :west
unit :archer, 621, 0, :west
unit :thick_sludge, 622, 0, :west
unit :sludge, 625, 0, :west
unit :captive, 626, 0, :west
unit :sludge, 628, 0, :west
unit :thick_sludge, 635, 0, :west
unit :wizard, 637, 0, :west
unit :sludge, 650, 0, :west
unit :captive, 657, 0, :west
unit :sludge, 662, 0, :west
unit :archer, 664, 0, :west
unit :thick_sludge, 665, 0, :west
unit :wizard, 668, 0, :west
unit :wizard, 673, 0, :west
unit :wizard, 679, 0, :west
unit :thick_sludge, 682, 0, :west
unit :sludge, 684, 0, :west
unit :thick_sludge, 686, 0, :west
unit :captive, 691, 0, :west
unit :thick_sludge, 693, 0, :west
unit :wizard, 696, 0, :west
unit :archer, 698, 0, :west
unit :wizard, 699, 0, :west
unit :captive, 701, 0, :west
unit :captive, 707, 0, :west
unit :sludge, 711, 0, :west
unit :thick_sludge, 712, 0, :west
unit :captive, 715, 0, :west
unit :thick_sludge, 728, 0, :west
unit :archer, 731, 0, :west
unit :wizard, 734, 0, :west
unit :archer, 736, 0, :west
unit :archer, 738, 0, :west
unit :archer, 739, 0, :west
unit :archer, 746, 0, :west
unit :archer, 748, 0, :west
unit :thick_sludge, 753, 0, :west
unit :sludge, 754, 0, :west
unit :sludge, 763, 0, :west
unit :sludge, 765, 0, :west
unit :thick_sludge, 768, 0, :west
unit :thick_sludge, 769, 0, :west
unit :archer, 772, 0, :west
unit :captive, 774, 0, :west
unit :sludge, 775, 0, :west
unit :archer, 780, 0, :west
unit :thick_sludge, 781, 0, :west
