#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   CwS     Cs  S      aCws     s a   C   C a  s      a Sa  s S   C     S    s a  Cs   w  C    w  SCS  a    C C         w s        w     s C  w    w       s  Ca         s       s s     C    w C C S    C  s  S   SS   a  a   aCs        s    w w C    C       w     s    w  S S    w a      w     C aC     C            S     a     a   S     @     w    aS     C  Swa      C   a a  w   s     w  C    C   s S     C     a    s    C    aa w    s SS    w  Ss SC w  w     ss   >       S a   a         S          s S   w         w    a    s w       sa s C   S     a        s    S   S     CS    assS       S a  s  a         s   |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 613
ace_score 3065
size 613, 1
stairs 464, 0

warrior 335, 0, :east

unit :captive, 3, 0, :east
unit :wizard, 4, 0, :east
unit :thick_sludge, 5, 0, :east
unit :captive, 11, 0, :east
unit :sludge, 12, 0, :east
unit :thick_sludge, 15, 0, :east
unit :archer, 22, 0, :east
unit :captive, 23, 0, :east
unit :wizard, 24, 0, :east
unit :sludge, 25, 0, :east
unit :sludge, 31, 0, :east
unit :archer, 33, 0, :east
unit :captive, 37, 0, :east
unit :captive, 41, 0, :east
unit :archer, 43, 0, :east
unit :sludge, 46, 0, :east
unit :archer, 53, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 56, 0, :east
unit :sludge, 59, 0, :east
unit :thick_sludge, 61, 0, :east
unit :captive, 65, 0, :east
unit :thick_sludge, 71, 0, :east
unit :sludge, 76, 0, :east
unit :archer, 78, 0, :east
unit :captive, 81, 0, :east
unit :sludge, 82, 0, :east
unit :wizard, 86, 0, :east
unit :captive, 89, 0, :east
unit :wizard, 94, 0, :east
unit :thick_sludge, 97, 0, :east
unit :captive, 98, 0, :east
unit :thick_sludge, 99, 0, :east
unit :archer, 102, 0, :east
unit :captive, 107, 0, :east
unit :captive, 109, 0, :east
unit :wizard, 119, 0, :east
unit :sludge, 121, 0, :east
unit :wizard, 130, 0, :east
unit :sludge, 136, 0, :east
unit :captive, 138, 0, :east
unit :wizard, 141, 0, :east
unit :wizard, 146, 0, :east
unit :sludge, 154, 0, :east
unit :captive, 157, 0, :east
unit :archer, 158, 0, :east
unit :sludge, 168, 0, :east
unit :sludge, 176, 0, :east
unit :sludge, 178, 0, :east
unit :captive, 184, 0, :east
unit :wizard, 189, 0, :east
unit :captive, 191, 0, :east
unit :captive, 193, 0, :east
unit :thick_sludge, 195, 0, :east
unit :captive, 200, 0, :east
unit :sludge, 203, 0, :east
unit :thick_sludge, 206, 0, :east
unit :thick_sludge, 210, 0, :east
unit :thick_sludge, 211, 0, :east
unit :archer, 215, 0, :east
unit :archer, 218, 0, :east
unit :archer, 222, 0, :east
unit :captive, 223, 0, :east
unit :sludge, 224, 0, :east
unit :sludge, 233, 0, :east
unit :wizard, 238, 0, :east
unit :wizard, 240, 0, :east
unit :captive, 242, 0, :east
unit :captive, 247, 0, :east
unit :wizard, 255, 0, :east
unit :sludge, 261, 0, :east
unit :wizard, 266, 0, :east
unit :thick_sludge, 269, 0, :east
unit :thick_sludge, 271, 0, :east
unit :wizard, 276, 0, :east
unit :archer, 278, 0, :east
unit :wizard, 285, 0, :east
unit :captive, 291, 0, :east
unit :archer, 293, 0, :east
unit :captive, 294, 0, :east
unit :captive, 300, 0, :east
unit :thick_sludge, 313, 0, :east
unit :archer, 319, 0, :east
unit :archer, 325, 0, :east
unit :thick_sludge, 329, 0, :east
unit :wizard, 341, 0, :west
unit :archer, 346, 0, :west
unit :thick_sludge, 347, 0, :west
unit :captive, 353, 0, :west
unit :thick_sludge, 356, 0, :west
unit :wizard, 357, 0, :west
unit :archer, 358, 0, :west
unit :captive, 365, 0, :west
unit :archer, 369, 0, :west
unit :archer, 371, 0, :west
unit :wizard, 374, 0, :west
unit :sludge, 378, 0, :west
unit :wizard, 384, 0, :west
unit :captive, 387, 0, :west
unit :captive, 392, 0, :west
unit :sludge, 396, 0, :west
unit :thick_sludge, 398, 0, :west
unit :captive, 404, 0, :west
unit :archer, 410, 0, :west
unit :sludge, 415, 0, :west
unit :captive, 420, 0, :west
unit :archer, 425, 0, :west
unit :archer, 426, 0, :west
unit :wizard, 428, 0, :west
unit :sludge, 433, 0, :west
unit :thick_sludge, 435, 0, :west
unit :thick_sludge, 436, 0, :west
unit :wizard, 441, 0, :west
unit :thick_sludge, 444, 0, :west
unit :sludge, 445, 0, :west
unit :thick_sludge, 447, 0, :west
unit :captive, 448, 0, :west
unit :wizard, 450, 0, :west
unit :wizard, 453, 0, :west
unit :sludge, 459, 0, :west
unit :sludge, 460, 0, :west
unit :thick_sludge, 472, 0, :west
unit :archer, 474, 0, :west
unit :archer, 478, 0, :west
unit :thick_sludge, 488, 0, :west
unit :sludge, 499, 0, :west
unit :thick_sludge, 501, 0, :west
unit :wizard, 505, 0, :west
unit :wizard, 515, 0, :west
unit :archer, 520, 0, :west
unit :sludge, 525, 0, :west
unit :wizard, 527, 0, :west
unit :sludge, 535, 0, :west
unit :archer, 536, 0, :west
unit :sludge, 538, 0, :west
unit :captive, 540, 0, :west
unit :thick_sludge, 544, 0, :west
unit :archer, 550, 0, :west
unit :sludge, 559, 0, :west
unit :thick_sludge, 564, 0, :west
unit :thick_sludge, 568, 0, :west
unit :captive, 574, 0, :west
unit :thick_sludge, 575, 0, :west
unit :archer, 580, 0, :west
unit :sludge, 581, 0, :west
unit :sludge, 582, 0, :west
unit :thick_sludge, 583, 0, :west
unit :thick_sludge, 591, 0, :west
unit :archer, 593, 0, :west
unit :sludge, 596, 0, :west
unit :archer, 599, 0, :west
unit :sludge, 609, 0, :west
