#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C    C   a  C w a   s s s    S       aa w S S        s S C        a     s w      C   sC      CS   s       S s    a S>  w  w    Sw               a C  a      w   s       w S C  C  s    C  a Sw     s     w  S C  w a a  s S   C         w    wa     C   a  s           a a  S      s  w  w    Cs S Sa       w sa   sa   s        C      S    C swC w s   w    wS       ss       C s    C S  s   w a  Cs       w  s aa w   w       a                  w w C  C S  s    S C  s       w           C  S    a a a   C      a  w s    SaCS     a Ca             SC      C   S  CS   C  S C  aSC a       a CC         a a    s           a S w   a C   w      @     sC aa S  C    s               S     w     S  C s a w S          w   S wC       Ss            s  C    C         w C  S S    S    Cw        w aa       a    a    w  w S      w       a C  C    C    s C     s  s a      as      a       s  C   a SC     a |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 887
ace_score 4435
size 887, 1
stairs 118, 0

warrior 633, 0, :east

unit :captive, 2, 0, :east
unit :captive, 7, 0, :east
unit :archer, 11, 0, :east
unit :captive, 14, 0, :east
unit :wizard, 16, 0, :east
unit :archer, 18, 0, :east
unit :sludge, 22, 0, :east
unit :sludge, 24, 0, :east
unit :sludge, 26, 0, :east
unit :thick_sludge, 31, 0, :east
unit :archer, 39, 0, :east
unit :archer, 40, 0, :east
unit :wizard, 42, 0, :east
unit :thick_sludge, 44, 0, :east
unit :thick_sludge, 46, 0, :east
unit :sludge, 55, 0, :east
unit :thick_sludge, 57, 0, :east
unit :captive, 59, 0, :east
unit :archer, 68, 0, :east
unit :sludge, 74, 0, :east
unit :wizard, 76, 0, :east
unit :captive, 83, 0, :east
unit :sludge, 87, 0, :east
unit :captive, 88, 0, :east
unit :captive, 95, 0, :east
unit :thick_sludge, 96, 0, :east
unit :sludge, 100, 0, :east
unit :thick_sludge, 108, 0, :east
unit :sludge, 110, 0, :east
unit :archer, 115, 0, :east
unit :thick_sludge, 117, 0, :east
unit :wizard, 121, 0, :east
unit :wizard, 124, 0, :east
unit :thick_sludge, 129, 0, :east
unit :wizard, 130, 0, :east
unit :archer, 146, 0, :east
unit :captive, 148, 0, :east
unit :archer, 151, 0, :east
unit :wizard, 158, 0, :east
unit :sludge, 162, 0, :east
unit :wizard, 170, 0, :east
unit :thick_sludge, 172, 0, :east
unit :captive, 174, 0, :east
unit :captive, 177, 0, :east
unit :sludge, 180, 0, :east
unit :captive, 185, 0, :east
unit :archer, 188, 0, :east
unit :thick_sludge, 190, 0, :east
unit :wizard, 191, 0, :east
unit :sludge, 197, 0, :east
unit :wizard, 203, 0, :east
unit :thick_sludge, 206, 0, :east
unit :captive, 208, 0, :east
unit :wizard, 211, 0, :east
unit :archer, 213, 0, :east
unit :archer, 215, 0, :east
unit :sludge, 218, 0, :east
unit :thick_sludge, 220, 0, :east
unit :captive, 224, 0, :east
unit :wizard, 234, 0, :east
unit :wizard, 239, 0, :east
unit :archer, 240, 0, :east
unit :captive, 246, 0, :east
unit :archer, 250, 0, :east
unit :sludge, 253, 0, :east
unit :archer, 265, 0, :east
unit :archer, 267, 0, :east
unit :thick_sludge, 270, 0, :east
unit :sludge, 277, 0, :east
unit :wizard, 280, 0, :east
unit :wizard, 283, 0, :east
unit :captive, 288, 0, :east
unit :sludge, 289, 0, :east
unit :thick_sludge, 291, 0, :east
unit :thick_sludge, 293, 0, :east
unit :archer, 294, 0, :east
unit :wizard, 302, 0, :east
unit :sludge, 304, 0, :east
unit :archer, 305, 0, :east
unit :sludge, 309, 0, :east
unit :archer, 310, 0, :east
unit :sludge, 314, 0, :east
unit :captive, 323, 0, :east
unit :thick_sludge, 330, 0, :east
unit :captive, 335, 0, :east
unit :sludge, 337, 0, :east
unit :wizard, 338, 0, :east
unit :captive, 339, 0, :east
unit :wizard, 341, 0, :east
unit :sludge, 343, 0, :east
unit :wizard, 347, 0, :east
unit :wizard, 352, 0, :east
unit :thick_sludge, 353, 0, :east
unit :sludge, 361, 0, :east
unit :sludge, 362, 0, :east
unit :captive, 370, 0, :east
unit :sludge, 372, 0, :east
unit :captive, 377, 0, :east
unit :thick_sludge, 379, 0, :east
unit :sludge, 382, 0, :east
unit :wizard, 386, 0, :east
unit :archer, 388, 0, :east
unit :captive, 391, 0, :east
unit :sludge, 392, 0, :east
unit :wizard, 400, 0, :east
unit :sludge, 403, 0, :east
unit :archer, 405, 0, :east
unit :archer, 406, 0, :east
unit :wizard, 408, 0, :east
unit :wizard, 412, 0, :east
unit :archer, 420, 0, :east
unit :wizard, 439, 0, :east
unit :wizard, 441, 0, :east
unit :captive, 443, 0, :east
unit :captive, 446, 0, :east
unit :thick_sludge, 448, 0, :east
unit :sludge, 451, 0, :east
unit :thick_sludge, 456, 0, :east
unit :captive, 458, 0, :east
unit :sludge, 461, 0, :east
unit :wizard, 469, 0, :east
unit :captive, 481, 0, :east
unit :thick_sludge, 484, 0, :east
unit :archer, 489, 0, :east
unit :archer, 491, 0, :east
unit :archer, 493, 0, :east
unit :captive, 497, 0, :east
unit :archer, 504, 0, :east
unit :wizard, 507, 0, :east
unit :sludge, 509, 0, :east
unit :thick_sludge, 514, 0, :east
unit :archer, 515, 0, :east
unit :captive, 516, 0, :east
unit :thick_sludge, 517, 0, :east
unit :archer, 523, 0, :east
unit :captive, 525, 0, :east
unit :archer, 526, 0, :east
unit :thick_sludge, 540, 0, :east
unit :captive, 541, 0, :east
unit :captive, 548, 0, :east
unit :thick_sludge, 552, 0, :east
unit :captive, 555, 0, :east
unit :thick_sludge, 556, 0, :east
unit :captive, 560, 0, :east
unit :thick_sludge, 563, 0, :east
unit :captive, 565, 0, :east
unit :archer, 568, 0, :east
unit :thick_sludge, 569, 0, :east
unit :captive, 570, 0, :east
unit :archer, 572, 0, :east
unit :archer, 580, 0, :east
unit :captive, 582, 0, :east
unit :captive, 583, 0, :east
unit :archer, 593, 0, :east
unit :archer, 595, 0, :east
unit :sludge, 600, 0, :east
unit :archer, 612, 0, :east
unit :thick_sludge, 614, 0, :east
unit :wizard, 616, 0, :east
unit :archer, 620, 0, :east
unit :captive, 622, 0, :east
unit :wizard, 626, 0, :east
unit :sludge, 639, 0, :west
unit :captive, 640, 0, :west
unit :archer, 642, 0, :west
unit :archer, 643, 0, :west
unit :thick_sludge, 645, 0, :west
unit :captive, 648, 0, :west
unit :sludge, 653, 0, :west
unit :thick_sludge, 669, 0, :west
unit :wizard, 675, 0, :west
unit :thick_sludge, 681, 0, :west
unit :captive, 684, 0, :west
unit :sludge, 686, 0, :west
unit :archer, 688, 0, :west
unit :wizard, 690, 0, :west
unit :thick_sludge, 692, 0, :west
unit :wizard, 703, 0, :west
unit :thick_sludge, 707, 0, :west
unit :wizard, 709, 0, :west
unit :captive, 710, 0, :west
unit :thick_sludge, 718, 0, :west
unit :sludge, 719, 0, :west
unit :sludge, 732, 0, :west
unit :captive, 735, 0, :west
unit :captive, 740, 0, :west
unit :wizard, 750, 0, :west
unit :captive, 752, 0, :west
unit :thick_sludge, 755, 0, :west
unit :thick_sludge, 757, 0, :west
unit :thick_sludge, 762, 0, :west
unit :captive, 767, 0, :west
unit :wizard, 768, 0, :west
unit :wizard, 777, 0, :west
unit :archer, 779, 0, :west
unit :archer, 780, 0, :west
unit :archer, 788, 0, :west
unit :archer, 793, 0, :west
unit :wizard, 798, 0, :west
unit :wizard, 801, 0, :west
unit :thick_sludge, 803, 0, :west
unit :wizard, 810, 0, :west
unit :archer, 818, 0, :west
unit :captive, 820, 0, :west
unit :captive, 823, 0, :west
unit :captive, 828, 0, :west
unit :sludge, 833, 0, :west
unit :captive, 835, 0, :west
unit :sludge, 841, 0, :west
unit :sludge, 844, 0, :west
unit :archer, 846, 0, :west
unit :archer, 853, 0, :west
unit :sludge, 854, 0, :west
unit :archer, 861, 0, :west
unit :sludge, 869, 0, :west
unit :captive, 872, 0, :west
unit :archer, 876, 0, :west
unit :thick_sludge, 878, 0, :west
unit :captive, 879, 0, :west
unit :archer, 885, 0, :west
