#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     S    C     s CSC   S  w     Ss w   aS aws Cs CC     s  Cs     S        a      s C   Sa   sC         SC   a a C s          s      S             SwC      S    Sss    a        Cw       S  S      wss  S    S  S C     s a S    a  Cs  s C S        C    SC  S   C a   a >       s   S       aSC     s     S    w w     sS w  s        a  a    Cw s  s  C    sa w  C    C    C a      S       S   S    s  S       s        s s         S       a      aa s  C   S      s  a  w  w  w    aSs   s C             s            S      a S       a      w s S  C  S     w aa        a      w      w   sS    sS   C  CC         Css     wC    Sw   S   S      S a s     S      C         w S    a     S      @        S SS  C    sa           sCs     w   w    w s awa     C  C     s   S    as        a Cw  s    s   a s            S  a     a S   C    Ss a          s    w    a C            w  s   as S S   aC         S   CaC s s    C a  S s    s  C |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 920
ace_score 4600
size 920, 1
stairs 268, 0

warrior 682, 0, :east

unit :thick_sludge, 5, 0, :east
unit :captive, 10, 0, :east
unit :sludge, 16, 0, :east
unit :captive, 18, 0, :east
unit :thick_sludge, 19, 0, :east
unit :captive, 20, 0, :east
unit :thick_sludge, 24, 0, :east
unit :wizard, 27, 0, :east
unit :thick_sludge, 33, 0, :east
unit :sludge, 34, 0, :east
unit :wizard, 36, 0, :east
unit :archer, 40, 0, :east
unit :thick_sludge, 41, 0, :east
unit :archer, 43, 0, :east
unit :wizard, 44, 0, :east
unit :sludge, 45, 0, :east
unit :captive, 47, 0, :east
unit :sludge, 48, 0, :east
unit :captive, 50, 0, :east
unit :captive, 51, 0, :east
unit :sludge, 57, 0, :east
unit :captive, 60, 0, :east
unit :sludge, 61, 0, :east
unit :thick_sludge, 67, 0, :east
unit :archer, 76, 0, :east
unit :sludge, 83, 0, :east
unit :captive, 85, 0, :east
unit :thick_sludge, 89, 0, :east
unit :archer, 90, 0, :east
unit :sludge, 94, 0, :east
unit :captive, 95, 0, :east
unit :thick_sludge, 105, 0, :east
unit :captive, 106, 0, :east
unit :archer, 110, 0, :east
unit :archer, 112, 0, :east
unit :captive, 114, 0, :east
unit :sludge, 116, 0, :east
unit :sludge, 127, 0, :east
unit :thick_sludge, 134, 0, :east
unit :thick_sludge, 148, 0, :east
unit :wizard, 149, 0, :east
unit :captive, 150, 0, :east
unit :thick_sludge, 157, 0, :east
unit :thick_sludge, 162, 0, :east
unit :sludge, 163, 0, :east
unit :sludge, 164, 0, :east
unit :archer, 169, 0, :east
unit :captive, 178, 0, :east
unit :wizard, 179, 0, :east
unit :thick_sludge, 187, 0, :east
unit :thick_sludge, 190, 0, :east
unit :wizard, 197, 0, :east
unit :sludge, 198, 0, :east
unit :sludge, 199, 0, :east
unit :thick_sludge, 202, 0, :east
unit :thick_sludge, 207, 0, :east
unit :thick_sludge, 210, 0, :east
unit :captive, 212, 0, :east
unit :sludge, 218, 0, :east
unit :archer, 220, 0, :east
unit :thick_sludge, 222, 0, :east
unit :archer, 227, 0, :east
unit :captive, 230, 0, :east
unit :sludge, 231, 0, :east
unit :sludge, 234, 0, :east
unit :captive, 236, 0, :east
unit :thick_sludge, 238, 0, :east
unit :captive, 247, 0, :east
unit :thick_sludge, 252, 0, :east
unit :captive, 253, 0, :east
unit :thick_sludge, 256, 0, :east
unit :captive, 260, 0, :east
unit :archer, 262, 0, :east
unit :archer, 266, 0, :east
unit :sludge, 276, 0, :east
unit :thick_sludge, 280, 0, :east
unit :archer, 288, 0, :east
unit :thick_sludge, 289, 0, :east
unit :captive, 290, 0, :east
unit :sludge, 296, 0, :east
unit :thick_sludge, 302, 0, :east
unit :wizard, 307, 0, :east
unit :wizard, 309, 0, :east
unit :sludge, 315, 0, :east
unit :thick_sludge, 316, 0, :east
unit :wizard, 318, 0, :east
unit :sludge, 321, 0, :east
unit :archer, 330, 0, :east
unit :archer, 333, 0, :east
unit :captive, 338, 0, :east
unit :wizard, 339, 0, :east
unit :sludge, 341, 0, :east
unit :sludge, 344, 0, :east
unit :captive, 347, 0, :east
unit :sludge, 352, 0, :east
unit :archer, 353, 0, :east
unit :wizard, 355, 0, :east
unit :captive, 358, 0, :east
unit :captive, 363, 0, :east
unit :captive, 368, 0, :east
unit :archer, 370, 0, :east
unit :thick_sludge, 377, 0, :east
unit :thick_sludge, 385, 0, :east
unit :thick_sludge, 389, 0, :east
unit :sludge, 394, 0, :east
unit :thick_sludge, 397, 0, :east
unit :sludge, 405, 0, :east
unit :sludge, 414, 0, :east
unit :sludge, 416, 0, :east
unit :thick_sludge, 426, 0, :east
unit :archer, 434, 0, :east
unit :archer, 441, 0, :east
unit :archer, 442, 0, :east
unit :sludge, 444, 0, :east
unit :captive, 447, 0, :east
unit :thick_sludge, 451, 0, :east
unit :sludge, 458, 0, :east
unit :archer, 461, 0, :east
unit :wizard, 464, 0, :east
unit :wizard, 467, 0, :east
unit :wizard, 470, 0, :east
unit :archer, 475, 0, :east
unit :thick_sludge, 476, 0, :east
unit :sludge, 477, 0, :east
unit :sludge, 481, 0, :east
unit :captive, 483, 0, :east
unit :sludge, 497, 0, :east
unit :thick_sludge, 510, 0, :east
unit :archer, 517, 0, :east
unit :thick_sludge, 519, 0, :east
unit :archer, 527, 0, :east
unit :wizard, 534, 0, :east
unit :sludge, 536, 0, :east
unit :thick_sludge, 538, 0, :east
unit :captive, 541, 0, :east
unit :thick_sludge, 544, 0, :east
unit :wizard, 550, 0, :east
unit :archer, 552, 0, :east
unit :archer, 553, 0, :east
unit :archer, 562, 0, :east
unit :wizard, 569, 0, :east
unit :wizard, 576, 0, :east
unit :sludge, 580, 0, :east
unit :thick_sludge, 581, 0, :east
unit :sludge, 586, 0, :east
unit :thick_sludge, 587, 0, :east
unit :captive, 591, 0, :east
unit :captive, 594, 0, :east
unit :captive, 595, 0, :east
unit :captive, 605, 0, :east
unit :sludge, 606, 0, :east
unit :sludge, 607, 0, :east
unit :wizard, 613, 0, :east
unit :captive, 614, 0, :east
unit :thick_sludge, 619, 0, :east
unit :wizard, 620, 0, :east
unit :thick_sludge, 624, 0, :east
unit :thick_sludge, 628, 0, :east
unit :thick_sludge, 635, 0, :east
unit :archer, 637, 0, :east
unit :sludge, 639, 0, :east
unit :thick_sludge, 645, 0, :east
unit :captive, 652, 0, :east
unit :wizard, 662, 0, :east
unit :thick_sludge, 664, 0, :east
unit :archer, 669, 0, :east
unit :thick_sludge, 675, 0, :east
unit :thick_sludge, 691, 0, :west
unit :thick_sludge, 693, 0, :west
unit :thick_sludge, 694, 0, :west
unit :captive, 697, 0, :west
unit :sludge, 702, 0, :west
unit :archer, 703, 0, :west
unit :sludge, 715, 0, :west
unit :captive, 716, 0, :west
unit :sludge, 717, 0, :west
unit :wizard, 723, 0, :west
unit :wizard, 727, 0, :west
unit :wizard, 732, 0, :west
unit :sludge, 734, 0, :west
unit :archer, 736, 0, :west
unit :wizard, 737, 0, :west
unit :archer, 738, 0, :west
unit :captive, 744, 0, :west
unit :captive, 747, 0, :west
unit :sludge, 753, 0, :west
unit :thick_sludge, 757, 0, :west
unit :archer, 762, 0, :west
unit :sludge, 763, 0, :west
unit :archer, 772, 0, :west
unit :captive, 774, 0, :west
unit :wizard, 775, 0, :west
unit :sludge, 778, 0, :west
unit :sludge, 783, 0, :west
unit :archer, 787, 0, :west
unit :sludge, 789, 0, :west
unit :thick_sludge, 802, 0, :west
unit :archer, 805, 0, :west
unit :archer, 811, 0, :west
unit :thick_sludge, 813, 0, :west
unit :captive, 817, 0, :west
unit :thick_sludge, 822, 0, :west
unit :sludge, 823, 0, :west
unit :archer, 825, 0, :west
unit :sludge, 836, 0, :west
unit :wizard, 841, 0, :west
unit :archer, 846, 0, :west
unit :captive, 848, 0, :west
unit :wizard, 861, 0, :west
unit :sludge, 864, 0, :west
unit :archer, 868, 0, :west
unit :sludge, 869, 0, :west
unit :thick_sludge, 871, 0, :west
unit :thick_sludge, 873, 0, :west
unit :archer, 877, 0, :west
unit :captive, 878, 0, :west
unit :thick_sludge, 888, 0, :west
unit :captive, 892, 0, :west
unit :archer, 893, 0, :west
unit :captive, 894, 0, :west
unit :sludge, 896, 0, :west
unit :sludge, 898, 0, :west
unit :captive, 903, 0, :west
unit :archer, 905, 0, :west
unit :thick_sludge, 908, 0, :west
unit :sludge, 910, 0, :west
unit :sludge, 915, 0, :west
unit :captive, 918, 0, :west
