#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S              a   wS S     C  S C  a    s   S     S     aw  s          aSa    a S s C                   a  S     s   s      C a   a S     s w  w C  S s           s        S   w      w   S    S a                  a   w        S  s s C        C C  w s    w w         a S      a   s    a S  sw S      S     Sw s   CS       S         w    Cs  C sw CS      ssCS C   w  w  S   w  a   s   S wS as S w         Ss  @         a   S a   a w  sC   S  a  w        S  sa  w ws        aC   a s          s         w     sa s   w s   a  a s a   a  CS  S wS  S  C      Sw      s     C   s           w      a    C   as         C      sS  w   s       w S  w     C  asS a   S    wsw    C  a    C   S Ca  C   C    sa   wS C a                  C   C  w   C  C       CS     Cs w          C    w w C         s s    C    a>CS a          w   a   w        S sa  w C  a         s  s           Cswa w    Ss     Ss           aw    S     w w       S Cs as   w             C   C a    a    C   s  a S     w a   C  ssw  |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 986
ace_score 4930
size 986, 1
stairs 797, 0

warrior 407, 0, :east

unit :thick_sludge, 0, 0, :east
unit :archer, 15, 0, :east
unit :wizard, 19, 0, :east
unit :thick_sludge, 20, 0, :east
unit :thick_sludge, 22, 0, :east
unit :captive, 28, 0, :east
unit :thick_sludge, 31, 0, :east
unit :captive, 33, 0, :east
unit :archer, 36, 0, :east
unit :sludge, 41, 0, :east
unit :thick_sludge, 45, 0, :east
unit :thick_sludge, 51, 0, :east
unit :archer, 57, 0, :east
unit :wizard, 58, 0, :east
unit :sludge, 61, 0, :east
unit :archer, 72, 0, :east
unit :thick_sludge, 73, 0, :east
unit :archer, 74, 0, :east
unit :archer, 79, 0, :east
unit :thick_sludge, 81, 0, :east
unit :sludge, 83, 0, :east
unit :captive, 85, 0, :east
unit :archer, 105, 0, :east
unit :thick_sludge, 108, 0, :east
unit :sludge, 114, 0, :east
unit :sludge, 118, 0, :east
unit :captive, 125, 0, :east
unit :archer, 127, 0, :east
unit :archer, 131, 0, :east
unit :thick_sludge, 133, 0, :east
unit :sludge, 139, 0, :east
unit :wizard, 141, 0, :east
unit :wizard, 144, 0, :east
unit :captive, 146, 0, :east
unit :thick_sludge, 149, 0, :east
unit :sludge, 151, 0, :east
unit :sludge, 163, 0, :east
unit :thick_sludge, 172, 0, :east
unit :wizard, 176, 0, :east
unit :wizard, 183, 0, :east
unit :thick_sludge, 187, 0, :east
unit :thick_sludge, 192, 0, :east
unit :archer, 194, 0, :east
unit :archer, 213, 0, :east
unit :wizard, 217, 0, :east
unit :thick_sludge, 226, 0, :east
unit :sludge, 229, 0, :east
unit :sludge, 231, 0, :east
unit :captive, 233, 0, :east
unit :captive, 242, 0, :east
unit :captive, 244, 0, :east
unit :wizard, 247, 0, :east
unit :sludge, 249, 0, :east
unit :wizard, 254, 0, :east
unit :wizard, 256, 0, :east
unit :archer, 266, 0, :east
unit :thick_sludge, 268, 0, :east
unit :archer, 275, 0, :east
unit :sludge, 279, 0, :east
unit :archer, 284, 0, :east
unit :thick_sludge, 286, 0, :east
unit :sludge, 289, 0, :east
unit :wizard, 290, 0, :east
unit :thick_sludge, 292, 0, :east
unit :thick_sludge, 299, 0, :east
unit :thick_sludge, 305, 0, :east
unit :wizard, 306, 0, :east
unit :sludge, 308, 0, :east
unit :captive, 312, 0, :east
unit :thick_sludge, 313, 0, :east
unit :thick_sludge, 321, 0, :east
unit :wizard, 331, 0, :east
unit :captive, 336, 0, :east
unit :sludge, 337, 0, :east
unit :captive, 340, 0, :east
unit :sludge, 342, 0, :east
unit :wizard, 343, 0, :east
unit :captive, 345, 0, :east
unit :thick_sludge, 346, 0, :east
unit :sludge, 353, 0, :east
unit :sludge, 354, 0, :east
unit :captive, 355, 0, :east
unit :thick_sludge, 356, 0, :east
unit :captive, 358, 0, :east
unit :wizard, 362, 0, :east
unit :wizard, 365, 0, :east
unit :thick_sludge, 368, 0, :east
unit :wizard, 372, 0, :east
unit :archer, 375, 0, :east
unit :sludge, 379, 0, :east
unit :thick_sludge, 383, 0, :east
unit :wizard, 385, 0, :east
unit :thick_sludge, 386, 0, :east
unit :archer, 388, 0, :east
unit :sludge, 389, 0, :east
unit :thick_sludge, 391, 0, :east
unit :wizard, 393, 0, :east
unit :thick_sludge, 403, 0, :east
unit :sludge, 404, 0, :east
unit :archer, 417, 0, :west
unit :thick_sludge, 421, 0, :west
unit :archer, 423, 0, :west
unit :archer, 427, 0, :west
unit :wizard, 429, 0, :west
unit :sludge, 432, 0, :west
unit :captive, 433, 0, :west
unit :thick_sludge, 437, 0, :west
unit :archer, 440, 0, :west
unit :wizard, 443, 0, :west
unit :thick_sludge, 452, 0, :west
unit :sludge, 455, 0, :west
unit :archer, 456, 0, :west
unit :wizard, 459, 0, :west
unit :wizard, 461, 0, :west
unit :sludge, 462, 0, :west
unit :archer, 471, 0, :west
unit :captive, 472, 0, :west
unit :archer, 476, 0, :west
unit :sludge, 478, 0, :west
unit :sludge, 489, 0, :west
unit :wizard, 499, 0, :west
unit :sludge, 505, 0, :west
unit :archer, 506, 0, :west
unit :sludge, 508, 0, :west
unit :wizard, 512, 0, :west
unit :sludge, 514, 0, :west
unit :archer, 518, 0, :west
unit :archer, 521, 0, :west
unit :sludge, 523, 0, :west
unit :archer, 525, 0, :west
unit :archer, 529, 0, :west
unit :captive, 532, 0, :west
unit :thick_sludge, 533, 0, :west
unit :thick_sludge, 536, 0, :west
unit :wizard, 538, 0, :west
unit :thick_sludge, 539, 0, :west
unit :thick_sludge, 542, 0, :west
unit :captive, 545, 0, :west
unit :thick_sludge, 552, 0, :west
unit :wizard, 553, 0, :west
unit :sludge, 560, 0, :west
unit :captive, 566, 0, :west
unit :sludge, 570, 0, :west
unit :wizard, 582, 0, :west
unit :archer, 589, 0, :west
unit :captive, 594, 0, :west
unit :archer, 598, 0, :west
unit :sludge, 599, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 616, 0, :west
unit :thick_sludge, 617, 0, :west
unit :wizard, 620, 0, :west
unit :sludge, 624, 0, :west
unit :wizard, 632, 0, :west
unit :thick_sludge, 634, 0, :west
unit :wizard, 637, 0, :west
unit :captive, 643, 0, :west
unit :archer, 646, 0, :west
unit :sludge, 647, 0, :west
unit :thick_sludge, 648, 0, :west
unit :archer, 650, 0, :west
unit :thick_sludge, 654, 0, :west
unit :wizard, 659, 0, :west
unit :sludge, 660, 0, :west
unit :wizard, 661, 0, :west
unit :captive, 666, 0, :west
unit :archer, 669, 0, :west
unit :captive, 674, 0, :west
unit :thick_sludge, 678, 0, :west
unit :captive, 680, 0, :west
unit :archer, 681, 0, :west
unit :captive, 684, 0, :west
unit :captive, 688, 0, :west
unit :sludge, 693, 0, :west
unit :archer, 694, 0, :west
unit :wizard, 698, 0, :west
unit :thick_sludge, 699, 0, :west
unit :captive, 701, 0, :west
unit :archer, 703, 0, :west
unit :captive, 722, 0, :west
unit :captive, 726, 0, :west
unit :wizard, 729, 0, :west
unit :captive, 733, 0, :west
unit :captive, 736, 0, :west
unit :captive, 744, 0, :west
unit :thick_sludge, 745, 0, :west
unit :captive, 751, 0, :west
unit :sludge, 752, 0, :west
unit :wizard, 754, 0, :west
unit :captive, 765, 0, :west
unit :wizard, 770, 0, :west
unit :wizard, 772, 0, :west
unit :captive, 774, 0, :west
unit :sludge, 784, 0, :west
unit :sludge, 786, 0, :west
unit :captive, 791, 0, :west
unit :archer, 796, 0, :west
unit :captive, 798, 0, :west
unit :thick_sludge, 799, 0, :west
unit :archer, 801, 0, :west
unit :wizard, 812, 0, :west
unit :archer, 816, 0, :west
unit :wizard, 820, 0, :west
unit :thick_sludge, 829, 0, :west
unit :sludge, 831, 0, :west
unit :archer, 832, 0, :west
unit :wizard, 835, 0, :west
unit :captive, 837, 0, :west
unit :archer, 840, 0, :west
unit :sludge, 850, 0, :west
unit :sludge, 853, 0, :west
unit :captive, 865, 0, :west
unit :sludge, 866, 0, :west
unit :wizard, 867, 0, :west
unit :archer, 868, 0, :west
unit :wizard, 870, 0, :west
unit :thick_sludge, 875, 0, :west
unit :sludge, 876, 0, :west
unit :thick_sludge, 882, 0, :west
unit :sludge, 883, 0, :west
unit :archer, 895, 0, :west
unit :wizard, 896, 0, :west
unit :thick_sludge, 901, 0, :west
unit :wizard, 907, 0, :west
unit :wizard, 909, 0, :west
unit :thick_sludge, 917, 0, :west
unit :captive, 919, 0, :west
unit :sludge, 920, 0, :west
unit :archer, 922, 0, :west
unit :sludge, 923, 0, :west
unit :wizard, 927, 0, :west
unit :captive, 941, 0, :west
unit :captive, 945, 0, :west
unit :archer, 947, 0, :west
unit :archer, 952, 0, :west
unit :captive, 957, 0, :west
unit :sludge, 961, 0, :west
unit :archer, 964, 0, :west
unit :thick_sludge, 966, 0, :west
unit :wizard, 972, 0, :west
unit :archer, 974, 0, :west
unit :captive, 978, 0, :west
unit :sludge, 981, 0, :west
unit :sludge, 982, 0, :west
unit :wizard, 983, 0, :west
