#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     w sSsa    S   a     Ss     C      C    w  a w   S   S     C     w      S s    w      S      a  C     a S    S  a      C   a     w a        s CS C   Ca s   C  a ss        s  C     C  s     w   aS  a a a    C  C    sS a    a a  w  S          C   S  s          s   wsaC                 a  C  Ca  sC aC C C     w      w w    C  C w        C     S    S           a   w  S S>      S   C  C   S   aa w ss S C  s     Cs        SC         w     C S   a     Cs       C S  w w     S C      Sa          a    w      C   C s        S  Ca      a w      a  a       s C  w s        wC    S  aa   aC        C w a       S s    C   w    s     S             S   w   @         sC    as      Cw aa   s              s Ss    C        w            a  w     w  asSCSa  s C  s            aS    as  C  w CC S  Sa SSa        s   S  C     a  C     S s Ca S s   s     s    w w   S   a  aw w     S         C sS  a                 w       S C     w S w   C        w w         a    sa  Cwa  a  a     C               w S aCa S C a |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 1000
ace_score 5000
size 1000, 1
stairs 373, 0

warrior 650, 0, :east

unit :wizard, 5, 0, :east
unit :sludge, 7, 0, :east
unit :thick_sludge, 8, 0, :east
unit :sludge, 9, 0, :east
unit :archer, 10, 0, :east
unit :thick_sludge, 15, 0, :east
unit :archer, 19, 0, :east
unit :thick_sludge, 25, 0, :east
unit :sludge, 26, 0, :east
unit :captive, 32, 0, :east
unit :captive, 39, 0, :east
unit :wizard, 44, 0, :east
unit :archer, 47, 0, :east
unit :wizard, 49, 0, :east
unit :thick_sludge, 53, 0, :east
unit :thick_sludge, 57, 0, :east
unit :captive, 63, 0, :east
unit :wizard, 69, 0, :east
unit :thick_sludge, 76, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 83, 0, :east
unit :thick_sludge, 90, 0, :east
unit :archer, 97, 0, :east
unit :captive, 100, 0, :east
unit :archer, 106, 0, :east
unit :thick_sludge, 108, 0, :east
unit :thick_sludge, 113, 0, :east
unit :archer, 116, 0, :east
unit :captive, 123, 0, :east
unit :archer, 127, 0, :east
unit :wizard, 133, 0, :east
unit :archer, 135, 0, :east
unit :sludge, 144, 0, :east
unit :captive, 146, 0, :east
unit :thick_sludge, 147, 0, :east
unit :captive, 149, 0, :east
unit :captive, 153, 0, :east
unit :archer, 154, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 160, 0, :east
unit :archer, 163, 0, :east
unit :sludge, 165, 0, :east
unit :sludge, 166, 0, :east
unit :sludge, 175, 0, :east
unit :captive, 178, 0, :east
unit :captive, 184, 0, :east
unit :sludge, 187, 0, :east
unit :wizard, 193, 0, :east
unit :archer, 197, 0, :east
unit :thick_sludge, 198, 0, :east
unit :archer, 201, 0, :east
unit :archer, 203, 0, :east
unit :archer, 205, 0, :east
unit :captive, 210, 0, :east
unit :captive, 213, 0, :east
unit :sludge, 218, 0, :east
unit :thick_sludge, 219, 0, :east
unit :archer, 221, 0, :east
unit :archer, 226, 0, :east
unit :archer, 228, 0, :east
unit :wizard, 231, 0, :east
unit :thick_sludge, 234, 0, :east
unit :captive, 245, 0, :east
unit :thick_sludge, 249, 0, :east
unit :sludge, 252, 0, :east
unit :sludge, 263, 0, :east
unit :wizard, 267, 0, :east
unit :sludge, 268, 0, :east
unit :archer, 269, 0, :east
unit :captive, 270, 0, :east
unit :archer, 288, 0, :east
unit :captive, 291, 0, :east
unit :captive, 294, 0, :east
unit :archer, 295, 0, :east
unit :sludge, 298, 0, :east
unit :captive, 299, 0, :east
unit :archer, 301, 0, :east
unit :captive, 302, 0, :east
unit :captive, 304, 0, :east
unit :captive, 306, 0, :east
unit :wizard, 312, 0, :east
unit :wizard, 319, 0, :east
unit :wizard, 321, 0, :east
unit :captive, 326, 0, :east
unit :captive, 329, 0, :east
unit :wizard, 331, 0, :east
unit :captive, 340, 0, :east
unit :thick_sludge, 346, 0, :east
unit :thick_sludge, 351, 0, :east
unit :archer, 363, 0, :east
unit :wizard, 367, 0, :east
unit :thick_sludge, 370, 0, :east
unit :thick_sludge, 372, 0, :east
unit :thick_sludge, 380, 0, :east
unit :captive, 384, 0, :east
unit :captive, 387, 0, :east
unit :thick_sludge, 391, 0, :east
unit :archer, 395, 0, :east
unit :archer, 396, 0, :east
unit :wizard, 398, 0, :east
unit :sludge, 400, 0, :east
unit :sludge, 401, 0, :east
unit :thick_sludge, 403, 0, :east
unit :captive, 405, 0, :east
unit :sludge, 408, 0, :east
unit :captive, 414, 0, :east
unit :sludge, 415, 0, :east
unit :thick_sludge, 424, 0, :east
unit :captive, 425, 0, :east
unit :wizard, 435, 0, :east
unit :captive, 441, 0, :east
unit :thick_sludge, 443, 0, :east
unit :archer, 447, 0, :east
unit :captive, 453, 0, :east
unit :sludge, 454, 0, :east
unit :captive, 462, 0, :east
unit :thick_sludge, 464, 0, :east
unit :wizard, 467, 0, :east
unit :wizard, 469, 0, :east
unit :thick_sludge, 475, 0, :east
unit :captive, 477, 0, :east
unit :thick_sludge, 484, 0, :east
unit :archer, 485, 0, :east
unit :archer, 496, 0, :east
unit :wizard, 501, 0, :east
unit :captive, 508, 0, :east
unit :captive, 512, 0, :east
unit :sludge, 514, 0, :east
unit :thick_sludge, 523, 0, :east
unit :captive, 526, 0, :east
unit :archer, 527, 0, :east
unit :archer, 534, 0, :east
unit :wizard, 536, 0, :east
unit :archer, 543, 0, :east
unit :archer, 546, 0, :east
unit :sludge, 554, 0, :east
unit :captive, 556, 0, :east
unit :wizard, 559, 0, :east
unit :sludge, 561, 0, :east
unit :wizard, 570, 0, :east
unit :captive, 571, 0, :east
unit :thick_sludge, 576, 0, :east
unit :archer, 579, 0, :east
unit :archer, 580, 0, :east
unit :archer, 584, 0, :east
unit :captive, 585, 0, :east
unit :captive, 594, 0, :east
unit :wizard, 596, 0, :east
unit :archer, 598, 0, :east
unit :thick_sludge, 606, 0, :east
unit :sludge, 608, 0, :east
unit :captive, 613, 0, :east
unit :wizard, 617, 0, :east
unit :sludge, 622, 0, :east
unit :thick_sludge, 628, 0, :east
unit :thick_sludge, 642, 0, :east
unit :wizard, 646, 0, :east
unit :sludge, 660, 0, :west
unit :captive, 661, 0, :west
unit :archer, 666, 0, :west
unit :sludge, 667, 0, :west
unit :captive, 674, 0, :west
unit :wizard, 675, 0, :west
unit :archer, 677, 0, :west
unit :archer, 678, 0, :west
unit :sludge, 682, 0, :west
unit :sludge, 697, 0, :west
unit :thick_sludge, 699, 0, :west
unit :sludge, 700, 0, :west
unit :captive, 705, 0, :west
unit :wizard, 714, 0, :west
unit :archer, 727, 0, :west
unit :wizard, 730, 0, :west
unit :wizard, 736, 0, :west
unit :archer, 739, 0, :west
unit :sludge, 740, 0, :west
unit :thick_sludge, 741, 0, :west
unit :captive, 742, 0, :west
unit :thick_sludge, 743, 0, :west
unit :archer, 744, 0, :west
unit :sludge, 747, 0, :west
unit :captive, 749, 0, :west
unit :sludge, 752, 0, :west
unit :archer, 765, 0, :west
unit :thick_sludge, 766, 0, :west
unit :archer, 771, 0, :west
unit :sludge, 772, 0, :west
unit :captive, 775, 0, :west
unit :wizard, 778, 0, :west
unit :captive, 780, 0, :west
unit :captive, 781, 0, :west
unit :thick_sludge, 783, 0, :west
unit :thick_sludge, 786, 0, :west
unit :archer, 787, 0, :west
unit :thick_sludge, 789, 0, :west
unit :thick_sludge, 790, 0, :west
unit :archer, 791, 0, :west
unit :sludge, 800, 0, :west
unit :thick_sludge, 804, 0, :west
unit :captive, 807, 0, :west
unit :archer, 813, 0, :west
unit :captive, 816, 0, :west
unit :thick_sludge, 822, 0, :west
unit :sludge, 824, 0, :west
unit :captive, 826, 0, :west
unit :archer, 827, 0, :west
unit :thick_sludge, 829, 0, :west
unit :sludge, 831, 0, :west
unit :sludge, 835, 0, :west
unit :sludge, 841, 0, :west
unit :wizard, 846, 0, :west
unit :wizard, 848, 0, :west
unit :thick_sludge, 852, 0, :west
unit :archer, 856, 0, :west
unit :archer, 859, 0, :west
unit :wizard, 860, 0, :west
unit :wizard, 862, 0, :west
unit :thick_sludge, 868, 0, :west
unit :captive, 878, 0, :west
unit :sludge, 880, 0, :west
unit :thick_sludge, 881, 0, :west
unit :archer, 884, 0, :west
unit :wizard, 902, 0, :west
unit :thick_sludge, 910, 0, :west
unit :captive, 912, 0, :west
unit :wizard, 918, 0, :west
unit :thick_sludge, 920, 0, :west
unit :wizard, 922, 0, :west
unit :captive, 926, 0, :west
unit :wizard, 935, 0, :west
unit :wizard, 937, 0, :west
unit :archer, 947, 0, :west
unit :sludge, 952, 0, :west
unit :archer, 953, 0, :west
unit :captive, 956, 0, :west
unit :wizard, 957, 0, :west
unit :archer, 958, 0, :west
unit :archer, 961, 0, :west
unit :archer, 964, 0, :west
unit :captive, 970, 0, :west
unit :wizard, 986, 0, :west
unit :thick_sludge, 988, 0, :west
unit :archer, 990, 0, :west
unit :captive, 991, 0, :west
unit :archer, 992, 0, :west
unit :thick_sludge, 994, 0, :west
unit :captive, 996, 0, :west
unit :archer, 998, 0, :west
