#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    SC SS    a   s   s a Ss    S s  a  CS  w      a           s s  a C      s        C       a   a   w    s       as           a w       S         a     w a    >         s  a  CC  w   a w  C   w  S     aCa   s   S   s   s  S    a  S a    S     s        ss w S s   S   C  s a  Ss s S    a   s   C w   C  sC C s a     ssC    C S   a   s   w C w      sa s sS  a    C             C  s  @    s         S     a  s     C   ws  sSS Sa     w s a         s  aS         a  C  s   s   a         s SS  aSS     a    Ss      S  s       a w     w   w  s  a    w    s s  s        s    C       S    s    a   s          SawS  CS   s   a   S a         C     s  sa  S  a S               Sw          w    a                 w   C   C  a  a   S   aS C  S|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 730
ace_score 3650
size 730, 1
stairs 160, 0

warrior 382, 0, :east

unit :thick_sludge, 4, 0, :east
unit :captive, 5, 0, :east
unit :thick_sludge, 7, 0, :east
unit :thick_sludge, 8, 0, :east
unit :archer, 13, 0, :east
unit :sludge, 17, 0, :east
unit :sludge, 21, 0, :east
unit :archer, 23, 0, :east
unit :thick_sludge, 25, 0, :east
unit :sludge, 26, 0, :east
unit :thick_sludge, 31, 0, :east
unit :sludge, 33, 0, :east
unit :archer, 36, 0, :east
unit :captive, 39, 0, :east
unit :thick_sludge, 40, 0, :east
unit :wizard, 43, 0, :east
unit :archer, 50, 0, :east
unit :sludge, 62, 0, :east
unit :sludge, 64, 0, :east
unit :archer, 67, 0, :east
unit :captive, 69, 0, :east
unit :sludge, 76, 0, :east
unit :captive, 85, 0, :east
unit :archer, 93, 0, :east
unit :archer, 97, 0, :east
unit :wizard, 101, 0, :east
unit :sludge, 106, 0, :east
unit :archer, 114, 0, :east
unit :sludge, 115, 0, :east
unit :archer, 127, 0, :east
unit :wizard, 129, 0, :east
unit :thick_sludge, 137, 0, :east
unit :archer, 147, 0, :east
unit :wizard, 153, 0, :east
unit :archer, 155, 0, :east
unit :sludge, 170, 0, :east
unit :archer, 173, 0, :east
unit :captive, 176, 0, :east
unit :captive, 177, 0, :east
unit :wizard, 180, 0, :east
unit :archer, 184, 0, :east
unit :wizard, 186, 0, :east
unit :captive, 189, 0, :east
unit :wizard, 193, 0, :east
unit :thick_sludge, 196, 0, :east
unit :archer, 202, 0, :east
unit :captive, 203, 0, :east
unit :archer, 204, 0, :east
unit :sludge, 208, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 216, 0, :east
unit :sludge, 220, 0, :east
unit :thick_sludge, 223, 0, :east
unit :archer, 228, 0, :east
unit :thick_sludge, 231, 0, :east
unit :archer, 233, 0, :east
unit :thick_sludge, 238, 0, :east
unit :sludge, 244, 0, :east
unit :sludge, 253, 0, :east
unit :sludge, 254, 0, :east
unit :wizard, 256, 0, :east
unit :thick_sludge, 258, 0, :east
unit :sludge, 260, 0, :east
unit :thick_sludge, 264, 0, :east
unit :captive, 268, 0, :east
unit :sludge, 271, 0, :east
unit :archer, 273, 0, :east
unit :thick_sludge, 276, 0, :east
unit :sludge, 277, 0, :east
unit :sludge, 279, 0, :east
unit :thick_sludge, 281, 0, :east
unit :archer, 286, 0, :east
unit :sludge, 290, 0, :east
unit :captive, 294, 0, :east
unit :wizard, 296, 0, :east
unit :captive, 300, 0, :east
unit :sludge, 303, 0, :east
unit :captive, 304, 0, :east
unit :captive, 306, 0, :east
unit :sludge, 308, 0, :east
unit :archer, 310, 0, :east
unit :sludge, 316, 0, :east
unit :sludge, 317, 0, :east
unit :captive, 318, 0, :east
unit :captive, 323, 0, :east
unit :thick_sludge, 325, 0, :east
unit :archer, 329, 0, :east
unit :sludge, 333, 0, :east
unit :wizard, 337, 0, :east
unit :captive, 339, 0, :east
unit :wizard, 341, 0, :east
unit :sludge, 348, 0, :east
unit :archer, 349, 0, :east
unit :sludge, 351, 0, :east
unit :sludge, 353, 0, :east
unit :thick_sludge, 354, 0, :east
unit :archer, 357, 0, :east
unit :captive, 362, 0, :east
unit :captive, 376, 0, :east
unit :sludge, 379, 0, :east
unit :sludge, 387, 0, :west
unit :thick_sludge, 397, 0, :west
unit :archer, 403, 0, :west
unit :sludge, 406, 0, :west
unit :captive, 412, 0, :west
unit :wizard, 416, 0, :west
unit :sludge, 417, 0, :west
unit :sludge, 420, 0, :west
unit :thick_sludge, 421, 0, :west
unit :thick_sludge, 422, 0, :west
unit :thick_sludge, 424, 0, :west
unit :archer, 425, 0, :west
unit :wizard, 431, 0, :west
unit :sludge, 433, 0, :west
unit :archer, 435, 0, :west
unit :sludge, 445, 0, :west
unit :archer, 448, 0, :west
unit :thick_sludge, 449, 0, :west
unit :archer, 459, 0, :west
unit :captive, 462, 0, :west
unit :sludge, 465, 0, :west
unit :sludge, 469, 0, :west
unit :archer, 473, 0, :west
unit :sludge, 483, 0, :west
unit :thick_sludge, 485, 0, :west
unit :thick_sludge, 486, 0, :west
unit :archer, 489, 0, :west
unit :thick_sludge, 490, 0, :west
unit :thick_sludge, 491, 0, :west
unit :archer, 497, 0, :west
unit :thick_sludge, 502, 0, :west
unit :sludge, 503, 0, :west
unit :thick_sludge, 510, 0, :west
unit :sludge, 513, 0, :west
unit :archer, 521, 0, :west
unit :wizard, 523, 0, :west
unit :wizard, 529, 0, :west
unit :wizard, 533, 0, :west
unit :sludge, 536, 0, :west
unit :archer, 539, 0, :west
unit :wizard, 544, 0, :west
unit :sludge, 549, 0, :west
unit :sludge, 551, 0, :west
unit :sludge, 554, 0, :west
unit :sludge, 563, 0, :west
unit :captive, 568, 0, :west
unit :thick_sludge, 576, 0, :west
unit :sludge, 581, 0, :west
unit :archer, 586, 0, :west
unit :sludge, 590, 0, :west
unit :thick_sludge, 601, 0, :west
unit :archer, 602, 0, :west
unit :wizard, 603, 0, :west
unit :thick_sludge, 604, 0, :west
unit :captive, 607, 0, :west
unit :thick_sludge, 608, 0, :west
unit :sludge, 612, 0, :west
unit :archer, 616, 0, :west
unit :thick_sludge, 620, 0, :west
unit :archer, 622, 0, :west
unit :captive, 632, 0, :west
unit :sludge, 638, 0, :west
unit :sludge, 641, 0, :west
unit :archer, 642, 0, :west
unit :thick_sludge, 645, 0, :west
unit :archer, 648, 0, :west
unit :thick_sludge, 650, 0, :west
unit :thick_sludge, 666, 0, :west
unit :wizard, 667, 0, :west
unit :wizard, 678, 0, :west
unit :archer, 683, 0, :west
unit :wizard, 701, 0, :west
unit :captive, 705, 0, :west
unit :captive, 709, 0, :west
unit :archer, 712, 0, :west
unit :archer, 715, 0, :west
unit :thick_sludge, 719, 0, :west
unit :archer, 723, 0, :west
unit :thick_sludge, 724, 0, :west
unit :captive, 726, 0, :west
unit :thick_sludge, 729, 0, :west
