#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     C    a  SsC        S   a   a  aC        C  s  C  S    S wC   s  C    s aS     s      w    S  a  s  C S SC w waC   S s S        as C       C     C        CS   C  S  S              a S   w  S a   s  a S       w  a        SS     s      s CC C    a ss   w  C a    S  a       a   S S       ssS    a  CC  s S C        ssC   a   C           a   C   S w         w           C    C s          C    S w S   a w    w Cs   w   S      C         s        w  S Sa     C    w  s        C        S      s                s   w s   w s       C     aS    a  ws C          C w       a  S w        a            s   wa  ss s      s   s   s        Ss w  w S Ss w       S Cs  Sa S    S      C   S  a  ss  w  s  s    s    S        sssS a w    C                 sw      S as  C  S   S a   C a  s    a    sC     sSSS     C  Ss         s      S     w     a            S    s SC       s S s   a w     s SSs      a    w S    Ss    S CS C  s    C   S   C >  S a  @   ss   S          w  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 959
ace_score 4795
size 959, 1
stairs 928, 0

warrior 936, 0, :east

unit :captive, 5, 0, :east
unit :archer, 10, 0, :east
unit :thick_sludge, 13, 0, :east
unit :sludge, 14, 0, :east
unit :captive, 15, 0, :east
unit :thick_sludge, 24, 0, :east
unit :archer, 28, 0, :east
unit :archer, 32, 0, :east
unit :archer, 35, 0, :east
unit :captive, 36, 0, :east
unit :captive, 45, 0, :east
unit :sludge, 48, 0, :east
unit :captive, 51, 0, :east
unit :thick_sludge, 54, 0, :east
unit :thick_sludge, 59, 0, :east
unit :wizard, 61, 0, :east
unit :captive, 62, 0, :east
unit :sludge, 66, 0, :east
unit :captive, 69, 0, :east
unit :sludge, 74, 0, :east
unit :archer, 76, 0, :east
unit :thick_sludge, 77, 0, :east
unit :sludge, 83, 0, :east
unit :wizard, 90, 0, :east
unit :thick_sludge, 95, 0, :east
unit :archer, 98, 0, :east
unit :sludge, 101, 0, :east
unit :captive, 104, 0, :east
unit :thick_sludge, 106, 0, :east
unit :thick_sludge, 108, 0, :east
unit :captive, 109, 0, :east
unit :wizard, 111, 0, :east
unit :wizard, 113, 0, :east
unit :archer, 114, 0, :east
unit :captive, 115, 0, :east
unit :thick_sludge, 119, 0, :east
unit :sludge, 121, 0, :east
unit :thick_sludge, 123, 0, :east
unit :archer, 132, 0, :east
unit :sludge, 133, 0, :east
unit :captive, 135, 0, :east
unit :captive, 143, 0, :east
unit :captive, 149, 0, :east
unit :captive, 158, 0, :east
unit :thick_sludge, 159, 0, :east
unit :captive, 163, 0, :east
unit :thick_sludge, 166, 0, :east
unit :thick_sludge, 169, 0, :east
unit :archer, 184, 0, :east
unit :thick_sludge, 186, 0, :east
unit :wizard, 190, 0, :east
unit :thick_sludge, 193, 0, :east
unit :archer, 195, 0, :east
unit :sludge, 199, 0, :east
unit :archer, 202, 0, :east
unit :thick_sludge, 204, 0, :east
unit :wizard, 212, 0, :east
unit :archer, 215, 0, :east
unit :thick_sludge, 224, 0, :east
unit :thick_sludge, 225, 0, :east
unit :sludge, 231, 0, :east
unit :sludge, 238, 0, :east
unit :captive, 240, 0, :east
unit :captive, 241, 0, :east
unit :captive, 243, 0, :east
unit :archer, 248, 0, :east
unit :sludge, 250, 0, :east
unit :sludge, 251, 0, :east
unit :wizard, 255, 0, :east
unit :captive, 258, 0, :east
unit :archer, 260, 0, :east
unit :thick_sludge, 265, 0, :east
unit :archer, 268, 0, :east
unit :archer, 276, 0, :east
unit :thick_sludge, 280, 0, :east
unit :thick_sludge, 282, 0, :east
unit :sludge, 290, 0, :east
unit :sludge, 291, 0, :east
unit :thick_sludge, 292, 0, :east
unit :archer, 297, 0, :east
unit :captive, 300, 0, :east
unit :captive, 301, 0, :east
unit :sludge, 304, 0, :east
unit :thick_sludge, 306, 0, :east
unit :captive, 308, 0, :east
unit :sludge, 317, 0, :east
unit :sludge, 318, 0, :east
unit :captive, 319, 0, :east
unit :archer, 323, 0, :east
unit :captive, 327, 0, :east
unit :archer, 339, 0, :east
unit :captive, 343, 0, :east
unit :thick_sludge, 347, 0, :east
unit :wizard, 349, 0, :east
unit :wizard, 359, 0, :east
unit :captive, 371, 0, :east
unit :captive, 376, 0, :east
unit :sludge, 378, 0, :east
unit :captive, 389, 0, :east
unit :thick_sludge, 394, 0, :east
unit :wizard, 396, 0, :east
unit :thick_sludge, 398, 0, :east
unit :archer, 402, 0, :east
unit :wizard, 404, 0, :east
unit :wizard, 409, 0, :east
unit :captive, 411, 0, :east
unit :sludge, 412, 0, :east
unit :wizard, 416, 0, :east
unit :thick_sludge, 420, 0, :east
unit :captive, 427, 0, :east
unit :sludge, 437, 0, :east
unit :wizard, 446, 0, :east
unit :thick_sludge, 449, 0, :east
unit :thick_sludge, 451, 0, :east
unit :archer, 452, 0, :east
unit :captive, 458, 0, :east
unit :wizard, 463, 0, :east
unit :sludge, 466, 0, :east
unit :captive, 475, 0, :east
unit :thick_sludge, 484, 0, :east
unit :sludge, 491, 0, :east
unit :sludge, 508, 0, :east
unit :wizard, 512, 0, :east
unit :sludge, 514, 0, :east
unit :wizard, 518, 0, :east
unit :sludge, 520, 0, :east
unit :captive, 528, 0, :east
unit :archer, 534, 0, :east
unit :thick_sludge, 535, 0, :east
unit :archer, 540, 0, :east
unit :wizard, 543, 0, :east
unit :sludge, 544, 0, :east
unit :captive, 546, 0, :east
unit :captive, 557, 0, :east
unit :wizard, 559, 0, :east
unit :archer, 567, 0, :east
unit :thick_sludge, 570, 0, :east
unit :wizard, 572, 0, :east
unit :archer, 581, 0, :east
unit :sludge, 594, 0, :east
unit :wizard, 598, 0, :east
unit :archer, 599, 0, :east
unit :sludge, 602, 0, :east
unit :sludge, 603, 0, :east
unit :sludge, 605, 0, :east
unit :sludge, 612, 0, :east
unit :sludge, 616, 0, :east
unit :sludge, 620, 0, :east
unit :thick_sludge, 629, 0, :east
unit :sludge, 630, 0, :east
unit :wizard, 632, 0, :east
unit :wizard, 635, 0, :east
unit :thick_sludge, 637, 0, :east
unit :thick_sludge, 639, 0, :east
unit :sludge, 640, 0, :east
unit :wizard, 642, 0, :east
unit :thick_sludge, 650, 0, :east
unit :captive, 652, 0, :east
unit :sludge, 653, 0, :east
unit :thick_sludge, 656, 0, :east
unit :archer, 657, 0, :east
unit :thick_sludge, 659, 0, :east
unit :thick_sludge, 664, 0, :east
unit :captive, 671, 0, :east
unit :thick_sludge, 675, 0, :east
unit :archer, 678, 0, :east
unit :sludge, 681, 0, :east
unit :sludge, 682, 0, :east
unit :wizard, 685, 0, :east
unit :sludge, 688, 0, :east
unit :sludge, 691, 0, :east
unit :sludge, 696, 0, :east
unit :thick_sludge, 701, 0, :east
unit :sludge, 710, 0, :east
unit :sludge, 711, 0, :east
unit :sludge, 712, 0, :east
unit :thick_sludge, 713, 0, :east
unit :archer, 715, 0, :east
unit :wizard, 717, 0, :east
unit :captive, 722, 0, :east
unit :sludge, 740, 0, :east
unit :wizard, 741, 0, :east
unit :thick_sludge, 748, 0, :east
unit :archer, 750, 0, :east
unit :sludge, 751, 0, :east
unit :captive, 754, 0, :east
unit :thick_sludge, 757, 0, :east
unit :thick_sludge, 761, 0, :east
unit :archer, 763, 0, :east
unit :captive, 767, 0, :east
unit :archer, 769, 0, :east
unit :sludge, 772, 0, :east
unit :archer, 777, 0, :east
unit :sludge, 782, 0, :east
unit :captive, 783, 0, :east
unit :sludge, 789, 0, :east
unit :thick_sludge, 790, 0, :east
unit :thick_sludge, 791, 0, :east
unit :thick_sludge, 792, 0, :east
unit :captive, 798, 0, :east
unit :thick_sludge, 801, 0, :east
unit :sludge, 802, 0, :east
unit :sludge, 812, 0, :east
unit :thick_sludge, 819, 0, :east
unit :wizard, 825, 0, :east
unit :archer, 831, 0, :east
unit :thick_sludge, 844, 0, :east
unit :sludge, 849, 0, :east
unit :thick_sludge, 851, 0, :east
unit :captive, 852, 0, :east
unit :sludge, 860, 0, :east
unit :thick_sludge, 862, 0, :east
unit :sludge, 864, 0, :east
unit :archer, 868, 0, :east
unit :wizard, 870, 0, :east
unit :sludge, 876, 0, :east
unit :thick_sludge, 878, 0, :east
unit :thick_sludge, 879, 0, :east
unit :sludge, 880, 0, :east
unit :archer, 887, 0, :east
unit :wizard, 892, 0, :east
unit :thick_sludge, 894, 0, :east
unit :thick_sludge, 899, 0, :east
unit :sludge, 900, 0, :east
unit :thick_sludge, 905, 0, :east
unit :captive, 907, 0, :east
unit :thick_sludge, 908, 0, :east
unit :captive, 910, 0, :east
unit :sludge, 913, 0, :east
unit :captive, 918, 0, :east
unit :thick_sludge, 922, 0, :east
unit :captive, 926, 0, :east
unit :thick_sludge, 931, 0, :east
unit :archer, 933, 0, :east
unit :sludge, 940, 0, :west
unit :sludge, 941, 0, :west
unit :thick_sludge, 945, 0, :west
unit :wizard, 956, 0, :west
