#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     S   SSC s   C     a       ss   C  aC  C C  C  w       w  w                     C         s   S    Ss  C   a    w       a w     sS      a  S S  a                     a S     S     S   s a w   w  C  @      s  ss     C S  a SCs S      S  Cs  s         CSS C    CCC   s   S s  a          C  s          S s  w   s a    C     w          S   Ss  w     C   w   S  a    w    w     S  aC Ca    a           s w   s a  w  a  w w w w    C     as   a   S             s   S           sC     S    saa     C    C     CS     S     S    S  S C            w  C  a S     C     SC     a a         a     aw a  SCsC    s       C   wa s> s   w S aS S            a  C   a a    a a S w   sSs   wCC  sC   a C         a        SC   C   w a|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 715
ace_score 3575
size 715, 1
stairs 616, 0

warrior 202, 0, :east

unit :thick_sludge, 5, 0, :east
unit :thick_sludge, 9, 0, :east
unit :thick_sludge, 10, 0, :east
unit :captive, 11, 0, :east
unit :sludge, 13, 0, :east
unit :captive, 17, 0, :east
unit :archer, 23, 0, :east
unit :sludge, 31, 0, :east
unit :sludge, 32, 0, :east
unit :captive, 36, 0, :east
unit :archer, 39, 0, :east
unit :captive, 40, 0, :east
unit :captive, 43, 0, :east
unit :captive, 45, 0, :east
unit :captive, 48, 0, :east
unit :wizard, 51, 0, :east
unit :wizard, 59, 0, :east
unit :wizard, 62, 0, :east
unit :captive, 84, 0, :east
unit :sludge, 94, 0, :east
unit :thick_sludge, 98, 0, :east
unit :thick_sludge, 103, 0, :east
unit :sludge, 104, 0, :east
unit :captive, 107, 0, :east
unit :archer, 111, 0, :east
unit :wizard, 116, 0, :east
unit :archer, 124, 0, :east
unit :wizard, 126, 0, :east
unit :sludge, 132, 0, :east
unit :thick_sludge, 133, 0, :east
unit :archer, 140, 0, :east
unit :thick_sludge, 143, 0, :east
unit :thick_sludge, 145, 0, :east
unit :archer, 148, 0, :east
unit :archer, 170, 0, :east
unit :thick_sludge, 172, 0, :east
unit :thick_sludge, 178, 0, :east
unit :thick_sludge, 184, 0, :east
unit :sludge, 188, 0, :east
unit :archer, 190, 0, :east
unit :wizard, 192, 0, :east
unit :wizard, 196, 0, :east
unit :captive, 199, 0, :east
unit :sludge, 209, 0, :west
unit :sludge, 212, 0, :west
unit :sludge, 213, 0, :west
unit :captive, 219, 0, :west
unit :thick_sludge, 221, 0, :west
unit :archer, 224, 0, :west
unit :thick_sludge, 226, 0, :west
unit :captive, 227, 0, :west
unit :sludge, 228, 0, :west
unit :thick_sludge, 230, 0, :west
unit :thick_sludge, 237, 0, :west
unit :captive, 240, 0, :west
unit :sludge, 241, 0, :west
unit :sludge, 244, 0, :west
unit :captive, 254, 0, :west
unit :thick_sludge, 255, 0, :west
unit :thick_sludge, 256, 0, :west
unit :captive, 258, 0, :west
unit :captive, 263, 0, :west
unit :captive, 264, 0, :west
unit :captive, 265, 0, :west
unit :sludge, 269, 0, :west
unit :thick_sludge, 273, 0, :west
unit :sludge, 275, 0, :west
unit :archer, 278, 0, :west
unit :captive, 289, 0, :west
unit :sludge, 292, 0, :west
unit :thick_sludge, 303, 0, :west
unit :sludge, 305, 0, :west
unit :wizard, 308, 0, :west
unit :sludge, 312, 0, :west
unit :archer, 314, 0, :west
unit :captive, 319, 0, :west
unit :wizard, 325, 0, :west
unit :thick_sludge, 336, 0, :west
unit :thick_sludge, 340, 0, :west
unit :sludge, 341, 0, :west
unit :wizard, 344, 0, :west
unit :captive, 350, 0, :west
unit :wizard, 354, 0, :west
unit :thick_sludge, 358, 0, :west
unit :archer, 361, 0, :west
unit :wizard, 366, 0, :west
unit :wizard, 371, 0, :west
unit :thick_sludge, 377, 0, :west
unit :archer, 380, 0, :west
unit :captive, 381, 0, :west
unit :captive, 383, 0, :west
unit :archer, 384, 0, :west
unit :archer, 389, 0, :west
unit :sludge, 401, 0, :west
unit :wizard, 403, 0, :west
unit :sludge, 407, 0, :west
unit :archer, 409, 0, :west
unit :wizard, 412, 0, :west
unit :archer, 415, 0, :west
unit :wizard, 418, 0, :west
unit :wizard, 420, 0, :west
unit :wizard, 422, 0, :west
unit :wizard, 424, 0, :west
unit :captive, 429, 0, :west
unit :archer, 435, 0, :west
unit :sludge, 436, 0, :west
unit :archer, 440, 0, :west
unit :thick_sludge, 444, 0, :west
unit :sludge, 458, 0, :west
unit :thick_sludge, 462, 0, :west
unit :sludge, 474, 0, :west
unit :captive, 475, 0, :west
unit :thick_sludge, 481, 0, :west
unit :sludge, 486, 0, :west
unit :archer, 487, 0, :west
unit :archer, 488, 0, :west
unit :captive, 494, 0, :west
unit :captive, 499, 0, :west
unit :captive, 505, 0, :west
unit :thick_sludge, 506, 0, :west
unit :thick_sludge, 512, 0, :west
unit :thick_sludge, 518, 0, :west
unit :thick_sludge, 523, 0, :west
unit :thick_sludge, 526, 0, :west
unit :captive, 528, 0, :west
unit :wizard, 541, 0, :west
unit :captive, 544, 0, :west
unit :archer, 547, 0, :west
unit :thick_sludge, 549, 0, :west
unit :captive, 555, 0, :west
unit :thick_sludge, 561, 0, :west
unit :captive, 562, 0, :west
unit :archer, 568, 0, :west
unit :archer, 570, 0, :west
unit :archer, 580, 0, :west
unit :archer, 586, 0, :west
unit :wizard, 587, 0, :west
unit :archer, 589, 0, :west
unit :thick_sludge, 592, 0, :west
unit :captive, 593, 0, :west
unit :sludge, 594, 0, :west
unit :captive, 595, 0, :west
unit :sludge, 600, 0, :west
unit :captive, 608, 0, :west
unit :wizard, 612, 0, :west
unit :archer, 613, 0, :west
unit :sludge, 615, 0, :west
unit :sludge, 618, 0, :west
unit :wizard, 622, 0, :west
unit :thick_sludge, 624, 0, :west
unit :archer, 626, 0, :west
unit :thick_sludge, 627, 0, :west
unit :thick_sludge, 629, 0, :west
unit :archer, 642, 0, :west
unit :captive, 645, 0, :west
unit :archer, 649, 0, :west
unit :archer, 651, 0, :west
unit :archer, 656, 0, :west
unit :archer, 658, 0, :west
unit :thick_sludge, 660, 0, :west
unit :wizard, 662, 0, :west
unit :sludge, 666, 0, :west
unit :thick_sludge, 667, 0, :west
unit :sludge, 668, 0, :west
unit :wizard, 672, 0, :west
unit :captive, 673, 0, :west
unit :captive, 674, 0, :west
unit :sludge, 677, 0, :west
unit :captive, 678, 0, :west
unit :archer, 682, 0, :west
unit :captive, 684, 0, :west
unit :archer, 694, 0, :west
unit :thick_sludge, 703, 0, :west
unit :captive, 704, 0, :west
unit :captive, 708, 0, :west
unit :wizard, 712, 0, :west
unit :archer, 714, 0, :west
