#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     w   a    a   w  s     a  sC       w aCSa     S      SSC        C  w  S    S         C    S  S      S     as  Ss       C   s Ss   S        s    C    s             SS  w S    S  w   @   a  s       s  w  w     a  SS  Ca  C a  Cs        w    C     S  Cws      S   a  S       C  a      S       w Sa    a a Sa        C   a    C s > C S  a  a a C s     CC    C      S C          S Sa SCs   w       S   w S Ss     w    Ca      a  w   C CS a   aS             a     a    ss             C  CS               S    sS  a   S   C   w  a   w   a  a s   C a S s   C C      SC   S w s               s w  s   C      C  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 605
ace_score 3025
size 605, 1
stairs 329, 0

warrior 185, 0, :east

unit :wizard, 5, 0, :east
unit :archer, 9, 0, :east
unit :archer, 14, 0, :east
unit :wizard, 18, 0, :east
unit :sludge, 21, 0, :east
unit :archer, 27, 0, :east
unit :sludge, 30, 0, :east
unit :captive, 31, 0, :east
unit :wizard, 39, 0, :east
unit :archer, 41, 0, :east
unit :captive, 42, 0, :east
unit :thick_sludge, 43, 0, :east
unit :archer, 44, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 57, 0, :east
unit :thick_sludge, 58, 0, :east
unit :captive, 59, 0, :east
unit :captive, 68, 0, :east
unit :wizard, 71, 0, :east
unit :thick_sludge, 74, 0, :east
unit :thick_sludge, 79, 0, :east
unit :captive, 89, 0, :east
unit :thick_sludge, 94, 0, :east
unit :thick_sludge, 97, 0, :east
unit :thick_sludge, 104, 0, :east
unit :archer, 110, 0, :east
unit :sludge, 111, 0, :east
unit :thick_sludge, 114, 0, :east
unit :sludge, 115, 0, :east
unit :captive, 123, 0, :east
unit :sludge, 127, 0, :east
unit :thick_sludge, 129, 0, :east
unit :sludge, 130, 0, :east
unit :thick_sludge, 134, 0, :east
unit :sludge, 143, 0, :east
unit :captive, 148, 0, :east
unit :sludge, 153, 0, :east
unit :thick_sludge, 167, 0, :east
unit :thick_sludge, 168, 0, :east
unit :wizard, 171, 0, :east
unit :thick_sludge, 173, 0, :east
unit :thick_sludge, 178, 0, :east
unit :wizard, 181, 0, :east
unit :archer, 189, 0, :west
unit :sludge, 192, 0, :west
unit :sludge, 200, 0, :west
unit :wizard, 203, 0, :west
unit :wizard, 206, 0, :west
unit :archer, 212, 0, :west
unit :thick_sludge, 215, 0, :west
unit :thick_sludge, 216, 0, :west
unit :captive, 219, 0, :west
unit :archer, 220, 0, :west
unit :captive, 223, 0, :west
unit :archer, 225, 0, :west
unit :captive, 228, 0, :west
unit :sludge, 229, 0, :west
unit :wizard, 238, 0, :west
unit :captive, 243, 0, :west
unit :thick_sludge, 249, 0, :west
unit :captive, 252, 0, :west
unit :wizard, 253, 0, :west
unit :sludge, 254, 0, :west
unit :thick_sludge, 261, 0, :west
unit :archer, 265, 0, :west
unit :thick_sludge, 268, 0, :west
unit :captive, 276, 0, :west
unit :archer, 279, 0, :west
unit :thick_sludge, 286, 0, :west
unit :wizard, 294, 0, :west
unit :thick_sludge, 296, 0, :west
unit :archer, 297, 0, :west
unit :archer, 302, 0, :west
unit :archer, 304, 0, :west
unit :thick_sludge, 306, 0, :west
unit :archer, 307, 0, :west
unit :captive, 316, 0, :west
unit :archer, 320, 0, :west
unit :captive, 325, 0, :west
unit :sludge, 327, 0, :west
unit :captive, 331, 0, :west
unit :thick_sludge, 333, 0, :west
unit :archer, 336, 0, :west
unit :archer, 339, 0, :west
unit :archer, 341, 0, :west
unit :captive, 343, 0, :west
unit :sludge, 345, 0, :west
unit :captive, 351, 0, :west
unit :captive, 352, 0, :west
unit :captive, 357, 0, :west
unit :thick_sludge, 364, 0, :west
unit :captive, 366, 0, :west
unit :thick_sludge, 377, 0, :west
unit :thick_sludge, 379, 0, :west
unit :archer, 380, 0, :west
unit :thick_sludge, 382, 0, :west
unit :captive, 383, 0, :west
unit :sludge, 384, 0, :west
unit :wizard, 388, 0, :west
unit :thick_sludge, 396, 0, :west
unit :wizard, 400, 0, :west
unit :thick_sludge, 402, 0, :west
unit :thick_sludge, 404, 0, :west
unit :sludge, 405, 0, :west
unit :wizard, 411, 0, :west
unit :captive, 416, 0, :west
unit :archer, 417, 0, :west
unit :archer, 424, 0, :west
unit :wizard, 427, 0, :west
unit :captive, 431, 0, :west
unit :captive, 433, 0, :west
unit :thick_sludge, 434, 0, :west
unit :archer, 436, 0, :west
unit :archer, 440, 0, :west
unit :thick_sludge, 441, 0, :west
unit :archer, 455, 0, :west
unit :archer, 461, 0, :west
unit :sludge, 466, 0, :west
unit :sludge, 467, 0, :west
unit :captive, 481, 0, :west
unit :captive, 484, 0, :west
unit :thick_sludge, 485, 0, :west
unit :thick_sludge, 501, 0, :west
unit :sludge, 506, 0, :west
unit :thick_sludge, 507, 0, :west
unit :archer, 510, 0, :west
unit :thick_sludge, 514, 0, :west
unit :captive, 518, 0, :west
unit :wizard, 522, 0, :west
unit :archer, 525, 0, :west
unit :wizard, 529, 0, :west
unit :archer, 533, 0, :west
unit :archer, 536, 0, :west
unit :sludge, 538, 0, :west
unit :captive, 542, 0, :west
unit :archer, 544, 0, :west
unit :thick_sludge, 546, 0, :west
unit :sludge, 548, 0, :west
unit :captive, 552, 0, :west
unit :captive, 554, 0, :west
unit :thick_sludge, 561, 0, :west
unit :captive, 562, 0, :west
unit :thick_sludge, 566, 0, :west
unit :wizard, 568, 0, :west
unit :sludge, 570, 0, :west
unit :sludge, 586, 0, :west
unit :wizard, 588, 0, :west
unit :sludge, 591, 0, :west
unit :captive, 595, 0, :west
unit :captive, 602, 0, :west
