#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S  w C   s    S   w   C    aa  a  a   C      s     w   @  ss  C S      a      w          a   as  S     a S   C      a s    C S  a    SCaS      S           sC    w             saa   s     S  S  w a    a w w   s               S      C    s  aa    C         w C     a  aa a C s  w       w   s wa w w  a   a  w   w   a   SSC   a        w w      s w   w Ss     s                s  C          Cs                 SCs  sCa S   S    w            S C  C  a s  s a   SCS   w    s          w aa aS     CS          as S   w     a a s       C   S    a   >   Ss        S  S   C     a  sS Sa        w   sa  aw   S         a        w      C    C S  Sa       sw      s   aa   sa w S         s     w C    a CC as  S   C |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 701
ace_score 3505
size 701, 1
stairs 540, 0

warrior 55, 0, :east

unit :thick_sludge, 0, 0, :east
unit :wizard, 3, 0, :east
unit :captive, 5, 0, :east
unit :sludge, 9, 0, :east
unit :thick_sludge, 14, 0, :east
unit :wizard, 18, 0, :east
unit :captive, 22, 0, :east
unit :archer, 27, 0, :east
unit :archer, 28, 0, :east
unit :archer, 31, 0, :east
unit :archer, 34, 0, :east
unit :captive, 38, 0, :east
unit :sludge, 45, 0, :east
unit :wizard, 51, 0, :east
unit :sludge, 58, 0, :west
unit :sludge, 59, 0, :west
unit :captive, 62, 0, :west
unit :thick_sludge, 64, 0, :west
unit :archer, 71, 0, :west
unit :wizard, 78, 0, :west
unit :archer, 89, 0, :west
unit :archer, 93, 0, :west
unit :sludge, 94, 0, :west
unit :thick_sludge, 97, 0, :west
unit :archer, 103, 0, :west
unit :thick_sludge, 105, 0, :west
unit :captive, 109, 0, :west
unit :archer, 116, 0, :west
unit :sludge, 118, 0, :west
unit :captive, 123, 0, :west
unit :thick_sludge, 125, 0, :west
unit :archer, 128, 0, :west
unit :thick_sludge, 133, 0, :west
unit :captive, 134, 0, :west
unit :archer, 135, 0, :west
unit :thick_sludge, 136, 0, :west
unit :thick_sludge, 143, 0, :west
unit :sludge, 155, 0, :west
unit :captive, 156, 0, :west
unit :wizard, 161, 0, :west
unit :sludge, 175, 0, :west
unit :archer, 176, 0, :west
unit :archer, 177, 0, :west
unit :sludge, 181, 0, :west
unit :thick_sludge, 187, 0, :west
unit :thick_sludge, 190, 0, :west
unit :wizard, 193, 0, :west
unit :archer, 195, 0, :west
unit :archer, 200, 0, :west
unit :wizard, 202, 0, :west
unit :wizard, 204, 0, :west
unit :sludge, 208, 0, :west
unit :thick_sludge, 224, 0, :west
unit :captive, 231, 0, :west
unit :sludge, 236, 0, :west
unit :archer, 239, 0, :west
unit :archer, 240, 0, :west
unit :captive, 245, 0, :west
unit :wizard, 255, 0, :west
unit :captive, 257, 0, :west
unit :archer, 263, 0, :west
unit :archer, 266, 0, :west
unit :archer, 267, 0, :west
unit :archer, 269, 0, :west
unit :captive, 271, 0, :west
unit :sludge, 273, 0, :west
unit :wizard, 276, 0, :west
unit :wizard, 284, 0, :west
unit :sludge, 288, 0, :west
unit :wizard, 290, 0, :west
unit :archer, 291, 0, :west
unit :wizard, 293, 0, :west
unit :wizard, 295, 0, :west
unit :archer, 298, 0, :west
unit :archer, 302, 0, :west
unit :wizard, 305, 0, :west
unit :wizard, 309, 0, :west
unit :archer, 313, 0, :west
unit :thick_sludge, 317, 0, :west
unit :thick_sludge, 318, 0, :west
unit :captive, 319, 0, :west
unit :archer, 323, 0, :west
unit :wizard, 332, 0, :west
unit :wizard, 334, 0, :west
unit :sludge, 341, 0, :west
unit :wizard, 343, 0, :west
unit :wizard, 347, 0, :west
unit :thick_sludge, 349, 0, :west
unit :sludge, 350, 0, :west
unit :sludge, 356, 0, :west
unit :sludge, 373, 0, :west
unit :captive, 376, 0, :west
unit :captive, 387, 0, :west
unit :sludge, 388, 0, :west
unit :thick_sludge, 406, 0, :west
unit :captive, 407, 0, :west
unit :sludge, 408, 0, :west
unit :sludge, 411, 0, :west
unit :captive, 412, 0, :west
unit :archer, 413, 0, :west
unit :thick_sludge, 415, 0, :west
unit :thick_sludge, 419, 0, :west
unit :wizard, 424, 0, :west
unit :thick_sludge, 437, 0, :west
unit :captive, 439, 0, :west
unit :captive, 442, 0, :west
unit :archer, 445, 0, :west
unit :sludge, 447, 0, :west
unit :sludge, 450, 0, :west
unit :archer, 452, 0, :west
unit :thick_sludge, 456, 0, :west
unit :captive, 457, 0, :west
unit :thick_sludge, 458, 0, :west
unit :wizard, 462, 0, :west
unit :sludge, 467, 0, :west
unit :wizard, 478, 0, :west
unit :archer, 480, 0, :west
unit :archer, 481, 0, :west
unit :archer, 483, 0, :west
unit :thick_sludge, 484, 0, :west
unit :captive, 490, 0, :west
unit :thick_sludge, 491, 0, :west
unit :archer, 502, 0, :west
unit :sludge, 503, 0, :west
unit :thick_sludge, 505, 0, :west
unit :wizard, 509, 0, :west
unit :archer, 515, 0, :west
unit :archer, 517, 0, :west
unit :sludge, 519, 0, :west
unit :captive, 527, 0, :west
unit :thick_sludge, 531, 0, :west
unit :archer, 536, 0, :west
unit :thick_sludge, 544, 0, :west
unit :sludge, 545, 0, :west
unit :thick_sludge, 554, 0, :west
unit :thick_sludge, 557, 0, :west
unit :captive, 561, 0, :west
unit :archer, 567, 0, :west
unit :sludge, 570, 0, :west
unit :thick_sludge, 571, 0, :west
unit :thick_sludge, 573, 0, :west
unit :archer, 574, 0, :west
unit :wizard, 583, 0, :west
unit :sludge, 587, 0, :west
unit :archer, 588, 0, :west
unit :archer, 591, 0, :west
unit :wizard, 592, 0, :west
unit :thick_sludge, 596, 0, :west
unit :archer, 606, 0, :west
unit :wizard, 615, 0, :west
unit :captive, 622, 0, :west
unit :captive, 627, 0, :west
unit :thick_sludge, 629, 0, :west
unit :thick_sludge, 632, 0, :west
unit :archer, 633, 0, :west
unit :sludge, 641, 0, :west
unit :wizard, 642, 0, :west
unit :sludge, 649, 0, :west
unit :archer, 653, 0, :west
unit :archer, 654, 0, :west
unit :sludge, 658, 0, :west
unit :archer, 659, 0, :west
unit :wizard, 661, 0, :west
unit :thick_sludge, 663, 0, :west
unit :sludge, 673, 0, :west
unit :wizard, 679, 0, :west
unit :captive, 681, 0, :west
unit :archer, 686, 0, :west
unit :captive, 688, 0, :west
unit :captive, 689, 0, :west
unit :archer, 691, 0, :west
unit :sludge, 692, 0, :west
unit :thick_sludge, 695, 0, :west
unit :captive, 699, 0, :west
