#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |          ws  sC   S      aw S   a S C  S aSa C C S      C    wC   S  S        aCa            w  a   s  C    a    w   s a     CSsa     C      w  S   C    aC   s       C        wC    a    S    Ssa         s   S    a         C    SCa a      C s              a     w     C    S    s Ca      s  s           w  a s  w    S C wsSCs    aw      as a C    S     S w   s    w a a s s w              w  S          C   S    sC  a        w a          S         w      S   aS    a  S S       @    s    C     C             Ca    C       ss   s    w   a  Cs    C   S   s  S  C a s       S       w   sw   s   sC   a     CwS a a   S     C   >     s  C s          C      C w  w      w   a  CS    S s    saS S C     C  s  w a     w a Sa   w sw  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 725
ace_score 3625
size 725, 1
stairs 623, 0

warrior 478, 0, :east

unit :wizard, 10, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 14, 0, :east
unit :captive, 15, 0, :east
unit :thick_sludge, 19, 0, :east
unit :archer, 26, 0, :east
unit :wizard, 27, 0, :east
unit :thick_sludge, 29, 0, :east
unit :archer, 33, 0, :east
unit :thick_sludge, 35, 0, :east
unit :captive, 37, 0, :east
unit :thick_sludge, 40, 0, :east
unit :archer, 42, 0, :east
unit :thick_sludge, 43, 0, :east
unit :archer, 44, 0, :east
unit :captive, 46, 0, :east
unit :captive, 48, 0, :east
unit :thick_sludge, 50, 0, :east
unit :captive, 57, 0, :east
unit :wizard, 62, 0, :east
unit :captive, 63, 0, :east
unit :thick_sludge, 67, 0, :east
unit :thick_sludge, 70, 0, :east
unit :archer, 79, 0, :east
unit :captive, 80, 0, :east
unit :archer, 81, 0, :east
unit :wizard, 94, 0, :east
unit :archer, 97, 0, :east
unit :sludge, 101, 0, :east
unit :captive, 104, 0, :east
unit :archer, 109, 0, :east
unit :wizard, 114, 0, :east
unit :sludge, 118, 0, :east
unit :archer, 120, 0, :east
unit :captive, 126, 0, :east
unit :thick_sludge, 127, 0, :east
unit :sludge, 128, 0, :east
unit :archer, 129, 0, :east
unit :captive, 135, 0, :east
unit :wizard, 142, 0, :east
unit :thick_sludge, 145, 0, :east
unit :captive, 149, 0, :east
unit :archer, 154, 0, :east
unit :captive, 155, 0, :east
unit :sludge, 159, 0, :east
unit :captive, 167, 0, :east
unit :wizard, 176, 0, :east
unit :captive, 177, 0, :east
unit :archer, 182, 0, :east
unit :thick_sludge, 187, 0, :east
unit :thick_sludge, 192, 0, :east
unit :sludge, 193, 0, :east
unit :archer, 194, 0, :east
unit :sludge, 204, 0, :east
unit :thick_sludge, 208, 0, :east
unit :archer, 213, 0, :east
unit :captive, 223, 0, :east
unit :thick_sludge, 228, 0, :east
unit :captive, 229, 0, :east
unit :archer, 230, 0, :east
unit :archer, 232, 0, :east
unit :captive, 239, 0, :east
unit :sludge, 241, 0, :east
unit :archer, 256, 0, :east
unit :wizard, 262, 0, :east
unit :captive, 268, 0, :east
unit :thick_sludge, 273, 0, :east
unit :sludge, 278, 0, :east
unit :captive, 280, 0, :east
unit :archer, 281, 0, :east
unit :sludge, 288, 0, :east
unit :sludge, 291, 0, :east
unit :wizard, 303, 0, :east
unit :archer, 306, 0, :east
unit :sludge, 308, 0, :east
unit :wizard, 311, 0, :east
unit :thick_sludge, 316, 0, :east
unit :captive, 318, 0, :east
unit :wizard, 320, 0, :east
unit :sludge, 321, 0, :east
unit :thick_sludge, 322, 0, :east
unit :captive, 323, 0, :east
unit :sludge, 324, 0, :east
unit :archer, 329, 0, :east
unit :wizard, 330, 0, :east
unit :archer, 337, 0, :east
unit :sludge, 338, 0, :east
unit :archer, 340, 0, :east
unit :captive, 342, 0, :east
unit :thick_sludge, 347, 0, :east
unit :thick_sludge, 353, 0, :east
unit :wizard, 355, 0, :east
unit :sludge, 359, 0, :east
unit :wizard, 364, 0, :east
unit :archer, 366, 0, :east
unit :archer, 368, 0, :east
unit :sludge, 370, 0, :east
unit :sludge, 372, 0, :east
unit :wizard, 374, 0, :east
unit :wizard, 389, 0, :east
unit :thick_sludge, 392, 0, :east
unit :captive, 403, 0, :east
unit :thick_sludge, 407, 0, :east
unit :sludge, 412, 0, :east
unit :captive, 413, 0, :east
unit :archer, 416, 0, :east
unit :wizard, 425, 0, :east
unit :archer, 427, 0, :east
unit :thick_sludge, 438, 0, :east
unit :wizard, 448, 0, :east
unit :thick_sludge, 455, 0, :east
unit :archer, 459, 0, :east
unit :thick_sludge, 460, 0, :east
unit :archer, 465, 0, :east
unit :thick_sludge, 468, 0, :east
unit :thick_sludge, 470, 0, :east
unit :sludge, 483, 0, :west
unit :captive, 488, 0, :west
unit :captive, 494, 0, :west
unit :captive, 508, 0, :west
unit :archer, 509, 0, :west
unit :captive, 514, 0, :west
unit :sludge, 522, 0, :west
unit :sludge, 523, 0, :west
unit :sludge, 527, 0, :west
unit :wizard, 532, 0, :west
unit :archer, 536, 0, :west
unit :captive, 539, 0, :west
unit :sludge, 540, 0, :west
unit :captive, 545, 0, :west
unit :thick_sludge, 549, 0, :west
unit :sludge, 553, 0, :west
unit :thick_sludge, 556, 0, :west
unit :captive, 559, 0, :west
unit :archer, 561, 0, :west
unit :sludge, 563, 0, :west
unit :thick_sludge, 571, 0, :west
unit :wizard, 579, 0, :west
unit :sludge, 583, 0, :west
unit :wizard, 584, 0, :west
unit :sludge, 588, 0, :west
unit :sludge, 592, 0, :west
unit :captive, 593, 0, :west
unit :archer, 597, 0, :west
unit :captive, 603, 0, :west
unit :wizard, 604, 0, :west
unit :thick_sludge, 605, 0, :west
unit :archer, 607, 0, :west
unit :archer, 609, 0, :west
unit :thick_sludge, 613, 0, :west
unit :captive, 619, 0, :west
unit :sludge, 629, 0, :west
unit :captive, 632, 0, :west
unit :sludge, 634, 0, :west
unit :captive, 645, 0, :west
unit :captive, 652, 0, :west
unit :wizard, 654, 0, :west
unit :wizard, 657, 0, :west
unit :wizard, 664, 0, :west
unit :archer, 668, 0, :west
unit :captive, 671, 0, :west
unit :thick_sludge, 672, 0, :west
unit :thick_sludge, 677, 0, :west
unit :sludge, 679, 0, :west
unit :sludge, 684, 0, :west
unit :archer, 685, 0, :west
unit :thick_sludge, 686, 0, :west
unit :thick_sludge, 688, 0, :west
unit :captive, 690, 0, :west
unit :captive, 696, 0, :west
unit :sludge, 699, 0, :west
unit :wizard, 702, 0, :west
unit :archer, 704, 0, :west
unit :wizard, 710, 0, :west
unit :archer, 712, 0, :west
unit :thick_sludge, 714, 0, :west
unit :archer, 715, 0, :west
unit :wizard, 719, 0, :west
unit :sludge, 721, 0, :west
unit :wizard, 722, 0, :west
