#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | w   C   s    s        s       s  w   S  CS        S   wS C s        a  a   C  S   S   ws    w    a  a s      aS     s  S          w a C    C    wS    s     a  s   s SC    sS w S a    SS         w    Ss     C  sCS    s     w    w   s    s S   a           s      >   a wS    s w  w     s  sS s  S a S   S           w w CC     C        a  a        a w    a     C  a     w     w wCa   w   SS w  aa    wSC a  a     a           aw   w   C        SS   s   S                 CS  w C       ss     S wC    S  S      C   C    s       aaaCa a  wS    a Sa   s  @   a     as     S SsS      a         s     s       a CC      S      w          aS  s  s  s     w     Sas  a     a s aC    w  s              C      C          a       ss aa   sa  S  s  a    w      S      C|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 754
ace_score 3770
size 754, 1
stairs 262, 0

warrior 549, 0, :east

unit :wizard, 1, 0, :east
unit :captive, 5, 0, :east
unit :sludge, 9, 0, :east
unit :sludge, 14, 0, :east
unit :sludge, 23, 0, :east
unit :sludge, 31, 0, :east
unit :wizard, 34, 0, :east
unit :thick_sludge, 38, 0, :east
unit :captive, 41, 0, :east
unit :thick_sludge, 42, 0, :east
unit :thick_sludge, 51, 0, :east
unit :wizard, 55, 0, :east
unit :thick_sludge, 56, 0, :east
unit :captive, 58, 0, :east
unit :sludge, 60, 0, :east
unit :archer, 69, 0, :east
unit :archer, 72, 0, :east
unit :captive, 76, 0, :east
unit :thick_sludge, 79, 0, :east
unit :thick_sludge, 83, 0, :east
unit :wizard, 87, 0, :east
unit :sludge, 88, 0, :east
unit :wizard, 93, 0, :east
unit :archer, 98, 0, :east
unit :archer, 101, 0, :east
unit :sludge, 103, 0, :east
unit :archer, 110, 0, :east
unit :thick_sludge, 111, 0, :east
unit :sludge, 117, 0, :east
unit :thick_sludge, 120, 0, :east
unit :wizard, 131, 0, :east
unit :archer, 133, 0, :east
unit :captive, 135, 0, :east
unit :captive, 140, 0, :east
unit :wizard, 145, 0, :east
unit :thick_sludge, 146, 0, :east
unit :sludge, 151, 0, :east
unit :archer, 157, 0, :east
unit :sludge, 160, 0, :east
unit :sludge, 164, 0, :east
unit :thick_sludge, 166, 0, :east
unit :captive, 167, 0, :east
unit :sludge, 172, 0, :east
unit :thick_sludge, 173, 0, :east
unit :wizard, 175, 0, :east
unit :thick_sludge, 177, 0, :east
unit :archer, 179, 0, :east
unit :thick_sludge, 184, 0, :east
unit :thick_sludge, 185, 0, :east
unit :wizard, 195, 0, :east
unit :thick_sludge, 200, 0, :east
unit :sludge, 201, 0, :east
unit :captive, 207, 0, :east
unit :sludge, 210, 0, :east
unit :captive, 211, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 217, 0, :east
unit :wizard, 223, 0, :east
unit :wizard, 228, 0, :east
unit :sludge, 232, 0, :east
unit :sludge, 237, 0, :east
unit :thick_sludge, 239, 0, :east
unit :archer, 243, 0, :east
unit :sludge, 255, 0, :east
unit :archer, 266, 0, :east
unit :wizard, 268, 0, :east
unit :thick_sludge, 269, 0, :east
unit :sludge, 274, 0, :east
unit :wizard, 276, 0, :east
unit :wizard, 279, 0, :east
unit :sludge, 285, 0, :east
unit :sludge, 288, 0, :east
unit :thick_sludge, 289, 0, :east
unit :sludge, 291, 0, :east
unit :thick_sludge, 294, 0, :east
unit :archer, 296, 0, :east
unit :thick_sludge, 298, 0, :east
unit :thick_sludge, 302, 0, :east
unit :wizard, 314, 0, :east
unit :wizard, 316, 0, :east
unit :captive, 318, 0, :east
unit :captive, 319, 0, :east
unit :captive, 325, 0, :east
unit :archer, 334, 0, :east
unit :archer, 337, 0, :east
unit :archer, 346, 0, :east
unit :wizard, 348, 0, :east
unit :archer, 353, 0, :east
unit :captive, 359, 0, :east
unit :archer, 362, 0, :east
unit :wizard, 368, 0, :east
unit :wizard, 374, 0, :east
unit :wizard, 376, 0, :east
unit :captive, 377, 0, :east
unit :archer, 378, 0, :east
unit :wizard, 382, 0, :east
unit :thick_sludge, 386, 0, :east
unit :thick_sludge, 387, 0, :east
unit :wizard, 389, 0, :east
unit :archer, 392, 0, :east
unit :archer, 393, 0, :east
unit :wizard, 398, 0, :east
unit :thick_sludge, 399, 0, :east
unit :captive, 400, 0, :east
unit :archer, 402, 0, :east
unit :archer, 405, 0, :east
unit :archer, 411, 0, :east
unit :archer, 423, 0, :east
unit :wizard, 424, 0, :east
unit :wizard, 428, 0, :east
unit :captive, 432, 0, :east
unit :thick_sludge, 441, 0, :east
unit :thick_sludge, 442, 0, :east
unit :sludge, 446, 0, :east
unit :thick_sludge, 450, 0, :east
unit :captive, 468, 0, :east
unit :thick_sludge, 469, 0, :east
unit :wizard, 472, 0, :east
unit :captive, 474, 0, :east
unit :sludge, 482, 0, :east
unit :sludge, 483, 0, :east
unit :thick_sludge, 489, 0, :east
unit :wizard, 491, 0, :east
unit :captive, 492, 0, :east
unit :thick_sludge, 497, 0, :east
unit :thick_sludge, 500, 0, :east
unit :captive, 507, 0, :east
unit :captive, 511, 0, :east
unit :sludge, 516, 0, :east
unit :archer, 524, 0, :east
unit :archer, 525, 0, :east
unit :archer, 526, 0, :east
unit :captive, 527, 0, :east
unit :archer, 528, 0, :east
unit :archer, 530, 0, :east
unit :wizard, 533, 0, :east
unit :thick_sludge, 534, 0, :east
unit :archer, 539, 0, :east
unit :thick_sludge, 541, 0, :east
unit :archer, 542, 0, :east
unit :sludge, 546, 0, :east
unit :archer, 553, 0, :west
unit :archer, 559, 0, :west
unit :sludge, 560, 0, :west
unit :thick_sludge, 566, 0, :west
unit :thick_sludge, 568, 0, :west
unit :sludge, 569, 0, :west
unit :thick_sludge, 570, 0, :west
unit :archer, 577, 0, :west
unit :sludge, 587, 0, :west
unit :sludge, 593, 0, :west
unit :archer, 601, 0, :west
unit :captive, 603, 0, :west
unit :captive, 604, 0, :west
unit :thick_sludge, 611, 0, :west
unit :wizard, 618, 0, :west
unit :archer, 629, 0, :west
unit :thick_sludge, 630, 0, :west
unit :sludge, 633, 0, :west
unit :sludge, 636, 0, :west
unit :sludge, 639, 0, :west
unit :wizard, 645, 0, :west
unit :thick_sludge, 651, 0, :west
unit :archer, 652, 0, :west
unit :sludge, 653, 0, :west
unit :archer, 656, 0, :west
unit :archer, 662, 0, :west
unit :sludge, 664, 0, :west
unit :archer, 666, 0, :west
unit :captive, 667, 0, :west
unit :wizard, 672, 0, :west
unit :sludge, 675, 0, :west
unit :captive, 690, 0, :west
unit :captive, 697, 0, :west
unit :archer, 708, 0, :west
unit :sludge, 716, 0, :west
unit :sludge, 717, 0, :west
unit :archer, 719, 0, :west
unit :archer, 720, 0, :west
unit :sludge, 724, 0, :west
unit :archer, 725, 0, :west
unit :thick_sludge, 728, 0, :west
unit :sludge, 731, 0, :west
unit :archer, 734, 0, :west
unit :wizard, 739, 0, :west
unit :thick_sludge, 746, 0, :west
unit :captive, 753, 0, :west
