#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     S                    @  s        S        w  C s   sw Ca   C  S     w  ss      Cs w w s    s w C    a       Ss  C  s  S  SS     a        wS    C  aCC   a w  S  w    ss   w    C aw   C  a   C  SS  s a  wCws  Ca   S  aa       C   w         s Sa w  sw C   asC C  a         a     C C       s C       Ca                w   S         s        SS       S   C       C         C a wSS   a       w    a  w     S          a     C  C C sa      C  a sa        ws           > s         s  S   w  C    C  s C a   a S                   CaS   w  s  asCs    a   |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 549
ace_score 2745
size 549, 1
stairs 465, 0

warrior 26, 0, :east

unit :thick_sludge, 5, 0, :east
unit :sludge, 29, 0, :west
unit :thick_sludge, 38, 0, :west
unit :wizard, 47, 0, :west
unit :captive, 50, 0, :west
unit :sludge, 52, 0, :west
unit :sludge, 56, 0, :west
unit :wizard, 57, 0, :west
unit :captive, 59, 0, :west
unit :archer, 60, 0, :west
unit :captive, 64, 0, :west
unit :thick_sludge, 67, 0, :west
unit :wizard, 73, 0, :west
unit :sludge, 76, 0, :west
unit :sludge, 77, 0, :west
unit :captive, 84, 0, :west
unit :sludge, 85, 0, :west
unit :wizard, 87, 0, :west
unit :wizard, 89, 0, :west
unit :sludge, 91, 0, :west
unit :sludge, 96, 0, :west
unit :wizard, 98, 0, :west
unit :captive, 100, 0, :west
unit :archer, 105, 0, :west
unit :thick_sludge, 113, 0, :west
unit :sludge, 114, 0, :west
unit :captive, 117, 0, :west
unit :sludge, 120, 0, :west
unit :thick_sludge, 123, 0, :west
unit :thick_sludge, 126, 0, :west
unit :thick_sludge, 127, 0, :west
unit :archer, 133, 0, :west
unit :wizard, 142, 0, :west
unit :thick_sludge, 143, 0, :west
unit :captive, 148, 0, :west
unit :archer, 151, 0, :west
unit :captive, 152, 0, :west
unit :captive, 153, 0, :west
unit :archer, 157, 0, :west
unit :wizard, 159, 0, :west
unit :thick_sludge, 162, 0, :west
unit :wizard, 165, 0, :west
unit :sludge, 170, 0, :west
unit :sludge, 171, 0, :west
unit :wizard, 175, 0, :west
unit :captive, 180, 0, :west
unit :archer, 182, 0, :west
unit :wizard, 183, 0, :west
unit :captive, 187, 0, :west
unit :archer, 190, 0, :west
unit :captive, 194, 0, :west
unit :thick_sludge, 197, 0, :west
unit :thick_sludge, 198, 0, :west
unit :sludge, 201, 0, :west
unit :archer, 203, 0, :west
unit :wizard, 206, 0, :west
unit :captive, 207, 0, :west
unit :wizard, 208, 0, :west
unit :sludge, 209, 0, :west
unit :captive, 212, 0, :west
unit :archer, 213, 0, :west
unit :thick_sludge, 217, 0, :west
unit :archer, 220, 0, :west
unit :archer, 221, 0, :west
unit :captive, 229, 0, :west
unit :wizard, 233, 0, :west
unit :sludge, 243, 0, :west
unit :thick_sludge, 245, 0, :west
unit :archer, 246, 0, :west
unit :wizard, 248, 0, :west
unit :sludge, 251, 0, :west
unit :wizard, 252, 0, :west
unit :captive, 254, 0, :west
unit :archer, 258, 0, :west
unit :sludge, 259, 0, :west
unit :captive, 260, 0, :west
unit :captive, 262, 0, :west
unit :archer, 265, 0, :west
unit :archer, 275, 0, :west
unit :captive, 281, 0, :west
unit :captive, 283, 0, :west
unit :sludge, 291, 0, :west
unit :captive, 293, 0, :west
unit :captive, 301, 0, :west
unit :archer, 302, 0, :west
unit :wizard, 319, 0, :west
unit :thick_sludge, 323, 0, :west
unit :sludge, 333, 0, :west
unit :thick_sludge, 342, 0, :west
unit :thick_sludge, 343, 0, :west
unit :thick_sludge, 351, 0, :west
unit :captive, 355, 0, :west
unit :captive, 363, 0, :west
unit :captive, 373, 0, :west
unit :archer, 375, 0, :west
unit :wizard, 377, 0, :west
unit :thick_sludge, 378, 0, :west
unit :thick_sludge, 379, 0, :west
unit :archer, 383, 0, :west
unit :wizard, 391, 0, :west
unit :archer, 396, 0, :west
unit :wizard, 399, 0, :west
unit :thick_sludge, 405, 0, :west
unit :archer, 416, 0, :west
unit :captive, 422, 0, :west
unit :captive, 425, 0, :west
unit :captive, 427, 0, :west
unit :sludge, 429, 0, :west
unit :archer, 430, 0, :west
unit :captive, 437, 0, :west
unit :archer, 440, 0, :west
unit :sludge, 442, 0, :west
unit :archer, 443, 0, :west
unit :wizard, 452, 0, :west
unit :sludge, 453, 0, :west
unit :sludge, 467, 0, :west
unit :sludge, 477, 0, :west
unit :thick_sludge, 480, 0, :west
unit :wizard, 484, 0, :west
unit :captive, 487, 0, :west
unit :captive, 492, 0, :west
unit :sludge, 495, 0, :west
unit :captive, 497, 0, :west
unit :archer, 499, 0, :west
unit :archer, 503, 0, :west
unit :thick_sludge, 505, 0, :west
unit :captive, 525, 0, :west
unit :archer, 526, 0, :west
unit :thick_sludge, 527, 0, :west
unit :wizard, 531, 0, :west
unit :sludge, 534, 0, :west
unit :archer, 537, 0, :west
unit :sludge, 538, 0, :west
unit :captive, 539, 0, :west
unit :sludge, 540, 0, :west
unit :archer, 545, 0, :west
