#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    s C   CS     s     w       wC  a aa  S  S    w w               C  S S  ss          s     C       S  S   aa      aS ss S   a wS   s  @    wC a     w s S a        sCw         a       C  s     a s     CS   SsS  Css a S      a   S         s       s  S w         CaS C            SSs  S  S   aa     S   C w                  S      S S   sC  C          a       aSs   wC  a s   w     C      S             Ca  S a Sw        Cs    wS w    CC  S      S  a        a            sC  w    C          a w      C    C S      C  a   w    wa    s  aS    ss  C  C    S  s     C   C    a C    S  w S         s  > a C                a   w  w     S   s     aCS a   Caa  w  S      s   C     s   w SCw s w  C    |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 692
ace_score 3460
size 692, 1
stairs 595, 0

warrior 136, 0, :east

unit :sludge, 4, 0, :east
unit :captive, 6, 0, :east
unit :captive, 10, 0, :east
unit :thick_sludge, 11, 0, :east
unit :sludge, 17, 0, :east
unit :wizard, 23, 0, :east
unit :wizard, 31, 0, :east
unit :captive, 32, 0, :east
unit :archer, 35, 0, :east
unit :archer, 37, 0, :east
unit :archer, 38, 0, :east
unit :thick_sludge, 41, 0, :east
unit :thick_sludge, 44, 0, :east
unit :wizard, 49, 0, :east
unit :wizard, 51, 0, :east
unit :captive, 67, 0, :east
unit :thick_sludge, 70, 0, :east
unit :thick_sludge, 72, 0, :east
unit :sludge, 75, 0, :east
unit :sludge, 76, 0, :east
unit :sludge, 87, 0, :east
unit :captive, 93, 0, :east
unit :thick_sludge, 101, 0, :east
unit :thick_sludge, 104, 0, :east
unit :archer, 108, 0, :east
unit :archer, 109, 0, :east
unit :archer, 116, 0, :east
unit :thick_sludge, 117, 0, :east
unit :sludge, 119, 0, :east
unit :sludge, 120, 0, :east
unit :thick_sludge, 122, 0, :east
unit :archer, 126, 0, :east
unit :wizard, 128, 0, :east
unit :thick_sludge, 129, 0, :east
unit :sludge, 133, 0, :east
unit :wizard, 141, 0, :west
unit :captive, 142, 0, :west
unit :archer, 144, 0, :west
unit :wizard, 150, 0, :west
unit :sludge, 152, 0, :west
unit :thick_sludge, 154, 0, :west
unit :archer, 156, 0, :west
unit :sludge, 165, 0, :west
unit :captive, 166, 0, :west
unit :wizard, 167, 0, :west
unit :archer, 177, 0, :west
unit :captive, 185, 0, :west
unit :sludge, 188, 0, :west
unit :archer, 194, 0, :west
unit :sludge, 196, 0, :west
unit :captive, 202, 0, :west
unit :thick_sludge, 203, 0, :west
unit :thick_sludge, 207, 0, :west
unit :sludge, 208, 0, :west
unit :thick_sludge, 209, 0, :west
unit :captive, 212, 0, :west
unit :sludge, 213, 0, :west
unit :sludge, 214, 0, :west
unit :archer, 216, 0, :west
unit :thick_sludge, 218, 0, :west
unit :archer, 225, 0, :west
unit :thick_sludge, 229, 0, :west
unit :sludge, 239, 0, :west
unit :sludge, 247, 0, :west
unit :thick_sludge, 250, 0, :west
unit :wizard, 252, 0, :west
unit :captive, 262, 0, :west
unit :archer, 263, 0, :west
unit :thick_sludge, 264, 0, :west
unit :captive, 266, 0, :west
unit :thick_sludge, 279, 0, :west
unit :thick_sludge, 280, 0, :west
unit :sludge, 281, 0, :west
unit :thick_sludge, 284, 0, :west
unit :thick_sludge, 287, 0, :west
unit :archer, 291, 0, :west
unit :archer, 292, 0, :west
unit :thick_sludge, 298, 0, :west
unit :captive, 302, 0, :west
unit :wizard, 304, 0, :west
unit :thick_sludge, 323, 0, :west
unit :thick_sludge, 330, 0, :west
unit :thick_sludge, 332, 0, :west
unit :sludge, 336, 0, :west
unit :captive, 337, 0, :west
unit :captive, 340, 0, :west
unit :archer, 351, 0, :west
unit :archer, 359, 0, :west
unit :thick_sludge, 360, 0, :west
unit :sludge, 361, 0, :west
unit :wizard, 365, 0, :west
unit :captive, 366, 0, :west
unit :archer, 369, 0, :west
unit :sludge, 371, 0, :west
unit :wizard, 375, 0, :west
unit :captive, 381, 0, :west
unit :thick_sludge, 388, 0, :west
unit :captive, 402, 0, :west
unit :archer, 403, 0, :west
unit :thick_sludge, 406, 0, :west
unit :archer, 408, 0, :west
unit :thick_sludge, 410, 0, :west
unit :wizard, 411, 0, :west
unit :captive, 420, 0, :west
unit :sludge, 421, 0, :west
unit :wizard, 426, 0, :west
unit :thick_sludge, 427, 0, :west
unit :wizard, 429, 0, :west
unit :captive, 434, 0, :west
unit :captive, 435, 0, :west
unit :thick_sludge, 438, 0, :west
unit :thick_sludge, 445, 0, :west
unit :archer, 448, 0, :west
unit :archer, 457, 0, :west
unit :sludge, 470, 0, :west
unit :captive, 471, 0, :west
unit :wizard, 474, 0, :west
unit :captive, 479, 0, :west
unit :archer, 490, 0, :west
unit :wizard, 492, 0, :west
unit :captive, 499, 0, :west
unit :captive, 504, 0, :west
unit :thick_sludge, 506, 0, :west
unit :captive, 513, 0, :west
unit :archer, 516, 0, :west
unit :wizard, 520, 0, :west
unit :wizard, 525, 0, :west
unit :archer, 526, 0, :west
unit :sludge, 531, 0, :west
unit :archer, 534, 0, :west
unit :thick_sludge, 535, 0, :west
unit :sludge, 540, 0, :west
unit :sludge, 541, 0, :west
unit :captive, 544, 0, :west
unit :captive, 547, 0, :west
unit :thick_sludge, 552, 0, :west
unit :sludge, 555, 0, :west
unit :captive, 561, 0, :west
unit :captive, 565, 0, :west
unit :archer, 570, 0, :west
unit :captive, 572, 0, :west
unit :thick_sludge, 577, 0, :west
unit :wizard, 580, 0, :west
unit :thick_sludge, 582, 0, :west
unit :sludge, 592, 0, :west
unit :archer, 597, 0, :west
unit :captive, 599, 0, :west
unit :archer, 616, 0, :west
unit :wizard, 620, 0, :west
unit :wizard, 623, 0, :west
unit :thick_sludge, 629, 0, :west
unit :sludge, 633, 0, :west
unit :archer, 639, 0, :west
unit :captive, 640, 0, :west
unit :thick_sludge, 641, 0, :west
unit :archer, 643, 0, :west
unit :captive, 647, 0, :west
unit :archer, 648, 0, :west
unit :archer, 649, 0, :west
unit :wizard, 652, 0, :west
unit :thick_sludge, 655, 0, :west
unit :sludge, 662, 0, :west
unit :captive, 666, 0, :west
unit :sludge, 672, 0, :west
unit :wizard, 676, 0, :west
unit :thick_sludge, 678, 0, :west
unit :captive, 679, 0, :west
unit :wizard, 680, 0, :west
unit :sludge, 682, 0, :west
unit :wizard, 684, 0, :west
unit :captive, 687, 0, :west
