#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C a  wS  SSs S  S      s       S       S           S    SC     w C S        S  S C      S  w      s     s w a   w     S         Sa              a        w           a S   sa  sCs   aas          w  S a     Cw   s     Cs  C a          s      w         aa  CC    w      ss      Ss   @       S                  a  s       s a  s S   C   s   S S s              C              C  S a           S  C    s S C       S ws C C      S        s     S   a  a   wC        a a    S w      a w  C  S S a    C swa        S    w S    C Css aC     w C     sSSw S     w   C   s  aC aa    a sS    s C   a S   aa                 saCa    S    wSswC   w      s    C  w  Sa     S a w w    S   C s s s                        C    S   S       s  C    s S  s  s w  S  ss   a   a      w   aa C s > a     s      C   Ca w        w  CSS   S wa    s   w     ssS Sa      s   S        w w a  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 857
ace_score 4285
size 857, 1
stairs 767, 0

warrior 280, 0, :east

unit :captive, 0, 0, :east
unit :archer, 2, 0, :east
unit :wizard, 5, 0, :east
unit :thick_sludge, 6, 0, :east
unit :thick_sludge, 9, 0, :east
unit :thick_sludge, 10, 0, :east
unit :sludge, 11, 0, :east
unit :thick_sludge, 13, 0, :east
unit :thick_sludge, 16, 0, :east
unit :sludge, 23, 0, :east
unit :thick_sludge, 31, 0, :east
unit :thick_sludge, 39, 0, :east
unit :thick_sludge, 51, 0, :east
unit :thick_sludge, 56, 0, :east
unit :captive, 57, 0, :east
unit :wizard, 63, 0, :east
unit :captive, 65, 0, :east
unit :thick_sludge, 67, 0, :east
unit :thick_sludge, 76, 0, :east
unit :thick_sludge, 79, 0, :east
unit :captive, 81, 0, :east
unit :thick_sludge, 88, 0, :east
unit :wizard, 91, 0, :east
unit :sludge, 98, 0, :east
unit :sludge, 104, 0, :east
unit :wizard, 106, 0, :east
unit :archer, 108, 0, :east
unit :wizard, 112, 0, :east
unit :thick_sludge, 118, 0, :east
unit :thick_sludge, 128, 0, :east
unit :archer, 129, 0, :east
unit :archer, 144, 0, :east
unit :wizard, 153, 0, :east
unit :archer, 165, 0, :east
unit :thick_sludge, 167, 0, :east
unit :sludge, 171, 0, :east
unit :archer, 172, 0, :east
unit :sludge, 175, 0, :east
unit :captive, 176, 0, :east
unit :sludge, 177, 0, :east
unit :archer, 181, 0, :east
unit :archer, 182, 0, :east
unit :sludge, 183, 0, :east
unit :wizard, 194, 0, :east
unit :thick_sludge, 197, 0, :east
unit :archer, 199, 0, :east
unit :captive, 205, 0, :east
unit :wizard, 206, 0, :east
unit :sludge, 210, 0, :east
unit :captive, 216, 0, :east
unit :sludge, 217, 0, :east
unit :captive, 220, 0, :east
unit :archer, 222, 0, :east
unit :sludge, 233, 0, :east
unit :wizard, 240, 0, :east
unit :archer, 250, 0, :east
unit :archer, 251, 0, :east
unit :captive, 254, 0, :east
unit :captive, 255, 0, :east
unit :wizard, 260, 0, :east
unit :sludge, 267, 0, :east
unit :sludge, 268, 0, :east
unit :thick_sludge, 275, 0, :east
unit :sludge, 276, 0, :east
unit :thick_sludge, 288, 0, :west
unit :archer, 307, 0, :west
unit :sludge, 310, 0, :west
unit :sludge, 318, 0, :west
unit :archer, 320, 0, :west
unit :sludge, 323, 0, :west
unit :thick_sludge, 325, 0, :west
unit :captive, 329, 0, :west
unit :sludge, 333, 0, :west
unit :thick_sludge, 337, 0, :west
unit :thick_sludge, 339, 0, :west
unit :sludge, 341, 0, :west
unit :captive, 356, 0, :west
unit :captive, 371, 0, :west
unit :thick_sludge, 374, 0, :west
unit :archer, 376, 0, :west
unit :thick_sludge, 388, 0, :west
unit :captive, 391, 0, :west
unit :sludge, 396, 0, :west
unit :thick_sludge, 398, 0, :west
unit :captive, 400, 0, :west
unit :thick_sludge, 408, 0, :west
unit :wizard, 410, 0, :west
unit :sludge, 411, 0, :west
unit :captive, 413, 0, :west
unit :captive, 415, 0, :west
unit :thick_sludge, 422, 0, :west
unit :sludge, 431, 0, :west
unit :thick_sludge, 437, 0, :west
unit :archer, 441, 0, :west
unit :archer, 444, 0, :west
unit :wizard, 448, 0, :west
unit :captive, 449, 0, :west
unit :archer, 458, 0, :west
unit :archer, 460, 0, :west
unit :thick_sludge, 465, 0, :west
unit :wizard, 467, 0, :west
unit :archer, 474, 0, :west
unit :wizard, 476, 0, :west
unit :captive, 479, 0, :west
unit :thick_sludge, 482, 0, :west
unit :thick_sludge, 484, 0, :west
unit :archer, 486, 0, :west
unit :captive, 491, 0, :west
unit :sludge, 493, 0, :west
unit :wizard, 494, 0, :west
unit :archer, 495, 0, :west
unit :thick_sludge, 504, 0, :west
unit :wizard, 509, 0, :west
unit :thick_sludge, 511, 0, :west
unit :captive, 516, 0, :west
unit :captive, 518, 0, :west
unit :sludge, 519, 0, :west
unit :sludge, 520, 0, :west
unit :archer, 522, 0, :west
unit :captive, 523, 0, :west
unit :wizard, 529, 0, :west
unit :captive, 531, 0, :west
unit :sludge, 537, 0, :west
unit :thick_sludge, 538, 0, :west
unit :thick_sludge, 539, 0, :west
unit :wizard, 540, 0, :west
unit :thick_sludge, 542, 0, :west
unit :wizard, 548, 0, :west
unit :captive, 552, 0, :west
unit :sludge, 556, 0, :west
unit :archer, 559, 0, :west
unit :captive, 560, 0, :west
unit :archer, 562, 0, :west
unit :archer, 563, 0, :west
unit :archer, 568, 0, :west
unit :sludge, 570, 0, :west
unit :thick_sludge, 571, 0, :west
unit :sludge, 576, 0, :west
unit :captive, 578, 0, :west
unit :archer, 582, 0, :west
unit :thick_sludge, 584, 0, :west
unit :archer, 588, 0, :west
unit :archer, 589, 0, :west
unit :sludge, 607, 0, :west
unit :archer, 608, 0, :west
unit :captive, 609, 0, :west
unit :archer, 610, 0, :west
unit :thick_sludge, 615, 0, :west
unit :wizard, 620, 0, :west
unit :thick_sludge, 621, 0, :west
unit :sludge, 622, 0, :west
unit :wizard, 623, 0, :west
unit :captive, 624, 0, :west
unit :wizard, 628, 0, :west
unit :sludge, 635, 0, :west
unit :captive, 640, 0, :west
unit :wizard, 643, 0, :west
unit :thick_sludge, 646, 0, :west
unit :archer, 647, 0, :west
unit :thick_sludge, 653, 0, :west
unit :archer, 655, 0, :west
unit :wizard, 657, 0, :west
unit :wizard, 659, 0, :west
unit :thick_sludge, 664, 0, :west
unit :captive, 668, 0, :west
unit :sludge, 670, 0, :west
unit :sludge, 672, 0, :west
unit :sludge, 674, 0, :west
unit :captive, 699, 0, :west
unit :thick_sludge, 704, 0, :west
unit :thick_sludge, 708, 0, :west
unit :sludge, 716, 0, :west
unit :captive, 719, 0, :west
unit :sludge, 724, 0, :west
unit :thick_sludge, 726, 0, :west
unit :sludge, 729, 0, :west
unit :sludge, 732, 0, :west
unit :wizard, 734, 0, :west
unit :thick_sludge, 737, 0, :west
unit :sludge, 740, 0, :west
unit :sludge, 741, 0, :west
unit :archer, 745, 0, :west
unit :archer, 749, 0, :west
unit :wizard, 756, 0, :west
unit :archer, 760, 0, :west
unit :archer, 761, 0, :west
unit :captive, 763, 0, :west
unit :sludge, 765, 0, :west
unit :archer, 769, 0, :west
unit :sludge, 775, 0, :west
unit :captive, 782, 0, :west
unit :captive, 786, 0, :west
unit :archer, 787, 0, :west
unit :wizard, 789, 0, :west
unit :wizard, 798, 0, :west
unit :captive, 801, 0, :west
unit :thick_sludge, 802, 0, :west
unit :thick_sludge, 803, 0, :west
unit :thick_sludge, 807, 0, :west
unit :wizard, 809, 0, :west
unit :archer, 810, 0, :west
unit :sludge, 815, 0, :west
unit :wizard, 819, 0, :west
unit :sludge, 825, 0, :west
unit :sludge, 826, 0, :west
unit :thick_sludge, 827, 0, :west
unit :thick_sludge, 829, 0, :west
unit :archer, 830, 0, :west
unit :sludge, 837, 0, :west
unit :thick_sludge, 841, 0, :west
unit :wizard, 850, 0, :west
unit :wizard, 852, 0, :west
unit :archer, 854, 0, :west
