#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   ss     S   SS    aS  s  w  w     s           w   C w        S       @    w         S  Cas      ss      S  S     wS   s C   a    C   a S    s     w    Ca    ws C   s  as       a   sS         s aS C  S Cs  S S S    a    w  S          asa        w   s    a   a  a     SCSw Sw  S S  C aS       s      s a     sa    w   a  S C  w      w   ss     a S w  w   aC S  a  S      w S  s     s a   w  S     C       > s   C C             C   Ca S       w S w   a       s    w S    wCs           CS w   S     a  s        a  a   a a w     C s     S w S     C s   C  w  a      s  s w  C        a  C      C        a          s  s  S              s sS   S SSC aS   a    C  s  w    C   s  Sw       S     a  C      a s          S    a    w aC S         Cs              C s s  S            C    w  S        a   w wa  s S    S        as   a  C    w            w    Ca    s C a aa|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 859
ace_score 4295
size 859, 1
stairs 405, 0

warrior 71, 0, :east

unit :sludge, 3, 0, :east
unit :sludge, 4, 0, :east
unit :thick_sludge, 10, 0, :east
unit :thick_sludge, 14, 0, :east
unit :thick_sludge, 15, 0, :east
unit :archer, 20, 0, :east
unit :thick_sludge, 21, 0, :east
unit :sludge, 24, 0, :east
unit :wizard, 27, 0, :east
unit :wizard, 30, 0, :east
unit :sludge, 36, 0, :east
unit :wizard, 48, 0, :east
unit :captive, 52, 0, :east
unit :wizard, 54, 0, :east
unit :thick_sludge, 63, 0, :east
unit :wizard, 76, 0, :west
unit :thick_sludge, 86, 0, :west
unit :captive, 89, 0, :west
unit :archer, 90, 0, :west
unit :sludge, 91, 0, :west
unit :sludge, 98, 0, :west
unit :sludge, 99, 0, :west
unit :thick_sludge, 106, 0, :west
unit :thick_sludge, 109, 0, :west
unit :wizard, 115, 0, :west
unit :thick_sludge, 116, 0, :west
unit :sludge, 120, 0, :west
unit :captive, 122, 0, :west
unit :archer, 126, 0, :west
unit :captive, 131, 0, :west
unit :archer, 135, 0, :west
unit :thick_sludge, 137, 0, :west
unit :sludge, 142, 0, :west
unit :wizard, 148, 0, :west
unit :captive, 153, 0, :west
unit :archer, 154, 0, :west
unit :wizard, 159, 0, :west
unit :sludge, 160, 0, :west
unit :captive, 162, 0, :west
unit :sludge, 166, 0, :west
unit :archer, 169, 0, :west
unit :sludge, 170, 0, :west
unit :archer, 178, 0, :west
unit :sludge, 182, 0, :west
unit :thick_sludge, 183, 0, :west
unit :sludge, 193, 0, :west
unit :archer, 195, 0, :west
unit :thick_sludge, 196, 0, :west
unit :captive, 198, 0, :west
unit :thick_sludge, 201, 0, :west
unit :captive, 203, 0, :west
unit :sludge, 204, 0, :west
unit :thick_sludge, 207, 0, :west
unit :thick_sludge, 209, 0, :west
unit :thick_sludge, 211, 0, :west
unit :archer, 216, 0, :west
unit :wizard, 221, 0, :west
unit :thick_sludge, 224, 0, :west
unit :archer, 235, 0, :west
unit :sludge, 236, 0, :west
unit :archer, 237, 0, :west
unit :wizard, 246, 0, :west
unit :sludge, 250, 0, :west
unit :archer, 255, 0, :west
unit :archer, 259, 0, :west
unit :archer, 262, 0, :west
unit :thick_sludge, 268, 0, :west
unit :captive, 269, 0, :west
unit :thick_sludge, 270, 0, :west
unit :wizard, 271, 0, :west
unit :thick_sludge, 273, 0, :west
unit :wizard, 274, 0, :west
unit :thick_sludge, 277, 0, :west
unit :thick_sludge, 279, 0, :west
unit :captive, 282, 0, :west
unit :archer, 284, 0, :west
unit :thick_sludge, 285, 0, :west
unit :sludge, 293, 0, :west
unit :sludge, 300, 0, :west
unit :archer, 302, 0, :west
unit :sludge, 308, 0, :west
unit :archer, 309, 0, :west
unit :wizard, 314, 0, :west
unit :archer, 318, 0, :west
unit :thick_sludge, 321, 0, :west
unit :captive, 323, 0, :west
unit :wizard, 326, 0, :west
unit :wizard, 333, 0, :west
unit :sludge, 337, 0, :west
unit :sludge, 338, 0, :west
unit :archer, 344, 0, :west
unit :thick_sludge, 346, 0, :west
unit :wizard, 348, 0, :west
unit :wizard, 351, 0, :west
unit :archer, 355, 0, :west
unit :captive, 356, 0, :west
unit :thick_sludge, 358, 0, :west
unit :archer, 361, 0, :west
unit :thick_sludge, 364, 0, :west
unit :wizard, 371, 0, :west
unit :thick_sludge, 373, 0, :west
unit :sludge, 376, 0, :west
unit :sludge, 382, 0, :west
unit :archer, 384, 0, :west
unit :wizard, 388, 0, :west
unit :thick_sludge, 391, 0, :west
unit :captive, 397, 0, :west
unit :sludge, 407, 0, :west
unit :captive, 411, 0, :west
unit :captive, 413, 0, :west
unit :captive, 427, 0, :west
unit :captive, 431, 0, :west
unit :archer, 432, 0, :west
unit :thick_sludge, 434, 0, :west
unit :wizard, 442, 0, :west
unit :thick_sludge, 444, 0, :west
unit :wizard, 446, 0, :west
unit :archer, 450, 0, :west
unit :sludge, 458, 0, :west
unit :wizard, 463, 0, :west
unit :thick_sludge, 465, 0, :west
unit :wizard, 470, 0, :west
unit :captive, 471, 0, :west
unit :sludge, 472, 0, :west
unit :captive, 484, 0, :west
unit :thick_sludge, 485, 0, :west
unit :wizard, 487, 0, :west
unit :thick_sludge, 491, 0, :west
unit :archer, 497, 0, :west
unit :sludge, 500, 0, :west
unit :archer, 509, 0, :west
unit :archer, 512, 0, :west
unit :archer, 516, 0, :west
unit :archer, 518, 0, :west
unit :wizard, 520, 0, :west
unit :captive, 526, 0, :west
unit :sludge, 528, 0, :west
unit :thick_sludge, 534, 0, :west
unit :wizard, 536, 0, :west
unit :thick_sludge, 538, 0, :west
unit :captive, 544, 0, :west
unit :sludge, 546, 0, :west
unit :captive, 550, 0, :west
unit :wizard, 553, 0, :west
unit :archer, 556, 0, :west
unit :sludge, 563, 0, :west
unit :sludge, 566, 0, :west
unit :wizard, 568, 0, :west
unit :captive, 571, 0, :west
unit :archer, 580, 0, :west
unit :captive, 583, 0, :west
unit :captive, 590, 0, :west
unit :archer, 599, 0, :west
unit :sludge, 610, 0, :west
unit :sludge, 613, 0, :west
unit :thick_sludge, 616, 0, :west
unit :sludge, 631, 0, :west
unit :sludge, 633, 0, :west
unit :thick_sludge, 634, 0, :west
unit :thick_sludge, 638, 0, :west
unit :thick_sludge, 640, 0, :west
unit :thick_sludge, 641, 0, :west
unit :captive, 642, 0, :west
unit :archer, 644, 0, :west
unit :thick_sludge, 645, 0, :west
unit :archer, 649, 0, :west
unit :captive, 654, 0, :west
unit :sludge, 657, 0, :west
unit :wizard, 660, 0, :west
unit :captive, 665, 0, :west
unit :sludge, 669, 0, :west
unit :thick_sludge, 672, 0, :west
unit :wizard, 673, 0, :west
unit :thick_sludge, 681, 0, :west
unit :archer, 687, 0, :west
unit :captive, 690, 0, :west
unit :archer, 697, 0, :west
unit :sludge, 699, 0, :west
unit :thick_sludge, 710, 0, :west
unit :archer, 715, 0, :west
unit :wizard, 720, 0, :west
unit :archer, 722, 0, :west
unit :captive, 723, 0, :west
unit :thick_sludge, 725, 0, :west
unit :captive, 735, 0, :west
unit :sludge, 736, 0, :west
unit :captive, 751, 0, :west
unit :sludge, 753, 0, :west
unit :sludge, 755, 0, :west
unit :thick_sludge, 758, 0, :west
unit :captive, 771, 0, :west
unit :wizard, 776, 0, :west
unit :thick_sludge, 779, 0, :west
unit :archer, 788, 0, :west
unit :wizard, 792, 0, :west
unit :wizard, 794, 0, :west
unit :archer, 795, 0, :west
unit :sludge, 798, 0, :west
unit :thick_sludge, 800, 0, :west
unit :thick_sludge, 805, 0, :west
unit :archer, 814, 0, :west
unit :sludge, 815, 0, :west
unit :archer, 819, 0, :west
unit :captive, 822, 0, :west
unit :wizard, 827, 0, :west
unit :wizard, 840, 0, :west
unit :captive, 845, 0, :west
unit :archer, 846, 0, :west
unit :sludge, 851, 0, :west
unit :captive, 853, 0, :west
unit :archer, 855, 0, :west
unit :archer, 857, 0, :west
unit :archer, 858, 0, :west
