#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |          sSa      s    s s   C       Ca saCC  a  w w C a       C        C s  a        C  S   a    wC             C   aC   s   S      S   sC        S C  C S   w     asC       sss a w   as     a aa   w      C    w w  w   a              aCa       S           Sa   S   s       S       CCC        w w  C   s        S      S     w       w  a      sa   a S    S  s  SaS CS    w      Ca   ss        a   s   C  s   a s    s a  a C     S a  Sa            w  w   C  wa  wC    S    S         SC  CS     aC   aaa   w    s     S      a   w  S w           @       Ss   S    s     sS S  a a C     S C     S     s     s    S      a w         a         a       a    C   s Ssa sS S    w      w a a  w   C      sC  w     a   CaS  ass    C w   wCCa    a         sw    w     S s  C       a  Cwa>    w  a      S               C       a w  w s            asSS C  a a  S      S  S    sC    C   a    w    a     Cs    C  w   S  s  w        s            S  S     w w C |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 942
ace_score 4710
size 942, 1
stairs 773, 0

warrior 542, 0, :east

unit :sludge, 10, 0, :east
unit :thick_sludge, 11, 0, :east
unit :archer, 12, 0, :east
unit :sludge, 19, 0, :east
unit :sludge, 24, 0, :east
unit :sludge, 26, 0, :east
unit :captive, 30, 0, :east
unit :captive, 38, 0, :east
unit :archer, 39, 0, :east
unit :sludge, 41, 0, :east
unit :archer, 42, 0, :east
unit :captive, 43, 0, :east
unit :captive, 44, 0, :east
unit :archer, 47, 0, :east
unit :wizard, 50, 0, :east
unit :wizard, 52, 0, :east
unit :captive, 54, 0, :east
unit :archer, 56, 0, :east
unit :captive, 64, 0, :east
unit :captive, 73, 0, :east
unit :sludge, 75, 0, :east
unit :archer, 78, 0, :east
unit :captive, 87, 0, :east
unit :thick_sludge, 90, 0, :east
unit :archer, 94, 0, :east
unit :wizard, 99, 0, :east
unit :captive, 100, 0, :east
unit :captive, 114, 0, :east
unit :archer, 118, 0, :east
unit :captive, 119, 0, :east
unit :sludge, 123, 0, :east
unit :thick_sludge, 127, 0, :east
unit :thick_sludge, 134, 0, :east
unit :sludge, 138, 0, :east
unit :captive, 139, 0, :east
unit :thick_sludge, 148, 0, :east
unit :captive, 150, 0, :east
unit :captive, 153, 0, :east
unit :thick_sludge, 155, 0, :east
unit :wizard, 159, 0, :east
unit :archer, 165, 0, :east
unit :sludge, 166, 0, :east
unit :captive, 167, 0, :east
unit :sludge, 175, 0, :east
unit :sludge, 176, 0, :east
unit :sludge, 177, 0, :east
unit :archer, 179, 0, :east
unit :wizard, 181, 0, :east
unit :archer, 185, 0, :east
unit :sludge, 186, 0, :east
unit :archer, 192, 0, :east
unit :archer, 194, 0, :east
unit :archer, 195, 0, :east
unit :wizard, 199, 0, :east
unit :captive, 206, 0, :east
unit :wizard, 211, 0, :east
unit :wizard, 213, 0, :east
unit :wizard, 216, 0, :east
unit :archer, 220, 0, :east
unit :archer, 235, 0, :east
unit :captive, 236, 0, :east
unit :archer, 237, 0, :east
unit :thick_sludge, 245, 0, :east
unit :thick_sludge, 257, 0, :east
unit :archer, 258, 0, :east
unit :thick_sludge, 262, 0, :east
unit :sludge, 266, 0, :east
unit :thick_sludge, 274, 0, :east
unit :captive, 282, 0, :east
unit :captive, 283, 0, :east
unit :captive, 284, 0, :east
unit :wizard, 293, 0, :east
unit :wizard, 295, 0, :east
unit :captive, 298, 0, :east
unit :sludge, 302, 0, :east
unit :thick_sludge, 311, 0, :east
unit :thick_sludge, 318, 0, :east
unit :wizard, 324, 0, :east
unit :wizard, 332, 0, :east
unit :archer, 335, 0, :east
unit :sludge, 342, 0, :east
unit :archer, 343, 0, :east
unit :archer, 347, 0, :east
unit :thick_sludge, 349, 0, :east
unit :thick_sludge, 354, 0, :east
unit :sludge, 357, 0, :east
unit :thick_sludge, 360, 0, :east
unit :archer, 361, 0, :east
unit :thick_sludge, 362, 0, :east
unit :captive, 364, 0, :east
unit :thick_sludge, 365, 0, :east
unit :wizard, 370, 0, :east
unit :captive, 377, 0, :east
unit :archer, 378, 0, :east
unit :sludge, 382, 0, :east
unit :sludge, 383, 0, :east
unit :archer, 392, 0, :east
unit :sludge, 396, 0, :east
unit :captive, 400, 0, :east
unit :sludge, 403, 0, :east
unit :archer, 407, 0, :east
unit :sludge, 409, 0, :east
unit :sludge, 414, 0, :east
unit :archer, 416, 0, :east
unit :archer, 419, 0, :east
unit :captive, 421, 0, :east
unit :thick_sludge, 427, 0, :east
unit :archer, 429, 0, :east
unit :thick_sludge, 432, 0, :east
unit :archer, 433, 0, :east
unit :wizard, 446, 0, :east
unit :wizard, 449, 0, :east
unit :captive, 453, 0, :east
unit :wizard, 456, 0, :east
unit :archer, 457, 0, :east
unit :wizard, 460, 0, :east
unit :captive, 461, 0, :east
unit :thick_sludge, 466, 0, :east
unit :thick_sludge, 471, 0, :east
unit :thick_sludge, 481, 0, :east
unit :captive, 482, 0, :east
unit :captive, 485, 0, :east
unit :thick_sludge, 486, 0, :east
unit :archer, 492, 0, :east
unit :captive, 493, 0, :east
unit :archer, 497, 0, :east
unit :archer, 498, 0, :east
unit :archer, 499, 0, :east
unit :wizard, 503, 0, :east
unit :sludge, 508, 0, :east
unit :thick_sludge, 514, 0, :east
unit :archer, 521, 0, :east
unit :wizard, 525, 0, :east
unit :thick_sludge, 528, 0, :east
unit :wizard, 530, 0, :east
unit :thick_sludge, 550, 0, :west
unit :sludge, 551, 0, :west
unit :thick_sludge, 555, 0, :west
unit :sludge, 560, 0, :west
unit :sludge, 566, 0, :west
unit :thick_sludge, 567, 0, :west
unit :thick_sludge, 569, 0, :west
unit :archer, 572, 0, :west
unit :archer, 574, 0, :west
unit :captive, 576, 0, :west
unit :thick_sludge, 582, 0, :west
unit :captive, 584, 0, :west
unit :thick_sludge, 590, 0, :west
unit :sludge, 596, 0, :west
unit :sludge, 602, 0, :west
unit :thick_sludge, 607, 0, :west
unit :archer, 614, 0, :west
unit :wizard, 616, 0, :west
unit :archer, 626, 0, :west
unit :archer, 636, 0, :west
unit :archer, 644, 0, :west
unit :captive, 649, 0, :west
unit :sludge, 653, 0, :west
unit :thick_sludge, 655, 0, :west
unit :sludge, 656, 0, :west
unit :archer, 657, 0, :west
unit :sludge, 659, 0, :west
unit :thick_sludge, 660, 0, :west
unit :thick_sludge, 662, 0, :west
unit :wizard, 667, 0, :west
unit :wizard, 674, 0, :west
unit :archer, 676, 0, :west
unit :archer, 678, 0, :west
unit :wizard, 681, 0, :west
unit :captive, 685, 0, :west
unit :sludge, 692, 0, :west
unit :captive, 693, 0, :west
unit :wizard, 696, 0, :west
unit :archer, 702, 0, :west
unit :captive, 706, 0, :west
unit :archer, 707, 0, :west
unit :thick_sludge, 708, 0, :west
unit :archer, 711, 0, :west
unit :sludge, 712, 0, :west
unit :sludge, 713, 0, :west
unit :captive, 718, 0, :west
unit :wizard, 720, 0, :west
unit :wizard, 724, 0, :west
unit :captive, 725, 0, :west
unit :captive, 726, 0, :west
unit :archer, 727, 0, :west
unit :archer, 732, 0, :west
unit :sludge, 742, 0, :west
unit :wizard, 743, 0, :west
unit :wizard, 748, 0, :west
unit :thick_sludge, 754, 0, :west
unit :sludge, 756, 0, :west
unit :captive, 759, 0, :west
unit :archer, 767, 0, :west
unit :captive, 770, 0, :west
unit :wizard, 771, 0, :west
unit :archer, 772, 0, :west
unit :wizard, 778, 0, :west
unit :archer, 781, 0, :west
unit :thick_sludge, 788, 0, :west
unit :captive, 804, 0, :west
unit :archer, 812, 0, :west
unit :wizard, 814, 0, :west
unit :wizard, 817, 0, :west
unit :sludge, 819, 0, :west
unit :archer, 832, 0, :west
unit :sludge, 833, 0, :west
unit :thick_sludge, 834, 0, :west
unit :thick_sludge, 835, 0, :west
unit :captive, 837, 0, :west
unit :archer, 840, 0, :west
unit :archer, 842, 0, :west
unit :thick_sludge, 845, 0, :west
unit :thick_sludge, 852, 0, :west
unit :thick_sludge, 855, 0, :west
unit :sludge, 860, 0, :west
unit :captive, 861, 0, :west
unit :captive, 866, 0, :west
unit :archer, 870, 0, :west
unit :wizard, 875, 0, :west
unit :archer, 880, 0, :west
unit :captive, 886, 0, :west
unit :sludge, 887, 0, :west
unit :captive, 892, 0, :west
unit :wizard, 895, 0, :west
unit :thick_sludge, 899, 0, :west
unit :sludge, 902, 0, :west
unit :wizard, 905, 0, :west
unit :sludge, 914, 0, :west
unit :thick_sludge, 927, 0, :west
unit :thick_sludge, 930, 0, :west
unit :wizard, 936, 0, :west
unit :wizard, 938, 0, :west
unit :captive, 940, 0, :west
