#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |           aS   C       a  S   s aa SC     w   C           C as   S S sw aCa  C s s    a w      w                  CC           a  s    C  Cs   w S     w a  w   a  s    C              S     C   S    s  S       a S  w   CC      s C  sC  CS           w      SC          SCs    ss   Ss    a         C sa C  w        a w   s a    sa      wC      aC   s           C      C  as  C  w   s  w S  S     C a w wC a  sS   w C w s S   C  w   SC     Sa        @      ss          s  CsS    S          w         S    s       Ss >       C   s S S      s C  Sa                  C    SCS        a   wS s  a   w    s C w a     aC   s S     a   s  s C   a             C       C   a w  S S        s  a         S S S     a   aCsC s   a   S   w S a         wC   w C|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 742
ace_score 3710
size 742, 1
stairs 513, 0

warrior 447, 0, :east

unit :archer, 11, 0, :east
unit :thick_sludge, 12, 0, :east
unit :captive, 16, 0, :east
unit :archer, 24, 0, :east
unit :thick_sludge, 27, 0, :east
unit :sludge, 31, 0, :east
unit :archer, 33, 0, :east
unit :archer, 34, 0, :east
unit :thick_sludge, 36, 0, :east
unit :captive, 37, 0, :east
unit :wizard, 43, 0, :east
unit :captive, 47, 0, :east
unit :captive, 59, 0, :east
unit :archer, 61, 0, :east
unit :sludge, 62, 0, :east
unit :thick_sludge, 66, 0, :east
unit :thick_sludge, 68, 0, :east
unit :sludge, 70, 0, :east
unit :wizard, 71, 0, :east
unit :archer, 73, 0, :east
unit :captive, 74, 0, :east
unit :archer, 75, 0, :east
unit :captive, 78, 0, :east
unit :sludge, 80, 0, :east
unit :sludge, 82, 0, :east
unit :archer, 87, 0, :east
unit :wizard, 89, 0, :east
unit :wizard, 96, 0, :east
unit :captive, 115, 0, :east
unit :captive, 116, 0, :east
unit :archer, 128, 0, :east
unit :sludge, 131, 0, :east
unit :captive, 136, 0, :east
unit :captive, 139, 0, :east
unit :sludge, 140, 0, :east
unit :wizard, 144, 0, :east
unit :thick_sludge, 146, 0, :east
unit :wizard, 152, 0, :east
unit :archer, 154, 0, :east
unit :wizard, 157, 0, :east
unit :archer, 161, 0, :east
unit :sludge, 164, 0, :east
unit :captive, 169, 0, :east
unit :thick_sludge, 184, 0, :east
unit :captive, 190, 0, :east
unit :thick_sludge, 194, 0, :east
unit :sludge, 199, 0, :east
unit :thick_sludge, 202, 0, :east
unit :archer, 210, 0, :east
unit :thick_sludge, 212, 0, :east
unit :wizard, 215, 0, :east
unit :captive, 219, 0, :east
unit :captive, 220, 0, :east
unit :sludge, 227, 0, :east
unit :captive, 229, 0, :east
unit :sludge, 232, 0, :east
unit :captive, 233, 0, :east
unit :captive, 236, 0, :east
unit :thick_sludge, 237, 0, :east
unit :wizard, 249, 0, :east
unit :thick_sludge, 256, 0, :east
unit :captive, 257, 0, :east
unit :thick_sludge, 268, 0, :east
unit :captive, 269, 0, :east
unit :sludge, 270, 0, :east
unit :sludge, 275, 0, :east
unit :sludge, 276, 0, :east
unit :thick_sludge, 280, 0, :east
unit :sludge, 281, 0, :east
unit :archer, 286, 0, :east
unit :captive, 296, 0, :east
unit :sludge, 298, 0, :east
unit :archer, 299, 0, :east
unit :captive, 301, 0, :east
unit :wizard, 304, 0, :east
unit :archer, 313, 0, :east
unit :wizard, 315, 0, :east
unit :sludge, 319, 0, :east
unit :archer, 321, 0, :east
unit :sludge, 326, 0, :east
unit :archer, 327, 0, :east
unit :wizard, 334, 0, :east
unit :captive, 335, 0, :east
unit :archer, 342, 0, :east
unit :captive, 343, 0, :east
unit :sludge, 347, 0, :east
unit :captive, 359, 0, :east
unit :captive, 366, 0, :east
unit :archer, 369, 0, :east
unit :sludge, 370, 0, :east
unit :captive, 373, 0, :east
unit :wizard, 376, 0, :east
unit :sludge, 380, 0, :east
unit :wizard, 383, 0, :east
unit :thick_sludge, 385, 0, :east
unit :thick_sludge, 388, 0, :east
unit :captive, 394, 0, :east
unit :archer, 396, 0, :east
unit :wizard, 398, 0, :east
unit :wizard, 400, 0, :east
unit :captive, 401, 0, :east
unit :archer, 403, 0, :east
unit :sludge, 406, 0, :east
unit :thick_sludge, 407, 0, :east
unit :wizard, 411, 0, :east
unit :captive, 413, 0, :east
unit :wizard, 415, 0, :east
unit :sludge, 417, 0, :east
unit :thick_sludge, 419, 0, :east
unit :captive, 423, 0, :east
unit :wizard, 426, 0, :east
unit :thick_sludge, 430, 0, :east
unit :captive, 431, 0, :east
unit :thick_sludge, 437, 0, :east
unit :archer, 438, 0, :east
unit :sludge, 454, 0, :west
unit :sludge, 455, 0, :west
unit :sludge, 466, 0, :west
unit :captive, 469, 0, :west
unit :sludge, 470, 0, :west
unit :thick_sludge, 471, 0, :west
unit :thick_sludge, 476, 0, :west
unit :wizard, 487, 0, :west
unit :thick_sludge, 497, 0, :west
unit :sludge, 502, 0, :west
unit :thick_sludge, 510, 0, :west
unit :sludge, 511, 0, :west
unit :captive, 521, 0, :west
unit :sludge, 525, 0, :west
unit :thick_sludge, 527, 0, :west
unit :thick_sludge, 529, 0, :west
unit :sludge, 536, 0, :west
unit :captive, 538, 0, :west
unit :thick_sludge, 541, 0, :west
unit :archer, 542, 0, :west
unit :captive, 561, 0, :west
unit :thick_sludge, 566, 0, :west
unit :captive, 567, 0, :west
unit :thick_sludge, 568, 0, :west
unit :archer, 577, 0, :west
unit :wizard, 581, 0, :west
unit :thick_sludge, 582, 0, :west
unit :sludge, 584, 0, :west
unit :archer, 587, 0, :west
unit :wizard, 591, 0, :west
unit :sludge, 596, 0, :west
unit :captive, 598, 0, :west
unit :wizard, 600, 0, :west
unit :archer, 602, 0, :west
unit :archer, 608, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 613, 0, :west
unit :thick_sludge, 615, 0, :west
unit :archer, 621, 0, :west
unit :sludge, 625, 0, :west
unit :sludge, 628, 0, :west
unit :captive, 630, 0, :west
unit :archer, 634, 0, :west
unit :captive, 648, 0, :west
unit :captive, 656, 0, :west
unit :archer, 660, 0, :west
unit :wizard, 662, 0, :west
unit :thick_sludge, 665, 0, :west
unit :thick_sludge, 667, 0, :west
unit :sludge, 676, 0, :west
unit :archer, 679, 0, :west
unit :thick_sludge, 689, 0, :west
unit :thick_sludge, 691, 0, :west
unit :thick_sludge, 693, 0, :west
unit :archer, 699, 0, :west
unit :archer, 703, 0, :west
unit :captive, 704, 0, :west
unit :sludge, 705, 0, :west
unit :captive, 706, 0, :west
unit :sludge, 708, 0, :west
unit :archer, 712, 0, :west
unit :thick_sludge, 716, 0, :west
unit :wizard, 720, 0, :west
unit :thick_sludge, 722, 0, :west
unit :archer, 724, 0, :west
unit :wizard, 734, 0, :west
unit :captive, 735, 0, :west
unit :wizard, 739, 0, :west
unit :captive, 741, 0, :west
