#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      S a    a  C aC        s      aS a  s  Cw  a         s s S asSC     w         S         s w      aS  w s   C    a     S w                Sa  sC C  Ca   s    C Cw     w C   SC     wa   a C      a CC    S S     s a w     a       w    as  C  ss   a    CC              C       S    wa   C            s S      C  CaC     a s   C  S s       C    w     a  s       Ss   w a w  a     s SC s       a   >wa   w aa  @  w S    a w   S a   a       a ws     s       C           s            s   a     C saa S  SS  C         s  C  w            C               S      SS  a w as  a      S w C a CaCs  s      C     s          aa a     C a                w  C s  C      Cs aSsa  s   C                C   a   S  Sa     s   w     Sa sw              s     S       w       a a        wSa   S   s  a  S      a  s   s  C   a        a       a S   s  C    Cs       a   s Sa  S      s   C   a w   sSw w  s   wS      s  a    S  C  S S   w S  s      wC   a  C      S   |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 944
ace_score 4720
size 944, 1
stairs 397, 0

warrior 409, 0, :east

unit :thick_sludge, 6, 0, :east
unit :archer, 8, 0, :east
unit :archer, 13, 0, :east
unit :captive, 16, 0, :east
unit :archer, 18, 0, :east
unit :captive, 19, 0, :east
unit :sludge, 28, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 36, 0, :east
unit :archer, 38, 0, :east
unit :sludge, 41, 0, :east
unit :captive, 44, 0, :east
unit :wizard, 45, 0, :east
unit :archer, 48, 0, :east
unit :sludge, 58, 0, :east
unit :sludge, 60, 0, :east
unit :thick_sludge, 62, 0, :east
unit :archer, 64, 0, :east
unit :sludge, 65, 0, :east
unit :thick_sludge, 66, 0, :east
unit :captive, 67, 0, :east
unit :wizard, 73, 0, :east
unit :thick_sludge, 83, 0, :east
unit :sludge, 93, 0, :east
unit :wizard, 95, 0, :east
unit :archer, 102, 0, :east
unit :thick_sludge, 103, 0, :east
unit :wizard, 106, 0, :east
unit :sludge, 108, 0, :east
unit :captive, 112, 0, :east
unit :archer, 117, 0, :east
unit :thick_sludge, 123, 0, :east
unit :wizard, 125, 0, :east
unit :thick_sludge, 142, 0, :east
unit :archer, 143, 0, :east
unit :sludge, 146, 0, :east
unit :captive, 147, 0, :east
unit :captive, 149, 0, :east
unit :captive, 152, 0, :east
unit :archer, 153, 0, :east
unit :sludge, 157, 0, :east
unit :captive, 162, 0, :east
unit :captive, 164, 0, :east
unit :wizard, 165, 0, :east
unit :wizard, 171, 0, :east
unit :captive, 173, 0, :east
unit :thick_sludge, 177, 0, :east
unit :captive, 178, 0, :east
unit :wizard, 184, 0, :east
unit :archer, 185, 0, :east
unit :archer, 189, 0, :east
unit :captive, 191, 0, :east
unit :archer, 198, 0, :east
unit :captive, 200, 0, :east
unit :captive, 201, 0, :east
unit :thick_sludge, 206, 0, :east
unit :thick_sludge, 208, 0, :east
unit :sludge, 214, 0, :east
unit :archer, 216, 0, :east
unit :wizard, 218, 0, :east
unit :archer, 224, 0, :east
unit :wizard, 232, 0, :east
unit :archer, 237, 0, :east
unit :sludge, 238, 0, :east
unit :captive, 241, 0, :east
unit :sludge, 244, 0, :east
unit :sludge, 245, 0, :east
unit :archer, 249, 0, :east
unit :captive, 254, 0, :east
unit :captive, 255, 0, :east
unit :captive, 270, 0, :east
unit :thick_sludge, 278, 0, :east
unit :wizard, 283, 0, :east
unit :archer, 284, 0, :east
unit :captive, 288, 0, :east
unit :sludge, 301, 0, :east
unit :thick_sludge, 303, 0, :east
unit :captive, 310, 0, :east
unit :captive, 313, 0, :east
unit :archer, 314, 0, :east
unit :captive, 315, 0, :east
unit :archer, 321, 0, :east
unit :sludge, 323, 0, :east
unit :captive, 327, 0, :east
unit :thick_sludge, 330, 0, :east
unit :sludge, 332, 0, :east
unit :captive, 340, 0, :east
unit :wizard, 345, 0, :east
unit :archer, 351, 0, :east
unit :sludge, 354, 0, :east
unit :thick_sludge, 362, 0, :east
unit :sludge, 363, 0, :east
unit :wizard, 367, 0, :east
unit :archer, 369, 0, :east
unit :wizard, 371, 0, :east
unit :archer, 374, 0, :east
unit :sludge, 380, 0, :east
unit :thick_sludge, 382, 0, :east
unit :captive, 383, 0, :east
unit :sludge, 385, 0, :east
unit :archer, 393, 0, :east
unit :wizard, 398, 0, :east
unit :archer, 399, 0, :east
unit :wizard, 403, 0, :east
unit :archer, 405, 0, :east
unit :archer, 406, 0, :east
unit :wizard, 412, 0, :west
unit :thick_sludge, 414, 0, :west
unit :archer, 419, 0, :west
unit :wizard, 421, 0, :west
unit :thick_sludge, 425, 0, :west
unit :archer, 427, 0, :west
unit :archer, 431, 0, :west
unit :archer, 439, 0, :west
unit :wizard, 441, 0, :west
unit :sludge, 442, 0, :west
unit :sludge, 448, 0, :west
unit :captive, 456, 0, :west
unit :sludge, 468, 0, :west
unit :sludge, 481, 0, :west
unit :archer, 485, 0, :west
unit :captive, 491, 0, :west
unit :sludge, 493, 0, :west
unit :archer, 494, 0, :west
unit :archer, 495, 0, :west
unit :thick_sludge, 497, 0, :west
unit :thick_sludge, 500, 0, :west
unit :thick_sludge, 501, 0, :west
unit :captive, 504, 0, :west
unit :sludge, 514, 0, :west
unit :captive, 517, 0, :west
unit :wizard, 520, 0, :west
unit :captive, 533, 0, :west
unit :thick_sludge, 549, 0, :west
unit :thick_sludge, 556, 0, :west
unit :thick_sludge, 557, 0, :west
unit :archer, 560, 0, :west
unit :wizard, 562, 0, :west
unit :archer, 564, 0, :west
unit :sludge, 565, 0, :west
unit :archer, 568, 0, :west
unit :thick_sludge, 575, 0, :west
unit :wizard, 577, 0, :west
unit :captive, 579, 0, :west
unit :archer, 581, 0, :west
unit :captive, 583, 0, :west
unit :archer, 584, 0, :west
unit :captive, 585, 0, :west
unit :sludge, 586, 0, :west
unit :sludge, 589, 0, :west
unit :captive, 596, 0, :west
unit :sludge, 602, 0, :west
unit :archer, 613, 0, :west
unit :archer, 614, 0, :west
unit :archer, 616, 0, :west
unit :captive, 622, 0, :west
unit :archer, 624, 0, :west
unit :wizard, 641, 0, :west
unit :captive, 644, 0, :west
unit :sludge, 646, 0, :west
unit :captive, 649, 0, :west
unit :captive, 656, 0, :west
unit :sludge, 657, 0, :west
unit :archer, 659, 0, :west
unit :thick_sludge, 660, 0, :west
unit :sludge, 661, 0, :west
unit :archer, 662, 0, :west
unit :sludge, 665, 0, :west
unit :captive, 669, 0, :west
unit :captive, 686, 0, :west
unit :archer, 690, 0, :west
unit :thick_sludge, 694, 0, :west
unit :thick_sludge, 697, 0, :west
unit :archer, 698, 0, :west
unit :sludge, 704, 0, :west
unit :wizard, 708, 0, :west
unit :thick_sludge, 714, 0, :west
unit :archer, 715, 0, :west
unit :sludge, 717, 0, :west
unit :wizard, 718, 0, :west
unit :sludge, 733, 0, :west
unit :thick_sludge, 739, 0, :west
unit :wizard, 747, 0, :west
unit :archer, 755, 0, :west
unit :archer, 757, 0, :west
unit :wizard, 766, 0, :west
unit :thick_sludge, 767, 0, :west
unit :archer, 768, 0, :west
unit :thick_sludge, 772, 0, :west
unit :sludge, 776, 0, :west
unit :archer, 779, 0, :west
unit :thick_sludge, 782, 0, :west
unit :archer, 789, 0, :west
unit :sludge, 792, 0, :west
unit :sludge, 796, 0, :west
unit :captive, 799, 0, :west
unit :archer, 803, 0, :west
unit :archer, 812, 0, :west
unit :archer, 820, 0, :west
unit :thick_sludge, 822, 0, :west
unit :sludge, 826, 0, :west
unit :captive, 829, 0, :west
unit :captive, 834, 0, :west
unit :sludge, 835, 0, :west
unit :archer, 843, 0, :west
unit :sludge, 847, 0, :west
unit :thick_sludge, 849, 0, :west
unit :archer, 850, 0, :west
unit :thick_sludge, 853, 0, :west
unit :sludge, 860, 0, :west
unit :captive, 864, 0, :west
unit :archer, 868, 0, :west
unit :wizard, 870, 0, :west
unit :sludge, 874, 0, :west
unit :thick_sludge, 875, 0, :west
unit :wizard, 876, 0, :west
unit :wizard, 878, 0, :west
unit :sludge, 881, 0, :west
unit :wizard, 885, 0, :west
unit :thick_sludge, 886, 0, :west
unit :sludge, 893, 0, :west
unit :archer, 896, 0, :west
unit :thick_sludge, 901, 0, :west
unit :captive, 904, 0, :west
unit :thick_sludge, 907, 0, :west
unit :thick_sludge, 909, 0, :west
unit :wizard, 913, 0, :west
unit :thick_sludge, 915, 0, :west
unit :sludge, 918, 0, :west
unit :wizard, 925, 0, :west
unit :captive, 926, 0, :west
unit :archer, 930, 0, :west
unit :captive, 933, 0, :west
unit :thick_sludge, 940, 0, :west
