#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   S w   s S   s a  S   SSS    s       aCS  C       SC S         SC  CS a    s      a       C SS   S    as S CC  w    C  w   a     Sa aS    w  C        C w   s        S   CC   CaS  w     S    S   C          s    Cs  a      S   CS   S       C  w          s a           Ca        S C      C Ss w  s          a       s  S       S    w sC     w         a aS> C     @    w      wC S  S      a   w      S S  C  w   sa C  sC w        a       S     w w  a  w        s  s    a w w    s  wC     Ss    aC  C w   CS      C           s  S          s w    C  s a             a    w   a      aS          C          S  S          s           s  Sa   sws S   s   SC          s w  a    S      Ca    w            s   S S           S  S    w         C  S         s  a    s  as     S            a    Swa   S   aS      s   w C aCCwC    CC      w sw    C       w s aa   Ca  SaC  s  S      C C    w  S           a CS          a    Cs    aS SSC   S     CaSCwS C       w aa      S  s  C a     s  a sa   w       S   S a   |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 995
ace_score 4975
size 995, 1
stairs 353, 0

warrior 361, 0, :east

unit :thick_sludge, 3, 0, :east
unit :wizard, 5, 0, :east
unit :sludge, 9, 0, :east
unit :thick_sludge, 11, 0, :east
unit :sludge, 15, 0, :east
unit :archer, 17, 0, :east
unit :thick_sludge, 20, 0, :east
unit :thick_sludge, 24, 0, :east
unit :thick_sludge, 25, 0, :east
unit :thick_sludge, 26, 0, :east
unit :sludge, 31, 0, :east
unit :archer, 39, 0, :east
unit :captive, 40, 0, :east
unit :thick_sludge, 41, 0, :east
unit :captive, 44, 0, :east
unit :thick_sludge, 52, 0, :east
unit :captive, 53, 0, :east
unit :thick_sludge, 55, 0, :east
unit :thick_sludge, 65, 0, :east
unit :captive, 66, 0, :east
unit :captive, 69, 0, :east
unit :thick_sludge, 70, 0, :east
unit :archer, 72, 0, :east
unit :sludge, 77, 0, :east
unit :archer, 84, 0, :east
unit :captive, 92, 0, :east
unit :thick_sludge, 94, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 99, 0, :east
unit :archer, 104, 0, :east
unit :sludge, 105, 0, :east
unit :thick_sludge, 107, 0, :east
unit :captive, 109, 0, :east
unit :captive, 110, 0, :east
unit :wizard, 113, 0, :east
unit :captive, 118, 0, :east
unit :wizard, 121, 0, :east
unit :archer, 125, 0, :east
unit :thick_sludge, 131, 0, :east
unit :archer, 132, 0, :east
unit :archer, 134, 0, :east
unit :thick_sludge, 135, 0, :east
unit :wizard, 140, 0, :east
unit :captive, 143, 0, :east
unit :captive, 152, 0, :east
unit :wizard, 154, 0, :east
unit :sludge, 158, 0, :east
unit :thick_sludge, 167, 0, :east
unit :captive, 171, 0, :east
unit :captive, 172, 0, :east
unit :captive, 176, 0, :east
unit :archer, 177, 0, :east
unit :thick_sludge, 178, 0, :east
unit :wizard, 181, 0, :east
unit :thick_sludge, 187, 0, :east
unit :thick_sludge, 192, 0, :east
unit :captive, 196, 0, :east
unit :sludge, 207, 0, :east
unit :captive, 212, 0, :east
unit :sludge, 213, 0, :east
unit :archer, 216, 0, :east
unit :thick_sludge, 223, 0, :east
unit :captive, 227, 0, :east
unit :thick_sludge, 228, 0, :east
unit :thick_sludge, 232, 0, :east
unit :captive, 240, 0, :east
unit :wizard, 243, 0, :east
unit :sludge, 254, 0, :east
unit :archer, 256, 0, :east
unit :captive, 268, 0, :east
unit :archer, 269, 0, :east
unit :thick_sludge, 278, 0, :east
unit :captive, 280, 0, :east
unit :captive, 287, 0, :east
unit :thick_sludge, 289, 0, :east
unit :sludge, 290, 0, :east
unit :wizard, 292, 0, :east
unit :sludge, 295, 0, :east
unit :archer, 306, 0, :east
unit :sludge, 314, 0, :east
unit :thick_sludge, 317, 0, :east
unit :thick_sludge, 325, 0, :east
unit :wizard, 330, 0, :east
unit :sludge, 332, 0, :east
unit :captive, 333, 0, :east
unit :wizard, 339, 0, :east
unit :archer, 349, 0, :east
unit :archer, 351, 0, :east
unit :thick_sludge, 352, 0, :east
unit :captive, 355, 0, :east
unit :wizard, 366, 0, :west
unit :wizard, 373, 0, :west
unit :captive, 374, 0, :west
unit :thick_sludge, 376, 0, :west
unit :thick_sludge, 379, 0, :west
unit :archer, 386, 0, :west
unit :wizard, 390, 0, :west
unit :thick_sludge, 397, 0, :west
unit :thick_sludge, 399, 0, :west
unit :captive, 402, 0, :west
unit :wizard, 405, 0, :west
unit :sludge, 409, 0, :west
unit :archer, 410, 0, :west
unit :captive, 412, 0, :west
unit :sludge, 415, 0, :west
unit :captive, 416, 0, :west
unit :wizard, 418, 0, :west
unit :archer, 427, 0, :west
unit :thick_sludge, 435, 0, :west
unit :wizard, 441, 0, :west
unit :wizard, 443, 0, :west
unit :archer, 446, 0, :west
unit :wizard, 449, 0, :west
unit :sludge, 458, 0, :west
unit :sludge, 461, 0, :west
unit :archer, 466, 0, :west
unit :wizard, 468, 0, :west
unit :wizard, 470, 0, :west
unit :sludge, 475, 0, :west
unit :wizard, 478, 0, :west
unit :captive, 479, 0, :west
unit :thick_sludge, 485, 0, :west
unit :sludge, 486, 0, :west
unit :archer, 491, 0, :west
unit :captive, 492, 0, :west
unit :captive, 495, 0, :west
unit :wizard, 497, 0, :west
unit :captive, 501, 0, :west
unit :thick_sludge, 502, 0, :west
unit :captive, 509, 0, :west
unit :sludge, 521, 0, :west
unit :thick_sludge, 524, 0, :west
unit :sludge, 535, 0, :west
unit :wizard, 537, 0, :west
unit :captive, 542, 0, :west
unit :sludge, 545, 0, :west
unit :archer, 547, 0, :west
unit :archer, 561, 0, :west
unit :wizard, 566, 0, :west
unit :archer, 570, 0, :west
unit :archer, 577, 0, :west
unit :thick_sludge, 578, 0, :west
unit :captive, 589, 0, :west
unit :thick_sludge, 600, 0, :west
unit :thick_sludge, 603, 0, :west
unit :sludge, 614, 0, :west
unit :sludge, 626, 0, :west
unit :thick_sludge, 629, 0, :west
unit :archer, 630, 0, :west
unit :sludge, 634, 0, :west
unit :wizard, 635, 0, :west
unit :sludge, 636, 0, :west
unit :thick_sludge, 638, 0, :west
unit :sludge, 642, 0, :west
unit :thick_sludge, 646, 0, :west
unit :captive, 647, 0, :west
unit :sludge, 658, 0, :west
unit :wizard, 660, 0, :west
unit :archer, 663, 0, :west
unit :thick_sludge, 668, 0, :west
unit :captive, 675, 0, :west
unit :archer, 676, 0, :west
unit :wizard, 681, 0, :west
unit :sludge, 694, 0, :west
unit :thick_sludge, 698, 0, :west
unit :thick_sludge, 700, 0, :west
unit :thick_sludge, 712, 0, :west
unit :thick_sludge, 715, 0, :west
unit :wizard, 720, 0, :west
unit :captive, 730, 0, :west
unit :thick_sludge, 733, 0, :west
unit :sludge, 743, 0, :west
unit :archer, 746, 0, :west
unit :sludge, 751, 0, :west
unit :archer, 754, 0, :west
unit :sludge, 755, 0, :west
unit :thick_sludge, 761, 0, :west
unit :archer, 774, 0, :west
unit :thick_sludge, 779, 0, :west
unit :wizard, 780, 0, :west
unit :archer, 781, 0, :west
unit :thick_sludge, 785, 0, :west
unit :archer, 789, 0, :west
unit :thick_sludge, 790, 0, :west
unit :sludge, 797, 0, :west
unit :wizard, 801, 0, :west
unit :captive, 803, 0, :west
unit :archer, 805, 0, :west
unit :captive, 806, 0, :west
unit :captive, 807, 0, :west
unit :wizard, 808, 0, :west
unit :captive, 809, 0, :west
unit :captive, 814, 0, :west
unit :captive, 815, 0, :west
unit :wizard, 822, 0, :west
unit :sludge, 824, 0, :west
unit :wizard, 825, 0, :west
unit :captive, 830, 0, :west
unit :wizard, 838, 0, :west
unit :sludge, 840, 0, :west
unit :archer, 842, 0, :west
unit :archer, 843, 0, :west
unit :captive, 847, 0, :west
unit :archer, 848, 0, :west
unit :thick_sludge, 851, 0, :west
unit :archer, 852, 0, :west
unit :captive, 853, 0, :west
unit :sludge, 856, 0, :west
unit :thick_sludge, 859, 0, :west
unit :captive, 866, 0, :west
unit :captive, 868, 0, :west
unit :wizard, 873, 0, :west
unit :thick_sludge, 876, 0, :west
unit :archer, 888, 0, :west
unit :captive, 890, 0, :west
unit :thick_sludge, 891, 0, :west
unit :archer, 902, 0, :west
unit :captive, 907, 0, :west
unit :sludge, 908, 0, :west
unit :archer, 913, 0, :west
unit :thick_sludge, 914, 0, :west
unit :thick_sludge, 916, 0, :west
unit :thick_sludge, 917, 0, :west
unit :captive, 918, 0, :west
unit :thick_sludge, 922, 0, :west
unit :captive, 928, 0, :west
unit :archer, 929, 0, :west
unit :thick_sludge, 930, 0, :west
unit :captive, 931, 0, :west
unit :wizard, 932, 0, :west
unit :thick_sludge, 933, 0, :west
unit :captive, 935, 0, :west
unit :wizard, 943, 0, :west
unit :archer, 945, 0, :west
unit :archer, 946, 0, :west
unit :thick_sludge, 953, 0, :west
unit :sludge, 956, 0, :west
unit :captive, 959, 0, :west
unit :archer, 961, 0, :west
unit :sludge, 967, 0, :west
unit :archer, 970, 0, :west
unit :sludge, 972, 0, :west
unit :archer, 973, 0, :west
unit :wizard, 977, 0, :west
unit :thick_sludge, 985, 0, :west
unit :thick_sludge, 989, 0, :west
unit :archer, 991, 0, :west
