#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w             a    S       S    w   a   w C w           w a S Sa  a   S aS    s       a   s     a      CC     a Sa    w a w        a    C   C  CS a    S                   sC a   ws w  >  S s s   s  C     C  s   ss     w   w      as   a   CaC   w a     w        S   S  S     C a           S    sCCC    SC      S s      S   C  w  S       s       CC S  S  C   as       s         S   w    @  C   w      S         S     Ca sSC a      Sw      aa wC    S   s  S       S CSa sS w w       S   s  C C       s  S   a s       w s       s    a a  s   a    a sS   s  SCa  w s        S s                 ws       sS    a           aa   aC   SC    a      S S |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 643
ace_score 3215
size 643, 1
stairs 184, 0

warrior 385, 0, :east

unit :wizard, 0, 0, :east
unit :archer, 14, 0, :east
unit :thick_sludge, 19, 0, :east
unit :thick_sludge, 27, 0, :east
unit :wizard, 32, 0, :east
unit :archer, 36, 0, :east
unit :wizard, 40, 0, :east
unit :captive, 42, 0, :east
unit :wizard, 44, 0, :east
unit :wizard, 56, 0, :east
unit :archer, 58, 0, :east
unit :thick_sludge, 60, 0, :east
unit :thick_sludge, 62, 0, :east
unit :archer, 63, 0, :east
unit :archer, 66, 0, :east
unit :thick_sludge, 70, 0, :east
unit :archer, 72, 0, :east
unit :thick_sludge, 73, 0, :east
unit :sludge, 78, 0, :east
unit :archer, 86, 0, :east
unit :sludge, 90, 0, :east
unit :archer, 96, 0, :east
unit :captive, 103, 0, :east
unit :captive, 104, 0, :east
unit :archer, 110, 0, :east
unit :thick_sludge, 112, 0, :east
unit :archer, 113, 0, :east
unit :wizard, 118, 0, :east
unit :archer, 120, 0, :east
unit :wizard, 122, 0, :east
unit :archer, 131, 0, :east
unit :captive, 136, 0, :east
unit :captive, 140, 0, :east
unit :captive, 143, 0, :east
unit :thick_sludge, 144, 0, :east
unit :archer, 146, 0, :east
unit :thick_sludge, 151, 0, :east
unit :sludge, 171, 0, :east
unit :captive, 172, 0, :east
unit :archer, 174, 0, :east
unit :wizard, 178, 0, :east
unit :sludge, 179, 0, :east
unit :wizard, 181, 0, :east
unit :thick_sludge, 187, 0, :east
unit :sludge, 189, 0, :east
unit :sludge, 191, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 198, 0, :east
unit :captive, 204, 0, :east
unit :sludge, 207, 0, :east
unit :sludge, 211, 0, :east
unit :sludge, 212, 0, :east
unit :wizard, 218, 0, :east
unit :wizard, 222, 0, :east
unit :archer, 229, 0, :east
unit :sludge, 230, 0, :east
unit :archer, 234, 0, :east
unit :captive, 238, 0, :east
unit :archer, 239, 0, :east
unit :captive, 240, 0, :east
unit :wizard, 244, 0, :east
unit :archer, 246, 0, :east
unit :wizard, 252, 0, :east
unit :thick_sludge, 261, 0, :east
unit :thick_sludge, 265, 0, :east
unit :thick_sludge, 268, 0, :east
unit :captive, 274, 0, :east
unit :archer, 276, 0, :east
unit :thick_sludge, 288, 0, :east
unit :sludge, 293, 0, :east
unit :captive, 294, 0, :east
unit :captive, 295, 0, :east
unit :captive, 296, 0, :east
unit :thick_sludge, 301, 0, :east
unit :captive, 302, 0, :east
unit :thick_sludge, 309, 0, :east
unit :sludge, 311, 0, :east
unit :thick_sludge, 318, 0, :east
unit :captive, 322, 0, :east
unit :wizard, 325, 0, :east
unit :thick_sludge, 328, 0, :east
unit :sludge, 336, 0, :east
unit :captive, 344, 0, :east
unit :captive, 345, 0, :east
unit :thick_sludge, 347, 0, :east
unit :thick_sludge, 350, 0, :east
unit :captive, 353, 0, :east
unit :archer, 357, 0, :east
unit :sludge, 358, 0, :east
unit :sludge, 366, 0, :east
unit :thick_sludge, 376, 0, :east
unit :wizard, 380, 0, :east
unit :captive, 388, 0, :west
unit :wizard, 392, 0, :west
unit :thick_sludge, 399, 0, :west
unit :thick_sludge, 409, 0, :west
unit :captive, 415, 0, :west
unit :archer, 416, 0, :west
unit :sludge, 418, 0, :west
unit :thick_sludge, 419, 0, :west
unit :captive, 420, 0, :west
unit :archer, 422, 0, :west
unit :thick_sludge, 429, 0, :west
unit :wizard, 430, 0, :west
unit :archer, 437, 0, :west
unit :archer, 438, 0, :west
unit :wizard, 440, 0, :west
unit :captive, 441, 0, :west
unit :thick_sludge, 446, 0, :west
unit :sludge, 450, 0, :west
unit :thick_sludge, 453, 0, :west
unit :thick_sludge, 461, 0, :west
unit :captive, 463, 0, :west
unit :thick_sludge, 464, 0, :west
unit :archer, 465, 0, :west
unit :sludge, 467, 0, :west
unit :thick_sludge, 468, 0, :west
unit :wizard, 470, 0, :west
unit :wizard, 472, 0, :west
unit :thick_sludge, 480, 0, :west
unit :sludge, 484, 0, :west
unit :captive, 487, 0, :west
unit :captive, 489, 0, :west
unit :sludge, 497, 0, :west
unit :thick_sludge, 500, 0, :west
unit :archer, 504, 0, :west
unit :sludge, 506, 0, :west
unit :wizard, 514, 0, :west
unit :sludge, 516, 0, :west
unit :sludge, 524, 0, :west
unit :archer, 529, 0, :west
unit :archer, 531, 0, :west
unit :sludge, 534, 0, :west
unit :archer, 538, 0, :west
unit :archer, 543, 0, :west
unit :sludge, 545, 0, :west
unit :thick_sludge, 546, 0, :west
unit :sludge, 550, 0, :west
unit :thick_sludge, 553, 0, :west
unit :captive, 554, 0, :west
unit :archer, 555, 0, :west
unit :wizard, 558, 0, :west
unit :sludge, 560, 0, :west
unit :thick_sludge, 569, 0, :west
unit :sludge, 571, 0, :west
unit :wizard, 589, 0, :west
unit :sludge, 590, 0, :west
unit :sludge, 598, 0, :west
unit :thick_sludge, 599, 0, :west
unit :archer, 604, 0, :west
unit :archer, 616, 0, :west
unit :archer, 617, 0, :west
unit :archer, 621, 0, :west
unit :captive, 622, 0, :west
unit :thick_sludge, 626, 0, :west
unit :captive, 627, 0, :west
unit :archer, 632, 0, :west
unit :thick_sludge, 639, 0, :west
unit :thick_sludge, 641, 0, :west
