#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C           sSa    w            a    S    CSSw S C   sws    S        S sS   a     C aw aS CS    a S   aS   s       a S     sa       s    w   a         > S      as  w   s  C  C  S  C    S   C              s        Ss             SS    C        s w s    ss            C  SC    a a w C   Ca   SC     @  wC       CS  s   s        s     a  sS    aS  s  a a     w      s    w        sC    S      s      sa   S     w      C S   a  a w S sw    aC       CSC    a   s      sw        sCS                  w       C    S a   a    S   saC   w   C  w    Ca  a   aas    C             S    w   aa    s   C    s  C s     s   CC  s   ss S S C           C S  a |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 642
ace_score 3210
size 642, 1
stairs 151, 0

warrior 297, 0, :east

unit :captive, 0, 0, :east
unit :sludge, 12, 0, :east
unit :thick_sludge, 13, 0, :east
unit :archer, 14, 0, :east
unit :wizard, 19, 0, :east
unit :archer, 32, 0, :east
unit :thick_sludge, 37, 0, :east
unit :captive, 42, 0, :east
unit :thick_sludge, 43, 0, :east
unit :thick_sludge, 44, 0, :east
unit :wizard, 45, 0, :east
unit :thick_sludge, 47, 0, :east
unit :captive, 49, 0, :east
unit :sludge, 53, 0, :east
unit :wizard, 54, 0, :east
unit :sludge, 55, 0, :east
unit :thick_sludge, 60, 0, :east
unit :thick_sludge, 69, 0, :east
unit :sludge, 71, 0, :east
unit :thick_sludge, 72, 0, :east
unit :archer, 76, 0, :east
unit :captive, 82, 0, :east
unit :archer, 84, 0, :east
unit :wizard, 85, 0, :east
unit :archer, 87, 0, :east
unit :thick_sludge, 88, 0, :east
unit :captive, 90, 0, :east
unit :thick_sludge, 91, 0, :east
unit :archer, 96, 0, :east
unit :thick_sludge, 98, 0, :east
unit :archer, 102, 0, :east
unit :thick_sludge, 103, 0, :east
unit :sludge, 107, 0, :east
unit :archer, 115, 0, :east
unit :thick_sludge, 117, 0, :east
unit :sludge, 123, 0, :east
unit :archer, 124, 0, :east
unit :sludge, 132, 0, :east
unit :wizard, 137, 0, :east
unit :archer, 141, 0, :east
unit :thick_sludge, 153, 0, :east
unit :archer, 160, 0, :east
unit :sludge, 161, 0, :east
unit :wizard, 164, 0, :east
unit :sludge, 168, 0, :east
unit :captive, 171, 0, :east
unit :captive, 174, 0, :east
unit :thick_sludge, 177, 0, :east
unit :captive, 180, 0, :east
unit :thick_sludge, 185, 0, :east
unit :captive, 189, 0, :east
unit :sludge, 204, 0, :east
unit :thick_sludge, 213, 0, :east
unit :sludge, 214, 0, :east
unit :thick_sludge, 228, 0, :east
unit :thick_sludge, 229, 0, :east
unit :captive, 234, 0, :east
unit :sludge, 243, 0, :east
unit :wizard, 245, 0, :east
unit :sludge, 247, 0, :east
unit :sludge, 252, 0, :east
unit :sludge, 253, 0, :east
unit :captive, 266, 0, :east
unit :thick_sludge, 269, 0, :east
unit :captive, 270, 0, :east
unit :archer, 275, 0, :east
unit :archer, 277, 0, :east
unit :wizard, 279, 0, :east
unit :captive, 281, 0, :east
unit :captive, 285, 0, :east
unit :archer, 286, 0, :east
unit :thick_sludge, 290, 0, :east
unit :captive, 291, 0, :east
unit :wizard, 300, 0, :west
unit :captive, 301, 0, :west
unit :captive, 309, 0, :west
unit :thick_sludge, 310, 0, :west
unit :sludge, 313, 0, :west
unit :sludge, 317, 0, :west
unit :sludge, 326, 0, :west
unit :archer, 332, 0, :west
unit :sludge, 335, 0, :west
unit :thick_sludge, 336, 0, :west
unit :archer, 341, 0, :west
unit :thick_sludge, 342, 0, :west
unit :sludge, 345, 0, :west
unit :archer, 348, 0, :west
unit :archer, 350, 0, :west
unit :wizard, 356, 0, :west
unit :sludge, 363, 0, :west
unit :wizard, 368, 0, :west
unit :sludge, 377, 0, :west
unit :captive, 378, 0, :west
unit :thick_sludge, 383, 0, :west
unit :sludge, 390, 0, :west
unit :sludge, 397, 0, :west
unit :archer, 398, 0, :west
unit :thick_sludge, 402, 0, :west
unit :wizard, 408, 0, :west
unit :captive, 415, 0, :west
unit :thick_sludge, 417, 0, :west
unit :archer, 421, 0, :west
unit :archer, 424, 0, :west
unit :wizard, 426, 0, :west
unit :thick_sludge, 428, 0, :west
unit :sludge, 430, 0, :west
unit :wizard, 431, 0, :west
unit :archer, 436, 0, :west
unit :captive, 437, 0, :west
unit :captive, 445, 0, :west
unit :thick_sludge, 446, 0, :west
unit :captive, 447, 0, :west
unit :archer, 452, 0, :west
unit :sludge, 456, 0, :west
unit :sludge, 463, 0, :west
unit :wizard, 464, 0, :west
unit :sludge, 473, 0, :west
unit :captive, 474, 0, :west
unit :thick_sludge, 475, 0, :west
unit :wizard, 494, 0, :west
unit :captive, 502, 0, :west
unit :thick_sludge, 507, 0, :west
unit :archer, 509, 0, :west
unit :archer, 513, 0, :west
unit :thick_sludge, 518, 0, :west
unit :sludge, 522, 0, :west
unit :archer, 523, 0, :west
unit :captive, 524, 0, :west
unit :wizard, 528, 0, :west
unit :captive, 532, 0, :west
unit :wizard, 535, 0, :west
unit :captive, 540, 0, :west
unit :archer, 541, 0, :west
unit :archer, 544, 0, :west
unit :archer, 548, 0, :west
unit :archer, 549, 0, :west
unit :sludge, 550, 0, :west
unit :captive, 555, 0, :west
unit :thick_sludge, 569, 0, :west
unit :wizard, 574, 0, :west
unit :archer, 578, 0, :west
unit :archer, 579, 0, :west
unit :sludge, 584, 0, :west
unit :captive, 588, 0, :west
unit :sludge, 593, 0, :west
unit :captive, 596, 0, :west
unit :sludge, 598, 0, :west
unit :sludge, 604, 0, :west
unit :captive, 608, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 612, 0, :west
unit :sludge, 616, 0, :west
unit :sludge, 617, 0, :west
unit :thick_sludge, 619, 0, :west
unit :thick_sludge, 621, 0, :west
unit :captive, 623, 0, :west
unit :captive, 635, 0, :west
unit :thick_sludge, 637, 0, :west
unit :archer, 640, 0, :west
