#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   a   w         C              S  CC s                   s  C C    s a      SswS  w      aCC    s  SC    C     a     SS  w   C w   C    w    a   w  C      s   C   S     s  s  s    S s       w C   s          S    a            wa   s         s  swC w  w                 S  ss  s         aSC     sa   S C     aC a        C  Cw  s s  sa     a w s s     w       S S              sS   S         S a    @   CC  aS   s    s  S   S             ss   S   a s Cw     aS     w Ca   w    C  a      CCssa                      w        s  w  S            aw S     w  s             s    Sa sss  aw C         s w S   sC    >Cas s   wa           wC s aS   C  S   a  s     w  a    S       C w     s Sw  as    S s ssC  C    S S a     a  SS  S sS  S  wa S    as   sC       s  a  s s     C      s    C     Cs        a    C  s       aw     Ss C             w C     S  w w   sC  s   CC   a      S C  s   S         ssaC             s |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 909
ace_score 4545
size 909, 1
stairs 606, 0

warrior 397, 0, :east

unit :archer, 3, 0, :east
unit :wizard, 7, 0, :east
unit :captive, 17, 0, :east
unit :thick_sludge, 32, 0, :east
unit :captive, 35, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 38, 0, :east
unit :sludge, 58, 0, :east
unit :captive, 61, 0, :east
unit :captive, 63, 0, :east
unit :sludge, 68, 0, :east
unit :archer, 70, 0, :east
unit :thick_sludge, 77, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 79, 0, :east
unit :thick_sludge, 80, 0, :east
unit :wizard, 83, 0, :east
unit :archer, 90, 0, :east
unit :captive, 91, 0, :east
unit :captive, 92, 0, :east
unit :sludge, 97, 0, :east
unit :thick_sludge, 100, 0, :east
unit :captive, 101, 0, :east
unit :captive, 106, 0, :east
unit :archer, 112, 0, :east
unit :thick_sludge, 118, 0, :east
unit :thick_sludge, 119, 0, :east
unit :wizard, 122, 0, :east
unit :captive, 126, 0, :east
unit :wizard, 128, 0, :east
unit :captive, 132, 0, :east
unit :wizard, 137, 0, :east
unit :archer, 142, 0, :east
unit :wizard, 146, 0, :east
unit :captive, 149, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 160, 0, :east
unit :thick_sludge, 164, 0, :east
unit :sludge, 170, 0, :east
unit :sludge, 173, 0, :east
unit :sludge, 176, 0, :east
unit :thick_sludge, 181, 0, :east
unit :sludge, 183, 0, :east
unit :wizard, 191, 0, :east
unit :captive, 193, 0, :east
unit :sludge, 197, 0, :east
unit :thick_sludge, 208, 0, :east
unit :archer, 213, 0, :east
unit :wizard, 226, 0, :east
unit :archer, 227, 0, :east
unit :sludge, 231, 0, :east
unit :sludge, 241, 0, :east
unit :sludge, 244, 0, :east
unit :wizard, 245, 0, :east
unit :captive, 246, 0, :east
unit :wizard, 248, 0, :east
unit :wizard, 251, 0, :east
unit :thick_sludge, 269, 0, :east
unit :sludge, 272, 0, :east
unit :sludge, 273, 0, :east
unit :sludge, 276, 0, :east
unit :archer, 286, 0, :east
unit :thick_sludge, 287, 0, :east
unit :captive, 288, 0, :east
unit :sludge, 294, 0, :east
unit :archer, 295, 0, :east
unit :thick_sludge, 299, 0, :east
unit :captive, 301, 0, :east
unit :archer, 307, 0, :east
unit :captive, 308, 0, :east
unit :archer, 310, 0, :east
unit :captive, 319, 0, :east
unit :captive, 322, 0, :east
unit :wizard, 323, 0, :east
unit :sludge, 326, 0, :east
unit :sludge, 328, 0, :east
unit :sludge, 331, 0, :east
unit :archer, 332, 0, :east
unit :archer, 338, 0, :east
unit :wizard, 340, 0, :east
unit :sludge, 342, 0, :east
unit :sludge, 344, 0, :east
unit :wizard, 350, 0, :east
unit :thick_sludge, 358, 0, :east
unit :thick_sludge, 360, 0, :east
unit :sludge, 375, 0, :east
unit :thick_sludge, 376, 0, :east
unit :thick_sludge, 380, 0, :east
unit :thick_sludge, 390, 0, :east
unit :archer, 392, 0, :east
unit :captive, 401, 0, :west
unit :captive, 402, 0, :west
unit :archer, 405, 0, :west
unit :thick_sludge, 406, 0, :west
unit :sludge, 410, 0, :west
unit :sludge, 415, 0, :west
unit :thick_sludge, 418, 0, :west
unit :thick_sludge, 422, 0, :west
unit :sludge, 436, 0, :west
unit :sludge, 437, 0, :west
unit :thick_sludge, 441, 0, :west
unit :archer, 445, 0, :west
unit :sludge, 447, 0, :west
unit :captive, 449, 0, :west
unit :wizard, 450, 0, :west
unit :archer, 456, 0, :west
unit :thick_sludge, 457, 0, :west
unit :wizard, 463, 0, :west
unit :captive, 465, 0, :west
unit :archer, 466, 0, :west
unit :wizard, 470, 0, :west
unit :captive, 475, 0, :west
unit :archer, 478, 0, :west
unit :captive, 485, 0, :west
unit :captive, 486, 0, :west
unit :sludge, 487, 0, :west
unit :sludge, 488, 0, :west
unit :archer, 489, 0, :west
unit :wizard, 512, 0, :west
unit :sludge, 521, 0, :west
unit :wizard, 524, 0, :west
unit :thick_sludge, 527, 0, :west
unit :archer, 540, 0, :west
unit :wizard, 541, 0, :west
unit :thick_sludge, 543, 0, :west
unit :wizard, 549, 0, :west
unit :sludge, 552, 0, :west
unit :sludge, 566, 0, :west
unit :thick_sludge, 571, 0, :west
unit :archer, 572, 0, :west
unit :sludge, 574, 0, :west
unit :sludge, 575, 0, :west
unit :sludge, 576, 0, :west
unit :archer, 579, 0, :west
unit :wizard, 580, 0, :west
unit :captive, 582, 0, :west
unit :sludge, 592, 0, :west
unit :wizard, 594, 0, :west
unit :thick_sludge, 596, 0, :west
unit :sludge, 600, 0, :west
unit :captive, 601, 0, :west
unit :captive, 607, 0, :west
unit :archer, 608, 0, :west
unit :sludge, 609, 0, :west
unit :sludge, 611, 0, :west
unit :wizard, 615, 0, :west
unit :archer, 616, 0, :west
unit :wizard, 628, 0, :west
unit :captive, 629, 0, :west
unit :sludge, 631, 0, :west
unit :archer, 633, 0, :west
unit :thick_sludge, 634, 0, :west
unit :captive, 638, 0, :west
unit :thick_sludge, 641, 0, :west
unit :archer, 645, 0, :west
unit :sludge, 648, 0, :west
unit :wizard, 654, 0, :west
unit :archer, 657, 0, :west
unit :thick_sludge, 662, 0, :west
unit :captive, 670, 0, :west
unit :wizard, 672, 0, :west
unit :sludge, 678, 0, :west
unit :thick_sludge, 680, 0, :west
unit :wizard, 681, 0, :west
unit :archer, 684, 0, :west
unit :sludge, 685, 0, :west
unit :thick_sludge, 690, 0, :west
unit :sludge, 692, 0, :west
unit :sludge, 694, 0, :west
unit :sludge, 695, 0, :west
unit :captive, 696, 0, :west
unit :captive, 699, 0, :west
unit :thick_sludge, 704, 0, :west
unit :thick_sludge, 706, 0, :west
unit :archer, 708, 0, :west
unit :archer, 714, 0, :west
unit :thick_sludge, 717, 0, :west
unit :thick_sludge, 718, 0, :west
unit :thick_sludge, 721, 0, :west
unit :sludge, 723, 0, :west
unit :thick_sludge, 724, 0, :west
unit :thick_sludge, 727, 0, :west
unit :wizard, 730, 0, :west
unit :archer, 731, 0, :west
unit :thick_sludge, 733, 0, :west
unit :archer, 738, 0, :west
unit :sludge, 739, 0, :west
unit :sludge, 743, 0, :west
unit :captive, 744, 0, :west
unit :sludge, 752, 0, :west
unit :archer, 755, 0, :west
unit :sludge, 758, 0, :west
unit :sludge, 760, 0, :west
unit :captive, 766, 0, :west
unit :sludge, 773, 0, :west
unit :captive, 778, 0, :west
unit :captive, 784, 0, :west
unit :sludge, 785, 0, :west
unit :archer, 794, 0, :west
unit :captive, 799, 0, :west
unit :sludge, 802, 0, :west
unit :archer, 810, 0, :west
unit :wizard, 811, 0, :west
unit :thick_sludge, 817, 0, :west
unit :sludge, 818, 0, :west
unit :captive, 820, 0, :west
unit :wizard, 834, 0, :west
unit :captive, 836, 0, :west
unit :thick_sludge, 842, 0, :west
unit :wizard, 845, 0, :west
unit :wizard, 847, 0, :west
unit :sludge, 851, 0, :west
unit :captive, 852, 0, :west
unit :sludge, 855, 0, :west
unit :captive, 859, 0, :west
unit :captive, 860, 0, :west
unit :archer, 864, 0, :west
unit :thick_sludge, 871, 0, :west
unit :captive, 873, 0, :west
unit :sludge, 876, 0, :west
unit :thick_sludge, 880, 0, :west
unit :sludge, 890, 0, :west
unit :sludge, 891, 0, :west
unit :archer, 892, 0, :west
unit :captive, 893, 0, :west
unit :sludge, 907, 0, :west
