#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    a              wS         w   C aSs a    w   s C S   w C    S    w   s C s S    s    wC sC            w S         w  @  ws    >   S s   aCa         Cs  S  SCS   S    SC     S        S      a       w s     w  C         s     wsw            s          s       w  CC    a w  Cw a Ca  w       Ss C a          a     C s    a C      sSa     a     s C   s  a    C    C                w    a    C      s                 S  CS    aa          C w a   a       S   a s w        C   S  a  SC     a     C a s      S    C    a         w S as  w     C  s     SC S s  w   a     S  sCw  w     wa S    a   a a   S   S   s a   wC   S  s     a  wC   a    C   C  a            s   SC  asa a  s         CC   w s SC w aS  S   s C |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 709
ace_score 3545
size 709, 1
stairs 130, 0

warrior 121, 0, :east

unit :archer, 4, 0, :east
unit :wizard, 19, 0, :east
unit :thick_sludge, 20, 0, :east
unit :wizard, 30, 0, :east
unit :captive, 34, 0, :east
unit :archer, 36, 0, :east
unit :thick_sludge, 37, 0, :east
unit :sludge, 38, 0, :east
unit :archer, 40, 0, :east
unit :wizard, 45, 0, :east
unit :sludge, 49, 0, :east
unit :captive, 51, 0, :east
unit :thick_sludge, 53, 0, :east
unit :wizard, 57, 0, :east
unit :captive, 59, 0, :east
unit :thick_sludge, 64, 0, :east
unit :wizard, 69, 0, :east
unit :sludge, 73, 0, :east
unit :captive, 75, 0, :east
unit :sludge, 77, 0, :east
unit :thick_sludge, 79, 0, :east
unit :sludge, 84, 0, :east
unit :wizard, 89, 0, :east
unit :captive, 90, 0, :east
unit :sludge, 92, 0, :east
unit :captive, 93, 0, :east
unit :wizard, 106, 0, :east
unit :thick_sludge, 108, 0, :east
unit :wizard, 118, 0, :east
unit :wizard, 124, 0, :west
unit :sludge, 125, 0, :west
unit :thick_sludge, 134, 0, :west
unit :sludge, 136, 0, :west
unit :archer, 140, 0, :west
unit :captive, 141, 0, :west
unit :archer, 142, 0, :west
unit :captive, 152, 0, :west
unit :sludge, 153, 0, :west
unit :thick_sludge, 156, 0, :west
unit :thick_sludge, 159, 0, :west
unit :captive, 160, 0, :west
unit :thick_sludge, 161, 0, :west
unit :thick_sludge, 165, 0, :west
unit :thick_sludge, 170, 0, :west
unit :captive, 171, 0, :west
unit :thick_sludge, 177, 0, :west
unit :thick_sludge, 186, 0, :west
unit :archer, 193, 0, :west
unit :wizard, 201, 0, :west
unit :sludge, 203, 0, :west
unit :wizard, 209, 0, :west
unit :captive, 212, 0, :west
unit :sludge, 222, 0, :west
unit :wizard, 228, 0, :west
unit :sludge, 229, 0, :west
unit :wizard, 230, 0, :west
unit :sludge, 243, 0, :west
unit :sludge, 254, 0, :west
unit :wizard, 262, 0, :west
unit :captive, 265, 0, :west
unit :captive, 266, 0, :west
unit :archer, 271, 0, :west
unit :wizard, 273, 0, :west
unit :captive, 276, 0, :west
unit :wizard, 277, 0, :west
unit :archer, 279, 0, :west
unit :captive, 281, 0, :west
unit :archer, 282, 0, :west
unit :wizard, 285, 0, :west
unit :thick_sludge, 293, 0, :west
unit :sludge, 294, 0, :west
unit :captive, 296, 0, :west
unit :archer, 298, 0, :west
unit :archer, 309, 0, :west
unit :captive, 315, 0, :west
unit :sludge, 317, 0, :west
unit :archer, 322, 0, :west
unit :captive, 324, 0, :west
unit :sludge, 331, 0, :west
unit :thick_sludge, 332, 0, :west
unit :archer, 333, 0, :west
unit :archer, 339, 0, :west
unit :sludge, 345, 0, :west
unit :captive, 347, 0, :west
unit :sludge, 351, 0, :west
unit :archer, 354, 0, :west
unit :captive, 359, 0, :west
unit :captive, 364, 0, :west
unit :wizard, 381, 0, :west
unit :archer, 386, 0, :west
unit :captive, 391, 0, :west
unit :sludge, 398, 0, :west
unit :thick_sludge, 416, 0, :west
unit :captive, 419, 0, :west
unit :thick_sludge, 420, 0, :west
unit :archer, 425, 0, :west
unit :archer, 426, 0, :west
unit :captive, 437, 0, :west
unit :wizard, 439, 0, :west
unit :archer, 441, 0, :west
unit :archer, 445, 0, :west
unit :thick_sludge, 453, 0, :west
unit :archer, 457, 0, :west
unit :sludge, 459, 0, :west
unit :wizard, 461, 0, :west
unit :captive, 470, 0, :west
unit :thick_sludge, 474, 0, :west
unit :archer, 477, 0, :west
unit :thick_sludge, 480, 0, :west
unit :captive, 481, 0, :west
unit :archer, 487, 0, :west
unit :captive, 493, 0, :west
unit :archer, 495, 0, :west
unit :sludge, 497, 0, :west
unit :thick_sludge, 504, 0, :west
unit :captive, 509, 0, :west
unit :archer, 514, 0, :west
unit :wizard, 524, 0, :west
unit :thick_sludge, 526, 0, :west
unit :archer, 528, 0, :west
unit :sludge, 529, 0, :west
unit :wizard, 532, 0, :west
unit :captive, 538, 0, :west
unit :sludge, 541, 0, :west
unit :thick_sludge, 547, 0, :west
unit :captive, 548, 0, :west
unit :thick_sludge, 550, 0, :west
unit :sludge, 552, 0, :west
unit :wizard, 555, 0, :west
unit :archer, 559, 0, :west
unit :thick_sludge, 565, 0, :west
unit :sludge, 568, 0, :west
unit :captive, 569, 0, :west
unit :wizard, 570, 0, :west
unit :wizard, 573, 0, :west
unit :wizard, 579, 0, :west
unit :archer, 580, 0, :west
unit :thick_sludge, 582, 0, :west
unit :archer, 587, 0, :west
unit :archer, 591, 0, :west
unit :archer, 593, 0, :west
unit :thick_sludge, 597, 0, :west
unit :thick_sludge, 601, 0, :west
unit :sludge, 605, 0, :west
unit :archer, 607, 0, :west
unit :wizard, 611, 0, :west
unit :captive, 612, 0, :west
unit :thick_sludge, 616, 0, :west
unit :sludge, 619, 0, :west
unit :archer, 625, 0, :west
unit :wizard, 628, 0, :west
unit :captive, 629, 0, :west
unit :archer, 633, 0, :west
unit :captive, 638, 0, :west
unit :captive, 642, 0, :west
unit :archer, 645, 0, :west
unit :sludge, 658, 0, :west
unit :thick_sludge, 662, 0, :west
unit :captive, 663, 0, :west
unit :archer, 666, 0, :west
unit :sludge, 667, 0, :west
unit :archer, 668, 0, :west
unit :archer, 670, 0, :west
unit :sludge, 673, 0, :west
unit :captive, 683, 0, :west
unit :captive, 684, 0, :west
unit :wizard, 688, 0, :west
unit :sludge, 690, 0, :west
unit :thick_sludge, 692, 0, :west
unit :captive, 693, 0, :west
unit :wizard, 695, 0, :west
unit :archer, 697, 0, :west
unit :thick_sludge, 698, 0, :west
unit :thick_sludge, 701, 0, :west
unit :sludge, 705, 0, :west
unit :captive, 707, 0, :west
