#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s         a   a                s       a   sC  S           Csa   CsS w C   s       S  w w  s  CCC   s  aw   Ss    s    aS     Sa w    S  Ca   C                  aS   w w C wa   S    s         aa    asw         s    S    C     a  C C  w     Ss           S aC  s w        s       S w Ss  S       S   s s C   @  C ss        Ss        s       C w      C           s   w sa      SC a    w as     C       a  s s    aa     s     wSC  w w      as       C w as a  Sa   w   CC   s C  C  ws     s    sS              C s       s  CC     sCS   s    a   C     wS  C      s     s        CC sC    C S  wSS   s C   w     S   w C                a S                 C                    w    C S C  w a      S    S  S        w       S w C Sa S a          a  C   sS  S  s       a    C    s  s a> SC    s     sw    S    s  C s    C  S S   s   SS w    a         w a  C    wC  |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 856
ace_score 4280
size 856, 1
stairs 776, 0

warrior 308, 0, :east

unit :sludge, 2, 0, :east
unit :archer, 12, 0, :east
unit :archer, 16, 0, :east
unit :sludge, 33, 0, :east
unit :archer, 41, 0, :east
unit :sludge, 45, 0, :east
unit :captive, 46, 0, :east
unit :thick_sludge, 49, 0, :east
unit :captive, 61, 0, :east
unit :sludge, 62, 0, :east
unit :archer, 63, 0, :east
unit :captive, 67, 0, :east
unit :sludge, 68, 0, :east
unit :thick_sludge, 69, 0, :east
unit :wizard, 71, 0, :east
unit :captive, 73, 0, :east
unit :sludge, 77, 0, :east
unit :thick_sludge, 85, 0, :east
unit :wizard, 88, 0, :east
unit :wizard, 90, 0, :east
unit :sludge, 93, 0, :east
unit :captive, 96, 0, :east
unit :captive, 97, 0, :east
unit :captive, 98, 0, :east
unit :sludge, 102, 0, :east
unit :archer, 105, 0, :east
unit :wizard, 106, 0, :east
unit :thick_sludge, 110, 0, :east
unit :sludge, 111, 0, :east
unit :sludge, 116, 0, :east
unit :archer, 121, 0, :east
unit :thick_sludge, 122, 0, :east
unit :thick_sludge, 128, 0, :east
unit :archer, 129, 0, :east
unit :wizard, 131, 0, :east
unit :thick_sludge, 136, 0, :east
unit :captive, 139, 0, :east
unit :archer, 140, 0, :east
unit :captive, 144, 0, :east
unit :archer, 163, 0, :east
unit :thick_sludge, 164, 0, :east
unit :wizard, 168, 0, :east
unit :wizard, 170, 0, :east
unit :captive, 172, 0, :east
unit :wizard, 174, 0, :east
unit :archer, 175, 0, :east
unit :thick_sludge, 179, 0, :east
unit :sludge, 184, 0, :east
unit :archer, 194, 0, :east
unit :archer, 195, 0, :east
unit :archer, 200, 0, :east
unit :sludge, 201, 0, :east
unit :wizard, 202, 0, :east
unit :sludge, 212, 0, :east
unit :thick_sludge, 217, 0, :east
unit :captive, 222, 0, :east
unit :archer, 228, 0, :east
unit :captive, 231, 0, :east
unit :captive, 233, 0, :east
unit :wizard, 236, 0, :east
unit :thick_sludge, 242, 0, :east
unit :sludge, 243, 0, :east
unit :thick_sludge, 255, 0, :east
unit :archer, 257, 0, :east
unit :captive, 258, 0, :east
unit :sludge, 261, 0, :east
unit :wizard, 263, 0, :east
unit :sludge, 272, 0, :east
unit :thick_sludge, 280, 0, :east
unit :wizard, 282, 0, :east
unit :thick_sludge, 284, 0, :east
unit :sludge, 285, 0, :east
unit :thick_sludge, 288, 0, :east
unit :thick_sludge, 296, 0, :east
unit :sludge, 300, 0, :east
unit :sludge, 302, 0, :east
unit :captive, 304, 0, :east
unit :captive, 311, 0, :west
unit :sludge, 313, 0, :west
unit :sludge, 314, 0, :west
unit :thick_sludge, 323, 0, :west
unit :sludge, 324, 0, :west
unit :sludge, 333, 0, :west
unit :captive, 341, 0, :west
unit :wizard, 343, 0, :west
unit :captive, 350, 0, :west
unit :sludge, 362, 0, :west
unit :wizard, 366, 0, :west
unit :sludge, 368, 0, :west
unit :archer, 369, 0, :west
unit :thick_sludge, 376, 0, :west
unit :captive, 377, 0, :west
unit :archer, 379, 0, :west
unit :wizard, 384, 0, :west
unit :archer, 386, 0, :west
unit :sludge, 387, 0, :west
unit :captive, 393, 0, :west
unit :archer, 401, 0, :west
unit :sludge, 404, 0, :west
unit :sludge, 406, 0, :west
unit :archer, 411, 0, :west
unit :archer, 412, 0, :west
unit :sludge, 418, 0, :west
unit :wizard, 424, 0, :west
unit :thick_sludge, 425, 0, :west
unit :captive, 426, 0, :west
unit :wizard, 429, 0, :west
unit :wizard, 431, 0, :west
unit :archer, 438, 0, :west
unit :sludge, 439, 0, :west
unit :captive, 447, 0, :west
unit :wizard, 449, 0, :west
unit :archer, 451, 0, :west
unit :sludge, 452, 0, :west
unit :archer, 454, 0, :west
unit :thick_sludge, 457, 0, :west
unit :archer, 458, 0, :west
unit :wizard, 462, 0, :west
unit :captive, 466, 0, :west
unit :captive, 467, 0, :west
unit :sludge, 471, 0, :west
unit :captive, 473, 0, :west
unit :captive, 476, 0, :west
unit :wizard, 479, 0, :west
unit :sludge, 480, 0, :west
unit :sludge, 486, 0, :west
unit :sludge, 491, 0, :west
unit :thick_sludge, 492, 0, :west
unit :captive, 507, 0, :west
unit :sludge, 509, 0, :west
unit :sludge, 517, 0, :west
unit :captive, 520, 0, :west
unit :captive, 521, 0, :west
unit :sludge, 527, 0, :west
unit :captive, 528, 0, :west
unit :thick_sludge, 529, 0, :west
unit :sludge, 533, 0, :west
unit :archer, 538, 0, :west
unit :captive, 542, 0, :west
unit :wizard, 548, 0, :west
unit :thick_sludge, 549, 0, :west
unit :captive, 552, 0, :west
unit :sludge, 559, 0, :west
unit :sludge, 565, 0, :west
unit :captive, 574, 0, :west
unit :captive, 575, 0, :west
unit :sludge, 577, 0, :west
unit :captive, 578, 0, :west
unit :captive, 583, 0, :west
unit :thick_sludge, 585, 0, :west
unit :wizard, 588, 0, :west
unit :thick_sludge, 589, 0, :west
unit :thick_sludge, 590, 0, :west
unit :sludge, 594, 0, :west
unit :captive, 596, 0, :west
unit :wizard, 600, 0, :west
unit :thick_sludge, 606, 0, :west
unit :wizard, 610, 0, :west
unit :captive, 612, 0, :west
unit :archer, 629, 0, :west
unit :thick_sludge, 631, 0, :west
unit :captive, 649, 0, :west
unit :wizard, 670, 0, :west
unit :captive, 675, 0, :west
unit :thick_sludge, 677, 0, :west
unit :captive, 679, 0, :west
unit :wizard, 682, 0, :west
unit :archer, 684, 0, :west
unit :thick_sludge, 691, 0, :west
unit :thick_sludge, 696, 0, :west
unit :thick_sludge, 699, 0, :west
unit :wizard, 708, 0, :west
unit :thick_sludge, 716, 0, :west
unit :wizard, 718, 0, :west
unit :captive, 720, 0, :west
unit :thick_sludge, 722, 0, :west
unit :archer, 723, 0, :west
unit :thick_sludge, 725, 0, :west
unit :archer, 727, 0, :west
unit :archer, 738, 0, :west
unit :captive, 741, 0, :west
unit :sludge, 745, 0, :west
unit :thick_sludge, 746, 0, :west
unit :thick_sludge, 749, 0, :west
unit :sludge, 752, 0, :west
unit :archer, 760, 0, :west
unit :captive, 765, 0, :west
unit :sludge, 770, 0, :west
unit :sludge, 773, 0, :west
unit :archer, 775, 0, :west
unit :thick_sludge, 778, 0, :west
unit :captive, 779, 0, :west
unit :sludge, 784, 0, :west
unit :sludge, 790, 0, :west
unit :wizard, 791, 0, :west
unit :thick_sludge, 796, 0, :west
unit :sludge, 801, 0, :west
unit :captive, 804, 0, :west
unit :sludge, 806, 0, :west
unit :captive, 811, 0, :west
unit :thick_sludge, 814, 0, :west
unit :thick_sludge, 816, 0, :west
unit :sludge, 820, 0, :west
unit :thick_sludge, 824, 0, :west
unit :thick_sludge, 825, 0, :west
unit :wizard, 827, 0, :west
unit :archer, 832, 0, :west
unit :wizard, 842, 0, :west
unit :archer, 844, 0, :west
unit :captive, 847, 0, :west
unit :wizard, 852, 0, :west
unit :captive, 853, 0, :west
