#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |           a   w w     C    C   S     S    a   s    s       aC   w Ss> S  w S    S              s C       SsS   S a Sa     a   C S   s                S S   w            w Sa sa s  s  S   C Cw S         s   SC     S   w S  w  C   w          sw  S a       Ss a a      S s     S  s   wC       @  Sa     C s  Sa        a sS  ss  C   wS    a C        awC   s     CS    S   C s     S    C        s   S   C w      as S  sS   C    a CC   C a     a       S    aCa  ws  w    s   a  C w   C w        w   a  S   w  C          a    a s          S       s  C   C   w w   a    Cw  S   w w   aa   C           Cs              C       w  S S    S  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 630
ace_score 3150
size 630, 1
stairs 69, 0

warrior 290, 0, :east

unit :archer, 11, 0, :east
unit :wizard, 15, 0, :east
unit :wizard, 17, 0, :east
unit :captive, 23, 0, :east
unit :captive, 28, 0, :east
unit :thick_sludge, 32, 0, :east
unit :thick_sludge, 38, 0, :east
unit :archer, 43, 0, :east
unit :sludge, 47, 0, :east
unit :sludge, 52, 0, :east
unit :archer, 60, 0, :east
unit :captive, 61, 0, :east
unit :wizard, 65, 0, :east
unit :thick_sludge, 67, 0, :east
unit :sludge, 68, 0, :east
unit :thick_sludge, 71, 0, :east
unit :wizard, 74, 0, :east
unit :thick_sludge, 76, 0, :east
unit :thick_sludge, 81, 0, :east
unit :sludge, 96, 0, :east
unit :captive, 98, 0, :east
unit :thick_sludge, 106, 0, :east
unit :sludge, 107, 0, :east
unit :thick_sludge, 108, 0, :east
unit :thick_sludge, 112, 0, :east
unit :archer, 114, 0, :east
unit :thick_sludge, 116, 0, :east
unit :archer, 117, 0, :east
unit :archer, 123, 0, :east
unit :captive, 127, 0, :east
unit :thick_sludge, 129, 0, :east
unit :sludge, 133, 0, :east
unit :thick_sludge, 150, 0, :east
unit :thick_sludge, 152, 0, :east
unit :wizard, 156, 0, :east
unit :wizard, 169, 0, :east
unit :thick_sludge, 171, 0, :east
unit :archer, 172, 0, :east
unit :sludge, 174, 0, :east
unit :archer, 175, 0, :east
unit :sludge, 177, 0, :east
unit :sludge, 180, 0, :east
unit :thick_sludge, 183, 0, :east
unit :captive, 187, 0, :east
unit :captive, 189, 0, :east
unit :wizard, 190, 0, :east
unit :thick_sludge, 192, 0, :east
unit :sludge, 202, 0, :east
unit :thick_sludge, 206, 0, :east
unit :captive, 207, 0, :east
unit :thick_sludge, 213, 0, :east
unit :wizard, 217, 0, :east
unit :thick_sludge, 219, 0, :east
unit :wizard, 222, 0, :east
unit :captive, 225, 0, :east
unit :wizard, 229, 0, :east
unit :sludge, 240, 0, :east
unit :wizard, 241, 0, :east
unit :thick_sludge, 244, 0, :east
unit :archer, 246, 0, :east
unit :thick_sludge, 254, 0, :east
unit :sludge, 255, 0, :east
unit :archer, 257, 0, :east
unit :archer, 259, 0, :east
unit :thick_sludge, 266, 0, :east
unit :sludge, 268, 0, :east
unit :thick_sludge, 274, 0, :east
unit :sludge, 277, 0, :east
unit :wizard, 281, 0, :east
unit :captive, 282, 0, :east
unit :thick_sludge, 293, 0, :west
unit :archer, 294, 0, :west
unit :captive, 300, 0, :west
unit :sludge, 302, 0, :west
unit :thick_sludge, 305, 0, :west
unit :archer, 306, 0, :west
unit :archer, 315, 0, :west
unit :sludge, 317, 0, :west
unit :thick_sludge, 318, 0, :west
unit :sludge, 321, 0, :west
unit :sludge, 322, 0, :west
unit :captive, 325, 0, :west
unit :wizard, 329, 0, :west
unit :thick_sludge, 330, 0, :west
unit :archer, 335, 0, :west
unit :captive, 337, 0, :west
unit :archer, 346, 0, :west
unit :wizard, 347, 0, :west
unit :captive, 348, 0, :west
unit :sludge, 352, 0, :west
unit :captive, 358, 0, :west
unit :thick_sludge, 359, 0, :west
unit :thick_sludge, 364, 0, :west
unit :captive, 368, 0, :west
unit :sludge, 370, 0, :west
unit :thick_sludge, 376, 0, :west
unit :captive, 381, 0, :west
unit :sludge, 390, 0, :west
unit :thick_sludge, 394, 0, :west
unit :captive, 398, 0, :west
unit :wizard, 400, 0, :west
unit :archer, 407, 0, :west
unit :sludge, 408, 0, :west
unit :thick_sludge, 410, 0, :west
unit :sludge, 413, 0, :west
unit :thick_sludge, 414, 0, :west
unit :captive, 418, 0, :west
unit :archer, 423, 0, :west
unit :captive, 425, 0, :west
unit :captive, 426, 0, :west
unit :captive, 430, 0, :west
unit :archer, 432, 0, :west
unit :archer, 438, 0, :west
unit :thick_sludge, 446, 0, :west
unit :archer, 451, 0, :west
unit :captive, 452, 0, :west
unit :archer, 453, 0, :west
unit :wizard, 456, 0, :west
unit :sludge, 457, 0, :west
unit :wizard, 460, 0, :west
unit :sludge, 465, 0, :west
unit :archer, 469, 0, :west
unit :captive, 472, 0, :west
unit :wizard, 474, 0, :west
unit :captive, 478, 0, :west
unit :wizard, 480, 0, :west
unit :wizard, 489, 0, :west
unit :archer, 493, 0, :west
unit :thick_sludge, 496, 0, :west
unit :wizard, 500, 0, :west
unit :captive, 503, 0, :west
unit :archer, 514, 0, :west
unit :archer, 519, 0, :west
unit :sludge, 521, 0, :west
unit :thick_sludge, 532, 0, :west
unit :sludge, 540, 0, :west
unit :captive, 543, 0, :west
unit :captive, 547, 0, :west
unit :wizard, 551, 0, :west
unit :wizard, 553, 0, :west
unit :archer, 557, 0, :west
unit :captive, 562, 0, :west
unit :wizard, 563, 0, :west
unit :thick_sludge, 566, 0, :west
unit :wizard, 570, 0, :west
unit :wizard, 572, 0, :west
unit :archer, 576, 0, :west
unit :archer, 577, 0, :west
unit :captive, 581, 0, :west
unit :captive, 593, 0, :west
unit :sludge, 594, 0, :west
unit :captive, 609, 0, :west
unit :wizard, 617, 0, :west
unit :thick_sludge, 620, 0, :west
unit :thick_sludge, 622, 0, :west
unit :thick_sludge, 627, 0, :west
