#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      S C    S           S            a      s  s       C S  a   C C    s    s w   S  s          a          C w  w a           SC  C s        S    wC          w         S a    s         a    w C   aC  w   s SC    s  w  aCw            wS s  S S    @           w            Ca      s S aa    s    w w S    C    s   w   S     S  s   C     w  S      SSC  s C    C   SC w C S    a   aS      C C   C     ss C   s      a S   ss w  C  a  C a     w     s      w   aw   s  Ss  w     s   w a    a     a S w  >w     as    s   C     S    C S w S    w    S    a  C S     S       w  CS        s S    s  s   s S w    Ss a    C      a      s     Ca      S     C Ss S SC  C    wSSs S    a  Cs          w C a   a  C     C   w|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 706
ace_score 3530
size 706, 1
stairs 497, 0

warrior 247, 0, :east

unit :thick_sludge, 6, 0, :east
unit :captive, 8, 0, :east
unit :thick_sludge, 13, 0, :east
unit :thick_sludge, 25, 0, :east
unit :archer, 38, 0, :east
unit :sludge, 45, 0, :east
unit :sludge, 48, 0, :east
unit :captive, 56, 0, :east
unit :thick_sludge, 58, 0, :east
unit :archer, 61, 0, :east
unit :captive, 65, 0, :east
unit :captive, 67, 0, :east
unit :sludge, 72, 0, :east
unit :sludge, 77, 0, :east
unit :wizard, 79, 0, :east
unit :thick_sludge, 83, 0, :east
unit :sludge, 86, 0, :east
unit :archer, 97, 0, :east
unit :captive, 108, 0, :east
unit :wizard, 110, 0, :east
unit :wizard, 113, 0, :east
unit :archer, 115, 0, :east
unit :thick_sludge, 127, 0, :east
unit :captive, 128, 0, :east
unit :captive, 131, 0, :east
unit :sludge, 133, 0, :east
unit :thick_sludge, 142, 0, :east
unit :wizard, 147, 0, :east
unit :captive, 148, 0, :east
unit :wizard, 159, 0, :east
unit :thick_sludge, 169, 0, :east
unit :archer, 171, 0, :east
unit :sludge, 176, 0, :east
unit :archer, 186, 0, :east
unit :wizard, 191, 0, :east
unit :captive, 193, 0, :east
unit :archer, 197, 0, :east
unit :captive, 198, 0, :east
unit :wizard, 201, 0, :east
unit :sludge, 205, 0, :east
unit :thick_sludge, 207, 0, :east
unit :captive, 208, 0, :east
unit :sludge, 213, 0, :east
unit :wizard, 216, 0, :east
unit :archer, 219, 0, :east
unit :captive, 220, 0, :east
unit :wizard, 221, 0, :east
unit :wizard, 234, 0, :east
unit :thick_sludge, 235, 0, :east
unit :sludge, 237, 0, :east
unit :thick_sludge, 240, 0, :east
unit :thick_sludge, 242, 0, :east
unit :wizard, 259, 0, :west
unit :captive, 272, 0, :west
unit :archer, 273, 0, :west
unit :sludge, 280, 0, :west
unit :thick_sludge, 282, 0, :west
unit :archer, 284, 0, :west
unit :archer, 285, 0, :west
unit :sludge, 290, 0, :west
unit :wizard, 295, 0, :west
unit :wizard, 297, 0, :west
unit :thick_sludge, 299, 0, :west
unit :captive, 304, 0, :west
unit :sludge, 309, 0, :west
unit :wizard, 313, 0, :west
unit :thick_sludge, 317, 0, :west
unit :thick_sludge, 323, 0, :west
unit :sludge, 326, 0, :west
unit :captive, 330, 0, :west
unit :wizard, 336, 0, :west
unit :thick_sludge, 339, 0, :west
unit :thick_sludge, 346, 0, :west
unit :thick_sludge, 347, 0, :west
unit :captive, 348, 0, :west
unit :sludge, 351, 0, :west
unit :captive, 353, 0, :west
unit :captive, 358, 0, :west
unit :thick_sludge, 362, 0, :west
unit :captive, 363, 0, :west
unit :wizard, 365, 0, :west
unit :captive, 367, 0, :west
unit :thick_sludge, 369, 0, :west
unit :archer, 374, 0, :west
unit :archer, 378, 0, :west
unit :thick_sludge, 379, 0, :west
unit :captive, 386, 0, :west
unit :captive, 388, 0, :west
unit :captive, 392, 0, :west
unit :sludge, 398, 0, :west
unit :sludge, 399, 0, :west
unit :captive, 401, 0, :west
unit :sludge, 405, 0, :west
unit :archer, 412, 0, :west
unit :thick_sludge, 414, 0, :west
unit :sludge, 418, 0, :west
unit :sludge, 419, 0, :west
unit :wizard, 421, 0, :west
unit :captive, 424, 0, :west
unit :archer, 427, 0, :west
unit :captive, 430, 0, :west
unit :archer, 432, 0, :west
unit :wizard, 438, 0, :west
unit :sludge, 444, 0, :west
unit :wizard, 451, 0, :west
unit :archer, 455, 0, :west
unit :wizard, 456, 0, :west
unit :sludge, 460, 0, :west
unit :thick_sludge, 463, 0, :west
unit :sludge, 464, 0, :west
unit :wizard, 467, 0, :west
unit :sludge, 473, 0, :west
unit :wizard, 477, 0, :west
unit :archer, 479, 0, :west
unit :archer, 484, 0, :west
unit :archer, 490, 0, :west
unit :thick_sludge, 492, 0, :west
unit :wizard, 494, 0, :west
unit :wizard, 498, 0, :west
unit :archer, 504, 0, :west
unit :sludge, 505, 0, :west
unit :sludge, 510, 0, :west
unit :captive, 514, 0, :west
unit :thick_sludge, 520, 0, :west
unit :captive, 525, 0, :west
unit :thick_sludge, 527, 0, :west
unit :wizard, 529, 0, :west
unit :thick_sludge, 531, 0, :west
unit :wizard, 536, 0, :west
unit :thick_sludge, 541, 0, :west
unit :archer, 546, 0, :west
unit :captive, 549, 0, :west
unit :thick_sludge, 551, 0, :west
unit :thick_sludge, 557, 0, :west
unit :wizard, 565, 0, :west
unit :captive, 568, 0, :west
unit :thick_sludge, 569, 0, :west
unit :sludge, 578, 0, :west
unit :thick_sludge, 580, 0, :west
unit :sludge, 585, 0, :west
unit :sludge, 588, 0, :west
unit :sludge, 592, 0, :west
unit :thick_sludge, 594, 0, :west
unit :wizard, 596, 0, :west
unit :thick_sludge, 601, 0, :west
unit :sludge, 602, 0, :west
unit :archer, 604, 0, :west
unit :captive, 609, 0, :west
unit :archer, 616, 0, :west
unit :sludge, 623, 0, :west
unit :captive, 629, 0, :west
unit :archer, 630, 0, :west
unit :thick_sludge, 637, 0, :west
unit :captive, 643, 0, :west
unit :thick_sludge, 645, 0, :west
unit :sludge, 646, 0, :west
unit :thick_sludge, 648, 0, :west
unit :thick_sludge, 650, 0, :west
unit :captive, 651, 0, :west
unit :captive, 654, 0, :west
unit :wizard, 659, 0, :west
unit :thick_sludge, 660, 0, :west
unit :thick_sludge, 661, 0, :west
unit :sludge, 662, 0, :west
unit :thick_sludge, 664, 0, :west
unit :archer, 669, 0, :west
unit :captive, 672, 0, :west
unit :sludge, 673, 0, :west
unit :wizard, 684, 0, :west
unit :captive, 686, 0, :west
unit :archer, 688, 0, :west
unit :archer, 692, 0, :west
unit :captive, 695, 0, :west
unit :captive, 701, 0, :west
unit :wizard, 705, 0, :west
