#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | Csw         s       ss  wa  C aw     w    S   Sa w     CC    S          w     s   Sa  wSw  s  w     C w S   a      wC    CSC ssC  CwSs          Cs      s        a    s a   Ss     Sa    C w     C   s     S    w  aC    s     s C   CS    w C      sS s Ca      S ss s   C        a   a    sC w            sC   CS s            SS  S  w  s Sa        a aa  sa               s      s    @            a      a              >                s  s     s w SS w w aS C    S       S      w a     S    w  aa  aS s             S  S    aaw       C        s   s    w S     S     wC   |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 566
ace_score 2830
size 566, 1
stairs 414, 0

warrior 379, 0, :east

unit :captive, 1, 0, :east
unit :sludge, 2, 0, :east
unit :wizard, 3, 0, :east
unit :sludge, 13, 0, :east
unit :sludge, 21, 0, :east
unit :sludge, 22, 0, :east
unit :wizard, 25, 0, :east
unit :archer, 26, 0, :east
unit :captive, 29, 0, :east
unit :archer, 31, 0, :east
unit :wizard, 32, 0, :east
unit :wizard, 38, 0, :east
unit :thick_sludge, 43, 0, :east
unit :thick_sludge, 47, 0, :east
unit :archer, 48, 0, :east
unit :wizard, 50, 0, :east
unit :captive, 56, 0, :east
unit :captive, 57, 0, :east
unit :thick_sludge, 62, 0, :east
unit :wizard, 73, 0, :east
unit :sludge, 79, 0, :east
unit :thick_sludge, 83, 0, :east
unit :archer, 84, 0, :east
unit :wizard, 87, 0, :east
unit :thick_sludge, 88, 0, :east
unit :wizard, 89, 0, :east
unit :sludge, 92, 0, :east
unit :wizard, 95, 0, :east
unit :captive, 101, 0, :east
unit :wizard, 103, 0, :east
unit :thick_sludge, 105, 0, :east
unit :archer, 109, 0, :east
unit :wizard, 116, 0, :east
unit :captive, 117, 0, :east
unit :captive, 122, 0, :east
unit :thick_sludge, 123, 0, :east
unit :captive, 124, 0, :east
unit :sludge, 126, 0, :east
unit :sludge, 127, 0, :east
unit :captive, 128, 0, :east
unit :captive, 131, 0, :east
unit :wizard, 132, 0, :east
unit :thick_sludge, 133, 0, :east
unit :sludge, 134, 0, :east
unit :captive, 145, 0, :east
unit :sludge, 146, 0, :east
unit :sludge, 153, 0, :east
unit :archer, 162, 0, :east
unit :sludge, 167, 0, :east
unit :archer, 169, 0, :east
unit :thick_sludge, 173, 0, :east
unit :sludge, 174, 0, :east
unit :thick_sludge, 180, 0, :east
unit :archer, 181, 0, :east
unit :captive, 186, 0, :east
unit :wizard, 188, 0, :east
unit :captive, 194, 0, :east
unit :sludge, 198, 0, :east
unit :thick_sludge, 204, 0, :east
unit :wizard, 209, 0, :east
unit :archer, 212, 0, :east
unit :captive, 213, 0, :east
unit :sludge, 218, 0, :east
unit :sludge, 224, 0, :east
unit :captive, 226, 0, :east
unit :captive, 230, 0, :east
unit :thick_sludge, 231, 0, :east
unit :wizard, 236, 0, :east
unit :captive, 238, 0, :east
unit :sludge, 245, 0, :east
unit :thick_sludge, 246, 0, :east
unit :sludge, 248, 0, :east
unit :captive, 250, 0, :east
unit :archer, 251, 0, :east
unit :thick_sludge, 258, 0, :east
unit :sludge, 260, 0, :east
unit :sludge, 261, 0, :east
unit :sludge, 263, 0, :east
unit :captive, 267, 0, :east
unit :archer, 276, 0, :east
unit :archer, 280, 0, :east
unit :sludge, 285, 0, :east
unit :captive, 286, 0, :east
unit :wizard, 288, 0, :east
unit :sludge, 301, 0, :east
unit :captive, 302, 0, :east
unit :captive, 306, 0, :east
unit :thick_sludge, 307, 0, :east
unit :sludge, 309, 0, :east
unit :thick_sludge, 322, 0, :east
unit :thick_sludge, 323, 0, :east
unit :thick_sludge, 326, 0, :east
unit :wizard, 329, 0, :east
unit :sludge, 332, 0, :east
unit :thick_sludge, 334, 0, :east
unit :archer, 335, 0, :east
unit :archer, 344, 0, :east
unit :archer, 346, 0, :east
unit :archer, 347, 0, :east
unit :sludge, 350, 0, :east
unit :archer, 351, 0, :east
unit :sludge, 367, 0, :east
unit :sludge, 374, 0, :east
unit :archer, 392, 0, :west
unit :archer, 399, 0, :west
unit :sludge, 431, 0, :west
unit :sludge, 434, 0, :west
unit :sludge, 440, 0, :west
unit :wizard, 442, 0, :west
unit :thick_sludge, 444, 0, :west
unit :thick_sludge, 445, 0, :west
unit :wizard, 447, 0, :west
unit :wizard, 449, 0, :west
unit :archer, 451, 0, :west
unit :thick_sludge, 452, 0, :west
unit :captive, 454, 0, :west
unit :thick_sludge, 459, 0, :west
unit :thick_sludge, 467, 0, :west
unit :wizard, 474, 0, :west
unit :archer, 476, 0, :west
unit :thick_sludge, 482, 0, :west
unit :wizard, 487, 0, :west
unit :archer, 490, 0, :west
unit :archer, 491, 0, :west
unit :archer, 494, 0, :west
unit :thick_sludge, 495, 0, :west
unit :sludge, 497, 0, :west
unit :thick_sludge, 511, 0, :west
unit :thick_sludge, 514, 0, :west
unit :archer, 519, 0, :west
unit :archer, 520, 0, :west
unit :wizard, 521, 0, :west
unit :captive, 529, 0, :west
unit :sludge, 538, 0, :west
unit :sludge, 542, 0, :west
unit :wizard, 547, 0, :west
unit :thick_sludge, 549, 0, :west
unit :thick_sludge, 555, 0, :west
unit :wizard, 561, 0, :west
unit :captive, 562, 0, :west
