#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |        s   C     w  C      s    a S  CC  C a  w            C   a  aS  Cs   w  w   ss     aa    w    s     S        CSSCa       C    Sw wC w s   C  Sa  w         w s   w  w  a     S    C    s   SsC                          s     SS          S   s Cw ss  a wa>           Cs S   a s S   w  s        w        C      s    C    w  a  C  s  C      w w w Ca     a  CCC C  s C   s a a       a CC   sS   C    S   S   @  s      S    s   w  s          Ss               S C s C a   a  S        S  C C             C   sC  Sw           S s s   s s  C          S    S w     CS      s   aw      s   a  C   Ca  C SS   S                S  w a       CS  S  aa    a      a    w  s C           a    w     a  sC s  S   w    w  s C|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 708
ace_score 3540
size 708, 1
stairs 258, 0

warrior 408, 0, :east

unit :sludge, 8, 0, :east
unit :captive, 12, 0, :east
unit :wizard, 18, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 28, 0, :east
unit :archer, 33, 0, :east
unit :thick_sludge, 35, 0, :east
unit :captive, 38, 0, :east
unit :captive, 39, 0, :east
unit :captive, 42, 0, :east
unit :archer, 44, 0, :east
unit :wizard, 47, 0, :east
unit :captive, 60, 0, :east
unit :archer, 64, 0, :east
unit :archer, 67, 0, :east
unit :thick_sludge, 68, 0, :east
unit :captive, 71, 0, :east
unit :sludge, 72, 0, :east
unit :wizard, 76, 0, :east
unit :wizard, 79, 0, :east
unit :sludge, 83, 0, :east
unit :sludge, 84, 0, :east
unit :archer, 90, 0, :east
unit :archer, 91, 0, :east
unit :wizard, 96, 0, :east
unit :sludge, 101, 0, :east
unit :thick_sludge, 107, 0, :east
unit :captive, 116, 0, :east
unit :thick_sludge, 117, 0, :east
unit :thick_sludge, 118, 0, :east
unit :captive, 119, 0, :east
unit :archer, 120, 0, :east
unit :captive, 128, 0, :east
unit :thick_sludge, 133, 0, :east
unit :wizard, 134, 0, :east
unit :wizard, 136, 0, :east
unit :captive, 137, 0, :east
unit :wizard, 139, 0, :east
unit :sludge, 141, 0, :east
unit :captive, 145, 0, :east
unit :thick_sludge, 148, 0, :east
unit :archer, 149, 0, :east
unit :wizard, 152, 0, :east
unit :wizard, 162, 0, :east
unit :sludge, 164, 0, :east
unit :wizard, 168, 0, :east
unit :wizard, 171, 0, :east
unit :archer, 174, 0, :east
unit :thick_sludge, 180, 0, :east
unit :captive, 185, 0, :east
unit :sludge, 190, 0, :east
unit :thick_sludge, 194, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 196, 0, :east
unit :sludge, 223, 0, :east
unit :thick_sludge, 229, 0, :east
unit :thick_sludge, 230, 0, :east
unit :thick_sludge, 241, 0, :east
unit :sludge, 245, 0, :east
unit :captive, 247, 0, :east
unit :wizard, 248, 0, :east
unit :sludge, 250, 0, :east
unit :sludge, 251, 0, :east
unit :archer, 254, 0, :east
unit :wizard, 256, 0, :east
unit :archer, 257, 0, :east
unit :captive, 270, 0, :east
unit :sludge, 271, 0, :east
unit :thick_sludge, 273, 0, :east
unit :archer, 277, 0, :east
unit :sludge, 279, 0, :east
unit :thick_sludge, 281, 0, :east
unit :wizard, 285, 0, :east
unit :sludge, 288, 0, :east
unit :wizard, 297, 0, :east
unit :captive, 306, 0, :east
unit :sludge, 313, 0, :east
unit :captive, 318, 0, :east
unit :wizard, 323, 0, :east
unit :archer, 326, 0, :east
unit :captive, 329, 0, :east
unit :sludge, 332, 0, :east
unit :captive, 335, 0, :east
unit :wizard, 342, 0, :east
unit :wizard, 344, 0, :east
unit :wizard, 346, 0, :east
unit :captive, 348, 0, :east
unit :archer, 349, 0, :east
unit :archer, 355, 0, :east
unit :captive, 358, 0, :east
unit :captive, 359, 0, :east
unit :captive, 360, 0, :east
unit :captive, 362, 0, :east
unit :sludge, 365, 0, :east
unit :captive, 367, 0, :east
unit :sludge, 371, 0, :east
unit :archer, 373, 0, :east
unit :archer, 375, 0, :east
unit :archer, 383, 0, :east
unit :captive, 385, 0, :east
unit :captive, 386, 0, :east
unit :sludge, 390, 0, :east
unit :thick_sludge, 391, 0, :east
unit :captive, 395, 0, :east
unit :thick_sludge, 400, 0, :east
unit :thick_sludge, 404, 0, :east
unit :sludge, 411, 0, :west
unit :thick_sludge, 418, 0, :west
unit :sludge, 423, 0, :west
unit :wizard, 427, 0, :west
unit :sludge, 430, 0, :west
unit :thick_sludge, 441, 0, :west
unit :sludge, 442, 0, :west
unit :thick_sludge, 458, 0, :west
unit :captive, 460, 0, :west
unit :sludge, 462, 0, :west
unit :captive, 464, 0, :west
unit :archer, 466, 0, :west
unit :archer, 470, 0, :west
unit :thick_sludge, 473, 0, :west
unit :thick_sludge, 482, 0, :west
unit :captive, 485, 0, :west
unit :captive, 487, 0, :west
unit :captive, 501, 0, :west
unit :sludge, 505, 0, :west
unit :captive, 506, 0, :west
unit :thick_sludge, 509, 0, :west
unit :wizard, 510, 0, :west
unit :thick_sludge, 522, 0, :west
unit :sludge, 524, 0, :west
unit :sludge, 526, 0, :west
unit :sludge, 530, 0, :west
unit :sludge, 532, 0, :west
unit :captive, 535, 0, :west
unit :thick_sludge, 546, 0, :west
unit :thick_sludge, 551, 0, :west
unit :wizard, 553, 0, :west
unit :captive, 559, 0, :west
unit :thick_sludge, 560, 0, :west
unit :sludge, 567, 0, :west
unit :archer, 571, 0, :west
unit :wizard, 572, 0, :west
unit :sludge, 579, 0, :west
unit :archer, 583, 0, :west
unit :captive, 586, 0, :west
unit :captive, 590, 0, :west
unit :archer, 591, 0, :west
unit :captive, 594, 0, :west
unit :thick_sludge, 596, 0, :west
unit :thick_sludge, 597, 0, :west
unit :thick_sludge, 601, 0, :west
unit :thick_sludge, 618, 0, :west
unit :wizard, 621, 0, :west
unit :archer, 623, 0, :west
unit :captive, 631, 0, :west
unit :thick_sludge, 632, 0, :west
unit :thick_sludge, 635, 0, :west
unit :archer, 638, 0, :west
unit :archer, 639, 0, :west
unit :archer, 644, 0, :west
unit :archer, 651, 0, :west
unit :wizard, 656, 0, :west
unit :sludge, 659, 0, :west
unit :captive, 661, 0, :west
unit :archer, 673, 0, :west
unit :wizard, 678, 0, :west
unit :archer, 684, 0, :west
unit :sludge, 687, 0, :west
unit :captive, 688, 0, :west
unit :sludge, 690, 0, :west
unit :thick_sludge, 693, 0, :west
unit :wizard, 697, 0, :west
unit :wizard, 702, 0, :west
unit :sludge, 705, 0, :west
unit :captive, 707, 0, :west
