#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |Sa C S      s   a a  w    w          a   saCs   a CS      C a S  C  S              s     wC S   a      s    C       w             w     S     Sw        w    C     S s          a      a   w          Ss w     C      C      C  C  s    w      a S       w      w w    a a a      w            SCS  C      s   C   S  S  S a   C   s  w     sC   s C   a S  C s      w S    Sw   Cw SS    wS   ws  s              a  sC                S  S      s s    S  a      CS a       s  s      C  s  C >  a w C s S S  w        S a wS  a  a           S  CCC a s   S w   sw  a S C aaCa   a       s    sS    a aC  s        Ss   s   C  a  a C          a C  @   a     a       w C             w   s     s     w  asS      w   Cw          s  s         C  S    s      w w w  s    s   a  C   s Sa ws SC    a S  S         S  s       C  C       as        C   C   S       SC S S s     C     a  s C C   CCC       S  w  a  w  SS     Cs   a s  ss s  a        CC    a w  s   S w  sw    C      C      w a      w       |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 977
ace_score 4885
size 977, 1
stairs 479, 0

warrior 630, 0, :east

unit :thick_sludge, 0, 0, :east
unit :archer, 1, 0, :east
unit :captive, 3, 0, :east
unit :thick_sludge, 5, 0, :east
unit :sludge, 12, 0, :east
unit :archer, 16, 0, :east
unit :archer, 18, 0, :east
unit :wizard, 21, 0, :east
unit :wizard, 26, 0, :east
unit :archer, 37, 0, :east
unit :sludge, 41, 0, :east
unit :archer, 42, 0, :east
unit :captive, 43, 0, :east
unit :sludge, 44, 0, :east
unit :archer, 48, 0, :east
unit :captive, 50, 0, :east
unit :thick_sludge, 51, 0, :east
unit :captive, 58, 0, :east
unit :archer, 60, 0, :east
unit :thick_sludge, 62, 0, :east
unit :captive, 65, 0, :east
unit :thick_sludge, 68, 0, :east
unit :sludge, 83, 0, :east
unit :wizard, 89, 0, :east
unit :captive, 90, 0, :east
unit :thick_sludge, 92, 0, :east
unit :archer, 96, 0, :east
unit :sludge, 103, 0, :east
unit :captive, 108, 0, :east
unit :wizard, 116, 0, :east
unit :wizard, 130, 0, :east
unit :thick_sludge, 136, 0, :east
unit :thick_sludge, 142, 0, :east
unit :wizard, 143, 0, :east
unit :wizard, 152, 0, :east
unit :captive, 157, 0, :east
unit :thick_sludge, 163, 0, :east
unit :sludge, 165, 0, :east
unit :archer, 176, 0, :east
unit :archer, 183, 0, :east
unit :wizard, 187, 0, :east
unit :thick_sludge, 198, 0, :east
unit :sludge, 199, 0, :east
unit :wizard, 201, 0, :east
unit :captive, 207, 0, :east
unit :captive, 214, 0, :east
unit :captive, 221, 0, :east
unit :captive, 224, 0, :east
unit :sludge, 227, 0, :east
unit :wizard, 232, 0, :east
unit :archer, 239, 0, :east
unit :thick_sludge, 241, 0, :east
unit :wizard, 249, 0, :east
unit :wizard, 256, 0, :east
unit :wizard, 258, 0, :east
unit :archer, 263, 0, :east
unit :archer, 265, 0, :east
unit :archer, 267, 0, :east
unit :wizard, 274, 0, :east
unit :thick_sludge, 287, 0, :east
unit :captive, 288, 0, :east
unit :thick_sludge, 289, 0, :east
unit :captive, 292, 0, :east
unit :sludge, 299, 0, :east
unit :captive, 303, 0, :east
unit :thick_sludge, 307, 0, :east
unit :thick_sludge, 310, 0, :east
unit :thick_sludge, 313, 0, :east
unit :archer, 315, 0, :east
unit :captive, 319, 0, :east
unit :sludge, 323, 0, :east
unit :wizard, 326, 0, :east
unit :sludge, 332, 0, :east
unit :captive, 333, 0, :east
unit :sludge, 337, 0, :east
unit :captive, 339, 0, :east
unit :archer, 343, 0, :east
unit :thick_sludge, 345, 0, :east
unit :captive, 348, 0, :east
unit :sludge, 350, 0, :east
unit :wizard, 357, 0, :east
unit :thick_sludge, 359, 0, :east
unit :thick_sludge, 364, 0, :east
unit :wizard, 365, 0, :east
unit :captive, 369, 0, :east
unit :wizard, 370, 0, :east
unit :thick_sludge, 372, 0, :east
unit :thick_sludge, 373, 0, :east
unit :wizard, 378, 0, :east
unit :thick_sludge, 379, 0, :east
unit :wizard, 383, 0, :east
unit :sludge, 384, 0, :east
unit :sludge, 387, 0, :east
unit :archer, 402, 0, :east
unit :sludge, 405, 0, :east
unit :captive, 406, 0, :east
unit :thick_sludge, 423, 0, :east
unit :thick_sludge, 426, 0, :east
unit :sludge, 433, 0, :east
unit :sludge, 435, 0, :east
unit :thick_sludge, 440, 0, :east
unit :archer, 443, 0, :east
unit :captive, 450, 0, :east
unit :thick_sludge, 451, 0, :east
unit :archer, 453, 0, :east
unit :sludge, 461, 0, :east
unit :sludge, 464, 0, :east
unit :captive, 471, 0, :east
unit :sludge, 474, 0, :east
unit :captive, 477, 0, :east
unit :archer, 482, 0, :east
unit :wizard, 484, 0, :east
unit :captive, 486, 0, :east
unit :sludge, 488, 0, :east
unit :thick_sludge, 490, 0, :east
unit :thick_sludge, 492, 0, :east
unit :wizard, 495, 0, :east
unit :thick_sludge, 504, 0, :east
unit :archer, 506, 0, :east
unit :wizard, 508, 0, :east
unit :thick_sludge, 509, 0, :east
unit :archer, 512, 0, :east
unit :archer, 515, 0, :east
unit :thick_sludge, 527, 0, :east
unit :captive, 530, 0, :east
unit :captive, 531, 0, :east
unit :captive, 532, 0, :east
unit :archer, 534, 0, :east
unit :sludge, 536, 0, :east
unit :thick_sludge, 540, 0, :east
unit :wizard, 542, 0, :east
unit :sludge, 546, 0, :east
unit :wizard, 547, 0, :east
unit :archer, 550, 0, :east
unit :thick_sludge, 552, 0, :east
unit :captive, 554, 0, :east
unit :archer, 556, 0, :east
unit :archer, 557, 0, :east
unit :captive, 558, 0, :east
unit :archer, 559, 0, :east
unit :archer, 563, 0, :east
unit :sludge, 571, 0, :east
unit :sludge, 576, 0, :east
unit :thick_sludge, 577, 0, :east
unit :archer, 582, 0, :east
unit :archer, 584, 0, :east
unit :captive, 585, 0, :east
unit :sludge, 588, 0, :east
unit :thick_sludge, 597, 0, :east
unit :sludge, 598, 0, :east
unit :sludge, 602, 0, :east
unit :captive, 606, 0, :east
unit :archer, 609, 0, :east
unit :archer, 612, 0, :east
unit :captive, 614, 0, :east
unit :archer, 625, 0, :east
unit :captive, 627, 0, :east
unit :archer, 634, 0, :west
unit :archer, 640, 0, :west
unit :wizard, 648, 0, :west
unit :captive, 650, 0, :west
unit :wizard, 664, 0, :west
unit :sludge, 668, 0, :west
unit :sludge, 674, 0, :west
unit :wizard, 680, 0, :west
unit :archer, 683, 0, :west
unit :sludge, 684, 0, :west
unit :thick_sludge, 685, 0, :west
unit :wizard, 692, 0, :west
unit :captive, 696, 0, :west
unit :wizard, 697, 0, :west
unit :sludge, 708, 0, :west
unit :sludge, 711, 0, :west
unit :captive, 721, 0, :west
unit :thick_sludge, 724, 0, :west
unit :sludge, 729, 0, :west
unit :wizard, 736, 0, :west
unit :wizard, 738, 0, :west
unit :wizard, 740, 0, :west
unit :sludge, 743, 0, :west
unit :sludge, 748, 0, :west
unit :archer, 752, 0, :west
unit :captive, 755, 0, :west
unit :sludge, 759, 0, :west
unit :thick_sludge, 761, 0, :west
unit :archer, 762, 0, :west
unit :wizard, 764, 0, :west
unit :sludge, 765, 0, :west
unit :thick_sludge, 767, 0, :west
unit :captive, 768, 0, :west
unit :archer, 773, 0, :west
unit :thick_sludge, 775, 0, :west
unit :thick_sludge, 778, 0, :west
unit :thick_sludge, 788, 0, :west
unit :sludge, 791, 0, :west
unit :captive, 799, 0, :west
unit :captive, 802, 0, :west
unit :archer, 810, 0, :west
unit :sludge, 811, 0, :west
unit :captive, 820, 0, :west
unit :captive, 824, 0, :west
unit :thick_sludge, 828, 0, :west
unit :thick_sludge, 836, 0, :west
unit :captive, 837, 0, :west
unit :thick_sludge, 839, 0, :west
unit :thick_sludge, 841, 0, :west
unit :sludge, 843, 0, :west
unit :captive, 849, 0, :west
unit :archer, 855, 0, :west
unit :sludge, 858, 0, :west
unit :captive, 860, 0, :west
unit :captive, 862, 0, :west
unit :captive, 866, 0, :west
unit :captive, 867, 0, :west
unit :captive, 868, 0, :west
unit :thick_sludge, 876, 0, :west
unit :wizard, 879, 0, :west
unit :archer, 882, 0, :west
unit :wizard, 885, 0, :west
unit :thick_sludge, 888, 0, :west
unit :thick_sludge, 889, 0, :west
unit :captive, 895, 0, :west
unit :sludge, 896, 0, :west
unit :archer, 900, 0, :west
unit :sludge, 902, 0, :west
unit :sludge, 905, 0, :west
unit :sludge, 906, 0, :west
unit :sludge, 908, 0, :west
unit :archer, 911, 0, :west
unit :captive, 920, 0, :west
unit :captive, 921, 0, :west
unit :archer, 926, 0, :west
unit :wizard, 928, 0, :west
unit :sludge, 931, 0, :west
unit :thick_sludge, 935, 0, :west
unit :wizard, 937, 0, :west
unit :sludge, 940, 0, :west
unit :wizard, 941, 0, :west
unit :captive, 946, 0, :west
unit :captive, 953, 0, :west
unit :wizard, 960, 0, :west
unit :archer, 962, 0, :west
unit :wizard, 969, 0, :west
