#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      w          SC ss    w a    S  w w C sa S       a w sC    aS        w s   a S sS       S  w     C a    S  Ss  s   @   sCws     C         s    w   aC s      s        s   s   a      C a S    s    C aw        s     a  S        a s  s s  s            a      w     w            s   C S a C   C S   S  a s C w  wS   S         S    s s          C CSC   s             w         s C      S  Ssa   S Sa  C    a S s  w    a    s C  C  Sss     a        S     a    s          C  S  S S      C> S    s   S w C  Ca   S         s          a sw  Cs   S S     SCaa     sS   S       s         C s       wa  a      s    C  s  a     w    w     w SCs  a    a w    w       a       |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 663
ace_score 3315
size 663, 1
stairs 484, 0

warrior 119, 0, :east

unit :wizard, 6, 0, :east
unit :thick_sludge, 17, 0, :east
unit :captive, 18, 0, :east
unit :sludge, 20, 0, :east
unit :sludge, 21, 0, :east
unit :wizard, 26, 0, :east
unit :archer, 28, 0, :east
unit :thick_sludge, 33, 0, :east
unit :wizard, 36, 0, :east
unit :wizard, 38, 0, :east
unit :captive, 40, 0, :east
unit :sludge, 42, 0, :east
unit :archer, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :archer, 53, 0, :east
unit :wizard, 55, 0, :east
unit :sludge, 57, 0, :east
unit :captive, 58, 0, :east
unit :archer, 63, 0, :east
unit :thick_sludge, 64, 0, :east
unit :wizard, 73, 0, :east
unit :sludge, 75, 0, :east
unit :archer, 79, 0, :east
unit :thick_sludge, 81, 0, :east
unit :sludge, 83, 0, :east
unit :thick_sludge, 84, 0, :east
unit :thick_sludge, 92, 0, :east
unit :wizard, 95, 0, :east
unit :captive, 101, 0, :east
unit :archer, 103, 0, :east
unit :thick_sludge, 108, 0, :east
unit :thick_sludge, 111, 0, :east
unit :sludge, 112, 0, :east
unit :sludge, 115, 0, :east
unit :sludge, 123, 0, :west
unit :captive, 124, 0, :west
unit :wizard, 125, 0, :west
unit :sludge, 126, 0, :west
unit :captive, 132, 0, :west
unit :sludge, 142, 0, :west
unit :wizard, 147, 0, :west
unit :archer, 151, 0, :west
unit :captive, 152, 0, :west
unit :sludge, 154, 0, :west
unit :sludge, 161, 0, :west
unit :sludge, 170, 0, :west
unit :sludge, 174, 0, :west
unit :archer, 178, 0, :west
unit :captive, 185, 0, :west
unit :archer, 187, 0, :west
unit :thick_sludge, 189, 0, :west
unit :sludge, 194, 0, :west
unit :captive, 199, 0, :west
unit :archer, 201, 0, :west
unit :wizard, 202, 0, :west
unit :sludge, 211, 0, :west
unit :archer, 217, 0, :west
unit :thick_sludge, 220, 0, :west
unit :archer, 229, 0, :west
unit :sludge, 231, 0, :west
unit :sludge, 234, 0, :west
unit :sludge, 236, 0, :west
unit :sludge, 239, 0, :west
unit :archer, 252, 0, :west
unit :wizard, 259, 0, :west
unit :wizard, 265, 0, :west
unit :sludge, 278, 0, :west
unit :captive, 282, 0, :west
unit :thick_sludge, 284, 0, :west
unit :archer, 286, 0, :west
unit :captive, 288, 0, :west
unit :captive, 292, 0, :west
unit :thick_sludge, 294, 0, :west
unit :thick_sludge, 298, 0, :west
unit :archer, 301, 0, :west
unit :sludge, 303, 0, :west
unit :captive, 305, 0, :west
unit :wizard, 307, 0, :west
unit :wizard, 310, 0, :west
unit :thick_sludge, 311, 0, :west
unit :thick_sludge, 315, 0, :west
unit :thick_sludge, 325, 0, :west
unit :sludge, 330, 0, :west
unit :sludge, 332, 0, :west
unit :captive, 343, 0, :west
unit :captive, 345, 0, :west
unit :thick_sludge, 346, 0, :west
unit :captive, 347, 0, :west
unit :sludge, 351, 0, :west
unit :wizard, 365, 0, :west
unit :sludge, 375, 0, :west
unit :captive, 377, 0, :west
unit :thick_sludge, 384, 0, :west
unit :thick_sludge, 387, 0, :west
unit :sludge, 388, 0, :west
unit :archer, 389, 0, :west
unit :thick_sludge, 393, 0, :west
unit :thick_sludge, 395, 0, :west
unit :archer, 396, 0, :west
unit :captive, 399, 0, :west
unit :archer, 404, 0, :west
unit :thick_sludge, 406, 0, :west
unit :sludge, 408, 0, :west
unit :wizard, 411, 0, :west
unit :archer, 416, 0, :west
unit :sludge, 421, 0, :west
unit :captive, 423, 0, :west
unit :captive, 426, 0, :west
unit :thick_sludge, 429, 0, :west
unit :sludge, 430, 0, :west
unit :sludge, 431, 0, :west
unit :archer, 437, 0, :west
unit :thick_sludge, 446, 0, :west
unit :archer, 452, 0, :west
unit :sludge, 457, 0, :west
unit :captive, 468, 0, :west
unit :thick_sludge, 471, 0, :west
unit :thick_sludge, 474, 0, :west
unit :thick_sludge, 476, 0, :west
unit :captive, 483, 0, :west
unit :thick_sludge, 486, 0, :west
unit :sludge, 491, 0, :west
unit :thick_sludge, 495, 0, :west
unit :wizard, 497, 0, :west
unit :captive, 499, 0, :west
unit :captive, 502, 0, :west
unit :archer, 503, 0, :west
unit :thick_sludge, 507, 0, :west
unit :sludge, 517, 0, :west
unit :archer, 528, 0, :west
unit :sludge, 530, 0, :west
unit :wizard, 531, 0, :west
unit :captive, 534, 0, :west
unit :sludge, 535, 0, :west
unit :thick_sludge, 539, 0, :west
unit :thick_sludge, 541, 0, :west
unit :thick_sludge, 547, 0, :west
unit :captive, 548, 0, :west
unit :archer, 549, 0, :west
unit :archer, 550, 0, :west
unit :sludge, 556, 0, :west
unit :thick_sludge, 557, 0, :west
unit :thick_sludge, 561, 0, :west
unit :sludge, 569, 0, :west
unit :captive, 579, 0, :west
unit :sludge, 581, 0, :west
unit :wizard, 589, 0, :west
unit :archer, 590, 0, :west
unit :archer, 593, 0, :west
unit :sludge, 600, 0, :west
unit :captive, 605, 0, :west
unit :sludge, 608, 0, :west
unit :archer, 611, 0, :west
unit :wizard, 617, 0, :west
unit :wizard, 622, 0, :west
unit :wizard, 628, 0, :west
unit :thick_sludge, 630, 0, :west
unit :captive, 631, 0, :west
unit :sludge, 632, 0, :west
unit :archer, 635, 0, :west
unit :archer, 640, 0, :west
unit :wizard, 642, 0, :west
unit :wizard, 647, 0, :west
unit :archer, 655, 0, :west
