#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       a  SsS  S C  a w  C      CCS   w  a s s    s s  w s                     w   a   CCC  aa    a   a a     S S a       a  C    s      s        s w            a a       a     Sa>     s  s S a     w       S               a      s  CsCs w        w       w       S     s       a           Sw  s     a  S S a  w        S  C     C     s a     w      C     s   sC    aw  sS sS S S      C    C S      s a    sa     w CC   s S  a  C  s   w S        s    w  a  Ss   C   s     w    C       w Ss a  s      a     a    S w    a aS    w   S   a   S C  a  w  C   C  as    a aC         w  s  S        s    w    C   s   a   w a  s   s  s     @     w C sa  s s|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 644
ace_score 3220
size 644, 1
stairs 179, 0

warrior 627, 0, :east

unit :archer, 7, 0, :east
unit :thick_sludge, 10, 0, :east
unit :sludge, 11, 0, :east
unit :thick_sludge, 12, 0, :east
unit :thick_sludge, 15, 0, :east
unit :captive, 17, 0, :east
unit :archer, 20, 0, :east
unit :wizard, 22, 0, :east
unit :captive, 25, 0, :east
unit :captive, 32, 0, :east
unit :captive, 33, 0, :east
unit :thick_sludge, 34, 0, :east
unit :wizard, 38, 0, :east
unit :archer, 41, 0, :east
unit :sludge, 43, 0, :east
unit :sludge, 45, 0, :east
unit :sludge, 50, 0, :east
unit :sludge, 52, 0, :east
unit :wizard, 55, 0, :east
unit :sludge, 57, 0, :east
unit :wizard, 79, 0, :east
unit :archer, 83, 0, :east
unit :captive, 87, 0, :east
unit :captive, 88, 0, :east
unit :captive, 89, 0, :east
unit :archer, 92, 0, :east
unit :archer, 93, 0, :east
unit :archer, 98, 0, :east
unit :archer, 102, 0, :east
unit :archer, 104, 0, :east
unit :thick_sludge, 110, 0, :east
unit :thick_sludge, 112, 0, :east
unit :archer, 114, 0, :east
unit :archer, 122, 0, :east
unit :captive, 125, 0, :east
unit :sludge, 130, 0, :east
unit :sludge, 137, 0, :east
unit :sludge, 146, 0, :east
unit :wizard, 148, 0, :east
unit :archer, 161, 0, :east
unit :archer, 163, 0, :east
unit :archer, 171, 0, :east
unit :thick_sludge, 177, 0, :east
unit :archer, 178, 0, :east
unit :sludge, 185, 0, :east
unit :sludge, 188, 0, :east
unit :thick_sludge, 190, 0, :east
unit :archer, 192, 0, :east
unit :wizard, 198, 0, :east
unit :thick_sludge, 206, 0, :east
unit :archer, 222, 0, :east
unit :sludge, 229, 0, :east
unit :captive, 232, 0, :east
unit :sludge, 233, 0, :east
unit :captive, 234, 0, :east
unit :sludge, 235, 0, :east
unit :wizard, 237, 0, :east
unit :wizard, 246, 0, :east
unit :wizard, 254, 0, :east
unit :thick_sludge, 262, 0, :east
unit :sludge, 268, 0, :east
unit :archer, 276, 0, :east
unit :thick_sludge, 288, 0, :east
unit :wizard, 289, 0, :east
unit :sludge, 292, 0, :east
unit :archer, 298, 0, :east
unit :thick_sludge, 301, 0, :east
unit :thick_sludge, 303, 0, :east
unit :archer, 305, 0, :east
unit :wizard, 308, 0, :east
unit :thick_sludge, 317, 0, :east
unit :captive, 320, 0, :east
unit :captive, 326, 0, :east
unit :sludge, 332, 0, :east
unit :archer, 334, 0, :east
unit :wizard, 340, 0, :east
unit :captive, 347, 0, :east
unit :sludge, 353, 0, :east
unit :sludge, 357, 0, :east
unit :captive, 358, 0, :east
unit :archer, 363, 0, :east
unit :wizard, 364, 0, :east
unit :sludge, 367, 0, :east
unit :thick_sludge, 368, 0, :east
unit :sludge, 370, 0, :east
unit :thick_sludge, 371, 0, :east
unit :thick_sludge, 373, 0, :east
unit :thick_sludge, 375, 0, :east
unit :captive, 382, 0, :east
unit :captive, 387, 0, :east
unit :thick_sludge, 389, 0, :east
unit :sludge, 396, 0, :east
unit :archer, 398, 0, :east
unit :sludge, 403, 0, :east
unit :archer, 404, 0, :east
unit :wizard, 410, 0, :east
unit :captive, 412, 0, :east
unit :captive, 413, 0, :east
unit :sludge, 417, 0, :east
unit :thick_sludge, 419, 0, :east
unit :archer, 422, 0, :east
unit :captive, 425, 0, :east
unit :sludge, 428, 0, :east
unit :wizard, 432, 0, :east
unit :thick_sludge, 434, 0, :east
unit :sludge, 443, 0, :east
unit :wizard, 448, 0, :east
unit :archer, 451, 0, :east
unit :thick_sludge, 454, 0, :east
unit :sludge, 455, 0, :east
unit :captive, 459, 0, :east
unit :sludge, 463, 0, :east
unit :wizard, 469, 0, :east
unit :captive, 474, 0, :east
unit :wizard, 482, 0, :east
unit :thick_sludge, 484, 0, :east
unit :sludge, 485, 0, :east
unit :archer, 487, 0, :east
unit :sludge, 490, 0, :east
unit :archer, 497, 0, :east
unit :archer, 503, 0, :east
unit :thick_sludge, 508, 0, :east
unit :wizard, 510, 0, :east
unit :archer, 515, 0, :east
unit :archer, 517, 0, :east
unit :thick_sludge, 518, 0, :east
unit :wizard, 523, 0, :east
unit :thick_sludge, 527, 0, :east
unit :archer, 531, 0, :east
unit :thick_sludge, 535, 0, :east
unit :captive, 537, 0, :east
unit :archer, 540, 0, :east
unit :wizard, 543, 0, :east
unit :captive, 546, 0, :east
unit :captive, 550, 0, :east
unit :archer, 553, 0, :east
unit :sludge, 554, 0, :east
unit :archer, 559, 0, :east
unit :archer, 561, 0, :east
unit :captive, 562, 0, :east
unit :wizard, 572, 0, :east
unit :sludge, 575, 0, :east
unit :thick_sludge, 578, 0, :east
unit :sludge, 587, 0, :east
unit :wizard, 592, 0, :east
unit :captive, 597, 0, :east
unit :sludge, 601, 0, :east
unit :archer, 605, 0, :east
unit :wizard, 609, 0, :east
unit :archer, 611, 0, :east
unit :sludge, 614, 0, :east
unit :sludge, 618, 0, :east
unit :sludge, 621, 0, :east
unit :wizard, 633, 0, :west
unit :captive, 635, 0, :west
unit :sludge, 637, 0, :west
unit :archer, 638, 0, :west
unit :sludge, 641, 0, :west
unit :sludge, 643, 0, :west
