#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  a   S    C  w    s   C     a              C     S w     C   wS  ass  a  a  sC a      C   C                  wS S   S      C a  a S     SC    sw       a  Ssw w        S    C          s w    S C      s    swC    Ss  Sa   s    aC s     s   a    w      wa  w   w  a    s      C    s  S   a    w  a a   s     S s   S   C        w   C        sC                         s   sSC s   s w    sS       C          ws  S    w   S        Sw  w  a s S  S      s       C C   a  w C      a  s      CS    w    s   Sa     Ss    w a aC     SC wS     a  w      C         w   a       SS C         as w s     a  aS sS     aaa w    w   sw aS   aSw S w    C       a      s        C     S   S   @         s   as   CS      sS  Ss     s > Sa     w        S a  Ca            C  S sS     C     a            C        w  sCs   wC       C   w     C a  sC S s        C w    S   C  S    Sa a w C  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 864
ace_score 4320
size 864, 1
stairs 711, 0

warrior 671, 0, :east

unit :archer, 2, 0, :east
unit :thick_sludge, 6, 0, :east
unit :captive, 11, 0, :east
unit :wizard, 14, 0, :east
unit :sludge, 19, 0, :east
unit :captive, 23, 0, :east
unit :archer, 29, 0, :east
unit :captive, 44, 0, :east
unit :thick_sludge, 50, 0, :east
unit :wizard, 52, 0, :east
unit :captive, 58, 0, :east
unit :wizard, 62, 0, :east
unit :thick_sludge, 63, 0, :east
unit :archer, 66, 0, :east
unit :sludge, 67, 0, :east
unit :sludge, 68, 0, :east
unit :archer, 71, 0, :east
unit :archer, 74, 0, :east
unit :sludge, 77, 0, :east
unit :captive, 78, 0, :east
unit :archer, 80, 0, :east
unit :captive, 87, 0, :east
unit :captive, 91, 0, :east
unit :wizard, 110, 0, :east
unit :thick_sludge, 111, 0, :east
unit :thick_sludge, 113, 0, :east
unit :thick_sludge, 117, 0, :east
unit :captive, 124, 0, :east
unit :archer, 126, 0, :east
unit :archer, 129, 0, :east
unit :thick_sludge, 131, 0, :east
unit :thick_sludge, 137, 0, :east
unit :captive, 138, 0, :east
unit :sludge, 143, 0, :east
unit :wizard, 144, 0, :east
unit :archer, 152, 0, :east
unit :thick_sludge, 155, 0, :east
unit :sludge, 156, 0, :east
unit :wizard, 157, 0, :east
unit :wizard, 159, 0, :east
unit :thick_sludge, 168, 0, :east
unit :captive, 173, 0, :east
unit :sludge, 184, 0, :east
unit :wizard, 186, 0, :east
unit :thick_sludge, 191, 0, :east
unit :captive, 193, 0, :east
unit :sludge, 200, 0, :east
unit :sludge, 205, 0, :east
unit :wizard, 206, 0, :east
unit :captive, 207, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 213, 0, :east
unit :thick_sludge, 216, 0, :east
unit :archer, 217, 0, :east
unit :sludge, 221, 0, :east
unit :archer, 226, 0, :east
unit :captive, 227, 0, :east
unit :sludge, 229, 0, :east
unit :sludge, 235, 0, :east
unit :archer, 239, 0, :east
unit :wizard, 244, 0, :east
unit :wizard, 251, 0, :east
unit :archer, 252, 0, :east
unit :wizard, 255, 0, :east
unit :wizard, 259, 0, :east
unit :archer, 262, 0, :east
unit :sludge, 267, 0, :east
unit :captive, 274, 0, :east
unit :sludge, 279, 0, :east
unit :thick_sludge, 282, 0, :east
unit :archer, 286, 0, :east
unit :wizard, 291, 0, :east
unit :archer, 294, 0, :east
unit :archer, 296, 0, :east
unit :sludge, 300, 0, :east
unit :thick_sludge, 306, 0, :east
unit :sludge, 308, 0, :east
unit :thick_sludge, 312, 0, :east
unit :captive, 316, 0, :east
unit :wizard, 325, 0, :east
unit :captive, 329, 0, :east
unit :sludge, 338, 0, :east
unit :captive, 339, 0, :east
unit :sludge, 365, 0, :east
unit :sludge, 369, 0, :east
unit :thick_sludge, 370, 0, :east
unit :captive, 371, 0, :east
unit :sludge, 373, 0, :east
unit :sludge, 377, 0, :east
unit :wizard, 379, 0, :east
unit :sludge, 384, 0, :east
unit :thick_sludge, 385, 0, :east
unit :captive, 393, 0, :east
unit :wizard, 404, 0, :east
unit :sludge, 405, 0, :east
unit :thick_sludge, 408, 0, :east
unit :wizard, 413, 0, :east
unit :thick_sludge, 417, 0, :east
unit :thick_sludge, 426, 0, :east
unit :wizard, 427, 0, :east
unit :wizard, 430, 0, :east
unit :archer, 433, 0, :east
unit :sludge, 435, 0, :east
unit :thick_sludge, 437, 0, :east
unit :thick_sludge, 440, 0, :east
unit :sludge, 447, 0, :east
unit :captive, 455, 0, :east
unit :captive, 457, 0, :east
unit :archer, 461, 0, :east
unit :wizard, 464, 0, :east
unit :captive, 466, 0, :east
unit :archer, 473, 0, :east
unit :sludge, 476, 0, :east
unit :captive, 483, 0, :east
unit :thick_sludge, 484, 0, :east
unit :wizard, 489, 0, :east
unit :sludge, 494, 0, :east
unit :thick_sludge, 498, 0, :east
unit :archer, 499, 0, :east
unit :thick_sludge, 505, 0, :east
unit :sludge, 506, 0, :east
unit :wizard, 511, 0, :east
unit :archer, 513, 0, :east
unit :archer, 515, 0, :east
unit :captive, 516, 0, :east
unit :thick_sludge, 522, 0, :east
unit :captive, 523, 0, :east
unit :wizard, 525, 0, :east
unit :thick_sludge, 526, 0, :east
unit :archer, 532, 0, :east
unit :wizard, 535, 0, :east
unit :captive, 542, 0, :east
unit :wizard, 552, 0, :east
unit :archer, 556, 0, :east
unit :thick_sludge, 564, 0, :east
unit :thick_sludge, 565, 0, :east
unit :captive, 567, 0, :east
unit :archer, 577, 0, :east
unit :sludge, 578, 0, :east
unit :wizard, 580, 0, :east
unit :sludge, 582, 0, :east
unit :archer, 588, 0, :east
unit :archer, 591, 0, :east
unit :thick_sludge, 592, 0, :east
unit :sludge, 594, 0, :east
unit :thick_sludge, 595, 0, :east
unit :archer, 601, 0, :east
unit :archer, 602, 0, :east
unit :archer, 603, 0, :east
unit :wizard, 605, 0, :east
unit :wizard, 610, 0, :east
unit :sludge, 614, 0, :east
unit :wizard, 615, 0, :east
unit :archer, 617, 0, :east
unit :thick_sludge, 618, 0, :east
unit :archer, 622, 0, :east
unit :thick_sludge, 623, 0, :east
unit :wizard, 624, 0, :east
unit :thick_sludge, 626, 0, :east
unit :wizard, 628, 0, :east
unit :captive, 633, 0, :east
unit :archer, 641, 0, :east
unit :sludge, 648, 0, :east
unit :captive, 657, 0, :east
unit :thick_sludge, 663, 0, :east
unit :thick_sludge, 667, 0, :east
unit :sludge, 681, 0, :west
unit :archer, 685, 0, :west
unit :sludge, 686, 0, :west
unit :captive, 690, 0, :west
unit :thick_sludge, 691, 0, :west
unit :sludge, 698, 0, :west
unit :thick_sludge, 699, 0, :west
unit :thick_sludge, 702, 0, :west
unit :sludge, 703, 0, :west
unit :sludge, 709, 0, :west
unit :thick_sludge, 713, 0, :west
unit :archer, 714, 0, :west
unit :wizard, 720, 0, :west
unit :thick_sludge, 729, 0, :west
unit :archer, 731, 0, :west
unit :captive, 734, 0, :west
unit :archer, 735, 0, :west
unit :captive, 748, 0, :west
unit :thick_sludge, 751, 0, :west
unit :sludge, 753, 0, :west
unit :thick_sludge, 754, 0, :west
unit :captive, 760, 0, :west
unit :archer, 766, 0, :west
unit :captive, 779, 0, :west
unit :wizard, 788, 0, :west
unit :sludge, 791, 0, :west
unit :captive, 792, 0, :west
unit :sludge, 793, 0, :west
unit :wizard, 797, 0, :west
unit :captive, 798, 0, :west
unit :captive, 806, 0, :west
unit :wizard, 810, 0, :west
unit :captive, 816, 0, :west
unit :archer, 818, 0, :west
unit :sludge, 821, 0, :west
unit :captive, 822, 0, :west
unit :thick_sludge, 824, 0, :west
unit :sludge, 826, 0, :west
unit :captive, 835, 0, :west
unit :wizard, 837, 0, :west
unit :thick_sludge, 842, 0, :west
unit :captive, 846, 0, :west
unit :thick_sludge, 849, 0, :west
unit :thick_sludge, 854, 0, :west
unit :archer, 855, 0, :west
unit :archer, 857, 0, :west
unit :wizard, 859, 0, :west
unit :captive, 861, 0, :west
