#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   S         C s  S       a  s sw SCC     CC S       S     a     w    C    w w      sS      s   S s S    CC sCs as     S   S  sw  a  C   a SC ss    S   s   w    a a CsSa s  aC         ss a   SS           ws   Sa              s             S  w  w  Cs      s  w C  w  S   a               >  a    w       Sws      S                S     s  aa         wC S      S     w  a   C       C C   S         s  S  s w    S  w   a a w        Sws   S  s       w s            a    w SCC  @   S              CSS w       w Cs s  S S    w       s              w   s   sC  SC S a      a ssSa w s   C  a     a       C C Cs  w  C   a    a    s    a        S   S  a     s    a SC    s  s       a           S   s     w a        as s  C  w      C  a    a   w   SC a    s     w   a w    S   a C    |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 773
ace_score 3865
size 773, 1
stairs 287, 0

warrior 473, 0, :east

unit :thick_sludge, 3, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 15, 0, :east
unit :thick_sludge, 18, 0, :east
unit :archer, 26, 0, :east
unit :sludge, 29, 0, :east
unit :sludge, 31, 0, :east
unit :wizard, 32, 0, :east
unit :thick_sludge, 34, 0, :east
unit :captive, 35, 0, :east
unit :captive, 36, 0, :east
unit :captive, 42, 0, :east
unit :captive, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :thick_sludge, 53, 0, :east
unit :archer, 59, 0, :east
unit :wizard, 65, 0, :east
unit :captive, 70, 0, :east
unit :wizard, 75, 0, :east
unit :wizard, 77, 0, :east
unit :sludge, 84, 0, :east
unit :thick_sludge, 85, 0, :east
unit :sludge, 92, 0, :east
unit :thick_sludge, 96, 0, :east
unit :sludge, 98, 0, :east
unit :thick_sludge, 100, 0, :east
unit :captive, 105, 0, :east
unit :captive, 106, 0, :east
unit :sludge, 108, 0, :east
unit :captive, 109, 0, :east
unit :sludge, 110, 0, :east
unit :archer, 112, 0, :east
unit :sludge, 113, 0, :east
unit :thick_sludge, 119, 0, :east
unit :thick_sludge, 123, 0, :east
unit :sludge, 126, 0, :east
unit :wizard, 127, 0, :east
unit :archer, 130, 0, :east
unit :captive, 133, 0, :east
unit :archer, 137, 0, :east
unit :thick_sludge, 139, 0, :east
unit :captive, 140, 0, :east
unit :sludge, 142, 0, :east
unit :sludge, 143, 0, :east
unit :thick_sludge, 148, 0, :east
unit :sludge, 152, 0, :east
unit :wizard, 156, 0, :east
unit :archer, 161, 0, :east
unit :archer, 163, 0, :east
unit :captive, 165, 0, :east
unit :sludge, 166, 0, :east
unit :thick_sludge, 167, 0, :east
unit :archer, 168, 0, :east
unit :sludge, 170, 0, :east
unit :archer, 173, 0, :east
unit :captive, 174, 0, :east
unit :sludge, 184, 0, :east
unit :sludge, 185, 0, :east
unit :archer, 187, 0, :east
unit :thick_sludge, 191, 0, :east
unit :thick_sludge, 192, 0, :east
unit :wizard, 204, 0, :east
unit :sludge, 205, 0, :east
unit :thick_sludge, 209, 0, :east
unit :archer, 210, 0, :east
unit :sludge, 225, 0, :east
unit :thick_sludge, 239, 0, :east
unit :wizard, 242, 0, :east
unit :wizard, 245, 0, :east
unit :captive, 248, 0, :east
unit :sludge, 249, 0, :east
unit :sludge, 256, 0, :east
unit :wizard, 259, 0, :east
unit :captive, 261, 0, :east
unit :wizard, 264, 0, :east
unit :thick_sludge, 267, 0, :east
unit :archer, 271, 0, :east
unit :archer, 290, 0, :east
unit :wizard, 295, 0, :east
unit :thick_sludge, 303, 0, :east
unit :wizard, 304, 0, :east
unit :sludge, 305, 0, :east
unit :thick_sludge, 312, 0, :east
unit :thick_sludge, 329, 0, :east
unit :sludge, 335, 0, :east
unit :archer, 338, 0, :east
unit :archer, 339, 0, :east
unit :wizard, 349, 0, :east
unit :captive, 350, 0, :east
unit :thick_sludge, 352, 0, :east
unit :thick_sludge, 359, 0, :east
unit :wizard, 365, 0, :east
unit :archer, 368, 0, :east
unit :captive, 372, 0, :east
unit :captive, 380, 0, :east
unit :captive, 382, 0, :east
unit :thick_sludge, 386, 0, :east
unit :sludge, 396, 0, :east
unit :thick_sludge, 399, 0, :east
unit :sludge, 402, 0, :east
unit :wizard, 404, 0, :east
unit :thick_sludge, 409, 0, :east
unit :wizard, 412, 0, :east
unit :archer, 416, 0, :east
unit :archer, 418, 0, :east
unit :wizard, 420, 0, :east
unit :thick_sludge, 429, 0, :east
unit :wizard, 430, 0, :east
unit :sludge, 431, 0, :east
unit :thick_sludge, 435, 0, :east
unit :sludge, 438, 0, :east
unit :wizard, 446, 0, :east
unit :sludge, 448, 0, :east
unit :archer, 461, 0, :east
unit :wizard, 466, 0, :east
unit :thick_sludge, 468, 0, :east
unit :captive, 469, 0, :east
unit :captive, 470, 0, :east
unit :thick_sludge, 477, 0, :west
unit :captive, 492, 0, :west
unit :thick_sludge, 493, 0, :west
unit :thick_sludge, 494, 0, :west
unit :wizard, 496, 0, :west
unit :wizard, 504, 0, :west
unit :captive, 506, 0, :west
unit :sludge, 507, 0, :west
unit :sludge, 509, 0, :west
unit :thick_sludge, 512, 0, :west
unit :thick_sludge, 514, 0, :west
unit :wizard, 519, 0, :west
unit :sludge, 527, 0, :west
unit :wizard, 542, 0, :west
unit :sludge, 546, 0, :west
unit :sludge, 550, 0, :west
unit :captive, 551, 0, :west
unit :thick_sludge, 554, 0, :west
unit :captive, 555, 0, :west
unit :thick_sludge, 557, 0, :west
unit :archer, 559, 0, :west
unit :archer, 566, 0, :west
unit :sludge, 568, 0, :west
unit :sludge, 569, 0, :west
unit :thick_sludge, 570, 0, :west
unit :archer, 571, 0, :west
unit :wizard, 573, 0, :west
unit :sludge, 575, 0, :west
unit :captive, 579, 0, :west
unit :archer, 582, 0, :west
unit :archer, 588, 0, :west
unit :captive, 596, 0, :west
unit :captive, 598, 0, :west
unit :captive, 600, 0, :west
unit :sludge, 601, 0, :west
unit :wizard, 604, 0, :west
unit :captive, 607, 0, :west
unit :archer, 611, 0, :west
unit :archer, 616, 0, :west
unit :sludge, 621, 0, :west
unit :archer, 626, 0, :west
unit :thick_sludge, 635, 0, :west
unit :thick_sludge, 639, 0, :west
unit :archer, 642, 0, :west
unit :sludge, 648, 0, :west
unit :archer, 653, 0, :west
unit :thick_sludge, 655, 0, :west
unit :captive, 656, 0, :west
unit :sludge, 661, 0, :west
unit :sludge, 664, 0, :west
unit :archer, 672, 0, :west
unit :thick_sludge, 684, 0, :west
unit :sludge, 688, 0, :west
unit :wizard, 694, 0, :west
unit :archer, 696, 0, :west
unit :archer, 705, 0, :west
unit :sludge, 706, 0, :west
unit :sludge, 708, 0, :west
unit :captive, 711, 0, :west
unit :wizard, 714, 0, :west
unit :captive, 721, 0, :west
unit :archer, 724, 0, :west
unit :archer, 729, 0, :west
unit :wizard, 733, 0, :west
unit :thick_sludge, 737, 0, :west
unit :captive, 738, 0, :west
unit :archer, 740, 0, :west
unit :sludge, 745, 0, :west
unit :wizard, 751, 0, :west
unit :archer, 755, 0, :west
unit :wizard, 757, 0, :west
unit :thick_sludge, 762, 0, :west
unit :archer, 766, 0, :west
unit :captive, 768, 0, :west
