#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    CS       C  s     Sa s     w      S     s       s               @        C  w              C          w     s  C  wCa S w   Cs   sCS a   C  CCS    w  sS    a            S       w       w a  S  a a  CssC C  SS  s w     w     S     w  s    swSS     s  S C  S wa             s S         w    C       C  a SC     s aa w  s C  C    w s      Csw    S as>w      S   w  C    s  Cs  Ss         C   w wC a            S   CC     w w    sa w        sC         S  S   s    s                Ca      a  C  w    sCSS S      a     w     w   C a  C C           w ss      C    w w  C   S      C   s        w S C     C      w  w  w         Ss       w  S CsSas   s   S     |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 656
ace_score 3280
size 656, 1
stairs 351, 0

warrior 68, 0, :east

unit :captive, 4, 0, :east
unit :thick_sludge, 5, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 16, 0, :east
unit :thick_sludge, 22, 0, :east
unit :archer, 23, 0, :east
unit :sludge, 25, 0, :east
unit :wizard, 31, 0, :east
unit :thick_sludge, 38, 0, :east
unit :sludge, 44, 0, :east
unit :sludge, 52, 0, :east
unit :captive, 77, 0, :west
unit :wizard, 80, 0, :west
unit :captive, 95, 0, :west
unit :wizard, 106, 0, :west
unit :sludge, 112, 0, :west
unit :captive, 115, 0, :west
unit :wizard, 118, 0, :west
unit :captive, 119, 0, :west
unit :archer, 120, 0, :west
unit :thick_sludge, 122, 0, :west
unit :wizard, 124, 0, :west
unit :captive, 128, 0, :west
unit :sludge, 129, 0, :west
unit :sludge, 133, 0, :west
unit :captive, 134, 0, :west
unit :thick_sludge, 135, 0, :west
unit :archer, 137, 0, :west
unit :captive, 141, 0, :west
unit :captive, 144, 0, :west
unit :captive, 145, 0, :west
unit :thick_sludge, 146, 0, :west
unit :wizard, 151, 0, :west
unit :sludge, 154, 0, :west
unit :thick_sludge, 155, 0, :west
unit :archer, 160, 0, :west
unit :thick_sludge, 173, 0, :west
unit :wizard, 181, 0, :west
unit :wizard, 189, 0, :west
unit :archer, 191, 0, :west
unit :thick_sludge, 194, 0, :west
unit :archer, 197, 0, :west
unit :archer, 199, 0, :west
unit :captive, 202, 0, :west
unit :sludge, 203, 0, :west
unit :sludge, 204, 0, :west
unit :captive, 205, 0, :west
unit :captive, 207, 0, :west
unit :thick_sludge, 210, 0, :west
unit :thick_sludge, 211, 0, :west
unit :sludge, 214, 0, :west
unit :wizard, 216, 0, :west
unit :wizard, 222, 0, :west
unit :thick_sludge, 228, 0, :west
unit :wizard, 234, 0, :west
unit :sludge, 237, 0, :west
unit :sludge, 242, 0, :west
unit :wizard, 243, 0, :west
unit :thick_sludge, 244, 0, :west
unit :thick_sludge, 245, 0, :west
unit :sludge, 251, 0, :west
unit :thick_sludge, 254, 0, :west
unit :captive, 256, 0, :west
unit :thick_sludge, 259, 0, :west
unit :wizard, 261, 0, :west
unit :archer, 262, 0, :west
unit :sludge, 276, 0, :west
unit :thick_sludge, 278, 0, :west
unit :wizard, 288, 0, :west
unit :captive, 293, 0, :west
unit :captive, 301, 0, :west
unit :archer, 304, 0, :west
unit :thick_sludge, 306, 0, :west
unit :captive, 307, 0, :west
unit :sludge, 313, 0, :west
unit :archer, 315, 0, :west
unit :archer, 316, 0, :west
unit :wizard, 318, 0, :west
unit :sludge, 321, 0, :west
unit :captive, 323, 0, :west
unit :captive, 326, 0, :west
unit :wizard, 331, 0, :west
unit :sludge, 333, 0, :west
unit :captive, 340, 0, :west
unit :sludge, 341, 0, :west
unit :wizard, 342, 0, :west
unit :thick_sludge, 347, 0, :west
unit :archer, 349, 0, :west
unit :sludge, 350, 0, :west
unit :wizard, 352, 0, :west
unit :thick_sludge, 359, 0, :west
unit :wizard, 363, 0, :west
unit :captive, 366, 0, :west
unit :sludge, 371, 0, :west
unit :captive, 374, 0, :west
unit :sludge, 375, 0, :west
unit :thick_sludge, 378, 0, :west
unit :sludge, 379, 0, :west
unit :captive, 389, 0, :west
unit :wizard, 393, 0, :west
unit :wizard, 395, 0, :west
unit :captive, 396, 0, :west
unit :archer, 398, 0, :west
unit :thick_sludge, 411, 0, :west
unit :captive, 415, 0, :west
unit :captive, 416, 0, :west
unit :wizard, 422, 0, :west
unit :wizard, 424, 0, :west
unit :sludge, 429, 0, :west
unit :archer, 430, 0, :west
unit :wizard, 432, 0, :west
unit :sludge, 441, 0, :west
unit :captive, 442, 0, :west
unit :thick_sludge, 452, 0, :west
unit :thick_sludge, 455, 0, :west
unit :sludge, 459, 0, :west
unit :sludge, 464, 0, :west
unit :captive, 481, 0, :west
unit :archer, 482, 0, :west
unit :archer, 489, 0, :west
unit :captive, 492, 0, :west
unit :wizard, 495, 0, :west
unit :sludge, 500, 0, :west
unit :captive, 501, 0, :west
unit :thick_sludge, 502, 0, :west
unit :thick_sludge, 503, 0, :west
unit :thick_sludge, 505, 0, :west
unit :archer, 512, 0, :west
unit :wizard, 518, 0, :west
unit :wizard, 524, 0, :west
unit :captive, 528, 0, :west
unit :archer, 530, 0, :west
unit :captive, 533, 0, :west
unit :captive, 535, 0, :west
unit :wizard, 547, 0, :west
unit :sludge, 549, 0, :west
unit :sludge, 550, 0, :west
unit :captive, 557, 0, :west
unit :wizard, 562, 0, :west
unit :wizard, 564, 0, :west
unit :captive, 567, 0, :west
unit :thick_sludge, 571, 0, :west
unit :captive, 578, 0, :west
unit :sludge, 582, 0, :west
unit :wizard, 591, 0, :west
unit :thick_sludge, 593, 0, :west
unit :captive, 595, 0, :west
unit :captive, 601, 0, :west
unit :wizard, 608, 0, :west
unit :wizard, 611, 0, :west
unit :wizard, 614, 0, :west
unit :thick_sludge, 624, 0, :west
unit :sludge, 625, 0, :west
unit :wizard, 633, 0, :west
unit :thick_sludge, 636, 0, :west
unit :captive, 638, 0, :west
unit :sludge, 639, 0, :west
unit :thick_sludge, 640, 0, :west
unit :archer, 641, 0, :west
unit :sludge, 642, 0, :west
unit :sludge, 646, 0, :west
unit :thick_sludge, 650, 0, :west
