#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |a C        C   SCC  C   a  C     aw       a         C a a   s S S a   CC     w   w a    C    s        a              C S SCS    w S  a  S      S  S C    s  s   C C  s        w  CS s     w         sC    a     wSC   Sa    C     s   S ssC    wsS   S       s    sSC a      s         s   > Cs   w a          C  aa aS S          S          w       w   @     s C sw  Cs     aS            a  s    w           s     w      s       C CS    s       a  Ss    C  s   S    s    SS   S                 S  sCS    s   w   w     aa    CS  C      w    ss   sCs aSC  C    S   w     CS    S   Cs w          |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 586
ace_score 2930
size 586, 1
stairs 283, 0

warrior 346, 0, :east

unit :archer, 0, 0, :east
unit :captive, 2, 0, :east
unit :captive, 11, 0, :east
unit :thick_sludge, 15, 0, :east
unit :captive, 16, 0, :east
unit :captive, 17, 0, :east
unit :captive, 20, 0, :east
unit :archer, 24, 0, :east
unit :captive, 27, 0, :east
unit :archer, 33, 0, :east
unit :wizard, 34, 0, :east
unit :archer, 42, 0, :east
unit :captive, 52, 0, :east
unit :archer, 54, 0, :east
unit :archer, 56, 0, :east
unit :sludge, 60, 0, :east
unit :thick_sludge, 62, 0, :east
unit :thick_sludge, 64, 0, :east
unit :archer, 66, 0, :east
unit :captive, 70, 0, :east
unit :captive, 71, 0, :east
unit :wizard, 77, 0, :east
unit :wizard, 81, 0, :east
unit :archer, 83, 0, :east
unit :captive, 88, 0, :east
unit :sludge, 93, 0, :east
unit :archer, 102, 0, :east
unit :captive, 117, 0, :east
unit :thick_sludge, 119, 0, :east
unit :thick_sludge, 121, 0, :east
unit :captive, 122, 0, :east
unit :thick_sludge, 123, 0, :east
unit :wizard, 128, 0, :east
unit :thick_sludge, 130, 0, :east
unit :archer, 133, 0, :east
unit :thick_sludge, 136, 0, :east
unit :thick_sludge, 143, 0, :east
unit :thick_sludge, 146, 0, :east
unit :captive, 148, 0, :east
unit :sludge, 153, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 160, 0, :east
unit :captive, 162, 0, :east
unit :sludge, 165, 0, :east
unit :wizard, 174, 0, :east
unit :captive, 177, 0, :east
unit :thick_sludge, 178, 0, :east
unit :sludge, 180, 0, :east
unit :wizard, 186, 0, :east
unit :sludge, 196, 0, :east
unit :captive, 197, 0, :east
unit :archer, 202, 0, :east
unit :wizard, 208, 0, :east
unit :thick_sludge, 209, 0, :east
unit :captive, 210, 0, :east
unit :thick_sludge, 214, 0, :east
unit :archer, 215, 0, :east
unit :captive, 220, 0, :east
unit :sludge, 226, 0, :east
unit :thick_sludge, 230, 0, :east
unit :sludge, 232, 0, :east
unit :sludge, 233, 0, :east
unit :captive, 234, 0, :east
unit :wizard, 239, 0, :east
unit :sludge, 240, 0, :east
unit :thick_sludge, 241, 0, :east
unit :thick_sludge, 245, 0, :east
unit :sludge, 253, 0, :east
unit :sludge, 258, 0, :east
unit :thick_sludge, 259, 0, :east
unit :captive, 260, 0, :east
unit :archer, 262, 0, :east
unit :sludge, 269, 0, :east
unit :sludge, 279, 0, :east
unit :captive, 285, 0, :east
unit :sludge, 286, 0, :east
unit :wizard, 290, 0, :east
unit :archer, 292, 0, :east
unit :captive, 303, 0, :east
unit :archer, 306, 0, :east
unit :archer, 307, 0, :east
unit :archer, 309, 0, :east
unit :thick_sludge, 310, 0, :east
unit :thick_sludge, 312, 0, :east
unit :thick_sludge, 323, 0, :east
unit :wizard, 334, 0, :east
unit :wizard, 342, 0, :east
unit :sludge, 352, 0, :west
unit :captive, 354, 0, :west
unit :sludge, 356, 0, :west
unit :wizard, 357, 0, :west
unit :captive, 360, 0, :west
unit :sludge, 361, 0, :west
unit :archer, 367, 0, :west
unit :thick_sludge, 368, 0, :west
unit :archer, 381, 0, :west
unit :sludge, 384, 0, :west
unit :wizard, 389, 0, :west
unit :sludge, 401, 0, :west
unit :wizard, 407, 0, :west
unit :sludge, 414, 0, :west
unit :captive, 422, 0, :west
unit :captive, 424, 0, :west
unit :thick_sludge, 425, 0, :west
unit :sludge, 430, 0, :west
unit :archer, 438, 0, :west
unit :thick_sludge, 441, 0, :west
unit :sludge, 442, 0, :west
unit :captive, 447, 0, :west
unit :sludge, 450, 0, :west
unit :thick_sludge, 454, 0, :west
unit :sludge, 459, 0, :west
unit :thick_sludge, 464, 0, :west
unit :thick_sludge, 465, 0, :west
unit :thick_sludge, 469, 0, :west
unit :thick_sludge, 487, 0, :west
unit :sludge, 490, 0, :west
unit :captive, 491, 0, :west
unit :thick_sludge, 492, 0, :west
unit :sludge, 497, 0, :west
unit :wizard, 501, 0, :west
unit :wizard, 505, 0, :west
unit :archer, 511, 0, :west
unit :archer, 512, 0, :west
unit :captive, 517, 0, :west
unit :thick_sludge, 518, 0, :west
unit :captive, 521, 0, :west
unit :wizard, 528, 0, :west
unit :sludge, 533, 0, :west
unit :sludge, 534, 0, :west
unit :sludge, 538, 0, :west
unit :captive, 539, 0, :west
unit :sludge, 540, 0, :west
unit :archer, 542, 0, :west
unit :thick_sludge, 543, 0, :west
unit :captive, 544, 0, :west
unit :captive, 547, 0, :west
unit :thick_sludge, 552, 0, :west
unit :wizard, 556, 0, :west
unit :captive, 562, 0, :west
unit :thick_sludge, 563, 0, :west
unit :thick_sludge, 568, 0, :west
unit :captive, 572, 0, :west
unit :sludge, 573, 0, :west
unit :wizard, 575, 0, :west
