#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | s  C   C     wC  C s aC   S s a  w    s   C   aw          SSw           C  C s          C w   C s    C  w       C   s  ss        a    a   S      C  s          S      w    sC  a  S  w  S           aC C s   w       C       a       w   Cw  CC a  S     C          w       s     C     a  s S     w          w   a w  s a   >  w   w    aS S ss    S   C      s s   C    S   sSa        w s   a        C    SS      w C    S   w    s    w s     w  w  a s s   @    S  w    s  sC  sw aw   w        S                 aSS S   C     a S    a   S  s     S      C   s   w   C w w   sa w a   S  wC     s w  a          C   C CC      a          S    w      s s         Ss            C a  SC  aS    SC C   SS   s      C  Sss           w    s   a   a      as   a      C   aa      S      S s     a    aC w   C   s w s  S  Sa    w a       aC C    S Ss  w  C  s  wC   s C    S   S  a     S  aa S a    a Cw         C     Cs w  s  ss           C  s a    S         a      a S  a  s              sC   S  w  C|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 979
ace_score 4895
size 979, 1
stairs 318, 0

warrior 449, 0, :east

unit :sludge, 1, 0, :east
unit :captive, 4, 0, :east
unit :captive, 8, 0, :east
unit :wizard, 14, 0, :east
unit :captive, 15, 0, :east
unit :captive, 18, 0, :east
unit :sludge, 20, 0, :east
unit :archer, 22, 0, :east
unit :captive, 23, 0, :east
unit :thick_sludge, 27, 0, :east
unit :sludge, 29, 0, :east
unit :archer, 31, 0, :east
unit :wizard, 34, 0, :east
unit :sludge, 39, 0, :east
unit :captive, 43, 0, :east
unit :archer, 47, 0, :east
unit :wizard, 48, 0, :east
unit :thick_sludge, 59, 0, :east
unit :thick_sludge, 60, 0, :east
unit :wizard, 61, 0, :east
unit :captive, 73, 0, :east
unit :captive, 76, 0, :east
unit :sludge, 78, 0, :east
unit :captive, 89, 0, :east
unit :wizard, 91, 0, :east
unit :captive, 95, 0, :east
unit :sludge, 97, 0, :east
unit :captive, 102, 0, :east
unit :wizard, 105, 0, :east
unit :captive, 113, 0, :east
unit :sludge, 117, 0, :east
unit :sludge, 120, 0, :east
unit :sludge, 121, 0, :east
unit :archer, 130, 0, :east
unit :archer, 135, 0, :east
unit :thick_sludge, 139, 0, :east
unit :captive, 146, 0, :east
unit :sludge, 149, 0, :east
unit :thick_sludge, 160, 0, :east
unit :wizard, 167, 0, :east
unit :sludge, 172, 0, :east
unit :captive, 173, 0, :east
unit :archer, 176, 0, :east
unit :thick_sludge, 179, 0, :east
unit :wizard, 182, 0, :east
unit :thick_sludge, 185, 0, :east
unit :archer, 197, 0, :east
unit :captive, 198, 0, :east
unit :captive, 200, 0, :east
unit :sludge, 202, 0, :east
unit :wizard, 206, 0, :east
unit :captive, 214, 0, :east
unit :archer, 222, 0, :east
unit :wizard, 230, 0, :east
unit :captive, 234, 0, :east
unit :wizard, 235, 0, :east
unit :captive, 238, 0, :east
unit :captive, 239, 0, :east
unit :archer, 241, 0, :east
unit :thick_sludge, 244, 0, :east
unit :captive, 250, 0, :east
unit :wizard, 261, 0, :east
unit :sludge, 269, 0, :east
unit :captive, 275, 0, :east
unit :archer, 281, 0, :east
unit :sludge, 284, 0, :east
unit :thick_sludge, 286, 0, :east
unit :wizard, 292, 0, :east
unit :wizard, 303, 0, :east
unit :archer, 307, 0, :east
unit :wizard, 309, 0, :east
unit :sludge, 312, 0, :east
unit :archer, 314, 0, :east
unit :wizard, 321, 0, :east
unit :wizard, 325, 0, :east
unit :archer, 330, 0, :east
unit :thick_sludge, 331, 0, :east
unit :thick_sludge, 333, 0, :east
unit :sludge, 335, 0, :east
unit :sludge, 336, 0, :east
unit :thick_sludge, 341, 0, :east
unit :captive, 345, 0, :east
unit :sludge, 352, 0, :east
unit :sludge, 354, 0, :east
unit :captive, 358, 0, :east
unit :thick_sludge, 363, 0, :east
unit :sludge, 367, 0, :east
unit :thick_sludge, 368, 0, :east
unit :archer, 369, 0, :east
unit :wizard, 378, 0, :east
unit :sludge, 380, 0, :east
unit :archer, 384, 0, :east
unit :captive, 393, 0, :east
unit :thick_sludge, 398, 0, :east
unit :thick_sludge, 399, 0, :east
unit :wizard, 406, 0, :east
unit :captive, 408, 0, :east
unit :thick_sludge, 413, 0, :east
unit :wizard, 417, 0, :east
unit :sludge, 422, 0, :east
unit :wizard, 427, 0, :east
unit :sludge, 429, 0, :east
unit :wizard, 435, 0, :east
unit :wizard, 438, 0, :east
unit :archer, 441, 0, :east
unit :sludge, 443, 0, :east
unit :sludge, 445, 0, :east
unit :thick_sludge, 454, 0, :west
unit :wizard, 457, 0, :west
unit :sludge, 462, 0, :west
unit :sludge, 465, 0, :west
unit :captive, 466, 0, :west
unit :sludge, 469, 0, :west
unit :wizard, 470, 0, :west
unit :archer, 472, 0, :west
unit :wizard, 473, 0, :west
unit :wizard, 477, 0, :west
unit :thick_sludge, 486, 0, :west
unit :archer, 504, 0, :west
unit :thick_sludge, 505, 0, :west
unit :thick_sludge, 506, 0, :west
unit :thick_sludge, 508, 0, :west
unit :captive, 512, 0, :west
unit :archer, 518, 0, :west
unit :thick_sludge, 520, 0, :west
unit :archer, 525, 0, :west
unit :thick_sludge, 529, 0, :west
unit :sludge, 532, 0, :west
unit :thick_sludge, 538, 0, :west
unit :captive, 545, 0, :west
unit :sludge, 549, 0, :west
unit :wizard, 553, 0, :west
unit :captive, 557, 0, :west
unit :wizard, 559, 0, :west
unit :wizard, 561, 0, :west
unit :sludge, 565, 0, :west
unit :archer, 566, 0, :west
unit :wizard, 568, 0, :west
unit :archer, 570, 0, :west
unit :thick_sludge, 574, 0, :west
unit :wizard, 577, 0, :west
unit :captive, 578, 0, :west
unit :sludge, 584, 0, :west
unit :wizard, 586, 0, :west
unit :archer, 589, 0, :west
unit :captive, 600, 0, :west
unit :captive, 604, 0, :west
unit :captive, 606, 0, :west
unit :captive, 607, 0, :west
unit :archer, 614, 0, :west
unit :thick_sludge, 625, 0, :west
unit :wizard, 630, 0, :west
unit :sludge, 637, 0, :west
unit :sludge, 639, 0, :west
unit :thick_sludge, 649, 0, :west
unit :sludge, 650, 0, :west
unit :captive, 663, 0, :west
unit :archer, 665, 0, :west
unit :thick_sludge, 668, 0, :west
unit :captive, 669, 0, :west
unit :archer, 672, 0, :west
unit :thick_sludge, 673, 0, :west
unit :thick_sludge, 678, 0, :west
unit :captive, 679, 0, :west
unit :captive, 681, 0, :west
unit :thick_sludge, 685, 0, :west
unit :thick_sludge, 686, 0, :west
unit :sludge, 690, 0, :west
unit :captive, 697, 0, :west
unit :thick_sludge, 700, 0, :west
unit :sludge, 701, 0, :west
unit :sludge, 702, 0, :west
unit :wizard, 714, 0, :west
unit :sludge, 719, 0, :west
unit :archer, 723, 0, :west
unit :archer, 727, 0, :west
unit :archer, 734, 0, :west
unit :sludge, 735, 0, :west
unit :archer, 739, 0, :west
unit :captive, 746, 0, :west
unit :archer, 750, 0, :west
unit :archer, 751, 0, :west
unit :thick_sludge, 758, 0, :west
unit :thick_sludge, 765, 0, :west
unit :sludge, 767, 0, :west
unit :archer, 773, 0, :west
unit :archer, 778, 0, :west
unit :captive, 779, 0, :west
unit :wizard, 781, 0, :west
unit :captive, 785, 0, :west
unit :sludge, 789, 0, :west
unit :wizard, 791, 0, :west
unit :sludge, 793, 0, :west
unit :thick_sludge, 796, 0, :west
unit :thick_sludge, 799, 0, :west
unit :archer, 800, 0, :west
unit :wizard, 805, 0, :west
unit :archer, 807, 0, :west
unit :archer, 815, 0, :west
unit :captive, 816, 0, :west
unit :captive, 818, 0, :west
unit :thick_sludge, 823, 0, :west
unit :thick_sludge, 825, 0, :west
unit :sludge, 826, 0, :west
unit :wizard, 829, 0, :west
unit :captive, 832, 0, :west
unit :sludge, 835, 0, :west
unit :wizard, 838, 0, :west
unit :captive, 839, 0, :west
unit :sludge, 843, 0, :west
unit :captive, 845, 0, :west
unit :thick_sludge, 850, 0, :west
unit :thick_sludge, 854, 0, :west
unit :archer, 857, 0, :west
unit :thick_sludge, 863, 0, :west
unit :archer, 866, 0, :west
unit :archer, 867, 0, :west
unit :thick_sludge, 869, 0, :west
unit :archer, 871, 0, :west
unit :archer, 876, 0, :west
unit :captive, 878, 0, :west
unit :wizard, 879, 0, :west
unit :captive, 889, 0, :west
unit :captive, 895, 0, :west
unit :sludge, 896, 0, :west
unit :wizard, 898, 0, :west
unit :sludge, 901, 0, :west
unit :sludge, 904, 0, :west
unit :sludge, 905, 0, :west
unit :captive, 917, 0, :west
unit :sludge, 920, 0, :west
unit :archer, 922, 0, :west
unit :thick_sludge, 927, 0, :west
unit :archer, 937, 0, :west
unit :archer, 944, 0, :west
unit :thick_sludge, 946, 0, :west
unit :archer, 949, 0, :west
unit :sludge, 952, 0, :west
unit :sludge, 967, 0, :west
unit :captive, 968, 0, :west
unit :thick_sludge, 972, 0, :west
unit :wizard, 975, 0, :west
unit :captive, 978, 0, :west
