#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    SC       S  sC    S       w S      a   S      w    w S w C   s ss            s    s S Ca      CC s     w        C a  C           w    S   w C     C S     S s     sSs         s     ss a   C  a     sa    S       w a    Cs w    a w        Cs         s S  C a     s S  a a      w     Ca    @      S s  C C S Sw     s     w  a w   C      S  s   w   a    >  C  a     aSa     as       CC     S  Sa    S   a        s SSawC as  S a   s    C       a  aSs    s   s     w ws s    a s w        sa  s    w   a         w    s  w   s     C        Ca s   w       C  a         a    C       sw   a   C        SC     S            a      C   s    Ca S     w C S  w   a    C   C S  w         S   C S      w       w     Sa     Sw as   w  w    awS s    S     w  a a       a  s S        a  CC SS         |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 783
ace_score 3915
size 783, 1
stairs 353, 0

warrior 290, 0, :east

unit :thick_sludge, 4, 0, :east
unit :captive, 5, 0, :east
unit :thick_sludge, 13, 0, :east
unit :sludge, 16, 0, :east
unit :captive, 17, 0, :east
unit :thick_sludge, 22, 0, :east
unit :wizard, 30, 0, :east
unit :thick_sludge, 32, 0, :east
unit :archer, 39, 0, :east
unit :thick_sludge, 43, 0, :east
unit :wizard, 50, 0, :east
unit :wizard, 55, 0, :east
unit :thick_sludge, 57, 0, :east
unit :wizard, 59, 0, :east
unit :captive, 61, 0, :east
unit :sludge, 65, 0, :east
unit :sludge, 67, 0, :east
unit :sludge, 68, 0, :east
unit :sludge, 81, 0, :east
unit :sludge, 86, 0, :east
unit :thick_sludge, 88, 0, :east
unit :captive, 90, 0, :east
unit :archer, 91, 0, :east
unit :captive, 98, 0, :east
unit :captive, 99, 0, :east
unit :sludge, 101, 0, :east
unit :wizard, 107, 0, :east
unit :captive, 116, 0, :east
unit :archer, 118, 0, :east
unit :captive, 121, 0, :east
unit :wizard, 133, 0, :east
unit :thick_sludge, 138, 0, :east
unit :wizard, 142, 0, :east
unit :captive, 144, 0, :east
unit :captive, 150, 0, :east
unit :thick_sludge, 152, 0, :east
unit :thick_sludge, 158, 0, :east
unit :sludge, 160, 0, :east
unit :sludge, 166, 0, :east
unit :thick_sludge, 167, 0, :east
unit :sludge, 168, 0, :east
unit :sludge, 178, 0, :east
unit :sludge, 184, 0, :east
unit :sludge, 185, 0, :east
unit :archer, 187, 0, :east
unit :captive, 191, 0, :east
unit :archer, 194, 0, :east
unit :sludge, 200, 0, :east
unit :archer, 201, 0, :east
unit :thick_sludge, 206, 0, :east
unit :wizard, 214, 0, :east
unit :archer, 216, 0, :east
unit :captive, 221, 0, :east
unit :sludge, 222, 0, :east
unit :wizard, 224, 0, :east
unit :archer, 229, 0, :east
unit :wizard, 231, 0, :east
unit :captive, 240, 0, :east
unit :sludge, 241, 0, :east
unit :sludge, 251, 0, :east
unit :thick_sludge, 253, 0, :east
unit :captive, 256, 0, :east
unit :archer, 258, 0, :east
unit :sludge, 264, 0, :east
unit :thick_sludge, 266, 0, :east
unit :archer, 269, 0, :east
unit :archer, 271, 0, :east
unit :wizard, 278, 0, :east
unit :captive, 284, 0, :east
unit :archer, 285, 0, :east
unit :thick_sludge, 297, 0, :west
unit :sludge, 299, 0, :west
unit :captive, 302, 0, :west
unit :captive, 304, 0, :west
unit :thick_sludge, 306, 0, :west
unit :thick_sludge, 308, 0, :west
unit :wizard, 309, 0, :west
unit :sludge, 315, 0, :west
unit :wizard, 321, 0, :west
unit :archer, 324, 0, :west
unit :wizard, 326, 0, :west
unit :captive, 330, 0, :west
unit :thick_sludge, 337, 0, :west
unit :sludge, 340, 0, :west
unit :wizard, 344, 0, :west
unit :archer, 348, 0, :west
unit :captive, 356, 0, :west
unit :archer, 359, 0, :west
unit :archer, 365, 0, :west
unit :thick_sludge, 366, 0, :west
unit :archer, 367, 0, :west
unit :archer, 373, 0, :west
unit :sludge, 374, 0, :west
unit :captive, 382, 0, :west
unit :captive, 383, 0, :west
unit :thick_sludge, 389, 0, :west
unit :thick_sludge, 392, 0, :west
unit :archer, 393, 0, :west
unit :thick_sludge, 398, 0, :west
unit :archer, 402, 0, :west
unit :sludge, 411, 0, :west
unit :thick_sludge, 413, 0, :west
unit :thick_sludge, 414, 0, :west
unit :archer, 415, 0, :west
unit :wizard, 416, 0, :west
unit :captive, 417, 0, :west
unit :archer, 419, 0, :west
unit :sludge, 420, 0, :west
unit :thick_sludge, 423, 0, :west
unit :archer, 425, 0, :west
unit :sludge, 429, 0, :west
unit :captive, 434, 0, :west
unit :archer, 442, 0, :west
unit :archer, 445, 0, :west
unit :thick_sludge, 446, 0, :west
unit :sludge, 447, 0, :west
unit :sludge, 452, 0, :west
unit :sludge, 456, 0, :west
unit :wizard, 462, 0, :west
unit :wizard, 464, 0, :west
unit :sludge, 465, 0, :west
unit :sludge, 467, 0, :west
unit :archer, 472, 0, :west
unit :sludge, 474, 0, :west
unit :wizard, 476, 0, :west
unit :sludge, 485, 0, :west
unit :archer, 486, 0, :west
unit :sludge, 489, 0, :west
unit :wizard, 494, 0, :west
unit :archer, 498, 0, :west
unit :wizard, 508, 0, :west
unit :sludge, 513, 0, :west
unit :wizard, 516, 0, :west
unit :sludge, 520, 0, :west
unit :captive, 526, 0, :west
unit :captive, 535, 0, :west
unit :archer, 536, 0, :west
unit :sludge, 538, 0, :west
unit :wizard, 542, 0, :west
unit :captive, 550, 0, :west
unit :archer, 553, 0, :west
unit :archer, 563, 0, :west
unit :captive, 568, 0, :west
unit :sludge, 576, 0, :west
unit :wizard, 577, 0, :west
unit :archer, 581, 0, :west
unit :captive, 585, 0, :west
unit :thick_sludge, 594, 0, :west
unit :captive, 595, 0, :west
unit :thick_sludge, 601, 0, :west
unit :archer, 614, 0, :west
unit :captive, 621, 0, :west
unit :sludge, 625, 0, :west
unit :captive, 630, 0, :west
unit :archer, 631, 0, :west
unit :thick_sludge, 633, 0, :west
unit :wizard, 639, 0, :west
unit :captive, 641, 0, :west
unit :thick_sludge, 643, 0, :west
unit :wizard, 646, 0, :west
unit :archer, 650, 0, :west
unit :captive, 655, 0, :west
unit :captive, 659, 0, :west
unit :thick_sludge, 661, 0, :west
unit :wizard, 664, 0, :west
unit :thick_sludge, 674, 0, :west
unit :captive, 678, 0, :west
unit :thick_sludge, 680, 0, :west
unit :wizard, 687, 0, :west
unit :wizard, 695, 0, :west
unit :thick_sludge, 701, 0, :west
unit :archer, 702, 0, :west
unit :thick_sludge, 708, 0, :west
unit :wizard, 709, 0, :west
unit :archer, 711, 0, :west
unit :sludge, 712, 0, :west
unit :wizard, 716, 0, :west
unit :wizard, 719, 0, :west
unit :archer, 724, 0, :west
unit :wizard, 725, 0, :west
unit :thick_sludge, 726, 0, :west
unit :sludge, 728, 0, :west
unit :thick_sludge, 733, 0, :west
unit :wizard, 739, 0, :west
unit :archer, 742, 0, :west
unit :archer, 744, 0, :west
unit :archer, 752, 0, :west
unit :sludge, 755, 0, :west
unit :thick_sludge, 757, 0, :west
unit :archer, 766, 0, :west
unit :captive, 769, 0, :west
unit :captive, 770, 0, :west
unit :thick_sludge, 772, 0, :west
unit :thick_sludge, 773, 0, :west
