#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C     S     S     a    s a   w      Cs    w      s     s  C  s   saw  w  C    C    S  C  s   aS     a s    s      s         CS    C   w S  a  C    w    s   CS  C a s C                a  Ca   w sa    C    S   as SS         w         a         CC a     S   C S       sC   SS  a s  a     S  aa  C w       w  sC     S    S  w S     S  C Sa     S  w  w        S    s     C   s ass     SS sa sS        s s>      S       w aC     w C    C a  sw    w   SS wS s     SSs   a             sa   sCs   S  S a a  s       a wCss   a     s S   a                              wa    as       sS  S          s      C a      s            w w C       S     a      sCC     C  w Cw  Sa            S     w  @          s        s   a     S        S  C           S        w  a    S  Ss       aC  sw   CaCs  s  wS      C  C  ss C w   s       s    sS  |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 823
ace_score 4115
size 823, 1
stairs 399, 0

warrior 682, 0, :east

unit :captive, 0, 0, :east
unit :thick_sludge, 6, 0, :east
unit :thick_sludge, 12, 0, :east
unit :archer, 18, 0, :east
unit :sludge, 23, 0, :east
unit :archer, 25, 0, :east
unit :wizard, 29, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 37, 0, :east
unit :wizard, 42, 0, :east
unit :sludge, 49, 0, :east
unit :sludge, 55, 0, :east
unit :captive, 58, 0, :east
unit :sludge, 61, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 66, 0, :east
unit :wizard, 67, 0, :east
unit :wizard, 70, 0, :east
unit :captive, 73, 0, :east
unit :captive, 78, 0, :east
unit :thick_sludge, 83, 0, :east
unit :captive, 86, 0, :east
unit :sludge, 89, 0, :east
unit :archer, 93, 0, :east
unit :thick_sludge, 94, 0, :east
unit :archer, 100, 0, :east
unit :sludge, 102, 0, :east
unit :sludge, 107, 0, :east
unit :sludge, 114, 0, :east
unit :captive, 124, 0, :east
unit :thick_sludge, 125, 0, :east
unit :captive, 130, 0, :east
unit :wizard, 134, 0, :east
unit :thick_sludge, 136, 0, :east
unit :archer, 139, 0, :east
unit :captive, 142, 0, :east
unit :wizard, 147, 0, :east
unit :sludge, 152, 0, :east
unit :captive, 156, 0, :east
unit :thick_sludge, 157, 0, :east
unit :captive, 160, 0, :east
unit :archer, 162, 0, :east
unit :sludge, 164, 0, :east
unit :captive, 166, 0, :east
unit :archer, 183, 0, :east
unit :captive, 186, 0, :east
unit :archer, 187, 0, :east
unit :wizard, 191, 0, :east
unit :sludge, 193, 0, :east
unit :archer, 194, 0, :east
unit :captive, 199, 0, :east
unit :thick_sludge, 204, 0, :east
unit :archer, 208, 0, :east
unit :sludge, 209, 0, :east
unit :thick_sludge, 211, 0, :east
unit :thick_sludge, 212, 0, :east
unit :wizard, 222, 0, :east
unit :archer, 232, 0, :east
unit :captive, 242, 0, :east
unit :captive, 243, 0, :east
unit :archer, 245, 0, :east
unit :thick_sludge, 251, 0, :east
unit :captive, 255, 0, :east
unit :thick_sludge, 257, 0, :east
unit :sludge, 265, 0, :east
unit :captive, 266, 0, :east
unit :thick_sludge, 270, 0, :east
unit :thick_sludge, 271, 0, :east
unit :archer, 274, 0, :east
unit :sludge, 276, 0, :east
unit :archer, 279, 0, :east
unit :thick_sludge, 285, 0, :east
unit :archer, 288, 0, :east
unit :archer, 289, 0, :east
unit :captive, 292, 0, :east
unit :wizard, 294, 0, :east
unit :wizard, 302, 0, :east
unit :sludge, 305, 0, :east
unit :captive, 306, 0, :east
unit :thick_sludge, 312, 0, :east
unit :thick_sludge, 317, 0, :east
unit :wizard, 320, 0, :east
unit :thick_sludge, 322, 0, :east
unit :thick_sludge, 328, 0, :east
unit :captive, 331, 0, :east
unit :thick_sludge, 333, 0, :east
unit :archer, 334, 0, :east
unit :thick_sludge, 340, 0, :east
unit :wizard, 343, 0, :east
unit :wizard, 346, 0, :east
unit :thick_sludge, 355, 0, :east
unit :sludge, 360, 0, :east
unit :captive, 366, 0, :east
unit :sludge, 370, 0, :east
unit :archer, 372, 0, :east
unit :sludge, 373, 0, :east
unit :sludge, 374, 0, :east
unit :thick_sludge, 380, 0, :east
unit :thick_sludge, 381, 0, :east
unit :sludge, 383, 0, :east
unit :archer, 384, 0, :east
unit :sludge, 386, 0, :east
unit :thick_sludge, 387, 0, :east
unit :sludge, 396, 0, :east
unit :sludge, 398, 0, :east
unit :thick_sludge, 406, 0, :east
unit :wizard, 414, 0, :east
unit :archer, 416, 0, :east
unit :captive, 417, 0, :east
unit :wizard, 423, 0, :east
unit :captive, 425, 0, :east
unit :captive, 430, 0, :east
unit :archer, 432, 0, :east
unit :sludge, 435, 0, :east
unit :wizard, 436, 0, :east
unit :wizard, 441, 0, :east
unit :thick_sludge, 445, 0, :east
unit :thick_sludge, 446, 0, :east
unit :wizard, 448, 0, :east
unit :thick_sludge, 449, 0, :east
unit :sludge, 451, 0, :east
unit :thick_sludge, 457, 0, :east
unit :thick_sludge, 458, 0, :east
unit :sludge, 459, 0, :east
unit :archer, 463, 0, :east
unit :sludge, 477, 0, :east
unit :archer, 478, 0, :east
unit :sludge, 482, 0, :east
unit :captive, 483, 0, :east
unit :sludge, 484, 0, :east
unit :thick_sludge, 488, 0, :east
unit :thick_sludge, 491, 0, :east
unit :archer, 493, 0, :east
unit :archer, 495, 0, :east
unit :sludge, 498, 0, :east
unit :archer, 506, 0, :east
unit :wizard, 508, 0, :east
unit :captive, 509, 0, :east
unit :sludge, 510, 0, :east
unit :sludge, 511, 0, :east
unit :archer, 515, 0, :east
unit :sludge, 521, 0, :east
unit :thick_sludge, 523, 0, :east
unit :archer, 527, 0, :east
unit :wizard, 558, 0, :east
unit :archer, 559, 0, :east
unit :archer, 564, 0, :east
unit :sludge, 565, 0, :east
unit :sludge, 573, 0, :east
unit :thick_sludge, 574, 0, :east
unit :thick_sludge, 577, 0, :east
unit :sludge, 588, 0, :east
unit :captive, 595, 0, :east
unit :archer, 597, 0, :east
unit :sludge, 604, 0, :east
unit :wizard, 617, 0, :east
unit :wizard, 619, 0, :east
unit :captive, 621, 0, :east
unit :thick_sludge, 629, 0, :east
unit :archer, 635, 0, :east
unit :sludge, 642, 0, :east
unit :captive, 643, 0, :east
unit :captive, 644, 0, :east
unit :captive, 650, 0, :east
unit :wizard, 653, 0, :east
unit :captive, 655, 0, :east
unit :wizard, 656, 0, :east
unit :thick_sludge, 659, 0, :east
unit :archer, 660, 0, :east
unit :thick_sludge, 673, 0, :east
unit :wizard, 679, 0, :east
unit :sludge, 693, 0, :west
unit :sludge, 702, 0, :west
unit :archer, 706, 0, :west
unit :thick_sludge, 712, 0, :west
unit :thick_sludge, 721, 0, :west
unit :captive, 724, 0, :west
unit :thick_sludge, 736, 0, :west
unit :wizard, 745, 0, :west
unit :archer, 748, 0, :west
unit :thick_sludge, 753, 0, :west
unit :thick_sludge, 756, 0, :west
unit :sludge, 757, 0, :west
unit :archer, 765, 0, :west
unit :captive, 766, 0, :west
unit :sludge, 769, 0, :west
unit :wizard, 770, 0, :west
unit :captive, 774, 0, :west
unit :archer, 775, 0, :west
unit :captive, 776, 0, :west
unit :sludge, 777, 0, :west
unit :sludge, 780, 0, :west
unit :wizard, 783, 0, :west
unit :thick_sludge, 784, 0, :west
unit :captive, 791, 0, :west
unit :captive, 794, 0, :west
unit :sludge, 797, 0, :west
unit :sludge, 798, 0, :west
unit :captive, 800, 0, :west
unit :wizard, 802, 0, :west
unit :sludge, 806, 0, :west
unit :sludge, 814, 0, :west
unit :sludge, 819, 0, :west
unit :thick_sludge, 820, 0, :west
