#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     CCCw    C s   s      CwS C s    a        a a          s   s            Cw CC             C  w  w   a  s   CC s       sSw  C       S  w  a SS      S  SSsC a   s  w   @   w   w C C                 aC       as    swS  a     S a       S   SC    S    s      Sw  s   C S sS s  a     Sw    a   C a   w           s  a        w  w      sa   C   a a  CC          w   Sw       a          S          C   sSa  w  w   s    a C        Ss    a  w        S    S a   w      a  a    w  S s w C  s      swsa      C a    a        sC w C C  wSC      S w    S       C      aSCSa          a C w C    a    C s    S             s       w         w   a  a  S       a C     S  s     C        s a  S s   w w S>      wa    a         CC|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 710
ace_score 3550
size 710, 1
stairs 685, 0

warrior 170, 0, :east

unit :captive, 5, 0, :east
unit :captive, 6, 0, :east
unit :captive, 7, 0, :east
unit :wizard, 8, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 15, 0, :east
unit :sludge, 19, 0, :east
unit :captive, 26, 0, :east
unit :wizard, 27, 0, :east
unit :thick_sludge, 28, 0, :east
unit :captive, 30, 0, :east
unit :sludge, 32, 0, :east
unit :archer, 37, 0, :east
unit :archer, 46, 0, :east
unit :archer, 48, 0, :east
unit :sludge, 59, 0, :east
unit :sludge, 63, 0, :east
unit :captive, 76, 0, :east
unit :wizard, 77, 0, :east
unit :captive, 79, 0, :east
unit :captive, 80, 0, :east
unit :captive, 94, 0, :east
unit :wizard, 97, 0, :east
unit :wizard, 100, 0, :east
unit :archer, 104, 0, :east
unit :sludge, 107, 0, :east
unit :captive, 111, 0, :east
unit :captive, 112, 0, :east
unit :sludge, 114, 0, :east
unit :sludge, 122, 0, :east
unit :thick_sludge, 123, 0, :east
unit :wizard, 124, 0, :east
unit :captive, 127, 0, :east
unit :thick_sludge, 135, 0, :east
unit :wizard, 138, 0, :east
unit :archer, 141, 0, :east
unit :thick_sludge, 143, 0, :east
unit :thick_sludge, 144, 0, :east
unit :thick_sludge, 151, 0, :east
unit :thick_sludge, 154, 0, :east
unit :thick_sludge, 155, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 157, 0, :east
unit :archer, 159, 0, :east
unit :sludge, 163, 0, :east
unit :wizard, 166, 0, :east
unit :wizard, 174, 0, :west
unit :wizard, 178, 0, :west
unit :captive, 180, 0, :west
unit :captive, 182, 0, :west
unit :archer, 200, 0, :west
unit :captive, 201, 0, :west
unit :archer, 209, 0, :west
unit :sludge, 210, 0, :west
unit :sludge, 215, 0, :west
unit :wizard, 216, 0, :west
unit :thick_sludge, 217, 0, :west
unit :archer, 220, 0, :west
unit :thick_sludge, 226, 0, :west
unit :archer, 228, 0, :west
unit :thick_sludge, 236, 0, :west
unit :thick_sludge, 240, 0, :west
unit :captive, 241, 0, :west
unit :thick_sludge, 246, 0, :west
unit :sludge, 251, 0, :west
unit :thick_sludge, 258, 0, :west
unit :wizard, 259, 0, :west
unit :sludge, 262, 0, :west
unit :captive, 266, 0, :west
unit :thick_sludge, 268, 0, :west
unit :sludge, 270, 0, :west
unit :thick_sludge, 271, 0, :west
unit :sludge, 273, 0, :west
unit :archer, 276, 0, :west
unit :thick_sludge, 282, 0, :west
unit :wizard, 283, 0, :west
unit :archer, 288, 0, :west
unit :captive, 292, 0, :west
unit :archer, 294, 0, :west
unit :wizard, 298, 0, :west
unit :sludge, 310, 0, :west
unit :archer, 313, 0, :west
unit :wizard, 322, 0, :west
unit :wizard, 325, 0, :west
unit :sludge, 332, 0, :west
unit :archer, 333, 0, :west
unit :captive, 337, 0, :west
unit :archer, 341, 0, :west
unit :archer, 343, 0, :west
unit :captive, 346, 0, :west
unit :captive, 347, 0, :west
unit :wizard, 358, 0, :west
unit :thick_sludge, 362, 0, :west
unit :wizard, 363, 0, :west
unit :archer, 371, 0, :west
unit :thick_sludge, 382, 0, :west
unit :captive, 393, 0, :west
unit :sludge, 397, 0, :west
unit :thick_sludge, 398, 0, :west
unit :archer, 399, 0, :west
unit :wizard, 402, 0, :west
unit :wizard, 405, 0, :west
unit :sludge, 409, 0, :west
unit :archer, 414, 0, :west
unit :captive, 416, 0, :west
unit :thick_sludge, 425, 0, :west
unit :sludge, 426, 0, :west
unit :archer, 431, 0, :west
unit :wizard, 434, 0, :west
unit :thick_sludge, 443, 0, :west
unit :thick_sludge, 448, 0, :west
unit :archer, 450, 0, :west
unit :wizard, 454, 0, :west
unit :archer, 461, 0, :west
unit :archer, 464, 0, :west
unit :wizard, 469, 0, :west
unit :thick_sludge, 472, 0, :west
unit :sludge, 474, 0, :west
unit :wizard, 476, 0, :west
unit :captive, 478, 0, :west
unit :sludge, 481, 0, :west
unit :sludge, 488, 0, :west
unit :wizard, 489, 0, :west
unit :sludge, 490, 0, :west
unit :archer, 491, 0, :west
unit :captive, 498, 0, :west
unit :archer, 500, 0, :west
unit :archer, 505, 0, :west
unit :sludge, 514, 0, :west
unit :captive, 515, 0, :west
unit :wizard, 517, 0, :west
unit :captive, 519, 0, :west
unit :captive, 521, 0, :west
unit :wizard, 524, 0, :west
unit :thick_sludge, 525, 0, :west
unit :captive, 526, 0, :west
unit :thick_sludge, 533, 0, :west
unit :wizard, 535, 0, :west
unit :thick_sludge, 540, 0, :west
unit :captive, 548, 0, :west
unit :archer, 555, 0, :west
unit :thick_sludge, 556, 0, :west
unit :captive, 557, 0, :west
unit :thick_sludge, 558, 0, :west
unit :archer, 559, 0, :west
unit :archer, 570, 0, :west
unit :captive, 572, 0, :west
unit :wizard, 574, 0, :west
unit :captive, 576, 0, :west
unit :archer, 581, 0, :west
unit :captive, 586, 0, :west
unit :sludge, 588, 0, :west
unit :thick_sludge, 593, 0, :west
unit :sludge, 607, 0, :west
unit :wizard, 615, 0, :west
unit :wizard, 625, 0, :west
unit :archer, 629, 0, :west
unit :archer, 632, 0, :west
unit :thick_sludge, 635, 0, :west
unit :archer, 643, 0, :west
unit :captive, 645, 0, :west
unit :thick_sludge, 651, 0, :west
unit :sludge, 654, 0, :west
unit :captive, 660, 0, :west
unit :sludge, 669, 0, :west
unit :archer, 671, 0, :west
unit :thick_sludge, 674, 0, :west
unit :sludge, 676, 0, :west
unit :wizard, 680, 0, :west
unit :wizard, 682, 0, :west
unit :thick_sludge, 684, 0, :west
unit :wizard, 692, 0, :west
unit :archer, 693, 0, :west
unit :archer, 698, 0, :west
unit :captive, 708, 0, :west
unit :captive, 709, 0, :west
