#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     C         C w s    a      S    w               wSw      w   s  a  S   w          a C   C   s       s   C      CCs  s a  s   C  CS     w  C a         s w C  w  s   a w    s C            sa       s    C   S           aa C      s S a            S     w     C    sS s    Sw   s S C   SS    w     w          w    a      S   w   C  a     a sC  SSS   w  S  C    aC     w w        Cs   s     S     a  s a   w sC sS    a             a s         S    C          S    s      a   S  a ss      C   w  C   Sa    S       w  w a a          w  w   a S CC       a  C a  C C     C    a        s        C      a C   a   w    sC  C  Cs w w    a sS   S w          C    a            a C w   SSsw   w   a aa     C     S s   S             S CS    w    S      a    sS  SSw  w  aS  w a C    w a  w     w   s s C     w  a      a > s   S      sCC   w       aa       w  a aw S s w      C      s      a   s         S S  w  sa a  Ss    C s       @   s S  S s sC     ss  a   S|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 948
ace_score 4740
size 948, 1
stairs 806, 0

warrior 919, 0, :east

unit :captive, 5, 0, :east
unit :captive, 15, 0, :east
unit :wizard, 17, 0, :east
unit :sludge, 19, 0, :east
unit :archer, 24, 0, :east
unit :thick_sludge, 31, 0, :east
unit :wizard, 36, 0, :east
unit :wizard, 52, 0, :east
unit :thick_sludge, 53, 0, :east
unit :wizard, 54, 0, :east
unit :wizard, 61, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 68, 0, :east
unit :thick_sludge, 71, 0, :east
unit :wizard, 75, 0, :east
unit :archer, 86, 0, :east
unit :captive, 88, 0, :east
unit :captive, 92, 0, :east
unit :sludge, 96, 0, :east
unit :sludge, 104, 0, :east
unit :captive, 108, 0, :east
unit :captive, 115, 0, :east
unit :captive, 116, 0, :east
unit :sludge, 117, 0, :east
unit :sludge, 120, 0, :east
unit :archer, 122, 0, :east
unit :sludge, 125, 0, :east
unit :captive, 129, 0, :east
unit :captive, 132, 0, :east
unit :thick_sludge, 133, 0, :east
unit :wizard, 139, 0, :east
unit :captive, 142, 0, :east
unit :archer, 144, 0, :east
unit :sludge, 154, 0, :east
unit :wizard, 156, 0, :east
unit :captive, 158, 0, :east
unit :wizard, 161, 0, :east
unit :sludge, 164, 0, :east
unit :archer, 168, 0, :east
unit :wizard, 170, 0, :east
unit :sludge, 175, 0, :east
unit :captive, 177, 0, :east
unit :sludge, 190, 0, :east
unit :archer, 191, 0, :east
unit :sludge, 199, 0, :east
unit :captive, 204, 0, :east
unit :thick_sludge, 208, 0, :east
unit :archer, 220, 0, :east
unit :archer, 221, 0, :east
unit :captive, 223, 0, :east
unit :sludge, 230, 0, :east
unit :thick_sludge, 232, 0, :east
unit :archer, 234, 0, :east
unit :thick_sludge, 247, 0, :east
unit :wizard, 253, 0, :east
unit :captive, 259, 0, :east
unit :sludge, 264, 0, :east
unit :thick_sludge, 265, 0, :east
unit :sludge, 267, 0, :east
unit :thick_sludge, 272, 0, :east
unit :wizard, 273, 0, :east
unit :sludge, 277, 0, :east
unit :thick_sludge, 279, 0, :east
unit :captive, 281, 0, :east
unit :thick_sludge, 285, 0, :east
unit :thick_sludge, 286, 0, :east
unit :wizard, 291, 0, :east
unit :wizard, 297, 0, :east
unit :wizard, 308, 0, :east
unit :archer, 313, 0, :east
unit :thick_sludge, 320, 0, :east
unit :wizard, 324, 0, :east
unit :captive, 328, 0, :east
unit :archer, 331, 0, :east
unit :archer, 337, 0, :east
unit :sludge, 339, 0, :east
unit :captive, 340, 0, :east
unit :thick_sludge, 343, 0, :east
unit :thick_sludge, 344, 0, :east
unit :thick_sludge, 345, 0, :east
unit :wizard, 349, 0, :east
unit :thick_sludge, 352, 0, :east
unit :captive, 355, 0, :east
unit :archer, 360, 0, :east
unit :captive, 361, 0, :east
unit :wizard, 367, 0, :east
unit :wizard, 369, 0, :east
unit :captive, 378, 0, :east
unit :sludge, 379, 0, :east
unit :sludge, 383, 0, :east
unit :thick_sludge, 389, 0, :east
unit :archer, 395, 0, :east
unit :sludge, 398, 0, :east
unit :archer, 400, 0, :east
unit :wizard, 404, 0, :east
unit :sludge, 406, 0, :east
unit :captive, 407, 0, :east
unit :sludge, 409, 0, :east
unit :thick_sludge, 410, 0, :east
unit :archer, 415, 0, :east
unit :archer, 429, 0, :east
unit :sludge, 431, 0, :east
unit :thick_sludge, 441, 0, :east
unit :captive, 446, 0, :east
unit :thick_sludge, 457, 0, :east
unit :sludge, 462, 0, :east
unit :archer, 469, 0, :east
unit :thick_sludge, 473, 0, :east
unit :archer, 476, 0, :east
unit :sludge, 478, 0, :east
unit :sludge, 479, 0, :east
unit :captive, 486, 0, :east
unit :wizard, 490, 0, :east
unit :captive, 493, 0, :east
unit :thick_sludge, 497, 0, :east
unit :archer, 498, 0, :east
unit :thick_sludge, 503, 0, :east
unit :wizard, 511, 0, :east
unit :wizard, 514, 0, :east
unit :archer, 516, 0, :east
unit :archer, 518, 0, :east
unit :wizard, 529, 0, :east
unit :wizard, 532, 0, :east
unit :archer, 536, 0, :east
unit :thick_sludge, 538, 0, :east
unit :captive, 540, 0, :east
unit :captive, 541, 0, :east
unit :archer, 549, 0, :east
unit :captive, 552, 0, :east
unit :archer, 554, 0, :east
unit :captive, 557, 0, :east
unit :captive, 559, 0, :east
unit :captive, 565, 0, :east
unit :archer, 570, 0, :east
unit :sludge, 579, 0, :east
unit :captive, 588, 0, :east
unit :archer, 595, 0, :east
unit :captive, 597, 0, :east
unit :archer, 601, 0, :east
unit :wizard, 605, 0, :east
unit :sludge, 610, 0, :east
unit :captive, 611, 0, :east
unit :captive, 614, 0, :east
unit :captive, 617, 0, :east
unit :sludge, 618, 0, :east
unit :wizard, 620, 0, :east
unit :wizard, 622, 0, :east
unit :archer, 627, 0, :east
unit :sludge, 629, 0, :east
unit :thick_sludge, 630, 0, :east
unit :thick_sludge, 634, 0, :east
unit :wizard, 636, 0, :east
unit :captive, 647, 0, :east
unit :archer, 652, 0, :east
unit :archer, 665, 0, :east
unit :captive, 667, 0, :east
unit :wizard, 669, 0, :east
unit :thick_sludge, 673, 0, :east
unit :thick_sludge, 674, 0, :east
unit :sludge, 675, 0, :east
unit :wizard, 676, 0, :east
unit :wizard, 680, 0, :east
unit :archer, 684, 0, :east
unit :archer, 686, 0, :east
unit :archer, 687, 0, :east
unit :captive, 693, 0, :east
unit :thick_sludge, 699, 0, :east
unit :sludge, 701, 0, :east
unit :thick_sludge, 705, 0, :east
unit :thick_sludge, 719, 0, :east
unit :captive, 721, 0, :east
unit :thick_sludge, 722, 0, :east
unit :wizard, 727, 0, :east
unit :thick_sludge, 732, 0, :east
unit :archer, 739, 0, :east
unit :sludge, 744, 0, :east
unit :thick_sludge, 745, 0, :east
unit :thick_sludge, 748, 0, :east
unit :thick_sludge, 749, 0, :east
unit :wizard, 750, 0, :east
unit :wizard, 753, 0, :east
unit :archer, 756, 0, :east
unit :thick_sludge, 757, 0, :east
unit :wizard, 760, 0, :east
unit :archer, 762, 0, :east
unit :captive, 764, 0, :east
unit :wizard, 769, 0, :east
unit :archer, 771, 0, :east
unit :wizard, 774, 0, :east
unit :wizard, 780, 0, :east
unit :sludge, 784, 0, :east
unit :sludge, 786, 0, :east
unit :captive, 788, 0, :east
unit :wizard, 794, 0, :east
unit :archer, 797, 0, :east
unit :archer, 804, 0, :east
unit :sludge, 808, 0, :east
unit :thick_sludge, 812, 0, :east
unit :sludge, 819, 0, :east
unit :captive, 820, 0, :east
unit :captive, 821, 0, :east
unit :wizard, 825, 0, :east
unit :archer, 833, 0, :east
unit :archer, 834, 0, :east
unit :wizard, 842, 0, :east
unit :archer, 845, 0, :east
unit :archer, 847, 0, :east
unit :wizard, 848, 0, :east
unit :thick_sludge, 850, 0, :east
unit :sludge, 852, 0, :east
unit :wizard, 854, 0, :east
unit :captive, 861, 0, :east
unit :sludge, 868, 0, :east
unit :archer, 875, 0, :east
unit :sludge, 879, 0, :east
unit :thick_sludge, 889, 0, :east
unit :thick_sludge, 891, 0, :east
unit :wizard, 894, 0, :east
unit :sludge, 897, 0, :east
unit :archer, 898, 0, :east
unit :archer, 900, 0, :east
unit :thick_sludge, 903, 0, :east
unit :sludge, 904, 0, :east
unit :captive, 909, 0, :east
unit :sludge, 911, 0, :east
unit :sludge, 923, 0, :west
unit :thick_sludge, 925, 0, :west
unit :thick_sludge, 928, 0, :west
unit :sludge, 930, 0, :west
unit :sludge, 932, 0, :west
unit :captive, 933, 0, :west
unit :sludge, 939, 0, :west
unit :sludge, 940, 0, :west
unit :archer, 943, 0, :west
unit :thick_sludge, 947, 0, :west
