#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  S   a  a a a  s   C     C w S            s  sa Cs     s        C  w  w  s  a   C        a s   s          w  a >        w aCa  wC  SSS              s      S  S    C   w    aaCa    s  sa a w  s a  s         s     CC           C         s   w        s      w   Cs     ws  CS S  a w     w   S C aS s  s    S   a    a     sS a S               s   a       C  sa        w    a SC      a            asCSa     sa S   w        S         S  C      S   w     C  S     CSS        C   w s    sS  a  a S  w    CS   S     w   S        s s  w aaSw  Cs   a   w           Cw   wC C    a  S  w a        @      S     sS   CS a   w  CS     a   a     S     s   C  ss   aS   CS    s s     w   S    s      Cs s          Ca             S   w  w  w  s C  S    C            s         wC S   s w     w  |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 776
ace_score 3880
size 776, 1
stairs 112, 0

warrior 585, 0, :east

unit :thick_sludge, 2, 0, :east
unit :archer, 6, 0, :east
unit :archer, 9, 0, :east
unit :archer, 11, 0, :east
unit :archer, 13, 0, :east
unit :sludge, 16, 0, :east
unit :captive, 20, 0, :east
unit :captive, 26, 0, :east
unit :wizard, 28, 0, :east
unit :thick_sludge, 30, 0, :east
unit :sludge, 43, 0, :east
unit :sludge, 46, 0, :east
unit :archer, 47, 0, :east
unit :captive, 49, 0, :east
unit :sludge, 50, 0, :east
unit :sludge, 56, 0, :east
unit :captive, 65, 0, :east
unit :wizard, 68, 0, :east
unit :wizard, 71, 0, :east
unit :sludge, 74, 0, :east
unit :archer, 77, 0, :east
unit :captive, 81, 0, :east
unit :archer, 90, 0, :east
unit :sludge, 92, 0, :east
unit :sludge, 96, 0, :east
unit :wizard, 107, 0, :east
unit :archer, 110, 0, :east
unit :wizard, 121, 0, :east
unit :archer, 123, 0, :east
unit :captive, 124, 0, :east
unit :archer, 125, 0, :east
unit :wizard, 128, 0, :east
unit :captive, 129, 0, :east
unit :thick_sludge, 132, 0, :east
unit :thick_sludge, 133, 0, :east
unit :thick_sludge, 134, 0, :east
unit :sludge, 149, 0, :east
unit :thick_sludge, 156, 0, :east
unit :thick_sludge, 159, 0, :east
unit :captive, 164, 0, :east
unit :wizard, 168, 0, :east
unit :archer, 173, 0, :east
unit :archer, 174, 0, :east
unit :captive, 175, 0, :east
unit :archer, 176, 0, :east
unit :sludge, 181, 0, :east
unit :sludge, 184, 0, :east
unit :archer, 185, 0, :east
unit :archer, 187, 0, :east
unit :wizard, 189, 0, :east
unit :sludge, 192, 0, :east
unit :archer, 194, 0, :east
unit :sludge, 197, 0, :east
unit :sludge, 207, 0, :east
unit :captive, 213, 0, :east
unit :captive, 214, 0, :east
unit :captive, 226, 0, :east
unit :sludge, 236, 0, :east
unit :wizard, 240, 0, :east
unit :sludge, 249, 0, :east
unit :wizard, 256, 0, :east
unit :captive, 260, 0, :east
unit :sludge, 261, 0, :east
unit :wizard, 267, 0, :east
unit :sludge, 268, 0, :east
unit :captive, 271, 0, :east
unit :thick_sludge, 272, 0, :east
unit :thick_sludge, 274, 0, :east
unit :archer, 277, 0, :east
unit :wizard, 279, 0, :east
unit :wizard, 285, 0, :east
unit :thick_sludge, 289, 0, :east
unit :captive, 291, 0, :east
unit :archer, 293, 0, :east
unit :thick_sludge, 294, 0, :east
unit :sludge, 296, 0, :east
unit :sludge, 299, 0, :east
unit :thick_sludge, 304, 0, :east
unit :archer, 308, 0, :east
unit :archer, 313, 0, :east
unit :sludge, 319, 0, :east
unit :thick_sludge, 320, 0, :east
unit :archer, 322, 0, :east
unit :thick_sludge, 324, 0, :east
unit :sludge, 340, 0, :east
unit :archer, 344, 0, :east
unit :captive, 352, 0, :east
unit :sludge, 355, 0, :east
unit :archer, 356, 0, :east
unit :wizard, 365, 0, :east
unit :archer, 370, 0, :east
unit :thick_sludge, 372, 0, :east
unit :captive, 373, 0, :east
unit :archer, 380, 0, :east
unit :archer, 393, 0, :east
unit :sludge, 394, 0, :east
unit :captive, 395, 0, :east
unit :thick_sludge, 396, 0, :east
unit :archer, 397, 0, :east
unit :sludge, 403, 0, :east
unit :archer, 404, 0, :east
unit :thick_sludge, 406, 0, :east
unit :wizard, 410, 0, :east
unit :thick_sludge, 419, 0, :east
unit :thick_sludge, 429, 0, :east
unit :captive, 432, 0, :east
unit :thick_sludge, 439, 0, :east
unit :wizard, 443, 0, :east
unit :captive, 449, 0, :east
unit :thick_sludge, 452, 0, :east
unit :captive, 458, 0, :east
unit :thick_sludge, 459, 0, :east
unit :thick_sludge, 460, 0, :east
unit :captive, 469, 0, :east
unit :wizard, 473, 0, :east
unit :sludge, 475, 0, :east
unit :sludge, 480, 0, :east
unit :thick_sludge, 481, 0, :east
unit :archer, 484, 0, :east
unit :archer, 487, 0, :east
unit :thick_sludge, 489, 0, :east
unit :wizard, 492, 0, :east
unit :captive, 497, 0, :east
unit :thick_sludge, 498, 0, :east
unit :thick_sludge, 502, 0, :east
unit :wizard, 508, 0, :east
unit :thick_sludge, 512, 0, :east
unit :sludge, 521, 0, :east
unit :sludge, 523, 0, :east
unit :wizard, 526, 0, :east
unit :archer, 528, 0, :east
unit :archer, 529, 0, :east
unit :thick_sludge, 530, 0, :east
unit :wizard, 531, 0, :east
unit :captive, 534, 0, :east
unit :sludge, 535, 0, :east
unit :archer, 539, 0, :east
unit :wizard, 543, 0, :east
unit :captive, 555, 0, :east
unit :wizard, 556, 0, :east
unit :wizard, 560, 0, :east
unit :captive, 561, 0, :east
unit :captive, 563, 0, :east
unit :archer, 568, 0, :east
unit :thick_sludge, 571, 0, :east
unit :wizard, 574, 0, :east
unit :archer, 576, 0, :east
unit :thick_sludge, 592, 0, :west
unit :sludge, 598, 0, :west
unit :thick_sludge, 599, 0, :west
unit :captive, 603, 0, :west
unit :thick_sludge, 604, 0, :west
unit :archer, 606, 0, :west
unit :wizard, 610, 0, :west
unit :captive, 613, 0, :west
unit :thick_sludge, 614, 0, :west
unit :archer, 620, 0, :west
unit :archer, 624, 0, :west
unit :thick_sludge, 630, 0, :west
unit :sludge, 636, 0, :west
unit :captive, 640, 0, :west
unit :sludge, 643, 0, :west
unit :sludge, 644, 0, :west
unit :archer, 648, 0, :west
unit :thick_sludge, 649, 0, :west
unit :captive, 653, 0, :west
unit :thick_sludge, 654, 0, :west
unit :sludge, 659, 0, :west
unit :sludge, 661, 0, :west
unit :wizard, 667, 0, :west
unit :thick_sludge, 671, 0, :west
unit :sludge, 676, 0, :west
unit :captive, 683, 0, :west
unit :sludge, 684, 0, :west
unit :sludge, 686, 0, :west
unit :captive, 697, 0, :west
unit :archer, 698, 0, :west
unit :thick_sludge, 712, 0, :west
unit :wizard, 716, 0, :west
unit :wizard, 719, 0, :west
unit :wizard, 722, 0, :west
unit :sludge, 725, 0, :west
unit :captive, 727, 0, :west
unit :thick_sludge, 730, 0, :west
unit :captive, 735, 0, :west
unit :sludge, 748, 0, :west
unit :wizard, 758, 0, :west
unit :captive, 759, 0, :west
unit :thick_sludge, 761, 0, :west
unit :sludge, 765, 0, :west
unit :wizard, 767, 0, :west
unit :wizard, 773, 0, :west
