#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w s           a s a     aa   C       Cs s  s     w       w   C s   C        S  aa w S S   S     w    a    a >S        a          w   C C s           s    S     a   C w     C     C        C Cs S    C        S   S S       a   C    s w       w  a  w w  S S   S  a        ws   a Sa   ss      S   s   w     C     w    w  S             a       s Sa  aw        s             s    aC    s   w  S    S                   S a C   C aw  s  C  a  sC sw    s s s  w    CC    ss  aSC     Ss  S    C         as Csa    SS  C        SS  aa   S    s     sa       aC   aSS      Cw    w   a a  C s  s   sa     w  @   C    S a   C a     w    s ws           C   a        a   aa     ss a  C |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 669
ace_score 3345
size 669, 1
stairs 110, 0

warrior 594, 0, :east

unit :wizard, 2, 0, :east
unit :sludge, 4, 0, :east
unit :archer, 16, 0, :east
unit :sludge, 18, 0, :east
unit :archer, 20, 0, :east
unit :archer, 26, 0, :east
unit :archer, 27, 0, :east
unit :captive, 31, 0, :east
unit :captive, 39, 0, :east
unit :sludge, 40, 0, :east
unit :sludge, 42, 0, :east
unit :sludge, 45, 0, :east
unit :wizard, 51, 0, :east
unit :wizard, 59, 0, :east
unit :captive, 63, 0, :east
unit :sludge, 65, 0, :east
unit :captive, 69, 0, :east
unit :thick_sludge, 78, 0, :east
unit :archer, 81, 0, :east
unit :archer, 82, 0, :east
unit :wizard, 84, 0, :east
unit :thick_sludge, 86, 0, :east
unit :thick_sludge, 88, 0, :east
unit :thick_sludge, 92, 0, :east
unit :wizard, 98, 0, :east
unit :archer, 103, 0, :east
unit :archer, 108, 0, :east
unit :thick_sludge, 111, 0, :east
unit :archer, 120, 0, :east
unit :wizard, 131, 0, :east
unit :captive, 135, 0, :east
unit :captive, 137, 0, :east
unit :sludge, 139, 0, :east
unit :sludge, 151, 0, :east
unit :thick_sludge, 156, 0, :east
unit :archer, 162, 0, :east
unit :captive, 166, 0, :east
unit :wizard, 168, 0, :east
unit :captive, 174, 0, :east
unit :captive, 180, 0, :east
unit :captive, 189, 0, :east
unit :captive, 191, 0, :east
unit :sludge, 192, 0, :east
unit :thick_sludge, 194, 0, :east
unit :captive, 199, 0, :east
unit :thick_sludge, 208, 0, :east
unit :thick_sludge, 212, 0, :east
unit :thick_sludge, 214, 0, :east
unit :archer, 222, 0, :east
unit :captive, 226, 0, :east
unit :sludge, 231, 0, :east
unit :wizard, 233, 0, :east
unit :wizard, 241, 0, :east
unit :archer, 244, 0, :east
unit :wizard, 247, 0, :east
unit :wizard, 249, 0, :east
unit :thick_sludge, 252, 0, :east
unit :thick_sludge, 254, 0, :east
unit :thick_sludge, 258, 0, :east
unit :archer, 261, 0, :east
unit :wizard, 270, 0, :east
unit :sludge, 271, 0, :east
unit :archer, 275, 0, :east
unit :thick_sludge, 277, 0, :east
unit :archer, 278, 0, :east
unit :sludge, 282, 0, :east
unit :sludge, 283, 0, :east
unit :thick_sludge, 290, 0, :east
unit :sludge, 294, 0, :east
unit :wizard, 298, 0, :east
unit :captive, 304, 0, :east
unit :wizard, 310, 0, :east
unit :wizard, 315, 0, :east
unit :thick_sludge, 318, 0, :east
unit :archer, 332, 0, :east
unit :sludge, 340, 0, :east
unit :thick_sludge, 342, 0, :east
unit :archer, 343, 0, :east
unit :archer, 346, 0, :east
unit :wizard, 347, 0, :east
unit :sludge, 356, 0, :east
unit :sludge, 370, 0, :east
unit :archer, 375, 0, :east
unit :captive, 376, 0, :east
unit :sludge, 381, 0, :east
unit :wizard, 385, 0, :east
unit :thick_sludge, 388, 0, :east
unit :thick_sludge, 393, 0, :east
unit :thick_sludge, 413, 0, :east
unit :archer, 415, 0, :east
unit :captive, 417, 0, :east
unit :captive, 421, 0, :east
unit :archer, 423, 0, :east
unit :wizard, 424, 0, :east
unit :sludge, 427, 0, :east
unit :captive, 430, 0, :east
unit :archer, 433, 0, :east
unit :sludge, 436, 0, :east
unit :captive, 437, 0, :east
unit :sludge, 439, 0, :east
unit :wizard, 440, 0, :east
unit :sludge, 445, 0, :east
unit :sludge, 447, 0, :east
unit :sludge, 449, 0, :east
unit :wizard, 452, 0, :east
unit :captive, 457, 0, :east
unit :captive, 458, 0, :east
unit :sludge, 463, 0, :east
unit :sludge, 464, 0, :east
unit :archer, 467, 0, :east
unit :thick_sludge, 468, 0, :east
unit :captive, 469, 0, :east
unit :thick_sludge, 475, 0, :east
unit :sludge, 476, 0, :east
unit :thick_sludge, 479, 0, :east
unit :captive, 484, 0, :east
unit :archer, 494, 0, :east
unit :sludge, 495, 0, :east
unit :captive, 497, 0, :east
unit :sludge, 498, 0, :east
unit :archer, 499, 0, :east
unit :thick_sludge, 504, 0, :east
unit :thick_sludge, 505, 0, :east
unit :captive, 508, 0, :east
unit :thick_sludge, 517, 0, :east
unit :thick_sludge, 518, 0, :east
unit :archer, 521, 0, :east
unit :archer, 522, 0, :east
unit :thick_sludge, 526, 0, :east
unit :sludge, 531, 0, :east
unit :sludge, 537, 0, :east
unit :archer, 538, 0, :east
unit :archer, 546, 0, :east
unit :captive, 547, 0, :east
unit :archer, 551, 0, :east
unit :thick_sludge, 552, 0, :east
unit :thick_sludge, 553, 0, :east
unit :captive, 560, 0, :east
unit :wizard, 561, 0, :east
unit :wizard, 566, 0, :east
unit :archer, 570, 0, :east
unit :archer, 572, 0, :east
unit :captive, 575, 0, :east
unit :sludge, 577, 0, :east
unit :sludge, 580, 0, :east
unit :sludge, 584, 0, :east
unit :archer, 585, 0, :east
unit :wizard, 591, 0, :east
unit :captive, 598, 0, :west
unit :thick_sludge, 603, 0, :west
unit :archer, 605, 0, :west
unit :captive, 609, 0, :west
unit :archer, 611, 0, :west
unit :wizard, 617, 0, :west
unit :sludge, 622, 0, :west
unit :wizard, 624, 0, :west
unit :sludge, 625, 0, :west
unit :captive, 637, 0, :west
unit :archer, 641, 0, :west
unit :archer, 650, 0, :west
unit :archer, 654, 0, :west
unit :archer, 655, 0, :west
unit :sludge, 661, 0, :west
unit :sludge, 662, 0, :west
unit :archer, 664, 0, :west
unit :captive, 667, 0, :west
