#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  Caa   wCCa     w  aa         C    s          a      C   s  a     s   ass      s    C   s         w Cs      s S              a    C  w        a sS    a as   C as    w  w   a      S     S  w CCw C    C   sa    s   a    CaS   a   ss   ss         Ss  a  s  S     w      w       a   w ss     a     s          sC     s aS S   ss  ss  a  C     w   SC                 aC      w   S s   S aw   s  w          S   a s  a   S s       S   Ca       s    a            S s S C  a  @   s      a      >C    s          C         S                  sa         S   C w sw a  w CC     a s  CC S   aCs C    a          a         s         w     s    S      S     C   Cw    a   a   aC s  aw SS  w  S   S s s     C S w    C      S w    C     C w S  SC      C a  C    Ss s S   w a      S Cs     |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 770
ace_score 3850
size 770, 1
stairs 485, 0

warrior 467, 0, :east

unit :captive, 2, 0, :east
unit :archer, 3, 0, :east
unit :archer, 4, 0, :east
unit :wizard, 8, 0, :east
unit :captive, 9, 0, :east
unit :captive, 10, 0, :east
unit :archer, 11, 0, :east
unit :wizard, 17, 0, :east
unit :archer, 20, 0, :east
unit :archer, 21, 0, :east
unit :captive, 31, 0, :east
unit :sludge, 36, 0, :east
unit :archer, 47, 0, :east
unit :captive, 54, 0, :east
unit :sludge, 58, 0, :east
unit :archer, 61, 0, :east
unit :sludge, 67, 0, :east
unit :archer, 71, 0, :east
unit :sludge, 72, 0, :east
unit :sludge, 73, 0, :east
unit :sludge, 80, 0, :east
unit :captive, 85, 0, :east
unit :sludge, 89, 0, :east
unit :wizard, 99, 0, :east
unit :captive, 101, 0, :east
unit :sludge, 102, 0, :east
unit :sludge, 109, 0, :east
unit :thick_sludge, 111, 0, :east
unit :archer, 126, 0, :east
unit :captive, 131, 0, :east
unit :wizard, 134, 0, :east
unit :archer, 143, 0, :east
unit :sludge, 145, 0, :east
unit :thick_sludge, 146, 0, :east
unit :archer, 151, 0, :east
unit :archer, 153, 0, :east
unit :sludge, 154, 0, :east
unit :captive, 158, 0, :east
unit :archer, 160, 0, :east
unit :sludge, 161, 0, :east
unit :wizard, 166, 0, :east
unit :wizard, 169, 0, :east
unit :archer, 173, 0, :east
unit :thick_sludge, 180, 0, :east
unit :thick_sludge, 186, 0, :east
unit :wizard, 189, 0, :east
unit :captive, 191, 0, :east
unit :captive, 192, 0, :east
unit :wizard, 193, 0, :east
unit :captive, 195, 0, :east
unit :captive, 200, 0, :east
unit :sludge, 204, 0, :east
unit :archer, 205, 0, :east
unit :sludge, 210, 0, :east
unit :archer, 214, 0, :east
unit :captive, 219, 0, :east
unit :archer, 220, 0, :east
unit :thick_sludge, 221, 0, :east
unit :archer, 225, 0, :east
unit :sludge, 229, 0, :east
unit :sludge, 230, 0, :east
unit :sludge, 234, 0, :east
unit :sludge, 235, 0, :east
unit :thick_sludge, 245, 0, :east
unit :sludge, 246, 0, :east
unit :archer, 249, 0, :east
unit :sludge, 252, 0, :east
unit :thick_sludge, 255, 0, :east
unit :wizard, 261, 0, :east
unit :wizard, 268, 0, :east
unit :archer, 276, 0, :east
unit :wizard, 280, 0, :east
unit :sludge, 282, 0, :east
unit :sludge, 283, 0, :east
unit :archer, 289, 0, :east
unit :sludge, 295, 0, :east
unit :sludge, 306, 0, :east
unit :captive, 307, 0, :east
unit :sludge, 313, 0, :east
unit :archer, 315, 0, :east
unit :thick_sludge, 316, 0, :east
unit :thick_sludge, 318, 0, :east
unit :sludge, 322, 0, :east
unit :sludge, 323, 0, :east
unit :sludge, 326, 0, :east
unit :sludge, 327, 0, :east
unit :archer, 330, 0, :east
unit :captive, 333, 0, :east
unit :wizard, 339, 0, :east
unit :thick_sludge, 343, 0, :east
unit :captive, 344, 0, :east
unit :archer, 362, 0, :east
unit :captive, 363, 0, :east
unit :wizard, 370, 0, :east
unit :thick_sludge, 374, 0, :east
unit :sludge, 376, 0, :east
unit :thick_sludge, 380, 0, :east
unit :archer, 382, 0, :east
unit :wizard, 383, 0, :east
unit :sludge, 387, 0, :east
unit :wizard, 390, 0, :east
unit :thick_sludge, 401, 0, :east
unit :archer, 405, 0, :east
unit :sludge, 407, 0, :east
unit :archer, 410, 0, :east
unit :thick_sludge, 414, 0, :east
unit :sludge, 416, 0, :east
unit :thick_sludge, 424, 0, :east
unit :captive, 428, 0, :east
unit :archer, 429, 0, :east
unit :sludge, 437, 0, :east
unit :archer, 442, 0, :east
unit :thick_sludge, 455, 0, :east
unit :sludge, 457, 0, :east
unit :thick_sludge, 459, 0, :east
unit :captive, 461, 0, :east
unit :archer, 464, 0, :east
unit :sludge, 471, 0, :west
unit :archer, 478, 0, :west
unit :captive, 486, 0, :west
unit :sludge, 491, 0, :west
unit :captive, 502, 0, :west
unit :thick_sludge, 512, 0, :west
unit :sludge, 531, 0, :west
unit :archer, 532, 0, :west
unit :thick_sludge, 542, 0, :west
unit :captive, 546, 0, :west
unit :wizard, 548, 0, :west
unit :sludge, 550, 0, :west
unit :wizard, 551, 0, :west
unit :archer, 553, 0, :west
unit :wizard, 556, 0, :west
unit :captive, 558, 0, :west
unit :captive, 559, 0, :west
unit :archer, 565, 0, :west
unit :sludge, 567, 0, :west
unit :captive, 570, 0, :west
unit :captive, 571, 0, :west
unit :thick_sludge, 573, 0, :west
unit :archer, 577, 0, :west
unit :captive, 578, 0, :west
unit :sludge, 579, 0, :west
unit :captive, 581, 0, :west
unit :archer, 586, 0, :west
unit :archer, 597, 0, :west
unit :sludge, 607, 0, :west
unit :wizard, 617, 0, :west
unit :sludge, 623, 0, :west
unit :thick_sludge, 628, 0, :west
unit :thick_sludge, 635, 0, :west
unit :captive, 641, 0, :west
unit :captive, 645, 0, :west
unit :wizard, 646, 0, :west
unit :archer, 651, 0, :west
unit :archer, 655, 0, :west
unit :archer, 659, 0, :west
unit :captive, 660, 0, :west
unit :sludge, 662, 0, :west
unit :archer, 665, 0, :west
unit :wizard, 666, 0, :west
unit :thick_sludge, 668, 0, :west
unit :thick_sludge, 669, 0, :west
unit :wizard, 672, 0, :west
unit :thick_sludge, 675, 0, :west
unit :thick_sludge, 679, 0, :west
unit :sludge, 681, 0, :west
unit :sludge, 683, 0, :west
unit :captive, 689, 0, :west
unit :thick_sludge, 691, 0, :west
unit :wizard, 693, 0, :west
unit :captive, 698, 0, :west
unit :thick_sludge, 705, 0, :west
unit :wizard, 707, 0, :west
unit :captive, 712, 0, :west
unit :captive, 718, 0, :west
unit :wizard, 720, 0, :west
unit :thick_sludge, 722, 0, :west
unit :thick_sludge, 725, 0, :west
unit :captive, 726, 0, :west
unit :captive, 733, 0, :west
unit :archer, 735, 0, :west
unit :captive, 738, 0, :west
unit :thick_sludge, 743, 0, :west
unit :sludge, 744, 0, :west
unit :sludge, 746, 0, :west
unit :thick_sludge, 748, 0, :west
unit :wizard, 752, 0, :west
unit :archer, 754, 0, :west
unit :thick_sludge, 761, 0, :west
unit :captive, 763, 0, :west
unit :sludge, 764, 0, :west
