#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    aC     a  s   w   C  S   a     S CS     > aC    wC      s C     S   C  a        C           aS       w    as  w     s   C          a a C    SS w      Ca    CS       S      w            a   S C      a   a    s  S s     C   s  a      a     w  w  S Cw  s  s  a      s    C    C     w C a asw s                          a     S    w   C   s  C  a    aS  S w a CsSw           s s   S C     CSSs            C a      w  sC  w   Csaa      wS a C      a        S aaC as  s            s s      a    a     a s sa      S       s a      C   C   w w  a      a w     w  S  S        a     aa     a C  s  C       S   Ss  C  wS CCaS sS sS        a   s     s    @      aS         a           a  s s Sa a     w|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 694
ace_score 3470
size 694, 1
stairs 44, 0

warrior 647, 0, :east

unit :archer, 4, 0, :east
unit :captive, 5, 0, :east
unit :archer, 11, 0, :east
unit :sludge, 14, 0, :east
unit :wizard, 18, 0, :east
unit :captive, 22, 0, :east
unit :thick_sludge, 25, 0, :east
unit :archer, 29, 0, :east
unit :thick_sludge, 35, 0, :east
unit :captive, 37, 0, :east
unit :thick_sludge, 38, 0, :east
unit :archer, 46, 0, :east
unit :captive, 47, 0, :east
unit :wizard, 52, 0, :east
unit :captive, 53, 0, :east
unit :sludge, 60, 0, :east
unit :captive, 62, 0, :east
unit :thick_sludge, 68, 0, :east
unit :captive, 72, 0, :east
unit :archer, 75, 0, :east
unit :captive, 84, 0, :east
unit :archer, 96, 0, :east
unit :thick_sludge, 97, 0, :east
unit :wizard, 105, 0, :east
unit :archer, 110, 0, :east
unit :sludge, 111, 0, :east
unit :wizard, 114, 0, :east
unit :sludge, 120, 0, :east
unit :captive, 124, 0, :east
unit :archer, 135, 0, :east
unit :archer, 137, 0, :east
unit :captive, 139, 0, :east
unit :thick_sludge, 144, 0, :east
unit :thick_sludge, 145, 0, :east
unit :wizard, 147, 0, :east
unit :captive, 154, 0, :east
unit :archer, 155, 0, :east
unit :captive, 160, 0, :east
unit :thick_sludge, 161, 0, :east
unit :thick_sludge, 169, 0, :east
unit :wizard, 176, 0, :east
unit :archer, 189, 0, :east
unit :thick_sludge, 193, 0, :east
unit :captive, 195, 0, :east
unit :archer, 202, 0, :east
unit :archer, 206, 0, :east
unit :sludge, 211, 0, :east
unit :thick_sludge, 214, 0, :east
unit :sludge, 216, 0, :east
unit :captive, 222, 0, :east
unit :sludge, 226, 0, :east
unit :archer, 229, 0, :east
unit :archer, 236, 0, :east
unit :wizard, 242, 0, :east
unit :wizard, 245, 0, :east
unit :thick_sludge, 248, 0, :east
unit :captive, 250, 0, :east
unit :wizard, 251, 0, :east
unit :sludge, 254, 0, :east
unit :sludge, 257, 0, :east
unit :archer, 260, 0, :east
unit :sludge, 267, 0, :east
unit :captive, 272, 0, :east
unit :captive, 277, 0, :east
unit :wizard, 283, 0, :east
unit :captive, 285, 0, :east
unit :archer, 287, 0, :east
unit :archer, 289, 0, :east
unit :sludge, 290, 0, :east
unit :wizard, 291, 0, :east
unit :sludge, 293, 0, :east
unit :archer, 320, 0, :east
unit :thick_sludge, 326, 0, :east
unit :wizard, 331, 0, :east
unit :captive, 335, 0, :east
unit :sludge, 339, 0, :east
unit :captive, 342, 0, :east
unit :archer, 345, 0, :east
unit :archer, 350, 0, :east
unit :thick_sludge, 351, 0, :east
unit :thick_sludge, 354, 0, :east
unit :wizard, 356, 0, :east
unit :archer, 358, 0, :east
unit :captive, 360, 0, :east
unit :sludge, 361, 0, :east
unit :thick_sludge, 362, 0, :east
unit :wizard, 363, 0, :east
unit :sludge, 375, 0, :east
unit :sludge, 377, 0, :east
unit :thick_sludge, 381, 0, :east
unit :captive, 383, 0, :east
unit :captive, 389, 0, :east
unit :thick_sludge, 390, 0, :east
unit :thick_sludge, 391, 0, :east
unit :sludge, 392, 0, :east
unit :captive, 405, 0, :east
unit :archer, 407, 0, :east
unit :wizard, 414, 0, :east
unit :sludge, 417, 0, :east
unit :captive, 418, 0, :east
unit :wizard, 421, 0, :east
unit :captive, 425, 0, :east
unit :sludge, 426, 0, :east
unit :archer, 427, 0, :east
unit :archer, 428, 0, :east
unit :wizard, 435, 0, :east
unit :thick_sludge, 436, 0, :east
unit :archer, 438, 0, :east
unit :captive, 440, 0, :east
unit :archer, 447, 0, :east
unit :thick_sludge, 456, 0, :east
unit :archer, 458, 0, :east
unit :archer, 459, 0, :east
unit :captive, 460, 0, :east
unit :archer, 462, 0, :east
unit :sludge, 463, 0, :east
unit :sludge, 466, 0, :east
unit :sludge, 479, 0, :east
unit :sludge, 481, 0, :east
unit :archer, 488, 0, :east
unit :archer, 493, 0, :east
unit :archer, 499, 0, :east
unit :sludge, 501, 0, :east
unit :sludge, 503, 0, :east
unit :archer, 504, 0, :east
unit :thick_sludge, 511, 0, :east
unit :sludge, 519, 0, :east
unit :archer, 521, 0, :east
unit :captive, 528, 0, :east
unit :captive, 532, 0, :east
unit :wizard, 536, 0, :east
unit :wizard, 538, 0, :east
unit :archer, 541, 0, :east
unit :archer, 548, 0, :east
unit :wizard, 550, 0, :east
unit :wizard, 556, 0, :east
unit :thick_sludge, 559, 0, :east
unit :thick_sludge, 562, 0, :east
unit :archer, 571, 0, :east
unit :archer, 577, 0, :east
unit :archer, 578, 0, :east
unit :archer, 584, 0, :east
unit :captive, 586, 0, :east
unit :sludge, 589, 0, :east
unit :captive, 592, 0, :east
unit :thick_sludge, 600, 0, :east
unit :thick_sludge, 604, 0, :east
unit :sludge, 605, 0, :east
unit :captive, 608, 0, :east
unit :wizard, 611, 0, :east
unit :thick_sludge, 612, 0, :east
unit :captive, 614, 0, :east
unit :captive, 615, 0, :east
unit :archer, 616, 0, :east
unit :thick_sludge, 617, 0, :east
unit :sludge, 619, 0, :east
unit :thick_sludge, 620, 0, :east
unit :sludge, 622, 0, :east
unit :thick_sludge, 623, 0, :east
unit :archer, 632, 0, :east
unit :sludge, 636, 0, :east
unit :sludge, 642, 0, :east
unit :archer, 654, 0, :west
unit :thick_sludge, 655, 0, :west
unit :archer, 665, 0, :west
unit :archer, 677, 0, :west
unit :sludge, 680, 0, :west
unit :sludge, 682, 0, :west
unit :thick_sludge, 684, 0, :west
unit :archer, 685, 0, :west
unit :archer, 687, 0, :west
unit :wizard, 693, 0, :west
