#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | aS w s  w     s     S           S   C   s             S   a   SS   S  w      w   C          C  C           S          C s      w w        Cw C    S    S S       C   Csw    aa   S  s  w   s  sCa      S    s  w C aC     a aS  wC as sw Ca    a  Ss         CC   w  C       S   C aS     s      w aS   s s C     SSa  a   w  s  s s                aa C S  a a      s     a w  Cw  S ss CSw            C    w        s   s a s         s    sS    C  Sa  a  C   a   s    wS     a   w   w s       w    SCC    S  w        C      SC                    a C S  Casa            s C         w            w     a  s a ss      a    w         C    C   a s         wa    aa   S   s ssCaS                  w    a    SS                 s  w     S  C sw  C  a     C  sCS      as  w    SC      a  C            Ca S>s  s     S   S     s   C   s as aC s    s s sS       S     @  S    a   a      CC a   S w  s         w    CC           CC   aC  s  s      w  w    S |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 935
ace_score 4675
size 935, 1
stairs 787, 0

warrior 847, 0, :east

unit :archer, 1, 0, :east
unit :thick_sludge, 2, 0, :east
unit :wizard, 4, 0, :east
unit :sludge, 6, 0, :east
unit :wizard, 9, 0, :east
unit :sludge, 15, 0, :east
unit :thick_sludge, 21, 0, :east
unit :thick_sludge, 33, 0, :east
unit :captive, 37, 0, :east
unit :sludge, 41, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 59, 0, :east
unit :thick_sludge, 63, 0, :east
unit :thick_sludge, 64, 0, :east
unit :thick_sludge, 68, 0, :east
unit :wizard, 71, 0, :east
unit :wizard, 78, 0, :east
unit :captive, 82, 0, :east
unit :captive, 93, 0, :east
unit :captive, 96, 0, :east
unit :thick_sludge, 108, 0, :east
unit :captive, 119, 0, :east
unit :sludge, 121, 0, :east
unit :wizard, 128, 0, :east
unit :wizard, 130, 0, :east
unit :captive, 139, 0, :east
unit :wizard, 140, 0, :east
unit :captive, 142, 0, :east
unit :thick_sludge, 147, 0, :east
unit :thick_sludge, 152, 0, :east
unit :thick_sludge, 154, 0, :east
unit :captive, 162, 0, :east
unit :captive, 166, 0, :east
unit :sludge, 167, 0, :east
unit :wizard, 168, 0, :east
unit :archer, 173, 0, :east
unit :archer, 174, 0, :east
unit :thick_sludge, 178, 0, :east
unit :sludge, 181, 0, :east
unit :wizard, 184, 0, :east
unit :sludge, 188, 0, :east
unit :sludge, 191, 0, :east
unit :captive, 192, 0, :east
unit :archer, 193, 0, :east
unit :thick_sludge, 200, 0, :east
unit :sludge, 205, 0, :east
unit :wizard, 208, 0, :east
unit :captive, 210, 0, :east
unit :archer, 212, 0, :east
unit :captive, 213, 0, :east
unit :archer, 219, 0, :east
unit :archer, 221, 0, :east
unit :thick_sludge, 222, 0, :east
unit :wizard, 225, 0, :east
unit :captive, 226, 0, :east
unit :archer, 228, 0, :east
unit :sludge, 229, 0, :east
unit :sludge, 231, 0, :east
unit :wizard, 232, 0, :east
unit :captive, 234, 0, :east
unit :archer, 235, 0, :east
unit :archer, 240, 0, :east
unit :thick_sludge, 243, 0, :east
unit :sludge, 244, 0, :east
unit :captive, 254, 0, :east
unit :captive, 255, 0, :east
unit :wizard, 259, 0, :east
unit :captive, 262, 0, :east
unit :thick_sludge, 270, 0, :east
unit :captive, 274, 0, :east
unit :archer, 276, 0, :east
unit :thick_sludge, 277, 0, :east
unit :sludge, 283, 0, :east
unit :wizard, 290, 0, :east
unit :archer, 292, 0, :east
unit :thick_sludge, 293, 0, :east
unit :sludge, 297, 0, :east
unit :sludge, 299, 0, :east
unit :captive, 301, 0, :east
unit :thick_sludge, 307, 0, :east
unit :thick_sludge, 308, 0, :east
unit :archer, 309, 0, :east
unit :archer, 312, 0, :east
unit :wizard, 316, 0, :east
unit :sludge, 319, 0, :east
unit :sludge, 322, 0, :east
unit :sludge, 324, 0, :east
unit :archer, 341, 0, :east
unit :archer, 342, 0, :east
unit :captive, 344, 0, :east
unit :thick_sludge, 346, 0, :east
unit :archer, 349, 0, :east
unit :archer, 351, 0, :east
unit :sludge, 358, 0, :east
unit :archer, 364, 0, :east
unit :wizard, 366, 0, :east
unit :captive, 369, 0, :east
unit :wizard, 370, 0, :east
unit :thick_sludge, 373, 0, :east
unit :sludge, 375, 0, :east
unit :sludge, 376, 0, :east
unit :captive, 378, 0, :east
unit :thick_sludge, 379, 0, :east
unit :wizard, 380, 0, :east
unit :captive, 393, 0, :east
unit :wizard, 398, 0, :east
unit :sludge, 407, 0, :east
unit :sludge, 411, 0, :east
unit :archer, 413, 0, :east
unit :sludge, 415, 0, :east
unit :sludge, 425, 0, :east
unit :sludge, 430, 0, :east
unit :thick_sludge, 431, 0, :east
unit :captive, 436, 0, :east
unit :thick_sludge, 439, 0, :east
unit :archer, 440, 0, :east
unit :archer, 443, 0, :east
unit :captive, 446, 0, :east
unit :archer, 450, 0, :east
unit :sludge, 454, 0, :east
unit :wizard, 459, 0, :east
unit :thick_sludge, 460, 0, :east
unit :archer, 466, 0, :east
unit :wizard, 470, 0, :east
unit :wizard, 474, 0, :east
unit :sludge, 476, 0, :east
unit :wizard, 484, 0, :east
unit :thick_sludge, 489, 0, :east
unit :captive, 490, 0, :east
unit :captive, 491, 0, :east
unit :thick_sludge, 496, 0, :east
unit :wizard, 499, 0, :east
unit :captive, 508, 0, :east
unit :thick_sludge, 515, 0, :east
unit :captive, 516, 0, :east
unit :archer, 537, 0, :east
unit :captive, 539, 0, :east
unit :thick_sludge, 541, 0, :east
unit :captive, 544, 0, :east
unit :archer, 545, 0, :east
unit :sludge, 546, 0, :east
unit :archer, 547, 0, :east
unit :sludge, 560, 0, :east
unit :captive, 562, 0, :east
unit :wizard, 572, 0, :east
unit :wizard, 585, 0, :east
unit :archer, 591, 0, :east
unit :sludge, 594, 0, :east
unit :archer, 596, 0, :east
unit :sludge, 598, 0, :east
unit :sludge, 599, 0, :east
unit :archer, 606, 0, :east
unit :wizard, 611, 0, :east
unit :captive, 621, 0, :east
unit :captive, 626, 0, :east
unit :archer, 630, 0, :east
unit :sludge, 632, 0, :east
unit :wizard, 642, 0, :east
unit :archer, 643, 0, :east
unit :archer, 648, 0, :east
unit :archer, 649, 0, :east
unit :thick_sludge, 653, 0, :east
unit :sludge, 657, 0, :east
unit :sludge, 659, 0, :east
unit :sludge, 660, 0, :east
unit :captive, 661, 0, :east
unit :archer, 662, 0, :east
unit :thick_sludge, 663, 0, :east
unit :wizard, 682, 0, :east
unit :archer, 687, 0, :east
unit :thick_sludge, 692, 0, :east
unit :thick_sludge, 693, 0, :east
unit :sludge, 711, 0, :east
unit :wizard, 714, 0, :east
unit :thick_sludge, 720, 0, :east
unit :captive, 723, 0, :east
unit :sludge, 725, 0, :east
unit :wizard, 726, 0, :east
unit :captive, 729, 0, :east
unit :archer, 732, 0, :east
unit :captive, 738, 0, :east
unit :sludge, 741, 0, :east
unit :captive, 742, 0, :east
unit :thick_sludge, 743, 0, :east
unit :archer, 750, 0, :east
unit :sludge, 751, 0, :east
unit :wizard, 754, 0, :east
unit :thick_sludge, 759, 0, :east
unit :captive, 760, 0, :east
unit :archer, 767, 0, :east
unit :captive, 770, 0, :east
unit :captive, 783, 0, :east
unit :archer, 784, 0, :east
unit :thick_sludge, 786, 0, :east
unit :sludge, 788, 0, :east
unit :sludge, 791, 0, :east
unit :thick_sludge, 797, 0, :east
unit :thick_sludge, 801, 0, :east
unit :sludge, 807, 0, :east
unit :captive, 811, 0, :east
unit :sludge, 815, 0, :east
unit :archer, 817, 0, :east
unit :sludge, 818, 0, :east
unit :archer, 820, 0, :east
unit :captive, 821, 0, :east
unit :sludge, 823, 0, :east
unit :sludge, 828, 0, :east
unit :sludge, 830, 0, :east
unit :sludge, 832, 0, :east
unit :thick_sludge, 833, 0, :east
unit :thick_sludge, 841, 0, :east
unit :thick_sludge, 850, 0, :west
unit :archer, 855, 0, :west
unit :archer, 859, 0, :west
unit :captive, 866, 0, :west
unit :captive, 867, 0, :west
unit :archer, 869, 0, :west
unit :thick_sludge, 873, 0, :west
unit :wizard, 875, 0, :west
unit :sludge, 878, 0, :west
unit :wizard, 888, 0, :west
unit :captive, 893, 0, :west
unit :captive, 894, 0, :west
unit :captive, 906, 0, :west
unit :captive, 907, 0, :west
unit :archer, 911, 0, :west
unit :captive, 912, 0, :west
unit :sludge, 915, 0, :west
unit :sludge, 918, 0, :west
unit :wizard, 925, 0, :west
unit :wizard, 928, 0, :west
unit :thick_sludge, 933, 0, :west
