#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s     S             w C  s    s s   s      S   w Sw   s  S      C S      Ss  S  w           w    a  aS     s   C    S         S CS       a aS  w  aa    a     S   w a    w  aC C           w s   s  a   w as   w     as                   w   S aa w a w  as a         a       a   S      s S  ws       a        s         s a S       w   a              s S     sC C  wS   s  S   a SCs C      Cw  @     a SC Sw sw   w  CC   C   C s   C    a            C                        w    w  C    C  Cs w  sa   C        aC        s     S s        C C C     s w C w     a     C Ss S CC a  Cs             aSsC   a s  w    a s   a S S  s      a w     C a     > s         s  SC  w     S w S       s      s S s   s   sa     a w w  a   C Ss   Cw  C      C       s a      w a   SC            C S        C   C C    s  w s     s   S  a   w s   s   aC  S    a        a  a   w         S     s     s   s   C C a Ca       a  s  C w    w  |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 912
ace_score 4560
size 912, 1
stairs 643, 0

warrior 391, 0, :east

unit :sludge, 2, 0, :east
unit :thick_sludge, 8, 0, :east
unit :wizard, 22, 0, :east
unit :captive, 24, 0, :east
unit :sludge, 27, 0, :east
unit :sludge, 32, 0, :east
unit :sludge, 34, 0, :east
unit :sludge, 38, 0, :east
unit :thick_sludge, 45, 0, :east
unit :wizard, 49, 0, :east
unit :thick_sludge, 51, 0, :east
unit :wizard, 52, 0, :east
unit :sludge, 56, 0, :east
unit :thick_sludge, 59, 0, :east
unit :captive, 66, 0, :east
unit :thick_sludge, 68, 0, :east
unit :thick_sludge, 75, 0, :east
unit :sludge, 76, 0, :east
unit :thick_sludge, 79, 0, :east
unit :wizard, 82, 0, :east
unit :wizard, 94, 0, :east
unit :archer, 99, 0, :east
unit :archer, 102, 0, :east
unit :thick_sludge, 103, 0, :east
unit :sludge, 109, 0, :east
unit :captive, 113, 0, :east
unit :thick_sludge, 118, 0, :east
unit :thick_sludge, 128, 0, :east
unit :captive, 130, 0, :east
unit :thick_sludge, 131, 0, :east
unit :archer, 139, 0, :east
unit :archer, 141, 0, :east
unit :thick_sludge, 142, 0, :east
unit :wizard, 145, 0, :east
unit :archer, 148, 0, :east
unit :archer, 149, 0, :east
unit :archer, 154, 0, :east
unit :thick_sludge, 160, 0, :east
unit :wizard, 164, 0, :east
unit :archer, 166, 0, :east
unit :wizard, 171, 0, :east
unit :archer, 174, 0, :east
unit :captive, 175, 0, :east
unit :captive, 177, 0, :east
unit :wizard, 189, 0, :east
unit :sludge, 191, 0, :east
unit :sludge, 195, 0, :east
unit :archer, 198, 0, :east
unit :wizard, 202, 0, :east
unit :archer, 204, 0, :east
unit :sludge, 205, 0, :east
unit :wizard, 209, 0, :east
unit :archer, 215, 0, :east
unit :sludge, 216, 0, :east
unit :wizard, 236, 0, :east
unit :thick_sludge, 240, 0, :east
unit :archer, 242, 0, :east
unit :archer, 243, 0, :east
unit :wizard, 245, 0, :east
unit :archer, 247, 0, :east
unit :wizard, 249, 0, :east
unit :archer, 252, 0, :east
unit :sludge, 253, 0, :east
unit :archer, 255, 0, :east
unit :archer, 265, 0, :east
unit :archer, 273, 0, :east
unit :thick_sludge, 277, 0, :east
unit :sludge, 284, 0, :east
unit :thick_sludge, 286, 0, :east
unit :wizard, 289, 0, :east
unit :sludge, 290, 0, :east
unit :archer, 298, 0, :east
unit :sludge, 307, 0, :east
unit :sludge, 317, 0, :east
unit :archer, 319, 0, :east
unit :thick_sludge, 321, 0, :east
unit :wizard, 329, 0, :east
unit :archer, 333, 0, :east
unit :sludge, 348, 0, :east
unit :thick_sludge, 350, 0, :east
unit :sludge, 356, 0, :east
unit :captive, 357, 0, :east
unit :captive, 359, 0, :east
unit :wizard, 362, 0, :east
unit :thick_sludge, 363, 0, :east
unit :sludge, 367, 0, :east
unit :thick_sludge, 370, 0, :east
unit :archer, 374, 0, :east
unit :thick_sludge, 376, 0, :east
unit :captive, 377, 0, :east
unit :sludge, 378, 0, :east
unit :captive, 380, 0, :east
unit :captive, 387, 0, :east
unit :wizard, 388, 0, :east
unit :archer, 397, 0, :west
unit :thick_sludge, 399, 0, :west
unit :captive, 400, 0, :west
unit :thick_sludge, 402, 0, :west
unit :wizard, 403, 0, :west
unit :sludge, 405, 0, :west
unit :wizard, 406, 0, :west
unit :wizard, 410, 0, :west
unit :captive, 413, 0, :west
unit :captive, 414, 0, :west
unit :captive, 418, 0, :west
unit :captive, 422, 0, :west
unit :sludge, 424, 0, :west
unit :captive, 428, 0, :west
unit :archer, 433, 0, :west
unit :captive, 446, 0, :west
unit :wizard, 471, 0, :west
unit :wizard, 476, 0, :west
unit :captive, 479, 0, :west
unit :captive, 484, 0, :west
unit :captive, 487, 0, :west
unit :sludge, 488, 0, :west
unit :wizard, 490, 0, :west
unit :sludge, 493, 0, :west
unit :archer, 494, 0, :west
unit :captive, 498, 0, :west
unit :archer, 507, 0, :west
unit :captive, 508, 0, :west
unit :sludge, 517, 0, :west
unit :thick_sludge, 523, 0, :west
unit :sludge, 525, 0, :west
unit :captive, 534, 0, :west
unit :captive, 536, 0, :west
unit :captive, 538, 0, :west
unit :sludge, 544, 0, :west
unit :wizard, 546, 0, :west
unit :captive, 548, 0, :west
unit :wizard, 550, 0, :west
unit :archer, 556, 0, :west
unit :captive, 562, 0, :west
unit :thick_sludge, 564, 0, :west
unit :sludge, 565, 0, :west
unit :thick_sludge, 567, 0, :west
unit :captive, 569, 0, :west
unit :captive, 570, 0, :west
unit :archer, 572, 0, :west
unit :captive, 575, 0, :west
unit :sludge, 576, 0, :west
unit :archer, 590, 0, :west
unit :thick_sludge, 591, 0, :west
unit :sludge, 592, 0, :west
unit :captive, 593, 0, :west
unit :archer, 597, 0, :west
unit :sludge, 599, 0, :west
unit :wizard, 602, 0, :west
unit :archer, 607, 0, :west
unit :sludge, 609, 0, :west
unit :archer, 613, 0, :west
unit :thick_sludge, 615, 0, :west
unit :thick_sludge, 617, 0, :west
unit :sludge, 620, 0, :west
unit :archer, 627, 0, :west
unit :wizard, 629, 0, :west
unit :captive, 635, 0, :west
unit :archer, 637, 0, :west
unit :sludge, 645, 0, :west
unit :sludge, 655, 0, :west
unit :thick_sludge, 658, 0, :west
unit :captive, 659, 0, :west
unit :wizard, 662, 0, :west
unit :thick_sludge, 668, 0, :west
unit :wizard, 670, 0, :west
unit :thick_sludge, 672, 0, :west
unit :sludge, 680, 0, :west
unit :sludge, 687, 0, :west
unit :thick_sludge, 689, 0, :west
unit :sludge, 691, 0, :west
unit :sludge, 695, 0, :west
unit :sludge, 699, 0, :west
unit :archer, 700, 0, :west
unit :archer, 706, 0, :west
unit :wizard, 708, 0, :west
unit :wizard, 710, 0, :west
unit :archer, 713, 0, :west
unit :captive, 717, 0, :west
unit :thick_sludge, 719, 0, :west
unit :sludge, 720, 0, :west
unit :captive, 724, 0, :west
unit :wizard, 725, 0, :west
unit :captive, 728, 0, :west
unit :captive, 735, 0, :west
unit :sludge, 743, 0, :west
unit :archer, 745, 0, :west
unit :wizard, 752, 0, :west
unit :archer, 754, 0, :west
unit :thick_sludge, 758, 0, :west
unit :captive, 759, 0, :west
unit :captive, 772, 0, :west
unit :thick_sludge, 774, 0, :west
unit :captive, 783, 0, :west
unit :captive, 787, 0, :west
unit :captive, 789, 0, :west
unit :sludge, 794, 0, :west
unit :wizard, 797, 0, :west
unit :sludge, 799, 0, :west
unit :sludge, 805, 0, :west
unit :thick_sludge, 809, 0, :west
unit :archer, 812, 0, :west
unit :wizard, 816, 0, :west
unit :sludge, 818, 0, :west
unit :sludge, 822, 0, :west
unit :archer, 826, 0, :west
unit :captive, 827, 0, :west
unit :thick_sludge, 830, 0, :west
unit :archer, 835, 0, :west
unit :archer, 844, 0, :west
unit :archer, 847, 0, :west
unit :wizard, 851, 0, :west
unit :thick_sludge, 861, 0, :west
unit :sludge, 867, 0, :west
unit :sludge, 873, 0, :west
unit :sludge, 877, 0, :west
unit :captive, 881, 0, :west
unit :captive, 883, 0, :west
unit :archer, 885, 0, :west
unit :captive, 887, 0, :west
unit :archer, 888, 0, :west
unit :archer, 896, 0, :west
unit :sludge, 899, 0, :west
unit :captive, 902, 0, :west
unit :wizard, 904, 0, :west
unit :wizard, 909, 0, :west
