#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       C s      a     w  a          C      S        a a       a w Ca     C a       S     SssS w Sa    s  s     C   CC w            w      SS S C S         a    s           a  C        C      s   CS C         CC   a   Ss sC       w     w      S   C     S s C    C  CsSs    s                    C  C       C    CSsa  a            a  a s Cs  s    w  SS   s     S  ws   > w      @  S    s  ss  S      S    C C w     ss S   C S   C             a   a    Ss    a a  w       a aa   s as  a  w  wC       S   w  C  S   C    S  s    a     s    s C   S S SS C  w     SC  w    Ca         aa s      S S          s    S      S S        a S     aaSs Cssa         s        S        s aw w S C    s|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 680
ace_score 3400
size 680, 1
stairs 366, 0

warrior 375, 0, :east

unit :captive, 7, 0, :east
unit :sludge, 9, 0, :east
unit :archer, 16, 0, :east
unit :wizard, 22, 0, :east
unit :archer, 25, 0, :east
unit :captive, 36, 0, :east
unit :thick_sludge, 43, 0, :east
unit :archer, 52, 0, :east
unit :archer, 54, 0, :east
unit :archer, 62, 0, :east
unit :wizard, 64, 0, :east
unit :captive, 66, 0, :east
unit :archer, 67, 0, :east
unit :captive, 73, 0, :east
unit :archer, 75, 0, :east
unit :thick_sludge, 83, 0, :east
unit :thick_sludge, 89, 0, :east
unit :sludge, 90, 0, :east
unit :sludge, 91, 0, :east
unit :thick_sludge, 92, 0, :east
unit :wizard, 94, 0, :east
unit :thick_sludge, 96, 0, :east
unit :archer, 97, 0, :east
unit :sludge, 102, 0, :east
unit :sludge, 105, 0, :east
unit :captive, 111, 0, :east
unit :captive, 115, 0, :east
unit :captive, 116, 0, :east
unit :wizard, 118, 0, :east
unit :wizard, 131, 0, :east
unit :thick_sludge, 138, 0, :east
unit :thick_sludge, 139, 0, :east
unit :thick_sludge, 141, 0, :east
unit :captive, 143, 0, :east
unit :thick_sludge, 145, 0, :east
unit :archer, 155, 0, :east
unit :sludge, 160, 0, :east
unit :archer, 172, 0, :east
unit :captive, 175, 0, :east
unit :captive, 184, 0, :east
unit :sludge, 191, 0, :east
unit :captive, 195, 0, :east
unit :thick_sludge, 196, 0, :east
unit :captive, 198, 0, :east
unit :captive, 208, 0, :east
unit :captive, 209, 0, :east
unit :archer, 213, 0, :east
unit :thick_sludge, 217, 0, :east
unit :sludge, 218, 0, :east
unit :sludge, 220, 0, :east
unit :captive, 221, 0, :east
unit :wizard, 229, 0, :east
unit :wizard, 235, 0, :east
unit :thick_sludge, 242, 0, :east
unit :captive, 246, 0, :east
unit :thick_sludge, 252, 0, :east
unit :sludge, 254, 0, :east
unit :captive, 256, 0, :east
unit :captive, 261, 0, :east
unit :captive, 264, 0, :east
unit :sludge, 265, 0, :east
unit :thick_sludge, 266, 0, :east
unit :sludge, 267, 0, :east
unit :sludge, 272, 0, :east
unit :captive, 293, 0, :east
unit :captive, 296, 0, :east
unit :captive, 304, 0, :east
unit :captive, 309, 0, :east
unit :thick_sludge, 310, 0, :east
unit :sludge, 311, 0, :east
unit :archer, 312, 0, :east
unit :archer, 315, 0, :east
unit :archer, 328, 0, :east
unit :archer, 331, 0, :east
unit :sludge, 333, 0, :east
unit :captive, 335, 0, :east
unit :sludge, 336, 0, :east
unit :sludge, 339, 0, :east
unit :wizard, 344, 0, :east
unit :thick_sludge, 347, 0, :east
unit :thick_sludge, 348, 0, :east
unit :sludge, 352, 0, :east
unit :thick_sludge, 358, 0, :east
unit :wizard, 361, 0, :east
unit :sludge, 362, 0, :east
unit :wizard, 368, 0, :east
unit :thick_sludge, 378, 0, :west
unit :sludge, 383, 0, :west
unit :sludge, 386, 0, :west
unit :sludge, 387, 0, :west
unit :thick_sludge, 390, 0, :west
unit :thick_sludge, 397, 0, :west
unit :captive, 402, 0, :west
unit :captive, 404, 0, :west
unit :wizard, 406, 0, :west
unit :sludge, 412, 0, :west
unit :sludge, 413, 0, :west
unit :thick_sludge, 415, 0, :west
unit :captive, 419, 0, :west
unit :thick_sludge, 421, 0, :west
unit :captive, 425, 0, :west
unit :archer, 439, 0, :west
unit :archer, 443, 0, :west
unit :thick_sludge, 448, 0, :west
unit :sludge, 449, 0, :west
unit :archer, 454, 0, :west
unit :archer, 456, 0, :west
unit :wizard, 459, 0, :west
unit :archer, 467, 0, :west
unit :archer, 469, 0, :west
unit :archer, 470, 0, :west
unit :sludge, 474, 0, :west
unit :archer, 476, 0, :west
unit :sludge, 477, 0, :west
unit :archer, 480, 0, :west
unit :wizard, 483, 0, :west
unit :wizard, 486, 0, :west
unit :captive, 487, 0, :west
unit :thick_sludge, 495, 0, :west
unit :wizard, 499, 0, :west
unit :captive, 502, 0, :west
unit :thick_sludge, 505, 0, :west
unit :captive, 509, 0, :west
unit :thick_sludge, 514, 0, :west
unit :sludge, 517, 0, :west
unit :archer, 522, 0, :west
unit :sludge, 528, 0, :west
unit :sludge, 533, 0, :west
unit :captive, 535, 0, :west
unit :thick_sludge, 539, 0, :west
unit :thick_sludge, 541, 0, :west
unit :thick_sludge, 543, 0, :west
unit :thick_sludge, 544, 0, :west
unit :captive, 546, 0, :west
unit :wizard, 549, 0, :west
unit :thick_sludge, 555, 0, :west
unit :captive, 556, 0, :west
unit :wizard, 559, 0, :west
unit :captive, 564, 0, :west
unit :archer, 565, 0, :west
unit :archer, 575, 0, :west
unit :archer, 576, 0, :west
unit :sludge, 578, 0, :west
unit :thick_sludge, 585, 0, :west
unit :thick_sludge, 587, 0, :west
unit :sludge, 598, 0, :west
unit :thick_sludge, 603, 0, :west
unit :thick_sludge, 610, 0, :west
unit :thick_sludge, 612, 0, :west
unit :archer, 621, 0, :west
unit :thick_sludge, 623, 0, :west
unit :archer, 629, 0, :west
unit :archer, 630, 0, :west
unit :thick_sludge, 631, 0, :west
unit :sludge, 632, 0, :west
unit :captive, 634, 0, :west
unit :sludge, 635, 0, :west
unit :sludge, 636, 0, :west
unit :archer, 637, 0, :west
unit :sludge, 647, 0, :west
unit :thick_sludge, 656, 0, :west
unit :sludge, 665, 0, :west
unit :archer, 667, 0, :west
unit :wizard, 668, 0, :west
unit :wizard, 670, 0, :west
unit :thick_sludge, 672, 0, :west
unit :captive, 674, 0, :west
unit :sludge, 679, 0, :west
