#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    as  S w  C S sC s       a  a    S C s  w S  S S  SS  a     S        s     a        s S  s     S   sCa   S sC S C                         s        s    C  aCSw w     C s        SS     w  s        Sa    S s  s CCsC       a sa  s    CSa   Ca sa CsC  s  s S   sw       C   C a     a  a      CSa     C    Sw      a a       Cas  a    S      a   w    a   w s C      s      S             w    w  S  C    a  S     aS         Cs        S    w     sCa    SS           S  s     @  C     a   w   a s C    C     S       S sa w  S       s   S       S       w   a   a  aS s Sa     s    aw S   a s    C CC   S  s                 w      s      aC        a     a a  CsC   S       s   w      a            SC a C    a              s    w  s>s      CaaC S w  ss  S             w    S    C  waC s  w         s      C  a w  S             s      a  w|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 829
ace_score 4145
size 829, 1
stairs 723, 0

warrior 470, 0, :east

unit :archer, 4, 0, :east
unit :sludge, 5, 0, :east
unit :thick_sludge, 8, 0, :east
unit :wizard, 10, 0, :east
unit :captive, 13, 0, :east
unit :thick_sludge, 15, 0, :east
unit :sludge, 17, 0, :east
unit :captive, 18, 0, :east
unit :sludge, 20, 0, :east
unit :archer, 28, 0, :east
unit :archer, 31, 0, :east
unit :thick_sludge, 36, 0, :east
unit :captive, 38, 0, :east
unit :sludge, 40, 0, :east
unit :wizard, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :thick_sludge, 48, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 53, 0, :east
unit :thick_sludge, 54, 0, :east
unit :archer, 57, 0, :east
unit :thick_sludge, 63, 0, :east
unit :sludge, 72, 0, :east
unit :archer, 78, 0, :east
unit :sludge, 87, 0, :east
unit :thick_sludge, 89, 0, :east
unit :sludge, 92, 0, :east
unit :thick_sludge, 98, 0, :east
unit :sludge, 102, 0, :east
unit :captive, 103, 0, :east
unit :archer, 104, 0, :east
unit :thick_sludge, 108, 0, :east
unit :sludge, 110, 0, :east
unit :captive, 111, 0, :east
unit :thick_sludge, 113, 0, :east
unit :captive, 115, 0, :east
unit :sludge, 141, 0, :east
unit :sludge, 150, 0, :east
unit :captive, 155, 0, :east
unit :archer, 158, 0, :east
unit :captive, 159, 0, :east
unit :thick_sludge, 160, 0, :east
unit :wizard, 161, 0, :east
unit :wizard, 163, 0, :east
unit :captive, 169, 0, :east
unit :sludge, 171, 0, :east
unit :thick_sludge, 180, 0, :east
unit :thick_sludge, 181, 0, :east
unit :wizard, 187, 0, :east
unit :sludge, 190, 0, :east
unit :thick_sludge, 199, 0, :east
unit :archer, 200, 0, :east
unit :thick_sludge, 205, 0, :east
unit :sludge, 207, 0, :east
unit :sludge, 210, 0, :east
unit :captive, 212, 0, :east
unit :captive, 213, 0, :east
unit :sludge, 214, 0, :east
unit :captive, 215, 0, :east
unit :archer, 223, 0, :east
unit :sludge, 225, 0, :east
unit :archer, 226, 0, :east
unit :sludge, 229, 0, :east
unit :captive, 234, 0, :east
unit :thick_sludge, 235, 0, :east
unit :archer, 236, 0, :east
unit :captive, 240, 0, :east
unit :archer, 241, 0, :east
unit :sludge, 243, 0, :east
unit :archer, 244, 0, :east
unit :captive, 246, 0, :east
unit :sludge, 247, 0, :east
unit :captive, 248, 0, :east
unit :sludge, 251, 0, :east
unit :sludge, 254, 0, :east
unit :thick_sludge, 256, 0, :east
unit :sludge, 260, 0, :east
unit :wizard, 261, 0, :east
unit :captive, 269, 0, :east
unit :captive, 273, 0, :east
unit :archer, 275, 0, :east
unit :archer, 281, 0, :east
unit :archer, 284, 0, :east
unit :captive, 291, 0, :east
unit :thick_sludge, 292, 0, :east
unit :archer, 293, 0, :east
unit :captive, 299, 0, :east
unit :thick_sludge, 304, 0, :east
unit :wizard, 305, 0, :east
unit :archer, 312, 0, :east
unit :archer, 314, 0, :east
unit :captive, 322, 0, :east
unit :archer, 323, 0, :east
unit :sludge, 324, 0, :east
unit :archer, 327, 0, :east
unit :thick_sludge, 332, 0, :east
unit :archer, 339, 0, :east
unit :wizard, 343, 0, :east
unit :archer, 348, 0, :east
unit :wizard, 352, 0, :east
unit :sludge, 354, 0, :east
unit :captive, 356, 0, :east
unit :sludge, 363, 0, :east
unit :thick_sludge, 370, 0, :east
unit :wizard, 384, 0, :east
unit :wizard, 389, 0, :east
unit :thick_sludge, 392, 0, :east
unit :captive, 395, 0, :east
unit :archer, 400, 0, :east
unit :thick_sludge, 403, 0, :east
unit :archer, 409, 0, :east
unit :thick_sludge, 410, 0, :east
unit :captive, 420, 0, :east
unit :sludge, 421, 0, :east
unit :thick_sludge, 430, 0, :east
unit :wizard, 435, 0, :east
unit :sludge, 441, 0, :east
unit :captive, 442, 0, :east
unit :archer, 443, 0, :east
unit :thick_sludge, 448, 0, :east
unit :thick_sludge, 449, 0, :east
unit :thick_sludge, 461, 0, :east
unit :sludge, 464, 0, :east
unit :captive, 473, 0, :west
unit :archer, 479, 0, :west
unit :wizard, 483, 0, :west
unit :archer, 487, 0, :west
unit :sludge, 489, 0, :west
unit :captive, 491, 0, :west
unit :captive, 496, 0, :west
unit :thick_sludge, 502, 0, :west
unit :thick_sludge, 510, 0, :west
unit :sludge, 512, 0, :west
unit :archer, 513, 0, :west
unit :wizard, 515, 0, :west
unit :thick_sludge, 518, 0, :west
unit :sludge, 526, 0, :west
unit :thick_sludge, 530, 0, :west
unit :thick_sludge, 538, 0, :west
unit :wizard, 546, 0, :west
unit :archer, 550, 0, :west
unit :archer, 554, 0, :west
unit :archer, 557, 0, :west
unit :thick_sludge, 558, 0, :west
unit :sludge, 560, 0, :west
unit :thick_sludge, 562, 0, :west
unit :archer, 563, 0, :west
unit :sludge, 569, 0, :west
unit :archer, 574, 0, :west
unit :wizard, 575, 0, :west
unit :thick_sludge, 577, 0, :west
unit :archer, 581, 0, :west
unit :sludge, 583, 0, :west
unit :captive, 588, 0, :west
unit :captive, 590, 0, :west
unit :captive, 591, 0, :west
unit :thick_sludge, 595, 0, :west
unit :sludge, 598, 0, :west
unit :wizard, 616, 0, :west
unit :sludge, 623, 0, :west
unit :archer, 630, 0, :west
unit :captive, 631, 0, :west
unit :archer, 640, 0, :west
unit :archer, 646, 0, :west
unit :archer, 648, 0, :west
unit :captive, 651, 0, :west
unit :sludge, 652, 0, :west
unit :captive, 653, 0, :west
unit :thick_sludge, 657, 0, :west
unit :sludge, 665, 0, :west
unit :wizard, 669, 0, :west
unit :archer, 676, 0, :west
unit :thick_sludge, 689, 0, :west
unit :captive, 690, 0, :west
unit :archer, 692, 0, :west
unit :captive, 694, 0, :west
unit :archer, 699, 0, :west
unit :sludge, 714, 0, :west
unit :wizard, 719, 0, :west
unit :sludge, 722, 0, :west
unit :sludge, 724, 0, :west
unit :captive, 731, 0, :west
unit :archer, 732, 0, :west
unit :archer, 733, 0, :west
unit :captive, 734, 0, :west
unit :thick_sludge, 736, 0, :west
unit :wizard, 738, 0, :west
unit :sludge, 741, 0, :west
unit :sludge, 742, 0, :west
unit :thick_sludge, 745, 0, :west
unit :wizard, 759, 0, :west
unit :thick_sludge, 764, 0, :west
unit :captive, 769, 0, :west
unit :wizard, 772, 0, :west
unit :archer, 773, 0, :west
unit :captive, 774, 0, :west
unit :sludge, 776, 0, :west
unit :wizard, 779, 0, :west
unit :sludge, 789, 0, :west
unit :captive, 796, 0, :west
unit :archer, 799, 0, :west
unit :wizard, 801, 0, :west
unit :thick_sludge, 804, 0, :west
unit :sludge, 818, 0, :west
unit :archer, 825, 0, :west
unit :wizard, 828, 0, :west
