#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | s     aa   C    CS  s      w  S   w      S        C    Ca       w          a    S a    Sa S      S      w     C       s S   w s s         s    S s  w  C S       C      sSs    S   S   SS     as      w s  w Ca           sS w w  C w               C      as  w     s       a       Cw         sC   C     S   Ca   w w  s a  C   w  s                S              @       Cw a         S     w  S      wC w  w   SS  C  a  aS    a    s S     S      C  s        Ss w      s   S  a aw C            wa        w S            C        w C     aC  SCC     S  S         Ssw   s    C    s S C   S     C   wS     Ca  SC    aS  sSa     sC w  w aCC      C   a  C  w  a      CS    a  S  s    w  S     Ss   Ca  a C  C  S aS S     S SSs     w        C    s          sS       w  S  s  C    C              S      a a    C        w s  w     a s     C >      S   sa   w s S  S S a C   S   C     ssw  w          Ca  w       Cs S     s C w  C   w   SS s    w w      sa  s   C   SS|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 952
ace_score 4760
size 952, 1
stairs 826, 0

warrior 358, 0, :east

unit :sludge, 1, 0, :east
unit :archer, 7, 0, :east
unit :archer, 8, 0, :east
unit :captive, 12, 0, :east
unit :captive, 17, 0, :east
unit :thick_sludge, 18, 0, :east
unit :sludge, 21, 0, :east
unit :wizard, 28, 0, :east
unit :thick_sludge, 31, 0, :east
unit :wizard, 35, 0, :east
unit :thick_sludge, 42, 0, :east
unit :captive, 51, 0, :east
unit :captive, 56, 0, :east
unit :archer, 57, 0, :east
unit :wizard, 65, 0, :east
unit :archer, 76, 0, :east
unit :thick_sludge, 81, 0, :east
unit :archer, 83, 0, :east
unit :thick_sludge, 88, 0, :east
unit :archer, 89, 0, :east
unit :thick_sludge, 91, 0, :east
unit :thick_sludge, 98, 0, :east
unit :wizard, 105, 0, :east
unit :captive, 111, 0, :east
unit :sludge, 119, 0, :east
unit :thick_sludge, 121, 0, :east
unit :wizard, 125, 0, :east
unit :sludge, 127, 0, :east
unit :sludge, 129, 0, :east
unit :sludge, 139, 0, :east
unit :thick_sludge, 144, 0, :east
unit :sludge, 146, 0, :east
unit :wizard, 149, 0, :east
unit :captive, 152, 0, :east
unit :thick_sludge, 154, 0, :east
unit :captive, 162, 0, :east
unit :sludge, 169, 0, :east
unit :thick_sludge, 170, 0, :east
unit :sludge, 171, 0, :east
unit :thick_sludge, 176, 0, :east
unit :thick_sludge, 180, 0, :east
unit :thick_sludge, 184, 0, :east
unit :thick_sludge, 185, 0, :east
unit :archer, 191, 0, :east
unit :sludge, 192, 0, :east
unit :wizard, 199, 0, :east
unit :sludge, 201, 0, :east
unit :wizard, 204, 0, :east
unit :captive, 206, 0, :east
unit :archer, 207, 0, :east
unit :sludge, 219, 0, :east
unit :thick_sludge, 220, 0, :east
unit :wizard, 222, 0, :east
unit :wizard, 224, 0, :east
unit :captive, 227, 0, :east
unit :wizard, 229, 0, :east
unit :captive, 245, 0, :east
unit :archer, 252, 0, :east
unit :sludge, 253, 0, :east
unit :wizard, 256, 0, :east
unit :sludge, 262, 0, :east
unit :archer, 270, 0, :east
unit :captive, 278, 0, :east
unit :wizard, 279, 0, :east
unit :sludge, 289, 0, :east
unit :captive, 290, 0, :east
unit :captive, 294, 0, :east
unit :thick_sludge, 300, 0, :east
unit :captive, 304, 0, :east
unit :archer, 305, 0, :east
unit :wizard, 309, 0, :east
unit :wizard, 311, 0, :east
unit :sludge, 314, 0, :east
unit :archer, 316, 0, :east
unit :captive, 319, 0, :east
unit :wizard, 323, 0, :east
unit :sludge, 326, 0, :east
unit :thick_sludge, 343, 0, :east
unit :captive, 366, 0, :west
unit :wizard, 367, 0, :west
unit :archer, 369, 0, :west
unit :thick_sludge, 379, 0, :west
unit :wizard, 385, 0, :west
unit :thick_sludge, 388, 0, :west
unit :wizard, 395, 0, :west
unit :captive, 396, 0, :west
unit :wizard, 398, 0, :west
unit :wizard, 401, 0, :west
unit :thick_sludge, 405, 0, :west
unit :thick_sludge, 406, 0, :west
unit :captive, 409, 0, :west
unit :archer, 412, 0, :west
unit :archer, 415, 0, :west
unit :thick_sludge, 416, 0, :west
unit :archer, 421, 0, :west
unit :sludge, 426, 0, :west
unit :thick_sludge, 428, 0, :west
unit :thick_sludge, 434, 0, :west
unit :captive, 441, 0, :west
unit :sludge, 444, 0, :west
unit :thick_sludge, 453, 0, :west
unit :sludge, 454, 0, :west
unit :wizard, 456, 0, :west
unit :sludge, 463, 0, :west
unit :thick_sludge, 467, 0, :west
unit :archer, 470, 0, :west
unit :archer, 472, 0, :west
unit :wizard, 473, 0, :west
unit :captive, 475, 0, :west
unit :wizard, 488, 0, :west
unit :archer, 489, 0, :west
unit :wizard, 498, 0, :west
unit :thick_sludge, 500, 0, :west
unit :captive, 513, 0, :west
unit :wizard, 522, 0, :west
unit :captive, 524, 0, :west
unit :archer, 530, 0, :west
unit :captive, 531, 0, :west
unit :thick_sludge, 534, 0, :west
unit :captive, 535, 0, :west
unit :captive, 536, 0, :west
unit :thick_sludge, 542, 0, :west
unit :thick_sludge, 545, 0, :west
unit :thick_sludge, 555, 0, :west
unit :sludge, 556, 0, :west
unit :wizard, 557, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 566, 0, :west
unit :sludge, 571, 0, :west
unit :thick_sludge, 573, 0, :west
unit :captive, 575, 0, :west
unit :thick_sludge, 579, 0, :west
unit :captive, 585, 0, :west
unit :wizard, 589, 0, :west
unit :thick_sludge, 590, 0, :west
unit :captive, 596, 0, :west
unit :archer, 597, 0, :west
unit :thick_sludge, 600, 0, :west
unit :captive, 601, 0, :west
unit :archer, 606, 0, :west
unit :thick_sludge, 607, 0, :west
unit :sludge, 610, 0, :west
unit :thick_sludge, 611, 0, :west
unit :archer, 612, 0, :west
unit :sludge, 618, 0, :west
unit :captive, 619, 0, :west
unit :wizard, 621, 0, :west
unit :wizard, 624, 0, :west
unit :archer, 626, 0, :west
unit :captive, 627, 0, :west
unit :captive, 628, 0, :west
unit :captive, 635, 0, :west
unit :archer, 639, 0, :west
unit :captive, 642, 0, :west
unit :wizard, 645, 0, :west
unit :archer, 648, 0, :west
unit :captive, 655, 0, :west
unit :thick_sludge, 656, 0, :west
unit :archer, 661, 0, :west
unit :thick_sludge, 664, 0, :west
unit :sludge, 667, 0, :west
unit :wizard, 672, 0, :west
unit :thick_sludge, 675, 0, :west
unit :thick_sludge, 681, 0, :west
unit :sludge, 682, 0, :west
unit :captive, 686, 0, :west
unit :archer, 687, 0, :west
unit :archer, 690, 0, :west
unit :captive, 692, 0, :west
unit :captive, 695, 0, :west
unit :thick_sludge, 698, 0, :west
unit :archer, 700, 0, :west
unit :thick_sludge, 701, 0, :west
unit :thick_sludge, 703, 0, :west
unit :thick_sludge, 709, 0, :west
unit :thick_sludge, 711, 0, :west
unit :thick_sludge, 712, 0, :west
unit :sludge, 713, 0, :west
unit :wizard, 719, 0, :west
unit :captive, 728, 0, :west
unit :sludge, 733, 0, :west
unit :sludge, 744, 0, :west
unit :thick_sludge, 745, 0, :west
unit :wizard, 753, 0, :west
unit :thick_sludge, 756, 0, :west
unit :sludge, 759, 0, :west
unit :captive, 762, 0, :west
unit :captive, 767, 0, :west
unit :thick_sludge, 782, 0, :west
unit :archer, 789, 0, :west
unit :archer, 791, 0, :west
unit :captive, 796, 0, :west
unit :wizard, 805, 0, :west
unit :sludge, 807, 0, :west
unit :wizard, 810, 0, :west
unit :archer, 816, 0, :west
unit :sludge, 818, 0, :west
unit :captive, 824, 0, :west
unit :thick_sludge, 833, 0, :west
unit :sludge, 837, 0, :west
unit :archer, 838, 0, :west
unit :wizard, 842, 0, :west
unit :sludge, 844, 0, :west
unit :thick_sludge, 846, 0, :west
unit :thick_sludge, 849, 0, :west
unit :thick_sludge, 851, 0, :west
unit :archer, 853, 0, :west
unit :captive, 855, 0, :west
unit :thick_sludge, 859, 0, :west
unit :captive, 863, 0, :west
unit :sludge, 869, 0, :west
unit :sludge, 870, 0, :west
unit :wizard, 871, 0, :west
unit :wizard, 874, 0, :west
unit :captive, 885, 0, :west
unit :archer, 886, 0, :west
unit :wizard, 889, 0, :west
unit :captive, 897, 0, :west
unit :sludge, 898, 0, :west
unit :thick_sludge, 900, 0, :west
unit :sludge, 906, 0, :west
unit :captive, 908, 0, :west
unit :wizard, 910, 0, :west
unit :captive, 913, 0, :west
unit :wizard, 917, 0, :west
unit :thick_sludge, 921, 0, :west
unit :thick_sludge, 922, 0, :west
unit :sludge, 924, 0, :west
unit :wizard, 929, 0, :west
unit :wizard, 931, 0, :west
unit :sludge, 938, 0, :west
unit :archer, 939, 0, :west
unit :sludge, 942, 0, :west
unit :captive, 946, 0, :west
unit :thick_sludge, 950, 0, :west
unit :thick_sludge, 951, 0, :west
