#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S    sw  w  C a      CaS     w      C    s    a s   wC       w  sa awC  C           wS   C     w    S   S   s   S          S     S  Cs       s a   C    w   C     S   s    CCCS w   sw        w w  C wS saC Ca   CC   SS  S    S               a  s CS       w    s     C           w           a   a w  s  sC S      sS   sC a Ss  C a  CS    s    w     a    aa            C  sS   s        a   s  Ssa C s S s     C   S     C   CS   sC   s  S  ss  sw     @      aSSs   S      S    S    C SS        C   S      a  aC w       S   a     C    C        C    s            > S w    C   w  C  w   w      s  w w     C as   Sw      a w   a w  s a   a                 CC       C a     C    w   s   s   aS sC  s  S         w       S    w    s  sa           S    s       w    S          aw w     S   CS     w      s        |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 800
ace_score 4000
size 800, 1
stairs 556, 0

warrior 446, 0, :east

unit :thick_sludge, 0, 0, :east
unit :sludge, 5, 0, :east
unit :wizard, 6, 0, :east
unit :wizard, 9, 0, :east
unit :captive, 12, 0, :east
unit :archer, 14, 0, :east
unit :captive, 21, 0, :east
unit :archer, 22, 0, :east
unit :thick_sludge, 23, 0, :east
unit :wizard, 29, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 41, 0, :east
unit :archer, 46, 0, :east
unit :sludge, 48, 0, :east
unit :wizard, 52, 0, :east
unit :captive, 53, 0, :east
unit :wizard, 61, 0, :east
unit :sludge, 64, 0, :east
unit :archer, 65, 0, :east
unit :archer, 67, 0, :east
unit :wizard, 68, 0, :east
unit :captive, 69, 0, :east
unit :captive, 72, 0, :east
unit :wizard, 84, 0, :east
unit :thick_sludge, 85, 0, :east
unit :captive, 89, 0, :east
unit :wizard, 95, 0, :east
unit :thick_sludge, 100, 0, :east
unit :thick_sludge, 104, 0, :east
unit :sludge, 108, 0, :east
unit :thick_sludge, 112, 0, :east
unit :thick_sludge, 123, 0, :east
unit :thick_sludge, 129, 0, :east
unit :captive, 132, 0, :east
unit :sludge, 133, 0, :east
unit :sludge, 141, 0, :east
unit :archer, 143, 0, :east
unit :captive, 147, 0, :east
unit :wizard, 152, 0, :east
unit :captive, 156, 0, :east
unit :thick_sludge, 162, 0, :east
unit :sludge, 166, 0, :east
unit :captive, 171, 0, :east
unit :captive, 172, 0, :east
unit :captive, 173, 0, :east
unit :thick_sludge, 174, 0, :east
unit :wizard, 176, 0, :east
unit :sludge, 180, 0, :east
unit :wizard, 181, 0, :east
unit :wizard, 190, 0, :east
unit :wizard, 192, 0, :east
unit :captive, 195, 0, :east
unit :wizard, 197, 0, :east
unit :thick_sludge, 198, 0, :east
unit :sludge, 200, 0, :east
unit :archer, 201, 0, :east
unit :captive, 202, 0, :east
unit :captive, 204, 0, :east
unit :archer, 205, 0, :east
unit :captive, 209, 0, :east
unit :captive, 210, 0, :east
unit :thick_sludge, 214, 0, :east
unit :thick_sludge, 215, 0, :east
unit :thick_sludge, 218, 0, :east
unit :thick_sludge, 223, 0, :east
unit :archer, 239, 0, :east
unit :sludge, 242, 0, :east
unit :captive, 244, 0, :east
unit :thick_sludge, 245, 0, :east
unit :wizard, 253, 0, :east
unit :sludge, 258, 0, :east
unit :captive, 264, 0, :east
unit :wizard, 276, 0, :east
unit :archer, 288, 0, :east
unit :archer, 292, 0, :east
unit :wizard, 294, 0, :east
unit :sludge, 297, 0, :east
unit :sludge, 300, 0, :east
unit :captive, 301, 0, :east
unit :thick_sludge, 303, 0, :east
unit :sludge, 310, 0, :east
unit :thick_sludge, 311, 0, :east
unit :sludge, 315, 0, :east
unit :captive, 316, 0, :east
unit :archer, 318, 0, :east
unit :thick_sludge, 320, 0, :east
unit :sludge, 321, 0, :east
unit :captive, 324, 0, :east
unit :archer, 326, 0, :east
unit :captive, 329, 0, :east
unit :thick_sludge, 330, 0, :east
unit :sludge, 335, 0, :east
unit :wizard, 340, 0, :east
unit :archer, 346, 0, :east
unit :archer, 351, 0, :east
unit :archer, 352, 0, :east
unit :captive, 365, 0, :east
unit :sludge, 368, 0, :east
unit :thick_sludge, 369, 0, :east
unit :sludge, 373, 0, :east
unit :archer, 382, 0, :east
unit :sludge, 386, 0, :east
unit :thick_sludge, 389, 0, :east
unit :sludge, 390, 0, :east
unit :archer, 391, 0, :east
unit :captive, 393, 0, :east
unit :sludge, 395, 0, :east
unit :thick_sludge, 397, 0, :east
unit :sludge, 399, 0, :east
unit :captive, 405, 0, :east
unit :thick_sludge, 409, 0, :east
unit :captive, 415, 0, :east
unit :captive, 419, 0, :east
unit :thick_sludge, 420, 0, :east
unit :sludge, 424, 0, :east
unit :captive, 425, 0, :east
unit :sludge, 429, 0, :east
unit :thick_sludge, 432, 0, :east
unit :sludge, 435, 0, :east
unit :sludge, 436, 0, :east
unit :sludge, 439, 0, :east
unit :wizard, 440, 0, :east
unit :archer, 453, 0, :west
unit :thick_sludge, 454, 0, :west
unit :thick_sludge, 455, 0, :west
unit :sludge, 456, 0, :west
unit :thick_sludge, 460, 0, :west
unit :thick_sludge, 467, 0, :west
unit :thick_sludge, 472, 0, :west
unit :captive, 477, 0, :west
unit :thick_sludge, 479, 0, :west
unit :thick_sludge, 480, 0, :west
unit :captive, 489, 0, :west
unit :thick_sludge, 493, 0, :west
unit :archer, 500, 0, :west
unit :archer, 503, 0, :west
unit :captive, 504, 0, :west
unit :wizard, 506, 0, :west
unit :thick_sludge, 514, 0, :west
unit :archer, 518, 0, :west
unit :captive, 524, 0, :west
unit :captive, 529, 0, :west
unit :captive, 538, 0, :west
unit :sludge, 543, 0, :west
unit :thick_sludge, 558, 0, :west
unit :wizard, 560, 0, :west
unit :captive, 565, 0, :west
unit :wizard, 569, 0, :west
unit :captive, 572, 0, :west
unit :wizard, 575, 0, :west
unit :wizard, 579, 0, :west
unit :sludge, 586, 0, :west
unit :wizard, 589, 0, :west
unit :wizard, 591, 0, :west
unit :captive, 597, 0, :west
unit :archer, 599, 0, :west
unit :sludge, 600, 0, :west
unit :thick_sludge, 604, 0, :west
unit :wizard, 605, 0, :west
unit :archer, 612, 0, :west
unit :wizard, 614, 0, :west
unit :archer, 618, 0, :west
unit :wizard, 620, 0, :west
unit :sludge, 623, 0, :west
unit :archer, 625, 0, :west
unit :archer, 629, 0, :west
unit :captive, 647, 0, :west
unit :captive, 648, 0, :west
unit :captive, 656, 0, :west
unit :archer, 658, 0, :west
unit :captive, 664, 0, :west
unit :wizard, 669, 0, :west
unit :sludge, 673, 0, :west
unit :sludge, 677, 0, :west
unit :archer, 681, 0, :west
unit :thick_sludge, 682, 0, :west
unit :sludge, 684, 0, :west
unit :captive, 685, 0, :west
unit :sludge, 688, 0, :west
unit :thick_sludge, 691, 0, :west
unit :wizard, 701, 0, :west
unit :thick_sludge, 709, 0, :west
unit :wizard, 714, 0, :west
unit :sludge, 719, 0, :west
unit :sludge, 722, 0, :west
unit :archer, 723, 0, :west
unit :thick_sludge, 735, 0, :west
unit :sludge, 740, 0, :west
unit :wizard, 748, 0, :west
unit :thick_sludge, 753, 0, :west
unit :archer, 764, 0, :west
unit :wizard, 765, 0, :west
unit :wizard, 767, 0, :west
unit :thick_sludge, 773, 0, :west
unit :captive, 777, 0, :west
unit :thick_sludge, 778, 0, :west
unit :wizard, 784, 0, :west
unit :sludge, 791, 0, :west
