#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C        w        S    S   C CC      s    C   S   C w  sCC   a   S   C   a   a   s>  a  as C   a     S      Sw w       s s          s sC   @      a            a   s  w      C  C a     a   sa       s            SS a S      s    S   C     CS      w w      s s  w         a sSSss      CsC  s  w    wS        S     a    S   C     s     w w       w s a     a     S      S      C        s  C    w s CS S      aS    a C  C   s  w Sw        SS            C w S     s  a         w       Ss         aS  w a    a  SC aa Ca     C   w s aa  a s    S    C CS w       w    CC S   w    C w s aa    S      S   S       C            s        s         w S      S    w C   S     C   S         Sw     ss   s     a     w    w Sw  Ss w C a         a  s  w  C       C     Sa  C  S C  a      S   w     C    C      w C     w  S   C C s C     wS    a CC S C           C sCS as     a  a   Ss      a    w  s  w w a   s w  C  w C      CCs      w           w           Cs|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 940
ace_score 4700
size 940, 1
stairs 82, 0

warrior 139, 0, :east

unit :captive, 0, 0, :east
unit :wizard, 9, 0, :east
unit :thick_sludge, 18, 0, :east
unit :thick_sludge, 23, 0, :east
unit :captive, 27, 0, :east
unit :captive, 29, 0, :east
unit :captive, 30, 0, :east
unit :sludge, 37, 0, :east
unit :captive, 42, 0, :east
unit :thick_sludge, 46, 0, :east
unit :captive, 50, 0, :east
unit :wizard, 52, 0, :east
unit :sludge, 55, 0, :east
unit :captive, 56, 0, :east
unit :captive, 57, 0, :east
unit :archer, 61, 0, :east
unit :thick_sludge, 65, 0, :east
unit :captive, 69, 0, :east
unit :archer, 73, 0, :east
unit :archer, 77, 0, :east
unit :sludge, 81, 0, :east
unit :archer, 85, 0, :east
unit :archer, 88, 0, :east
unit :sludge, 89, 0, :east
unit :captive, 91, 0, :east
unit :archer, 95, 0, :east
unit :thick_sludge, 101, 0, :east
unit :thick_sludge, 108, 0, :east
unit :wizard, 109, 0, :east
unit :wizard, 111, 0, :east
unit :sludge, 119, 0, :east
unit :sludge, 121, 0, :east
unit :sludge, 132, 0, :east
unit :sludge, 134, 0, :east
unit :captive, 135, 0, :east
unit :archer, 146, 0, :west
unit :archer, 159, 0, :west
unit :sludge, 163, 0, :west
unit :wizard, 166, 0, :west
unit :captive, 173, 0, :west
unit :captive, 176, 0, :west
unit :archer, 178, 0, :west
unit :archer, 184, 0, :west
unit :sludge, 188, 0, :west
unit :archer, 189, 0, :west
unit :sludge, 197, 0, :west
unit :thick_sludge, 210, 0, :west
unit :thick_sludge, 211, 0, :west
unit :archer, 213, 0, :west
unit :thick_sludge, 215, 0, :west
unit :sludge, 222, 0, :west
unit :thick_sludge, 227, 0, :west
unit :captive, 231, 0, :west
unit :captive, 237, 0, :west
unit :thick_sludge, 238, 0, :west
unit :wizard, 245, 0, :west
unit :wizard, 247, 0, :west
unit :sludge, 254, 0, :west
unit :sludge, 256, 0, :west
unit :wizard, 259, 0, :west
unit :archer, 269, 0, :west
unit :sludge, 271, 0, :west
unit :thick_sludge, 272, 0, :west
unit :thick_sludge, 273, 0, :west
unit :sludge, 274, 0, :west
unit :sludge, 275, 0, :west
unit :captive, 282, 0, :west
unit :sludge, 283, 0, :west
unit :captive, 284, 0, :west
unit :sludge, 287, 0, :west
unit :wizard, 290, 0, :west
unit :wizard, 295, 0, :west
unit :thick_sludge, 296, 0, :west
unit :thick_sludge, 305, 0, :west
unit :archer, 311, 0, :west
unit :thick_sludge, 316, 0, :west
unit :captive, 320, 0, :west
unit :sludge, 326, 0, :west
unit :wizard, 332, 0, :west
unit :wizard, 334, 0, :west
unit :wizard, 342, 0, :west
unit :sludge, 344, 0, :west
unit :archer, 346, 0, :west
unit :archer, 352, 0, :west
unit :thick_sludge, 358, 0, :west
unit :thick_sludge, 365, 0, :west
unit :captive, 372, 0, :west
unit :sludge, 381, 0, :west
unit :captive, 384, 0, :west
unit :wizard, 389, 0, :west
unit :sludge, 391, 0, :west
unit :captive, 393, 0, :west
unit :thick_sludge, 394, 0, :west
unit :thick_sludge, 396, 0, :west
unit :archer, 403, 0, :west
unit :thick_sludge, 404, 0, :west
unit :archer, 409, 0, :west
unit :captive, 411, 0, :west
unit :captive, 414, 0, :west
unit :sludge, 418, 0, :west
unit :wizard, 421, 0, :west
unit :thick_sludge, 423, 0, :west
unit :wizard, 424, 0, :west
unit :thick_sludge, 433, 0, :west
unit :thick_sludge, 434, 0, :west
unit :captive, 447, 0, :west
unit :wizard, 449, 0, :west
unit :thick_sludge, 451, 0, :west
unit :sludge, 457, 0, :west
unit :archer, 460, 0, :west
unit :wizard, 470, 0, :west
unit :thick_sludge, 478, 0, :west
unit :sludge, 479, 0, :west
unit :archer, 489, 0, :west
unit :thick_sludge, 490, 0, :west
unit :wizard, 493, 0, :west
unit :archer, 495, 0, :west
unit :archer, 500, 0, :west
unit :thick_sludge, 503, 0, :west
unit :captive, 504, 0, :west
unit :archer, 506, 0, :west
unit :archer, 507, 0, :west
unit :captive, 509, 0, :west
unit :archer, 510, 0, :west
unit :captive, 516, 0, :west
unit :wizard, 520, 0, :west
unit :sludge, 522, 0, :west
unit :archer, 524, 0, :west
unit :archer, 525, 0, :west
unit :archer, 528, 0, :west
unit :sludge, 530, 0, :west
unit :thick_sludge, 535, 0, :west
unit :captive, 540, 0, :west
unit :captive, 542, 0, :west
unit :thick_sludge, 543, 0, :west
unit :wizard, 545, 0, :west
unit :wizard, 553, 0, :west
unit :captive, 558, 0, :west
unit :captive, 559, 0, :west
unit :thick_sludge, 561, 0, :west
unit :wizard, 565, 0, :west
unit :captive, 570, 0, :west
unit :wizard, 572, 0, :west
unit :sludge, 574, 0, :west
unit :archer, 576, 0, :west
unit :archer, 577, 0, :west
unit :thick_sludge, 582, 0, :west
unit :thick_sludge, 589, 0, :west
unit :thick_sludge, 593, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 614, 0, :west
unit :sludge, 623, 0, :west
unit :wizard, 633, 0, :west
unit :thick_sludge, 635, 0, :west
unit :thick_sludge, 642, 0, :west
unit :wizard, 647, 0, :west
unit :captive, 649, 0, :west
unit :thick_sludge, 653, 0, :west
unit :captive, 659, 0, :west
unit :thick_sludge, 663, 0, :west
unit :thick_sludge, 673, 0, :west
unit :wizard, 674, 0, :west
unit :sludge, 680, 0, :west
unit :sludge, 681, 0, :west
unit :sludge, 685, 0, :west
unit :archer, 691, 0, :west
unit :wizard, 697, 0, :west
unit :wizard, 702, 0, :west
unit :thick_sludge, 704, 0, :west
unit :wizard, 705, 0, :west
unit :thick_sludge, 708, 0, :west
unit :sludge, 709, 0, :west
unit :wizard, 711, 0, :west
unit :captive, 713, 0, :west
unit :archer, 715, 0, :west
unit :archer, 725, 0, :west
unit :sludge, 728, 0, :west
unit :wizard, 731, 0, :west
unit :captive, 734, 0, :west
unit :captive, 742, 0, :west
unit :thick_sludge, 748, 0, :west
unit :archer, 749, 0, :west
unit :captive, 752, 0, :west
unit :thick_sludge, 755, 0, :west
unit :captive, 757, 0, :west
unit :archer, 760, 0, :west
unit :thick_sludge, 767, 0, :west
unit :wizard, 771, 0, :west
unit :captive, 777, 0, :west
unit :captive, 782, 0, :west
unit :wizard, 789, 0, :west
unit :captive, 791, 0, :west
unit :wizard, 797, 0, :west
unit :thick_sludge, 800, 0, :west
unit :captive, 804, 0, :west
unit :captive, 806, 0, :west
unit :sludge, 808, 0, :west
unit :captive, 810, 0, :west
unit :wizard, 816, 0, :west
unit :thick_sludge, 817, 0, :west
unit :archer, 822, 0, :west
unit :captive, 824, 0, :west
unit :captive, 825, 0, :west
unit :thick_sludge, 827, 0, :west
unit :captive, 829, 0, :west
unit :captive, 841, 0, :west
unit :sludge, 843, 0, :west
unit :captive, 844, 0, :west
unit :thick_sludge, 845, 0, :west
unit :archer, 847, 0, :west
unit :sludge, 848, 0, :west
unit :archer, 854, 0, :west
unit :archer, 857, 0, :west
unit :thick_sludge, 861, 0, :west
unit :sludge, 862, 0, :west
unit :archer, 869, 0, :west
unit :wizard, 874, 0, :west
unit :sludge, 877, 0, :west
unit :wizard, 880, 0, :west
unit :wizard, 882, 0, :west
unit :archer, 884, 0, :west
unit :sludge, 888, 0, :west
unit :wizard, 890, 0, :west
unit :captive, 893, 0, :west
unit :wizard, 896, 0, :west
unit :captive, 898, 0, :west
unit :captive, 905, 0, :west
unit :captive, 906, 0, :west
unit :sludge, 907, 0, :west
unit :wizard, 914, 0, :west
unit :wizard, 926, 0, :west
unit :captive, 938, 0, :west
unit :sludge, 939, 0, :west
