#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w  s  >        w C         S    as S sS              S  aC   a  Cw   s S w      a    s w w   aa  S w    w      s  w   @  C   aw S   a    w      w     s      w      as     Sa                S     s s   a  S     C S        a   C SS     C    Ssws      w S w  S   a  SC          a       S    a  aa     w           a        w s S C  Cw     S  CS    a    S S w     Cs sS w s a a    S  sC  aa      a     C       w a  w       sC  w  s   s   C S S  sC    SS      w  a     S  s  S aS   w    a   w  w   sS  SCw            w      a  w       C w  w        s     s sSs   w   s Cw   C      sS  C S    w    S          wa    S a         C        s w     S    w   C     C   w               w     C  s|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 682
ace_score 3410
size 682, 1
stairs 6, 0

warrior 118, 0, :east

unit :wizard, 0, 0, :east
unit :sludge, 3, 0, :east
unit :wizard, 15, 0, :east
unit :captive, 17, 0, :east
unit :thick_sludge, 27, 0, :east
unit :archer, 32, 0, :east
unit :sludge, 33, 0, :east
unit :thick_sludge, 35, 0, :east
unit :sludge, 37, 0, :east
unit :thick_sludge, 38, 0, :east
unit :thick_sludge, 53, 0, :east
unit :archer, 56, 0, :east
unit :captive, 57, 0, :east
unit :archer, 61, 0, :east
unit :captive, 64, 0, :east
unit :wizard, 65, 0, :east
unit :sludge, 69, 0, :east
unit :thick_sludge, 71, 0, :east
unit :wizard, 73, 0, :east
unit :archer, 80, 0, :east
unit :sludge, 85, 0, :east
unit :wizard, 87, 0, :east
unit :wizard, 89, 0, :east
unit :archer, 93, 0, :east
unit :archer, 94, 0, :east
unit :thick_sludge, 97, 0, :east
unit :wizard, 99, 0, :east
unit :wizard, 104, 0, :east
unit :sludge, 111, 0, :east
unit :wizard, 114, 0, :east
unit :captive, 121, 0, :west
unit :archer, 125, 0, :west
unit :wizard, 126, 0, :west
unit :thick_sludge, 128, 0, :west
unit :archer, 132, 0, :west
unit :wizard, 137, 0, :west
unit :wizard, 144, 0, :west
unit :sludge, 150, 0, :west
unit :wizard, 157, 0, :west
unit :archer, 164, 0, :west
unit :sludge, 165, 0, :west
unit :thick_sludge, 171, 0, :west
unit :archer, 172, 0, :west
unit :thick_sludge, 189, 0, :west
unit :sludge, 195, 0, :west
unit :sludge, 197, 0, :west
unit :archer, 201, 0, :west
unit :thick_sludge, 204, 0, :west
unit :captive, 210, 0, :west
unit :thick_sludge, 212, 0, :west
unit :archer, 221, 0, :west
unit :captive, 225, 0, :west
unit :thick_sludge, 227, 0, :west
unit :thick_sludge, 228, 0, :west
unit :captive, 234, 0, :west
unit :thick_sludge, 239, 0, :west
unit :sludge, 240, 0, :west
unit :wizard, 241, 0, :west
unit :sludge, 242, 0, :west
unit :wizard, 249, 0, :west
unit :thick_sludge, 251, 0, :west
unit :wizard, 253, 0, :west
unit :thick_sludge, 256, 0, :west
unit :archer, 260, 0, :west
unit :thick_sludge, 263, 0, :west
unit :captive, 264, 0, :west
unit :archer, 275, 0, :west
unit :thick_sludge, 283, 0, :west
unit :archer, 288, 0, :west
unit :archer, 291, 0, :west
unit :archer, 292, 0, :west
unit :wizard, 298, 0, :west
unit :archer, 310, 0, :west
unit :wizard, 319, 0, :west
unit :sludge, 321, 0, :west
unit :thick_sludge, 323, 0, :west
unit :captive, 325, 0, :west
unit :captive, 328, 0, :west
unit :wizard, 329, 0, :west
unit :thick_sludge, 335, 0, :west
unit :captive, 338, 0, :west
unit :thick_sludge, 339, 0, :west
unit :archer, 344, 0, :west
unit :thick_sludge, 349, 0, :west
unit :thick_sludge, 351, 0, :west
unit :wizard, 353, 0, :west
unit :captive, 359, 0, :west
unit :sludge, 360, 0, :west
unit :sludge, 362, 0, :west
unit :thick_sludge, 363, 0, :west
unit :wizard, 365, 0, :west
unit :sludge, 367, 0, :west
unit :archer, 369, 0, :west
unit :archer, 371, 0, :west
unit :thick_sludge, 376, 0, :west
unit :sludge, 379, 0, :west
unit :captive, 380, 0, :west
unit :archer, 383, 0, :west
unit :archer, 384, 0, :west
unit :archer, 391, 0, :west
unit :captive, 397, 0, :west
unit :wizard, 405, 0, :west
unit :archer, 407, 0, :west
unit :wizard, 410, 0, :west
unit :sludge, 418, 0, :west
unit :captive, 419, 0, :west
unit :wizard, 422, 0, :west
unit :sludge, 425, 0, :west
unit :sludge, 429, 0, :west
unit :captive, 433, 0, :west
unit :thick_sludge, 435, 0, :west
unit :thick_sludge, 437, 0, :west
unit :sludge, 440, 0, :west
unit :captive, 441, 0, :west
unit :thick_sludge, 446, 0, :west
unit :thick_sludge, 447, 0, :west
unit :wizard, 454, 0, :west
unit :archer, 457, 0, :west
unit :thick_sludge, 463, 0, :west
unit :sludge, 466, 0, :west
unit :thick_sludge, 469, 0, :west
unit :archer, 471, 0, :west
unit :thick_sludge, 472, 0, :west
unit :wizard, 476, 0, :west
unit :archer, 481, 0, :west
unit :wizard, 485, 0, :west
unit :wizard, 488, 0, :west
unit :sludge, 492, 0, :west
unit :thick_sludge, 493, 0, :west
unit :thick_sludge, 496, 0, :west
unit :captive, 497, 0, :west
unit :wizard, 498, 0, :west
unit :wizard, 511, 0, :west
unit :archer, 518, 0, :west
unit :wizard, 521, 0, :west
unit :captive, 529, 0, :west
unit :wizard, 531, 0, :west
unit :wizard, 534, 0, :west
unit :sludge, 543, 0, :west
unit :sludge, 549, 0, :west
unit :sludge, 551, 0, :west
unit :thick_sludge, 552, 0, :west
unit :sludge, 553, 0, :west
unit :wizard, 557, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 563, 0, :west
unit :wizard, 564, 0, :west
unit :captive, 568, 0, :west
unit :sludge, 575, 0, :west
unit :thick_sludge, 576, 0, :west
unit :captive, 579, 0, :west
unit :thick_sludge, 581, 0, :west
unit :wizard, 586, 0, :west
unit :thick_sludge, 591, 0, :west
unit :wizard, 602, 0, :west
unit :archer, 603, 0, :west
unit :thick_sludge, 608, 0, :west
unit :archer, 610, 0, :west
unit :captive, 620, 0, :west
unit :sludge, 629, 0, :west
unit :wizard, 631, 0, :west
unit :thick_sludge, 637, 0, :west
unit :wizard, 642, 0, :west
unit :captive, 646, 0, :west
unit :captive, 652, 0, :west
unit :wizard, 656, 0, :west
unit :wizard, 672, 0, :west
unit :captive, 678, 0, :west
unit :sludge, 681, 0, :west
