#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  S w  w   > s      sC    s aw         C  C  C w    a a    Ss a   w         s       wa  w s w w S a                   a S    w          C s S C         w   C   s      a S   CSa     aw    s C  w a     C   S    CSS      C   ssS   S  S S      a     C w  Cs      w   a   a         C w   C Cw  C Ca   s         C  a   w     aw   C  w   w  w      S         C S     s     s      sa S      s   w s      w     S      a   C   S C   w    sS sC  a  a    S   S asC  a    a  C    w a     s  S      w s     w    s         @    SCS  w   w      w       S S  s    w    a  S     Ss          s |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 574
ace_score 2870
size 574, 1
stairs 11, 0

warrior 507, 0, :east

unit :thick_sludge, 2, 0, :east
unit :wizard, 4, 0, :east
unit :wizard, 7, 0, :east
unit :sludge, 13, 0, :east
unit :sludge, 20, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 26, 0, :east
unit :archer, 28, 0, :east
unit :wizard, 29, 0, :east
unit :captive, 39, 0, :east
unit :captive, 42, 0, :east
unit :captive, 45, 0, :east
unit :wizard, 47, 0, :east
unit :archer, 52, 0, :east
unit :archer, 54, 0, :east
unit :thick_sludge, 59, 0, :east
unit :sludge, 60, 0, :east
unit :archer, 62, 0, :east
unit :wizard, 66, 0, :east
unit :sludge, 76, 0, :east
unit :wizard, 84, 0, :east
unit :archer, 85, 0, :east
unit :wizard, 88, 0, :east
unit :sludge, 90, 0, :east
unit :wizard, 92, 0, :east
unit :wizard, 94, 0, :east
unit :thick_sludge, 96, 0, :east
unit :archer, 98, 0, :east
unit :archer, 118, 0, :east
unit :thick_sludge, 120, 0, :east
unit :wizard, 125, 0, :east
unit :captive, 136, 0, :east
unit :sludge, 138, 0, :east
unit :thick_sludge, 140, 0, :east
unit :captive, 142, 0, :east
unit :wizard, 152, 0, :east
unit :captive, 156, 0, :east
unit :sludge, 160, 0, :east
unit :archer, 167, 0, :east
unit :thick_sludge, 169, 0, :east
unit :captive, 173, 0, :east
unit :thick_sludge, 174, 0, :east
unit :archer, 175, 0, :east
unit :archer, 181, 0, :east
unit :wizard, 182, 0, :east
unit :sludge, 187, 0, :east
unit :captive, 189, 0, :east
unit :wizard, 192, 0, :east
unit :archer, 194, 0, :east
unit :captive, 200, 0, :east
unit :thick_sludge, 204, 0, :east
unit :captive, 209, 0, :east
unit :thick_sludge, 210, 0, :east
unit :thick_sludge, 211, 0, :east
unit :captive, 218, 0, :east
unit :sludge, 222, 0, :east
unit :sludge, 223, 0, :east
unit :thick_sludge, 224, 0, :east
unit :thick_sludge, 228, 0, :east
unit :thick_sludge, 231, 0, :east
unit :thick_sludge, 233, 0, :east
unit :archer, 240, 0, :east
unit :captive, 246, 0, :east
unit :wizard, 248, 0, :east
unit :captive, 251, 0, :east
unit :sludge, 252, 0, :east
unit :wizard, 259, 0, :east
unit :archer, 263, 0, :east
unit :archer, 267, 0, :east
unit :captive, 277, 0, :east
unit :wizard, 279, 0, :east
unit :captive, 283, 0, :east
unit :captive, 285, 0, :east
unit :wizard, 286, 0, :east
unit :captive, 289, 0, :east
unit :captive, 291, 0, :east
unit :archer, 292, 0, :east
unit :sludge, 296, 0, :east
unit :captive, 306, 0, :east
unit :archer, 309, 0, :east
unit :wizard, 313, 0, :east
unit :archer, 319, 0, :east
unit :wizard, 320, 0, :east
unit :captive, 324, 0, :east
unit :wizard, 327, 0, :east
unit :wizard, 331, 0, :east
unit :wizard, 334, 0, :east
unit :thick_sludge, 341, 0, :east
unit :captive, 351, 0, :east
unit :thick_sludge, 353, 0, :east
unit :sludge, 359, 0, :east
unit :sludge, 365, 0, :east
unit :sludge, 372, 0, :east
unit :archer, 373, 0, :east
unit :thick_sludge, 375, 0, :east
unit :sludge, 382, 0, :east
unit :wizard, 386, 0, :east
unit :sludge, 388, 0, :east
unit :wizard, 395, 0, :east
unit :thick_sludge, 401, 0, :east
unit :archer, 408, 0, :east
unit :captive, 412, 0, :east
unit :thick_sludge, 416, 0, :east
unit :captive, 418, 0, :east
unit :wizard, 422, 0, :east
unit :sludge, 427, 0, :east
unit :thick_sludge, 428, 0, :east
unit :sludge, 430, 0, :east
unit :captive, 431, 0, :east
unit :archer, 434, 0, :east
unit :archer, 437, 0, :east
unit :thick_sludge, 442, 0, :east
unit :thick_sludge, 446, 0, :east
unit :archer, 448, 0, :east
unit :sludge, 449, 0, :east
unit :captive, 450, 0, :east
unit :archer, 453, 0, :east
unit :archer, 458, 0, :east
unit :captive, 461, 0, :east
unit :wizard, 466, 0, :east
unit :archer, 468, 0, :east
unit :sludge, 474, 0, :east
unit :thick_sludge, 477, 0, :east
unit :wizard, 484, 0, :east
unit :sludge, 486, 0, :east
unit :wizard, 492, 0, :east
unit :sludge, 497, 0, :east
unit :thick_sludge, 512, 0, :west
unit :captive, 513, 0, :west
unit :thick_sludge, 514, 0, :west
unit :wizard, 517, 0, :west
unit :wizard, 521, 0, :west
unit :wizard, 528, 0, :west
unit :thick_sludge, 536, 0, :west
unit :thick_sludge, 538, 0, :west
unit :sludge, 541, 0, :west
unit :wizard, 546, 0, :west
unit :archer, 551, 0, :west
unit :thick_sludge, 554, 0, :west
unit :thick_sludge, 560, 0, :west
unit :sludge, 561, 0, :west
unit :sludge, 572, 0, :west
