#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a   w   a   a   S      s   S     wC   S s s   w  sw C C  C   a S       a w  s  s S   aa >      w           C  w       w w   S  sa       a         S  s         S SS    a   S   w    S    s S a             a Ca   s     a S     a a    w as w a C  wsS a    w s           Sa    S   Cs      S         s           s    w      s  C C s S  S     a  SsC  w     w  C    C Sa  S a     Ss     Ss     S      C   C   S                   s   a C C      as S  s       a          w   S       s            w   s    a  S  s   w  w  s   a      w      a  SS S    s   w S     w  Cs  s      s s       a   s a   s     C S  C   C  sw        S  a     s  SSC  w S  w a   s    SC         s S  S           S   s C S  aCa s s   C     a     S C   S      s          s CC   s   s   a w  w     s      w C    wa     s   a as   a s     C   C  C s s     s             s  S         w s          a C SC  w     a  s          a  C   s   Ss     C   w  S  SSSSa    S   s S  w   ssC     w  a  C C  s  @   aS              C     s   w             sCSs|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 1004
ace_score 5020
size 1004, 1
stairs 89, 0

warrior 956, 0, :east

unit :archer, 1, 0, :east
unit :wizard, 5, 0, :east
unit :archer, 9, 0, :east
unit :archer, 13, 0, :east
unit :thick_sludge, 17, 0, :east
unit :sludge, 24, 0, :east
unit :thick_sludge, 28, 0, :east
unit :wizard, 34, 0, :east
unit :captive, 35, 0, :east
unit :thick_sludge, 39, 0, :east
unit :sludge, 41, 0, :east
unit :sludge, 43, 0, :east
unit :wizard, 47, 0, :east
unit :sludge, 50, 0, :east
unit :wizard, 51, 0, :east
unit :captive, 53, 0, :east
unit :captive, 55, 0, :east
unit :captive, 58, 0, :east
unit :archer, 62, 0, :east
unit :thick_sludge, 64, 0, :east
unit :archer, 72, 0, :east
unit :wizard, 74, 0, :east
unit :sludge, 77, 0, :east
unit :sludge, 80, 0, :east
unit :thick_sludge, 82, 0, :east
unit :archer, 86, 0, :east
unit :archer, 87, 0, :east
unit :wizard, 96, 0, :east
unit :captive, 108, 0, :east
unit :wizard, 111, 0, :east
unit :wizard, 119, 0, :east
unit :wizard, 121, 0, :east
unit :thick_sludge, 125, 0, :east
unit :sludge, 128, 0, :east
unit :archer, 129, 0, :east
unit :archer, 137, 0, :east
unit :thick_sludge, 147, 0, :east
unit :sludge, 150, 0, :east
unit :thick_sludge, 160, 0, :east
unit :thick_sludge, 162, 0, :east
unit :thick_sludge, 163, 0, :east
unit :archer, 168, 0, :east
unit :thick_sludge, 172, 0, :east
unit :wizard, 176, 0, :east
unit :thick_sludge, 181, 0, :east
unit :sludge, 186, 0, :east
unit :thick_sludge, 188, 0, :east
unit :archer, 190, 0, :east
unit :archer, 204, 0, :east
unit :captive, 206, 0, :east
unit :archer, 207, 0, :east
unit :sludge, 211, 0, :east
unit :archer, 217, 0, :east
unit :thick_sludge, 219, 0, :east
unit :archer, 225, 0, :east
unit :archer, 227, 0, :east
unit :wizard, 232, 0, :east
unit :archer, 234, 0, :east
unit :sludge, 235, 0, :east
unit :wizard, 237, 0, :east
unit :archer, 239, 0, :east
unit :captive, 241, 0, :east
unit :wizard, 244, 0, :east
unit :sludge, 245, 0, :east
unit :thick_sludge, 246, 0, :east
unit :archer, 248, 0, :east
unit :wizard, 253, 0, :east
unit :sludge, 255, 0, :east
unit :thick_sludge, 267, 0, :east
unit :archer, 268, 0, :east
unit :thick_sludge, 273, 0, :east
unit :captive, 277, 0, :east
unit :sludge, 278, 0, :east
unit :thick_sludge, 285, 0, :east
unit :sludge, 295, 0, :east
unit :sludge, 307, 0, :east
unit :wizard, 312, 0, :east
unit :sludge, 319, 0, :east
unit :captive, 322, 0, :east
unit :captive, 324, 0, :east
unit :sludge, 326, 0, :east
unit :thick_sludge, 328, 0, :east
unit :thick_sludge, 331, 0, :east
unit :archer, 337, 0, :east
unit :thick_sludge, 340, 0, :east
unit :sludge, 341, 0, :east
unit :captive, 342, 0, :east
unit :wizard, 345, 0, :east
unit :wizard, 351, 0, :east
unit :captive, 354, 0, :east
unit :captive, 359, 0, :east
unit :thick_sludge, 361, 0, :east
unit :archer, 362, 0, :east
unit :thick_sludge, 365, 0, :east
unit :archer, 367, 0, :east
unit :thick_sludge, 373, 0, :east
unit :sludge, 374, 0, :east
unit :thick_sludge, 380, 0, :east
unit :sludge, 381, 0, :east
unit :thick_sludge, 387, 0, :east
unit :captive, 394, 0, :east
unit :captive, 398, 0, :east
unit :thick_sludge, 402, 0, :east
unit :sludge, 422, 0, :east
unit :archer, 426, 0, :east
unit :captive, 428, 0, :east
unit :captive, 430, 0, :east
unit :archer, 437, 0, :east
unit :sludge, 438, 0, :east
unit :thick_sludge, 440, 0, :east
unit :sludge, 443, 0, :east
unit :archer, 451, 0, :east
unit :wizard, 462, 0, :east
unit :thick_sludge, 466, 0, :east
unit :sludge, 474, 0, :east
unit :wizard, 487, 0, :east
unit :sludge, 491, 0, :east
unit :archer, 496, 0, :east
unit :thick_sludge, 499, 0, :east
unit :sludge, 502, 0, :east
unit :wizard, 506, 0, :east
unit :wizard, 509, 0, :east
unit :sludge, 512, 0, :east
unit :archer, 516, 0, :east
unit :wizard, 523, 0, :east
unit :archer, 530, 0, :east
unit :thick_sludge, 533, 0, :east
unit :thick_sludge, 534, 0, :east
unit :thick_sludge, 536, 0, :east
unit :sludge, 541, 0, :east
unit :wizard, 545, 0, :east
unit :thick_sludge, 547, 0, :east
unit :wizard, 553, 0, :east
unit :captive, 556, 0, :east
unit :sludge, 557, 0, :east
unit :sludge, 560, 0, :east
unit :sludge, 567, 0, :east
unit :sludge, 569, 0, :east
unit :archer, 577, 0, :east
unit :sludge, 581, 0, :east
unit :archer, 583, 0, :east
unit :sludge, 587, 0, :east
unit :captive, 593, 0, :east
unit :thick_sludge, 595, 0, :east
unit :captive, 598, 0, :east
unit :captive, 602, 0, :east
unit :sludge, 605, 0, :east
unit :wizard, 606, 0, :east
unit :thick_sludge, 615, 0, :east
unit :archer, 618, 0, :east
unit :sludge, 624, 0, :east
unit :thick_sludge, 627, 0, :east
unit :thick_sludge, 628, 0, :east
unit :captive, 629, 0, :east
unit :wizard, 632, 0, :east
unit :thick_sludge, 634, 0, :east
unit :wizard, 637, 0, :east
unit :archer, 639, 0, :east
unit :sludge, 643, 0, :east
unit :thick_sludge, 648, 0, :east
unit :captive, 649, 0, :east
unit :sludge, 659, 0, :east
unit :thick_sludge, 661, 0, :east
unit :thick_sludge, 664, 0, :east
unit :thick_sludge, 676, 0, :east
unit :sludge, 680, 0, :east
unit :captive, 682, 0, :east
unit :thick_sludge, 684, 0, :east
unit :archer, 687, 0, :east
unit :captive, 688, 0, :east
unit :archer, 689, 0, :east
unit :sludge, 691, 0, :east
unit :sludge, 693, 0, :east
unit :captive, 697, 0, :east
unit :archer, 703, 0, :east
unit :thick_sludge, 709, 0, :east
unit :captive, 711, 0, :east
unit :thick_sludge, 715, 0, :east
unit :sludge, 722, 0, :east
unit :sludge, 733, 0, :east
unit :captive, 735, 0, :east
unit :captive, 736, 0, :east
unit :sludge, 740, 0, :east
unit :sludge, 744, 0, :east
unit :archer, 748, 0, :east
unit :wizard, 750, 0, :east
unit :wizard, 753, 0, :east
unit :sludge, 759, 0, :east
unit :wizard, 766, 0, :east
unit :captive, 768, 0, :east
unit :wizard, 773, 0, :east
unit :archer, 774, 0, :east
unit :sludge, 780, 0, :east
unit :archer, 784, 0, :east
unit :archer, 786, 0, :east
unit :sludge, 787, 0, :east
unit :archer, 791, 0, :east
unit :sludge, 793, 0, :east
unit :captive, 799, 0, :east
unit :captive, 803, 0, :east
unit :captive, 806, 0, :east
unit :sludge, 808, 0, :east
unit :sludge, 810, 0, :east
unit :sludge, 816, 0, :east
unit :sludge, 830, 0, :east
unit :thick_sludge, 833, 0, :east
unit :wizard, 843, 0, :east
unit :sludge, 845, 0, :east
unit :archer, 856, 0, :east
unit :captive, 858, 0, :east
unit :thick_sludge, 860, 0, :east
unit :captive, 861, 0, :east
unit :wizard, 864, 0, :east
unit :archer, 870, 0, :east
unit :sludge, 873, 0, :east
unit :archer, 884, 0, :east
unit :captive, 887, 0, :east
unit :sludge, 891, 0, :east
unit :thick_sludge, 895, 0, :east
unit :sludge, 896, 0, :east
unit :captive, 902, 0, :east
unit :wizard, 906, 0, :east
unit :thick_sludge, 909, 0, :east
unit :thick_sludge, 912, 0, :east
unit :thick_sludge, 913, 0, :east
unit :thick_sludge, 914, 0, :east
unit :thick_sludge, 915, 0, :east
unit :archer, 916, 0, :east
unit :thick_sludge, 921, 0, :east
unit :sludge, 925, 0, :east
unit :thick_sludge, 927, 0, :east
unit :wizard, 930, 0, :east
unit :sludge, 934, 0, :east
unit :sludge, 935, 0, :east
unit :captive, 936, 0, :east
unit :wizard, 942, 0, :east
unit :archer, 945, 0, :east
unit :captive, 948, 0, :east
unit :captive, 950, 0, :east
unit :sludge, 953, 0, :east
unit :archer, 960, 0, :west
unit :thick_sludge, 961, 0, :west
unit :captive, 976, 0, :west
unit :sludge, 982, 0, :west
unit :wizard, 986, 0, :west
unit :sludge, 1000, 0, :west
unit :captive, 1001, 0, :west
unit :thick_sludge, 1002, 0, :west
unit :sludge, 1003, 0, :west
