#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C  C  s   w   s w  w C sCC  a  SC C     S   S    a C      as  S  s CSw        wCC s     a  sS a  C     C             w s   a    wS     a            C w w    w        SC     C s   s        Sa  wC SC S sS    w   C  Cs C s            S C ssa a  S       S w a   Sa   C       S        a    C C w      S aC  a    S Ssa        s C C Cs     aa    a  s s s       @  wS       w          s  C    CsS    S wa  w w      sC  Ca       S              a   SaS s  a                   ss C  S   as  S    w a     a      C     s  s         w     s C          S        s  S        S  SCS   s  CS     s            s  S CS    w    aS      aa       SS s aS  C    w     a    w              C    aC  sC    w s      S     w s  C  aa         s s        Cs   s   a                  s  C a   C      CsCSs     S C  a   >ss s   C  S   a   C      s   s w            S  a   a a    s     w           S  C  w   s   as             s      w     s      a    C  w      S s   sS  CC s            C SSC  w   a  s              C   Cs   S        |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 1002
ace_score 5010
size 1002, 1
stairs 788, 0

warrior 355, 0, :east

unit :captive, 1, 0, :east
unit :captive, 4, 0, :east
unit :sludge, 7, 0, :east
unit :wizard, 11, 0, :east
unit :sludge, 15, 0, :east
unit :wizard, 17, 0, :east
unit :wizard, 20, 0, :east
unit :captive, 22, 0, :east
unit :sludge, 24, 0, :east
unit :captive, 25, 0, :east
unit :captive, 26, 0, :east
unit :archer, 29, 0, :east
unit :thick_sludge, 32, 0, :east
unit :captive, 33, 0, :east
unit :captive, 35, 0, :east
unit :thick_sludge, 41, 0, :east
unit :thick_sludge, 45, 0, :east
unit :archer, 50, 0, :east
unit :captive, 52, 0, :east
unit :archer, 59, 0, :east
unit :sludge, 60, 0, :east
unit :thick_sludge, 63, 0, :east
unit :sludge, 66, 0, :east
unit :captive, 68, 0, :east
unit :thick_sludge, 69, 0, :east
unit :wizard, 70, 0, :east
unit :wizard, 79, 0, :east
unit :captive, 80, 0, :east
unit :captive, 81, 0, :east
unit :sludge, 83, 0, :east
unit :archer, 89, 0, :east
unit :sludge, 92, 0, :east
unit :thick_sludge, 93, 0, :east
unit :archer, 95, 0, :east
unit :captive, 98, 0, :east
unit :captive, 104, 0, :east
unit :wizard, 118, 0, :east
unit :sludge, 120, 0, :east
unit :archer, 124, 0, :east
unit :wizard, 129, 0, :east
unit :thick_sludge, 130, 0, :east
unit :archer, 136, 0, :east
unit :captive, 149, 0, :east
unit :wizard, 151, 0, :east
unit :wizard, 153, 0, :east
unit :wizard, 158, 0, :east
unit :thick_sludge, 167, 0, :east
unit :captive, 168, 0, :east
unit :captive, 174, 0, :east
unit :sludge, 176, 0, :east
unit :sludge, 180, 0, :east
unit :thick_sludge, 189, 0, :east
unit :archer, 190, 0, :east
unit :wizard, 193, 0, :east
unit :captive, 194, 0, :east
unit :thick_sludge, 196, 0, :east
unit :captive, 197, 0, :east
unit :thick_sludge, 199, 0, :east
unit :sludge, 201, 0, :east
unit :thick_sludge, 202, 0, :east
unit :wizard, 207, 0, :east
unit :captive, 211, 0, :east
unit :captive, 214, 0, :east
unit :sludge, 215, 0, :east
unit :captive, 217, 0, :east
unit :sludge, 219, 0, :east
unit :thick_sludge, 232, 0, :east
unit :captive, 234, 0, :east
unit :sludge, 236, 0, :east
unit :sludge, 237, 0, :east
unit :archer, 238, 0, :east
unit :archer, 240, 0, :east
unit :thick_sludge, 243, 0, :east
unit :thick_sludge, 251, 0, :east
unit :wizard, 253, 0, :east
unit :archer, 255, 0, :east
unit :thick_sludge, 259, 0, :east
unit :archer, 260, 0, :east
unit :captive, 264, 0, :east
unit :thick_sludge, 272, 0, :east
unit :archer, 281, 0, :east
unit :captive, 286, 0, :east
unit :captive, 288, 0, :east
unit :wizard, 290, 0, :east
unit :thick_sludge, 297, 0, :east
unit :archer, 299, 0, :east
unit :captive, 300, 0, :east
unit :archer, 303, 0, :east
unit :thick_sludge, 308, 0, :east
unit :thick_sludge, 310, 0, :east
unit :sludge, 311, 0, :east
unit :archer, 312, 0, :east
unit :sludge, 321, 0, :east
unit :captive, 323, 0, :east
unit :captive, 325, 0, :east
unit :captive, 327, 0, :east
unit :sludge, 328, 0, :east
unit :archer, 334, 0, :east
unit :archer, 335, 0, :east
unit :archer, 340, 0, :east
unit :sludge, 343, 0, :east
unit :sludge, 345, 0, :east
unit :sludge, 347, 0, :east
unit :wizard, 358, 0, :west
unit :thick_sludge, 359, 0, :west
unit :wizard, 367, 0, :west
unit :sludge, 378, 0, :west
unit :captive, 381, 0, :west
unit :captive, 386, 0, :west
unit :sludge, 387, 0, :west
unit :thick_sludge, 388, 0, :west
unit :thick_sludge, 393, 0, :west
unit :wizard, 395, 0, :west
unit :archer, 396, 0, :west
unit :wizard, 399, 0, :west
unit :wizard, 401, 0, :west
unit :sludge, 408, 0, :west
unit :captive, 409, 0, :west
unit :captive, 412, 0, :west
unit :archer, 413, 0, :west
unit :thick_sludge, 421, 0, :west
unit :archer, 436, 0, :west
unit :thick_sludge, 440, 0, :west
unit :archer, 441, 0, :west
unit :thick_sludge, 442, 0, :west
unit :sludge, 444, 0, :west
unit :archer, 447, 0, :west
unit :sludge, 467, 0, :west
unit :sludge, 468, 0, :west
unit :captive, 470, 0, :west
unit :thick_sludge, 473, 0, :west
unit :archer, 477, 0, :west
unit :sludge, 478, 0, :west
unit :thick_sludge, 481, 0, :west
unit :wizard, 486, 0, :west
unit :archer, 488, 0, :west
unit :archer, 494, 0, :west
unit :captive, 501, 0, :west
unit :sludge, 507, 0, :west
unit :sludge, 510, 0, :west
unit :wizard, 520, 0, :west
unit :sludge, 526, 0, :west
unit :captive, 528, 0, :west
unit :thick_sludge, 539, 0, :west
unit :sludge, 548, 0, :west
unit :thick_sludge, 551, 0, :west
unit :thick_sludge, 560, 0, :west
unit :thick_sludge, 563, 0, :west
unit :captive, 564, 0, :west
unit :thick_sludge, 565, 0, :west
unit :sludge, 569, 0, :west
unit :captive, 572, 0, :west
unit :thick_sludge, 573, 0, :west
unit :sludge, 579, 0, :west
unit :sludge, 592, 0, :west
unit :thick_sludge, 595, 0, :west
unit :captive, 597, 0, :west
unit :thick_sludge, 598, 0, :west
unit :wizard, 603, 0, :west
unit :archer, 608, 0, :west
unit :thick_sludge, 609, 0, :west
unit :archer, 616, 0, :west
unit :archer, 617, 0, :west
unit :thick_sludge, 625, 0, :west
unit :thick_sludge, 626, 0, :west
unit :sludge, 628, 0, :west
unit :archer, 630, 0, :west
unit :thick_sludge, 631, 0, :west
unit :captive, 634, 0, :west
unit :wizard, 639, 0, :west
unit :archer, 645, 0, :west
unit :wizard, 650, 0, :west
unit :captive, 665, 0, :west
unit :archer, 670, 0, :west
unit :captive, 671, 0, :west
unit :sludge, 674, 0, :west
unit :captive, 675, 0, :west
unit :wizard, 680, 0, :west
unit :sludge, 682, 0, :west
unit :thick_sludge, 689, 0, :west
unit :wizard, 695, 0, :west
unit :sludge, 697, 0, :west
unit :captive, 700, 0, :west
unit :archer, 703, 0, :west
unit :archer, 704, 0, :west
unit :sludge, 714, 0, :west
unit :sludge, 716, 0, :west
unit :captive, 725, 0, :west
unit :sludge, 726, 0, :west
unit :sludge, 730, 0, :west
unit :archer, 734, 0, :west
unit :sludge, 753, 0, :west
unit :captive, 756, 0, :west
unit :archer, 758, 0, :west
unit :captive, 762, 0, :west
unit :captive, 769, 0, :west
unit :sludge, 770, 0, :west
unit :captive, 771, 0, :west
unit :thick_sludge, 772, 0, :west
unit :sludge, 773, 0, :west
unit :thick_sludge, 779, 0, :west
unit :captive, 781, 0, :west
unit :archer, 784, 0, :west
unit :sludge, 789, 0, :west
unit :sludge, 790, 0, :west
unit :sludge, 792, 0, :west
unit :captive, 796, 0, :west
unit :thick_sludge, 799, 0, :west
unit :archer, 803, 0, :west
unit :captive, 807, 0, :west
unit :sludge, 814, 0, :west
unit :sludge, 818, 0, :west
unit :wizard, 820, 0, :west
unit :thick_sludge, 833, 0, :west
unit :archer, 836, 0, :west
unit :archer, 840, 0, :west
unit :archer, 842, 0, :west
unit :sludge, 847, 0, :west
unit :wizard, 853, 0, :west
unit :thick_sludge, 865, 0, :west
unit :captive, 868, 0, :west
unit :wizard, 871, 0, :west
unit :sludge, 875, 0, :west
unit :archer, 879, 0, :west
unit :sludge, 880, 0, :west
unit :sludge, 894, 0, :west
unit :wizard, 901, 0, :west
unit :sludge, 907, 0, :west
unit :archer, 914, 0, :west
unit :captive, 919, 0, :west
unit :wizard, 922, 0, :west
unit :thick_sludge, 929, 0, :west
unit :sludge, 931, 0, :west
unit :sludge, 935, 0, :west
unit :thick_sludge, 936, 0, :west
unit :captive, 939, 0, :west
unit :captive, 940, 0, :west
unit :sludge, 942, 0, :west
unit :captive, 955, 0, :west
unit :thick_sludge, 957, 0, :west
unit :thick_sludge, 958, 0, :west
unit :captive, 959, 0, :west
unit :wizard, 962, 0, :west
unit :archer, 966, 0, :west
unit :sludge, 969, 0, :west
unit :captive, 984, 0, :west
unit :captive, 988, 0, :west
unit :sludge, 989, 0, :west
unit :thick_sludge, 993, 0, :west
