#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   S    s  S  sC   as  C      a   S   w      s  C S w     a w        S      C  S    wS  S   s     a      w    CSSa  C  SC   aSs  C      a  C   C a   s     a             sS C          SCS   w       w S  a     w  Ssw   Sa      s     s     w    s   w ss  aC  a     C       a  w    w    s w     S      @    S S  S a w SCC C                      S   a  S    CC  S       w  Cs   S    Cs   a     Cs   S as        C    a  s as a  w   a   w   SCs  C  >    a s      S S  C         w a   w w  C  a        S   C  SS           s w         a   S             SaS     w     s      s    C  a   |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 577
ace_score 2885
size 577, 1
stairs 442, 0

warrior 298, 0, :east

unit :thick_sludge, 3, 0, :east
unit :sludge, 8, 0, :east
unit :thick_sludge, 11, 0, :east
unit :sludge, 14, 0, :east
unit :captive, 15, 0, :east
unit :archer, 19, 0, :east
unit :sludge, 20, 0, :east
unit :captive, 23, 0, :east
unit :archer, 30, 0, :east
unit :thick_sludge, 34, 0, :east
unit :wizard, 38, 0, :east
unit :sludge, 45, 0, :east
unit :captive, 48, 0, :east
unit :thick_sludge, 50, 0, :east
unit :wizard, 52, 0, :east
unit :archer, 58, 0, :east
unit :wizard, 60, 0, :east
unit :thick_sludge, 69, 0, :east
unit :captive, 76, 0, :east
unit :thick_sludge, 79, 0, :east
unit :wizard, 84, 0, :east
unit :thick_sludge, 85, 0, :east
unit :thick_sludge, 88, 0, :east
unit :sludge, 92, 0, :east
unit :archer, 98, 0, :east
unit :wizard, 105, 0, :east
unit :captive, 110, 0, :east
unit :thick_sludge, 111, 0, :east
unit :thick_sludge, 112, 0, :east
unit :archer, 113, 0, :east
unit :captive, 116, 0, :east
unit :thick_sludge, 119, 0, :east
unit :captive, 120, 0, :east
unit :archer, 124, 0, :east
unit :thick_sludge, 125, 0, :east
unit :sludge, 126, 0, :east
unit :captive, 129, 0, :east
unit :archer, 136, 0, :east
unit :captive, 139, 0, :east
unit :captive, 143, 0, :east
unit :archer, 145, 0, :east
unit :sludge, 149, 0, :east
unit :archer, 155, 0, :east
unit :sludge, 169, 0, :east
unit :thick_sludge, 170, 0, :east
unit :captive, 172, 0, :east
unit :thick_sludge, 183, 0, :east
unit :captive, 184, 0, :east
unit :thick_sludge, 185, 0, :east
unit :wizard, 189, 0, :east
unit :wizard, 197, 0, :east
unit :thick_sludge, 199, 0, :east
unit :archer, 202, 0, :east
unit :wizard, 208, 0, :east
unit :thick_sludge, 211, 0, :east
unit :sludge, 212, 0, :east
unit :wizard, 213, 0, :east
unit :thick_sludge, 217, 0, :east
unit :archer, 218, 0, :east
unit :sludge, 225, 0, :east
unit :sludge, 231, 0, :east
unit :wizard, 237, 0, :east
unit :sludge, 242, 0, :east
unit :wizard, 246, 0, :east
unit :sludge, 248, 0, :east
unit :sludge, 249, 0, :east
unit :archer, 252, 0, :east
unit :captive, 253, 0, :east
unit :archer, 256, 0, :east
unit :captive, 262, 0, :east
unit :archer, 270, 0, :east
unit :wizard, 273, 0, :east
unit :wizard, 278, 0, :east
unit :sludge, 283, 0, :east
unit :wizard, 285, 0, :east
unit :thick_sludge, 291, 0, :east
unit :thick_sludge, 303, 0, :west
unit :thick_sludge, 305, 0, :west
unit :thick_sludge, 308, 0, :west
unit :archer, 310, 0, :west
unit :wizard, 312, 0, :west
unit :thick_sludge, 314, 0, :west
unit :captive, 315, 0, :west
unit :captive, 316, 0, :west
unit :captive, 318, 0, :west
unit :thick_sludge, 341, 0, :west
unit :archer, 345, 0, :west
unit :thick_sludge, 348, 0, :west
unit :captive, 353, 0, :west
unit :captive, 354, 0, :west
unit :thick_sludge, 357, 0, :west
unit :wizard, 365, 0, :west
unit :captive, 368, 0, :west
unit :sludge, 369, 0, :west
unit :thick_sludge, 373, 0, :west
unit :captive, 378, 0, :west
unit :sludge, 379, 0, :west
unit :archer, 383, 0, :west
unit :captive, 389, 0, :west
unit :sludge, 390, 0, :west
unit :thick_sludge, 394, 0, :west
unit :archer, 396, 0, :west
unit :sludge, 397, 0, :west
unit :captive, 406, 0, :west
unit :archer, 411, 0, :west
unit :sludge, 414, 0, :west
unit :archer, 416, 0, :west
unit :sludge, 417, 0, :west
unit :archer, 419, 0, :west
unit :wizard, 422, 0, :west
unit :archer, 426, 0, :west
unit :wizard, 430, 0, :west
unit :thick_sludge, 434, 0, :west
unit :captive, 435, 0, :west
unit :sludge, 436, 0, :west
unit :captive, 439, 0, :west
unit :archer, 447, 0, :west
unit :sludge, 449, 0, :west
unit :thick_sludge, 456, 0, :west
unit :thick_sludge, 458, 0, :west
unit :captive, 461, 0, :west
unit :wizard, 471, 0, :west
unit :archer, 473, 0, :west
unit :wizard, 477, 0, :west
unit :wizard, 479, 0, :west
unit :captive, 482, 0, :west
unit :archer, 485, 0, :west
unit :thick_sludge, 494, 0, :west
unit :captive, 498, 0, :west
unit :thick_sludge, 501, 0, :west
unit :thick_sludge, 502, 0, :west
unit :sludge, 514, 0, :west
unit :wizard, 516, 0, :west
unit :archer, 526, 0, :west
unit :thick_sludge, 530, 0, :west
unit :thick_sludge, 544, 0, :west
unit :archer, 545, 0, :west
unit :thick_sludge, 546, 0, :west
unit :wizard, 552, 0, :west
unit :sludge, 558, 0, :west
unit :sludge, 565, 0, :west
unit :captive, 570, 0, :west
unit :archer, 573, 0, :west
