#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     C    SCC  a    s C       aSS    S  aS   C w  CC sC   s    s     s CS       w a   > CC sa  S   s        s            a   Sa  w   ss   w    S  S  s s     w    a S               C CS  w S   C   s     w            s       sa  s      w       a  s  C         a C  w         sCs         s    C C  w S       a   a w  S               S S      Cs  w      s Sa         a  asSS  a  ws        S          S  S  s s      w sss   Saa w     s C s as S    Sw  a     aa         w  s  wS   s s       a  s    S a            w     a               s    C   C  Ca  SS       S      w w   a    swS      Sw  a s   S    w sSs a ss a a  SC  CS C    S     a S   S Ss      C  C S                  S        a     s   S w   C   C   w   a      s w      w S    C   a         w      C    w  w aa    Ca  a    s   C s    s   w   Cw    sS      w C   w  s      w  s w   S      a       a w  S   CS   a w  S             aSC S    C s  s       s          w   wa     s    C      sC   s       w          SCC           sSw C    @  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 989
ace_score 4945
size 989, 1
stairs 86, 0

warrior 986, 0, :east

unit :captive, 5, 0, :east
unit :thick_sludge, 10, 0, :east
unit :captive, 11, 0, :east
unit :captive, 12, 0, :east
unit :archer, 15, 0, :east
unit :sludge, 20, 0, :east
unit :captive, 22, 0, :east
unit :archer, 30, 0, :east
unit :thick_sludge, 31, 0, :east
unit :thick_sludge, 32, 0, :east
unit :thick_sludge, 37, 0, :east
unit :archer, 40, 0, :east
unit :thick_sludge, 41, 0, :east
unit :captive, 45, 0, :east
unit :wizard, 47, 0, :east
unit :captive, 50, 0, :east
unit :captive, 51, 0, :east
unit :sludge, 53, 0, :east
unit :captive, 54, 0, :east
unit :sludge, 58, 0, :east
unit :sludge, 63, 0, :east
unit :sludge, 69, 0, :east
unit :captive, 71, 0, :east
unit :thick_sludge, 72, 0, :east
unit :wizard, 80, 0, :east
unit :archer, 82, 0, :east
unit :captive, 88, 0, :east
unit :captive, 89, 0, :east
unit :sludge, 91, 0, :east
unit :archer, 92, 0, :east
unit :thick_sludge, 95, 0, :east
unit :sludge, 99, 0, :east
unit :sludge, 108, 0, :east
unit :archer, 121, 0, :east
unit :thick_sludge, 125, 0, :east
unit :archer, 126, 0, :east
unit :wizard, 129, 0, :east
unit :sludge, 133, 0, :east
unit :sludge, 134, 0, :east
unit :wizard, 138, 0, :east
unit :thick_sludge, 143, 0, :east
unit :thick_sludge, 146, 0, :east
unit :sludge, 149, 0, :east
unit :sludge, 151, 0, :east
unit :wizard, 157, 0, :east
unit :archer, 162, 0, :east
unit :thick_sludge, 164, 0, :east
unit :captive, 180, 0, :east
unit :captive, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :wizard, 186, 0, :east
unit :thick_sludge, 188, 0, :east
unit :captive, 192, 0, :east
unit :sludge, 196, 0, :east
unit :wizard, 202, 0, :east
unit :sludge, 215, 0, :east
unit :sludge, 223, 0, :east
unit :archer, 224, 0, :east
unit :sludge, 227, 0, :east
unit :wizard, 234, 0, :east
unit :archer, 242, 0, :east
unit :sludge, 245, 0, :east
unit :captive, 248, 0, :east
unit :archer, 258, 0, :east
unit :captive, 260, 0, :east
unit :wizard, 263, 0, :east
unit :sludge, 273, 0, :east
unit :captive, 274, 0, :east
unit :sludge, 275, 0, :east
unit :sludge, 285, 0, :east
unit :captive, 290, 0, :east
unit :captive, 292, 0, :east
unit :wizard, 295, 0, :east
unit :thick_sludge, 297, 0, :east
unit :archer, 305, 0, :east
unit :archer, 309, 0, :east
unit :wizard, 311, 0, :east
unit :thick_sludge, 314, 0, :east
unit :thick_sludge, 330, 0, :east
unit :thick_sludge, 332, 0, :east
unit :captive, 339, 0, :east
unit :sludge, 340, 0, :east
unit :wizard, 343, 0, :east
unit :sludge, 350, 0, :east
unit :thick_sludge, 352, 0, :east
unit :archer, 353, 0, :east
unit :archer, 363, 0, :east
unit :archer, 366, 0, :east
unit :sludge, 367, 0, :east
unit :thick_sludge, 368, 0, :east
unit :thick_sludge, 369, 0, :east
unit :archer, 372, 0, :east
unit :wizard, 375, 0, :east
unit :sludge, 376, 0, :east
unit :thick_sludge, 385, 0, :east
unit :thick_sludge, 396, 0, :east
unit :thick_sludge, 399, 0, :east
unit :sludge, 402, 0, :east
unit :sludge, 404, 0, :east
unit :wizard, 411, 0, :east
unit :sludge, 413, 0, :east
unit :sludge, 414, 0, :east
unit :sludge, 415, 0, :east
unit :thick_sludge, 419, 0, :east
unit :archer, 420, 0, :east
unit :archer, 421, 0, :east
unit :wizard, 423, 0, :east
unit :sludge, 429, 0, :east
unit :captive, 431, 0, :east
unit :sludge, 433, 0, :east
unit :archer, 435, 0, :east
unit :sludge, 436, 0, :east
unit :thick_sludge, 438, 0, :east
unit :thick_sludge, 443, 0, :east
unit :wizard, 444, 0, :east
unit :archer, 447, 0, :east
unit :archer, 453, 0, :east
unit :archer, 454, 0, :east
unit :wizard, 464, 0, :east
unit :sludge, 467, 0, :east
unit :wizard, 470, 0, :east
unit :thick_sludge, 471, 0, :east
unit :sludge, 475, 0, :east
unit :sludge, 477, 0, :east
unit :archer, 485, 0, :east
unit :sludge, 488, 0, :east
unit :thick_sludge, 493, 0, :east
unit :archer, 495, 0, :east
unit :wizard, 508, 0, :east
unit :archer, 514, 0, :east
unit :sludge, 530, 0, :east
unit :captive, 535, 0, :east
unit :captive, 539, 0, :east
unit :captive, 542, 0, :east
unit :archer, 543, 0, :east
unit :thick_sludge, 546, 0, :east
unit :thick_sludge, 547, 0, :east
unit :thick_sludge, 555, 0, :east
unit :wizard, 562, 0, :east
unit :wizard, 564, 0, :east
unit :archer, 568, 0, :east
unit :sludge, 573, 0, :east
unit :wizard, 574, 0, :east
unit :thick_sludge, 575, 0, :east
unit :thick_sludge, 582, 0, :east
unit :wizard, 583, 0, :east
unit :archer, 586, 0, :east
unit :sludge, 588, 0, :east
unit :thick_sludge, 592, 0, :east
unit :wizard, 597, 0, :east
unit :sludge, 599, 0, :east
unit :thick_sludge, 600, 0, :east
unit :sludge, 601, 0, :east
unit :archer, 603, 0, :east
unit :sludge, 605, 0, :east
unit :sludge, 606, 0, :east
unit :archer, 608, 0, :east
unit :archer, 610, 0, :east
unit :thick_sludge, 613, 0, :east
unit :captive, 614, 0, :east
unit :captive, 617, 0, :east
unit :thick_sludge, 618, 0, :east
unit :captive, 620, 0, :east
unit :thick_sludge, 625, 0, :east
unit :archer, 631, 0, :east
unit :thick_sludge, 633, 0, :east
unit :thick_sludge, 637, 0, :east
unit :thick_sludge, 639, 0, :east
unit :sludge, 640, 0, :east
unit :captive, 647, 0, :east
unit :captive, 650, 0, :east
unit :thick_sludge, 652, 0, :east
unit :thick_sludge, 671, 0, :east
unit :archer, 680, 0, :east
unit :sludge, 686, 0, :east
unit :thick_sludge, 690, 0, :east
unit :wizard, 692, 0, :east
unit :captive, 696, 0, :east
unit :captive, 700, 0, :east
unit :wizard, 704, 0, :east
unit :archer, 708, 0, :east
unit :sludge, 715, 0, :east
unit :wizard, 717, 0, :east
unit :wizard, 724, 0, :east
unit :thick_sludge, 726, 0, :east
unit :captive, 731, 0, :east
unit :archer, 735, 0, :east
unit :wizard, 745, 0, :east
unit :captive, 752, 0, :east
unit :wizard, 757, 0, :east
unit :wizard, 760, 0, :east
unit :archer, 762, 0, :east
unit :archer, 763, 0, :east
unit :captive, 768, 0, :east
unit :archer, 769, 0, :east
unit :archer, 772, 0, :east
unit :sludge, 777, 0, :east
unit :captive, 781, 0, :east
unit :sludge, 783, 0, :east
unit :sludge, 788, 0, :east
unit :wizard, 792, 0, :east
unit :captive, 796, 0, :east
unit :wizard, 797, 0, :east
unit :sludge, 802, 0, :east
unit :thick_sludge, 803, 0, :east
unit :wizard, 810, 0, :east
unit :captive, 812, 0, :east
unit :wizard, 816, 0, :east
unit :sludge, 819, 0, :east
unit :wizard, 826, 0, :east
unit :sludge, 829, 0, :east
unit :wizard, 831, 0, :east
unit :thick_sludge, 835, 0, :east
unit :archer, 842, 0, :east
unit :archer, 850, 0, :east
unit :wizard, 852, 0, :east
unit :thick_sludge, 855, 0, :east
unit :captive, 859, 0, :east
unit :thick_sludge, 860, 0, :east
unit :archer, 864, 0, :east
unit :wizard, 866, 0, :east
unit :thick_sludge, 869, 0, :east
unit :archer, 883, 0, :east
unit :thick_sludge, 884, 0, :east
unit :captive, 885, 0, :east
unit :thick_sludge, 887, 0, :east
unit :captive, 892, 0, :east
unit :sludge, 894, 0, :east
unit :sludge, 897, 0, :east
unit :sludge, 905, 0, :east
unit :wizard, 916, 0, :east
unit :wizard, 920, 0, :east
unit :archer, 921, 0, :east
unit :sludge, 927, 0, :east
unit :captive, 932, 0, :east
unit :sludge, 939, 0, :east
unit :captive, 940, 0, :east
unit :sludge, 944, 0, :east
unit :wizard, 952, 0, :east
unit :thick_sludge, 963, 0, :east
unit :captive, 964, 0, :east
unit :captive, 965, 0, :east
unit :sludge, 977, 0, :east
unit :thick_sludge, 978, 0, :east
unit :wizard, 979, 0, :east
unit :captive, 981, 0, :east
