#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a C S  s wa     a    s   a     s          s  a S  s   S S   S    s   s  w  w    w  s  C     w  w   C w  S C           s   a  w sCsC      C   S   C aS C w   SasSC       C   a                C   >  C s w S    w S S   ss   s   w Cs w C  w  C      S C   C    S w  C   a S   S      w     a               wC  a w    a             C      s         w sw      C  Sa   a       w w C       S   s  w     w a             aC w  S wa  aS        C  C s   wC   s      a            s  CC  s  S      aw      w C     S            C  s aC     C        ss       C  C C  S  CC   C     w C    Ca C  a  C   s  a C    sS      w     C C   w      @   S s   a       s  Sa   sS     a         SC   C            sS    a       s      CC |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 705
ace_score 3525
size 705, 1
stairs 194, 0

warrior 620, 0, :east

unit :archer, 1, 0, :east
unit :captive, 3, 0, :east
unit :thick_sludge, 5, 0, :east
unit :sludge, 8, 0, :east
unit :wizard, 10, 0, :east
unit :archer, 11, 0, :east
unit :archer, 17, 0, :east
unit :sludge, 22, 0, :east
unit :archer, 26, 0, :east
unit :sludge, 32, 0, :east
unit :sludge, 43, 0, :east
unit :archer, 46, 0, :east
unit :thick_sludge, 48, 0, :east
unit :sludge, 51, 0, :east
unit :thick_sludge, 55, 0, :east
unit :thick_sludge, 57, 0, :east
unit :thick_sludge, 61, 0, :east
unit :sludge, 66, 0, :east
unit :sludge, 70, 0, :east
unit :wizard, 73, 0, :east
unit :wizard, 76, 0, :east
unit :wizard, 81, 0, :east
unit :sludge, 84, 0, :east
unit :captive, 87, 0, :east
unit :wizard, 93, 0, :east
unit :wizard, 96, 0, :east
unit :captive, 100, 0, :east
unit :wizard, 102, 0, :east
unit :thick_sludge, 105, 0, :east
unit :captive, 107, 0, :east
unit :sludge, 119, 0, :east
unit :archer, 123, 0, :east
unit :wizard, 126, 0, :east
unit :sludge, 128, 0, :east
unit :captive, 129, 0, :east
unit :sludge, 130, 0, :east
unit :captive, 131, 0, :east
unit :captive, 138, 0, :east
unit :thick_sludge, 142, 0, :east
unit :captive, 146, 0, :east
unit :archer, 148, 0, :east
unit :thick_sludge, 149, 0, :east
unit :captive, 151, 0, :east
unit :wizard, 153, 0, :east
unit :thick_sludge, 157, 0, :east
unit :archer, 158, 0, :east
unit :sludge, 159, 0, :east
unit :thick_sludge, 160, 0, :east
unit :captive, 161, 0, :east
unit :captive, 169, 0, :east
unit :archer, 173, 0, :east
unit :captive, 190, 0, :east
unit :captive, 197, 0, :east
unit :sludge, 199, 0, :east
unit :wizard, 201, 0, :east
unit :thick_sludge, 203, 0, :east
unit :wizard, 208, 0, :east
unit :thick_sludge, 210, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 216, 0, :east
unit :sludge, 217, 0, :east
unit :sludge, 221, 0, :east
unit :wizard, 225, 0, :east
unit :captive, 227, 0, :east
unit :sludge, 228, 0, :east
unit :wizard, 230, 0, :east
unit :captive, 232, 0, :east
unit :wizard, 235, 0, :east
unit :captive, 238, 0, :east
unit :thick_sludge, 245, 0, :east
unit :captive, 247, 0, :east
unit :captive, 251, 0, :east
unit :thick_sludge, 256, 0, :east
unit :wizard, 258, 0, :east
unit :captive, 261, 0, :east
unit :archer, 265, 0, :east
unit :thick_sludge, 267, 0, :east
unit :thick_sludge, 271, 0, :east
unit :wizard, 278, 0, :east
unit :archer, 284, 0, :east
unit :wizard, 300, 0, :east
unit :captive, 301, 0, :east
unit :archer, 304, 0, :east
unit :wizard, 306, 0, :east
unit :archer, 311, 0, :east
unit :captive, 325, 0, :east
unit :sludge, 332, 0, :east
unit :wizard, 342, 0, :east
unit :sludge, 344, 0, :east
unit :wizard, 345, 0, :east
unit :captive, 352, 0, :east
unit :thick_sludge, 355, 0, :east
unit :archer, 356, 0, :east
unit :archer, 360, 0, :east
unit :wizard, 368, 0, :east
unit :wizard, 370, 0, :east
unit :captive, 372, 0, :east
unit :thick_sludge, 380, 0, :east
unit :sludge, 384, 0, :east
unit :wizard, 387, 0, :east
unit :wizard, 393, 0, :east
unit :archer, 395, 0, :east
unit :archer, 409, 0, :east
unit :captive, 410, 0, :east
unit :wizard, 412, 0, :east
unit :thick_sludge, 415, 0, :east
unit :wizard, 417, 0, :east
unit :archer, 418, 0, :east
unit :archer, 421, 0, :east
unit :thick_sludge, 422, 0, :east
unit :captive, 431, 0, :east
unit :captive, 434, 0, :east
unit :sludge, 436, 0, :east
unit :wizard, 440, 0, :east
unit :captive, 441, 0, :east
unit :sludge, 445, 0, :east
unit :archer, 452, 0, :east
unit :sludge, 465, 0, :east
unit :captive, 468, 0, :east
unit :captive, 469, 0, :east
unit :sludge, 472, 0, :east
unit :thick_sludge, 475, 0, :east
unit :archer, 482, 0, :east
unit :wizard, 483, 0, :east
unit :wizard, 490, 0, :east
unit :captive, 492, 0, :east
unit :thick_sludge, 498, 0, :east
unit :captive, 511, 0, :east
unit :sludge, 514, 0, :east
unit :archer, 516, 0, :east
unit :captive, 517, 0, :east
unit :captive, 523, 0, :east
unit :sludge, 532, 0, :east
unit :sludge, 533, 0, :east
unit :captive, 541, 0, :east
unit :captive, 544, 0, :east
unit :captive, 546, 0, :east
unit :thick_sludge, 549, 0, :east
unit :captive, 552, 0, :east
unit :captive, 553, 0, :east
unit :captive, 557, 0, :east
unit :wizard, 563, 0, :east
unit :captive, 565, 0, :east
unit :captive, 570, 0, :east
unit :archer, 571, 0, :east
unit :captive, 573, 0, :east
unit :archer, 576, 0, :east
unit :captive, 579, 0, :east
unit :sludge, 583, 0, :east
unit :archer, 586, 0, :east
unit :captive, 588, 0, :east
unit :sludge, 593, 0, :east
unit :thick_sludge, 594, 0, :east
unit :wizard, 601, 0, :east
unit :captive, 607, 0, :east
unit :captive, 609, 0, :east
unit :wizard, 613, 0, :east
unit :thick_sludge, 624, 0, :west
unit :sludge, 626, 0, :west
unit :archer, 630, 0, :west
unit :sludge, 638, 0, :west
unit :thick_sludge, 641, 0, :west
unit :archer, 642, 0, :west
unit :sludge, 646, 0, :west
unit :thick_sludge, 647, 0, :west
unit :archer, 653, 0, :west
unit :thick_sludge, 663, 0, :west
unit :captive, 664, 0, :west
unit :captive, 668, 0, :west
unit :sludge, 681, 0, :west
unit :thick_sludge, 682, 0, :west
unit :archer, 687, 0, :west
unit :sludge, 695, 0, :west
unit :captive, 702, 0, :west
unit :captive, 703, 0, :west
