#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w    S     S C   S   s       @   w S   S  Cas      SC  s    S w CS S   Cw aC      aC   C       s    w        as             C  aws  a       C         C  w S   s     S  s   w  Cs         C w    S  w   a a    sSs w  S    S    S   w    S      S   C      S  s  w Sa        a  S   S         aSS        S  C       w    S     w   S       Sw   C             S     wSSaa       C     S   w      Caa S       w S    C       s     S    a a   CS    C  aC Sw    as aC    Ca  C  a S a                  ss         w    C                     S s   C a SC s  a     s      C    C   S w   a sa   C S       a           w S  s   aC   w  S   w  w s    C    s            Ca  Ca  s s  sa       sa   a s s  S s   CS   s       C        w  S S   Ss     s   w a          SCa       w         s    w  sS w       w  w     sS      w >sa  SC    S w    C  |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 820
ace_score 4100
size 820, 1
stairs 799, 0

warrior 29, 0, :east

unit :wizard, 0, 0, :east
unit :thick_sludge, 5, 0, :east
unit :thick_sludge, 11, 0, :east
unit :captive, 13, 0, :east
unit :thick_sludge, 17, 0, :east
unit :sludge, 21, 0, :east
unit :wizard, 33, 0, :west
unit :thick_sludge, 35, 0, :west
unit :thick_sludge, 39, 0, :west
unit :captive, 42, 0, :west
unit :archer, 43, 0, :west
unit :sludge, 44, 0, :west
unit :thick_sludge, 51, 0, :west
unit :captive, 52, 0, :west
unit :sludge, 55, 0, :west
unit :thick_sludge, 60, 0, :west
unit :wizard, 62, 0, :west
unit :captive, 64, 0, :west
unit :thick_sludge, 65, 0, :west
unit :thick_sludge, 67, 0, :west
unit :captive, 71, 0, :west
unit :wizard, 72, 0, :west
unit :archer, 74, 0, :west
unit :captive, 75, 0, :west
unit :archer, 82, 0, :west
unit :captive, 83, 0, :west
unit :captive, 87, 0, :west
unit :sludge, 95, 0, :west
unit :wizard, 100, 0, :west
unit :archer, 109, 0, :west
unit :sludge, 110, 0, :west
unit :captive, 124, 0, :west
unit :archer, 127, 0, :west
unit :wizard, 128, 0, :west
unit :sludge, 129, 0, :west
unit :archer, 132, 0, :west
unit :captive, 140, 0, :west
unit :captive, 150, 0, :west
unit :wizard, 153, 0, :west
unit :thick_sludge, 155, 0, :west
unit :sludge, 159, 0, :west
unit :thick_sludge, 165, 0, :west
unit :sludge, 168, 0, :west
unit :wizard, 172, 0, :west
unit :captive, 175, 0, :west
unit :sludge, 176, 0, :west
unit :captive, 186, 0, :west
unit :wizard, 188, 0, :west
unit :thick_sludge, 193, 0, :west
unit :wizard, 196, 0, :west
unit :archer, 200, 0, :west
unit :archer, 202, 0, :west
unit :sludge, 207, 0, :west
unit :thick_sludge, 208, 0, :west
unit :sludge, 209, 0, :west
unit :wizard, 211, 0, :west
unit :thick_sludge, 214, 0, :west
unit :thick_sludge, 219, 0, :west
unit :thick_sludge, 224, 0, :west
unit :wizard, 228, 0, :west
unit :thick_sludge, 233, 0, :west
unit :thick_sludge, 240, 0, :west
unit :captive, 244, 0, :west
unit :thick_sludge, 251, 0, :west
unit :sludge, 254, 0, :west
unit :wizard, 257, 0, :west
unit :thick_sludge, 259, 0, :west
unit :archer, 260, 0, :west
unit :archer, 269, 0, :west
unit :thick_sludge, 272, 0, :west
unit :thick_sludge, 276, 0, :west
unit :archer, 286, 0, :west
unit :thick_sludge, 287, 0, :west
unit :thick_sludge, 288, 0, :west
unit :thick_sludge, 297, 0, :west
unit :captive, 300, 0, :west
unit :wizard, 308, 0, :west
unit :thick_sludge, 313, 0, :west
unit :wizard, 319, 0, :west
unit :thick_sludge, 323, 0, :west
unit :thick_sludge, 331, 0, :west
unit :wizard, 332, 0, :west
unit :captive, 336, 0, :west
unit :thick_sludge, 350, 0, :west
unit :wizard, 356, 0, :west
unit :thick_sludge, 357, 0, :west
unit :thick_sludge, 358, 0, :west
unit :archer, 359, 0, :west
unit :archer, 360, 0, :west
unit :captive, 368, 0, :west
unit :thick_sludge, 374, 0, :west
unit :wizard, 378, 0, :west
unit :captive, 385, 0, :west
unit :archer, 386, 0, :west
unit :archer, 387, 0, :west
unit :thick_sludge, 389, 0, :west
unit :wizard, 397, 0, :west
unit :thick_sludge, 399, 0, :west
unit :captive, 404, 0, :west
unit :sludge, 412, 0, :west
unit :thick_sludge, 418, 0, :west
unit :archer, 423, 0, :west
unit :archer, 425, 0, :west
unit :captive, 429, 0, :west
unit :thick_sludge, 430, 0, :west
unit :captive, 435, 0, :west
unit :archer, 438, 0, :west
unit :captive, 439, 0, :west
unit :thick_sludge, 441, 0, :west
unit :wizard, 442, 0, :west
unit :archer, 447, 0, :west
unit :sludge, 448, 0, :west
unit :archer, 450, 0, :west
unit :captive, 451, 0, :west
unit :captive, 456, 0, :west
unit :archer, 457, 0, :west
unit :captive, 460, 0, :west
unit :archer, 463, 0, :west
unit :thick_sludge, 465, 0, :west
unit :archer, 467, 0, :west
unit :sludge, 486, 0, :west
unit :sludge, 487, 0, :west
unit :wizard, 497, 0, :west
unit :captive, 502, 0, :west
unit :thick_sludge, 524, 0, :west
unit :sludge, 526, 0, :west
unit :captive, 530, 0, :west
unit :archer, 532, 0, :west
unit :thick_sludge, 534, 0, :west
unit :captive, 535, 0, :west
unit :sludge, 537, 0, :west
unit :archer, 540, 0, :west
unit :sludge, 546, 0, :west
unit :captive, 553, 0, :west
unit :captive, 558, 0, :west
unit :thick_sludge, 562, 0, :west
unit :wizard, 564, 0, :west
unit :archer, 568, 0, :west
unit :sludge, 570, 0, :west
unit :archer, 571, 0, :west
unit :captive, 575, 0, :west
unit :thick_sludge, 577, 0, :west
unit :archer, 585, 0, :west
unit :wizard, 597, 0, :west
unit :thick_sludge, 599, 0, :west
unit :sludge, 602, 0, :west
unit :archer, 606, 0, :west
unit :captive, 607, 0, :west
unit :wizard, 611, 0, :west
unit :thick_sludge, 614, 0, :west
unit :wizard, 618, 0, :west
unit :wizard, 621, 0, :west
unit :sludge, 623, 0, :west
unit :captive, 628, 0, :west
unit :sludge, 633, 0, :west
unit :captive, 646, 0, :west
unit :archer, 647, 0, :west
unit :captive, 650, 0, :west
unit :archer, 651, 0, :west
unit :sludge, 654, 0, :west
unit :sludge, 656, 0, :west
unit :sludge, 659, 0, :west
unit :archer, 660, 0, :west
unit :sludge, 668, 0, :west
unit :archer, 669, 0, :west
unit :archer, 673, 0, :west
unit :sludge, 675, 0, :west
unit :sludge, 677, 0, :west
unit :thick_sludge, 680, 0, :west
unit :sludge, 682, 0, :west
unit :captive, 686, 0, :west
unit :thick_sludge, 687, 0, :west
unit :sludge, 691, 0, :west
unit :captive, 699, 0, :west
unit :wizard, 708, 0, :west
unit :thick_sludge, 711, 0, :west
unit :thick_sludge, 713, 0, :west
unit :thick_sludge, 717, 0, :west
unit :sludge, 718, 0, :west
unit :sludge, 724, 0, :west
unit :wizard, 728, 0, :west
unit :archer, 730, 0, :west
unit :thick_sludge, 741, 0, :west
unit :captive, 742, 0, :west
unit :archer, 743, 0, :west
unit :wizard, 751, 0, :west
unit :sludge, 761, 0, :west
unit :wizard, 766, 0, :west
unit :sludge, 769, 0, :west
unit :thick_sludge, 770, 0, :west
unit :wizard, 772, 0, :west
unit :wizard, 780, 0, :west
unit :wizard, 783, 0, :west
unit :sludge, 789, 0, :west
unit :thick_sludge, 790, 0, :west
unit :wizard, 797, 0, :west
unit :sludge, 800, 0, :west
unit :archer, 801, 0, :west
unit :thick_sludge, 804, 0, :west
unit :captive, 805, 0, :west
unit :thick_sludge, 810, 0, :west
unit :wizard, 812, 0, :west
unit :captive, 817, 0, :west
