#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | SSa C   a C as     sss  C C  s     S S   aC     s  s          s a  w C w             SSa      ss   S sSCa  s      S  C      >     aw w a     w  CC       a     a a       S       @       a  S   C        sa         a s   a   as as  S Cw  s    a  w                    a   S  s        w  sa     s      w     s  aC     C           S  C     Cs      s       w       C    S         a      s  S  aw a      C s a S  C      a   w     C s                w C  s   C  Sa w s SS     s                        S s s        w  C     Ca  w   S      Cs   w       SS  s  w SsS w sS w   a   s  a aa a s     C   a  wS     a  a|
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 603
ace_score 3015
size 603, 1
stairs 125, 0

warrior 178, 0, :east

unit :thick_sludge, 1, 0, :east
unit :thick_sludge, 2, 0, :east
unit :archer, 3, 0, :east
unit :captive, 5, 0, :east
unit :archer, 9, 0, :east
unit :captive, 11, 0, :east
unit :archer, 13, 0, :east
unit :sludge, 14, 0, :east
unit :sludge, 20, 0, :east
unit :sludge, 21, 0, :east
unit :sludge, 22, 0, :east
unit :captive, 25, 0, :east
unit :captive, 27, 0, :east
unit :sludge, 30, 0, :east
unit :thick_sludge, 36, 0, :east
unit :thick_sludge, 38, 0, :east
unit :archer, 42, 0, :east
unit :captive, 43, 0, :east
unit :sludge, 49, 0, :east
unit :sludge, 52, 0, :east
unit :sludge, 63, 0, :east
unit :archer, 65, 0, :east
unit :wizard, 68, 0, :east
unit :captive, 70, 0, :east
unit :wizard, 72, 0, :east
unit :thick_sludge, 86, 0, :east
unit :thick_sludge, 87, 0, :east
unit :archer, 88, 0, :east
unit :sludge, 95, 0, :east
unit :sludge, 96, 0, :east
unit :thick_sludge, 100, 0, :east
unit :sludge, 102, 0, :east
unit :thick_sludge, 103, 0, :east
unit :captive, 104, 0, :east
unit :archer, 105, 0, :east
unit :sludge, 108, 0, :east
unit :thick_sludge, 115, 0, :east
unit :captive, 118, 0, :east
unit :archer, 131, 0, :east
unit :wizard, 132, 0, :east
unit :wizard, 134, 0, :east
unit :archer, 136, 0, :east
unit :wizard, 142, 0, :east
unit :captive, 145, 0, :east
unit :captive, 146, 0, :east
unit :archer, 154, 0, :east
unit :archer, 160, 0, :east
unit :archer, 162, 0, :east
unit :thick_sludge, 170, 0, :east
unit :archer, 186, 0, :west
unit :thick_sludge, 189, 0, :west
unit :captive, 193, 0, :west
unit :sludge, 202, 0, :west
unit :archer, 203, 0, :west
unit :archer, 213, 0, :west
unit :sludge, 215, 0, :west
unit :archer, 219, 0, :west
unit :archer, 223, 0, :west
unit :sludge, 224, 0, :west
unit :archer, 226, 0, :west
unit :sludge, 227, 0, :west
unit :thick_sludge, 230, 0, :west
unit :captive, 232, 0, :west
unit :wizard, 233, 0, :west
unit :sludge, 236, 0, :west
unit :archer, 241, 0, :west
unit :wizard, 244, 0, :west
unit :archer, 265, 0, :west
unit :thick_sludge, 269, 0, :west
unit :sludge, 272, 0, :west
unit :wizard, 281, 0, :west
unit :sludge, 284, 0, :west
unit :archer, 285, 0, :west
unit :sludge, 291, 0, :west
unit :wizard, 298, 0, :west
unit :sludge, 304, 0, :west
unit :archer, 307, 0, :west
unit :captive, 308, 0, :west
unit :captive, 314, 0, :west
unit :thick_sludge, 326, 0, :west
unit :captive, 329, 0, :west
unit :captive, 335, 0, :west
unit :sludge, 336, 0, :west
unit :sludge, 343, 0, :west
unit :wizard, 351, 0, :west
unit :captive, 359, 0, :west
unit :thick_sludge, 364, 0, :west
unit :archer, 374, 0, :west
unit :sludge, 381, 0, :west
unit :thick_sludge, 384, 0, :west
unit :archer, 387, 0, :west
unit :wizard, 388, 0, :west
unit :archer, 390, 0, :west
unit :captive, 397, 0, :west
unit :sludge, 399, 0, :west
unit :archer, 401, 0, :west
unit :thick_sludge, 403, 0, :west
unit :captive, 406, 0, :west
unit :archer, 413, 0, :west
unit :wizard, 417, 0, :west
unit :captive, 423, 0, :west
unit :sludge, 425, 0, :west
unit :wizard, 442, 0, :west
unit :captive, 444, 0, :west
unit :sludge, 447, 0, :west
unit :captive, 451, 0, :west
unit :thick_sludge, 454, 0, :west
unit :archer, 455, 0, :west
unit :wizard, 457, 0, :west
unit :sludge, 459, 0, :west
unit :thick_sludge, 461, 0, :west
unit :thick_sludge, 462, 0, :west
unit :sludge, 468, 0, :west
unit :thick_sludge, 493, 0, :west
unit :sludge, 495, 0, :west
unit :sludge, 497, 0, :west
unit :wizard, 506, 0, :west
unit :captive, 509, 0, :west
unit :captive, 515, 0, :west
unit :archer, 516, 0, :west
unit :wizard, 519, 0, :west
unit :thick_sludge, 523, 0, :west
unit :captive, 530, 0, :west
unit :sludge, 531, 0, :west
unit :wizard, 535, 0, :west
unit :thick_sludge, 543, 0, :west
unit :thick_sludge, 544, 0, :west
unit :sludge, 547, 0, :west
unit :wizard, 550, 0, :west
unit :thick_sludge, 552, 0, :west
unit :sludge, 553, 0, :west
unit :thick_sludge, 554, 0, :west
unit :wizard, 556, 0, :west
unit :sludge, 558, 0, :west
unit :thick_sludge, 559, 0, :west
unit :wizard, 561, 0, :west
unit :archer, 565, 0, :west
unit :sludge, 569, 0, :west
unit :archer, 572, 0, :west
unit :archer, 574, 0, :west
unit :archer, 575, 0, :west
unit :archer, 577, 0, :west
unit :sludge, 579, 0, :west
unit :captive, 585, 0, :west
unit :archer, 589, 0, :west
unit :wizard, 592, 0, :west
unit :thick_sludge, 593, 0, :west
unit :archer, 599, 0, :west
unit :archer, 602, 0, :west
