#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |s     w   aC      S  sa     w        a             Ca  s     a   S          a   C C     s    @   wS Sa   S               w             a a s C     s   w  S    s    sa  C aCS   CS  w   C a     w  s  w s   C        Cs  S      s  C   w   s   C    a a           C  a       s w  s  a   w        s C   aC SCs  s  s S  s  C    Ca           Ca  w    a     a      C   S a  C C s          wS          C  SC      > S a  S            S    ss      CSs w       S  a sC   s s       a      C  w      s    C w        a a        CsC       a      aCw     a  S C w    ss  s           a  SCa    S  s awS  SS  w w            w    SC sS S     S   S w |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 628
ace_score 3140
size 628, 1
stairs 402, 0

warrior 93, 0, :east

unit :sludge, 0, 0, :east
unit :wizard, 6, 0, :east
unit :archer, 10, 0, :east
unit :captive, 11, 0, :east
unit :thick_sludge, 18, 0, :east
unit :sludge, 21, 0, :east
unit :archer, 22, 0, :east
unit :wizard, 28, 0, :east
unit :archer, 37, 0, :east
unit :captive, 51, 0, :east
unit :archer, 52, 0, :east
unit :sludge, 55, 0, :east
unit :archer, 61, 0, :east
unit :thick_sludge, 65, 0, :east
unit :archer, 76, 0, :east
unit :captive, 80, 0, :east
unit :captive, 82, 0, :east
unit :sludge, 88, 0, :east
unit :wizard, 97, 0, :west
unit :thick_sludge, 98, 0, :west
unit :thick_sludge, 100, 0, :west
unit :archer, 101, 0, :west
unit :thick_sludge, 105, 0, :west
unit :wizard, 121, 0, :west
unit :archer, 135, 0, :west
unit :archer, 137, 0, :west
unit :sludge, 139, 0, :west
unit :captive, 141, 0, :west
unit :sludge, 147, 0, :west
unit :wizard, 151, 0, :west
unit :thick_sludge, 154, 0, :west
unit :sludge, 159, 0, :west
unit :sludge, 164, 0, :west
unit :archer, 165, 0, :west
unit :captive, 168, 0, :west
unit :archer, 170, 0, :west
unit :captive, 171, 0, :west
unit :thick_sludge, 172, 0, :west
unit :captive, 176, 0, :west
unit :thick_sludge, 177, 0, :west
unit :wizard, 180, 0, :west
unit :captive, 184, 0, :west
unit :archer, 186, 0, :west
unit :wizard, 192, 0, :west
unit :sludge, 195, 0, :west
unit :wizard, 198, 0, :west
unit :sludge, 200, 0, :west
unit :captive, 204, 0, :west
unit :captive, 213, 0, :west
unit :sludge, 214, 0, :west
unit :thick_sludge, 217, 0, :west
unit :sludge, 224, 0, :west
unit :captive, 227, 0, :west
unit :wizard, 231, 0, :west
unit :sludge, 235, 0, :west
unit :captive, 239, 0, :west
unit :archer, 244, 0, :west
unit :archer, 246, 0, :west
unit :captive, 258, 0, :west
unit :archer, 261, 0, :west
unit :sludge, 269, 0, :west
unit :wizard, 271, 0, :west
unit :sludge, 274, 0, :west
unit :archer, 277, 0, :west
unit :wizard, 281, 0, :west
unit :sludge, 290, 0, :west
unit :captive, 292, 0, :west
unit :archer, 296, 0, :west
unit :captive, 297, 0, :west
unit :thick_sludge, 299, 0, :west
unit :captive, 300, 0, :west
unit :sludge, 301, 0, :west
unit :sludge, 304, 0, :west
unit :sludge, 307, 0, :west
unit :thick_sludge, 309, 0, :west
unit :sludge, 312, 0, :west
unit :captive, 315, 0, :west
unit :captive, 320, 0, :west
unit :archer, 321, 0, :west
unit :captive, 333, 0, :west
unit :archer, 334, 0, :west
unit :wizard, 337, 0, :west
unit :archer, 342, 0, :west
unit :archer, 348, 0, :west
unit :captive, 355, 0, :west
unit :thick_sludge, 359, 0, :west
unit :archer, 361, 0, :west
unit :captive, 364, 0, :west
unit :captive, 366, 0, :west
unit :sludge, 368, 0, :west
unit :wizard, 379, 0, :west
unit :thick_sludge, 380, 0, :west
unit :captive, 391, 0, :west
unit :thick_sludge, 394, 0, :west
unit :captive, 395, 0, :west
unit :thick_sludge, 404, 0, :west
unit :archer, 406, 0, :west
unit :thick_sludge, 409, 0, :west
unit :thick_sludge, 422, 0, :west
unit :sludge, 427, 0, :west
unit :sludge, 428, 0, :west
unit :captive, 435, 0, :west
unit :thick_sludge, 436, 0, :west
unit :sludge, 437, 0, :west
unit :wizard, 439, 0, :west
unit :thick_sludge, 447, 0, :west
unit :archer, 450, 0, :west
unit :sludge, 452, 0, :west
unit :captive, 453, 0, :west
unit :sludge, 457, 0, :west
unit :sludge, 459, 0, :west
unit :archer, 467, 0, :west
unit :captive, 474, 0, :west
unit :wizard, 477, 0, :west
unit :sludge, 484, 0, :west
unit :captive, 489, 0, :west
unit :wizard, 491, 0, :west
unit :archer, 500, 0, :west
unit :archer, 502, 0, :west
unit :captive, 511, 0, :west
unit :sludge, 512, 0, :west
unit :captive, 513, 0, :west
unit :archer, 521, 0, :west
unit :archer, 528, 0, :west
unit :captive, 529, 0, :west
unit :wizard, 530, 0, :west
unit :archer, 536, 0, :west
unit :thick_sludge, 539, 0, :west
unit :captive, 541, 0, :west
unit :wizard, 543, 0, :west
unit :sludge, 548, 0, :west
unit :sludge, 549, 0, :west
unit :sludge, 552, 0, :west
unit :archer, 564, 0, :west
unit :thick_sludge, 567, 0, :west
unit :captive, 568, 0, :west
unit :archer, 569, 0, :west
unit :thick_sludge, 574, 0, :west
unit :sludge, 577, 0, :west
unit :archer, 579, 0, :west
unit :wizard, 580, 0, :west
unit :thick_sludge, 581, 0, :west
unit :thick_sludge, 584, 0, :west
unit :thick_sludge, 585, 0, :west
unit :wizard, 588, 0, :west
unit :wizard, 590, 0, :west
unit :wizard, 603, 0, :west
unit :thick_sludge, 608, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 611, 0, :west
unit :thick_sludge, 612, 0, :west
unit :thick_sludge, 614, 0, :west
unit :thick_sludge, 620, 0, :west
unit :thick_sludge, 624, 0, :west
unit :wizard, 626, 0, :west
