#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |                S  a  a  C        a       s       S       S   C  sS          s w     sw    S    a       S S w      C   a s       w w   s           s         a w C   S   s  w  C Sws Ss    S  C s  aw                  w     w    s     a        C  w a  S C   sC  aa       wS        S   wsCaa  S    C s w        a   S  sS  aw       a s aw s    C    s     Cw a   S a   @  a s  S   CS  SC s    w     a        S     w S S Sa a   S w        w      as   S              s a  C   S    >    w  S      a    C   C    w    C CS  a SS  w  a s  aSCs  C a      a S s wC   w                 C     ss a   S  a  a           w  w  |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 608
ace_score 3040
size 608, 1
stairs 473, 0

warrior 363, 0, :east

unit :thick_sludge, 16, 0, :east
unit :archer, 19, 0, :east
unit :archer, 22, 0, :east
unit :captive, 25, 0, :east
unit :archer, 34, 0, :east
unit :sludge, 42, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 58, 0, :east
unit :captive, 62, 0, :east
unit :sludge, 65, 0, :east
unit :thick_sludge, 66, 0, :east
unit :sludge, 77, 0, :east
unit :wizard, 79, 0, :east
unit :sludge, 85, 0, :east
unit :wizard, 86, 0, :east
unit :thick_sludge, 91, 0, :east
unit :archer, 96, 0, :east
unit :thick_sludge, 104, 0, :east
unit :thick_sludge, 106, 0, :east
unit :wizard, 108, 0, :east
unit :captive, 115, 0, :east
unit :archer, 119, 0, :east
unit :sludge, 121, 0, :east
unit :wizard, 129, 0, :east
unit :wizard, 131, 0, :east
unit :sludge, 135, 0, :east
unit :sludge, 147, 0, :east
unit :archer, 157, 0, :east
unit :wizard, 159, 0, :east
unit :captive, 161, 0, :east
unit :thick_sludge, 165, 0, :east
unit :sludge, 169, 0, :east
unit :wizard, 172, 0, :east
unit :captive, 175, 0, :east
unit :thick_sludge, 177, 0, :east
unit :wizard, 178, 0, :east
unit :sludge, 179, 0, :east
unit :thick_sludge, 181, 0, :east
unit :sludge, 182, 0, :east
unit :thick_sludge, 187, 0, :east
unit :captive, 190, 0, :east
unit :sludge, 192, 0, :east
unit :archer, 195, 0, :east
unit :wizard, 196, 0, :east
unit :wizard, 215, 0, :east
unit :wizard, 221, 0, :east
unit :sludge, 226, 0, :east
unit :archer, 232, 0, :east
unit :captive, 241, 0, :east
unit :wizard, 244, 0, :east
unit :archer, 246, 0, :east
unit :thick_sludge, 249, 0, :east
unit :captive, 251, 0, :east
unit :sludge, 255, 0, :east
unit :captive, 256, 0, :east
unit :archer, 259, 0, :east
unit :archer, 260, 0, :east
unit :wizard, 268, 0, :east
unit :thick_sludge, 269, 0, :east
unit :thick_sludge, 278, 0, :east
unit :wizard, 282, 0, :east
unit :sludge, 283, 0, :east
unit :captive, 284, 0, :east
unit :archer, 285, 0, :east
unit :archer, 286, 0, :east
unit :thick_sludge, 289, 0, :east
unit :captive, 294, 0, :east
unit :sludge, 296, 0, :east
unit :wizard, 298, 0, :east
unit :archer, 307, 0, :east
unit :thick_sludge, 311, 0, :east
unit :sludge, 314, 0, :east
unit :thick_sludge, 315, 0, :east
unit :archer, 318, 0, :east
unit :wizard, 319, 0, :east
unit :archer, 327, 0, :east
unit :sludge, 329, 0, :east
unit :archer, 331, 0, :east
unit :wizard, 332, 0, :east
unit :sludge, 334, 0, :east
unit :captive, 339, 0, :east
unit :sludge, 344, 0, :east
unit :captive, 350, 0, :east
unit :wizard, 351, 0, :east
unit :archer, 353, 0, :east
unit :thick_sludge, 357, 0, :east
unit :archer, 359, 0, :east
unit :archer, 366, 0, :west
unit :sludge, 368, 0, :west
unit :thick_sludge, 371, 0, :west
unit :captive, 375, 0, :west
unit :thick_sludge, 376, 0, :west
unit :thick_sludge, 379, 0, :west
unit :captive, 380, 0, :west
unit :sludge, 382, 0, :west
unit :wizard, 387, 0, :west
unit :archer, 393, 0, :west
unit :thick_sludge, 402, 0, :west
unit :wizard, 408, 0, :west
unit :thick_sludge, 410, 0, :west
unit :thick_sludge, 412, 0, :west
unit :thick_sludge, 414, 0, :west
unit :archer, 415, 0, :west
unit :archer, 417, 0, :west
unit :thick_sludge, 421, 0, :west
unit :wizard, 423, 0, :west
unit :wizard, 432, 0, :west
unit :archer, 439, 0, :west
unit :sludge, 440, 0, :west
unit :thick_sludge, 444, 0, :west
unit :sludge, 459, 0, :west
unit :archer, 461, 0, :west
unit :captive, 464, 0, :west
unit :thick_sludge, 468, 0, :west
unit :wizard, 478, 0, :west
unit :thick_sludge, 481, 0, :west
unit :archer, 488, 0, :west
unit :captive, 493, 0, :west
unit :captive, 497, 0, :west
unit :wizard, 502, 0, :west
unit :captive, 507, 0, :west
unit :captive, 509, 0, :west
unit :thick_sludge, 510, 0, :west
unit :archer, 513, 0, :west
unit :thick_sludge, 515, 0, :west
unit :thick_sludge, 516, 0, :west
unit :wizard, 519, 0, :west
unit :archer, 522, 0, :west
unit :sludge, 524, 0, :west
unit :archer, 527, 0, :west
unit :thick_sludge, 528, 0, :west
unit :captive, 529, 0, :west
unit :sludge, 530, 0, :west
unit :captive, 533, 0, :west
unit :archer, 535, 0, :west
unit :archer, 542, 0, :west
unit :thick_sludge, 544, 0, :west
unit :sludge, 546, 0, :west
unit :wizard, 548, 0, :west
unit :captive, 549, 0, :west
unit :wizard, 553, 0, :west
unit :captive, 571, 0, :west
unit :sludge, 577, 0, :west
unit :sludge, 578, 0, :west
unit :archer, 580, 0, :west
unit :thick_sludge, 584, 0, :west
unit :archer, 587, 0, :west
unit :archer, 590, 0, :west
unit :wizard, 602, 0, :west
unit :wizard, 605, 0, :west
