#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       w  a   CS S   a a a  w   s    s w    C   s      s  S aw          C     C Ss             C    s    C   s      w  C  Ca   S a a S a         S       S S  s  C w     w s    C S  C   aS s    S     s     S S      a  s  @          a    sa a    a w w    a a   w S   a   sS        S   C  w   a w  S             w     a      awS aw         S     sC   aS  SSs       w   S a                 w             S  s  S   s Cs   S s    Ss   C    SC C     s       w     Ss   w a     CS     C sw  sa    CC    s                     sa s   CC   sC wa       sa         s   S     S       s       a  S   C w   s                           S  w ssCC S  C   S     a s      a           s   w   SS S        C s   s     S  C     S      w  s       s    C s a  as  S       s     C  s   w s   a    S   a w> S  w  S    s     aC  s        w ss    ss  SC  s  C           a  CC  a      sS     C  w   S     S a      S      S   s sC CS           C    C  SSa  s Cs     sSa  C a   SC s       SSC  a|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 962
ace_score 4810
size 962, 1
stairs 777, 0

warrior 220, 0, :east

unit :wizard, 7, 0, :east
unit :archer, 10, 0, :east
unit :captive, 14, 0, :east
unit :thick_sludge, 15, 0, :east
unit :thick_sludge, 17, 0, :east
unit :archer, 21, 0, :east
unit :archer, 23, 0, :east
unit :archer, 25, 0, :east
unit :wizard, 28, 0, :east
unit :sludge, 32, 0, :east
unit :sludge, 37, 0, :east
unit :wizard, 39, 0, :east
unit :captive, 44, 0, :east
unit :sludge, 48, 0, :east
unit :sludge, 55, 0, :east
unit :thick_sludge, 58, 0, :east
unit :archer, 60, 0, :east
unit :wizard, 61, 0, :east
unit :captive, 72, 0, :east
unit :captive, 78, 0, :east
unit :thick_sludge, 80, 0, :east
unit :sludge, 81, 0, :east
unit :captive, 95, 0, :east
unit :sludge, 100, 0, :east
unit :captive, 105, 0, :east
unit :sludge, 109, 0, :east
unit :wizard, 116, 0, :east
unit :captive, 119, 0, :east
unit :captive, 122, 0, :east
unit :archer, 123, 0, :east
unit :thick_sludge, 127, 0, :east
unit :archer, 129, 0, :east
unit :archer, 131, 0, :east
unit :thick_sludge, 133, 0, :east
unit :archer, 135, 0, :east
unit :thick_sludge, 145, 0, :east
unit :thick_sludge, 153, 0, :east
unit :thick_sludge, 155, 0, :east
unit :sludge, 158, 0, :east
unit :captive, 161, 0, :east
unit :wizard, 163, 0, :east
unit :wizard, 169, 0, :east
unit :sludge, 171, 0, :east
unit :captive, 176, 0, :east
unit :thick_sludge, 178, 0, :east
unit :captive, 181, 0, :east
unit :archer, 185, 0, :east
unit :thick_sludge, 186, 0, :east
unit :sludge, 188, 0, :east
unit :thick_sludge, 193, 0, :east
unit :sludge, 199, 0, :east
unit :thick_sludge, 205, 0, :east
unit :thick_sludge, 207, 0, :east
unit :archer, 214, 0, :east
unit :sludge, 217, 0, :east
unit :archer, 231, 0, :west
unit :sludge, 236, 0, :west
unit :archer, 237, 0, :west
unit :archer, 239, 0, :west
unit :archer, 244, 0, :west
unit :wizard, 246, 0, :west
unit :wizard, 248, 0, :west
unit :archer, 253, 0, :west
unit :archer, 255, 0, :west
unit :wizard, 259, 0, :west
unit :thick_sludge, 261, 0, :west
unit :archer, 265, 0, :west
unit :sludge, 269, 0, :west
unit :thick_sludge, 270, 0, :west
unit :thick_sludge, 279, 0, :west
unit :captive, 283, 0, :west
unit :wizard, 286, 0, :west
unit :archer, 290, 0, :west
unit :wizard, 292, 0, :west
unit :thick_sludge, 295, 0, :west
unit :wizard, 309, 0, :west
unit :archer, 315, 0, :west
unit :archer, 322, 0, :west
unit :wizard, 323, 0, :west
unit :thick_sludge, 324, 0, :west
unit :archer, 326, 0, :west
unit :wizard, 327, 0, :west
unit :thick_sludge, 337, 0, :west
unit :sludge, 343, 0, :west
unit :captive, 344, 0, :west
unit :archer, 348, 0, :west
unit :thick_sludge, 349, 0, :west
unit :thick_sludge, 352, 0, :west
unit :thick_sludge, 353, 0, :west
unit :sludge, 354, 0, :west
unit :wizard, 362, 0, :west
unit :thick_sludge, 366, 0, :west
unit :archer, 368, 0, :west
unit :wizard, 386, 0, :west
unit :thick_sludge, 400, 0, :west
unit :sludge, 403, 0, :west
unit :thick_sludge, 406, 0, :west
unit :sludge, 410, 0, :west
unit :captive, 412, 0, :west
unit :sludge, 413, 0, :west
unit :thick_sludge, 417, 0, :west
unit :sludge, 419, 0, :west
unit :thick_sludge, 424, 0, :west
unit :sludge, 425, 0, :west
unit :captive, 429, 0, :west
unit :thick_sludge, 434, 0, :west
unit :captive, 435, 0, :west
unit :captive, 437, 0, :west
unit :sludge, 443, 0, :west
unit :wizard, 451, 0, :west
unit :thick_sludge, 457, 0, :west
unit :sludge, 458, 0, :west
unit :wizard, 462, 0, :west
unit :archer, 464, 0, :west
unit :captive, 470, 0, :west
unit :thick_sludge, 471, 0, :west
unit :captive, 477, 0, :west
unit :sludge, 479, 0, :west
unit :wizard, 480, 0, :west
unit :sludge, 483, 0, :west
unit :archer, 484, 0, :west
unit :captive, 489, 0, :west
unit :captive, 490, 0, :west
unit :sludge, 495, 0, :west
unit :sludge, 517, 0, :west
unit :archer, 518, 0, :west
unit :sludge, 520, 0, :west
unit :captive, 524, 0, :west
unit :captive, 525, 0, :west
unit :sludge, 529, 0, :west
unit :captive, 530, 0, :west
unit :wizard, 532, 0, :west
unit :archer, 533, 0, :west
unit :sludge, 541, 0, :west
unit :archer, 542, 0, :west
unit :sludge, 552, 0, :west
unit :thick_sludge, 556, 0, :west
unit :thick_sludge, 562, 0, :west
unit :sludge, 570, 0, :west
unit :archer, 578, 0, :west
unit :thick_sludge, 581, 0, :west
unit :captive, 585, 0, :west
unit :wizard, 587, 0, :west
unit :sludge, 591, 0, :west
unit :thick_sludge, 619, 0, :west
unit :wizard, 622, 0, :west
unit :sludge, 624, 0, :west
unit :sludge, 625, 0, :west
unit :captive, 626, 0, :west
unit :captive, 627, 0, :west
unit :thick_sludge, 629, 0, :west
unit :captive, 632, 0, :west
unit :thick_sludge, 636, 0, :west
unit :archer, 642, 0, :west
unit :sludge, 644, 0, :west
unit :archer, 651, 0, :west
unit :sludge, 663, 0, :west
unit :wizard, 667, 0, :west
unit :thick_sludge, 671, 0, :west
unit :thick_sludge, 672, 0, :west
unit :thick_sludge, 674, 0, :west
unit :captive, 683, 0, :west
unit :sludge, 685, 0, :west
unit :sludge, 689, 0, :west
unit :thick_sludge, 695, 0, :west
unit :captive, 698, 0, :west
unit :thick_sludge, 704, 0, :west
unit :wizard, 711, 0, :west
unit :sludge, 714, 0, :west
unit :sludge, 722, 0, :west
unit :captive, 727, 0, :west
unit :sludge, 729, 0, :west
unit :archer, 731, 0, :west
unit :archer, 734, 0, :west
unit :sludge, 735, 0, :west
unit :thick_sludge, 738, 0, :west
unit :sludge, 746, 0, :west
unit :captive, 752, 0, :west
unit :sludge, 755, 0, :west
unit :wizard, 759, 0, :west
unit :sludge, 761, 0, :west
unit :archer, 765, 0, :west
unit :thick_sludge, 770, 0, :west
unit :archer, 774, 0, :west
unit :wizard, 776, 0, :west
unit :thick_sludge, 779, 0, :west
unit :wizard, 782, 0, :west
unit :thick_sludge, 785, 0, :west
unit :sludge, 790, 0, :west
unit :archer, 796, 0, :west
unit :captive, 797, 0, :west
unit :sludge, 800, 0, :west
unit :wizard, 809, 0, :west
unit :sludge, 811, 0, :west
unit :sludge, 812, 0, :west
unit :sludge, 817, 0, :west
unit :sludge, 818, 0, :west
unit :thick_sludge, 821, 0, :west
unit :captive, 822, 0, :west
unit :sludge, 825, 0, :west
unit :captive, 828, 0, :west
unit :archer, 840, 0, :west
unit :captive, 843, 0, :west
unit :captive, 844, 0, :west
unit :archer, 847, 0, :west
unit :sludge, 854, 0, :west
unit :thick_sludge, 855, 0, :west
unit :captive, 861, 0, :west
unit :wizard, 864, 0, :west
unit :thick_sludge, 868, 0, :west
unit :thick_sludge, 874, 0, :west
unit :archer, 876, 0, :west
unit :thick_sludge, 883, 0, :west
unit :thick_sludge, 890, 0, :west
unit :sludge, 894, 0, :west
unit :sludge, 896, 0, :west
unit :captive, 897, 0, :west
unit :captive, 899, 0, :west
unit :thick_sludge, 900, 0, :west
unit :captive, 912, 0, :west
unit :captive, 917, 0, :west
unit :thick_sludge, 920, 0, :west
unit :thick_sludge, 921, 0, :west
unit :archer, 922, 0, :west
unit :sludge, 925, 0, :west
unit :captive, 927, 0, :west
unit :sludge, 928, 0, :west
unit :sludge, 934, 0, :west
unit :thick_sludge, 935, 0, :west
unit :archer, 936, 0, :west
unit :captive, 939, 0, :west
unit :archer, 941, 0, :west
unit :thick_sludge, 945, 0, :west
unit :captive, 946, 0, :west
unit :sludge, 948, 0, :west
unit :thick_sludge, 956, 0, :west
unit :thick_sludge, 957, 0, :west
unit :captive, 958, 0, :west
unit :archer, 961, 0, :west
