#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C  a s     a aas   w   w    a s           wa C     sS  a  a    s       a> s    w    as     CSw   CaC      a  C                   S  Cs a     Cw            S  sC     a                 S  C a CS   a  s  S       swS   Sa   a   S   awas    aC as     wa S  s  s a  S    S s  s    w C w     sa          C  C   S     C   a a   S           w   s      C     C         aa  S   a      S   S       CCw s        w      C  sa        w  w                S   wss      a     C    a w wCw S   w      w  a   S   s     s  C  s  C    aS   w                  C C       C      s  s         w    as    S Sa   SS          w aS      s    w        a   w  sa    C a      a  w  a  C sa    w         @     S  a S    C   S w                       w  C  C   S    C  s   aCw   awC a  C   w w  a s  aws s wswss      s       a         S  S             C  a      w w  aCs             a  sasC  Ca  s    S C      C   a   S   a  a           SC a   w C  a  C      C  aS s          aw CS  S       C C|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 961
ace_score 4805
size 961, 1
stairs 74, 0

warrior 672, 0, :east

unit :captive, 2, 0, :east
unit :archer, 5, 0, :east
unit :sludge, 7, 0, :east
unit :archer, 13, 0, :east
unit :archer, 15, 0, :east
unit :archer, 16, 0, :east
unit :sludge, 17, 0, :east
unit :wizard, 21, 0, :east
unit :wizard, 25, 0, :east
unit :archer, 30, 0, :east
unit :sludge, 32, 0, :east
unit :wizard, 44, 0, :east
unit :archer, 45, 0, :east
unit :captive, 47, 0, :east
unit :sludge, 53, 0, :east
unit :thick_sludge, 54, 0, :east
unit :archer, 57, 0, :east
unit :archer, 60, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 73, 0, :east
unit :sludge, 76, 0, :east
unit :wizard, 81, 0, :east
unit :archer, 86, 0, :east
unit :sludge, 87, 0, :east
unit :captive, 93, 0, :east
unit :thick_sludge, 94, 0, :east
unit :wizard, 95, 0, :east
unit :captive, 99, 0, :east
unit :archer, 100, 0, :east
unit :captive, 101, 0, :east
unit :archer, 108, 0, :east
unit :captive, 111, 0, :east
unit :thick_sludge, 131, 0, :east
unit :captive, 134, 0, :east
unit :sludge, 135, 0, :east
unit :archer, 137, 0, :east
unit :captive, 143, 0, :east
unit :wizard, 144, 0, :east
unit :thick_sludge, 157, 0, :east
unit :sludge, 160, 0, :east
unit :captive, 161, 0, :east
unit :archer, 167, 0, :east
unit :thick_sludge, 185, 0, :east
unit :captive, 188, 0, :east
unit :archer, 190, 0, :east
unit :captive, 192, 0, :east
unit :thick_sludge, 193, 0, :east
unit :archer, 197, 0, :east
unit :sludge, 200, 0, :east
unit :thick_sludge, 203, 0, :east
unit :sludge, 211, 0, :east
unit :wizard, 212, 0, :east
unit :thick_sludge, 213, 0, :east
unit :thick_sludge, 217, 0, :east
unit :archer, 218, 0, :east
unit :archer, 222, 0, :east
unit :thick_sludge, 226, 0, :east
unit :archer, 230, 0, :east
unit :wizard, 231, 0, :east
unit :archer, 232, 0, :east
unit :sludge, 233, 0, :east
unit :archer, 238, 0, :east
unit :captive, 239, 0, :east
unit :archer, 241, 0, :east
unit :sludge, 242, 0, :east
unit :wizard, 248, 0, :east
unit :archer, 249, 0, :east
unit :thick_sludge, 251, 0, :east
unit :sludge, 254, 0, :east
unit :sludge, 257, 0, :east
unit :archer, 259, 0, :east
unit :thick_sludge, 262, 0, :east
unit :thick_sludge, 267, 0, :east
unit :sludge, 269, 0, :east
unit :sludge, 272, 0, :east
unit :wizard, 277, 0, :east
unit :captive, 279, 0, :east
unit :wizard, 281, 0, :east
unit :sludge, 287, 0, :east
unit :archer, 288, 0, :east
unit :captive, 299, 0, :east
unit :captive, 302, 0, :east
unit :thick_sludge, 306, 0, :east
unit :captive, 312, 0, :east
unit :archer, 316, 0, :east
unit :archer, 318, 0, :east
unit :thick_sludge, 322, 0, :east
unit :wizard, 334, 0, :east
unit :sludge, 338, 0, :east
unit :captive, 345, 0, :east
unit :captive, 351, 0, :east
unit :archer, 361, 0, :east
unit :archer, 362, 0, :east
unit :thick_sludge, 365, 0, :east
unit :archer, 369, 0, :east
unit :thick_sludge, 376, 0, :east
unit :thick_sludge, 380, 0, :east
unit :captive, 388, 0, :east
unit :captive, 389, 0, :east
unit :wizard, 390, 0, :east
unit :sludge, 392, 0, :east
unit :wizard, 401, 0, :east
unit :captive, 408, 0, :east
unit :sludge, 411, 0, :east
unit :archer, 412, 0, :east
unit :wizard, 421, 0, :east
unit :wizard, 424, 0, :east
unit :thick_sludge, 441, 0, :east
unit :wizard, 445, 0, :east
unit :sludge, 446, 0, :east
unit :sludge, 447, 0, :east
unit :archer, 454, 0, :east
unit :captive, 460, 0, :east
unit :archer, 465, 0, :east
unit :wizard, 467, 0, :east
unit :wizard, 469, 0, :east
unit :captive, 470, 0, :east
unit :wizard, 471, 0, :east
unit :thick_sludge, 473, 0, :east
unit :wizard, 477, 0, :east
unit :wizard, 484, 0, :east
unit :archer, 487, 0, :east
unit :thick_sludge, 491, 0, :east
unit :sludge, 495, 0, :east
unit :sludge, 501, 0, :east
unit :captive, 504, 0, :east
unit :sludge, 507, 0, :east
unit :captive, 510, 0, :east
unit :archer, 515, 0, :east
unit :thick_sludge, 516, 0, :east
unit :wizard, 520, 0, :east
unit :captive, 539, 0, :east
unit :captive, 541, 0, :east
unit :captive, 549, 0, :east
unit :sludge, 556, 0, :east
unit :sludge, 559, 0, :east
unit :wizard, 569, 0, :east
unit :archer, 574, 0, :east
unit :sludge, 575, 0, :east
unit :thick_sludge, 580, 0, :east
unit :thick_sludge, 582, 0, :east
unit :archer, 583, 0, :east
unit :thick_sludge, 587, 0, :east
unit :thick_sludge, 588, 0, :east
unit :wizard, 599, 0, :east
unit :archer, 601, 0, :east
unit :thick_sludge, 602, 0, :east
unit :sludge, 609, 0, :east
unit :wizard, 614, 0, :east
unit :archer, 623, 0, :east
unit :wizard, 627, 0, :east
unit :sludge, 630, 0, :east
unit :archer, 631, 0, :east
unit :captive, 636, 0, :east
unit :archer, 638, 0, :east
unit :archer, 645, 0, :east
unit :wizard, 648, 0, :east
unit :archer, 651, 0, :east
unit :captive, 654, 0, :east
unit :sludge, 656, 0, :east
unit :archer, 657, 0, :east
unit :wizard, 662, 0, :east
unit :thick_sludge, 678, 0, :west
unit :archer, 681, 0, :west
unit :thick_sludge, 683, 0, :west
unit :captive, 688, 0, :west
unit :thick_sludge, 692, 0, :west
unit :wizard, 694, 0, :west
unit :wizard, 718, 0, :west
unit :captive, 721, 0, :west
unit :captive, 724, 0, :west
unit :thick_sludge, 728, 0, :west
unit :captive, 733, 0, :west
unit :sludge, 736, 0, :west
unit :archer, 740, 0, :west
unit :captive, 741, 0, :west
unit :wizard, 742, 0, :west
unit :archer, 746, 0, :west
unit :wizard, 747, 0, :west
unit :captive, 748, 0, :west
unit :archer, 750, 0, :west
unit :captive, 753, 0, :west
unit :wizard, 757, 0, :west
unit :wizard, 759, 0, :west
unit :archer, 762, 0, :west
unit :sludge, 764, 0, :west
unit :archer, 767, 0, :west
unit :wizard, 768, 0, :west
unit :sludge, 769, 0, :west
unit :sludge, 771, 0, :west
unit :wizard, 773, 0, :west
unit :sludge, 774, 0, :west
unit :wizard, 775, 0, :west
unit :sludge, 776, 0, :west
unit :sludge, 777, 0, :west
unit :sludge, 784, 0, :west
unit :archer, 792, 0, :west
unit :thick_sludge, 802, 0, :west
unit :thick_sludge, 805, 0, :west
unit :captive, 819, 0, :west
unit :archer, 822, 0, :west
unit :wizard, 829, 0, :west
unit :wizard, 831, 0, :west
unit :archer, 834, 0, :west
unit :captive, 835, 0, :west
unit :sludge, 836, 0, :west
unit :archer, 850, 0, :west
unit :sludge, 853, 0, :west
unit :archer, 854, 0, :west
unit :sludge, 855, 0, :west
unit :captive, 856, 0, :west
unit :captive, 859, 0, :west
unit :archer, 860, 0, :west
unit :sludge, 863, 0, :west
unit :thick_sludge, 868, 0, :west
unit :captive, 870, 0, :west
unit :captive, 877, 0, :west
unit :archer, 881, 0, :west
unit :thick_sludge, 885, 0, :west
unit :archer, 889, 0, :west
unit :archer, 892, 0, :west
unit :thick_sludge, 904, 0, :west
unit :captive, 905, 0, :west
unit :archer, 907, 0, :west
unit :wizard, 911, 0, :west
unit :captive, 913, 0, :west
unit :archer, 916, 0, :west
unit :captive, 919, 0, :west
unit :captive, 926, 0, :west
unit :archer, 929, 0, :west
unit :thick_sludge, 930, 0, :west
unit :sludge, 932, 0, :west
unit :archer, 943, 0, :west
unit :wizard, 944, 0, :west
unit :captive, 946, 0, :west
unit :thick_sludge, 947, 0, :west
unit :thick_sludge, 950, 0, :west
unit :captive, 958, 0, :west
unit :captive, 960, 0, :west
