#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     a S    s s S w      w   a    S SS    SS  a   S S   a C a   wa   S    C     C  w    w    aS     s         Ca      S  ss S a  S   C    s  a     S  w S  s        S  S  S w w      s    CaC  wC  s             CC    Cw      SS   S wa    C CC CC C  as  C S         C       S  a       w   a        s   s C    > Ca     sS               S       a     C   sC sa            w    C S             aS  w     aC    s  a    C          w      s         S       s     sC     wasC   C    s SC   Ss            s  S     C   CSaaCa         a   s   w a w C    sCS w   s S    Cs     S   s  aC  s           S    C            w  C         C  C    S    aS   S         S  aw sC   s       S            w    a  S S C  C       s S C      s C  S  s    Ss    CS     S    a     s w     C   a S s        w  s          S  CC  s C S w s  w     a  C   w SS w a   a                          C       w  C a   a  s    @         S   a    S   C a     w  a  s   S s  CS   S          C  w  CS  a     C S  C   S  S   a   a s   CS    S  aS|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 996
ace_score 4980
size 996, 1
stairs 306, 0

warrior 881, 0, :east

unit :archer, 5, 0, :east
unit :thick_sludge, 7, 0, :east
unit :sludge, 12, 0, :east
unit :sludge, 14, 0, :east
unit :thick_sludge, 16, 0, :east
unit :wizard, 18, 0, :east
unit :wizard, 25, 0, :east
unit :archer, 29, 0, :east
unit :thick_sludge, 34, 0, :east
unit :thick_sludge, 36, 0, :east
unit :thick_sludge, 37, 0, :east
unit :thick_sludge, 42, 0, :east
unit :thick_sludge, 43, 0, :east
unit :archer, 46, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 52, 0, :east
unit :archer, 56, 0, :east
unit :captive, 58, 0, :east
unit :archer, 60, 0, :east
unit :wizard, 64, 0, :east
unit :archer, 65, 0, :east
unit :thick_sludge, 69, 0, :east
unit :captive, 74, 0, :east
unit :captive, 80, 0, :east
unit :wizard, 83, 0, :east
unit :wizard, 88, 0, :east
unit :archer, 93, 0, :east
unit :thick_sludge, 94, 0, :east
unit :sludge, 100, 0, :east
unit :captive, 110, 0, :east
unit :archer, 111, 0, :east
unit :thick_sludge, 118, 0, :east
unit :sludge, 121, 0, :east
unit :sludge, 122, 0, :east
unit :thick_sludge, 124, 0, :east
unit :archer, 126, 0, :east
unit :thick_sludge, 129, 0, :east
unit :captive, 133, 0, :east
unit :sludge, 138, 0, :east
unit :archer, 141, 0, :east
unit :thick_sludge, 147, 0, :east
unit :wizard, 150, 0, :east
unit :thick_sludge, 152, 0, :east
unit :sludge, 155, 0, :east
unit :thick_sludge, 164, 0, :east
unit :thick_sludge, 167, 0, :east
unit :thick_sludge, 170, 0, :east
unit :wizard, 172, 0, :east
unit :wizard, 174, 0, :east
unit :sludge, 181, 0, :east
unit :captive, 186, 0, :east
unit :archer, 187, 0, :east
unit :captive, 188, 0, :east
unit :wizard, 191, 0, :east
unit :captive, 192, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 209, 0, :east
unit :captive, 210, 0, :east
unit :captive, 215, 0, :east
unit :wizard, 216, 0, :east
unit :thick_sludge, 223, 0, :east
unit :thick_sludge, 224, 0, :east
unit :thick_sludge, 228, 0, :east
unit :wizard, 230, 0, :east
unit :archer, 231, 0, :east
unit :captive, 236, 0, :east
unit :captive, 238, 0, :east
unit :captive, 239, 0, :east
unit :captive, 241, 0, :east
unit :captive, 242, 0, :east
unit :captive, 244, 0, :east
unit :archer, 247, 0, :east
unit :sludge, 248, 0, :east
unit :captive, 251, 0, :east
unit :thick_sludge, 253, 0, :east
unit :captive, 263, 0, :east
unit :thick_sludge, 271, 0, :east
unit :archer, 274, 0, :east
unit :wizard, 282, 0, :east
unit :archer, 286, 0, :east
unit :sludge, 295, 0, :east
unit :sludge, 299, 0, :east
unit :captive, 301, 0, :east
unit :captive, 308, 0, :east
unit :archer, 309, 0, :east
unit :sludge, 315, 0, :east
unit :thick_sludge, 316, 0, :east
unit :thick_sludge, 332, 0, :east
unit :archer, 340, 0, :east
unit :captive, 346, 0, :east
unit :sludge, 350, 0, :east
unit :captive, 351, 0, :east
unit :sludge, 353, 0, :east
unit :archer, 354, 0, :east
unit :wizard, 367, 0, :east
unit :captive, 372, 0, :east
unit :thick_sludge, 374, 0, :east
unit :archer, 388, 0, :east
unit :thick_sludge, 389, 0, :east
unit :wizard, 392, 0, :east
unit :archer, 398, 0, :east
unit :captive, 399, 0, :east
unit :sludge, 404, 0, :east
unit :archer, 407, 0, :east
unit :captive, 412, 0, :east
unit :wizard, 423, 0, :east
unit :sludge, 430, 0, :east
unit :thick_sludge, 440, 0, :east
unit :sludge, 448, 0, :east
unit :sludge, 454, 0, :east
unit :captive, 455, 0, :east
unit :wizard, 461, 0, :east
unit :archer, 462, 0, :east
unit :sludge, 463, 0, :east
unit :captive, 464, 0, :east
unit :captive, 468, 0, :east
unit :sludge, 473, 0, :east
unit :thick_sludge, 475, 0, :east
unit :captive, 476, 0, :east
unit :thick_sludge, 480, 0, :east
unit :sludge, 481, 0, :east
unit :sludge, 494, 0, :east
unit :thick_sludge, 497, 0, :east
unit :captive, 503, 0, :east
unit :captive, 507, 0, :east
unit :thick_sludge, 508, 0, :east
unit :archer, 509, 0, :east
unit :archer, 510, 0, :east
unit :captive, 511, 0, :east
unit :archer, 512, 0, :east
unit :archer, 522, 0, :east
unit :sludge, 526, 0, :east
unit :wizard, 530, 0, :east
unit :archer, 532, 0, :east
unit :wizard, 534, 0, :east
unit :captive, 536, 0, :east
unit :sludge, 541, 0, :east
unit :captive, 542, 0, :east
unit :thick_sludge, 543, 0, :east
unit :wizard, 545, 0, :east
unit :sludge, 549, 0, :east
unit :thick_sludge, 551, 0, :east
unit :captive, 556, 0, :east
unit :sludge, 557, 0, :east
unit :thick_sludge, 563, 0, :east
unit :sludge, 567, 0, :east
unit :archer, 570, 0, :east
unit :captive, 571, 0, :east
unit :sludge, 574, 0, :east
unit :thick_sludge, 586, 0, :east
unit :captive, 591, 0, :east
unit :wizard, 604, 0, :east
unit :captive, 607, 0, :east
unit :captive, 617, 0, :east
unit :captive, 620, 0, :east
unit :thick_sludge, 625, 0, :east
unit :archer, 630, 0, :east
unit :thick_sludge, 631, 0, :east
unit :thick_sludge, 635, 0, :east
unit :thick_sludge, 645, 0, :east
unit :archer, 648, 0, :east
unit :wizard, 649, 0, :east
unit :sludge, 651, 0, :east
unit :captive, 652, 0, :east
unit :sludge, 656, 0, :east
unit :thick_sludge, 664, 0, :east
unit :wizard, 677, 0, :east
unit :archer, 682, 0, :east
unit :thick_sludge, 685, 0, :east
unit :thick_sludge, 687, 0, :east
unit :captive, 689, 0, :east
unit :captive, 692, 0, :east
unit :sludge, 700, 0, :east
unit :thick_sludge, 702, 0, :east
unit :captive, 704, 0, :east
unit :sludge, 711, 0, :east
unit :captive, 713, 0, :east
unit :thick_sludge, 716, 0, :east
unit :sludge, 719, 0, :east
unit :thick_sludge, 724, 0, :east
unit :sludge, 725, 0, :east
unit :captive, 730, 0, :east
unit :thick_sludge, 731, 0, :east
unit :thick_sludge, 737, 0, :east
unit :archer, 742, 0, :east
unit :sludge, 748, 0, :east
unit :wizard, 750, 0, :east
unit :captive, 756, 0, :east
unit :archer, 760, 0, :east
unit :thick_sludge, 762, 0, :east
unit :sludge, 764, 0, :east
unit :wizard, 773, 0, :east
unit :sludge, 776, 0, :east
unit :thick_sludge, 787, 0, :east
unit :captive, 790, 0, :east
unit :captive, 791, 0, :east
unit :sludge, 794, 0, :east
unit :captive, 796, 0, :east
unit :thick_sludge, 798, 0, :east
unit :wizard, 800, 0, :east
unit :sludge, 802, 0, :east
unit :wizard, 805, 0, :east
unit :archer, 811, 0, :east
unit :captive, 814, 0, :east
unit :wizard, 818, 0, :east
unit :thick_sludge, 820, 0, :east
unit :thick_sludge, 821, 0, :east
unit :wizard, 823, 0, :east
unit :archer, 825, 0, :east
unit :archer, 829, 0, :east
unit :captive, 856, 0, :east
unit :wizard, 864, 0, :east
unit :captive, 867, 0, :east
unit :archer, 869, 0, :east
unit :archer, 873, 0, :east
unit :sludge, 876, 0, :east
unit :thick_sludge, 891, 0, :west
unit :archer, 895, 0, :west
unit :thick_sludge, 900, 0, :west
unit :captive, 904, 0, :west
unit :archer, 906, 0, :west
unit :wizard, 912, 0, :west
unit :archer, 915, 0, :west
unit :sludge, 918, 0, :west
unit :thick_sludge, 922, 0, :west
unit :sludge, 924, 0, :west
unit :captive, 927, 0, :west
unit :thick_sludge, 928, 0, :west
unit :thick_sludge, 932, 0, :west
unit :captive, 943, 0, :west
unit :wizard, 946, 0, :west
unit :captive, 949, 0, :west
unit :thick_sludge, 950, 0, :west
unit :archer, 953, 0, :west
unit :captive, 959, 0, :west
unit :thick_sludge, 961, 0, :west
unit :captive, 964, 0, :west
unit :thick_sludge, 968, 0, :west
unit :thick_sludge, 971, 0, :west
unit :archer, 975, 0, :west
unit :archer, 979, 0, :west
unit :sludge, 981, 0, :west
unit :captive, 985, 0, :west
unit :thick_sludge, 986, 0, :west
unit :thick_sludge, 991, 0, :west
unit :archer, 994, 0, :west
unit :thick_sludge, 995, 0, :west
