#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s as S  Ss  s aS      C    S       w  w s C    s C     C S  C    a  aaC        s      S          wSC    s   s         a   s       a  w C     w         a     a  C   w       S  Ca   @  w       a        aC  w w        awa     C        C      a    a    a     s  CC S   S sw S w     w  S   a a S   C    a    S  w a  w         SC  s         Cs     Sa  w   w         a   ss Sa      S  C  w C w  CS      a  s w   C  w     s   > C     s a a      w       w    C  C     s a   s    S      C           C   sa w  CC    a C        S S       w  C  a        a           w  sS w  C     a a  a S  s as   S|
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 588
ace_score 2940
size 588, 1
stairs 420, 0

warrior 182, 0, :east

unit :sludge, 2, 0, :east
unit :archer, 4, 0, :east
unit :sludge, 5, 0, :east
unit :thick_sludge, 7, 0, :east
unit :thick_sludge, 10, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 14, 0, :east
unit :archer, 16, 0, :east
unit :thick_sludge, 17, 0, :east
unit :captive, 24, 0, :east
unit :thick_sludge, 29, 0, :east
unit :wizard, 37, 0, :east
unit :wizard, 40, 0, :east
unit :sludge, 42, 0, :east
unit :captive, 44, 0, :east
unit :sludge, 49, 0, :east
unit :captive, 51, 0, :east
unit :captive, 57, 0, :east
unit :thick_sludge, 59, 0, :east
unit :captive, 62, 0, :east
unit :archer, 67, 0, :east
unit :archer, 70, 0, :east
unit :archer, 71, 0, :east
unit :captive, 72, 0, :east
unit :sludge, 81, 0, :east
unit :thick_sludge, 88, 0, :east
unit :wizard, 99, 0, :east
unit :thick_sludge, 100, 0, :east
unit :captive, 101, 0, :east
unit :sludge, 106, 0, :east
unit :sludge, 110, 0, :east
unit :archer, 120, 0, :east
unit :sludge, 124, 0, :east
unit :archer, 132, 0, :east
unit :wizard, 135, 0, :east
unit :captive, 137, 0, :east
unit :wizard, 143, 0, :east
unit :archer, 153, 0, :east
unit :archer, 159, 0, :east
unit :captive, 162, 0, :east
unit :wizard, 166, 0, :east
unit :thick_sludge, 174, 0, :east
unit :captive, 177, 0, :east
unit :archer, 178, 0, :east
unit :wizard, 185, 0, :west
unit :archer, 193, 0, :west
unit :archer, 202, 0, :west
unit :captive, 203, 0, :west
unit :wizard, 206, 0, :west
unit :wizard, 208, 0, :west
unit :archer, 217, 0, :west
unit :wizard, 218, 0, :west
unit :archer, 219, 0, :west
unit :captive, 225, 0, :west
unit :captive, 234, 0, :west
unit :archer, 241, 0, :west
unit :archer, 246, 0, :west
unit :archer, 251, 0, :west
unit :sludge, 257, 0, :west
unit :captive, 260, 0, :west
unit :captive, 261, 0, :west
unit :thick_sludge, 263, 0, :west
unit :thick_sludge, 267, 0, :west
unit :sludge, 269, 0, :west
unit :wizard, 270, 0, :west
unit :thick_sludge, 272, 0, :west
unit :wizard, 274, 0, :west
unit :wizard, 280, 0, :west
unit :thick_sludge, 283, 0, :west
unit :archer, 287, 0, :west
unit :archer, 289, 0, :west
unit :thick_sludge, 291, 0, :west
unit :captive, 295, 0, :west
unit :archer, 300, 0, :west
unit :thick_sludge, 305, 0, :west
unit :wizard, 308, 0, :west
unit :archer, 310, 0, :west
unit :wizard, 313, 0, :west
unit :thick_sludge, 323, 0, :west
unit :captive, 324, 0, :west
unit :sludge, 327, 0, :west
unit :captive, 337, 0, :west
unit :sludge, 338, 0, :west
unit :thick_sludge, 344, 0, :west
unit :archer, 345, 0, :west
unit :wizard, 348, 0, :west
unit :wizard, 352, 0, :west
unit :archer, 362, 0, :west
unit :sludge, 366, 0, :west
unit :sludge, 367, 0, :west
unit :thick_sludge, 369, 0, :west
unit :archer, 370, 0, :west
unit :thick_sludge, 377, 0, :west
unit :captive, 380, 0, :west
unit :wizard, 383, 0, :west
unit :captive, 385, 0, :west
unit :wizard, 387, 0, :west
unit :captive, 390, 0, :west
unit :thick_sludge, 391, 0, :west
unit :archer, 398, 0, :west
unit :sludge, 401, 0, :west
unit :wizard, 403, 0, :west
unit :captive, 407, 0, :west
unit :wizard, 410, 0, :west
unit :sludge, 416, 0, :west
unit :captive, 422, 0, :west
unit :sludge, 428, 0, :west
unit :archer, 430, 0, :west
unit :archer, 432, 0, :west
unit :wizard, 439, 0, :west
unit :wizard, 447, 0, :west
unit :captive, 452, 0, :west
unit :captive, 455, 0, :west
unit :sludge, 461, 0, :west
unit :archer, 463, 0, :west
unit :sludge, 467, 0, :west
unit :thick_sludge, 472, 0, :west
unit :captive, 479, 0, :west
unit :captive, 491, 0, :west
unit :sludge, 495, 0, :west
unit :archer, 496, 0, :west
unit :wizard, 498, 0, :west
unit :captive, 501, 0, :west
unit :captive, 502, 0, :west
unit :archer, 507, 0, :west
unit :captive, 509, 0, :west
unit :thick_sludge, 518, 0, :west
unit :thick_sludge, 520, 0, :west
unit :wizard, 528, 0, :west
unit :captive, 531, 0, :west
unit :archer, 534, 0, :west
unit :archer, 543, 0, :west
unit :wizard, 555, 0, :west
unit :sludge, 558, 0, :west
unit :thick_sludge, 559, 0, :west
unit :wizard, 561, 0, :west
unit :captive, 564, 0, :west
unit :archer, 570, 0, :west
unit :archer, 572, 0, :west
unit :archer, 575, 0, :west
unit :thick_sludge, 577, 0, :west
unit :sludge, 580, 0, :west
unit :archer, 582, 0, :west
unit :sludge, 583, 0, :west
unit :thick_sludge, 587, 0, :west
