#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C s      S a     S   C          CC  a     w         SC     CC a       a     a S  w   ss a SSs      s  s      w     s         S       CS      s      s        S  w    a     Saa  s  a  w       a      aa            C C          s    w  w                 w wCw Cs       w      C    aw          sCa      s          w  w              S      C w  aaC      C      S w  C  S      wa ws aSw  S    aa   Sa    S   a   sC C  a S a   C s   s S   Sa  wS    w  a     Sa   s    C  s   wS         SS s       aa  S   S  S     a      a     a    S     s  s       C   S      S         s   C  Sw w C   w   C        a S        aa a C    C     w     S            sS            S C  w >w a       asa  ss  w   S  a  C a   w  @  a a   SC  SC w S   C      C   s  SwS s  a as     a wC  S s s a  w    w      C            S  a    a w   s   w   s   w  w   |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 822
ace_score 4110
size 822, 1
stairs 658, 0

warrior 697, 0, :east

unit :captive, 0, 0, :east
unit :sludge, 2, 0, :east
unit :thick_sludge, 9, 0, :east
unit :archer, 11, 0, :east
unit :thick_sludge, 17, 0, :east
unit :captive, 21, 0, :east
unit :captive, 32, 0, :east
unit :captive, 33, 0, :east
unit :archer, 36, 0, :east
unit :wizard, 42, 0, :east
unit :thick_sludge, 52, 0, :east
unit :captive, 53, 0, :east
unit :captive, 59, 0, :east
unit :captive, 60, 0, :east
unit :archer, 62, 0, :east
unit :archer, 70, 0, :east
unit :archer, 76, 0, :east
unit :thick_sludge, 78, 0, :east
unit :wizard, 81, 0, :east
unit :sludge, 85, 0, :east
unit :sludge, 86, 0, :east
unit :archer, 88, 0, :east
unit :thick_sludge, 90, 0, :east
unit :thick_sludge, 91, 0, :east
unit :sludge, 92, 0, :east
unit :sludge, 99, 0, :east
unit :sludge, 102, 0, :east
unit :wizard, 109, 0, :east
unit :sludge, 115, 0, :east
unit :thick_sludge, 125, 0, :east
unit :captive, 133, 0, :east
unit :thick_sludge, 134, 0, :east
unit :sludge, 141, 0, :east
unit :sludge, 148, 0, :east
unit :thick_sludge, 157, 0, :east
unit :wizard, 160, 0, :east
unit :archer, 165, 0, :east
unit :thick_sludge, 171, 0, :east
unit :archer, 172, 0, :east
unit :archer, 173, 0, :east
unit :sludge, 176, 0, :east
unit :archer, 179, 0, :east
unit :wizard, 182, 0, :east
unit :archer, 190, 0, :east
unit :archer, 197, 0, :east
unit :archer, 198, 0, :east
unit :captive, 211, 0, :east
unit :captive, 213, 0, :east
unit :sludge, 224, 0, :east
unit :wizard, 229, 0, :east
unit :wizard, 232, 0, :east
unit :wizard, 250, 0, :east
unit :wizard, 252, 0, :east
unit :captive, 253, 0, :east
unit :wizard, 254, 0, :east
unit :captive, 256, 0, :east
unit :sludge, 257, 0, :east
unit :wizard, 265, 0, :east
unit :captive, 272, 0, :east
unit :archer, 277, 0, :east
unit :wizard, 278, 0, :east
unit :sludge, 289, 0, :east
unit :captive, 290, 0, :east
unit :archer, 291, 0, :east
unit :sludge, 298, 0, :east
unit :wizard, 309, 0, :east
unit :wizard, 312, 0, :east
unit :thick_sludge, 327, 0, :east
unit :captive, 334, 0, :east
unit :wizard, 336, 0, :east
unit :archer, 339, 0, :east
unit :archer, 340, 0, :east
unit :captive, 341, 0, :east
unit :captive, 348, 0, :east
unit :thick_sludge, 355, 0, :east
unit :wizard, 357, 0, :east
unit :captive, 360, 0, :east
unit :thick_sludge, 363, 0, :east
unit :wizard, 370, 0, :east
unit :archer, 371, 0, :east
unit :wizard, 373, 0, :east
unit :sludge, 374, 0, :east
unit :archer, 376, 0, :east
unit :thick_sludge, 377, 0, :east
unit :wizard, 378, 0, :east
unit :thick_sludge, 381, 0, :east
unit :archer, 386, 0, :east
unit :archer, 387, 0, :east
unit :thick_sludge, 391, 0, :east
unit :archer, 392, 0, :east
unit :thick_sludge, 397, 0, :east
unit :archer, 401, 0, :east
unit :sludge, 405, 0, :east
unit :captive, 406, 0, :east
unit :captive, 408, 0, :east
unit :archer, 411, 0, :east
unit :thick_sludge, 413, 0, :east
unit :archer, 415, 0, :east
unit :captive, 419, 0, :east
unit :sludge, 421, 0, :east
unit :sludge, 425, 0, :east
unit :thick_sludge, 427, 0, :east
unit :thick_sludge, 431, 0, :east
unit :archer, 432, 0, :east
unit :wizard, 435, 0, :east
unit :thick_sludge, 436, 0, :east
unit :wizard, 441, 0, :east
unit :archer, 444, 0, :east
unit :thick_sludge, 450, 0, :east
unit :archer, 451, 0, :east
unit :sludge, 455, 0, :east
unit :captive, 460, 0, :east
unit :sludge, 463, 0, :east
unit :wizard, 467, 0, :east
unit :thick_sludge, 468, 0, :east
unit :thick_sludge, 478, 0, :east
unit :thick_sludge, 479, 0, :east
unit :sludge, 481, 0, :east
unit :archer, 489, 0, :east
unit :archer, 490, 0, :east
unit :thick_sludge, 493, 0, :east
unit :thick_sludge, 497, 0, :east
unit :thick_sludge, 500, 0, :east
unit :archer, 506, 0, :east
unit :archer, 513, 0, :east
unit :archer, 519, 0, :east
unit :thick_sludge, 524, 0, :east
unit :sludge, 530, 0, :east
unit :sludge, 533, 0, :east
unit :captive, 541, 0, :east
unit :thick_sludge, 545, 0, :east
unit :thick_sludge, 552, 0, :east
unit :sludge, 562, 0, :east
unit :captive, 566, 0, :east
unit :thick_sludge, 569, 0, :east
unit :wizard, 570, 0, :east
unit :wizard, 572, 0, :east
unit :captive, 574, 0, :east
unit :wizard, 578, 0, :east
unit :captive, 582, 0, :east
unit :archer, 591, 0, :east
unit :thick_sludge, 593, 0, :east
unit :archer, 602, 0, :east
unit :archer, 603, 0, :east
unit :archer, 605, 0, :east
unit :captive, 607, 0, :east
unit :captive, 612, 0, :east
unit :wizard, 618, 0, :east
unit :thick_sludge, 624, 0, :east
unit :sludge, 637, 0, :east
unit :thick_sludge, 638, 0, :east
unit :thick_sludge, 651, 0, :east
unit :captive, 653, 0, :east
unit :wizard, 656, 0, :east
unit :wizard, 659, 0, :east
unit :archer, 661, 0, :east
unit :archer, 669, 0, :east
unit :sludge, 670, 0, :east
unit :archer, 671, 0, :east
unit :sludge, 674, 0, :east
unit :sludge, 675, 0, :east
unit :wizard, 678, 0, :east
unit :thick_sludge, 682, 0, :east
unit :archer, 685, 0, :east
unit :captive, 688, 0, :east
unit :archer, 690, 0, :east
unit :wizard, 694, 0, :east
unit :archer, 700, 0, :west
unit :archer, 702, 0, :west
unit :thick_sludge, 706, 0, :west
unit :captive, 707, 0, :west
unit :thick_sludge, 710, 0, :west
unit :captive, 711, 0, :west
unit :wizard, 713, 0, :west
unit :thick_sludge, 715, 0, :west
unit :captive, 719, 0, :west
unit :captive, 726, 0, :west
unit :sludge, 730, 0, :west
unit :thick_sludge, 733, 0, :west
unit :wizard, 734, 0, :west
unit :thick_sludge, 735, 0, :west
unit :sludge, 737, 0, :west
unit :archer, 740, 0, :west
unit :archer, 742, 0, :west
unit :sludge, 743, 0, :west
unit :archer, 749, 0, :west
unit :wizard, 751, 0, :west
unit :captive, 752, 0, :west
unit :thick_sludge, 755, 0, :west
unit :sludge, 757, 0, :west
unit :sludge, 759, 0, :west
unit :archer, 761, 0, :west
unit :wizard, 764, 0, :west
unit :wizard, 769, 0, :west
unit :captive, 776, 0, :west
unit :thick_sludge, 789, 0, :west
unit :archer, 792, 0, :west
unit :archer, 797, 0, :west
unit :wizard, 799, 0, :west
unit :sludge, 803, 0, :west
unit :wizard, 807, 0, :west
unit :sludge, 811, 0, :west
unit :wizard, 815, 0, :west
unit :wizard, 818, 0, :west
