#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    a w Ca  a        aw     S             w   s  s s    a  s   s             a        s                    S   s   w S         a  a        SS    C    asC a     s     @   S   w           C S S  C  C    C C   ssSw   S    s  w     S S      S CC    w            Cs                CCs  a  a    s  s     C a a C     Ca      w   a   CC   Cs Ca    Sa  C     w  SCS   s    w  w  C  a    s  Ca    w  aCs  S      S    s    aS       s      aS  a S    a w SSC w s w       S    S     sS    C a wa        S a >     C S aw   a s     s a        S  w  a   s s       aC  a   s a  w            s    w s   w         sC  w   a     a  a CCC  C  ss  C          w    a   as    C  a s        C         Sa          Sass C    S             w w s   C w    |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 727
ace_score 3635
size 727, 1
stairs 494, 0

warrior 166, 0, :east

unit :archer, 4, 0, :east
unit :wizard, 6, 0, :east
unit :captive, 8, 0, :east
unit :archer, 9, 0, :east
unit :archer, 12, 0, :east
unit :archer, 21, 0, :east
unit :wizard, 22, 0, :east
unit :thick_sludge, 28, 0, :east
unit :wizard, 42, 0, :east
unit :sludge, 46, 0, :east
unit :sludge, 49, 0, :east
unit :sludge, 51, 0, :east
unit :archer, 56, 0, :east
unit :sludge, 59, 0, :east
unit :sludge, 63, 0, :east
unit :archer, 77, 0, :east
unit :sludge, 86, 0, :east
unit :thick_sludge, 107, 0, :east
unit :sludge, 111, 0, :east
unit :wizard, 115, 0, :east
unit :thick_sludge, 117, 0, :east
unit :archer, 127, 0, :east
unit :archer, 130, 0, :east
unit :thick_sludge, 139, 0, :east
unit :thick_sludge, 140, 0, :east
unit :captive, 145, 0, :east
unit :archer, 150, 0, :east
unit :sludge, 151, 0, :east
unit :captive, 152, 0, :east
unit :archer, 154, 0, :east
unit :sludge, 160, 0, :east
unit :thick_sludge, 170, 0, :west
unit :wizard, 174, 0, :west
unit :captive, 186, 0, :west
unit :thick_sludge, 188, 0, :west
unit :thick_sludge, 190, 0, :west
unit :captive, 193, 0, :west
unit :captive, 196, 0, :west
unit :captive, 201, 0, :west
unit :captive, 203, 0, :west
unit :sludge, 207, 0, :west
unit :sludge, 208, 0, :west
unit :thick_sludge, 209, 0, :west
unit :wizard, 210, 0, :west
unit :thick_sludge, 214, 0, :west
unit :sludge, 219, 0, :west
unit :wizard, 222, 0, :west
unit :thick_sludge, 228, 0, :west
unit :thick_sludge, 230, 0, :west
unit :thick_sludge, 237, 0, :west
unit :captive, 239, 0, :west
unit :captive, 240, 0, :west
unit :wizard, 245, 0, :west
unit :captive, 258, 0, :west
unit :sludge, 259, 0, :west
unit :captive, 276, 0, :west
unit :captive, 277, 0, :west
unit :sludge, 278, 0, :west
unit :archer, 281, 0, :west
unit :archer, 284, 0, :west
unit :sludge, 289, 0, :west
unit :sludge, 292, 0, :west
unit :captive, 298, 0, :west
unit :archer, 300, 0, :west
unit :archer, 302, 0, :west
unit :captive, 304, 0, :west
unit :captive, 310, 0, :west
unit :archer, 311, 0, :west
unit :wizard, 318, 0, :west
unit :archer, 322, 0, :west
unit :captive, 326, 0, :west
unit :captive, 327, 0, :west
unit :captive, 331, 0, :west
unit :sludge, 332, 0, :west
unit :captive, 334, 0, :west
unit :archer, 335, 0, :west
unit :thick_sludge, 340, 0, :west
unit :archer, 341, 0, :west
unit :captive, 344, 0, :west
unit :wizard, 350, 0, :west
unit :thick_sludge, 353, 0, :west
unit :captive, 354, 0, :west
unit :thick_sludge, 355, 0, :west
unit :sludge, 359, 0, :west
unit :wizard, 364, 0, :west
unit :wizard, 367, 0, :west
unit :captive, 370, 0, :west
unit :archer, 373, 0, :west
unit :sludge, 378, 0, :west
unit :captive, 381, 0, :west
unit :archer, 382, 0, :west
unit :wizard, 387, 0, :west
unit :archer, 390, 0, :west
unit :captive, 391, 0, :west
unit :sludge, 392, 0, :west
unit :thick_sludge, 395, 0, :west
unit :thick_sludge, 402, 0, :west
unit :sludge, 407, 0, :west
unit :archer, 412, 0, :west
unit :thick_sludge, 413, 0, :west
unit :sludge, 421, 0, :west
unit :archer, 428, 0, :west
unit :thick_sludge, 429, 0, :west
unit :archer, 432, 0, :west
unit :thick_sludge, 434, 0, :west
unit :archer, 439, 0, :west
unit :wizard, 441, 0, :west
unit :thick_sludge, 443, 0, :west
unit :thick_sludge, 444, 0, :west
unit :captive, 445, 0, :west
unit :wizard, 447, 0, :west
unit :sludge, 449, 0, :west
unit :wizard, 451, 0, :west
unit :thick_sludge, 459, 0, :west
unit :thick_sludge, 464, 0, :west
unit :sludge, 470, 0, :west
unit :thick_sludge, 471, 0, :west
unit :captive, 476, 0, :west
unit :archer, 478, 0, :west
unit :wizard, 480, 0, :west
unit :archer, 481, 0, :west
unit :thick_sludge, 490, 0, :west
unit :archer, 492, 0, :west
unit :captive, 500, 0, :west
unit :thick_sludge, 502, 0, :west
unit :archer, 504, 0, :west
unit :wizard, 505, 0, :west
unit :archer, 509, 0, :west
unit :sludge, 511, 0, :west
unit :sludge, 517, 0, :west
unit :archer, 519, 0, :west
unit :thick_sludge, 528, 0, :west
unit :wizard, 531, 0, :west
unit :archer, 534, 0, :west
unit :sludge, 538, 0, :west
unit :sludge, 540, 0, :west
unit :archer, 548, 0, :west
unit :captive, 549, 0, :west
unit :archer, 552, 0, :west
unit :sludge, 556, 0, :west
unit :archer, 558, 0, :west
unit :wizard, 561, 0, :west
unit :sludge, 574, 0, :west
unit :wizard, 579, 0, :west
unit :sludge, 581, 0, :west
unit :wizard, 585, 0, :west
unit :sludge, 595, 0, :west
unit :captive, 596, 0, :west
unit :wizard, 599, 0, :west
unit :archer, 603, 0, :west
unit :archer, 609, 0, :west
unit :archer, 612, 0, :west
unit :captive, 614, 0, :west
unit :captive, 615, 0, :west
unit :captive, 616, 0, :west
unit :captive, 619, 0, :west
unit :sludge, 622, 0, :west
unit :sludge, 623, 0, :west
unit :captive, 626, 0, :west
unit :wizard, 637, 0, :west
unit :archer, 642, 0, :west
unit :archer, 646, 0, :west
unit :sludge, 647, 0, :west
unit :captive, 652, 0, :west
unit :archer, 655, 0, :west
unit :sludge, 657, 0, :west
unit :captive, 666, 0, :west
unit :thick_sludge, 676, 0, :west
unit :archer, 677, 0, :west
unit :thick_sludge, 688, 0, :west
unit :archer, 689, 0, :west
unit :sludge, 690, 0, :west
unit :sludge, 691, 0, :west
unit :captive, 693, 0, :west
unit :thick_sludge, 698, 0, :west
unit :wizard, 712, 0, :west
unit :wizard, 714, 0, :west
unit :sludge, 716, 0, :west
unit :captive, 720, 0, :west
unit :wizard, 722, 0, :west
