#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |          wC a       w S  a w S               >a     S    S a   w S    w      w       w                     S    CCC    S   a w        wC     C      C    w  CC   C        C  s    Sa   a S a        a  S  C   C     CS   C  S w S CS a        S  s   a  S     sCw       s  C w   w s C   w   w  S                  w   a w a  SSS   sCaC C      S      a  s S  @  C sa   S a   Ss a  C       s C w     wa       aSw  s w  w      S a S a       w  a      S w       aC   s C            s  C   w w      S      C    s S S  SS   C S s  C    as  SS  C w   ss S    S w  a        a       S         a          SS      w   S    S    a    C   C     S    w C  w  s S  C S s  s    S   s     a S     a w        |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 685
ace_score 3425
size 685, 1
stairs 46, 0

warrior 352, 0, :east

unit :wizard, 10, 0, :east
unit :captive, 11, 0, :east
unit :archer, 13, 0, :east
unit :wizard, 21, 0, :east
unit :thick_sludge, 23, 0, :east
unit :archer, 26, 0, :east
unit :wizard, 28, 0, :east
unit :thick_sludge, 30, 0, :east
unit :archer, 47, 0, :east
unit :thick_sludge, 53, 0, :east
unit :thick_sludge, 58, 0, :east
unit :archer, 60, 0, :east
unit :wizard, 64, 0, :east
unit :thick_sludge, 66, 0, :east
unit :wizard, 71, 0, :east
unit :wizard, 78, 0, :east
unit :wizard, 86, 0, :east
unit :thick_sludge, 108, 0, :east
unit :captive, 113, 0, :east
unit :captive, 114, 0, :east
unit :captive, 115, 0, :east
unit :thick_sludge, 120, 0, :east
unit :archer, 124, 0, :east
unit :wizard, 126, 0, :east
unit :wizard, 135, 0, :east
unit :captive, 136, 0, :east
unit :captive, 142, 0, :east
unit :captive, 149, 0, :east
unit :wizard, 154, 0, :east
unit :captive, 157, 0, :east
unit :captive, 158, 0, :east
unit :captive, 162, 0, :east
unit :captive, 171, 0, :east
unit :sludge, 174, 0, :east
unit :thick_sludge, 179, 0, :east
unit :archer, 180, 0, :east
unit :archer, 184, 0, :east
unit :thick_sludge, 186, 0, :east
unit :archer, 188, 0, :east
unit :archer, 197, 0, :east
unit :thick_sludge, 200, 0, :east
unit :captive, 203, 0, :east
unit :captive, 207, 0, :east
unit :captive, 213, 0, :east
unit :thick_sludge, 214, 0, :east
unit :captive, 218, 0, :east
unit :thick_sludge, 221, 0, :east
unit :wizard, 223, 0, :east
unit :thick_sludge, 225, 0, :east
unit :captive, 227, 0, :east
unit :thick_sludge, 228, 0, :east
unit :archer, 230, 0, :east
unit :thick_sludge, 239, 0, :east
unit :sludge, 242, 0, :east
unit :archer, 246, 0, :east
unit :thick_sludge, 249, 0, :east
unit :sludge, 255, 0, :east
unit :captive, 256, 0, :east
unit :wizard, 257, 0, :east
unit :sludge, 265, 0, :east
unit :captive, 268, 0, :east
unit :wizard, 270, 0, :east
unit :wizard, 274, 0, :east
unit :sludge, 276, 0, :east
unit :captive, 278, 0, :east
unit :wizard, 282, 0, :east
unit :wizard, 286, 0, :east
unit :thick_sludge, 289, 0, :east
unit :wizard, 308, 0, :east
unit :archer, 312, 0, :east
unit :wizard, 314, 0, :east
unit :archer, 316, 0, :east
unit :thick_sludge, 319, 0, :east
unit :thick_sludge, 320, 0, :east
unit :thick_sludge, 321, 0, :east
unit :sludge, 325, 0, :east
unit :captive, 326, 0, :east
unit :archer, 327, 0, :east
unit :captive, 328, 0, :east
unit :captive, 330, 0, :east
unit :thick_sludge, 337, 0, :east
unit :archer, 344, 0, :east
unit :sludge, 347, 0, :east
unit :thick_sludge, 349, 0, :east
unit :captive, 355, 0, :west
unit :sludge, 357, 0, :west
unit :archer, 358, 0, :west
unit :thick_sludge, 362, 0, :west
unit :archer, 364, 0, :west
unit :thick_sludge, 368, 0, :west
unit :sludge, 369, 0, :west
unit :archer, 371, 0, :west
unit :captive, 374, 0, :west
unit :sludge, 382, 0, :west
unit :captive, 384, 0, :west
unit :wizard, 386, 0, :west
unit :wizard, 392, 0, :west
unit :archer, 393, 0, :west
unit :archer, 401, 0, :west
unit :thick_sludge, 402, 0, :west
unit :wizard, 403, 0, :west
unit :sludge, 406, 0, :west
unit :wizard, 408, 0, :west
unit :wizard, 411, 0, :west
unit :thick_sludge, 418, 0, :west
unit :archer, 420, 0, :west
unit :thick_sludge, 422, 0, :west
unit :archer, 424, 0, :west
unit :wizard, 432, 0, :west
unit :archer, 435, 0, :west
unit :thick_sludge, 442, 0, :west
unit :wizard, 444, 0, :west
unit :archer, 452, 0, :west
unit :captive, 453, 0, :west
unit :sludge, 457, 0, :west
unit :captive, 459, 0, :west
unit :sludge, 472, 0, :west
unit :captive, 475, 0, :west
unit :wizard, 479, 0, :west
unit :wizard, 481, 0, :west
unit :thick_sludge, 488, 0, :west
unit :captive, 495, 0, :west
unit :sludge, 500, 0, :west
unit :thick_sludge, 502, 0, :west
unit :thick_sludge, 504, 0, :west
unit :thick_sludge, 507, 0, :west
unit :thick_sludge, 508, 0, :west
unit :captive, 512, 0, :west
unit :thick_sludge, 514, 0, :west
unit :sludge, 516, 0, :west
unit :captive, 519, 0, :west
unit :archer, 524, 0, :west
unit :sludge, 525, 0, :west
unit :thick_sludge, 528, 0, :west
unit :thick_sludge, 529, 0, :west
unit :captive, 532, 0, :west
unit :wizard, 534, 0, :west
unit :sludge, 538, 0, :west
unit :sludge, 539, 0, :west
unit :thick_sludge, 541, 0, :west
unit :thick_sludge, 546, 0, :west
unit :wizard, 548, 0, :west
unit :archer, 551, 0, :west
unit :archer, 560, 0, :west
unit :thick_sludge, 568, 0, :west
unit :archer, 578, 0, :west
unit :thick_sludge, 589, 0, :west
unit :thick_sludge, 590, 0, :west
unit :wizard, 597, 0, :west
unit :thick_sludge, 601, 0, :west
unit :thick_sludge, 606, 0, :west
unit :archer, 611, 0, :west
unit :captive, 616, 0, :west
unit :captive, 620, 0, :west
unit :thick_sludge, 626, 0, :west
unit :wizard, 631, 0, :west
unit :captive, 633, 0, :west
unit :wizard, 636, 0, :west
unit :sludge, 639, 0, :west
unit :thick_sludge, 641, 0, :west
unit :captive, 644, 0, :west
unit :thick_sludge, 646, 0, :west
unit :sludge, 648, 0, :west
unit :sludge, 651, 0, :west
unit :thick_sludge, 656, 0, :west
unit :sludge, 660, 0, :west
unit :archer, 666, 0, :west
unit :thick_sludge, 668, 0, :west
unit :archer, 674, 0, :west
unit :wizard, 676, 0, :west
