#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S     C  a Cs    >CC  s    S aw  s   s         C C   s   SCa    C  Ss a s       a      C Ss        S S  S    s    s s   sw     C      SSs      a   CC    s a     S    w                aS  aCa  C      C   S w s wC        S    w Csw   wC      S w S                    S s   w   Cw w       C  s    CaS         S w           a Ca s      C CC     w               w sss      S  a   w   a   w      C   S           @   s   Ca     a Cs  Sa w     a  C  C  S   CCS a       w CCS S    Cw          S  ss   S   aC  a  CwS            w  aC     s sC    s     a           Ca a S       s C              a  C     s     S     S     sS s s      w  s  S        w      ss   s S C   S   S  w        a w a    w   a s  C C   C         C       C     S w w  S    Ss            ss    S  SS          sS      a s    w      as s   a           s  w    s S        Sw s  S C  a S  a a         s     S        S  s   w   s      w C |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 895
ace_score 4475
size 895, 1
stairs 18, 0

warrior 407, 0, :east

unit :thick_sludge, 1, 0, :east
unit :captive, 7, 0, :east
unit :archer, 10, 0, :east
unit :captive, 12, 0, :east
unit :sludge, 13, 0, :east
unit :captive, 19, 0, :east
unit :captive, 20, 0, :east
unit :sludge, 23, 0, :east
unit :thick_sludge, 28, 0, :east
unit :archer, 30, 0, :east
unit :wizard, 31, 0, :east
unit :sludge, 34, 0, :east
unit :sludge, 38, 0, :east
unit :captive, 48, 0, :east
unit :captive, 50, 0, :east
unit :sludge, 54, 0, :east
unit :thick_sludge, 58, 0, :east
unit :captive, 59, 0, :east
unit :archer, 60, 0, :east
unit :captive, 65, 0, :east
unit :thick_sludge, 68, 0, :east
unit :sludge, 69, 0, :east
unit :archer, 71, 0, :east
unit :sludge, 73, 0, :east
unit :archer, 81, 0, :east
unit :captive, 88, 0, :east
unit :thick_sludge, 90, 0, :east
unit :sludge, 91, 0, :east
unit :thick_sludge, 100, 0, :east
unit :thick_sludge, 102, 0, :east
unit :thick_sludge, 105, 0, :east
unit :sludge, 110, 0, :east
unit :sludge, 115, 0, :east
unit :sludge, 117, 0, :east
unit :sludge, 121, 0, :east
unit :wizard, 122, 0, :east
unit :captive, 128, 0, :east
unit :thick_sludge, 135, 0, :east
unit :thick_sludge, 136, 0, :east
unit :sludge, 137, 0, :east
unit :archer, 144, 0, :east
unit :captive, 148, 0, :east
unit :captive, 149, 0, :east
unit :sludge, 154, 0, :east
unit :archer, 156, 0, :east
unit :thick_sludge, 162, 0, :east
unit :wizard, 167, 0, :east
unit :archer, 184, 0, :east
unit :thick_sludge, 185, 0, :east
unit :archer, 188, 0, :east
unit :captive, 189, 0, :east
unit :archer, 190, 0, :east
unit :captive, 193, 0, :east
unit :captive, 200, 0, :east
unit :thick_sludge, 204, 0, :east
unit :wizard, 206, 0, :east
unit :sludge, 208, 0, :east
unit :wizard, 210, 0, :east
unit :captive, 211, 0, :east
unit :thick_sludge, 220, 0, :east
unit :wizard, 225, 0, :east
unit :captive, 227, 0, :east
unit :sludge, 228, 0, :east
unit :wizard, 229, 0, :east
unit :wizard, 233, 0, :east
unit :captive, 234, 0, :east
unit :thick_sludge, 241, 0, :east
unit :wizard, 243, 0, :east
unit :thick_sludge, 245, 0, :east
unit :thick_sludge, 266, 0, :east
unit :sludge, 268, 0, :east
unit :wizard, 272, 0, :east
unit :captive, 276, 0, :east
unit :wizard, 277, 0, :east
unit :wizard, 279, 0, :east
unit :captive, 287, 0, :east
unit :sludge, 290, 0, :east
unit :captive, 295, 0, :east
unit :archer, 296, 0, :east
unit :thick_sludge, 297, 0, :east
unit :thick_sludge, 307, 0, :east
unit :wizard, 309, 0, :east
unit :archer, 321, 0, :east
unit :captive, 323, 0, :east
unit :archer, 324, 0, :east
unit :sludge, 326, 0, :east
unit :captive, 333, 0, :east
unit :captive, 335, 0, :east
unit :captive, 336, 0, :east
unit :wizard, 342, 0, :east
unit :wizard, 358, 0, :east
unit :sludge, 360, 0, :east
unit :sludge, 361, 0, :east
unit :sludge, 362, 0, :east
unit :thick_sludge, 369, 0, :east
unit :archer, 372, 0, :east
unit :wizard, 376, 0, :east
unit :archer, 380, 0, :east
unit :wizard, 384, 0, :east
unit :captive, 391, 0, :east
unit :thick_sludge, 395, 0, :east
unit :sludge, 411, 0, :west
unit :captive, 415, 0, :west
unit :archer, 416, 0, :west
unit :archer, 422, 0, :west
unit :captive, 424, 0, :west
unit :sludge, 425, 0, :west
unit :thick_sludge, 428, 0, :west
unit :archer, 429, 0, :west
unit :wizard, 431, 0, :west
unit :archer, 437, 0, :west
unit :captive, 440, 0, :west
unit :captive, 443, 0, :west
unit :thick_sludge, 446, 0, :west
unit :captive, 450, 0, :west
unit :captive, 451, 0, :west
unit :thick_sludge, 452, 0, :west
unit :archer, 454, 0, :west
unit :wizard, 462, 0, :west
unit :captive, 464, 0, :west
unit :captive, 465, 0, :west
unit :thick_sludge, 466, 0, :west
unit :thick_sludge, 468, 0, :west
unit :captive, 473, 0, :west
unit :wizard, 474, 0, :west
unit :thick_sludge, 485, 0, :west
unit :sludge, 488, 0, :west
unit :sludge, 489, 0, :west
unit :thick_sludge, 493, 0, :west
unit :archer, 497, 0, :west
unit :captive, 498, 0, :west
unit :archer, 501, 0, :west
unit :captive, 504, 0, :west
unit :wizard, 505, 0, :west
unit :thick_sludge, 506, 0, :west
unit :wizard, 519, 0, :west
unit :archer, 522, 0, :west
unit :captive, 523, 0, :west
unit :sludge, 529, 0, :west
unit :sludge, 531, 0, :west
unit :captive, 532, 0, :west
unit :sludge, 537, 0, :west
unit :archer, 543, 0, :west
unit :captive, 555, 0, :west
unit :archer, 556, 0, :west
unit :archer, 558, 0, :west
unit :thick_sludge, 560, 0, :west
unit :sludge, 568, 0, :west
unit :captive, 570, 0, :west
unit :archer, 585, 0, :west
unit :captive, 588, 0, :west
unit :sludge, 594, 0, :west
unit :thick_sludge, 600, 0, :west
unit :thick_sludge, 606, 0, :west
unit :sludge, 612, 0, :west
unit :thick_sludge, 613, 0, :west
unit :sludge, 615, 0, :west
unit :sludge, 617, 0, :west
unit :wizard, 624, 0, :west
unit :sludge, 627, 0, :west
unit :thick_sludge, 630, 0, :west
unit :wizard, 639, 0, :west
unit :sludge, 646, 0, :west
unit :sludge, 647, 0, :west
unit :sludge, 651, 0, :west
unit :thick_sludge, 653, 0, :west
unit :captive, 655, 0, :west
unit :thick_sludge, 659, 0, :west
unit :thick_sludge, 663, 0, :west
unit :wizard, 666, 0, :west
unit :archer, 675, 0, :west
unit :wizard, 677, 0, :west
unit :archer, 679, 0, :west
unit :wizard, 684, 0, :west
unit :archer, 688, 0, :west
unit :sludge, 690, 0, :west
unit :captive, 693, 0, :west
unit :captive, 695, 0, :west
unit :captive, 699, 0, :west
unit :captive, 709, 0, :west
unit :captive, 717, 0, :west
unit :thick_sludge, 723, 0, :west
unit :wizard, 725, 0, :west
unit :wizard, 727, 0, :west
unit :thick_sludge, 730, 0, :west
unit :thick_sludge, 735, 0, :west
unit :sludge, 736, 0, :west
unit :sludge, 749, 0, :west
unit :sludge, 750, 0, :west
unit :thick_sludge, 755, 0, :west
unit :thick_sludge, 758, 0, :west
unit :thick_sludge, 759, 0, :west
unit :sludge, 770, 0, :west
unit :thick_sludge, 771, 0, :west
unit :archer, 778, 0, :west
unit :sludge, 780, 0, :west
unit :wizard, 785, 0, :west
unit :archer, 792, 0, :west
unit :sludge, 793, 0, :west
unit :sludge, 795, 0, :west
unit :archer, 799, 0, :west
unit :sludge, 811, 0, :west
unit :wizard, 814, 0, :west
unit :sludge, 819, 0, :west
unit :thick_sludge, 821, 0, :west
unit :thick_sludge, 830, 0, :west
unit :wizard, 831, 0, :west
unit :sludge, 833, 0, :west
unit :thick_sludge, 836, 0, :west
unit :captive, 838, 0, :west
unit :archer, 841, 0, :west
unit :thick_sludge, 843, 0, :west
unit :archer, 846, 0, :west
unit :archer, 848, 0, :west
unit :sludge, 858, 0, :west
unit :thick_sludge, 864, 0, :west
unit :thick_sludge, 873, 0, :west
unit :sludge, 876, 0, :west
unit :wizard, 880, 0, :west
unit :sludge, 884, 0, :west
unit :wizard, 891, 0, :west
unit :captive, 893, 0, :west
