#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |           C s  a  aS C S S         s       s     w  S C      s a   a      w C as    w    Sw      C    S S aS   C       a  s  S         sw s         s      aa  s s w  S         S C      w a    C a  a C           s  sS          C  C  s a    w         w wa  S   Cs  s     w     s s    w    s            S        sS      Cw   C       a SCC       s     s  a       sa      C S       Cs     a  C sa w C  C       w  a      w        sw         aa C   s       wSC a   CaS C  C     wa     s>  S   a  w       w    C S ss          w  C   sS   aS   a                a   w  a    s    s     SsS       w             S   s   s a    s w  a a wa  w   S  s   SS  S   w  C  S   wa     aa    CS S   S  @          w a     s S a  w wSws          S s   C   a   C           Sa C   s  C |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 760
ace_score 3800
size 760, 1
stairs 480, 0

warrior 680, 0, :east

unit :captive, 11, 0, :east
unit :sludge, 13, 0, :east
unit :archer, 16, 0, :east
unit :archer, 19, 0, :east
unit :thick_sludge, 20, 0, :east
unit :captive, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :thick_sludge, 26, 0, :east
unit :sludge, 36, 0, :east
unit :sludge, 44, 0, :east
unit :wizard, 50, 0, :east
unit :thick_sludge, 53, 0, :east
unit :captive, 55, 0, :east
unit :sludge, 62, 0, :east
unit :archer, 64, 0, :east
unit :archer, 68, 0, :east
unit :wizard, 75, 0, :east
unit :captive, 77, 0, :east
unit :archer, 79, 0, :east
unit :sludge, 80, 0, :east
unit :wizard, 85, 0, :east
unit :thick_sludge, 90, 0, :east
unit :wizard, 91, 0, :east
unit :captive, 98, 0, :east
unit :thick_sludge, 103, 0, :east
unit :thick_sludge, 105, 0, :east
unit :archer, 107, 0, :east
unit :thick_sludge, 108, 0, :east
unit :captive, 112, 0, :east
unit :archer, 120, 0, :east
unit :sludge, 123, 0, :east
unit :thick_sludge, 126, 0, :east
unit :sludge, 136, 0, :east
unit :wizard, 137, 0, :east
unit :sludge, 139, 0, :east
unit :sludge, 149, 0, :east
unit :archer, 156, 0, :east
unit :archer, 157, 0, :east
unit :sludge, 160, 0, :east
unit :sludge, 162, 0, :east
unit :wizard, 164, 0, :east
unit :thick_sludge, 167, 0, :east
unit :thick_sludge, 177, 0, :east
unit :captive, 179, 0, :east
unit :wizard, 186, 0, :east
unit :archer, 188, 0, :east
unit :captive, 193, 0, :east
unit :archer, 195, 0, :east
unit :archer, 198, 0, :east
unit :captive, 200, 0, :east
unit :sludge, 212, 0, :east
unit :sludge, 215, 0, :east
unit :thick_sludge, 216, 0, :east
unit :captive, 227, 0, :east
unit :captive, 230, 0, :east
unit :sludge, 233, 0, :east
unit :archer, 235, 0, :east
unit :wizard, 240, 0, :east
unit :wizard, 250, 0, :east
unit :wizard, 252, 0, :east
unit :archer, 253, 0, :east
unit :thick_sludge, 256, 0, :east
unit :captive, 260, 0, :east
unit :sludge, 261, 0, :east
unit :sludge, 264, 0, :east
unit :wizard, 270, 0, :east
unit :sludge, 276, 0, :east
unit :sludge, 278, 0, :east
unit :wizard, 283, 0, :east
unit :sludge, 288, 0, :east
unit :thick_sludge, 301, 0, :east
unit :sludge, 310, 0, :east
unit :thick_sludge, 311, 0, :east
unit :captive, 318, 0, :east
unit :wizard, 319, 0, :east
unit :captive, 323, 0, :east
unit :archer, 331, 0, :east
unit :thick_sludge, 333, 0, :east
unit :captive, 334, 0, :east
unit :captive, 335, 0, :east
unit :sludge, 343, 0, :east
unit :sludge, 349, 0, :east
unit :archer, 352, 0, :east
unit :sludge, 360, 0, :east
unit :archer, 361, 0, :east
unit :captive, 368, 0, :east
unit :thick_sludge, 370, 0, :east
unit :captive, 378, 0, :east
unit :sludge, 379, 0, :east
unit :archer, 385, 0, :east
unit :captive, 388, 0, :east
unit :sludge, 390, 0, :east
unit :archer, 391, 0, :east
unit :wizard, 393, 0, :east
unit :captive, 395, 0, :east
unit :captive, 398, 0, :east
unit :wizard, 406, 0, :east
unit :archer, 409, 0, :east
unit :wizard, 416, 0, :east
unit :sludge, 425, 0, :east
unit :wizard, 426, 0, :east
unit :archer, 436, 0, :east
unit :archer, 437, 0, :east
unit :captive, 439, 0, :east
unit :sludge, 443, 0, :east
unit :wizard, 451, 0, :east
unit :thick_sludge, 452, 0, :east
unit :captive, 453, 0, :east
unit :archer, 455, 0, :east
unit :captive, 459, 0, :east
unit :archer, 460, 0, :east
unit :thick_sludge, 461, 0, :east
unit :captive, 463, 0, :east
unit :captive, 466, 0, :east
unit :wizard, 472, 0, :east
unit :archer, 473, 0, :east
unit :sludge, 479, 0, :east
unit :thick_sludge, 483, 0, :east
unit :archer, 487, 0, :east
unit :wizard, 490, 0, :east
unit :wizard, 498, 0, :east
unit :captive, 503, 0, :east
unit :thick_sludge, 505, 0, :east
unit :sludge, 507, 0, :east
unit :sludge, 508, 0, :east
unit :wizard, 519, 0, :east
unit :captive, 522, 0, :east
unit :sludge, 526, 0, :east
unit :thick_sludge, 527, 0, :east
unit :archer, 531, 0, :east
unit :thick_sludge, 532, 0, :east
unit :archer, 536, 0, :east
unit :archer, 553, 0, :east
unit :wizard, 557, 0, :east
unit :archer, 560, 0, :east
unit :sludge, 565, 0, :east
unit :sludge, 570, 0, :east
unit :thick_sludge, 576, 0, :east
unit :sludge, 577, 0, :east
unit :thick_sludge, 578, 0, :east
unit :wizard, 586, 0, :east
unit :thick_sludge, 600, 0, :east
unit :sludge, 604, 0, :east
unit :sludge, 608, 0, :east
unit :archer, 610, 0, :east
unit :sludge, 615, 0, :east
unit :wizard, 617, 0, :east
unit :archer, 620, 0, :east
unit :archer, 622, 0, :east
unit :wizard, 624, 0, :east
unit :archer, 625, 0, :east
unit :wizard, 628, 0, :east
unit :thick_sludge, 632, 0, :east
unit :sludge, 635, 0, :east
unit :thick_sludge, 639, 0, :east
unit :thick_sludge, 640, 0, :east
unit :thick_sludge, 643, 0, :east
unit :wizard, 647, 0, :east
unit :captive, 650, 0, :east
unit :thick_sludge, 653, 0, :east
unit :wizard, 657, 0, :east
unit :archer, 658, 0, :east
unit :archer, 664, 0, :east
unit :archer, 665, 0, :east
unit :captive, 670, 0, :east
unit :thick_sludge, 671, 0, :east
unit :thick_sludge, 673, 0, :east
unit :thick_sludge, 677, 0, :east
unit :wizard, 691, 0, :west
unit :archer, 693, 0, :west
unit :sludge, 699, 0, :west
unit :thick_sludge, 701, 0, :west
unit :archer, 703, 0, :west
unit :wizard, 706, 0, :west
unit :wizard, 708, 0, :west
unit :thick_sludge, 709, 0, :west
unit :wizard, 710, 0, :west
unit :sludge, 711, 0, :west
unit :thick_sludge, 722, 0, :west
unit :sludge, 724, 0, :west
unit :captive, 728, 0, :west
unit :archer, 732, 0, :west
unit :captive, 736, 0, :west
unit :thick_sludge, 748, 0, :west
unit :archer, 749, 0, :west
unit :captive, 751, 0, :west
unit :sludge, 755, 0, :west
unit :captive, 758, 0, :west
