#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s  S     wa  a      a  Sw       C C   s s            w    C           Ca     s  a   Ca C   w a SS      Sw      s    w S    s   @   a     C S  s  aC      Cs    w w    ss   s s   aCs   S C     s S        a ss  a     S  a C S    C s    as   wS S  Ca  s                w C     s s   CC s        s CCs    w    s sC  C  C w w     s   s     s   w   C   s  w s S    C    S  s  s  C  S     s        S a  S   w s>    C   C    a a    S C         w a  sS  sS C  S                   a  S    s  s         a      w    sSa        w a                  w  w   C s        s   w   S      a   S     w     ws   S      w         s w      S      wa        SCs  SC as    a  S      sC  ss C C    Ca s       C      w            Ssw   S   C             S    s s  ssSs          w         aC       S  a     SS    s  S C SSsas  a      w    a   a     aCSC        C s    wC         S  ss  Ss      s         S a           s   S  S   |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 901
ace_score 4505
size 901, 1
stairs 404, 0

warrior 129, 0, :east

unit :sludge, 2, 0, :east
unit :thick_sludge, 5, 0, :east
unit :wizard, 11, 0, :east
unit :archer, 12, 0, :east
unit :archer, 15, 0, :east
unit :archer, 22, 0, :east
unit :thick_sludge, 25, 0, :east
unit :wizard, 26, 0, :east
unit :captive, 34, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 40, 0, :east
unit :sludge, 42, 0, :east
unit :wizard, 55, 0, :east
unit :captive, 60, 0, :east
unit :captive, 72, 0, :east
unit :archer, 73, 0, :east
unit :sludge, 79, 0, :east
unit :archer, 82, 0, :east
unit :captive, 86, 0, :east
unit :archer, 87, 0, :east
unit :captive, 89, 0, :east
unit :wizard, 93, 0, :east
unit :archer, 95, 0, :east
unit :thick_sludge, 97, 0, :east
unit :thick_sludge, 98, 0, :east
unit :thick_sludge, 105, 0, :east
unit :wizard, 106, 0, :east
unit :sludge, 113, 0, :east
unit :wizard, 118, 0, :east
unit :thick_sludge, 120, 0, :east
unit :sludge, 125, 0, :east
unit :archer, 133, 0, :west
unit :captive, 139, 0, :west
unit :thick_sludge, 141, 0, :west
unit :sludge, 144, 0, :west
unit :archer, 147, 0, :west
unit :captive, 148, 0, :west
unit :captive, 155, 0, :west
unit :sludge, 156, 0, :west
unit :wizard, 161, 0, :west
unit :wizard, 163, 0, :west
unit :sludge, 168, 0, :west
unit :sludge, 169, 0, :west
unit :sludge, 173, 0, :west
unit :sludge, 175, 0, :west
unit :archer, 179, 0, :west
unit :captive, 180, 0, :west
unit :sludge, 181, 0, :west
unit :thick_sludge, 185, 0, :west
unit :captive, 187, 0, :west
unit :sludge, 193, 0, :west
unit :thick_sludge, 195, 0, :west
unit :archer, 204, 0, :west
unit :sludge, 206, 0, :west
unit :sludge, 207, 0, :west
unit :archer, 210, 0, :west
unit :thick_sludge, 216, 0, :west
unit :archer, 219, 0, :west
unit :captive, 221, 0, :west
unit :thick_sludge, 223, 0, :west
unit :captive, 228, 0, :west
unit :sludge, 230, 0, :west
unit :archer, 235, 0, :west
unit :sludge, 236, 0, :west
unit :wizard, 240, 0, :west
unit :thick_sludge, 241, 0, :west
unit :thick_sludge, 243, 0, :west
unit :captive, 246, 0, :west
unit :archer, 247, 0, :west
unit :sludge, 250, 0, :west
unit :wizard, 267, 0, :west
unit :captive, 269, 0, :west
unit :sludge, 275, 0, :west
unit :sludge, 277, 0, :west
unit :captive, 281, 0, :west
unit :captive, 282, 0, :west
unit :sludge, 284, 0, :west
unit :sludge, 293, 0, :west
unit :captive, 295, 0, :west
unit :captive, 296, 0, :west
unit :sludge, 297, 0, :west
unit :wizard, 302, 0, :west
unit :sludge, 307, 0, :west
unit :sludge, 309, 0, :west
unit :captive, 310, 0, :west
unit :captive, 313, 0, :west
unit :captive, 316, 0, :west
unit :wizard, 318, 0, :west
unit :wizard, 320, 0, :west
unit :sludge, 326, 0, :west
unit :sludge, 330, 0, :west
unit :sludge, 336, 0, :west
unit :wizard, 340, 0, :west
unit :captive, 344, 0, :west
unit :sludge, 348, 0, :west
unit :wizard, 351, 0, :west
unit :sludge, 353, 0, :west
unit :thick_sludge, 355, 0, :west
unit :captive, 360, 0, :west
unit :thick_sludge, 365, 0, :west
unit :sludge, 368, 0, :west
unit :sludge, 371, 0, :west
unit :captive, 374, 0, :west
unit :thick_sludge, 377, 0, :west
unit :sludge, 383, 0, :west
unit :thick_sludge, 392, 0, :west
unit :archer, 394, 0, :west
unit :thick_sludge, 397, 0, :west
unit :wizard, 401, 0, :west
unit :sludge, 403, 0, :west
unit :captive, 409, 0, :west
unit :captive, 413, 0, :west
unit :archer, 418, 0, :west
unit :archer, 420, 0, :west
unit :thick_sludge, 425, 0, :west
unit :captive, 427, 0, :west
unit :wizard, 437, 0, :west
unit :archer, 439, 0, :west
unit :sludge, 442, 0, :west
unit :thick_sludge, 443, 0, :west
unit :sludge, 446, 0, :west
unit :thick_sludge, 447, 0, :west
unit :captive, 449, 0, :west
unit :thick_sludge, 452, 0, :west
unit :archer, 472, 0, :west
unit :thick_sludge, 475, 0, :west
unit :sludge, 480, 0, :west
unit :sludge, 483, 0, :west
unit :archer, 493, 0, :west
unit :wizard, 500, 0, :west
unit :sludge, 505, 0, :west
unit :thick_sludge, 506, 0, :west
unit :archer, 507, 0, :west
unit :wizard, 516, 0, :west
unit :archer, 518, 0, :west
unit :wizard, 537, 0, :west
unit :wizard, 540, 0, :west
unit :captive, 544, 0, :west
unit :sludge, 546, 0, :west
unit :sludge, 555, 0, :west
unit :wizard, 559, 0, :west
unit :thick_sludge, 563, 0, :west
unit :archer, 570, 0, :west
unit :thick_sludge, 574, 0, :west
unit :wizard, 580, 0, :west
unit :wizard, 586, 0, :west
unit :sludge, 587, 0, :west
unit :thick_sludge, 591, 0, :west
unit :wizard, 598, 0, :west
unit :sludge, 608, 0, :west
unit :wizard, 610, 0, :west
unit :thick_sludge, 617, 0, :west
unit :wizard, 624, 0, :west
unit :archer, 625, 0, :west
unit :thick_sludge, 634, 0, :west
unit :captive, 635, 0, :west
unit :sludge, 636, 0, :west
unit :thick_sludge, 639, 0, :west
unit :captive, 640, 0, :west
unit :archer, 642, 0, :west
unit :sludge, 643, 0, :west
unit :archer, 648, 0, :west
unit :thick_sludge, 651, 0, :west
unit :sludge, 658, 0, :west
unit :captive, 659, 0, :west
unit :sludge, 662, 0, :west
unit :sludge, 663, 0, :west
unit :captive, 665, 0, :west
unit :captive, 667, 0, :west
unit :captive, 672, 0, :west
unit :archer, 673, 0, :west
unit :sludge, 675, 0, :west
unit :captive, 683, 0, :west
unit :wizard, 690, 0, :west
unit :thick_sludge, 703, 0, :west
unit :sludge, 704, 0, :west
unit :wizard, 705, 0, :west
unit :thick_sludge, 709, 0, :west
unit :captive, 713, 0, :west
unit :thick_sludge, 727, 0, :west
unit :sludge, 732, 0, :west
unit :sludge, 734, 0, :west
unit :sludge, 737, 0, :west
unit :sludge, 738, 0, :west
unit :thick_sludge, 739, 0, :west
unit :sludge, 740, 0, :west
unit :wizard, 751, 0, :west
unit :archer, 761, 0, :west
unit :captive, 762, 0, :west
unit :thick_sludge, 770, 0, :west
unit :archer, 773, 0, :west
unit :thick_sludge, 779, 0, :west
unit :thick_sludge, 780, 0, :west
unit :sludge, 785, 0, :west
unit :thick_sludge, 788, 0, :west
unit :captive, 790, 0, :west
unit :thick_sludge, 792, 0, :west
unit :thick_sludge, 793, 0, :west
unit :sludge, 794, 0, :west
unit :archer, 795, 0, :west
unit :sludge, 796, 0, :west
unit :archer, 799, 0, :west
unit :wizard, 806, 0, :west
unit :archer, 811, 0, :west
unit :archer, 815, 0, :west
unit :archer, 821, 0, :west
unit :captive, 822, 0, :west
unit :thick_sludge, 823, 0, :west
unit :captive, 824, 0, :west
unit :captive, 833, 0, :west
unit :sludge, 835, 0, :west
unit :wizard, 840, 0, :west
unit :captive, 841, 0, :west
unit :thick_sludge, 851, 0, :west
unit :sludge, 854, 0, :west
unit :sludge, 855, 0, :west
unit :thick_sludge, 858, 0, :west
unit :sludge, 859, 0, :west
unit :sludge, 866, 0, :west
unit :thick_sludge, 876, 0, :west
unit :archer, 878, 0, :west
unit :sludge, 890, 0, :west
unit :thick_sludge, 894, 0, :west
unit :thick_sludge, 897, 0, :west
