#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  CC     sa   Cs S      C     C    C  s    S s  @   CS   s    S         C S  sC C      SS  s s     S  C  aS CS s         SS   s  ss s           S a  S S    a w  SS  w          S  S      a      >    C   S   w   Cs  C               a     Cas     CSS   w  C  aS   s        ss   S s           s w w           C      s         s           s    S    S   a     w   s      C   w     w   S     a     Ca    sC  s    w    Ca S           C C   s   S    S w  aassC S s           S  Cw ws Cw sw  w   S s     w   aSS            Ss           s S  S     w S     C          s  S a     C    w  s  CS s s      |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 590
ace_score 2950
size 590, 1
stairs 193, 0

warrior 48, 0, :east

unit :captive, 2, 0, :east
unit :captive, 3, 0, :east
unit :sludge, 9, 0, :east
unit :archer, 10, 0, :east
unit :captive, 14, 0, :east
unit :sludge, 15, 0, :east
unit :thick_sludge, 17, 0, :east
unit :captive, 24, 0, :east
unit :captive, 30, 0, :east
unit :captive, 35, 0, :east
unit :sludge, 38, 0, :east
unit :thick_sludge, 43, 0, :east
unit :sludge, 45, 0, :east
unit :captive, 52, 0, :west
unit :thick_sludge, 53, 0, :west
unit :sludge, 57, 0, :west
unit :thick_sludge, 62, 0, :west
unit :captive, 72, 0, :west
unit :thick_sludge, 74, 0, :west
unit :sludge, 77, 0, :west
unit :captive, 78, 0, :west
unit :captive, 80, 0, :west
unit :thick_sludge, 87, 0, :west
unit :thick_sludge, 88, 0, :west
unit :sludge, 91, 0, :west
unit :sludge, 93, 0, :west
unit :thick_sludge, 99, 0, :west
unit :captive, 102, 0, :west
unit :archer, 105, 0, :west
unit :thick_sludge, 106, 0, :west
unit :captive, 108, 0, :west
unit :thick_sludge, 109, 0, :west
unit :sludge, 111, 0, :west
unit :thick_sludge, 121, 0, :west
unit :thick_sludge, 122, 0, :west
unit :sludge, 126, 0, :west
unit :sludge, 129, 0, :west
unit :sludge, 130, 0, :west
unit :sludge, 132, 0, :west
unit :thick_sludge, 144, 0, :west
unit :archer, 146, 0, :west
unit :thick_sludge, 149, 0, :west
unit :thick_sludge, 151, 0, :west
unit :archer, 156, 0, :west
unit :wizard, 158, 0, :west
unit :thick_sludge, 161, 0, :west
unit :thick_sludge, 162, 0, :west
unit :wizard, 165, 0, :west
unit :thick_sludge, 176, 0, :west
unit :thick_sludge, 179, 0, :west
unit :archer, 186, 0, :west
unit :captive, 198, 0, :west
unit :thick_sludge, 202, 0, :west
unit :wizard, 206, 0, :west
unit :captive, 210, 0, :west
unit :sludge, 211, 0, :west
unit :captive, 214, 0, :west
unit :archer, 230, 0, :west
unit :captive, 236, 0, :west
unit :archer, 237, 0, :west
unit :sludge, 238, 0, :west
unit :captive, 244, 0, :west
unit :thick_sludge, 245, 0, :west
unit :thick_sludge, 246, 0, :west
unit :wizard, 250, 0, :west
unit :captive, 253, 0, :west
unit :archer, 256, 0, :west
unit :thick_sludge, 257, 0, :west
unit :sludge, 261, 0, :west
unit :sludge, 270, 0, :west
unit :sludge, 271, 0, :west
unit :thick_sludge, 275, 0, :west
unit :sludge, 277, 0, :west
unit :sludge, 289, 0, :west
unit :wizard, 291, 0, :west
unit :wizard, 293, 0, :west
unit :captive, 305, 0, :west
unit :sludge, 312, 0, :west
unit :sludge, 322, 0, :west
unit :sludge, 334, 0, :west
unit :thick_sludge, 339, 0, :west
unit :thick_sludge, 344, 0, :west
unit :archer, 348, 0, :west
unit :wizard, 354, 0, :west
unit :sludge, 358, 0, :west
unit :captive, 365, 0, :west
unit :wizard, 369, 0, :west
unit :wizard, 375, 0, :west
unit :thick_sludge, 379, 0, :west
unit :archer, 385, 0, :west
unit :captive, 391, 0, :west
unit :archer, 392, 0, :west
unit :sludge, 397, 0, :west
unit :captive, 398, 0, :west
unit :sludge, 401, 0, :west
unit :wizard, 406, 0, :west
unit :captive, 411, 0, :west
unit :archer, 412, 0, :west
unit :thick_sludge, 414, 0, :west
unit :captive, 426, 0, :west
unit :captive, 428, 0, :west
unit :sludge, 432, 0, :west
unit :thick_sludge, 436, 0, :west
unit :thick_sludge, 441, 0, :west
unit :wizard, 443, 0, :west
unit :archer, 446, 0, :west
unit :archer, 447, 0, :west
unit :sludge, 448, 0, :west
unit :sludge, 449, 0, :west
unit :captive, 450, 0, :west
unit :thick_sludge, 452, 0, :west
unit :sludge, 454, 0, :west
unit :thick_sludge, 466, 0, :west
unit :captive, 469, 0, :west
unit :wizard, 470, 0, :west
unit :wizard, 472, 0, :west
unit :sludge, 473, 0, :west
unit :captive, 475, 0, :west
unit :wizard, 476, 0, :west
unit :sludge, 478, 0, :west
unit :wizard, 479, 0, :west
unit :wizard, 482, 0, :west
unit :thick_sludge, 486, 0, :west
unit :sludge, 488, 0, :west
unit :wizard, 494, 0, :west
unit :archer, 498, 0, :west
unit :thick_sludge, 499, 0, :west
unit :thick_sludge, 500, 0, :west
unit :thick_sludge, 513, 0, :west
unit :sludge, 514, 0, :west
unit :sludge, 526, 0, :west
unit :thick_sludge, 528, 0, :west
unit :thick_sludge, 531, 0, :west
unit :wizard, 537, 0, :west
unit :thick_sludge, 539, 0, :west
unit :captive, 545, 0, :west
unit :sludge, 556, 0, :west
unit :thick_sludge, 559, 0, :west
unit :archer, 561, 0, :west
unit :captive, 567, 0, :west
unit :wizard, 572, 0, :west
unit :sludge, 575, 0, :west
unit :captive, 578, 0, :west
unit :thick_sludge, 579, 0, :west
unit :sludge, 581, 0, :west
unit :sludge, 583, 0, :west
