#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     aC s  w       w s s w        C    a  C  sSSsS  SS s a    S C    CS    s w w  C   s  S  sC      s S  ss     s a        C      S   @  S   a  s   a s      a         s sw    a  w  sa    a      s   C   S  a             C        ass  Sa    C   a      S sw   S  a          S aw      wS ws    C   s            a C a         S  w SaS > s  a        w     w       w    aSa  C                         Cs    C                   S      C  C   sC a    w    w w ss a     w            w s      a  s    w              s  w  s  S C a  w        ws    s       SS  a    a  a  saC a   w Sa   C C      w       C   S     C   a w s    w   C  s  s w     w        S   aw a       Cs    a    S   S ss  a          S  C    s   aSS    S   s  a      s a aw     aa     a    aw  s    s     CC   w    S    ss  as   w    C CS   Ss SSC      sS           ss  a   a   sSC          s      C    w  w        S     w   C   C    w w       w w         SCa      S     aa    sC        w |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 943
ace_score 4715
size 943, 1
stairs 330, 0

warrior 134, 0, :east

unit :archer, 5, 0, :east
unit :captive, 6, 0, :east
unit :sludge, 8, 0, :east
unit :wizard, 11, 0, :east
unit :wizard, 19, 0, :east
unit :sludge, 21, 0, :east
unit :sludge, 23, 0, :east
unit :wizard, 25, 0, :east
unit :captive, 34, 0, :east
unit :archer, 39, 0, :east
unit :captive, 42, 0, :east
unit :sludge, 45, 0, :east
unit :thick_sludge, 46, 0, :east
unit :thick_sludge, 47, 0, :east
unit :sludge, 48, 0, :east
unit :thick_sludge, 49, 0, :east
unit :thick_sludge, 52, 0, :east
unit :thick_sludge, 53, 0, :east
unit :sludge, 55, 0, :east
unit :archer, 57, 0, :east
unit :thick_sludge, 62, 0, :east
unit :captive, 64, 0, :east
unit :captive, 69, 0, :east
unit :thick_sludge, 70, 0, :east
unit :sludge, 75, 0, :east
unit :wizard, 77, 0, :east
unit :wizard, 79, 0, :east
unit :captive, 82, 0, :east
unit :sludge, 86, 0, :east
unit :thick_sludge, 89, 0, :east
unit :sludge, 92, 0, :east
unit :captive, 93, 0, :east
unit :sludge, 100, 0, :east
unit :thick_sludge, 102, 0, :east
unit :sludge, 105, 0, :east
unit :sludge, 106, 0, :east
unit :sludge, 112, 0, :east
unit :archer, 114, 0, :east
unit :captive, 123, 0, :east
unit :thick_sludge, 130, 0, :east
unit :thick_sludge, 137, 0, :west
unit :archer, 141, 0, :west
unit :sludge, 144, 0, :west
unit :archer, 148, 0, :west
unit :sludge, 150, 0, :west
unit :archer, 157, 0, :west
unit :sludge, 167, 0, :west
unit :sludge, 169, 0, :west
unit :wizard, 170, 0, :west
unit :archer, 175, 0, :west
unit :wizard, 178, 0, :west
unit :sludge, 181, 0, :west
unit :archer, 182, 0, :west
unit :archer, 187, 0, :west
unit :sludge, 194, 0, :west
unit :captive, 198, 0, :west
unit :thick_sludge, 202, 0, :west
unit :archer, 205, 0, :west
unit :captive, 219, 0, :west
unit :archer, 228, 0, :west
unit :sludge, 229, 0, :west
unit :sludge, 230, 0, :west
unit :thick_sludge, 233, 0, :west
unit :archer, 234, 0, :west
unit :captive, 239, 0, :west
unit :archer, 243, 0, :west
unit :thick_sludge, 250, 0, :west
unit :sludge, 252, 0, :west
unit :wizard, 253, 0, :west
unit :thick_sludge, 257, 0, :west
unit :archer, 260, 0, :west
unit :thick_sludge, 271, 0, :west
unit :archer, 273, 0, :west
unit :wizard, 274, 0, :west
unit :wizard, 281, 0, :west
unit :thick_sludge, 282, 0, :west
unit :wizard, 284, 0, :west
unit :sludge, 285, 0, :west
unit :captive, 290, 0, :west
unit :sludge, 294, 0, :west
unit :archer, 307, 0, :west
unit :captive, 309, 0, :west
unit :archer, 311, 0, :west
unit :thick_sludge, 321, 0, :west
unit :wizard, 324, 0, :west
unit :thick_sludge, 326, 0, :west
unit :archer, 327, 0, :west
unit :thick_sludge, 328, 0, :west
unit :sludge, 332, 0, :west
unit :archer, 335, 0, :west
unit :wizard, 344, 0, :west
unit :wizard, 350, 0, :west
unit :wizard, 358, 0, :west
unit :archer, 363, 0, :west
unit :thick_sludge, 364, 0, :west
unit :archer, 365, 0, :west
unit :captive, 368, 0, :west
unit :captive, 394, 0, :west
unit :sludge, 395, 0, :west
unit :captive, 400, 0, :west
unit :thick_sludge, 420, 0, :west
unit :captive, 427, 0, :west
unit :captive, 430, 0, :west
unit :sludge, 434, 0, :west
unit :captive, 435, 0, :west
unit :archer, 437, 0, :west
unit :wizard, 442, 0, :west
unit :wizard, 447, 0, :west
unit :wizard, 449, 0, :west
unit :sludge, 451, 0, :west
unit :sludge, 452, 0, :west
unit :archer, 454, 0, :west
unit :wizard, 460, 0, :west
unit :wizard, 473, 0, :west
unit :sludge, 475, 0, :west
unit :archer, 482, 0, :west
unit :sludge, 485, 0, :west
unit :wizard, 490, 0, :west
unit :sludge, 505, 0, :west
unit :wizard, 508, 0, :west
unit :sludge, 511, 0, :west
unit :thick_sludge, 514, 0, :west
unit :captive, 516, 0, :west
unit :archer, 518, 0, :west
unit :wizard, 521, 0, :west
unit :wizard, 530, 0, :west
unit :sludge, 531, 0, :west
unit :sludge, 536, 0, :west
unit :thick_sludge, 544, 0, :west
unit :thick_sludge, 545, 0, :west
unit :archer, 548, 0, :west
unit :archer, 553, 0, :west
unit :archer, 556, 0, :west
unit :sludge, 559, 0, :west
unit :archer, 560, 0, :west
unit :captive, 561, 0, :west
unit :archer, 563, 0, :west
unit :wizard, 567, 0, :west
unit :thick_sludge, 569, 0, :west
unit :archer, 570, 0, :west
unit :captive, 574, 0, :west
unit :captive, 576, 0, :west
unit :wizard, 583, 0, :west
unit :captive, 591, 0, :west
unit :thick_sludge, 595, 0, :west
unit :captive, 601, 0, :west
unit :archer, 605, 0, :west
unit :wizard, 607, 0, :west
unit :sludge, 609, 0, :west
unit :wizard, 614, 0, :west
unit :captive, 618, 0, :west
unit :sludge, 621, 0, :west
unit :sludge, 624, 0, :west
unit :wizard, 626, 0, :west
unit :wizard, 632, 0, :west
unit :thick_sludge, 641, 0, :west
unit :archer, 645, 0, :west
unit :wizard, 646, 0, :west
unit :archer, 648, 0, :west
unit :captive, 656, 0, :west
unit :sludge, 657, 0, :west
unit :archer, 662, 0, :west
unit :thick_sludge, 667, 0, :west
unit :thick_sludge, 671, 0, :west
unit :sludge, 673, 0, :west
unit :sludge, 674, 0, :west
unit :archer, 677, 0, :west
unit :thick_sludge, 688, 0, :west
unit :captive, 691, 0, :west
unit :sludge, 696, 0, :west
unit :archer, 700, 0, :west
unit :thick_sludge, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :thick_sludge, 707, 0, :west
unit :sludge, 711, 0, :west
unit :archer, 714, 0, :west
unit :sludge, 721, 0, :west
unit :archer, 723, 0, :west
unit :archer, 725, 0, :west
unit :wizard, 726, 0, :west
unit :archer, 732, 0, :west
unit :archer, 733, 0, :west
unit :archer, 739, 0, :west
unit :archer, 744, 0, :west
unit :wizard, 745, 0, :west
unit :sludge, 748, 0, :west
unit :sludge, 753, 0, :west
unit :captive, 759, 0, :west
unit :captive, 760, 0, :west
unit :wizard, 764, 0, :west
unit :thick_sludge, 769, 0, :west
unit :sludge, 774, 0, :west
unit :sludge, 775, 0, :west
unit :archer, 778, 0, :west
unit :sludge, 779, 0, :west
unit :wizard, 783, 0, :west
unit :captive, 788, 0, :west
unit :captive, 790, 0, :west
unit :thick_sludge, 791, 0, :west
unit :thick_sludge, 795, 0, :west
unit :sludge, 796, 0, :west
unit :thick_sludge, 798, 0, :west
unit :thick_sludge, 799, 0, :west
unit :captive, 800, 0, :west
unit :sludge, 807, 0, :west
unit :thick_sludge, 808, 0, :west
unit :sludge, 820, 0, :west
unit :sludge, 821, 0, :west
unit :archer, 824, 0, :west
unit :archer, 828, 0, :west
unit :sludge, 832, 0, :west
unit :thick_sludge, 833, 0, :west
unit :captive, 834, 0, :west
unit :sludge, 845, 0, :west
unit :captive, 852, 0, :west
unit :wizard, 857, 0, :west
unit :wizard, 860, 0, :west
unit :thick_sludge, 869, 0, :west
unit :wizard, 875, 0, :west
unit :captive, 879, 0, :west
unit :captive, 883, 0, :west
unit :wizard, 888, 0, :west
unit :wizard, 890, 0, :west
unit :wizard, 898, 0, :west
unit :wizard, 900, 0, :west
unit :thick_sludge, 910, 0, :west
unit :captive, 911, 0, :west
unit :archer, 912, 0, :west
unit :thick_sludge, 919, 0, :west
unit :archer, 925, 0, :west
unit :archer, 926, 0, :west
unit :sludge, 931, 0, :west
unit :captive, 932, 0, :west
unit :wizard, 941, 0, :west
