#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s a aCawSS a   Ca    a  s        w             s  S          S          w        S             C  s w   w     s w   w    a     wS      s    aS ws   s     s         CS   w S     s S  s   Ca            aa      C    sS     s Cs    C   CSs    a         a aC  C       S  ss  Cw   C     w   S         s  a        s  C s aS   w s  w s  S                  aS    CC     CC a  C    w             w   S    C      C S   sS        a    w     w     aC  a  C   w          a   Cw                  w     s  s   a S>     wS CS    wC CaC Ca    a        w       aw  s aa  S s   a     S C Cw      w S   sa  w S            C w  C C  C   S    C  a C      aSC      @         s     C  S a SCSaC w  C      a|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 683
ace_score 3415
size 683, 1
stairs 499, 0

warrior 643, 0, :east

unit :sludge, 2, 0, :east
unit :archer, 4, 0, :east
unit :archer, 6, 0, :east
unit :captive, 7, 0, :east
unit :archer, 8, 0, :east
unit :wizard, 9, 0, :east
unit :thick_sludge, 10, 0, :east
unit :thick_sludge, 11, 0, :east
unit :archer, 13, 0, :east
unit :captive, 17, 0, :east
unit :archer, 18, 0, :east
unit :archer, 23, 0, :east
unit :sludge, 26, 0, :east
unit :wizard, 35, 0, :east
unit :sludge, 49, 0, :east
unit :thick_sludge, 52, 0, :east
unit :thick_sludge, 63, 0, :east
unit :wizard, 74, 0, :east
unit :thick_sludge, 83, 0, :east
unit :captive, 97, 0, :east
unit :sludge, 100, 0, :east
unit :wizard, 102, 0, :east
unit :wizard, 106, 0, :east
unit :sludge, 112, 0, :east
unit :wizard, 114, 0, :east
unit :wizard, 118, 0, :east
unit :archer, 123, 0, :east
unit :wizard, 129, 0, :east
unit :thick_sludge, 130, 0, :east
unit :sludge, 137, 0, :east
unit :archer, 142, 0, :east
unit :thick_sludge, 143, 0, :east
unit :wizard, 145, 0, :east
unit :sludge, 146, 0, :east
unit :sludge, 150, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 166, 0, :east
unit :thick_sludge, 167, 0, :east
unit :wizard, 171, 0, :east
unit :thick_sludge, 173, 0, :east
unit :sludge, 179, 0, :east
unit :thick_sludge, 181, 0, :east
unit :sludge, 184, 0, :east
unit :captive, 188, 0, :east
unit :archer, 189, 0, :east
unit :archer, 202, 0, :east
unit :archer, 203, 0, :east
unit :captive, 210, 0, :east
unit :sludge, 215, 0, :east
unit :thick_sludge, 216, 0, :east
unit :sludge, 222, 0, :east
unit :captive, 224, 0, :east
unit :sludge, 225, 0, :east
unit :captive, 230, 0, :east
unit :captive, 234, 0, :east
unit :thick_sludge, 235, 0, :east
unit :sludge, 236, 0, :east
unit :archer, 241, 0, :east
unit :archer, 251, 0, :east
unit :archer, 253, 0, :east
unit :captive, 254, 0, :east
unit :captive, 257, 0, :east
unit :thick_sludge, 265, 0, :east
unit :sludge, 268, 0, :east
unit :sludge, 269, 0, :east
unit :captive, 272, 0, :east
unit :wizard, 273, 0, :east
unit :captive, 277, 0, :east
unit :wizard, 283, 0, :east
unit :thick_sludge, 287, 0, :east
unit :sludge, 297, 0, :east
unit :archer, 300, 0, :east
unit :sludge, 309, 0, :east
unit :captive, 312, 0, :east
unit :sludge, 314, 0, :east
unit :archer, 316, 0, :east
unit :thick_sludge, 317, 0, :east
unit :wizard, 321, 0, :east
unit :sludge, 323, 0, :east
unit :wizard, 326, 0, :east
unit :sludge, 328, 0, :east
unit :thick_sludge, 331, 0, :east
unit :archer, 350, 0, :east
unit :thick_sludge, 351, 0, :east
unit :captive, 356, 0, :east
unit :captive, 357, 0, :east
unit :captive, 363, 0, :east
unit :captive, 364, 0, :east
unit :archer, 366, 0, :east
unit :captive, 369, 0, :east
unit :wizard, 374, 0, :east
unit :wizard, 388, 0, :east
unit :thick_sludge, 392, 0, :east
unit :captive, 397, 0, :east
unit :captive, 404, 0, :east
unit :thick_sludge, 406, 0, :east
unit :sludge, 410, 0, :east
unit :thick_sludge, 411, 0, :east
unit :archer, 420, 0, :east
unit :wizard, 425, 0, :east
unit :wizard, 431, 0, :east
unit :archer, 437, 0, :east
unit :captive, 438, 0, :east
unit :archer, 441, 0, :east
unit :captive, 444, 0, :east
unit :wizard, 448, 0, :east
unit :archer, 459, 0, :east
unit :captive, 463, 0, :east
unit :wizard, 464, 0, :east
unit :wizard, 483, 0, :east
unit :sludge, 489, 0, :east
unit :sludge, 492, 0, :east
unit :archer, 496, 0, :east
unit :thick_sludge, 498, 0, :east
unit :wizard, 505, 0, :east
unit :thick_sludge, 506, 0, :east
unit :captive, 508, 0, :east
unit :thick_sludge, 509, 0, :east
unit :wizard, 514, 0, :east
unit :captive, 515, 0, :east
unit :captive, 517, 0, :east
unit :archer, 518, 0, :east
unit :captive, 519, 0, :east
unit :captive, 521, 0, :east
unit :archer, 522, 0, :east
unit :archer, 527, 0, :east
unit :wizard, 536, 0, :east
unit :archer, 544, 0, :east
unit :wizard, 545, 0, :east
unit :sludge, 548, 0, :east
unit :archer, 550, 0, :east
unit :archer, 551, 0, :east
unit :thick_sludge, 554, 0, :east
unit :sludge, 556, 0, :east
unit :archer, 560, 0, :east
unit :thick_sludge, 566, 0, :east
unit :captive, 568, 0, :east
unit :captive, 570, 0, :east
unit :wizard, 571, 0, :east
unit :wizard, 578, 0, :east
unit :thick_sludge, 580, 0, :east
unit :sludge, 584, 0, :east
unit :archer, 585, 0, :east
unit :wizard, 588, 0, :east
unit :thick_sludge, 590, 0, :east
unit :captive, 603, 0, :east
unit :wizard, 605, 0, :east
unit :captive, 608, 0, :east
unit :captive, 610, 0, :east
unit :captive, 613, 0, :east
unit :thick_sludge, 617, 0, :east
unit :captive, 622, 0, :east
unit :archer, 625, 0, :east
unit :captive, 627, 0, :east
unit :archer, 634, 0, :east
unit :thick_sludge, 635, 0, :east
unit :captive, 636, 0, :east
unit :sludge, 653, 0, :west
unit :captive, 659, 0, :west
unit :thick_sludge, 662, 0, :west
unit :archer, 664, 0, :west
unit :thick_sludge, 666, 0, :west
unit :captive, 667, 0, :west
unit :thick_sludge, 668, 0, :west
unit :archer, 669, 0, :west
unit :captive, 670, 0, :west
unit :wizard, 672, 0, :west
unit :captive, 675, 0, :west
unit :archer, 682, 0, :west
