#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | Sa            C       wC    S   s   @  C  w       s    a  C SS   w a C   C   C         a S      S  Cs               C C  Sw     S  s   s  s  s          sS    s   s a w      CwS         S    w a  s     C   Cs  S  C aw C  a   w     s  C a  C      w    w  w    w s   a S       C   w  w w                   S         ws s  a      s  S aS      s       ws C w a a s C a     Ca     S       s S        a   S     sa s   S  w   s    s        s  w sa CS          S C      ssS     CSw         w  a Ss        Ca a   C        C S ws      C   S wSw  S    S       w      s   S  CsC    a   sa   a   C    w     s     a   S     SS     Ss     s s aCa   wa  C          w  s      S       a   ws      a aa         s C    Sa S                   s sS C  as w    s              a      a  s     w s S  w  s   w     aC  S  S   w     s Ss s      C  s  Cw     SS   S   w         >    w   C    a wS w       |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 877
ace_score 4385
size 877, 1
stairs 850, 0

warrior 37, 0, :east

unit :thick_sludge, 1, 0, :east
unit :archer, 2, 0, :east
unit :captive, 15, 0, :east
unit :wizard, 23, 0, :east
unit :captive, 24, 0, :east
unit :thick_sludge, 29, 0, :east
unit :sludge, 33, 0, :east
unit :captive, 40, 0, :west
unit :wizard, 43, 0, :west
unit :sludge, 51, 0, :west
unit :archer, 56, 0, :west
unit :captive, 59, 0, :west
unit :thick_sludge, 61, 0, :west
unit :thick_sludge, 62, 0, :west
unit :wizard, 66, 0, :west
unit :archer, 68, 0, :west
unit :captive, 70, 0, :west
unit :captive, 74, 0, :west
unit :captive, 78, 0, :west
unit :archer, 88, 0, :west
unit :thick_sludge, 90, 0, :west
unit :thick_sludge, 97, 0, :west
unit :captive, 100, 0, :west
unit :sludge, 101, 0, :west
unit :captive, 117, 0, :west
unit :captive, 119, 0, :west
unit :thick_sludge, 122, 0, :west
unit :wizard, 123, 0, :west
unit :thick_sludge, 129, 0, :west
unit :sludge, 132, 0, :west
unit :sludge, 136, 0, :west
unit :sludge, 139, 0, :west
unit :sludge, 142, 0, :west
unit :sludge, 153, 0, :west
unit :thick_sludge, 154, 0, :west
unit :sludge, 159, 0, :west
unit :sludge, 163, 0, :west
unit :archer, 165, 0, :west
unit :wizard, 167, 0, :west
unit :captive, 174, 0, :west
unit :wizard, 175, 0, :west
unit :thick_sludge, 176, 0, :west
unit :thick_sludge, 186, 0, :west
unit :wizard, 191, 0, :west
unit :archer, 193, 0, :west
unit :sludge, 196, 0, :west
unit :captive, 202, 0, :west
unit :captive, 206, 0, :west
unit :sludge, 207, 0, :west
unit :thick_sludge, 210, 0, :west
unit :captive, 213, 0, :west
unit :archer, 215, 0, :west
unit :wizard, 216, 0, :west
unit :captive, 218, 0, :west
unit :archer, 221, 0, :west
unit :wizard, 225, 0, :west
unit :sludge, 231, 0, :west
unit :captive, 234, 0, :west
unit :archer, 236, 0, :west
unit :captive, 239, 0, :west
unit :wizard, 246, 0, :west
unit :wizard, 251, 0, :west
unit :wizard, 254, 0, :west
unit :wizard, 259, 0, :west
unit :sludge, 261, 0, :west
unit :archer, 265, 0, :west
unit :thick_sludge, 267, 0, :west
unit :captive, 275, 0, :west
unit :wizard, 279, 0, :west
unit :wizard, 282, 0, :west
unit :wizard, 284, 0, :west
unit :thick_sludge, 304, 0, :west
unit :wizard, 314, 0, :west
unit :sludge, 315, 0, :west
unit :sludge, 317, 0, :west
unit :archer, 320, 0, :west
unit :sludge, 327, 0, :west
unit :thick_sludge, 330, 0, :west
unit :archer, 332, 0, :west
unit :thick_sludge, 333, 0, :west
unit :sludge, 340, 0, :west
unit :wizard, 348, 0, :west
unit :sludge, 349, 0, :west
unit :captive, 351, 0, :west
unit :wizard, 353, 0, :west
unit :archer, 355, 0, :west
unit :archer, 357, 0, :west
unit :sludge, 359, 0, :west
unit :captive, 361, 0, :west
unit :archer, 363, 0, :west
unit :captive, 369, 0, :west
unit :archer, 370, 0, :west
unit :thick_sludge, 376, 0, :west
unit :sludge, 384, 0, :west
unit :thick_sludge, 386, 0, :west
unit :archer, 395, 0, :west
unit :thick_sludge, 399, 0, :west
unit :sludge, 405, 0, :west
unit :archer, 406, 0, :west
unit :sludge, 408, 0, :west
unit :thick_sludge, 412, 0, :west
unit :wizard, 415, 0, :west
unit :sludge, 419, 0, :west
unit :sludge, 424, 0, :west
unit :sludge, 433, 0, :west
unit :wizard, 436, 0, :west
unit :sludge, 438, 0, :west
unit :archer, 439, 0, :west
unit :captive, 441, 0, :west
unit :thick_sludge, 442, 0, :west
unit :thick_sludge, 453, 0, :west
unit :captive, 455, 0, :west
unit :sludge, 462, 0, :west
unit :sludge, 463, 0, :west
unit :thick_sludge, 464, 0, :west
unit :captive, 470, 0, :west
unit :thick_sludge, 471, 0, :west
unit :wizard, 472, 0, :west
unit :wizard, 482, 0, :west
unit :archer, 485, 0, :west
unit :thick_sludge, 487, 0, :west
unit :sludge, 488, 0, :west
unit :captive, 497, 0, :west
unit :archer, 498, 0, :west
unit :archer, 500, 0, :west
unit :captive, 504, 0, :west
unit :captive, 513, 0, :west
unit :thick_sludge, 515, 0, :west
unit :wizard, 517, 0, :west
unit :sludge, 518, 0, :west
unit :captive, 525, 0, :west
unit :thick_sludge, 529, 0, :west
unit :wizard, 531, 0, :west
unit :thick_sludge, 532, 0, :west
unit :wizard, 533, 0, :west
unit :thick_sludge, 536, 0, :west
unit :thick_sludge, 541, 0, :west
unit :wizard, 549, 0, :west
unit :sludge, 556, 0, :west
unit :thick_sludge, 560, 0, :west
unit :captive, 563, 0, :west
unit :sludge, 564, 0, :west
unit :captive, 565, 0, :west
unit :archer, 570, 0, :west
unit :sludge, 574, 0, :west
unit :archer, 575, 0, :west
unit :archer, 579, 0, :west
unit :captive, 583, 0, :west
unit :wizard, 588, 0, :west
unit :sludge, 594, 0, :west
unit :archer, 600, 0, :west
unit :thick_sludge, 604, 0, :west
unit :thick_sludge, 610, 0, :west
unit :thick_sludge, 611, 0, :west
unit :thick_sludge, 617, 0, :west
unit :sludge, 618, 0, :west
unit :sludge, 624, 0, :west
unit :sludge, 626, 0, :west
unit :archer, 628, 0, :west
unit :captive, 629, 0, :west
unit :archer, 630, 0, :west
unit :wizard, 634, 0, :west
unit :archer, 635, 0, :west
unit :captive, 638, 0, :west
unit :wizard, 649, 0, :west
unit :sludge, 652, 0, :west
unit :thick_sludge, 659, 0, :west
unit :archer, 667, 0, :west
unit :wizard, 671, 0, :west
unit :sludge, 672, 0, :west
unit :archer, 679, 0, :west
unit :archer, 681, 0, :west
unit :archer, 682, 0, :west
unit :sludge, 692, 0, :west
unit :captive, 694, 0, :west
unit :thick_sludge, 699, 0, :west
unit :archer, 700, 0, :west
unit :thick_sludge, 702, 0, :west
unit :sludge, 722, 0, :west
unit :sludge, 724, 0, :west
unit :thick_sludge, 725, 0, :west
unit :captive, 727, 0, :west
unit :archer, 730, 0, :west
unit :sludge, 731, 0, :west
unit :wizard, 733, 0, :west
unit :sludge, 738, 0, :west
unit :archer, 753, 0, :west
unit :archer, 760, 0, :west
unit :sludge, 763, 0, :west
unit :wizard, 769, 0, :west
unit :sludge, 771, 0, :west
unit :thick_sludge, 773, 0, :west
unit :wizard, 776, 0, :west
unit :sludge, 779, 0, :west
unit :wizard, 783, 0, :west
unit :archer, 789, 0, :west
unit :captive, 790, 0, :west
unit :thick_sludge, 793, 0, :west
unit :thick_sludge, 796, 0, :west
unit :wizard, 800, 0, :west
unit :sludge, 806, 0, :west
unit :thick_sludge, 808, 0, :west
unit :sludge, 809, 0, :west
unit :sludge, 811, 0, :west
unit :captive, 818, 0, :west
unit :sludge, 821, 0, :west
unit :captive, 824, 0, :west
unit :wizard, 825, 0, :west
unit :thick_sludge, 831, 0, :west
unit :thick_sludge, 832, 0, :west
unit :thick_sludge, 836, 0, :west
unit :wizard, 840, 0, :west
unit :wizard, 855, 0, :west
unit :captive, 859, 0, :west
unit :archer, 864, 0, :west
unit :wizard, 866, 0, :west
unit :thick_sludge, 867, 0, :west
unit :wizard, 869, 0, :west
