#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |s     w     w   C    Cs   aC  sC       a  a a SCCs            C  s C   w  w    Sa   a     a  a  w  C  Ca C     a  Sw     w    w  C   Ca SC    aS        sa  sC         > w    @   s  w     w        s   S s   Ca                    a          S    w  a S  C   s a    S  w  SS       C   C        s   w  w    ss  Sa    s        S     ws    SS     C   a S    C   sC   C s s       s    a         s  w a as    S     aC     S     a    s    S    C             w    sC C   C  s    S  S a s   ws      S S C a     SC C   S  a S  C   s            w    w    w a aC w a     S  S          C  C            s a  s |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 594
ace_score 2970
size 594, 1
stairs 167, 0

warrior 174, 0, :east

unit :sludge, 0, 0, :east
unit :wizard, 6, 0, :east
unit :wizard, 12, 0, :east
unit :captive, 16, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 22, 0, :east
unit :archer, 26, 0, :east
unit :captive, 27, 0, :east
unit :sludge, 30, 0, :east
unit :captive, 31, 0, :east
unit :archer, 39, 0, :east
unit :archer, 42, 0, :east
unit :archer, 44, 0, :east
unit :thick_sludge, 46, 0, :east
unit :captive, 47, 0, :east
unit :captive, 48, 0, :east
unit :sludge, 49, 0, :east
unit :captive, 62, 0, :east
unit :sludge, 65, 0, :east
unit :captive, 67, 0, :east
unit :wizard, 71, 0, :east
unit :wizard, 74, 0, :east
unit :thick_sludge, 79, 0, :east
unit :archer, 80, 0, :east
unit :archer, 84, 0, :east
unit :archer, 90, 0, :east
unit :archer, 93, 0, :east
unit :wizard, 96, 0, :east
unit :captive, 99, 0, :east
unit :captive, 102, 0, :east
unit :archer, 103, 0, :east
unit :captive, 105, 0, :east
unit :archer, 111, 0, :east
unit :thick_sludge, 114, 0, :east
unit :wizard, 115, 0, :east
unit :wizard, 121, 0, :east
unit :wizard, 126, 0, :east
unit :captive, 129, 0, :east
unit :captive, 133, 0, :east
unit :archer, 134, 0, :east
unit :thick_sludge, 136, 0, :east
unit :captive, 137, 0, :east
unit :archer, 142, 0, :east
unit :thick_sludge, 143, 0, :east
unit :sludge, 152, 0, :east
unit :archer, 153, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 157, 0, :east
unit :wizard, 169, 0, :east
unit :sludge, 178, 0, :west
unit :wizard, 181, 0, :west
unit :wizard, 187, 0, :west
unit :sludge, 196, 0, :west
unit :thick_sludge, 200, 0, :west
unit :sludge, 202, 0, :west
unit :captive, 206, 0, :west
unit :archer, 207, 0, :west
unit :archer, 228, 0, :west
unit :thick_sludge, 239, 0, :west
unit :wizard, 244, 0, :west
unit :archer, 247, 0, :west
unit :thick_sludge, 249, 0, :west
unit :captive, 252, 0, :west
unit :sludge, 256, 0, :west
unit :archer, 258, 0, :west
unit :thick_sludge, 263, 0, :west
unit :wizard, 266, 0, :west
unit :thick_sludge, 269, 0, :west
unit :thick_sludge, 270, 0, :west
unit :captive, 278, 0, :west
unit :captive, 282, 0, :west
unit :sludge, 291, 0, :west
unit :wizard, 295, 0, :west
unit :wizard, 298, 0, :west
unit :sludge, 303, 0, :west
unit :sludge, 304, 0, :west
unit :thick_sludge, 307, 0, :west
unit :archer, 308, 0, :west
unit :sludge, 313, 0, :west
unit :thick_sludge, 322, 0, :west
unit :wizard, 328, 0, :west
unit :sludge, 329, 0, :west
unit :thick_sludge, 334, 0, :west
unit :thick_sludge, 335, 0, :west
unit :captive, 341, 0, :west
unit :archer, 345, 0, :west
unit :thick_sludge, 347, 0, :west
unit :captive, 352, 0, :west
unit :sludge, 356, 0, :west
unit :captive, 357, 0, :west
unit :captive, 361, 0, :west
unit :sludge, 363, 0, :west
unit :sludge, 365, 0, :west
unit :sludge, 373, 0, :west
unit :archer, 378, 0, :west
unit :sludge, 388, 0, :west
unit :wizard, 391, 0, :west
unit :archer, 393, 0, :west
unit :archer, 395, 0, :west
unit :sludge, 396, 0, :west
unit :thick_sludge, 401, 0, :west
unit :archer, 407, 0, :west
unit :captive, 408, 0, :west
unit :thick_sludge, 414, 0, :west
unit :archer, 420, 0, :west
unit :sludge, 425, 0, :west
unit :thick_sludge, 430, 0, :west
unit :captive, 435, 0, :west
unit :wizard, 449, 0, :west
unit :sludge, 454, 0, :west
unit :captive, 455, 0, :west
unit :captive, 457, 0, :west
unit :captive, 461, 0, :west
unit :sludge, 464, 0, :west
unit :thick_sludge, 469, 0, :west
unit :thick_sludge, 472, 0, :west
unit :archer, 474, 0, :west
unit :sludge, 476, 0, :west
unit :wizard, 480, 0, :west
unit :sludge, 481, 0, :west
unit :thick_sludge, 488, 0, :west
unit :thick_sludge, 490, 0, :west
unit :captive, 492, 0, :west
unit :archer, 494, 0, :west
unit :thick_sludge, 500, 0, :west
unit :captive, 501, 0, :west
unit :captive, 503, 0, :west
unit :thick_sludge, 507, 0, :west
unit :archer, 510, 0, :west
unit :thick_sludge, 512, 0, :west
unit :captive, 515, 0, :west
unit :sludge, 519, 0, :west
unit :wizard, 532, 0, :west
unit :wizard, 537, 0, :west
unit :wizard, 542, 0, :west
unit :archer, 544, 0, :west
unit :archer, 546, 0, :west
unit :captive, 547, 0, :west
unit :wizard, 549, 0, :west
unit :archer, 551, 0, :west
unit :thick_sludge, 557, 0, :west
unit :thick_sludge, 560, 0, :west
unit :captive, 571, 0, :west
unit :captive, 574, 0, :west
unit :sludge, 587, 0, :west
unit :archer, 589, 0, :west
unit :sludge, 592, 0, :west
