#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   s         s       C            a     S a     w s    a  w    w  SS  a w        w    C   S s   s    s w        S s             C  w Cs  S C w w s a       w      a    a aa  S       s   S Ss   ws SaSw C   aC          sa a ss   s    asC      w    wC      C      C        w     s   w         a            a        S  Ca         S       w  C s  w w          w     s       CCsC   aS    Ca      s   S       w S C  SC   C       Ca     C w    w        S sss  S   C w  C  @         w         s    aa  S         s S  S     s    S w   w    S     Cs  sa     s      C  S C  s     aSw        > a         s  C   wCCs   S        w S     s      a s ss  sw w  S      ss    wa sw      s       s      a  ws  S      a  S   s     sC  sw             sssw as        Ss    C S     S w    w    Ca        SC Ca |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 784
ace_score 3920
size 784, 1
stairs 578, 0

warrior 463, 0, :east

unit :sludge, 3, 0, :east
unit :sludge, 13, 0, :east
unit :captive, 21, 0, :east
unit :archer, 34, 0, :east
unit :thick_sludge, 40, 0, :east
unit :archer, 42, 0, :east
unit :wizard, 48, 0, :east
unit :sludge, 50, 0, :east
unit :archer, 55, 0, :east
unit :wizard, 58, 0, :east
unit :wizard, 63, 0, :east
unit :thick_sludge, 66, 0, :east
unit :thick_sludge, 67, 0, :east
unit :archer, 70, 0, :east
unit :wizard, 72, 0, :east
unit :wizard, 81, 0, :east
unit :captive, 86, 0, :east
unit :thick_sludge, 90, 0, :east
unit :sludge, 92, 0, :east
unit :sludge, 96, 0, :east
unit :sludge, 101, 0, :east
unit :wizard, 103, 0, :east
unit :thick_sludge, 112, 0, :east
unit :sludge, 114, 0, :east
unit :captive, 128, 0, :east
unit :wizard, 131, 0, :east
unit :captive, 133, 0, :east
unit :sludge, 134, 0, :east
unit :thick_sludge, 137, 0, :east
unit :captive, 139, 0, :east
unit :wizard, 141, 0, :east
unit :wizard, 143, 0, :east
unit :sludge, 145, 0, :east
unit :archer, 147, 0, :east
unit :wizard, 155, 0, :east
unit :archer, 162, 0, :east
unit :archer, 167, 0, :east
unit :archer, 169, 0, :east
unit :archer, 170, 0, :east
unit :thick_sludge, 173, 0, :east
unit :sludge, 181, 0, :east
unit :thick_sludge, 185, 0, :east
unit :thick_sludge, 187, 0, :east
unit :sludge, 188, 0, :east
unit :wizard, 192, 0, :east
unit :sludge, 193, 0, :east
unit :thick_sludge, 195, 0, :east
unit :archer, 196, 0, :east
unit :thick_sludge, 197, 0, :east
unit :wizard, 198, 0, :east
unit :captive, 200, 0, :east
unit :archer, 204, 0, :east
unit :captive, 205, 0, :east
unit :sludge, 216, 0, :east
unit :archer, 217, 0, :east
unit :archer, 219, 0, :east
unit :sludge, 221, 0, :east
unit :sludge, 222, 0, :east
unit :sludge, 226, 0, :east
unit :archer, 231, 0, :east
unit :sludge, 232, 0, :east
unit :captive, 233, 0, :east
unit :wizard, 240, 0, :east
unit :wizard, 245, 0, :east
unit :captive, 246, 0, :east
unit :captive, 253, 0, :east
unit :captive, 260, 0, :east
unit :wizard, 269, 0, :east
unit :sludge, 275, 0, :east
unit :wizard, 279, 0, :east
unit :archer, 289, 0, :east
unit :archer, 302, 0, :east
unit :thick_sludge, 311, 0, :east
unit :captive, 314, 0, :east
unit :archer, 315, 0, :east
unit :thick_sludge, 325, 0, :east
unit :wizard, 333, 0, :east
unit :captive, 336, 0, :east
unit :sludge, 338, 0, :east
unit :wizard, 341, 0, :east
unit :wizard, 343, 0, :east
unit :wizard, 354, 0, :east
unit :sludge, 360, 0, :east
unit :captive, 368, 0, :east
unit :captive, 369, 0, :east
unit :sludge, 370, 0, :east
unit :captive, 371, 0, :east
unit :archer, 375, 0, :east
unit :thick_sludge, 376, 0, :east
unit :captive, 381, 0, :east
unit :archer, 382, 0, :east
unit :sludge, 389, 0, :east
unit :thick_sludge, 393, 0, :east
unit :wizard, 401, 0, :east
unit :thick_sludge, 403, 0, :east
unit :captive, 405, 0, :east
unit :thick_sludge, 408, 0, :east
unit :captive, 409, 0, :east
unit :captive, 413, 0, :east
unit :captive, 421, 0, :east
unit :archer, 422, 0, :east
unit :captive, 428, 0, :east
unit :wizard, 430, 0, :east
unit :wizard, 435, 0, :east
unit :thick_sludge, 444, 0, :east
unit :sludge, 446, 0, :east
unit :sludge, 447, 0, :east
unit :sludge, 448, 0, :east
unit :thick_sludge, 451, 0, :east
unit :captive, 455, 0, :east
unit :wizard, 457, 0, :east
unit :captive, 460, 0, :east
unit :wizard, 473, 0, :west
unit :sludge, 483, 0, :west
unit :archer, 488, 0, :west
unit :archer, 489, 0, :west
unit :thick_sludge, 492, 0, :west
unit :sludge, 502, 0, :west
unit :thick_sludge, 504, 0, :west
unit :thick_sludge, 507, 0, :west
unit :sludge, 513, 0, :west
unit :thick_sludge, 518, 0, :west
unit :wizard, 520, 0, :west
unit :wizard, 524, 0, :west
unit :thick_sludge, 529, 0, :west
unit :captive, 535, 0, :west
unit :sludge, 536, 0, :west
unit :sludge, 539, 0, :west
unit :archer, 540, 0, :west
unit :sludge, 546, 0, :west
unit :captive, 553, 0, :west
unit :thick_sludge, 556, 0, :west
unit :captive, 558, 0, :west
unit :sludge, 561, 0, :west
unit :archer, 567, 0, :west
unit :thick_sludge, 568, 0, :west
unit :wizard, 569, 0, :west
unit :archer, 580, 0, :west
unit :sludge, 590, 0, :west
unit :captive, 593, 0, :west
unit :wizard, 597, 0, :west
unit :captive, 598, 0, :west
unit :captive, 599, 0, :west
unit :sludge, 600, 0, :west
unit :thick_sludge, 604, 0, :west
unit :wizard, 613, 0, :west
unit :thick_sludge, 615, 0, :west
unit :sludge, 621, 0, :west
unit :archer, 628, 0, :west
unit :sludge, 630, 0, :west
unit :sludge, 632, 0, :west
unit :sludge, 633, 0, :west
unit :sludge, 636, 0, :west
unit :wizard, 637, 0, :west
unit :wizard, 639, 0, :west
unit :thick_sludge, 642, 0, :west
unit :sludge, 649, 0, :west
unit :sludge, 650, 0, :west
unit :wizard, 655, 0, :west
unit :archer, 656, 0, :west
unit :sludge, 658, 0, :west
unit :wizard, 659, 0, :west
unit :sludge, 666, 0, :west
unit :sludge, 674, 0, :west
unit :archer, 681, 0, :west
unit :wizard, 684, 0, :west
unit :sludge, 685, 0, :west
unit :thick_sludge, 688, 0, :west
unit :archer, 695, 0, :west
unit :thick_sludge, 698, 0, :west
unit :sludge, 702, 0, :west
unit :sludge, 708, 0, :west
unit :captive, 709, 0, :west
unit :sludge, 712, 0, :west
unit :wizard, 713, 0, :west
unit :sludge, 727, 0, :west
unit :sludge, 728, 0, :west
unit :sludge, 729, 0, :west
unit :wizard, 730, 0, :west
unit :archer, 732, 0, :west
unit :sludge, 733, 0, :west
unit :thick_sludge, 742, 0, :west
unit :sludge, 743, 0, :west
unit :captive, 748, 0, :west
unit :thick_sludge, 750, 0, :west
unit :thick_sludge, 756, 0, :west
unit :wizard, 758, 0, :west
unit :wizard, 763, 0, :west
unit :captive, 768, 0, :west
unit :archer, 769, 0, :west
unit :thick_sludge, 778, 0, :west
unit :captive, 779, 0, :west
unit :captive, 781, 0, :west
unit :archer, 782, 0, :west
