#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  a      S  S  SSS     S  wS       w w a         a      w  aS wS       a     a    C SwCa S   s a w      sCs sCa  w w a     w    s   S         a                  C   w      w  a   a S w     w  C          s w        aSsSsC     s     a C       s  s        w   C S  C w    s  S w S     as    S  a sS  s   s    S S a   C  C    ss    CS   S   s      C w  w   C    w   CC CC Cs  w  wa                 SS    sS S  s     a     s Cw  w   S    @      a    w  s     w       a     s   w      a  s a  w    CS     a   S            wa  aC       s w w  w S   s     s  s s SaS          S  S  w  C         a a  a w      a    C     C    s    w   a    >   CC   w   a  sC   w  w        w  w       C w  S  w  S          a       S C  C  w       S  a  aS        s  a    C  C w     s         s wC     C     w s    S S    aa  CC S      s wsa   a  C     C                  sC      aS   C      C       S   s  Ss            C    S C       w    sS as    S         C        Sa  S   w  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 953
ace_score 4765
size 953, 1
stairs 631, 0

warrior 433, 0, :east

unit :archer, 2, 0, :east
unit :thick_sludge, 9, 0, :east
unit :thick_sludge, 12, 0, :east
unit :thick_sludge, 15, 0, :east
unit :thick_sludge, 16, 0, :east
unit :thick_sludge, 17, 0, :east
unit :thick_sludge, 23, 0, :east
unit :wizard, 26, 0, :east
unit :thick_sludge, 27, 0, :east
unit :wizard, 35, 0, :east
unit :wizard, 37, 0, :east
unit :archer, 39, 0, :east
unit :archer, 49, 0, :east
unit :wizard, 56, 0, :east
unit :archer, 59, 0, :east
unit :thick_sludge, 60, 0, :east
unit :wizard, 62, 0, :east
unit :thick_sludge, 63, 0, :east
unit :archer, 71, 0, :east
unit :archer, 77, 0, :east
unit :captive, 82, 0, :east
unit :thick_sludge, 84, 0, :east
unit :wizard, 85, 0, :east
unit :captive, 86, 0, :east
unit :archer, 87, 0, :east
unit :thick_sludge, 89, 0, :east
unit :sludge, 93, 0, :east
unit :archer, 95, 0, :east
unit :wizard, 97, 0, :east
unit :sludge, 104, 0, :east
unit :captive, 105, 0, :east
unit :sludge, 106, 0, :east
unit :sludge, 108, 0, :east
unit :captive, 109, 0, :east
unit :archer, 110, 0, :east
unit :wizard, 113, 0, :east
unit :wizard, 115, 0, :east
unit :archer, 117, 0, :east
unit :wizard, 123, 0, :east
unit :sludge, 128, 0, :east
unit :thick_sludge, 132, 0, :east
unit :archer, 142, 0, :east
unit :captive, 161, 0, :east
unit :wizard, 165, 0, :east
unit :wizard, 172, 0, :east
unit :archer, 175, 0, :east
unit :archer, 179, 0, :east
unit :thick_sludge, 181, 0, :east
unit :wizard, 183, 0, :east
unit :wizard, 189, 0, :east
unit :captive, 192, 0, :east
unit :sludge, 203, 0, :east
unit :wizard, 205, 0, :east
unit :archer, 214, 0, :east
unit :thick_sludge, 215, 0, :east
unit :sludge, 216, 0, :east
unit :thick_sludge, 217, 0, :east
unit :sludge, 218, 0, :east
unit :captive, 219, 0, :east
unit :sludge, 225, 0, :east
unit :archer, 231, 0, :east
unit :captive, 233, 0, :east
unit :sludge, 241, 0, :east
unit :sludge, 244, 0, :east
unit :wizard, 253, 0, :east
unit :captive, 257, 0, :east
unit :thick_sludge, 259, 0, :east
unit :captive, 262, 0, :east
unit :wizard, 264, 0, :east
unit :sludge, 269, 0, :east
unit :thick_sludge, 272, 0, :east
unit :wizard, 274, 0, :east
unit :thick_sludge, 276, 0, :east
unit :archer, 282, 0, :east
unit :sludge, 283, 0, :east
unit :thick_sludge, 288, 0, :east
unit :archer, 291, 0, :east
unit :sludge, 293, 0, :east
unit :thick_sludge, 294, 0, :east
unit :sludge, 297, 0, :east
unit :sludge, 301, 0, :east
unit :thick_sludge, 306, 0, :east
unit :thick_sludge, 308, 0, :east
unit :archer, 310, 0, :east
unit :captive, 314, 0, :east
unit :captive, 317, 0, :east
unit :sludge, 322, 0, :east
unit :sludge, 323, 0, :east
unit :captive, 328, 0, :east
unit :thick_sludge, 329, 0, :east
unit :thick_sludge, 333, 0, :east
unit :sludge, 337, 0, :east
unit :captive, 344, 0, :east
unit :wizard, 346, 0, :east
unit :wizard, 349, 0, :east
unit :captive, 353, 0, :east
unit :wizard, 358, 0, :east
unit :captive, 362, 0, :east
unit :captive, 363, 0, :east
unit :captive, 365, 0, :east
unit :captive, 366, 0, :east
unit :captive, 368, 0, :east
unit :sludge, 369, 0, :east
unit :wizard, 372, 0, :east
unit :wizard, 375, 0, :east
unit :archer, 376, 0, :east
unit :thick_sludge, 394, 0, :east
unit :thick_sludge, 395, 0, :east
unit :sludge, 400, 0, :east
unit :thick_sludge, 401, 0, :east
unit :thick_sludge, 403, 0, :east
unit :sludge, 406, 0, :east
unit :archer, 412, 0, :east
unit :sludge, 418, 0, :east
unit :captive, 420, 0, :east
unit :wizard, 421, 0, :east
unit :wizard, 424, 0, :east
unit :thick_sludge, 428, 0, :east
unit :archer, 440, 0, :west
unit :wizard, 445, 0, :west
unit :sludge, 448, 0, :west
unit :wizard, 454, 0, :west
unit :archer, 462, 0, :west
unit :sludge, 468, 0, :west
unit :wizard, 472, 0, :west
unit :archer, 479, 0, :west
unit :sludge, 482, 0, :west
unit :archer, 484, 0, :west
unit :wizard, 487, 0, :west
unit :captive, 492, 0, :west
unit :thick_sludge, 493, 0, :west
unit :archer, 499, 0, :west
unit :thick_sludge, 503, 0, :west
unit :wizard, 516, 0, :west
unit :archer, 517, 0, :west
unit :archer, 520, 0, :west
unit :captive, 521, 0, :west
unit :sludge, 529, 0, :west
unit :wizard, 531, 0, :west
unit :wizard, 533, 0, :west
unit :wizard, 536, 0, :west
unit :thick_sludge, 538, 0, :west
unit :sludge, 542, 0, :west
unit :sludge, 548, 0, :west
unit :sludge, 551, 0, :west
unit :sludge, 553, 0, :west
unit :thick_sludge, 555, 0, :west
unit :archer, 556, 0, :west
unit :thick_sludge, 557, 0, :west
unit :thick_sludge, 568, 0, :west
unit :thick_sludge, 571, 0, :west
unit :wizard, 574, 0, :west
unit :captive, 577, 0, :west
unit :archer, 587, 0, :west
unit :archer, 589, 0, :west
unit :archer, 592, 0, :west
unit :wizard, 594, 0, :west
unit :archer, 601, 0, :west
unit :captive, 606, 0, :west
unit :captive, 612, 0, :west
unit :sludge, 617, 0, :west
unit :wizard, 622, 0, :west
unit :archer, 626, 0, :west
unit :captive, 635, 0, :west
unit :captive, 636, 0, :west
unit :wizard, 640, 0, :west
unit :archer, 644, 0, :west
unit :sludge, 647, 0, :west
unit :captive, 648, 0, :west
unit :wizard, 652, 0, :west
unit :wizard, 655, 0, :west
unit :wizard, 664, 0, :west
unit :wizard, 667, 0, :west
unit :captive, 675, 0, :west
unit :wizard, 677, 0, :west
unit :thick_sludge, 680, 0, :west
unit :wizard, 683, 0, :west
unit :thick_sludge, 686, 0, :west
unit :archer, 697, 0, :west
unit :thick_sludge, 705, 0, :west
unit :captive, 707, 0, :west
unit :captive, 710, 0, :west
unit :wizard, 713, 0, :west
unit :thick_sludge, 721, 0, :west
unit :archer, 724, 0, :west
unit :archer, 727, 0, :west
unit :thick_sludge, 728, 0, :west
unit :sludge, 737, 0, :west
unit :archer, 740, 0, :west
unit :captive, 745, 0, :west
unit :captive, 748, 0, :west
unit :wizard, 750, 0, :west
unit :sludge, 756, 0, :west
unit :sludge, 766, 0, :west
unit :wizard, 768, 0, :west
unit :captive, 769, 0, :west
unit :captive, 775, 0, :west
unit :wizard, 781, 0, :west
unit :sludge, 783, 0, :west
unit :thick_sludge, 788, 0, :west
unit :thick_sludge, 790, 0, :west
unit :archer, 795, 0, :west
unit :archer, 796, 0, :west
unit :captive, 799, 0, :west
unit :captive, 800, 0, :west
unit :thick_sludge, 802, 0, :west
unit :sludge, 809, 0, :west
unit :wizard, 811, 0, :west
unit :sludge, 812, 0, :west
unit :archer, 813, 0, :west
unit :archer, 817, 0, :west
unit :captive, 820, 0, :west
unit :captive, 826, 0, :west
unit :sludge, 845, 0, :west
unit :captive, 846, 0, :west
unit :archer, 853, 0, :west
unit :thick_sludge, 854, 0, :west
unit :captive, 858, 0, :west
unit :captive, 865, 0, :west
unit :thick_sludge, 873, 0, :west
unit :sludge, 877, 0, :west
unit :thick_sludge, 880, 0, :west
unit :sludge, 881, 0, :west
unit :captive, 894, 0, :west
unit :thick_sludge, 899, 0, :west
unit :captive, 901, 0, :west
unit :wizard, 909, 0, :west
unit :sludge, 914, 0, :west
unit :thick_sludge, 915, 0, :west
unit :archer, 917, 0, :west
unit :sludge, 918, 0, :west
unit :thick_sludge, 923, 0, :west
unit :captive, 933, 0, :west
unit :thick_sludge, 942, 0, :west
unit :archer, 943, 0, :west
unit :thick_sludge, 946, 0, :west
unit :wizard, 950, 0, :west
