#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    C   s a            C   a   wa   Ss S     CS    S s w   S   w sS    S  s  C  a         C  Sw   a  sw S      @         w  w sw    s    a     sS     a        C S ss    >S s  S  w  a  aw       w    C            w                 C     s   s  C s   aaS           w   sC  a    w      S  ss         a      a    S  CSC       s a  a        w      s  s      S  C    C a       s s       SaS    w C  s w  wC ss  C   C   a a w  C  s    s   a S  S w       S    S CC  w aw s   w   sss S           w     a S        w w                 s   a    S     w   S    s           a   Cs  C awC    Cs  S|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 581
ace_score 2905
size 581, 1
stairs 169, 0

warrior 111, 0, :east

unit :captive, 4, 0, :east
unit :sludge, 8, 0, :east
unit :archer, 10, 0, :east
unit :captive, 23, 0, :east
unit :archer, 27, 0, :east
unit :wizard, 31, 0, :east
unit :archer, 32, 0, :east
unit :thick_sludge, 36, 0, :east
unit :sludge, 37, 0, :east
unit :thick_sludge, 39, 0, :east
unit :captive, 45, 0, :east
unit :thick_sludge, 46, 0, :east
unit :thick_sludge, 51, 0, :east
unit :sludge, 53, 0, :east
unit :wizard, 55, 0, :east
unit :thick_sludge, 59, 0, :east
unit :wizard, 63, 0, :east
unit :sludge, 65, 0, :east
unit :thick_sludge, 66, 0, :east
unit :thick_sludge, 71, 0, :east
unit :sludge, 74, 0, :east
unit :captive, 77, 0, :east
unit :archer, 80, 0, :east
unit :captive, 90, 0, :east
unit :thick_sludge, 93, 0, :east
unit :wizard, 94, 0, :east
unit :archer, 98, 0, :east
unit :sludge, 101, 0, :east
unit :wizard, 102, 0, :east
unit :thick_sludge, 104, 0, :east
unit :wizard, 121, 0, :west
unit :wizard, 124, 0, :west
unit :sludge, 126, 0, :west
unit :wizard, 127, 0, :west
unit :sludge, 132, 0, :west
unit :archer, 137, 0, :west
unit :sludge, 143, 0, :west
unit :thick_sludge, 144, 0, :west
unit :archer, 150, 0, :west
unit :captive, 159, 0, :west
unit :thick_sludge, 161, 0, :west
unit :sludge, 163, 0, :west
unit :sludge, 164, 0, :west
unit :thick_sludge, 170, 0, :west
unit :sludge, 172, 0, :west
unit :thick_sludge, 175, 0, :west
unit :wizard, 178, 0, :west
unit :archer, 181, 0, :west
unit :archer, 184, 0, :west
unit :wizard, 185, 0, :west
unit :wizard, 193, 0, :west
unit :captive, 198, 0, :west
unit :wizard, 211, 0, :west
unit :captive, 229, 0, :west
unit :sludge, 235, 0, :west
unit :sludge, 239, 0, :west
unit :captive, 242, 0, :west
unit :sludge, 244, 0, :west
unit :archer, 248, 0, :west
unit :archer, 249, 0, :west
unit :thick_sludge, 250, 0, :west
unit :wizard, 262, 0, :west
unit :sludge, 266, 0, :west
unit :captive, 267, 0, :west
unit :archer, 270, 0, :west
unit :wizard, 275, 0, :west
unit :thick_sludge, 282, 0, :west
unit :sludge, 285, 0, :west
unit :sludge, 286, 0, :west
unit :archer, 296, 0, :west
unit :archer, 303, 0, :west
unit :thick_sludge, 308, 0, :west
unit :captive, 311, 0, :west
unit :thick_sludge, 312, 0, :west
unit :captive, 313, 0, :west
unit :sludge, 321, 0, :west
unit :archer, 323, 0, :west
unit :archer, 326, 0, :west
unit :wizard, 335, 0, :west
unit :sludge, 342, 0, :west
unit :sludge, 345, 0, :west
unit :thick_sludge, 352, 0, :west
unit :captive, 355, 0, :west
unit :captive, 360, 0, :west
unit :archer, 362, 0, :west
unit :sludge, 370, 0, :west
unit :sludge, 372, 0, :west
unit :thick_sludge, 380, 0, :west
unit :archer, 381, 0, :west
unit :thick_sludge, 382, 0, :west
unit :wizard, 387, 0, :west
unit :captive, 389, 0, :west
unit :sludge, 392, 0, :west
unit :wizard, 394, 0, :west
unit :wizard, 397, 0, :west
unit :captive, 398, 0, :west
unit :sludge, 400, 0, :west
unit :sludge, 401, 0, :west
unit :captive, 404, 0, :west
unit :captive, 408, 0, :west
unit :archer, 412, 0, :west
unit :archer, 414, 0, :west
unit :wizard, 416, 0, :west
unit :captive, 419, 0, :west
unit :sludge, 422, 0, :west
unit :sludge, 427, 0, :west
unit :archer, 431, 0, :west
unit :thick_sludge, 433, 0, :west
unit :thick_sludge, 436, 0, :west
unit :wizard, 438, 0, :west
unit :thick_sludge, 446, 0, :west
unit :thick_sludge, 451, 0, :west
unit :captive, 453, 0, :west
unit :captive, 454, 0, :west
unit :wizard, 457, 0, :west
unit :archer, 459, 0, :west
unit :wizard, 460, 0, :west
unit :sludge, 462, 0, :west
unit :wizard, 466, 0, :west
unit :sludge, 470, 0, :west
unit :sludge, 471, 0, :west
unit :sludge, 472, 0, :west
unit :thick_sludge, 474, 0, :west
unit :wizard, 486, 0, :west
unit :archer, 492, 0, :west
unit :thick_sludge, 494, 0, :west
unit :wizard, 503, 0, :west
unit :wizard, 505, 0, :west
unit :sludge, 523, 0, :west
unit :archer, 527, 0, :west
unit :thick_sludge, 532, 0, :west
unit :wizard, 538, 0, :west
unit :thick_sludge, 542, 0, :west
unit :sludge, 547, 0, :west
unit :archer, 559, 0, :west
unit :captive, 563, 0, :west
unit :sludge, 564, 0, :west
unit :captive, 567, 0, :west
unit :archer, 569, 0, :west
unit :wizard, 570, 0, :west
unit :captive, 571, 0, :west
unit :captive, 576, 0, :west
unit :sludge, 577, 0, :west
unit :thick_sludge, 580, 0, :west
