#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  SC      a as       w       a  a    a a  C        s   SC w   a        w  S       w      S wS          a S       aCS       S   S w             C   s      S sw      C      C a        a S  s  >      sSs S    a   CC  CC a   Ca  s w      w S w        a      s  aSa w   C  w    s  a  s  w   a    @   s   a    S          S     S aCa     a   s       s   Ca      aS s     C  Ss       C        s a s   w   w       C s  w C CC S           C S   w  SC   a    s   S      a s s     w    awCCS        sS  w S C    w  ws s C C               a a  Csw w  a w S w        w  s a    w  Sw w CC  S Ca   w    S       w       s    sC Ss  s     S a C   w                 a    S      a         C  S       SC S  S      C                  w s   C  aS         w     C             SC s    S sss   a   s   s   C       Ca    Sa  S  C   w   ss s    C   sS        ssC      S       w s      w S      w    Sa C    SCaa C  C  aC   w    a                 Ss   S         S   w       C  w      aa         C Ca     sCs  w         a|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 991
ace_score 4955
size 991, 1
stairs 190, 0

warrior 291, 0, :east

unit :thick_sludge, 2, 0, :east
unit :captive, 3, 0, :east
unit :archer, 10, 0, :east
unit :archer, 12, 0, :east
unit :sludge, 13, 0, :east
unit :wizard, 21, 0, :east
unit :archer, 29, 0, :east
unit :archer, 32, 0, :east
unit :archer, 37, 0, :east
unit :archer, 39, 0, :east
unit :captive, 42, 0, :east
unit :sludge, 51, 0, :east
unit :thick_sludge, 55, 0, :east
unit :captive, 56, 0, :east
unit :wizard, 58, 0, :east
unit :archer, 62, 0, :east
unit :wizard, 71, 0, :east
unit :thick_sludge, 74, 0, :east
unit :wizard, 82, 0, :east
unit :thick_sludge, 89, 0, :east
unit :wizard, 91, 0, :east
unit :thick_sludge, 92, 0, :east
unit :archer, 103, 0, :east
unit :thick_sludge, 105, 0, :east
unit :archer, 113, 0, :east
unit :captive, 114, 0, :east
unit :thick_sludge, 115, 0, :east
unit :thick_sludge, 123, 0, :east
unit :thick_sludge, 127, 0, :east
unit :wizard, 129, 0, :east
unit :captive, 143, 0, :east
unit :sludge, 147, 0, :east
unit :thick_sludge, 154, 0, :east
unit :sludge, 156, 0, :east
unit :wizard, 157, 0, :east
unit :captive, 164, 0, :east
unit :captive, 171, 0, :east
unit :archer, 173, 0, :east
unit :archer, 182, 0, :east
unit :thick_sludge, 184, 0, :east
unit :sludge, 187, 0, :east
unit :sludge, 197, 0, :east
unit :thick_sludge, 198, 0, :east
unit :sludge, 199, 0, :east
unit :thick_sludge, 201, 0, :east
unit :archer, 206, 0, :east
unit :captive, 210, 0, :east
unit :captive, 211, 0, :east
unit :captive, 214, 0, :east
unit :captive, 215, 0, :east
unit :archer, 217, 0, :east
unit :captive, 221, 0, :east
unit :archer, 222, 0, :east
unit :sludge, 225, 0, :east
unit :wizard, 227, 0, :east
unit :wizard, 234, 0, :east
unit :thick_sludge, 236, 0, :east
unit :wizard, 238, 0, :east
unit :archer, 247, 0, :east
unit :sludge, 254, 0, :east
unit :archer, 257, 0, :east
unit :thick_sludge, 258, 0, :east
unit :archer, 259, 0, :east
unit :wizard, 261, 0, :east
unit :captive, 265, 0, :east
unit :wizard, 268, 0, :east
unit :sludge, 273, 0, :east
unit :archer, 276, 0, :east
unit :sludge, 279, 0, :east
unit :wizard, 282, 0, :east
unit :archer, 286, 0, :east
unit :sludge, 295, 0, :west
unit :archer, 299, 0, :west
unit :thick_sludge, 304, 0, :west
unit :thick_sludge, 315, 0, :west
unit :thick_sludge, 321, 0, :west
unit :archer, 323, 0, :west
unit :captive, 324, 0, :west
unit :archer, 325, 0, :west
unit :archer, 331, 0, :west
unit :sludge, 335, 0, :west
unit :sludge, 343, 0, :west
unit :captive, 347, 0, :west
unit :archer, 348, 0, :west
unit :archer, 355, 0, :west
unit :thick_sludge, 356, 0, :west
unit :sludge, 358, 0, :west
unit :captive, 364, 0, :west
unit :thick_sludge, 367, 0, :west
unit :sludge, 368, 0, :west
unit :captive, 376, 0, :west
unit :sludge, 385, 0, :west
unit :archer, 387, 0, :west
unit :sludge, 389, 0, :west
unit :wizard, 393, 0, :west
unit :wizard, 397, 0, :west
unit :captive, 405, 0, :west
unit :sludge, 407, 0, :west
unit :wizard, 410, 0, :west
unit :captive, 412, 0, :west
unit :captive, 414, 0, :west
unit :captive, 415, 0, :west
unit :thick_sludge, 417, 0, :west
unit :captive, 429, 0, :west
unit :thick_sludge, 431, 0, :west
unit :wizard, 435, 0, :west
unit :thick_sludge, 438, 0, :west
unit :captive, 439, 0, :west
unit :archer, 443, 0, :west
unit :sludge, 448, 0, :west
unit :thick_sludge, 452, 0, :west
unit :archer, 459, 0, :west
unit :sludge, 461, 0, :west
unit :sludge, 463, 0, :west
unit :wizard, 469, 0, :west
unit :archer, 474, 0, :west
unit :wizard, 475, 0, :west
unit :captive, 476, 0, :west
unit :captive, 477, 0, :west
unit :thick_sludge, 478, 0, :west
unit :sludge, 487, 0, :west
unit :thick_sludge, 488, 0, :west
unit :wizard, 491, 0, :west
unit :thick_sludge, 493, 0, :west
unit :captive, 495, 0, :west
unit :wizard, 500, 0, :west
unit :wizard, 503, 0, :west
unit :sludge, 504, 0, :west
unit :sludge, 506, 0, :west
unit :captive, 508, 0, :west
unit :captive, 510, 0, :west
unit :archer, 526, 0, :west
unit :archer, 528, 0, :west
unit :captive, 531, 0, :west
unit :sludge, 532, 0, :west
unit :wizard, 533, 0, :west
unit :wizard, 535, 0, :west
unit :archer, 538, 0, :west
unit :wizard, 540, 0, :west
unit :thick_sludge, 542, 0, :west
unit :wizard, 544, 0, :west
unit :wizard, 553, 0, :west
unit :sludge, 556, 0, :west
unit :archer, 558, 0, :west
unit :wizard, 563, 0, :west
unit :thick_sludge, 566, 0, :west
unit :wizard, 567, 0, :west
unit :wizard, 569, 0, :west
unit :captive, 571, 0, :west
unit :captive, 572, 0, :west
unit :thick_sludge, 575, 0, :west
unit :captive, 577, 0, :west
unit :archer, 578, 0, :west
unit :wizard, 582, 0, :west
unit :thick_sludge, 587, 0, :west
unit :wizard, 595, 0, :west
unit :sludge, 603, 0, :west
unit :sludge, 608, 0, :west
unit :captive, 609, 0, :west
unit :thick_sludge, 611, 0, :west
unit :sludge, 612, 0, :west
unit :sludge, 615, 0, :west
unit :thick_sludge, 621, 0, :west
unit :archer, 623, 0, :west
unit :captive, 625, 0, :west
unit :wizard, 629, 0, :west
unit :archer, 647, 0, :west
unit :thick_sludge, 652, 0, :west
unit :archer, 659, 0, :west
unit :captive, 669, 0, :west
unit :thick_sludge, 672, 0, :west
unit :thick_sludge, 680, 0, :west
unit :captive, 681, 0, :west
unit :thick_sludge, 683, 0, :west
unit :thick_sludge, 686, 0, :west
unit :captive, 693, 0, :west
unit :wizard, 712, 0, :west
unit :sludge, 714, 0, :west
unit :captive, 718, 0, :west
unit :archer, 721, 0, :west
unit :thick_sludge, 722, 0, :west
unit :wizard, 732, 0, :west
unit :captive, 738, 0, :west
unit :thick_sludge, 752, 0, :west
unit :captive, 753, 0, :west
unit :sludge, 755, 0, :west
unit :thick_sludge, 760, 0, :west
unit :sludge, 762, 0, :west
unit :sludge, 763, 0, :west
unit :sludge, 764, 0, :west
unit :archer, 768, 0, :west
unit :sludge, 772, 0, :west
unit :sludge, 776, 0, :west
unit :captive, 780, 0, :west
unit :captive, 788, 0, :west
unit :archer, 789, 0, :west
unit :thick_sludge, 794, 0, :west
unit :archer, 795, 0, :west
unit :thick_sludge, 798, 0, :west
unit :captive, 801, 0, :west
unit :wizard, 805, 0, :west
unit :sludge, 809, 0, :west
unit :sludge, 810, 0, :west
unit :sludge, 812, 0, :west
unit :captive, 817, 0, :west
unit :sludge, 821, 0, :west
unit :thick_sludge, 822, 0, :west
unit :sludge, 831, 0, :west
unit :sludge, 832, 0, :west
unit :captive, 833, 0, :west
unit :thick_sludge, 840, 0, :west
unit :wizard, 848, 0, :west
unit :sludge, 850, 0, :west
unit :wizard, 857, 0, :west
unit :thick_sludge, 859, 0, :west
unit :wizard, 866, 0, :west
unit :thick_sludge, 871, 0, :west
unit :archer, 872, 0, :west
unit :captive, 874, 0, :west
unit :thick_sludge, 879, 0, :west
unit :captive, 880, 0, :west
unit :archer, 881, 0, :west
unit :archer, 882, 0, :west
unit :captive, 884, 0, :west
unit :captive, 887, 0, :west
unit :archer, 890, 0, :west
unit :captive, 891, 0, :west
unit :wizard, 895, 0, :west
unit :archer, 900, 0, :west
unit :thick_sludge, 918, 0, :west
unit :sludge, 919, 0, :west
unit :thick_sludge, 923, 0, :west
unit :thick_sludge, 933, 0, :west
unit :wizard, 937, 0, :west
unit :captive, 945, 0, :west
unit :wizard, 948, 0, :west
unit :archer, 955, 0, :west
unit :archer, 956, 0, :west
unit :captive, 966, 0, :west
unit :captive, 968, 0, :west
unit :archer, 969, 0, :west
unit :sludge, 975, 0, :west
unit :captive, 976, 0, :west
unit :sludge, 977, 0, :west
unit :wizard, 980, 0, :west
unit :archer, 990, 0, :west
