#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |a w  s   >      SC   s   sC  s  w SC   w       CS  S               S Css  C    S  w         w  w    aw        s S   s     a   C    a   C  C   sws  Ssa a  a   C                   @    Sw s  ss    S   s C         w       s  w        C   C  C as   w   aC S   s  w     s sS  aw a  C         CCs  CS   s         a      Cs        w         s Cs     C   S   w S S wa C w     a   w CsSCa   C       a           w a  s     S   s a      w   S  S as  S         S C   C          C   s  SS C          C      C     S  C          S      Sa  w S   s     s  s    wCC C  w  w       w   C      C   S s          a  s          S      C         w      C   S   sS          a as a             C    C    a      C w    ss a w S s       s s w  w S  S      s  s  C   S     a   C s  C s C      C    a C   S a s w   S   s S S   s      w  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 807
ace_score 4035
size 807, 1
stairs 9, 0

warrior 178, 0, :east

unit :archer, 0, 0, :east
unit :wizard, 2, 0, :east
unit :sludge, 5, 0, :east
unit :thick_sludge, 16, 0, :east
unit :captive, 17, 0, :east
unit :sludge, 21, 0, :east
unit :sludge, 25, 0, :east
unit :captive, 26, 0, :east
unit :sludge, 29, 0, :east
unit :wizard, 32, 0, :east
unit :thick_sludge, 34, 0, :east
unit :captive, 35, 0, :east
unit :wizard, 39, 0, :east
unit :captive, 47, 0, :east
unit :thick_sludge, 48, 0, :east
unit :thick_sludge, 51, 0, :east
unit :thick_sludge, 67, 0, :east
unit :captive, 69, 0, :east
unit :sludge, 70, 0, :east
unit :sludge, 71, 0, :east
unit :captive, 74, 0, :east
unit :thick_sludge, 79, 0, :east
unit :wizard, 82, 0, :east
unit :wizard, 92, 0, :east
unit :wizard, 95, 0, :east
unit :archer, 100, 0, :east
unit :wizard, 101, 0, :east
unit :sludge, 110, 0, :east
unit :thick_sludge, 112, 0, :east
unit :sludge, 116, 0, :east
unit :archer, 122, 0, :east
unit :captive, 126, 0, :east
unit :archer, 131, 0, :east
unit :captive, 135, 0, :east
unit :captive, 138, 0, :east
unit :sludge, 142, 0, :east
unit :wizard, 143, 0, :east
unit :sludge, 144, 0, :east
unit :thick_sludge, 147, 0, :east
unit :sludge, 148, 0, :east
unit :archer, 149, 0, :east
unit :archer, 151, 0, :east
unit :archer, 154, 0, :east
unit :captive, 158, 0, :east
unit :thick_sludge, 183, 0, :west
unit :wizard, 184, 0, :west
unit :sludge, 186, 0, :west
unit :sludge, 189, 0, :west
unit :sludge, 190, 0, :west
unit :thick_sludge, 195, 0, :west
unit :sludge, 199, 0, :west
unit :captive, 201, 0, :west
unit :wizard, 211, 0, :west
unit :sludge, 219, 0, :west
unit :wizard, 222, 0, :west
unit :captive, 231, 0, :west
unit :captive, 235, 0, :west
unit :captive, 238, 0, :west
unit :archer, 240, 0, :west
unit :sludge, 241, 0, :west
unit :wizard, 245, 0, :west
unit :archer, 249, 0, :west
unit :captive, 250, 0, :west
unit :thick_sludge, 252, 0, :west
unit :sludge, 256, 0, :west
unit :wizard, 259, 0, :west
unit :sludge, 265, 0, :west
unit :sludge, 267, 0, :west
unit :thick_sludge, 268, 0, :west
unit :archer, 271, 0, :west
unit :wizard, 272, 0, :west
unit :archer, 274, 0, :west
unit :captive, 277, 0, :west
unit :captive, 287, 0, :west
unit :captive, 288, 0, :west
unit :sludge, 289, 0, :west
unit :captive, 292, 0, :west
unit :thick_sludge, 293, 0, :west
unit :sludge, 297, 0, :west
unit :archer, 307, 0, :west
unit :captive, 314, 0, :west
unit :sludge, 315, 0, :west
unit :wizard, 324, 0, :west
unit :sludge, 334, 0, :west
unit :captive, 336, 0, :west
unit :sludge, 337, 0, :west
unit :captive, 343, 0, :west
unit :thick_sludge, 347, 0, :west
unit :wizard, 351, 0, :west
unit :thick_sludge, 353, 0, :west
unit :thick_sludge, 355, 0, :west
unit :wizard, 357, 0, :west
unit :archer, 358, 0, :west
unit :captive, 360, 0, :west
unit :wizard, 362, 0, :west
unit :archer, 368, 0, :west
unit :wizard, 372, 0, :west
unit :captive, 374, 0, :west
unit :sludge, 375, 0, :west
unit :thick_sludge, 376, 0, :west
unit :captive, 377, 0, :west
unit :archer, 378, 0, :west
unit :captive, 382, 0, :west
unit :archer, 390, 0, :west
unit :wizard, 402, 0, :west
unit :archer, 404, 0, :west
unit :sludge, 407, 0, :west
unit :thick_sludge, 413, 0, :west
unit :sludge, 417, 0, :west
unit :archer, 419, 0, :west
unit :wizard, 426, 0, :west
unit :thick_sludge, 430, 0, :west
unit :thick_sludge, 433, 0, :west
unit :archer, 435, 0, :west
unit :sludge, 436, 0, :west
unit :thick_sludge, 439, 0, :west
unit :thick_sludge, 449, 0, :west
unit :captive, 451, 0, :west
unit :captive, 455, 0, :west
unit :captive, 466, 0, :west
unit :sludge, 470, 0, :west
unit :thick_sludge, 473, 0, :west
unit :thick_sludge, 474, 0, :west
unit :captive, 476, 0, :west
unit :captive, 487, 0, :west
unit :captive, 494, 0, :west
unit :thick_sludge, 500, 0, :west
unit :captive, 503, 0, :west
unit :thick_sludge, 514, 0, :west
unit :thick_sludge, 521, 0, :west
unit :archer, 522, 0, :west
unit :wizard, 525, 0, :west
unit :thick_sludge, 527, 0, :west
unit :sludge, 531, 0, :west
unit :sludge, 537, 0, :west
unit :sludge, 540, 0, :west
unit :wizard, 545, 0, :west
unit :captive, 546, 0, :west
unit :captive, 547, 0, :west
unit :captive, 549, 0, :west
unit :wizard, 552, 0, :west
unit :wizard, 555, 0, :west
unit :wizard, 563, 0, :west
unit :captive, 567, 0, :west
unit :captive, 574, 0, :west
unit :thick_sludge, 578, 0, :west
unit :sludge, 580, 0, :west
unit :archer, 591, 0, :west
unit :sludge, 594, 0, :west
unit :thick_sludge, 605, 0, :west
unit :captive, 612, 0, :west
unit :wizard, 622, 0, :west
unit :captive, 629, 0, :west
unit :thick_sludge, 633, 0, :west
unit :sludge, 637, 0, :west
unit :thick_sludge, 638, 0, :west
unit :archer, 649, 0, :west
unit :archer, 651, 0, :west
unit :sludge, 652, 0, :west
unit :archer, 654, 0, :west
unit :captive, 668, 0, :west
unit :captive, 673, 0, :west
unit :archer, 678, 0, :west
unit :captive, 685, 0, :west
unit :wizard, 687, 0, :west
unit :sludge, 692, 0, :west
unit :sludge, 693, 0, :west
unit :archer, 695, 0, :west
unit :wizard, 697, 0, :west
unit :thick_sludge, 699, 0, :west
unit :sludge, 701, 0, :west
unit :sludge, 709, 0, :west
unit :sludge, 711, 0, :west
unit :wizard, 713, 0, :west
unit :wizard, 716, 0, :west
unit :thick_sludge, 718, 0, :west
unit :thick_sludge, 721, 0, :west
unit :sludge, 728, 0, :west
unit :sludge, 731, 0, :west
unit :captive, 734, 0, :west
unit :thick_sludge, 738, 0, :west
unit :archer, 744, 0, :west
unit :captive, 748, 0, :west
unit :sludge, 750, 0, :west
unit :captive, 753, 0, :west
unit :sludge, 755, 0, :west
unit :captive, 757, 0, :west
unit :captive, 764, 0, :west
unit :archer, 769, 0, :west
unit :captive, 771, 0, :west
unit :thick_sludge, 775, 0, :west
unit :archer, 777, 0, :west
unit :sludge, 779, 0, :west
unit :wizard, 781, 0, :west
unit :thick_sludge, 785, 0, :west
unit :sludge, 789, 0, :west
unit :thick_sludge, 791, 0, :west
unit :thick_sludge, 793, 0, :west
unit :sludge, 797, 0, :west
unit :wizard, 804, 0, :west
