#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |Cw    s   a   S          s    C Cs  s w   s w           s S   S w             a C     Cs  as  a    s    S   S   s   s   aa     w       C a  a      w a     w   w C C  s  w    Cs    w  sCw  C     S   w   as    s    a         as  s S s    Sa w     Sw      sS            C     SC S   S         w C              w s s      C s w C     a  s  a    >  C      C S    w    a     sC       C   Ca  s   a    S a a    wa s  C                 s  wC         sS     C s S       sC    w    w   s S     w       w s  w   w  CS     C    a    C   ws w CS wa                    S      s   S      C s C    s            a  a   w     a     C     a   w w  sSCS a      C  S  ss    s       sas       sCsC     s   a            C            w CC   s           a  sS      w    Sa       w    w    s      a           a S  S  CsCC  C s C                     aa      s C a  s    w   C S  w a S  S SC    w  C S     a   w SC      w a  CCs a a      w   a  a   sw   S     s       w   sC w    S C  Ssa  w   @     s     s sS|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 982
ace_score 4910
size 982, 1
stairs 341, 0

warrior 966, 0, :east

unit :captive, 0, 0, :east
unit :wizard, 1, 0, :east
unit :sludge, 6, 0, :east
unit :archer, 10, 0, :east
unit :thick_sludge, 14, 0, :east
unit :sludge, 25, 0, :east
unit :captive, 30, 0, :east
unit :captive, 32, 0, :east
unit :sludge, 33, 0, :east
unit :sludge, 36, 0, :east
unit :wizard, 38, 0, :east
unit :sludge, 42, 0, :east
unit :wizard, 44, 0, :east
unit :sludge, 56, 0, :east
unit :thick_sludge, 58, 0, :east
unit :thick_sludge, 62, 0, :east
unit :wizard, 64, 0, :east
unit :archer, 78, 0, :east
unit :captive, 80, 0, :east
unit :captive, 86, 0, :east
unit :sludge, 87, 0, :east
unit :archer, 90, 0, :east
unit :sludge, 91, 0, :east
unit :archer, 94, 0, :east
unit :sludge, 99, 0, :east
unit :thick_sludge, 104, 0, :east
unit :thick_sludge, 108, 0, :east
unit :sludge, 112, 0, :east
unit :sludge, 116, 0, :east
unit :archer, 120, 0, :east
unit :archer, 121, 0, :east
unit :wizard, 127, 0, :east
unit :captive, 135, 0, :east
unit :archer, 137, 0, :east
unit :archer, 140, 0, :east
unit :wizard, 147, 0, :east
unit :archer, 149, 0, :east
unit :wizard, 155, 0, :east
unit :wizard, 159, 0, :east
unit :captive, 161, 0, :east
unit :captive, 163, 0, :east
unit :sludge, 166, 0, :east
unit :wizard, 169, 0, :east
unit :captive, 174, 0, :east
unit :sludge, 175, 0, :east
unit :wizard, 180, 0, :east
unit :sludge, 183, 0, :east
unit :captive, 184, 0, :east
unit :wizard, 185, 0, :east
unit :captive, 188, 0, :east
unit :thick_sludge, 194, 0, :east
unit :wizard, 198, 0, :east
unit :archer, 202, 0, :east
unit :sludge, 203, 0, :east
unit :sludge, 208, 0, :east
unit :archer, 213, 0, :east
unit :archer, 223, 0, :east
unit :sludge, 224, 0, :east
unit :sludge, 227, 0, :east
unit :thick_sludge, 229, 0, :east
unit :sludge, 231, 0, :east
unit :thick_sludge, 236, 0, :east
unit :archer, 237, 0, :east
unit :wizard, 239, 0, :east
unit :thick_sludge, 245, 0, :east
unit :wizard, 246, 0, :east
unit :sludge, 253, 0, :east
unit :thick_sludge, 254, 0, :east
unit :captive, 267, 0, :east
unit :thick_sludge, 273, 0, :east
unit :captive, 274, 0, :east
unit :thick_sludge, 276, 0, :east
unit :thick_sludge, 280, 0, :east
unit :wizard, 290, 0, :east
unit :captive, 292, 0, :east
unit :wizard, 307, 0, :east
unit :sludge, 309, 0, :east
unit :sludge, 311, 0, :east
unit :captive, 318, 0, :east
unit :sludge, 320, 0, :east
unit :wizard, 322, 0, :east
unit :captive, 324, 0, :east
unit :archer, 330, 0, :east
unit :sludge, 333, 0, :east
unit :archer, 336, 0, :east
unit :captive, 344, 0, :east
unit :captive, 351, 0, :east
unit :thick_sludge, 353, 0, :east
unit :wizard, 358, 0, :east
unit :archer, 363, 0, :east
unit :sludge, 369, 0, :east
unit :captive, 370, 0, :east
unit :captive, 378, 0, :east
unit :captive, 382, 0, :east
unit :archer, 383, 0, :east
unit :sludge, 386, 0, :east
unit :archer, 390, 0, :east
unit :thick_sludge, 395, 0, :east
unit :archer, 397, 0, :east
unit :archer, 399, 0, :east
unit :wizard, 404, 0, :east
unit :archer, 405, 0, :east
unit :sludge, 407, 0, :east
unit :captive, 410, 0, :east
unit :sludge, 428, 0, :east
unit :wizard, 431, 0, :east
unit :captive, 432, 0, :east
unit :sludge, 442, 0, :east
unit :thick_sludge, 443, 0, :east
unit :captive, 449, 0, :east
unit :sludge, 451, 0, :east
unit :thick_sludge, 453, 0, :east
unit :sludge, 461, 0, :east
unit :captive, 462, 0, :east
unit :wizard, 467, 0, :east
unit :wizard, 472, 0, :east
unit :sludge, 476, 0, :east
unit :thick_sludge, 478, 0, :east
unit :wizard, 484, 0, :east
unit :wizard, 492, 0, :east
unit :sludge, 494, 0, :east
unit :wizard, 497, 0, :east
unit :wizard, 501, 0, :east
unit :captive, 504, 0, :east
unit :thick_sludge, 505, 0, :east
unit :captive, 511, 0, :east
unit :archer, 516, 0, :east
unit :captive, 521, 0, :east
unit :wizard, 525, 0, :east
unit :sludge, 526, 0, :east
unit :wizard, 528, 0, :east
unit :captive, 530, 0, :east
unit :thick_sludge, 531, 0, :east
unit :wizard, 533, 0, :east
unit :archer, 534, 0, :east
unit :thick_sludge, 555, 0, :east
unit :sludge, 562, 0, :east
unit :thick_sludge, 566, 0, :east
unit :captive, 573, 0, :east
unit :sludge, 575, 0, :east
unit :captive, 577, 0, :east
unit :sludge, 582, 0, :east
unit :archer, 595, 0, :east
unit :archer, 598, 0, :east
unit :wizard, 602, 0, :east
unit :archer, 608, 0, :east
unit :captive, 614, 0, :east
unit :archer, 620, 0, :east
unit :wizard, 624, 0, :east
unit :wizard, 626, 0, :east
unit :sludge, 629, 0, :east
unit :thick_sludge, 630, 0, :east
unit :captive, 631, 0, :east
unit :thick_sludge, 632, 0, :east
unit :archer, 634, 0, :east
unit :captive, 641, 0, :east
unit :thick_sludge, 644, 0, :east
unit :sludge, 647, 0, :east
unit :sludge, 648, 0, :east
unit :sludge, 653, 0, :east
unit :sludge, 661, 0, :east
unit :archer, 662, 0, :east
unit :sludge, 663, 0, :east
unit :sludge, 671, 0, :east
unit :captive, 672, 0, :east
unit :sludge, 673, 0, :east
unit :captive, 674, 0, :east
unit :sludge, 680, 0, :east
unit :archer, 684, 0, :east
unit :captive, 697, 0, :east
unit :wizard, 710, 0, :east
unit :captive, 712, 0, :east
unit :captive, 713, 0, :east
unit :sludge, 717, 0, :east
unit :archer, 729, 0, :east
unit :sludge, 732, 0, :east
unit :thick_sludge, 733, 0, :east
unit :wizard, 740, 0, :east
unit :thick_sludge, 745, 0, :east
unit :archer, 746, 0, :east
unit :wizard, 754, 0, :east
unit :wizard, 759, 0, :east
unit :sludge, 764, 0, :east
unit :archer, 771, 0, :east
unit :archer, 783, 0, :east
unit :thick_sludge, 785, 0, :east
unit :thick_sludge, 788, 0, :east
unit :captive, 791, 0, :east
unit :sludge, 792, 0, :east
unit :captive, 793, 0, :east
unit :captive, 794, 0, :east
unit :captive, 797, 0, :east
unit :sludge, 799, 0, :east
unit :captive, 801, 0, :east
unit :archer, 823, 0, :east
unit :archer, 824, 0, :east
unit :sludge, 831, 0, :east
unit :captive, 833, 0, :east
unit :archer, 835, 0, :east
unit :sludge, 838, 0, :east
unit :wizard, 843, 0, :east
unit :captive, 847, 0, :east
unit :thick_sludge, 849, 0, :east
unit :wizard, 852, 0, :east
unit :archer, 854, 0, :east
unit :thick_sludge, 856, 0, :east
unit :thick_sludge, 859, 0, :east
unit :thick_sludge, 861, 0, :east
unit :captive, 862, 0, :east
unit :wizard, 867, 0, :east
unit :captive, 870, 0, :east
unit :thick_sludge, 872, 0, :east
unit :archer, 878, 0, :east
unit :wizard, 882, 0, :east
unit :thick_sludge, 884, 0, :east
unit :captive, 885, 0, :east
unit :wizard, 892, 0, :east
unit :archer, 894, 0, :east
unit :captive, 897, 0, :east
unit :captive, 898, 0, :east
unit :sludge, 899, 0, :east
unit :archer, 901, 0, :east
unit :archer, 903, 0, :east
unit :wizard, 910, 0, :east
unit :archer, 914, 0, :east
unit :archer, 917, 0, :east
unit :sludge, 921, 0, :east
unit :wizard, 922, 0, :east
unit :thick_sludge, 926, 0, :east
unit :sludge, 932, 0, :east
unit :wizard, 940, 0, :east
unit :sludge, 944, 0, :east
unit :captive, 945, 0, :east
unit :wizard, 947, 0, :east
unit :thick_sludge, 952, 0, :east
unit :captive, 954, 0, :east
unit :thick_sludge, 957, 0, :east
unit :sludge, 958, 0, :east
unit :archer, 959, 0, :east
unit :wizard, 962, 0, :east
unit :sludge, 972, 0, :west
unit :sludge, 978, 0, :west
unit :sludge, 980, 0, :west
unit :thick_sludge, 981, 0, :west
