#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |sS   S         sC  s  C S       C     a  a C     s    S      a   s  C        S    SS        ws s  C    C    C    S     Cs      C s S S       ss             w S C   SS C     sSa aC    S    S   Ca      s S    SsSCs   s C        w     s  s       Sw    w                    w ssa     a     C  w  aa  s    C   a  S    C sC  a                   S            a  s   C   C  S     S a aa   SS  a  w   a a  s    a w  s    C s C  a      C                 Ss a C w     C      a             >s  ssSa      w   a  w   a     S    s  s wSw  C a   w    sa    s  SCaa              a   w        wC     C          S   S  a a sC aa    @  |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 614
ace_score 3070
size 614, 1
stairs 478, 0

warrior 613, 0, :east

unit :sludge, 0, 0, :east
unit :thick_sludge, 1, 0, :east
unit :thick_sludge, 5, 0, :east
unit :sludge, 15, 0, :east
unit :captive, 16, 0, :east
unit :sludge, 19, 0, :east
unit :captive, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :captive, 32, 0, :east
unit :archer, 38, 0, :east
unit :archer, 41, 0, :east
unit :captive, 43, 0, :east
unit :sludge, 49, 0, :east
unit :thick_sludge, 54, 0, :east
unit :archer, 61, 0, :east
unit :sludge, 65, 0, :east
unit :captive, 68, 0, :east
unit :thick_sludge, 77, 0, :east
unit :thick_sludge, 82, 0, :east
unit :thick_sludge, 83, 0, :east
unit :wizard, 92, 0, :east
unit :sludge, 93, 0, :east
unit :sludge, 95, 0, :east
unit :captive, 98, 0, :east
unit :captive, 103, 0, :east
unit :captive, 108, 0, :east
unit :thick_sludge, 113, 0, :east
unit :captive, 119, 0, :east
unit :sludge, 120, 0, :east
unit :captive, 127, 0, :east
unit :sludge, 129, 0, :east
unit :thick_sludge, 131, 0, :east
unit :thick_sludge, 133, 0, :east
unit :sludge, 141, 0, :east
unit :sludge, 142, 0, :east
unit :wizard, 156, 0, :east
unit :thick_sludge, 158, 0, :east
unit :captive, 160, 0, :east
unit :thick_sludge, 164, 0, :east
unit :thick_sludge, 165, 0, :east
unit :captive, 167, 0, :east
unit :sludge, 173, 0, :east
unit :thick_sludge, 174, 0, :east
unit :archer, 175, 0, :east
unit :archer, 177, 0, :east
unit :captive, 178, 0, :east
unit :thick_sludge, 183, 0, :east
unit :thick_sludge, 188, 0, :east
unit :captive, 192, 0, :east
unit :archer, 193, 0, :east
unit :sludge, 200, 0, :east
unit :thick_sludge, 202, 0, :east
unit :thick_sludge, 207, 0, :east
unit :sludge, 208, 0, :east
unit :thick_sludge, 209, 0, :east
unit :captive, 210, 0, :east
unit :sludge, 211, 0, :east
unit :sludge, 215, 0, :east
unit :captive, 217, 0, :east
unit :wizard, 226, 0, :east
unit :sludge, 232, 0, :east
unit :sludge, 235, 0, :east
unit :thick_sludge, 243, 0, :east
unit :wizard, 244, 0, :east
unit :wizard, 249, 0, :east
unit :wizard, 270, 0, :east
unit :sludge, 272, 0, :east
unit :sludge, 273, 0, :east
unit :archer, 274, 0, :east
unit :archer, 280, 0, :east
unit :captive, 286, 0, :east
unit :wizard, 289, 0, :east
unit :archer, 292, 0, :east
unit :archer, 293, 0, :east
unit :sludge, 296, 0, :east
unit :captive, 301, 0, :east
unit :archer, 305, 0, :east
unit :thick_sludge, 308, 0, :east
unit :captive, 313, 0, :east
unit :sludge, 315, 0, :east
unit :captive, 316, 0, :east
unit :archer, 319, 0, :east
unit :thick_sludge, 339, 0, :east
unit :archer, 352, 0, :east
unit :sludge, 355, 0, :east
unit :captive, 359, 0, :east
unit :captive, 363, 0, :east
unit :thick_sludge, 366, 0, :east
unit :thick_sludge, 372, 0, :east
unit :archer, 374, 0, :east
unit :archer, 376, 0, :east
unit :archer, 377, 0, :east
unit :thick_sludge, 381, 0, :east
unit :thick_sludge, 382, 0, :east
unit :archer, 385, 0, :east
unit :wizard, 388, 0, :east
unit :archer, 392, 0, :east
unit :archer, 394, 0, :east
unit :sludge, 397, 0, :east
unit :archer, 402, 0, :east
unit :wizard, 404, 0, :east
unit :sludge, 407, 0, :east
unit :captive, 412, 0, :east
unit :sludge, 414, 0, :east
unit :captive, 416, 0, :east
unit :archer, 419, 0, :east
unit :captive, 426, 0, :east
unit :thick_sludge, 444, 0, :east
unit :sludge, 445, 0, :east
unit :archer, 447, 0, :east
unit :captive, 449, 0, :east
unit :wizard, 451, 0, :east
unit :captive, 457, 0, :east
unit :archer, 464, 0, :east
unit :sludge, 479, 0, :east
unit :sludge, 482, 0, :east
unit :sludge, 483, 0, :east
unit :thick_sludge, 484, 0, :east
unit :archer, 485, 0, :east
unit :wizard, 492, 0, :east
unit :archer, 496, 0, :east
unit :wizard, 499, 0, :east
unit :archer, 503, 0, :east
unit :thick_sludge, 509, 0, :east
unit :sludge, 514, 0, :east
unit :sludge, 517, 0, :east
unit :wizard, 519, 0, :east
unit :thick_sludge, 520, 0, :east
unit :wizard, 521, 0, :east
unit :captive, 524, 0, :east
unit :archer, 526, 0, :east
unit :wizard, 530, 0, :east
unit :sludge, 535, 0, :east
unit :archer, 536, 0, :east
unit :sludge, 541, 0, :east
unit :thick_sludge, 544, 0, :east
unit :captive, 545, 0, :east
unit :archer, 546, 0, :east
unit :archer, 547, 0, :east
unit :archer, 562, 0, :east
unit :wizard, 566, 0, :east
unit :wizard, 575, 0, :east
unit :captive, 576, 0, :east
unit :captive, 582, 0, :east
unit :thick_sludge, 593, 0, :east
unit :thick_sludge, 597, 0, :east
unit :archer, 600, 0, :east
unit :archer, 602, 0, :east
unit :sludge, 604, 0, :east
unit :captive, 605, 0, :east
unit :archer, 607, 0, :east
unit :archer, 608, 0, :east
