#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   S     C   w    S          S   s C a    s        ss C     C S       S      sa w   s          C  w     s    aC  s        w S  a  s  w      w w C  C  w  w  a  wC S    a   C      s   a S  a     s ass        s    C       s      a            w    s w    a a Ca   a       C   a S   C  S  a  Sa Sa  S            C        Ca     s        CSC CC s     a    C s a aw    w    s   w                  C       S w     s            Sw   C    sS S       a   w  w   s          s  CsS   S    @   a sSa  a     C    C       Cs Ca  S        wa   s  aa s S     C  C  aC w  C  S   sa    >Sw  wC w     C s s        |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 593
ace_score 2965
size 593, 1
stairs 566, 0

warrior 476, 0, :east

unit :thick_sludge, 3, 0, :east
unit :captive, 9, 0, :east
unit :wizard, 13, 0, :east
unit :thick_sludge, 18, 0, :east
unit :thick_sludge, 29, 0, :east
unit :sludge, 33, 0, :east
unit :captive, 35, 0, :east
unit :archer, 37, 0, :east
unit :sludge, 42, 0, :east
unit :sludge, 51, 0, :east
unit :sludge, 52, 0, :east
unit :captive, 54, 0, :east
unit :captive, 60, 0, :east
unit :thick_sludge, 62, 0, :east
unit :thick_sludge, 70, 0, :east
unit :sludge, 77, 0, :east
unit :archer, 78, 0, :east
unit :wizard, 80, 0, :east
unit :sludge, 84, 0, :east
unit :captive, 95, 0, :east
unit :wizard, 98, 0, :east
unit :sludge, 104, 0, :east
unit :archer, 109, 0, :east
unit :captive, 110, 0, :east
unit :sludge, 113, 0, :east
unit :wizard, 122, 0, :east
unit :thick_sludge, 124, 0, :east
unit :archer, 127, 0, :east
unit :sludge, 130, 0, :east
unit :wizard, 133, 0, :east
unit :wizard, 140, 0, :east
unit :wizard, 142, 0, :east
unit :captive, 144, 0, :east
unit :captive, 147, 0, :east
unit :wizard, 150, 0, :east
unit :wizard, 153, 0, :east
unit :archer, 156, 0, :east
unit :wizard, 159, 0, :east
unit :captive, 160, 0, :east
unit :thick_sludge, 162, 0, :east
unit :archer, 167, 0, :east
unit :captive, 171, 0, :east
unit :sludge, 178, 0, :east
unit :archer, 182, 0, :east
unit :thick_sludge, 184, 0, :east
unit :archer, 187, 0, :east
unit :sludge, 193, 0, :east
unit :archer, 195, 0, :east
unit :sludge, 196, 0, :east
unit :sludge, 197, 0, :east
unit :sludge, 206, 0, :east
unit :captive, 211, 0, :east
unit :sludge, 219, 0, :east
unit :archer, 226, 0, :east
unit :wizard, 239, 0, :east
unit :sludge, 244, 0, :east
unit :wizard, 246, 0, :east
unit :archer, 251, 0, :east
unit :archer, 253, 0, :east
unit :captive, 255, 0, :east
unit :archer, 256, 0, :east
unit :archer, 260, 0, :east
unit :captive, 268, 0, :east
unit :archer, 272, 0, :east
unit :thick_sludge, 274, 0, :east
unit :captive, 278, 0, :east
unit :thick_sludge, 281, 0, :east
unit :archer, 284, 0, :east
unit :thick_sludge, 287, 0, :east
unit :archer, 288, 0, :east
unit :thick_sludge, 290, 0, :east
unit :archer, 291, 0, :east
unit :thick_sludge, 294, 0, :east
unit :captive, 307, 0, :east
unit :captive, 316, 0, :east
unit :archer, 317, 0, :east
unit :sludge, 323, 0, :east
unit :captive, 332, 0, :east
unit :thick_sludge, 333, 0, :east
unit :captive, 334, 0, :east
unit :captive, 336, 0, :east
unit :captive, 337, 0, :east
unit :sludge, 339, 0, :east
unit :archer, 345, 0, :east
unit :captive, 350, 0, :east
unit :sludge, 352, 0, :east
unit :archer, 354, 0, :east
unit :archer, 356, 0, :east
unit :wizard, 357, 0, :east
unit :wizard, 362, 0, :east
unit :sludge, 367, 0, :east
unit :wizard, 371, 0, :east
unit :captive, 390, 0, :east
unit :thick_sludge, 398, 0, :east
unit :wizard, 400, 0, :east
unit :sludge, 406, 0, :east
unit :thick_sludge, 419, 0, :east
unit :wizard, 420, 0, :east
unit :captive, 424, 0, :east
unit :sludge, 429, 0, :east
unit :thick_sludge, 430, 0, :east
unit :thick_sludge, 432, 0, :east
unit :archer, 440, 0, :east
unit :wizard, 444, 0, :east
unit :wizard, 447, 0, :east
unit :sludge, 451, 0, :east
unit :sludge, 462, 0, :east
unit :captive, 465, 0, :east
unit :sludge, 466, 0, :east
unit :thick_sludge, 467, 0, :east
unit :thick_sludge, 471, 0, :east
unit :archer, 480, 0, :west
unit :sludge, 482, 0, :west
unit :thick_sludge, 483, 0, :west
unit :archer, 484, 0, :west
unit :archer, 487, 0, :west
unit :captive, 493, 0, :west
unit :captive, 498, 0, :west
unit :captive, 506, 0, :west
unit :sludge, 507, 0, :west
unit :captive, 509, 0, :west
unit :archer, 510, 0, :west
unit :thick_sludge, 513, 0, :west
unit :wizard, 522, 0, :west
unit :archer, 523, 0, :west
unit :sludge, 527, 0, :west
unit :archer, 530, 0, :west
unit :archer, 531, 0, :west
unit :sludge, 533, 0, :west
unit :thick_sludge, 535, 0, :west
unit :captive, 541, 0, :west
unit :captive, 544, 0, :west
unit :archer, 547, 0, :west
unit :captive, 548, 0, :west
unit :wizard, 550, 0, :west
unit :captive, 553, 0, :west
unit :thick_sludge, 556, 0, :west
unit :sludge, 560, 0, :west
unit :archer, 561, 0, :west
unit :thick_sludge, 567, 0, :west
unit :wizard, 568, 0, :west
unit :wizard, 571, 0, :west
unit :captive, 572, 0, :west
unit :wizard, 574, 0, :west
unit :captive, 580, 0, :west
unit :sludge, 582, 0, :west
unit :sludge, 584, 0, :west
