#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   sw sSs    S a     a a    @  S C C  w S   w                 S      CS         w > S   Cs S C C   a      a        C  C C  C   S    a    C       a    a     s     C  C  a C  C s  s        C   w    a  a            a   a w    s  C  S       a  S    a  wC C     ss         a a Ca     a  C s  a     SC      S                as   s  C   SC         S s  s  C      a      s  s aS aCa   wSS  C       CC      w        s     C    s  S  s sa s a             Sa            Cw   aC S  a  a   S       s  C s w C  s    a S     aa     S   a    S  s  S   S  C C      a    sa w    S      s  w   |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 575
ace_score 2875
size 575, 1
stairs 82, 0

warrior 28, 0, :east

unit :sludge, 3, 0, :east
unit :wizard, 4, 0, :east
unit :sludge, 6, 0, :east
unit :thick_sludge, 7, 0, :east
unit :sludge, 8, 0, :east
unit :thick_sludge, 13, 0, :east
unit :archer, 15, 0, :east
unit :archer, 21, 0, :east
unit :archer, 23, 0, :east
unit :thick_sludge, 31, 0, :west
unit :captive, 33, 0, :west
unit :captive, 35, 0, :west
unit :wizard, 38, 0, :west
unit :thick_sludge, 40, 0, :west
unit :wizard, 44, 0, :west
unit :thick_sludge, 62, 0, :west
unit :captive, 69, 0, :west
unit :thick_sludge, 70, 0, :west
unit :wizard, 80, 0, :west
unit :thick_sludge, 84, 0, :west
unit :captive, 88, 0, :west
unit :sludge, 89, 0, :west
unit :thick_sludge, 91, 0, :west
unit :captive, 93, 0, :west
unit :captive, 95, 0, :west
unit :archer, 99, 0, :west
unit :archer, 106, 0, :west
unit :captive, 115, 0, :west
unit :captive, 118, 0, :west
unit :captive, 120, 0, :west
unit :captive, 123, 0, :west
unit :thick_sludge, 127, 0, :west
unit :archer, 132, 0, :west
unit :captive, 137, 0, :west
unit :archer, 145, 0, :west
unit :archer, 150, 0, :west
unit :sludge, 156, 0, :west
unit :captive, 162, 0, :west
unit :captive, 165, 0, :west
unit :archer, 168, 0, :west
unit :captive, 170, 0, :west
unit :captive, 173, 0, :west
unit :sludge, 175, 0, :west
unit :sludge, 178, 0, :west
unit :captive, 187, 0, :west
unit :wizard, 191, 0, :west
unit :archer, 196, 0, :west
unit :archer, 199, 0, :west
unit :archer, 212, 0, :west
unit :archer, 216, 0, :west
unit :wizard, 218, 0, :west
unit :sludge, 223, 0, :west
unit :captive, 226, 0, :west
unit :thick_sludge, 229, 0, :west
unit :archer, 237, 0, :west
unit :thick_sludge, 240, 0, :west
unit :archer, 245, 0, :west
unit :wizard, 248, 0, :west
unit :captive, 249, 0, :west
unit :captive, 251, 0, :west
unit :sludge, 257, 0, :west
unit :sludge, 258, 0, :west
unit :archer, 268, 0, :west
unit :archer, 270, 0, :west
unit :captive, 272, 0, :west
unit :archer, 273, 0, :west
unit :archer, 279, 0, :west
unit :captive, 282, 0, :west
unit :sludge, 284, 0, :west
unit :archer, 287, 0, :west
unit :thick_sludge, 293, 0, :west
unit :captive, 294, 0, :west
unit :thick_sludge, 301, 0, :west
unit :archer, 318, 0, :west
unit :sludge, 319, 0, :west
unit :sludge, 323, 0, :west
unit :captive, 326, 0, :west
unit :thick_sludge, 330, 0, :west
unit :captive, 331, 0, :west
unit :thick_sludge, 341, 0, :west
unit :sludge, 343, 0, :west
unit :sludge, 346, 0, :west
unit :captive, 349, 0, :west
unit :archer, 356, 0, :west
unit :sludge, 363, 0, :west
unit :sludge, 366, 0, :west
unit :archer, 368, 0, :west
unit :thick_sludge, 369, 0, :west
unit :archer, 371, 0, :west
unit :captive, 372, 0, :west
unit :archer, 373, 0, :west
unit :wizard, 377, 0, :west
unit :thick_sludge, 378, 0, :west
unit :thick_sludge, 379, 0, :west
unit :captive, 382, 0, :west
unit :captive, 390, 0, :west
unit :captive, 391, 0, :west
unit :wizard, 398, 0, :west
unit :sludge, 407, 0, :west
unit :captive, 413, 0, :west
unit :sludge, 418, 0, :west
unit :thick_sludge, 421, 0, :west
unit :sludge, 424, 0, :west
unit :sludge, 426, 0, :west
unit :archer, 427, 0, :west
unit :sludge, 429, 0, :west
unit :archer, 431, 0, :west
unit :thick_sludge, 445, 0, :west
unit :archer, 446, 0, :west
unit :captive, 459, 0, :west
unit :wizard, 460, 0, :west
unit :archer, 464, 0, :west
unit :captive, 465, 0, :west
unit :thick_sludge, 467, 0, :west
unit :archer, 470, 0, :west
unit :archer, 473, 0, :west
unit :thick_sludge, 477, 0, :west
unit :sludge, 485, 0, :west
unit :captive, 488, 0, :west
unit :sludge, 490, 0, :west
unit :wizard, 492, 0, :west
unit :captive, 494, 0, :west
unit :sludge, 497, 0, :west
unit :archer, 502, 0, :west
unit :thick_sludge, 504, 0, :west
unit :archer, 510, 0, :west
unit :archer, 511, 0, :west
unit :thick_sludge, 517, 0, :west
unit :archer, 521, 0, :west
unit :thick_sludge, 526, 0, :west
unit :sludge, 529, 0, :west
unit :thick_sludge, 532, 0, :west
unit :thick_sludge, 536, 0, :west
unit :captive, 539, 0, :west
unit :captive, 541, 0, :west
unit :archer, 548, 0, :west
unit :sludge, 553, 0, :west
unit :archer, 554, 0, :west
unit :wizard, 556, 0, :west
unit :thick_sludge, 561, 0, :west
unit :sludge, 568, 0, :west
unit :wizard, 571, 0, :west
