#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  S      s     C     s a  w    C  C    w      C w sa   Sa     w      w  S    Ssa        C  s   S  s     S    C      aC  w       wa         w       CS         w SC   a a  w C S  s       s S a         S       w   sss     C     a C     w             w   w s   s     SCa    w a    C  Sa s              sC        C    w  w  aC   w  aC  @  S   w CSC             a     CC            s w     CS wa  a C a S          s   w     C w    SS Sa       s  Sa   a   s S C       w s   CC a  S       C    S  Sa            w     a  S   C              w s   w         aas a    SS w           SsC Sa  s   s   a a C   a     w           s s     s      Css       S   Cs  a    w         S   a    s w Cs aS   a  s C  s      w   C   a    C   a    s  a  a a       C w    w          a w S   s s> sw          s saC     S  asa  s  C sa     aas   S   C    s w     a    w    s   aS      S            sS      wCs   C    w   s  s         |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 902
ace_score 4510
size 902, 1
stairs 764, 0

warrior 331, 0, :east

unit :thick_sludge, 2, 0, :east
unit :sludge, 9, 0, :east
unit :captive, 15, 0, :east
unit :sludge, 21, 0, :east
unit :archer, 23, 0, :east
unit :wizard, 26, 0, :east
unit :captive, 31, 0, :east
unit :captive, 34, 0, :east
unit :wizard, 39, 0, :east
unit :captive, 46, 0, :east
unit :wizard, 48, 0, :east
unit :sludge, 50, 0, :east
unit :archer, 51, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 56, 0, :east
unit :wizard, 62, 0, :east
unit :wizard, 69, 0, :east
unit :thick_sludge, 72, 0, :east
unit :thick_sludge, 77, 0, :east
unit :sludge, 78, 0, :east
unit :archer, 79, 0, :east
unit :captive, 88, 0, :east
unit :sludge, 91, 0, :east
unit :thick_sludge, 95, 0, :east
unit :sludge, 98, 0, :east
unit :thick_sludge, 104, 0, :east
unit :captive, 109, 0, :east
unit :archer, 116, 0, :east
unit :captive, 117, 0, :east
unit :wizard, 120, 0, :east
unit :wizard, 128, 0, :east
unit :archer, 129, 0, :east
unit :wizard, 139, 0, :east
unit :captive, 147, 0, :east
unit :thick_sludge, 148, 0, :east
unit :wizard, 158, 0, :east
unit :thick_sludge, 160, 0, :east
unit :captive, 161, 0, :east
unit :archer, 165, 0, :east
unit :archer, 167, 0, :east
unit :wizard, 170, 0, :east
unit :captive, 172, 0, :east
unit :thick_sludge, 174, 0, :east
unit :sludge, 177, 0, :east
unit :sludge, 185, 0, :east
unit :thick_sludge, 187, 0, :east
unit :archer, 189, 0, :east
unit :thick_sludge, 199, 0, :east
unit :wizard, 207, 0, :east
unit :sludge, 211, 0, :east
unit :sludge, 212, 0, :east
unit :sludge, 213, 0, :east
unit :captive, 219, 0, :east
unit :archer, 225, 0, :east
unit :captive, 227, 0, :east
unit :wizard, 233, 0, :east
unit :wizard, 247, 0, :east
unit :wizard, 251, 0, :east
unit :sludge, 253, 0, :east
unit :sludge, 257, 0, :east
unit :thick_sludge, 263, 0, :east
unit :captive, 264, 0, :east
unit :archer, 265, 0, :east
unit :wizard, 270, 0, :east
unit :archer, 272, 0, :east
unit :captive, 277, 0, :east
unit :thick_sludge, 280, 0, :east
unit :archer, 281, 0, :east
unit :sludge, 283, 0, :east
unit :sludge, 298, 0, :east
unit :captive, 299, 0, :east
unit :captive, 308, 0, :east
unit :wizard, 313, 0, :east
unit :wizard, 316, 0, :east
unit :archer, 319, 0, :east
unit :captive, 320, 0, :east
unit :wizard, 324, 0, :east
unit :archer, 327, 0, :east
unit :captive, 328, 0, :east
unit :thick_sludge, 334, 0, :west
unit :wizard, 338, 0, :west
unit :captive, 340, 0, :west
unit :thick_sludge, 341, 0, :west
unit :captive, 342, 0, :west
unit :archer, 356, 0, :west
unit :captive, 362, 0, :west
unit :captive, 363, 0, :west
unit :sludge, 376, 0, :west
unit :wizard, 378, 0, :west
unit :captive, 384, 0, :west
unit :thick_sludge, 385, 0, :west
unit :wizard, 387, 0, :west
unit :archer, 388, 0, :west
unit :archer, 391, 0, :west
unit :captive, 393, 0, :west
unit :archer, 395, 0, :west
unit :thick_sludge, 397, 0, :west
unit :sludge, 408, 0, :west
unit :wizard, 412, 0, :west
unit :captive, 418, 0, :west
unit :wizard, 420, 0, :west
unit :thick_sludge, 425, 0, :west
unit :thick_sludge, 426, 0, :west
unit :thick_sludge, 428, 0, :west
unit :archer, 429, 0, :west
unit :sludge, 437, 0, :west
unit :thick_sludge, 440, 0, :west
unit :archer, 441, 0, :west
unit :archer, 445, 0, :west
unit :sludge, 449, 0, :west
unit :thick_sludge, 451, 0, :west
unit :captive, 453, 0, :west
unit :wizard, 461, 0, :west
unit :sludge, 463, 0, :west
unit :captive, 467, 0, :west
unit :captive, 468, 0, :west
unit :archer, 470, 0, :west
unit :thick_sludge, 473, 0, :west
unit :captive, 481, 0, :west
unit :thick_sludge, 486, 0, :west
unit :thick_sludge, 489, 0, :west
unit :archer, 490, 0, :west
unit :wizard, 503, 0, :west
unit :archer, 509, 0, :west
unit :thick_sludge, 512, 0, :west
unit :captive, 516, 0, :west
unit :wizard, 531, 0, :west
unit :sludge, 533, 0, :west
unit :wizard, 537, 0, :west
unit :archer, 547, 0, :west
unit :archer, 548, 0, :west
unit :sludge, 549, 0, :west
unit :archer, 551, 0, :west
unit :thick_sludge, 556, 0, :west
unit :thick_sludge, 557, 0, :west
unit :wizard, 559, 0, :west
unit :thick_sludge, 571, 0, :west
unit :sludge, 572, 0, :west
unit :captive, 573, 0, :west
unit :thick_sludge, 575, 0, :west
unit :archer, 576, 0, :west
unit :sludge, 579, 0, :west
unit :sludge, 583, 0, :west
unit :archer, 587, 0, :west
unit :archer, 589, 0, :west
unit :captive, 591, 0, :west
unit :archer, 595, 0, :west
unit :wizard, 601, 0, :west
unit :sludge, 613, 0, :west
unit :sludge, 615, 0, :west
unit :sludge, 621, 0, :west
unit :captive, 628, 0, :west
unit :sludge, 629, 0, :west
unit :sludge, 630, 0, :west
unit :thick_sludge, 638, 0, :west
unit :captive, 642, 0, :west
unit :sludge, 643, 0, :west
unit :archer, 646, 0, :west
unit :wizard, 651, 0, :west
unit :thick_sludge, 661, 0, :west
unit :archer, 665, 0, :west
unit :sludge, 670, 0, :west
unit :wizard, 672, 0, :west
unit :captive, 674, 0, :west
unit :sludge, 675, 0, :west
unit :archer, 677, 0, :west
unit :thick_sludge, 678, 0, :west
unit :archer, 682, 0, :west
unit :sludge, 685, 0, :west
unit :captive, 687, 0, :west
unit :sludge, 690, 0, :west
unit :wizard, 697, 0, :west
unit :captive, 701, 0, :west
unit :archer, 705, 0, :west
unit :captive, 710, 0, :west
unit :archer, 714, 0, :west
unit :sludge, 719, 0, :west
unit :archer, 722, 0, :west
unit :archer, 725, 0, :west
unit :archer, 727, 0, :west
unit :captive, 735, 0, :west
unit :wizard, 737, 0, :west
unit :wizard, 742, 0, :west
unit :archer, 753, 0, :west
unit :wizard, 755, 0, :west
unit :thick_sludge, 757, 0, :west
unit :sludge, 761, 0, :west
unit :sludge, 763, 0, :west
unit :sludge, 766, 0, :west
unit :wizard, 767, 0, :west
unit :sludge, 778, 0, :west
unit :sludge, 780, 0, :west
unit :archer, 781, 0, :west
unit :captive, 782, 0, :west
unit :thick_sludge, 788, 0, :west
unit :archer, 791, 0, :west
unit :sludge, 792, 0, :west
unit :archer, 793, 0, :west
unit :sludge, 796, 0, :west
unit :captive, 799, 0, :west
unit :sludge, 801, 0, :west
unit :archer, 802, 0, :west
unit :archer, 808, 0, :west
unit :archer, 809, 0, :west
unit :sludge, 810, 0, :west
unit :thick_sludge, 814, 0, :west
unit :captive, 818, 0, :west
unit :sludge, 823, 0, :west
unit :wizard, 825, 0, :west
unit :archer, 831, 0, :west
unit :wizard, 836, 0, :west
unit :sludge, 841, 0, :west
unit :archer, 845, 0, :west
unit :thick_sludge, 846, 0, :west
unit :thick_sludge, 853, 0, :west
unit :sludge, 866, 0, :west
unit :thick_sludge, 867, 0, :west
unit :wizard, 874, 0, :west
unit :captive, 875, 0, :west
unit :sludge, 876, 0, :west
unit :captive, 880, 0, :west
unit :wizard, 885, 0, :west
unit :sludge, 889, 0, :west
unit :sludge, 892, 0, :west
