#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       s  aw   aS S a ssss      ssS w   a  w C    SCwa w         a a    C     S    >      Cs        wC        s    a sC        C  S    S   S  aS     a C    S     S     C             CC       s     w     Sa      s      ss a               s C s      w    a w w     wss  Ca    w     @   saC                S  S C w  s    C   sS w   S        s  S   w  a s C     s    a     a          s  a           s   S  w    a   w  a  C  a s   a a           sCC   s a    S    S            a        C   a C          s    a      aSCSS   wS       a   S a     s    a sS            C  w S SS   a   aw   C          sS     s           a       C S    w   CS     S a    w  a a   a  C Ss w    s      C sC     C  C s   Sw a aw Sa  ss   w  s wS       a      a  a aa     a    C  C   s       s   sC S   s    s         w  S   aws       w  aa    S S    a      s          S  a    s      sss    S|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 860
ace_score 4300
size 860, 1
stairs 83, 0

warrior 280, 0, :east

unit :sludge, 7, 0, :east
unit :archer, 10, 0, :east
unit :wizard, 11, 0, :east
unit :archer, 15, 0, :east
unit :thick_sludge, 16, 0, :east
unit :thick_sludge, 18, 0, :east
unit :archer, 20, 0, :east
unit :sludge, 22, 0, :east
unit :sludge, 23, 0, :east
unit :sludge, 24, 0, :east
unit :sludge, 25, 0, :east
unit :sludge, 32, 0, :east
unit :sludge, 33, 0, :east
unit :thick_sludge, 34, 0, :east
unit :wizard, 36, 0, :east
unit :archer, 40, 0, :east
unit :wizard, 43, 0, :east
unit :captive, 45, 0, :east
unit :thick_sludge, 50, 0, :east
unit :captive, 51, 0, :east
unit :wizard, 52, 0, :east
unit :archer, 53, 0, :east
unit :wizard, 55, 0, :east
unit :archer, 65, 0, :east
unit :archer, 67, 0, :east
unit :captive, 72, 0, :east
unit :thick_sludge, 78, 0, :east
unit :captive, 90, 0, :east
unit :sludge, 91, 0, :east
unit :wizard, 100, 0, :east
unit :captive, 101, 0, :east
unit :sludge, 110, 0, :east
unit :archer, 115, 0, :east
unit :sludge, 117, 0, :east
unit :captive, 118, 0, :east
unit :captive, 127, 0, :east
unit :thick_sludge, 130, 0, :east
unit :thick_sludge, 135, 0, :east
unit :thick_sludge, 139, 0, :east
unit :archer, 142, 0, :east
unit :thick_sludge, 143, 0, :east
unit :archer, 149, 0, :east
unit :captive, 151, 0, :east
unit :thick_sludge, 156, 0, :east
unit :thick_sludge, 162, 0, :east
unit :captive, 168, 0, :east
unit :captive, 182, 0, :east
unit :captive, 183, 0, :east
unit :sludge, 191, 0, :east
unit :wizard, 197, 0, :east
unit :thick_sludge, 203, 0, :east
unit :archer, 204, 0, :east
unit :sludge, 211, 0, :east
unit :sludge, 218, 0, :east
unit :sludge, 219, 0, :east
unit :archer, 221, 0, :east
unit :sludge, 237, 0, :east
unit :captive, 239, 0, :east
unit :sludge, 241, 0, :east
unit :wizard, 248, 0, :east
unit :archer, 253, 0, :east
unit :wizard, 255, 0, :east
unit :wizard, 257, 0, :east
unit :wizard, 263, 0, :east
unit :sludge, 264, 0, :east
unit :sludge, 265, 0, :east
unit :captive, 268, 0, :east
unit :archer, 269, 0, :east
unit :wizard, 274, 0, :east
unit :sludge, 284, 0, :west
unit :archer, 285, 0, :west
unit :captive, 286, 0, :west
unit :thick_sludge, 303, 0, :west
unit :thick_sludge, 306, 0, :west
unit :captive, 308, 0, :west
unit :wizard, 310, 0, :west
unit :sludge, 313, 0, :west
unit :captive, 318, 0, :west
unit :sludge, 322, 0, :west
unit :thick_sludge, 323, 0, :west
unit :wizard, 325, 0, :west
unit :thick_sludge, 329, 0, :west
unit :sludge, 338, 0, :west
unit :thick_sludge, 341, 0, :west
unit :wizard, 345, 0, :west
unit :archer, 348, 0, :west
unit :sludge, 350, 0, :west
unit :captive, 352, 0, :west
unit :sludge, 358, 0, :west
unit :archer, 363, 0, :west
unit :archer, 369, 0, :west
unit :sludge, 380, 0, :west
unit :archer, 383, 0, :west
unit :sludge, 395, 0, :west
unit :thick_sludge, 399, 0, :west
unit :wizard, 402, 0, :west
unit :archer, 407, 0, :west
unit :wizard, 411, 0, :west
unit :archer, 414, 0, :west
unit :captive, 417, 0, :west
unit :archer, 420, 0, :west
unit :sludge, 422, 0, :west
unit :archer, 426, 0, :west
unit :archer, 428, 0, :west
unit :sludge, 440, 0, :west
unit :captive, 441, 0, :west
unit :captive, 442, 0, :west
unit :sludge, 446, 0, :west
unit :archer, 448, 0, :west
unit :thick_sludge, 453, 0, :west
unit :thick_sludge, 458, 0, :west
unit :archer, 471, 0, :west
unit :captive, 480, 0, :west
unit :archer, 484, 0, :west
unit :captive, 486, 0, :west
unit :sludge, 497, 0, :west
unit :archer, 502, 0, :west
unit :archer, 509, 0, :west
unit :thick_sludge, 510, 0, :west
unit :captive, 511, 0, :west
unit :thick_sludge, 512, 0, :west
unit :thick_sludge, 513, 0, :west
unit :wizard, 517, 0, :west
unit :thick_sludge, 518, 0, :west
unit :archer, 526, 0, :west
unit :thick_sludge, 530, 0, :west
unit :archer, 532, 0, :west
unit :sludge, 538, 0, :west
unit :archer, 543, 0, :west
unit :sludge, 545, 0, :west
unit :thick_sludge, 546, 0, :west
unit :captive, 559, 0, :west
unit :wizard, 562, 0, :west
unit :thick_sludge, 564, 0, :west
unit :thick_sludge, 566, 0, :west
unit :thick_sludge, 567, 0, :west
unit :archer, 571, 0, :west
unit :archer, 575, 0, :west
unit :wizard, 576, 0, :west
unit :captive, 580, 0, :west
unit :sludge, 591, 0, :west
unit :thick_sludge, 592, 0, :west
unit :sludge, 598, 0, :west
unit :archer, 610, 0, :west
unit :captive, 618, 0, :west
unit :thick_sludge, 620, 0, :west
unit :wizard, 625, 0, :west
unit :captive, 629, 0, :west
unit :thick_sludge, 630, 0, :west
unit :thick_sludge, 636, 0, :west
unit :archer, 638, 0, :west
unit :wizard, 643, 0, :west
unit :archer, 646, 0, :west
unit :archer, 648, 0, :west
unit :archer, 652, 0, :west
unit :captive, 655, 0, :west
unit :thick_sludge, 657, 0, :west
unit :sludge, 658, 0, :west
unit :wizard, 660, 0, :west
unit :sludge, 665, 0, :west
unit :captive, 672, 0, :west
unit :sludge, 674, 0, :west
unit :captive, 675, 0, :west
unit :captive, 681, 0, :west
unit :captive, 684, 0, :west
unit :sludge, 686, 0, :west
unit :thick_sludge, 690, 0, :west
unit :wizard, 691, 0, :west
unit :archer, 693, 0, :west
unit :archer, 695, 0, :west
unit :wizard, 696, 0, :west
unit :thick_sludge, 698, 0, :west
unit :archer, 699, 0, :west
unit :sludge, 702, 0, :west
unit :sludge, 703, 0, :west
unit :wizard, 707, 0, :west
unit :sludge, 710, 0, :west
unit :wizard, 712, 0, :west
unit :thick_sludge, 713, 0, :west
unit :archer, 721, 0, :west
unit :archer, 728, 0, :west
unit :archer, 731, 0, :west
unit :archer, 733, 0, :west
unit :archer, 734, 0, :west
unit :archer, 740, 0, :west
unit :captive, 745, 0, :west
unit :captive, 748, 0, :west
unit :sludge, 752, 0, :west
unit :sludge, 760, 0, :west
unit :sludge, 764, 0, :west
unit :captive, 765, 0, :west
unit :thick_sludge, 767, 0, :west
unit :sludge, 771, 0, :west
unit :sludge, 776, 0, :west
unit :wizard, 786, 0, :west
unit :thick_sludge, 789, 0, :west
unit :archer, 793, 0, :west
unit :wizard, 794, 0, :west
unit :sludge, 795, 0, :west
unit :wizard, 803, 0, :west
unit :archer, 806, 0, :west
unit :archer, 807, 0, :west
unit :thick_sludge, 812, 0, :west
unit :thick_sludge, 814, 0, :west
unit :archer, 819, 0, :west
unit :sludge, 826, 0, :west
unit :thick_sludge, 837, 0, :west
unit :archer, 840, 0, :west
unit :sludge, 845, 0, :west
unit :sludge, 852, 0, :west
unit :sludge, 853, 0, :west
unit :sludge, 854, 0, :west
unit :thick_sludge, 859, 0, :west
