#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |aS a  a w      w      s S wSaw s    a       S    s C S C       s  C C         sw SC a        SC       w       a       s        s s          a  a S    C      s      w C   s  s   w   a   s    as  aC  aw     aS w     wS  s as    SS  @       SC   a    a         w w         Sa   a     a             w  aC        sa        S a     S  CSS a s s C  >Sa          CC  w s  C  S ws  as          w     s  w C C  C   SsS    s   a w   C a       C   w   C    C C        wa  s  s s sSC w  S         ws       w   s     as S              a s   C   s   a C C    w             C      w a   s          w     S   w     Sa w  C  s       a   C  CC         C         C a a  s      a    C a  s     a S             w  S  a w  C    s   SC S  Ss  w a   aa a C  s   w  a        aw s      a  S s  C       S  C   C  S   S          S    a      s    S         Ss     CCS    S S                 w SC a wa     CS    a   s     s   Cs    S S       C  w      C       a C   a w C  S        aa          w  s   |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 970
ace_score 4850
size 970, 1
stairs 342, 0

warrior 230, 0, :east

unit :archer, 0, 0, :east
unit :thick_sludge, 1, 0, :east
unit :archer, 3, 0, :east
unit :archer, 6, 0, :east
unit :wizard, 8, 0, :east
unit :wizard, 15, 0, :east
unit :sludge, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :wizard, 26, 0, :east
unit :thick_sludge, 27, 0, :east
unit :archer, 28, 0, :east
unit :wizard, 29, 0, :east
unit :sludge, 31, 0, :east
unit :archer, 36, 0, :east
unit :thick_sludge, 44, 0, :east
unit :sludge, 49, 0, :east
unit :captive, 51, 0, :east
unit :thick_sludge, 53, 0, :east
unit :captive, 55, 0, :east
unit :sludge, 63, 0, :east
unit :captive, 66, 0, :east
unit :captive, 68, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 79, 0, :east
unit :thick_sludge, 81, 0, :east
unit :captive, 82, 0, :east
unit :archer, 84, 0, :east
unit :thick_sludge, 93, 0, :east
unit :captive, 94, 0, :east
unit :wizard, 102, 0, :east
unit :archer, 110, 0, :east
unit :sludge, 118, 0, :east
unit :sludge, 127, 0, :east
unit :sludge, 129, 0, :east
unit :archer, 140, 0, :east
unit :archer, 143, 0, :east
unit :thick_sludge, 145, 0, :east
unit :captive, 150, 0, :east
unit :sludge, 157, 0, :east
unit :wizard, 164, 0, :east
unit :captive, 166, 0, :east
unit :sludge, 170, 0, :east
unit :sludge, 173, 0, :east
unit :wizard, 177, 0, :east
unit :archer, 181, 0, :east
unit :sludge, 185, 0, :east
unit :archer, 190, 0, :east
unit :sludge, 191, 0, :east
unit :archer, 194, 0, :east
unit :captive, 195, 0, :east
unit :archer, 198, 0, :east
unit :wizard, 199, 0, :east
unit :archer, 205, 0, :east
unit :thick_sludge, 206, 0, :east
unit :wizard, 208, 0, :east
unit :wizard, 214, 0, :east
unit :thick_sludge, 215, 0, :east
unit :sludge, 218, 0, :east
unit :archer, 220, 0, :east
unit :sludge, 221, 0, :east
unit :thick_sludge, 226, 0, :east
unit :thick_sludge, 227, 0, :east
unit :thick_sludge, 238, 0, :west
unit :captive, 239, 0, :west
unit :archer, 243, 0, :west
unit :archer, 248, 0, :west
unit :wizard, 258, 0, :west
unit :wizard, 260, 0, :west
unit :thick_sludge, 270, 0, :west
unit :archer, 271, 0, :west
unit :archer, 275, 0, :west
unit :archer, 281, 0, :west
unit :wizard, 295, 0, :west
unit :archer, 298, 0, :west
unit :captive, 299, 0, :west
unit :sludge, 308, 0, :west
unit :archer, 309, 0, :west
unit :thick_sludge, 318, 0, :west
unit :archer, 320, 0, :west
unit :thick_sludge, 326, 0, :west
unit :captive, 329, 0, :west
unit :thick_sludge, 330, 0, :west
unit :thick_sludge, 331, 0, :west
unit :archer, 333, 0, :west
unit :sludge, 335, 0, :west
unit :sludge, 337, 0, :west
unit :captive, 339, 0, :west
unit :thick_sludge, 343, 0, :west
unit :archer, 344, 0, :west
unit :captive, 355, 0, :west
unit :captive, 356, 0, :west
unit :wizard, 359, 0, :west
unit :sludge, 361, 0, :west
unit :captive, 364, 0, :west
unit :thick_sludge, 367, 0, :west
unit :wizard, 369, 0, :west
unit :sludge, 370, 0, :west
unit :archer, 373, 0, :west
unit :sludge, 374, 0, :west
unit :wizard, 385, 0, :west
unit :sludge, 391, 0, :west
unit :wizard, 394, 0, :west
unit :captive, 396, 0, :west
unit :captive, 398, 0, :west
unit :captive, 401, 0, :west
unit :thick_sludge, 405, 0, :west
unit :sludge, 406, 0, :west
unit :thick_sludge, 407, 0, :west
unit :sludge, 412, 0, :west
unit :archer, 416, 0, :west
unit :wizard, 418, 0, :west
unit :captive, 422, 0, :west
unit :archer, 424, 0, :west
unit :captive, 432, 0, :west
unit :wizard, 436, 0, :west
unit :captive, 440, 0, :west
unit :captive, 445, 0, :west
unit :captive, 447, 0, :west
unit :wizard, 456, 0, :west
unit :archer, 457, 0, :west
unit :sludge, 460, 0, :west
unit :sludge, 463, 0, :west
unit :sludge, 465, 0, :west
unit :sludge, 467, 0, :west
unit :thick_sludge, 468, 0, :west
unit :captive, 469, 0, :west
unit :wizard, 471, 0, :west
unit :thick_sludge, 474, 0, :west
unit :wizard, 484, 0, :west
unit :sludge, 485, 0, :west
unit :wizard, 493, 0, :west
unit :sludge, 497, 0, :west
unit :archer, 503, 0, :west
unit :sludge, 504, 0, :west
unit :thick_sludge, 506, 0, :west
unit :archer, 521, 0, :west
unit :sludge, 523, 0, :west
unit :captive, 527, 0, :west
unit :sludge, 531, 0, :west
unit :archer, 535, 0, :west
unit :captive, 537, 0, :west
unit :captive, 539, 0, :west
unit :wizard, 544, 0, :west
unit :captive, 558, 0, :west
unit :wizard, 565, 0, :west
unit :archer, 567, 0, :west
unit :sludge, 571, 0, :west
unit :wizard, 582, 0, :west
unit :thick_sludge, 588, 0, :west
unit :wizard, 592, 0, :west
unit :thick_sludge, 598, 0, :west
unit :archer, 599, 0, :west
unit :wizard, 601, 0, :west
unit :captive, 604, 0, :west
unit :sludge, 607, 0, :west
unit :archer, 615, 0, :west
unit :captive, 619, 0, :west
unit :captive, 622, 0, :west
unit :captive, 623, 0, :west
unit :captive, 633, 0, :west
unit :captive, 643, 0, :west
unit :archer, 645, 0, :west
unit :archer, 647, 0, :west
unit :sludge, 650, 0, :west
unit :archer, 657, 0, :west
unit :captive, 662, 0, :west
unit :archer, 664, 0, :west
unit :sludge, 667, 0, :west
unit :archer, 673, 0, :west
unit :thick_sludge, 675, 0, :west
unit :wizard, 689, 0, :west
unit :thick_sludge, 692, 0, :west
unit :archer, 695, 0, :west
unit :wizard, 697, 0, :west
unit :captive, 700, 0, :west
unit :sludge, 705, 0, :west
unit :thick_sludge, 709, 0, :west
unit :captive, 710, 0, :west
unit :thick_sludge, 712, 0, :west
unit :thick_sludge, 715, 0, :west
unit :sludge, 716, 0, :west
unit :wizard, 719, 0, :west
unit :archer, 721, 0, :west
unit :archer, 725, 0, :west
unit :archer, 726, 0, :west
unit :archer, 728, 0, :west
unit :captive, 730, 0, :west
unit :sludge, 733, 0, :west
unit :wizard, 737, 0, :west
unit :archer, 740, 0, :west
unit :archer, 749, 0, :west
unit :wizard, 750, 0, :west
unit :sludge, 752, 0, :west
unit :archer, 759, 0, :west
unit :thick_sludge, 762, 0, :west
unit :sludge, 764, 0, :west
unit :captive, 767, 0, :west
unit :thick_sludge, 775, 0, :west
unit :captive, 778, 0, :west
unit :captive, 782, 0, :west
unit :thick_sludge, 785, 0, :west
unit :thick_sludge, 789, 0, :west
unit :thick_sludge, 800, 0, :west
unit :archer, 805, 0, :west
unit :sludge, 812, 0, :west
unit :thick_sludge, 817, 0, :west
unit :thick_sludge, 827, 0, :west
unit :sludge, 828, 0, :west
unit :captive, 834, 0, :west
unit :captive, 835, 0, :west
unit :thick_sludge, 836, 0, :west
unit :thick_sludge, 841, 0, :west
unit :thick_sludge, 843, 0, :west
unit :wizard, 861, 0, :west
unit :thick_sludge, 863, 0, :west
unit :captive, 864, 0, :west
unit :archer, 866, 0, :west
unit :wizard, 868, 0, :west
unit :archer, 869, 0, :west
unit :captive, 875, 0, :west
unit :thick_sludge, 876, 0, :west
unit :archer, 881, 0, :west
unit :sludge, 885, 0, :west
unit :sludge, 891, 0, :west
unit :captive, 895, 0, :west
unit :sludge, 896, 0, :west
unit :thick_sludge, 901, 0, :west
unit :thick_sludge, 903, 0, :west
unit :captive, 911, 0, :west
unit :wizard, 914, 0, :west
unit :captive, 921, 0, :west
unit :archer, 929, 0, :west
unit :captive, 931, 0, :west
unit :archer, 935, 0, :west
unit :wizard, 937, 0, :west
unit :captive, 939, 0, :west
unit :thick_sludge, 942, 0, :west
unit :archer, 951, 0, :west
unit :archer, 952, 0, :west
unit :wizard, 963, 0, :west
unit :sludge, 966, 0, :west
