#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |        S             a    s    w     a  S  a       as s    S   S CsaS w            ss  S a        a       a    w    @   CC  w     sS a s  C         aC   s      w wS  CCS  w          a       s   S          sw       w C sw  S   C  S   s                  aaS   s  w    C SS S   S a  a        w w  s  C w S a             Ss   C w  S   aa S  C      C  w   s  s       a S >     a S  S         ss  CC     C  ws a  C    s       sC    w   s    S            SC  s                     C  S       s   w      aC S        C       as  w      S       aC        S   a  a  w   sS     C    a S    w  C w     ws    w   Css   w SaC C        a C         s CC   C    C    S   w           Cw  w         S   S    Sw   w     C      C    C   C             w C    aC a      w       S  S      a   a  a a    w C C  C a    w        CC     C   SSssa     SSCw aw w   S S s   wsC C  a  w    w   a     C       w  w   Sw  asS  aa w     C  |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 904
ace_score 4520
size 904, 1
stairs 367, 0

warrior 117, 0, :east

unit :thick_sludge, 8, 0, :east
unit :archer, 22, 0, :east
unit :sludge, 27, 0, :east
unit :wizard, 32, 0, :east
unit :archer, 38, 0, :east
unit :thick_sludge, 41, 0, :east
unit :archer, 44, 0, :east
unit :archer, 52, 0, :east
unit :sludge, 53, 0, :east
unit :sludge, 55, 0, :east
unit :thick_sludge, 60, 0, :east
unit :thick_sludge, 64, 0, :east
unit :captive, 66, 0, :east
unit :sludge, 67, 0, :east
unit :archer, 68, 0, :east
unit :thick_sludge, 69, 0, :east
unit :wizard, 71, 0, :east
unit :sludge, 84, 0, :east
unit :sludge, 85, 0, :east
unit :thick_sludge, 88, 0, :east
unit :archer, 90, 0, :east
unit :archer, 99, 0, :east
unit :archer, 107, 0, :east
unit :wizard, 112, 0, :east
unit :captive, 121, 0, :west
unit :captive, 122, 0, :west
unit :wizard, 125, 0, :west
unit :sludge, 131, 0, :west
unit :thick_sludge, 132, 0, :west
unit :archer, 134, 0, :west
unit :sludge, 136, 0, :west
unit :captive, 139, 0, :west
unit :archer, 149, 0, :west
unit :captive, 150, 0, :west
unit :sludge, 154, 0, :west
unit :wizard, 161, 0, :west
unit :wizard, 163, 0, :west
unit :thick_sludge, 164, 0, :west
unit :captive, 167, 0, :west
unit :captive, 168, 0, :west
unit :thick_sludge, 169, 0, :west
unit :wizard, 172, 0, :west
unit :archer, 183, 0, :west
unit :sludge, 191, 0, :west
unit :thick_sludge, 195, 0, :west
unit :sludge, 206, 0, :west
unit :wizard, 207, 0, :west
unit :wizard, 215, 0, :west
unit :captive, 217, 0, :west
unit :sludge, 219, 0, :west
unit :wizard, 220, 0, :west
unit :thick_sludge, 223, 0, :west
unit :captive, 227, 0, :west
unit :thick_sludge, 230, 0, :west
unit :sludge, 234, 0, :west
unit :archer, 253, 0, :west
unit :archer, 254, 0, :west
unit :thick_sludge, 255, 0, :west
unit :sludge, 259, 0, :west
unit :wizard, 262, 0, :west
unit :captive, 267, 0, :west
unit :thick_sludge, 269, 0, :west
unit :thick_sludge, 270, 0, :west
unit :thick_sludge, 272, 0, :west
unit :thick_sludge, 276, 0, :west
unit :archer, 278, 0, :west
unit :archer, 281, 0, :west
unit :wizard, 290, 0, :west
unit :wizard, 292, 0, :west
unit :sludge, 295, 0, :west
unit :captive, 298, 0, :west
unit :wizard, 300, 0, :west
unit :thick_sludge, 302, 0, :west
unit :archer, 304, 0, :west
unit :thick_sludge, 318, 0, :west
unit :sludge, 319, 0, :west
unit :captive, 323, 0, :west
unit :wizard, 325, 0, :west
unit :thick_sludge, 328, 0, :west
unit :archer, 332, 0, :west
unit :archer, 333, 0, :west
unit :thick_sludge, 335, 0, :west
unit :captive, 338, 0, :west
unit :captive, 345, 0, :west
unit :wizard, 348, 0, :west
unit :sludge, 352, 0, :west
unit :sludge, 355, 0, :west
unit :archer, 363, 0, :west
unit :thick_sludge, 365, 0, :west
unit :archer, 373, 0, :west
unit :thick_sludge, 375, 0, :west
unit :thick_sludge, 378, 0, :west
unit :sludge, 388, 0, :west
unit :sludge, 389, 0, :west
unit :captive, 392, 0, :west
unit :captive, 393, 0, :west
unit :captive, 399, 0, :west
unit :wizard, 402, 0, :west
unit :sludge, 403, 0, :west
unit :archer, 405, 0, :west
unit :captive, 408, 0, :west
unit :sludge, 413, 0, :west
unit :sludge, 421, 0, :west
unit :captive, 422, 0, :west
unit :wizard, 427, 0, :west
unit :sludge, 431, 0, :west
unit :thick_sludge, 436, 0, :west
unit :thick_sludge, 449, 0, :west
unit :captive, 450, 0, :west
unit :sludge, 453, 0, :west
unit :captive, 475, 0, :west
unit :thick_sludge, 478, 0, :west
unit :sludge, 486, 0, :west
unit :wizard, 490, 0, :west
unit :archer, 497, 0, :west
unit :captive, 498, 0, :west
unit :thick_sludge, 500, 0, :west
unit :captive, 509, 0, :west
unit :archer, 517, 0, :west
unit :sludge, 518, 0, :west
unit :wizard, 521, 0, :west
unit :thick_sludge, 528, 0, :west
unit :archer, 536, 0, :west
unit :captive, 537, 0, :west
unit :thick_sludge, 546, 0, :west
unit :archer, 550, 0, :west
unit :archer, 553, 0, :west
unit :wizard, 556, 0, :west
unit :sludge, 560, 0, :west
unit :thick_sludge, 561, 0, :west
unit :captive, 567, 0, :west
unit :archer, 572, 0, :west
unit :thick_sludge, 574, 0, :west
unit :wizard, 579, 0, :west
unit :captive, 582, 0, :west
unit :wizard, 584, 0, :west
unit :wizard, 590, 0, :west
unit :sludge, 591, 0, :west
unit :wizard, 596, 0, :west
unit :captive, 600, 0, :west
unit :sludge, 601, 0, :west
unit :sludge, 602, 0, :west
unit :wizard, 606, 0, :west
unit :thick_sludge, 608, 0, :west
unit :archer, 609, 0, :west
unit :captive, 610, 0, :west
unit :captive, 612, 0, :west
unit :archer, 621, 0, :west
unit :captive, 623, 0, :west
unit :sludge, 633, 0, :west
unit :captive, 635, 0, :west
unit :captive, 636, 0, :west
unit :captive, 640, 0, :west
unit :captive, 645, 0, :west
unit :thick_sludge, 650, 0, :west
unit :wizard, 654, 0, :west
unit :captive, 666, 0, :west
unit :wizard, 667, 0, :west
unit :wizard, 670, 0, :west
unit :thick_sludge, 680, 0, :west
unit :thick_sludge, 684, 0, :west
unit :thick_sludge, 689, 0, :west
unit :wizard, 690, 0, :west
unit :wizard, 694, 0, :west
unit :captive, 700, 0, :west
unit :captive, 707, 0, :west
unit :captive, 712, 0, :west
unit :captive, 716, 0, :west
unit :wizard, 730, 0, :west
unit :captive, 732, 0, :west
unit :archer, 737, 0, :west
unit :captive, 738, 0, :west
unit :archer, 740, 0, :west
unit :wizard, 747, 0, :west
unit :thick_sludge, 755, 0, :west
unit :thick_sludge, 758, 0, :west
unit :archer, 765, 0, :west
unit :archer, 769, 0, :west
unit :archer, 772, 0, :west
unit :archer, 774, 0, :west
unit :wizard, 779, 0, :west
unit :captive, 781, 0, :west
unit :captive, 783, 0, :west
unit :captive, 786, 0, :west
unit :archer, 788, 0, :west
unit :wizard, 793, 0, :west
unit :captive, 802, 0, :west
unit :captive, 803, 0, :west
unit :captive, 809, 0, :west
unit :thick_sludge, 813, 0, :west
unit :thick_sludge, 814, 0, :west
unit :sludge, 815, 0, :west
unit :sludge, 816, 0, :west
unit :archer, 817, 0, :west
unit :thick_sludge, 823, 0, :west
unit :thick_sludge, 824, 0, :west
unit :captive, 825, 0, :west
unit :wizard, 826, 0, :west
unit :archer, 828, 0, :west
unit :wizard, 829, 0, :west
unit :wizard, 831, 0, :west
unit :thick_sludge, 835, 0, :west
unit :thick_sludge, 837, 0, :west
unit :sludge, 839, 0, :west
unit :wizard, 843, 0, :west
unit :sludge, 844, 0, :west
unit :captive, 845, 0, :west
unit :captive, 847, 0, :west
unit :archer, 850, 0, :west
unit :wizard, 853, 0, :west
unit :wizard, 858, 0, :west
unit :archer, 862, 0, :west
unit :captive, 868, 0, :west
unit :wizard, 876, 0, :west
unit :wizard, 879, 0, :west
unit :thick_sludge, 883, 0, :west
unit :wizard, 884, 0, :west
unit :archer, 887, 0, :west
unit :sludge, 888, 0, :west
unit :thick_sludge, 889, 0, :west
unit :archer, 892, 0, :west
unit :archer, 893, 0, :west
unit :wizard, 895, 0, :west
unit :captive, 901, 0, :west
