#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | w w a          SC    s  a    S    sa  a a s  s    C C S   w a  S    S  a s     C     sC    a         a a     ws S w wSSS      w  S  w      S   S w   S         s   s          w   w aC      a s  s       S      CS    s   S    w  @       s   C w    CCs a S  C C   CS  S   C    a   as         Cs a    s     a    a          C     aw        s   s  w      w s   s aC           ass C  Cw  CC s      a    S S C      CsC    w      a  w          ss       C  C          C   a S   Cs  S Cs C   s S wS    w s    w   CSa             a     Ss    s   C    Sa sS     C C  ss S         CC      Ss w   s    s  a  C     SC  s       C   s C        w              C   S      s      w         wC C      >  wCs C        w    S  aC        w      w         C aa   a             a   a    a  C  w    a   s S w  w ss      s s      C CCC     C      C      s  C  s       s       C w    w  s       sC S    CS w          aw   aC          w   |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 908
ace_score 4540
size 908, 1
stairs 679, 0

warrior 227, 0, :east

unit :wizard, 1, 0, :east
unit :wizard, 3, 0, :east
unit :archer, 5, 0, :east
unit :thick_sludge, 16, 0, :east
unit :captive, 17, 0, :east
unit :sludge, 22, 0, :east
unit :archer, 25, 0, :east
unit :thick_sludge, 30, 0, :east
unit :sludge, 35, 0, :east
unit :archer, 36, 0, :east
unit :archer, 39, 0, :east
unit :archer, 41, 0, :east
unit :sludge, 43, 0, :east
unit :sludge, 46, 0, :east
unit :captive, 51, 0, :east
unit :captive, 53, 0, :east
unit :thick_sludge, 55, 0, :east
unit :wizard, 59, 0, :east
unit :archer, 61, 0, :east
unit :thick_sludge, 64, 0, :east
unit :thick_sludge, 69, 0, :east
unit :archer, 72, 0, :east
unit :sludge, 74, 0, :east
unit :captive, 80, 0, :east
unit :sludge, 86, 0, :east
unit :captive, 87, 0, :east
unit :archer, 92, 0, :east
unit :archer, 102, 0, :east
unit :archer, 104, 0, :east
unit :wizard, 110, 0, :east
unit :sludge, 111, 0, :east
unit :thick_sludge, 113, 0, :east
unit :wizard, 115, 0, :east
unit :wizard, 117, 0, :east
unit :thick_sludge, 118, 0, :east
unit :thick_sludge, 119, 0, :east
unit :thick_sludge, 120, 0, :east
unit :wizard, 127, 0, :east
unit :thick_sludge, 130, 0, :east
unit :wizard, 133, 0, :east
unit :thick_sludge, 140, 0, :east
unit :thick_sludge, 144, 0, :east
unit :wizard, 146, 0, :east
unit :thick_sludge, 150, 0, :east
unit :sludge, 160, 0, :east
unit :sludge, 164, 0, :east
unit :wizard, 175, 0, :east
unit :wizard, 179, 0, :east
unit :archer, 181, 0, :east
unit :captive, 182, 0, :east
unit :archer, 189, 0, :east
unit :sludge, 191, 0, :east
unit :sludge, 194, 0, :east
unit :thick_sludge, 202, 0, :east
unit :captive, 209, 0, :east
unit :thick_sludge, 210, 0, :east
unit :sludge, 215, 0, :east
unit :thick_sludge, 219, 0, :east
unit :wizard, 224, 0, :east
unit :sludge, 235, 0, :west
unit :captive, 239, 0, :west
unit :wizard, 241, 0, :west
unit :captive, 246, 0, :west
unit :captive, 247, 0, :west
unit :sludge, 248, 0, :west
unit :archer, 250, 0, :west
unit :thick_sludge, 252, 0, :west
unit :captive, 255, 0, :west
unit :captive, 257, 0, :west
unit :captive, 261, 0, :west
unit :thick_sludge, 262, 0, :west
unit :thick_sludge, 265, 0, :west
unit :captive, 269, 0, :west
unit :archer, 274, 0, :west
unit :archer, 278, 0, :west
unit :sludge, 279, 0, :west
unit :captive, 289, 0, :west
unit :sludge, 290, 0, :west
unit :archer, 292, 0, :west
unit :sludge, 297, 0, :west
unit :archer, 303, 0, :west
unit :archer, 308, 0, :west
unit :captive, 319, 0, :west
unit :archer, 325, 0, :west
unit :wizard, 326, 0, :west
unit :sludge, 335, 0, :west
unit :sludge, 339, 0, :west
unit :wizard, 342, 0, :west
unit :wizard, 349, 0, :west
unit :sludge, 351, 0, :west
unit :sludge, 355, 0, :west
unit :archer, 357, 0, :west
unit :captive, 358, 0, :west
unit :archer, 370, 0, :west
unit :sludge, 371, 0, :west
unit :sludge, 372, 0, :west
unit :captive, 374, 0, :west
unit :captive, 377, 0, :west
unit :wizard, 378, 0, :west
unit :captive, 381, 0, :west
unit :captive, 382, 0, :west
unit :sludge, 384, 0, :west
unit :archer, 391, 0, :west
unit :thick_sludge, 396, 0, :west
unit :thick_sludge, 398, 0, :west
unit :captive, 400, 0, :west
unit :captive, 407, 0, :west
unit :sludge, 408, 0, :west
unit :captive, 409, 0, :west
unit :wizard, 414, 0, :west
unit :archer, 421, 0, :west
unit :wizard, 424, 0, :west
unit :sludge, 435, 0, :west
unit :sludge, 436, 0, :west
unit :captive, 444, 0, :west
unit :captive, 447, 0, :west
unit :captive, 458, 0, :west
unit :archer, 462, 0, :west
unit :thick_sludge, 464, 0, :west
unit :captive, 468, 0, :west
unit :sludge, 469, 0, :west
unit :thick_sludge, 472, 0, :west
unit :captive, 474, 0, :west
unit :sludge, 475, 0, :west
unit :captive, 477, 0, :west
unit :sludge, 481, 0, :west
unit :thick_sludge, 483, 0, :west
unit :wizard, 485, 0, :west
unit :thick_sludge, 486, 0, :west
unit :wizard, 491, 0, :west
unit :sludge, 493, 0, :west
unit :wizard, 498, 0, :west
unit :captive, 502, 0, :west
unit :thick_sludge, 503, 0, :west
unit :archer, 504, 0, :west
unit :archer, 518, 0, :west
unit :thick_sludge, 524, 0, :west
unit :sludge, 525, 0, :west
unit :sludge, 530, 0, :west
unit :captive, 534, 0, :west
unit :thick_sludge, 539, 0, :west
unit :archer, 540, 0, :west
unit :sludge, 542, 0, :west
unit :thick_sludge, 543, 0, :west
unit :captive, 549, 0, :west
unit :captive, 551, 0, :west
unit :sludge, 554, 0, :west
unit :sludge, 555, 0, :west
unit :thick_sludge, 557, 0, :west
unit :captive, 567, 0, :west
unit :captive, 568, 0, :west
unit :thick_sludge, 575, 0, :west
unit :sludge, 576, 0, :west
unit :wizard, 578, 0, :west
unit :sludge, 582, 0, :west
unit :sludge, 587, 0, :west
unit :archer, 590, 0, :west
unit :captive, 593, 0, :west
unit :thick_sludge, 599, 0, :west
unit :captive, 600, 0, :west
unit :sludge, 603, 0, :west
unit :captive, 611, 0, :west
unit :sludge, 615, 0, :west
unit :captive, 617, 0, :west
unit :wizard, 626, 0, :west
unit :captive, 641, 0, :west
unit :thick_sludge, 645, 0, :west
unit :sludge, 652, 0, :west
unit :wizard, 659, 0, :west
unit :wizard, 669, 0, :west
unit :captive, 670, 0, :west
unit :captive, 672, 0, :west
unit :wizard, 682, 0, :west
unit :captive, 683, 0, :west
unit :sludge, 684, 0, :west
unit :captive, 686, 0, :west
unit :wizard, 695, 0, :west
unit :thick_sludge, 700, 0, :west
unit :archer, 703, 0, :west
unit :captive, 704, 0, :west
unit :wizard, 713, 0, :west
unit :wizard, 720, 0, :west
unit :captive, 730, 0, :west
unit :archer, 732, 0, :west
unit :archer, 733, 0, :west
unit :archer, 737, 0, :west
unit :archer, 751, 0, :west
unit :archer, 755, 0, :west
unit :archer, 760, 0, :west
unit :captive, 763, 0, :west
unit :wizard, 766, 0, :west
unit :archer, 771, 0, :west
unit :sludge, 775, 0, :west
unit :thick_sludge, 777, 0, :west
unit :wizard, 779, 0, :west
unit :wizard, 782, 0, :west
unit :sludge, 784, 0, :west
unit :sludge, 785, 0, :west
unit :sludge, 792, 0, :west
unit :sludge, 794, 0, :west
unit :captive, 801, 0, :west
unit :captive, 803, 0, :west
unit :captive, 804, 0, :west
unit :captive, 805, 0, :west
unit :captive, 811, 0, :west
unit :captive, 818, 0, :west
unit :sludge, 825, 0, :west
unit :captive, 828, 0, :west
unit :sludge, 831, 0, :west
unit :sludge, 839, 0, :west
unit :captive, 847, 0, :west
unit :wizard, 849, 0, :west
unit :wizard, 854, 0, :west
unit :sludge, 857, 0, :west
unit :sludge, 865, 0, :west
unit :captive, 866, 0, :west
unit :thick_sludge, 868, 0, :west
unit :captive, 873, 0, :west
unit :thick_sludge, 874, 0, :west
unit :wizard, 876, 0, :west
unit :archer, 887, 0, :west
unit :wizard, 888, 0, :west
unit :archer, 892, 0, :west
unit :captive, 893, 0, :west
unit :wizard, 904, 0, :west
