#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  aa C  S  as  s   s  Ss   S  w    C   s      as S    w   wsC   S  S s   s s  w C  w         s  C Sw   w  C    Cw s        aC s   s     w   w          w         S      C        Cs   w S    S    C   a    s  C S  w      a      CS   C sw C w   CSC C     S    s w    S   a     w       a a     Ss Sa s  a  Sa   S   S C w s         w ss     s    C w    a      a  w w w            S  a  S Ca  C    CC S   as    w  s   S       s   C S   S    S   @  aS      w  a   C   C        w                 C   w SC  >              sa     w    s S     C     S w     w    a C      C w C a         w a     Ca a s       w    S  S        s          S      sC       C   S    CC       C       w C a S   as          aS      wS  aS           w      wS   a              s a  C      s s      S  C      w  SC w  awS    S      a w     a  S   w |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 812
ace_score 4060
size 812, 1
stairs 497, 0

warrior 438, 0, :east

unit :archer, 2, 0, :east
unit :archer, 3, 0, :east
unit :captive, 5, 0, :east
unit :thick_sludge, 8, 0, :east
unit :archer, 11, 0, :east
unit :sludge, 12, 0, :east
unit :sludge, 15, 0, :east
unit :sludge, 19, 0, :east
unit :thick_sludge, 22, 0, :east
unit :sludge, 23, 0, :east
unit :thick_sludge, 27, 0, :east
unit :wizard, 30, 0, :east
unit :captive, 35, 0, :east
unit :sludge, 39, 0, :east
unit :archer, 46, 0, :east
unit :sludge, 47, 0, :east
unit :thick_sludge, 49, 0, :east
unit :wizard, 54, 0, :east
unit :wizard, 58, 0, :east
unit :sludge, 59, 0, :east
unit :captive, 60, 0, :east
unit :thick_sludge, 64, 0, :east
unit :thick_sludge, 67, 0, :east
unit :sludge, 69, 0, :east
unit :sludge, 73, 0, :east
unit :sludge, 75, 0, :east
unit :wizard, 78, 0, :east
unit :captive, 80, 0, :east
unit :wizard, 83, 0, :east
unit :sludge, 93, 0, :east
unit :captive, 96, 0, :east
unit :thick_sludge, 98, 0, :east
unit :wizard, 99, 0, :east
unit :wizard, 103, 0, :east
unit :captive, 106, 0, :east
unit :captive, 111, 0, :east
unit :wizard, 112, 0, :east
unit :sludge, 114, 0, :east
unit :archer, 123, 0, :east
unit :captive, 124, 0, :east
unit :sludge, 126, 0, :east
unit :sludge, 130, 0, :east
unit :wizard, 136, 0, :east
unit :wizard, 140, 0, :east
unit :wizard, 151, 0, :east
unit :thick_sludge, 161, 0, :east
unit :captive, 168, 0, :east
unit :captive, 177, 0, :east
unit :sludge, 178, 0, :east
unit :wizard, 182, 0, :east
unit :thick_sludge, 184, 0, :east
unit :thick_sludge, 189, 0, :east
unit :captive, 194, 0, :east
unit :archer, 198, 0, :east
unit :sludge, 203, 0, :east
unit :captive, 206, 0, :east
unit :thick_sludge, 208, 0, :east
unit :wizard, 211, 0, :east
unit :archer, 218, 0, :east
unit :captive, 225, 0, :east
unit :thick_sludge, 226, 0, :east
unit :captive, 230, 0, :east
unit :sludge, 232, 0, :east
unit :wizard, 233, 0, :east
unit :captive, 235, 0, :east
unit :wizard, 237, 0, :east
unit :captive, 241, 0, :east
unit :thick_sludge, 242, 0, :east
unit :captive, 243, 0, :east
unit :captive, 245, 0, :east
unit :thick_sludge, 251, 0, :east
unit :sludge, 256, 0, :east
unit :wizard, 258, 0, :east
unit :thick_sludge, 263, 0, :east
unit :archer, 267, 0, :east
unit :wizard, 273, 0, :east
unit :archer, 281, 0, :east
unit :archer, 283, 0, :east
unit :thick_sludge, 289, 0, :east
unit :sludge, 290, 0, :east
unit :thick_sludge, 292, 0, :east
unit :archer, 293, 0, :east
unit :sludge, 295, 0, :east
unit :archer, 298, 0, :east
unit :thick_sludge, 301, 0, :east
unit :archer, 302, 0, :east
unit :thick_sludge, 306, 0, :east
unit :thick_sludge, 310, 0, :east
unit :captive, 312, 0, :east
unit :wizard, 314, 0, :east
unit :sludge, 316, 0, :east
unit :wizard, 326, 0, :east
unit :sludge, 328, 0, :east
unit :sludge, 329, 0, :east
unit :sludge, 335, 0, :east
unit :captive, 340, 0, :east
unit :wizard, 342, 0, :east
unit :archer, 347, 0, :east
unit :archer, 354, 0, :east
unit :wizard, 357, 0, :east
unit :wizard, 359, 0, :east
unit :wizard, 361, 0, :east
unit :thick_sludge, 374, 0, :east
unit :archer, 377, 0, :east
unit :thick_sludge, 380, 0, :east
unit :captive, 382, 0, :east
unit :archer, 383, 0, :east
unit :captive, 386, 0, :east
unit :captive, 391, 0, :east
unit :captive, 392, 0, :east
unit :thick_sludge, 394, 0, :east
unit :archer, 398, 0, :east
unit :sludge, 399, 0, :east
unit :wizard, 404, 0, :east
unit :sludge, 407, 0, :east
unit :thick_sludge, 411, 0, :east
unit :sludge, 419, 0, :east
unit :captive, 423, 0, :east
unit :thick_sludge, 425, 0, :east
unit :thick_sludge, 429, 0, :east
unit :thick_sludge, 434, 0, :east
unit :archer, 441, 0, :west
unit :thick_sludge, 442, 0, :west
unit :wizard, 449, 0, :west
unit :archer, 452, 0, :west
unit :captive, 456, 0, :west
unit :captive, 460, 0, :west
unit :wizard, 469, 0, :west
unit :captive, 487, 0, :west
unit :wizard, 491, 0, :west
unit :thick_sludge, 493, 0, :west
unit :captive, 494, 0, :west
unit :sludge, 512, 0, :west
unit :archer, 513, 0, :west
unit :wizard, 519, 0, :west
unit :sludge, 524, 0, :west
unit :thick_sludge, 526, 0, :west
unit :captive, 532, 0, :west
unit :thick_sludge, 538, 0, :west
unit :wizard, 540, 0, :west
unit :wizard, 546, 0, :west
unit :archer, 551, 0, :west
unit :captive, 553, 0, :west
unit :captive, 560, 0, :west
unit :wizard, 562, 0, :west
unit :captive, 564, 0, :west
unit :archer, 566, 0, :west
unit :wizard, 576, 0, :west
unit :archer, 578, 0, :west
unit :captive, 584, 0, :west
unit :archer, 585, 0, :west
unit :archer, 587, 0, :west
unit :sludge, 589, 0, :west
unit :wizard, 597, 0, :west
unit :thick_sludge, 602, 0, :west
unit :thick_sludge, 605, 0, :west
unit :sludge, 614, 0, :west
unit :thick_sludge, 625, 0, :west
unit :sludge, 632, 0, :west
unit :captive, 633, 0, :west
unit :captive, 641, 0, :west
unit :thick_sludge, 645, 0, :west
unit :captive, 650, 0, :west
unit :captive, 651, 0, :west
unit :captive, 659, 0, :west
unit :wizard, 667, 0, :west
unit :captive, 669, 0, :west
unit :archer, 671, 0, :west
unit :thick_sludge, 673, 0, :west
unit :archer, 677, 0, :west
unit :sludge, 678, 0, :west
unit :archer, 689, 0, :west
unit :thick_sludge, 690, 0, :west
unit :wizard, 697, 0, :west
unit :thick_sludge, 698, 0, :west
unit :archer, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :wizard, 714, 0, :west
unit :wizard, 721, 0, :west
unit :thick_sludge, 722, 0, :west
unit :archer, 726, 0, :west
unit :sludge, 741, 0, :west
unit :archer, 743, 0, :west
unit :captive, 746, 0, :west
unit :sludge, 753, 0, :west
unit :sludge, 755, 0, :west
unit :thick_sludge, 762, 0, :west
unit :captive, 765, 0, :west
unit :wizard, 772, 0, :west
unit :thick_sludge, 775, 0, :west
unit :captive, 776, 0, :west
unit :wizard, 778, 0, :west
unit :archer, 781, 0, :west
unit :wizard, 782, 0, :west
unit :thick_sludge, 783, 0, :west
unit :thick_sludge, 788, 0, :west
unit :archer, 795, 0, :west
unit :wizard, 797, 0, :west
unit :archer, 803, 0, :west
unit :thick_sludge, 806, 0, :west
unit :wizard, 810, 0, :west
