#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  a C   a                a          w   SC Cw      S          w  a     S       S C  C a   S  s  S      w a   s  s C  w  as   sC  C  sa   aC   C  wC            wCS                 sC  C C    ws     a  s   S      a   w     aw  C  w       s   a  w s     C  S a  SCS w CC  s a s  a S    s     SsSaC  a    w   S        sw  w        aS  w      w s   s    s                   a CC           S               a C   S S    S C S             @   C      s  s  a   s  a       s   w S   a  s       w       w          s  s  sw w   Css                  aa    aCa    w  w    w wsS S        a                 s  a        s   w    s a a    S      CS SSsa      S  S C     w      a   CssC        S    a   a S ss Csa   a   s S    >C    S      S   a s  sa   s  aSC   a  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 747
ace_score 3735
size 747, 1
stairs 708, 0

warrior 431, 0, :east

unit :archer, 2, 0, :east
unit :captive, 4, 0, :east
unit :archer, 8, 0, :east
unit :archer, 25, 0, :east
unit :wizard, 36, 0, :east
unit :thick_sludge, 40, 0, :east
unit :captive, 41, 0, :east
unit :captive, 43, 0, :east
unit :wizard, 44, 0, :east
unit :thick_sludge, 51, 0, :east
unit :wizard, 62, 0, :east
unit :archer, 65, 0, :east
unit :thick_sludge, 71, 0, :east
unit :thick_sludge, 79, 0, :east
unit :captive, 81, 0, :east
unit :captive, 84, 0, :east
unit :archer, 86, 0, :east
unit :thick_sludge, 90, 0, :east
unit :sludge, 93, 0, :east
unit :thick_sludge, 96, 0, :east
unit :wizard, 103, 0, :east
unit :archer, 105, 0, :east
unit :sludge, 109, 0, :east
unit :sludge, 112, 0, :east
unit :captive, 114, 0, :east
unit :wizard, 117, 0, :east
unit :archer, 120, 0, :east
unit :sludge, 121, 0, :east
unit :sludge, 125, 0, :east
unit :captive, 126, 0, :east
unit :captive, 129, 0, :east
unit :sludge, 132, 0, :east
unit :archer, 133, 0, :east
unit :archer, 137, 0, :east
unit :captive, 138, 0, :east
unit :captive, 142, 0, :east
unit :wizard, 145, 0, :east
unit :captive, 146, 0, :east
unit :wizard, 159, 0, :east
unit :captive, 160, 0, :east
unit :thick_sludge, 161, 0, :east
unit :sludge, 179, 0, :east
unit :captive, 180, 0, :east
unit :captive, 183, 0, :east
unit :captive, 185, 0, :east
unit :wizard, 190, 0, :east
unit :sludge, 191, 0, :east
unit :archer, 197, 0, :east
unit :sludge, 200, 0, :east
unit :thick_sludge, 204, 0, :east
unit :archer, 211, 0, :east
unit :wizard, 215, 0, :east
unit :archer, 221, 0, :east
unit :wizard, 222, 0, :east
unit :captive, 225, 0, :east
unit :wizard, 228, 0, :east
unit :sludge, 236, 0, :east
unit :archer, 240, 0, :east
unit :wizard, 243, 0, :east
unit :sludge, 245, 0, :east
unit :captive, 251, 0, :east
unit :thick_sludge, 254, 0, :east
unit :archer, 256, 0, :east
unit :thick_sludge, 259, 0, :east
unit :captive, 260, 0, :east
unit :thick_sludge, 261, 0, :east
unit :wizard, 263, 0, :east
unit :captive, 265, 0, :east
unit :captive, 266, 0, :east
unit :sludge, 269, 0, :east
unit :archer, 271, 0, :east
unit :sludge, 273, 0, :east
unit :archer, 276, 0, :east
unit :thick_sludge, 278, 0, :east
unit :sludge, 283, 0, :east
unit :thick_sludge, 289, 0, :east
unit :sludge, 290, 0, :east
unit :thick_sludge, 291, 0, :east
unit :archer, 292, 0, :east
unit :captive, 293, 0, :east
unit :archer, 296, 0, :east
unit :wizard, 301, 0, :east
unit :thick_sludge, 305, 0, :east
unit :sludge, 314, 0, :east
unit :wizard, 315, 0, :east
unit :wizard, 318, 0, :east
unit :archer, 327, 0, :east
unit :thick_sludge, 328, 0, :east
unit :wizard, 331, 0, :east
unit :wizard, 338, 0, :east
unit :sludge, 340, 0, :east
unit :sludge, 344, 0, :east
unit :sludge, 349, 0, :east
unit :archer, 369, 0, :east
unit :captive, 371, 0, :east
unit :captive, 372, 0, :east
unit :thick_sludge, 384, 0, :east
unit :archer, 400, 0, :east
unit :captive, 402, 0, :east
unit :thick_sludge, 406, 0, :east
unit :thick_sludge, 408, 0, :east
unit :thick_sludge, 413, 0, :east
unit :captive, 415, 0, :east
unit :thick_sludge, 417, 0, :east
unit :captive, 435, 0, :west
unit :sludge, 442, 0, :west
unit :sludge, 445, 0, :west
unit :archer, 448, 0, :west
unit :sludge, 452, 0, :west
unit :archer, 455, 0, :west
unit :sludge, 463, 0, :west
unit :wizard, 467, 0, :west
unit :thick_sludge, 469, 0, :west
unit :archer, 473, 0, :west
unit :sludge, 476, 0, :west
unit :wizard, 484, 0, :west
unit :wizard, 492, 0, :west
unit :sludge, 503, 0, :west
unit :sludge, 506, 0, :west
unit :sludge, 509, 0, :west
unit :wizard, 510, 0, :west
unit :wizard, 512, 0, :west
unit :captive, 516, 0, :west
unit :sludge, 517, 0, :west
unit :sludge, 518, 0, :west
unit :archer, 537, 0, :west
unit :archer, 538, 0, :west
unit :archer, 543, 0, :west
unit :captive, 544, 0, :west
unit :archer, 545, 0, :west
unit :wizard, 550, 0, :west
unit :wizard, 553, 0, :west
unit :wizard, 558, 0, :west
unit :wizard, 560, 0, :west
unit :sludge, 561, 0, :west
unit :thick_sludge, 562, 0, :west
unit :thick_sludge, 564, 0, :west
unit :archer, 573, 0, :west
unit :sludge, 591, 0, :west
unit :archer, 594, 0, :west
unit :sludge, 603, 0, :west
unit :wizard, 607, 0, :west
unit :sludge, 612, 0, :west
unit :archer, 614, 0, :west
unit :archer, 616, 0, :west
unit :thick_sludge, 621, 0, :west
unit :captive, 628, 0, :west
unit :thick_sludge, 629, 0, :west
unit :thick_sludge, 631, 0, :west
unit :thick_sludge, 632, 0, :west
unit :sludge, 633, 0, :west
unit :archer, 634, 0, :west
unit :thick_sludge, 641, 0, :west
unit :thick_sludge, 644, 0, :west
unit :captive, 646, 0, :west
unit :wizard, 652, 0, :west
unit :archer, 659, 0, :west
unit :captive, 663, 0, :west
unit :sludge, 664, 0, :west
unit :sludge, 665, 0, :west
unit :captive, 666, 0, :west
unit :thick_sludge, 675, 0, :west
unit :archer, 680, 0, :west
unit :archer, 684, 0, :west
unit :thick_sludge, 686, 0, :west
unit :sludge, 688, 0, :west
unit :sludge, 689, 0, :west
unit :captive, 691, 0, :west
unit :sludge, 692, 0, :west
unit :archer, 693, 0, :west
unit :archer, 697, 0, :west
unit :sludge, 701, 0, :west
unit :thick_sludge, 703, 0, :west
unit :captive, 709, 0, :west
unit :thick_sludge, 714, 0, :west
unit :thick_sludge, 721, 0, :west
unit :archer, 725, 0, :west
unit :sludge, 727, 0, :west
unit :sludge, 730, 0, :west
unit :archer, 731, 0, :west
unit :sludge, 735, 0, :west
unit :archer, 738, 0, :west
unit :thick_sludge, 739, 0, :west
unit :captive, 740, 0, :west
unit :archer, 744, 0, :west
