#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       a      a                  w C w         sa   w   s          w sa      C S     sw   s    S       w w   a w       a   S   s  aSCssS     @    a               a w  SsC a a S   C     w s s  w      a   S s   wS s ws w   C      a       w   w s S    C s   w      Cs    a  aC  SS         SwC S S  S  a   s      aws    w   s S  w   s     a        S   S S   S C    C   C      a S                 C aS   s  aC a     a    aS C C         S        S  S      C          S    a   C            w   a    w         Ss    S   aS    S     S s  w   s      Sa  CC s    s       s   a        S         C  w  Saa   wsS >     a C           C   s C  S s aSC S     Cs s  w   a       s   S   S  w   wS  s  a a S  C   s    w S  wa  a   s    s   s    s C       C     C          s        SC     a    sCs    a S w    w   a  C     C|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 803
ace_score 4015
size 803, 1
stairs 599, 0

warrior 141, 0, :east

unit :archer, 7, 0, :east
unit :archer, 14, 0, :east
unit :wizard, 33, 0, :east
unit :captive, 35, 0, :east
unit :wizard, 37, 0, :east
unit :sludge, 47, 0, :east
unit :archer, 48, 0, :east
unit :wizard, 52, 0, :east
unit :sludge, 56, 0, :east
unit :wizard, 67, 0, :east
unit :sludge, 69, 0, :east
unit :archer, 70, 0, :east
unit :captive, 77, 0, :east
unit :thick_sludge, 79, 0, :east
unit :sludge, 85, 0, :east
unit :wizard, 86, 0, :east
unit :sludge, 90, 0, :east
unit :thick_sludge, 95, 0, :east
unit :wizard, 103, 0, :east
unit :wizard, 105, 0, :east
unit :archer, 109, 0, :east
unit :wizard, 111, 0, :east
unit :archer, 119, 0, :east
unit :thick_sludge, 123, 0, :east
unit :sludge, 127, 0, :east
unit :archer, 130, 0, :east
unit :thick_sludge, 131, 0, :east
unit :captive, 132, 0, :east
unit :sludge, 133, 0, :east
unit :sludge, 134, 0, :east
unit :thick_sludge, 135, 0, :east
unit :archer, 146, 0, :west
unit :archer, 162, 0, :west
unit :wizard, 164, 0, :west
unit :thick_sludge, 167, 0, :west
unit :sludge, 168, 0, :west
unit :captive, 169, 0, :west
unit :archer, 171, 0, :west
unit :archer, 173, 0, :west
unit :thick_sludge, 175, 0, :west
unit :captive, 179, 0, :west
unit :wizard, 185, 0, :west
unit :sludge, 187, 0, :west
unit :sludge, 189, 0, :west
unit :wizard, 192, 0, :west
unit :archer, 199, 0, :west
unit :thick_sludge, 203, 0, :west
unit :sludge, 205, 0, :west
unit :wizard, 209, 0, :west
unit :thick_sludge, 210, 0, :west
unit :sludge, 212, 0, :west
unit :wizard, 214, 0, :west
unit :sludge, 215, 0, :west
unit :wizard, 217, 0, :west
unit :captive, 221, 0, :west
unit :archer, 228, 0, :west
unit :wizard, 236, 0, :west
unit :wizard, 240, 0, :west
unit :sludge, 242, 0, :west
unit :thick_sludge, 244, 0, :west
unit :captive, 249, 0, :west
unit :sludge, 251, 0, :west
unit :wizard, 255, 0, :west
unit :captive, 262, 0, :west
unit :sludge, 263, 0, :west
unit :archer, 268, 0, :west
unit :archer, 271, 0, :west
unit :captive, 272, 0, :west
unit :thick_sludge, 275, 0, :west
unit :thick_sludge, 276, 0, :west
unit :thick_sludge, 286, 0, :west
unit :wizard, 287, 0, :west
unit :captive, 288, 0, :west
unit :thick_sludge, 290, 0, :west
unit :thick_sludge, 292, 0, :west
unit :thick_sludge, 295, 0, :west
unit :archer, 298, 0, :west
unit :sludge, 302, 0, :west
unit :archer, 309, 0, :west
unit :wizard, 310, 0, :west
unit :sludge, 311, 0, :west
unit :wizard, 316, 0, :west
unit :sludge, 320, 0, :west
unit :thick_sludge, 322, 0, :west
unit :wizard, 325, 0, :west
unit :sludge, 329, 0, :west
unit :archer, 335, 0, :west
unit :thick_sludge, 344, 0, :west
unit :thick_sludge, 348, 0, :west
unit :thick_sludge, 350, 0, :west
unit :thick_sludge, 354, 0, :west
unit :captive, 356, 0, :west
unit :captive, 361, 0, :west
unit :captive, 365, 0, :west
unit :archer, 372, 0, :west
unit :thick_sludge, 374, 0, :west
unit :captive, 392, 0, :west
unit :archer, 394, 0, :west
unit :thick_sludge, 395, 0, :west
unit :sludge, 399, 0, :west
unit :archer, 402, 0, :west
unit :captive, 403, 0, :west
unit :archer, 405, 0, :west
unit :archer, 411, 0, :west
unit :archer, 416, 0, :west
unit :thick_sludge, 417, 0, :west
unit :captive, 419, 0, :west
unit :captive, 421, 0, :west
unit :thick_sludge, 431, 0, :west
unit :thick_sludge, 440, 0, :west
unit :thick_sludge, 443, 0, :west
unit :captive, 450, 0, :west
unit :thick_sludge, 461, 0, :west
unit :archer, 466, 0, :west
unit :captive, 470, 0, :west
unit :wizard, 483, 0, :west
unit :archer, 487, 0, :west
unit :wizard, 492, 0, :west
unit :thick_sludge, 502, 0, :west
unit :sludge, 503, 0, :west
unit :thick_sludge, 508, 0, :west
unit :archer, 512, 0, :west
unit :thick_sludge, 513, 0, :west
unit :thick_sludge, 518, 0, :west
unit :thick_sludge, 524, 0, :west
unit :sludge, 526, 0, :west
unit :wizard, 529, 0, :west
unit :sludge, 533, 0, :west
unit :thick_sludge, 540, 0, :west
unit :archer, 541, 0, :west
unit :captive, 544, 0, :west
unit :captive, 545, 0, :west
unit :sludge, 547, 0, :west
unit :sludge, 552, 0, :west
unit :sludge, 560, 0, :west
unit :archer, 564, 0, :west
unit :thick_sludge, 573, 0, :west
unit :captive, 583, 0, :west
unit :wizard, 586, 0, :west
unit :thick_sludge, 589, 0, :west
unit :archer, 590, 0, :west
unit :archer, 591, 0, :west
unit :wizard, 595, 0, :west
unit :sludge, 596, 0, :west
unit :thick_sludge, 597, 0, :west
unit :archer, 605, 0, :west
unit :captive, 607, 0, :west
unit :captive, 619, 0, :west
unit :sludge, 623, 0, :west
unit :captive, 625, 0, :west
unit :thick_sludge, 628, 0, :west
unit :sludge, 630, 0, :west
unit :archer, 632, 0, :west
unit :thick_sludge, 633, 0, :west
unit :captive, 634, 0, :west
unit :thick_sludge, 636, 0, :west
unit :captive, 642, 0, :west
unit :sludge, 643, 0, :west
unit :sludge, 645, 0, :west
unit :wizard, 648, 0, :west
unit :archer, 652, 0, :west
unit :sludge, 660, 0, :west
unit :thick_sludge, 664, 0, :west
unit :thick_sludge, 668, 0, :west
unit :wizard, 671, 0, :west
unit :wizard, 675, 0, :west
unit :thick_sludge, 676, 0, :west
unit :sludge, 679, 0, :west
unit :archer, 682, 0, :west
unit :archer, 684, 0, :west
unit :thick_sludge, 686, 0, :west
unit :captive, 689, 0, :west
unit :sludge, 693, 0, :west
unit :wizard, 698, 0, :west
unit :thick_sludge, 700, 0, :west
unit :wizard, 703, 0, :west
unit :archer, 704, 0, :west
unit :archer, 707, 0, :west
unit :sludge, 711, 0, :west
unit :sludge, 716, 0, :west
unit :sludge, 720, 0, :west
unit :sludge, 725, 0, :west
unit :captive, 727, 0, :west
unit :captive, 735, 0, :west
unit :captive, 741, 0, :west
unit :sludge, 752, 0, :west
unit :thick_sludge, 761, 0, :west
unit :captive, 762, 0, :west
unit :archer, 768, 0, :west
unit :sludge, 773, 0, :west
unit :captive, 774, 0, :west
unit :sludge, 775, 0, :west
unit :archer, 780, 0, :west
unit :thick_sludge, 782, 0, :west
unit :wizard, 784, 0, :west
unit :wizard, 789, 0, :west
unit :archer, 793, 0, :west
unit :captive, 796, 0, :west
unit :captive, 802, 0, :west
