#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   s       s s as aS   @       C    w   w  a w    C  S    C     s     S       S w   s   S C     S s     C      s                      s     C   S sa    wa         S a      sSC s       a      s   >   w   sa   SSs C      w  C          S       a  C  w   w    s   SC    S Cs  sC         a       s S s S s Cs   S     C w Ss    w C SS         S  s      S   sS  s  wsCS        S wa     C a    s  a  s             sC   a C  C     C C               s  S      a    S       w             s s    sC ss     s  s sS ssss     w  s  C C   a  SS  Sw  s w       s s  C  s           C  S  S a  S       w  S    w   C w   Cs w S    a   S a  ws  a C  C ws              aa   wa    CsC   C    a   S  C    a  wsa    s    C    a    asC        w  S a    C           w C           w          w a   a  w C         a  C    a w           S     s|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 814
ace_score 4070
size 814, 1
stairs 195, 0

warrior 23, 0, :east

unit :sludge, 3, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 13, 0, :east
unit :archer, 15, 0, :east
unit :sludge, 16, 0, :east
unit :archer, 18, 0, :east
unit :thick_sludge, 19, 0, :east
unit :captive, 31, 0, :west
unit :wizard, 36, 0, :west
unit :wizard, 40, 0, :west
unit :archer, 43, 0, :west
unit :wizard, 45, 0, :west
unit :captive, 50, 0, :west
unit :thick_sludge, 53, 0, :west
unit :captive, 58, 0, :west
unit :sludge, 64, 0, :west
unit :thick_sludge, 70, 0, :west
unit :thick_sludge, 78, 0, :west
unit :wizard, 80, 0, :west
unit :sludge, 84, 0, :west
unit :thick_sludge, 88, 0, :west
unit :captive, 90, 0, :west
unit :thick_sludge, 96, 0, :west
unit :sludge, 98, 0, :west
unit :captive, 104, 0, :west
unit :sludge, 111, 0, :west
unit :sludge, 134, 0, :west
unit :captive, 140, 0, :west
unit :thick_sludge, 144, 0, :west
unit :sludge, 146, 0, :west
unit :archer, 147, 0, :west
unit :wizard, 152, 0, :west
unit :archer, 153, 0, :west
unit :thick_sludge, 163, 0, :west
unit :archer, 165, 0, :west
unit :sludge, 172, 0, :west
unit :thick_sludge, 173, 0, :west
unit :captive, 174, 0, :west
unit :sludge, 176, 0, :west
unit :archer, 184, 0, :west
unit :sludge, 191, 0, :west
unit :wizard, 199, 0, :west
unit :sludge, 203, 0, :west
unit :archer, 204, 0, :west
unit :thick_sludge, 208, 0, :west
unit :thick_sludge, 209, 0, :west
unit :sludge, 210, 0, :west
unit :captive, 212, 0, :west
unit :wizard, 219, 0, :west
unit :captive, 222, 0, :west
unit :thick_sludge, 233, 0, :west
unit :archer, 241, 0, :west
unit :captive, 244, 0, :west
unit :wizard, 247, 0, :west
unit :wizard, 251, 0, :west
unit :sludge, 256, 0, :west
unit :thick_sludge, 260, 0, :west
unit :captive, 261, 0, :west
unit :thick_sludge, 266, 0, :west
unit :captive, 268, 0, :west
unit :sludge, 269, 0, :west
unit :sludge, 272, 0, :west
unit :captive, 273, 0, :west
unit :archer, 283, 0, :west
unit :sludge, 291, 0, :west
unit :thick_sludge, 293, 0, :west
unit :sludge, 295, 0, :west
unit :thick_sludge, 297, 0, :west
unit :sludge, 299, 0, :west
unit :captive, 301, 0, :west
unit :sludge, 302, 0, :west
unit :thick_sludge, 306, 0, :west
unit :captive, 312, 0, :west
unit :wizard, 314, 0, :west
unit :thick_sludge, 316, 0, :west
unit :sludge, 317, 0, :west
unit :wizard, 322, 0, :west
unit :captive, 324, 0, :west
unit :thick_sludge, 326, 0, :west
unit :thick_sludge, 327, 0, :west
unit :thick_sludge, 337, 0, :west
unit :sludge, 340, 0, :west
unit :thick_sludge, 347, 0, :west
unit :sludge, 351, 0, :west
unit :thick_sludge, 352, 0, :west
unit :sludge, 355, 0, :west
unit :wizard, 358, 0, :west
unit :sludge, 359, 0, :west
unit :captive, 360, 0, :west
unit :thick_sludge, 361, 0, :west
unit :thick_sludge, 370, 0, :west
unit :wizard, 372, 0, :west
unit :archer, 373, 0, :west
unit :captive, 379, 0, :west
unit :archer, 381, 0, :west
unit :sludge, 386, 0, :west
unit :archer, 389, 0, :west
unit :sludge, 392, 0, :west
unit :sludge, 406, 0, :west
unit :captive, 407, 0, :west
unit :archer, 411, 0, :west
unit :captive, 413, 0, :west
unit :captive, 416, 0, :west
unit :captive, 422, 0, :west
unit :captive, 424, 0, :west
unit :sludge, 440, 0, :west
unit :thick_sludge, 443, 0, :west
unit :archer, 450, 0, :west
unit :thick_sludge, 455, 0, :west
unit :wizard, 463, 0, :west
unit :sludge, 477, 0, :west
unit :sludge, 479, 0, :west
unit :sludge, 484, 0, :west
unit :captive, 485, 0, :west
unit :sludge, 487, 0, :west
unit :sludge, 488, 0, :west
unit :sludge, 494, 0, :west
unit :sludge, 497, 0, :west
unit :sludge, 499, 0, :west
unit :thick_sludge, 500, 0, :west
unit :sludge, 502, 0, :west
unit :sludge, 503, 0, :west
unit :sludge, 504, 0, :west
unit :sludge, 505, 0, :west
unit :wizard, 511, 0, :west
unit :sludge, 514, 0, :west
unit :captive, 517, 0, :west
unit :captive, 519, 0, :west
unit :archer, 523, 0, :west
unit :thick_sludge, 526, 0, :west
unit :thick_sludge, 527, 0, :west
unit :thick_sludge, 530, 0, :west
unit :wizard, 531, 0, :west
unit :sludge, 534, 0, :west
unit :wizard, 536, 0, :west
unit :sludge, 544, 0, :west
unit :sludge, 546, 0, :west
unit :captive, 549, 0, :west
unit :sludge, 552, 0, :west
unit :captive, 564, 0, :west
unit :thick_sludge, 567, 0, :west
unit :thick_sludge, 570, 0, :west
unit :archer, 572, 0, :west
unit :thick_sludge, 575, 0, :west
unit :wizard, 583, 0, :west
unit :thick_sludge, 586, 0, :west
unit :wizard, 591, 0, :west
unit :captive, 595, 0, :west
unit :wizard, 597, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 602, 0, :west
unit :wizard, 604, 0, :west
unit :thick_sludge, 606, 0, :west
unit :archer, 611, 0, :west
unit :thick_sludge, 615, 0, :west
unit :archer, 617, 0, :west
unit :wizard, 620, 0, :west
unit :sludge, 621, 0, :west
unit :archer, 624, 0, :west
unit :captive, 626, 0, :west
unit :captive, 629, 0, :west
unit :wizard, 631, 0, :west
unit :sludge, 632, 0, :west
unit :archer, 647, 0, :west
unit :archer, 648, 0, :west
unit :wizard, 652, 0, :west
unit :archer, 653, 0, :west
unit :captive, 658, 0, :west
unit :sludge, 659, 0, :west
unit :captive, 660, 0, :west
unit :captive, 664, 0, :west
unit :archer, 669, 0, :west
unit :thick_sludge, 673, 0, :west
unit :captive, 676, 0, :west
unit :archer, 681, 0, :west
unit :wizard, 684, 0, :west
unit :sludge, 685, 0, :west
unit :archer, 686, 0, :west
unit :sludge, 691, 0, :west
unit :captive, 696, 0, :west
unit :archer, 701, 0, :west
unit :archer, 706, 0, :west
unit :sludge, 707, 0, :west
unit :captive, 708, 0, :west
unit :wizard, 717, 0, :west
unit :thick_sludge, 720, 0, :west
unit :archer, 722, 0, :west
unit :captive, 727, 0, :west
unit :wizard, 739, 0, :west
unit :captive, 741, 0, :west
unit :wizard, 753, 0, :west
unit :wizard, 764, 0, :west
unit :archer, 766, 0, :west
unit :archer, 770, 0, :west
unit :wizard, 773, 0, :west
unit :captive, 775, 0, :west
unit :archer, 785, 0, :west
unit :captive, 788, 0, :west
unit :archer, 793, 0, :west
unit :wizard, 795, 0, :west
unit :thick_sludge, 807, 0, :west
unit :sludge, 813, 0, :west
