#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    w     SC C    s     Cw   SS           C               a a S    sS   s          w   a sa      SC aS   S a S   S w ws s         S          s        S  S   C aS   C        S  a S s S     s a        CSC   w w    SwSs SC wSS C      sC a   C      w s          C        C C    s w        C       S  a         a   a   C C     C sCS  S   w S S  C  ws   C  S    s     S  a      sCaC    C   sa S   CS  w      w  w s    C  ws    C     C   a S     w   C S w   a Cs       C C S    w S   a    a SC  C     a  C      w     w     S             s   w  aC C w C  s  s      a    C S   s  wS    w   S    Sw  w    a a    a w      C s  CC      a         S        a         C  S  aC    S  a     S w CsSs      S  >  a ws  C                    C   Cs  s        aC S  S  C            s    w    S    as s a      S   a          s   a    S   s        wS       Ca   C a S    s s             Cw               s    s      w  aS  @        S as w     C        C w  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 933
ace_score 4665
size 933, 1
stairs 691, 0

warrior 899, 0, :east

unit :wizard, 4, 0, :east
unit :thick_sludge, 10, 0, :east
unit :captive, 11, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 18, 0, :east
unit :captive, 24, 0, :east
unit :wizard, 25, 0, :east
unit :thick_sludge, 29, 0, :east
unit :thick_sludge, 30, 0, :east
unit :captive, 42, 0, :east
unit :archer, 58, 0, :east
unit :archer, 60, 0, :east
unit :thick_sludge, 62, 0, :east
unit :sludge, 67, 0, :east
unit :thick_sludge, 68, 0, :east
unit :sludge, 72, 0, :east
unit :wizard, 83, 0, :east
unit :archer, 87, 0, :east
unit :sludge, 89, 0, :east
unit :archer, 90, 0, :east
unit :thick_sludge, 97, 0, :east
unit :captive, 98, 0, :east
unit :archer, 100, 0, :east
unit :thick_sludge, 101, 0, :east
unit :thick_sludge, 105, 0, :east
unit :archer, 107, 0, :east
unit :thick_sludge, 109, 0, :east
unit :thick_sludge, 113, 0, :east
unit :wizard, 115, 0, :east
unit :wizard, 117, 0, :east
unit :sludge, 118, 0, :east
unit :sludge, 120, 0, :east
unit :thick_sludge, 130, 0, :east
unit :sludge, 141, 0, :east
unit :thick_sludge, 150, 0, :east
unit :thick_sludge, 153, 0, :east
unit :captive, 157, 0, :east
unit :archer, 159, 0, :east
unit :thick_sludge, 160, 0, :east
unit :captive, 164, 0, :east
unit :thick_sludge, 173, 0, :east
unit :archer, 176, 0, :east
unit :thick_sludge, 178, 0, :east
unit :sludge, 180, 0, :east
unit :thick_sludge, 182, 0, :east
unit :sludge, 188, 0, :east
unit :archer, 190, 0, :east
unit :captive, 199, 0, :east
unit :thick_sludge, 200, 0, :east
unit :captive, 201, 0, :east
unit :wizard, 205, 0, :east
unit :wizard, 207, 0, :east
unit :thick_sludge, 212, 0, :east
unit :wizard, 213, 0, :east
unit :thick_sludge, 214, 0, :east
unit :sludge, 215, 0, :east
unit :thick_sludge, 217, 0, :east
unit :captive, 218, 0, :east
unit :wizard, 220, 0, :east
unit :thick_sludge, 221, 0, :east
unit :thick_sludge, 222, 0, :east
unit :captive, 224, 0, :east
unit :sludge, 231, 0, :east
unit :captive, 232, 0, :east
unit :archer, 234, 0, :east
unit :captive, 238, 0, :east
unit :wizard, 245, 0, :east
unit :sludge, 247, 0, :east
unit :captive, 258, 0, :east
unit :captive, 267, 0, :east
unit :captive, 269, 0, :east
unit :sludge, 274, 0, :east
unit :wizard, 276, 0, :east
unit :captive, 285, 0, :east
unit :thick_sludge, 293, 0, :east
unit :archer, 296, 0, :east
unit :archer, 306, 0, :east
unit :archer, 310, 0, :east
unit :captive, 314, 0, :east
unit :captive, 316, 0, :east
unit :captive, 322, 0, :east
unit :sludge, 324, 0, :east
unit :captive, 325, 0, :east
unit :thick_sludge, 326, 0, :east
unit :thick_sludge, 329, 0, :east
unit :wizard, 333, 0, :east
unit :thick_sludge, 335, 0, :east
unit :thick_sludge, 337, 0, :east
unit :captive, 340, 0, :east
unit :wizard, 343, 0, :east
unit :sludge, 344, 0, :east
unit :captive, 348, 0, :east
unit :thick_sludge, 351, 0, :east
unit :sludge, 356, 0, :east
unit :thick_sludge, 362, 0, :east
unit :archer, 365, 0, :east
unit :sludge, 372, 0, :east
unit :captive, 373, 0, :east
unit :archer, 374, 0, :east
unit :captive, 375, 0, :east
unit :captive, 380, 0, :east
unit :sludge, 384, 0, :east
unit :archer, 385, 0, :east
unit :thick_sludge, 387, 0, :east
unit :captive, 391, 0, :east
unit :thick_sludge, 392, 0, :east
unit :wizard, 395, 0, :east
unit :wizard, 402, 0, :east
unit :wizard, 405, 0, :east
unit :sludge, 407, 0, :east
unit :captive, 412, 0, :east
unit :wizard, 415, 0, :east
unit :sludge, 416, 0, :east
unit :captive, 421, 0, :east
unit :captive, 427, 0, :east
unit :archer, 431, 0, :east
unit :thick_sludge, 433, 0, :east
unit :wizard, 439, 0, :east
unit :captive, 443, 0, :east
unit :thick_sludge, 445, 0, :east
unit :wizard, 447, 0, :east
unit :archer, 451, 0, :east
unit :captive, 453, 0, :east
unit :sludge, 454, 0, :east
unit :captive, 462, 0, :east
unit :captive, 464, 0, :east
unit :thick_sludge, 466, 0, :east
unit :wizard, 471, 0, :east
unit :thick_sludge, 473, 0, :east
unit :archer, 477, 0, :east
unit :archer, 482, 0, :east
unit :thick_sludge, 484, 0, :east
unit :captive, 485, 0, :east
unit :captive, 488, 0, :east
unit :archer, 494, 0, :east
unit :captive, 497, 0, :east
unit :wizard, 504, 0, :east
unit :wizard, 510, 0, :east
unit :thick_sludge, 516, 0, :east
unit :sludge, 530, 0, :east
unit :wizard, 534, 0, :east
unit :archer, 537, 0, :east
unit :captive, 538, 0, :east
unit :captive, 540, 0, :east
unit :wizard, 542, 0, :east
unit :captive, 544, 0, :east
unit :sludge, 547, 0, :east
unit :sludge, 550, 0, :east
unit :archer, 557, 0, :east
unit :captive, 562, 0, :east
unit :thick_sludge, 564, 0, :east
unit :sludge, 568, 0, :east
unit :wizard, 571, 0, :east
unit :thick_sludge, 572, 0, :east
unit :wizard, 577, 0, :east
unit :thick_sludge, 581, 0, :east
unit :thick_sludge, 586, 0, :east
unit :wizard, 587, 0, :east
unit :wizard, 590, 0, :east
unit :archer, 595, 0, :east
unit :archer, 597, 0, :east
unit :archer, 602, 0, :east
unit :wizard, 604, 0, :east
unit :captive, 611, 0, :east
unit :sludge, 613, 0, :east
unit :captive, 616, 0, :east
unit :captive, 617, 0, :east
unit :archer, 624, 0, :east
unit :thick_sludge, 634, 0, :east
unit :archer, 643, 0, :east
unit :captive, 653, 0, :east
unit :thick_sludge, 656, 0, :east
unit :archer, 659, 0, :east
unit :captive, 660, 0, :east
unit :thick_sludge, 665, 0, :east
unit :archer, 668, 0, :east
unit :thick_sludge, 674, 0, :east
unit :wizard, 676, 0, :east
unit :captive, 678, 0, :east
unit :sludge, 679, 0, :east
unit :thick_sludge, 680, 0, :east
unit :sludge, 681, 0, :east
unit :thick_sludge, 688, 0, :east
unit :archer, 694, 0, :east
unit :wizard, 696, 0, :east
unit :sludge, 697, 0, :east
unit :captive, 700, 0, :east
unit :captive, 721, 0, :east
unit :captive, 725, 0, :east
unit :sludge, 726, 0, :east
unit :sludge, 729, 0, :east
unit :archer, 738, 0, :east
unit :captive, 739, 0, :east
unit :thick_sludge, 741, 0, :east
unit :thick_sludge, 744, 0, :east
unit :captive, 747, 0, :east
unit :sludge, 760, 0, :east
unit :wizard, 765, 0, :east
unit :thick_sludge, 770, 0, :east
unit :archer, 775, 0, :east
unit :sludge, 776, 0, :east
unit :sludge, 778, 0, :east
unit :archer, 780, 0, :east
unit :thick_sludge, 787, 0, :east
unit :archer, 791, 0, :east
unit :sludge, 802, 0, :east
unit :archer, 806, 0, :east
unit :thick_sludge, 811, 0, :east
unit :sludge, 815, 0, :east
unit :wizard, 824, 0, :east
unit :thick_sludge, 825, 0, :east
unit :captive, 833, 0, :east
unit :archer, 834, 0, :east
unit :captive, 838, 0, :east
unit :archer, 840, 0, :east
unit :thick_sludge, 842, 0, :east
unit :sludge, 847, 0, :east
unit :sludge, 849, 0, :east
unit :captive, 863, 0, :east
unit :wizard, 864, 0, :east
unit :sludge, 880, 0, :east
unit :sludge, 885, 0, :east
unit :wizard, 892, 0, :east
unit :archer, 895, 0, :east
unit :thick_sludge, 896, 0, :east
unit :thick_sludge, 908, 0, :west
unit :archer, 910, 0, :west
unit :sludge, 911, 0, :west
unit :wizard, 913, 0, :west
unit :captive, 919, 0, :west
unit :captive, 928, 0, :west
unit :wizard, 930, 0, :west
