#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   s  s   aS     C     C  S     S  a       S       w   S aS             s   aS  wC     a        w               a        S w   Sw     S   ssSs    S w    aS  a w w C   a  w w    w Swa     C       w  w         S  @    sa          s C wSw  CS C w   s    C w aS S   a    S C S             SC   aC C        aC        as  a  s a  >   S    w   a  w     a w    C w   S  C         wS     w  aw   Ca                  ss    a          aS a s a  S     s C        Sa a  C   a     C a       a     Sa   Cs   C  SC  s       a    w  aC       s          s C     w |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 546
ace_score 2730
size 546, 1
stairs 324, 0

warrior 211, 0, :east

unit :sludge, 3, 0, :east
unit :sludge, 6, 0, :east
unit :archer, 10, 0, :east
unit :thick_sludge, 11, 0, :east
unit :captive, 17, 0, :east
unit :captive, 23, 0, :east
unit :thick_sludge, 26, 0, :east
unit :thick_sludge, 32, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 43, 0, :east
unit :wizard, 51, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 57, 0, :east
unit :thick_sludge, 58, 0, :east
unit :sludge, 72, 0, :east
unit :archer, 76, 0, :east
unit :thick_sludge, 77, 0, :east
unit :wizard, 80, 0, :east
unit :captive, 81, 0, :east
unit :archer, 87, 0, :east
unit :wizard, 96, 0, :east
unit :archer, 112, 0, :east
unit :thick_sludge, 121, 0, :east
unit :wizard, 123, 0, :east
unit :thick_sludge, 127, 0, :east
unit :wizard, 128, 0, :east
unit :thick_sludge, 134, 0, :east
unit :sludge, 138, 0, :east
unit :sludge, 139, 0, :east
unit :thick_sludge, 140, 0, :east
unit :sludge, 141, 0, :east
unit :thick_sludge, 146, 0, :east
unit :wizard, 148, 0, :east
unit :archer, 153, 0, :east
unit :thick_sludge, 154, 0, :east
unit :archer, 157, 0, :east
unit :wizard, 159, 0, :east
unit :wizard, 161, 0, :east
unit :captive, 163, 0, :east
unit :archer, 167, 0, :east
unit :wizard, 170, 0, :east
unit :wizard, 172, 0, :east
unit :wizard, 177, 0, :east
unit :thick_sludge, 179, 0, :east
unit :wizard, 180, 0, :east
unit :archer, 181, 0, :east
unit :captive, 187, 0, :east
unit :wizard, 195, 0, :east
unit :wizard, 198, 0, :east
unit :thick_sludge, 208, 0, :east
unit :sludge, 216, 0, :west
unit :archer, 217, 0, :west
unit :sludge, 228, 0, :west
unit :captive, 230, 0, :west
unit :wizard, 232, 0, :west
unit :thick_sludge, 233, 0, :west
unit :wizard, 234, 0, :west
unit :captive, 237, 0, :west
unit :thick_sludge, 238, 0, :west
unit :captive, 240, 0, :west
unit :wizard, 242, 0, :west
unit :sludge, 246, 0, :west
unit :captive, 251, 0, :west
unit :wizard, 253, 0, :west
unit :archer, 255, 0, :west
unit :thick_sludge, 256, 0, :west
unit :thick_sludge, 258, 0, :west
unit :archer, 262, 0, :west
unit :thick_sludge, 267, 0, :west
unit :captive, 269, 0, :west
unit :thick_sludge, 271, 0, :west
unit :thick_sludge, 285, 0, :west
unit :captive, 286, 0, :west
unit :archer, 290, 0, :west
unit :captive, 291, 0, :west
unit :captive, 293, 0, :west
unit :archer, 302, 0, :west
unit :captive, 303, 0, :west
unit :archer, 312, 0, :west
unit :sludge, 313, 0, :west
unit :archer, 316, 0, :west
unit :sludge, 319, 0, :west
unit :archer, 321, 0, :west
unit :thick_sludge, 328, 0, :west
unit :wizard, 333, 0, :west
unit :archer, 337, 0, :west
unit :wizard, 340, 0, :west
unit :archer, 346, 0, :west
unit :wizard, 348, 0, :west
unit :captive, 353, 0, :west
unit :wizard, 355, 0, :west
unit :thick_sludge, 359, 0, :west
unit :captive, 362, 0, :west
unit :wizard, 372, 0, :west
unit :thick_sludge, 373, 0, :west
unit :wizard, 379, 0, :west
unit :archer, 382, 0, :west
unit :wizard, 383, 0, :west
unit :captive, 387, 0, :west
unit :archer, 388, 0, :west
unit :sludge, 407, 0, :west
unit :sludge, 408, 0, :west
unit :archer, 413, 0, :west
unit :archer, 424, 0, :west
unit :thick_sludge, 425, 0, :west
unit :archer, 427, 0, :west
unit :sludge, 429, 0, :west
unit :archer, 431, 0, :west
unit :thick_sludge, 434, 0, :west
unit :sludge, 440, 0, :west
unit :captive, 442, 0, :west
unit :thick_sludge, 451, 0, :west
unit :archer, 452, 0, :west
unit :archer, 454, 0, :west
unit :captive, 457, 0, :west
unit :archer, 461, 0, :west
unit :captive, 467, 0, :west
unit :archer, 469, 0, :west
unit :archer, 477, 0, :west
unit :thick_sludge, 483, 0, :west
unit :archer, 484, 0, :west
unit :captive, 488, 0, :west
unit :sludge, 489, 0, :west
unit :captive, 493, 0, :west
unit :thick_sludge, 496, 0, :west
unit :captive, 497, 0, :west
unit :sludge, 500, 0, :west
unit :archer, 508, 0, :west
unit :wizard, 513, 0, :west
unit :archer, 516, 0, :west
unit :captive, 517, 0, :west
unit :sludge, 525, 0, :west
unit :sludge, 536, 0, :west
unit :captive, 538, 0, :west
unit :wizard, 544, 0, :west
