#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w       as s    w a   S    a a w s   C    w SCC s  sa  S s w   w   S  C     C s   S        w     C        C w     s  sC     SCs   @  s aCs             w   w    a     S s S   s  sC         CCas   w   SS C      s S   ss a w a     w  s a         SS       wSSw  w   a   w  a s S     Cw a                 w        a         S      w  a           w as    C w s               s           w sC  C Sw  S      CC ws   a  w     C           a     w   S      S    w  s S       CS    s a   a  a  s       C   ass CS   s              C w    s    a    a  aa        S   a   s    s      S a    w S     asC    C         a  C           CC          C   ss      a a   w   w     C C         s  >ss   wCs C          ss      s            a C    s s C     w  s  w S w a C        S  w a   s        s   s    a  w    sCC a  s     aa w sw  a     a      s   w  a w    a  S     a w   s Cs  ws Cw  C  w            a   C        C  w    C    a  C S         C    w S    s   s   Ss     S             a    s aa |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 974
ace_score 4870
size 974, 1
stairs 672, 0

warrior 132, 0, :east

unit :wizard, 2, 0, :east
unit :archer, 10, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 13, 0, :east
unit :wizard, 18, 0, :east
unit :archer, 20, 0, :east
unit :thick_sludge, 24, 0, :east
unit :archer, 29, 0, :east
unit :archer, 31, 0, :east
unit :wizard, 33, 0, :east
unit :sludge, 35, 0, :east
unit :captive, 39, 0, :east
unit :wizard, 44, 0, :east
unit :thick_sludge, 46, 0, :east
unit :captive, 47, 0, :east
unit :captive, 48, 0, :east
unit :sludge, 50, 0, :east
unit :sludge, 53, 0, :east
unit :archer, 54, 0, :east
unit :thick_sludge, 57, 0, :east
unit :sludge, 59, 0, :east
unit :wizard, 61, 0, :east
unit :wizard, 65, 0, :east
unit :thick_sludge, 69, 0, :east
unit :captive, 72, 0, :east
unit :captive, 78, 0, :east
unit :sludge, 80, 0, :east
unit :thick_sludge, 84, 0, :east
unit :wizard, 93, 0, :east
unit :captive, 99, 0, :east
unit :captive, 108, 0, :east
unit :wizard, 110, 0, :east
unit :sludge, 116, 0, :east
unit :sludge, 119, 0, :east
unit :captive, 120, 0, :east
unit :thick_sludge, 126, 0, :east
unit :captive, 127, 0, :east
unit :sludge, 128, 0, :east
unit :sludge, 135, 0, :west
unit :archer, 137, 0, :west
unit :captive, 138, 0, :west
unit :sludge, 139, 0, :west
unit :wizard, 153, 0, :west
unit :wizard, 157, 0, :west
unit :archer, 162, 0, :west
unit :thick_sludge, 168, 0, :west
unit :sludge, 170, 0, :west
unit :thick_sludge, 172, 0, :west
unit :sludge, 176, 0, :west
unit :sludge, 179, 0, :west
unit :captive, 180, 0, :west
unit :captive, 190, 0, :west
unit :captive, 191, 0, :west
unit :archer, 192, 0, :west
unit :sludge, 193, 0, :west
unit :wizard, 197, 0, :west
unit :thick_sludge, 201, 0, :west
unit :thick_sludge, 202, 0, :west
unit :captive, 204, 0, :west
unit :sludge, 211, 0, :west
unit :thick_sludge, 213, 0, :west
unit :sludge, 217, 0, :west
unit :sludge, 218, 0, :west
unit :archer, 220, 0, :west
unit :wizard, 222, 0, :west
unit :archer, 224, 0, :west
unit :wizard, 230, 0, :west
unit :sludge, 233, 0, :west
unit :archer, 235, 0, :west
unit :thick_sludge, 245, 0, :west
unit :thick_sludge, 246, 0, :west
unit :wizard, 254, 0, :west
unit :thick_sludge, 255, 0, :west
unit :thick_sludge, 256, 0, :west
unit :wizard, 257, 0, :west
unit :wizard, 260, 0, :west
unit :archer, 264, 0, :west
unit :wizard, 268, 0, :west
unit :archer, 271, 0, :west
unit :sludge, 273, 0, :west
unit :thick_sludge, 275, 0, :west
unit :captive, 281, 0, :west
unit :wizard, 282, 0, :west
unit :archer, 284, 0, :west
unit :wizard, 302, 0, :west
unit :archer, 311, 0, :west
unit :thick_sludge, 321, 0, :west
unit :wizard, 328, 0, :west
unit :archer, 331, 0, :west
unit :wizard, 343, 0, :west
unit :archer, 345, 0, :west
unit :sludge, 346, 0, :west
unit :captive, 351, 0, :west
unit :wizard, 353, 0, :west
unit :sludge, 355, 0, :west
unit :sludge, 371, 0, :west
unit :wizard, 383, 0, :west
unit :sludge, 385, 0, :west
unit :captive, 386, 0, :west
unit :captive, 389, 0, :west
unit :thick_sludge, 391, 0, :west
unit :wizard, 392, 0, :west
unit :thick_sludge, 395, 0, :west
unit :captive, 402, 0, :west
unit :captive, 403, 0, :west
unit :wizard, 405, 0, :west
unit :sludge, 406, 0, :west
unit :archer, 410, 0, :west
unit :wizard, 413, 0, :west
unit :captive, 419, 0, :west
unit :archer, 431, 0, :west
unit :wizard, 437, 0, :west
unit :thick_sludge, 441, 0, :west
unit :thick_sludge, 448, 0, :west
unit :wizard, 453, 0, :west
unit :sludge, 456, 0, :west
unit :thick_sludge, 458, 0, :west
unit :captive, 466, 0, :west
unit :thick_sludge, 467, 0, :west
unit :sludge, 472, 0, :west
unit :archer, 474, 0, :west
unit :archer, 478, 0, :west
unit :archer, 481, 0, :west
unit :sludge, 484, 0, :west
unit :captive, 492, 0, :west
unit :archer, 496, 0, :west
unit :sludge, 497, 0, :west
unit :sludge, 498, 0, :west
unit :captive, 500, 0, :west
unit :thick_sludge, 501, 0, :west
unit :sludge, 505, 0, :west
unit :captive, 520, 0, :west
unit :wizard, 522, 0, :west
unit :sludge, 527, 0, :west
unit :archer, 532, 0, :west
unit :archer, 537, 0, :west
unit :archer, 540, 0, :west
unit :archer, 541, 0, :west
unit :thick_sludge, 550, 0, :west
unit :archer, 554, 0, :west
unit :sludge, 558, 0, :west
unit :sludge, 563, 0, :west
unit :thick_sludge, 570, 0, :west
unit :archer, 572, 0, :west
unit :wizard, 577, 0, :west
unit :thick_sludge, 579, 0, :west
unit :archer, 585, 0, :west
unit :sludge, 586, 0, :west
unit :captive, 587, 0, :west
unit :captive, 592, 0, :west
unit :archer, 602, 0, :west
unit :captive, 605, 0, :west
unit :captive, 617, 0, :west
unit :captive, 618, 0, :west
unit :captive, 629, 0, :west
unit :sludge, 633, 0, :west
unit :sludge, 634, 0, :west
unit :archer, 641, 0, :west
unit :archer, 643, 0, :west
unit :wizard, 647, 0, :west
unit :wizard, 651, 0, :west
unit :captive, 657, 0, :west
unit :captive, 659, 0, :west
unit :sludge, 669, 0, :west
unit :sludge, 673, 0, :west
unit :sludge, 674, 0, :west
unit :wizard, 678, 0, :west
unit :captive, 679, 0, :west
unit :sludge, 680, 0, :west
unit :captive, 682, 0, :west
unit :sludge, 693, 0, :west
unit :sludge, 694, 0, :west
unit :sludge, 701, 0, :west
unit :archer, 714, 0, :west
unit :captive, 716, 0, :west
unit :sludge, 721, 0, :west
unit :sludge, 723, 0, :west
unit :captive, 725, 0, :west
unit :wizard, 731, 0, :west
unit :sludge, 734, 0, :west
unit :wizard, 737, 0, :west
unit :thick_sludge, 739, 0, :west
unit :wizard, 741, 0, :west
unit :archer, 743, 0, :west
unit :captive, 745, 0, :west
unit :thick_sludge, 754, 0, :west
unit :wizard, 757, 0, :west
unit :archer, 759, 0, :west
unit :sludge, 763, 0, :west
unit :sludge, 772, 0, :west
unit :sludge, 776, 0, :west
unit :archer, 781, 0, :west
unit :wizard, 784, 0, :west
unit :sludge, 789, 0, :west
unit :captive, 790, 0, :west
unit :captive, 791, 0, :west
unit :archer, 793, 0, :west
unit :sludge, 796, 0, :west
unit :archer, 802, 0, :west
unit :archer, 803, 0, :west
unit :wizard, 805, 0, :west
unit :sludge, 807, 0, :west
unit :wizard, 808, 0, :west
unit :archer, 811, 0, :west
unit :archer, 817, 0, :west
unit :sludge, 824, 0, :west
unit :wizard, 828, 0, :west
unit :archer, 831, 0, :west
unit :wizard, 833, 0, :west
unit :archer, 838, 0, :west
unit :thick_sludge, 841, 0, :west
unit :archer, 847, 0, :west
unit :wizard, 849, 0, :west
unit :sludge, 853, 0, :west
unit :captive, 855, 0, :west
unit :sludge, 856, 0, :west
unit :wizard, 859, 0, :west
unit :sludge, 860, 0, :west
unit :captive, 862, 0, :west
unit :wizard, 863, 0, :west
unit :captive, 866, 0, :west
unit :wizard, 869, 0, :west
unit :archer, 882, 0, :west
unit :captive, 886, 0, :west
unit :captive, 895, 0, :west
unit :wizard, 898, 0, :west
unit :captive, 903, 0, :west
unit :archer, 908, 0, :west
unit :captive, 911, 0, :west
unit :thick_sludge, 913, 0, :west
unit :captive, 923, 0, :west
unit :wizard, 928, 0, :west
unit :thick_sludge, 930, 0, :west
unit :sludge, 935, 0, :west
unit :sludge, 939, 0, :west
unit :thick_sludge, 943, 0, :west
unit :sludge, 944, 0, :west
unit :thick_sludge, 950, 0, :west
unit :archer, 964, 0, :west
unit :sludge, 969, 0, :west
unit :archer, 971, 0, :west
unit :archer, 972, 0, :west
