#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     a      C    C          C   SS         S     C     a   a             Cs              w                C aC        aaSS Sa   C S S  s S CCC     s w w  w   s     aSS      SS w         w aC           S S  S       s w  ws a  C    s      C a         Cws  w C  Cs Cw      S      S    SC S   s   wS a a    s a  C w w     C >   s a        C  Ca     S  sS   S  aS Cw Ca    C  as       a           C          C   C   sC   S      wa        S w   @  S    s     aC    C      S  sC w w   C a a   C s       s      S       a C   S       sS       Ca         S     Ss C   a a         a   S   a  a aC  a         S a      S   Sa a a     a  s C       s    C a       s  C ass     C      w                     SCSC     w  a a       a      S CS s   Ca a  sS   aS      a         S    s        C       S a s    S ss C     s      sC         S       a      CC    a       w aw CCa a  C a|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 862
ace_score 4310
size 862, 1
stairs 320, 0

warrior 439, 0, :east

unit :archer, 5, 0, :east
unit :captive, 12, 0, :east
unit :captive, 17, 0, :east
unit :captive, 28, 0, :east
unit :thick_sludge, 32, 0, :east
unit :thick_sludge, 33, 0, :east
unit :thick_sludge, 43, 0, :east
unit :captive, 49, 0, :east
unit :archer, 55, 0, :east
unit :archer, 59, 0, :east
unit :captive, 73, 0, :east
unit :sludge, 74, 0, :east
unit :wizard, 89, 0, :east
unit :captive, 106, 0, :east
unit :archer, 108, 0, :east
unit :captive, 109, 0, :east
unit :archer, 118, 0, :east
unit :archer, 119, 0, :east
unit :thick_sludge, 120, 0, :east
unit :thick_sludge, 121, 0, :east
unit :thick_sludge, 123, 0, :east
unit :archer, 124, 0, :east
unit :captive, 128, 0, :east
unit :thick_sludge, 130, 0, :east
unit :thick_sludge, 132, 0, :east
unit :sludge, 135, 0, :east
unit :thick_sludge, 137, 0, :east
unit :captive, 139, 0, :east
unit :captive, 140, 0, :east
unit :captive, 141, 0, :east
unit :sludge, 147, 0, :east
unit :wizard, 149, 0, :east
unit :wizard, 151, 0, :east
unit :wizard, 154, 0, :east
unit :sludge, 158, 0, :east
unit :archer, 164, 0, :east
unit :thick_sludge, 165, 0, :east
unit :thick_sludge, 166, 0, :east
unit :thick_sludge, 173, 0, :east
unit :thick_sludge, 174, 0, :east
unit :wizard, 176, 0, :east
unit :wizard, 186, 0, :east
unit :archer, 188, 0, :east
unit :captive, 189, 0, :east
unit :thick_sludge, 201, 0, :east
unit :thick_sludge, 203, 0, :east
unit :thick_sludge, 206, 0, :east
unit :sludge, 214, 0, :east
unit :wizard, 216, 0, :east
unit :wizard, 219, 0, :east
unit :sludge, 220, 0, :east
unit :archer, 222, 0, :east
unit :captive, 225, 0, :east
unit :sludge, 230, 0, :east
unit :captive, 237, 0, :east
unit :archer, 239, 0, :east
unit :captive, 249, 0, :east
unit :wizard, 250, 0, :east
unit :sludge, 251, 0, :east
unit :wizard, 254, 0, :east
unit :captive, 256, 0, :east
unit :captive, 259, 0, :east
unit :sludge, 260, 0, :east
unit :captive, 262, 0, :east
unit :wizard, 263, 0, :east
unit :thick_sludge, 270, 0, :east
unit :thick_sludge, 277, 0, :east
unit :thick_sludge, 282, 0, :east
unit :captive, 283, 0, :east
unit :thick_sludge, 285, 0, :east
unit :sludge, 289, 0, :east
unit :wizard, 293, 0, :east
unit :thick_sludge, 294, 0, :east
unit :archer, 296, 0, :east
unit :archer, 298, 0, :east
unit :sludge, 303, 0, :east
unit :archer, 305, 0, :east
unit :captive, 308, 0, :east
unit :wizard, 310, 0, :east
unit :wizard, 312, 0, :east
unit :captive, 318, 0, :east
unit :sludge, 324, 0, :east
unit :archer, 326, 0, :east
unit :captive, 335, 0, :east
unit :captive, 338, 0, :east
unit :archer, 339, 0, :east
unit :thick_sludge, 345, 0, :east
unit :sludge, 348, 0, :east
unit :thick_sludge, 349, 0, :east
unit :thick_sludge, 353, 0, :east
unit :archer, 356, 0, :east
unit :thick_sludge, 357, 0, :east
unit :captive, 359, 0, :east
unit :wizard, 360, 0, :east
unit :captive, 362, 0, :east
unit :archer, 363, 0, :east
unit :captive, 368, 0, :east
unit :archer, 371, 0, :east
unit :sludge, 372, 0, :east
unit :archer, 380, 0, :east
unit :captive, 392, 0, :east
unit :captive, 403, 0, :east
unit :captive, 407, 0, :east
unit :sludge, 411, 0, :east
unit :captive, 412, 0, :east
unit :thick_sludge, 416, 0, :east
unit :wizard, 423, 0, :east
unit :archer, 424, 0, :east
unit :thick_sludge, 433, 0, :east
unit :wizard, 435, 0, :east
unit :thick_sludge, 442, 0, :west
unit :sludge, 447, 0, :west
unit :archer, 453, 0, :west
unit :captive, 454, 0, :west
unit :captive, 459, 0, :west
unit :thick_sludge, 466, 0, :west
unit :sludge, 469, 0, :west
unit :captive, 470, 0, :west
unit :wizard, 472, 0, :west
unit :wizard, 474, 0, :west
unit :captive, 478, 0, :west
unit :archer, 480, 0, :west
unit :archer, 482, 0, :west
unit :captive, 486, 0, :west
unit :sludge, 488, 0, :west
unit :sludge, 496, 0, :west
unit :thick_sludge, 503, 0, :west
unit :archer, 511, 0, :west
unit :captive, 513, 0, :west
unit :thick_sludge, 517, 0, :west
unit :sludge, 525, 0, :west
unit :thick_sludge, 526, 0, :west
unit :captive, 534, 0, :west
unit :archer, 535, 0, :west
unit :thick_sludge, 545, 0, :west
unit :thick_sludge, 551, 0, :west
unit :sludge, 552, 0, :west
unit :captive, 554, 0, :west
unit :archer, 558, 0, :west
unit :archer, 560, 0, :west
unit :archer, 570, 0, :west
unit :thick_sludge, 574, 0, :west
unit :archer, 578, 0, :west
unit :archer, 581, 0, :west
unit :archer, 583, 0, :west
unit :captive, 584, 0, :west
unit :archer, 587, 0, :west
unit :thick_sludge, 597, 0, :west
unit :archer, 599, 0, :west
unit :thick_sludge, 606, 0, :west
unit :thick_sludge, 610, 0, :west
unit :archer, 611, 0, :west
unit :archer, 613, 0, :west
unit :archer, 615, 0, :west
unit :archer, 621, 0, :west
unit :sludge, 624, 0, :west
unit :captive, 626, 0, :west
unit :sludge, 634, 0, :west
unit :captive, 639, 0, :west
unit :archer, 641, 0, :west
unit :sludge, 649, 0, :west
unit :captive, 652, 0, :west
unit :archer, 654, 0, :west
unit :sludge, 655, 0, :west
unit :sludge, 656, 0, :west
unit :captive, 662, 0, :west
unit :wizard, 669, 0, :west
unit :thick_sludge, 691, 0, :west
unit :captive, 692, 0, :west
unit :thick_sludge, 693, 0, :west
unit :captive, 694, 0, :west
unit :wizard, 700, 0, :west
unit :archer, 703, 0, :west
unit :archer, 705, 0, :west
unit :archer, 713, 0, :west
unit :thick_sludge, 720, 0, :west
unit :captive, 722, 0, :west
unit :thick_sludge, 723, 0, :west
unit :sludge, 725, 0, :west
unit :captive, 729, 0, :west
unit :archer, 730, 0, :west
unit :archer, 732, 0, :west
unit :sludge, 735, 0, :west
unit :thick_sludge, 736, 0, :west
unit :archer, 740, 0, :west
unit :thick_sludge, 741, 0, :west
unit :archer, 748, 0, :west
unit :thick_sludge, 758, 0, :west
unit :sludge, 763, 0, :west
unit :captive, 772, 0, :west
unit :thick_sludge, 780, 0, :west
unit :archer, 782, 0, :west
unit :sludge, 784, 0, :west
unit :thick_sludge, 789, 0, :west
unit :sludge, 791, 0, :west
unit :sludge, 792, 0, :west
unit :captive, 794, 0, :west
unit :sludge, 800, 0, :west
unit :sludge, 807, 0, :west
unit :captive, 808, 0, :west
unit :thick_sludge, 818, 0, :west
unit :archer, 826, 0, :west
unit :captive, 833, 0, :west
unit :captive, 834, 0, :west
unit :archer, 839, 0, :west
unit :wizard, 847, 0, :west
unit :archer, 849, 0, :west
unit :wizard, 850, 0, :west
unit :captive, 852, 0, :west
unit :captive, 853, 0, :west
unit :archer, 854, 0, :west
unit :archer, 856, 0, :west
unit :captive, 859, 0, :west
unit :archer, 861, 0, :west
