#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | s          CC S w S  asa C    s     S           s C    S    S   C SC     C      CS     Ss w a  Cw        S Ca    CSS a       s s       CS       SC  w   C          w    s  s    s  S    s C  s    ws  w           aSs  C  s       a S S s s      s  w   @     a   a          s    S  w   C         C          s         C   Cs     a  a  as    aS     a          S  a   S       wCw   S s   ws a  s>a  s     a s     ass CCC    S      a sC     s  a       w s    w      s  w Cw   a  wa  a s  a S        sa   Ca        as s       C S C   aS  w     C    w  w      C        C    a   w  a  a  C a   S  a   S     w    a    a SC a w   a  C    C s            s  S               a  S                 S|
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 681
ace_score 3405
size 681, 1
stairs 388, 0

warrior 249, 0, :east

unit :sludge, 1, 0, :east
unit :captive, 12, 0, :east
unit :captive, 13, 0, :east
unit :thick_sludge, 15, 0, :east
unit :wizard, 17, 0, :east
unit :thick_sludge, 19, 0, :east
unit :archer, 22, 0, :east
unit :sludge, 23, 0, :east
unit :archer, 24, 0, :east
unit :captive, 26, 0, :east
unit :sludge, 31, 0, :east
unit :thick_sludge, 37, 0, :east
unit :sludge, 49, 0, :east
unit :captive, 51, 0, :east
unit :thick_sludge, 56, 0, :east
unit :thick_sludge, 61, 0, :east
unit :captive, 65, 0, :east
unit :thick_sludge, 67, 0, :east
unit :captive, 68, 0, :east
unit :captive, 74, 0, :east
unit :captive, 81, 0, :east
unit :thick_sludge, 82, 0, :east
unit :thick_sludge, 88, 0, :east
unit :sludge, 89, 0, :east
unit :wizard, 91, 0, :east
unit :archer, 93, 0, :east
unit :captive, 96, 0, :east
unit :wizard, 97, 0, :east
unit :thick_sludge, 106, 0, :east
unit :captive, 108, 0, :east
unit :archer, 109, 0, :east
unit :captive, 114, 0, :east
unit :thick_sludge, 115, 0, :east
unit :thick_sludge, 116, 0, :east
unit :archer, 118, 0, :east
unit :sludge, 126, 0, :east
unit :sludge, 128, 0, :east
unit :captive, 136, 0, :east
unit :thick_sludge, 137, 0, :east
unit :thick_sludge, 145, 0, :east
unit :captive, 146, 0, :east
unit :wizard, 149, 0, :east
unit :captive, 153, 0, :east
unit :wizard, 164, 0, :east
unit :sludge, 169, 0, :east
unit :sludge, 172, 0, :east
unit :sludge, 177, 0, :east
unit :thick_sludge, 180, 0, :east
unit :sludge, 185, 0, :east
unit :captive, 187, 0, :east
unit :sludge, 190, 0, :east
unit :wizard, 195, 0, :east
unit :sludge, 196, 0, :east
unit :wizard, 199, 0, :east
unit :archer, 211, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 213, 0, :east
unit :captive, 216, 0, :east
unit :sludge, 219, 0, :east
unit :archer, 227, 0, :east
unit :thick_sludge, 229, 0, :east
unit :thick_sludge, 231, 0, :east
unit :sludge, 233, 0, :east
unit :sludge, 235, 0, :east
unit :sludge, 242, 0, :east
unit :wizard, 245, 0, :east
unit :archer, 255, 0, :west
unit :archer, 259, 0, :west
unit :sludge, 270, 0, :west
unit :thick_sludge, 275, 0, :west
unit :wizard, 278, 0, :west
unit :captive, 282, 0, :west
unit :captive, 292, 0, :west
unit :sludge, 303, 0, :west
unit :captive, 313, 0, :west
unit :captive, 317, 0, :west
unit :sludge, 318, 0, :west
unit :archer, 324, 0, :west
unit :archer, 327, 0, :west
unit :archer, 330, 0, :west
unit :sludge, 331, 0, :west
unit :archer, 336, 0, :west
unit :thick_sludge, 337, 0, :west
unit :archer, 343, 0, :west
unit :thick_sludge, 354, 0, :west
unit :archer, 357, 0, :west
unit :thick_sludge, 361, 0, :west
unit :wizard, 369, 0, :west
unit :captive, 370, 0, :west
unit :wizard, 371, 0, :west
unit :thick_sludge, 375, 0, :west
unit :sludge, 377, 0, :west
unit :wizard, 381, 0, :west
unit :sludge, 382, 0, :west
unit :archer, 384, 0, :west
unit :sludge, 387, 0, :west
unit :archer, 389, 0, :west
unit :sludge, 392, 0, :west
unit :archer, 398, 0, :west
unit :sludge, 400, 0, :west
unit :archer, 406, 0, :west
unit :sludge, 407, 0, :west
unit :sludge, 408, 0, :west
unit :captive, 410, 0, :west
unit :captive, 411, 0, :west
unit :captive, 412, 0, :west
unit :thick_sludge, 417, 0, :west
unit :archer, 424, 0, :west
unit :sludge, 426, 0, :west
unit :captive, 427, 0, :west
unit :sludge, 433, 0, :west
unit :archer, 436, 0, :west
unit :wizard, 444, 0, :west
unit :sludge, 446, 0, :west
unit :wizard, 451, 0, :west
unit :sludge, 458, 0, :west
unit :wizard, 461, 0, :west
unit :captive, 463, 0, :west
unit :wizard, 464, 0, :west
unit :archer, 468, 0, :west
unit :wizard, 471, 0, :west
unit :archer, 472, 0, :west
unit :archer, 475, 0, :west
unit :sludge, 477, 0, :west
unit :archer, 480, 0, :west
unit :thick_sludge, 482, 0, :west
unit :sludge, 491, 0, :west
unit :archer, 492, 0, :west
unit :captive, 496, 0, :west
unit :archer, 497, 0, :west
unit :archer, 506, 0, :west
unit :sludge, 507, 0, :west
unit :sludge, 509, 0, :west
unit :captive, 517, 0, :west
unit :thick_sludge, 519, 0, :west
unit :captive, 521, 0, :west
unit :archer, 525, 0, :west
unit :thick_sludge, 526, 0, :west
unit :wizard, 529, 0, :west
unit :captive, 535, 0, :west
unit :wizard, 540, 0, :west
unit :wizard, 543, 0, :west
unit :captive, 550, 0, :west
unit :captive, 559, 0, :west
unit :archer, 564, 0, :west
unit :wizard, 568, 0, :west
unit :archer, 571, 0, :west
unit :archer, 574, 0, :west
unit :captive, 577, 0, :west
unit :archer, 579, 0, :west
unit :thick_sludge, 583, 0, :west
unit :archer, 586, 0, :west
unit :thick_sludge, 590, 0, :west
unit :wizard, 596, 0, :west
unit :archer, 601, 0, :west
unit :archer, 606, 0, :west
unit :thick_sludge, 608, 0, :west
unit :captive, 609, 0, :west
unit :archer, 611, 0, :west
unit :wizard, 613, 0, :west
unit :archer, 617, 0, :west
unit :captive, 620, 0, :west
unit :captive, 625, 0, :west
unit :sludge, 627, 0, :west
unit :sludge, 640, 0, :west
unit :thick_sludge, 643, 0, :west
unit :archer, 659, 0, :west
unit :thick_sludge, 662, 0, :west
unit :thick_sludge, 680, 0, :west
