#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   s          S       C sw   w  S                    C  s S S   as    asS         C     >S    s  S   C  s a   Sw   w C     S   S    w   C  C      C       @    a       S     S   S        Ssa  S  S w  S s     C     w        aC       S     s   S a  S Cw s    ass    a       C       C  Cs             S   S  w C           s      C     S        w    CS  w    S     S  a Ca  w s       s      a  a a    w   CCa     Ca a w        Sa   S   C C  a S   S    SCwsS  s      w w    w  C    sC s    C  s  s    s a C s s  a Cw C         a C s w    a     C  C     C  s s   S sC a   w    a  s  s ss      S     C   w a  Cs w         w s C    aCS   w             s     C   s  s    C C     aS a    s          w    S   Sw        s a   sCC    C    C       s SC   asSw    w     C   a                  S                 S  Ss    C   S        wa S sa s   s|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 830
ace_score 4150
size 830, 1
stairs 88, 0

warrior 154, 0, :east

unit :sludge, 3, 0, :east
unit :thick_sludge, 14, 0, :east
unit :captive, 22, 0, :east
unit :sludge, 24, 0, :east
unit :wizard, 25, 0, :east
unit :wizard, 29, 0, :east
unit :thick_sludge, 32, 0, :east
unit :captive, 53, 0, :east
unit :sludge, 56, 0, :east
unit :thick_sludge, 58, 0, :east
unit :thick_sludge, 60, 0, :east
unit :archer, 64, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 70, 0, :east
unit :sludge, 71, 0, :east
unit :thick_sludge, 72, 0, :east
unit :captive, 82, 0, :east
unit :thick_sludge, 89, 0, :east
unit :sludge, 94, 0, :east
unit :thick_sludge, 97, 0, :east
unit :captive, 101, 0, :east
unit :sludge, 104, 0, :east
unit :archer, 106, 0, :east
unit :thick_sludge, 110, 0, :east
unit :wizard, 111, 0, :east
unit :wizard, 115, 0, :east
unit :captive, 117, 0, :east
unit :thick_sludge, 123, 0, :east
unit :thick_sludge, 127, 0, :east
unit :wizard, 132, 0, :east
unit :captive, 136, 0, :east
unit :captive, 139, 0, :east
unit :captive, 146, 0, :east
unit :archer, 159, 0, :west
unit :thick_sludge, 167, 0, :west
unit :thick_sludge, 173, 0, :west
unit :thick_sludge, 177, 0, :west
unit :thick_sludge, 186, 0, :west
unit :sludge, 187, 0, :west
unit :archer, 188, 0, :west
unit :thick_sludge, 191, 0, :west
unit :thick_sludge, 194, 0, :west
unit :wizard, 196, 0, :west
unit :thick_sludge, 199, 0, :west
unit :sludge, 201, 0, :west
unit :captive, 207, 0, :west
unit :wizard, 213, 0, :west
unit :archer, 222, 0, :west
unit :captive, 223, 0, :west
unit :thick_sludge, 231, 0, :west
unit :sludge, 237, 0, :west
unit :thick_sludge, 241, 0, :west
unit :archer, 243, 0, :west
unit :thick_sludge, 246, 0, :west
unit :captive, 248, 0, :west
unit :wizard, 249, 0, :west
unit :sludge, 251, 0, :west
unit :archer, 256, 0, :west
unit :sludge, 257, 0, :west
unit :sludge, 258, 0, :west
unit :archer, 263, 0, :west
unit :captive, 271, 0, :west
unit :captive, 279, 0, :west
unit :captive, 282, 0, :west
unit :sludge, 283, 0, :west
unit :thick_sludge, 297, 0, :west
unit :thick_sludge, 301, 0, :west
unit :wizard, 304, 0, :west
unit :captive, 306, 0, :west
unit :sludge, 318, 0, :west
unit :captive, 325, 0, :west
unit :thick_sludge, 331, 0, :west
unit :wizard, 340, 0, :west
unit :captive, 345, 0, :west
unit :thick_sludge, 346, 0, :west
unit :wizard, 349, 0, :west
unit :thick_sludge, 354, 0, :west
unit :thick_sludge, 360, 0, :west
unit :archer, 363, 0, :west
unit :captive, 365, 0, :west
unit :archer, 366, 0, :west
unit :wizard, 369, 0, :west
unit :sludge, 371, 0, :west
unit :sludge, 379, 0, :west
unit :archer, 386, 0, :west
unit :archer, 389, 0, :west
unit :archer, 391, 0, :west
unit :wizard, 396, 0, :west
unit :captive, 400, 0, :west
unit :captive, 401, 0, :west
unit :archer, 402, 0, :west
unit :captive, 408, 0, :west
unit :archer, 409, 0, :west
unit :archer, 411, 0, :west
unit :wizard, 413, 0, :west
unit :thick_sludge, 422, 0, :west
unit :archer, 423, 0, :west
unit :thick_sludge, 427, 0, :west
unit :captive, 431, 0, :west
unit :captive, 433, 0, :west
unit :archer, 436, 0, :west
unit :thick_sludge, 438, 0, :west
unit :thick_sludge, 442, 0, :west
unit :thick_sludge, 447, 0, :west
unit :captive, 448, 0, :west
unit :wizard, 449, 0, :west
unit :sludge, 450, 0, :west
unit :thick_sludge, 451, 0, :west
unit :sludge, 454, 0, :west
unit :wizard, 461, 0, :west
unit :wizard, 463, 0, :west
unit :wizard, 468, 0, :west
unit :captive, 471, 0, :west
unit :sludge, 476, 0, :west
unit :captive, 477, 0, :west
unit :sludge, 479, 0, :west
unit :captive, 484, 0, :west
unit :sludge, 487, 0, :west
unit :sludge, 490, 0, :west
unit :sludge, 495, 0, :west
unit :archer, 497, 0, :west
unit :captive, 499, 0, :west
unit :sludge, 501, 0, :west
unit :sludge, 503, 0, :west
unit :archer, 506, 0, :west
unit :captive, 508, 0, :west
unit :wizard, 509, 0, :west
unit :captive, 511, 0, :west
unit :archer, 521, 0, :west
unit :captive, 523, 0, :west
unit :sludge, 525, 0, :west
unit :wizard, 527, 0, :west
unit :archer, 532, 0, :west
unit :captive, 538, 0, :west
unit :captive, 541, 0, :west
unit :captive, 547, 0, :west
unit :sludge, 550, 0, :west
unit :sludge, 552, 0, :west
unit :thick_sludge, 556, 0, :west
unit :sludge, 558, 0, :west
unit :captive, 559, 0, :west
unit :archer, 561, 0, :west
unit :wizard, 565, 0, :west
unit :archer, 570, 0, :west
unit :sludge, 573, 0, :west
unit :sludge, 576, 0, :west
unit :sludge, 578, 0, :west
unit :sludge, 579, 0, :west
unit :thick_sludge, 586, 0, :west
unit :captive, 592, 0, :west
unit :wizard, 596, 0, :west
unit :archer, 598, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 602, 0, :west
unit :wizard, 604, 0, :west
unit :wizard, 614, 0, :west
unit :sludge, 616, 0, :west
unit :captive, 618, 0, :west
unit :archer, 623, 0, :west
unit :captive, 624, 0, :west
unit :thick_sludge, 625, 0, :west
unit :wizard, 629, 0, :west
unit :sludge, 643, 0, :west
unit :captive, 649, 0, :west
unit :sludge, 653, 0, :west
unit :sludge, 656, 0, :west
unit :captive, 661, 0, :west
unit :captive, 663, 0, :west
unit :archer, 669, 0, :west
unit :thick_sludge, 670, 0, :west
unit :archer, 672, 0, :west
unit :sludge, 677, 0, :west
unit :wizard, 688, 0, :west
unit :thick_sludge, 693, 0, :west
unit :thick_sludge, 697, 0, :west
unit :wizard, 698, 0, :west
unit :sludge, 707, 0, :west
unit :archer, 709, 0, :west
unit :sludge, 713, 0, :west
unit :captive, 714, 0, :west
unit :captive, 715, 0, :west
unit :captive, 720, 0, :west
unit :captive, 725, 0, :west
unit :sludge, 733, 0, :west
unit :thick_sludge, 735, 0, :west
unit :captive, 736, 0, :west
unit :archer, 740, 0, :west
unit :sludge, 741, 0, :west
unit :thick_sludge, 742, 0, :west
unit :wizard, 743, 0, :west
unit :wizard, 748, 0, :west
unit :captive, 754, 0, :west
unit :archer, 758, 0, :west
unit :thick_sludge, 777, 0, :west
unit :thick_sludge, 795, 0, :west
unit :thick_sludge, 798, 0, :west
unit :sludge, 799, 0, :west
unit :captive, 804, 0, :west
unit :thick_sludge, 808, 0, :west
unit :wizard, 817, 0, :west
unit :archer, 818, 0, :west
unit :thick_sludge, 820, 0, :west
unit :sludge, 822, 0, :west
unit :archer, 823, 0, :west
unit :sludge, 825, 0, :west
unit :sludge, 829, 0, :west
