#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a        C     Cs    wC   w          S S       wS         wsS   a        s    s    S C sC    s    s C    C  Cs   asa  S   w a         C     ass  w a    s             S      CCsS  a Ca         w  w  sa    a     C sSsC  S    w     s >wSw s        w s  s            sSC   s   a   w       CC        S a    CSsa       s           C   s  S  w   Cs             w  aS   S      w    s  C aw           sS                      w a      C          aw  S        C      sS w  ss aS  CC  s      C    a    CS s      C     a   s    Cs sC  S ss  s   w      a      C a            a     s w aC         CSwS  a a S  a      ssa   sC               C      S w          aS   C     s        a   s  sa  w  Sa    a  SS  w S   w        a    w      C w    wC        aS    a  w              sS   S s a  a s      a  w Cs   w Ca    w Sa     C  C    C                 wa  C w     as  @  s   s  a |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 863
ace_score 4315
size 863, 1
stairs 232, 0

warrior 851, 0, :east

unit :archer, 1, 0, :east
unit :captive, 10, 0, :east
unit :captive, 16, 0, :east
unit :sludge, 17, 0, :east
unit :wizard, 22, 0, :east
unit :captive, 23, 0, :east
unit :wizard, 27, 0, :east
unit :thick_sludge, 38, 0, :east
unit :thick_sludge, 40, 0, :east
unit :wizard, 48, 0, :east
unit :thick_sludge, 49, 0, :east
unit :wizard, 59, 0, :east
unit :sludge, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :archer, 65, 0, :east
unit :sludge, 74, 0, :east
unit :sludge, 79, 0, :east
unit :thick_sludge, 84, 0, :east
unit :captive, 86, 0, :east
unit :sludge, 88, 0, :east
unit :captive, 89, 0, :east
unit :sludge, 94, 0, :east
unit :sludge, 99, 0, :east
unit :captive, 101, 0, :east
unit :captive, 106, 0, :east
unit :captive, 109, 0, :east
unit :sludge, 110, 0, :east
unit :archer, 114, 0, :east
unit :sludge, 115, 0, :east
unit :archer, 116, 0, :east
unit :thick_sludge, 119, 0, :east
unit :wizard, 123, 0, :east
unit :archer, 125, 0, :east
unit :captive, 135, 0, :east
unit :archer, 141, 0, :east
unit :sludge, 142, 0, :east
unit :sludge, 143, 0, :east
unit :wizard, 146, 0, :east
unit :archer, 148, 0, :east
unit :sludge, 153, 0, :east
unit :thick_sludge, 167, 0, :east
unit :captive, 174, 0, :east
unit :captive, 175, 0, :east
unit :sludge, 176, 0, :east
unit :thick_sludge, 177, 0, :east
unit :archer, 180, 0, :east
unit :captive, 182, 0, :east
unit :archer, 183, 0, :east
unit :wizard, 193, 0, :east
unit :wizard, 196, 0, :east
unit :sludge, 199, 0, :east
unit :archer, 200, 0, :east
unit :archer, 205, 0, :east
unit :captive, 211, 0, :east
unit :sludge, 213, 0, :east
unit :thick_sludge, 214, 0, :east
unit :sludge, 215, 0, :east
unit :captive, 216, 0, :east
unit :thick_sludge, 219, 0, :east
unit :wizard, 224, 0, :east
unit :sludge, 230, 0, :east
unit :wizard, 233, 0, :east
unit :thick_sludge, 234, 0, :east
unit :wizard, 235, 0, :east
unit :sludge, 237, 0, :east
unit :wizard, 246, 0, :east
unit :sludge, 248, 0, :east
unit :sludge, 251, 0, :east
unit :sludge, 264, 0, :east
unit :thick_sludge, 265, 0, :east
unit :captive, 266, 0, :east
unit :sludge, 270, 0, :east
unit :archer, 274, 0, :east
unit :wizard, 278, 0, :east
unit :captive, 286, 0, :east
unit :captive, 287, 0, :east
unit :thick_sludge, 296, 0, :east
unit :archer, 298, 0, :east
unit :captive, 303, 0, :east
unit :thick_sludge, 304, 0, :east
unit :sludge, 305, 0, :east
unit :archer, 306, 0, :east
unit :sludge, 314, 0, :east
unit :captive, 326, 0, :east
unit :sludge, 330, 0, :east
unit :thick_sludge, 333, 0, :east
unit :wizard, 336, 0, :east
unit :captive, 340, 0, :east
unit :sludge, 341, 0, :east
unit :wizard, 355, 0, :east
unit :archer, 358, 0, :east
unit :thick_sludge, 359, 0, :east
unit :thick_sludge, 363, 0, :east
unit :wizard, 370, 0, :east
unit :sludge, 375, 0, :east
unit :captive, 378, 0, :east
unit :archer, 380, 0, :east
unit :wizard, 381, 0, :east
unit :sludge, 393, 0, :east
unit :thick_sludge, 394, 0, :east
unit :wizard, 417, 0, :east
unit :archer, 419, 0, :east
unit :captive, 426, 0, :east
unit :archer, 437, 0, :east
unit :wizard, 438, 0, :east
unit :thick_sludge, 441, 0, :east
unit :captive, 450, 0, :east
unit :sludge, 457, 0, :east
unit :thick_sludge, 458, 0, :east
unit :wizard, 460, 0, :east
unit :sludge, 463, 0, :east
unit :sludge, 464, 0, :east
unit :archer, 466, 0, :east
unit :thick_sludge, 467, 0, :east
unit :captive, 470, 0, :east
unit :captive, 471, 0, :east
unit :sludge, 474, 0, :east
unit :captive, 481, 0, :east
unit :archer, 486, 0, :east
unit :captive, 491, 0, :east
unit :thick_sludge, 492, 0, :east
unit :sludge, 494, 0, :east
unit :captive, 501, 0, :east
unit :archer, 507, 0, :east
unit :sludge, 511, 0, :east
unit :captive, 516, 0, :east
unit :sludge, 517, 0, :east
unit :sludge, 519, 0, :east
unit :captive, 520, 0, :east
unit :thick_sludge, 523, 0, :east
unit :sludge, 525, 0, :east
unit :sludge, 526, 0, :east
unit :sludge, 529, 0, :east
unit :wizard, 533, 0, :east
unit :archer, 540, 0, :east
unit :captive, 547, 0, :east
unit :archer, 549, 0, :east
unit :archer, 562, 0, :east
unit :sludge, 568, 0, :east
unit :wizard, 570, 0, :east
unit :archer, 572, 0, :east
unit :captive, 573, 0, :east
unit :captive, 583, 0, :east
unit :thick_sludge, 584, 0, :east
unit :wizard, 585, 0, :east
unit :thick_sludge, 586, 0, :east
unit :archer, 589, 0, :east
unit :archer, 591, 0, :east
unit :thick_sludge, 593, 0, :east
unit :archer, 596, 0, :east
unit :sludge, 603, 0, :east
unit :sludge, 604, 0, :east
unit :archer, 605, 0, :east
unit :sludge, 609, 0, :east
unit :captive, 610, 0, :east
unit :captive, 626, 0, :east
unit :thick_sludge, 633, 0, :east
unit :wizard, 635, 0, :east
unit :archer, 646, 0, :east
unit :thick_sludge, 647, 0, :east
unit :captive, 651, 0, :east
unit :sludge, 657, 0, :east
unit :archer, 666, 0, :east
unit :sludge, 670, 0, :east
unit :sludge, 673, 0, :east
unit :archer, 674, 0, :east
unit :wizard, 677, 0, :east
unit :thick_sludge, 680, 0, :east
unit :archer, 681, 0, :east
unit :archer, 686, 0, :east
unit :thick_sludge, 689, 0, :east
unit :thick_sludge, 690, 0, :east
unit :wizard, 693, 0, :east
unit :thick_sludge, 695, 0, :east
unit :wizard, 699, 0, :east
unit :archer, 708, 0, :east
unit :wizard, 713, 0, :east
unit :captive, 720, 0, :east
unit :wizard, 722, 0, :east
unit :wizard, 727, 0, :east
unit :captive, 728, 0, :east
unit :archer, 737, 0, :east
unit :thick_sludge, 738, 0, :east
unit :archer, 743, 0, :east
unit :wizard, 746, 0, :east
unit :sludge, 761, 0, :east
unit :thick_sludge, 762, 0, :east
unit :thick_sludge, 766, 0, :east
unit :sludge, 768, 0, :east
unit :archer, 770, 0, :east
unit :archer, 773, 0, :east
unit :sludge, 775, 0, :east
unit :archer, 782, 0, :east
unit :wizard, 785, 0, :east
unit :captive, 787, 0, :east
unit :sludge, 788, 0, :east
unit :wizard, 792, 0, :east
unit :captive, 794, 0, :east
unit :archer, 795, 0, :east
unit :wizard, 800, 0, :east
unit :thick_sludge, 802, 0, :east
unit :archer, 803, 0, :east
unit :captive, 809, 0, :east
unit :captive, 812, 0, :east
unit :captive, 817, 0, :east
unit :wizard, 835, 0, :east
unit :archer, 836, 0, :east
unit :captive, 839, 0, :east
unit :wizard, 841, 0, :east
unit :archer, 847, 0, :east
unit :sludge, 848, 0, :east
unit :sludge, 854, 0, :west
unit :sludge, 858, 0, :west
unit :archer, 861, 0, :west
