#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  SS s    sSC        s   C   CC         C   aa S C S aa    a C          a C  s   C      S   w w  s  C  sa       a     C s    s    CS s            s     Sa      s  a s      C S      CS S      S  Cs w>C         s  s  S  w    S   S  C           C C s      w    w             S    C     C  a     C  w   C  C  S a   C C s    a  s  s S w C   Sa   w          sss C  s     C  C               ssC     s S             sa     CCs    wSw  ws  w  C  C  w C     a C       a w         S       a         ss         w   w w    Ca     w  a   SC CCaS   s       @   sC        s SsSa w as  a    C S   sS         C     s         Sa      C   C   Ca   S CS      C s C C  s      saS           Cs        C     a S    C           aa        s w    Ss     w  S           CC  S w Ss   s w      S S      w    C s     w S s S   s C      a    s     s a    w   w C a     S             as C     Cs w  a s   a  CS      SCa  w       w         C    s  a  w a  a  Sas             a s            a     a                  SC  C Cs   S      Sa       a |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 1010
ace_score 5050
size 1010, 1
stairs 198, 0

warrior 542, 0, :east

unit :thick_sludge, 2, 0, :east
unit :thick_sludge, 3, 0, :east
unit :sludge, 5, 0, :east
unit :sludge, 10, 0, :east
unit :thick_sludge, 11, 0, :east
unit :captive, 12, 0, :east
unit :sludge, 21, 0, :east
unit :captive, 25, 0, :east
unit :captive, 29, 0, :east
unit :captive, 30, 0, :east
unit :captive, 40, 0, :east
unit :archer, 44, 0, :east
unit :archer, 45, 0, :east
unit :thick_sludge, 47, 0, :east
unit :captive, 49, 0, :east
unit :thick_sludge, 51, 0, :east
unit :archer, 53, 0, :east
unit :archer, 54, 0, :east
unit :archer, 59, 0, :east
unit :captive, 61, 0, :east
unit :archer, 72, 0, :east
unit :captive, 74, 0, :east
unit :sludge, 77, 0, :east
unit :captive, 81, 0, :east
unit :thick_sludge, 88, 0, :east
unit :wizard, 92, 0, :east
unit :wizard, 94, 0, :east
unit :sludge, 97, 0, :east
unit :captive, 100, 0, :east
unit :sludge, 103, 0, :east
unit :archer, 104, 0, :east
unit :archer, 112, 0, :east
unit :captive, 118, 0, :east
unit :sludge, 120, 0, :east
unit :sludge, 125, 0, :east
unit :captive, 130, 0, :east
unit :thick_sludge, 131, 0, :east
unit :sludge, 133, 0, :east
unit :sludge, 146, 0, :east
unit :thick_sludge, 152, 0, :east
unit :archer, 153, 0, :east
unit :sludge, 160, 0, :east
unit :archer, 163, 0, :east
unit :sludge, 165, 0, :east
unit :captive, 172, 0, :east
unit :thick_sludge, 174, 0, :east
unit :captive, 181, 0, :east
unit :thick_sludge, 182, 0, :east
unit :thick_sludge, 184, 0, :east
unit :thick_sludge, 191, 0, :east
unit :captive, 194, 0, :east
unit :sludge, 195, 0, :east
unit :wizard, 197, 0, :east
unit :captive, 199, 0, :east
unit :sludge, 209, 0, :east
unit :sludge, 212, 0, :east
unit :thick_sludge, 215, 0, :east
unit :wizard, 218, 0, :east
unit :thick_sludge, 223, 0, :east
unit :thick_sludge, 227, 0, :east
unit :captive, 230, 0, :east
unit :captive, 242, 0, :east
unit :captive, 244, 0, :east
unit :sludge, 246, 0, :east
unit :wizard, 253, 0, :east
unit :wizard, 258, 0, :east
unit :thick_sludge, 272, 0, :east
unit :captive, 277, 0, :east
unit :captive, 283, 0, :east
unit :archer, 286, 0, :east
unit :captive, 292, 0, :east
unit :wizard, 295, 0, :east
unit :captive, 299, 0, :east
unit :captive, 302, 0, :east
unit :thick_sludge, 305, 0, :east
unit :archer, 307, 0, :east
unit :captive, 311, 0, :east
unit :captive, 313, 0, :east
unit :sludge, 315, 0, :east
unit :archer, 320, 0, :east
unit :sludge, 323, 0, :east
unit :sludge, 326, 0, :east
unit :thick_sludge, 328, 0, :east
unit :wizard, 330, 0, :east
unit :captive, 332, 0, :east
unit :thick_sludge, 336, 0, :east
unit :archer, 337, 0, :east
unit :wizard, 341, 0, :east
unit :sludge, 352, 0, :east
unit :sludge, 353, 0, :east
unit :sludge, 354, 0, :east
unit :captive, 356, 0, :east
unit :sludge, 359, 0, :east
unit :captive, 365, 0, :east
unit :captive, 368, 0, :east
unit :sludge, 384, 0, :east
unit :sludge, 385, 0, :east
unit :captive, 386, 0, :east
unit :sludge, 392, 0, :east
unit :thick_sludge, 394, 0, :east
unit :sludge, 408, 0, :east
unit :archer, 409, 0, :east
unit :captive, 415, 0, :east
unit :captive, 416, 0, :east
unit :sludge, 417, 0, :east
unit :wizard, 422, 0, :east
unit :thick_sludge, 423, 0, :east
unit :wizard, 424, 0, :east
unit :wizard, 427, 0, :east
unit :sludge, 428, 0, :east
unit :wizard, 431, 0, :east
unit :captive, 434, 0, :east
unit :captive, 437, 0, :east
unit :wizard, 440, 0, :east
unit :captive, 442, 0, :east
unit :archer, 448, 0, :east
unit :captive, 450, 0, :east
unit :archer, 458, 0, :east
unit :wizard, 460, 0, :east
unit :thick_sludge, 470, 0, :east
unit :archer, 478, 0, :east
unit :sludge, 488, 0, :east
unit :sludge, 489, 0, :east
unit :wizard, 499, 0, :east
unit :wizard, 503, 0, :east
unit :wizard, 505, 0, :east
unit :captive, 510, 0, :east
unit :archer, 511, 0, :east
unit :wizard, 517, 0, :east
unit :archer, 520, 0, :east
unit :thick_sludge, 524, 0, :east
unit :captive, 525, 0, :east
unit :captive, 527, 0, :east
unit :captive, 528, 0, :east
unit :archer, 529, 0, :east
unit :thick_sludge, 530, 0, :east
unit :sludge, 534, 0, :east
unit :sludge, 546, 0, :west
unit :captive, 547, 0, :west
unit :sludge, 556, 0, :west
unit :thick_sludge, 558, 0, :west
unit :sludge, 559, 0, :west
unit :thick_sludge, 560, 0, :west
unit :archer, 561, 0, :west
unit :wizard, 563, 0, :west
unit :archer, 565, 0, :west
unit :sludge, 566, 0, :west
unit :archer, 569, 0, :west
unit :captive, 574, 0, :west
unit :thick_sludge, 576, 0, :west
unit :sludge, 580, 0, :west
unit :thick_sludge, 581, 0, :west
unit :captive, 591, 0, :west
unit :sludge, 597, 0, :west
unit :thick_sludge, 607, 0, :west
unit :archer, 608, 0, :west
unit :captive, 615, 0, :west
unit :captive, 619, 0, :west
unit :captive, 623, 0, :west
unit :archer, 624, 0, :west
unit :thick_sludge, 628, 0, :west
unit :captive, 630, 0, :west
unit :thick_sludge, 631, 0, :west
unit :captive, 638, 0, :west
unit :sludge, 640, 0, :west
unit :captive, 642, 0, :west
unit :captive, 644, 0, :west
unit :sludge, 647, 0, :west
unit :sludge, 654, 0, :west
unit :archer, 655, 0, :west
unit :thick_sludge, 656, 0, :west
unit :captive, 668, 0, :west
unit :sludge, 669, 0, :west
unit :captive, 678, 0, :west
unit :archer, 684, 0, :west
unit :thick_sludge, 686, 0, :west
unit :captive, 691, 0, :west
unit :archer, 703, 0, :west
unit :archer, 704, 0, :west
unit :sludge, 713, 0, :west
unit :wizard, 715, 0, :west
unit :thick_sludge, 720, 0, :west
unit :sludge, 721, 0, :west
unit :wizard, 727, 0, :west
unit :thick_sludge, 730, 0, :west
unit :captive, 742, 0, :west
unit :captive, 743, 0, :west
unit :thick_sludge, 746, 0, :west
unit :wizard, 748, 0, :west
unit :thick_sludge, 750, 0, :west
unit :sludge, 751, 0, :west
unit :sludge, 755, 0, :west
unit :wizard, 757, 0, :west
unit :thick_sludge, 764, 0, :west
unit :thick_sludge, 766, 0, :west
unit :wizard, 773, 0, :west
unit :captive, 778, 0, :west
unit :sludge, 780, 0, :west
unit :wizard, 786, 0, :west
unit :thick_sludge, 788, 0, :west
unit :sludge, 790, 0, :west
unit :thick_sludge, 792, 0, :west
unit :sludge, 796, 0, :west
unit :captive, 798, 0, :west
unit :archer, 805, 0, :west
unit :sludge, 810, 0, :west
unit :sludge, 816, 0, :west
unit :archer, 818, 0, :west
unit :wizard, 823, 0, :west
unit :wizard, 827, 0, :west
unit :captive, 829, 0, :west
unit :archer, 831, 0, :west
unit :thick_sludge, 837, 0, :west
unit :archer, 851, 0, :west
unit :sludge, 852, 0, :west
unit :captive, 854, 0, :west
unit :captive, 860, 0, :west
unit :sludge, 861, 0, :west
unit :wizard, 863, 0, :west
unit :archer, 866, 0, :west
unit :sludge, 868, 0, :west
unit :archer, 872, 0, :west
unit :captive, 875, 0, :west
unit :thick_sludge, 876, 0, :west
unit :thick_sludge, 883, 0, :west
unit :captive, 884, 0, :west
unit :archer, 885, 0, :west
unit :wizard, 888, 0, :west
unit :wizard, 896, 0, :west
unit :captive, 906, 0, :west
unit :sludge, 911, 0, :west
unit :archer, 914, 0, :west
unit :wizard, 917, 0, :west
unit :archer, 919, 0, :west
unit :archer, 922, 0, :west
unit :thick_sludge, 925, 0, :west
unit :archer, 926, 0, :west
unit :sludge, 927, 0, :west
unit :archer, 941, 0, :west
unit :sludge, 943, 0, :west
unit :archer, 956, 0, :west
unit :archer, 962, 0, :west
unit :thick_sludge, 981, 0, :west
unit :captive, 982, 0, :west
unit :captive, 985, 0, :west
unit :captive, 987, 0, :west
unit :sludge, 988, 0, :west
unit :thick_sludge, 992, 0, :west
unit :thick_sludge, 999, 0, :west
unit :archer, 1000, 0, :west
unit :archer, 1008, 0, :west
