#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |         CS a    aa C   w   C s   w  a  C w Cw         S S   C    w      a     s    C  sw      s   C S Cs       s    w          a          C w w   a    Cw         S     S S    a aCC sS   Ca      s S     S      w         C   s  aa aw          a     S C a      C    w        C          s  C    Caa     s s         C  s saS aCS     C  w      s   s           w C  a   aa C   @  awSSss   w      S     w  S  w        s         C    a s   S  C          a   a         s      w s C C a    C Cs     a SC  S    C  Ss > C C S    s  S w     s S a w    a    a          C   SC   a a  SCSaC    a           a      Sa w S Sa    S    as     s Ss a s s s  C      Sw      s      S   C      s   w      ssw  C C                 w     SCC    a s   w w  S       S      ws    a  Ss sa C  a       a   w   C       w                      s      s     w s S   s     s  S  w             sSa S aSa s         C    w      w    S    w  C   |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 905
ace_score 4525
size 905, 1
stairs 506, 0

warrior 371, 0, :east

unit :captive, 9, 0, :east
unit :thick_sludge, 10, 0, :east
unit :archer, 12, 0, :east
unit :archer, 17, 0, :east
unit :archer, 18, 0, :east
unit :captive, 20, 0, :east
unit :wizard, 24, 0, :east
unit :captive, 28, 0, :east
unit :sludge, 30, 0, :east
unit :wizard, 34, 0, :east
unit :archer, 37, 0, :east
unit :captive, 40, 0, :east
unit :wizard, 42, 0, :east
unit :captive, 44, 0, :east
unit :wizard, 45, 0, :east
unit :thick_sludge, 55, 0, :east
unit :thick_sludge, 57, 0, :east
unit :captive, 61, 0, :east
unit :wizard, 66, 0, :east
unit :archer, 73, 0, :east
unit :sludge, 79, 0, :east
unit :captive, 84, 0, :east
unit :sludge, 87, 0, :east
unit :wizard, 88, 0, :east
unit :sludge, 95, 0, :east
unit :captive, 99, 0, :east
unit :thick_sludge, 101, 0, :east
unit :captive, 103, 0, :east
unit :sludge, 104, 0, :east
unit :sludge, 112, 0, :east
unit :wizard, 117, 0, :east
unit :archer, 128, 0, :east
unit :captive, 139, 0, :east
unit :wizard, 141, 0, :east
unit :wizard, 143, 0, :east
unit :archer, 147, 0, :east
unit :captive, 152, 0, :east
unit :wizard, 153, 0, :east
unit :thick_sludge, 163, 0, :east
unit :thick_sludge, 169, 0, :east
unit :thick_sludge, 171, 0, :east
unit :archer, 176, 0, :east
unit :archer, 178, 0, :east
unit :captive, 179, 0, :east
unit :captive, 180, 0, :east
unit :sludge, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :captive, 187, 0, :east
unit :archer, 188, 0, :east
unit :sludge, 195, 0, :east
unit :thick_sludge, 197, 0, :east
unit :thick_sludge, 203, 0, :east
unit :wizard, 210, 0, :east
unit :captive, 220, 0, :east
unit :sludge, 224, 0, :east
unit :archer, 227, 0, :east
unit :archer, 228, 0, :east
unit :archer, 230, 0, :east
unit :wizard, 231, 0, :east
unit :archer, 242, 0, :east
unit :thick_sludge, 248, 0, :east
unit :captive, 250, 0, :east
unit :archer, 252, 0, :east
unit :captive, 259, 0, :east
unit :wizard, 264, 0, :east
unit :captive, 273, 0, :east
unit :sludge, 284, 0, :east
unit :captive, 287, 0, :east
unit :captive, 292, 0, :east
unit :archer, 293, 0, :east
unit :archer, 294, 0, :east
unit :sludge, 300, 0, :east
unit :sludge, 302, 0, :east
unit :captive, 312, 0, :east
unit :sludge, 315, 0, :east
unit :sludge, 317, 0, :east
unit :archer, 318, 0, :east
unit :thick_sludge, 319, 0, :east
unit :archer, 321, 0, :east
unit :captive, 322, 0, :east
unit :thick_sludge, 323, 0, :east
unit :captive, 329, 0, :east
unit :wizard, 332, 0, :east
unit :sludge, 339, 0, :east
unit :sludge, 343, 0, :east
unit :wizard, 355, 0, :east
unit :captive, 357, 0, :east
unit :archer, 360, 0, :east
unit :archer, 364, 0, :east
unit :archer, 365, 0, :east
unit :captive, 367, 0, :east
unit :archer, 374, 0, :west
unit :wizard, 375, 0, :west
unit :thick_sludge, 376, 0, :west
unit :thick_sludge, 377, 0, :west
unit :sludge, 378, 0, :west
unit :sludge, 379, 0, :west
unit :wizard, 383, 0, :west
unit :thick_sludge, 390, 0, :west
unit :wizard, 396, 0, :west
unit :thick_sludge, 399, 0, :west
unit :wizard, 402, 0, :west
unit :sludge, 411, 0, :west
unit :captive, 421, 0, :west
unit :archer, 426, 0, :west
unit :sludge, 428, 0, :west
unit :thick_sludge, 432, 0, :west
unit :captive, 435, 0, :west
unit :archer, 446, 0, :west
unit :archer, 450, 0, :west
unit :sludge, 460, 0, :west
unit :wizard, 467, 0, :west
unit :sludge, 469, 0, :west
unit :captive, 471, 0, :west
unit :captive, 473, 0, :west
unit :archer, 475, 0, :west
unit :captive, 480, 0, :west
unit :captive, 482, 0, :west
unit :sludge, 483, 0, :west
unit :archer, 489, 0, :west
unit :thick_sludge, 491, 0, :west
unit :captive, 492, 0, :west
unit :thick_sludge, 495, 0, :west
unit :captive, 500, 0, :west
unit :thick_sludge, 503, 0, :west
unit :sludge, 504, 0, :west
unit :captive, 508, 0, :west
unit :captive, 510, 0, :west
unit :thick_sludge, 512, 0, :west
unit :sludge, 517, 0, :west
unit :thick_sludge, 520, 0, :west
unit :wizard, 522, 0, :west
unit :sludge, 528, 0, :west
unit :thick_sludge, 530, 0, :west
unit :archer, 532, 0, :west
unit :wizard, 534, 0, :west
unit :archer, 539, 0, :west
unit :archer, 544, 0, :west
unit :captive, 555, 0, :west
unit :thick_sludge, 559, 0, :west
unit :captive, 560, 0, :west
unit :archer, 564, 0, :west
unit :archer, 566, 0, :west
unit :thick_sludge, 569, 0, :west
unit :captive, 570, 0, :west
unit :thick_sludge, 571, 0, :west
unit :archer, 572, 0, :west
unit :captive, 573, 0, :west
unit :archer, 578, 0, :west
unit :archer, 590, 0, :west
unit :thick_sludge, 597, 0, :west
unit :archer, 598, 0, :west
unit :wizard, 600, 0, :west
unit :thick_sludge, 602, 0, :west
unit :thick_sludge, 604, 0, :west
unit :archer, 605, 0, :west
unit :thick_sludge, 610, 0, :west
unit :archer, 615, 0, :west
unit :sludge, 616, 0, :west
unit :sludge, 622, 0, :west
unit :thick_sludge, 624, 0, :west
unit :sludge, 625, 0, :west
unit :archer, 627, 0, :west
unit :sludge, 629, 0, :west
unit :sludge, 631, 0, :west
unit :sludge, 633, 0, :west
unit :captive, 636, 0, :west
unit :thick_sludge, 643, 0, :west
unit :wizard, 644, 0, :west
unit :sludge, 651, 0, :west
unit :thick_sludge, 658, 0, :west
unit :captive, 662, 0, :west
unit :sludge, 669, 0, :west
unit :wizard, 673, 0, :west
unit :sludge, 680, 0, :west
unit :sludge, 681, 0, :west
unit :wizard, 682, 0, :west
unit :captive, 685, 0, :west
unit :captive, 687, 0, :west
unit :wizard, 705, 0, :west
unit :thick_sludge, 711, 0, :west
unit :captive, 712, 0, :west
unit :captive, 713, 0, :west
unit :archer, 718, 0, :west
unit :sludge, 720, 0, :west
unit :wizard, 724, 0, :west
unit :wizard, 726, 0, :west
unit :thick_sludge, 729, 0, :west
unit :thick_sludge, 737, 0, :west
unit :wizard, 744, 0, :west
unit :sludge, 745, 0, :west
unit :archer, 750, 0, :west
unit :thick_sludge, 753, 0, :west
unit :sludge, 754, 0, :west
unit :sludge, 756, 0, :west
unit :archer, 757, 0, :west
unit :captive, 759, 0, :west
unit :archer, 762, 0, :west
unit :archer, 770, 0, :west
unit :wizard, 774, 0, :west
unit :captive, 778, 0, :west
unit :wizard, 786, 0, :west
unit :sludge, 809, 0, :west
unit :sludge, 816, 0, :west
unit :wizard, 822, 0, :west
unit :sludge, 824, 0, :west
unit :thick_sludge, 826, 0, :west
unit :sludge, 830, 0, :west
unit :sludge, 836, 0, :west
unit :thick_sludge, 839, 0, :west
unit :wizard, 842, 0, :west
unit :sludge, 856, 0, :west
unit :thick_sludge, 857, 0, :west
unit :archer, 858, 0, :west
unit :thick_sludge, 860, 0, :west
unit :archer, 862, 0, :west
unit :thick_sludge, 863, 0, :west
unit :archer, 864, 0, :west
unit :sludge, 866, 0, :west
unit :captive, 876, 0, :west
unit :wizard, 881, 0, :west
unit :wizard, 888, 0, :west
unit :thick_sludge, 893, 0, :west
unit :wizard, 898, 0, :west
unit :captive, 901, 0, :west
