#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     C        w        C     w   Sw        aC      Sa s     s >   a      C         wa  a            C C  a   C   C        S a w  w  w s    C a C    s asSa CCw   S   C    w   w           a         aa  a        wS      s S              C    w  C C   a  C a    w   CS        w                  C a C CS  SsC C  CS    Ss SCw           C w a    w S    CS        w     as       s   a   @  w      s   Ca   s          Ssa   a  sSa a       S  a     C C   SaC  w C     SCs  a  w             w   S      s w         w  S     a   aSC      w a  S     a    s  S               s  C   CC        sa  S C     a          a       s s a sC w a a      C  w   C       S w  sa   S CS    Ca     w     C a    a s     s      w Sa w        s C s  S CC   a         S w     C        s   C  s C   S S  w  s wsC s   SS C   w      a                    SS        S w  a SCS a             a   w C       wsCsCa              aC  s a  S|
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 897
ace_score 4485
size 897, 1
stairs 62, 0

warrior 380, 0, :east

unit :captive, 5, 0, :east
unit :wizard, 14, 0, :east
unit :captive, 23, 0, :east
unit :wizard, 29, 0, :east
unit :thick_sludge, 33, 0, :east
unit :wizard, 34, 0, :east
unit :archer, 43, 0, :east
unit :captive, 44, 0, :east
unit :thick_sludge, 51, 0, :east
unit :archer, 52, 0, :east
unit :sludge, 54, 0, :east
unit :sludge, 60, 0, :east
unit :archer, 66, 0, :east
unit :captive, 73, 0, :east
unit :wizard, 83, 0, :east
unit :archer, 84, 0, :east
unit :archer, 87, 0, :east
unit :captive, 100, 0, :east
unit :captive, 102, 0, :east
unit :archer, 105, 0, :east
unit :captive, 109, 0, :east
unit :captive, 113, 0, :east
unit :thick_sludge, 122, 0, :east
unit :archer, 124, 0, :east
unit :wizard, 126, 0, :east
unit :wizard, 129, 0, :east
unit :wizard, 132, 0, :east
unit :sludge, 134, 0, :east
unit :captive, 139, 0, :east
unit :archer, 141, 0, :east
unit :captive, 143, 0, :east
unit :sludge, 148, 0, :east
unit :archer, 150, 0, :east
unit :sludge, 151, 0, :east
unit :thick_sludge, 152, 0, :east
unit :archer, 153, 0, :east
unit :captive, 155, 0, :east
unit :captive, 156, 0, :east
unit :wizard, 157, 0, :east
unit :thick_sludge, 161, 0, :east
unit :captive, 165, 0, :east
unit :wizard, 170, 0, :east
unit :wizard, 174, 0, :east
unit :archer, 186, 0, :east
unit :archer, 196, 0, :east
unit :archer, 197, 0, :east
unit :archer, 200, 0, :east
unit :wizard, 209, 0, :east
unit :thick_sludge, 210, 0, :east
unit :sludge, 217, 0, :east
unit :thick_sludge, 219, 0, :east
unit :captive, 234, 0, :east
unit :wizard, 239, 0, :east
unit :captive, 242, 0, :east
unit :captive, 244, 0, :east
unit :archer, 248, 0, :east
unit :captive, 251, 0, :east
unit :archer, 253, 0, :east
unit :wizard, 258, 0, :east
unit :captive, 262, 0, :east
unit :thick_sludge, 263, 0, :east
unit :wizard, 272, 0, :east
unit :captive, 291, 0, :east
unit :archer, 293, 0, :east
unit :captive, 295, 0, :east
unit :captive, 297, 0, :east
unit :thick_sludge, 298, 0, :east
unit :thick_sludge, 301, 0, :east
unit :sludge, 302, 0, :east
unit :captive, 303, 0, :east
unit :captive, 305, 0, :east
unit :captive, 308, 0, :east
unit :thick_sludge, 309, 0, :east
unit :thick_sludge, 314, 0, :east
unit :sludge, 315, 0, :east
unit :thick_sludge, 317, 0, :east
unit :captive, 318, 0, :east
unit :wizard, 319, 0, :east
unit :captive, 331, 0, :east
unit :wizard, 333, 0, :east
unit :archer, 335, 0, :east
unit :wizard, 340, 0, :east
unit :thick_sludge, 342, 0, :east
unit :captive, 347, 0, :east
unit :thick_sludge, 348, 0, :east
unit :wizard, 357, 0, :east
unit :archer, 363, 0, :east
unit :sludge, 364, 0, :east
unit :sludge, 372, 0, :east
unit :archer, 376, 0, :east
unit :wizard, 383, 0, :west
unit :sludge, 390, 0, :west
unit :captive, 394, 0, :west
unit :archer, 395, 0, :west
unit :sludge, 399, 0, :west
unit :thick_sludge, 410, 0, :west
unit :sludge, 411, 0, :west
unit :archer, 412, 0, :west
unit :archer, 416, 0, :west
unit :sludge, 419, 0, :west
unit :thick_sludge, 420, 0, :west
unit :archer, 421, 0, :west
unit :archer, 423, 0, :west
unit :thick_sludge, 431, 0, :west
unit :archer, 434, 0, :west
unit :captive, 440, 0, :west
unit :captive, 442, 0, :west
unit :thick_sludge, 446, 0, :west
unit :archer, 447, 0, :west
unit :captive, 448, 0, :west
unit :wizard, 451, 0, :west
unit :captive, 453, 0, :west
unit :thick_sludge, 459, 0, :west
unit :captive, 460, 0, :west
unit :sludge, 461, 0, :west
unit :archer, 464, 0, :west
unit :wizard, 467, 0, :west
unit :wizard, 481, 0, :west
unit :thick_sludge, 485, 0, :west
unit :sludge, 492, 0, :west
unit :wizard, 494, 0, :west
unit :wizard, 504, 0, :west
unit :thick_sludge, 507, 0, :west
unit :archer, 513, 0, :west
unit :archer, 517, 0, :west
unit :thick_sludge, 518, 0, :west
unit :captive, 519, 0, :west
unit :wizard, 526, 0, :west
unit :archer, 528, 0, :west
unit :thick_sludge, 531, 0, :west
unit :archer, 537, 0, :west
unit :sludge, 542, 0, :west
unit :thick_sludge, 545, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 564, 0, :west
unit :captive, 568, 0, :west
unit :captive, 569, 0, :west
unit :sludge, 578, 0, :west
unit :archer, 579, 0, :west
unit :thick_sludge, 582, 0, :west
unit :captive, 584, 0, :west
unit :archer, 590, 0, :west
unit :archer, 601, 0, :west
unit :sludge, 609, 0, :west
unit :sludge, 611, 0, :west
unit :archer, 613, 0, :west
unit :sludge, 615, 0, :west
unit :captive, 616, 0, :west
unit :wizard, 618, 0, :west
unit :archer, 620, 0, :west
unit :archer, 622, 0, :west
unit :captive, 629, 0, :west
unit :wizard, 632, 0, :west
unit :captive, 636, 0, :west
unit :thick_sludge, 644, 0, :west
unit :wizard, 646, 0, :west
unit :sludge, 649, 0, :west
unit :archer, 650, 0, :west
unit :thick_sludge, 654, 0, :west
unit :captive, 656, 0, :west
unit :thick_sludge, 657, 0, :west
unit :captive, 662, 0, :west
unit :archer, 663, 0, :west
unit :wizard, 669, 0, :west
unit :captive, 675, 0, :west
unit :archer, 677, 0, :west
unit :archer, 682, 0, :west
unit :sludge, 684, 0, :west
unit :sludge, 690, 0, :west
unit :wizard, 697, 0, :west
unit :thick_sludge, 699, 0, :west
unit :archer, 700, 0, :west
unit :wizard, 702, 0, :west
unit :sludge, 711, 0, :west
unit :captive, 713, 0, :west
unit :sludge, 715, 0, :west
unit :thick_sludge, 718, 0, :west
unit :captive, 720, 0, :west
unit :captive, 721, 0, :west
unit :archer, 725, 0, :west
unit :thick_sludge, 735, 0, :west
unit :wizard, 737, 0, :west
unit :captive, 743, 0, :west
unit :sludge, 752, 0, :west
unit :captive, 756, 0, :west
unit :sludge, 759, 0, :west
unit :captive, 761, 0, :west
unit :thick_sludge, 765, 0, :west
unit :thick_sludge, 767, 0, :west
unit :wizard, 770, 0, :west
unit :sludge, 773, 0, :west
unit :wizard, 775, 0, :west
unit :sludge, 776, 0, :west
unit :captive, 777, 0, :west
unit :sludge, 779, 0, :west
unit :thick_sludge, 783, 0, :west
unit :thick_sludge, 784, 0, :west
unit :captive, 786, 0, :west
unit :wizard, 790, 0, :west
unit :archer, 797, 0, :west
unit :thick_sludge, 818, 0, :west
unit :thick_sludge, 819, 0, :west
unit :thick_sludge, 828, 0, :west
unit :wizard, 830, 0, :west
unit :archer, 833, 0, :west
unit :thick_sludge, 835, 0, :west
unit :captive, 836, 0, :west
unit :thick_sludge, 837, 0, :west
unit :archer, 839, 0, :west
unit :archer, 853, 0, :west
unit :wizard, 857, 0, :west
unit :captive, 859, 0, :west
unit :wizard, 867, 0, :west
unit :sludge, 868, 0, :west
unit :captive, 869, 0, :west
unit :sludge, 870, 0, :west
unit :captive, 871, 0, :west
unit :archer, 872, 0, :west
unit :archer, 887, 0, :west
unit :captive, 888, 0, :west
unit :sludge, 891, 0, :west
unit :archer, 893, 0, :west
unit :thick_sludge, 896, 0, :west
