#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   w     a a  sa      w sC      s   a  SC       S       s       a     CC a           C                      w  s  w    w   > s   CS     aC         S    CS   ss   s           w S      a       s    Ss       sa         SCs   S s    s w   ssw               s   awC   s           a   a   Ss       Ss      Ssa        C  a s   S         S s     wC             w   C S     a S Sa               sCCSaS    C  s    s  Sa   @     a   a        w   a         C  a w w   sS     a    sS   S       S                s   a  w   CaC     w      S     C  a s  aC   s  w       S       w s wCa    w   SC     sa  w C   s       sw      aS a aC          a  C      aa    S S  S a      CC Ca a  w   w  sa aC aa w   a   s w S ss     C     S Csa      C aa       S  C a s      C S     S      wS s w        C   a  s s  SS    S w  w    aa      S  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 813
ace_score 4065
size 813, 1
stairs 123, 0

warrior 412, 0, :east

unit :wizard, 3, 0, :east
unit :archer, 9, 0, :east
unit :archer, 11, 0, :east
unit :sludge, 14, 0, :east
unit :archer, 15, 0, :east
unit :wizard, 22, 0, :east
unit :sludge, 24, 0, :east
unit :captive, 25, 0, :east
unit :sludge, 32, 0, :east
unit :archer, 36, 0, :east
unit :thick_sludge, 39, 0, :east
unit :captive, 40, 0, :east
unit :thick_sludge, 48, 0, :east
unit :sludge, 56, 0, :east
unit :archer, 64, 0, :east
unit :captive, 70, 0, :east
unit :captive, 71, 0, :east
unit :archer, 73, 0, :east
unit :captive, 85, 0, :east
unit :wizard, 108, 0, :east
unit :sludge, 111, 0, :east
unit :wizard, 114, 0, :east
unit :wizard, 119, 0, :east
unit :sludge, 125, 0, :east
unit :captive, 129, 0, :east
unit :thick_sludge, 130, 0, :east
unit :archer, 136, 0, :east
unit :captive, 137, 0, :east
unit :thick_sludge, 147, 0, :east
unit :captive, 152, 0, :east
unit :thick_sludge, 153, 0, :east
unit :sludge, 157, 0, :east
unit :sludge, 158, 0, :east
unit :sludge, 162, 0, :east
unit :wizard, 174, 0, :east
unit :thick_sludge, 176, 0, :east
unit :archer, 183, 0, :east
unit :sludge, 191, 0, :east
unit :thick_sludge, 196, 0, :east
unit :sludge, 197, 0, :east
unit :sludge, 205, 0, :east
unit :archer, 206, 0, :east
unit :thick_sludge, 216, 0, :east
unit :captive, 217, 0, :east
unit :sludge, 218, 0, :east
unit :thick_sludge, 222, 0, :east
unit :sludge, 224, 0, :east
unit :sludge, 229, 0, :east
unit :wizard, 231, 0, :east
unit :sludge, 235, 0, :east
unit :sludge, 236, 0, :east
unit :wizard, 237, 0, :east
unit :sludge, 253, 0, :east
unit :archer, 257, 0, :east
unit :wizard, 258, 0, :east
unit :captive, 259, 0, :east
unit :sludge, 263, 0, :east
unit :archer, 275, 0, :east
unit :archer, 279, 0, :east
unit :thick_sludge, 283, 0, :east
unit :sludge, 284, 0, :east
unit :thick_sludge, 292, 0, :east
unit :sludge, 293, 0, :east
unit :thick_sludge, 300, 0, :east
unit :sludge, 301, 0, :east
unit :archer, 302, 0, :east
unit :captive, 311, 0, :east
unit :archer, 314, 0, :east
unit :sludge, 316, 0, :east
unit :thick_sludge, 320, 0, :east
unit :thick_sludge, 330, 0, :east
unit :sludge, 332, 0, :east
unit :wizard, 338, 0, :east
unit :captive, 339, 0, :east
unit :wizard, 353, 0, :east
unit :captive, 357, 0, :east
unit :thick_sludge, 359, 0, :east
unit :archer, 365, 0, :east
unit :thick_sludge, 367, 0, :east
unit :thick_sludge, 369, 0, :east
unit :archer, 370, 0, :east
unit :sludge, 386, 0, :east
unit :captive, 387, 0, :east
unit :captive, 388, 0, :east
unit :thick_sludge, 389, 0, :east
unit :archer, 390, 0, :east
unit :thick_sludge, 391, 0, :east
unit :captive, 396, 0, :east
unit :sludge, 399, 0, :east
unit :sludge, 404, 0, :east
unit :thick_sludge, 407, 0, :east
unit :archer, 408, 0, :east
unit :archer, 418, 0, :west
unit :archer, 422, 0, :west
unit :wizard, 431, 0, :west
unit :archer, 435, 0, :west
unit :captive, 445, 0, :west
unit :archer, 448, 0, :west
unit :wizard, 450, 0, :west
unit :wizard, 452, 0, :west
unit :sludge, 456, 0, :west
unit :thick_sludge, 457, 0, :west
unit :archer, 463, 0, :west
unit :sludge, 468, 0, :west
unit :thick_sludge, 469, 0, :west
unit :thick_sludge, 473, 0, :west
unit :thick_sludge, 481, 0, :west
unit :sludge, 498, 0, :west
unit :archer, 502, 0, :west
unit :wizard, 505, 0, :west
unit :captive, 509, 0, :west
unit :archer, 510, 0, :west
unit :captive, 511, 0, :west
unit :wizard, 517, 0, :west
unit :thick_sludge, 524, 0, :west
unit :captive, 530, 0, :west
unit :archer, 533, 0, :west
unit :sludge, 535, 0, :west
unit :archer, 538, 0, :west
unit :captive, 539, 0, :west
unit :sludge, 543, 0, :west
unit :wizard, 546, 0, :west
unit :thick_sludge, 554, 0, :west
unit :wizard, 562, 0, :west
unit :sludge, 564, 0, :west
unit :wizard, 566, 0, :west
unit :captive, 567, 0, :west
unit :archer, 568, 0, :west
unit :wizard, 573, 0, :west
unit :thick_sludge, 577, 0, :west
unit :captive, 578, 0, :west
unit :sludge, 584, 0, :west
unit :archer, 585, 0, :west
unit :wizard, 588, 0, :west
unit :captive, 590, 0, :west
unit :sludge, 594, 0, :west
unit :sludge, 602, 0, :west
unit :wizard, 603, 0, :west
unit :archer, 610, 0, :west
unit :thick_sludge, 611, 0, :west
unit :archer, 613, 0, :west
unit :archer, 615, 0, :west
unit :captive, 616, 0, :west
unit :archer, 627, 0, :west
unit :captive, 630, 0, :west
unit :archer, 637, 0, :west
unit :archer, 638, 0, :west
unit :thick_sludge, 643, 0, :west
unit :thick_sludge, 645, 0, :west
unit :thick_sludge, 648, 0, :west
unit :archer, 650, 0, :west
unit :captive, 657, 0, :west
unit :captive, 658, 0, :west
unit :captive, 660, 0, :west
unit :archer, 661, 0, :west
unit :archer, 663, 0, :west
unit :wizard, 666, 0, :west
unit :wizard, 670, 0, :west
unit :sludge, 673, 0, :west
unit :archer, 674, 0, :west
unit :archer, 676, 0, :west
unit :captive, 677, 0, :west
unit :archer, 679, 0, :west
unit :archer, 680, 0, :west
unit :wizard, 682, 0, :west
unit :archer, 686, 0, :west
unit :sludge, 690, 0, :west
unit :wizard, 692, 0, :west
unit :thick_sludge, 694, 0, :west
unit :sludge, 696, 0, :west
unit :sludge, 697, 0, :west
unit :captive, 703, 0, :west
unit :thick_sludge, 709, 0, :west
unit :captive, 711, 0, :west
unit :sludge, 712, 0, :west
unit :archer, 713, 0, :west
unit :captive, 720, 0, :west
unit :archer, 722, 0, :west
unit :archer, 723, 0, :west
unit :thick_sludge, 731, 0, :west
unit :captive, 734, 0, :west
unit :archer, 736, 0, :west
unit :sludge, 738, 0, :west
unit :captive, 745, 0, :west
unit :thick_sludge, 747, 0, :west
unit :thick_sludge, 753, 0, :west
unit :wizard, 760, 0, :west
unit :thick_sludge, 761, 0, :west
unit :sludge, 763, 0, :west
unit :wizard, 765, 0, :west
unit :captive, 774, 0, :west
unit :archer, 778, 0, :west
unit :sludge, 781, 0, :west
unit :sludge, 783, 0, :west
unit :thick_sludge, 786, 0, :west
unit :thick_sludge, 787, 0, :west
unit :thick_sludge, 792, 0, :west
unit :wizard, 794, 0, :west
unit :wizard, 797, 0, :west
unit :archer, 802, 0, :west
unit :archer, 803, 0, :west
unit :thick_sludge, 810, 0, :west
