#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C     S     C  s   C  aCS     s w         S  w   S SC   S C     s   w   a   S  s    a aw       Saa    w     s a   a C       s      S s CCs a    w   wC C w   s w w             a   >       C  a       C sa a      a s     a  s   s        w   C           Ca       s  C   S    a   w  w  s    @   s w   C     a     Ca    S     w   s Cw  w   asw  s aa     w  Ss w  s w S   S   C     s S       S  w w  s    C       s               aC                 C  w s         s SC    S   s C   w    C aS a   w              ss   S    w            C s       a S         S C CSa Cw w   C      CC s         aa   w     sCS    |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 602
ace_score 3010
size 602, 1
stairs 180, 0

warrior 287, 0, :east

unit :captive, 1, 0, :east
unit :thick_sludge, 7, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 16, 0, :east
unit :captive, 20, 0, :east
unit :archer, 23, 0, :east
unit :captive, 24, 0, :east
unit :thick_sludge, 25, 0, :east
unit :sludge, 31, 0, :east
unit :wizard, 33, 0, :east
unit :thick_sludge, 43, 0, :east
unit :wizard, 46, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 52, 0, :east
unit :captive, 53, 0, :east
unit :thick_sludge, 57, 0, :east
unit :captive, 59, 0, :east
unit :sludge, 65, 0, :east
unit :wizard, 69, 0, :east
unit :archer, 73, 0, :east
unit :thick_sludge, 77, 0, :east
unit :sludge, 80, 0, :east
unit :archer, 85, 0, :east
unit :archer, 87, 0, :east
unit :wizard, 88, 0, :east
unit :thick_sludge, 96, 0, :east
unit :archer, 97, 0, :east
unit :archer, 98, 0, :east
unit :wizard, 103, 0, :east
unit :sludge, 109, 0, :east
unit :archer, 111, 0, :east
unit :archer, 115, 0, :east
unit :captive, 117, 0, :east
unit :sludge, 125, 0, :east
unit :thick_sludge, 132, 0, :east
unit :sludge, 134, 0, :east
unit :captive, 136, 0, :east
unit :captive, 137, 0, :east
unit :sludge, 138, 0, :east
unit :archer, 140, 0, :east
unit :wizard, 145, 0, :east
unit :wizard, 149, 0, :east
unit :captive, 150, 0, :east
unit :captive, 152, 0, :east
unit :wizard, 154, 0, :east
unit :sludge, 158, 0, :east
unit :wizard, 160, 0, :east
unit :wizard, 162, 0, :east
unit :archer, 176, 0, :east
unit :captive, 188, 0, :east
unit :archer, 191, 0, :east
unit :captive, 199, 0, :east
unit :sludge, 201, 0, :east
unit :archer, 202, 0, :east
unit :archer, 204, 0, :east
unit :archer, 211, 0, :east
unit :sludge, 213, 0, :east
unit :archer, 219, 0, :east
unit :sludge, 222, 0, :east
unit :sludge, 226, 0, :east
unit :wizard, 235, 0, :east
unit :captive, 239, 0, :east
unit :captive, 251, 0, :east
unit :archer, 252, 0, :east
unit :sludge, 260, 0, :east
unit :captive, 263, 0, :east
unit :thick_sludge, 267, 0, :east
unit :archer, 272, 0, :east
unit :wizard, 276, 0, :east
unit :wizard, 279, 0, :east
unit :sludge, 282, 0, :east
unit :sludge, 291, 0, :west
unit :wizard, 293, 0, :west
unit :captive, 297, 0, :west
unit :archer, 303, 0, :west
unit :captive, 309, 0, :west
unit :archer, 310, 0, :west
unit :thick_sludge, 315, 0, :west
unit :wizard, 321, 0, :west
unit :sludge, 325, 0, :west
unit :captive, 327, 0, :west
unit :wizard, 328, 0, :west
unit :wizard, 331, 0, :west
unit :archer, 335, 0, :west
unit :sludge, 336, 0, :west
unit :wizard, 337, 0, :west
unit :sludge, 340, 0, :west
unit :archer, 342, 0, :west
unit :archer, 343, 0, :west
unit :wizard, 349, 0, :west
unit :thick_sludge, 352, 0, :west
unit :sludge, 353, 0, :west
unit :wizard, 355, 0, :west
unit :sludge, 358, 0, :west
unit :wizard, 360, 0, :west
unit :thick_sludge, 362, 0, :west
unit :thick_sludge, 366, 0, :west
unit :captive, 370, 0, :west
unit :sludge, 376, 0, :west
unit :thick_sludge, 378, 0, :west
unit :thick_sludge, 386, 0, :west
unit :wizard, 389, 0, :west
unit :wizard, 391, 0, :west
unit :sludge, 394, 0, :west
unit :captive, 399, 0, :west
unit :sludge, 407, 0, :west
unit :archer, 423, 0, :west
unit :captive, 424, 0, :west
unit :captive, 442, 0, :west
unit :wizard, 445, 0, :west
unit :sludge, 447, 0, :west
unit :sludge, 457, 0, :west
unit :thick_sludge, 459, 0, :west
unit :captive, 460, 0, :west
unit :thick_sludge, 465, 0, :west
unit :sludge, 469, 0, :west
unit :captive, 471, 0, :west
unit :wizard, 475, 0, :west
unit :captive, 480, 0, :west
unit :archer, 482, 0, :west
unit :thick_sludge, 483, 0, :west
unit :archer, 485, 0, :west
unit :wizard, 489, 0, :west
unit :sludge, 504, 0, :west
unit :sludge, 505, 0, :west
unit :thick_sludge, 509, 0, :west
unit :wizard, 514, 0, :west
unit :captive, 527, 0, :west
unit :sludge, 529, 0, :west
unit :archer, 537, 0, :west
unit :thick_sludge, 539, 0, :west
unit :thick_sludge, 549, 0, :west
unit :captive, 551, 0, :west
unit :captive, 553, 0, :west
unit :thick_sludge, 554, 0, :west
unit :archer, 555, 0, :west
unit :captive, 557, 0, :west
unit :wizard, 558, 0, :west
unit :wizard, 560, 0, :west
unit :captive, 564, 0, :west
unit :captive, 571, 0, :west
unit :captive, 572, 0, :west
unit :sludge, 574, 0, :west
unit :archer, 584, 0, :west
unit :archer, 585, 0, :west
unit :wizard, 589, 0, :west
unit :sludge, 595, 0, :west
unit :captive, 596, 0, :west
unit :thick_sludge, 597, 0, :west
