#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S  s      w          a s    C                s  C    s w Ss s   w    a s  s wC     a   S S S  s        w   Ss            s  S     S  @  sS         wS   sw    SSa s   CC  C   S        w   S  Sw    Sa C  SC    CSa  S          S  S a s      S s     s    C s  S       s    s       w   as    SC            wSS a    a Ca    Sa    w S SwS    S  s          C w  a          a    C     S   SSC   w wC S   a C    CS             w  C            s>      ws C    s S    w w   C   a          s              Ss        w a s  C  s S   aS  s           S   Cw  aaa    a  s      a                      ss      C     Ca C w    w    s  a  a     w        C as         a  a   a     w  C                  C   awa  C   aC saaSwC C   a     a    C  Cs|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 724
ace_score 3620
size 724, 1
stairs 435, 0

warrior 134, 0, :east

unit :thick_sludge, 1, 0, :east
unit :sludge, 4, 0, :east
unit :wizard, 11, 0, :east
unit :archer, 22, 0, :east
unit :sludge, 24, 0, :east
unit :captive, 29, 0, :east
unit :sludge, 46, 0, :east
unit :captive, 49, 0, :east
unit :sludge, 54, 0, :east
unit :wizard, 56, 0, :east
unit :thick_sludge, 58, 0, :east
unit :sludge, 59, 0, :east
unit :sludge, 61, 0, :east
unit :wizard, 65, 0, :east
unit :archer, 70, 0, :east
unit :sludge, 72, 0, :east
unit :sludge, 75, 0, :east
unit :wizard, 77, 0, :east
unit :captive, 78, 0, :east
unit :archer, 84, 0, :east
unit :thick_sludge, 88, 0, :east
unit :thick_sludge, 90, 0, :east
unit :thick_sludge, 92, 0, :east
unit :sludge, 95, 0, :east
unit :wizard, 104, 0, :east
unit :thick_sludge, 108, 0, :east
unit :sludge, 109, 0, :east
unit :sludge, 122, 0, :east
unit :thick_sludge, 125, 0, :east
unit :thick_sludge, 131, 0, :east
unit :sludge, 137, 0, :west
unit :thick_sludge, 138, 0, :west
unit :wizard, 148, 0, :west
unit :thick_sludge, 149, 0, :west
unit :sludge, 153, 0, :west
unit :wizard, 154, 0, :west
unit :thick_sludge, 159, 0, :west
unit :thick_sludge, 160, 0, :west
unit :archer, 161, 0, :west
unit :sludge, 163, 0, :west
unit :captive, 167, 0, :west
unit :captive, 168, 0, :west
unit :captive, 171, 0, :west
unit :thick_sludge, 175, 0, :west
unit :wizard, 184, 0, :west
unit :thick_sludge, 188, 0, :west
unit :thick_sludge, 191, 0, :west
unit :wizard, 192, 0, :west
unit :thick_sludge, 197, 0, :west
unit :archer, 198, 0, :west
unit :captive, 200, 0, :west
unit :thick_sludge, 203, 0, :west
unit :captive, 204, 0, :west
unit :captive, 209, 0, :west
unit :thick_sludge, 210, 0, :west
unit :archer, 211, 0, :west
unit :thick_sludge, 214, 0, :west
unit :thick_sludge, 225, 0, :west
unit :thick_sludge, 228, 0, :west
unit :archer, 230, 0, :west
unit :sludge, 232, 0, :west
unit :thick_sludge, 239, 0, :west
unit :sludge, 241, 0, :west
unit :sludge, 247, 0, :west
unit :captive, 252, 0, :west
unit :sludge, 254, 0, :west
unit :thick_sludge, 257, 0, :west
unit :sludge, 265, 0, :west
unit :sludge, 270, 0, :west
unit :wizard, 278, 0, :west
unit :archer, 282, 0, :west
unit :sludge, 283, 0, :west
unit :thick_sludge, 288, 0, :west
unit :captive, 289, 0, :west
unit :wizard, 302, 0, :west
unit :thick_sludge, 303, 0, :west
unit :thick_sludge, 304, 0, :west
unit :archer, 306, 0, :west
unit :archer, 311, 0, :west
unit :captive, 313, 0, :west
unit :archer, 314, 0, :west
unit :thick_sludge, 319, 0, :west
unit :archer, 320, 0, :west
unit :wizard, 325, 0, :west
unit :thick_sludge, 327, 0, :west
unit :thick_sludge, 329, 0, :west
unit :wizard, 330, 0, :west
unit :thick_sludge, 331, 0, :west
unit :thick_sludge, 336, 0, :west
unit :sludge, 339, 0, :west
unit :captive, 350, 0, :west
unit :wizard, 352, 0, :west
unit :archer, 355, 0, :west
unit :archer, 366, 0, :west
unit :captive, 371, 0, :west
unit :thick_sludge, 377, 0, :west
unit :thick_sludge, 381, 0, :west
unit :thick_sludge, 382, 0, :west
unit :captive, 383, 0, :west
unit :wizard, 387, 0, :west
unit :wizard, 389, 0, :west
unit :captive, 390, 0, :west
unit :thick_sludge, 392, 0, :west
unit :archer, 396, 0, :west
unit :captive, 398, 0, :west
unit :captive, 403, 0, :west
unit :thick_sludge, 404, 0, :west
unit :wizard, 418, 0, :west
unit :captive, 421, 0, :west
unit :sludge, 434, 0, :west
unit :wizard, 442, 0, :west
unit :sludge, 443, 0, :west
unit :captive, 445, 0, :west
unit :sludge, 450, 0, :west
unit :thick_sludge, 452, 0, :west
unit :wizard, 457, 0, :west
unit :wizard, 459, 0, :west
unit :captive, 463, 0, :west
unit :archer, 467, 0, :west
unit :sludge, 478, 0, :west
unit :thick_sludge, 493, 0, :west
unit :sludge, 494, 0, :west
unit :wizard, 503, 0, :west
unit :archer, 505, 0, :west
unit :sludge, 507, 0, :west
unit :captive, 510, 0, :west
unit :sludge, 513, 0, :west
unit :thick_sludge, 515, 0, :west
unit :archer, 519, 0, :west
unit :thick_sludge, 520, 0, :west
unit :sludge, 523, 0, :west
unit :thick_sludge, 535, 0, :west
unit :captive, 539, 0, :west
unit :wizard, 540, 0, :west
unit :archer, 543, 0, :west
unit :archer, 544, 0, :west
unit :archer, 545, 0, :west
unit :archer, 550, 0, :west
unit :sludge, 553, 0, :west
unit :archer, 560, 0, :west
unit :sludge, 583, 0, :west
unit :sludge, 584, 0, :west
unit :captive, 591, 0, :west
unit :captive, 597, 0, :west
unit :archer, 598, 0, :west
unit :captive, 600, 0, :west
unit :wizard, 602, 0, :west
unit :wizard, 607, 0, :west
unit :sludge, 612, 0, :west
unit :archer, 615, 0, :west
unit :archer, 618, 0, :west
unit :wizard, 624, 0, :west
unit :captive, 633, 0, :west
unit :archer, 635, 0, :west
unit :sludge, 636, 0, :west
unit :archer, 646, 0, :west
unit :archer, 649, 0, :west
unit :archer, 653, 0, :west
unit :wizard, 659, 0, :west
unit :captive, 662, 0, :west
unit :captive, 681, 0, :west
unit :archer, 685, 0, :west
unit :wizard, 686, 0, :west
unit :archer, 687, 0, :west
unit :captive, 690, 0, :west
unit :archer, 694, 0, :west
unit :captive, 695, 0, :west
unit :sludge, 697, 0, :west
unit :archer, 698, 0, :west
unit :archer, 699, 0, :west
unit :thick_sludge, 700, 0, :west
unit :wizard, 701, 0, :west
unit :captive, 702, 0, :west
unit :captive, 704, 0, :west
unit :archer, 708, 0, :west
unit :archer, 714, 0, :west
unit :captive, 719, 0, :west
unit :captive, 722, 0, :west
unit :sludge, 723, 0, :west
