#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    aw   a    w  s  S       C      aC    s C           a   sS  w       a C  w   C  S  a     s     C   w          s  S        s  a S  S         s            a     SS      a    S C     Sw s s     s SC w C a  s    s    S           a Sa  a  C   SC         s         sw   a C       a C  s  s  SsS   aS ss    C  C          C         w SaC  C  wSC aC S    S S   wC          w  CS  s   s  aa    C    w   w  a  a    SCw C        s a   S s           @           aa   w S   w Cs      S    w C    C     CCS  C    Sa    a  a    a   S       s  S     ssSa      S       aw   s w     s CC     a   S  w Cw  C C         C sa  SsS            s         s a  S      S w C       aw a    w   w     w  C  s            wS a   s C                  a     C CC         a      C C    w      SsC s   a     >a  a  sS w         a   a C           CCC  a             a       S a   SC  a  C w   CS S    s    a  s w    |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 882
ace_score 4410
size 882, 1
stairs 775, 0

warrior 440, 0, :east

unit :archer, 4, 0, :east
unit :wizard, 5, 0, :east
unit :archer, 9, 0, :east
unit :wizard, 14, 0, :east
unit :sludge, 17, 0, :east
unit :thick_sludge, 20, 0, :east
unit :captive, 28, 0, :east
unit :archer, 35, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 41, 0, :east
unit :captive, 43, 0, :east
unit :archer, 55, 0, :east
unit :sludge, 59, 0, :east
unit :thick_sludge, 60, 0, :east
unit :wizard, 63, 0, :east
unit :archer, 71, 0, :east
unit :captive, 73, 0, :east
unit :wizard, 76, 0, :east
unit :captive, 80, 0, :east
unit :thick_sludge, 83, 0, :east
unit :archer, 86, 0, :east
unit :sludge, 92, 0, :east
unit :captive, 98, 0, :east
unit :wizard, 102, 0, :east
unit :sludge, 113, 0, :east
unit :thick_sludge, 116, 0, :east
unit :sludge, 125, 0, :east
unit :archer, 128, 0, :east
unit :thick_sludge, 130, 0, :east
unit :thick_sludge, 133, 0, :east
unit :sludge, 143, 0, :east
unit :archer, 156, 0, :east
unit :thick_sludge, 162, 0, :east
unit :thick_sludge, 163, 0, :east
unit :archer, 170, 0, :east
unit :thick_sludge, 175, 0, :east
unit :captive, 177, 0, :east
unit :thick_sludge, 183, 0, :east
unit :wizard, 184, 0, :east
unit :sludge, 186, 0, :east
unit :sludge, 188, 0, :east
unit :sludge, 194, 0, :east
unit :thick_sludge, 196, 0, :east
unit :captive, 197, 0, :east
unit :wizard, 199, 0, :east
unit :captive, 201, 0, :east
unit :archer, 203, 0, :east
unit :sludge, 206, 0, :east
unit :sludge, 211, 0, :east
unit :thick_sludge, 216, 0, :east
unit :archer, 228, 0, :east
unit :thick_sludge, 230, 0, :east
unit :archer, 231, 0, :east
unit :archer, 234, 0, :east
unit :captive, 237, 0, :east
unit :thick_sludge, 241, 0, :east
unit :captive, 242, 0, :east
unit :sludge, 252, 0, :east
unit :sludge, 262, 0, :east
unit :wizard, 263, 0, :east
unit :archer, 267, 0, :east
unit :captive, 269, 0, :east
unit :archer, 277, 0, :east
unit :captive, 279, 0, :east
unit :sludge, 282, 0, :east
unit :sludge, 285, 0, :east
unit :thick_sludge, 288, 0, :east
unit :sludge, 289, 0, :east
unit :thick_sludge, 290, 0, :east
unit :archer, 294, 0, :east
unit :thick_sludge, 295, 0, :east
unit :sludge, 297, 0, :east
unit :sludge, 298, 0, :east
unit :captive, 303, 0, :east
unit :captive, 306, 0, :east
unit :captive, 317, 0, :east
unit :wizard, 327, 0, :east
unit :thick_sludge, 329, 0, :east
unit :archer, 330, 0, :east
unit :captive, 331, 0, :east
unit :captive, 334, 0, :east
unit :wizard, 337, 0, :east
unit :thick_sludge, 338, 0, :east
unit :captive, 339, 0, :east
unit :archer, 341, 0, :east
unit :captive, 342, 0, :east
unit :thick_sludge, 344, 0, :east
unit :thick_sludge, 349, 0, :east
unit :thick_sludge, 351, 0, :east
unit :wizard, 355, 0, :east
unit :captive, 356, 0, :east
unit :wizard, 367, 0, :east
unit :captive, 370, 0, :east
unit :thick_sludge, 371, 0, :east
unit :sludge, 374, 0, :east
unit :sludge, 378, 0, :east
unit :archer, 381, 0, :east
unit :archer, 382, 0, :east
unit :captive, 387, 0, :east
unit :wizard, 392, 0, :east
unit :wizard, 396, 0, :east
unit :archer, 399, 0, :east
unit :archer, 402, 0, :east
unit :thick_sludge, 407, 0, :east
unit :captive, 408, 0, :east
unit :wizard, 409, 0, :east
unit :captive, 411, 0, :east
unit :sludge, 420, 0, :east
unit :archer, 422, 0, :east
unit :thick_sludge, 426, 0, :east
unit :sludge, 428, 0, :east
unit :archer, 452, 0, :west
unit :archer, 453, 0, :west
unit :wizard, 457, 0, :west
unit :thick_sludge, 459, 0, :west
unit :wizard, 463, 0, :west
unit :captive, 465, 0, :west
unit :sludge, 466, 0, :west
unit :thick_sludge, 473, 0, :west
unit :wizard, 478, 0, :west
unit :captive, 480, 0, :west
unit :captive, 485, 0, :west
unit :captive, 491, 0, :west
unit :captive, 492, 0, :west
unit :thick_sludge, 493, 0, :west
unit :captive, 496, 0, :west
unit :thick_sludge, 501, 0, :west
unit :archer, 502, 0, :west
unit :archer, 507, 0, :west
unit :archer, 510, 0, :west
unit :archer, 515, 0, :west
unit :thick_sludge, 519, 0, :west
unit :sludge, 527, 0, :west
unit :thick_sludge, 530, 0, :west
unit :sludge, 536, 0, :west
unit :sludge, 537, 0, :west
unit :thick_sludge, 538, 0, :west
unit :archer, 539, 0, :west
unit :thick_sludge, 546, 0, :west
unit :archer, 554, 0, :west
unit :wizard, 555, 0, :west
unit :sludge, 559, 0, :west
unit :wizard, 561, 0, :west
unit :sludge, 567, 0, :west
unit :captive, 569, 0, :west
unit :captive, 570, 0, :west
unit :archer, 576, 0, :west
unit :thick_sludge, 580, 0, :west
unit :wizard, 583, 0, :west
unit :captive, 585, 0, :west
unit :wizard, 586, 0, :west
unit :captive, 589, 0, :west
unit :captive, 591, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 603, 0, :west
unit :archer, 604, 0, :west
unit :thick_sludge, 607, 0, :west
unit :sludge, 608, 0, :west
unit :thick_sludge, 609, 0, :west
unit :sludge, 622, 0, :west
unit :sludge, 632, 0, :west
unit :archer, 634, 0, :west
unit :thick_sludge, 637, 0, :west
unit :thick_sludge, 644, 0, :west
unit :wizard, 646, 0, :west
unit :captive, 648, 0, :west
unit :archer, 656, 0, :west
unit :wizard, 657, 0, :west
unit :archer, 659, 0, :west
unit :wizard, 664, 0, :west
unit :wizard, 668, 0, :west
unit :wizard, 674, 0, :west
unit :captive, 677, 0, :west
unit :sludge, 680, 0, :west
unit :wizard, 693, 0, :west
unit :thick_sludge, 694, 0, :west
unit :archer, 696, 0, :west
unit :sludge, 700, 0, :west
unit :captive, 702, 0, :west
unit :archer, 721, 0, :west
unit :captive, 727, 0, :west
unit :captive, 729, 0, :west
unit :captive, 730, 0, :west
unit :archer, 740, 0, :west
unit :captive, 747, 0, :west
unit :captive, 749, 0, :west
unit :wizard, 754, 0, :west
unit :thick_sludge, 761, 0, :west
unit :sludge, 762, 0, :west
unit :captive, 763, 0, :west
unit :sludge, 765, 0, :west
unit :archer, 769, 0, :west
unit :archer, 776, 0, :west
unit :archer, 779, 0, :west
unit :sludge, 782, 0, :west
unit :thick_sludge, 783, 0, :west
unit :wizard, 785, 0, :west
unit :archer, 795, 0, :west
unit :archer, 799, 0, :west
unit :captive, 801, 0, :west
unit :captive, 813, 0, :west
unit :captive, 814, 0, :west
unit :captive, 815, 0, :west
unit :archer, 818, 0, :west
unit :archer, 832, 0, :west
unit :thick_sludge, 840, 0, :west
unit :archer, 842, 0, :west
unit :thick_sludge, 846, 0, :west
unit :captive, 847, 0, :west
unit :archer, 850, 0, :west
unit :captive, 853, 0, :west
unit :wizard, 855, 0, :west
unit :captive, 859, 0, :west
unit :thick_sludge, 860, 0, :west
unit :thick_sludge, 862, 0, :west
unit :sludge, 867, 0, :west
unit :archer, 872, 0, :west
unit :sludge, 875, 0, :west
unit :wizard, 877, 0, :west
