#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |       Ss    s   w a S       w      s   ssCa S     asS s         w   s w    Ca  wa   ws  s SC   w CS   SS        S S w>s   w     a  SS    s C  s    C C      ss           C    S   s aC   s     C  s       C      C       C  sC S S  C     S    a  S                    C     C      S S         ss      a  sS w w     Cs S    s C aS      s C   s    CCSw w  C   @   Sa        S      w    C     w  Ss  sC    aC  sSaa          w   C       a   a    w     S    w    aC w C   Sa          C   a C  C      S           s     s  w s          C  s   Ss         a    S a  a       C a  s  s        a     a   aC   a C        s S w             S    w Ca      |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 637
ace_score 3185
size 637, 1
stairs 118, 0

warrior 354, 0, :east

unit :thick_sludge, 7, 0, :east
unit :sludge, 8, 0, :east
unit :sludge, 13, 0, :east
unit :wizard, 17, 0, :east
unit :archer, 19, 0, :east
unit :thick_sludge, 21, 0, :east
unit :wizard, 29, 0, :east
unit :sludge, 36, 0, :east
unit :sludge, 40, 0, :east
unit :sludge, 41, 0, :east
unit :captive, 42, 0, :east
unit :archer, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :archer, 51, 0, :east
unit :sludge, 52, 0, :east
unit :thick_sludge, 53, 0, :east
unit :sludge, 55, 0, :east
unit :wizard, 65, 0, :east
unit :sludge, 69, 0, :east
unit :wizard, 71, 0, :east
unit :captive, 76, 0, :east
unit :archer, 77, 0, :east
unit :wizard, 80, 0, :east
unit :archer, 81, 0, :east
unit :wizard, 85, 0, :east
unit :sludge, 86, 0, :east
unit :sludge, 89, 0, :east
unit :thick_sludge, 91, 0, :east
unit :captive, 92, 0, :east
unit :wizard, 96, 0, :east
unit :captive, 98, 0, :east
unit :thick_sludge, 99, 0, :east
unit :thick_sludge, 103, 0, :east
unit :thick_sludge, 104, 0, :east
unit :thick_sludge, 113, 0, :east
unit :thick_sludge, 115, 0, :east
unit :wizard, 117, 0, :east
unit :sludge, 119, 0, :east
unit :wizard, 123, 0, :east
unit :archer, 129, 0, :east
unit :thick_sludge, 132, 0, :east
unit :thick_sludge, 133, 0, :east
unit :sludge, 138, 0, :east
unit :captive, 140, 0, :east
unit :sludge, 143, 0, :east
unit :captive, 148, 0, :east
unit :captive, 150, 0, :east
unit :sludge, 157, 0, :east
unit :sludge, 158, 0, :east
unit :captive, 170, 0, :east
unit :thick_sludge, 175, 0, :east
unit :sludge, 179, 0, :east
unit :archer, 181, 0, :east
unit :captive, 182, 0, :east
unit :sludge, 186, 0, :east
unit :captive, 192, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 203, 0, :east
unit :captive, 210, 0, :east
unit :captive, 218, 0, :east
unit :sludge, 221, 0, :east
unit :captive, 222, 0, :east
unit :thick_sludge, 224, 0, :east
unit :thick_sludge, 226, 0, :east
unit :captive, 229, 0, :east
unit :thick_sludge, 235, 0, :east
unit :archer, 240, 0, :east
unit :thick_sludge, 243, 0, :east
unit :captive, 264, 0, :east
unit :captive, 270, 0, :east
unit :thick_sludge, 277, 0, :east
unit :thick_sludge, 279, 0, :east
unit :sludge, 289, 0, :east
unit :sludge, 290, 0, :east
unit :archer, 297, 0, :east
unit :sludge, 300, 0, :east
unit :thick_sludge, 301, 0, :east
unit :wizard, 303, 0, :east
unit :wizard, 305, 0, :east
unit :captive, 311, 0, :east
unit :sludge, 312, 0, :east
unit :thick_sludge, 314, 0, :east
unit :sludge, 319, 0, :east
unit :captive, 321, 0, :east
unit :archer, 323, 0, :east
unit :thick_sludge, 324, 0, :east
unit :sludge, 331, 0, :east
unit :captive, 333, 0, :east
unit :sludge, 337, 0, :east
unit :captive, 342, 0, :east
unit :captive, 343, 0, :east
unit :thick_sludge, 344, 0, :east
unit :wizard, 345, 0, :east
unit :wizard, 347, 0, :east
unit :captive, 350, 0, :east
unit :thick_sludge, 358, 0, :west
unit :archer, 359, 0, :west
unit :thick_sludge, 368, 0, :west
unit :wizard, 375, 0, :west
unit :captive, 380, 0, :west
unit :wizard, 386, 0, :west
unit :thick_sludge, 389, 0, :west
unit :sludge, 390, 0, :west
unit :sludge, 393, 0, :west
unit :captive, 394, 0, :west
unit :archer, 399, 0, :west
unit :captive, 400, 0, :west
unit :sludge, 403, 0, :west
unit :thick_sludge, 404, 0, :west
unit :archer, 405, 0, :west
unit :archer, 406, 0, :west
unit :wizard, 417, 0, :west
unit :captive, 421, 0, :west
unit :archer, 429, 0, :west
unit :archer, 433, 0, :west
unit :wizard, 438, 0, :west
unit :thick_sludge, 444, 0, :west
unit :wizard, 449, 0, :west
unit :archer, 454, 0, :west
unit :captive, 455, 0, :west
unit :wizard, 457, 0, :west
unit :captive, 459, 0, :west
unit :thick_sludge, 463, 0, :west
unit :archer, 464, 0, :west
unit :captive, 475, 0, :west
unit :archer, 479, 0, :west
unit :captive, 481, 0, :west
unit :captive, 484, 0, :west
unit :thick_sludge, 491, 0, :west
unit :sludge, 503, 0, :west
unit :sludge, 509, 0, :west
unit :wizard, 512, 0, :west
unit :sludge, 514, 0, :west
unit :captive, 525, 0, :west
unit :sludge, 528, 0, :west
unit :thick_sludge, 532, 0, :west
unit :sludge, 533, 0, :west
unit :archer, 543, 0, :west
unit :thick_sludge, 548, 0, :west
unit :archer, 550, 0, :west
unit :archer, 553, 0, :west
unit :captive, 561, 0, :west
unit :archer, 563, 0, :west
unit :sludge, 566, 0, :west
unit :sludge, 569, 0, :west
unit :archer, 578, 0, :west
unit :archer, 584, 0, :west
unit :archer, 588, 0, :west
unit :captive, 589, 0, :west
unit :archer, 593, 0, :west
unit :captive, 595, 0, :west
unit :sludge, 604, 0, :west
unit :thick_sludge, 606, 0, :west
unit :wizard, 608, 0, :west
unit :thick_sludge, 622, 0, :west
unit :wizard, 627, 0, :west
unit :captive, 629, 0, :west
unit :archer, 630, 0, :west
