#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   a  sa Sa    s Cs  C  sa              C sCa        S C  S s s    s      ss      S  a s   w    w S S  a Ss  ss   S      w S     SS     S CC  w      w    S   C       a C         s                  Sa a  a  S       @   a   w  CC s  a    sw  S  s   S      s a  s    w  a  w  C  S   w  a          C      C      a w  C       a a  w w wsS   C   s a  C w    SC        a     C       s      S          aC     s        wa      SC  w ss       w s    Ca     as S   s       C      C   w w    S  S    Ss   a     w        a SC CC    aC    C  s   s   S   C  S           as    s    C CC a      aa Cs  wa C C    C        a       S     C   aa      S S  s               w ss  S  a   a           S  as   S s        a C       a       s    a   C a  w      C    C       s   sS      S w   S w   w C     s         SC > ss        C|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 805
ace_score 4025
size 805, 1
stairs 792, 0

warrior 214, 0, :east

unit :archer, 3, 0, :east
unit :sludge, 6, 0, :east
unit :archer, 7, 0, :east
unit :thick_sludge, 9, 0, :east
unit :archer, 10, 0, :east
unit :sludge, 15, 0, :east
unit :captive, 17, 0, :east
unit :sludge, 18, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 24, 0, :east
unit :archer, 25, 0, :east
unit :captive, 40, 0, :east
unit :sludge, 42, 0, :east
unit :captive, 43, 0, :east
unit :archer, 44, 0, :east
unit :thick_sludge, 53, 0, :east
unit :captive, 55, 0, :east
unit :thick_sludge, 58, 0, :east
unit :sludge, 60, 0, :east
unit :sludge, 62, 0, :east
unit :sludge, 67, 0, :east
unit :sludge, 74, 0, :east
unit :sludge, 75, 0, :east
unit :thick_sludge, 82, 0, :east
unit :archer, 85, 0, :east
unit :sludge, 87, 0, :east
unit :wizard, 91, 0, :east
unit :wizard, 96, 0, :east
unit :thick_sludge, 98, 0, :east
unit :thick_sludge, 100, 0, :east
unit :archer, 103, 0, :east
unit :thick_sludge, 105, 0, :east
unit :sludge, 106, 0, :east
unit :sludge, 109, 0, :east
unit :sludge, 110, 0, :east
unit :thick_sludge, 114, 0, :east
unit :wizard, 121, 0, :east
unit :thick_sludge, 123, 0, :east
unit :thick_sludge, 129, 0, :east
unit :thick_sludge, 130, 0, :east
unit :thick_sludge, 136, 0, :east
unit :captive, 138, 0, :east
unit :captive, 139, 0, :east
unit :wizard, 142, 0, :east
unit :wizard, 149, 0, :east
unit :thick_sludge, 154, 0, :east
unit :captive, 158, 0, :east
unit :archer, 166, 0, :east
unit :captive, 168, 0, :east
unit :sludge, 178, 0, :east
unit :thick_sludge, 197, 0, :east
unit :archer, 198, 0, :east
unit :archer, 200, 0, :east
unit :archer, 203, 0, :east
unit :thick_sludge, 206, 0, :east
unit :archer, 218, 0, :west
unit :wizard, 222, 0, :west
unit :captive, 225, 0, :west
unit :captive, 226, 0, :west
unit :sludge, 228, 0, :west
unit :archer, 231, 0, :west
unit :sludge, 236, 0, :west
unit :wizard, 237, 0, :west
unit :thick_sludge, 240, 0, :west
unit :sludge, 243, 0, :west
unit :thick_sludge, 247, 0, :west
unit :sludge, 254, 0, :west
unit :archer, 256, 0, :west
unit :sludge, 259, 0, :west
unit :wizard, 264, 0, :west
unit :archer, 267, 0, :west
unit :wizard, 270, 0, :west
unit :captive, 273, 0, :west
unit :thick_sludge, 276, 0, :west
unit :wizard, 280, 0, :west
unit :archer, 283, 0, :west
unit :captive, 294, 0, :west
unit :captive, 301, 0, :west
unit :archer, 308, 0, :west
unit :wizard, 310, 0, :west
unit :captive, 313, 0, :west
unit :archer, 321, 0, :west
unit :archer, 323, 0, :west
unit :wizard, 326, 0, :west
unit :wizard, 328, 0, :west
unit :wizard, 330, 0, :west
unit :sludge, 331, 0, :west
unit :thick_sludge, 332, 0, :west
unit :captive, 336, 0, :west
unit :sludge, 340, 0, :west
unit :archer, 342, 0, :west
unit :captive, 345, 0, :west
unit :wizard, 347, 0, :west
unit :thick_sludge, 352, 0, :west
unit :captive, 353, 0, :west
unit :archer, 362, 0, :west
unit :captive, 368, 0, :west
unit :sludge, 376, 0, :west
unit :thick_sludge, 383, 0, :west
unit :archer, 394, 0, :west
unit :captive, 395, 0, :west
unit :sludge, 401, 0, :west
unit :wizard, 410, 0, :west
unit :archer, 411, 0, :west
unit :thick_sludge, 418, 0, :west
unit :captive, 419, 0, :west
unit :wizard, 422, 0, :west
unit :sludge, 424, 0, :west
unit :sludge, 425, 0, :west
unit :wizard, 433, 0, :west
unit :sludge, 435, 0, :west
unit :captive, 440, 0, :west
unit :archer, 441, 0, :west
unit :archer, 447, 0, :west
unit :sludge, 448, 0, :west
unit :thick_sludge, 450, 0, :west
unit :sludge, 454, 0, :west
unit :captive, 462, 0, :west
unit :captive, 469, 0, :west
unit :wizard, 473, 0, :west
unit :wizard, 475, 0, :west
unit :thick_sludge, 480, 0, :west
unit :thick_sludge, 483, 0, :west
unit :thick_sludge, 488, 0, :west
unit :sludge, 489, 0, :west
unit :archer, 493, 0, :west
unit :wizard, 499, 0, :west
unit :archer, 508, 0, :west
unit :thick_sludge, 510, 0, :west
unit :captive, 511, 0, :west
unit :captive, 513, 0, :west
unit :captive, 514, 0, :west
unit :archer, 519, 0, :west
unit :captive, 520, 0, :west
unit :captive, 525, 0, :west
unit :sludge, 528, 0, :west
unit :sludge, 532, 0, :west
unit :thick_sludge, 536, 0, :west
unit :captive, 540, 0, :west
unit :thick_sludge, 543, 0, :west
unit :archer, 555, 0, :west
unit :sludge, 556, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 566, 0, :west
unit :captive, 568, 0, :west
unit :captive, 569, 0, :west
unit :archer, 571, 0, :west
unit :archer, 578, 0, :west
unit :archer, 579, 0, :west
unit :captive, 581, 0, :west
unit :sludge, 582, 0, :west
unit :wizard, 585, 0, :west
unit :archer, 586, 0, :west
unit :captive, 588, 0, :west
unit :captive, 590, 0, :west
unit :captive, 595, 0, :west
unit :archer, 604, 0, :west
unit :thick_sludge, 612, 0, :west
unit :captive, 618, 0, :west
unit :archer, 622, 0, :west
unit :archer, 623, 0, :west
unit :thick_sludge, 630, 0, :west
unit :thick_sludge, 632, 0, :west
unit :sludge, 635, 0, :west
unit :wizard, 651, 0, :west
unit :sludge, 653, 0, :west
unit :sludge, 654, 0, :west
unit :thick_sludge, 657, 0, :west
unit :archer, 660, 0, :west
unit :archer, 664, 0, :west
unit :thick_sludge, 676, 0, :west
unit :archer, 679, 0, :west
unit :sludge, 680, 0, :west
unit :thick_sludge, 684, 0, :west
unit :sludge, 686, 0, :west
unit :archer, 695, 0, :west
unit :captive, 697, 0, :west
unit :archer, 705, 0, :west
unit :sludge, 713, 0, :west
unit :archer, 718, 0, :west
unit :captive, 722, 0, :west
unit :archer, 724, 0, :west
unit :wizard, 727, 0, :west
unit :captive, 734, 0, :west
unit :captive, 739, 0, :west
unit :sludge, 747, 0, :west
unit :sludge, 751, 0, :west
unit :thick_sludge, 752, 0, :west
unit :thick_sludge, 759, 0, :west
unit :wizard, 761, 0, :west
unit :thick_sludge, 765, 0, :west
unit :wizard, 767, 0, :west
unit :wizard, 771, 0, :west
unit :captive, 773, 0, :west
unit :sludge, 779, 0, :west
unit :thick_sludge, 789, 0, :west
unit :captive, 790, 0, :west
unit :sludge, 794, 0, :west
unit :sludge, 795, 0, :west
unit :captive, 804, 0, :west
