#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      aw                w     a        w a C w    a        s     a  w sa   S    S s   S w      asa    S w    awa    as s    w CC  C a  s        a  a        a sCw  C  w     C   w  s S    sS    C s  a       a w sa    a s       S       C         S S       s    Cw w      a    @     Sa    w s C      w a w    a  S w  C C      w    s      w    w  C s    a w  w  S   w    a   aw  s   w S  s a          a     a C    w S   C  w w   S S     S a  C S s    a>    as  w             s a          s a  sC     a             a      C     sa  Sa S S  s   S s     s      a  s S             as    a   swS S     S    C  s               aC S     S|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 626
ace_score 3130
size 626, 1
stairs 447, 0

warrior 273, 0, :east

unit :archer, 6, 0, :east
unit :wizard, 7, 0, :east
unit :wizard, 24, 0, :east
unit :archer, 30, 0, :east
unit :wizard, 39, 0, :east
unit :archer, 41, 0, :east
unit :captive, 43, 0, :east
unit :wizard, 45, 0, :east
unit :archer, 50, 0, :east
unit :sludge, 59, 0, :east
unit :archer, 65, 0, :east
unit :wizard, 68, 0, :east
unit :sludge, 70, 0, :east
unit :archer, 71, 0, :east
unit :thick_sludge, 75, 0, :east
unit :thick_sludge, 80, 0, :east
unit :sludge, 82, 0, :east
unit :thick_sludge, 86, 0, :east
unit :wizard, 88, 0, :east
unit :archer, 95, 0, :east
unit :sludge, 96, 0, :east
unit :archer, 97, 0, :east
unit :thick_sludge, 102, 0, :east
unit :wizard, 104, 0, :east
unit :archer, 109, 0, :east
unit :wizard, 110, 0, :east
unit :archer, 111, 0, :east
unit :archer, 116, 0, :east
unit :sludge, 117, 0, :east
unit :sludge, 119, 0, :east
unit :wizard, 124, 0, :east
unit :captive, 126, 0, :east
unit :captive, 127, 0, :east
unit :captive, 130, 0, :east
unit :archer, 132, 0, :east
unit :sludge, 135, 0, :east
unit :archer, 144, 0, :east
unit :archer, 147, 0, :east
unit :archer, 156, 0, :east
unit :sludge, 158, 0, :east
unit :captive, 159, 0, :east
unit :wizard, 160, 0, :east
unit :captive, 163, 0, :east
unit :wizard, 166, 0, :east
unit :captive, 172, 0, :east
unit :wizard, 176, 0, :east
unit :sludge, 179, 0, :east
unit :thick_sludge, 181, 0, :east
unit :sludge, 186, 0, :east
unit :thick_sludge, 187, 0, :east
unit :captive, 192, 0, :east
unit :sludge, 194, 0, :east
unit :archer, 197, 0, :east
unit :archer, 205, 0, :east
unit :wizard, 207, 0, :east
unit :sludge, 209, 0, :east
unit :archer, 210, 0, :east
unit :archer, 215, 0, :east
unit :sludge, 217, 0, :east
unit :thick_sludge, 225, 0, :east
unit :captive, 233, 0, :east
unit :thick_sludge, 243, 0, :east
unit :thick_sludge, 245, 0, :east
unit :sludge, 253, 0, :east
unit :captive, 258, 0, :east
unit :wizard, 259, 0, :east
unit :wizard, 261, 0, :east
unit :archer, 268, 0, :east
unit :thick_sludge, 279, 0, :west
unit :archer, 280, 0, :west
unit :wizard, 285, 0, :west
unit :sludge, 287, 0, :west
unit :captive, 289, 0, :west
unit :wizard, 296, 0, :west
unit :archer, 298, 0, :west
unit :wizard, 300, 0, :west
unit :archer, 305, 0, :west
unit :thick_sludge, 308, 0, :west
unit :wizard, 310, 0, :west
unit :captive, 313, 0, :west
unit :captive, 315, 0, :west
unit :wizard, 322, 0, :west
unit :sludge, 327, 0, :west
unit :wizard, 334, 0, :west
unit :wizard, 339, 0, :west
unit :captive, 342, 0, :west
unit :sludge, 344, 0, :west
unit :archer, 349, 0, :west
unit :wizard, 351, 0, :west
unit :wizard, 354, 0, :west
unit :thick_sludge, 357, 0, :west
unit :wizard, 361, 0, :west
unit :archer, 366, 0, :west
unit :archer, 370, 0, :west
unit :wizard, 371, 0, :west
unit :sludge, 374, 0, :west
unit :wizard, 378, 0, :west
unit :thick_sludge, 380, 0, :west
unit :sludge, 383, 0, :west
unit :archer, 385, 0, :west
unit :archer, 396, 0, :west
unit :archer, 402, 0, :west
unit :captive, 404, 0, :west
unit :wizard, 409, 0, :west
unit :thick_sludge, 411, 0, :west
unit :captive, 415, 0, :west
unit :wizard, 418, 0, :west
unit :wizard, 420, 0, :west
unit :thick_sludge, 424, 0, :west
unit :thick_sludge, 426, 0, :west
unit :thick_sludge, 432, 0, :west
unit :archer, 434, 0, :west
unit :captive, 437, 0, :west
unit :thick_sludge, 439, 0, :west
unit :sludge, 441, 0, :west
unit :archer, 446, 0, :west
unit :archer, 452, 0, :west
unit :sludge, 453, 0, :west
unit :wizard, 456, 0, :west
unit :sludge, 470, 0, :west
unit :archer, 472, 0, :west
unit :sludge, 483, 0, :west
unit :archer, 485, 0, :west
unit :sludge, 488, 0, :west
unit :captive, 489, 0, :west
unit :archer, 495, 0, :west
unit :archer, 509, 0, :west
unit :captive, 516, 0, :west
unit :sludge, 522, 0, :west
unit :archer, 523, 0, :west
unit :thick_sludge, 526, 0, :west
unit :archer, 527, 0, :west
unit :thick_sludge, 529, 0, :west
unit :thick_sludge, 531, 0, :west
unit :sludge, 534, 0, :west
unit :thick_sludge, 538, 0, :west
unit :sludge, 540, 0, :west
unit :sludge, 546, 0, :west
unit :archer, 553, 0, :west
unit :sludge, 556, 0, :west
unit :thick_sludge, 558, 0, :west
unit :archer, 572, 0, :west
unit :sludge, 573, 0, :west
unit :archer, 578, 0, :west
unit :sludge, 582, 0, :west
unit :wizard, 583, 0, :west
unit :thick_sludge, 584, 0, :west
unit :thick_sludge, 586, 0, :west
unit :thick_sludge, 592, 0, :west
unit :captive, 597, 0, :west
unit :sludge, 600, 0, :west
unit :archer, 616, 0, :west
unit :captive, 617, 0, :west
unit :thick_sludge, 619, 0, :west
unit :thick_sludge, 625, 0, :west
