#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | a s    S  a    C          w              s S         w  S S    a            C      S s    s sw       w S C  a  C      a        C    S       @   a   sC w C     w   a    wss       a   s w         S  C  s  w a     a >  S   w  CaC C  ss            Ca  s aaC ss SS  SaSC   CC            s    S       a    s     a    a w       Ca     s Sw      C aa ss       a s                   asSw  CSS a  Ca s      a C  s w    SC        s  s           s sC      w      S w  aS S     C     S    C w   sS      s      s  aC  S    S S   S   s CSw  S      C        C            w  aC s    ss  sS       a w    s         a a      w     a    C  C    sa  S        C      CC   S  S    s S s  s     |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 671
ace_score 3355
size 671, 1
stairs 214, 0

warrior 141, 0, :east

unit :archer, 1, 0, :east
unit :sludge, 3, 0, :east
unit :thick_sludge, 8, 0, :east
unit :archer, 11, 0, :east
unit :captive, 16, 0, :east
unit :wizard, 27, 0, :east
unit :sludge, 42, 0, :east
unit :thick_sludge, 44, 0, :east
unit :wizard, 54, 0, :east
unit :thick_sludge, 57, 0, :east
unit :thick_sludge, 59, 0, :east
unit :archer, 64, 0, :east
unit :captive, 77, 0, :east
unit :thick_sludge, 84, 0, :east
unit :sludge, 86, 0, :east
unit :sludge, 91, 0, :east
unit :sludge, 93, 0, :east
unit :wizard, 94, 0, :east
unit :wizard, 102, 0, :east
unit :thick_sludge, 104, 0, :east
unit :captive, 106, 0, :east
unit :archer, 109, 0, :east
unit :captive, 112, 0, :east
unit :archer, 119, 0, :east
unit :captive, 128, 0, :east
unit :thick_sludge, 133, 0, :east
unit :archer, 145, 0, :west
unit :sludge, 149, 0, :west
unit :captive, 150, 0, :west
unit :wizard, 152, 0, :west
unit :captive, 154, 0, :west
unit :wizard, 160, 0, :west
unit :archer, 164, 0, :west
unit :wizard, 169, 0, :west
unit :sludge, 170, 0, :west
unit :sludge, 171, 0, :west
unit :archer, 179, 0, :west
unit :sludge, 183, 0, :west
unit :wizard, 185, 0, :west
unit :thick_sludge, 195, 0, :west
unit :captive, 198, 0, :west
unit :sludge, 201, 0, :west
unit :wizard, 204, 0, :west
unit :archer, 206, 0, :west
unit :archer, 212, 0, :west
unit :thick_sludge, 217, 0, :west
unit :wizard, 221, 0, :west
unit :captive, 224, 0, :west
unit :archer, 225, 0, :west
unit :captive, 226, 0, :west
unit :captive, 228, 0, :west
unit :sludge, 231, 0, :west
unit :sludge, 232, 0, :west
unit :captive, 245, 0, :west
unit :archer, 246, 0, :west
unit :sludge, 249, 0, :west
unit :archer, 251, 0, :west
unit :archer, 252, 0, :west
unit :captive, 253, 0, :west
unit :sludge, 255, 0, :west
unit :sludge, 256, 0, :west
unit :thick_sludge, 258, 0, :west
unit :thick_sludge, 259, 0, :west
unit :thick_sludge, 262, 0, :west
unit :archer, 263, 0, :west
unit :thick_sludge, 264, 0, :west
unit :captive, 265, 0, :west
unit :captive, 269, 0, :west
unit :captive, 270, 0, :west
unit :sludge, 283, 0, :west
unit :thick_sludge, 288, 0, :west
unit :archer, 296, 0, :west
unit :sludge, 301, 0, :west
unit :archer, 307, 0, :west
unit :archer, 312, 0, :west
unit :wizard, 314, 0, :west
unit :captive, 322, 0, :west
unit :archer, 323, 0, :west
unit :sludge, 329, 0, :west
unit :thick_sludge, 331, 0, :west
unit :wizard, 332, 0, :west
unit :captive, 339, 0, :west
unit :archer, 341, 0, :west
unit :archer, 342, 0, :west
unit :sludge, 344, 0, :west
unit :sludge, 345, 0, :west
unit :archer, 353, 0, :west
unit :sludge, 355, 0, :west
unit :archer, 375, 0, :west
unit :sludge, 376, 0, :west
unit :thick_sludge, 377, 0, :west
unit :wizard, 378, 0, :west
unit :captive, 381, 0, :west
unit :thick_sludge, 382, 0, :west
unit :thick_sludge, 383, 0, :west
unit :archer, 385, 0, :west
unit :captive, 388, 0, :west
unit :archer, 389, 0, :west
unit :sludge, 391, 0, :west
unit :archer, 398, 0, :west
unit :captive, 400, 0, :west
unit :sludge, 403, 0, :west
unit :wizard, 405, 0, :west
unit :thick_sludge, 410, 0, :west
unit :captive, 411, 0, :west
unit :sludge, 420, 0, :west
unit :sludge, 423, 0, :west
unit :sludge, 435, 0, :west
unit :sludge, 437, 0, :west
unit :captive, 438, 0, :west
unit :wizard, 445, 0, :west
unit :thick_sludge, 452, 0, :west
unit :wizard, 454, 0, :west
unit :archer, 457, 0, :west
unit :thick_sludge, 458, 0, :west
unit :thick_sludge, 460, 0, :west
unit :captive, 466, 0, :west
unit :thick_sludge, 472, 0, :west
unit :captive, 477, 0, :west
unit :wizard, 479, 0, :west
unit :sludge, 483, 0, :west
unit :thick_sludge, 484, 0, :west
unit :sludge, 491, 0, :west
unit :sludge, 498, 0, :west
unit :archer, 501, 0, :west
unit :captive, 502, 0, :west
unit :thick_sludge, 505, 0, :west
unit :thick_sludge, 510, 0, :west
unit :thick_sludge, 512, 0, :west
unit :thick_sludge, 516, 0, :west
unit :sludge, 520, 0, :west
unit :captive, 522, 0, :west
unit :thick_sludge, 523, 0, :west
unit :wizard, 524, 0, :west
unit :thick_sludge, 527, 0, :west
unit :captive, 534, 0, :west
unit :captive, 543, 0, :west
unit :wizard, 556, 0, :west
unit :archer, 559, 0, :west
unit :captive, 560, 0, :west
unit :sludge, 562, 0, :west
unit :sludge, 567, 0, :west
unit :sludge, 568, 0, :west
unit :sludge, 571, 0, :west
unit :thick_sludge, 572, 0, :west
unit :archer, 580, 0, :west
unit :wizard, 582, 0, :west
unit :sludge, 587, 0, :west
unit :archer, 597, 0, :west
unit :archer, 599, 0, :west
unit :wizard, 606, 0, :west
unit :archer, 612, 0, :west
unit :captive, 617, 0, :west
unit :captive, 620, 0, :west
unit :sludge, 625, 0, :west
unit :archer, 626, 0, :west
unit :thick_sludge, 629, 0, :west
unit :captive, 638, 0, :west
unit :captive, 645, 0, :west
unit :captive, 646, 0, :west
unit :thick_sludge, 650, 0, :west
unit :thick_sludge, 653, 0, :west
unit :sludge, 658, 0, :west
unit :thick_sludge, 660, 0, :west
unit :sludge, 662, 0, :west
unit :sludge, 665, 0, :west
