#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C a   a s    C   CC  a   s    >        S  w w w Ss   S     ws  C            s s  w SC w  C              S   w w s Ss    @  C     S   CS  as  S a Sa        s  w   SS  C    C  s  SC  w          a  SS      wSa     S  SC       C w  s aC         S     a                   C   a   w     s   wa  s   w     as    a  S S w  a    aS          s    a  a C           a       a  C  S   S        s    a   C w w  CSa ss  C as C      S wa     s       Ca        S    C    a      S w    C C Cw    aC   S  Ca a  C   a  w  SC         S  S      s      s  S  S         s          w  S     S         s  a        a  s w  S   a        Sa   a s            C C   S    s  C   aaaas        s  s  w a w   C     S  w   w       s    s        S  s w       C  w S     S C     C     a      C           CC       s SS s   S      C w   a w  w    S        Ss    Sa a  s s s    S w  w        S  s   w     w        S  a       CS  w C  CS s  S    CS   s C  s       w   a S   wS    S    w     S        |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 958
ace_score 4790
size 958, 1
stairs 30, 0

warrior 120, 0, :east

unit :captive, 0, 0, :east
unit :archer, 2, 0, :east
unit :archer, 6, 0, :east
unit :sludge, 8, 0, :east
unit :captive, 13, 0, :east
unit :captive, 17, 0, :east
unit :captive, 18, 0, :east
unit :archer, 21, 0, :east
unit :sludge, 25, 0, :east
unit :thick_sludge, 39, 0, :east
unit :wizard, 42, 0, :east
unit :wizard, 44, 0, :east
unit :wizard, 46, 0, :east
unit :thick_sludge, 48, 0, :east
unit :sludge, 49, 0, :east
unit :thick_sludge, 53, 0, :east
unit :wizard, 59, 0, :east
unit :sludge, 60, 0, :east
unit :captive, 63, 0, :east
unit :sludge, 76, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 81, 0, :east
unit :thick_sludge, 83, 0, :east
unit :captive, 84, 0, :east
unit :wizard, 86, 0, :east
unit :captive, 89, 0, :east
unit :thick_sludge, 104, 0, :east
unit :wizard, 108, 0, :east
unit :wizard, 110, 0, :east
unit :sludge, 112, 0, :east
unit :thick_sludge, 114, 0, :east
unit :sludge, 115, 0, :east
unit :captive, 123, 0, :west
unit :thick_sludge, 129, 0, :west
unit :captive, 133, 0, :west
unit :thick_sludge, 134, 0, :west
unit :archer, 137, 0, :west
unit :sludge, 138, 0, :west
unit :thick_sludge, 141, 0, :west
unit :archer, 143, 0, :west
unit :thick_sludge, 145, 0, :west
unit :archer, 146, 0, :west
unit :sludge, 155, 0, :west
unit :wizard, 158, 0, :west
unit :thick_sludge, 162, 0, :west
unit :thick_sludge, 163, 0, :west
unit :captive, 166, 0, :west
unit :captive, 171, 0, :west
unit :sludge, 174, 0, :west
unit :thick_sludge, 177, 0, :west
unit :captive, 178, 0, :west
unit :wizard, 181, 0, :west
unit :archer, 192, 0, :west
unit :thick_sludge, 195, 0, :west
unit :thick_sludge, 196, 0, :west
unit :wizard, 203, 0, :west
unit :thick_sludge, 204, 0, :west
unit :archer, 205, 0, :west
unit :thick_sludge, 211, 0, :west
unit :thick_sludge, 214, 0, :west
unit :captive, 215, 0, :west
unit :captive, 223, 0, :west
unit :wizard, 225, 0, :west
unit :sludge, 228, 0, :west
unit :archer, 230, 0, :west
unit :captive, 231, 0, :west
unit :thick_sludge, 241, 0, :west
unit :archer, 247, 0, :west
unit :captive, 267, 0, :west
unit :archer, 271, 0, :west
unit :wizard, 275, 0, :west
unit :sludge, 281, 0, :west
unit :wizard, 285, 0, :west
unit :archer, 286, 0, :west
unit :sludge, 289, 0, :west
unit :wizard, 293, 0, :west
unit :archer, 299, 0, :west
unit :sludge, 300, 0, :west
unit :archer, 305, 0, :west
unit :thick_sludge, 308, 0, :west
unit :thick_sludge, 310, 0, :west
unit :wizard, 312, 0, :west
unit :archer, 315, 0, :west
unit :archer, 320, 0, :west
unit :thick_sludge, 321, 0, :west
unit :sludge, 332, 0, :west
unit :archer, 337, 0, :west
unit :archer, 340, 0, :west
unit :captive, 342, 0, :west
unit :archer, 354, 0, :west
unit :archer, 362, 0, :west
unit :captive, 365, 0, :west
unit :thick_sludge, 368, 0, :west
unit :thick_sludge, 372, 0, :west
unit :sludge, 381, 0, :west
unit :archer, 386, 0, :west
unit :captive, 390, 0, :west
unit :wizard, 392, 0, :west
unit :wizard, 394, 0, :west
unit :captive, 397, 0, :west
unit :thick_sludge, 398, 0, :west
unit :archer, 399, 0, :west
unit :sludge, 401, 0, :west
unit :sludge, 402, 0, :west
unit :captive, 405, 0, :west
unit :archer, 407, 0, :west
unit :sludge, 408, 0, :west
unit :captive, 410, 0, :west
unit :thick_sludge, 417, 0, :west
unit :wizard, 419, 0, :west
unit :archer, 420, 0, :west
unit :sludge, 426, 0, :west
unit :captive, 434, 0, :west
unit :archer, 435, 0, :west
unit :thick_sludge, 444, 0, :west
unit :captive, 449, 0, :west
unit :archer, 454, 0, :west
unit :thick_sludge, 461, 0, :west
unit :wizard, 463, 0, :west
unit :captive, 468, 0, :west
unit :captive, 470, 0, :west
unit :captive, 472, 0, :west
unit :wizard, 473, 0, :west
unit :archer, 478, 0, :west
unit :captive, 479, 0, :west
unit :thick_sludge, 483, 0, :west
unit :captive, 486, 0, :west
unit :archer, 487, 0, :west
unit :archer, 489, 0, :west
unit :captive, 492, 0, :west
unit :archer, 496, 0, :west
unit :wizard, 499, 0, :west
unit :thick_sludge, 502, 0, :west
unit :captive, 503, 0, :west
unit :thick_sludge, 513, 0, :west
unit :thick_sludge, 516, 0, :west
unit :sludge, 523, 0, :west
unit :sludge, 530, 0, :west
unit :thick_sludge, 533, 0, :west
unit :thick_sludge, 536, 0, :west
unit :sludge, 546, 0, :west
unit :wizard, 557, 0, :west
unit :thick_sludge, 560, 0, :west
unit :thick_sludge, 566, 0, :west
unit :sludge, 576, 0, :west
unit :archer, 579, 0, :west
unit :archer, 588, 0, :west
unit :sludge, 591, 0, :west
unit :wizard, 593, 0, :west
unit :thick_sludge, 596, 0, :west
unit :archer, 600, 0, :west
unit :thick_sludge, 609, 0, :west
unit :archer, 610, 0, :west
unit :archer, 614, 0, :west
unit :sludge, 616, 0, :west
unit :captive, 629, 0, :west
unit :captive, 631, 0, :west
unit :thick_sludge, 635, 0, :west
unit :sludge, 640, 0, :west
unit :captive, 643, 0, :west
unit :archer, 647, 0, :west
unit :archer, 648, 0, :west
unit :archer, 649, 0, :west
unit :archer, 650, 0, :west
unit :sludge, 651, 0, :west
unit :sludge, 660, 0, :west
unit :sludge, 663, 0, :west
unit :wizard, 666, 0, :west
unit :archer, 668, 0, :west
unit :wizard, 670, 0, :west
unit :captive, 674, 0, :west
unit :thick_sludge, 680, 0, :west
unit :wizard, 683, 0, :west
unit :wizard, 687, 0, :west
unit :sludge, 695, 0, :west
unit :sludge, 700, 0, :west
unit :thick_sludge, 709, 0, :west
unit :sludge, 712, 0, :west
unit :wizard, 714, 0, :west
unit :captive, 722, 0, :west
unit :wizard, 725, 0, :west
unit :thick_sludge, 727, 0, :west
unit :thick_sludge, 733, 0, :west
unit :captive, 735, 0, :west
unit :captive, 741, 0, :west
unit :archer, 747, 0, :west
unit :captive, 754, 0, :west
unit :captive, 766, 0, :west
unit :captive, 767, 0, :west
unit :sludge, 775, 0, :west
unit :thick_sludge, 777, 0, :west
unit :thick_sludge, 778, 0, :west
unit :sludge, 780, 0, :west
unit :thick_sludge, 784, 0, :west
unit :captive, 791, 0, :west
unit :wizard, 793, 0, :west
unit :archer, 797, 0, :west
unit :wizard, 799, 0, :west
unit :wizard, 802, 0, :west
unit :thick_sludge, 807, 0, :west
unit :thick_sludge, 816, 0, :west
unit :sludge, 817, 0, :west
unit :thick_sludge, 822, 0, :west
unit :archer, 823, 0, :west
unit :archer, 825, 0, :west
unit :sludge, 828, 0, :west
unit :sludge, 830, 0, :west
unit :sludge, 832, 0, :west
unit :thick_sludge, 837, 0, :west
unit :wizard, 839, 0, :west
unit :wizard, 842, 0, :west
unit :thick_sludge, 851, 0, :west
unit :sludge, 854, 0, :west
unit :wizard, 858, 0, :west
unit :wizard, 864, 0, :west
unit :thick_sludge, 873, 0, :west
unit :archer, 876, 0, :west
unit :captive, 884, 0, :west
unit :thick_sludge, 885, 0, :west
unit :wizard, 888, 0, :west
unit :captive, 890, 0, :west
unit :captive, 893, 0, :west
unit :thick_sludge, 894, 0, :west
unit :sludge, 896, 0, :west
unit :thick_sludge, 899, 0, :west
unit :captive, 904, 0, :west
unit :thick_sludge, 905, 0, :west
unit :sludge, 909, 0, :west
unit :captive, 911, 0, :west
unit :sludge, 914, 0, :west
unit :wizard, 922, 0, :west
unit :archer, 926, 0, :west
unit :thick_sludge, 928, 0, :west
unit :wizard, 932, 0, :west
unit :thick_sludge, 933, 0, :west
unit :thick_sludge, 938, 0, :west
unit :wizard, 943, 0, :west
unit :thick_sludge, 949, 0, :west
