#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  ss s       aS  C    a      S     s     a s              s  S   w   s   a   Cw  w     s   aa      C     CS      S CC  C   C  sC      s C  w  w     SS   wa   aSC  aS     sS   C             a     aa      w     w w w  aaS s  S        C   a      w  a w    a  a     S  C a w  C>w  a as  C   w     S     s  C    w  C Ca          aa     S S      a    s     a      Ss   C    w               w  ss  w s  w    C         C   C     C    S    s w       C    Sa  C       s             ss S          Sa a  s    s CSass    C      S     w    w   s      Sa  C Ss s       s   Sa      s S Cs           Cs S s        C                       s SS sa  w  @  w a       S               sC s     C Cw SSa C      w       w  s  s   S    Sa        C     S      Cs s          s   C  Ca  S         s S w   aC  wC   w S  S S |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 794
ace_score 3970
size 794, 1
stairs 273, 0

warrior 633, 0, :east

unit :sludge, 2, 0, :east
unit :sludge, 3, 0, :east
unit :sludge, 5, 0, :east
unit :archer, 13, 0, :east
unit :thick_sludge, 14, 0, :east
unit :captive, 17, 0, :east
unit :archer, 22, 0, :east
unit :thick_sludge, 29, 0, :east
unit :sludge, 35, 0, :east
unit :archer, 41, 0, :east
unit :sludge, 43, 0, :east
unit :sludge, 58, 0, :east
unit :thick_sludge, 61, 0, :east
unit :wizard, 65, 0, :east
unit :sludge, 69, 0, :east
unit :archer, 73, 0, :east
unit :captive, 77, 0, :east
unit :wizard, 78, 0, :east
unit :wizard, 81, 0, :east
unit :sludge, 87, 0, :east
unit :archer, 91, 0, :east
unit :archer, 92, 0, :east
unit :captive, 99, 0, :east
unit :captive, 105, 0, :east
unit :thick_sludge, 106, 0, :east
unit :thick_sludge, 113, 0, :east
unit :captive, 115, 0, :east
unit :captive, 116, 0, :east
unit :captive, 119, 0, :east
unit :captive, 123, 0, :east
unit :sludge, 126, 0, :east
unit :captive, 127, 0, :east
unit :sludge, 134, 0, :east
unit :captive, 136, 0, :east
unit :wizard, 139, 0, :east
unit :wizard, 142, 0, :east
unit :thick_sludge, 148, 0, :east
unit :thick_sludge, 149, 0, :east
unit :wizard, 153, 0, :east
unit :archer, 154, 0, :east
unit :archer, 158, 0, :east
unit :thick_sludge, 159, 0, :east
unit :captive, 160, 0, :east
unit :archer, 163, 0, :east
unit :thick_sludge, 164, 0, :east
unit :sludge, 170, 0, :east
unit :thick_sludge, 171, 0, :east
unit :captive, 175, 0, :east
unit :archer, 189, 0, :east
unit :archer, 195, 0, :east
unit :archer, 196, 0, :east
unit :wizard, 203, 0, :east
unit :wizard, 209, 0, :east
unit :wizard, 211, 0, :east
unit :wizard, 213, 0, :east
unit :archer, 216, 0, :east
unit :archer, 217, 0, :east
unit :thick_sludge, 218, 0, :east
unit :sludge, 220, 0, :east
unit :thick_sludge, 223, 0, :east
unit :captive, 232, 0, :east
unit :archer, 236, 0, :east
unit :wizard, 243, 0, :east
unit :archer, 246, 0, :east
unit :wizard, 248, 0, :east
unit :archer, 253, 0, :east
unit :archer, 256, 0, :east
unit :thick_sludge, 262, 0, :east
unit :captive, 265, 0, :east
unit :archer, 267, 0, :east
unit :wizard, 269, 0, :east
unit :captive, 272, 0, :east
unit :wizard, 274, 0, :east
unit :archer, 277, 0, :east
unit :archer, 279, 0, :east
unit :sludge, 280, 0, :east
unit :captive, 283, 0, :east
unit :wizard, 287, 0, :east
unit :thick_sludge, 293, 0, :east
unit :sludge, 299, 0, :east
unit :captive, 302, 0, :east
unit :wizard, 307, 0, :east
unit :captive, 310, 0, :east
unit :captive, 312, 0, :east
unit :archer, 313, 0, :east
unit :archer, 324, 0, :east
unit :archer, 325, 0, :east
unit :thick_sludge, 331, 0, :east
unit :thick_sludge, 333, 0, :east
unit :archer, 340, 0, :east
unit :sludge, 345, 0, :east
unit :archer, 351, 0, :east
unit :thick_sludge, 358, 0, :east
unit :sludge, 359, 0, :east
unit :captive, 363, 0, :east
unit :wizard, 368, 0, :east
unit :wizard, 384, 0, :east
unit :sludge, 387, 0, :east
unit :sludge, 388, 0, :east
unit :wizard, 391, 0, :east
unit :sludge, 393, 0, :east
unit :wizard, 396, 0, :east
unit :captive, 401, 0, :east
unit :captive, 411, 0, :east
unit :captive, 415, 0, :east
unit :captive, 421, 0, :east
unit :thick_sludge, 426, 0, :east
unit :sludge, 431, 0, :east
unit :wizard, 433, 0, :east
unit :captive, 441, 0, :east
unit :thick_sludge, 446, 0, :east
unit :archer, 447, 0, :east
unit :captive, 450, 0, :east
unit :sludge, 458, 0, :east
unit :sludge, 472, 0, :east
unit :sludge, 473, 0, :east
unit :thick_sludge, 475, 0, :east
unit :thick_sludge, 486, 0, :east
unit :archer, 487, 0, :east
unit :archer, 489, 0, :east
unit :sludge, 492, 0, :east
unit :sludge, 497, 0, :east
unit :captive, 499, 0, :east
unit :thick_sludge, 500, 0, :east
unit :archer, 501, 0, :east
unit :sludge, 502, 0, :east
unit :sludge, 503, 0, :east
unit :captive, 508, 0, :east
unit :thick_sludge, 515, 0, :east
unit :wizard, 521, 0, :east
unit :wizard, 526, 0, :east
unit :sludge, 530, 0, :east
unit :thick_sludge, 537, 0, :east
unit :archer, 538, 0, :east
unit :captive, 541, 0, :east
unit :thick_sludge, 543, 0, :east
unit :sludge, 544, 0, :east
unit :sludge, 546, 0, :east
unit :sludge, 554, 0, :east
unit :thick_sludge, 558, 0, :east
unit :archer, 559, 0, :east
unit :sludge, 566, 0, :east
unit :thick_sludge, 568, 0, :east
unit :captive, 570, 0, :east
unit :sludge, 571, 0, :east
unit :captive, 583, 0, :east
unit :sludge, 584, 0, :east
unit :thick_sludge, 586, 0, :east
unit :sludge, 588, 0, :east
unit :captive, 597, 0, :east
unit :sludge, 621, 0, :east
unit :thick_sludge, 623, 0, :east
unit :thick_sludge, 624, 0, :east
unit :sludge, 626, 0, :east
unit :archer, 627, 0, :east
unit :wizard, 630, 0, :east
unit :wizard, 636, 0, :west
unit :archer, 638, 0, :west
unit :thick_sludge, 646, 0, :west
unit :sludge, 662, 0, :west
unit :captive, 663, 0, :west
unit :sludge, 665, 0, :west
unit :captive, 671, 0, :west
unit :captive, 673, 0, :west
unit :wizard, 674, 0, :west
unit :thick_sludge, 676, 0, :west
unit :thick_sludge, 677, 0, :west
unit :archer, 678, 0, :west
unit :captive, 680, 0, :west
unit :wizard, 687, 0, :west
unit :wizard, 695, 0, :west
unit :sludge, 698, 0, :west
unit :sludge, 701, 0, :west
unit :thick_sludge, 705, 0, :west
unit :thick_sludge, 710, 0, :west
unit :archer, 711, 0, :west
unit :captive, 720, 0, :west
unit :thick_sludge, 726, 0, :west
unit :captive, 733, 0, :west
unit :sludge, 734, 0, :west
unit :sludge, 736, 0, :west
unit :sludge, 747, 0, :west
unit :captive, 751, 0, :west
unit :captive, 754, 0, :west
unit :archer, 755, 0, :west
unit :thick_sludge, 758, 0, :west
unit :sludge, 768, 0, :west
unit :thick_sludge, 770, 0, :west
unit :wizard, 772, 0, :west
unit :archer, 776, 0, :west
unit :captive, 777, 0, :west
unit :wizard, 780, 0, :west
unit :captive, 781, 0, :west
unit :wizard, 785, 0, :west
unit :thick_sludge, 787, 0, :west
unit :thick_sludge, 790, 0, :west
unit :thick_sludge, 792, 0, :west
