#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     S w   s C   s       w>w     s      CC  S   a    C    C  C                Sa   a      w      w     s  C  w sw s  C     S  C   a  s S  w    a    s             a    sSs  a   a        CSs        S CC   SC   SS w  w  Sw a                 C        s    asS    s    CSS  a   aS  w   a  @       a       C        S            C S s    w  as  a w  C C   s s         S C C s a s    w     a  a CS ss  C CSw       C s S ss CS s      s      CsS            Ca    Ca w s  s            w  s          C   a        s       a  s         w       s        a   a     Cw        a  a  C a           aa  s  aa S Cw       C      S C  s     s Saa  w a  s        w       a   w     C       sa          S  C   C      w    s  s    S     S C   C s Ss         w      S  a   s   C   C s  s a    C  Ss C S  a C C   a   C sa      C      a    w CS             a    s sS      w S        S w C       s   C     C    a     as s    Csa       s S CCws    a  S  S     |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 928
ace_score 4640
size 928, 1
stairs 26, 0

warrior 284, 0, :east

unit :thick_sludge, 5, 0, :east
unit :wizard, 7, 0, :east
unit :sludge, 11, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 17, 0, :east
unit :wizard, 25, 0, :east
unit :wizard, 27, 0, :east
unit :sludge, 33, 0, :east
unit :captive, 40, 0, :east
unit :captive, 41, 0, :east
unit :thick_sludge, 44, 0, :east
unit :archer, 48, 0, :east
unit :captive, 53, 0, :east
unit :captive, 58, 0, :east
unit :captive, 61, 0, :east
unit :thick_sludge, 78, 0, :east
unit :archer, 79, 0, :east
unit :archer, 83, 0, :east
unit :wizard, 90, 0, :east
unit :wizard, 97, 0, :east
unit :sludge, 103, 0, :east
unit :captive, 106, 0, :east
unit :wizard, 109, 0, :east
unit :sludge, 111, 0, :east
unit :wizard, 112, 0, :east
unit :sludge, 114, 0, :east
unit :captive, 117, 0, :east
unit :thick_sludge, 123, 0, :east
unit :captive, 126, 0, :east
unit :archer, 130, 0, :east
unit :sludge, 133, 0, :east
unit :thick_sludge, 135, 0, :east
unit :wizard, 138, 0, :east
unit :archer, 143, 0, :east
unit :sludge, 148, 0, :east
unit :archer, 162, 0, :east
unit :sludge, 167, 0, :east
unit :thick_sludge, 168, 0, :east
unit :sludge, 169, 0, :east
unit :archer, 172, 0, :east
unit :archer, 176, 0, :east
unit :captive, 185, 0, :east
unit :thick_sludge, 186, 0, :east
unit :sludge, 187, 0, :east
unit :thick_sludge, 196, 0, :east
unit :captive, 198, 0, :east
unit :captive, 199, 0, :east
unit :thick_sludge, 203, 0, :east
unit :captive, 204, 0, :east
unit :thick_sludge, 208, 0, :east
unit :thick_sludge, 209, 0, :east
unit :wizard, 211, 0, :east
unit :wizard, 214, 0, :east
unit :thick_sludge, 217, 0, :east
unit :wizard, 218, 0, :east
unit :archer, 220, 0, :east
unit :captive, 238, 0, :east
unit :sludge, 247, 0, :east
unit :archer, 252, 0, :east
unit :sludge, 253, 0, :east
unit :thick_sludge, 254, 0, :east
unit :sludge, 259, 0, :east
unit :captive, 264, 0, :east
unit :thick_sludge, 265, 0, :east
unit :thick_sludge, 266, 0, :east
unit :archer, 269, 0, :east
unit :archer, 273, 0, :east
unit :thick_sludge, 274, 0, :east
unit :wizard, 277, 0, :east
unit :archer, 281, 0, :east
unit :archer, 292, 0, :west
unit :captive, 300, 0, :west
unit :thick_sludge, 309, 0, :west
unit :captive, 322, 0, :west
unit :thick_sludge, 324, 0, :west
unit :sludge, 326, 0, :west
unit :wizard, 331, 0, :west
unit :archer, 334, 0, :west
unit :sludge, 335, 0, :west
unit :archer, 338, 0, :west
unit :wizard, 340, 0, :west
unit :captive, 343, 0, :west
unit :captive, 345, 0, :west
unit :sludge, 349, 0, :west
unit :sludge, 351, 0, :west
unit :thick_sludge, 361, 0, :west
unit :captive, 363, 0, :west
unit :captive, 365, 0, :west
unit :sludge, 367, 0, :west
unit :archer, 369, 0, :west
unit :sludge, 371, 0, :west
unit :wizard, 376, 0, :west
unit :archer, 382, 0, :west
unit :archer, 385, 0, :west
unit :captive, 387, 0, :west
unit :thick_sludge, 388, 0, :west
unit :sludge, 390, 0, :west
unit :sludge, 391, 0, :west
unit :captive, 394, 0, :west
unit :captive, 396, 0, :west
unit :thick_sludge, 397, 0, :west
unit :wizard, 398, 0, :west
unit :captive, 406, 0, :west
unit :sludge, 408, 0, :west
unit :thick_sludge, 410, 0, :west
unit :sludge, 412, 0, :west
unit :sludge, 413, 0, :west
unit :captive, 415, 0, :west
unit :thick_sludge, 416, 0, :west
unit :sludge, 418, 0, :west
unit :sludge, 425, 0, :west
unit :captive, 432, 0, :west
unit :sludge, 433, 0, :west
unit :thick_sludge, 434, 0, :west
unit :captive, 447, 0, :west
unit :archer, 448, 0, :west
unit :captive, 453, 0, :west
unit :archer, 454, 0, :west
unit :wizard, 456, 0, :west
unit :sludge, 458, 0, :west
unit :sludge, 461, 0, :west
unit :wizard, 474, 0, :west
unit :sludge, 477, 0, :west
unit :captive, 488, 0, :west
unit :archer, 492, 0, :west
unit :sludge, 501, 0, :west
unit :archer, 509, 0, :west
unit :sludge, 512, 0, :west
unit :wizard, 522, 0, :west
unit :sludge, 530, 0, :west
unit :archer, 539, 0, :west
unit :archer, 543, 0, :west
unit :captive, 549, 0, :west
unit :wizard, 550, 0, :west
unit :archer, 559, 0, :west
unit :archer, 562, 0, :west
unit :captive, 565, 0, :west
unit :archer, 567, 0, :west
unit :archer, 579, 0, :west
unit :archer, 580, 0, :west
unit :sludge, 583, 0, :west
unit :archer, 586, 0, :west
unit :archer, 587, 0, :west
unit :thick_sludge, 589, 0, :west
unit :captive, 591, 0, :west
unit :wizard, 592, 0, :west
unit :captive, 600, 0, :west
unit :thick_sludge, 607, 0, :west
unit :captive, 609, 0, :west
unit :sludge, 612, 0, :west
unit :sludge, 618, 0, :west
unit :thick_sludge, 620, 0, :west
unit :archer, 621, 0, :west
unit :archer, 622, 0, :west
unit :wizard, 625, 0, :west
unit :archer, 627, 0, :west
unit :sludge, 630, 0, :west
unit :wizard, 639, 0, :west
unit :archer, 647, 0, :west
unit :wizard, 651, 0, :west
unit :captive, 657, 0, :west
unit :sludge, 665, 0, :west
unit :archer, 666, 0, :west
unit :thick_sludge, 677, 0, :west
unit :captive, 680, 0, :west
unit :captive, 684, 0, :west
unit :wizard, 691, 0, :west
unit :sludge, 696, 0, :west
unit :sludge, 699, 0, :west
unit :thick_sludge, 704, 0, :west
unit :thick_sludge, 710, 0, :west
unit :captive, 712, 0, :west
unit :captive, 716, 0, :west
unit :sludge, 718, 0, :west
unit :thick_sludge, 720, 0, :west
unit :sludge, 721, 0, :west
unit :wizard, 731, 0, :west
unit :thick_sludge, 738, 0, :west
unit :archer, 741, 0, :west
unit :sludge, 745, 0, :west
unit :captive, 749, 0, :west
unit :captive, 753, 0, :west
unit :sludge, 755, 0, :west
unit :sludge, 758, 0, :west
unit :archer, 760, 0, :west
unit :captive, 765, 0, :west
unit :thick_sludge, 768, 0, :west
unit :sludge, 769, 0, :west
unit :captive, 771, 0, :west
unit :thick_sludge, 773, 0, :west
unit :archer, 776, 0, :west
unit :captive, 778, 0, :west
unit :captive, 780, 0, :west
unit :archer, 784, 0, :west
unit :captive, 788, 0, :west
unit :sludge, 790, 0, :west
unit :archer, 791, 0, :west
unit :captive, 798, 0, :west
unit :archer, 805, 0, :west
unit :wizard, 810, 0, :west
unit :captive, 812, 0, :west
unit :thick_sludge, 813, 0, :west
unit :archer, 827, 0, :west
unit :sludge, 832, 0, :west
unit :sludge, 834, 0, :west
unit :thick_sludge, 835, 0, :west
unit :wizard, 842, 0, :west
unit :thick_sludge, 844, 0, :west
unit :thick_sludge, 853, 0, :west
unit :wizard, 855, 0, :west
unit :captive, 857, 0, :west
unit :sludge, 865, 0, :west
unit :captive, 869, 0, :west
unit :captive, 875, 0, :west
unit :archer, 880, 0, :west
unit :archer, 886, 0, :west
unit :sludge, 887, 0, :west
unit :sludge, 889, 0, :west
unit :captive, 894, 0, :west
unit :sludge, 895, 0, :west
unit :archer, 896, 0, :west
unit :sludge, 904, 0, :west
unit :thick_sludge, 906, 0, :west
unit :captive, 908, 0, :west
unit :captive, 909, 0, :west
unit :wizard, 910, 0, :west
unit :sludge, 911, 0, :west
unit :archer, 916, 0, :west
unit :thick_sludge, 919, 0, :west
unit :thick_sludge, 922, 0, :west
