#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     C  a  s       S a  aCw w   s a  w  aw w      C         w               w    a S           s s        a C      C  C  C    C C aa   SC  sw       s a   >swa a as  s    s    aS C       aC      s    Ca  Sa   S w w   s w       S s w C    sC as    SwC    a Ss a            SsS w    C          a S               S    C       a  s s         a  S  SC  w  C      s      a      C w         w S  S   w  a                C  S    s          s      a            w w   s   SC       SC     S             ss Ca a           Ca S  w  S   SSSC C    C a     S  aa          SwsC    w        C         s     as C  S  aC w  a  S   aa  a w      a      a a   w      a  sasSa  s    S  w    a w   s      C            Ca        a s s  C     a       C s  s Cs  S a C   Sw        a   C  a      S  Cs   S    C    s   a    a      w aa         a           @   S w a a sC   C      s   w     C  s w Cw  w    w      a  w   a C  w   S C                w  wC           C S s  w  S     SC    S  a s wS    a  s         |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 981
ace_score 4905
size 981, 1
stairs 154, 0

warrior 825, 0, :east

unit :captive, 5, 0, :east
unit :archer, 8, 0, :east
unit :sludge, 11, 0, :east
unit :thick_sludge, 19, 0, :east
unit :archer, 21, 0, :east
unit :archer, 24, 0, :east
unit :captive, 25, 0, :east
unit :wizard, 26, 0, :east
unit :wizard, 28, 0, :east
unit :sludge, 32, 0, :east
unit :archer, 34, 0, :east
unit :wizard, 37, 0, :east
unit :archer, 40, 0, :east
unit :wizard, 41, 0, :east
unit :wizard, 43, 0, :east
unit :captive, 50, 0, :east
unit :wizard, 60, 0, :east
unit :wizard, 76, 0, :east
unit :archer, 81, 0, :east
unit :thick_sludge, 83, 0, :east
unit :sludge, 95, 0, :east
unit :sludge, 97, 0, :east
unit :archer, 106, 0, :east
unit :captive, 108, 0, :east
unit :captive, 115, 0, :east
unit :captive, 118, 0, :east
unit :captive, 121, 0, :east
unit :captive, 126, 0, :east
unit :captive, 128, 0, :east
unit :archer, 130, 0, :east
unit :archer, 131, 0, :east
unit :thick_sludge, 135, 0, :east
unit :captive, 136, 0, :east
unit :sludge, 139, 0, :east
unit :wizard, 140, 0, :east
unit :sludge, 148, 0, :east
unit :archer, 150, 0, :east
unit :sludge, 155, 0, :east
unit :wizard, 156, 0, :east
unit :archer, 157, 0, :east
unit :archer, 159, 0, :east
unit :archer, 161, 0, :east
unit :sludge, 162, 0, :east
unit :sludge, 165, 0, :east
unit :sludge, 170, 0, :east
unit :archer, 175, 0, :east
unit :thick_sludge, 176, 0, :east
unit :captive, 178, 0, :east
unit :archer, 186, 0, :east
unit :captive, 187, 0, :east
unit :sludge, 194, 0, :east
unit :captive, 199, 0, :east
unit :archer, 200, 0, :east
unit :thick_sludge, 203, 0, :east
unit :archer, 204, 0, :east
unit :thick_sludge, 208, 0, :east
unit :wizard, 210, 0, :east
unit :wizard, 212, 0, :east
unit :sludge, 216, 0, :east
unit :wizard, 218, 0, :east
unit :thick_sludge, 226, 0, :east
unit :sludge, 228, 0, :east
unit :wizard, 230, 0, :east
unit :captive, 232, 0, :east
unit :sludge, 237, 0, :east
unit :captive, 238, 0, :east
unit :archer, 240, 0, :east
unit :sludge, 241, 0, :east
unit :thick_sludge, 246, 0, :east
unit :wizard, 247, 0, :east
unit :captive, 248, 0, :east
unit :archer, 253, 0, :east
unit :thick_sludge, 255, 0, :east
unit :sludge, 256, 0, :east
unit :archer, 258, 0, :east
unit :thick_sludge, 271, 0, :east
unit :sludge, 272, 0, :east
unit :thick_sludge, 273, 0, :east
unit :wizard, 275, 0, :east
unit :captive, 280, 0, :east
unit :archer, 291, 0, :east
unit :thick_sludge, 293, 0, :east
unit :thick_sludge, 309, 0, :east
unit :captive, 314, 0, :east
unit :archer, 322, 0, :east
unit :sludge, 325, 0, :east
unit :sludge, 327, 0, :east
unit :archer, 337, 0, :east
unit :thick_sludge, 340, 0, :east
unit :thick_sludge, 343, 0, :east
unit :captive, 344, 0, :east
unit :wizard, 347, 0, :east
unit :captive, 350, 0, :east
unit :sludge, 357, 0, :east
unit :archer, 364, 0, :east
unit :captive, 371, 0, :east
unit :wizard, 373, 0, :east
unit :wizard, 383, 0, :east
unit :thick_sludge, 385, 0, :east
unit :thick_sludge, 388, 0, :east
unit :wizard, 392, 0, :east
unit :archer, 395, 0, :east
unit :captive, 412, 0, :east
unit :thick_sludge, 415, 0, :east
unit :sludge, 420, 0, :east
unit :sludge, 431, 0, :east
unit :archer, 438, 0, :east
unit :wizard, 451, 0, :east
unit :wizard, 453, 0, :east
unit :sludge, 457, 0, :east
unit :thick_sludge, 461, 0, :east
unit :captive, 462, 0, :east
unit :thick_sludge, 470, 0, :east
unit :captive, 471, 0, :east
unit :thick_sludge, 477, 0, :east
unit :sludge, 491, 0, :east
unit :sludge, 492, 0, :east
unit :captive, 494, 0, :east
unit :archer, 495, 0, :east
unit :archer, 497, 0, :east
unit :captive, 509, 0, :east
unit :archer, 510, 0, :east
unit :thick_sludge, 512, 0, :east
unit :wizard, 515, 0, :east
unit :thick_sludge, 518, 0, :east
unit :thick_sludge, 522, 0, :east
unit :thick_sludge, 523, 0, :east
unit :thick_sludge, 524, 0, :east
unit :captive, 525, 0, :east
unit :captive, 527, 0, :east
unit :captive, 532, 0, :east
unit :archer, 534, 0, :east
unit :thick_sludge, 540, 0, :east
unit :archer, 543, 0, :east
unit :archer, 544, 0, :east
unit :thick_sludge, 555, 0, :east
unit :wizard, 556, 0, :east
unit :sludge, 557, 0, :east
unit :captive, 558, 0, :east
unit :wizard, 563, 0, :east
unit :captive, 572, 0, :east
unit :sludge, 582, 0, :east
unit :archer, 588, 0, :east
unit :sludge, 589, 0, :east
unit :captive, 591, 0, :east
unit :thick_sludge, 594, 0, :east
unit :archer, 597, 0, :east
unit :captive, 598, 0, :east
unit :wizard, 600, 0, :east
unit :archer, 603, 0, :east
unit :thick_sludge, 606, 0, :east
unit :archer, 610, 0, :east
unit :archer, 611, 0, :east
unit :archer, 614, 0, :east
unit :wizard, 616, 0, :east
unit :archer, 623, 0, :east
unit :archer, 630, 0, :east
unit :archer, 632, 0, :east
unit :wizard, 636, 0, :east
unit :archer, 643, 0, :east
unit :sludge, 646, 0, :east
unit :archer, 647, 0, :east
unit :sludge, 648, 0, :east
unit :thick_sludge, 649, 0, :east
unit :archer, 650, 0, :east
unit :sludge, 653, 0, :east
unit :thick_sludge, 658, 0, :east
unit :wizard, 661, 0, :east
unit :archer, 666, 0, :east
unit :wizard, 668, 0, :east
unit :sludge, 672, 0, :east
unit :captive, 679, 0, :east
unit :captive, 692, 0, :east
unit :archer, 693, 0, :east
unit :archer, 702, 0, :east
unit :sludge, 704, 0, :east
unit :sludge, 706, 0, :east
unit :captive, 709, 0, :east
unit :archer, 715, 0, :east
unit :captive, 723, 0, :east
unit :sludge, 725, 0, :east
unit :sludge, 728, 0, :east
unit :captive, 730, 0, :east
unit :sludge, 731, 0, :east
unit :thick_sludge, 734, 0, :east
unit :archer, 736, 0, :east
unit :captive, 738, 0, :east
unit :thick_sludge, 742, 0, :east
unit :wizard, 743, 0, :east
unit :archer, 752, 0, :east
unit :captive, 756, 0, :east
unit :archer, 759, 0, :east
unit :thick_sludge, 766, 0, :east
unit :captive, 769, 0, :east
unit :sludge, 770, 0, :east
unit :thick_sludge, 774, 0, :east
unit :captive, 779, 0, :east
unit :sludge, 784, 0, :east
unit :archer, 788, 0, :east
unit :archer, 793, 0, :east
unit :wizard, 800, 0, :east
unit :archer, 802, 0, :east
unit :archer, 803, 0, :east
unit :archer, 813, 0, :east
unit :thick_sludge, 829, 0, :west
unit :wizard, 831, 0, :west
unit :archer, 833, 0, :west
unit :archer, 835, 0, :west
unit :sludge, 837, 0, :west
unit :captive, 838, 0, :west
unit :captive, 842, 0, :west
unit :sludge, 849, 0, :west
unit :wizard, 853, 0, :west
unit :captive, 859, 0, :west
unit :sludge, 862, 0, :west
unit :wizard, 864, 0, :west
unit :captive, 866, 0, :west
unit :wizard, 867, 0, :west
unit :wizard, 870, 0, :west
unit :wizard, 875, 0, :west
unit :archer, 882, 0, :west
unit :wizard, 885, 0, :west
unit :archer, 889, 0, :west
unit :captive, 891, 0, :west
unit :wizard, 894, 0, :west
unit :thick_sludge, 898, 0, :west
unit :captive, 900, 0, :west
unit :wizard, 917, 0, :west
unit :wizard, 920, 0, :west
unit :captive, 921, 0, :west
unit :captive, 933, 0, :west
unit :thick_sludge, 935, 0, :west
unit :sludge, 937, 0, :west
unit :wizard, 940, 0, :west
unit :thick_sludge, 943, 0, :west
unit :thick_sludge, 949, 0, :west
unit :captive, 950, 0, :west
unit :thick_sludge, 955, 0, :west
unit :archer, 958, 0, :west
unit :sludge, 960, 0, :west
unit :wizard, 962, 0, :west
unit :thick_sludge, 963, 0, :west
unit :archer, 968, 0, :west
unit :sludge, 971, 0, :west
