#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C         ss       s      ss        C s   C Cs     C     s      w        wC    sCw      a       S   S      sS  s  a     C  a C > a           a     w       S w   C a  S        C  w     C  C         s  w              C      w  a    a S   s  sw  a  SS C       S wC  C     aC  a   S      w  C    aa      ssSCC    w    S C  a     S     C        s  Ss    a      w a w  a C a    sa           S    s     a C      s       C  s  C  a   s       S    @    a w      a Ca S S s S   a C    a             w  a  wCS s  a   C     C  S C   aw   C    S   a S w  Sa     sa    s s  C      C S               C     sa     w SC s    CssCaa   Ca      S SS  sS    s      ss         a s   Sa C    s   a     a            sC a      |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 702
ace_score 3510
size 702, 1
stairs 127, 0

warrior 439, 0, :east

unit :captive, 0, 0, :east
unit :sludge, 10, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 19, 0, :east
unit :sludge, 26, 0, :east
unit :sludge, 27, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 38, 0, :east
unit :captive, 42, 0, :east
unit :captive, 44, 0, :east
unit :sludge, 45, 0, :east
unit :captive, 51, 0, :east
unit :sludge, 57, 0, :east
unit :wizard, 64, 0, :east
unit :wizard, 73, 0, :east
unit :captive, 74, 0, :east
unit :sludge, 79, 0, :east
unit :captive, 80, 0, :east
unit :wizard, 81, 0, :east
unit :archer, 88, 0, :east
unit :thick_sludge, 96, 0, :east
unit :thick_sludge, 100, 0, :east
unit :sludge, 107, 0, :east
unit :thick_sludge, 108, 0, :east
unit :sludge, 111, 0, :east
unit :archer, 114, 0, :east
unit :captive, 120, 0, :east
unit :archer, 123, 0, :east
unit :captive, 125, 0, :east
unit :archer, 129, 0, :east
unit :archer, 141, 0, :east
unit :wizard, 147, 0, :east
unit :thick_sludge, 155, 0, :east
unit :wizard, 157, 0, :east
unit :captive, 161, 0, :east
unit :archer, 163, 0, :east
unit :thick_sludge, 166, 0, :east
unit :captive, 175, 0, :east
unit :wizard, 178, 0, :east
unit :captive, 184, 0, :east
unit :captive, 187, 0, :east
unit :sludge, 197, 0, :east
unit :wizard, 200, 0, :east
unit :captive, 215, 0, :east
unit :wizard, 222, 0, :east
unit :archer, 225, 0, :east
unit :archer, 230, 0, :east
unit :thick_sludge, 232, 0, :east
unit :sludge, 236, 0, :east
unit :sludge, 239, 0, :east
unit :wizard, 240, 0, :east
unit :archer, 243, 0, :east
unit :thick_sludge, 246, 0, :east
unit :thick_sludge, 247, 0, :east
unit :captive, 249, 0, :east
unit :thick_sludge, 257, 0, :east
unit :wizard, 259, 0, :east
unit :captive, 260, 0, :east
unit :captive, 263, 0, :east
unit :archer, 269, 0, :east
unit :captive, 270, 0, :east
unit :archer, 273, 0, :east
unit :thick_sludge, 277, 0, :east
unit :wizard, 284, 0, :east
unit :captive, 287, 0, :east
unit :archer, 292, 0, :east
unit :archer, 293, 0, :east
unit :sludge, 300, 0, :east
unit :sludge, 301, 0, :east
unit :thick_sludge, 302, 0, :east
unit :captive, 303, 0, :east
unit :captive, 304, 0, :east
unit :wizard, 309, 0, :east
unit :thick_sludge, 314, 0, :east
unit :captive, 316, 0, :east
unit :archer, 319, 0, :east
unit :thick_sludge, 325, 0, :east
unit :captive, 331, 0, :east
unit :sludge, 340, 0, :east
unit :thick_sludge, 343, 0, :east
unit :sludge, 344, 0, :east
unit :archer, 349, 0, :east
unit :wizard, 356, 0, :east
unit :archer, 358, 0, :east
unit :wizard, 360, 0, :east
unit :archer, 363, 0, :east
unit :captive, 365, 0, :east
unit :archer, 367, 0, :east
unit :sludge, 372, 0, :east
unit :archer, 373, 0, :east
unit :thick_sludge, 385, 0, :east
unit :sludge, 390, 0, :east
unit :archer, 396, 0, :east
unit :captive, 398, 0, :east
unit :sludge, 405, 0, :east
unit :captive, 413, 0, :east
unit :sludge, 416, 0, :east
unit :captive, 419, 0, :east
unit :archer, 422, 0, :east
unit :sludge, 426, 0, :east
unit :thick_sludge, 434, 0, :east
unit :archer, 444, 0, :west
unit :wizard, 446, 0, :west
unit :archer, 453, 0, :west
unit :captive, 455, 0, :west
unit :archer, 456, 0, :west
unit :thick_sludge, 458, 0, :west
unit :thick_sludge, 460, 0, :west
unit :sludge, 462, 0, :west
unit :thick_sludge, 464, 0, :west
unit :archer, 468, 0, :west
unit :captive, 470, 0, :west
unit :archer, 475, 0, :west
unit :wizard, 489, 0, :west
unit :archer, 492, 0, :west
unit :wizard, 495, 0, :west
unit :captive, 496, 0, :west
unit :thick_sludge, 497, 0, :west
unit :sludge, 499, 0, :west
unit :archer, 502, 0, :west
unit :captive, 506, 0, :west
unit :captive, 512, 0, :west
unit :thick_sludge, 515, 0, :west
unit :captive, 517, 0, :west
unit :archer, 521, 0, :west
unit :wizard, 522, 0, :west
unit :captive, 526, 0, :west
unit :thick_sludge, 531, 0, :west
unit :archer, 535, 0, :west
unit :thick_sludge, 537, 0, :west
unit :wizard, 539, 0, :west
unit :thick_sludge, 542, 0, :west
unit :archer, 543, 0, :west
unit :sludge, 549, 0, :west
unit :archer, 550, 0, :west
unit :sludge, 555, 0, :west
unit :sludge, 557, 0, :west
unit :captive, 560, 0, :west
unit :captive, 567, 0, :west
unit :thick_sludge, 569, 0, :west
unit :captive, 585, 0, :west
unit :sludge, 591, 0, :west
unit :archer, 592, 0, :west
unit :wizard, 598, 0, :west
unit :thick_sludge, 600, 0, :west
unit :captive, 601, 0, :west
unit :sludge, 603, 0, :west
unit :captive, 608, 0, :west
unit :sludge, 609, 0, :west
unit :sludge, 610, 0, :west
unit :captive, 611, 0, :west
unit :archer, 612, 0, :west
unit :archer, 613, 0, :west
unit :captive, 617, 0, :west
unit :archer, 618, 0, :west
unit :thick_sludge, 625, 0, :west
unit :thick_sludge, 627, 0, :west
unit :thick_sludge, 628, 0, :west
unit :sludge, 631, 0, :west
unit :thick_sludge, 632, 0, :west
unit :sludge, 637, 0, :west
unit :sludge, 644, 0, :west
unit :sludge, 645, 0, :west
unit :archer, 655, 0, :west
unit :sludge, 657, 0, :west
unit :thick_sludge, 661, 0, :west
unit :archer, 662, 0, :west
unit :captive, 664, 0, :west
unit :sludge, 669, 0, :west
unit :archer, 673, 0, :west
unit :archer, 679, 0, :west
unit :sludge, 692, 0, :west
unit :captive, 693, 0, :west
unit :archer, 695, 0, :west
