#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S C C           C       CaS  s   S    w   S s  as  s         w   C   C S            w        a S  S s as S   a   w    S   C  w     C      a                S           S S   s   S SwSS   s   CC   @           C      aS  a                  aC w SC   a    a   a    a   C      S     s   S           C C          C w            S    Sw    s w a  s       w      C   Cs   a   aS    CC S  s  S ss   C    aSSw  a S a                           C w         w        S   C Ss    CS  w  C       w   Ca C   a  ws  ss  s    aS C a  S  S       S  CC> a    s   a     S sS      C     w    sa    C        aCSS  S  s   C    s       awS  S  Ca w S   C aa     ssC S    S       s       w w    ss C s  C  Ss   s w s    S CS   S S       s w   w  asC        S     a    s     s        SC     wa        a         a   Cs     aa        a a     w S   SS w     w  SC    a    w s w    s           C    s  s        a         s S   S  a   a             S Cs       CSCaS       w  as w   a   C|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 955
ace_score 4775
size 955, 1
stairs 532, 0

warrior 195, 0, :east

unit :thick_sludge, 0, 0, :east
unit :captive, 2, 0, :east
unit :captive, 4, 0, :east
unit :captive, 16, 0, :east
unit :captive, 24, 0, :east
unit :archer, 25, 0, :east
unit :thick_sludge, 26, 0, :east
unit :sludge, 29, 0, :east
unit :thick_sludge, 33, 0, :east
unit :wizard, 38, 0, :east
unit :thick_sludge, 42, 0, :east
unit :sludge, 44, 0, :east
unit :archer, 47, 0, :east
unit :sludge, 48, 0, :east
unit :sludge, 51, 0, :east
unit :wizard, 61, 0, :east
unit :captive, 65, 0, :east
unit :captive, 69, 0, :east
unit :thick_sludge, 71, 0, :east
unit :wizard, 84, 0, :east
unit :archer, 93, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 98, 0, :east
unit :sludge, 100, 0, :east
unit :archer, 102, 0, :east
unit :sludge, 103, 0, :east
unit :thick_sludge, 105, 0, :east
unit :archer, 109, 0, :east
unit :wizard, 113, 0, :east
unit :thick_sludge, 118, 0, :east
unit :captive, 122, 0, :east
unit :wizard, 125, 0, :east
unit :captive, 131, 0, :east
unit :archer, 138, 0, :east
unit :thick_sludge, 155, 0, :east
unit :thick_sludge, 167, 0, :east
unit :thick_sludge, 169, 0, :east
unit :sludge, 173, 0, :east
unit :thick_sludge, 177, 0, :east
unit :thick_sludge, 179, 0, :east
unit :wizard, 180, 0, :east
unit :thick_sludge, 181, 0, :east
unit :thick_sludge, 182, 0, :east
unit :sludge, 186, 0, :east
unit :captive, 190, 0, :east
unit :captive, 191, 0, :east
unit :captive, 207, 0, :west
unit :archer, 214, 0, :west
unit :thick_sludge, 215, 0, :west
unit :archer, 218, 0, :west
unit :archer, 237, 0, :west
unit :captive, 238, 0, :west
unit :wizard, 240, 0, :west
unit :thick_sludge, 242, 0, :west
unit :captive, 243, 0, :west
unit :archer, 247, 0, :west
unit :archer, 252, 0, :west
unit :archer, 256, 0, :west
unit :archer, 261, 0, :west
unit :captive, 265, 0, :west
unit :thick_sludge, 272, 0, :west
unit :sludge, 278, 0, :west
unit :thick_sludge, 282, 0, :west
unit :captive, 294, 0, :west
unit :captive, 296, 0, :west
unit :captive, 307, 0, :west
unit :wizard, 309, 0, :west
unit :thick_sludge, 322, 0, :west
unit :thick_sludge, 327, 0, :west
unit :wizard, 328, 0, :west
unit :sludge, 333, 0, :west
unit :wizard, 335, 0, :west
unit :archer, 337, 0, :west
unit :sludge, 340, 0, :west
unit :wizard, 348, 0, :west
unit :captive, 355, 0, :west
unit :captive, 359, 0, :west
unit :sludge, 360, 0, :west
unit :archer, 364, 0, :west
unit :archer, 368, 0, :west
unit :thick_sludge, 369, 0, :west
unit :captive, 374, 0, :west
unit :captive, 375, 0, :west
unit :thick_sludge, 377, 0, :west
unit :sludge, 380, 0, :west
unit :thick_sludge, 383, 0, :west
unit :sludge, 385, 0, :west
unit :sludge, 386, 0, :west
unit :captive, 390, 0, :west
unit :archer, 395, 0, :west
unit :thick_sludge, 396, 0, :west
unit :thick_sludge, 397, 0, :west
unit :wizard, 398, 0, :west
unit :archer, 401, 0, :west
unit :thick_sludge, 403, 0, :west
unit :archer, 405, 0, :west
unit :captive, 433, 0, :west
unit :wizard, 435, 0, :west
unit :wizard, 445, 0, :west
unit :thick_sludge, 454, 0, :west
unit :captive, 458, 0, :west
unit :thick_sludge, 460, 0, :west
unit :sludge, 461, 0, :west
unit :captive, 466, 0, :west
unit :thick_sludge, 467, 0, :west
unit :wizard, 470, 0, :west
unit :captive, 473, 0, :west
unit :wizard, 481, 0, :west
unit :captive, 485, 0, :west
unit :archer, 486, 0, :west
unit :captive, 488, 0, :west
unit :archer, 492, 0, :west
unit :wizard, 495, 0, :west
unit :sludge, 496, 0, :west
unit :sludge, 499, 0, :west
unit :sludge, 500, 0, :west
unit :sludge, 503, 0, :west
unit :archer, 508, 0, :west
unit :thick_sludge, 509, 0, :west
unit :captive, 511, 0, :west
unit :archer, 513, 0, :west
unit :thick_sludge, 516, 0, :west
unit :thick_sludge, 519, 0, :west
unit :thick_sludge, 527, 0, :west
unit :captive, 530, 0, :west
unit :captive, 531, 0, :west
unit :archer, 534, 0, :west
unit :sludge, 539, 0, :west
unit :archer, 543, 0, :west
unit :thick_sludge, 549, 0, :west
unit :sludge, 551, 0, :west
unit :thick_sludge, 552, 0, :west
unit :captive, 559, 0, :west
unit :wizard, 565, 0, :west
unit :sludge, 570, 0, :west
unit :archer, 571, 0, :west
unit :captive, 576, 0, :west
unit :archer, 585, 0, :west
unit :captive, 586, 0, :west
unit :thick_sludge, 587, 0, :west
unit :thick_sludge, 588, 0, :west
unit :thick_sludge, 591, 0, :west
unit :sludge, 594, 0, :west
unit :captive, 598, 0, :west
unit :sludge, 603, 0, :west
unit :archer, 611, 0, :west
unit :wizard, 612, 0, :west
unit :thick_sludge, 613, 0, :west
unit :thick_sludge, 616, 0, :west
unit :captive, 619, 0, :west
unit :archer, 620, 0, :west
unit :wizard, 622, 0, :west
unit :thick_sludge, 624, 0, :west
unit :captive, 628, 0, :west
unit :archer, 630, 0, :west
unit :archer, 631, 0, :west
unit :sludge, 637, 0, :west
unit :sludge, 638, 0, :west
unit :captive, 639, 0, :west
unit :thick_sludge, 641, 0, :west
unit :thick_sludge, 646, 0, :west
unit :sludge, 654, 0, :west
unit :wizard, 662, 0, :west
unit :wizard, 664, 0, :west
unit :sludge, 669, 0, :west
unit :sludge, 670, 0, :west
unit :captive, 672, 0, :west
unit :sludge, 674, 0, :west
unit :captive, 677, 0, :west
unit :thick_sludge, 680, 0, :west
unit :sludge, 681, 0, :west
unit :sludge, 685, 0, :west
unit :wizard, 687, 0, :west
unit :sludge, 689, 0, :west
unit :thick_sludge, 694, 0, :west
unit :captive, 696, 0, :west
unit :thick_sludge, 697, 0, :west
unit :thick_sludge, 701, 0, :west
unit :thick_sludge, 703, 0, :west
unit :sludge, 711, 0, :west
unit :wizard, 713, 0, :west
unit :wizard, 717, 0, :west
unit :archer, 720, 0, :west
unit :sludge, 721, 0, :west
unit :captive, 722, 0, :west
unit :thick_sludge, 731, 0, :west
unit :archer, 737, 0, :west
unit :sludge, 742, 0, :west
unit :sludge, 748, 0, :west
unit :thick_sludge, 757, 0, :west
unit :captive, 758, 0, :west
unit :wizard, 764, 0, :west
unit :archer, 765, 0, :west
unit :archer, 774, 0, :west
unit :archer, 784, 0, :west
unit :captive, 788, 0, :west
unit :sludge, 789, 0, :west
unit :archer, 795, 0, :west
unit :archer, 796, 0, :west
unit :archer, 805, 0, :west
unit :archer, 807, 0, :west
unit :wizard, 813, 0, :west
unit :thick_sludge, 815, 0, :west
unit :thick_sludge, 819, 0, :west
unit :thick_sludge, 820, 0, :west
unit :wizard, 822, 0, :west
unit :wizard, 828, 0, :west
unit :thick_sludge, 831, 0, :west
unit :captive, 832, 0, :west
unit :archer, 837, 0, :west
unit :wizard, 842, 0, :west
unit :sludge, 844, 0, :west
unit :wizard, 846, 0, :west
unit :sludge, 851, 0, :west
unit :captive, 863, 0, :west
unit :sludge, 868, 0, :west
unit :sludge, 871, 0, :west
unit :archer, 880, 0, :west
unit :sludge, 890, 0, :west
unit :thick_sludge, 892, 0, :west
unit :thick_sludge, 896, 0, :west
unit :archer, 899, 0, :west
unit :archer, 903, 0, :west
unit :thick_sludge, 917, 0, :west
unit :captive, 919, 0, :west
unit :sludge, 920, 0, :west
unit :captive, 928, 0, :west
unit :thick_sludge, 929, 0, :west
unit :captive, 930, 0, :west
unit :archer, 931, 0, :west
unit :thick_sludge, 932, 0, :west
unit :wizard, 940, 0, :west
unit :archer, 943, 0, :west
unit :sludge, 944, 0, :west
unit :wizard, 946, 0, :west
unit :archer, 950, 0, :west
unit :captive, 954, 0, :west
