#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      S    SCs        C      S    a  SS  s  s S S  S   C        S      aSa   a s  a   S aSwSCSs   > w   s  s a        C     S    a  S a         w    a w S    a   w   a  a  s       s a         S              C   S  S  S a    w  a     s    aC  sa    w     wsC    s  w  s w   Ca s     Cs    s w   a  C     w    w S w              w                      S  ss       s    C         C   a s    a C C              S        S  s       s  a       sS      w a ws S a s     C  a  s     C    s   s s     a C S   S      aS  as    a  w    s   C    w      a   wC    S       w C   S  s Cs         aS    s  sCC   w        as w Ss  C              s a C  a  w    aC         C  SsS    S         w  as Cs  s s  s  a  @   wa ws  a S   C   S     C    w  w         sS S       C   sS    CC  w S    s  C a        Sa S     w    Sw Ca  a  S ss   a                C S      s  C      C          w  s       S     C      s|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 890
ace_score 4450
size 890, 1
stairs 98, 0

warrior 696, 0, :east

unit :thick_sludge, 6, 0, :east
unit :thick_sludge, 11, 0, :east
unit :captive, 12, 0, :east
unit :sludge, 13, 0, :east
unit :captive, 22, 0, :east
unit :thick_sludge, 29, 0, :east
unit :archer, 34, 0, :east
unit :thick_sludge, 37, 0, :east
unit :thick_sludge, 38, 0, :east
unit :sludge, 41, 0, :east
unit :sludge, 44, 0, :east
unit :thick_sludge, 46, 0, :east
unit :thick_sludge, 48, 0, :east
unit :thick_sludge, 51, 0, :east
unit :captive, 55, 0, :east
unit :thick_sludge, 64, 0, :east
unit :archer, 71, 0, :east
unit :thick_sludge, 72, 0, :east
unit :archer, 73, 0, :east
unit :archer, 77, 0, :east
unit :sludge, 79, 0, :east
unit :archer, 82, 0, :east
unit :thick_sludge, 86, 0, :east
unit :archer, 88, 0, :east
unit :thick_sludge, 89, 0, :east
unit :wizard, 90, 0, :east
unit :thick_sludge, 91, 0, :east
unit :captive, 92, 0, :east
unit :thick_sludge, 93, 0, :east
unit :sludge, 94, 0, :east
unit :wizard, 100, 0, :east
unit :sludge, 104, 0, :east
unit :sludge, 107, 0, :east
unit :archer, 109, 0, :east
unit :captive, 118, 0, :east
unit :thick_sludge, 124, 0, :east
unit :archer, 129, 0, :east
unit :thick_sludge, 132, 0, :east
unit :archer, 134, 0, :east
unit :wizard, 144, 0, :east
unit :archer, 149, 0, :east
unit :wizard, 151, 0, :east
unit :thick_sludge, 153, 0, :east
unit :archer, 158, 0, :east
unit :wizard, 162, 0, :east
unit :archer, 166, 0, :east
unit :archer, 169, 0, :east
unit :sludge, 172, 0, :east
unit :sludge, 180, 0, :east
unit :archer, 182, 0, :east
unit :thick_sludge, 192, 0, :east
unit :captive, 207, 0, :east
unit :thick_sludge, 211, 0, :east
unit :thick_sludge, 214, 0, :east
unit :thick_sludge, 217, 0, :east
unit :archer, 219, 0, :east
unit :wizard, 224, 0, :east
unit :archer, 227, 0, :east
unit :sludge, 233, 0, :east
unit :archer, 238, 0, :east
unit :captive, 239, 0, :east
unit :sludge, 242, 0, :east
unit :archer, 243, 0, :east
unit :wizard, 248, 0, :east
unit :wizard, 254, 0, :east
unit :sludge, 255, 0, :east
unit :captive, 256, 0, :east
unit :sludge, 261, 0, :east
unit :wizard, 264, 0, :east
unit :sludge, 267, 0, :east
unit :wizard, 269, 0, :east
unit :captive, 273, 0, :east
unit :archer, 274, 0, :east
unit :sludge, 276, 0, :east
unit :captive, 282, 0, :east
unit :sludge, 283, 0, :east
unit :sludge, 288, 0, :east
unit :wizard, 290, 0, :east
unit :archer, 294, 0, :east
unit :captive, 297, 0, :east
unit :wizard, 303, 0, :east
unit :wizard, 308, 0, :east
unit :thick_sludge, 310, 0, :east
unit :wizard, 312, 0, :east
unit :wizard, 327, 0, :east
unit :thick_sludge, 350, 0, :east
unit :sludge, 353, 0, :east
unit :sludge, 354, 0, :east
unit :sludge, 362, 0, :east
unit :captive, 367, 0, :east
unit :captive, 377, 0, :east
unit :archer, 381, 0, :east
unit :sludge, 383, 0, :east
unit :archer, 388, 0, :east
unit :captive, 390, 0, :east
unit :captive, 392, 0, :east
unit :thick_sludge, 407, 0, :east
unit :thick_sludge, 416, 0, :east
unit :sludge, 419, 0, :east
unit :sludge, 427, 0, :east
unit :archer, 430, 0, :east
unit :sludge, 438, 0, :east
unit :thick_sludge, 439, 0, :east
unit :wizard, 446, 0, :east
unit :archer, 448, 0, :east
unit :wizard, 450, 0, :east
unit :sludge, 451, 0, :east
unit :thick_sludge, 453, 0, :east
unit :archer, 455, 0, :east
unit :sludge, 457, 0, :east
unit :captive, 463, 0, :east
unit :archer, 466, 0, :east
unit :sludge, 469, 0, :east
unit :captive, 475, 0, :east
unit :sludge, 480, 0, :east
unit :sludge, 484, 0, :east
unit :sludge, 486, 0, :east
unit :archer, 492, 0, :east
unit :captive, 494, 0, :east
unit :thick_sludge, 496, 0, :east
unit :thick_sludge, 500, 0, :east
unit :archer, 507, 0, :east
unit :thick_sludge, 508, 0, :east
unit :archer, 511, 0, :east
unit :sludge, 512, 0, :east
unit :archer, 517, 0, :east
unit :wizard, 520, 0, :east
unit :sludge, 525, 0, :east
unit :captive, 529, 0, :east
unit :wizard, 534, 0, :east
unit :archer, 541, 0, :east
unit :wizard, 545, 0, :east
unit :captive, 546, 0, :east
unit :thick_sludge, 551, 0, :east
unit :wizard, 559, 0, :east
unit :captive, 561, 0, :east
unit :thick_sludge, 565, 0, :east
unit :sludge, 568, 0, :east
unit :captive, 570, 0, :east
unit :sludge, 571, 0, :east
unit :archer, 581, 0, :east
unit :thick_sludge, 582, 0, :east
unit :sludge, 587, 0, :east
unit :sludge, 590, 0, :east
unit :captive, 591, 0, :east
unit :captive, 592, 0, :east
unit :wizard, 596, 0, :east
unit :archer, 605, 0, :east
unit :sludge, 606, 0, :east
unit :wizard, 608, 0, :east
unit :thick_sludge, 610, 0, :east
unit :sludge, 611, 0, :east
unit :captive, 614, 0, :east
unit :sludge, 629, 0, :east
unit :archer, 631, 0, :east
unit :captive, 633, 0, :east
unit :archer, 636, 0, :east
unit :wizard, 639, 0, :east
unit :archer, 644, 0, :east
unit :captive, 645, 0, :east
unit :captive, 655, 0, :east
unit :thick_sludge, 658, 0, :east
unit :sludge, 659, 0, :east
unit :thick_sludge, 660, 0, :east
unit :thick_sludge, 665, 0, :east
unit :wizard, 675, 0, :east
unit :archer, 678, 0, :east
unit :sludge, 679, 0, :east
unit :captive, 681, 0, :east
unit :sludge, 682, 0, :east
unit :sludge, 685, 0, :east
unit :sludge, 687, 0, :east
unit :sludge, 690, 0, :east
unit :archer, 693, 0, :east
unit :wizard, 700, 0, :west
unit :archer, 701, 0, :west
unit :wizard, 703, 0, :west
unit :sludge, 704, 0, :west
unit :archer, 707, 0, :west
unit :thick_sludge, 709, 0, :west
unit :captive, 713, 0, :west
unit :thick_sludge, 717, 0, :west
unit :captive, 723, 0, :west
unit :wizard, 728, 0, :west
unit :wizard, 731, 0, :west
unit :sludge, 741, 0, :west
unit :thick_sludge, 742, 0, :west
unit :thick_sludge, 744, 0, :west
unit :captive, 752, 0, :west
unit :sludge, 756, 0, :west
unit :thick_sludge, 757, 0, :west
unit :captive, 762, 0, :west
unit :captive, 763, 0, :west
unit :wizard, 766, 0, :west
unit :thick_sludge, 768, 0, :west
unit :sludge, 773, 0, :west
unit :captive, 776, 0, :west
unit :archer, 778, 0, :west
unit :thick_sludge, 787, 0, :west
unit :archer, 788, 0, :west
unit :thick_sludge, 790, 0, :west
unit :wizard, 796, 0, :west
unit :thick_sludge, 801, 0, :west
unit :wizard, 802, 0, :west
unit :captive, 804, 0, :west
unit :archer, 805, 0, :west
unit :archer, 808, 0, :west
unit :thick_sludge, 811, 0, :west
unit :sludge, 813, 0, :west
unit :sludge, 814, 0, :west
unit :archer, 818, 0, :west
unit :captive, 835, 0, :west
unit :thick_sludge, 837, 0, :west
unit :sludge, 844, 0, :west
unit :captive, 847, 0, :west
unit :captive, 854, 0, :west
unit :wizard, 865, 0, :west
unit :sludge, 868, 0, :west
unit :thick_sludge, 876, 0, :west
unit :captive, 882, 0, :west
unit :sludge, 889, 0, :west
