#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  sa    S     S  SS  a        s   S   C a a  a          s   SS                   S          s      s w    a  w     C w  a  S  CC C  a  C    S    S    S s w w  s     S a       s        w a  C  SC     wsw  C C  S   C  C     S   w S        Sa   S a     s     w C    s    w     aS     w          a    a       wC  w    w w  C a  w a    C      CS   Sw ws S  w  w  S     w s        w           C  S     w       a a   C     S  aC w    S        S    s         sS        CCs wa  S Ca   S  s C aSCs  sw     S   S    w  C S  S       C      a a  a   w             wS   a   a w      w  S  S  w      a a w C a    s   S       S       > C S s  s  S         w     s  Ca  S    C s                  S      a   s    a s         w  s  a  aS   s   C  S C   s      S     C S CsS   S aS S      s   a   S  a w     S   w  C       S     CCa SC s a       s    @        C  C  w   S   sa   a   w S        w s      a    a    a       Ss     sC|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 910
ace_score 4550
size 910, 1
stairs 618, 0

warrior 831, 0, :east

unit :sludge, 2, 0, :east
unit :archer, 3, 0, :east
unit :thick_sludge, 8, 0, :east
unit :thick_sludge, 14, 0, :east
unit :thick_sludge, 17, 0, :east
unit :thick_sludge, 18, 0, :east
unit :archer, 21, 0, :east
unit :sludge, 30, 0, :east
unit :thick_sludge, 34, 0, :east
unit :captive, 38, 0, :east
unit :archer, 40, 0, :east
unit :archer, 42, 0, :east
unit :archer, 45, 0, :east
unit :sludge, 56, 0, :east
unit :thick_sludge, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :thick_sludge, 81, 0, :east
unit :sludge, 92, 0, :east
unit :sludge, 99, 0, :east
unit :wizard, 101, 0, :east
unit :archer, 106, 0, :east
unit :wizard, 109, 0, :east
unit :captive, 115, 0, :east
unit :wizard, 117, 0, :east
unit :archer, 120, 0, :east
unit :thick_sludge, 123, 0, :east
unit :captive, 126, 0, :east
unit :captive, 127, 0, :east
unit :captive, 129, 0, :east
unit :archer, 132, 0, :east
unit :captive, 135, 0, :east
unit :thick_sludge, 140, 0, :east
unit :thick_sludge, 145, 0, :east
unit :thick_sludge, 150, 0, :east
unit :sludge, 152, 0, :east
unit :wizard, 154, 0, :east
unit :wizard, 156, 0, :east
unit :sludge, 159, 0, :east
unit :thick_sludge, 165, 0, :east
unit :archer, 167, 0, :east
unit :sludge, 175, 0, :east
unit :wizard, 184, 0, :east
unit :archer, 186, 0, :east
unit :captive, 189, 0, :east
unit :thick_sludge, 192, 0, :east
unit :captive, 193, 0, :east
unit :wizard, 199, 0, :east
unit :sludge, 200, 0, :east
unit :wizard, 201, 0, :east
unit :captive, 204, 0, :east
unit :captive, 206, 0, :east
unit :thick_sludge, 209, 0, :east
unit :captive, 213, 0, :east
unit :captive, 216, 0, :east
unit :thick_sludge, 222, 0, :east
unit :wizard, 226, 0, :east
unit :thick_sludge, 228, 0, :east
unit :thick_sludge, 237, 0, :east
unit :archer, 238, 0, :east
unit :thick_sludge, 242, 0, :east
unit :archer, 244, 0, :east
unit :sludge, 250, 0, :east
unit :wizard, 256, 0, :east
unit :captive, 258, 0, :east
unit :sludge, 263, 0, :east
unit :wizard, 268, 0, :east
unit :archer, 274, 0, :east
unit :thick_sludge, 275, 0, :east
unit :wizard, 281, 0, :east
unit :archer, 292, 0, :east
unit :archer, 297, 0, :east
unit :wizard, 305, 0, :east
unit :captive, 306, 0, :east
unit :wizard, 309, 0, :east
unit :wizard, 314, 0, :east
unit :wizard, 316, 0, :east
unit :captive, 319, 0, :east
unit :archer, 321, 0, :east
unit :wizard, 324, 0, :east
unit :archer, 326, 0, :east
unit :captive, 331, 0, :east
unit :captive, 338, 0, :east
unit :thick_sludge, 339, 0, :east
unit :thick_sludge, 343, 0, :east
unit :wizard, 344, 0, :east
unit :wizard, 346, 0, :east
unit :sludge, 347, 0, :east
unit :thick_sludge, 349, 0, :east
unit :wizard, 352, 0, :east
unit :wizard, 355, 0, :east
unit :thick_sludge, 358, 0, :east
unit :wizard, 364, 0, :east
unit :sludge, 366, 0, :east
unit :wizard, 375, 0, :east
unit :captive, 387, 0, :east
unit :thick_sludge, 390, 0, :east
unit :wizard, 396, 0, :east
unit :archer, 404, 0, :east
unit :archer, 406, 0, :east
unit :captive, 410, 0, :east
unit :thick_sludge, 416, 0, :east
unit :archer, 419, 0, :east
unit :captive, 420, 0, :east
unit :wizard, 422, 0, :east
unit :thick_sludge, 427, 0, :east
unit :thick_sludge, 436, 0, :east
unit :sludge, 441, 0, :east
unit :sludge, 451, 0, :east
unit :thick_sludge, 452, 0, :east
unit :captive, 461, 0, :east
unit :captive, 462, 0, :east
unit :sludge, 463, 0, :east
unit :wizard, 465, 0, :east
unit :archer, 466, 0, :east
unit :thick_sludge, 469, 0, :east
unit :captive, 471, 0, :east
unit :archer, 472, 0, :east
unit :thick_sludge, 476, 0, :east
unit :sludge, 479, 0, :east
unit :captive, 481, 0, :east
unit :archer, 483, 0, :east
unit :thick_sludge, 484, 0, :east
unit :captive, 485, 0, :east
unit :sludge, 486, 0, :east
unit :sludge, 489, 0, :east
unit :wizard, 490, 0, :east
unit :thick_sludge, 496, 0, :east
unit :thick_sludge, 500, 0, :east
unit :wizard, 505, 0, :east
unit :captive, 508, 0, :east
unit :thick_sludge, 510, 0, :east
unit :thick_sludge, 513, 0, :east
unit :captive, 521, 0, :east
unit :archer, 528, 0, :east
unit :archer, 530, 0, :east
unit :archer, 533, 0, :east
unit :wizard, 537, 0, :east
unit :wizard, 551, 0, :east
unit :thick_sludge, 552, 0, :east
unit :archer, 556, 0, :east
unit :archer, 560, 0, :east
unit :wizard, 562, 0, :east
unit :wizard, 569, 0, :east
unit :thick_sludge, 572, 0, :east
unit :thick_sludge, 575, 0, :east
unit :wizard, 578, 0, :east
unit :archer, 585, 0, :east
unit :archer, 587, 0, :east
unit :wizard, 589, 0, :east
unit :captive, 591, 0, :east
unit :archer, 593, 0, :east
unit :sludge, 598, 0, :east
unit :thick_sludge, 602, 0, :east
unit :thick_sludge, 610, 0, :east
unit :captive, 620, 0, :east
unit :thick_sludge, 622, 0, :east
unit :sludge, 624, 0, :east
unit :sludge, 627, 0, :east
unit :thick_sludge, 630, 0, :east
unit :wizard, 640, 0, :east
unit :sludge, 646, 0, :east
unit :captive, 649, 0, :east
unit :archer, 650, 0, :east
unit :thick_sludge, 653, 0, :east
unit :captive, 658, 0, :east
unit :sludge, 660, 0, :east
unit :thick_sludge, 679, 0, :east
unit :archer, 686, 0, :east
unit :sludge, 690, 0, :east
unit :archer, 695, 0, :east
unit :sludge, 697, 0, :east
unit :wizard, 707, 0, :east
unit :sludge, 710, 0, :east
unit :archer, 713, 0, :east
unit :archer, 716, 0, :east
unit :thick_sludge, 717, 0, :east
unit :sludge, 721, 0, :east
unit :captive, 725, 0, :east
unit :thick_sludge, 728, 0, :east
unit :captive, 730, 0, :east
unit :sludge, 734, 0, :east
unit :thick_sludge, 741, 0, :east
unit :captive, 747, 0, :east
unit :thick_sludge, 749, 0, :east
unit :captive, 751, 0, :east
unit :sludge, 752, 0, :east
unit :thick_sludge, 753, 0, :east
unit :thick_sludge, 757, 0, :east
unit :archer, 759, 0, :east
unit :thick_sludge, 760, 0, :east
unit :thick_sludge, 762, 0, :east
unit :sludge, 769, 0, :east
unit :archer, 773, 0, :east
unit :thick_sludge, 777, 0, :east
unit :archer, 780, 0, :east
unit :wizard, 782, 0, :east
unit :thick_sludge, 788, 0, :east
unit :wizard, 792, 0, :east
unit :captive, 795, 0, :east
unit :thick_sludge, 803, 0, :east
unit :captive, 809, 0, :east
unit :captive, 810, 0, :east
unit :archer, 811, 0, :east
unit :thick_sludge, 813, 0, :east
unit :captive, 814, 0, :east
unit :sludge, 816, 0, :east
unit :archer, 818, 0, :east
unit :sludge, 826, 0, :east
unit :captive, 840, 0, :west
unit :captive, 843, 0, :west
unit :wizard, 846, 0, :west
unit :thick_sludge, 850, 0, :west
unit :sludge, 854, 0, :west
unit :archer, 855, 0, :west
unit :archer, 859, 0, :west
unit :wizard, 863, 0, :west
unit :thick_sludge, 865, 0, :west
unit :wizard, 874, 0, :west
unit :sludge, 876, 0, :west
unit :archer, 883, 0, :west
unit :archer, 888, 0, :west
unit :archer, 893, 0, :west
unit :thick_sludge, 901, 0, :west
unit :sludge, 902, 0, :west
unit :sludge, 908, 0, :west
unit :captive, 909, 0, :west
