#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |w w  w  S s C a  wCS      CC   w C  sS    S    s   S S    w S w w S  CC     sa w      a           C    S  C     s sC a    S   C     sC            S     S    C    w  s  S s   C wS C  S   Sa       s         w C  a sa     s      s   S         s             >  C  S    SC  s      S  S C    Ss     s    S C    SC  asS        w       s           Sw  s    s  C   C  aa   Cs   C     Csa   as       s w    a s   C     s   s   S    aa   a    as    S   w a Sa           as     sws a aa     s           w       C  SSS  a      s      s   S  a a    a            a  S a      a          SCS a w   Ca  s as   a     a     C    Ss           w Cs                        ss a   C       S  s w     Sas   w   S w  S C s  w Sw C    S      C  @  Ca C   aCs   C         S     s    S        wa   S a       aa s  S C      C w  C         a   a      w  SS    wSs s  C  C  S             s        w Cw a      C  aS    S         S    C   C     w  C         a       s    s        ss           C wa      S   |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 973
ace_score 4865
size 973, 1
stairs 254, 0

warrior 718, 0, :east

unit :wizard, 0, 0, :east
unit :wizard, 2, 0, :east
unit :wizard, 5, 0, :east
unit :thick_sludge, 8, 0, :east
unit :sludge, 10, 0, :east
unit :captive, 12, 0, :east
unit :archer, 14, 0, :east
unit :wizard, 17, 0, :east
unit :captive, 18, 0, :east
unit :thick_sludge, 19, 0, :east
unit :captive, 26, 0, :east
unit :captive, 27, 0, :east
unit :wizard, 31, 0, :east
unit :captive, 33, 0, :east
unit :sludge, 36, 0, :east
unit :thick_sludge, 37, 0, :east
unit :thick_sludge, 42, 0, :east
unit :sludge, 47, 0, :east
unit :thick_sludge, 51, 0, :east
unit :thick_sludge, 53, 0, :east
unit :wizard, 58, 0, :east
unit :thick_sludge, 60, 0, :east
unit :wizard, 62, 0, :east
unit :wizard, 64, 0, :east
unit :thick_sludge, 66, 0, :east
unit :captive, 69, 0, :east
unit :captive, 70, 0, :east
unit :sludge, 76, 0, :east
unit :archer, 77, 0, :east
unit :wizard, 79, 0, :east
unit :archer, 86, 0, :east
unit :captive, 98, 0, :east
unit :thick_sludge, 103, 0, :east
unit :captive, 106, 0, :east
unit :sludge, 112, 0, :east
unit :sludge, 114, 0, :east
unit :captive, 115, 0, :east
unit :archer, 117, 0, :east
unit :thick_sludge, 122, 0, :east
unit :captive, 126, 0, :east
unit :sludge, 132, 0, :east
unit :captive, 133, 0, :east
unit :thick_sludge, 146, 0, :east
unit :thick_sludge, 152, 0, :east
unit :captive, 157, 0, :east
unit :wizard, 162, 0, :east
unit :sludge, 165, 0, :east
unit :thick_sludge, 168, 0, :east
unit :sludge, 170, 0, :east
unit :captive, 174, 0, :east
unit :wizard, 176, 0, :east
unit :thick_sludge, 177, 0, :east
unit :captive, 179, 0, :east
unit :thick_sludge, 182, 0, :east
unit :thick_sludge, 186, 0, :east
unit :archer, 187, 0, :east
unit :sludge, 195, 0, :east
unit :wizard, 205, 0, :east
unit :captive, 207, 0, :east
unit :archer, 210, 0, :east
unit :sludge, 212, 0, :east
unit :archer, 213, 0, :east
unit :sludge, 219, 0, :east
unit :sludge, 226, 0, :east
unit :thick_sludge, 230, 0, :east
unit :sludge, 240, 0, :east
unit :captive, 257, 0, :east
unit :thick_sludge, 260, 0, :east
unit :thick_sludge, 265, 0, :east
unit :captive, 266, 0, :east
unit :sludge, 269, 0, :east
unit :thick_sludge, 276, 0, :east
unit :thick_sludge, 279, 0, :east
unit :captive, 281, 0, :east
unit :thick_sludge, 286, 0, :east
unit :sludge, 287, 0, :east
unit :sludge, 293, 0, :east
unit :thick_sludge, 298, 0, :east
unit :captive, 300, 0, :east
unit :thick_sludge, 305, 0, :east
unit :captive, 306, 0, :east
unit :archer, 309, 0, :east
unit :sludge, 310, 0, :east
unit :thick_sludge, 311, 0, :east
unit :wizard, 320, 0, :east
unit :sludge, 328, 0, :east
unit :thick_sludge, 340, 0, :east
unit :wizard, 341, 0, :east
unit :sludge, 344, 0, :east
unit :sludge, 349, 0, :east
unit :captive, 352, 0, :east
unit :captive, 356, 0, :east
unit :archer, 359, 0, :east
unit :archer, 360, 0, :east
unit :captive, 364, 0, :east
unit :sludge, 365, 0, :east
unit :captive, 369, 0, :east
unit :captive, 375, 0, :east
unit :sludge, 376, 0, :east
unit :archer, 377, 0, :east
unit :archer, 381, 0, :east
unit :sludge, 382, 0, :east
unit :sludge, 390, 0, :east
unit :wizard, 392, 0, :east
unit :archer, 397, 0, :east
unit :sludge, 399, 0, :east
unit :captive, 403, 0, :east
unit :sludge, 409, 0, :east
unit :sludge, 413, 0, :east
unit :thick_sludge, 417, 0, :east
unit :archer, 422, 0, :east
unit :archer, 423, 0, :east
unit :archer, 427, 0, :east
unit :archer, 432, 0, :east
unit :sludge, 433, 0, :east
unit :thick_sludge, 438, 0, :east
unit :wizard, 442, 0, :east
unit :archer, 444, 0, :east
unit :thick_sludge, 446, 0, :east
unit :archer, 447, 0, :east
unit :archer, 459, 0, :east
unit :sludge, 460, 0, :east
unit :sludge, 466, 0, :east
unit :wizard, 467, 0, :east
unit :sludge, 468, 0, :east
unit :archer, 470, 0, :east
unit :archer, 472, 0, :east
unit :archer, 473, 0, :east
unit :sludge, 479, 0, :east
unit :wizard, 491, 0, :east
unit :captive, 499, 0, :east
unit :thick_sludge, 502, 0, :east
unit :thick_sludge, 503, 0, :east
unit :thick_sludge, 504, 0, :east
unit :archer, 507, 0, :east
unit :sludge, 514, 0, :east
unit :sludge, 521, 0, :east
unit :thick_sludge, 525, 0, :east
unit :archer, 528, 0, :east
unit :archer, 530, 0, :east
unit :archer, 535, 0, :east
unit :archer, 548, 0, :east
unit :thick_sludge, 551, 0, :east
unit :archer, 553, 0, :east
unit :archer, 560, 0, :east
unit :thick_sludge, 571, 0, :east
unit :captive, 572, 0, :east
unit :thick_sludge, 573, 0, :east
unit :archer, 575, 0, :east
unit :wizard, 577, 0, :east
unit :captive, 581, 0, :east
unit :archer, 582, 0, :east
unit :sludge, 585, 0, :east
unit :archer, 587, 0, :east
unit :sludge, 588, 0, :east
unit :archer, 592, 0, :east
unit :archer, 598, 0, :east
unit :captive, 604, 0, :east
unit :thick_sludge, 609, 0, :east
unit :sludge, 610, 0, :east
unit :wizard, 622, 0, :east
unit :captive, 624, 0, :east
unit :sludge, 625, 0, :east
unit :sludge, 650, 0, :east
unit :sludge, 651, 0, :east
unit :archer, 653, 0, :east
unit :captive, 657, 0, :east
unit :thick_sludge, 665, 0, :east
unit :sludge, 668, 0, :east
unit :wizard, 670, 0, :east
unit :thick_sludge, 676, 0, :east
unit :archer, 677, 0, :east
unit :sludge, 678, 0, :east
unit :wizard, 682, 0, :east
unit :thick_sludge, 686, 0, :east
unit :wizard, 688, 0, :east
unit :thick_sludge, 691, 0, :east
unit :captive, 693, 0, :east
unit :sludge, 695, 0, :east
unit :wizard, 698, 0, :east
unit :thick_sludge, 700, 0, :east
unit :wizard, 701, 0, :east
unit :captive, 703, 0, :east
unit :thick_sludge, 708, 0, :east
unit :captive, 715, 0, :east
unit :captive, 721, 0, :west
unit :archer, 722, 0, :west
unit :captive, 724, 0, :west
unit :archer, 728, 0, :west
unit :captive, 729, 0, :west
unit :sludge, 730, 0, :west
unit :captive, 734, 0, :west
unit :thick_sludge, 744, 0, :west
unit :sludge, 750, 0, :west
unit :thick_sludge, 755, 0, :west
unit :wizard, 764, 0, :west
unit :archer, 765, 0, :west
unit :thick_sludge, 769, 0, :west
unit :archer, 771, 0, :west
unit :archer, 779, 0, :west
unit :archer, 780, 0, :west
unit :sludge, 782, 0, :west
unit :thick_sludge, 785, 0, :west
unit :captive, 787, 0, :west
unit :captive, 794, 0, :west
unit :wizard, 796, 0, :west
unit :captive, 799, 0, :west
unit :archer, 809, 0, :west
unit :archer, 813, 0, :west
unit :wizard, 820, 0, :west
unit :thick_sludge, 823, 0, :west
unit :thick_sludge, 824, 0, :west
unit :wizard, 829, 0, :west
unit :thick_sludge, 830, 0, :west
unit :sludge, 831, 0, :west
unit :sludge, 833, 0, :west
unit :captive, 836, 0, :west
unit :captive, 839, 0, :west
unit :thick_sludge, 842, 0, :west
unit :sludge, 856, 0, :west
unit :wizard, 865, 0, :west
unit :captive, 867, 0, :west
unit :wizard, 868, 0, :west
unit :archer, 870, 0, :west
unit :captive, 877, 0, :west
unit :archer, 880, 0, :west
unit :thick_sludge, 881, 0, :west
unit :thick_sludge, 886, 0, :west
unit :thick_sludge, 896, 0, :west
unit :captive, 901, 0, :west
unit :captive, 905, 0, :west
unit :wizard, 911, 0, :west
unit :captive, 914, 0, :west
unit :archer, 924, 0, :west
unit :sludge, 932, 0, :west
unit :sludge, 937, 0, :west
unit :sludge, 946, 0, :west
unit :sludge, 947, 0, :west
unit :captive, 959, 0, :west
unit :wizard, 961, 0, :west
unit :archer, 962, 0, :west
unit :thick_sludge, 969, 0, :west
