#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      C S   S s        w    as  a        w S S  s   C              S  s S  S SC    S S a a      w  s          S C   S aas ss  Sw   C  C     S    w            a   w         S s     as S               w     sC       C    SC   w      s  aaS   S          wS >  aa     s   S w   s   s a  @    S  a   a        w S a  s      a   S  w  C      aa  sw   s C s S   C   C  w    a    a a  a  s     S a Ss w  s  s   w   w   a   sC Sa C     a C   C S             a               a      C       ws   S   sC   s a         a      C a   S      S    w          s  s   s   S     s    sw   C    S  s   w     a sa Sw a    a       CC   a   a a |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 620
ace_score 3100
size 620, 1
stairs 254, 0

warrior 283, 0, :east

unit :captive, 6, 0, :east
unit :thick_sludge, 8, 0, :east
unit :thick_sludge, 12, 0, :east
unit :sludge, 14, 0, :east
unit :wizard, 23, 0, :east
unit :archer, 28, 0, :east
unit :sludge, 29, 0, :east
unit :archer, 32, 0, :east
unit :wizard, 41, 0, :east
unit :thick_sludge, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :sludge, 48, 0, :east
unit :captive, 52, 0, :east
unit :thick_sludge, 67, 0, :east
unit :sludge, 70, 0, :east
unit :thick_sludge, 72, 0, :east
unit :thick_sludge, 75, 0, :east
unit :thick_sludge, 77, 0, :east
unit :captive, 78, 0, :east
unit :thick_sludge, 83, 0, :east
unit :thick_sludge, 85, 0, :east
unit :archer, 87, 0, :east
unit :archer, 89, 0, :east
unit :wizard, 96, 0, :east
unit :sludge, 99, 0, :east
unit :thick_sludge, 110, 0, :east
unit :captive, 112, 0, :east
unit :thick_sludge, 116, 0, :east
unit :archer, 118, 0, :east
unit :archer, 119, 0, :east
unit :sludge, 120, 0, :east
unit :sludge, 122, 0, :east
unit :sludge, 123, 0, :east
unit :thick_sludge, 126, 0, :east
unit :wizard, 127, 0, :east
unit :captive, 131, 0, :east
unit :captive, 134, 0, :east
unit :thick_sludge, 140, 0, :east
unit :wizard, 145, 0, :east
unit :archer, 158, 0, :east
unit :wizard, 162, 0, :east
unit :thick_sludge, 172, 0, :east
unit :sludge, 174, 0, :east
unit :archer, 180, 0, :east
unit :sludge, 181, 0, :east
unit :thick_sludge, 183, 0, :east
unit :wizard, 199, 0, :east
unit :sludge, 205, 0, :east
unit :captive, 206, 0, :east
unit :captive, 214, 0, :east
unit :thick_sludge, 219, 0, :east
unit :captive, 220, 0, :east
unit :wizard, 224, 0, :east
unit :sludge, 231, 0, :east
unit :archer, 234, 0, :east
unit :archer, 235, 0, :east
unit :thick_sludge, 236, 0, :east
unit :thick_sludge, 240, 0, :east
unit :wizard, 251, 0, :east
unit :thick_sludge, 252, 0, :east
unit :archer, 257, 0, :east
unit :archer, 258, 0, :east
unit :sludge, 264, 0, :east
unit :thick_sludge, 268, 0, :east
unit :wizard, 270, 0, :east
unit :sludge, 274, 0, :east
unit :sludge, 278, 0, :east
unit :archer, 280, 0, :east
unit :thick_sludge, 288, 0, :west
unit :archer, 291, 0, :west
unit :archer, 295, 0, :west
unit :wizard, 304, 0, :west
unit :thick_sludge, 306, 0, :west
unit :archer, 308, 0, :west
unit :sludge, 311, 0, :west
unit :archer, 318, 0, :west
unit :thick_sludge, 322, 0, :west
unit :wizard, 325, 0, :west
unit :captive, 328, 0, :west
unit :archer, 335, 0, :west
unit :archer, 336, 0, :west
unit :sludge, 339, 0, :west
unit :wizard, 340, 0, :west
unit :sludge, 344, 0, :west
unit :captive, 346, 0, :west
unit :sludge, 348, 0, :west
unit :thick_sludge, 350, 0, :west
unit :captive, 354, 0, :west
unit :captive, 358, 0, :west
unit :wizard, 361, 0, :west
unit :archer, 366, 0, :west
unit :archer, 371, 0, :west
unit :archer, 373, 0, :west
unit :archer, 376, 0, :west
unit :sludge, 379, 0, :west
unit :thick_sludge, 385, 0, :west
unit :archer, 387, 0, :west
unit :thick_sludge, 389, 0, :west
unit :sludge, 390, 0, :west
unit :wizard, 392, 0, :west
unit :sludge, 395, 0, :west
unit :sludge, 398, 0, :west
unit :wizard, 402, 0, :west
unit :wizard, 406, 0, :west
unit :archer, 410, 0, :west
unit :sludge, 414, 0, :west
unit :captive, 415, 0, :west
unit :thick_sludge, 417, 0, :west
unit :archer, 418, 0, :west
unit :captive, 420, 0, :west
unit :archer, 426, 0, :west
unit :captive, 428, 0, :west
unit :captive, 432, 0, :west
unit :thick_sludge, 434, 0, :west
unit :archer, 448, 0, :west
unit :archer, 464, 0, :west
unit :captive, 471, 0, :west
unit :wizard, 479, 0, :west
unit :sludge, 480, 0, :west
unit :thick_sludge, 484, 0, :west
unit :sludge, 488, 0, :west
unit :captive, 489, 0, :west
unit :sludge, 493, 0, :west
unit :archer, 495, 0, :west
unit :archer, 505, 0, :west
unit :captive, 512, 0, :west
unit :archer, 514, 0, :west
unit :thick_sludge, 518, 0, :west
unit :thick_sludge, 525, 0, :west
unit :wizard, 530, 0, :west
unit :sludge, 541, 0, :west
unit :sludge, 544, 0, :west
unit :sludge, 548, 0, :west
unit :thick_sludge, 552, 0, :west
unit :sludge, 558, 0, :west
unit :sludge, 563, 0, :west
unit :wizard, 564, 0, :west
unit :captive, 568, 0, :west
unit :thick_sludge, 573, 0, :west
unit :sludge, 576, 0, :west
unit :wizard, 580, 0, :west
unit :archer, 586, 0, :west
unit :sludge, 588, 0, :west
unit :archer, 589, 0, :west
unit :thick_sludge, 591, 0, :west
unit :wizard, 592, 0, :west
unit :archer, 594, 0, :west
unit :archer, 599, 0, :west
unit :captive, 607, 0, :west
unit :captive, 608, 0, :west
unit :archer, 612, 0, :west
unit :archer, 616, 0, :west
unit :archer, 618, 0, :west
