#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |            S      w  a S  a a CSw SS  C  s S a               a            C     s  s       C aS          Sw      s        s  @  CsSw      C        S s        a    aw           w         s C  C     a C s s  s  CS S  s Sa     a   s              s  s S  S     w   S C   S       w    C             w                S   aC  s  a    S  a a  a     aa      aa w C   C   aa    s  as a  S >s       w      s s    C   C    w      a S C    a        S a    sa       C     w a ss w   w  C      S a SS   w Cs w  a   C   sa    sa  aS s     S C w   w w   aa    w w        a    s  Cs      C  S C    CSs wC                      C   C    ssS w           C   wa  s      s  s   w   S   s   w   S wS w S ss C  s   a  s a  w s   Caw     C aS             a  w       a  w  C             w aS    a  s     C  C            C             w w      SSa      sC  SsCC    C  aa           s   s    w a        C      wS     CC       C   wa  C w  C  S        a    s SS   a s       C  ws  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 951
ace_score 4755
size 951, 1
stairs 380, 0

warrior 126, 0, :east

unit :thick_sludge, 12, 0, :east
unit :wizard, 19, 0, :east
unit :archer, 22, 0, :east
unit :thick_sludge, 24, 0, :east
unit :archer, 27, 0, :east
unit :archer, 29, 0, :east
unit :captive, 31, 0, :east
unit :thick_sludge, 32, 0, :east
unit :wizard, 33, 0, :east
unit :thick_sludge, 35, 0, :east
unit :thick_sludge, 36, 0, :east
unit :captive, 39, 0, :east
unit :sludge, 42, 0, :east
unit :thick_sludge, 44, 0, :east
unit :archer, 46, 0, :east
unit :archer, 62, 0, :east
unit :captive, 75, 0, :east
unit :sludge, 81, 0, :east
unit :sludge, 84, 0, :east
unit :captive, 92, 0, :east
unit :archer, 94, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 106, 0, :east
unit :wizard, 107, 0, :east
unit :sludge, 114, 0, :east
unit :sludge, 123, 0, :east
unit :captive, 129, 0, :west
unit :sludge, 130, 0, :west
unit :thick_sludge, 131, 0, :west
unit :wizard, 132, 0, :west
unit :captive, 139, 0, :west
unit :thick_sludge, 148, 0, :west
unit :sludge, 150, 0, :west
unit :archer, 159, 0, :west
unit :archer, 164, 0, :west
unit :wizard, 165, 0, :west
unit :wizard, 177, 0, :west
unit :sludge, 187, 0, :west
unit :captive, 189, 0, :west
unit :captive, 192, 0, :west
unit :archer, 198, 0, :west
unit :captive, 200, 0, :west
unit :sludge, 202, 0, :west
unit :sludge, 204, 0, :west
unit :sludge, 207, 0, :west
unit :captive, 210, 0, :west
unit :thick_sludge, 211, 0, :west
unit :thick_sludge, 213, 0, :west
unit :sludge, 216, 0, :west
unit :thick_sludge, 218, 0, :west
unit :archer, 219, 0, :west
unit :archer, 225, 0, :west
unit :sludge, 229, 0, :west
unit :sludge, 244, 0, :west
unit :sludge, 247, 0, :west
unit :thick_sludge, 249, 0, :west
unit :thick_sludge, 252, 0, :west
unit :wizard, 258, 0, :west
unit :thick_sludge, 262, 0, :west
unit :captive, 264, 0, :west
unit :thick_sludge, 268, 0, :west
unit :wizard, 276, 0, :west
unit :captive, 281, 0, :west
unit :wizard, 295, 0, :west
unit :thick_sludge, 312, 0, :west
unit :archer, 316, 0, :west
unit :captive, 317, 0, :west
unit :sludge, 320, 0, :west
unit :archer, 323, 0, :west
unit :thick_sludge, 328, 0, :west
unit :archer, 331, 0, :west
unit :archer, 333, 0, :west
unit :archer, 336, 0, :west
unit :archer, 342, 0, :west
unit :archer, 343, 0, :west
unit :archer, 350, 0, :west
unit :archer, 351, 0, :west
unit :wizard, 353, 0, :west
unit :captive, 355, 0, :west
unit :captive, 359, 0, :west
unit :archer, 363, 0, :west
unit :archer, 364, 0, :west
unit :sludge, 369, 0, :west
unit :archer, 372, 0, :west
unit :sludge, 373, 0, :west
unit :archer, 375, 0, :west
unit :thick_sludge, 378, 0, :west
unit :sludge, 381, 0, :west
unit :wizard, 389, 0, :west
unit :sludge, 396, 0, :west
unit :sludge, 398, 0, :west
unit :captive, 403, 0, :west
unit :captive, 407, 0, :west
unit :wizard, 412, 0, :west
unit :archer, 419, 0, :west
unit :thick_sludge, 421, 0, :west
unit :captive, 423, 0, :west
unit :archer, 428, 0, :west
unit :thick_sludge, 437, 0, :west
unit :archer, 439, 0, :west
unit :sludge, 444, 0, :west
unit :archer, 445, 0, :west
unit :captive, 453, 0, :west
unit :wizard, 459, 0, :west
unit :archer, 461, 0, :west
unit :sludge, 463, 0, :west
unit :sludge, 464, 0, :west
unit :wizard, 466, 0, :west
unit :wizard, 470, 0, :west
unit :captive, 473, 0, :west
unit :thick_sludge, 480, 0, :west
unit :archer, 482, 0, :west
unit :thick_sludge, 484, 0, :west
unit :thick_sludge, 485, 0, :west
unit :wizard, 489, 0, :west
unit :captive, 491, 0, :west
unit :sludge, 492, 0, :west
unit :wizard, 494, 0, :west
unit :archer, 497, 0, :west
unit :captive, 501, 0, :west
unit :sludge, 505, 0, :west
unit :archer, 506, 0, :west
unit :sludge, 511, 0, :west
unit :archer, 512, 0, :west
unit :archer, 515, 0, :west
unit :thick_sludge, 516, 0, :west
unit :sludge, 518, 0, :west
unit :thick_sludge, 524, 0, :west
unit :captive, 526, 0, :west
unit :wizard, 528, 0, :west
unit :wizard, 532, 0, :west
unit :wizard, 534, 0, :west
unit :archer, 538, 0, :west
unit :archer, 539, 0, :west
unit :wizard, 544, 0, :west
unit :wizard, 546, 0, :west
unit :archer, 555, 0, :west
unit :sludge, 560, 0, :west
unit :captive, 563, 0, :west
unit :sludge, 564, 0, :west
unit :captive, 571, 0, :west
unit :thick_sludge, 574, 0, :west
unit :captive, 576, 0, :west
unit :captive, 581, 0, :west
unit :thick_sludge, 582, 0, :west
unit :sludge, 583, 0, :west
unit :wizard, 585, 0, :west
unit :captive, 586, 0, :west
unit :captive, 609, 0, :west
unit :captive, 613, 0, :west
unit :sludge, 618, 0, :west
unit :sludge, 619, 0, :west
unit :thick_sludge, 620, 0, :west
unit :wizard, 622, 0, :west
unit :captive, 634, 0, :west
unit :wizard, 638, 0, :west
unit :archer, 639, 0, :west
unit :sludge, 642, 0, :west
unit :sludge, 649, 0, :west
unit :sludge, 652, 0, :west
unit :wizard, 656, 0, :west
unit :thick_sludge, 660, 0, :west
unit :sludge, 664, 0, :west
unit :wizard, 668, 0, :west
unit :thick_sludge, 672, 0, :west
unit :wizard, 674, 0, :west
unit :thick_sludge, 675, 0, :west
unit :wizard, 677, 0, :west
unit :thick_sludge, 679, 0, :west
unit :sludge, 681, 0, :west
unit :sludge, 682, 0, :west
unit :captive, 684, 0, :west
unit :sludge, 687, 0, :west
unit :archer, 691, 0, :west
unit :sludge, 694, 0, :west
unit :archer, 696, 0, :west
unit :wizard, 699, 0, :west
unit :sludge, 701, 0, :west
unit :captive, 705, 0, :west
unit :archer, 706, 0, :west
unit :wizard, 707, 0, :west
unit :captive, 713, 0, :west
unit :archer, 715, 0, :west
unit :thick_sludge, 716, 0, :west
unit :archer, 730, 0, :west
unit :wizard, 733, 0, :west
unit :archer, 741, 0, :west
unit :wizard, 744, 0, :west
unit :captive, 747, 0, :west
unit :wizard, 761, 0, :west
unit :archer, 763, 0, :west
unit :thick_sludge, 764, 0, :west
unit :archer, 769, 0, :west
unit :sludge, 772, 0, :west
unit :captive, 778, 0, :west
unit :captive, 781, 0, :west
unit :captive, 794, 0, :west
unit :wizard, 808, 0, :west
unit :wizard, 810, 0, :west
unit :thick_sludge, 817, 0, :west
unit :thick_sludge, 818, 0, :west
unit :archer, 819, 0, :west
unit :sludge, 826, 0, :west
unit :captive, 827, 0, :west
unit :thick_sludge, 830, 0, :west
unit :sludge, 831, 0, :west
unit :captive, 832, 0, :west
unit :captive, 833, 0, :west
unit :captive, 838, 0, :west
unit :archer, 841, 0, :west
unit :archer, 842, 0, :west
unit :sludge, 854, 0, :west
unit :sludge, 858, 0, :west
unit :wizard, 863, 0, :west
unit :archer, 865, 0, :west
unit :captive, 874, 0, :west
unit :wizard, 881, 0, :west
unit :thick_sludge, 882, 0, :west
unit :captive, 888, 0, :west
unit :captive, 889, 0, :west
unit :captive, 897, 0, :west
unit :wizard, 901, 0, :west
unit :archer, 902, 0, :west
unit :captive, 905, 0, :west
unit :wizard, 907, 0, :west
unit :captive, 910, 0, :west
unit :thick_sludge, 913, 0, :west
unit :archer, 922, 0, :west
unit :sludge, 927, 0, :west
unit :thick_sludge, 929, 0, :west
unit :thick_sludge, 930, 0, :west
unit :archer, 934, 0, :west
unit :sludge, 936, 0, :west
unit :captive, 944, 0, :west
unit :wizard, 947, 0, :west
unit :sludge, 948, 0, :west
