#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   S  a    w   CC w S      s a         w    a   w   wa     wa       sS   s   C s  a S   s  SS aSa        w    asC    w      S  CC    as w      a   C     S        w C s w   C      C       w  s   sC            S   a   asC s C    C  a   aa  a    w   w        w    s      S   w     a  Cw  w w  a       s  s w  a       S    s         >    S  SC            w   w      s  s  S     a S s w  s            s    CC S   C C    aa    a       s    S    C  S   C   w CCS C        s S   S     CSw       ss  wC   C          s SawCss         s              a sss       a     w   S w  a   Ca Sw      s S         S s S        a   @   S     s s      aw   a S  s  S   C               s   C    S         S  ws     wa        S  a  w      S S w     C  Ss s S   w   S       a     C   w       aS    a     s   a  wC a C w       aa saws     C     C        s C  w       w  a             s Cws  S|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 865
ace_score 4325
size 865, 1
stairs 329, 0

warrior 610, 0, :east

unit :thick_sludge, 3, 0, :east
unit :archer, 6, 0, :east
unit :wizard, 11, 0, :east
unit :captive, 15, 0, :east
unit :captive, 16, 0, :east
unit :wizard, 18, 0, :east
unit :thick_sludge, 20, 0, :east
unit :sludge, 27, 0, :east
unit :archer, 29, 0, :east
unit :wizard, 39, 0, :east
unit :archer, 44, 0, :east
unit :wizard, 48, 0, :east
unit :wizard, 52, 0, :east
unit :archer, 53, 0, :east
unit :wizard, 59, 0, :east
unit :archer, 60, 0, :east
unit :sludge, 68, 0, :east
unit :thick_sludge, 69, 0, :east
unit :sludge, 73, 0, :east
unit :captive, 77, 0, :east
unit :sludge, 79, 0, :east
unit :archer, 82, 0, :east
unit :thick_sludge, 84, 0, :east
unit :sludge, 88, 0, :east
unit :thick_sludge, 91, 0, :east
unit :thick_sludge, 92, 0, :east
unit :archer, 94, 0, :east
unit :thick_sludge, 95, 0, :east
unit :archer, 96, 0, :east
unit :wizard, 105, 0, :east
unit :archer, 110, 0, :east
unit :sludge, 111, 0, :east
unit :captive, 112, 0, :east
unit :wizard, 117, 0, :east
unit :thick_sludge, 124, 0, :east
unit :captive, 127, 0, :east
unit :captive, 128, 0, :east
unit :archer, 133, 0, :east
unit :sludge, 134, 0, :east
unit :wizard, 136, 0, :east
unit :archer, 143, 0, :east
unit :captive, 147, 0, :east
unit :thick_sludge, 153, 0, :east
unit :wizard, 162, 0, :east
unit :captive, 164, 0, :east
unit :sludge, 166, 0, :east
unit :wizard, 168, 0, :east
unit :captive, 172, 0, :east
unit :captive, 179, 0, :east
unit :wizard, 187, 0, :east
unit :sludge, 190, 0, :east
unit :sludge, 194, 0, :east
unit :captive, 195, 0, :east
unit :thick_sludge, 208, 0, :east
unit :archer, 212, 0, :east
unit :archer, 216, 0, :east
unit :sludge, 217, 0, :east
unit :captive, 218, 0, :east
unit :sludge, 220, 0, :east
unit :captive, 222, 0, :east
unit :captive, 227, 0, :east
unit :archer, 230, 0, :east
unit :archer, 234, 0, :east
unit :archer, 235, 0, :east
unit :archer, 238, 0, :east
unit :wizard, 243, 0, :east
unit :wizard, 247, 0, :east
unit :wizard, 256, 0, :east
unit :sludge, 261, 0, :east
unit :thick_sludge, 268, 0, :east
unit :wizard, 272, 0, :east
unit :archer, 278, 0, :east
unit :captive, 281, 0, :east
unit :wizard, 282, 0, :east
unit :wizard, 285, 0, :east
unit :wizard, 287, 0, :east
unit :archer, 290, 0, :east
unit :sludge, 298, 0, :east
unit :sludge, 301, 0, :east
unit :wizard, 303, 0, :east
unit :archer, 306, 0, :east
unit :thick_sludge, 314, 0, :east
unit :sludge, 319, 0, :east
unit :thick_sludge, 334, 0, :east
unit :thick_sludge, 337, 0, :east
unit :captive, 338, 0, :east
unit :wizard, 351, 0, :east
unit :wizard, 355, 0, :east
unit :sludge, 362, 0, :east
unit :sludge, 365, 0, :east
unit :thick_sludge, 368, 0, :east
unit :archer, 374, 0, :east
unit :thick_sludge, 376, 0, :east
unit :sludge, 378, 0, :east
unit :wizard, 380, 0, :east
unit :sludge, 383, 0, :east
unit :sludge, 396, 0, :east
unit :captive, 401, 0, :east
unit :captive, 402, 0, :east
unit :thick_sludge, 404, 0, :east
unit :captive, 408, 0, :east
unit :captive, 410, 0, :east
unit :archer, 415, 0, :east
unit :archer, 416, 0, :east
unit :archer, 421, 0, :east
unit :sludge, 429, 0, :east
unit :thick_sludge, 434, 0, :east
unit :captive, 439, 0, :east
unit :thick_sludge, 442, 0, :east
unit :captive, 446, 0, :east
unit :wizard, 450, 0, :east
unit :captive, 452, 0, :east
unit :captive, 453, 0, :east
unit :thick_sludge, 454, 0, :east
unit :captive, 456, 0, :east
unit :sludge, 465, 0, :east
unit :thick_sludge, 467, 0, :east
unit :thick_sludge, 471, 0, :east
unit :captive, 477, 0, :east
unit :thick_sludge, 478, 0, :east
unit :wizard, 479, 0, :east
unit :sludge, 487, 0, :east
unit :sludge, 488, 0, :east
unit :wizard, 491, 0, :east
unit :captive, 492, 0, :east
unit :captive, 496, 0, :east
unit :sludge, 507, 0, :east
unit :thick_sludge, 509, 0, :east
unit :archer, 510, 0, :east
unit :wizard, 511, 0, :east
unit :captive, 512, 0, :east
unit :sludge, 513, 0, :east
unit :sludge, 514, 0, :east
unit :sludge, 524, 0, :east
unit :archer, 539, 0, :east
unit :sludge, 541, 0, :east
unit :sludge, 542, 0, :east
unit :sludge, 543, 0, :east
unit :archer, 551, 0, :east
unit :wizard, 557, 0, :east
unit :thick_sludge, 561, 0, :east
unit :wizard, 563, 0, :east
unit :archer, 566, 0, :east
unit :captive, 570, 0, :east
unit :archer, 571, 0, :east
unit :thick_sludge, 573, 0, :east
unit :wizard, 574, 0, :east
unit :sludge, 581, 0, :east
unit :thick_sludge, 583, 0, :east
unit :thick_sludge, 593, 0, :east
unit :sludge, 595, 0, :east
unit :thick_sludge, 597, 0, :east
unit :archer, 606, 0, :east
unit :thick_sludge, 614, 0, :west
unit :sludge, 620, 0, :west
unit :sludge, 622, 0, :west
unit :archer, 629, 0, :west
unit :wizard, 630, 0, :west
unit :archer, 634, 0, :west
unit :thick_sludge, 636, 0, :west
unit :sludge, 639, 0, :west
unit :thick_sludge, 642, 0, :west
unit :captive, 646, 0, :west
unit :sludge, 662, 0, :west
unit :captive, 666, 0, :west
unit :thick_sludge, 671, 0, :west
unit :thick_sludge, 681, 0, :west
unit :wizard, 684, 0, :west
unit :sludge, 685, 0, :west
unit :wizard, 691, 0, :west
unit :archer, 692, 0, :west
unit :thick_sludge, 701, 0, :west
unit :archer, 704, 0, :west
unit :wizard, 707, 0, :west
unit :thick_sludge, 714, 0, :west
unit :thick_sludge, 716, 0, :west
unit :wizard, 718, 0, :west
unit :captive, 724, 0, :west
unit :thick_sludge, 727, 0, :west
unit :sludge, 728, 0, :west
unit :sludge, 730, 0, :west
unit :thick_sludge, 732, 0, :west
unit :wizard, 736, 0, :west
unit :thick_sludge, 740, 0, :west
unit :archer, 748, 0, :west
unit :captive, 754, 0, :west
unit :wizard, 758, 0, :west
unit :archer, 766, 0, :west
unit :thick_sludge, 767, 0, :west
unit :archer, 772, 0, :west
unit :sludge, 778, 0, :west
unit :archer, 782, 0, :west
unit :wizard, 785, 0, :west
unit :captive, 786, 0, :west
unit :archer, 788, 0, :west
unit :captive, 790, 0, :west
unit :wizard, 792, 0, :west
unit :archer, 800, 0, :west
unit :archer, 801, 0, :west
unit :sludge, 803, 0, :west
unit :archer, 804, 0, :west
unit :wizard, 805, 0, :west
unit :sludge, 806, 0, :west
unit :captive, 812, 0, :west
unit :captive, 818, 0, :west
unit :sludge, 827, 0, :west
unit :captive, 829, 0, :west
unit :wizard, 832, 0, :west
unit :wizard, 840, 0, :west
unit :archer, 843, 0, :west
unit :sludge, 857, 0, :west
unit :captive, 859, 0, :west
unit :wizard, 860, 0, :west
unit :sludge, 861, 0, :west
unit :thick_sludge, 864, 0, :west
