#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   w w Css       a   S      wS     w  S Css    w   S   a  a  s   Cs  s w     S     S   sC SSa s    S  s s     w    a    s Cw s      a  a          a  s  >          S s    a          C               w  C  aa S S w Sss   w C  CSS        aaS   w   C   C a    asa     w w          w s     s   w    C w        a     w   ws      S w   s aa SaS        C  a  S      a aw wS  S  a       sa  w       a     S a            C        Ss          aa s           S    Ss  C  w  S  s   S a     a a  sC        S   a               C w       S C Sa  a CS  C    C    a  s w    S    ss     S      S   s      a  w   @      w   a as      s ssCS    S aa      S    S      S        a    C w w  S             w   s  S  s    a a  saS  a w s     w     a                               S   a   Sa a     w S wa S    w    CS w  a a                    |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 816
ace_score 4080
size 816, 1
stairs 152, 0

warrior 592, 0, :east

unit :wizard, 3, 0, :east
unit :wizard, 5, 0, :east
unit :captive, 7, 0, :east
unit :sludge, 8, 0, :east
unit :sludge, 9, 0, :east
unit :archer, 17, 0, :east
unit :thick_sludge, 21, 0, :east
unit :wizard, 28, 0, :east
unit :thick_sludge, 29, 0, :east
unit :wizard, 35, 0, :east
unit :thick_sludge, 38, 0, :east
unit :captive, 40, 0, :east
unit :sludge, 41, 0, :east
unit :sludge, 42, 0, :east
unit :wizard, 47, 0, :east
unit :thick_sludge, 51, 0, :east
unit :archer, 55, 0, :east
unit :archer, 58, 0, :east
unit :sludge, 61, 0, :east
unit :captive, 65, 0, :east
unit :sludge, 66, 0, :east
unit :sludge, 69, 0, :east
unit :wizard, 71, 0, :east
unit :thick_sludge, 77, 0, :east
unit :thick_sludge, 83, 0, :east
unit :sludge, 87, 0, :east
unit :captive, 88, 0, :east
unit :thick_sludge, 90, 0, :east
unit :thick_sludge, 91, 0, :east
unit :archer, 92, 0, :east
unit :sludge, 94, 0, :east
unit :thick_sludge, 99, 0, :east
unit :sludge, 102, 0, :east
unit :sludge, 104, 0, :east
unit :wizard, 110, 0, :east
unit :archer, 115, 0, :east
unit :sludge, 120, 0, :east
unit :captive, 122, 0, :east
unit :wizard, 123, 0, :east
unit :sludge, 125, 0, :east
unit :archer, 132, 0, :east
unit :archer, 135, 0, :east
unit :archer, 146, 0, :east
unit :sludge, 149, 0, :east
unit :thick_sludge, 163, 0, :east
unit :sludge, 165, 0, :east
unit :archer, 170, 0, :east
unit :captive, 181, 0, :east
unit :wizard, 197, 0, :east
unit :captive, 200, 0, :east
unit :archer, 203, 0, :east
unit :archer, 204, 0, :east
unit :thick_sludge, 206, 0, :east
unit :thick_sludge, 208, 0, :east
unit :wizard, 210, 0, :east
unit :thick_sludge, 212, 0, :east
unit :sludge, 213, 0, :east
unit :sludge, 214, 0, :east
unit :wizard, 218, 0, :east
unit :captive, 220, 0, :east
unit :captive, 223, 0, :east
unit :thick_sludge, 224, 0, :east
unit :thick_sludge, 225, 0, :east
unit :archer, 234, 0, :east
unit :archer, 235, 0, :east
unit :thick_sludge, 236, 0, :east
unit :wizard, 240, 0, :east
unit :captive, 244, 0, :east
unit :captive, 248, 0, :east
unit :archer, 250, 0, :east
unit :archer, 255, 0, :east
unit :sludge, 256, 0, :east
unit :archer, 257, 0, :east
unit :wizard, 263, 0, :east
unit :wizard, 265, 0, :east
unit :wizard, 276, 0, :east
unit :sludge, 278, 0, :east
unit :sludge, 284, 0, :east
unit :wizard, 288, 0, :east
unit :captive, 293, 0, :east
unit :wizard, 295, 0, :east
unit :archer, 304, 0, :east
unit :wizard, 310, 0, :east
unit :wizard, 314, 0, :east
unit :sludge, 315, 0, :east
unit :thick_sludge, 322, 0, :east
unit :wizard, 324, 0, :east
unit :sludge, 328, 0, :east
unit :archer, 330, 0, :east
unit :archer, 331, 0, :east
unit :thick_sludge, 333, 0, :east
unit :archer, 334, 0, :east
unit :thick_sludge, 335, 0, :east
unit :captive, 344, 0, :east
unit :archer, 347, 0, :east
unit :thick_sludge, 350, 0, :east
unit :archer, 357, 0, :east
unit :archer, 359, 0, :east
unit :wizard, 360, 0, :east
unit :wizard, 362, 0, :east
unit :thick_sludge, 363, 0, :east
unit :thick_sludge, 366, 0, :east
unit :archer, 369, 0, :east
unit :sludge, 377, 0, :east
unit :archer, 378, 0, :east
unit :wizard, 381, 0, :east
unit :archer, 389, 0, :east
unit :thick_sludge, 395, 0, :east
unit :archer, 397, 0, :east
unit :captive, 410, 0, :east
unit :thick_sludge, 419, 0, :east
unit :sludge, 420, 0, :east
unit :archer, 431, 0, :east
unit :archer, 432, 0, :east
unit :sludge, 434, 0, :east
unit :thick_sludge, 446, 0, :east
unit :thick_sludge, 451, 0, :east
unit :sludge, 452, 0, :east
unit :captive, 455, 0, :east
unit :wizard, 458, 0, :east
unit :thick_sludge, 461, 0, :east
unit :sludge, 464, 0, :east
unit :thick_sludge, 468, 0, :east
unit :archer, 470, 0, :east
unit :archer, 476, 0, :east
unit :archer, 478, 0, :east
unit :sludge, 481, 0, :east
unit :captive, 482, 0, :east
unit :thick_sludge, 491, 0, :east
unit :archer, 495, 0, :east
unit :captive, 511, 0, :east
unit :wizard, 513, 0, :east
unit :thick_sludge, 521, 0, :east
unit :captive, 523, 0, :east
unit :thick_sludge, 525, 0, :east
unit :archer, 526, 0, :east
unit :archer, 529, 0, :east
unit :captive, 531, 0, :east
unit :thick_sludge, 532, 0, :east
unit :captive, 535, 0, :east
unit :captive, 540, 0, :east
unit :archer, 545, 0, :east
unit :sludge, 548, 0, :east
unit :wizard, 550, 0, :east
unit :thick_sludge, 555, 0, :east
unit :sludge, 560, 0, :east
unit :sludge, 561, 0, :east
unit :thick_sludge, 567, 0, :east
unit :thick_sludge, 574, 0, :east
unit :sludge, 578, 0, :east
unit :archer, 585, 0, :east
unit :wizard, 588, 0, :east
unit :wizard, 599, 0, :west
unit :archer, 603, 0, :west
unit :archer, 605, 0, :west
unit :sludge, 606, 0, :west
unit :sludge, 613, 0, :west
unit :sludge, 615, 0, :west
unit :sludge, 616, 0, :west
unit :captive, 617, 0, :west
unit :thick_sludge, 618, 0, :west
unit :thick_sludge, 623, 0, :west
unit :archer, 625, 0, :west
unit :archer, 626, 0, :west
unit :thick_sludge, 633, 0, :west
unit :thick_sludge, 638, 0, :west
unit :thick_sludge, 645, 0, :west
unit :archer, 654, 0, :west
unit :captive, 659, 0, :west
unit :wizard, 661, 0, :west
unit :wizard, 663, 0, :west
unit :thick_sludge, 666, 0, :west
unit :wizard, 680, 0, :west
unit :sludge, 684, 0, :west
unit :thick_sludge, 687, 0, :west
unit :sludge, 690, 0, :west
unit :archer, 695, 0, :west
unit :archer, 697, 0, :west
unit :sludge, 700, 0, :west
unit :archer, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :archer, 705, 0, :west
unit :wizard, 707, 0, :west
unit :sludge, 709, 0, :west
unit :wizard, 715, 0, :west
unit :archer, 721, 0, :west
unit :thick_sludge, 753, 0, :west
unit :archer, 757, 0, :west
unit :thick_sludge, 761, 0, :west
unit :archer, 762, 0, :west
unit :archer, 764, 0, :west
unit :wizard, 770, 0, :west
unit :thick_sludge, 772, 0, :west
unit :wizard, 774, 0, :west
unit :archer, 775, 0, :west
unit :thick_sludge, 777, 0, :west
unit :wizard, 782, 0, :west
unit :captive, 787, 0, :west
unit :thick_sludge, 788, 0, :west
unit :wizard, 790, 0, :west
unit :archer, 793, 0, :west
unit :archer, 795, 0, :west
