#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s    w     Ca      S   a  s w       w  S     s  S  S      s S        C   w    Ss w   S w    aS        C   C     SCSs  s ss w   a                     S C            s Cw a   Cw     C S           s >    @   a  aS       w      C     SS           s   sC   C   a   C S aws    s   CSS      Ss  s a     Sa     aa s         S wa  a     s  S  Sa S  Ss   wa wCa  S  s aC s     S  s      s CC  sC   a   Sw a    S  aC   w   s a S        S           C C   w          sa  sSS  a          s  w   C a a a a  s        w   CC         as      s       S                S     SC       S     S   S    a                S    C             C      a S   CS     s   aCaC   CC  C    S  S Sa S  C  sS         a as          s w   C    C    aS      s  w   S  w C w         C  S C wS S w   S  C   w   a   w           S           |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 799
ace_score 3995
size 799, 1
stairs 198, 0

warrior 203, 0, :east

unit :sludge, 2, 0, :east
unit :wizard, 7, 0, :east
unit :captive, 13, 0, :east
unit :archer, 14, 0, :east
unit :thick_sludge, 21, 0, :east
unit :archer, 25, 0, :east
unit :sludge, 28, 0, :east
unit :wizard, 30, 0, :east
unit :wizard, 38, 0, :east
unit :thick_sludge, 41, 0, :east
unit :sludge, 47, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 53, 0, :east
unit :sludge, 60, 0, :east
unit :thick_sludge, 62, 0, :east
unit :captive, 71, 0, :east
unit :wizard, 75, 0, :east
unit :thick_sludge, 80, 0, :east
unit :sludge, 81, 0, :east
unit :wizard, 83, 0, :east
unit :thick_sludge, 87, 0, :east
unit :wizard, 89, 0, :east
unit :archer, 94, 0, :east
unit :thick_sludge, 95, 0, :east
unit :captive, 104, 0, :east
unit :captive, 108, 0, :east
unit :thick_sludge, 114, 0, :east
unit :captive, 115, 0, :east
unit :thick_sludge, 116, 0, :east
unit :sludge, 117, 0, :east
unit :sludge, 120, 0, :east
unit :sludge, 122, 0, :east
unit :sludge, 123, 0, :east
unit :wizard, 125, 0, :east
unit :archer, 129, 0, :east
unit :thick_sludge, 151, 0, :east
unit :captive, 153, 0, :east
unit :sludge, 166, 0, :east
unit :captive, 168, 0, :east
unit :wizard, 169, 0, :east
unit :archer, 171, 0, :east
unit :captive, 175, 0, :east
unit :wizard, 176, 0, :east
unit :captive, 182, 0, :east
unit :thick_sludge, 184, 0, :east
unit :sludge, 196, 0, :east
unit :archer, 207, 0, :west
unit :archer, 210, 0, :west
unit :thick_sludge, 211, 0, :west
unit :wizard, 219, 0, :west
unit :captive, 226, 0, :west
unit :thick_sludge, 232, 0, :west
unit :thick_sludge, 233, 0, :west
unit :sludge, 245, 0, :west
unit :sludge, 249, 0, :west
unit :captive, 250, 0, :west
unit :captive, 254, 0, :west
unit :archer, 258, 0, :west
unit :captive, 262, 0, :west
unit :thick_sludge, 264, 0, :west
unit :archer, 266, 0, :west
unit :wizard, 267, 0, :west
unit :sludge, 268, 0, :west
unit :sludge, 273, 0, :west
unit :captive, 277, 0, :west
unit :thick_sludge, 278, 0, :west
unit :thick_sludge, 279, 0, :west
unit :thick_sludge, 286, 0, :west
unit :sludge, 287, 0, :west
unit :sludge, 290, 0, :west
unit :archer, 292, 0, :west
unit :thick_sludge, 298, 0, :west
unit :archer, 299, 0, :west
unit :archer, 305, 0, :west
unit :archer, 306, 0, :west
unit :sludge, 308, 0, :west
unit :thick_sludge, 318, 0, :west
unit :wizard, 320, 0, :west
unit :archer, 321, 0, :west
unit :archer, 324, 0, :west
unit :sludge, 330, 0, :west
unit :thick_sludge, 333, 0, :west
unit :thick_sludge, 336, 0, :west
unit :archer, 337, 0, :west
unit :thick_sludge, 339, 0, :west
unit :thick_sludge, 342, 0, :west
unit :sludge, 343, 0, :west
unit :wizard, 347, 0, :west
unit :archer, 348, 0, :west
unit :wizard, 350, 0, :west
unit :captive, 351, 0, :west
unit :archer, 352, 0, :west
unit :thick_sludge, 355, 0, :west
unit :sludge, 358, 0, :west
unit :archer, 360, 0, :west
unit :captive, 361, 0, :west
unit :sludge, 363, 0, :west
unit :thick_sludge, 369, 0, :west
unit :sludge, 372, 0, :west
unit :sludge, 379, 0, :west
unit :captive, 381, 0, :west
unit :captive, 382, 0, :west
unit :sludge, 385, 0, :west
unit :captive, 386, 0, :west
unit :archer, 390, 0, :west
unit :thick_sludge, 394, 0, :west
unit :wizard, 395, 0, :west
unit :archer, 397, 0, :west
unit :thick_sludge, 402, 0, :west
unit :archer, 405, 0, :west
unit :captive, 406, 0, :west
unit :wizard, 410, 0, :west
unit :sludge, 414, 0, :west
unit :archer, 416, 0, :west
unit :thick_sludge, 418, 0, :west
unit :thick_sludge, 427, 0, :west
unit :captive, 439, 0, :west
unit :captive, 441, 0, :west
unit :wizard, 445, 0, :west
unit :sludge, 456, 0, :west
unit :archer, 457, 0, :west
unit :sludge, 460, 0, :west
unit :thick_sludge, 461, 0, :west
unit :thick_sludge, 462, 0, :west
unit :archer, 465, 0, :west
unit :sludge, 476, 0, :west
unit :wizard, 479, 0, :west
unit :captive, 483, 0, :west
unit :archer, 485, 0, :west
unit :archer, 487, 0, :west
unit :archer, 489, 0, :west
unit :archer, 491, 0, :west
unit :sludge, 494, 0, :west
unit :wizard, 503, 0, :west
unit :captive, 507, 0, :west
unit :captive, 508, 0, :west
unit :archer, 518, 0, :west
unit :sludge, 519, 0, :west
unit :sludge, 526, 0, :west
unit :thick_sludge, 534, 0, :west
unit :thick_sludge, 551, 0, :west
unit :thick_sludge, 557, 0, :west
unit :captive, 558, 0, :west
unit :thick_sludge, 566, 0, :west
unit :thick_sludge, 572, 0, :west
unit :thick_sludge, 576, 0, :west
unit :archer, 581, 0, :west
unit :thick_sludge, 598, 0, :west
unit :captive, 603, 0, :west
unit :captive, 617, 0, :west
unit :archer, 624, 0, :west
unit :thick_sludge, 626, 0, :west
unit :captive, 630, 0, :west
unit :thick_sludge, 631, 0, :west
unit :sludge, 637, 0, :west
unit :archer, 641, 0, :west
unit :captive, 642, 0, :west
unit :archer, 643, 0, :west
unit :captive, 644, 0, :west
unit :captive, 648, 0, :west
unit :captive, 649, 0, :west
unit :captive, 652, 0, :west
unit :thick_sludge, 657, 0, :west
unit :thick_sludge, 660, 0, :west
unit :thick_sludge, 662, 0, :west
unit :archer, 663, 0, :west
unit :thick_sludge, 665, 0, :west
unit :captive, 668, 0, :west
unit :sludge, 671, 0, :west
unit :thick_sludge, 672, 0, :west
unit :archer, 682, 0, :west
unit :archer, 684, 0, :west
unit :sludge, 685, 0, :west
unit :sludge, 696, 0, :west
unit :wizard, 698, 0, :west
unit :captive, 702, 0, :west
unit :captive, 707, 0, :west
unit :archer, 712, 0, :west
unit :thick_sludge, 713, 0, :west
unit :sludge, 720, 0, :west
unit :wizard, 723, 0, :west
unit :thick_sludge, 727, 0, :west
unit :wizard, 730, 0, :west
unit :captive, 732, 0, :west
unit :wizard, 734, 0, :west
unit :captive, 744, 0, :west
unit :thick_sludge, 747, 0, :west
unit :captive, 749, 0, :west
unit :wizard, 751, 0, :west
unit :thick_sludge, 752, 0, :west
unit :thick_sludge, 754, 0, :west
unit :wizard, 756, 0, :west
unit :thick_sludge, 760, 0, :west
unit :captive, 763, 0, :west
unit :wizard, 767, 0, :west
unit :archer, 771, 0, :west
unit :wizard, 775, 0, :west
unit :thick_sludge, 787, 0, :west
