#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |S wC   w   sS           a w             w   >S  a w C   C sS  S w    C    a     sSS  C     aS   S  S  Sa s  C       sC    C          w w CC     w  C   S   SC  a   a   aw  C       a   w C C sa       s w a sa    w  wa C  w   aa    s        S    w a  CSa       s    w a a    s        a   w    S     S         w  S                             a   SSC   Cs C  C   CS    CC s   C      s   wS C w a    s w       a aC    sa     Ca          w   aaC    aa aa    a S   @    S  a   S   w        w               S     a   w        a S          C    a      s   a   sa   s   Ss  C  a SaSsw       C        s            s      w w  s       as  S    S         s       s aa       C   aC   a  s   s          s   C     S S  s S       a a     Ss   Ca w       w      C   s C  w  Cs w C     ws s          w       a  s    a w        C   w  C   |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 819
ace_score 4095
size 819, 1
stairs 44, 0

warrior 458, 0, :east

unit :thick_sludge, 0, 0, :east
unit :wizard, 2, 0, :east
unit :captive, 3, 0, :east
unit :wizard, 7, 0, :east
unit :sludge, 11, 0, :east
unit :thick_sludge, 12, 0, :east
unit :archer, 24, 0, :east
unit :wizard, 26, 0, :east
unit :wizard, 40, 0, :east
unit :thick_sludge, 45, 0, :east
unit :archer, 48, 0, :east
unit :wizard, 50, 0, :east
unit :captive, 52, 0, :east
unit :captive, 56, 0, :east
unit :sludge, 58, 0, :east
unit :thick_sludge, 59, 0, :east
unit :thick_sludge, 62, 0, :east
unit :wizard, 64, 0, :east
unit :captive, 69, 0, :east
unit :archer, 74, 0, :east
unit :sludge, 80, 0, :east
unit :thick_sludge, 81, 0, :east
unit :thick_sludge, 82, 0, :east
unit :captive, 85, 0, :east
unit :archer, 91, 0, :east
unit :thick_sludge, 92, 0, :east
unit :thick_sludge, 96, 0, :east
unit :thick_sludge, 99, 0, :east
unit :thick_sludge, 102, 0, :east
unit :archer, 103, 0, :east
unit :sludge, 105, 0, :east
unit :captive, 108, 0, :east
unit :sludge, 116, 0, :east
unit :captive, 117, 0, :east
unit :captive, 122, 0, :east
unit :wizard, 133, 0, :east
unit :wizard, 135, 0, :east
unit :captive, 137, 0, :east
unit :captive, 138, 0, :east
unit :wizard, 144, 0, :east
unit :captive, 147, 0, :east
unit :thick_sludge, 151, 0, :east
unit :thick_sludge, 155, 0, :east
unit :captive, 156, 0, :east
unit :archer, 159, 0, :east
unit :archer, 163, 0, :east
unit :archer, 167, 0, :east
unit :wizard, 168, 0, :east
unit :captive, 171, 0, :east
unit :archer, 179, 0, :east
unit :wizard, 183, 0, :east
unit :captive, 185, 0, :east
unit :captive, 187, 0, :east
unit :sludge, 189, 0, :east
unit :archer, 190, 0, :east
unit :sludge, 198, 0, :east
unit :wizard, 200, 0, :east
unit :archer, 202, 0, :east
unit :sludge, 204, 0, :east
unit :archer, 205, 0, :east
unit :wizard, 210, 0, :east
unit :wizard, 213, 0, :east
unit :archer, 214, 0, :east
unit :captive, 216, 0, :east
unit :wizard, 219, 0, :east
unit :archer, 223, 0, :east
unit :archer, 224, 0, :east
unit :sludge, 229, 0, :east
unit :thick_sludge, 238, 0, :east
unit :wizard, 243, 0, :east
unit :archer, 245, 0, :east
unit :captive, 248, 0, :east
unit :thick_sludge, 249, 0, :east
unit :archer, 250, 0, :east
unit :sludge, 258, 0, :east
unit :wizard, 263, 0, :east
unit :archer, 265, 0, :east
unit :archer, 267, 0, :east
unit :sludge, 272, 0, :east
unit :archer, 281, 0, :east
unit :wizard, 285, 0, :east
unit :thick_sludge, 290, 0, :east
unit :thick_sludge, 296, 0, :east
unit :wizard, 306, 0, :east
unit :thick_sludge, 309, 0, :east
unit :archer, 339, 0, :east
unit :thick_sludge, 343, 0, :east
unit :thick_sludge, 344, 0, :east
unit :captive, 345, 0, :east
unit :captive, 349, 0, :east
unit :sludge, 350, 0, :east
unit :captive, 352, 0, :east
unit :captive, 355, 0, :east
unit :captive, 359, 0, :east
unit :thick_sludge, 360, 0, :east
unit :captive, 365, 0, :east
unit :captive, 366, 0, :east
unit :sludge, 368, 0, :east
unit :captive, 372, 0, :east
unit :sludge, 379, 0, :east
unit :wizard, 383, 0, :east
unit :thick_sludge, 384, 0, :east
unit :captive, 386, 0, :east
unit :wizard, 388, 0, :east
unit :archer, 390, 0, :east
unit :sludge, 395, 0, :east
unit :wizard, 397, 0, :east
unit :archer, 405, 0, :east
unit :archer, 407, 0, :east
unit :captive, 408, 0, :east
unit :sludge, 413, 0, :east
unit :archer, 414, 0, :east
unit :captive, 420, 0, :east
unit :archer, 421, 0, :east
unit :wizard, 432, 0, :east
unit :archer, 436, 0, :east
unit :archer, 437, 0, :east
unit :captive, 438, 0, :east
unit :archer, 443, 0, :east
unit :archer, 444, 0, :east
unit :archer, 446, 0, :east
unit :archer, 447, 0, :east
unit :archer, 452, 0, :east
unit :thick_sludge, 454, 0, :east
unit :thick_sludge, 463, 0, :west
unit :archer, 466, 0, :west
unit :thick_sludge, 470, 0, :west
unit :wizard, 474, 0, :west
unit :wizard, 483, 0, :west
unit :thick_sludge, 499, 0, :west
unit :archer, 505, 0, :west
unit :wizard, 509, 0, :west
unit :archer, 518, 0, :west
unit :thick_sludge, 520, 0, :west
unit :captive, 531, 0, :west
unit :archer, 536, 0, :west
unit :sludge, 543, 0, :west
unit :archer, 547, 0, :west
unit :sludge, 551, 0, :west
unit :archer, 552, 0, :west
unit :sludge, 556, 0, :west
unit :thick_sludge, 560, 0, :west
unit :sludge, 561, 0, :west
unit :captive, 564, 0, :west
unit :archer, 567, 0, :west
unit :thick_sludge, 569, 0, :west
unit :archer, 570, 0, :west
unit :thick_sludge, 571, 0, :west
unit :sludge, 572, 0, :west
unit :wizard, 573, 0, :west
unit :captive, 581, 0, :west
unit :sludge, 590, 0, :west
unit :sludge, 603, 0, :west
unit :wizard, 610, 0, :west
unit :wizard, 612, 0, :west
unit :sludge, 615, 0, :west
unit :archer, 623, 0, :west
unit :sludge, 624, 0, :west
unit :thick_sludge, 627, 0, :west
unit :thick_sludge, 632, 0, :west
unit :sludge, 642, 0, :west
unit :sludge, 650, 0, :west
unit :archer, 652, 0, :west
unit :archer, 653, 0, :west
unit :captive, 661, 0, :west
unit :archer, 665, 0, :west
unit :captive, 666, 0, :west
unit :archer, 670, 0, :west
unit :sludge, 673, 0, :west
unit :sludge, 677, 0, :west
unit :sludge, 688, 0, :west
unit :captive, 692, 0, :west
unit :thick_sludge, 698, 0, :west
unit :thick_sludge, 700, 0, :west
unit :sludge, 703, 0, :west
unit :thick_sludge, 705, 0, :west
unit :archer, 713, 0, :west
unit :archer, 715, 0, :west
unit :thick_sludge, 721, 0, :west
unit :sludge, 722, 0, :west
unit :captive, 726, 0, :west
unit :archer, 727, 0, :west
unit :wizard, 729, 0, :west
unit :wizard, 737, 0, :west
unit :captive, 744, 0, :west
unit :sludge, 748, 0, :west
unit :captive, 750, 0, :west
unit :wizard, 753, 0, :west
unit :captive, 756, 0, :west
unit :sludge, 757, 0, :west
unit :wizard, 759, 0, :west
unit :captive, 761, 0, :west
unit :wizard, 767, 0, :west
unit :sludge, 768, 0, :west
unit :sludge, 770, 0, :west
unit :wizard, 781, 0, :west
unit :archer, 789, 0, :west
unit :sludge, 792, 0, :west
unit :archer, 797, 0, :west
unit :wizard, 799, 0, :west
unit :captive, 808, 0, :west
unit :wizard, 812, 0, :west
unit :captive, 815, 0, :west
