#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C      aw    s a C     a w s  S  w   a     s   S  Sss   w       Ss  a C           a    s            wC  S  s  w a     a  a          S SswC   s     w       SCs  w>  w             sa         C    s  w   S   Ss    s   S S   ss S       C    a  a w   a        S S C  a   CC       C  aw       w S   a  w    C S          s    s       C        a  C          w C     s    w  C      sa C          Cw   asC  C             a SS     SC S     w  w             S SC s   w   Ca     C       s       C   CS    C   Ss  C  s   aa    a    a               Sa     w   w   S s               s aw            a C   w       sa s    S  a     aCa  Sss S  a  C   a C     w C     CC  w  wCSa  S            a     s  w   aS  s       a  C   @   C   s          a w   S S   w    S S C     wa     s     a   S sC       C  a  wss a     a s       w  C as    C s   aS  aaw S    w       s    C |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 853
ace_score 4265
size 853, 1
stairs 162, 0

warrior 708, 0, :east

unit :captive, 1, 0, :east
unit :archer, 8, 0, :east
unit :wizard, 9, 0, :east
unit :sludge, 14, 0, :east
unit :archer, 16, 0, :east
unit :captive, 18, 0, :east
unit :archer, 24, 0, :east
unit :wizard, 26, 0, :east
unit :sludge, 28, 0, :east
unit :thick_sludge, 31, 0, :east
unit :wizard, 34, 0, :east
unit :archer, 38, 0, :east
unit :sludge, 44, 0, :east
unit :thick_sludge, 48, 0, :east
unit :thick_sludge, 51, 0, :east
unit :sludge, 52, 0, :east
unit :sludge, 53, 0, :east
unit :wizard, 57, 0, :east
unit :thick_sludge, 65, 0, :east
unit :sludge, 66, 0, :east
unit :archer, 69, 0, :east
unit :captive, 71, 0, :east
unit :archer, 83, 0, :east
unit :sludge, 88, 0, :east
unit :wizard, 101, 0, :east
unit :captive, 102, 0, :east
unit :thick_sludge, 105, 0, :east
unit :sludge, 108, 0, :east
unit :wizard, 111, 0, :east
unit :archer, 113, 0, :east
unit :archer, 119, 0, :east
unit :archer, 122, 0, :east
unit :thick_sludge, 133, 0, :east
unit :thick_sludge, 135, 0, :east
unit :sludge, 136, 0, :east
unit :wizard, 137, 0, :east
unit :captive, 138, 0, :east
unit :sludge, 142, 0, :east
unit :wizard, 148, 0, :east
unit :thick_sludge, 156, 0, :east
unit :captive, 157, 0, :east
unit :sludge, 158, 0, :east
unit :wizard, 161, 0, :east
unit :wizard, 165, 0, :east
unit :sludge, 179, 0, :east
unit :archer, 180, 0, :east
unit :captive, 190, 0, :east
unit :sludge, 195, 0, :east
unit :wizard, 198, 0, :east
unit :thick_sludge, 202, 0, :east
unit :thick_sludge, 206, 0, :east
unit :sludge, 207, 0, :east
unit :sludge, 212, 0, :east
unit :thick_sludge, 216, 0, :east
unit :thick_sludge, 218, 0, :east
unit :sludge, 222, 0, :east
unit :sludge, 223, 0, :east
unit :thick_sludge, 225, 0, :east
unit :captive, 233, 0, :east
unit :archer, 238, 0, :east
unit :archer, 241, 0, :east
unit :wizard, 243, 0, :east
unit :archer, 247, 0, :east
unit :thick_sludge, 256, 0, :east
unit :thick_sludge, 258, 0, :east
unit :captive, 260, 0, :east
unit :archer, 263, 0, :east
unit :captive, 267, 0, :east
unit :captive, 268, 0, :east
unit :captive, 276, 0, :east
unit :archer, 279, 0, :east
unit :wizard, 280, 0, :east
unit :wizard, 288, 0, :east
unit :thick_sludge, 290, 0, :east
unit :archer, 294, 0, :east
unit :wizard, 297, 0, :east
unit :captive, 302, 0, :east
unit :thick_sludge, 304, 0, :east
unit :sludge, 315, 0, :east
unit :sludge, 320, 0, :east
unit :captive, 328, 0, :east
unit :archer, 337, 0, :east
unit :captive, 340, 0, :east
unit :wizard, 351, 0, :east
unit :captive, 353, 0, :east
unit :sludge, 359, 0, :east
unit :wizard, 364, 0, :east
unit :captive, 367, 0, :east
unit :sludge, 374, 0, :east
unit :archer, 375, 0, :east
unit :captive, 377, 0, :east
unit :captive, 388, 0, :east
unit :wizard, 389, 0, :east
unit :archer, 393, 0, :east
unit :sludge, 394, 0, :east
unit :captive, 395, 0, :east
unit :captive, 398, 0, :east
unit :archer, 412, 0, :east
unit :thick_sludge, 414, 0, :east
unit :thick_sludge, 415, 0, :east
unit :thick_sludge, 421, 0, :east
unit :captive, 422, 0, :east
unit :thick_sludge, 424, 0, :east
unit :wizard, 430, 0, :east
unit :wizard, 433, 0, :east
unit :thick_sludge, 447, 0, :east
unit :thick_sludge, 449, 0, :east
unit :captive, 450, 0, :east
unit :sludge, 452, 0, :east
unit :wizard, 456, 0, :east
unit :captive, 460, 0, :east
unit :archer, 461, 0, :east
unit :captive, 467, 0, :east
unit :sludge, 475, 0, :east
unit :captive, 483, 0, :east
unit :captive, 487, 0, :east
unit :thick_sludge, 488, 0, :east
unit :captive, 493, 0, :east
unit :thick_sludge, 497, 0, :east
unit :sludge, 498, 0, :east
unit :captive, 501, 0, :east
unit :sludge, 504, 0, :east
unit :archer, 508, 0, :east
unit :archer, 509, 0, :east
unit :archer, 514, 0, :east
unit :archer, 519, 0, :east
unit :thick_sludge, 535, 0, :east
unit :archer, 536, 0, :east
unit :wizard, 542, 0, :east
unit :wizard, 546, 0, :east
unit :thick_sludge, 550, 0, :east
unit :sludge, 552, 0, :east
unit :sludge, 568, 0, :east
unit :archer, 570, 0, :east
unit :wizard, 571, 0, :east
unit :archer, 584, 0, :east
unit :captive, 586, 0, :east
unit :wizard, 590, 0, :east
unit :sludge, 598, 0, :east
unit :archer, 599, 0, :east
unit :sludge, 601, 0, :east
unit :thick_sludge, 606, 0, :east
unit :archer, 609, 0, :east
unit :archer, 615, 0, :east
unit :captive, 616, 0, :east
unit :archer, 617, 0, :east
unit :thick_sludge, 620, 0, :east
unit :sludge, 621, 0, :east
unit :sludge, 622, 0, :east
unit :thick_sludge, 624, 0, :east
unit :archer, 627, 0, :east
unit :captive, 630, 0, :east
unit :archer, 634, 0, :east
unit :captive, 636, 0, :east
unit :wizard, 642, 0, :east
unit :captive, 644, 0, :east
unit :captive, 650, 0, :east
unit :captive, 651, 0, :east
unit :wizard, 654, 0, :east
unit :wizard, 657, 0, :east
unit :captive, 658, 0, :east
unit :thick_sludge, 659, 0, :east
unit :archer, 660, 0, :east
unit :thick_sludge, 663, 0, :east
unit :archer, 676, 0, :east
unit :sludge, 682, 0, :east
unit :wizard, 685, 0, :east
unit :archer, 689, 0, :east
unit :thick_sludge, 690, 0, :east
unit :sludge, 693, 0, :east
unit :archer, 701, 0, :east
unit :captive, 704, 0, :east
unit :captive, 712, 0, :west
unit :sludge, 716, 0, :west
unit :archer, 727, 0, :west
unit :wizard, 729, 0, :west
unit :thick_sludge, 733, 0, :west
unit :thick_sludge, 735, 0, :west
unit :wizard, 739, 0, :west
unit :thick_sludge, 744, 0, :west
unit :thick_sludge, 746, 0, :west
unit :captive, 748, 0, :west
unit :wizard, 754, 0, :west
unit :archer, 755, 0, :west
unit :sludge, 761, 0, :west
unit :archer, 767, 0, :west
unit :thick_sludge, 771, 0, :west
unit :sludge, 773, 0, :west
unit :captive, 774, 0, :west
unit :captive, 782, 0, :west
unit :archer, 785, 0, :west
unit :wizard, 788, 0, :west
unit :sludge, 789, 0, :west
unit :sludge, 790, 0, :west
unit :archer, 792, 0, :west
unit :archer, 798, 0, :west
unit :sludge, 800, 0, :west
unit :wizard, 808, 0, :west
unit :captive, 811, 0, :west
unit :archer, 813, 0, :west
unit :sludge, 814, 0, :west
unit :captive, 819, 0, :west
unit :sludge, 821, 0, :west
unit :archer, 825, 0, :west
unit :thick_sludge, 826, 0, :west
unit :archer, 829, 0, :west
unit :archer, 830, 0, :west
unit :wizard, 831, 0, :west
unit :thick_sludge, 833, 0, :west
unit :wizard, 838, 0, :west
unit :sludge, 846, 0, :west
unit :captive, 851, 0, :west
