#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     a ws w  sa  s  w              a w   w a     a     sC        a C       S a       S  ssC   s         @   C    s S  w      >   w    C               s a     S  C   a    w C  C     C w a w      C   S s  a w s C CCs a  w  as  w S  a   sC aa  w   C SSs      s s    C     s         C   aS     s C a sw aw  S  s s    Cs sC   a  S a          Sa         w   S    S      C    C     C       S  a aS   C   a        wCC  SSs  w a           C           C a     S    s    w        a  a   w a        CwsS    s            a  sS S   a       S  a              w C                  s  a S S s   S     |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 584
ace_score 2920
size 584, 1
stairs 125, 0

warrior 104, 0, :east

unit :archer, 5, 0, :east
unit :wizard, 7, 0, :east
unit :sludge, 8, 0, :east
unit :wizard, 10, 0, :east
unit :sludge, 13, 0, :east
unit :archer, 14, 0, :east
unit :sludge, 17, 0, :east
unit :wizard, 20, 0, :east
unit :archer, 35, 0, :east
unit :wizard, 37, 0, :east
unit :wizard, 41, 0, :east
unit :archer, 43, 0, :east
unit :archer, 49, 0, :east
unit :sludge, 55, 0, :east
unit :captive, 56, 0, :east
unit :archer, 65, 0, :east
unit :captive, 67, 0, :east
unit :thick_sludge, 75, 0, :east
unit :archer, 77, 0, :east
unit :thick_sludge, 85, 0, :east
unit :sludge, 88, 0, :east
unit :sludge, 89, 0, :east
unit :captive, 90, 0, :east
unit :sludge, 94, 0, :east
unit :captive, 108, 0, :west
unit :sludge, 113, 0, :west
unit :thick_sludge, 115, 0, :west
unit :wizard, 118, 0, :west
unit :wizard, 129, 0, :west
unit :captive, 134, 0, :west
unit :sludge, 150, 0, :west
unit :archer, 152, 0, :west
unit :thick_sludge, 158, 0, :west
unit :captive, 161, 0, :west
unit :archer, 165, 0, :west
unit :wizard, 170, 0, :west
unit :captive, 172, 0, :west
unit :captive, 175, 0, :west
unit :captive, 181, 0, :west
unit :wizard, 183, 0, :west
unit :archer, 185, 0, :west
unit :wizard, 187, 0, :west
unit :captive, 194, 0, :west
unit :thick_sludge, 198, 0, :west
unit :sludge, 200, 0, :west
unit :archer, 203, 0, :west
unit :wizard, 205, 0, :west
unit :sludge, 207, 0, :west
unit :captive, 209, 0, :west
unit :captive, 211, 0, :west
unit :captive, 212, 0, :west
unit :sludge, 213, 0, :west
unit :archer, 215, 0, :west
unit :wizard, 218, 0, :west
unit :archer, 221, 0, :west
unit :sludge, 222, 0, :west
unit :wizard, 225, 0, :west
unit :thick_sludge, 227, 0, :west
unit :archer, 230, 0, :west
unit :sludge, 234, 0, :west
unit :captive, 235, 0, :west
unit :archer, 237, 0, :west
unit :archer, 238, 0, :west
unit :wizard, 241, 0, :west
unit :captive, 245, 0, :west
unit :thick_sludge, 247, 0, :west
unit :thick_sludge, 248, 0, :west
unit :sludge, 249, 0, :west
unit :sludge, 256, 0, :west
unit :sludge, 258, 0, :west
unit :captive, 263, 0, :west
unit :sludge, 269, 0, :west
unit :captive, 279, 0, :west
unit :archer, 283, 0, :west
unit :thick_sludge, 284, 0, :west
unit :sludge, 290, 0, :west
unit :captive, 292, 0, :west
unit :archer, 294, 0, :west
unit :sludge, 296, 0, :west
unit :wizard, 297, 0, :west
unit :archer, 299, 0, :west
unit :wizard, 300, 0, :west
unit :thick_sludge, 303, 0, :west
unit :sludge, 306, 0, :west
unit :sludge, 308, 0, :west
unit :captive, 313, 0, :west
unit :sludge, 314, 0, :west
unit :sludge, 316, 0, :west
unit :captive, 317, 0, :west
unit :archer, 321, 0, :west
unit :thick_sludge, 324, 0, :west
unit :archer, 326, 0, :west
unit :thick_sludge, 337, 0, :west
unit :archer, 338, 0, :west
unit :wizard, 348, 0, :west
unit :thick_sludge, 352, 0, :west
unit :thick_sludge, 357, 0, :west
unit :captive, 364, 0, :west
unit :captive, 369, 0, :west
unit :captive, 375, 0, :west
unit :thick_sludge, 383, 0, :west
unit :archer, 386, 0, :west
unit :archer, 388, 0, :west
unit :thick_sludge, 389, 0, :west
unit :captive, 393, 0, :west
unit :archer, 397, 0, :west
unit :wizard, 406, 0, :west
unit :captive, 407, 0, :west
unit :captive, 408, 0, :west
unit :thick_sludge, 411, 0, :west
unit :thick_sludge, 412, 0, :west
unit :sludge, 413, 0, :west
unit :wizard, 416, 0, :west
unit :archer, 418, 0, :west
unit :captive, 430, 0, :west
unit :captive, 442, 0, :west
unit :archer, 444, 0, :west
unit :thick_sludge, 450, 0, :west
unit :sludge, 455, 0, :west
unit :wizard, 460, 0, :west
unit :archer, 469, 0, :west
unit :archer, 472, 0, :west
unit :wizard, 476, 0, :west
unit :archer, 478, 0, :west
unit :captive, 487, 0, :west
unit :wizard, 488, 0, :west
unit :sludge, 489, 0, :west
unit :thick_sludge, 490, 0, :west
unit :sludge, 495, 0, :west
unit :archer, 508, 0, :west
unit :sludge, 511, 0, :west
unit :thick_sludge, 512, 0, :west
unit :thick_sludge, 514, 0, :west
unit :archer, 518, 0, :west
unit :thick_sludge, 526, 0, :west
unit :archer, 529, 0, :west
unit :wizard, 544, 0, :west
unit :captive, 546, 0, :west
unit :sludge, 565, 0, :west
unit :archer, 568, 0, :west
unit :thick_sludge, 570, 0, :west
unit :thick_sludge, 572, 0, :west
unit :sludge, 574, 0, :west
unit :thick_sludge, 578, 0, :west
