#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      s     s     aw C  C       s        >a      a  S       CS      sC   SC  CC      w         s             w w C wa      C   S  sCS   Sw   as    C  sS        Ss  w S w      C   sa  a     C   w    S   a    SCa        w     w C       Sa s   S     S          sa   sa  s   C CC aaS C                     w   CaS   s s   s  w  C C     C       S   s      w   a C  a w   a       s  a w w wa C        wS  C  S          s          a    w SCS C  a    w        a       a S C w  S    aaS        S a    w  wa C   w        w  @   s   S  C      SsSs       C     C          s s  s    a  C   a S    Cw        S a S       Ca  C    S        a  aC     sSa          |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 647
ace_score 3235
size 647, 1
stairs 41, 0

warrior 514, 0, :east

unit :sludge, 6, 0, :east
unit :sludge, 12, 0, :east
unit :archer, 18, 0, :east
unit :wizard, 19, 0, :east
unit :captive, 21, 0, :east
unit :captive, 24, 0, :east
unit :sludge, 32, 0, :east
unit :archer, 42, 0, :east
unit :archer, 49, 0, :east
unit :thick_sludge, 52, 0, :east
unit :captive, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :sludge, 68, 0, :east
unit :captive, 69, 0, :east
unit :thick_sludge, 73, 0, :east
unit :captive, 74, 0, :east
unit :captive, 77, 0, :east
unit :captive, 78, 0, :east
unit :wizard, 85, 0, :east
unit :sludge, 95, 0, :east
unit :wizard, 109, 0, :east
unit :wizard, 111, 0, :east
unit :captive, 113, 0, :east
unit :wizard, 115, 0, :east
unit :archer, 116, 0, :east
unit :captive, 123, 0, :east
unit :thick_sludge, 127, 0, :east
unit :sludge, 130, 0, :east
unit :captive, 131, 0, :east
unit :thick_sludge, 132, 0, :east
unit :thick_sludge, 136, 0, :east
unit :wizard, 137, 0, :east
unit :archer, 141, 0, :east
unit :sludge, 142, 0, :east
unit :captive, 147, 0, :east
unit :sludge, 150, 0, :east
unit :thick_sludge, 151, 0, :east
unit :thick_sludge, 160, 0, :east
unit :sludge, 161, 0, :east
unit :wizard, 164, 0, :east
unit :thick_sludge, 166, 0, :east
unit :wizard, 168, 0, :east
unit :captive, 175, 0, :east
unit :sludge, 179, 0, :east
unit :archer, 180, 0, :east
unit :archer, 183, 0, :east
unit :captive, 189, 0, :east
unit :wizard, 193, 0, :east
unit :thick_sludge, 198, 0, :east
unit :archer, 202, 0, :east
unit :thick_sludge, 207, 0, :east
unit :captive, 208, 0, :east
unit :archer, 209, 0, :east
unit :wizard, 218, 0, :east
unit :wizard, 224, 0, :east
unit :captive, 226, 0, :east
unit :thick_sludge, 234, 0, :east
unit :archer, 235, 0, :east
unit :sludge, 237, 0, :east
unit :thick_sludge, 241, 0, :east
unit :thick_sludge, 247, 0, :east
unit :sludge, 258, 0, :east
unit :archer, 259, 0, :east
unit :sludge, 263, 0, :east
unit :archer, 264, 0, :east
unit :sludge, 267, 0, :east
unit :captive, 271, 0, :east
unit :captive, 273, 0, :east
unit :captive, 274, 0, :east
unit :archer, 276, 0, :east
unit :archer, 277, 0, :east
unit :thick_sludge, 278, 0, :east
unit :captive, 280, 0, :east
unit :wizard, 302, 0, :east
unit :captive, 306, 0, :east
unit :archer, 307, 0, :east
unit :thick_sludge, 308, 0, :east
unit :sludge, 312, 0, :east
unit :sludge, 314, 0, :east
unit :sludge, 318, 0, :east
unit :wizard, 321, 0, :east
unit :captive, 324, 0, :east
unit :captive, 326, 0, :east
unit :captive, 332, 0, :east
unit :thick_sludge, 340, 0, :east
unit :sludge, 344, 0, :east
unit :wizard, 351, 0, :east
unit :archer, 355, 0, :east
unit :captive, 357, 0, :east
unit :archer, 360, 0, :east
unit :wizard, 362, 0, :east
unit :archer, 366, 0, :east
unit :sludge, 374, 0, :east
unit :archer, 377, 0, :east
unit :wizard, 379, 0, :east
unit :wizard, 381, 0, :east
unit :wizard, 383, 0, :east
unit :archer, 384, 0, :east
unit :captive, 386, 0, :east
unit :wizard, 395, 0, :east
unit :thick_sludge, 396, 0, :east
unit :captive, 399, 0, :east
unit :thick_sludge, 402, 0, :east
unit :sludge, 413, 0, :east
unit :archer, 424, 0, :east
unit :wizard, 429, 0, :east
unit :thick_sludge, 431, 0, :east
unit :captive, 432, 0, :east
unit :thick_sludge, 433, 0, :east
unit :captive, 435, 0, :east
unit :archer, 438, 0, :east
unit :wizard, 443, 0, :east
unit :archer, 452, 0, :east
unit :archer, 460, 0, :east
unit :thick_sludge, 462, 0, :east
unit :captive, 464, 0, :east
unit :wizard, 466, 0, :east
unit :thick_sludge, 469, 0, :east
unit :archer, 474, 0, :east
unit :archer, 475, 0, :east
unit :thick_sludge, 476, 0, :east
unit :thick_sludge, 485, 0, :east
unit :archer, 487, 0, :east
unit :wizard, 492, 0, :east
unit :wizard, 495, 0, :east
unit :archer, 496, 0, :east
unit :captive, 498, 0, :east
unit :wizard, 502, 0, :east
unit :wizard, 511, 0, :east
unit :sludge, 518, 0, :west
unit :thick_sludge, 522, 0, :west
unit :captive, 525, 0, :west
unit :thick_sludge, 532, 0, :west
unit :sludge, 533, 0, :west
unit :thick_sludge, 534, 0, :west
unit :sludge, 535, 0, :west
unit :captive, 543, 0, :west
unit :captive, 549, 0, :west
unit :sludge, 560, 0, :west
unit :sludge, 562, 0, :west
unit :sludge, 565, 0, :west
unit :archer, 570, 0, :west
unit :captive, 573, 0, :west
unit :archer, 577, 0, :west
unit :thick_sludge, 579, 0, :west
unit :captive, 584, 0, :west
unit :wizard, 585, 0, :west
unit :thick_sludge, 594, 0, :west
unit :archer, 596, 0, :west
unit :thick_sludge, 598, 0, :west
unit :captive, 606, 0, :west
unit :archer, 607, 0, :west
unit :captive, 610, 0, :west
unit :thick_sludge, 615, 0, :west
unit :archer, 624, 0, :west
unit :archer, 627, 0, :west
unit :captive, 628, 0, :west
unit :sludge, 634, 0, :west
unit :thick_sludge, 635, 0, :west
unit :archer, 636, 0, :west
