#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |Saw  S   sa a w  S C  S          >   s w  w     C              a S     S      C C  S  a         wS  C   s    C    C C  S   s  a s     s   w       CS  a  Sa s    C  s C a  Cs     a      a  CCa  S    C w     @        S C C s          s  s  S        a       a     a  a swS      C w     S  C   C sC  s              C    w S   S  a     s  Sa             w  w   sa   a s sa s     SS    S  SC  a  a    C   w   w          CS s  C         s  s      w SC w  S C  sC a s         Ca   a   as          C     S        sS      s    a     s  S   C         w               s       w     w  Sw   w   C S a awC       C   w   S     S       sCs C  w         a   w s     w     S   w  S              aa    S  a         C sC     w   Ca a  S  S ss  w  a CC         s  s       a S       SC   s    w   S a      a    a S  w w   a sS    C  S   w |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 817
ace_score 4085
size 817, 1
stairs 33, 0

warrior 206, 0, :east

unit :thick_sludge, 0, 0, :east
unit :archer, 1, 0, :east
unit :wizard, 2, 0, :east
unit :thick_sludge, 5, 0, :east
unit :sludge, 9, 0, :east
unit :archer, 10, 0, :east
unit :archer, 12, 0, :east
unit :wizard, 14, 0, :east
unit :thick_sludge, 17, 0, :east
unit :captive, 19, 0, :east
unit :thick_sludge, 22, 0, :east
unit :sludge, 37, 0, :east
unit :wizard, 39, 0, :east
unit :wizard, 42, 0, :east
unit :captive, 48, 0, :east
unit :archer, 63, 0, :east
unit :thick_sludge, 65, 0, :east
unit :thick_sludge, 71, 0, :east
unit :captive, 78, 0, :east
unit :captive, 80, 0, :east
unit :thick_sludge, 83, 0, :east
unit :archer, 86, 0, :east
unit :wizard, 96, 0, :east
unit :thick_sludge, 97, 0, :east
unit :captive, 100, 0, :east
unit :sludge, 104, 0, :east
unit :captive, 109, 0, :east
unit :captive, 114, 0, :east
unit :captive, 116, 0, :east
unit :thick_sludge, 119, 0, :east
unit :sludge, 123, 0, :east
unit :archer, 126, 0, :east
unit :sludge, 128, 0, :east
unit :sludge, 134, 0, :east
unit :wizard, 138, 0, :east
unit :captive, 146, 0, :east
unit :thick_sludge, 147, 0, :east
unit :archer, 150, 0, :east
unit :thick_sludge, 153, 0, :east
unit :archer, 154, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 161, 0, :east
unit :sludge, 164, 0, :east
unit :captive, 166, 0, :east
unit :archer, 168, 0, :east
unit :captive, 171, 0, :east
unit :sludge, 172, 0, :east
unit :archer, 178, 0, :east
unit :archer, 185, 0, :east
unit :captive, 188, 0, :east
unit :captive, 189, 0, :east
unit :archer, 190, 0, :east
unit :thick_sludge, 193, 0, :east
unit :captive, 198, 0, :east
unit :wizard, 200, 0, :east
unit :thick_sludge, 215, 0, :west
unit :captive, 217, 0, :west
unit :captive, 219, 0, :west
unit :sludge, 221, 0, :west
unit :sludge, 232, 0, :west
unit :sludge, 235, 0, :west
unit :thick_sludge, 238, 0, :west
unit :archer, 247, 0, :west
unit :archer, 255, 0, :west
unit :archer, 261, 0, :west
unit :archer, 264, 0, :west
unit :sludge, 266, 0, :west
unit :wizard, 267, 0, :west
unit :thick_sludge, 268, 0, :west
unit :captive, 275, 0, :west
unit :wizard, 277, 0, :west
unit :thick_sludge, 283, 0, :west
unit :captive, 286, 0, :west
unit :captive, 290, 0, :west
unit :sludge, 292, 0, :west
unit :captive, 293, 0, :west
unit :sludge, 296, 0, :west
unit :captive, 311, 0, :west
unit :wizard, 316, 0, :west
unit :thick_sludge, 318, 0, :west
unit :thick_sludge, 322, 0, :west
unit :archer, 325, 0, :west
unit :sludge, 331, 0, :west
unit :thick_sludge, 334, 0, :west
unit :archer, 335, 0, :west
unit :wizard, 349, 0, :west
unit :wizard, 352, 0, :west
unit :sludge, 356, 0, :west
unit :archer, 357, 0, :west
unit :archer, 361, 0, :west
unit :sludge, 363, 0, :west
unit :sludge, 365, 0, :west
unit :archer, 366, 0, :west
unit :sludge, 368, 0, :west
unit :thick_sludge, 374, 0, :west
unit :thick_sludge, 375, 0, :west
unit :thick_sludge, 380, 0, :west
unit :thick_sludge, 383, 0, :west
unit :captive, 384, 0, :west
unit :archer, 387, 0, :west
unit :archer, 390, 0, :west
unit :captive, 395, 0, :west
unit :wizard, 399, 0, :west
unit :wizard, 403, 0, :west
unit :captive, 414, 0, :west
unit :thick_sludge, 415, 0, :west
unit :sludge, 417, 0, :west
unit :captive, 420, 0, :west
unit :sludge, 430, 0, :west
unit :sludge, 433, 0, :west
unit :wizard, 440, 0, :west
unit :thick_sludge, 442, 0, :west
unit :captive, 443, 0, :west
unit :wizard, 445, 0, :west
unit :thick_sludge, 448, 0, :west
unit :captive, 450, 0, :west
unit :sludge, 453, 0, :west
unit :captive, 454, 0, :west
unit :archer, 456, 0, :west
unit :sludge, 458, 0, :west
unit :captive, 468, 0, :west
unit :archer, 469, 0, :west
unit :archer, 473, 0, :west
unit :archer, 477, 0, :west
unit :sludge, 478, 0, :west
unit :captive, 489, 0, :west
unit :thick_sludge, 495, 0, :west
unit :sludge, 504, 0, :west
unit :thick_sludge, 505, 0, :west
unit :sludge, 512, 0, :west
unit :archer, 517, 0, :west
unit :sludge, 523, 0, :west
unit :thick_sludge, 526, 0, :west
unit :captive, 530, 0, :west
unit :wizard, 540, 0, :west
unit :sludge, 556, 0, :west
unit :wizard, 564, 0, :west
unit :wizard, 570, 0, :west
unit :thick_sludge, 573, 0, :west
unit :wizard, 574, 0, :west
unit :wizard, 578, 0, :west
unit :captive, 582, 0, :west
unit :thick_sludge, 584, 0, :west
unit :archer, 586, 0, :west
unit :archer, 588, 0, :west
unit :wizard, 589, 0, :west
unit :captive, 590, 0, :west
unit :captive, 598, 0, :west
unit :wizard, 602, 0, :west
unit :thick_sludge, 606, 0, :west
unit :thick_sludge, 612, 0, :west
unit :sludge, 620, 0, :west
unit :captive, 621, 0, :west
unit :sludge, 622, 0, :west
unit :captive, 624, 0, :west
unit :wizard, 627, 0, :west
unit :archer, 637, 0, :west
unit :wizard, 641, 0, :west
unit :sludge, 643, 0, :west
unit :wizard, 649, 0, :west
unit :thick_sludge, 655, 0, :west
unit :wizard, 659, 0, :west
unit :thick_sludge, 662, 0, :west
unit :archer, 677, 0, :west
unit :archer, 678, 0, :west
unit :thick_sludge, 683, 0, :west
unit :archer, 686, 0, :west
unit :captive, 696, 0, :west
unit :sludge, 698, 0, :west
unit :captive, 699, 0, :west
unit :wizard, 705, 0, :west
unit :captive, 709, 0, :west
unit :archer, 710, 0, :west
unit :archer, 712, 0, :west
unit :thick_sludge, 715, 0, :west
unit :thick_sludge, 718, 0, :west
unit :sludge, 720, 0, :west
unit :sludge, 721, 0, :west
unit :wizard, 724, 0, :west
unit :archer, 727, 0, :west
unit :captive, 729, 0, :west
unit :captive, 730, 0, :west
unit :sludge, 740, 0, :west
unit :sludge, 743, 0, :west
unit :archer, 751, 0, :west
unit :thick_sludge, 753, 0, :west
unit :thick_sludge, 761, 0, :west
unit :captive, 762, 0, :west
unit :sludge, 766, 0, :west
unit :wizard, 771, 0, :west
unit :thick_sludge, 775, 0, :west
unit :archer, 777, 0, :west
unit :archer, 784, 0, :west
unit :archer, 789, 0, :west
unit :thick_sludge, 791, 0, :west
unit :wizard, 794, 0, :west
unit :wizard, 796, 0, :west
unit :archer, 800, 0, :west
unit :sludge, 802, 0, :west
unit :thick_sludge, 803, 0, :west
unit :captive, 808, 0, :west
unit :thick_sludge, 811, 0, :west
unit :wizard, 815, 0, :west
