#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   C s C  S       w w s  a SC   s Cas  s  s    C  w  a  a    a            a       w        s     w    a  C  sa      a  S  w s  S    C a sa       sSa  S     S         C      aw  s    a      a        S S            as a  wC  S      C Cs C w a                     s sa C Sa w s   a  s a   w s a  C  Csw   w  Cw  C       saa   S   w a Sw   s     a C    a    w      s   a     @       w w  a  a    s a S a            a C      s     CC  s     aw   s          s   waC  S   C     w as  aw C   s        a         s    w    a  C    aws      CC   s           C     s     aa       a   a            w    w s         s sa   a  C C       a      S   S        a     S   sss    w        w  ws      w    w   a    w SS  C w S  C       s          s >a    s  C    s S  aw s  s C C  w   Sa              S S      C     C     C     C sa    a      S     s a sS  s  S  a      s   sC C    wC a a     C C              a   w   w  C       Ss        C   S  SC C     a     C S    w   a    C    SC    |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 966
ace_score 4830
size 966, 1
stairs 727, 0

warrior 371, 0, :east

unit :captive, 3, 0, :east
unit :sludge, 5, 0, :east
unit :captive, 7, 0, :east
unit :thick_sludge, 10, 0, :east
unit :wizard, 18, 0, :east
unit :wizard, 20, 0, :east
unit :sludge, 22, 0, :east
unit :archer, 25, 0, :east
unit :thick_sludge, 27, 0, :east
unit :captive, 28, 0, :east
unit :sludge, 32, 0, :east
unit :captive, 34, 0, :east
unit :archer, 35, 0, :east
unit :sludge, 36, 0, :east
unit :sludge, 39, 0, :east
unit :sludge, 42, 0, :east
unit :captive, 47, 0, :east
unit :wizard, 50, 0, :east
unit :archer, 53, 0, :east
unit :archer, 56, 0, :east
unit :archer, 61, 0, :east
unit :archer, 74, 0, :east
unit :wizard, 82, 0, :east
unit :sludge, 91, 0, :east
unit :wizard, 97, 0, :east
unit :archer, 102, 0, :east
unit :captive, 105, 0, :east
unit :sludge, 108, 0, :east
unit :archer, 109, 0, :east
unit :archer, 116, 0, :east
unit :thick_sludge, 119, 0, :east
unit :wizard, 122, 0, :east
unit :sludge, 124, 0, :east
unit :thick_sludge, 127, 0, :east
unit :captive, 132, 0, :east
unit :archer, 134, 0, :east
unit :sludge, 136, 0, :east
unit :archer, 137, 0, :east
unit :sludge, 145, 0, :east
unit :thick_sludge, 146, 0, :east
unit :archer, 147, 0, :east
unit :thick_sludge, 150, 0, :east
unit :thick_sludge, 156, 0, :east
unit :captive, 166, 0, :east
unit :archer, 173, 0, :east
unit :wizard, 174, 0, :east
unit :sludge, 177, 0, :east
unit :archer, 182, 0, :east
unit :archer, 189, 0, :east
unit :thick_sludge, 198, 0, :east
unit :thick_sludge, 200, 0, :east
unit :archer, 213, 0, :east
unit :sludge, 214, 0, :east
unit :archer, 216, 0, :east
unit :wizard, 219, 0, :east
unit :captive, 220, 0, :east
unit :thick_sludge, 223, 0, :east
unit :captive, 230, 0, :east
unit :captive, 232, 0, :east
unit :sludge, 233, 0, :east
unit :captive, 235, 0, :east
unit :wizard, 237, 0, :east
unit :archer, 239, 0, :east
unit :sludge, 261, 0, :east
unit :sludge, 263, 0, :east
unit :archer, 264, 0, :east
unit :captive, 266, 0, :east
unit :thick_sludge, 268, 0, :east
unit :archer, 269, 0, :east
unit :wizard, 271, 0, :east
unit :sludge, 273, 0, :east
unit :archer, 277, 0, :east
unit :sludge, 280, 0, :east
unit :archer, 282, 0, :east
unit :wizard, 286, 0, :east
unit :sludge, 288, 0, :east
unit :archer, 290, 0, :east
unit :captive, 293, 0, :east
unit :captive, 296, 0, :east
unit :sludge, 297, 0, :east
unit :wizard, 298, 0, :east
unit :wizard, 302, 0, :east
unit :captive, 305, 0, :east
unit :wizard, 306, 0, :east
unit :captive, 309, 0, :east
unit :sludge, 317, 0, :east
unit :archer, 318, 0, :east
unit :archer, 319, 0, :east
unit :thick_sludge, 323, 0, :east
unit :wizard, 327, 0, :east
unit :archer, 329, 0, :east
unit :thick_sludge, 331, 0, :east
unit :wizard, 332, 0, :east
unit :sludge, 336, 0, :east
unit :archer, 342, 0, :east
unit :captive, 344, 0, :east
unit :archer, 349, 0, :east
unit :wizard, 354, 0, :east
unit :sludge, 361, 0, :east
unit :archer, 365, 0, :east
unit :wizard, 379, 0, :west
unit :wizard, 381, 0, :west
unit :archer, 384, 0, :west
unit :archer, 387, 0, :west
unit :sludge, 392, 0, :west
unit :archer, 394, 0, :west
unit :thick_sludge, 396, 0, :west
unit :archer, 398, 0, :west
unit :archer, 411, 0, :west
unit :captive, 413, 0, :west
unit :sludge, 420, 0, :west
unit :captive, 426, 0, :west
unit :captive, 427, 0, :west
unit :sludge, 430, 0, :west
unit :archer, 436, 0, :west
unit :wizard, 437, 0, :west
unit :sludge, 441, 0, :west
unit :sludge, 452, 0, :west
unit :wizard, 456, 0, :west
unit :archer, 457, 0, :west
unit :captive, 458, 0, :west
unit :thick_sludge, 461, 0, :west
unit :captive, 465, 0, :west
unit :wizard, 471, 0, :west
unit :archer, 473, 0, :west
unit :sludge, 474, 0, :west
unit :archer, 477, 0, :west
unit :wizard, 478, 0, :west
unit :captive, 480, 0, :west
unit :sludge, 484, 0, :west
unit :archer, 493, 0, :west
unit :sludge, 503, 0, :west
unit :wizard, 508, 0, :west
unit :archer, 513, 0, :west
unit :captive, 516, 0, :west
unit :archer, 521, 0, :west
unit :wizard, 522, 0, :west
unit :sludge, 523, 0, :west
unit :captive, 530, 0, :west
unit :captive, 531, 0, :west
unit :sludge, 535, 0, :west
unit :captive, 547, 0, :west
unit :sludge, 553, 0, :west
unit :archer, 559, 0, :west
unit :archer, 560, 0, :west
unit :archer, 568, 0, :west
unit :archer, 572, 0, :west
unit :wizard, 585, 0, :west
unit :wizard, 590, 0, :west
unit :sludge, 592, 0, :west
unit :sludge, 602, 0, :west
unit :sludge, 604, 0, :west
unit :archer, 605, 0, :west
unit :archer, 609, 0, :west
unit :captive, 612, 0, :west
unit :captive, 614, 0, :west
unit :archer, 622, 0, :west
unit :thick_sludge, 629, 0, :west
unit :thick_sludge, 633, 0, :west
unit :archer, 642, 0, :west
unit :thick_sludge, 648, 0, :west
unit :sludge, 652, 0, :west
unit :sludge, 653, 0, :west
unit :sludge, 654, 0, :west
unit :wizard, 659, 0, :west
unit :wizard, 668, 0, :west
unit :wizard, 671, 0, :west
unit :sludge, 672, 0, :west
unit :wizard, 679, 0, :west
unit :wizard, 684, 0, :west
unit :archer, 688, 0, :west
unit :wizard, 693, 0, :west
unit :thick_sludge, 695, 0, :west
unit :thick_sludge, 696, 0, :west
unit :captive, 699, 0, :west
unit :wizard, 701, 0, :west
unit :thick_sludge, 703, 0, :west
unit :captive, 706, 0, :west
unit :sludge, 714, 0, :west
unit :sludge, 725, 0, :west
unit :archer, 728, 0, :west
unit :sludge, 733, 0, :west
unit :captive, 736, 0, :west
unit :sludge, 741, 0, :west
unit :thick_sludge, 743, 0, :west
unit :archer, 746, 0, :west
unit :wizard, 747, 0, :west
unit :sludge, 749, 0, :west
unit :sludge, 752, 0, :west
unit :captive, 754, 0, :west
unit :captive, 756, 0, :west
unit :wizard, 759, 0, :west
unit :thick_sludge, 763, 0, :west
unit :archer, 764, 0, :west
unit :thick_sludge, 779, 0, :west
unit :thick_sludge, 781, 0, :west
unit :captive, 788, 0, :west
unit :captive, 794, 0, :west
unit :captive, 800, 0, :west
unit :captive, 806, 0, :west
unit :sludge, 808, 0, :west
unit :archer, 809, 0, :west
unit :archer, 814, 0, :west
unit :thick_sludge, 821, 0, :west
unit :sludge, 827, 0, :west
unit :archer, 829, 0, :west
unit :sludge, 831, 0, :west
unit :thick_sludge, 832, 0, :west
unit :sludge, 835, 0, :west
unit :thick_sludge, 838, 0, :west
unit :archer, 841, 0, :west
unit :sludge, 848, 0, :west
unit :sludge, 852, 0, :west
unit :captive, 853, 0, :west
unit :captive, 855, 0, :west
unit :wizard, 860, 0, :west
unit :captive, 861, 0, :west
unit :archer, 863, 0, :west
unit :archer, 865, 0, :west
unit :captive, 871, 0, :west
unit :captive, 873, 0, :west
unit :archer, 888, 0, :west
unit :wizard, 892, 0, :west
unit :wizard, 896, 0, :west
unit :captive, 899, 0, :west
unit :thick_sludge, 907, 0, :west
unit :sludge, 908, 0, :west
unit :captive, 917, 0, :west
unit :thick_sludge, 921, 0, :west
unit :thick_sludge, 924, 0, :west
unit :captive, 925, 0, :west
unit :captive, 927, 0, :west
unit :archer, 933, 0, :west
unit :captive, 939, 0, :west
unit :thick_sludge, 941, 0, :west
unit :wizard, 946, 0, :west
unit :archer, 950, 0, :west
unit :captive, 955, 0, :west
unit :thick_sludge, 960, 0, :west
unit :captive, 961, 0, :west
