#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      aw  s    C   aS CC      w          ss a  @  s  a   S  sS   C a  S  s s a     s  S  C Cw C  a ss   w      C     S  C  wa   s   as S s  S sw a S   S  w w     S  a    s     s C S            sw    a C  C  >        C sS  S      s    wC       S  C           sSS  a  C       S      C   s      a  SS a  SSS S s          C wS a    w        aS S      s   C   C  C                  S     sw    w                 w s  C S    s      w  w     aa     w    C   a  a asS a        C C   CC s  s  a aC       C        s        a    s       a C a      s  w        C      s C            w   s S          aw   s   sa   aw a      s s      w       C w   wC S     S  s      C           sS  S  C   Cw     SS                a    S C S  C S   S  C a    a      S             a s    s   saa          Ss s   w a    C Ca s s    w   C      w S    C    |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 824
ace_score 4120
size 824, 1
stairs 207, 0

warrior 47, 0, :east

unit :archer, 6, 0, :east
unit :wizard, 7, 0, :east
unit :sludge, 10, 0, :east
unit :captive, 15, 0, :east
unit :archer, 19, 0, :east
unit :thick_sludge, 20, 0, :east
unit :captive, 22, 0, :east
unit :captive, 23, 0, :east
unit :wizard, 30, 0, :east
unit :sludge, 41, 0, :east
unit :sludge, 42, 0, :east
unit :archer, 44, 0, :east
unit :sludge, 50, 0, :west
unit :archer, 53, 0, :west
unit :thick_sludge, 57, 0, :west
unit :sludge, 60, 0, :west
unit :thick_sludge, 61, 0, :west
unit :captive, 65, 0, :west
unit :archer, 67, 0, :west
unit :thick_sludge, 70, 0, :west
unit :sludge, 73, 0, :west
unit :sludge, 75, 0, :west
unit :archer, 77, 0, :west
unit :sludge, 83, 0, :west
unit :thick_sludge, 86, 0, :west
unit :captive, 89, 0, :west
unit :captive, 91, 0, :west
unit :wizard, 92, 0, :west
unit :captive, 94, 0, :west
unit :archer, 97, 0, :west
unit :sludge, 99, 0, :west
unit :sludge, 100, 0, :west
unit :wizard, 104, 0, :west
unit :captive, 111, 0, :west
unit :thick_sludge, 117, 0, :west
unit :captive, 120, 0, :west
unit :wizard, 123, 0, :west
unit :archer, 124, 0, :west
unit :sludge, 128, 0, :west
unit :archer, 132, 0, :west
unit :sludge, 133, 0, :west
unit :thick_sludge, 135, 0, :west
unit :sludge, 137, 0, :west
unit :thick_sludge, 140, 0, :west
unit :sludge, 142, 0, :west
unit :wizard, 143, 0, :west
unit :archer, 145, 0, :west
unit :thick_sludge, 147, 0, :west
unit :thick_sludge, 151, 0, :west
unit :wizard, 154, 0, :west
unit :wizard, 156, 0, :west
unit :thick_sludge, 162, 0, :west
unit :archer, 165, 0, :west
unit :sludge, 170, 0, :west
unit :sludge, 176, 0, :west
unit :captive, 178, 0, :west
unit :thick_sludge, 180, 0, :west
unit :sludge, 193, 0, :west
unit :wizard, 194, 0, :west
unit :archer, 199, 0, :west
unit :captive, 201, 0, :west
unit :captive, 204, 0, :west
unit :captive, 216, 0, :west
unit :sludge, 218, 0, :west
unit :thick_sludge, 219, 0, :west
unit :thick_sludge, 222, 0, :west
unit :sludge, 229, 0, :west
unit :wizard, 234, 0, :west
unit :captive, 235, 0, :west
unit :thick_sludge, 243, 0, :west
unit :captive, 246, 0, :west
unit :sludge, 258, 0, :west
unit :thick_sludge, 259, 0, :west
unit :thick_sludge, 260, 0, :west
unit :archer, 263, 0, :west
unit :captive, 266, 0, :west
unit :thick_sludge, 274, 0, :west
unit :captive, 281, 0, :west
unit :sludge, 285, 0, :west
unit :archer, 292, 0, :west
unit :thick_sludge, 295, 0, :west
unit :thick_sludge, 296, 0, :west
unit :archer, 298, 0, :west
unit :thick_sludge, 301, 0, :west
unit :thick_sludge, 302, 0, :west
unit :thick_sludge, 303, 0, :west
unit :thick_sludge, 305, 0, :west
unit :sludge, 307, 0, :west
unit :captive, 318, 0, :west
unit :wizard, 320, 0, :west
unit :thick_sludge, 321, 0, :west
unit :archer, 323, 0, :west
unit :wizard, 328, 0, :west
unit :archer, 337, 0, :west
unit :thick_sludge, 338, 0, :west
unit :thick_sludge, 340, 0, :west
unit :sludge, 347, 0, :west
unit :captive, 351, 0, :west
unit :captive, 355, 0, :west
unit :captive, 358, 0, :west
unit :thick_sludge, 377, 0, :west
unit :sludge, 383, 0, :west
unit :wizard, 384, 0, :west
unit :wizard, 389, 0, :west
unit :wizard, 407, 0, :west
unit :sludge, 409, 0, :west
unit :captive, 412, 0, :west
unit :thick_sludge, 414, 0, :west
unit :sludge, 419, 0, :west
unit :wizard, 426, 0, :west
unit :wizard, 429, 0, :west
unit :archer, 435, 0, :west
unit :archer, 436, 0, :west
unit :wizard, 442, 0, :west
unit :captive, 447, 0, :west
unit :archer, 451, 0, :west
unit :archer, 454, 0, :west
unit :archer, 456, 0, :west
unit :sludge, 457, 0, :west
unit :thick_sludge, 458, 0, :west
unit :archer, 460, 0, :west
unit :captive, 469, 0, :west
unit :captive, 471, 0, :west
unit :captive, 475, 0, :west
unit :captive, 476, 0, :west
unit :sludge, 478, 0, :west
unit :sludge, 481, 0, :west
unit :archer, 484, 0, :west
unit :archer, 486, 0, :west
unit :captive, 487, 0, :west
unit :captive, 495, 0, :west
unit :sludge, 504, 0, :west
unit :archer, 513, 0, :west
unit :sludge, 518, 0, :west
unit :archer, 526, 0, :west
unit :captive, 528, 0, :west
unit :archer, 530, 0, :west
unit :sludge, 537, 0, :west
unit :wizard, 540, 0, :west
unit :captive, 549, 0, :west
unit :sludge, 556, 0, :west
unit :captive, 558, 0, :west
unit :wizard, 571, 0, :west
unit :sludge, 575, 0, :west
unit :thick_sludge, 577, 0, :west
unit :archer, 588, 0, :west
unit :wizard, 589, 0, :west
unit :sludge, 593, 0, :west
unit :sludge, 597, 0, :west
unit :archer, 598, 0, :west
unit :archer, 602, 0, :west
unit :wizard, 603, 0, :west
unit :archer, 605, 0, :west
unit :sludge, 612, 0, :west
unit :sludge, 614, 0, :west
unit :wizard, 621, 0, :west
unit :captive, 629, 0, :west
unit :wizard, 631, 0, :west
unit :wizard, 635, 0, :west
unit :captive, 636, 0, :west
unit :thick_sludge, 638, 0, :west
unit :thick_sludge, 644, 0, :west
unit :sludge, 647, 0, :west
unit :captive, 654, 0, :west
unit :sludge, 666, 0, :west
unit :thick_sludge, 667, 0, :west
unit :thick_sludge, 670, 0, :west
unit :captive, 673, 0, :west
unit :captive, 677, 0, :west
unit :wizard, 678, 0, :west
unit :thick_sludge, 684, 0, :west
unit :thick_sludge, 685, 0, :west
unit :archer, 702, 0, :west
unit :thick_sludge, 707, 0, :west
unit :captive, 709, 0, :west
unit :thick_sludge, 711, 0, :west
unit :captive, 714, 0, :west
unit :thick_sludge, 716, 0, :west
unit :thick_sludge, 720, 0, :west
unit :captive, 723, 0, :west
unit :archer, 725, 0, :west
unit :archer, 730, 0, :west
unit :thick_sludge, 737, 0, :west
unit :archer, 751, 0, :west
unit :sludge, 753, 0, :west
unit :sludge, 758, 0, :west
unit :sludge, 762, 0, :west
unit :archer, 763, 0, :west
unit :archer, 764, 0, :west
unit :thick_sludge, 775, 0, :west
unit :sludge, 776, 0, :west
unit :sludge, 778, 0, :west
unit :wizard, 782, 0, :west
unit :archer, 784, 0, :west
unit :captive, 789, 0, :west
unit :captive, 791, 0, :west
unit :archer, 792, 0, :west
unit :sludge, 794, 0, :west
unit :sludge, 796, 0, :west
unit :wizard, 801, 0, :west
unit :captive, 805, 0, :west
unit :wizard, 812, 0, :west
unit :thick_sludge, 814, 0, :west
unit :captive, 819, 0, :west
