#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w C w      Cs  S  s            w       s S S   S       ss      w S  S   a    S S a   w   S      a   @   C a     C            C   SC           S  SsC  aSSS S aa w  Ss  s wS      ssaSw a         w    w  Cs C     Ssa   aC  w    CSS a  >     a    s  s  C        C    S          C   w         S       S s s  S a  S     as Ss      as  s Cs  S    a wa        C      C    S   S   w      w  sC  a sS S   s  a sa aw    C   a     Ss     S  a  S     w S            s  S                   s wa w    SS C               S      s sa  s  S S     S    a    C                  C    C     s   C       s  C   C            a  S S  s     S     C C     CS    CSa       C C   S     S      s     w  s |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 677
ace_score 3385
size 677, 1
stairs 234, 0

warrior 102, 0, :east

unit :wizard, 2, 0, :east
unit :captive, 4, 0, :east
unit :wizard, 6, 0, :east
unit :captive, 13, 0, :east
unit :sludge, 14, 0, :east
unit :thick_sludge, 17, 0, :east
unit :sludge, 20, 0, :east
unit :wizard, 33, 0, :east
unit :sludge, 41, 0, :east
unit :thick_sludge, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :thick_sludge, 49, 0, :east
unit :sludge, 57, 0, :east
unit :sludge, 58, 0, :east
unit :wizard, 65, 0, :east
unit :thick_sludge, 67, 0, :east
unit :thick_sludge, 70, 0, :east
unit :archer, 74, 0, :east
unit :thick_sludge, 79, 0, :east
unit :thick_sludge, 81, 0, :east
unit :archer, 83, 0, :east
unit :wizard, 87, 0, :east
unit :thick_sludge, 91, 0, :east
unit :archer, 98, 0, :east
unit :captive, 106, 0, :west
unit :archer, 108, 0, :west
unit :captive, 114, 0, :west
unit :captive, 127, 0, :west
unit :thick_sludge, 131, 0, :west
unit :captive, 132, 0, :west
unit :thick_sludge, 144, 0, :west
unit :thick_sludge, 147, 0, :west
unit :sludge, 148, 0, :west
unit :captive, 149, 0, :west
unit :archer, 152, 0, :west
unit :thick_sludge, 153, 0, :west
unit :thick_sludge, 154, 0, :west
unit :thick_sludge, 155, 0, :west
unit :thick_sludge, 157, 0, :west
unit :archer, 159, 0, :west
unit :archer, 160, 0, :west
unit :wizard, 162, 0, :west
unit :thick_sludge, 165, 0, :west
unit :sludge, 166, 0, :west
unit :sludge, 169, 0, :west
unit :wizard, 171, 0, :west
unit :thick_sludge, 172, 0, :west
unit :sludge, 179, 0, :west
unit :sludge, 180, 0, :west
unit :archer, 181, 0, :west
unit :thick_sludge, 182, 0, :west
unit :wizard, 183, 0, :west
unit :archer, 185, 0, :west
unit :wizard, 195, 0, :west
unit :wizard, 200, 0, :west
unit :captive, 203, 0, :west
unit :sludge, 204, 0, :west
unit :captive, 206, 0, :west
unit :thick_sludge, 212, 0, :west
unit :sludge, 213, 0, :west
unit :archer, 214, 0, :west
unit :archer, 218, 0, :west
unit :captive, 219, 0, :west
unit :wizard, 222, 0, :west
unit :captive, 227, 0, :west
unit :thick_sludge, 228, 0, :west
unit :thick_sludge, 229, 0, :west
unit :archer, 231, 0, :west
unit :archer, 240, 0, :west
unit :sludge, 245, 0, :west
unit :sludge, 248, 0, :west
unit :captive, 251, 0, :west
unit :captive, 260, 0, :west
unit :thick_sludge, 265, 0, :west
unit :captive, 276, 0, :west
unit :wizard, 280, 0, :west
unit :thick_sludge, 290, 0, :west
unit :thick_sludge, 298, 0, :west
unit :sludge, 300, 0, :west
unit :sludge, 302, 0, :west
unit :thick_sludge, 305, 0, :west
unit :archer, 307, 0, :west
unit :thick_sludge, 310, 0, :west
unit :archer, 316, 0, :west
unit :sludge, 317, 0, :west
unit :thick_sludge, 319, 0, :west
unit :sludge, 320, 0, :west
unit :archer, 327, 0, :west
unit :sludge, 328, 0, :west
unit :sludge, 331, 0, :west
unit :captive, 333, 0, :west
unit :sludge, 334, 0, :west
unit :thick_sludge, 337, 0, :west
unit :archer, 342, 0, :west
unit :wizard, 344, 0, :west
unit :archer, 345, 0, :west
unit :captive, 354, 0, :west
unit :captive, 361, 0, :west
unit :thick_sludge, 366, 0, :west
unit :thick_sludge, 370, 0, :west
unit :wizard, 374, 0, :west
unit :wizard, 381, 0, :west
unit :sludge, 384, 0, :west
unit :captive, 385, 0, :west
unit :archer, 388, 0, :west
unit :sludge, 390, 0, :west
unit :thick_sludge, 391, 0, :west
unit :thick_sludge, 393, 0, :west
unit :sludge, 397, 0, :west
unit :archer, 400, 0, :west
unit :sludge, 402, 0, :west
unit :archer, 403, 0, :west
unit :archer, 405, 0, :west
unit :wizard, 406, 0, :west
unit :captive, 411, 0, :west
unit :archer, 415, 0, :west
unit :thick_sludge, 421, 0, :west
unit :sludge, 422, 0, :west
unit :thick_sludge, 428, 0, :west
unit :archer, 431, 0, :west
unit :thick_sludge, 434, 0, :west
unit :wizard, 440, 0, :west
unit :thick_sludge, 442, 0, :west
unit :sludge, 455, 0, :west
unit :thick_sludge, 458, 0, :west
unit :sludge, 478, 0, :west
unit :wizard, 480, 0, :west
unit :archer, 481, 0, :west
unit :wizard, 483, 0, :west
unit :thick_sludge, 488, 0, :west
unit :thick_sludge, 489, 0, :west
unit :captive, 491, 0, :west
unit :thick_sludge, 507, 0, :west
unit :sludge, 514, 0, :west
unit :sludge, 516, 0, :west
unit :archer, 517, 0, :west
unit :sludge, 520, 0, :west
unit :thick_sludge, 523, 0, :west
unit :thick_sludge, 525, 0, :west
unit :thick_sludge, 531, 0, :west
unit :archer, 536, 0, :west
unit :captive, 541, 0, :west
unit :captive, 560, 0, :west
unit :captive, 565, 0, :west
unit :sludge, 571, 0, :west
unit :captive, 575, 0, :west
unit :sludge, 583, 0, :west
unit :captive, 586, 0, :west
unit :captive, 590, 0, :west
unit :archer, 603, 0, :west
unit :thick_sludge, 606, 0, :west
unit :thick_sludge, 608, 0, :west
unit :sludge, 611, 0, :west
unit :thick_sludge, 617, 0, :west
unit :captive, 623, 0, :west
unit :captive, 625, 0, :west
unit :captive, 631, 0, :west
unit :thick_sludge, 632, 0, :west
unit :captive, 637, 0, :west
unit :thick_sludge, 638, 0, :west
unit :archer, 639, 0, :west
unit :captive, 647, 0, :west
unit :captive, 649, 0, :west
unit :thick_sludge, 653, 0, :west
unit :thick_sludge, 659, 0, :west
unit :sludge, 666, 0, :west
unit :wizard, 672, 0, :west
unit :sludge, 675, 0, :west
