#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     a wCs  s    C a S  C   a S  aSCs   s> sa  @   s       w SS  S    a               w     a    S    s  a S  w  SC                 w       CwS      S            Cs      S    C  wC   a  w        a sa          C s     S     SS  s C C       C aC  C     a     C  sa w       C      S     a  C   sC   a    C     sS           s w   w  w     s                a  w      CS       C  S  s    S     s    s   CS   S S    Ca   C    S s CS     w        C              S C   a  s  s w ssS   s   s a        S S C           Cs    wssC  sw  C a s    a  CC   w   C    C     C   SC C     S   C SS  wC w     s  C    w  C C a     a a    s S  S     a      C   w   wsS S as        a   C     a     aC            w   aC             s         Ca    w C             sS a s   Cw    S  a   a  w      s|
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 771
ace_score 3855
size 771, 1
stairs 41, 0

warrior 47, 0, :east

unit :archer, 5, 0, :east
unit :wizard, 7, 0, :east
unit :captive, 8, 0, :east
unit :sludge, 9, 0, :east
unit :sludge, 12, 0, :east
unit :captive, 17, 0, :east
unit :archer, 19, 0, :east
unit :thick_sludge, 21, 0, :east
unit :captive, 24, 0, :east
unit :archer, 28, 0, :east
unit :thick_sludge, 30, 0, :east
unit :archer, 33, 0, :east
unit :thick_sludge, 34, 0, :east
unit :captive, 35, 0, :east
unit :sludge, 36, 0, :east
unit :sludge, 40, 0, :east
unit :sludge, 43, 0, :east
unit :archer, 44, 0, :east
unit :sludge, 51, 0, :west
unit :wizard, 59, 0, :west
unit :thick_sludge, 61, 0, :west
unit :thick_sludge, 62, 0, :west
unit :thick_sludge, 65, 0, :west
unit :archer, 70, 0, :west
unit :wizard, 86, 0, :west
unit :archer, 92, 0, :west
unit :thick_sludge, 97, 0, :west
unit :sludge, 102, 0, :west
unit :archer, 105, 0, :west
unit :thick_sludge, 107, 0, :west
unit :wizard, 110, 0, :west
unit :thick_sludge, 113, 0, :west
unit :captive, 114, 0, :west
unit :wizard, 132, 0, :west
unit :captive, 140, 0, :west
unit :wizard, 141, 0, :west
unit :thick_sludge, 142, 0, :west
unit :thick_sludge, 149, 0, :west
unit :captive, 162, 0, :west
unit :sludge, 163, 0, :west
unit :thick_sludge, 170, 0, :west
unit :captive, 175, 0, :west
unit :wizard, 178, 0, :west
unit :captive, 179, 0, :west
unit :archer, 183, 0, :west
unit :wizard, 186, 0, :west
unit :archer, 195, 0, :west
unit :sludge, 197, 0, :west
unit :archer, 198, 0, :west
unit :captive, 209, 0, :west
unit :sludge, 211, 0, :west
unit :thick_sludge, 217, 0, :west
unit :thick_sludge, 223, 0, :west
unit :thick_sludge, 224, 0, :west
unit :sludge, 227, 0, :west
unit :captive, 229, 0, :west
unit :captive, 231, 0, :west
unit :captive, 239, 0, :west
unit :archer, 241, 0, :west
unit :captive, 242, 0, :west
unit :captive, 245, 0, :west
unit :archer, 251, 0, :west
unit :captive, 257, 0, :west
unit :sludge, 260, 0, :west
unit :archer, 261, 0, :west
unit :wizard, 263, 0, :west
unit :captive, 271, 0, :west
unit :thick_sludge, 278, 0, :west
unit :archer, 284, 0, :west
unit :captive, 287, 0, :west
unit :sludge, 291, 0, :west
unit :captive, 292, 0, :west
unit :archer, 296, 0, :west
unit :captive, 301, 0, :west
unit :sludge, 307, 0, :west
unit :thick_sludge, 308, 0, :west
unit :sludge, 320, 0, :west
unit :wizard, 322, 0, :west
unit :wizard, 326, 0, :west
unit :wizard, 329, 0, :west
unit :sludge, 335, 0, :west
unit :archer, 352, 0, :west
unit :wizard, 355, 0, :west
unit :captive, 362, 0, :west
unit :thick_sludge, 363, 0, :west
unit :captive, 371, 0, :west
unit :thick_sludge, 374, 0, :west
unit :sludge, 377, 0, :west
unit :thick_sludge, 382, 0, :west
unit :sludge, 388, 0, :west
unit :sludge, 393, 0, :west
unit :captive, 397, 0, :west
unit :thick_sludge, 398, 0, :west
unit :thick_sludge, 402, 0, :west
unit :thick_sludge, 404, 0, :west
unit :captive, 409, 0, :west
unit :archer, 410, 0, :west
unit :captive, 414, 0, :west
unit :thick_sludge, 419, 0, :west
unit :sludge, 421, 0, :west
unit :captive, 423, 0, :west
unit :thick_sludge, 424, 0, :west
unit :wizard, 430, 0, :west
unit :captive, 439, 0, :west
unit :thick_sludge, 454, 0, :west
unit :captive, 456, 0, :west
unit :archer, 460, 0, :west
unit :sludge, 463, 0, :west
unit :sludge, 466, 0, :west
unit :wizard, 468, 0, :west
unit :sludge, 470, 0, :west
unit :sludge, 471, 0, :west
unit :thick_sludge, 472, 0, :west
unit :sludge, 476, 0, :west
unit :sludge, 480, 0, :west
unit :archer, 482, 0, :west
unit :thick_sludge, 491, 0, :west
unit :thick_sludge, 493, 0, :west
unit :captive, 495, 0, :west
unit :captive, 507, 0, :west
unit :sludge, 508, 0, :west
unit :wizard, 513, 0, :west
unit :sludge, 514, 0, :west
unit :sludge, 515, 0, :west
unit :captive, 516, 0, :west
unit :sludge, 519, 0, :west
unit :wizard, 520, 0, :west
unit :captive, 523, 0, :west
unit :archer, 525, 0, :west
unit :sludge, 527, 0, :west
unit :archer, 532, 0, :west
unit :captive, 535, 0, :west
unit :captive, 536, 0, :west
unit :wizard, 540, 0, :west
unit :captive, 544, 0, :west
unit :captive, 549, 0, :west
unit :captive, 555, 0, :west
unit :thick_sludge, 559, 0, :west
unit :captive, 560, 0, :west
unit :captive, 562, 0, :west
unit :thick_sludge, 568, 0, :west
unit :captive, 572, 0, :west
unit :thick_sludge, 574, 0, :west
unit :thick_sludge, 575, 0, :west
unit :wizard, 578, 0, :west
unit :captive, 579, 0, :west
unit :wizard, 581, 0, :west
unit :sludge, 587, 0, :west
unit :captive, 590, 0, :west
unit :wizard, 595, 0, :west
unit :captive, 598, 0, :west
unit :captive, 600, 0, :west
unit :archer, 602, 0, :west
unit :archer, 608, 0, :west
unit :archer, 610, 0, :west
unit :sludge, 615, 0, :west
unit :thick_sludge, 617, 0, :west
unit :thick_sludge, 620, 0, :west
unit :archer, 626, 0, :west
unit :captive, 633, 0, :west
unit :wizard, 637, 0, :west
unit :wizard, 641, 0, :west
unit :sludge, 642, 0, :west
unit :thick_sludge, 643, 0, :west
unit :thick_sludge, 645, 0, :west
unit :archer, 647, 0, :west
unit :sludge, 648, 0, :west
unit :archer, 657, 0, :west
unit :captive, 661, 0, :west
unit :archer, 667, 0, :west
unit :archer, 673, 0, :west
unit :captive, 674, 0, :west
unit :wizard, 687, 0, :west
unit :archer, 691, 0, :west
unit :captive, 692, 0, :west
unit :sludge, 706, 0, :west
unit :captive, 716, 0, :west
unit :archer, 717, 0, :west
unit :wizard, 722, 0, :west
unit :captive, 724, 0, :west
unit :sludge, 738, 0, :west
unit :thick_sludge, 739, 0, :west
unit :archer, 741, 0, :west
unit :sludge, 743, 0, :west
unit :captive, 747, 0, :west
unit :wizard, 748, 0, :west
unit :thick_sludge, 753, 0, :west
unit :archer, 756, 0, :west
unit :archer, 760, 0, :west
unit :wizard, 763, 0, :west
unit :sludge, 770, 0, :west
