#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w       Cs   s                   CsS      s       C S  CS     a s     s    S   w S s     C    CCCsS   sw  s SC  s       as a    C S  a  s       a         sSC   C    w        C  ss   wC S C C     sS w   Cw     w   ws  Sw       w S              w         S   aa aaS      w     S s               s    S w   S   a  wS         C wS  s        s    C    C           C CC   a  s          wSs C SCCaa S  a S     a w  CC        @      CC   s          s a C     s    s    w      S  C      s    C    a   aaS      s Sa         sSS w      Sw          C        S  C C   Ca  S    S         aSa      w s s S  sw     S    Ss s   S     S C s     s     s          s      S          C  C   ss     C a  Sss          s         a          w w      w wS       >  sSa      s   sa Cw s    |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 764
ace_score 3820
size 764, 1
stairs 737, 0

warrior 420, 0, :east

unit :wizard, 2, 0, :east
unit :captive, 10, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 15, 0, :east
unit :captive, 35, 0, :east
unit :sludge, 36, 0, :east
unit :thick_sludge, 37, 0, :east
unit :sludge, 44, 0, :east
unit :captive, 52, 0, :east
unit :thick_sludge, 54, 0, :east
unit :captive, 57, 0, :east
unit :thick_sludge, 58, 0, :east
unit :archer, 64, 0, :east
unit :sludge, 66, 0, :east
unit :sludge, 72, 0, :east
unit :thick_sludge, 77, 0, :east
unit :wizard, 81, 0, :east
unit :thick_sludge, 83, 0, :east
unit :sludge, 85, 0, :east
unit :captive, 91, 0, :east
unit :captive, 96, 0, :east
unit :captive, 97, 0, :east
unit :captive, 98, 0, :east
unit :sludge, 99, 0, :east
unit :thick_sludge, 100, 0, :east
unit :sludge, 104, 0, :east
unit :wizard, 105, 0, :east
unit :sludge, 108, 0, :east
unit :thick_sludge, 110, 0, :east
unit :captive, 111, 0, :east
unit :sludge, 114, 0, :east
unit :archer, 122, 0, :east
unit :sludge, 123, 0, :east
unit :archer, 125, 0, :east
unit :captive, 130, 0, :east
unit :thick_sludge, 132, 0, :east
unit :archer, 135, 0, :east
unit :sludge, 138, 0, :east
unit :archer, 146, 0, :east
unit :sludge, 156, 0, :east
unit :thick_sludge, 157, 0, :east
unit :captive, 158, 0, :east
unit :captive, 162, 0, :east
unit :wizard, 167, 0, :east
unit :captive, 176, 0, :east
unit :sludge, 179, 0, :east
unit :sludge, 180, 0, :east
unit :wizard, 184, 0, :east
unit :captive, 185, 0, :east
unit :thick_sludge, 187, 0, :east
unit :captive, 189, 0, :east
unit :captive, 191, 0, :east
unit :sludge, 197, 0, :east
unit :thick_sludge, 198, 0, :east
unit :wizard, 200, 0, :east
unit :captive, 204, 0, :east
unit :wizard, 205, 0, :east
unit :wizard, 211, 0, :east
unit :wizard, 215, 0, :east
unit :sludge, 216, 0, :east
unit :thick_sludge, 219, 0, :east
unit :wizard, 220, 0, :east
unit :wizard, 228, 0, :east
unit :thick_sludge, 230, 0, :east
unit :wizard, 245, 0, :east
unit :thick_sludge, 255, 0, :east
unit :archer, 259, 0, :east
unit :archer, 260, 0, :east
unit :archer, 262, 0, :east
unit :archer, 263, 0, :east
unit :thick_sludge, 264, 0, :east
unit :wizard, 271, 0, :east
unit :thick_sludge, 277, 0, :east
unit :sludge, 279, 0, :east
unit :sludge, 295, 0, :east
unit :thick_sludge, 300, 0, :east
unit :wizard, 302, 0, :east
unit :thick_sludge, 306, 0, :east
unit :archer, 310, 0, :east
unit :wizard, 313, 0, :east
unit :thick_sludge, 314, 0, :east
unit :captive, 324, 0, :east
unit :wizard, 326, 0, :east
unit :thick_sludge, 327, 0, :east
unit :sludge, 330, 0, :east
unit :sludge, 339, 0, :east
unit :captive, 344, 0, :east
unit :captive, 349, 0, :east
unit :captive, 361, 0, :east
unit :captive, 363, 0, :east
unit :captive, 364, 0, :east
unit :archer, 368, 0, :east
unit :sludge, 371, 0, :east
unit :wizard, 382, 0, :east
unit :thick_sludge, 383, 0, :east
unit :sludge, 384, 0, :east
unit :captive, 386, 0, :east
unit :thick_sludge, 388, 0, :east
unit :captive, 389, 0, :east
unit :captive, 390, 0, :east
unit :archer, 391, 0, :east
unit :archer, 392, 0, :east
unit :thick_sludge, 394, 0, :east
unit :archer, 397, 0, :east
unit :thick_sludge, 399, 0, :east
unit :archer, 405, 0, :east
unit :wizard, 407, 0, :east
unit :captive, 410, 0, :east
unit :captive, 411, 0, :east
unit :captive, 427, 0, :west
unit :captive, 428, 0, :west
unit :sludge, 432, 0, :west
unit :sludge, 443, 0, :west
unit :archer, 445, 0, :west
unit :captive, 447, 0, :west
unit :sludge, 453, 0, :west
unit :sludge, 458, 0, :west
unit :wizard, 463, 0, :west
unit :thick_sludge, 470, 0, :west
unit :captive, 473, 0, :west
unit :sludge, 480, 0, :west
unit :captive, 485, 0, :west
unit :archer, 490, 0, :west
unit :archer, 494, 0, :west
unit :archer, 495, 0, :west
unit :thick_sludge, 496, 0, :west
unit :sludge, 503, 0, :west
unit :thick_sludge, 505, 0, :west
unit :archer, 506, 0, :west
unit :sludge, 516, 0, :west
unit :thick_sludge, 517, 0, :west
unit :thick_sludge, 518, 0, :west
unit :wizard, 520, 0, :west
unit :thick_sludge, 527, 0, :west
unit :wizard, 528, 0, :west
unit :captive, 539, 0, :west
unit :thick_sludge, 548, 0, :west
unit :captive, 551, 0, :west
unit :captive, 553, 0, :west
unit :captive, 557, 0, :west
unit :archer, 558, 0, :west
unit :thick_sludge, 561, 0, :west
unit :thick_sludge, 566, 0, :west
unit :archer, 576, 0, :west
unit :thick_sludge, 577, 0, :west
unit :archer, 578, 0, :west
unit :wizard, 585, 0, :west
unit :sludge, 587, 0, :west
unit :sludge, 589, 0, :west
unit :thick_sludge, 591, 0, :west
unit :sludge, 594, 0, :west
unit :wizard, 595, 0, :west
unit :thick_sludge, 601, 0, :west
unit :thick_sludge, 606, 0, :west
unit :sludge, 607, 0, :west
unit :sludge, 609, 0, :west
unit :thick_sludge, 613, 0, :west
unit :thick_sludge, 619, 0, :west
unit :captive, 621, 0, :west
unit :sludge, 623, 0, :west
unit :sludge, 629, 0, :west
unit :sludge, 635, 0, :west
unit :sludge, 646, 0, :west
unit :thick_sludge, 653, 0, :west
unit :captive, 664, 0, :west
unit :captive, 667, 0, :west
unit :sludge, 671, 0, :west
unit :sludge, 672, 0, :west
unit :captive, 678, 0, :west
unit :archer, 680, 0, :west
unit :thick_sludge, 683, 0, :west
unit :sludge, 684, 0, :west
unit :sludge, 685, 0, :west
unit :sludge, 696, 0, :west
unit :archer, 706, 0, :west
unit :wizard, 717, 0, :west
unit :wizard, 719, 0, :west
unit :wizard, 726, 0, :west
unit :wizard, 728, 0, :west
unit :thick_sludge, 729, 0, :west
unit :sludge, 740, 0, :west
unit :thick_sludge, 741, 0, :west
unit :archer, 742, 0, :west
unit :sludge, 749, 0, :west
unit :sludge, 753, 0, :west
unit :archer, 754, 0, :west
unit :captive, 756, 0, :west
unit :wizard, 757, 0, :west
unit :sludge, 759, 0, :west
