#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |        Sa   a    a   sa w       S C  w        S      C  C  w       C         s    w  S S       Cs         wS      S    wC   a   C  s       s      a  S s  C  w    C   s  a w    C    C  s           a           a         aS     w      w S    a    a       S     CC    a CS              SC      S  a a                  w         @  a  w S S C Ss   SS C          w CC    S    S   C w wCS  as    w  C s      s  CC    saCS  aS s S w Ssas s  a>       w    w   Sas a  s a aw C      a   S            s           w      S a              a  s    s w S S   s      s        S  s w  sa  s    C s    C a  C   C  S  CSC   C   C  w     a   w w     a a a         s  s  SC  w     w     C SC C   Sa C asC C     a     a   S           w        C C s   C  a s     SC   s   w       C S w    w w       s C C C      |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 789
ace_score 3945
size 789, 1
stairs 435, 0

warrior 325, 0, :east

unit :thick_sludge, 8, 0, :east
unit :archer, 9, 0, :east
unit :archer, 13, 0, :east
unit :archer, 18, 0, :east
unit :sludge, 22, 0, :east
unit :archer, 23, 0, :east
unit :wizard, 25, 0, :east
unit :thick_sludge, 33, 0, :east
unit :captive, 35, 0, :east
unit :wizard, 38, 0, :east
unit :thick_sludge, 47, 0, :east
unit :captive, 54, 0, :east
unit :captive, 57, 0, :east
unit :wizard, 60, 0, :east
unit :captive, 68, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 83, 0, :east
unit :thick_sludge, 86, 0, :east
unit :thick_sludge, 88, 0, :east
unit :captive, 96, 0, :east
unit :sludge, 97, 0, :east
unit :wizard, 107, 0, :east
unit :thick_sludge, 108, 0, :east
unit :thick_sludge, 115, 0, :east
unit :wizard, 120, 0, :east
unit :captive, 121, 0, :east
unit :archer, 125, 0, :east
unit :captive, 129, 0, :east
unit :sludge, 132, 0, :east
unit :sludge, 140, 0, :east
unit :archer, 147, 0, :east
unit :thick_sludge, 150, 0, :east
unit :sludge, 152, 0, :east
unit :captive, 155, 0, :east
unit :wizard, 158, 0, :east
unit :captive, 163, 0, :east
unit :sludge, 167, 0, :east
unit :archer, 170, 0, :east
unit :wizard, 172, 0, :east
unit :captive, 177, 0, :east
unit :captive, 182, 0, :east
unit :sludge, 185, 0, :east
unit :archer, 197, 0, :east
unit :archer, 209, 0, :east
unit :archer, 219, 0, :east
unit :thick_sludge, 220, 0, :east
unit :wizard, 226, 0, :east
unit :wizard, 233, 0, :east
unit :thick_sludge, 235, 0, :east
unit :archer, 240, 0, :east
unit :archer, 245, 0, :east
unit :thick_sludge, 253, 0, :east
unit :captive, 259, 0, :east
unit :captive, 260, 0, :east
unit :archer, 265, 0, :east
unit :captive, 267, 0, :east
unit :thick_sludge, 268, 0, :east
unit :thick_sludge, 283, 0, :east
unit :captive, 284, 0, :east
unit :thick_sludge, 291, 0, :east
unit :archer, 294, 0, :east
unit :archer, 296, 0, :east
unit :wizard, 315, 0, :east
unit :archer, 328, 0, :west
unit :wizard, 331, 0, :west
unit :thick_sludge, 333, 0, :west
unit :thick_sludge, 335, 0, :west
unit :captive, 337, 0, :west
unit :thick_sludge, 339, 0, :west
unit :sludge, 340, 0, :west
unit :thick_sludge, 344, 0, :west
unit :thick_sludge, 345, 0, :west
unit :captive, 347, 0, :west
unit :wizard, 358, 0, :west
unit :captive, 360, 0, :west
unit :captive, 361, 0, :west
unit :thick_sludge, 366, 0, :west
unit :thick_sludge, 371, 0, :west
unit :captive, 375, 0, :west
unit :wizard, 377, 0, :west
unit :wizard, 379, 0, :west
unit :captive, 380, 0, :west
unit :thick_sludge, 381, 0, :west
unit :archer, 384, 0, :west
unit :sludge, 385, 0, :west
unit :wizard, 390, 0, :west
unit :captive, 393, 0, :west
unit :sludge, 395, 0, :west
unit :sludge, 402, 0, :west
unit :captive, 405, 0, :west
unit :captive, 406, 0, :west
unit :sludge, 411, 0, :west
unit :archer, 412, 0, :west
unit :captive, 413, 0, :west
unit :thick_sludge, 414, 0, :west
unit :archer, 417, 0, :west
unit :thick_sludge, 418, 0, :west
unit :sludge, 420, 0, :west
unit :thick_sludge, 422, 0, :west
unit :wizard, 424, 0, :west
unit :thick_sludge, 426, 0, :west
unit :sludge, 427, 0, :west
unit :archer, 428, 0, :west
unit :sludge, 429, 0, :west
unit :sludge, 431, 0, :west
unit :archer, 434, 0, :west
unit :wizard, 443, 0, :west
unit :wizard, 448, 0, :west
unit :thick_sludge, 452, 0, :west
unit :archer, 453, 0, :west
unit :sludge, 454, 0, :west
unit :archer, 456, 0, :west
unit :sludge, 459, 0, :west
unit :archer, 461, 0, :west
unit :archer, 463, 0, :west
unit :wizard, 464, 0, :west
unit :captive, 466, 0, :west
unit :archer, 473, 0, :west
unit :thick_sludge, 477, 0, :west
unit :sludge, 490, 0, :west
unit :wizard, 502, 0, :west
unit :thick_sludge, 509, 0, :west
unit :archer, 511, 0, :west
unit :archer, 526, 0, :west
unit :sludge, 529, 0, :west
unit :sludge, 534, 0, :west
unit :wizard, 536, 0, :west
unit :thick_sludge, 538, 0, :west
unit :thick_sludge, 540, 0, :west
unit :sludge, 544, 0, :west
unit :sludge, 551, 0, :west
unit :thick_sludge, 560, 0, :west
unit :sludge, 563, 0, :west
unit :wizard, 565, 0, :west
unit :sludge, 568, 0, :west
unit :archer, 569, 0, :west
unit :sludge, 572, 0, :west
unit :captive, 577, 0, :west
unit :sludge, 579, 0, :west
unit :captive, 584, 0, :west
unit :archer, 586, 0, :west
unit :captive, 589, 0, :west
unit :captive, 593, 0, :west
unit :thick_sludge, 596, 0, :west
unit :captive, 599, 0, :west
unit :thick_sludge, 600, 0, :west
unit :captive, 601, 0, :west
unit :captive, 605, 0, :west
unit :captive, 609, 0, :west
unit :wizard, 612, 0, :west
unit :archer, 618, 0, :west
unit :wizard, 622, 0, :west
unit :wizard, 624, 0, :west
unit :archer, 630, 0, :west
unit :archer, 632, 0, :west
unit :archer, 634, 0, :west
unit :sludge, 644, 0, :west
unit :sludge, 647, 0, :west
unit :thick_sludge, 650, 0, :west
unit :captive, 651, 0, :west
unit :wizard, 654, 0, :west
unit :wizard, 660, 0, :west
unit :captive, 666, 0, :west
unit :thick_sludge, 668, 0, :west
unit :captive, 669, 0, :west
unit :captive, 671, 0, :west
unit :thick_sludge, 675, 0, :west
unit :archer, 676, 0, :west
unit :captive, 678, 0, :west
unit :archer, 680, 0, :west
unit :sludge, 681, 0, :west
unit :captive, 682, 0, :west
unit :captive, 684, 0, :west
unit :archer, 690, 0, :west
unit :archer, 696, 0, :west
unit :thick_sludge, 700, 0, :west
unit :wizard, 712, 0, :west
unit :captive, 721, 0, :west
unit :captive, 723, 0, :west
unit :sludge, 725, 0, :west
unit :captive, 729, 0, :west
unit :archer, 732, 0, :west
unit :sludge, 734, 0, :west
unit :thick_sludge, 740, 0, :west
unit :captive, 741, 0, :west
unit :sludge, 745, 0, :west
unit :wizard, 749, 0, :west
unit :captive, 757, 0, :west
unit :thick_sludge, 759, 0, :west
unit :wizard, 761, 0, :west
unit :wizard, 766, 0, :west
unit :wizard, 768, 0, :west
unit :sludge, 776, 0, :west
unit :captive, 778, 0, :west
unit :captive, 780, 0, :west
unit :captive, 782, 0, :west
