#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   S       sC             s  w  C  CC a w aas             C                  s  a             C        ss  w    Cs S      a w            w    s     C      Ca w aC a s     >   sw     C  s     s     C    S       S   a S     w ws  C         w    w  wS  C   S   as  a    s                w        w      S         as      sC  SSs saC    w          S  C     s  S  a              Ss C        C w   sa    s Ca     s  S C   aa a s C     C  w     C w    C w    C   wS     @  w    C   C       a       w C  Sa  s s     C   C      s C    s  w         S a     S    s   C   C a   a a  CSa C   C  w   aa aw      SS   w     w   w         s      a  Sw a     Csw       Sa  S wa C  S Cs    SC      w        C    C  s   SC  w            w  S   S s     a  s w  ss      SC         a CSS       s w  C   C  S  w   w  C         Cw     S CSS   a s aa  s S  s     S w  |
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 842
ace_score 4210
size 842, 1
stairs 171, 0

warrior 463, 0, :east

unit :thick_sludge, 3, 0, :east
unit :sludge, 11, 0, :east
unit :captive, 12, 0, :east
unit :sludge, 26, 0, :east
unit :wizard, 29, 0, :east
unit :captive, 32, 0, :east
unit :captive, 35, 0, :east
unit :captive, 36, 0, :east
unit :archer, 38, 0, :east
unit :wizard, 40, 0, :east
unit :archer, 42, 0, :east
unit :archer, 43, 0, :east
unit :sludge, 44, 0, :east
unit :captive, 58, 0, :east
unit :sludge, 77, 0, :east
unit :archer, 80, 0, :east
unit :captive, 94, 0, :east
unit :sludge, 103, 0, :east
unit :sludge, 104, 0, :east
unit :wizard, 107, 0, :east
unit :captive, 112, 0, :east
unit :sludge, 113, 0, :east
unit :thick_sludge, 115, 0, :east
unit :archer, 122, 0, :east
unit :wizard, 124, 0, :east
unit :wizard, 137, 0, :east
unit :sludge, 142, 0, :east
unit :captive, 148, 0, :east
unit :captive, 155, 0, :east
unit :archer, 156, 0, :east
unit :wizard, 158, 0, :east
unit :archer, 160, 0, :east
unit :captive, 161, 0, :east
unit :archer, 163, 0, :east
unit :sludge, 165, 0, :east
unit :sludge, 175, 0, :east
unit :wizard, 176, 0, :east
unit :captive, 182, 0, :east
unit :sludge, 185, 0, :east
unit :sludge, 191, 0, :east
unit :captive, 197, 0, :east
unit :thick_sludge, 202, 0, :east
unit :thick_sludge, 210, 0, :east
unit :archer, 214, 0, :east
unit :thick_sludge, 216, 0, :east
unit :wizard, 222, 0, :east
unit :wizard, 224, 0, :east
unit :sludge, 225, 0, :east
unit :captive, 228, 0, :east
unit :wizard, 238, 0, :east
unit :wizard, 243, 0, :east
unit :wizard, 246, 0, :east
unit :thick_sludge, 247, 0, :east
unit :captive, 250, 0, :east
unit :thick_sludge, 254, 0, :east
unit :archer, 258, 0, :east
unit :sludge, 259, 0, :east
unit :archer, 262, 0, :east
unit :sludge, 267, 0, :east
unit :wizard, 284, 0, :east
unit :wizard, 293, 0, :east
unit :thick_sludge, 300, 0, :east
unit :archer, 310, 0, :east
unit :sludge, 311, 0, :east
unit :sludge, 318, 0, :east
unit :captive, 319, 0, :east
unit :thick_sludge, 322, 0, :east
unit :thick_sludge, 323, 0, :east
unit :sludge, 324, 0, :east
unit :sludge, 326, 0, :east
unit :archer, 327, 0, :east
unit :captive, 328, 0, :east
unit :wizard, 333, 0, :east
unit :thick_sludge, 344, 0, :east
unit :captive, 347, 0, :east
unit :sludge, 353, 0, :east
unit :thick_sludge, 356, 0, :east
unit :archer, 359, 0, :east
unit :thick_sludge, 374, 0, :east
unit :sludge, 375, 0, :east
unit :captive, 377, 0, :east
unit :captive, 386, 0, :east
unit :wizard, 388, 0, :east
unit :sludge, 392, 0, :east
unit :archer, 393, 0, :east
unit :sludge, 398, 0, :east
unit :captive, 400, 0, :east
unit :archer, 401, 0, :east
unit :sludge, 407, 0, :east
unit :thick_sludge, 410, 0, :east
unit :captive, 412, 0, :east
unit :archer, 416, 0, :east
unit :archer, 417, 0, :east
unit :archer, 419, 0, :east
unit :sludge, 421, 0, :east
unit :captive, 423, 0, :east
unit :captive, 429, 0, :east
unit :wizard, 432, 0, :east
unit :captive, 438, 0, :east
unit :wizard, 440, 0, :east
unit :captive, 445, 0, :east
unit :wizard, 447, 0, :east
unit :captive, 452, 0, :east
unit :wizard, 456, 0, :east
unit :thick_sludge, 457, 0, :east
unit :wizard, 466, 0, :west
unit :captive, 471, 0, :west
unit :captive, 475, 0, :west
unit :archer, 483, 0, :west
unit :wizard, 491, 0, :west
unit :captive, 493, 0, :west
unit :thick_sludge, 496, 0, :west
unit :archer, 497, 0, :west
unit :sludge, 500, 0, :west
unit :sludge, 502, 0, :west
unit :captive, 508, 0, :west
unit :captive, 512, 0, :west
unit :sludge, 519, 0, :west
unit :captive, 521, 0, :west
unit :sludge, 526, 0, :west
unit :wizard, 529, 0, :west
unit :thick_sludge, 539, 0, :west
unit :archer, 541, 0, :west
unit :thick_sludge, 547, 0, :west
unit :sludge, 552, 0, :west
unit :captive, 556, 0, :west
unit :captive, 560, 0, :west
unit :archer, 562, 0, :west
unit :archer, 566, 0, :west
unit :archer, 568, 0, :west
unit :captive, 571, 0, :west
unit :thick_sludge, 572, 0, :west
unit :archer, 573, 0, :west
unit :captive, 575, 0, :west
unit :captive, 579, 0, :west
unit :wizard, 582, 0, :west
unit :archer, 586, 0, :west
unit :archer, 587, 0, :west
unit :archer, 589, 0, :west
unit :wizard, 590, 0, :west
unit :thick_sludge, 597, 0, :west
unit :thick_sludge, 598, 0, :west
unit :wizard, 602, 0, :west
unit :wizard, 608, 0, :west
unit :wizard, 612, 0, :west
unit :sludge, 622, 0, :west
unit :archer, 629, 0, :west
unit :thick_sludge, 632, 0, :west
unit :wizard, 633, 0, :west
unit :archer, 635, 0, :west
unit :captive, 641, 0, :west
unit :sludge, 642, 0, :west
unit :wizard, 643, 0, :west
unit :thick_sludge, 651, 0, :west
unit :archer, 652, 0, :west
unit :thick_sludge, 655, 0, :west
unit :wizard, 657, 0, :west
unit :archer, 658, 0, :west
unit :captive, 660, 0, :west
unit :thick_sludge, 663, 0, :west
unit :captive, 665, 0, :west
unit :sludge, 666, 0, :west
unit :thick_sludge, 671, 0, :west
unit :captive, 672, 0, :west
unit :wizard, 679, 0, :west
unit :captive, 688, 0, :west
unit :captive, 693, 0, :west
unit :sludge, 696, 0, :west
unit :thick_sludge, 700, 0, :west
unit :captive, 701, 0, :west
unit :wizard, 704, 0, :west
unit :wizard, 717, 0, :west
unit :thick_sludge, 720, 0, :west
unit :thick_sludge, 724, 0, :west
unit :sludge, 726, 0, :west
unit :archer, 732, 0, :west
unit :sludge, 735, 0, :west
unit :wizard, 737, 0, :west
unit :sludge, 740, 0, :west
unit :sludge, 741, 0, :west
unit :thick_sludge, 748, 0, :west
unit :captive, 749, 0, :west
unit :archer, 759, 0, :west
unit :captive, 761, 0, :west
unit :thick_sludge, 762, 0, :west
unit :thick_sludge, 763, 0, :west
unit :sludge, 771, 0, :west
unit :wizard, 773, 0, :west
unit :captive, 776, 0, :west
unit :captive, 780, 0, :west
unit :thick_sludge, 783, 0, :west
unit :wizard, 786, 0, :west
unit :wizard, 790, 0, :west
unit :captive, 793, 0, :west
unit :captive, 803, 0, :west
unit :wizard, 804, 0, :west
unit :thick_sludge, 810, 0, :west
unit :captive, 812, 0, :west
unit :thick_sludge, 813, 0, :west
unit :thick_sludge, 814, 0, :west
unit :archer, 818, 0, :west
unit :sludge, 820, 0, :west
unit :archer, 822, 0, :west
unit :archer, 823, 0, :west
unit :sludge, 826, 0, :west
unit :thick_sludge, 828, 0, :west
unit :sludge, 831, 0, :west
unit :thick_sludge, 837, 0, :west
unit :wizard, 839, 0, :west
