#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  a  CC  a C          a  w    C S  w  s   S  C     w  w       wS          C ss   s   a   sC          Cs   ssC     s S         S C S    C    s    Swa s w    s  SS >w      s w w   C a     s s           s   S  as     C    w s   w  s         a   S            a    Ca         s   s        w    w   SC  C   S S    aasa S        aC   ws sC w     s C      swC C                      a  a   ass     Ss S           C a C  a      s  w s     a  w      Cs          sC      Cs   wC           SS   C C   s S     w     s   a  wCa    SS   s a    C    s s SC     a       w S    CC  C                    S  aS C   C  s       w        a Ca       s  s  a   w   s    @  S   w  s s     w   S    s|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 673
ace_score 3365
size 673, 1
stairs 162, 0

warrior 645, 0, :east

unit :archer, 2, 0, :east
unit :captive, 5, 0, :east
unit :captive, 6, 0, :east
unit :archer, 9, 0, :east
unit :captive, 11, 0, :east
unit :archer, 22, 0, :east
unit :wizard, 25, 0, :east
unit :captive, 30, 0, :east
unit :thick_sludge, 32, 0, :east
unit :wizard, 35, 0, :east
unit :sludge, 38, 0, :east
unit :thick_sludge, 42, 0, :east
unit :captive, 45, 0, :east
unit :wizard, 51, 0, :east
unit :wizard, 54, 0, :east
unit :wizard, 62, 0, :east
unit :thick_sludge, 63, 0, :east
unit :captive, 74, 0, :east
unit :sludge, 76, 0, :east
unit :sludge, 77, 0, :east
unit :sludge, 81, 0, :east
unit :archer, 85, 0, :east
unit :sludge, 89, 0, :east
unit :captive, 90, 0, :east
unit :captive, 101, 0, :east
unit :sludge, 102, 0, :east
unit :sludge, 106, 0, :east
unit :sludge, 107, 0, :east
unit :captive, 108, 0, :east
unit :sludge, 114, 0, :east
unit :thick_sludge, 116, 0, :east
unit :thick_sludge, 126, 0, :east
unit :captive, 128, 0, :east
unit :thick_sludge, 130, 0, :east
unit :captive, 135, 0, :east
unit :sludge, 140, 0, :east
unit :thick_sludge, 145, 0, :east
unit :wizard, 146, 0, :east
unit :archer, 147, 0, :east
unit :sludge, 149, 0, :east
unit :wizard, 151, 0, :east
unit :sludge, 156, 0, :east
unit :thick_sludge, 159, 0, :east
unit :thick_sludge, 160, 0, :east
unit :wizard, 163, 0, :east
unit :sludge, 170, 0, :east
unit :wizard, 172, 0, :east
unit :wizard, 174, 0, :east
unit :captive, 178, 0, :east
unit :archer, 180, 0, :east
unit :sludge, 186, 0, :east
unit :sludge, 188, 0, :east
unit :sludge, 200, 0, :east
unit :thick_sludge, 204, 0, :east
unit :archer, 207, 0, :east
unit :sludge, 208, 0, :east
unit :captive, 214, 0, :east
unit :wizard, 219, 0, :east
unit :sludge, 221, 0, :east
unit :wizard, 225, 0, :east
unit :sludge, 228, 0, :east
unit :archer, 238, 0, :east
unit :thick_sludge, 242, 0, :east
unit :archer, 255, 0, :east
unit :captive, 260, 0, :east
unit :archer, 261, 0, :east
unit :sludge, 271, 0, :east
unit :sludge, 275, 0, :east
unit :wizard, 284, 0, :east
unit :wizard, 289, 0, :east
unit :thick_sludge, 293, 0, :east
unit :captive, 294, 0, :east
unit :captive, 297, 0, :east
unit :thick_sludge, 301, 0, :east
unit :thick_sludge, 303, 0, :east
unit :archer, 308, 0, :east
unit :archer, 309, 0, :east
unit :sludge, 310, 0, :east
unit :archer, 311, 0, :east
unit :thick_sludge, 313, 0, :east
unit :archer, 322, 0, :east
unit :captive, 323, 0, :east
unit :wizard, 327, 0, :east
unit :sludge, 328, 0, :east
unit :sludge, 330, 0, :east
unit :captive, 331, 0, :east
unit :wizard, 333, 0, :east
unit :sludge, 339, 0, :east
unit :captive, 341, 0, :east
unit :sludge, 348, 0, :east
unit :wizard, 349, 0, :east
unit :captive, 350, 0, :east
unit :captive, 352, 0, :east
unit :archer, 375, 0, :east
unit :archer, 378, 0, :east
unit :archer, 382, 0, :east
unit :sludge, 383, 0, :east
unit :sludge, 384, 0, :east
unit :thick_sludge, 390, 0, :east
unit :sludge, 391, 0, :east
unit :thick_sludge, 393, 0, :east
unit :captive, 405, 0, :east
unit :archer, 407, 0, :east
unit :captive, 409, 0, :east
unit :archer, 412, 0, :east
unit :sludge, 419, 0, :east
unit :wizard, 422, 0, :east
unit :sludge, 424, 0, :east
unit :archer, 430, 0, :east
unit :wizard, 433, 0, :east
unit :captive, 440, 0, :east
unit :sludge, 441, 0, :east
unit :sludge, 452, 0, :east
unit :captive, 453, 0, :east
unit :captive, 460, 0, :east
unit :sludge, 461, 0, :east
unit :wizard, 465, 0, :east
unit :captive, 466, 0, :east
unit :thick_sludge, 478, 0, :east
unit :thick_sludge, 479, 0, :east
unit :captive, 483, 0, :east
unit :captive, 485, 0, :east
unit :sludge, 489, 0, :east
unit :thick_sludge, 491, 0, :east
unit :wizard, 497, 0, :east
unit :sludge, 503, 0, :east
unit :archer, 507, 0, :east
unit :wizard, 510, 0, :east
unit :captive, 511, 0, :east
unit :archer, 512, 0, :east
unit :thick_sludge, 517, 0, :east
unit :thick_sludge, 518, 0, :east
unit :sludge, 522, 0, :east
unit :archer, 524, 0, :east
unit :captive, 529, 0, :east
unit :sludge, 534, 0, :east
unit :sludge, 536, 0, :east
unit :thick_sludge, 538, 0, :east
unit :captive, 539, 0, :east
unit :archer, 545, 0, :east
unit :wizard, 553, 0, :east
unit :thick_sludge, 555, 0, :east
unit :captive, 560, 0, :east
unit :captive, 561, 0, :east
unit :captive, 564, 0, :east
unit :thick_sludge, 585, 0, :east
unit :archer, 588, 0, :east
unit :thick_sludge, 589, 0, :east
unit :captive, 591, 0, :east
unit :captive, 595, 0, :east
unit :sludge, 598, 0, :east
unit :wizard, 606, 0, :east
unit :archer, 615, 0, :east
unit :captive, 617, 0, :east
unit :archer, 618, 0, :east
unit :sludge, 626, 0, :east
unit :sludge, 629, 0, :east
unit :archer, 632, 0, :east
unit :wizard, 636, 0, :east
unit :sludge, 640, 0, :east
unit :thick_sludge, 648, 0, :west
unit :wizard, 652, 0, :west
unit :sludge, 655, 0, :west
unit :sludge, 657, 0, :west
unit :wizard, 663, 0, :west
unit :thick_sludge, 667, 0, :west
unit :sludge, 672, 0, :west
