#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S C               a  w    S  a C       aSa s      C aw    a   s     S   C   s  wa   w a            s         s  sa S  SS    Cw  s    S a  s  C    w s   C SC  s         w  s       C  ss a sswa    Cs    S  w C     C   Ca a     C    CS          sCC            wasC       a Ss  S      w C   @    a      w   a     s        S  s  CSSa s        S  w  C  S   C S       C  w              s         a C    C  C      s  s  s       s   sC      S         S  CS SCa a  w  w s SCC  C  w      a    s C  s        Sa    s    s  C    >C a   C             C   a a     C C            S     s   s        S C  sC     as    SCS  ss S s         S s    w  a  s            wS               Sas       s     C w  S     w   s   a wS s     a s  C       w    C         C a    ss a        a w     w w      a|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 775
ace_score 3875
size 775, 1
stairs 516, 0

warrior 288, 0, :east

unit :thick_sludge, 1, 0, :east
unit :captive, 3, 0, :east
unit :archer, 19, 0, :east
unit :wizard, 22, 0, :east
unit :thick_sludge, 27, 0, :east
unit :archer, 30, 0, :east
unit :captive, 32, 0, :east
unit :archer, 40, 0, :east
unit :thick_sludge, 41, 0, :east
unit :archer, 42, 0, :east
unit :sludge, 44, 0, :east
unit :captive, 51, 0, :east
unit :archer, 53, 0, :east
unit :wizard, 54, 0, :east
unit :archer, 59, 0, :east
unit :sludge, 63, 0, :east
unit :thick_sludge, 69, 0, :east
unit :captive, 73, 0, :east
unit :sludge, 77, 0, :east
unit :wizard, 80, 0, :east
unit :archer, 81, 0, :east
unit :wizard, 85, 0, :east
unit :archer, 87, 0, :east
unit :sludge, 100, 0, :east
unit :sludge, 110, 0, :east
unit :sludge, 113, 0, :east
unit :archer, 114, 0, :east
unit :thick_sludge, 116, 0, :east
unit :thick_sludge, 119, 0, :east
unit :thick_sludge, 120, 0, :east
unit :captive, 125, 0, :east
unit :wizard, 126, 0, :east
unit :sludge, 129, 0, :east
unit :thick_sludge, 134, 0, :east
unit :archer, 136, 0, :east
unit :sludge, 139, 0, :east
unit :captive, 142, 0, :east
unit :wizard, 147, 0, :east
unit :sludge, 149, 0, :east
unit :captive, 153, 0, :east
unit :thick_sludge, 155, 0, :east
unit :captive, 156, 0, :east
unit :sludge, 159, 0, :east
unit :wizard, 169, 0, :east
unit :sludge, 172, 0, :east
unit :captive, 180, 0, :east
unit :sludge, 183, 0, :east
unit :sludge, 184, 0, :east
unit :archer, 186, 0, :east
unit :sludge, 188, 0, :east
unit :sludge, 189, 0, :east
unit :wizard, 190, 0, :east
unit :archer, 191, 0, :east
unit :captive, 196, 0, :east
unit :sludge, 197, 0, :east
unit :thick_sludge, 202, 0, :east
unit :wizard, 205, 0, :east
unit :captive, 207, 0, :east
unit :captive, 213, 0, :east
unit :captive, 217, 0, :east
unit :archer, 218, 0, :east
unit :archer, 220, 0, :east
unit :captive, 226, 0, :east
unit :captive, 231, 0, :east
unit :thick_sludge, 232, 0, :east
unit :sludge, 243, 0, :east
unit :captive, 244, 0, :east
unit :captive, 245, 0, :east
unit :wizard, 258, 0, :east
unit :archer, 259, 0, :east
unit :sludge, 260, 0, :east
unit :captive, 261, 0, :east
unit :archer, 269, 0, :east
unit :thick_sludge, 271, 0, :east
unit :sludge, 272, 0, :east
unit :thick_sludge, 275, 0, :east
unit :wizard, 282, 0, :east
unit :captive, 284, 0, :east
unit :archer, 293, 0, :west
unit :wizard, 300, 0, :west
unit :archer, 304, 0, :west
unit :sludge, 310, 0, :west
unit :thick_sludge, 319, 0, :west
unit :sludge, 322, 0, :west
unit :captive, 325, 0, :west
unit :thick_sludge, 326, 0, :west
unit :thick_sludge, 327, 0, :west
unit :archer, 328, 0, :west
unit :sludge, 330, 0, :west
unit :thick_sludge, 339, 0, :west
unit :wizard, 342, 0, :west
unit :captive, 345, 0, :west
unit :thick_sludge, 348, 0, :west
unit :captive, 352, 0, :west
unit :thick_sludge, 354, 0, :west
unit :captive, 362, 0, :west
unit :wizard, 365, 0, :west
unit :sludge, 380, 0, :west
unit :archer, 390, 0, :west
unit :captive, 392, 0, :west
unit :captive, 397, 0, :west
unit :captive, 400, 0, :west
unit :sludge, 407, 0, :west
unit :sludge, 410, 0, :west
unit :sludge, 413, 0, :west
unit :sludge, 421, 0, :west
unit :sludge, 425, 0, :west
unit :captive, 426, 0, :west
unit :thick_sludge, 433, 0, :west
unit :thick_sludge, 443, 0, :west
unit :captive, 446, 0, :west
unit :thick_sludge, 447, 0, :west
unit :thick_sludge, 449, 0, :west
unit :captive, 450, 0, :west
unit :archer, 451, 0, :west
unit :archer, 453, 0, :west
unit :wizard, 456, 0, :west
unit :wizard, 459, 0, :west
unit :sludge, 461, 0, :west
unit :thick_sludge, 463, 0, :west
unit :captive, 464, 0, :west
unit :captive, 465, 0, :west
unit :captive, 468, 0, :west
unit :wizard, 471, 0, :west
unit :archer, 478, 0, :west
unit :sludge, 483, 0, :west
unit :captive, 485, 0, :west
unit :sludge, 488, 0, :west
unit :thick_sludge, 497, 0, :west
unit :archer, 498, 0, :west
unit :sludge, 503, 0, :west
unit :sludge, 508, 0, :west
unit :captive, 511, 0, :west
unit :captive, 517, 0, :west
unit :archer, 519, 0, :west
unit :captive, 523, 0, :west
unit :captive, 537, 0, :west
unit :archer, 541, 0, :west
unit :archer, 543, 0, :west
unit :captive, 549, 0, :west
unit :captive, 551, 0, :west
unit :thick_sludge, 564, 0, :west
unit :sludge, 570, 0, :west
unit :sludge, 574, 0, :west
unit :thick_sludge, 583, 0, :west
unit :captive, 585, 0, :west
unit :sludge, 588, 0, :west
unit :captive, 589, 0, :west
unit :archer, 595, 0, :west
unit :sludge, 596, 0, :west
unit :thick_sludge, 601, 0, :west
unit :captive, 602, 0, :west
unit :thick_sludge, 603, 0, :west
unit :sludge, 606, 0, :west
unit :sludge, 607, 0, :west
unit :thick_sludge, 609, 0, :west
unit :sludge, 611, 0, :west
unit :thick_sludge, 621, 0, :west
unit :sludge, 623, 0, :west
unit :wizard, 628, 0, :west
unit :archer, 631, 0, :west
unit :sludge, 634, 0, :west
unit :wizard, 647, 0, :west
unit :thick_sludge, 648, 0, :west
unit :thick_sludge, 664, 0, :west
unit :archer, 665, 0, :west
unit :sludge, 666, 0, :west
unit :sludge, 674, 0, :west
unit :captive, 680, 0, :west
unit :wizard, 682, 0, :west
unit :thick_sludge, 685, 0, :west
unit :wizard, 691, 0, :west
unit :sludge, 695, 0, :west
unit :archer, 699, 0, :west
unit :wizard, 701, 0, :west
unit :thick_sludge, 702, 0, :west
unit :sludge, 704, 0, :west
unit :archer, 710, 0, :west
unit :sludge, 712, 0, :west
unit :captive, 715, 0, :west
unit :wizard, 723, 0, :west
unit :captive, 728, 0, :west
unit :captive, 738, 0, :west
unit :archer, 740, 0, :west
unit :sludge, 745, 0, :west
unit :sludge, 746, 0, :west
unit :archer, 748, 0, :west
unit :archer, 757, 0, :west
unit :wizard, 759, 0, :west
unit :wizard, 765, 0, :west
unit :wizard, 767, 0, :west
unit :archer, 774, 0, :west
