#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |         SC  C C    S  a  s   w a      C         a   C     w S           S       sC    w  S aS SS    S       a as  S         s s a       s  C   S sS a      s      C    s         a CS  aSw       w     S  a  s     Ca      S a S    S   ss         S  w   S SC w S    w    w   C        C s      s> C sa    C         as w    CC  sCC              S S S        a  w  a w s  S     S a  S        s   w C a     C w a   S    C  a       S   w w         w w             @   wC        C  aS aa    Ca S  a  w  S  S  S CC   a   CwC s     a               S      s      S s         w S       w S a      Sa s  a w  w   |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 599
ace_score 2995
size 599, 1
stairs 291, 0

warrior 456, 0, :east

unit :thick_sludge, 9, 0, :east
unit :captive, 10, 0, :east
unit :captive, 13, 0, :east
unit :captive, 15, 0, :east
unit :thick_sludge, 20, 0, :east
unit :archer, 23, 0, :east
unit :sludge, 26, 0, :east
unit :wizard, 30, 0, :east
unit :archer, 32, 0, :east
unit :captive, 39, 0, :east
unit :archer, 49, 0, :east
unit :captive, 53, 0, :east
unit :wizard, 59, 0, :east
unit :thick_sludge, 61, 0, :east
unit :thick_sludge, 73, 0, :east
unit :sludge, 81, 0, :east
unit :captive, 82, 0, :east
unit :wizard, 87, 0, :east
unit :thick_sludge, 90, 0, :east
unit :archer, 92, 0, :east
unit :thick_sludge, 93, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 96, 0, :east
unit :thick_sludge, 101, 0, :east
unit :archer, 109, 0, :east
unit :archer, 111, 0, :east
unit :sludge, 112, 0, :east
unit :thick_sludge, 115, 0, :east
unit :sludge, 125, 0, :east
unit :sludge, 127, 0, :east
unit :archer, 129, 0, :east
unit :sludge, 137, 0, :east
unit :captive, 140, 0, :east
unit :thick_sludge, 144, 0, :east
unit :sludge, 146, 0, :east
unit :thick_sludge, 147, 0, :east
unit :archer, 149, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 163, 0, :east
unit :sludge, 168, 0, :east
unit :archer, 178, 0, :east
unit :captive, 180, 0, :east
unit :thick_sludge, 181, 0, :east
unit :archer, 184, 0, :east
unit :thick_sludge, 185, 0, :east
unit :wizard, 186, 0, :east
unit :wizard, 194, 0, :east
unit :thick_sludge, 200, 0, :east
unit :archer, 203, 0, :east
unit :sludge, 206, 0, :east
unit :captive, 212, 0, :east
unit :archer, 213, 0, :east
unit :thick_sludge, 220, 0, :east
unit :archer, 222, 0, :east
unit :thick_sludge, 224, 0, :east
unit :thick_sludge, 229, 0, :east
unit :sludge, 233, 0, :east
unit :sludge, 234, 0, :east
unit :thick_sludge, 244, 0, :east
unit :wizard, 247, 0, :east
unit :thick_sludge, 251, 0, :east
unit :thick_sludge, 253, 0, :east
unit :captive, 254, 0, :east
unit :wizard, 256, 0, :east
unit :thick_sludge, 258, 0, :east
unit :wizard, 263, 0, :east
unit :wizard, 268, 0, :east
unit :captive, 272, 0, :east
unit :captive, 281, 0, :east
unit :sludge, 283, 0, :east
unit :sludge, 290, 0, :east
unit :captive, 293, 0, :east
unit :sludge, 295, 0, :east
unit :archer, 296, 0, :east
unit :captive, 301, 0, :east
unit :archer, 311, 0, :east
unit :sludge, 312, 0, :east
unit :wizard, 314, 0, :east
unit :captive, 319, 0, :east
unit :captive, 320, 0, :east
unit :sludge, 323, 0, :east
unit :captive, 324, 0, :east
unit :captive, 325, 0, :east
unit :thick_sludge, 340, 0, :east
unit :thick_sludge, 342, 0, :east
unit :thick_sludge, 344, 0, :east
unit :archer, 353, 0, :east
unit :wizard, 356, 0, :east
unit :archer, 359, 0, :east
unit :wizard, 361, 0, :east
unit :sludge, 363, 0, :east
unit :thick_sludge, 366, 0, :east
unit :thick_sludge, 372, 0, :east
unit :archer, 374, 0, :east
unit :thick_sludge, 377, 0, :east
unit :sludge, 386, 0, :east
unit :wizard, 390, 0, :east
unit :captive, 392, 0, :east
unit :archer, 394, 0, :east
unit :captive, 400, 0, :east
unit :wizard, 402, 0, :east
unit :archer, 404, 0, :east
unit :thick_sludge, 408, 0, :east
unit :captive, 413, 0, :east
unit :archer, 416, 0, :east
unit :thick_sludge, 424, 0, :east
unit :wizard, 428, 0, :east
unit :wizard, 430, 0, :east
unit :wizard, 440, 0, :east
unit :wizard, 442, 0, :east
unit :wizard, 460, 0, :west
unit :captive, 461, 0, :west
unit :captive, 470, 0, :west
unit :archer, 473, 0, :west
unit :thick_sludge, 474, 0, :west
unit :archer, 476, 0, :west
unit :archer, 477, 0, :west
unit :captive, 482, 0, :west
unit :archer, 483, 0, :west
unit :thick_sludge, 485, 0, :west
unit :archer, 488, 0, :west
unit :wizard, 491, 0, :west
unit :thick_sludge, 494, 0, :west
unit :thick_sludge, 497, 0, :west
unit :thick_sludge, 500, 0, :west
unit :captive, 502, 0, :west
unit :captive, 503, 0, :west
unit :archer, 507, 0, :west
unit :captive, 511, 0, :west
unit :wizard, 512, 0, :west
unit :captive, 513, 0, :west
unit :sludge, 515, 0, :west
unit :archer, 521, 0, :west
unit :thick_sludge, 537, 0, :west
unit :sludge, 544, 0, :west
unit :thick_sludge, 551, 0, :west
unit :sludge, 553, 0, :west
unit :wizard, 563, 0, :west
unit :thick_sludge, 565, 0, :west
unit :wizard, 573, 0, :west
unit :thick_sludge, 575, 0, :west
unit :archer, 577, 0, :west
unit :thick_sludge, 584, 0, :west
unit :archer, 585, 0, :west
unit :sludge, 587, 0, :west
unit :archer, 590, 0, :west
unit :wizard, 592, 0, :west
unit :wizard, 595, 0, :west
