#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   Cs   Ss     s  S        C        C   ws   Cs      s   a     ass a   w    S   s  Cw          C   S  a       SC  s C    as    w    aC        C ss  a s w       w    sC w     S w         a a   a  sC  S   @       a  C w                              C   C S  S      w C   Sa     a C     sC   C Ca    w             sSa a      C             a   S  C C   a      S w  S  a  w S   Ca         C  a     sw w  s    s  Cw   w  s  a C     S   S C       a     a s    s       s s     SC  w    S C>         a              s   S     w    C a  a            w     s Sa      C      w     S   a    S    S      aa     C s  C  SS  CC       S    a   S   S  S        s a    sC  S s CsS      Ss        C      aS       sas     aC s s     aSa   S w            w a  ss  S a  C    s s    s     s C  C    SC   w        C   a   a swsa s       aa     a        w  S    a w    aCa   a    a wS Cs           S    aS  a C    S w |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 891
ace_score 4455
size 891, 1
stairs 481, 0

warrior 203, 0, :east

unit :captive, 3, 0, :east
unit :sludge, 4, 0, :east
unit :thick_sludge, 8, 0, :east
unit :sludge, 9, 0, :east
unit :sludge, 15, 0, :east
unit :thick_sludge, 18, 0, :east
unit :captive, 27, 0, :east
unit :captive, 36, 0, :east
unit :wizard, 40, 0, :east
unit :sludge, 41, 0, :east
unit :captive, 45, 0, :east
unit :sludge, 46, 0, :east
unit :sludge, 53, 0, :east
unit :archer, 57, 0, :east
unit :archer, 63, 0, :east
unit :sludge, 64, 0, :east
unit :sludge, 65, 0, :east
unit :archer, 67, 0, :east
unit :wizard, 71, 0, :east
unit :thick_sludge, 76, 0, :east
unit :sludge, 80, 0, :east
unit :captive, 83, 0, :east
unit :wizard, 84, 0, :east
unit :captive, 95, 0, :east
unit :thick_sludge, 99, 0, :east
unit :archer, 102, 0, :east
unit :thick_sludge, 110, 0, :east
unit :captive, 111, 0, :east
unit :sludge, 114, 0, :east
unit :captive, 116, 0, :east
unit :archer, 121, 0, :east
unit :sludge, 122, 0, :east
unit :wizard, 127, 0, :east
unit :archer, 132, 0, :east
unit :captive, 133, 0, :east
unit :captive, 142, 0, :east
unit :sludge, 144, 0, :east
unit :sludge, 145, 0, :east
unit :archer, 148, 0, :east
unit :sludge, 150, 0, :east
unit :wizard, 152, 0, :east
unit :wizard, 160, 0, :east
unit :sludge, 165, 0, :east
unit :captive, 166, 0, :east
unit :wizard, 168, 0, :east
unit :thick_sludge, 174, 0, :east
unit :wizard, 176, 0, :east
unit :archer, 186, 0, :east
unit :archer, 188, 0, :east
unit :archer, 192, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 196, 0, :east
unit :thick_sludge, 199, 0, :east
unit :archer, 211, 0, :west
unit :captive, 214, 0, :west
unit :wizard, 216, 0, :west
unit :captive, 247, 0, :west
unit :captive, 251, 0, :west
unit :thick_sludge, 253, 0, :west
unit :thick_sludge, 256, 0, :west
unit :wizard, 263, 0, :west
unit :captive, 265, 0, :west
unit :thick_sludge, 269, 0, :west
unit :archer, 270, 0, :west
unit :archer, 276, 0, :west
unit :captive, 278, 0, :west
unit :sludge, 284, 0, :west
unit :captive, 285, 0, :west
unit :captive, 289, 0, :west
unit :captive, 291, 0, :west
unit :archer, 292, 0, :west
unit :wizard, 297, 0, :west
unit :sludge, 311, 0, :west
unit :thick_sludge, 312, 0, :west
unit :archer, 313, 0, :west
unit :archer, 315, 0, :west
unit :captive, 322, 0, :west
unit :archer, 336, 0, :west
unit :thick_sludge, 340, 0, :west
unit :captive, 343, 0, :west
unit :captive, 345, 0, :west
unit :archer, 349, 0, :west
unit :thick_sludge, 356, 0, :west
unit :wizard, 358, 0, :west
unit :thick_sludge, 361, 0, :west
unit :archer, 364, 0, :west
unit :wizard, 367, 0, :west
unit :thick_sludge, 369, 0, :west
unit :captive, 373, 0, :west
unit :archer, 374, 0, :west
unit :captive, 384, 0, :west
unit :archer, 387, 0, :west
unit :sludge, 393, 0, :west
unit :wizard, 394, 0, :west
unit :wizard, 396, 0, :west
unit :sludge, 399, 0, :west
unit :sludge, 404, 0, :west
unit :captive, 407, 0, :west
unit :wizard, 408, 0, :west
unit :wizard, 412, 0, :west
unit :sludge, 415, 0, :west
unit :archer, 418, 0, :west
unit :captive, 420, 0, :west
unit :thick_sludge, 426, 0, :west
unit :thick_sludge, 430, 0, :west
unit :captive, 432, 0, :west
unit :archer, 440, 0, :west
unit :archer, 446, 0, :west
unit :sludge, 448, 0, :west
unit :sludge, 453, 0, :west
unit :sludge, 461, 0, :west
unit :sludge, 463, 0, :west
unit :thick_sludge, 469, 0, :west
unit :captive, 470, 0, :west
unit :wizard, 473, 0, :west
unit :thick_sludge, 478, 0, :west
unit :captive, 480, 0, :west
unit :archer, 491, 0, :west
unit :sludge, 506, 0, :west
unit :thick_sludge, 510, 0, :west
unit :wizard, 516, 0, :west
unit :captive, 521, 0, :west
unit :archer, 523, 0, :west
unit :archer, 526, 0, :west
unit :wizard, 539, 0, :west
unit :sludge, 545, 0, :west
unit :thick_sludge, 547, 0, :west
unit :archer, 548, 0, :west
unit :captive, 555, 0, :west
unit :wizard, 562, 0, :west
unit :thick_sludge, 568, 0, :west
unit :archer, 572, 0, :west
unit :thick_sludge, 577, 0, :west
unit :thick_sludge, 582, 0, :west
unit :archer, 589, 0, :west
unit :archer, 590, 0, :west
unit :captive, 596, 0, :west
unit :sludge, 598, 0, :west
unit :captive, 601, 0, :west
unit :thick_sludge, 604, 0, :west
unit :thick_sludge, 605, 0, :west
unit :captive, 608, 0, :west
unit :captive, 609, 0, :west
unit :thick_sludge, 617, 0, :west
unit :archer, 622, 0, :west
unit :thick_sludge, 626, 0, :west
unit :thick_sludge, 630, 0, :west
unit :thick_sludge, 633, 0, :west
unit :sludge, 642, 0, :west
unit :archer, 644, 0, :west
unit :sludge, 649, 0, :west
unit :captive, 650, 0, :west
unit :thick_sludge, 653, 0, :west
unit :sludge, 655, 0, :west
unit :captive, 657, 0, :west
unit :sludge, 658, 0, :west
unit :thick_sludge, 659, 0, :west
unit :thick_sludge, 666, 0, :west
unit :sludge, 667, 0, :west
unit :captive, 676, 0, :west
unit :archer, 683, 0, :west
unit :thick_sludge, 684, 0, :west
unit :sludge, 692, 0, :west
unit :archer, 693, 0, :west
unit :sludge, 694, 0, :west
unit :archer, 700, 0, :west
unit :captive, 701, 0, :west
unit :sludge, 703, 0, :west
unit :sludge, 705, 0, :west
unit :archer, 711, 0, :west
unit :thick_sludge, 712, 0, :west
unit :archer, 713, 0, :west
unit :thick_sludge, 717, 0, :west
unit :wizard, 719, 0, :west
unit :wizard, 732, 0, :west
unit :archer, 734, 0, :west
unit :sludge, 737, 0, :west
unit :sludge, 738, 0, :west
unit :thick_sludge, 741, 0, :west
unit :archer, 743, 0, :west
unit :captive, 746, 0, :west
unit :sludge, 751, 0, :west
unit :sludge, 753, 0, :west
unit :sludge, 758, 0, :west
unit :sludge, 764, 0, :west
unit :captive, 766, 0, :west
unit :captive, 769, 0, :west
unit :thick_sludge, 774, 0, :west
unit :captive, 775, 0, :west
unit :wizard, 779, 0, :west
unit :captive, 788, 0, :west
unit :archer, 792, 0, :west
unit :archer, 796, 0, :west
unit :sludge, 798, 0, :west
unit :wizard, 799, 0, :west
unit :sludge, 800, 0, :west
unit :archer, 801, 0, :west
unit :sludge, 803, 0, :west
unit :archer, 811, 0, :west
unit :archer, 812, 0, :west
unit :archer, 818, 0, :west
unit :wizard, 827, 0, :west
unit :thick_sludge, 830, 0, :west
unit :archer, 835, 0, :west
unit :wizard, 837, 0, :west
unit :archer, 842, 0, :west
unit :captive, 843, 0, :west
unit :archer, 844, 0, :west
unit :archer, 848, 0, :west
unit :archer, 853, 0, :west
unit :wizard, 855, 0, :west
unit :thick_sludge, 856, 0, :west
unit :captive, 858, 0, :west
unit :sludge, 859, 0, :west
unit :thick_sludge, 871, 0, :west
unit :archer, 876, 0, :west
unit :thick_sludge, 877, 0, :west
unit :archer, 880, 0, :west
unit :captive, 882, 0, :west
unit :thick_sludge, 887, 0, :west
unit :wizard, 889, 0, :west
