#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C    CSa C   a    a   w    w CC  S S   s  sa a   as  w C S   S SC    wsCC aa  S  S  C    w SC    S s  w  a             S  w  w  w      w Sa        s    ws   @     aa    w S    S s     w    C       CS  S   sC   w    s      a      a   w     a a   s  S    s     S a C  C Cs S    s     C     a  w  S     a      w w C    C  sS  a           w  s    s   Sw s     w    a        s   s     s         S        S                 a    w  S  w    CS  w  SS        a a w s    Sa            C              w  w SS s           w       s     w       S     a   C      Cw   s       s a    CCs s       a   a  s     a aa         w   C     C CS    w  C         w                 S   C         aa   a wa a w  S C  s  C  a  s    C      a sSSS  s     CC  CSs      >   a    SSw w  a   a   S  Cs s s s   S                a       sS    aCC C   S           a     |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 835
ace_score 4175
size 835, 1
stairs 740, 0

warrior 159, 0, :east

unit :captive, 2, 0, :east
unit :captive, 7, 0, :east
unit :thick_sludge, 8, 0, :east
unit :archer, 9, 0, :east
unit :captive, 11, 0, :east
unit :archer, 15, 0, :east
unit :archer, 20, 0, :east
unit :wizard, 24, 0, :east
unit :wizard, 29, 0, :east
unit :captive, 31, 0, :east
unit :captive, 32, 0, :east
unit :thick_sludge, 35, 0, :east
unit :thick_sludge, 37, 0, :east
unit :sludge, 41, 0, :east
unit :sludge, 44, 0, :east
unit :archer, 45, 0, :east
unit :archer, 47, 0, :east
unit :archer, 51, 0, :east
unit :sludge, 52, 0, :east
unit :wizard, 55, 0, :east
unit :captive, 57, 0, :east
unit :thick_sludge, 59, 0, :east
unit :thick_sludge, 63, 0, :east
unit :thick_sludge, 65, 0, :east
unit :captive, 66, 0, :east
unit :wizard, 71, 0, :east
unit :sludge, 72, 0, :east
unit :captive, 73, 0, :east
unit :captive, 74, 0, :east
unit :archer, 76, 0, :east
unit :archer, 77, 0, :east
unit :thick_sludge, 80, 0, :east
unit :thick_sludge, 83, 0, :east
unit :captive, 86, 0, :east
unit :wizard, 91, 0, :east
unit :thick_sludge, 93, 0, :east
unit :captive, 94, 0, :east
unit :thick_sludge, 99, 0, :east
unit :sludge, 101, 0, :east
unit :wizard, 104, 0, :east
unit :archer, 107, 0, :east
unit :thick_sludge, 121, 0, :east
unit :wizard, 124, 0, :east
unit :wizard, 127, 0, :east
unit :wizard, 130, 0, :east
unit :wizard, 137, 0, :east
unit :thick_sludge, 139, 0, :east
unit :archer, 140, 0, :east
unit :sludge, 149, 0, :east
unit :wizard, 154, 0, :east
unit :sludge, 155, 0, :east
unit :archer, 165, 0, :west
unit :archer, 166, 0, :west
unit :wizard, 171, 0, :west
unit :thick_sludge, 173, 0, :west
unit :thick_sludge, 178, 0, :west
unit :sludge, 180, 0, :west
unit :wizard, 186, 0, :west
unit :captive, 191, 0, :west
unit :captive, 199, 0, :west
unit :thick_sludge, 200, 0, :west
unit :thick_sludge, 203, 0, :west
unit :sludge, 207, 0, :west
unit :captive, 208, 0, :west
unit :wizard, 212, 0, :west
unit :sludge, 217, 0, :west
unit :archer, 224, 0, :west
unit :archer, 231, 0, :west
unit :wizard, 235, 0, :west
unit :archer, 241, 0, :west
unit :archer, 243, 0, :west
unit :sludge, 247, 0, :west
unit :thick_sludge, 250, 0, :west
unit :sludge, 255, 0, :west
unit :thick_sludge, 261, 0, :west
unit :archer, 263, 0, :west
unit :captive, 265, 0, :west
unit :captive, 268, 0, :west
unit :captive, 270, 0, :west
unit :sludge, 271, 0, :west
unit :thick_sludge, 273, 0, :west
unit :sludge, 278, 0, :west
unit :captive, 284, 0, :west
unit :archer, 290, 0, :west
unit :wizard, 293, 0, :west
unit :thick_sludge, 296, 0, :west
unit :archer, 302, 0, :west
unit :wizard, 309, 0, :west
unit :wizard, 311, 0, :west
unit :captive, 313, 0, :west
unit :captive, 318, 0, :west
unit :sludge, 321, 0, :west
unit :thick_sludge, 322, 0, :west
unit :archer, 325, 0, :west
unit :wizard, 337, 0, :west
unit :sludge, 340, 0, :west
unit :sludge, 345, 0, :west
unit :thick_sludge, 349, 0, :west
unit :wizard, 350, 0, :west
unit :sludge, 352, 0, :west
unit :wizard, 358, 0, :west
unit :archer, 363, 0, :west
unit :sludge, 372, 0, :west
unit :sludge, 376, 0, :west
unit :sludge, 382, 0, :west
unit :thick_sludge, 392, 0, :west
unit :thick_sludge, 401, 0, :west
unit :archer, 419, 0, :west
unit :wizard, 424, 0, :west
unit :thick_sludge, 427, 0, :west
unit :wizard, 430, 0, :west
unit :captive, 435, 0, :west
unit :thick_sludge, 436, 0, :west
unit :wizard, 439, 0, :west
unit :thick_sludge, 442, 0, :west
unit :thick_sludge, 443, 0, :west
unit :archer, 452, 0, :west
unit :archer, 454, 0, :west
unit :wizard, 456, 0, :west
unit :sludge, 458, 0, :west
unit :thick_sludge, 463, 0, :west
unit :archer, 464, 0, :west
unit :captive, 477, 0, :west
unit :wizard, 492, 0, :west
unit :wizard, 495, 0, :west
unit :thick_sludge, 497, 0, :west
unit :thick_sludge, 498, 0, :west
unit :sludge, 500, 0, :west
unit :wizard, 512, 0, :west
unit :sludge, 520, 0, :west
unit :wizard, 526, 0, :west
unit :thick_sludge, 534, 0, :west
unit :archer, 540, 0, :west
unit :captive, 544, 0, :west
unit :captive, 551, 0, :west
unit :wizard, 552, 0, :west
unit :sludge, 556, 0, :west
unit :sludge, 564, 0, :west
unit :archer, 566, 0, :west
unit :captive, 571, 0, :west
unit :captive, 572, 0, :west
unit :sludge, 573, 0, :west
unit :sludge, 575, 0, :west
unit :archer, 583, 0, :west
unit :archer, 587, 0, :west
unit :sludge, 590, 0, :west
unit :archer, 596, 0, :west
unit :archer, 598, 0, :west
unit :archer, 599, 0, :west
unit :wizard, 609, 0, :west
unit :captive, 613, 0, :west
unit :captive, 619, 0, :west
unit :captive, 621, 0, :west
unit :thick_sludge, 622, 0, :west
unit :wizard, 627, 0, :west
unit :captive, 630, 0, :west
unit :wizard, 640, 0, :west
unit :thick_sludge, 658, 0, :west
unit :captive, 662, 0, :west
unit :archer, 672, 0, :west
unit :archer, 673, 0, :west
unit :archer, 677, 0, :west
unit :wizard, 679, 0, :west
unit :archer, 680, 0, :west
unit :archer, 682, 0, :west
unit :wizard, 684, 0, :west
unit :thick_sludge, 687, 0, :west
unit :captive, 689, 0, :west
unit :sludge, 692, 0, :west
unit :captive, 695, 0, :west
unit :archer, 698, 0, :west
unit :sludge, 701, 0, :west
unit :captive, 706, 0, :west
unit :archer, 713, 0, :west
unit :sludge, 715, 0, :west
unit :thick_sludge, 716, 0, :west
unit :thick_sludge, 717, 0, :west
unit :thick_sludge, 718, 0, :west
unit :sludge, 721, 0, :west
unit :captive, 727, 0, :west
unit :captive, 728, 0, :west
unit :captive, 731, 0, :west
unit :thick_sludge, 732, 0, :west
unit :sludge, 733, 0, :west
unit :archer, 744, 0, :west
unit :thick_sludge, 749, 0, :west
unit :thick_sludge, 750, 0, :west
unit :wizard, 751, 0, :west
unit :wizard, 753, 0, :west
unit :archer, 756, 0, :west
unit :archer, 760, 0, :west
unit :thick_sludge, 764, 0, :west
unit :captive, 767, 0, :west
unit :sludge, 768, 0, :west
unit :sludge, 770, 0, :west
unit :sludge, 772, 0, :west
unit :sludge, 774, 0, :west
unit :thick_sludge, 778, 0, :west
unit :archer, 795, 0, :west
unit :sludge, 803, 0, :west
unit :thick_sludge, 804, 0, :west
unit :archer, 809, 0, :west
unit :captive, 810, 0, :west
unit :captive, 811, 0, :west
unit :captive, 813, 0, :west
unit :thick_sludge, 817, 0, :west
unit :archer, 829, 0, :west
