#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C    s   a      s      w     S   Cs  w             as      S a S s         ss      sS  C SC a          SC S w a  s a    aC    w        ss         s            S      Sa     s             S       a C   a             a  w          w      C  S        S   SsCs   a    w    S  Sa       s            s       S             w              a      s  sw         sSS s    a    w  a        s  S  s       w   s   a Ss           w s    a     s   S  w       ss s   a w  CC ws S  s Sw  wS    w       as    a    a   s    a   a s   s      s   w     a  s a     w aS s   S Cw  CS   s              a      s       S  S  as  S a  S w     as   C  w     a a   w s w     Ss   ss        a  s    S >          Sa     S   a   w   s  S  w saSC a   w      w      SS    ssC   C  @  a  aC         s  a    a  a a SSS  Sw s   s   w S  a s   CCSC   aS     aw  C     s  s   C  sS a |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 844
ace_score 4220
size 844, 1
stairs 670, 0

warrior 746, 0, :east

unit :captive, 0, 0, :east
unit :sludge, 5, 0, :east
unit :archer, 9, 0, :east
unit :sludge, 16, 0, :east
unit :wizard, 23, 0, :east
unit :thick_sludge, 29, 0, :east
unit :captive, 33, 0, :east
unit :sludge, 34, 0, :east
unit :wizard, 37, 0, :east
unit :archer, 51, 0, :east
unit :sludge, 52, 0, :east
unit :thick_sludge, 59, 0, :east
unit :archer, 61, 0, :east
unit :thick_sludge, 63, 0, :east
unit :sludge, 65, 0, :east
unit :sludge, 75, 0, :east
unit :sludge, 76, 0, :east
unit :sludge, 83, 0, :east
unit :thick_sludge, 84, 0, :east
unit :captive, 87, 0, :east
unit :thick_sludge, 89, 0, :east
unit :captive, 90, 0, :east
unit :archer, 92, 0, :east
unit :thick_sludge, 103, 0, :east
unit :captive, 104, 0, :east
unit :thick_sludge, 106, 0, :east
unit :wizard, 108, 0, :east
unit :archer, 110, 0, :east
unit :sludge, 113, 0, :east
unit :archer, 115, 0, :east
unit :archer, 120, 0, :east
unit :captive, 121, 0, :east
unit :wizard, 126, 0, :east
unit :sludge, 135, 0, :east
unit :sludge, 136, 0, :east
unit :sludge, 146, 0, :east
unit :thick_sludge, 159, 0, :east
unit :thick_sludge, 166, 0, :east
unit :archer, 167, 0, :east
unit :sludge, 173, 0, :east
unit :thick_sludge, 187, 0, :east
unit :archer, 195, 0, :east
unit :captive, 197, 0, :east
unit :archer, 201, 0, :east
unit :archer, 215, 0, :east
unit :wizard, 218, 0, :east
unit :wizard, 229, 0, :east
unit :captive, 236, 0, :east
unit :thick_sludge, 239, 0, :east
unit :thick_sludge, 248, 0, :east
unit :thick_sludge, 252, 0, :east
unit :sludge, 253, 0, :east
unit :captive, 254, 0, :east
unit :sludge, 255, 0, :east
unit :archer, 259, 0, :east
unit :wizard, 264, 0, :east
unit :thick_sludge, 269, 0, :east
unit :thick_sludge, 272, 0, :east
unit :archer, 273, 0, :east
unit :sludge, 281, 0, :east
unit :sludge, 294, 0, :east
unit :thick_sludge, 302, 0, :east
unit :wizard, 316, 0, :east
unit :archer, 331, 0, :east
unit :sludge, 338, 0, :east
unit :sludge, 341, 0, :east
unit :wizard, 342, 0, :east
unit :sludge, 352, 0, :east
unit :thick_sludge, 353, 0, :east
unit :thick_sludge, 354, 0, :east
unit :sludge, 356, 0, :east
unit :archer, 361, 0, :east
unit :wizard, 366, 0, :east
unit :archer, 369, 0, :east
unit :sludge, 378, 0, :east
unit :thick_sludge, 381, 0, :east
unit :sludge, 384, 0, :east
unit :wizard, 392, 0, :east
unit :sludge, 396, 0, :east
unit :archer, 400, 0, :east
unit :thick_sludge, 402, 0, :east
unit :sludge, 403, 0, :east
unit :wizard, 415, 0, :east
unit :sludge, 417, 0, :east
unit :archer, 422, 0, :east
unit :sludge, 428, 0, :east
unit :thick_sludge, 432, 0, :east
unit :wizard, 435, 0, :east
unit :sludge, 443, 0, :east
unit :sludge, 444, 0, :east
unit :sludge, 446, 0, :east
unit :archer, 450, 0, :east
unit :wizard, 452, 0, :east
unit :captive, 455, 0, :east
unit :captive, 456, 0, :east
unit :wizard, 458, 0, :east
unit :sludge, 459, 0, :east
unit :thick_sludge, 461, 0, :east
unit :sludge, 464, 0, :east
unit :thick_sludge, 466, 0, :east
unit :wizard, 467, 0, :east
unit :wizard, 470, 0, :east
unit :thick_sludge, 471, 0, :east
unit :wizard, 476, 0, :east
unit :archer, 484, 0, :east
unit :sludge, 485, 0, :east
unit :archer, 490, 0, :east
unit :archer, 495, 0, :east
unit :sludge, 499, 0, :east
unit :archer, 504, 0, :east
unit :archer, 508, 0, :east
unit :sludge, 510, 0, :east
unit :sludge, 514, 0, :east
unit :sludge, 521, 0, :east
unit :wizard, 525, 0, :east
unit :archer, 531, 0, :east
unit :sludge, 534, 0, :east
unit :archer, 536, 0, :east
unit :wizard, 542, 0, :east
unit :archer, 544, 0, :east
unit :thick_sludge, 545, 0, :east
unit :sludge, 547, 0, :east
unit :thick_sludge, 551, 0, :east
unit :captive, 553, 0, :east
unit :wizard, 554, 0, :east
unit :captive, 557, 0, :east
unit :thick_sludge, 558, 0, :east
unit :sludge, 562, 0, :east
unit :archer, 577, 0, :east
unit :sludge, 584, 0, :east
unit :thick_sludge, 592, 0, :east
unit :thick_sludge, 595, 0, :east
unit :archer, 598, 0, :east
unit :sludge, 599, 0, :east
unit :thick_sludge, 602, 0, :east
unit :archer, 604, 0, :east
unit :thick_sludge, 607, 0, :east
unit :wizard, 609, 0, :east
unit :archer, 615, 0, :east
unit :sludge, 616, 0, :east
unit :captive, 620, 0, :east
unit :wizard, 623, 0, :east
unit :archer, 629, 0, :east
unit :archer, 631, 0, :east
unit :wizard, 635, 0, :east
unit :sludge, 637, 0, :east
unit :wizard, 639, 0, :east
unit :thick_sludge, 645, 0, :east
unit :sludge, 646, 0, :east
unit :sludge, 650, 0, :east
unit :sludge, 651, 0, :east
unit :archer, 660, 0, :east
unit :sludge, 663, 0, :east
unit :thick_sludge, 668, 0, :east
unit :thick_sludge, 681, 0, :east
unit :archer, 682, 0, :east
unit :thick_sludge, 688, 0, :east
unit :archer, 692, 0, :east
unit :wizard, 696, 0, :east
unit :sludge, 700, 0, :east
unit :thick_sludge, 703, 0, :east
unit :wizard, 706, 0, :east
unit :sludge, 708, 0, :east
unit :archer, 709, 0, :east
unit :thick_sludge, 710, 0, :east
unit :captive, 711, 0, :east
unit :archer, 713, 0, :east
unit :wizard, 717, 0, :east
unit :wizard, 724, 0, :east
unit :thick_sludge, 731, 0, :east
unit :thick_sludge, 732, 0, :east
unit :sludge, 737, 0, :east
unit :sludge, 738, 0, :east
unit :captive, 739, 0, :east
unit :captive, 743, 0, :east
unit :archer, 749, 0, :west
unit :archer, 752, 0, :west
unit :captive, 753, 0, :west
unit :sludge, 763, 0, :west
unit :archer, 766, 0, :west
unit :archer, 771, 0, :west
unit :archer, 774, 0, :west
unit :archer, 776, 0, :west
unit :thick_sludge, 778, 0, :west
unit :thick_sludge, 779, 0, :west
unit :thick_sludge, 780, 0, :west
unit :thick_sludge, 783, 0, :west
unit :wizard, 784, 0, :west
unit :sludge, 786, 0, :west
unit :sludge, 790, 0, :west
unit :wizard, 794, 0, :west
unit :thick_sludge, 796, 0, :west
unit :archer, 799, 0, :west
unit :sludge, 801, 0, :west
unit :captive, 805, 0, :west
unit :captive, 806, 0, :west
unit :thick_sludge, 807, 0, :west
unit :captive, 808, 0, :west
unit :archer, 812, 0, :west
unit :thick_sludge, 813, 0, :west
unit :archer, 819, 0, :west
unit :wizard, 820, 0, :west
unit :captive, 823, 0, :west
unit :sludge, 829, 0, :west
unit :sludge, 832, 0, :west
unit :captive, 836, 0, :west
unit :sludge, 839, 0, :west
unit :thick_sludge, 840, 0, :west
unit :archer, 842, 0, :west
