#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s s      aS   saa a           C          a S    a       s  a       S          S s   w          ss  a     as  Sa   w  w       Ssa C         S   s    Sa w  s C  CC   s S      S   s   a w         S  s s    aa         S s  sCa  a  a s   S   s      a   C       a     C  S  w    CS S  sS    s        @  S   C sa w C  S     S        C  a         SCaa Cs CS      aC  CS  sSS       S s Ca    S          a      S  a    s   >S     w  aw  S s     S       a      S s  C  S  a     a       w    S a    wC         aC   S       a        w    S C w     C            a      w   S aSs  a  a   w a Ss    Sw   s             w S    S    C  S   s       C        C        C     S  a    a   S aSSa  S      C |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 684
ace_score 3420
size 684, 1
stairs 415, 0

warrior 296, 0, :east

unit :sludge, 2, 0, :east
unit :sludge, 4, 0, :east
unit :archer, 11, 0, :east
unit :thick_sludge, 12, 0, :east
unit :sludge, 16, 0, :east
unit :archer, 17, 0, :east
unit :archer, 18, 0, :east
unit :archer, 20, 0, :east
unit :captive, 32, 0, :east
unit :archer, 43, 0, :east
unit :thick_sludge, 45, 0, :east
unit :archer, 50, 0, :east
unit :sludge, 58, 0, :east
unit :archer, 61, 0, :east
unit :thick_sludge, 69, 0, :east
unit :thick_sludge, 80, 0, :east
unit :sludge, 82, 0, :east
unit :wizard, 86, 0, :east
unit :sludge, 97, 0, :east
unit :sludge, 98, 0, :east
unit :archer, 101, 0, :east
unit :archer, 107, 0, :east
unit :sludge, 108, 0, :east
unit :thick_sludge, 111, 0, :east
unit :archer, 112, 0, :east
unit :wizard, 116, 0, :east
unit :wizard, 119, 0, :east
unit :thick_sludge, 127, 0, :east
unit :sludge, 128, 0, :east
unit :archer, 129, 0, :east
unit :captive, 131, 0, :east
unit :thick_sludge, 141, 0, :east
unit :sludge, 145, 0, :east
unit :thick_sludge, 150, 0, :east
unit :archer, 151, 0, :east
unit :wizard, 153, 0, :east
unit :sludge, 156, 0, :east
unit :captive, 158, 0, :east
unit :captive, 161, 0, :east
unit :captive, 162, 0, :east
unit :sludge, 166, 0, :east
unit :thick_sludge, 168, 0, :east
unit :thick_sludge, 175, 0, :east
unit :sludge, 179, 0, :east
unit :archer, 183, 0, :east
unit :wizard, 185, 0, :east
unit :thick_sludge, 195, 0, :east
unit :sludge, 198, 0, :east
unit :sludge, 200, 0, :east
unit :archer, 205, 0, :east
unit :archer, 206, 0, :east
unit :thick_sludge, 216, 0, :east
unit :sludge, 218, 0, :east
unit :sludge, 221, 0, :east
unit :captive, 222, 0, :east
unit :archer, 223, 0, :east
unit :archer, 226, 0, :east
unit :archer, 229, 0, :east
unit :sludge, 231, 0, :east
unit :thick_sludge, 235, 0, :east
unit :sludge, 239, 0, :east
unit :archer, 246, 0, :east
unit :captive, 250, 0, :east
unit :archer, 258, 0, :east
unit :captive, 264, 0, :east
unit :thick_sludge, 267, 0, :east
unit :wizard, 270, 0, :east
unit :captive, 275, 0, :east
unit :thick_sludge, 276, 0, :east
unit :thick_sludge, 278, 0, :east
unit :sludge, 281, 0, :east
unit :thick_sludge, 282, 0, :east
unit :sludge, 287, 0, :east
unit :thick_sludge, 299, 0, :west
unit :captive, 303, 0, :west
unit :sludge, 305, 0, :west
unit :archer, 306, 0, :west
unit :wizard, 308, 0, :west
unit :captive, 310, 0, :west
unit :thick_sludge, 313, 0, :west
unit :thick_sludge, 319, 0, :west
unit :captive, 328, 0, :west
unit :archer, 331, 0, :west
unit :thick_sludge, 341, 0, :west
unit :captive, 342, 0, :west
unit :archer, 343, 0, :west
unit :archer, 344, 0, :west
unit :captive, 346, 0, :west
unit :sludge, 347, 0, :west
unit :captive, 349, 0, :west
unit :thick_sludge, 350, 0, :west
unit :archer, 357, 0, :west
unit :captive, 358, 0, :west
unit :captive, 361, 0, :west
unit :thick_sludge, 362, 0, :west
unit :sludge, 365, 0, :west
unit :thick_sludge, 366, 0, :west
unit :thick_sludge, 367, 0, :west
unit :thick_sludge, 375, 0, :west
unit :sludge, 377, 0, :west
unit :captive, 379, 0, :west
unit :archer, 380, 0, :west
unit :thick_sludge, 385, 0, :west
unit :archer, 396, 0, :west
unit :thick_sludge, 403, 0, :west
unit :archer, 406, 0, :west
unit :sludge, 411, 0, :west
unit :thick_sludge, 416, 0, :west
unit :wizard, 422, 0, :west
unit :archer, 425, 0, :west
unit :wizard, 426, 0, :west
unit :thick_sludge, 429, 0, :west
unit :sludge, 431, 0, :west
unit :thick_sludge, 437, 0, :west
unit :archer, 445, 0, :west
unit :thick_sludge, 452, 0, :west
unit :sludge, 454, 0, :west
unit :captive, 457, 0, :west
unit :thick_sludge, 460, 0, :west
unit :archer, 463, 0, :west
unit :archer, 469, 0, :west
unit :wizard, 477, 0, :west
unit :thick_sludge, 482, 0, :west
unit :archer, 484, 0, :west
unit :wizard, 489, 0, :west
unit :captive, 490, 0, :west
unit :archer, 500, 0, :west
unit :captive, 501, 0, :west
unit :thick_sludge, 505, 0, :west
unit :archer, 513, 0, :west
unit :wizard, 522, 0, :west
unit :thick_sludge, 527, 0, :west
unit :captive, 529, 0, :west
unit :wizard, 531, 0, :west
unit :captive, 537, 0, :west
unit :archer, 550, 0, :west
unit :wizard, 557, 0, :west
unit :thick_sludge, 561, 0, :west
unit :archer, 563, 0, :west
unit :thick_sludge, 564, 0, :west
unit :sludge, 565, 0, :west
unit :archer, 568, 0, :west
unit :archer, 571, 0, :west
unit :wizard, 575, 0, :west
unit :archer, 577, 0, :west
unit :thick_sludge, 579, 0, :west
unit :sludge, 580, 0, :west
unit :thick_sludge, 585, 0, :west
unit :wizard, 586, 0, :west
unit :sludge, 590, 0, :west
unit :wizard, 604, 0, :west
unit :thick_sludge, 606, 0, :west
unit :thick_sludge, 611, 0, :west
unit :captive, 616, 0, :west
unit :thick_sludge, 619, 0, :west
unit :sludge, 623, 0, :west
unit :captive, 631, 0, :west
unit :captive, 640, 0, :west
unit :captive, 649, 0, :west
unit :thick_sludge, 655, 0, :west
unit :archer, 658, 0, :west
unit :archer, 663, 0, :west
unit :thick_sludge, 667, 0, :west
unit :archer, 669, 0, :west
unit :thick_sludge, 670, 0, :west
unit :thick_sludge, 671, 0, :west
unit :archer, 672, 0, :west
unit :thick_sludge, 675, 0, :west
unit :captive, 682, 0, :west
