#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |     s       a   a   s   s    S    >      S w      s  C  sS C C      a     C w  w S     CS   Ss S  w S  C  w  s C         s    C a aC w a     S  a  S     C   s w    s Cw  s S C         a   a    w     S SaC     a a s C  C a C    s C   ss    a  s CS       S   w  C    w C    C   C sa s     a   S         w  as  @    a      S     aC w as     s    a   S  Sa   S      S C s   sC  s         C          S   w  S  s   C   S     S wS Cw  C       S       C a  ss        w  w   s w S       C s   CC    SC    a              C wa  C  Ca S      S      S S   s   Ca                    a s                 C    s s            a C       w          w aC    s  sa C       S     wS S       w     s C  a              S      a   a  wS|
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 712
ace_score 3560
size 712, 1
stairs 35, 0

warrior 309, 0, :east

unit :sludge, 5, 0, :east
unit :archer, 13, 0, :east
unit :archer, 17, 0, :east
unit :sludge, 21, 0, :east
unit :sludge, 25, 0, :east
unit :thick_sludge, 30, 0, :east
unit :thick_sludge, 42, 0, :east
unit :wizard, 44, 0, :east
unit :sludge, 51, 0, :east
unit :captive, 54, 0, :east
unit :sludge, 57, 0, :east
unit :thick_sludge, 58, 0, :east
unit :captive, 60, 0, :east
unit :captive, 62, 0, :east
unit :archer, 69, 0, :east
unit :captive, 75, 0, :east
unit :wizard, 77, 0, :east
unit :wizard, 80, 0, :east
unit :thick_sludge, 82, 0, :east
unit :captive, 88, 0, :east
unit :thick_sludge, 89, 0, :east
unit :thick_sludge, 93, 0, :east
unit :sludge, 94, 0, :east
unit :thick_sludge, 96, 0, :east
unit :wizard, 99, 0, :east
unit :thick_sludge, 101, 0, :east
unit :captive, 104, 0, :east
unit :wizard, 107, 0, :east
unit :sludge, 110, 0, :east
unit :captive, 112, 0, :east
unit :sludge, 122, 0, :east
unit :captive, 127, 0, :east
unit :archer, 129, 0, :east
unit :archer, 131, 0, :east
unit :captive, 132, 0, :east
unit :wizard, 134, 0, :east
unit :archer, 136, 0, :east
unit :thick_sludge, 142, 0, :east
unit :archer, 145, 0, :east
unit :thick_sludge, 148, 0, :east
unit :captive, 154, 0, :east
unit :sludge, 158, 0, :east
unit :wizard, 160, 0, :east
unit :sludge, 165, 0, :east
unit :captive, 167, 0, :east
unit :wizard, 168, 0, :east
unit :sludge, 171, 0, :east
unit :thick_sludge, 173, 0, :east
unit :captive, 175, 0, :east
unit :archer, 185, 0, :east
unit :archer, 189, 0, :east
unit :wizard, 194, 0, :east
unit :thick_sludge, 200, 0, :east
unit :thick_sludge, 202, 0, :east
unit :archer, 203, 0, :east
unit :captive, 204, 0, :east
unit :archer, 210, 0, :east
unit :archer, 212, 0, :east
unit :sludge, 214, 0, :east
unit :captive, 216, 0, :east
unit :captive, 219, 0, :east
unit :archer, 221, 0, :east
unit :captive, 223, 0, :east
unit :sludge, 228, 0, :east
unit :captive, 230, 0, :east
unit :sludge, 234, 0, :east
unit :sludge, 235, 0, :east
unit :archer, 240, 0, :east
unit :sludge, 243, 0, :east
unit :captive, 245, 0, :east
unit :thick_sludge, 246, 0, :east
unit :thick_sludge, 254, 0, :east
unit :wizard, 258, 0, :east
unit :captive, 261, 0, :east
unit :wizard, 266, 0, :east
unit :captive, 268, 0, :east
unit :captive, 273, 0, :east
unit :captive, 277, 0, :east
unit :sludge, 279, 0, :east
unit :archer, 280, 0, :east
unit :sludge, 282, 0, :east
unit :archer, 288, 0, :east
unit :thick_sludge, 292, 0, :east
unit :wizard, 302, 0, :east
unit :archer, 305, 0, :east
unit :sludge, 306, 0, :east
unit :archer, 314, 0, :west
unit :thick_sludge, 321, 0, :west
unit :archer, 327, 0, :west
unit :captive, 328, 0, :west
unit :wizard, 330, 0, :west
unit :archer, 332, 0, :west
unit :sludge, 333, 0, :west
unit :sludge, 339, 0, :west
unit :archer, 344, 0, :west
unit :thick_sludge, 348, 0, :west
unit :thick_sludge, 351, 0, :west
unit :archer, 352, 0, :west
unit :thick_sludge, 356, 0, :west
unit :thick_sludge, 363, 0, :west
unit :captive, 365, 0, :west
unit :sludge, 367, 0, :west
unit :sludge, 371, 0, :west
unit :captive, 372, 0, :west
unit :sludge, 375, 0, :west
unit :captive, 385, 0, :west
unit :thick_sludge, 396, 0, :west
unit :wizard, 400, 0, :west
unit :thick_sludge, 403, 0, :west
unit :sludge, 406, 0, :west
unit :captive, 410, 0, :west
unit :thick_sludge, 414, 0, :west
unit :thick_sludge, 420, 0, :west
unit :wizard, 422, 0, :west
unit :thick_sludge, 423, 0, :west
unit :captive, 425, 0, :west
unit :wizard, 426, 0, :west
unit :captive, 429, 0, :west
unit :thick_sludge, 437, 0, :west
unit :captive, 445, 0, :west
unit :archer, 447, 0, :west
unit :sludge, 450, 0, :west
unit :sludge, 451, 0, :west
unit :wizard, 460, 0, :west
unit :wizard, 463, 0, :west
unit :sludge, 467, 0, :west
unit :wizard, 469, 0, :west
unit :thick_sludge, 471, 0, :west
unit :captive, 479, 0, :west
unit :sludge, 481, 0, :west
unit :captive, 485, 0, :west
unit :captive, 486, 0, :west
unit :thick_sludge, 491, 0, :west
unit :captive, 492, 0, :west
unit :archer, 497, 0, :west
unit :captive, 512, 0, :west
unit :wizard, 514, 0, :west
unit :archer, 515, 0, :west
unit :captive, 518, 0, :west
unit :captive, 521, 0, :west
unit :archer, 522, 0, :west
unit :thick_sludge, 524, 0, :west
unit :thick_sludge, 531, 0, :west
unit :thick_sludge, 538, 0, :west
unit :thick_sludge, 540, 0, :west
unit :sludge, 544, 0, :west
unit :captive, 548, 0, :west
unit :archer, 549, 0, :west
unit :archer, 570, 0, :west
unit :sludge, 572, 0, :west
unit :captive, 590, 0, :west
unit :sludge, 595, 0, :west
unit :sludge, 597, 0, :west
unit :archer, 610, 0, :west
unit :captive, 612, 0, :west
unit :wizard, 620, 0, :west
unit :wizard, 631, 0, :west
unit :archer, 633, 0, :west
unit :captive, 634, 0, :west
unit :sludge, 639, 0, :west
unit :sludge, 642, 0, :west
unit :archer, 643, 0, :west
unit :captive, 645, 0, :west
unit :thick_sludge, 653, 0, :west
unit :wizard, 659, 0, :west
unit :thick_sludge, 660, 0, :west
unit :thick_sludge, 662, 0, :west
unit :wizard, 670, 0, :west
unit :sludge, 676, 0, :west
unit :captive, 678, 0, :west
unit :archer, 681, 0, :west
unit :thick_sludge, 696, 0, :west
unit :archer, 703, 0, :west
unit :archer, 707, 0, :west
unit :wizard, 710, 0, :west
unit :thick_sludge, 711, 0, :west
