#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |             C   s  w     a      w   S   w w   S    w   CSs  C>   a  S            w  wSsSa           C  C           C     CS C  a  a   a      a   Ca   CCa            S     C  a asC C w     aS       C      wS   s C       s    s               C s C  CCS  s       C    S a        w    w  a w    SC     s CS    a C      a s      C     @   aC          a w     aa   s  s     w w     S S               wsw  a     as  as     C   a   S  a    sa      w  aC C      as  SC a  w     SC      w asCw C      w     S ssC    a        a     C   wC  C   s   s  S  s  C          w     wC                        a           S w Saa  C     as w w C asC  |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 631
ace_score 3155
size 631, 1
stairs 62, 0

warrior 331, 0, :east

unit :captive, 13, 0, :east
unit :sludge, 17, 0, :east
unit :wizard, 20, 0, :east
unit :archer, 26, 0, :east
unit :wizard, 33, 0, :east
unit :thick_sludge, 37, 0, :east
unit :wizard, 41, 0, :east
unit :wizard, 43, 0, :east
unit :thick_sludge, 47, 0, :east
unit :wizard, 52, 0, :east
unit :captive, 56, 0, :east
unit :thick_sludge, 57, 0, :east
unit :sludge, 58, 0, :east
unit :captive, 61, 0, :east
unit :archer, 66, 0, :east
unit :thick_sludge, 69, 0, :east
unit :wizard, 82, 0, :east
unit :wizard, 85, 0, :east
unit :thick_sludge, 86, 0, :east
unit :sludge, 87, 0, :east
unit :thick_sludge, 88, 0, :east
unit :archer, 89, 0, :east
unit :captive, 101, 0, :east
unit :captive, 104, 0, :east
unit :captive, 116, 0, :east
unit :captive, 122, 0, :east
unit :thick_sludge, 123, 0, :east
unit :captive, 125, 0, :east
unit :archer, 128, 0, :east
unit :archer, 131, 0, :east
unit :archer, 135, 0, :east
unit :archer, 142, 0, :east
unit :captive, 146, 0, :east
unit :archer, 147, 0, :east
unit :captive, 151, 0, :east
unit :captive, 152, 0, :east
unit :archer, 153, 0, :east
unit :thick_sludge, 166, 0, :east
unit :captive, 172, 0, :east
unit :archer, 175, 0, :east
unit :archer, 177, 0, :east
unit :sludge, 178, 0, :east
unit :captive, 179, 0, :east
unit :captive, 181, 0, :east
unit :wizard, 183, 0, :east
unit :archer, 189, 0, :east
unit :thick_sludge, 190, 0, :east
unit :captive, 198, 0, :east
unit :wizard, 205, 0, :east
unit :thick_sludge, 206, 0, :east
unit :sludge, 210, 0, :east
unit :captive, 212, 0, :east
unit :sludge, 220, 0, :east
unit :sludge, 225, 0, :east
unit :captive, 241, 0, :east
unit :sludge, 243, 0, :east
unit :captive, 245, 0, :east
unit :captive, 248, 0, :east
unit :captive, 249, 0, :east
unit :thick_sludge, 250, 0, :east
unit :sludge, 253, 0, :east
unit :captive, 261, 0, :east
unit :thick_sludge, 266, 0, :east
unit :archer, 268, 0, :east
unit :wizard, 277, 0, :east
unit :wizard, 282, 0, :east
unit :archer, 285, 0, :east
unit :wizard, 287, 0, :east
unit :thick_sludge, 292, 0, :east
unit :captive, 293, 0, :east
unit :sludge, 299, 0, :east
unit :captive, 301, 0, :east
unit :thick_sludge, 302, 0, :east
unit :archer, 307, 0, :east
unit :captive, 309, 0, :east
unit :archer, 316, 0, :east
unit :sludge, 318, 0, :east
unit :captive, 325, 0, :east
unit :archer, 335, 0, :west
unit :captive, 336, 0, :west
unit :archer, 347, 0, :west
unit :wizard, 349, 0, :west
unit :archer, 355, 0, :west
unit :archer, 356, 0, :west
unit :sludge, 360, 0, :west
unit :sludge, 363, 0, :west
unit :wizard, 369, 0, :west
unit :wizard, 371, 0, :west
unit :thick_sludge, 377, 0, :west
unit :thick_sludge, 379, 0, :west
unit :wizard, 395, 0, :west
unit :sludge, 396, 0, :west
unit :wizard, 397, 0, :west
unit :archer, 400, 0, :west
unit :archer, 406, 0, :west
unit :sludge, 407, 0, :west
unit :archer, 410, 0, :west
unit :sludge, 411, 0, :west
unit :captive, 417, 0, :west
unit :archer, 421, 0, :west
unit :thick_sludge, 425, 0, :west
unit :archer, 428, 0, :west
unit :sludge, 433, 0, :west
unit :archer, 434, 0, :west
unit :wizard, 441, 0, :west
unit :archer, 444, 0, :west
unit :captive, 445, 0, :west
unit :captive, 447, 0, :west
unit :archer, 454, 0, :west
unit :sludge, 455, 0, :west
unit :thick_sludge, 458, 0, :west
unit :captive, 459, 0, :west
unit :archer, 461, 0, :west
unit :wizard, 464, 0, :west
unit :thick_sludge, 470, 0, :west
unit :captive, 471, 0, :west
unit :wizard, 478, 0, :west
unit :archer, 480, 0, :west
unit :sludge, 481, 0, :west
unit :captive, 482, 0, :west
unit :wizard, 483, 0, :west
unit :captive, 485, 0, :west
unit :wizard, 492, 0, :west
unit :thick_sludge, 498, 0, :west
unit :sludge, 500, 0, :west
unit :sludge, 501, 0, :west
unit :captive, 502, 0, :west
unit :archer, 507, 0, :west
unit :archer, 516, 0, :west
unit :captive, 522, 0, :west
unit :wizard, 526, 0, :west
unit :captive, 527, 0, :west
unit :captive, 530, 0, :west
unit :sludge, 534, 0, :west
unit :sludge, 538, 0, :west
unit :thick_sludge, 541, 0, :west
unit :sludge, 544, 0, :west
unit :captive, 547, 0, :west
unit :wizard, 558, 0, :west
unit :wizard, 564, 0, :west
unit :captive, 565, 0, :west
unit :archer, 590, 0, :west
unit :thick_sludge, 602, 0, :west
unit :wizard, 604, 0, :west
unit :thick_sludge, 606, 0, :west
unit :archer, 607, 0, :west
unit :archer, 608, 0, :west
unit :captive, 611, 0, :west
unit :archer, 617, 0, :west
unit :sludge, 618, 0, :west
unit :wizard, 620, 0, :west
unit :wizard, 622, 0, :west
unit :captive, 624, 0, :west
unit :archer, 626, 0, :west
unit :sludge, 627, 0, :west
unit :captive, 628, 0, :west
