#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |            S w           C  CC          a   w       @     C CsCC   w  a      a    S  a     w    S      sCa a s   s     a            SS            Sa a    w C   SS  w C         a   s  s   >          w   sCaS  S    w     w  s  S      w      a     a   s   w               s   a s       a    s      a w S         a        a  SS  CC    Sa  s a              C   w w   SS  S     w   C aaC  a    Ss C s  w   S     aa  sC   wsa w      s       a    SC   SC S       C           s a       C    a     w      as   C         CCCS       aC s        Ss    a  w S   sS      s C  aa   S    a             ss   C  CS                 S       S     s S  Sw a   S       w  a w  ss  aS w  wCs     s   SC   s SC         a Cw  S  w       w   S a  w  Cw  a   CS C S          a    a     aa    C      C        Ca a  a w C s    w C  C S s   w w S    a    C   aC|
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 831
ace_score 4155
size 831, 1
stairs 188, 0

warrior 53, 0, :east

unit :thick_sludge, 12, 0, :east
unit :wizard, 14, 0, :east
unit :captive, 26, 0, :east
unit :captive, 29, 0, :east
unit :captive, 30, 0, :east
unit :archer, 41, 0, :east
unit :wizard, 45, 0, :east
unit :captive, 59, 0, :west
unit :captive, 61, 0, :west
unit :sludge, 62, 0, :west
unit :captive, 63, 0, :west
unit :captive, 64, 0, :west
unit :wizard, 68, 0, :west
unit :archer, 71, 0, :west
unit :archer, 78, 0, :west
unit :thick_sludge, 83, 0, :west
unit :archer, 86, 0, :west
unit :wizard, 92, 0, :west
unit :thick_sludge, 97, 0, :west
unit :sludge, 104, 0, :west
unit :captive, 105, 0, :west
unit :archer, 106, 0, :west
unit :archer, 108, 0, :west
unit :sludge, 110, 0, :west
unit :sludge, 114, 0, :west
unit :archer, 120, 0, :west
unit :thick_sludge, 133, 0, :west
unit :thick_sludge, 134, 0, :west
unit :thick_sludge, 147, 0, :west
unit :archer, 148, 0, :west
unit :archer, 150, 0, :west
unit :wizard, 155, 0, :west
unit :captive, 157, 0, :west
unit :thick_sludge, 161, 0, :west
unit :thick_sludge, 162, 0, :west
unit :wizard, 165, 0, :west
unit :captive, 167, 0, :west
unit :archer, 177, 0, :west
unit :sludge, 181, 0, :west
unit :sludge, 184, 0, :west
unit :wizard, 199, 0, :west
unit :sludge, 203, 0, :west
unit :captive, 204, 0, :west
unit :archer, 205, 0, :west
unit :thick_sludge, 206, 0, :west
unit :thick_sludge, 209, 0, :west
unit :wizard, 214, 0, :west
unit :wizard, 220, 0, :west
unit :sludge, 223, 0, :west
unit :thick_sludge, 226, 0, :west
unit :wizard, 233, 0, :west
unit :archer, 240, 0, :west
unit :archer, 246, 0, :west
unit :sludge, 250, 0, :west
unit :wizard, 254, 0, :west
unit :sludge, 270, 0, :west
unit :archer, 274, 0, :west
unit :sludge, 276, 0, :west
unit :archer, 284, 0, :west
unit :sludge, 289, 0, :west
unit :archer, 296, 0, :west
unit :wizard, 298, 0, :west
unit :thick_sludge, 300, 0, :west
unit :archer, 310, 0, :west
unit :archer, 319, 0, :west
unit :thick_sludge, 322, 0, :west
unit :thick_sludge, 323, 0, :west
unit :captive, 326, 0, :west
unit :captive, 327, 0, :west
unit :thick_sludge, 332, 0, :west
unit :archer, 333, 0, :west
unit :sludge, 336, 0, :west
unit :archer, 338, 0, :west
unit :captive, 353, 0, :west
unit :wizard, 357, 0, :west
unit :wizard, 359, 0, :west
unit :thick_sludge, 363, 0, :west
unit :thick_sludge, 364, 0, :west
unit :thick_sludge, 367, 0, :west
unit :wizard, 373, 0, :west
unit :captive, 377, 0, :west
unit :archer, 379, 0, :west
unit :archer, 380, 0, :west
unit :captive, 381, 0, :west
unit :archer, 384, 0, :west
unit :thick_sludge, 389, 0, :west
unit :sludge, 390, 0, :west
unit :captive, 392, 0, :west
unit :sludge, 394, 0, :west
unit :wizard, 397, 0, :west
unit :thick_sludge, 401, 0, :west
unit :archer, 407, 0, :west
unit :archer, 408, 0, :west
unit :sludge, 411, 0, :west
unit :captive, 412, 0, :west
unit :wizard, 416, 0, :west
unit :sludge, 417, 0, :west
unit :archer, 418, 0, :west
unit :wizard, 420, 0, :west
unit :sludge, 427, 0, :west
unit :archer, 435, 0, :west
unit :thick_sludge, 440, 0, :west
unit :captive, 441, 0, :west
unit :thick_sludge, 445, 0, :west
unit :captive, 446, 0, :west
unit :thick_sludge, 448, 0, :west
unit :captive, 456, 0, :west
unit :sludge, 468, 0, :west
unit :archer, 470, 0, :west
unit :captive, 478, 0, :west
unit :archer, 483, 0, :west
unit :wizard, 489, 0, :west
unit :archer, 496, 0, :west
unit :sludge, 497, 0, :west
unit :captive, 501, 0, :west
unit :captive, 511, 0, :west
unit :captive, 512, 0, :west
unit :captive, 513, 0, :west
unit :thick_sludge, 514, 0, :west
unit :archer, 522, 0, :west
unit :captive, 523, 0, :west
unit :sludge, 525, 0, :west
unit :thick_sludge, 534, 0, :west
unit :sludge, 535, 0, :west
unit :archer, 540, 0, :west
unit :wizard, 543, 0, :west
unit :thick_sludge, 545, 0, :west
unit :sludge, 549, 0, :west
unit :thick_sludge, 550, 0, :west
unit :sludge, 557, 0, :west
unit :captive, 559, 0, :west
unit :archer, 562, 0, :west
unit :archer, 563, 0, :west
unit :thick_sludge, 567, 0, :west
unit :archer, 572, 0, :west
unit :sludge, 586, 0, :west
unit :sludge, 587, 0, :west
unit :captive, 591, 0, :west
unit :captive, 594, 0, :west
unit :thick_sludge, 595, 0, :west
unit :thick_sludge, 613, 0, :west
unit :thick_sludge, 621, 0, :west
unit :sludge, 627, 0, :west
unit :thick_sludge, 629, 0, :west
unit :thick_sludge, 632, 0, :west
unit :wizard, 633, 0, :west
unit :archer, 635, 0, :west
unit :thick_sludge, 639, 0, :west
unit :wizard, 647, 0, :west
unit :archer, 650, 0, :west
unit :wizard, 652, 0, :west
unit :sludge, 655, 0, :west
unit :sludge, 656, 0, :west
unit :archer, 659, 0, :west
unit :thick_sludge, 660, 0, :west
unit :wizard, 662, 0, :west
unit :wizard, 665, 0, :west
unit :captive, 666, 0, :west
unit :sludge, 667, 0, :west
unit :sludge, 673, 0, :west
unit :thick_sludge, 677, 0, :west
unit :captive, 678, 0, :west
unit :sludge, 682, 0, :west
unit :thick_sludge, 684, 0, :west
unit :captive, 685, 0, :west
unit :archer, 695, 0, :west
unit :captive, 697, 0, :west
unit :wizard, 698, 0, :west
unit :thick_sludge, 701, 0, :west
unit :wizard, 704, 0, :west
unit :wizard, 712, 0, :west
unit :thick_sludge, 716, 0, :west
unit :archer, 718, 0, :west
unit :wizard, 721, 0, :west
unit :captive, 724, 0, :west
unit :wizard, 725, 0, :west
unit :archer, 728, 0, :west
unit :captive, 732, 0, :west
unit :thick_sludge, 733, 0, :west
unit :captive, 735, 0, :west
unit :thick_sludge, 737, 0, :west
unit :archer, 748, 0, :west
unit :archer, 753, 0, :west
unit :archer, 759, 0, :west
unit :archer, 760, 0, :west
unit :captive, 765, 0, :west
unit :captive, 772, 0, :west
unit :captive, 781, 0, :west
unit :archer, 782, 0, :west
unit :archer, 784, 0, :west
unit :archer, 787, 0, :west
unit :wizard, 789, 0, :west
unit :captive, 791, 0, :west
unit :sludge, 793, 0, :west
unit :wizard, 798, 0, :west
unit :captive, 800, 0, :west
unit :captive, 803, 0, :west
unit :thick_sludge, 805, 0, :west
unit :sludge, 807, 0, :west
unit :wizard, 811, 0, :west
unit :wizard, 813, 0, :west
unit :thick_sludge, 815, 0, :west
unit :archer, 820, 0, :west
unit :captive, 825, 0, :west
unit :archer, 829, 0, :west
unit :captive, 830, 0, :west
