#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C       a     SC  SaSa w         a   S  wS    s w saa s      C  sw         Cw    S s        a          w   w s      w          a       w w           w                  C ss   C         w  a     S   Ssa    s    C  aCC  S     w         S   C Ss         w S         s  a      C>S       a C   a a        @  C  a   C  w C a        S      sas Ca  a  S     C w   C   w    as    aS     C C    w      a   C        a sa     s  C   C  S S    SS     s   s a    w            a  w   a  as      S C Csa      aa    w        w aa   s                 C SC C   SSs       s       w  a         S            s S w C S        C   as    S      aSs    C   wSa s w w C  C C     SC sS  s a    S     wS     s  wsw sS       C C              S      sw w aw  s   a Ca   |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 741
ace_score 3705
size 741, 1
stairs 276, 0

warrior 302, 0, :east

unit :captive, 2, 0, :east
unit :archer, 10, 0, :east
unit :thick_sludge, 16, 0, :east
unit :captive, 17, 0, :east
unit :thick_sludge, 20, 0, :east
unit :archer, 21, 0, :east
unit :thick_sludge, 22, 0, :east
unit :archer, 23, 0, :east
unit :wizard, 25, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 39, 0, :east
unit :wizard, 42, 0, :east
unit :thick_sludge, 43, 0, :east
unit :sludge, 48, 0, :east
unit :wizard, 50, 0, :east
unit :sludge, 52, 0, :east
unit :archer, 53, 0, :east
unit :archer, 54, 0, :east
unit :sludge, 56, 0, :east
unit :captive, 63, 0, :east
unit :sludge, 66, 0, :east
unit :wizard, 67, 0, :east
unit :captive, 77, 0, :east
unit :wizard, 78, 0, :east
unit :thick_sludge, 83, 0, :east
unit :sludge, 85, 0, :east
unit :archer, 94, 0, :east
unit :wizard, 105, 0, :east
unit :wizard, 109, 0, :east
unit :sludge, 111, 0, :east
unit :wizard, 118, 0, :east
unit :archer, 129, 0, :east
unit :wizard, 137, 0, :east
unit :wizard, 139, 0, :east
unit :wizard, 151, 0, :east
unit :captive, 170, 0, :east
unit :sludge, 172, 0, :east
unit :sludge, 173, 0, :east
unit :captive, 177, 0, :east
unit :wizard, 187, 0, :east
unit :archer, 190, 0, :east
unit :thick_sludge, 196, 0, :east
unit :thick_sludge, 200, 0, :east
unit :sludge, 201, 0, :east
unit :archer, 202, 0, :east
unit :sludge, 207, 0, :east
unit :captive, 212, 0, :east
unit :archer, 215, 0, :east
unit :captive, 216, 0, :east
unit :captive, 217, 0, :east
unit :thick_sludge, 220, 0, :east
unit :wizard, 226, 0, :east
unit :thick_sludge, 236, 0, :east
unit :captive, 240, 0, :east
unit :thick_sludge, 242, 0, :east
unit :sludge, 243, 0, :east
unit :wizard, 253, 0, :east
unit :thick_sludge, 255, 0, :east
unit :sludge, 265, 0, :east
unit :archer, 268, 0, :east
unit :captive, 275, 0, :east
unit :thick_sludge, 277, 0, :east
unit :archer, 285, 0, :east
unit :captive, 287, 0, :east
unit :archer, 291, 0, :east
unit :archer, 293, 0, :east
unit :captive, 305, 0, :west
unit :archer, 308, 0, :west
unit :captive, 312, 0, :west
unit :wizard, 315, 0, :west
unit :captive, 317, 0, :west
unit :archer, 319, 0, :west
unit :thick_sludge, 328, 0, :west
unit :sludge, 335, 0, :west
unit :archer, 336, 0, :west
unit :sludge, 337, 0, :west
unit :captive, 339, 0, :west
unit :archer, 340, 0, :west
unit :archer, 343, 0, :west
unit :thick_sludge, 346, 0, :west
unit :captive, 352, 0, :west
unit :wizard, 354, 0, :west
unit :captive, 358, 0, :west
unit :wizard, 362, 0, :west
unit :archer, 367, 0, :west
unit :sludge, 368, 0, :west
unit :archer, 373, 0, :west
unit :thick_sludge, 374, 0, :west
unit :captive, 380, 0, :west
unit :captive, 382, 0, :west
unit :wizard, 387, 0, :west
unit :archer, 394, 0, :west
unit :captive, 398, 0, :west
unit :archer, 407, 0, :west
unit :sludge, 409, 0, :west
unit :archer, 410, 0, :west
unit :sludge, 416, 0, :west
unit :captive, 419, 0, :west
unit :captive, 423, 0, :west
unit :thick_sludge, 426, 0, :west
unit :thick_sludge, 428, 0, :west
unit :thick_sludge, 433, 0, :west
unit :thick_sludge, 434, 0, :west
unit :sludge, 440, 0, :west
unit :sludge, 444, 0, :west
unit :archer, 446, 0, :west
unit :wizard, 451, 0, :west
unit :archer, 464, 0, :west
unit :wizard, 467, 0, :west
unit :archer, 471, 0, :west
unit :archer, 474, 0, :west
unit :sludge, 475, 0, :west
unit :thick_sludge, 482, 0, :west
unit :captive, 484, 0, :west
unit :captive, 486, 0, :west
unit :sludge, 487, 0, :west
unit :archer, 488, 0, :west
unit :archer, 495, 0, :west
unit :archer, 496, 0, :west
unit :wizard, 501, 0, :west
unit :wizard, 510, 0, :west
unit :archer, 512, 0, :west
unit :archer, 513, 0, :west
unit :sludge, 517, 0, :west
unit :captive, 535, 0, :west
unit :thick_sludge, 537, 0, :west
unit :captive, 538, 0, :west
unit :captive, 540, 0, :west
unit :thick_sludge, 544, 0, :west
unit :thick_sludge, 545, 0, :west
unit :sludge, 546, 0, :west
unit :sludge, 554, 0, :west
unit :wizard, 562, 0, :west
unit :archer, 565, 0, :west
unit :thick_sludge, 575, 0, :west
unit :sludge, 588, 0, :west
unit :thick_sludge, 590, 0, :west
unit :wizard, 592, 0, :west
unit :captive, 594, 0, :west
unit :thick_sludge, 596, 0, :west
unit :captive, 605, 0, :west
unit :archer, 609, 0, :west
unit :sludge, 610, 0, :west
unit :thick_sludge, 615, 0, :west
unit :archer, 622, 0, :west
unit :thick_sludge, 623, 0, :west
unit :sludge, 624, 0, :west
unit :captive, 629, 0, :west
unit :wizard, 633, 0, :west
unit :thick_sludge, 634, 0, :west
unit :archer, 635, 0, :west
unit :sludge, 637, 0, :west
unit :wizard, 639, 0, :west
unit :wizard, 641, 0, :west
unit :captive, 643, 0, :west
unit :captive, 646, 0, :west
unit :captive, 648, 0, :west
unit :thick_sludge, 654, 0, :west
unit :captive, 655, 0, :west
unit :sludge, 657, 0, :west
unit :thick_sludge, 658, 0, :west
unit :sludge, 661, 0, :west
unit :archer, 663, 0, :west
unit :thick_sludge, 668, 0, :west
unit :wizard, 674, 0, :west
unit :thick_sludge, 675, 0, :west
unit :sludge, 681, 0, :west
unit :wizard, 684, 0, :west
unit :sludge, 685, 0, :west
unit :wizard, 686, 0, :west
unit :sludge, 688, 0, :west
unit :thick_sludge, 689, 0, :west
unit :captive, 697, 0, :west
unit :captive, 699, 0, :west
unit :thick_sludge, 714, 0, :west
unit :sludge, 721, 0, :west
unit :wizard, 722, 0, :west
unit :wizard, 724, 0, :west
unit :archer, 726, 0, :west
unit :wizard, 727, 0, :west
unit :sludge, 730, 0, :west
unit :archer, 734, 0, :west
unit :captive, 736, 0, :west
unit :archer, 737, 0, :west
