#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s   s  w CC  C    wC   S  >   w       C C       S  CSS     sC  S       w      s     s a s wS            w   S    w    a ss    a   a    w  S     w      w           w        @   C w   s         w     S a   S s      s  SS      Cs S   w  a S             S  S a  a as a a a s    as      w     S     CS        S  s         S     a     SS    a  w        as    Sws  w   as   SC  C   a           w  S         w  wS      CCC      a   sw S  S     aw wSs             a       C C w   s   S     w  w aCC a    aC   w        a     Ca  w   s     C       a  a      s   s S  S  s        S S         C     s    S  w    S    s s Ss   wa       aSs  s  C  w    C  w  s  s  w   S aS w  sw    a C    SS          s              C   S S    s    Caa   CSC   s        w       S  w   C   w   aS   S    C S    Ca w             S     S   C C          s     ws         Ca   a S w     w   a  sS    sCa |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 870
ace_score 4350
size 870, 1
stairs 28, 0

warrior 174, 0, :east

unit :sludge, 2, 0, :east
unit :sludge, 6, 0, :east
unit :wizard, 9, 0, :east
unit :captive, 11, 0, :east
unit :captive, 12, 0, :east
unit :captive, 15, 0, :east
unit :wizard, 20, 0, :east
unit :captive, 21, 0, :east
unit :thick_sludge, 25, 0, :east
unit :wizard, 32, 0, :east
unit :captive, 40, 0, :east
unit :captive, 42, 0, :east
unit :thick_sludge, 50, 0, :east
unit :captive, 53, 0, :east
unit :thick_sludge, 54, 0, :east
unit :thick_sludge, 55, 0, :east
unit :sludge, 61, 0, :east
unit :captive, 62, 0, :east
unit :thick_sludge, 65, 0, :east
unit :wizard, 73, 0, :east
unit :sludge, 80, 0, :east
unit :sludge, 86, 0, :east
unit :archer, 88, 0, :east
unit :sludge, 90, 0, :east
unit :wizard, 92, 0, :east
unit :thick_sludge, 93, 0, :east
unit :wizard, 106, 0, :east
unit :thick_sludge, 110, 0, :east
unit :wizard, 115, 0, :east
unit :archer, 120, 0, :east
unit :sludge, 122, 0, :east
unit :sludge, 123, 0, :east
unit :archer, 128, 0, :east
unit :archer, 132, 0, :east
unit :wizard, 137, 0, :east
unit :thick_sludge, 140, 0, :east
unit :wizard, 146, 0, :east
unit :wizard, 153, 0, :east
unit :wizard, 165, 0, :east
unit :captive, 178, 0, :west
unit :wizard, 180, 0, :west
unit :sludge, 184, 0, :west
unit :wizard, 194, 0, :west
unit :thick_sludge, 200, 0, :west
unit :archer, 202, 0, :west
unit :thick_sludge, 206, 0, :west
unit :sludge, 208, 0, :west
unit :sludge, 215, 0, :west
unit :thick_sludge, 218, 0, :west
unit :thick_sludge, 219, 0, :west
unit :captive, 226, 0, :west
unit :sludge, 227, 0, :west
unit :thick_sludge, 229, 0, :west
unit :wizard, 233, 0, :west
unit :archer, 236, 0, :west
unit :thick_sludge, 238, 0, :west
unit :thick_sludge, 252, 0, :west
unit :thick_sludge, 255, 0, :west
unit :archer, 257, 0, :west
unit :archer, 260, 0, :west
unit :archer, 262, 0, :west
unit :sludge, 263, 0, :west
unit :archer, 265, 0, :west
unit :archer, 267, 0, :west
unit :archer, 269, 0, :west
unit :sludge, 271, 0, :west
unit :archer, 276, 0, :west
unit :sludge, 277, 0, :west
unit :wizard, 284, 0, :west
unit :thick_sludge, 290, 0, :west
unit :captive, 296, 0, :west
unit :thick_sludge, 297, 0, :west
unit :thick_sludge, 306, 0, :west
unit :sludge, 309, 0, :west
unit :thick_sludge, 319, 0, :west
unit :archer, 325, 0, :west
unit :thick_sludge, 331, 0, :west
unit :thick_sludge, 332, 0, :west
unit :archer, 337, 0, :west
unit :wizard, 340, 0, :west
unit :archer, 349, 0, :west
unit :sludge, 350, 0, :west
unit :thick_sludge, 355, 0, :west
unit :wizard, 356, 0, :west
unit :sludge, 357, 0, :west
unit :wizard, 360, 0, :west
unit :archer, 364, 0, :west
unit :sludge, 365, 0, :west
unit :thick_sludge, 369, 0, :west
unit :captive, 370, 0, :west
unit :captive, 373, 0, :west
unit :archer, 377, 0, :west
unit :wizard, 389, 0, :west
unit :thick_sludge, 392, 0, :west
unit :wizard, 402, 0, :west
unit :wizard, 405, 0, :west
unit :thick_sludge, 406, 0, :west
unit :captive, 413, 0, :west
unit :captive, 414, 0, :west
unit :captive, 415, 0, :west
unit :archer, 422, 0, :west
unit :sludge, 426, 0, :west
unit :wizard, 427, 0, :west
unit :thick_sludge, 429, 0, :west
unit :thick_sludge, 432, 0, :west
unit :archer, 438, 0, :west
unit :wizard, 439, 0, :west
unit :wizard, 441, 0, :west
unit :thick_sludge, 442, 0, :west
unit :sludge, 443, 0, :west
unit :archer, 457, 0, :west
unit :captive, 465, 0, :west
unit :captive, 467, 0, :west
unit :wizard, 469, 0, :west
unit :sludge, 473, 0, :west
unit :thick_sludge, 477, 0, :west
unit :wizard, 483, 0, :west
unit :wizard, 486, 0, :west
unit :archer, 488, 0, :west
unit :captive, 489, 0, :west
unit :captive, 490, 0, :west
unit :archer, 492, 0, :west
unit :archer, 497, 0, :west
unit :captive, 498, 0, :west
unit :wizard, 502, 0, :west
unit :archer, 511, 0, :west
unit :captive, 517, 0, :west
unit :archer, 518, 0, :west
unit :wizard, 521, 0, :west
unit :sludge, 525, 0, :west
unit :captive, 531, 0, :west
unit :archer, 539, 0, :west
unit :archer, 542, 0, :west
unit :sludge, 549, 0, :west
unit :sludge, 553, 0, :west
unit :thick_sludge, 555, 0, :west
unit :thick_sludge, 558, 0, :west
unit :sludge, 561, 0, :west
unit :thick_sludge, 570, 0, :west
unit :thick_sludge, 572, 0, :west
unit :captive, 582, 0, :west
unit :sludge, 588, 0, :west
unit :thick_sludge, 593, 0, :west
unit :wizard, 596, 0, :west
unit :thick_sludge, 601, 0, :west
unit :sludge, 606, 0, :west
unit :sludge, 608, 0, :west
unit :thick_sludge, 610, 0, :west
unit :sludge, 611, 0, :west
unit :wizard, 615, 0, :west
unit :archer, 616, 0, :west
unit :archer, 624, 0, :west
unit :thick_sludge, 625, 0, :west
unit :sludge, 626, 0, :west
unit :sludge, 629, 0, :west
unit :captive, 632, 0, :west
unit :wizard, 635, 0, :west
unit :captive, 640, 0, :west
unit :wizard, 643, 0, :west
unit :sludge, 646, 0, :west
unit :sludge, 649, 0, :west
unit :wizard, 652, 0, :west
unit :thick_sludge, 656, 0, :west
unit :archer, 658, 0, :west
unit :thick_sludge, 659, 0, :west
unit :wizard, 661, 0, :west
unit :sludge, 664, 0, :west
unit :wizard, 665, 0, :west
unit :archer, 670, 0, :west
unit :captive, 672, 0, :west
unit :thick_sludge, 677, 0, :west
unit :thick_sludge, 678, 0, :west
unit :sludge, 689, 0, :west
unit :captive, 704, 0, :west
unit :thick_sludge, 708, 0, :west
unit :thick_sludge, 710, 0, :west
unit :sludge, 715, 0, :west
unit :captive, 720, 0, :west
unit :archer, 721, 0, :west
unit :archer, 722, 0, :west
unit :captive, 726, 0, :west
unit :thick_sludge, 727, 0, :west
unit :captive, 728, 0, :west
unit :sludge, 732, 0, :west
unit :wizard, 741, 0, :west
unit :thick_sludge, 749, 0, :west
unit :wizard, 752, 0, :west
unit :captive, 756, 0, :west
unit :wizard, 760, 0, :west
unit :archer, 764, 0, :west
unit :thick_sludge, 765, 0, :west
unit :thick_sludge, 769, 0, :west
unit :captive, 774, 0, :west
unit :thick_sludge, 776, 0, :west
unit :captive, 781, 0, :west
unit :archer, 782, 0, :west
unit :wizard, 784, 0, :west
unit :thick_sludge, 798, 0, :west
unit :thick_sludge, 804, 0, :west
unit :captive, 808, 0, :west
unit :captive, 810, 0, :west
unit :sludge, 821, 0, :west
unit :wizard, 827, 0, :west
unit :sludge, 828, 0, :west
unit :captive, 838, 0, :west
unit :archer, 839, 0, :west
unit :archer, 843, 0, :west
unit :thick_sludge, 845, 0, :west
unit :wizard, 847, 0, :west
unit :wizard, 853, 0, :west
unit :archer, 857, 0, :west
unit :sludge, 860, 0, :west
unit :thick_sludge, 861, 0, :west
unit :sludge, 866, 0, :west
unit :captive, 867, 0, :west
unit :archer, 868, 0, :west
