#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |a     s   S a    w   C   sS     S   a           C w                s      sa        s s      s     asa C C         a    C       SCS   S  Cws C    Sa sS  CC w  a  as    S      Sw SC    s s   S S    a aCS   S S S   a w  s s   w          a  s C  a  wSS a  s sCs  s S      sS C   a     a   aa w      C   C          C Sa  C     s s    SCS            Cw w   w  S  w   SCw  s   a       s     w s       w     S>    C  s s      aw  wS   w  a   C sC      ws w C       wS   C      C S C a  C   w C    S w       a        C      s C           a          a   SC   a  S  w          a     s    s C  S   s w            s  S w  s w              s      sw w    w         s         s a w          S        C   CS           a w  a   C  C a S w    a    S sw     @    s  S w     w w w   S  a w      a    s  w  C s     aa  C     w  wC    wa            a          s w         S    s s  C      C     S  C     C   S         w s a    sS      wa w   w           aS      |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 941
ace_score 4705
size 941, 1
stairs 402, 0

warrior 740, 0, :east

unit :archer, 0, 0, :east
unit :sludge, 6, 0, :east
unit :thick_sludge, 10, 0, :east
unit :archer, 12, 0, :east
unit :wizard, 17, 0, :east
unit :captive, 21, 0, :east
unit :sludge, 25, 0, :east
unit :thick_sludge, 26, 0, :east
unit :thick_sludge, 32, 0, :east
unit :archer, 36, 0, :east
unit :captive, 48, 0, :east
unit :wizard, 50, 0, :east
unit :sludge, 67, 0, :east
unit :sludge, 74, 0, :east
unit :archer, 75, 0, :east
unit :sludge, 84, 0, :east
unit :sludge, 86, 0, :east
unit :sludge, 93, 0, :east
unit :archer, 99, 0, :east
unit :sludge, 100, 0, :east
unit :archer, 101, 0, :east
unit :captive, 103, 0, :east
unit :captive, 105, 0, :east
unit :archer, 115, 0, :east
unit :captive, 120, 0, :east
unit :thick_sludge, 128, 0, :east
unit :captive, 129, 0, :east
unit :thick_sludge, 130, 0, :east
unit :thick_sludge, 134, 0, :east
unit :captive, 137, 0, :east
unit :wizard, 138, 0, :east
unit :sludge, 139, 0, :east
unit :captive, 141, 0, :east
unit :thick_sludge, 146, 0, :east
unit :archer, 147, 0, :east
unit :sludge, 149, 0, :east
unit :thick_sludge, 150, 0, :east
unit :captive, 153, 0, :east
unit :captive, 154, 0, :east
unit :wizard, 156, 0, :east
unit :archer, 159, 0, :east
unit :archer, 162, 0, :east
unit :sludge, 163, 0, :east
unit :thick_sludge, 168, 0, :east
unit :thick_sludge, 175, 0, :east
unit :wizard, 176, 0, :east
unit :thick_sludge, 178, 0, :east
unit :captive, 179, 0, :east
unit :sludge, 184, 0, :east
unit :sludge, 186, 0, :east
unit :thick_sludge, 190, 0, :east
unit :thick_sludge, 192, 0, :east
unit :archer, 197, 0, :east
unit :archer, 199, 0, :east
unit :captive, 200, 0, :east
unit :thick_sludge, 201, 0, :east
unit :thick_sludge, 205, 0, :east
unit :thick_sludge, 207, 0, :east
unit :thick_sludge, 209, 0, :east
unit :archer, 213, 0, :east
unit :wizard, 215, 0, :east
unit :sludge, 218, 0, :east
unit :sludge, 220, 0, :east
unit :wizard, 224, 0, :east
unit :archer, 235, 0, :east
unit :sludge, 238, 0, :east
unit :captive, 240, 0, :east
unit :archer, 243, 0, :east
unit :wizard, 246, 0, :east
unit :thick_sludge, 247, 0, :east
unit :thick_sludge, 248, 0, :east
unit :archer, 250, 0, :east
unit :sludge, 253, 0, :east
unit :sludge, 255, 0, :east
unit :captive, 256, 0, :east
unit :sludge, 257, 0, :east
unit :sludge, 260, 0, :east
unit :thick_sludge, 262, 0, :east
unit :sludge, 269, 0, :east
unit :thick_sludge, 270, 0, :east
unit :captive, 272, 0, :east
unit :archer, 276, 0, :east
unit :archer, 282, 0, :east
unit :archer, 286, 0, :east
unit :archer, 287, 0, :east
unit :wizard, 289, 0, :east
unit :captive, 296, 0, :east
unit :captive, 300, 0, :east
unit :captive, 311, 0, :east
unit :thick_sludge, 313, 0, :east
unit :archer, 314, 0, :east
unit :captive, 317, 0, :east
unit :sludge, 323, 0, :east
unit :sludge, 325, 0, :east
unit :thick_sludge, 330, 0, :east
unit :captive, 331, 0, :east
unit :thick_sludge, 332, 0, :east
unit :captive, 345, 0, :east
unit :wizard, 346, 0, :east
unit :wizard, 348, 0, :east
unit :wizard, 352, 0, :east
unit :thick_sludge, 355, 0, :east
unit :wizard, 358, 0, :east
unit :thick_sludge, 362, 0, :east
unit :captive, 363, 0, :east
unit :wizard, 364, 0, :east
unit :sludge, 367, 0, :east
unit :archer, 371, 0, :east
unit :sludge, 379, 0, :east
unit :wizard, 385, 0, :east
unit :sludge, 387, 0, :east
unit :wizard, 395, 0, :east
unit :thick_sludge, 401, 0, :east
unit :captive, 407, 0, :east
unit :sludge, 410, 0, :east
unit :sludge, 412, 0, :east
unit :archer, 419, 0, :east
unit :wizard, 420, 0, :east
unit :wizard, 423, 0, :east
unit :thick_sludge, 424, 0, :east
unit :wizard, 428, 0, :east
unit :archer, 431, 0, :east
unit :captive, 435, 0, :east
unit :sludge, 437, 0, :east
unit :captive, 438, 0, :east
unit :wizard, 445, 0, :east
unit :sludge, 446, 0, :east
unit :wizard, 448, 0, :east
unit :captive, 450, 0, :east
unit :wizard, 458, 0, :east
unit :thick_sludge, 459, 0, :east
unit :captive, 463, 0, :east
unit :captive, 470, 0, :east
unit :thick_sludge, 472, 0, :east
unit :captive, 474, 0, :east
unit :archer, 476, 0, :east
unit :captive, 479, 0, :east
unit :wizard, 483, 0, :east
unit :captive, 485, 0, :east
unit :thick_sludge, 490, 0, :east
unit :wizard, 492, 0, :east
unit :archer, 500, 0, :east
unit :captive, 509, 0, :east
unit :sludge, 516, 0, :east
unit :captive, 518, 0, :east
unit :archer, 530, 0, :east
unit :archer, 541, 0, :east
unit :thick_sludge, 545, 0, :east
unit :captive, 546, 0, :east
unit :archer, 550, 0, :east
unit :thick_sludge, 553, 0, :east
unit :wizard, 556, 0, :east
unit :archer, 567, 0, :east
unit :sludge, 573, 0, :east
unit :sludge, 578, 0, :east
unit :captive, 580, 0, :east
unit :thick_sludge, 583, 0, :east
unit :sludge, 587, 0, :east
unit :wizard, 589, 0, :east
unit :sludge, 602, 0, :east
unit :thick_sludge, 605, 0, :east
unit :wizard, 607, 0, :east
unit :sludge, 610, 0, :east
unit :wizard, 612, 0, :east
unit :sludge, 627, 0, :east
unit :sludge, 634, 0, :east
unit :wizard, 635, 0, :east
unit :wizard, 637, 0, :east
unit :wizard, 642, 0, :east
unit :sludge, 652, 0, :east
unit :sludge, 662, 0, :east
unit :archer, 664, 0, :east
unit :wizard, 666, 0, :east
unit :thick_sludge, 677, 0, :east
unit :captive, 686, 0, :east
unit :captive, 690, 0, :east
unit :thick_sludge, 691, 0, :east
unit :archer, 703, 0, :east
unit :wizard, 705, 0, :east
unit :archer, 708, 0, :east
unit :captive, 712, 0, :east
unit :captive, 715, 0, :east
unit :archer, 717, 0, :east
unit :thick_sludge, 719, 0, :east
unit :wizard, 721, 0, :east
unit :archer, 726, 0, :east
unit :thick_sludge, 731, 0, :east
unit :sludge, 733, 0, :east
unit :wizard, 734, 0, :east
unit :sludge, 745, 0, :west
unit :thick_sludge, 748, 0, :west
unit :wizard, 750, 0, :west
unit :wizard, 756, 0, :west
unit :wizard, 758, 0, :west
unit :wizard, 760, 0, :west
unit :thick_sludge, 764, 0, :west
unit :archer, 767, 0, :west
unit :wizard, 769, 0, :west
unit :archer, 776, 0, :west
unit :sludge, 781, 0, :west
unit :wizard, 784, 0, :west
unit :captive, 787, 0, :west
unit :sludge, 789, 0, :west
unit :archer, 795, 0, :west
unit :archer, 796, 0, :west
unit :captive, 799, 0, :west
unit :wizard, 805, 0, :west
unit :wizard, 808, 0, :west
unit :captive, 809, 0, :west
unit :wizard, 814, 0, :west
unit :archer, 815, 0, :west
unit :archer, 828, 0, :west
unit :sludge, 839, 0, :west
unit :wizard, 841, 0, :west
unit :thick_sludge, 851, 0, :west
unit :sludge, 856, 0, :west
unit :sludge, 858, 0, :west
unit :captive, 861, 0, :west
unit :captive, 868, 0, :west
unit :thick_sludge, 874, 0, :west
unit :captive, 877, 0, :west
unit :captive, 883, 0, :west
unit :thick_sludge, 887, 0, :west
unit :wizard, 897, 0, :west
unit :sludge, 899, 0, :west
unit :archer, 901, 0, :west
unit :sludge, 906, 0, :west
unit :thick_sludge, 907, 0, :west
unit :wizard, 914, 0, :west
unit :archer, 915, 0, :west
unit :wizard, 917, 0, :west
unit :wizard, 921, 0, :west
unit :archer, 933, 0, :west
unit :thick_sludge, 934, 0, :west
