#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  s  SsSSswC         S w a         a         S    a      C  S  w         a w w     a            a      S     w            a    sa w  CS   s        s a   CC           a C  S     C C  s  Sa        s  as    w s            a   w      s  SC    C  s aa   S   S   ss Cs         as    C C                  s Sw     C   S aS  s   CC             S  S w a   S     s    C          C s s sw            S     a        w   C s     sC  s     w     a  C   s    w C Cs C   wa         sw            w  w S w Cs          s  a     w    a      w CS     S a a    S  S  a >  w  s a    S a  sa   sa   w     S C  a   w    s sCCs  w w Sw a    S             sS     @   w s   Ssa    s      CS Sa           s      w w awS    CCS   sa  w a  S  C       a      s  C     w a          a  |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 753
ace_score 3765
size 753, 1
stairs 548, 0

warrior 637, 0, :east

unit :sludge, 2, 0, :east
unit :thick_sludge, 5, 0, :east
unit :sludge, 6, 0, :east
unit :thick_sludge, 7, 0, :east
unit :thick_sludge, 8, 0, :east
unit :sludge, 9, 0, :east
unit :wizard, 10, 0, :east
unit :captive, 11, 0, :east
unit :thick_sludge, 21, 0, :east
unit :wizard, 23, 0, :east
unit :archer, 25, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 45, 0, :east
unit :archer, 50, 0, :east
unit :captive, 57, 0, :east
unit :thick_sludge, 60, 0, :east
unit :wizard, 63, 0, :east
unit :archer, 73, 0, :east
unit :wizard, 75, 0, :east
unit :wizard, 77, 0, :east
unit :archer, 83, 0, :east
unit :archer, 96, 0, :east
unit :thick_sludge, 103, 0, :east
unit :wizard, 109, 0, :east
unit :archer, 122, 0, :east
unit :sludge, 127, 0, :east
unit :archer, 128, 0, :east
unit :wizard, 130, 0, :east
unit :captive, 133, 0, :east
unit :thick_sludge, 134, 0, :east
unit :sludge, 138, 0, :east
unit :sludge, 147, 0, :east
unit :archer, 149, 0, :east
unit :captive, 153, 0, :east
unit :captive, 154, 0, :east
unit :archer, 166, 0, :east
unit :captive, 168, 0, :east
unit :thick_sludge, 171, 0, :east
unit :captive, 177, 0, :east
unit :captive, 179, 0, :east
unit :sludge, 182, 0, :east
unit :thick_sludge, 185, 0, :east
unit :archer, 186, 0, :east
unit :sludge, 195, 0, :east
unit :archer, 198, 0, :east
unit :sludge, 199, 0, :east
unit :wizard, 204, 0, :east
unit :sludge, 206, 0, :east
unit :archer, 219, 0, :east
unit :wizard, 223, 0, :east
unit :sludge, 230, 0, :east
unit :thick_sludge, 233, 0, :east
unit :captive, 234, 0, :east
unit :captive, 239, 0, :east
unit :sludge, 242, 0, :east
unit :archer, 244, 0, :east
unit :archer, 245, 0, :east
unit :thick_sludge, 249, 0, :east
unit :thick_sludge, 253, 0, :east
unit :sludge, 257, 0, :east
unit :sludge, 258, 0, :east
unit :captive, 260, 0, :east
unit :sludge, 261, 0, :east
unit :archer, 271, 0, :east
unit :sludge, 272, 0, :east
unit :captive, 277, 0, :east
unit :captive, 279, 0, :east
unit :sludge, 298, 0, :east
unit :thick_sludge, 300, 0, :east
unit :wizard, 301, 0, :east
unit :captive, 307, 0, :east
unit :thick_sludge, 311, 0, :east
unit :archer, 313, 0, :east
unit :thick_sludge, 314, 0, :east
unit :sludge, 317, 0, :east
unit :captive, 321, 0, :east
unit :captive, 322, 0, :east
unit :thick_sludge, 336, 0, :east
unit :thick_sludge, 339, 0, :east
unit :wizard, 341, 0, :east
unit :archer, 343, 0, :east
unit :thick_sludge, 347, 0, :east
unit :sludge, 353, 0, :east
unit :captive, 358, 0, :east
unit :captive, 369, 0, :east
unit :sludge, 371, 0, :east
unit :sludge, 373, 0, :east
unit :sludge, 375, 0, :east
unit :wizard, 376, 0, :east
unit :thick_sludge, 389, 0, :east
unit :archer, 395, 0, :east
unit :wizard, 404, 0, :east
unit :captive, 408, 0, :east
unit :sludge, 410, 0, :east
unit :sludge, 416, 0, :east
unit :captive, 417, 0, :east
unit :sludge, 420, 0, :east
unit :wizard, 426, 0, :east
unit :archer, 432, 0, :east
unit :captive, 435, 0, :east
unit :sludge, 439, 0, :east
unit :wizard, 444, 0, :east
unit :captive, 446, 0, :east
unit :captive, 448, 0, :east
unit :sludge, 449, 0, :east
unit :captive, 451, 0, :east
unit :wizard, 455, 0, :east
unit :archer, 456, 0, :east
unit :sludge, 466, 0, :east
unit :wizard, 467, 0, :east
unit :wizard, 480, 0, :east
unit :wizard, 483, 0, :east
unit :thick_sludge, 485, 0, :east
unit :wizard, 487, 0, :east
unit :captive, 489, 0, :east
unit :sludge, 490, 0, :east
unit :sludge, 501, 0, :east
unit :archer, 504, 0, :east
unit :wizard, 510, 0, :east
unit :archer, 515, 0, :east
unit :wizard, 522, 0, :east
unit :captive, 524, 0, :east
unit :thick_sludge, 525, 0, :east
unit :thick_sludge, 531, 0, :east
unit :archer, 533, 0, :east
unit :archer, 535, 0, :east
unit :thick_sludge, 540, 0, :east
unit :thick_sludge, 543, 0, :east
unit :archer, 546, 0, :east
unit :wizard, 551, 0, :east
unit :sludge, 554, 0, :east
unit :archer, 556, 0, :east
unit :thick_sludge, 561, 0, :east
unit :archer, 563, 0, :east
unit :sludge, 566, 0, :east
unit :archer, 567, 0, :east
unit :sludge, 571, 0, :east
unit :archer, 572, 0, :east
unit :wizard, 576, 0, :east
unit :thick_sludge, 582, 0, :east
unit :captive, 584, 0, :east
unit :archer, 587, 0, :east
unit :wizard, 591, 0, :east
unit :sludge, 596, 0, :east
unit :sludge, 598, 0, :east
unit :captive, 599, 0, :east
unit :captive, 600, 0, :east
unit :sludge, 601, 0, :east
unit :wizard, 604, 0, :east
unit :wizard, 606, 0, :east
unit :thick_sludge, 608, 0, :east
unit :wizard, 609, 0, :east
unit :archer, 611, 0, :east
unit :thick_sludge, 616, 0, :east
unit :sludge, 630, 0, :east
unit :thick_sludge, 631, 0, :east
unit :wizard, 641, 0, :west
unit :sludge, 643, 0, :west
unit :thick_sludge, 647, 0, :west
unit :sludge, 648, 0, :west
unit :archer, 649, 0, :west
unit :sludge, 654, 0, :west
unit :captive, 661, 0, :west
unit :thick_sludge, 662, 0, :west
unit :thick_sludge, 664, 0, :west
unit :archer, 665, 0, :west
unit :sludge, 677, 0, :west
unit :wizard, 684, 0, :west
unit :wizard, 686, 0, :west
unit :archer, 688, 0, :west
unit :wizard, 689, 0, :west
unit :thick_sludge, 690, 0, :west
unit :captive, 695, 0, :west
unit :captive, 696, 0, :west
unit :thick_sludge, 697, 0, :west
unit :sludge, 701, 0, :west
unit :archer, 702, 0, :west
unit :wizard, 705, 0, :west
unit :archer, 707, 0, :west
unit :thick_sludge, 710, 0, :west
unit :captive, 713, 0, :west
unit :archer, 721, 0, :west
unit :sludge, 728, 0, :west
unit :captive, 731, 0, :west
unit :wizard, 737, 0, :west
unit :archer, 739, 0, :west
unit :archer, 750, 0, :west
