#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      w a a s  sS  w   ss      S S  S Cs         ss    S  a   C   S        C   sS  a    w   C     C      a   S  as     S      a      S   w C          C     a S       SC       S     as    w    w  sC      S w             C  w aS        asS               s C   Cs   a           sa     s C w   C  C           aSw   s S     aC             S  a C    s        C      S wS         s     wC  s C  C     Cs       aSC S SC>     s  CsaC     as  s   S      a  sw              s      s w    w   C  a   s  CS C      C C   w   C    sC s   a    s   as     CaC    S C a   aw     w         C sC     w     a   a         s   S  ss    s       CS a        w    s w   wC      w   s S  a s            Ca   C  wa   s           ss  w w      Css      aS S       @    w a  wC     C          w w as C a    s  s    a sw  C      Ss   |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 802
ace_score 4010
size 802, 1
stairs 411, 0

warrior 734, 0, :east

unit :wizard, 6, 0, :east
unit :archer, 8, 0, :east
unit :archer, 10, 0, :east
unit :sludge, 12, 0, :east
unit :sludge, 15, 0, :east
unit :thick_sludge, 16, 0, :east
unit :wizard, 19, 0, :east
unit :sludge, 23, 0, :east
unit :sludge, 24, 0, :east
unit :thick_sludge, 31, 0, :east
unit :thick_sludge, 33, 0, :east
unit :thick_sludge, 36, 0, :east
unit :captive, 38, 0, :east
unit :sludge, 39, 0, :east
unit :sludge, 49, 0, :east
unit :sludge, 50, 0, :east
unit :thick_sludge, 55, 0, :east
unit :archer, 58, 0, :east
unit :captive, 62, 0, :east
unit :thick_sludge, 66, 0, :east
unit :captive, 75, 0, :east
unit :sludge, 79, 0, :east
unit :thick_sludge, 80, 0, :east
unit :archer, 83, 0, :east
unit :wizard, 88, 0, :east
unit :captive, 92, 0, :east
unit :captive, 98, 0, :east
unit :archer, 105, 0, :east
unit :thick_sludge, 109, 0, :east
unit :archer, 112, 0, :east
unit :sludge, 113, 0, :east
unit :thick_sludge, 119, 0, :east
unit :archer, 126, 0, :east
unit :thick_sludge, 133, 0, :east
unit :wizard, 137, 0, :east
unit :captive, 139, 0, :east
unit :captive, 150, 0, :east
unit :archer, 156, 0, :east
unit :thick_sludge, 158, 0, :east
unit :thick_sludge, 166, 0, :east
unit :captive, 167, 0, :east
unit :thick_sludge, 175, 0, :east
unit :archer, 181, 0, :east
unit :sludge, 182, 0, :east
unit :wizard, 187, 0, :east
unit :wizard, 192, 0, :east
unit :sludge, 195, 0, :east
unit :captive, 196, 0, :east
unit :thick_sludge, 203, 0, :east
unit :wizard, 205, 0, :east
unit :captive, 219, 0, :east
unit :wizard, 222, 0, :east
unit :archer, 224, 0, :east
unit :thick_sludge, 225, 0, :east
unit :archer, 234, 0, :east
unit :sludge, 235, 0, :east
unit :thick_sludge, 236, 0, :east
unit :sludge, 252, 0, :east
unit :captive, 254, 0, :east
unit :captive, 258, 0, :east
unit :sludge, 259, 0, :east
unit :archer, 263, 0, :east
unit :sludge, 275, 0, :east
unit :archer, 276, 0, :east
unit :sludge, 282, 0, :east
unit :captive, 284, 0, :east
unit :wizard, 286, 0, :east
unit :captive, 290, 0, :east
unit :captive, 293, 0, :east
unit :archer, 305, 0, :east
unit :thick_sludge, 306, 0, :east
unit :wizard, 307, 0, :east
unit :sludge, 311, 0, :east
unit :thick_sludge, 313, 0, :east
unit :archer, 319, 0, :east
unit :captive, 320, 0, :east
unit :thick_sludge, 334, 0, :east
unit :archer, 337, 0, :east
unit :captive, 339, 0, :east
unit :sludge, 344, 0, :east
unit :captive, 353, 0, :east
unit :thick_sludge, 360, 0, :east
unit :wizard, 362, 0, :east
unit :thick_sludge, 363, 0, :east
unit :sludge, 373, 0, :east
unit :wizard, 379, 0, :east
unit :captive, 380, 0, :east
unit :sludge, 383, 0, :east
unit :captive, 385, 0, :east
unit :captive, 388, 0, :east
unit :captive, 394, 0, :east
unit :sludge, 395, 0, :east
unit :archer, 403, 0, :east
unit :thick_sludge, 404, 0, :east
unit :captive, 405, 0, :east
unit :thick_sludge, 407, 0, :east
unit :thick_sludge, 409, 0, :east
unit :captive, 410, 0, :east
unit :sludge, 417, 0, :east
unit :captive, 420, 0, :east
unit :sludge, 421, 0, :east
unit :archer, 422, 0, :east
unit :captive, 423, 0, :east
unit :archer, 429, 0, :east
unit :sludge, 430, 0, :east
unit :sludge, 433, 0, :east
unit :thick_sludge, 437, 0, :east
unit :archer, 444, 0, :east
unit :sludge, 447, 0, :east
unit :wizard, 448, 0, :east
unit :sludge, 463, 0, :east
unit :sludge, 470, 0, :east
unit :wizard, 472, 0, :east
unit :wizard, 477, 0, :east
unit :captive, 481, 0, :east
unit :archer, 484, 0, :east
unit :sludge, 488, 0, :east
unit :captive, 491, 0, :east
unit :thick_sludge, 492, 0, :east
unit :captive, 494, 0, :east
unit :captive, 501, 0, :east
unit :captive, 503, 0, :east
unit :wizard, 507, 0, :east
unit :captive, 511, 0, :east
unit :sludge, 516, 0, :east
unit :captive, 517, 0, :east
unit :sludge, 519, 0, :east
unit :archer, 523, 0, :east
unit :sludge, 528, 0, :east
unit :archer, 532, 0, :east
unit :sludge, 533, 0, :east
unit :captive, 539, 0, :east
unit :archer, 540, 0, :east
unit :captive, 541, 0, :east
unit :thick_sludge, 546, 0, :east
unit :captive, 548, 0, :east
unit :archer, 550, 0, :east
unit :archer, 554, 0, :east
unit :wizard, 555, 0, :east
unit :wizard, 561, 0, :east
unit :captive, 571, 0, :east
unit :sludge, 573, 0, :east
unit :captive, 574, 0, :east
unit :wizard, 580, 0, :east
unit :archer, 586, 0, :east
unit :archer, 590, 0, :east
unit :sludge, 600, 0, :east
unit :thick_sludge, 604, 0, :east
unit :sludge, 607, 0, :east
unit :sludge, 608, 0, :east
unit :sludge, 613, 0, :east
unit :captive, 621, 0, :east
unit :thick_sludge, 622, 0, :east
unit :archer, 624, 0, :east
unit :wizard, 633, 0, :east
unit :sludge, 638, 0, :east
unit :wizard, 640, 0, :east
unit :wizard, 644, 0, :east
unit :captive, 645, 0, :east
unit :wizard, 652, 0, :east
unit :sludge, 656, 0, :east
unit :thick_sludge, 658, 0, :east
unit :archer, 661, 0, :east
unit :sludge, 663, 0, :east
unit :captive, 676, 0, :east
unit :archer, 677, 0, :east
unit :captive, 681, 0, :east
unit :wizard, 684, 0, :east
unit :archer, 685, 0, :east
unit :sludge, 689, 0, :east
unit :sludge, 701, 0, :east
unit :sludge, 702, 0, :east
unit :wizard, 705, 0, :east
unit :wizard, 707, 0, :east
unit :captive, 714, 0, :east
unit :sludge, 715, 0, :east
unit :sludge, 716, 0, :east
unit :archer, 723, 0, :east
unit :thick_sludge, 724, 0, :east
unit :thick_sludge, 726, 0, :east
unit :wizard, 739, 0, :west
unit :archer, 741, 0, :west
unit :wizard, 744, 0, :west
unit :captive, 745, 0, :west
unit :captive, 751, 0, :west
unit :wizard, 762, 0, :west
unit :wizard, 764, 0, :west
unit :archer, 766, 0, :west
unit :sludge, 767, 0, :west
unit :captive, 769, 0, :west
unit :archer, 771, 0, :west
unit :sludge, 776, 0, :west
unit :sludge, 779, 0, :west
unit :archer, 784, 0, :west
unit :sludge, 786, 0, :west
unit :wizard, 787, 0, :west
unit :captive, 790, 0, :west
unit :thick_sludge, 797, 0, :west
unit :sludge, 798, 0, :west
