#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  C  C    a C a      s      w s CS C   Ss  wa  w sS            SC   a     C aS  wSCSCC as         C         s    sC         SC    w             a     w         s                 CS  a C   C    a  a       C      a  S a   a     CC     S       ss w w as         C    a s  s  wS S   CC           C  Swa  C S    C  a s       a         wa  S      w       CS aw a SS S  s  aa   a     C  s C    aC    aC   S  C w    s  s s  wS  s  C   S w              sS    sC    w         @                    C    a       s C    S  s        S S ws S      w     s         a     Ca S a  s w a     w      C  aC   a w   C    S   s a            a  S      asS  C s w w>                 SsC              a sw|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 679
ace_score 3395
size 679, 1
stairs 640, 0

warrior 466, 0, :east

unit :captive, 2, 0, :east
unit :captive, 5, 0, :east
unit :archer, 10, 0, :east
unit :captive, 12, 0, :east
unit :archer, 14, 0, :east
unit :sludge, 21, 0, :east
unit :wizard, 28, 0, :east
unit :sludge, 30, 0, :east
unit :captive, 32, 0, :east
unit :thick_sludge, 33, 0, :east
unit :captive, 35, 0, :east
unit :thick_sludge, 39, 0, :east
unit :sludge, 40, 0, :east
unit :wizard, 43, 0, :east
unit :archer, 44, 0, :east
unit :wizard, 47, 0, :east
unit :sludge, 49, 0, :east
unit :thick_sludge, 50, 0, :east
unit :thick_sludge, 63, 0, :east
unit :captive, 64, 0, :east
unit :archer, 68, 0, :east
unit :captive, 74, 0, :east
unit :archer, 76, 0, :east
unit :thick_sludge, 77, 0, :east
unit :wizard, 80, 0, :east
unit :thick_sludge, 81, 0, :east
unit :captive, 82, 0, :east
unit :thick_sludge, 83, 0, :east
unit :captive, 84, 0, :east
unit :captive, 85, 0, :east
unit :archer, 87, 0, :east
unit :sludge, 88, 0, :east
unit :captive, 98, 0, :east
unit :sludge, 108, 0, :east
unit :sludge, 113, 0, :east
unit :captive, 114, 0, :east
unit :thick_sludge, 124, 0, :east
unit :captive, 125, 0, :east
unit :wizard, 130, 0, :east
unit :archer, 144, 0, :east
unit :wizard, 150, 0, :east
unit :sludge, 160, 0, :east
unit :captive, 178, 0, :east
unit :thick_sludge, 179, 0, :east
unit :archer, 182, 0, :east
unit :captive, 184, 0, :east
unit :captive, 188, 0, :east
unit :archer, 193, 0, :east
unit :archer, 196, 0, :east
unit :captive, 204, 0, :east
unit :archer, 211, 0, :east
unit :thick_sludge, 214, 0, :east
unit :archer, 216, 0, :east
unit :archer, 220, 0, :east
unit :captive, 226, 0, :east
unit :captive, 227, 0, :east
unit :thick_sludge, 233, 0, :east
unit :sludge, 241, 0, :east
unit :sludge, 242, 0, :east
unit :wizard, 244, 0, :east
unit :wizard, 246, 0, :east
unit :archer, 248, 0, :east
unit :sludge, 249, 0, :east
unit :captive, 259, 0, :east
unit :archer, 264, 0, :east
unit :sludge, 266, 0, :east
unit :sludge, 269, 0, :east
unit :wizard, 272, 0, :east
unit :thick_sludge, 273, 0, :east
unit :thick_sludge, 275, 0, :east
unit :captive, 279, 0, :east
unit :captive, 280, 0, :east
unit :captive, 292, 0, :east
unit :thick_sludge, 295, 0, :east
unit :wizard, 296, 0, :east
unit :archer, 297, 0, :east
unit :captive, 300, 0, :east
unit :thick_sludge, 302, 0, :east
unit :captive, 307, 0, :east
unit :archer, 310, 0, :east
unit :sludge, 312, 0, :east
unit :archer, 320, 0, :east
unit :wizard, 330, 0, :east
unit :archer, 331, 0, :east
unit :thick_sludge, 334, 0, :east
unit :wizard, 341, 0, :east
unit :captive, 349, 0, :east
unit :thick_sludge, 350, 0, :east
unit :archer, 352, 0, :east
unit :wizard, 353, 0, :east
unit :archer, 355, 0, :east
unit :thick_sludge, 357, 0, :east
unit :thick_sludge, 358, 0, :east
unit :thick_sludge, 360, 0, :east
unit :sludge, 363, 0, :east
unit :archer, 366, 0, :east
unit :archer, 367, 0, :east
unit :archer, 371, 0, :east
unit :captive, 377, 0, :east
unit :sludge, 380, 0, :east
unit :captive, 382, 0, :east
unit :archer, 387, 0, :east
unit :captive, 388, 0, :east
unit :archer, 393, 0, :east
unit :captive, 394, 0, :east
unit :thick_sludge, 398, 0, :east
unit :captive, 401, 0, :east
unit :wizard, 403, 0, :east
unit :sludge, 408, 0, :east
unit :sludge, 411, 0, :east
unit :sludge, 413, 0, :east
unit :wizard, 416, 0, :east
unit :thick_sludge, 417, 0, :east
unit :sludge, 420, 0, :east
unit :captive, 423, 0, :east
unit :thick_sludge, 427, 0, :east
unit :wizard, 429, 0, :east
unit :sludge, 444, 0, :east
unit :thick_sludge, 445, 0, :east
unit :sludge, 450, 0, :east
unit :captive, 451, 0, :east
unit :wizard, 456, 0, :east
unit :captive, 487, 0, :west
unit :archer, 492, 0, :west
unit :sludge, 500, 0, :west
unit :captive, 502, 0, :west
unit :thick_sludge, 507, 0, :west
unit :sludge, 510, 0, :west
unit :thick_sludge, 519, 0, :west
unit :thick_sludge, 521, 0, :west
unit :wizard, 523, 0, :west
unit :sludge, 524, 0, :west
unit :thick_sludge, 526, 0, :west
unit :wizard, 533, 0, :west
unit :sludge, 539, 0, :west
unit :archer, 549, 0, :west
unit :captive, 555, 0, :west
unit :archer, 556, 0, :west
unit :thick_sludge, 558, 0, :west
unit :archer, 560, 0, :west
unit :sludge, 563, 0, :west
unit :wizard, 565, 0, :west
unit :archer, 567, 0, :west
unit :wizard, 573, 0, :west
unit :captive, 580, 0, :west
unit :archer, 583, 0, :west
unit :captive, 584, 0, :west
unit :archer, 588, 0, :west
unit :wizard, 590, 0, :west
unit :captive, 594, 0, :west
unit :thick_sludge, 599, 0, :west
unit :sludge, 603, 0, :west
unit :archer, 605, 0, :west
unit :archer, 618, 0, :west
unit :thick_sludge, 621, 0, :west
unit :archer, 628, 0, :west
unit :sludge, 629, 0, :west
unit :thick_sludge, 630, 0, :west
unit :captive, 633, 0, :west
unit :sludge, 635, 0, :west
unit :wizard, 637, 0, :west
unit :wizard, 639, 0, :west
unit :thick_sludge, 658, 0, :west
unit :sludge, 659, 0, :west
unit :captive, 660, 0, :west
unit :archer, 675, 0, :west
unit :sludge, 677, 0, :west
unit :wizard, 678, 0, :west
