#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   S             C w aS       sS ws                aS  w     a  w s a             s   C  asa    w   Sw s   w S a   a  a S s   a      a   C S    ws          a   @      SCs w S    s    a a S ws s            sCS  w SC          C           w   s  C SC        a      a      w  s     Cs  a       w       s   Cw      s     C s          s   w    w    C   w    a a      saa SC C       Ssa          s  wC     w a   sa        S  C  S   S    w   C s   C   Ss a      C     s  SS      Cwa    s  a     C  w     C  a w  aa S w   s  w  Sa a s  w    s   S     sC C  S    s     S   C   as  S w  w           SS    a  S  aC  w        S     S    s     C       aC      Cw         s  S sw     S S  S    >a   C      C  C     a     a     C w             Ssw     w    a       S      aC  s    s   S a         S     s   w  Cs         C    CS s      S  Sa S|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 827
ace_score 4135
size 827, 1
stairs 679, 0

warrior 160, 0, :east

unit :thick_sludge, 3, 0, :east
unit :captive, 17, 0, :east
unit :wizard, 19, 0, :east
unit :archer, 21, 0, :east
unit :thick_sludge, 22, 0, :east
unit :sludge, 30, 0, :east
unit :thick_sludge, 31, 0, :east
unit :wizard, 33, 0, :east
unit :sludge, 34, 0, :east
unit :archer, 51, 0, :east
unit :thick_sludge, 52, 0, :east
unit :wizard, 55, 0, :east
unit :archer, 61, 0, :east
unit :wizard, 64, 0, :east
unit :sludge, 66, 0, :east
unit :archer, 68, 0, :east
unit :sludge, 82, 0, :east
unit :captive, 86, 0, :east
unit :archer, 89, 0, :east
unit :sludge, 90, 0, :east
unit :archer, 91, 0, :east
unit :wizard, 96, 0, :east
unit :thick_sludge, 100, 0, :east
unit :wizard, 101, 0, :east
unit :sludge, 103, 0, :east
unit :wizard, 107, 0, :east
unit :thick_sludge, 109, 0, :east
unit :archer, 111, 0, :east
unit :archer, 115, 0, :east
unit :archer, 118, 0, :east
unit :thick_sludge, 120, 0, :east
unit :sludge, 122, 0, :east
unit :archer, 126, 0, :east
unit :archer, 133, 0, :east
unit :captive, 137, 0, :east
unit :thick_sludge, 139, 0, :east
unit :wizard, 144, 0, :east
unit :sludge, 145, 0, :east
unit :archer, 156, 0, :east
unit :thick_sludge, 167, 0, :west
unit :captive, 168, 0, :west
unit :sludge, 169, 0, :west
unit :wizard, 171, 0, :west
unit :thick_sludge, 173, 0, :west
unit :sludge, 178, 0, :west
unit :archer, 183, 0, :west
unit :archer, 185, 0, :west
unit :thick_sludge, 187, 0, :west
unit :wizard, 189, 0, :west
unit :sludge, 190, 0, :west
unit :sludge, 192, 0, :west
unit :sludge, 205, 0, :west
unit :captive, 206, 0, :west
unit :thick_sludge, 207, 0, :west
unit :wizard, 210, 0, :west
unit :thick_sludge, 212, 0, :west
unit :captive, 213, 0, :west
unit :captive, 224, 0, :west
unit :wizard, 236, 0, :west
unit :sludge, 240, 0, :west
unit :captive, 243, 0, :west
unit :thick_sludge, 245, 0, :west
unit :captive, 246, 0, :west
unit :archer, 255, 0, :west
unit :archer, 262, 0, :west
unit :wizard, 269, 0, :west
unit :sludge, 272, 0, :west
unit :captive, 278, 0, :west
unit :sludge, 279, 0, :west
unit :archer, 282, 0, :west
unit :wizard, 290, 0, :west
unit :sludge, 298, 0, :west
unit :captive, 302, 0, :west
unit :wizard, 303, 0, :west
unit :sludge, 310, 0, :west
unit :captive, 316, 0, :west
unit :sludge, 318, 0, :west
unit :sludge, 329, 0, :west
unit :wizard, 333, 0, :west
unit :wizard, 338, 0, :west
unit :captive, 343, 0, :west
unit :wizard, 347, 0, :west
unit :archer, 352, 0, :west
unit :archer, 354, 0, :west
unit :sludge, 361, 0, :west
unit :archer, 362, 0, :west
unit :archer, 363, 0, :west
unit :thick_sludge, 365, 0, :west
unit :captive, 366, 0, :west
unit :captive, 368, 0, :west
unit :thick_sludge, 376, 0, :west
unit :sludge, 377, 0, :west
unit :archer, 378, 0, :west
unit :sludge, 389, 0, :west
unit :wizard, 392, 0, :west
unit :captive, 393, 0, :west
unit :wizard, 399, 0, :west
unit :archer, 401, 0, :west
unit :sludge, 405, 0, :west
unit :archer, 406, 0, :west
unit :thick_sludge, 415, 0, :west
unit :captive, 418, 0, :west
unit :thick_sludge, 421, 0, :west
unit :thick_sludge, 425, 0, :west
unit :wizard, 430, 0, :west
unit :captive, 434, 0, :west
unit :sludge, 436, 0, :west
unit :captive, 440, 0, :west
unit :thick_sludge, 444, 0, :west
unit :sludge, 445, 0, :west
unit :archer, 447, 0, :west
unit :captive, 454, 0, :west
unit :sludge, 460, 0, :west
unit :thick_sludge, 463, 0, :west
unit :thick_sludge, 464, 0, :west
unit :captive, 471, 0, :west
unit :wizard, 472, 0, :west
unit :archer, 473, 0, :west
unit :sludge, 478, 0, :west
unit :archer, 481, 0, :west
unit :captive, 487, 0, :west
unit :wizard, 490, 0, :west
unit :captive, 496, 0, :west
unit :archer, 499, 0, :west
unit :wizard, 501, 0, :west
unit :archer, 504, 0, :west
unit :archer, 505, 0, :west
unit :thick_sludge, 507, 0, :west
unit :wizard, 509, 0, :west
unit :sludge, 513, 0, :west
unit :wizard, 516, 0, :west
unit :thick_sludge, 519, 0, :west
unit :archer, 520, 0, :west
unit :archer, 522, 0, :west
unit :sludge, 524, 0, :west
unit :wizard, 527, 0, :west
unit :sludge, 532, 0, :west
unit :thick_sludge, 536, 0, :west
unit :sludge, 542, 0, :west
unit :captive, 543, 0, :west
unit :captive, 545, 0, :west
unit :thick_sludge, 548, 0, :west
unit :sludge, 553, 0, :west
unit :thick_sludge, 559, 0, :west
unit :captive, 563, 0, :west
unit :archer, 567, 0, :west
unit :sludge, 568, 0, :west
unit :thick_sludge, 571, 0, :west
unit :wizard, 573, 0, :west
unit :wizard, 576, 0, :west
unit :thick_sludge, 588, 0, :west
unit :thick_sludge, 589, 0, :west
unit :archer, 594, 0, :west
unit :thick_sludge, 597, 0, :west
unit :archer, 600, 0, :west
unit :captive, 601, 0, :west
unit :wizard, 604, 0, :west
unit :thick_sludge, 613, 0, :west
unit :thick_sludge, 619, 0, :west
unit :sludge, 624, 0, :west
unit :captive, 630, 0, :west
unit :archer, 638, 0, :west
unit :captive, 639, 0, :west
unit :captive, 646, 0, :west
unit :wizard, 647, 0, :west
unit :sludge, 657, 0, :west
unit :thick_sludge, 660, 0, :west
unit :sludge, 662, 0, :west
unit :wizard, 663, 0, :west
unit :thick_sludge, 669, 0, :west
unit :thick_sludge, 671, 0, :west
unit :thick_sludge, 674, 0, :west
unit :archer, 680, 0, :west
unit :captive, 684, 0, :west
unit :captive, 691, 0, :west
unit :captive, 694, 0, :west
unit :archer, 700, 0, :west
unit :archer, 706, 0, :west
unit :captive, 712, 0, :west
unit :wizard, 714, 0, :west
unit :thick_sludge, 728, 0, :west
unit :sludge, 729, 0, :west
unit :wizard, 730, 0, :west
unit :wizard, 736, 0, :west
unit :archer, 741, 0, :west
unit :thick_sludge, 749, 0, :west
unit :archer, 756, 0, :west
unit :captive, 757, 0, :west
unit :sludge, 760, 0, :west
unit :sludge, 765, 0, :west
unit :thick_sludge, 769, 0, :west
unit :archer, 771, 0, :west
unit :thick_sludge, 781, 0, :west
unit :sludge, 787, 0, :west
unit :wizard, 791, 0, :west
unit :captive, 794, 0, :west
unit :sludge, 795, 0, :west
unit :captive, 805, 0, :west
unit :captive, 810, 0, :west
unit :thick_sludge, 811, 0, :west
unit :sludge, 813, 0, :west
unit :thick_sludge, 820, 0, :west
unit :thick_sludge, 823, 0, :west
unit :archer, 824, 0, :west
unit :thick_sludge, 826, 0, :west
