#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   sSC  w   w  s C       a            Ca  a   s sa  C   C a   S                  s C s      w    CC      sSa  C a    sw     w     S       aw  s     w  s a w  a        C  w        s    S       C a s   w      s   s  w  s     w  C sC Ss  C    a C a       C s C      C   w C   S      sC           aC   C           a       a aS S      S aa       SC   ss    C   w C  S   a s  sC C   s S  CC      SS      w  sC       Sw  C aaCw  a  wa  s       C S   C   w  S   S         Ca    a   >   w    s           C   s  w    S a w   S                 w     s  s w      C  a C Cs  s SC               C sCa      aC Cw   s       w  C   S      S S aa           w    S  @          S  CS w   S sS  CS aa   s          a   S       a  C          C S s   s C  S ss  w          s S    S s      s sC     C s      a       s  w  a      S         S  sC a    S      S s     C a            |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 855
ace_score 4275
size 855, 1
stairs 474, 0

warrior 647, 0, :east

unit :sludge, 3, 0, :east
unit :thick_sludge, 4, 0, :east
unit :captive, 5, 0, :east
unit :wizard, 8, 0, :east
unit :wizard, 12, 0, :east
unit :sludge, 15, 0, :east
unit :captive, 17, 0, :east
unit :archer, 25, 0, :east
unit :captive, 38, 0, :east
unit :archer, 39, 0, :east
unit :archer, 42, 0, :east
unit :sludge, 46, 0, :east
unit :sludge, 48, 0, :east
unit :archer, 49, 0, :east
unit :captive, 52, 0, :east
unit :captive, 56, 0, :east
unit :archer, 58, 0, :east
unit :thick_sludge, 62, 0, :east
unit :sludge, 81, 0, :east
unit :captive, 83, 0, :east
unit :sludge, 85, 0, :east
unit :wizard, 92, 0, :east
unit :captive, 97, 0, :east
unit :captive, 98, 0, :east
unit :sludge, 105, 0, :east
unit :thick_sludge, 106, 0, :east
unit :archer, 107, 0, :east
unit :captive, 110, 0, :east
unit :archer, 112, 0, :east
unit :sludge, 117, 0, :east
unit :wizard, 118, 0, :east
unit :wizard, 124, 0, :east
unit :thick_sludge, 130, 0, :east
unit :archer, 138, 0, :east
unit :wizard, 139, 0, :east
unit :sludge, 142, 0, :east
unit :wizard, 148, 0, :east
unit :sludge, 151, 0, :east
unit :archer, 153, 0, :east
unit :wizard, 155, 0, :east
unit :archer, 158, 0, :east
unit :captive, 167, 0, :east
unit :wizard, 170, 0, :east
unit :sludge, 179, 0, :east
unit :thick_sludge, 184, 0, :east
unit :captive, 192, 0, :east
unit :archer, 194, 0, :east
unit :sludge, 196, 0, :east
unit :wizard, 200, 0, :east
unit :sludge, 207, 0, :east
unit :sludge, 211, 0, :east
unit :wizard, 214, 0, :east
unit :sludge, 217, 0, :east
unit :wizard, 223, 0, :east
unit :captive, 226, 0, :east
unit :sludge, 228, 0, :east
unit :captive, 229, 0, :east
unit :thick_sludge, 231, 0, :east
unit :sludge, 232, 0, :east
unit :captive, 235, 0, :east
unit :archer, 240, 0, :east
unit :captive, 242, 0, :east
unit :archer, 244, 0, :east
unit :captive, 252, 0, :east
unit :sludge, 254, 0, :east
unit :captive, 256, 0, :east
unit :captive, 263, 0, :east
unit :wizard, 267, 0, :east
unit :captive, 269, 0, :east
unit :thick_sludge, 273, 0, :east
unit :sludge, 280, 0, :east
unit :captive, 281, 0, :east
unit :archer, 293, 0, :east
unit :captive, 294, 0, :east
unit :captive, 298, 0, :east
unit :archer, 310, 0, :east
unit :archer, 318, 0, :east
unit :archer, 320, 0, :east
unit :thick_sludge, 321, 0, :east
unit :thick_sludge, 323, 0, :east
unit :thick_sludge, 330, 0, :east
unit :archer, 332, 0, :east
unit :archer, 333, 0, :east
unit :thick_sludge, 341, 0, :east
unit :captive, 342, 0, :east
unit :sludge, 346, 0, :east
unit :sludge, 347, 0, :east
unit :captive, 352, 0, :east
unit :wizard, 356, 0, :east
unit :captive, 358, 0, :east
unit :thick_sludge, 361, 0, :east
unit :archer, 365, 0, :east
unit :sludge, 367, 0, :east
unit :sludge, 370, 0, :east
unit :captive, 371, 0, :east
unit :captive, 373, 0, :east
unit :sludge, 377, 0, :east
unit :thick_sludge, 379, 0, :east
unit :captive, 382, 0, :east
unit :captive, 383, 0, :east
unit :thick_sludge, 390, 0, :east
unit :thick_sludge, 391, 0, :east
unit :wizard, 398, 0, :east
unit :sludge, 401, 0, :east
unit :captive, 402, 0, :east
unit :thick_sludge, 410, 0, :east
unit :wizard, 411, 0, :east
unit :captive, 414, 0, :east
unit :archer, 416, 0, :east
unit :archer, 417, 0, :east
unit :captive, 418, 0, :east
unit :wizard, 419, 0, :east
unit :archer, 422, 0, :east
unit :wizard, 425, 0, :east
unit :archer, 426, 0, :east
unit :sludge, 429, 0, :east
unit :captive, 437, 0, :east
unit :thick_sludge, 439, 0, :east
unit :captive, 443, 0, :east
unit :wizard, 447, 0, :east
unit :thick_sludge, 450, 0, :east
unit :thick_sludge, 454, 0, :east
unit :captive, 464, 0, :east
unit :archer, 465, 0, :east
unit :archer, 470, 0, :east
unit :wizard, 478, 0, :east
unit :sludge, 483, 0, :east
unit :captive, 495, 0, :east
unit :sludge, 499, 0, :east
unit :wizard, 502, 0, :east
unit :thick_sludge, 507, 0, :east
unit :archer, 509, 0, :east
unit :wizard, 511, 0, :east
unit :thick_sludge, 515, 0, :east
unit :wizard, 533, 0, :east
unit :sludge, 539, 0, :east
unit :sludge, 542, 0, :east
unit :wizard, 544, 0, :east
unit :captive, 551, 0, :east
unit :archer, 554, 0, :east
unit :captive, 556, 0, :east
unit :captive, 558, 0, :east
unit :sludge, 559, 0, :east
unit :sludge, 562, 0, :east
unit :thick_sludge, 564, 0, :east
unit :captive, 565, 0, :east
unit :captive, 581, 0, :east
unit :sludge, 583, 0, :east
unit :captive, 584, 0, :east
unit :archer, 585, 0, :east
unit :archer, 592, 0, :east
unit :captive, 593, 0, :east
unit :captive, 595, 0, :east
unit :wizard, 596, 0, :east
unit :sludge, 600, 0, :east
unit :wizard, 608, 0, :east
unit :captive, 611, 0, :east
unit :thick_sludge, 615, 0, :east
unit :thick_sludge, 622, 0, :east
unit :thick_sludge, 624, 0, :east
unit :archer, 626, 0, :east
unit :archer, 627, 0, :east
unit :wizard, 639, 0, :east
unit :thick_sludge, 644, 0, :east
unit :thick_sludge, 658, 0, :west
unit :captive, 661, 0, :west
unit :thick_sludge, 662, 0, :west
unit :wizard, 664, 0, :west
unit :thick_sludge, 668, 0, :west
unit :sludge, 670, 0, :west
unit :thick_sludge, 671, 0, :west
unit :captive, 674, 0, :west
unit :thick_sludge, 675, 0, :west
unit :archer, 677, 0, :west
unit :archer, 678, 0, :west
unit :sludge, 682, 0, :west
unit :archer, 693, 0, :west
unit :thick_sludge, 697, 0, :west
unit :archer, 705, 0, :west
unit :captive, 708, 0, :west
unit :captive, 719, 0, :west
unit :thick_sludge, 721, 0, :west
unit :sludge, 723, 0, :west
unit :sludge, 727, 0, :west
unit :captive, 729, 0, :west
unit :thick_sludge, 732, 0, :west
unit :sludge, 734, 0, :west
unit :sludge, 735, 0, :west
unit :wizard, 738, 0, :west
unit :sludge, 749, 0, :west
unit :thick_sludge, 751, 0, :west
unit :thick_sludge, 756, 0, :west
unit :sludge, 758, 0, :west
unit :sludge, 765, 0, :west
unit :sludge, 767, 0, :west
unit :captive, 768, 0, :west
unit :captive, 774, 0, :west
unit :sludge, 776, 0, :west
unit :archer, 783, 0, :west
unit :sludge, 791, 0, :west
unit :wizard, 794, 0, :west
unit :archer, 797, 0, :west
unit :thick_sludge, 804, 0, :west
unit :thick_sludge, 814, 0, :west
unit :sludge, 817, 0, :west
unit :captive, 818, 0, :west
unit :archer, 820, 0, :west
unit :thick_sludge, 825, 0, :west
unit :thick_sludge, 832, 0, :west
unit :sludge, 834, 0, :west
unit :captive, 840, 0, :west
unit :archer, 842, 0, :west
