#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  sCS wC  w     C         aS    w s  Ss w  > waC             s      w s     S w   a   C    C    s s a  w w CC   a    S         s   a            w  w      S  a           s         w        S       a  s C            s  S  s  S  a ss      w  Cs      a w    w  w  S  s  Cs    w    ssa           w  wC       w    a    sS  C  w                a    s s  S  SSw        SSw  s   w  w      a       S C        sa      s                 C       w as s  SCCs   s         w C  w           @  w  C Casa    a   s  a      s            s  C  w         S    s s S     Caa  w  C s  S    Ca a  wCa        w   ssw a   s  SS  s w       S w s  S    C S   aS S     s|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 641
ace_score 3205
size 641, 1
stairs 43, 0

warrior 475, 0, :east

unit :sludge, 2, 0, :east
unit :captive, 3, 0, :east
unit :thick_sludge, 4, 0, :east
unit :wizard, 6, 0, :east
unit :captive, 7, 0, :east
unit :wizard, 10, 0, :east
unit :captive, 16, 0, :east
unit :archer, 26, 0, :east
unit :thick_sludge, 27, 0, :east
unit :wizard, 32, 0, :east
unit :sludge, 34, 0, :east
unit :thick_sludge, 37, 0, :east
unit :sludge, 38, 0, :east
unit :wizard, 40, 0, :east
unit :wizard, 45, 0, :east
unit :archer, 46, 0, :east
unit :captive, 47, 0, :east
unit :sludge, 61, 0, :east
unit :wizard, 68, 0, :east
unit :sludge, 70, 0, :east
unit :thick_sludge, 76, 0, :east
unit :wizard, 78, 0, :east
unit :archer, 82, 0, :east
unit :captive, 86, 0, :east
unit :captive, 91, 0, :east
unit :sludge, 96, 0, :east
unit :sludge, 98, 0, :east
unit :archer, 100, 0, :east
unit :wizard, 103, 0, :east
unit :wizard, 105, 0, :east
unit :captive, 107, 0, :east
unit :captive, 108, 0, :east
unit :archer, 112, 0, :east
unit :thick_sludge, 117, 0, :east
unit :sludge, 127, 0, :east
unit :archer, 131, 0, :east
unit :wizard, 144, 0, :east
unit :wizard, 147, 0, :east
unit :thick_sludge, 154, 0, :east
unit :archer, 157, 0, :east
unit :sludge, 169, 0, :east
unit :wizard, 179, 0, :east
unit :thick_sludge, 188, 0, :east
unit :archer, 196, 0, :east
unit :sludge, 199, 0, :east
unit :captive, 201, 0, :east
unit :sludge, 214, 0, :east
unit :thick_sludge, 217, 0, :east
unit :sludge, 220, 0, :east
unit :thick_sludge, 223, 0, :east
unit :archer, 226, 0, :east
unit :sludge, 228, 0, :east
unit :sludge, 229, 0, :east
unit :wizard, 236, 0, :east
unit :captive, 239, 0, :east
unit :sludge, 240, 0, :east
unit :archer, 247, 0, :east
unit :wizard, 249, 0, :east
unit :wizard, 254, 0, :east
unit :wizard, 257, 0, :east
unit :thick_sludge, 260, 0, :east
unit :sludge, 263, 0, :east
unit :captive, 266, 0, :east
unit :sludge, 267, 0, :east
unit :wizard, 272, 0, :east
unit :sludge, 277, 0, :east
unit :sludge, 278, 0, :east
unit :archer, 279, 0, :east
unit :wizard, 291, 0, :east
unit :wizard, 294, 0, :east
unit :captive, 295, 0, :east
unit :wizard, 303, 0, :east
unit :archer, 308, 0, :east
unit :sludge, 313, 0, :east
unit :thick_sludge, 314, 0, :east
unit :captive, 317, 0, :east
unit :wizard, 320, 0, :east
unit :archer, 337, 0, :east
unit :sludge, 342, 0, :east
unit :sludge, 344, 0, :east
unit :thick_sludge, 347, 0, :east
unit :thick_sludge, 350, 0, :east
unit :thick_sludge, 351, 0, :east
unit :wizard, 352, 0, :east
unit :thick_sludge, 361, 0, :east
unit :thick_sludge, 362, 0, :east
unit :wizard, 363, 0, :east
unit :sludge, 366, 0, :east
unit :wizard, 370, 0, :east
unit :wizard, 373, 0, :east
unit :archer, 380, 0, :east
unit :thick_sludge, 388, 0, :east
unit :captive, 390, 0, :east
unit :sludge, 399, 0, :east
unit :archer, 400, 0, :east
unit :sludge, 407, 0, :east
unit :captive, 425, 0, :east
unit :wizard, 433, 0, :east
unit :archer, 435, 0, :east
unit :sludge, 436, 0, :east
unit :sludge, 438, 0, :east
unit :thick_sludge, 441, 0, :east
unit :captive, 442, 0, :east
unit :captive, 443, 0, :east
unit :sludge, 444, 0, :east
unit :sludge, 448, 0, :east
unit :wizard, 458, 0, :east
unit :captive, 460, 0, :east
unit :wizard, 463, 0, :east
unit :wizard, 478, 0, :west
unit :captive, 481, 0, :west
unit :captive, 483, 0, :west
unit :archer, 484, 0, :west
unit :sludge, 485, 0, :west
unit :archer, 486, 0, :west
unit :archer, 491, 0, :west
unit :sludge, 495, 0, :west
unit :archer, 498, 0, :west
unit :sludge, 505, 0, :west
unit :sludge, 518, 0, :west
unit :captive, 521, 0, :west
unit :wizard, 524, 0, :west
unit :thick_sludge, 534, 0, :west
unit :sludge, 539, 0, :west
unit :sludge, 541, 0, :west
unit :thick_sludge, 543, 0, :west
unit :captive, 549, 0, :west
unit :archer, 550, 0, :west
unit :archer, 551, 0, :west
unit :wizard, 554, 0, :west
unit :captive, 557, 0, :west
unit :sludge, 559, 0, :west
unit :thick_sludge, 562, 0, :west
unit :captive, 567, 0, :west
unit :archer, 568, 0, :west
unit :archer, 570, 0, :west
unit :wizard, 573, 0, :west
unit :captive, 574, 0, :west
unit :archer, 575, 0, :west
unit :wizard, 584, 0, :west
unit :sludge, 588, 0, :west
unit :sludge, 589, 0, :west
unit :wizard, 590, 0, :west
unit :archer, 592, 0, :west
unit :sludge, 596, 0, :west
unit :thick_sludge, 599, 0, :west
unit :thick_sludge, 600, 0, :west
unit :sludge, 603, 0, :west
unit :wizard, 605, 0, :west
unit :thick_sludge, 613, 0, :west
unit :wizard, 615, 0, :west
unit :sludge, 617, 0, :west
unit :thick_sludge, 620, 0, :west
unit :captive, 625, 0, :west
unit :thick_sludge, 627, 0, :west
unit :archer, 631, 0, :west
unit :thick_sludge, 632, 0, :west
unit :thick_sludge, 634, 0, :west
unit :sludge, 640, 0, :west
