#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   w  C  C  w    s   S C S   @    s s   CC    Sw          Csa   S    a          a       a a       s     CC w    wC      a w C  S    C        SC ss    aa           a  s C Sw   a         S  w  S C w     S      s    S  aa w          aSw   w   a   w  s  a   w       a aS      sw     s C      aw     S   s C   asC     C     S  S as      s     s    C  w   S    w s  a           a   C C      a s          a s S                C   w  S  C a        Sa C     C          s    S  a C   s     S  Ss asC    w  C   s      S SC     S    w      > s s   w  C   S   a       S w SS     C     s S  w  C |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 582
ace_score 2910
size 582, 1
stairs 528, 0

warrior 29, 0, :east

unit :wizard, 3, 0, :east
unit :captive, 6, 0, :east
unit :captive, 9, 0, :east
unit :wizard, 12, 0, :east
unit :sludge, 17, 0, :east
unit :thick_sludge, 21, 0, :east
unit :captive, 23, 0, :east
unit :thick_sludge, 25, 0, :east
unit :sludge, 34, 0, :west
unit :sludge, 36, 0, :west
unit :captive, 40, 0, :west
unit :captive, 41, 0, :west
unit :thick_sludge, 46, 0, :west
unit :wizard, 47, 0, :west
unit :captive, 58, 0, :west
unit :sludge, 59, 0, :west
unit :archer, 60, 0, :west
unit :thick_sludge, 64, 0, :west
unit :archer, 69, 0, :west
unit :archer, 80, 0, :west
unit :archer, 88, 0, :west
unit :archer, 90, 0, :west
unit :sludge, 98, 0, :west
unit :captive, 104, 0, :west
unit :captive, 105, 0, :west
unit :wizard, 107, 0, :west
unit :wizard, 112, 0, :west
unit :captive, 113, 0, :west
unit :archer, 120, 0, :west
unit :wizard, 122, 0, :west
unit :captive, 124, 0, :west
unit :thick_sludge, 127, 0, :west
unit :captive, 132, 0, :west
unit :thick_sludge, 141, 0, :west
unit :captive, 142, 0, :west
unit :sludge, 144, 0, :west
unit :sludge, 145, 0, :west
unit :archer, 150, 0, :west
unit :archer, 151, 0, :west
unit :archer, 163, 0, :west
unit :sludge, 166, 0, :west
unit :captive, 168, 0, :west
unit :thick_sludge, 170, 0, :west
unit :wizard, 171, 0, :west
unit :archer, 175, 0, :west
unit :thick_sludge, 185, 0, :west
unit :wizard, 188, 0, :west
unit :thick_sludge, 191, 0, :west
unit :captive, 193, 0, :west
unit :wizard, 195, 0, :west
unit :thick_sludge, 201, 0, :west
unit :sludge, 208, 0, :west
unit :thick_sludge, 213, 0, :west
unit :archer, 216, 0, :west
unit :archer, 217, 0, :west
unit :wizard, 219, 0, :west
unit :archer, 230, 0, :west
unit :thick_sludge, 231, 0, :west
unit :wizard, 232, 0, :west
unit :wizard, 236, 0, :west
unit :archer, 240, 0, :west
unit :wizard, 244, 0, :west
unit :sludge, 247, 0, :west
unit :archer, 250, 0, :west
unit :wizard, 254, 0, :west
unit :archer, 262, 0, :west
unit :archer, 264, 0, :west
unit :thick_sludge, 265, 0, :west
unit :sludge, 272, 0, :west
unit :wizard, 273, 0, :west
unit :sludge, 279, 0, :west
unit :captive, 281, 0, :west
unit :archer, 288, 0, :west
unit :wizard, 289, 0, :west
unit :thick_sludge, 295, 0, :west
unit :sludge, 299, 0, :west
unit :captive, 301, 0, :west
unit :archer, 305, 0, :west
unit :sludge, 306, 0, :west
unit :captive, 307, 0, :west
unit :captive, 313, 0, :west
unit :thick_sludge, 319, 0, :west
unit :thick_sludge, 322, 0, :west
unit :archer, 324, 0, :west
unit :sludge, 325, 0, :west
unit :sludge, 332, 0, :west
unit :sludge, 338, 0, :west
unit :captive, 343, 0, :west
unit :wizard, 346, 0, :west
unit :thick_sludge, 350, 0, :west
unit :wizard, 355, 0, :west
unit :sludge, 357, 0, :west
unit :archer, 360, 0, :west
unit :archer, 372, 0, :west
unit :captive, 376, 0, :west
unit :captive, 378, 0, :west
unit :archer, 385, 0, :west
unit :sludge, 387, 0, :west
unit :archer, 398, 0, :west
unit :sludge, 400, 0, :west
unit :thick_sludge, 402, 0, :west
unit :captive, 419, 0, :west
unit :wizard, 423, 0, :west
unit :thick_sludge, 426, 0, :west
unit :captive, 429, 0, :west
unit :archer, 431, 0, :west
unit :thick_sludge, 440, 0, :west
unit :archer, 441, 0, :west
unit :captive, 443, 0, :west
unit :captive, 449, 0, :west
unit :sludge, 460, 0, :west
unit :thick_sludge, 465, 0, :west
unit :archer, 468, 0, :west
unit :captive, 470, 0, :west
unit :sludge, 474, 0, :west
unit :thick_sludge, 480, 0, :west
unit :thick_sludge, 483, 0, :west
unit :sludge, 484, 0, :west
unit :archer, 486, 0, :west
unit :sludge, 487, 0, :west
unit :captive, 488, 0, :west
unit :wizard, 493, 0, :west
unit :captive, 496, 0, :west
unit :sludge, 500, 0, :west
unit :thick_sludge, 507, 0, :west
unit :thick_sludge, 509, 0, :west
unit :captive, 510, 0, :west
unit :thick_sludge, 516, 0, :west
unit :wizard, 521, 0, :west
unit :sludge, 530, 0, :west
unit :sludge, 532, 0, :west
unit :wizard, 536, 0, :west
unit :captive, 539, 0, :west
unit :thick_sludge, 543, 0, :west
unit :archer, 547, 0, :west
unit :thick_sludge, 555, 0, :west
unit :wizard, 557, 0, :west
unit :thick_sludge, 559, 0, :west
unit :thick_sludge, 560, 0, :west
unit :captive, 566, 0, :west
unit :sludge, 572, 0, :west
unit :thick_sludge, 574, 0, :west
unit :wizard, 577, 0, :west
unit :captive, 580, 0, :west
