#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    S   Ca    sss   w  s     C C  S   s    a  a    w        S     C   s      C        s Ss        a   C   s    a      C   a   w    S s     C Ss    S  as  @   as               s  a              s CS ws          SS w    a  aa   C         C a  C  s aS  w    w   C SS C       s   C    w a C S    s   a w   a     a   s   S s         a s C  s   C  C s    C      s       S s         wC  a  Sa       a   C  a  aw              w        w   S     w  S              C s C      w C a             w  SSs a w     SC      Sw  C      a     a     s  a   w S w sC   wSs   a wa a    w S          s ass      a       a      S a C w    C     wC    C   w      C              w C  as a        S S        a wS      a       w a     s       s     C   SS    C    a  w   C    w   w SC         a     w ws SS   S      w > CC     a a     ss   C  s C a    ws as  a      CSw S C Sa a   a s wa    C        Ca  C     a          ws       C   C   w  w  C a s     C  S  a     s  s s  C         a       S   a    |
#  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 972
ace_score 4860
size 972, 1
stairs 789, 0

warrior 154, 0, :east

unit :thick_sludge, 4, 0, :east
unit :captive, 8, 0, :east
unit :archer, 9, 0, :east
unit :sludge, 14, 0, :east
unit :sludge, 15, 0, :east
unit :sludge, 16, 0, :east
unit :wizard, 20, 0, :east
unit :sludge, 23, 0, :east
unit :captive, 29, 0, :east
unit :captive, 31, 0, :east
unit :thick_sludge, 34, 0, :east
unit :sludge, 38, 0, :east
unit :archer, 43, 0, :east
unit :archer, 46, 0, :east
unit :wizard, 51, 0, :east
unit :thick_sludge, 60, 0, :east
unit :captive, 66, 0, :east
unit :sludge, 70, 0, :east
unit :captive, 77, 0, :east
unit :sludge, 86, 0, :east
unit :thick_sludge, 88, 0, :east
unit :sludge, 89, 0, :east
unit :archer, 98, 0, :east
unit :captive, 102, 0, :east
unit :sludge, 106, 0, :east
unit :archer, 111, 0, :east
unit :captive, 118, 0, :east
unit :archer, 122, 0, :east
unit :wizard, 126, 0, :east
unit :thick_sludge, 131, 0, :east
unit :sludge, 133, 0, :east
unit :captive, 139, 0, :east
unit :thick_sludge, 141, 0, :east
unit :sludge, 142, 0, :east
unit :thick_sludge, 147, 0, :east
unit :archer, 150, 0, :east
unit :sludge, 151, 0, :east
unit :archer, 158, 0, :west
unit :sludge, 159, 0, :west
unit :sludge, 175, 0, :west
unit :archer, 178, 0, :west
unit :sludge, 193, 0, :west
unit :captive, 195, 0, :west
unit :thick_sludge, 196, 0, :west
unit :wizard, 198, 0, :west
unit :sludge, 199, 0, :west
unit :thick_sludge, 210, 0, :west
unit :thick_sludge, 211, 0, :west
unit :wizard, 213, 0, :west
unit :archer, 218, 0, :west
unit :archer, 221, 0, :west
unit :archer, 222, 0, :west
unit :captive, 226, 0, :west
unit :captive, 236, 0, :west
unit :archer, 238, 0, :west
unit :captive, 241, 0, :west
unit :sludge, 244, 0, :west
unit :archer, 246, 0, :west
unit :thick_sludge, 247, 0, :west
unit :wizard, 250, 0, :west
unit :wizard, 255, 0, :west
unit :captive, 259, 0, :west
unit :thick_sludge, 261, 0, :west
unit :thick_sludge, 262, 0, :west
unit :captive, 264, 0, :west
unit :sludge, 272, 0, :west
unit :captive, 276, 0, :west
unit :wizard, 281, 0, :west
unit :archer, 283, 0, :west
unit :captive, 285, 0, :west
unit :thick_sludge, 287, 0, :west
unit :sludge, 292, 0, :west
unit :archer, 296, 0, :west
unit :wizard, 298, 0, :west
unit :archer, 302, 0, :west
unit :archer, 308, 0, :west
unit :sludge, 312, 0, :west
unit :thick_sludge, 316, 0, :west
unit :sludge, 318, 0, :west
unit :archer, 328, 0, :west
unit :sludge, 330, 0, :west
unit :captive, 332, 0, :west
unit :sludge, 335, 0, :west
unit :captive, 339, 0, :west
unit :captive, 342, 0, :west
unit :sludge, 344, 0, :west
unit :captive, 349, 0, :west
unit :sludge, 356, 0, :west
unit :thick_sludge, 364, 0, :west
unit :sludge, 366, 0, :west
unit :wizard, 376, 0, :west
unit :captive, 377, 0, :west
unit :archer, 380, 0, :west
unit :thick_sludge, 383, 0, :west
unit :archer, 384, 0, :west
unit :archer, 392, 0, :west
unit :captive, 396, 0, :west
unit :archer, 399, 0, :west
unit :archer, 402, 0, :west
unit :wizard, 403, 0, :west
unit :wizard, 418, 0, :west
unit :wizard, 427, 0, :west
unit :thick_sludge, 431, 0, :west
unit :wizard, 437, 0, :west
unit :thick_sludge, 440, 0, :west
unit :captive, 455, 0, :west
unit :sludge, 457, 0, :west
unit :captive, 459, 0, :west
unit :wizard, 466, 0, :west
unit :captive, 468, 0, :west
unit :archer, 470, 0, :west
unit :wizard, 484, 0, :west
unit :thick_sludge, 487, 0, :west
unit :thick_sludge, 488, 0, :west
unit :sludge, 489, 0, :west
unit :archer, 491, 0, :west
unit :wizard, 493, 0, :west
unit :thick_sludge, 499, 0, :west
unit :captive, 500, 0, :west
unit :thick_sludge, 507, 0, :west
unit :wizard, 508, 0, :west
unit :captive, 511, 0, :west
unit :archer, 518, 0, :west
unit :archer, 524, 0, :west
unit :sludge, 530, 0, :west
unit :archer, 533, 0, :west
unit :wizard, 537, 0, :west
unit :thick_sludge, 539, 0, :west
unit :wizard, 541, 0, :west
unit :sludge, 543, 0, :west
unit :captive, 544, 0, :west
unit :wizard, 548, 0, :west
unit :thick_sludge, 549, 0, :west
unit :sludge, 550, 0, :west
unit :archer, 554, 0, :west
unit :wizard, 556, 0, :west
unit :archer, 557, 0, :west
unit :archer, 559, 0, :west
unit :wizard, 564, 0, :west
unit :thick_sludge, 566, 0, :west
unit :sludge, 577, 0, :west
unit :archer, 579, 0, :west
unit :sludge, 580, 0, :west
unit :sludge, 581, 0, :west
unit :archer, 588, 0, :west
unit :archer, 596, 0, :west
unit :thick_sludge, 603, 0, :west
unit :archer, 605, 0, :west
unit :captive, 607, 0, :west
unit :wizard, 609, 0, :west
unit :captive, 614, 0, :west
unit :wizard, 620, 0, :west
unit :captive, 621, 0, :west
unit :captive, 626, 0, :west
unit :wizard, 630, 0, :west
unit :captive, 637, 0, :west
unit :wizard, 652, 0, :west
unit :captive, 654, 0, :west
unit :archer, 657, 0, :west
unit :sludge, 658, 0, :west
unit :archer, 660, 0, :west
unit :thick_sludge, 669, 0, :west
unit :thick_sludge, 671, 0, :west
unit :archer, 680, 0, :west
unit :wizard, 682, 0, :west
unit :thick_sludge, 683, 0, :west
unit :archer, 690, 0, :west
unit :wizard, 698, 0, :west
unit :archer, 700, 0, :west
unit :sludge, 706, 0, :west
unit :sludge, 714, 0, :west
unit :captive, 720, 0, :west
unit :thick_sludge, 724, 0, :west
unit :thick_sludge, 725, 0, :west
unit :captive, 730, 0, :west
unit :archer, 735, 0, :west
unit :wizard, 738, 0, :west
unit :captive, 742, 0, :west
unit :wizard, 747, 0, :west
unit :wizard, 751, 0, :west
unit :thick_sludge, 753, 0, :west
unit :captive, 754, 0, :west
unit :archer, 764, 0, :west
unit :wizard, 770, 0, :west
unit :wizard, 772, 0, :west
unit :sludge, 773, 0, :west
unit :thick_sludge, 775, 0, :west
unit :thick_sludge, 776, 0, :west
unit :thick_sludge, 780, 0, :west
unit :wizard, 787, 0, :west
unit :captive, 791, 0, :west
unit :captive, 792, 0, :west
unit :archer, 798, 0, :west
unit :archer, 800, 0, :west
unit :sludge, 806, 0, :west
unit :sludge, 807, 0, :west
unit :captive, 811, 0, :west
unit :sludge, 814, 0, :west
unit :captive, 816, 0, :west
unit :archer, 818, 0, :west
unit :wizard, 823, 0, :west
unit :sludge, 824, 0, :west
unit :archer, 826, 0, :west
unit :sludge, 827, 0, :west
unit :archer, 830, 0, :west
unit :captive, 837, 0, :west
unit :thick_sludge, 838, 0, :west
unit :wizard, 839, 0, :west
unit :thick_sludge, 841, 0, :west
unit :captive, 843, 0, :west
unit :thick_sludge, 845, 0, :west
unit :archer, 846, 0, :west
unit :archer, 848, 0, :west
unit :archer, 852, 0, :west
unit :sludge, 854, 0, :west
unit :wizard, 856, 0, :west
unit :archer, 857, 0, :west
unit :captive, 862, 0, :west
unit :captive, 871, 0, :west
unit :archer, 872, 0, :west
unit :captive, 875, 0, :west
unit :archer, 881, 0, :west
unit :wizard, 892, 0, :west
unit :sludge, 893, 0, :west
unit :captive, 901, 0, :west
unit :captive, 905, 0, :west
unit :wizard, 909, 0, :west
unit :wizard, 912, 0, :west
unit :captive, 915, 0, :west
unit :archer, 917, 0, :west
unit :sludge, 919, 0, :west
unit :captive, 925, 0, :west
unit :thick_sludge, 928, 0, :west
unit :archer, 931, 0, :west
unit :sludge, 937, 0, :west
unit :sludge, 940, 0, :west
unit :sludge, 942, 0, :west
unit :captive, 945, 0, :west
unit :archer, 955, 0, :west
unit :thick_sludge, 963, 0, :west
unit :archer, 967, 0, :west
