#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  ss       S          a    S     C C   S  Cs   C        a     w  Cw S                a>    s     a  a w          S as   as       a      w     w    w C  sa        s C S      s      a      CC Cs    s     s  a    as    a   s         a    w   s  aC Ca sw  s      S w       S w  CC w        Ca CS   S C         s       a S   SaC S     C    C C   Ca s      s sa   SS CC      S   aC      C           C   s      a           S w      s S      s   S S a   S      S       S       C a    C    as SCa w  a s     s    CC   C     s  wS  C   S S       w        S   a wa        a  C   ws           S               Cw     S  C   w s       S      sC  C     w     w as         s a   Csaa   w C     C w    s S     w s      sC   w       a  s   as s      S    aa aw w    wC  a a      s  w s   SCa     w  @    S  C       SSa S                a   S C  C        sC  C  w  w    S sa  as    w w     S   |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 875
ace_score 4375
size 875, 1
stairs 86, 0

warrior 781, 0, :east

unit :sludge, 2, 0, :east
unit :sludge, 3, 0, :east
unit :thick_sludge, 11, 0, :east
unit :archer, 22, 0, :east
unit :thick_sludge, 27, 0, :east
unit :captive, 33, 0, :east
unit :captive, 35, 0, :east
unit :thick_sludge, 39, 0, :east
unit :captive, 42, 0, :east
unit :sludge, 43, 0, :east
unit :captive, 47, 0, :east
unit :archer, 56, 0, :east
unit :wizard, 62, 0, :east
unit :captive, 65, 0, :east
unit :wizard, 66, 0, :east
unit :thick_sludge, 68, 0, :east
unit :archer, 85, 0, :east
unit :sludge, 91, 0, :east
unit :archer, 97, 0, :east
unit :archer, 100, 0, :east
unit :wizard, 102, 0, :east
unit :thick_sludge, 113, 0, :east
unit :archer, 115, 0, :east
unit :sludge, 116, 0, :east
unit :archer, 120, 0, :east
unit :sludge, 121, 0, :east
unit :archer, 129, 0, :east
unit :wizard, 136, 0, :east
unit :wizard, 142, 0, :east
unit :wizard, 147, 0, :east
unit :captive, 149, 0, :east
unit :sludge, 152, 0, :east
unit :archer, 153, 0, :east
unit :sludge, 162, 0, :east
unit :captive, 164, 0, :east
unit :thick_sludge, 166, 0, :east
unit :sludge, 173, 0, :east
unit :archer, 180, 0, :east
unit :captive, 187, 0, :east
unit :captive, 188, 0, :east
unit :captive, 190, 0, :east
unit :sludge, 191, 0, :east
unit :sludge, 196, 0, :east
unit :sludge, 202, 0, :east
unit :archer, 205, 0, :east
unit :archer, 210, 0, :east
unit :sludge, 211, 0, :east
unit :archer, 216, 0, :east
unit :sludge, 220, 0, :east
unit :archer, 230, 0, :east
unit :wizard, 235, 0, :east
unit :sludge, 239, 0, :east
unit :archer, 242, 0, :east
unit :captive, 243, 0, :east
unit :captive, 245, 0, :east
unit :archer, 246, 0, :east
unit :sludge, 248, 0, :east
unit :wizard, 249, 0, :east
unit :sludge, 252, 0, :east
unit :thick_sludge, 259, 0, :east
unit :wizard, 261, 0, :east
unit :thick_sludge, 269, 0, :east
unit :wizard, 271, 0, :east
unit :captive, 274, 0, :east
unit :captive, 275, 0, :east
unit :wizard, 277, 0, :east
unit :captive, 286, 0, :east
unit :archer, 287, 0, :east
unit :captive, 289, 0, :east
unit :thick_sludge, 290, 0, :east
unit :thick_sludge, 294, 0, :east
unit :captive, 296, 0, :east
unit :sludge, 306, 0, :east
unit :archer, 314, 0, :east
unit :thick_sludge, 316, 0, :east
unit :thick_sludge, 320, 0, :east
unit :archer, 321, 0, :east
unit :captive, 322, 0, :east
unit :thick_sludge, 324, 0, :east
unit :captive, 330, 0, :east
unit :captive, 335, 0, :east
unit :captive, 337, 0, :east
unit :captive, 341, 0, :east
unit :archer, 342, 0, :east
unit :sludge, 344, 0, :east
unit :sludge, 351, 0, :east
unit :sludge, 353, 0, :east
unit :archer, 354, 0, :east
unit :thick_sludge, 358, 0, :east
unit :thick_sludge, 359, 0, :east
unit :captive, 361, 0, :east
unit :captive, 362, 0, :east
unit :thick_sludge, 369, 0, :east
unit :archer, 373, 0, :east
unit :captive, 374, 0, :east
unit :captive, 381, 0, :east
unit :captive, 393, 0, :east
unit :sludge, 397, 0, :east
unit :archer, 404, 0, :east
unit :thick_sludge, 416, 0, :east
unit :wizard, 418, 0, :east
unit :sludge, 425, 0, :east
unit :thick_sludge, 427, 0, :east
unit :sludge, 434, 0, :east
unit :thick_sludge, 438, 0, :east
unit :thick_sludge, 440, 0, :east
unit :archer, 442, 0, :east
unit :thick_sludge, 446, 0, :east
unit :thick_sludge, 453, 0, :east
unit :thick_sludge, 461, 0, :east
unit :captive, 469, 0, :east
unit :archer, 471, 0, :east
unit :captive, 476, 0, :east
unit :archer, 481, 0, :east
unit :sludge, 482, 0, :east
unit :thick_sludge, 484, 0, :east
unit :captive, 485, 0, :east
unit :archer, 486, 0, :east
unit :wizard, 488, 0, :east
unit :archer, 491, 0, :east
unit :sludge, 493, 0, :east
unit :sludge, 499, 0, :east
unit :captive, 504, 0, :east
unit :captive, 505, 0, :east
unit :captive, 509, 0, :east
unit :sludge, 515, 0, :east
unit :wizard, 518, 0, :east
unit :thick_sludge, 519, 0, :east
unit :captive, 522, 0, :east
unit :thick_sludge, 526, 0, :east
unit :thick_sludge, 528, 0, :east
unit :wizard, 536, 0, :east
unit :thick_sludge, 545, 0, :east
unit :archer, 549, 0, :east
unit :wizard, 551, 0, :east
unit :archer, 552, 0, :east
unit :archer, 561, 0, :east
unit :captive, 564, 0, :east
unit :wizard, 568, 0, :east
unit :sludge, 569, 0, :east
unit :thick_sludge, 581, 0, :east
unit :captive, 597, 0, :east
unit :wizard, 598, 0, :east
unit :thick_sludge, 604, 0, :east
unit :captive, 607, 0, :east
unit :wizard, 611, 0, :east
unit :sludge, 613, 0, :east
unit :thick_sludge, 621, 0, :east
unit :sludge, 628, 0, :east
unit :captive, 629, 0, :east
unit :captive, 632, 0, :east
unit :wizard, 638, 0, :east
unit :wizard, 644, 0, :east
unit :archer, 646, 0, :east
unit :sludge, 647, 0, :east
unit :sludge, 657, 0, :east
unit :archer, 659, 0, :east
unit :captive, 663, 0, :east
unit :sludge, 664, 0, :east
unit :archer, 665, 0, :east
unit :archer, 666, 0, :east
unit :wizard, 670, 0, :east
unit :captive, 672, 0, :east
unit :captive, 678, 0, :east
unit :wizard, 680, 0, :east
unit :sludge, 685, 0, :east
unit :thick_sludge, 687, 0, :east
unit :wizard, 693, 0, :east
unit :sludge, 695, 0, :east
unit :sludge, 702, 0, :east
unit :captive, 703, 0, :east
unit :wizard, 707, 0, :east
unit :archer, 715, 0, :east
unit :sludge, 718, 0, :east
unit :archer, 722, 0, :east
unit :sludge, 723, 0, :east
unit :sludge, 725, 0, :east
unit :thick_sludge, 732, 0, :east
unit :archer, 737, 0, :east
unit :archer, 738, 0, :east
unit :archer, 740, 0, :east
unit :wizard, 741, 0, :east
unit :wizard, 743, 0, :east
unit :wizard, 748, 0, :east
unit :captive, 749, 0, :east
unit :archer, 752, 0, :east
unit :archer, 754, 0, :east
unit :sludge, 761, 0, :east
unit :wizard, 764, 0, :east
unit :sludge, 766, 0, :east
unit :thick_sludge, 770, 0, :east
unit :captive, 771, 0, :east
unit :archer, 772, 0, :east
unit :wizard, 778, 0, :east
unit :thick_sludge, 786, 0, :west
unit :captive, 789, 0, :west
unit :thick_sludge, 797, 0, :west
unit :thick_sludge, 798, 0, :west
unit :archer, 799, 0, :west
unit :thick_sludge, 801, 0, :west
unit :archer, 818, 0, :west
unit :thick_sludge, 822, 0, :west
unit :captive, 824, 0, :west
unit :captive, 827, 0, :west
unit :sludge, 836, 0, :west
unit :captive, 837, 0, :west
unit :captive, 840, 0, :west
unit :wizard, 843, 0, :west
unit :wizard, 846, 0, :west
unit :thick_sludge, 851, 0, :west
unit :sludge, 853, 0, :west
unit :archer, 854, 0, :west
unit :archer, 857, 0, :west
unit :sludge, 858, 0, :west
unit :wizard, 863, 0, :west
unit :wizard, 865, 0, :west
unit :thick_sludge, 871, 0, :west
