#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |         s w  S    S     a wsS         a   Ss     C s   S Sa   s   s  S     C         aS      S S S       a C     C      S  S         w S  s     aa s S aS           C S   s C   SSss  S    a     C       C    w   w          a      w      s s s     S   aa        ws  w C C  a  w  S  a    w w  w        sS   w   C   s S w      sC    SS C    Ca    S       sCs    w w   C C  CC  s  s    S   sw   s   s              sCa     Ss w    S     w  >s          s   S    w  S  S a     S   a     saS     S   Cw  a    w SC  w          w              a     s wsaCCC      s     w    a        w SC  S      S sC              s       C C           S  S     C   C     CC    @  S a  a|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 659
ace_score 3295
size 659, 1
stairs 434, 0

warrior 650, 0, :east

unit :sludge, 9, 0, :east
unit :wizard, 11, 0, :east
unit :thick_sludge, 14, 0, :east
unit :thick_sludge, 19, 0, :east
unit :archer, 25, 0, :east
unit :wizard, 27, 0, :east
unit :sludge, 28, 0, :east
unit :thick_sludge, 29, 0, :east
unit :archer, 39, 0, :east
unit :thick_sludge, 43, 0, :east
unit :sludge, 44, 0, :east
unit :captive, 50, 0, :east
unit :sludge, 52, 0, :east
unit :thick_sludge, 56, 0, :east
unit :thick_sludge, 58, 0, :east
unit :archer, 59, 0, :east
unit :sludge, 63, 0, :east
unit :sludge, 67, 0, :east
unit :thick_sludge, 70, 0, :east
unit :captive, 76, 0, :east
unit :archer, 86, 0, :east
unit :thick_sludge, 87, 0, :east
unit :thick_sludge, 94, 0, :east
unit :thick_sludge, 96, 0, :east
unit :thick_sludge, 98, 0, :east
unit :archer, 106, 0, :east
unit :captive, 108, 0, :east
unit :captive, 114, 0, :east
unit :thick_sludge, 121, 0, :east
unit :thick_sludge, 124, 0, :east
unit :wizard, 134, 0, :east
unit :thick_sludge, 136, 0, :east
unit :sludge, 139, 0, :east
unit :archer, 145, 0, :east
unit :archer, 146, 0, :east
unit :sludge, 148, 0, :east
unit :thick_sludge, 150, 0, :east
unit :archer, 152, 0, :east
unit :thick_sludge, 153, 0, :east
unit :captive, 165, 0, :east
unit :thick_sludge, 167, 0, :east
unit :sludge, 171, 0, :east
unit :captive, 173, 0, :east
unit :thick_sludge, 177, 0, :east
unit :thick_sludge, 178, 0, :east
unit :sludge, 179, 0, :east
unit :sludge, 180, 0, :east
unit :thick_sludge, 183, 0, :east
unit :archer, 188, 0, :east
unit :captive, 194, 0, :east
unit :captive, 202, 0, :east
unit :wizard, 207, 0, :east
unit :wizard, 211, 0, :east
unit :archer, 222, 0, :east
unit :wizard, 229, 0, :east
unit :sludge, 236, 0, :east
unit :sludge, 238, 0, :east
unit :sludge, 240, 0, :east
unit :thick_sludge, 246, 0, :east
unit :archer, 250, 0, :east
unit :archer, 251, 0, :east
unit :wizard, 260, 0, :east
unit :sludge, 261, 0, :east
unit :wizard, 264, 0, :east
unit :captive, 266, 0, :east
unit :captive, 268, 0, :east
unit :archer, 271, 0, :east
unit :wizard, 274, 0, :east
unit :thick_sludge, 277, 0, :east
unit :archer, 280, 0, :east
unit :wizard, 285, 0, :east
unit :wizard, 287, 0, :east
unit :wizard, 290, 0, :east
unit :sludge, 299, 0, :east
unit :thick_sludge, 300, 0, :east
unit :wizard, 304, 0, :east
unit :captive, 308, 0, :east
unit :sludge, 312, 0, :east
unit :thick_sludge, 314, 0, :east
unit :wizard, 316, 0, :east
unit :sludge, 323, 0, :east
unit :captive, 324, 0, :east
unit :thick_sludge, 329, 0, :east
unit :thick_sludge, 330, 0, :east
unit :captive, 332, 0, :east
unit :captive, 337, 0, :east
unit :archer, 338, 0, :east
unit :thick_sludge, 343, 0, :east
unit :sludge, 351, 0, :east
unit :captive, 352, 0, :east
unit :sludge, 353, 0, :east
unit :wizard, 358, 0, :east
unit :wizard, 360, 0, :east
unit :captive, 364, 0, :east
unit :captive, 366, 0, :east
unit :captive, 369, 0, :east
unit :captive, 370, 0, :east
unit :sludge, 373, 0, :east
unit :sludge, 376, 0, :east
unit :thick_sludge, 381, 0, :east
unit :sludge, 385, 0, :east
unit :wizard, 386, 0, :east
unit :sludge, 390, 0, :east
unit :sludge, 394, 0, :east
unit :sludge, 409, 0, :east
unit :captive, 410, 0, :east
unit :archer, 411, 0, :east
unit :thick_sludge, 417, 0, :east
unit :sludge, 418, 0, :east
unit :wizard, 420, 0, :east
unit :thick_sludge, 425, 0, :east
unit :wizard, 431, 0, :east
unit :sludge, 435, 0, :east
unit :sludge, 446, 0, :east
unit :thick_sludge, 450, 0, :east
unit :wizard, 455, 0, :east
unit :thick_sludge, 458, 0, :east
unit :thick_sludge, 461, 0, :east
unit :archer, 463, 0, :east
unit :thick_sludge, 469, 0, :east
unit :archer, 473, 0, :east
unit :sludge, 479, 0, :east
unit :archer, 480, 0, :east
unit :thick_sludge, 481, 0, :east
unit :thick_sludge, 487, 0, :east
unit :captive, 491, 0, :east
unit :wizard, 492, 0, :east
unit :archer, 495, 0, :east
unit :wizard, 500, 0, :east
unit :thick_sludge, 502, 0, :east
unit :captive, 503, 0, :east
unit :wizard, 506, 0, :east
unit :wizard, 517, 0, :east
unit :archer, 532, 0, :east
unit :sludge, 538, 0, :east
unit :wizard, 540, 0, :east
unit :sludge, 541, 0, :east
unit :archer, 542, 0, :east
unit :captive, 543, 0, :east
unit :captive, 544, 0, :east
unit :captive, 545, 0, :east
unit :sludge, 552, 0, :east
unit :wizard, 558, 0, :east
unit :archer, 563, 0, :east
unit :wizard, 572, 0, :east
unit :thick_sludge, 574, 0, :east
unit :captive, 575, 0, :east
unit :thick_sludge, 578, 0, :east
unit :thick_sludge, 585, 0, :east
unit :sludge, 587, 0, :east
unit :captive, 588, 0, :east
unit :sludge, 603, 0, :east
unit :captive, 611, 0, :east
unit :captive, 613, 0, :east
unit :thick_sludge, 625, 0, :east
unit :thick_sludge, 628, 0, :east
unit :captive, 634, 0, :east
unit :captive, 638, 0, :east
unit :captive, 644, 0, :east
unit :captive, 645, 0, :east
unit :thick_sludge, 653, 0, :west
unit :archer, 655, 0, :west
unit :archer, 658, 0, :west
