#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |a s      S     w  a      w C  C   S     S          S sC s   aS a C C          C         C    SC  w >   w       C      S              w S w   a             w          s     C S       SS   w S  w   C  S w     S   C  w S  S  Caa   sw   s   C Cs     S      aas         aS   C     S    s   C     S     CC        aw     s  aC  C    S      C       C   a  a         S   C    w  S  a  C w   Sw      sw     aw C sS    C a           C w  aa S w           s   w  a wa S            s  aS    C s            C    S SC           aSC  @    S    a  S  s    s s S    S   s     S  C CS  s Cs     wa         C w       a s  S       C    s   S          Ss    SCC a  a      a       Cw a  aS  sCa    w  a          s S        w   sC    w C   s        w       S    S    C  a  C s       S C ws      S  CS   a  a a s     CsCCS  w  a   C  |
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 809
ace_score 4045
size 809, 1
stairs 99, 0

warrior 518, 0, :east

unit :archer, 0, 0, :east
unit :sludge, 2, 0, :east
unit :thick_sludge, 9, 0, :east
unit :wizard, 15, 0, :east
unit :archer, 18, 0, :east
unit :wizard, 25, 0, :east
unit :captive, 27, 0, :east
unit :captive, 30, 0, :east
unit :thick_sludge, 34, 0, :east
unit :thick_sludge, 40, 0, :east
unit :thick_sludge, 51, 0, :east
unit :sludge, 53, 0, :east
unit :captive, 54, 0, :east
unit :sludge, 56, 0, :east
unit :archer, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :archer, 63, 0, :east
unit :captive, 65, 0, :east
unit :captive, 67, 0, :east
unit :captive, 78, 0, :east
unit :captive, 88, 0, :east
unit :thick_sludge, 93, 0, :east
unit :captive, 94, 0, :east
unit :wizard, 97, 0, :east
unit :wizard, 103, 0, :east
unit :captive, 111, 0, :east
unit :thick_sludge, 118, 0, :east
unit :wizard, 133, 0, :east
unit :thick_sludge, 135, 0, :east
unit :wizard, 137, 0, :east
unit :archer, 141, 0, :east
unit :wizard, 155, 0, :east
unit :sludge, 166, 0, :east
unit :captive, 172, 0, :east
unit :thick_sludge, 174, 0, :east
unit :thick_sludge, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :wizard, 187, 0, :east
unit :thick_sludge, 189, 0, :east
unit :wizard, 192, 0, :east
unit :captive, 196, 0, :east
unit :thick_sludge, 199, 0, :east
unit :wizard, 201, 0, :east
unit :thick_sludge, 207, 0, :east
unit :captive, 211, 0, :east
unit :wizard, 214, 0, :east
unit :thick_sludge, 216, 0, :east
unit :thick_sludge, 219, 0, :east
unit :captive, 222, 0, :east
unit :archer, 223, 0, :east
unit :archer, 224, 0, :east
unit :sludge, 228, 0, :east
unit :wizard, 229, 0, :east
unit :sludge, 233, 0, :east
unit :captive, 237, 0, :east
unit :captive, 239, 0, :east
unit :sludge, 240, 0, :east
unit :thick_sludge, 246, 0, :east
unit :archer, 253, 0, :east
unit :archer, 254, 0, :east
unit :sludge, 255, 0, :east
unit :archer, 265, 0, :east
unit :thick_sludge, 266, 0, :east
unit :captive, 270, 0, :east
unit :thick_sludge, 276, 0, :east
unit :sludge, 281, 0, :east
unit :captive, 285, 0, :east
unit :thick_sludge, 291, 0, :east
unit :captive, 297, 0, :east
unit :captive, 298, 0, :east
unit :archer, 307, 0, :east
unit :wizard, 308, 0, :east
unit :sludge, 314, 0, :east
unit :archer, 317, 0, :east
unit :captive, 318, 0, :east
unit :captive, 321, 0, :east
unit :thick_sludge, 326, 0, :east
unit :captive, 333, 0, :east
unit :captive, 341, 0, :east
unit :archer, 345, 0, :east
unit :archer, 348, 0, :east
unit :thick_sludge, 358, 0, :east
unit :captive, 362, 0, :east
unit :wizard, 367, 0, :east
unit :thick_sludge, 370, 0, :east
unit :archer, 373, 0, :east
unit :captive, 376, 0, :east
unit :wizard, 378, 0, :east
unit :thick_sludge, 382, 0, :east
unit :wizard, 383, 0, :east
unit :sludge, 390, 0, :east
unit :wizard, 391, 0, :east
unit :archer, 397, 0, :east
unit :wizard, 398, 0, :east
unit :captive, 400, 0, :east
unit :sludge, 402, 0, :east
unit :thick_sludge, 403, 0, :east
unit :captive, 408, 0, :east
unit :archer, 410, 0, :east
unit :captive, 422, 0, :east
unit :wizard, 424, 0, :east
unit :archer, 427, 0, :east
unit :archer, 428, 0, :east
unit :thick_sludge, 430, 0, :east
unit :wizard, 432, 0, :east
unit :sludge, 444, 0, :east
unit :wizard, 448, 0, :east
unit :archer, 451, 0, :east
unit :wizard, 453, 0, :east
unit :archer, 454, 0, :east
unit :thick_sludge, 456, 0, :east
unit :sludge, 469, 0, :east
unit :archer, 472, 0, :east
unit :thick_sludge, 473, 0, :east
unit :captive, 478, 0, :east
unit :sludge, 480, 0, :east
unit :captive, 493, 0, :east
unit :thick_sludge, 498, 0, :east
unit :thick_sludge, 500, 0, :east
unit :captive, 501, 0, :east
unit :archer, 513, 0, :east
unit :thick_sludge, 514, 0, :east
unit :captive, 515, 0, :east
unit :thick_sludge, 523, 0, :west
unit :archer, 528, 0, :west
unit :thick_sludge, 531, 0, :west
unit :sludge, 534, 0, :west
unit :sludge, 539, 0, :west
unit :sludge, 541, 0, :west
unit :thick_sludge, 543, 0, :west
unit :thick_sludge, 548, 0, :west
unit :sludge, 552, 0, :west
unit :thick_sludge, 558, 0, :west
unit :captive, 561, 0, :west
unit :captive, 563, 0, :west
unit :thick_sludge, 564, 0, :west
unit :sludge, 567, 0, :west
unit :captive, 569, 0, :west
unit :sludge, 570, 0, :west
unit :wizard, 576, 0, :west
unit :archer, 577, 0, :west
unit :captive, 587, 0, :west
unit :wizard, 589, 0, :west
unit :archer, 597, 0, :west
unit :sludge, 599, 0, :west
unit :thick_sludge, 602, 0, :west
unit :captive, 610, 0, :west
unit :sludge, 615, 0, :west
unit :thick_sludge, 619, 0, :west
unit :thick_sludge, 630, 0, :west
unit :sludge, 631, 0, :west
unit :thick_sludge, 636, 0, :west
unit :captive, 637, 0, :west
unit :captive, 638, 0, :west
unit :archer, 640, 0, :west
unit :archer, 643, 0, :west
unit :archer, 650, 0, :west
unit :captive, 658, 0, :west
unit :wizard, 659, 0, :west
unit :archer, 661, 0, :west
unit :archer, 664, 0, :west
unit :thick_sludge, 665, 0, :west
unit :sludge, 668, 0, :west
unit :captive, 669, 0, :west
unit :archer, 670, 0, :west
unit :wizard, 675, 0, :west
unit :archer, 678, 0, :west
unit :sludge, 689, 0, :west
unit :thick_sludge, 691, 0, :west
unit :wizard, 700, 0, :west
unit :sludge, 704, 0, :west
unit :captive, 705, 0, :west
unit :wizard, 710, 0, :west
unit :captive, 712, 0, :west
unit :sludge, 716, 0, :west
unit :wizard, 725, 0, :west
unit :thick_sludge, 733, 0, :west
unit :thick_sludge, 738, 0, :west
unit :captive, 743, 0, :west
unit :archer, 746, 0, :west
unit :captive, 749, 0, :west
unit :sludge, 751, 0, :west
unit :thick_sludge, 759, 0, :west
unit :captive, 761, 0, :west
unit :wizard, 763, 0, :west
unit :sludge, 764, 0, :west
unit :thick_sludge, 771, 0, :west
unit :captive, 774, 0, :west
unit :thick_sludge, 775, 0, :west
unit :archer, 779, 0, :west
unit :archer, 782, 0, :west
unit :archer, 784, 0, :west
unit :sludge, 786, 0, :west
unit :captive, 792, 0, :west
unit :sludge, 793, 0, :west
unit :captive, 794, 0, :west
unit :captive, 795, 0, :west
unit :thick_sludge, 796, 0, :west
unit :wizard, 799, 0, :west
unit :archer, 802, 0, :west
unit :captive, 806, 0, :west
