#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | S  sS  a  s      C s        C a      w       asaC w  aC   @          ss  s  a s  Cs     C  s s w        a     s  a    a  S Cs   S S        w C S  a   ss     s  w  w  w Cw        C  ss  Sa   w   Sa     as Ca       s    s    sw  s sS  aS  S     a  a  C    S   a       s     w     S a          S          w   sa   s      a      C          a        S    S a      C  s aS s    >       s Cw    ws   w     sa      S C     S    s    w S     Cw C     sCC  S    S              s C s  a S       C s s    C SS      C    w      as               a w    a       w S     wa  s     CC    S a          |
#  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 585
ace_score 2925
size 585, 1
stairs 373, 0

warrior 59, 0, :east

unit :thick_sludge, 1, 0, :east
unit :sludge, 4, 0, :east
unit :thick_sludge, 5, 0, :east
unit :archer, 8, 0, :east
unit :sludge, 11, 0, :east
unit :captive, 18, 0, :east
unit :sludge, 20, 0, :east
unit :captive, 29, 0, :east
unit :archer, 31, 0, :east
unit :wizard, 38, 0, :east
unit :archer, 46, 0, :east
unit :sludge, 47, 0, :east
unit :archer, 48, 0, :east
unit :captive, 49, 0, :east
unit :wizard, 51, 0, :east
unit :archer, 54, 0, :east
unit :captive, 55, 0, :east
unit :sludge, 70, 0, :west
unit :sludge, 71, 0, :west
unit :sludge, 74, 0, :west
unit :archer, 77, 0, :west
unit :sludge, 79, 0, :west
unit :captive, 82, 0, :west
unit :sludge, 83, 0, :west
unit :captive, 89, 0, :west
unit :sludge, 92, 0, :west
unit :sludge, 94, 0, :west
unit :wizard, 96, 0, :west
unit :archer, 105, 0, :west
unit :sludge, 111, 0, :west
unit :archer, 114, 0, :west
unit :archer, 119, 0, :west
unit :thick_sludge, 122, 0, :west
unit :captive, 124, 0, :west
unit :sludge, 125, 0, :west
unit :thick_sludge, 129, 0, :west
unit :thick_sludge, 131, 0, :west
unit :wizard, 140, 0, :west
unit :captive, 142, 0, :west
unit :thick_sludge, 144, 0, :west
unit :archer, 147, 0, :west
unit :sludge, 151, 0, :west
unit :sludge, 152, 0, :west
unit :sludge, 158, 0, :west
unit :wizard, 161, 0, :west
unit :wizard, 164, 0, :west
unit :wizard, 167, 0, :west
unit :captive, 169, 0, :west
unit :wizard, 170, 0, :west
unit :captive, 179, 0, :west
unit :sludge, 182, 0, :west
unit :sludge, 183, 0, :west
unit :thick_sludge, 186, 0, :west
unit :archer, 187, 0, :west
unit :wizard, 191, 0, :west
unit :thick_sludge, 195, 0, :west
unit :archer, 196, 0, :west
unit :archer, 202, 0, :west
unit :sludge, 203, 0, :west
unit :captive, 205, 0, :west
unit :archer, 206, 0, :west
unit :sludge, 214, 0, :west
unit :sludge, 219, 0, :west
unit :sludge, 224, 0, :west
unit :wizard, 225, 0, :west
unit :sludge, 228, 0, :west
unit :sludge, 230, 0, :west
unit :thick_sludge, 231, 0, :west
unit :archer, 234, 0, :west
unit :thick_sludge, 235, 0, :west
unit :thick_sludge, 238, 0, :west
unit :archer, 244, 0, :west
unit :archer, 247, 0, :west
unit :captive, 250, 0, :west
unit :thick_sludge, 255, 0, :west
unit :archer, 259, 0, :west
unit :sludge, 267, 0, :west
unit :wizard, 273, 0, :west
unit :thick_sludge, 279, 0, :west
unit :archer, 281, 0, :west
unit :thick_sludge, 292, 0, :west
unit :wizard, 303, 0, :west
unit :sludge, 307, 0, :west
unit :archer, 308, 0, :west
unit :sludge, 312, 0, :west
unit :archer, 319, 0, :west
unit :captive, 326, 0, :west
unit :archer, 337, 0, :west
unit :thick_sludge, 346, 0, :west
unit :thick_sludge, 351, 0, :west
unit :archer, 353, 0, :west
unit :captive, 360, 0, :west
unit :sludge, 363, 0, :west
unit :archer, 365, 0, :west
unit :thick_sludge, 366, 0, :west
unit :sludge, 368, 0, :west
unit :sludge, 381, 0, :west
unit :captive, 383, 0, :west
unit :wizard, 384, 0, :west
unit :wizard, 389, 0, :west
unit :sludge, 390, 0, :west
unit :wizard, 394, 0, :west
unit :sludge, 400, 0, :west
unit :archer, 401, 0, :west
unit :thick_sludge, 408, 0, :west
unit :captive, 410, 0, :west
unit :thick_sludge, 416, 0, :west
unit :sludge, 421, 0, :west
unit :wizard, 426, 0, :west
unit :thick_sludge, 428, 0, :west
unit :captive, 434, 0, :west
unit :wizard, 435, 0, :west
unit :captive, 437, 0, :west
unit :sludge, 443, 0, :west
unit :captive, 444, 0, :west
unit :captive, 445, 0, :west
unit :thick_sludge, 448, 0, :west
unit :thick_sludge, 453, 0, :west
unit :sludge, 468, 0, :west
unit :captive, 470, 0, :west
unit :sludge, 472, 0, :west
unit :archer, 475, 0, :west
unit :thick_sludge, 477, 0, :west
unit :captive, 485, 0, :west
unit :sludge, 487, 0, :west
unit :sludge, 489, 0, :west
unit :captive, 494, 0, :west
unit :thick_sludge, 496, 0, :west
unit :thick_sludge, 497, 0, :west
unit :captive, 504, 0, :west
unit :wizard, 509, 0, :west
unit :archer, 516, 0, :west
unit :sludge, 517, 0, :west
unit :archer, 533, 0, :west
unit :wizard, 535, 0, :west
unit :archer, 540, 0, :west
unit :wizard, 548, 0, :west
unit :thick_sludge, 550, 0, :west
unit :wizard, 556, 0, :west
unit :archer, 557, 0, :west
unit :sludge, 560, 0, :west
unit :captive, 566, 0, :west
unit :captive, 567, 0, :west
unit :thick_sludge, 572, 0, :west
unit :archer, 574, 0, :west
