#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |    S    S            sS        s > C s   C aa  s  w     S  CS s       a Sw   s wCC  Ca a         s    S    a  C aS  S         w Sw  w C           a  a                   w  s   CS    w SS   C  aC     s   s        C   S     S   a w    w a s     s    sS a C  @   a   sC w     a      s        w sa   a  C  w   s     w   CC     s  s     C     C S s   C          sa a s w C    s  a   s w          C   w        a   C        w w   C S         C    S    C   S   a    s S      SCCS    C C    CC  ws   s    CCw   C  S         Sw     S sa        a   C        w S   S  a      s     a     w    C    a    wa      s awa       a  a  a SS         as  a  w      w Cs          S     |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 664
ace_score 3320
size 664, 1
stairs 34, 0

warrior 257, 0, :east

unit :thick_sludge, 4, 0, :east
unit :thick_sludge, 9, 0, :east
unit :sludge, 22, 0, :east
unit :thick_sludge, 23, 0, :east
unit :sludge, 32, 0, :east
unit :captive, 36, 0, :east
unit :sludge, 38, 0, :east
unit :captive, 42, 0, :east
unit :archer, 44, 0, :east
unit :archer, 45, 0, :east
unit :sludge, 48, 0, :east
unit :wizard, 51, 0, :east
unit :thick_sludge, 57, 0, :east
unit :captive, 60, 0, :east
unit :thick_sludge, 61, 0, :east
unit :sludge, 63, 0, :east
unit :archer, 71, 0, :east
unit :thick_sludge, 73, 0, :east
unit :wizard, 74, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 80, 0, :east
unit :captive, 81, 0, :east
unit :captive, 82, 0, :east
unit :captive, 85, 0, :east
unit :archer, 86, 0, :east
unit :archer, 88, 0, :east
unit :sludge, 98, 0, :east
unit :thick_sludge, 103, 0, :east
unit :archer, 108, 0, :east
unit :captive, 111, 0, :east
unit :archer, 113, 0, :east
unit :thick_sludge, 114, 0, :east
unit :thick_sludge, 117, 0, :east
unit :wizard, 127, 0, :east
unit :thick_sludge, 129, 0, :east
unit :wizard, 130, 0, :east
unit :wizard, 133, 0, :east
unit :captive, 135, 0, :east
unit :archer, 147, 0, :east
unit :archer, 150, 0, :east
unit :wizard, 170, 0, :east
unit :sludge, 173, 0, :east
unit :captive, 177, 0, :east
unit :thick_sludge, 178, 0, :east
unit :wizard, 183, 0, :east
unit :thick_sludge, 185, 0, :east
unit :thick_sludge, 186, 0, :east
unit :captive, 190, 0, :east
unit :archer, 193, 0, :east
unit :captive, 194, 0, :east
unit :sludge, 200, 0, :east
unit :sludge, 204, 0, :east
unit :captive, 213, 0, :east
unit :thick_sludge, 217, 0, :east
unit :thick_sludge, 223, 0, :east
unit :archer, 227, 0, :east
unit :wizard, 229, 0, :east
unit :wizard, 234, 0, :east
unit :archer, 236, 0, :east
unit :sludge, 238, 0, :east
unit :sludge, 244, 0, :east
unit :sludge, 249, 0, :east
unit :thick_sludge, 250, 0, :east
unit :archer, 252, 0, :east
unit :captive, 254, 0, :east
unit :archer, 261, 0, :west
unit :sludge, 265, 0, :west
unit :captive, 266, 0, :west
unit :wizard, 268, 0, :west
unit :archer, 274, 0, :west
unit :sludge, 281, 0, :west
unit :wizard, 290, 0, :west
unit :sludge, 292, 0, :west
unit :archer, 293, 0, :west
unit :archer, 297, 0, :west
unit :captive, 300, 0, :west
unit :wizard, 303, 0, :west
unit :sludge, 307, 0, :west
unit :wizard, 313, 0, :west
unit :captive, 317, 0, :west
unit :captive, 318, 0, :west
unit :sludge, 324, 0, :west
unit :sludge, 327, 0, :west
unit :captive, 333, 0, :west
unit :captive, 339, 0, :west
unit :thick_sludge, 341, 0, :west
unit :sludge, 343, 0, :west
unit :captive, 347, 0, :west
unit :sludge, 358, 0, :west
unit :archer, 359, 0, :west
unit :archer, 361, 0, :west
unit :sludge, 363, 0, :west
unit :wizard, 365, 0, :west
unit :captive, 367, 0, :west
unit :sludge, 372, 0, :west
unit :archer, 375, 0, :west
unit :sludge, 379, 0, :west
unit :wizard, 381, 0, :west
unit :captive, 392, 0, :west
unit :wizard, 396, 0, :west
unit :archer, 405, 0, :west
unit :captive, 409, 0, :west
unit :wizard, 418, 0, :west
unit :wizard, 420, 0, :west
unit :captive, 424, 0, :west
unit :thick_sludge, 426, 0, :west
unit :captive, 436, 0, :west
unit :thick_sludge, 441, 0, :west
unit :captive, 446, 0, :west
unit :thick_sludge, 450, 0, :west
unit :archer, 454, 0, :west
unit :sludge, 459, 0, :west
unit :thick_sludge, 461, 0, :west
unit :thick_sludge, 468, 0, :west
unit :captive, 469, 0, :west
unit :captive, 470, 0, :west
unit :thick_sludge, 471, 0, :west
unit :captive, 476, 0, :west
unit :captive, 478, 0, :west
unit :captive, 483, 0, :west
unit :captive, 484, 0, :west
unit :wizard, 487, 0, :west
unit :sludge, 488, 0, :west
unit :sludge, 492, 0, :west
unit :captive, 497, 0, :west
unit :captive, 498, 0, :west
unit :wizard, 499, 0, :west
unit :captive, 503, 0, :west
unit :thick_sludge, 506, 0, :west
unit :thick_sludge, 516, 0, :west
unit :wizard, 517, 0, :west
unit :thick_sludge, 523, 0, :west
unit :sludge, 525, 0, :west
unit :archer, 526, 0, :west
unit :archer, 535, 0, :west
unit :captive, 539, 0, :west
unit :wizard, 548, 0, :west
unit :thick_sludge, 550, 0, :west
unit :thick_sludge, 554, 0, :west
unit :archer, 557, 0, :west
unit :sludge, 564, 0, :west
unit :archer, 570, 0, :west
unit :wizard, 576, 0, :west
unit :captive, 581, 0, :west
unit :archer, 586, 0, :west
unit :wizard, 591, 0, :west
unit :archer, 592, 0, :west
unit :sludge, 599, 0, :west
unit :archer, 601, 0, :west
unit :wizard, 602, 0, :west
unit :archer, 603, 0, :west
unit :archer, 611, 0, :west
unit :archer, 614, 0, :west
unit :archer, 617, 0, :west
unit :thick_sludge, 619, 0, :west
unit :thick_sludge, 620, 0, :west
unit :archer, 630, 0, :west
unit :sludge, 631, 0, :west
unit :archer, 634, 0, :west
unit :wizard, 637, 0, :west
unit :wizard, 644, 0, :west
unit :captive, 646, 0, :west
unit :sludge, 647, 0, :west
unit :thick_sludge, 658, 0, :west
