#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# | C a w     ss      S C  Ca  w  aw  S      C  Cs             w  wSs    sa   S ss     w          S S      s C w    w  s w      S    s    S   s  S S          s   w   a   Ss       aS   a         C    S  C C     Ca s      s     w              a C           C    wC        SC     S       C Sa  w  a   ss     a       SS w     s      s ws a S   a       C  sS    s   w  @  a w   sC   Cs     wS  s  C   C SS   C     a        C S  aC s  SC  >   s             s     ws            w        C  s         ws     C  C aCC S  S a   S Cw   a S  w  a   Ss     CS    S     aS         C S     w         wa   C         C  C  sC    w       sCs        C|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 629
ace_score 3145
size 629, 1
stairs 430, 0

warrior 361, 0, :east

unit :captive, 1, 0, :east
unit :archer, 3, 0, :east
unit :wizard, 5, 0, :east
unit :sludge, 11, 0, :east
unit :sludge, 12, 0, :east
unit :thick_sludge, 19, 0, :east
unit :captive, 21, 0, :east
unit :captive, 24, 0, :east
unit :archer, 25, 0, :east
unit :wizard, 28, 0, :east
unit :archer, 31, 0, :east
unit :wizard, 32, 0, :east
unit :thick_sludge, 35, 0, :east
unit :captive, 42, 0, :east
unit :captive, 45, 0, :east
unit :sludge, 46, 0, :east
unit :wizard, 60, 0, :east
unit :wizard, 63, 0, :east
unit :thick_sludge, 64, 0, :east
unit :sludge, 65, 0, :east
unit :sludge, 70, 0, :east
unit :archer, 71, 0, :east
unit :thick_sludge, 75, 0, :east
unit :sludge, 77, 0, :east
unit :sludge, 78, 0, :east
unit :wizard, 84, 0, :east
unit :thick_sludge, 95, 0, :east
unit :thick_sludge, 97, 0, :east
unit :sludge, 104, 0, :east
unit :captive, 106, 0, :east
unit :wizard, 108, 0, :east
unit :wizard, 113, 0, :east
unit :sludge, 116, 0, :east
unit :wizard, 118, 0, :east
unit :thick_sludge, 125, 0, :east
unit :sludge, 130, 0, :east
unit :thick_sludge, 135, 0, :east
unit :sludge, 139, 0, :east
unit :thick_sludge, 142, 0, :east
unit :thick_sludge, 144, 0, :east
unit :sludge, 155, 0, :east
unit :wizard, 159, 0, :east
unit :archer, 163, 0, :east
unit :thick_sludge, 167, 0, :east
unit :sludge, 168, 0, :east
unit :archer, 176, 0, :east
unit :thick_sludge, 177, 0, :east
unit :archer, 181, 0, :east
unit :captive, 191, 0, :east
unit :thick_sludge, 196, 0, :east
unit :captive, 199, 0, :east
unit :captive, 201, 0, :east
unit :captive, 207, 0, :east
unit :archer, 208, 0, :east
unit :sludge, 210, 0, :east
unit :sludge, 217, 0, :east
unit :wizard, 223, 0, :east
unit :archer, 238, 0, :east
unit :captive, 240, 0, :east
unit :captive, 252, 0, :east
unit :wizard, 257, 0, :east
unit :captive, 258, 0, :east
unit :thick_sludge, 267, 0, :east
unit :captive, 268, 0, :east
unit :thick_sludge, 274, 0, :east
unit :captive, 282, 0, :east
unit :thick_sludge, 284, 0, :east
unit :archer, 285, 0, :east
unit :wizard, 288, 0, :east
unit :archer, 291, 0, :east
unit :sludge, 295, 0, :east
unit :sludge, 296, 0, :east
unit :archer, 302, 0, :east
unit :thick_sludge, 310, 0, :east
unit :thick_sludge, 311, 0, :east
unit :wizard, 313, 0, :east
unit :sludge, 319, 0, :east
unit :sludge, 326, 0, :east
unit :wizard, 328, 0, :east
unit :sludge, 329, 0, :east
unit :archer, 331, 0, :east
unit :thick_sludge, 333, 0, :east
unit :archer, 337, 0, :east
unit :captive, 345, 0, :east
unit :sludge, 348, 0, :east
unit :thick_sludge, 349, 0, :east
unit :sludge, 354, 0, :east
unit :wizard, 358, 0, :east
unit :archer, 364, 0, :west
unit :wizard, 366, 0, :west
unit :sludge, 370, 0, :west
unit :captive, 371, 0, :west
unit :captive, 375, 0, :west
unit :sludge, 376, 0, :west
unit :wizard, 382, 0, :west
unit :thick_sludge, 383, 0, :west
unit :sludge, 386, 0, :west
unit :captive, 389, 0, :west
unit :captive, 393, 0, :west
unit :thick_sludge, 395, 0, :west
unit :thick_sludge, 396, 0, :west
unit :captive, 400, 0, :west
unit :archer, 406, 0, :west
unit :captive, 415, 0, :west
unit :thick_sludge, 417, 0, :west
unit :archer, 420, 0, :west
unit :captive, 421, 0, :west
unit :sludge, 423, 0, :west
unit :thick_sludge, 426, 0, :west
unit :captive, 427, 0, :west
unit :sludge, 434, 0, :west
unit :sludge, 448, 0, :west
unit :wizard, 454, 0, :west
unit :sludge, 455, 0, :west
unit :wizard, 468, 0, :west
unit :captive, 477, 0, :west
unit :sludge, 480, 0, :west
unit :wizard, 490, 0, :west
unit :sludge, 491, 0, :west
unit :captive, 497, 0, :west
unit :captive, 500, 0, :west
unit :archer, 502, 0, :west
unit :captive, 503, 0, :west
unit :captive, 504, 0, :west
unit :thick_sludge, 506, 0, :west
unit :thick_sludge, 509, 0, :west
unit :archer, 511, 0, :west
unit :thick_sludge, 515, 0, :west
unit :captive, 517, 0, :west
unit :wizard, 518, 0, :west
unit :archer, 522, 0, :west
unit :thick_sludge, 524, 0, :west
unit :wizard, 527, 0, :west
unit :archer, 530, 0, :west
unit :thick_sludge, 534, 0, :west
unit :sludge, 535, 0, :west
unit :captive, 541, 0, :west
unit :thick_sludge, 542, 0, :west
unit :thick_sludge, 547, 0, :west
unit :archer, 553, 0, :west
unit :thick_sludge, 554, 0, :west
unit :captive, 564, 0, :west
unit :thick_sludge, 566, 0, :west
unit :wizard, 572, 0, :west
unit :wizard, 582, 0, :west
unit :archer, 583, 0, :west
unit :captive, 587, 0, :west
unit :captive, 597, 0, :west
unit :captive, 600, 0, :west
unit :sludge, 603, 0, :west
unit :captive, 604, 0, :west
unit :wizard, 609, 0, :west
unit :sludge, 617, 0, :west
unit :captive, 618, 0, :west
unit :sludge, 619, 0, :west
unit :captive, 628, 0, :west
