#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |a    SS   w  S  a w    aCs   S S           s C  S s     C saS w   a S  w  s        S     SC  C w  wC       a  C    Sa  s   s w  w ssS C  Sss Ssa        a wS    a     SS        w      C   a w   S          s sC           @   s             wa       sC       C    w   w  w sw    S C  w          w   a     a  a     C     a  a sC   a    C         S s  C    S  aS    w     S  CS   s  a     s  S             sa    a   SS        S  a  a w                   C  a          s  S s aS a    a   w w a      > Sa  a       s    was      C  w S       S S    a    S   S     S      CsC  s S  C    a        S C         S     w  S  w Cw      S            a   C    S      w    w      w    CC   Caa|
#  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 674
ace_score 3370
size 674, 1
stairs 492, 0

warrior 219, 0, :east

unit :archer, 0, 0, :east
unit :thick_sludge, 5, 0, :east
unit :thick_sludge, 6, 0, :east
unit :wizard, 10, 0, :east
unit :thick_sludge, 13, 0, :east
unit :archer, 16, 0, :east
unit :wizard, 18, 0, :east
unit :archer, 23, 0, :east
unit :captive, 24, 0, :east
unit :sludge, 25, 0, :east
unit :thick_sludge, 29, 0, :east
unit :thick_sludge, 31, 0, :east
unit :sludge, 43, 0, :east
unit :captive, 45, 0, :east
unit :thick_sludge, 48, 0, :east
unit :sludge, 50, 0, :east
unit :captive, 56, 0, :east
unit :sludge, 58, 0, :east
unit :archer, 59, 0, :east
unit :thick_sludge, 60, 0, :east
unit :wizard, 62, 0, :east
unit :archer, 66, 0, :east
unit :thick_sludge, 68, 0, :east
unit :wizard, 71, 0, :east
unit :sludge, 74, 0, :east
unit :thick_sludge, 83, 0, :east
unit :thick_sludge, 89, 0, :east
unit :captive, 90, 0, :east
unit :captive, 93, 0, :east
unit :wizard, 95, 0, :east
unit :wizard, 98, 0, :east
unit :captive, 99, 0, :east
unit :archer, 107, 0, :east
unit :captive, 110, 0, :east
unit :thick_sludge, 115, 0, :east
unit :archer, 116, 0, :east
unit :sludge, 119, 0, :east
unit :sludge, 123, 0, :east
unit :wizard, 125, 0, :east
unit :wizard, 128, 0, :east
unit :sludge, 130, 0, :east
unit :sludge, 131, 0, :east
unit :thick_sludge, 132, 0, :east
unit :captive, 134, 0, :east
unit :thick_sludge, 137, 0, :east
unit :sludge, 138, 0, :east
unit :sludge, 139, 0, :east
unit :thick_sludge, 141, 0, :east
unit :sludge, 142, 0, :east
unit :archer, 143, 0, :east
unit :archer, 152, 0, :east
unit :wizard, 154, 0, :east
unit :thick_sludge, 155, 0, :east
unit :archer, 160, 0, :east
unit :thick_sludge, 166, 0, :east
unit :thick_sludge, 167, 0, :east
unit :wizard, 176, 0, :east
unit :captive, 183, 0, :east
unit :archer, 187, 0, :east
unit :wizard, 189, 0, :east
unit :thick_sludge, 193, 0, :east
unit :sludge, 204, 0, :east
unit :sludge, 206, 0, :east
unit :captive, 207, 0, :east
unit :sludge, 223, 0, :west
unit :wizard, 237, 0, :west
unit :archer, 238, 0, :west
unit :sludge, 246, 0, :west
unit :captive, 247, 0, :west
unit :captive, 255, 0, :west
unit :wizard, 260, 0, :west
unit :wizard, 264, 0, :west
unit :wizard, 267, 0, :west
unit :sludge, 269, 0, :west
unit :wizard, 270, 0, :west
unit :thick_sludge, 275, 0, :west
unit :captive, 277, 0, :west
unit :wizard, 280, 0, :west
unit :wizard, 291, 0, :west
unit :archer, 295, 0, :west
unit :archer, 301, 0, :west
unit :archer, 304, 0, :west
unit :captive, 310, 0, :west
unit :archer, 316, 0, :west
unit :archer, 319, 0, :west
unit :sludge, 321, 0, :west
unit :captive, 322, 0, :west
unit :archer, 326, 0, :west
unit :captive, 331, 0, :west
unit :thick_sludge, 341, 0, :west
unit :sludge, 343, 0, :west
unit :captive, 346, 0, :west
unit :thick_sludge, 351, 0, :west
unit :archer, 354, 0, :west
unit :thick_sludge, 355, 0, :west
unit :wizard, 360, 0, :west
unit :thick_sludge, 366, 0, :west
unit :captive, 369, 0, :west
unit :thick_sludge, 370, 0, :west
unit :sludge, 374, 0, :west
unit :archer, 377, 0, :west
unit :sludge, 383, 0, :west
unit :thick_sludge, 386, 0, :west
unit :sludge, 400, 0, :west
unit :archer, 401, 0, :west
unit :archer, 406, 0, :west
unit :thick_sludge, 410, 0, :west
unit :thick_sludge, 411, 0, :west
unit :thick_sludge, 420, 0, :west
unit :archer, 423, 0, :west
unit :archer, 426, 0, :west
unit :wizard, 428, 0, :west
unit :captive, 448, 0, :west
unit :archer, 451, 0, :west
unit :sludge, 462, 0, :west
unit :thick_sludge, 465, 0, :west
unit :sludge, 467, 0, :west
unit :archer, 469, 0, :west
unit :thick_sludge, 470, 0, :west
unit :archer, 472, 0, :west
unit :archer, 477, 0, :west
unit :wizard, 481, 0, :west
unit :wizard, 483, 0, :west
unit :archer, 485, 0, :west
unit :thick_sludge, 494, 0, :west
unit :archer, 495, 0, :west
unit :archer, 498, 0, :west
unit :sludge, 506, 0, :west
unit :wizard, 511, 0, :west
unit :archer, 512, 0, :west
unit :sludge, 513, 0, :west
unit :captive, 520, 0, :west
unit :wizard, 523, 0, :west
unit :thick_sludge, 525, 0, :west
unit :thick_sludge, 533, 0, :west
unit :thick_sludge, 535, 0, :west
unit :archer, 540, 0, :west
unit :thick_sludge, 545, 0, :west
unit :thick_sludge, 549, 0, :west
unit :thick_sludge, 555, 0, :west
unit :captive, 562, 0, :west
unit :sludge, 563, 0, :west
unit :captive, 564, 0, :west
unit :sludge, 567, 0, :west
unit :thick_sludge, 569, 0, :west
unit :captive, 572, 0, :west
unit :archer, 577, 0, :west
unit :thick_sludge, 586, 0, :west
unit :captive, 588, 0, :west
unit :thick_sludge, 598, 0, :west
unit :wizard, 604, 0, :west
unit :thick_sludge, 607, 0, :west
unit :wizard, 610, 0, :west
unit :captive, 612, 0, :west
unit :wizard, 613, 0, :west
unit :thick_sludge, 620, 0, :west
unit :archer, 633, 0, :west
unit :captive, 637, 0, :west
unit :thick_sludge, 642, 0, :west
unit :wizard, 649, 0, :west
unit :wizard, 654, 0, :west
unit :wizard, 661, 0, :west
unit :captive, 666, 0, :west
unit :captive, 667, 0, :west
unit :captive, 671, 0, :west
unit :archer, 672, 0, :west
unit :archer, 673, 0, :west
