#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |   SSC    s          sa      w   a a s                S a       S    S S C w     a   s         Sa S  w  C C     C        sS s    S          s          SC   w s    C   Sa    w                S  w SSa  S      S   C    a  Sa  a    S  wsC    a   S  S          w> s  S  C  w     w  Cs  S C    @  C   w   w w      C   a w      C  S  a    s CC w C       s          Cwa   C  C         s S   w       S    Ca         as  S       w    C      aS  C a    C    SS s   w       CS  S     a SsSs    a s SsS  SS                 w  C S           s   s  CsS   s    w   S  s  S      s     sw a s CC  SS w   Sss     a   a    w     w       S   C            s|
#  -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 635
ace_score 3175
size 635, 1
stairs 257, 0

warrior 288, 0, :east

unit :thick_sludge, 3, 0, :east
unit :thick_sludge, 4, 0, :east
unit :captive, 5, 0, :east
unit :sludge, 10, 0, :east
unit :sludge, 21, 0, :east
unit :archer, 22, 0, :east
unit :wizard, 29, 0, :east
unit :archer, 33, 0, :east
unit :archer, 35, 0, :east
unit :sludge, 37, 0, :east
unit :thick_sludge, 54, 0, :east
unit :archer, 56, 0, :east
unit :thick_sludge, 64, 0, :east
unit :thick_sludge, 69, 0, :east
unit :thick_sludge, 71, 0, :east
unit :captive, 73, 0, :east
unit :wizard, 75, 0, :east
unit :archer, 81, 0, :east
unit :sludge, 85, 0, :east
unit :thick_sludge, 95, 0, :east
unit :archer, 96, 0, :east
unit :thick_sludge, 98, 0, :east
unit :wizard, 101, 0, :east
unit :captive, 104, 0, :east
unit :captive, 106, 0, :east
unit :captive, 112, 0, :east
unit :sludge, 121, 0, :east
unit :thick_sludge, 122, 0, :east
unit :sludge, 124, 0, :east
unit :thick_sludge, 129, 0, :east
unit :sludge, 140, 0, :east
unit :thick_sludge, 151, 0, :east
unit :captive, 152, 0, :east
unit :wizard, 156, 0, :east
unit :sludge, 158, 0, :east
unit :captive, 163, 0, :east
unit :thick_sludge, 167, 0, :east
unit :archer, 168, 0, :east
unit :wizard, 173, 0, :east
unit :thick_sludge, 190, 0, :east
unit :wizard, 193, 0, :east
unit :thick_sludge, 195, 0, :east
unit :thick_sludge, 196, 0, :east
unit :archer, 197, 0, :east
unit :thick_sludge, 200, 0, :east
unit :thick_sludge, 207, 0, :east
unit :captive, 211, 0, :east
unit :archer, 216, 0, :east
unit :thick_sludge, 219, 0, :east
unit :archer, 220, 0, :east
unit :archer, 223, 0, :east
unit :thick_sludge, 228, 0, :east
unit :wizard, 231, 0, :east
unit :sludge, 232, 0, :east
unit :captive, 233, 0, :east
unit :archer, 238, 0, :east
unit :thick_sludge, 242, 0, :east
unit :thick_sludge, 245, 0, :east
unit :wizard, 256, 0, :east
unit :sludge, 259, 0, :east
unit :thick_sludge, 262, 0, :east
unit :captive, 265, 0, :east
unit :wizard, 268, 0, :east
unit :wizard, 274, 0, :east
unit :captive, 277, 0, :east
unit :sludge, 278, 0, :east
unit :thick_sludge, 281, 0, :east
unit :captive, 283, 0, :east
unit :captive, 291, 0, :west
unit :wizard, 295, 0, :west
unit :wizard, 299, 0, :west
unit :wizard, 301, 0, :west
unit :captive, 308, 0, :west
unit :archer, 312, 0, :west
unit :wizard, 314, 0, :west
unit :captive, 321, 0, :west
unit :thick_sludge, 324, 0, :west
unit :archer, 327, 0, :west
unit :sludge, 332, 0, :west
unit :captive, 334, 0, :west
unit :captive, 335, 0, :west
unit :wizard, 337, 0, :west
unit :captive, 339, 0, :west
unit :sludge, 347, 0, :west
unit :captive, 358, 0, :west
unit :wizard, 359, 0, :west
unit :archer, 360, 0, :west
unit :captive, 364, 0, :west
unit :captive, 367, 0, :west
unit :sludge, 377, 0, :west
unit :thick_sludge, 379, 0, :west
unit :wizard, 383, 0, :west
unit :thick_sludge, 391, 0, :west
unit :captive, 396, 0, :west
unit :archer, 397, 0, :west
unit :archer, 407, 0, :west
unit :sludge, 408, 0, :west
unit :thick_sludge, 411, 0, :west
unit :wizard, 419, 0, :west
unit :captive, 424, 0, :west
unit :archer, 431, 0, :west
unit :thick_sludge, 432, 0, :west
unit :captive, 435, 0, :west
unit :archer, 437, 0, :west
unit :captive, 442, 0, :west
unit :thick_sludge, 447, 0, :west
unit :thick_sludge, 448, 0, :west
unit :sludge, 450, 0, :west
unit :wizard, 454, 0, :west
unit :captive, 462, 0, :west
unit :thick_sludge, 463, 0, :west
unit :thick_sludge, 466, 0, :west
unit :archer, 472, 0, :west
unit :thick_sludge, 474, 0, :west
unit :sludge, 475, 0, :west
unit :thick_sludge, 476, 0, :west
unit :sludge, 477, 0, :west
unit :archer, 482, 0, :west
unit :sludge, 484, 0, :west
unit :thick_sludge, 486, 0, :west
unit :sludge, 487, 0, :west
unit :thick_sludge, 488, 0, :west
unit :thick_sludge, 491, 0, :west
unit :thick_sludge, 492, 0, :west
unit :wizard, 510, 0, :west
unit :captive, 513, 0, :west
unit :thick_sludge, 515, 0, :west
unit :sludge, 527, 0, :west
unit :sludge, 531, 0, :west
unit :captive, 534, 0, :west
unit :sludge, 535, 0, :west
unit :thick_sludge, 536, 0, :west
unit :sludge, 540, 0, :west
unit :wizard, 545, 0, :west
unit :thick_sludge, 549, 0, :west
unit :sludge, 552, 0, :west
unit :thick_sludge, 555, 0, :west
unit :sludge, 562, 0, :west
unit :sludge, 568, 0, :west
unit :wizard, 569, 0, :west
unit :archer, 571, 0, :west
unit :sludge, 573, 0, :west
unit :captive, 575, 0, :west
unit :captive, 576, 0, :west
unit :thick_sludge, 579, 0, :west
unit :thick_sludge, 580, 0, :west
unit :wizard, 582, 0, :west
unit :thick_sludge, 586, 0, :west
unit :sludge, 587, 0, :west
unit :sludge, 588, 0, :west
unit :archer, 594, 0, :west
unit :archer, 598, 0, :west
unit :wizard, 603, 0, :west
unit :wizard, 609, 0, :west
unit :thick_sludge, 617, 0, :west
unit :captive, 621, 0, :west
unit :sludge, 634, 0, :west
