#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |C  w    CS               S S     w a  S   SaC  as      w   w    a S   w a SC  s       C     SS a s a  C    C    a Cs s   w    C     S   a      s >  aS    S        w       s     C  w sS   C   s   C   w w S s     S   w     S   s  @    a Cs         sS a  a  S  w    SSC     a a w          S      SS a  w  C C       C C sCw  s        CC      w   a          ss   C  s    a  w S     s  w w   w        wS     C   w  a    w           w   w   C    w  w w   a  wS                     s   a     a  CC          S   SCa a     S       aw  s   a  S  a       a    C    s aC    w   a C  a a            S   S      w   aa       a    w s  |
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 619
ace_score 3095
size 619, 1
stairs 145, 0

warrior 228, 0, :east

unit :captive, 0, 0, :east
unit :wizard, 3, 0, :east
unit :captive, 8, 0, :east
unit :thick_sludge, 9, 0, :east
unit :thick_sludge, 25, 0, :east
unit :thick_sludge, 27, 0, :east
unit :wizard, 33, 0, :east
unit :archer, 35, 0, :east
unit :thick_sludge, 38, 0, :east
unit :thick_sludge, 42, 0, :east
unit :archer, 43, 0, :east
unit :captive, 44, 0, :east
unit :archer, 47, 0, :east
unit :sludge, 48, 0, :east
unit :wizard, 55, 0, :east
unit :wizard, 59, 0, :east
unit :archer, 64, 0, :east
unit :thick_sludge, 66, 0, :east
unit :wizard, 70, 0, :east
unit :archer, 72, 0, :east
unit :thick_sludge, 74, 0, :east
unit :captive, 75, 0, :east
unit :sludge, 78, 0, :east
unit :captive, 86, 0, :east
unit :thick_sludge, 92, 0, :east
unit :thick_sludge, 93, 0, :east
unit :archer, 95, 0, :east
unit :sludge, 97, 0, :east
unit :archer, 99, 0, :east
unit :captive, 102, 0, :east
unit :captive, 107, 0, :east
unit :archer, 112, 0, :east
unit :captive, 114, 0, :east
unit :sludge, 115, 0, :east
unit :sludge, 117, 0, :east
unit :wizard, 121, 0, :east
unit :captive, 126, 0, :east
unit :thick_sludge, 132, 0, :east
unit :archer, 136, 0, :east
unit :sludge, 143, 0, :east
unit :archer, 148, 0, :east
unit :thick_sludge, 149, 0, :east
unit :thick_sludge, 154, 0, :east
unit :wizard, 163, 0, :east
unit :sludge, 171, 0, :east
unit :captive, 177, 0, :east
unit :wizard, 180, 0, :east
unit :sludge, 182, 0, :east
unit :thick_sludge, 183, 0, :east
unit :captive, 187, 0, :east
unit :sludge, 191, 0, :east
unit :captive, 195, 0, :east
unit :wizard, 199, 0, :east
unit :wizard, 201, 0, :east
unit :thick_sludge, 203, 0, :east
unit :sludge, 205, 0, :east
unit :thick_sludge, 211, 0, :east
unit :wizard, 215, 0, :east
unit :thick_sludge, 221, 0, :east
unit :sludge, 225, 0, :east
unit :archer, 233, 0, :west
unit :captive, 235, 0, :west
unit :sludge, 236, 0, :west
unit :sludge, 246, 0, :west
unit :thick_sludge, 247, 0, :west
unit :archer, 249, 0, :west
unit :archer, 252, 0, :west
unit :thick_sludge, 255, 0, :west
unit :wizard, 258, 0, :west
unit :thick_sludge, 263, 0, :west
unit :thick_sludge, 264, 0, :west
unit :captive, 265, 0, :west
unit :archer, 271, 0, :west
unit :archer, 273, 0, :west
unit :wizard, 275, 0, :west
unit :thick_sludge, 286, 0, :west
unit :thick_sludge, 293, 0, :west
unit :thick_sludge, 294, 0, :west
unit :archer, 296, 0, :west
unit :wizard, 299, 0, :west
unit :captive, 302, 0, :west
unit :captive, 304, 0, :west
unit :captive, 312, 0, :west
unit :captive, 314, 0, :west
unit :sludge, 316, 0, :west
unit :captive, 317, 0, :west
unit :wizard, 318, 0, :west
unit :sludge, 321, 0, :west
unit :captive, 330, 0, :west
unit :captive, 331, 0, :west
unit :wizard, 338, 0, :west
unit :archer, 342, 0, :west
unit :sludge, 353, 0, :west
unit :sludge, 354, 0, :west
unit :captive, 358, 0, :west
unit :sludge, 361, 0, :west
unit :archer, 366, 0, :west
unit :wizard, 369, 0, :west
unit :thick_sludge, 371, 0, :west
unit :sludge, 377, 0, :west
unit :wizard, 380, 0, :west
unit :wizard, 382, 0, :west
unit :wizard, 386, 0, :west
unit :wizard, 395, 0, :west
unit :thick_sludge, 396, 0, :west
unit :captive, 402, 0, :west
unit :wizard, 406, 0, :west
unit :archer, 409, 0, :west
unit :wizard, 414, 0, :west
unit :wizard, 426, 0, :west
unit :wizard, 430, 0, :west
unit :captive, 434, 0, :west
unit :wizard, 439, 0, :west
unit :wizard, 442, 0, :west
unit :wizard, 444, 0, :west
unit :archer, 448, 0, :west
unit :wizard, 451, 0, :west
unit :thick_sludge, 452, 0, :west
unit :sludge, 474, 0, :west
unit :archer, 478, 0, :west
unit :archer, 484, 0, :west
unit :captive, 487, 0, :west
unit :captive, 488, 0, :west
unit :thick_sludge, 499, 0, :west
unit :thick_sludge, 503, 0, :west
unit :captive, 504, 0, :west
unit :archer, 505, 0, :west
unit :archer, 507, 0, :west
unit :thick_sludge, 513, 0, :west
unit :archer, 521, 0, :west
unit :wizard, 522, 0, :west
unit :sludge, 525, 0, :west
unit :archer, 529, 0, :west
unit :thick_sludge, 532, 0, :west
unit :archer, 535, 0, :west
unit :archer, 543, 0, :west
unit :captive, 548, 0, :west
unit :sludge, 553, 0, :west
unit :archer, 555, 0, :west
unit :captive, 556, 0, :west
unit :wizard, 561, 0, :west
unit :archer, 565, 0, :west
unit :captive, 567, 0, :west
unit :archer, 570, 0, :west
unit :archer, 572, 0, :west
unit :thick_sludge, 585, 0, :west
unit :thick_sludge, 589, 0, :west
unit :wizard, 596, 0, :west
unit :archer, 600, 0, :west
unit :archer, 601, 0, :west
unit :archer, 609, 0, :west
unit :wizard, 614, 0, :west
unit :sludge, 616, 0, :west
