#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |  w       w a      S  S  S  C a s        C  w  S  >w   a  a a       s  a            C   w       S  aaa   s   Sw    a     C      S         a  a s   S       w     C S  S                   Cs aC     Saa s    SCS   C   a    s   SsC S      Csas   w            Sa              s            w s       SC   a  S   C   S     @           CaC w S s          s        a w   C  Ss  S s CswC  s  w     ss  sa         a         a s       C           C a    C   aSs   sa   Sa C         a S   w            S   w S    SC  w  s  aSw         s    a         Ca   s  Ca  s  CSa  s     C  w      CCa wS a         C  C  a  s S        w w       C           C SwSs  w s a   a|
#  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 649
ace_score 3245
size 649, 1
stairs 50, 0

warrior 316, 0, :east

unit :wizard, 2, 0, :east
unit :wizard, 10, 0, :east
unit :archer, 12, 0, :east
unit :thick_sludge, 19, 0, :east
unit :thick_sludge, 22, 0, :east
unit :thick_sludge, 25, 0, :east
unit :captive, 28, 0, :east
unit :archer, 30, 0, :east
unit :sludge, 32, 0, :east
unit :captive, 41, 0, :east
unit :wizard, 44, 0, :east
unit :thick_sludge, 47, 0, :east
unit :wizard, 51, 0, :east
unit :archer, 55, 0, :east
unit :archer, 58, 0, :east
unit :archer, 60, 0, :east
unit :sludge, 68, 0, :east
unit :archer, 71, 0, :east
unit :captive, 84, 0, :east
unit :wizard, 88, 0, :east
unit :thick_sludge, 96, 0, :east
unit :archer, 99, 0, :east
unit :archer, 100, 0, :east
unit :archer, 101, 0, :east
unit :sludge, 105, 0, :east
unit :thick_sludge, 109, 0, :east
unit :wizard, 110, 0, :east
unit :archer, 115, 0, :east
unit :captive, 121, 0, :east
unit :thick_sludge, 128, 0, :east
unit :archer, 138, 0, :east
unit :archer, 141, 0, :east
unit :sludge, 143, 0, :east
unit :thick_sludge, 147, 0, :east
unit :wizard, 155, 0, :east
unit :captive, 161, 0, :east
unit :thick_sludge, 163, 0, :east
unit :thick_sludge, 166, 0, :east
unit :captive, 186, 0, :east
unit :sludge, 187, 0, :east
unit :archer, 189, 0, :east
unit :captive, 190, 0, :east
unit :thick_sludge, 196, 0, :east
unit :archer, 197, 0, :east
unit :archer, 198, 0, :east
unit :sludge, 200, 0, :east
unit :thick_sludge, 205, 0, :east
unit :captive, 206, 0, :east
unit :thick_sludge, 207, 0, :east
unit :captive, 211, 0, :east
unit :archer, 215, 0, :east
unit :sludge, 220, 0, :east
unit :thick_sludge, 224, 0, :east
unit :sludge, 225, 0, :east
unit :captive, 226, 0, :east
unit :thick_sludge, 228, 0, :east
unit :captive, 235, 0, :east
unit :sludge, 236, 0, :east
unit :archer, 237, 0, :east
unit :sludge, 238, 0, :east
unit :wizard, 242, 0, :east
unit :thick_sludge, 255, 0, :east
unit :archer, 256, 0, :east
unit :sludge, 271, 0, :east
unit :wizard, 284, 0, :east
unit :sludge, 286, 0, :east
unit :thick_sludge, 294, 0, :east
unit :captive, 295, 0, :east
unit :archer, 299, 0, :east
unit :thick_sludge, 302, 0, :east
unit :captive, 306, 0, :east
unit :thick_sludge, 310, 0, :east
unit :captive, 328, 0, :west
unit :archer, 329, 0, :west
unit :captive, 330, 0, :west
unit :wizard, 332, 0, :west
unit :thick_sludge, 334, 0, :west
unit :sludge, 336, 0, :west
unit :sludge, 347, 0, :west
unit :archer, 356, 0, :west
unit :wizard, 358, 0, :west
unit :captive, 362, 0, :west
unit :thick_sludge, 365, 0, :west
unit :sludge, 366, 0, :west
unit :thick_sludge, 369, 0, :west
unit :sludge, 371, 0, :west
unit :captive, 373, 0, :west
unit :sludge, 374, 0, :west
unit :wizard, 375, 0, :west
unit :captive, 376, 0, :west
unit :sludge, 379, 0, :west
unit :wizard, 382, 0, :west
unit :sludge, 388, 0, :west
unit :sludge, 389, 0, :west
unit :sludge, 392, 0, :west
unit :archer, 393, 0, :west
unit :archer, 403, 0, :west
unit :archer, 413, 0, :west
unit :sludge, 415, 0, :west
unit :captive, 423, 0, :west
unit :captive, 435, 0, :west
unit :archer, 437, 0, :west
unit :captive, 442, 0, :west
unit :archer, 446, 0, :west
unit :thick_sludge, 447, 0, :west
unit :sludge, 448, 0, :west
unit :sludge, 452, 0, :west
unit :archer, 453, 0, :west
unit :thick_sludge, 457, 0, :west
unit :archer, 458, 0, :west
unit :captive, 460, 0, :west
unit :archer, 470, 0, :west
unit :thick_sludge, 472, 0, :west
unit :wizard, 476, 0, :west
unit :thick_sludge, 489, 0, :west
unit :wizard, 493, 0, :west
unit :thick_sludge, 495, 0, :west
unit :thick_sludge, 500, 0, :west
unit :captive, 501, 0, :west
unit :wizard, 504, 0, :west
unit :sludge, 507, 0, :west
unit :archer, 510, 0, :west
unit :thick_sludge, 511, 0, :west
unit :wizard, 512, 0, :west
unit :sludge, 522, 0, :west
unit :archer, 527, 0, :west
unit :captive, 537, 0, :west
unit :archer, 538, 0, :west
unit :sludge, 542, 0, :west
unit :captive, 545, 0, :west
unit :archer, 546, 0, :west
unit :sludge, 549, 0, :west
unit :captive, 552, 0, :west
unit :thick_sludge, 553, 0, :west
unit :archer, 554, 0, :west
unit :sludge, 557, 0, :west
unit :captive, 563, 0, :west
unit :wizard, 566, 0, :west
unit :captive, 573, 0, :west
unit :captive, 574, 0, :west
unit :archer, 575, 0, :west
unit :wizard, 577, 0, :west
unit :thick_sludge, 578, 0, :west
unit :archer, 580, 0, :west
unit :captive, 590, 0, :west
unit :captive, 593, 0, :west
unit :archer, 596, 0, :west
unit :sludge, 599, 0, :west
unit :thick_sludge, 601, 0, :west
unit :wizard, 610, 0, :west
unit :wizard, 612, 0, :west
unit :captive, 620, 0, :west
unit :captive, 632, 0, :west
unit :thick_sludge, 634, 0, :west
unit :wizard, 635, 0, :west
unit :thick_sludge, 636, 0, :west
unit :sludge, 637, 0, :west
unit :wizard, 640, 0, :west
unit :sludge, 642, 0, :west
unit :archer, 644, 0, :west
unit :archer, 648, 0, :west
