#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# |      ss        @  C    w  SS    s   s      ss       s  C  Ss C   s           a      w    aa     S   C     ss  w     s     w     s     S S        SS C w sC        a a  C  w  a   S      Cas         S               sSC       S  S   Ca          s      w C C   a                w          w   SC      C  S aw     s  a     S    CC   a w sS      S    a     Sw      S  S wC   a  aC  S  wS sC    aCC     Ss     C s     w  w >      a    S  w      a Ca    w     S aC  w    w   w aa             a s      s s  a aa       a  C    Ca    C         CwS w Ss S         w   S a  S  s       S   s   S  w   w a    w   a         s   aC    C ssC s  a  S    Sw     S    S   S    S  a w     Sw       asC       S    C   C s        Ss  a a     |
#  ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

description "This level was randomly generated."
tip "No tip for you."
clue"No hint for you."

time_bonus 718
ace_score 3590
size 718, 1
stairs 416, 0

warrior 16, 0, :east

unit :sludge, 6, 0, :east
unit :sludge, 7, 0, :east
unit :captive, 19, 0, :west
unit :wizard, 24, 0, :west
unit :thick_sludge, 27, 0, :west
unit :thick_sludge, 28, 0, :west
unit :sludge, 33, 0, :west
unit :sludge, 37, 0, :west
unit :sludge, 44, 0, :west
unit :sludge, 45, 0, :west
unit :sludge, 53, 0, :west
unit :captive, 56, 0, :west
unit :thick_sludge, 59, 0, :west
unit :sludge, 60, 0, :west
unit :captive, 62, 0, :west
unit :sludge, 66, 0, :west
unit :archer, 78, 0, :west
unit :wizard, 85, 0, :west
unit :archer, 90, 0, :west
unit :archer, 91, 0, :west
unit :thick_sludge, 97, 0, :west
unit :captive, 101, 0, :west
unit :sludge, 107, 0, :west
unit :sludge, 108, 0, :west
unit :wizard, 111, 0, :west
unit :sludge, 117, 0, :west
unit :wizard, 123, 0, :west
unit :sludge, 129, 0, :west
unit :thick_sludge, 135, 0, :west
unit :thick_sludge, 137, 0, :west
unit :thick_sludge, 146, 0, :west
unit :thick_sludge, 147, 0, :west
unit :captive, 149, 0, :west
unit :wizard, 151, 0, :west
unit :sludge, 153, 0, :west
unit :captive, 154, 0, :west
unit :archer, 163, 0, :west
unit :archer, 165, 0, :west
unit :captive, 168, 0, :west
unit :wizard, 171, 0, :west
unit :archer, 174, 0, :west
unit :thick_sludge, 178, 0, :west
unit :captive, 185, 0, :west
unit :archer, 186, 0, :west
unit :sludge, 187, 0, :west
unit :thick_sludge, 197, 0, :west
unit :sludge, 213, 0, :west
unit :thick_sludge, 214, 0, :west
unit :captive, 215, 0, :west
unit :thick_sludge, 223, 0, :west
unit :thick_sludge, 226, 0, :west
unit :captive, 230, 0, :west
unit :archer, 231, 0, :west
unit :sludge, 242, 0, :west
unit :wizard, 249, 0, :west
unit :captive, 251, 0, :west
unit :captive, 253, 0, :west
unit :archer, 257, 0, :west
unit :wizard, 274, 0, :west
unit :wizard, 285, 0, :west
unit :thick_sludge, 289, 0, :west
unit :captive, 290, 0, :west
unit :captive, 297, 0, :west
unit :thick_sludge, 300, 0, :west
unit :archer, 302, 0, :west
unit :wizard, 303, 0, :west
unit :sludge, 309, 0, :west
unit :archer, 312, 0, :west
unit :thick_sludge, 318, 0, :west
unit :captive, 323, 0, :west
unit :captive, 324, 0, :west
unit :archer, 328, 0, :west
unit :wizard, 330, 0, :west
unit :sludge, 332, 0, :west
unit :thick_sludge, 333, 0, :west
unit :thick_sludge, 340, 0, :west
unit :archer, 345, 0, :west
unit :thick_sludge, 351, 0, :west
unit :wizard, 352, 0, :west
unit :thick_sludge, 359, 0, :west
unit :thick_sludge, 362, 0, :west
unit :wizard, 364, 0, :west
unit :captive, 365, 0, :west
unit :archer, 369, 0, :west
unit :archer, 372, 0, :west
unit :captive, 373, 0, :west
unit :thick_sludge, 376, 0, :west
unit :wizard, 379, 0, :west
unit :thick_sludge, 380, 0, :west
unit :sludge, 382, 0, :west
unit :captive, 383, 0, :west
unit :archer, 388, 0, :west
unit :captive, 389, 0, :west
unit :captive, 390, 0, :west
unit :thick_sludge, 396, 0, :west
unit :sludge, 397, 0, :west
unit :captive, 403, 0, :west
unit :sludge, 405, 0, :west
unit :wizard, 411, 0, :west
unit :wizard, 414, 0, :west
unit :archer, 423, 0, :west
unit :thick_sludge, 428, 0, :west
unit :wizard, 431, 0, :west
unit :archer, 438, 0, :west
unit :captive, 440, 0, :west
unit :archer, 441, 0, :west
unit :wizard, 446, 0, :west
unit :thick_sludge, 452, 0, :west
unit :archer, 454, 0, :west
unit :captive, 455, 0, :west
unit :wizard, 458, 0, :west
unit :wizard, 463, 0, :west
unit :wizard, 467, 0, :west
unit :archer, 469, 0, :west
unit :archer, 470, 0, :west
unit :archer, 484, 0, :west
unit :sludge, 486, 0, :west
unit :sludge, 493, 0, :west
unit :sludge, 495, 0, :west
unit :archer, 498, 0, :west
unit :archer, 500, 0, :west
unit :archer, 501, 0, :west
unit :archer, 509, 0, :west
unit :captive, 512, 0, :west
unit :captive, 517, 0, :west
unit :archer, 518, 0, :west
unit :captive, 523, 0, :west
unit :captive, 533, 0, :west
unit :wizard, 534, 0, :west
unit :thick_sludge, 535, 0, :west
unit :wizard, 537, 0, :west
unit :thick_sludge, 539, 0, :west
unit :sludge, 540, 0, :west
unit :thick_sludge, 542, 0, :west
unit :wizard, 552, 0, :west
unit :thick_sludge, 556, 0, :west
unit :archer, 558, 0, :west
unit :thick_sludge, 561, 0, :west
unit :sludge, 564, 0, :west
unit :thick_sludge, 572, 0, :west
unit :sludge, 576, 0, :west
unit :thick_sludge, 580, 0, :west
unit :wizard, 583, 0, :west
unit :wizard, 587, 0, :west
unit :archer, 589, 0, :west
unit :wizard, 594, 0, :west
unit :archer, 598, 0, :west
unit :sludge, 608, 0, :west
unit :archer, 612, 0, :west
unit :captive, 613, 0, :west
unit :captive, 618, 0, :west
unit :sludge, 620, 0, :west
unit :sludge, 621, 0, :west
unit :captive, 622, 0, :west
unit :sludge, 624, 0, :west
unit :archer, 627, 0, :west
unit :thick_sludge, 630, 0, :west
unit :thick_sludge, 635, 0, :west
unit :wizard, 636, 0, :west
unit :thick_sludge, 642, 0, :west
unit :thick_sludge, 647, 0, :west
unit :thick_sludge, 651, 0, :west
unit :thick_sludge, 656, 0, :west
unit :archer, 659, 0, :west
unit :wizard, 661, 0, :west
unit :thick_sludge, 667, 0, :west
unit :wizard, 668, 0, :west
unit :archer, 676, 0, :west
unit :sludge, 677, 0, :west
unit :captive, 678, 0, :west
unit :thick_sludge, 686, 0, :west
unit :captive, 691, 0, :west
unit :captive, 695, 0, :west
unit :sludge, 697, 0, :west
unit :thick_sludge, 706, 0, :west
unit :sludge, 707, 0, :west
unit :archer, 710, 0, :west
unit :archer, 712, 0, :west
